import Mathlib.GroupTheory.Frattini
import Mathlib.GroupTheory.Commutator.Basic
import Mathlib.Algebra.Module.ZMod
import Mathlib.LinearAlgebra.Dimension.Finrank

/-!
# Frattini and mod-`p` Frattini bookkeeping

Mathlib already defines the (ordinary) Frattini subgroup.  This file adds the
standard algebraic subgroup `G^p [G,G]` used for degree-one mod-`p` control, with
basic quotient-vanishing lemmas.  The comparison with the ordinary Frattini subgroup
for finite `p`-groups is a later theorem, not assumed here.
-/

open scoped commutatorElement

namespace Submission

variable (p : ℕ) (G : Type*) [Group G]

/-- Re-export/name for mathlib's Frattini subgroup in the Submission namespace. -/
abbrev fSubgro : Subgroup G := _root_.frattini G

/-- The normal subgroup generated by all `p`th powers. -/
def pPowerSubgroup : Subgroup G :=
  Subgroup.normalClosure (Set.range fun g : G => g ^ p)

instance p_subgroup_normal : (pPowerSubgroup p G).Normal :=
  Subgroup.normalClosure_normal

/-- The mod-`p` Frattini subgroup `G^p [G,G]`. -/
def modPFrattini : Subgroup G :=
  pPowerSubgroup p G ⊔ _root_.commutator G

instance mod_frattini_normal : (modPFrattini p G).Normal :=
  Subgroup.sup_normal (pPowerSubgroup p G) (_root_.commutator G)

/-- Every `p`th power lies in the `p`-power subgroup. -/
theorem p_power_subgroup (g : G) : g ^ p ∈ pPowerSubgroup p G := by
  apply Subgroup.subset_normalClosure
  exact Set.mem_range_self g

/-- Every `p`th power lies in `G^p [G,G]`. -/
theorem pow_mod_frattini (g : G) : g ^ p ∈ modPFrattini p G := by
  exact (le_sup_left : pPowerSubgroup p G ≤ modPFrattini p G)
    (p_power_subgroup p G g)

/-- Every commutator lies in `G^p [G,G]`. -/
theorem commutator_mod_frattini (g h : G) : ⁅g, h⁆ ∈ modPFrattini p G := by
  have hc : ⁅g, h⁆ ∈ _root_.commutator G := by
    rw [_root_.commutator_def]
    exact Subgroup.commutator_mem_commutator (by trivial) (by trivial)
  exact (le_sup_right : _root_.commutator G ≤ modPFrattini p G) hc

/-- The mod-`p` Frattini quotient. -/
abbrev mFQuot : Type _ := G ⧸ modPFrattini p G

/-- The quotient map to the mod-`p` Frattini quotient. -/
def mFQuot.mk : G →* mFQuot p G :=
  QuotientGroup.mk' (modPFrattini p G)

@[simp] theorem mFQuot.mk_pow_eqone (g : G) :
    (mFQuot.mk p G g) ^ p = 1 := by
  rw [← map_pow]
  exact (QuotientGroup.eq_one_iff (N := modPFrattini p G) (g ^ p)).2
    (pow_mod_frattini p G g)

@[simp] theorem mFQuot.mk_comm_eqone (g h : G) :
    mFQuot.mk p G ⁅g, h⁆ = 1 := by
  exact (QuotientGroup.eq_one_iff (N := modPFrattini p G) ⁅g, h⁆).2
    (commutator_mod_frattini p G g h)

/-- The ordinary Frattini subgroup is normal (indeed characteristic in mathlib). -/
instance frattiniSubgroup_normal : (fSubgro G).Normal := by
  infer_instance

end Submission

namespace Submission

open scoped commutatorElement

variable (p : ℕ) (G : Type*) [Group G]

/-- The mod-`p` Frattini quotient is abelian (stated as a commutativity theorem to
avoid installing a competing typeclass instance). -/
theorem mod_mul_comm (a b : mFQuot p G) :
    a * b = b * a := by
  refine QuotientGroup.induction_on a ?_
  intro g
  refine QuotientGroup.induction_on b ?_
  intro h
  change ((g : mFQuot p G) * (h : mFQuot p G) =
    (h : mFQuot p G) * (g : mFQuot p G))
  rw [← commutatorElement_eq_one_iff_mul_comm]
  have hm := mFQuot.mk_comm_eqone p G g h
  simpa [mFQuot.mk, map_commutatorElement] using hm

/-- Every element of the mod-`p` Frattini quotient has exponent dividing `p`. -/
@[simp] theorem mod_frattini_one (x : mFQuot p G) :
    x ^ p = 1 := by
  refine QuotientGroup.induction_on x ?_
  intro g
  exact mFQuot.mk_pow_eqone p G g

end Submission

/-! ## Additive `ZMod p`-module packaging of the quotient

The quotient `G / (G^p [G,G])` is abelian of exponent dividing `p`.  We install the
canonical commutative-group instance and expose its additive avatar as a `ZMod p`-module.
For prime `p`, this is the usual elementary-abelian/vector-space object.
-/

namespace Submission

variable (p : ℕ) (G : Type*) [Group G]

/-- The mod-`p` Frattini quotient is canonically a commutative group. -/
instance mFQuot.commGroup : CommGroup (mFQuot p G) :=
  { (inferInstance : Group (mFQuot p G)) with
    mul_comm := mod_mul_comm p G }

/-- Additive avatar of the mod-`p` Frattini quotient.  This is the object that will
carry the degree-one `ZMod p`-linear structure. -/
abbrev mFAdditi : Type _ := Additive (mFQuot p G)

/-- The additive quotient has characteristic dividing `p`. -/
@[simp] theorem mod_additive_nsmul (x : mFAdditi p G) :
    p • x = 0 := by
  induction x using Additive.rec with
  | ofMul q =>
    change Additive.ofMul ((q : mFQuot p G) ^ p) = 0
    simp [mod_frattini_one]

/-- The canonical `ZMod p`-module structure on the additive mod-`p` Frattini quotient. -/
noncomputable instance mFAdditi.moduleZMod :
    Module (ZMod p) (mFAdditi p G) :=
  AddCommGroup.zmodModule (n := p) (mod_additive_nsmul p G)


/-- Natural scalars on the additive quotient are represented by powers in the
multiplicative quotient. -/
@[simp] theorem smul_frattini_additive (n : ℕ)
    (q : mFQuot p G) :
    (n : ZMod p) • (Additive.ofMul q : mFAdditi p G) =
      Additive.ofMul (q ^ n) := by
  rw [Nat.cast_smul_eq_nsmul]
  rfl

/-! ## Generator rank -/

/-- The mod-`p` generator rank `d_p(G)`: the rank of the additive mod-`p`
Frattini quotient `G / (G^p [G,G])`.

For prime `p`, this is the usual `𝔽_p`-dimension of the Frattini quotient. It is
cardinal-valued so it remains honest for infinite-dimensional quotients. -/
noncomputable def generatorRank : Cardinal :=
  Module.rank (ZMod p) (mFAdditi p G)

/-- Nat-valued form of `generatorRank`, intended for finite-dimensional finite
`p`-group/GS statements. Outside the finite-dimensional setting this inherits
Mathlib's `Module.finrank` convention for infinite rank. -/
noncomputable def generatorRankNat : ℕ :=
  Cardinal.toNat (generatorRank p G)

@[simp] theorem generator_rank_finrank :
    generatorRankNat p G = Module.finrank (ZMod p) (mFAdditi p G) := rfl

end Submission
