import Towers.NumberTheory.Galois.DedekindTheorem
import Mathlib.RingTheory.Polynomial.Resultant.Basic

/-!
# Class Field Theory, Theorem 0.10 (Dedekind)

Dedekind's theorem relates three descriptions of a good prime for a monogenic
integral closure: the prime avoids the polynomial discriminant, the reduction
of the minimal polynomial has distinct irreducible factors, and the extended
prime is unramified.  The Kummer--Dedekind correspondence then identifies the
prime ideals above it with the ideals generated by the prime and lifted
polynomial factors.

The fixed-prime theorem below uses only coprimality with the conductor of
`A[alpha]`, the conductor formulation of the local integral-closure condition
in Theorem 0.10.  A second theorem retains the earlier globally monogenic
form as a convenient corollary.  Both package the factorization conclusions
using Mathlib's normalized-factor API.
-/

namespace Towers.CField.Examples

open Algebra Ideal Polynomial UniqueFactorizationMonoid
open Towers.NumberTheory.Milne

noncomputable section

attribute [local instance] Ideal.Quotient.field

/-- The polynomial discriminant commutes with a coefficient map to a field for
monic polynomials. -/
private theorem discr_monic
    {R k : Type*} [CommRing R] [Field k]
    (phi : R →+* k) (f : R[X]) (hf : f.Monic) :
    (f.map phi).discr = phi f.discr := by
  by_cases h0 : f.natDegree = 0
  · obtain rfl := Polynomial.eq_one_of_monic_natDegree_zero hf h0
    calc
      (Polynomial.map phi (1 : R[X])).discr = (Polynomial.C (1 : k)).discr := by simp
      _ = 1 := Polynomial.discr_C 1
      _ = phi 1 := (map_one phi).symm
      _ = phi (Polynomial.C (1 : R)).discr := by rw [Polynomial.discr_C]
      _ = phi (1 : R[X]).discr := by simp
  let g : k[X] := f.map phi
  have hg_monic : g.Monic := hf.map phi
  have hnatdeg_map : g.natDegree = f.natDegree := by
    simpa [g] using hf.natDegree_map phi
  have hdeg_pos : 0 < f.degree :=
    Polynomial.natDegree_pos_iff_degree_pos.mp (Nat.pos_of_ne_zero h0)
  have hgdeg_pos : 0 < g.degree := by
    apply Polynomial.natDegree_pos_iff_degree_pos.mp
    rw [hnatdeg_map]
    exact Nat.pos_of_ne_zero h0
  have hres_map :
      g.resultant g.derivative g.natDegree (g.natDegree - 1) =
        phi (f.resultant f.derivative f.natDegree (f.natDegree - 1)) := by
    rw [hnatdeg_map]
    dsimp [g]
    rw [Polynomial.derivative_map]
    exact Polynomial.resultant_map_map
      (f := f) (g := f.derivative) (m := f.natDegree) (n := f.natDegree - 1) (φ := phi)
  have h1 := Polynomial.resultant_deriv (f := g) hgdeg_pos
  rw [hg_monic.leadingCoeff] at h1
  have h2 := congrArg phi (Polynomial.resultant_deriv (f := f) hdeg_pos)
  rw [← hres_map, hf.leadingCoeff, ← hnatdeg_map] at h2
  simp only [map_mul, map_pow, map_neg, map_one] at h2
  have hs : ((-1 : k) ^ (g.natDegree * (g.natDegree - 1) / 2)) ≠ 0 :=
    pow_ne_zero _ (neg_ne_zero.mpr one_ne_zero)
  exact mul_left_cancel₀ hs (by
    rw [h1] at h2
    simpa [mul_assoc] using h2)

/-- Avoiding the discriminant makes the reduction of a monic polynomial
squarefree.  This is condition (a) implying condition (c) in Theorem 0.10. -/
private theorem squarefree_discr_not
    {A : Type*} [CommRing A] {p : Ideal A} [p.IsMaximal]
    (f : A[X]) (hf : f.Monic) (hdisc : f.discr ∉ p) :
    Squarefree (f.map (Ideal.Quotient.mk p)) := by
  let phi : A →+* A ⧸ p := Ideal.Quotient.mk p
  let g : (A ⧸ p)[X] := f.map phi
  have hg_monic : g.Monic := hf.map phi
  have hg_ne_zero : g ≠ 0 := hg_monic.ne_zero
  have hdiscr_map : g.discr = phi f.discr := by
    simpa [g, phi] using discr_monic phi f hf
  have hdiscr_ne_zero : phi f.discr ≠ 0 := by
    intro hzero
    apply hdisc
    exact Ideal.Quotient.eq_zero_iff_mem.mp hzero
  by_cases h0 : f.natDegree = 0
  · obtain rfl := Polynomial.eq_one_of_monic_natDegree_zero hf h0
    simp
  have hnatdeg_map : g.natDegree = f.natDegree := by
    simpa [g, phi] using hf.natDegree_map phi
  have hgdeg_pos : 0 < g.degree := by
    apply Polynomial.natDegree_pos_iff_degree_pos.mp
    rw [hnatdeg_map]
    exact Nat.pos_of_ne_zero h0
  have hres_big_ne_zero :
      g.resultant g.derivative g.natDegree (g.natDegree - 1) ≠ 0 := by
    rw [Polynomial.resultant_deriv (f := g) hgdeg_pos, hg_monic.leadingCoeff,
      hdiscr_map]
    have hs : ((-1 : A ⧸ p) ^ (g.natDegree * (g.natDegree - 1) / 2)) ≠ 0 :=
      pow_ne_zero _ (neg_ne_zero.mpr one_ne_zero)
    simpa using mul_ne_zero (mul_ne_zero hs one_ne_zero) hdiscr_ne_zero
  have hres_ne_zero : g.resultant g.derivative ≠ 0 := by
    have hdeg_deriv_le : g.derivative.natDegree ≤ g.natDegree - 1 := by
      simpa using Polynomial.natDegree_derivative_le (p := g)
    have hrel :=
      Polynomial.resultant_add_right_deg
        (f := g) (g := g.derivative) (m := g.natDegree) (n := g.derivative.natDegree)
        (k := (g.natDegree - 1) - g.derivative.natDegree) le_rfl
    have hrel' :
        g.resultant g.derivative g.natDegree (g.natDegree - 1) =
          g.resultant g.derivative := by
      simpa [Nat.add_sub_of_le hdeg_deriv_le, hg_monic.coeff_natDegree] using hrel
    exact hrel' ▸ hres_big_ne_zero
  apply Polynomial.Separable.squarefree
  exact not_not.mp fun hnot ↦ hres_ne_zero <|
    Polynomial.resultant_eq_zero_iff.mpr ⟨Or.inl hg_ne_zero, hnot⟩

variable {A B : Type*} [CommRing A] [CommRing B] [Algebra A B]
  [IsDomain A] [IsIntegrallyClosed A] [IsDedekindDomain B]
  [Module.IsTorsionFree A B]

open Classical in
/-- The fixed-prime form of the factorization conclusion of Theorem 0.10.

Only coprimality of the prime with the conductor of A[alpha] in B is used;
this is the conductor formulation of the local integral-closure condition
in part (b) of the source.  Thus global monogenicity is not needed for the
Kummer--Dedekind factorization at this prime. -/
theorem dedekind_coprime_conductor
    {alpha : B} {p : Ideal A} [p.IsMaximal] (hp0 : p ≠ ⊥)
    (hcoprime :
      (conductor A alpha).comap (algebraMap A B) ⊔ p = ⊤)
    (halpha_int : IsIntegral A alpha)
    (hdisc : (minpoly A alpha).discr ∉ p) :
    Squarefree ((minpoly A alpha).map (Ideal.Quotient.mk p)) ∧
      Multiset.Nodup (normalizedFactors (p.map (algebraMap A B))) ∧
      (∀ P ∈ normalizedFactors (p.map (algebraMap A B)),
        Ideal.ramificationIdx p P = 1) ∧
      normalizedFactors (p.map (algebraMap A B)) =
        Multiset.map
          (fun g ↦
            ((GKDedeki.factor_coprime_conductor
              hp0 hcoprime halpha_int).symm g : Ideal B))
          (normalizedFactors
            ((minpoly A alpha).map (Ideal.Quotient.mk p))).attach := by
  let fbar := (minpoly A alpha).map (Ideal.Quotient.mk p)
  have hfbar_sqfree : Squarefree fbar :=
    squarefree_discr_not
      (minpoly A alpha) (minpoly.monic halpha_int) hdisc
  have hfbar_ne : fbar ≠ 0 :=
    Polynomial.map_monic_ne_zero (minpoly.monic halpha_int)
  have hfbar_nodup : Multiset.Nodup (normalizedFactors fbar) :=
    (UniqueFactorizationMonoid.squarefree_iff_nodup_normalizedFactors
      hfbar_ne).mp hfbar_sqfree
  have hfactor :=
    GKDedeki.minpol_copri_condu
      hp0 hcoprime halpha_int
  have hprime_nodup :
      Multiset.Nodup (normalizedFactors (p.map (algebraMap A B))) := by
    rw [hfactor]
    apply hfbar_nodup.attach.map
    intro g h hgh
    apply
      (GKDedeki.factor_coprime_conductor
        hp0 hcoprime halpha_int).symm.injective
    exact Subtype.ext hgh
  refine ⟨hfbar_sqfree, hprime_nodup, ?_, hfactor⟩
  intro P hP
  have hPprime : P.IsPrime :=
    Ideal.isPrime_of_prime (irreducible_of_normalized_factor P hP).prime
  have hP0 : P ≠ ⊥ := by
    simpa [Ideal.zero_eq_bot] using
      (irreducible_of_normalized_factor P hP).ne_zero
  rw [IsDedekindDomain.ramificationIdx_eq_normalizedFactors_count
    (map_ne_bot_of_ne_bot hp0) hPprime hP0]
  exact Multiset.count_eq_one_of_mem hprime_nodup hP

open Classical in
/-- The explicit prime ideal in the fixed-prime conductor form of Theorem
0.10: a lifted factor G gives the ideal generated by p and G(alpha). -/
theorem dedekind_10_conductor
    {alpha : B} {p : Ideal A} [p.IsMaximal] (hp0 : p ≠ ⊥)
    (hcoprime :
      (conductor A alpha).comap (algebraMap A B) ⊔ p = ⊤)
    (halpha_int : IsIntegral A alpha) {G : A[X]}
    (hG : G.map (Ideal.Quotient.mk p) ∈
      normalizedFactors ((minpoly A alpha).map (Ideal.Quotient.mk p))) :
    ((GKDedeki.factor_coprime_conductor
      hp0 hcoprime halpha_int).symm
        ⟨G.map (Ideal.Quotient.mk p), hG⟩ : Ideal B) =
      Ideal.span (p.map (algebraMap A B) ∪ {G.aeval alpha}) := by
  exact
    GKDedeki.pair_coprime_conductor
      hp0 hcoprime halpha_int hG

open Classical in
/-- CFT Theorem 0.10, in the globally monogenic case provided by the current
Kummer--Dedekind API.

If `p` does not contain the discriminant of the minimal polynomial, its
reduction has distinct normalized irreducible factors.  The corresponding
prime factors of `p B` are also distinct (hence all have ramification index
one), and they are exactly the explicit ideals `(p, G(alpha))` supplied by the
Kummer--Dedekind correspondence. -/
theorem dedekind_factorization_monogenic
    {alpha : B} {p : Ideal A} [p.IsMaximal] (hp0 : p ≠ ⊥)
    (halpha : Algebra.adjoin A {alpha} = ⊤)
    (halpha_int : IsIntegral A alpha)
    (hdisc : (minpoly A alpha).discr ∉ p) :
    Squarefree ((minpoly A alpha).map (Ideal.Quotient.mk p)) ∧
      Multiset.Nodup (normalizedFactors (p.map (algebraMap A B))) ∧
      (∀ P ∈ normalizedFactors (p.map (algebraMap A B)),
        Ideal.ramificationIdx p P = 1) ∧
      normalizedFactors (p.map (algebraMap A B)) =
        Multiset.map
          (fun g ↦
            ((KummerDedekind.normalizedFactorsMapEquivNormalizedFactorsMinPolyMk
              inferInstance hp0 (by
                rw [conductor_eq_top_iff_adjoin_eq_top.mpr halpha,
                  Ideal.comap_top, top_sup_eq]) halpha_int).symm g : Ideal B))
          (normalizedFactors
            ((minpoly A alpha).map (Ideal.Quotient.mk p))).attach := by
  let fbar := (minpoly A alpha).map (Ideal.Quotient.mk p)
  have hfbar_sqfree : Squarefree fbar :=
    squarefree_discr_not
      (minpoly A alpha) (minpoly.monic halpha_int) hdisc
  have hfbar_ne : fbar ≠ 0 :=
    Polynomial.map_monic_ne_zero (minpoly.monic halpha_int)
  have hfbar_nodup : Multiset.Nodup (normalizedFactors fbar) :=
    (UniqueFactorizationMonoid.squarefree_iff_nodup_normalizedFactors hfbar_ne).mp hfbar_sqfree
  have hfactor :=
    Towers.NumberTheory.Milne.dedekind_factorization_theorem
      hp0 halpha halpha_int
  have hprime_nodup : Multiset.Nodup (normalizedFactors (p.map (algebraMap A B))) := by
    rw [hfactor]
    apply hfbar_nodup.attach.map
    intro g h hgh
    apply
      (KummerDedekind.normalizedFactorsMapEquivNormalizedFactorsMinPolyMk
        inferInstance hp0 (by
          rw [conductor_eq_top_iff_adjoin_eq_top.mpr halpha,
            Ideal.comap_top, top_sup_eq]) halpha_int).symm.injective
    exact Subtype.ext hgh
  refine ⟨hfbar_sqfree, hprime_nodup, ?_, hfactor⟩
  intro P hP
  have hPprime : P.IsPrime :=
    Ideal.isPrime_of_prime (irreducible_of_normalized_factor P hP).prime
  have hP0 : P ≠ ⊥ := by
    simpa [Ideal.zero_eq_bot] using (irreducible_of_normalized_factor P hP).ne_zero
  rw [IsDedekindDomain.ramificationIdx_eq_normalizedFactors_count
    (map_ne_bot_of_ne_bot hp0) hPprime hP0]
  exact Multiset.count_eq_one_of_mem hprime_nodup hP

open Classical in
/-- The explicit ideal in the factorization of Theorem 0.10: a lifted
irreducible factor `G` of the reduced minimal polynomial gives the prime ideal
`(p, G(alpha))`. -/
theorem dedekind_0_10
    {alpha : B} {p : Ideal A} [p.IsMaximal] (hp0 : p ≠ ⊥)
    (halpha : Algebra.adjoin A {alpha} = ⊤)
    (halpha_int : IsIntegral A alpha) {G : A[X]}
    (hG : G.map (Ideal.Quotient.mk p) ∈
      normalizedFactors ((minpoly A alpha).map (Ideal.Quotient.mk p))) :
    ((KummerDedekind.normalizedFactorsMapEquivNormalizedFactorsMinPolyMk
      inferInstance hp0 (by
        rw [conductor_eq_top_iff_adjoin_eq_top.mpr halpha,
          Ideal.comap_top, top_sup_eq]) halpha_int).symm
        ⟨G.map (Ideal.Quotient.mk p), hG⟩ : Ideal B) =
      Ideal.span (p.map (algebraMap A B) ∪ {G.aeval alpha}) := by
  exact
    GKDedeki.pair_adjoin_top
      hp0 halpha halpha_int hG

end

end Towers.CField.Examples
