import Mathlib.NumberTheory.NumberField.ClassNumber

/-!
# The narrow ideal class group

The narrow class group of a number field is the group of invertible fractional ideals modulo
principal ideals admitting a totally positive generator.  Here total positivity is expressed
directly in terms of all real embeddings `K →+∗ ℝ`.
-/

namespace Submission.NumberTheory.Milne

open scoped NumberField nonZeroDivisors

variable (K : Type*) [Field K] [NumberField K]

/-- An element of a number field is totally positive if every real embedding sends it to a
strictly positive real number. -/
def ITPos (x : K) : Prop :=
  ∀ φ : K →+* ℝ, 0 < φ x

namespace ITPos

omit [NumberField K] in
@[simp]
theorem one : ITPos K 1 := by
  intro φ
  simp

omit [NumberField K] in
theorem mul {x y : K} (hx : ITPos K x) (hy : ITPos K y) :
    ITPos K (x * y) := by
  intro φ
  simpa using mul_pos (hx φ) (hy φ)

omit [NumberField K] in
theorem inv {x : K} (hx : ITPos K x) :
    ITPos K x⁻¹ := by
  intro φ
  simpa using inv_pos.mpr (hx φ)

end ITPos

/-- The subgroup of nonzero totally positive elements of `K`. -/
def TotallyPositiveUnits : Subgroup Kˣ where
  carrier := {x | ITPos K (x : K)}
  one_mem' := ITPos.one K
  mul_mem' hx hy := ITPos.mul K hx hy
  inv_mem' hx := by
    simpa using ITPos.inv K hx

omit [NumberField K] in
@[simp]
theorem totally_positive_units (x : Kˣ) :
    x ∈ TotallyPositiveUnits K ↔ ∀ φ : K →+* ℝ, 0 < φ (x : K) :=
  Iff.rfl

/-- The homomorphism taking a totally positive nonzero element to its principal fractional
ideal. -/
noncomputable def narrowPrincipalIdeal :
    TotallyPositiveUnits K →* (FractionalIdeal (𝓞 K)⁰ K)ˣ :=
  (toPrincipalIdeal (𝓞 K) K).comp (TotallyPositiveUnits K).subtype

/-- The subgroup of invertible fractional ideals generated by totally positive elements. -/
noncomputable def NarrowPrincipalIdeals :
    Subgroup (FractionalIdeal (𝓞 K)⁰ K)ˣ :=
  (narrowPrincipalIdeal K).range

theorem narrow_principal (I : (FractionalIdeal (𝓞 K)⁰ K)ˣ) :
    I ∈ NarrowPrincipalIdeals K ↔
      ∃ x : Kˣ, ITPos K (x : K) ∧ toPrincipalIdeal (𝓞 K) K x = I := by
  constructor
  · rintro ⟨x, rfl⟩
    exact ⟨x, x.2, rfl⟩
  · rintro ⟨x, hx, rfl⟩
    exact ⟨⟨x, hx⟩, rfl⟩

instance narrow_ideals_normal : (NarrowPrincipalIdeals K).Normal :=
  Subgroup.normal_of_isMulCommutative _

/-- The narrow ideal class group of a number field. -/
noncomputable def NCGroup :=
  (FractionalIdeal (𝓞 K)⁰ K)ˣ ⧸ NarrowPrincipalIdeals K

noncomputable instance : CommGroup (NCGroup K) :=
  QuotientGroup.Quotient.commGroup (NarrowPrincipalIdeals K)

noncomputable instance : Inhabited (NCGroup K) :=
  ⟨1⟩

/-- Send an invertible fractional ideal to its narrow ideal class. -/
noncomputable def NCGroup.mk :
    (FractionalIdeal (𝓞 K)⁰ K)ˣ →* NCGroup K :=
  QuotientGroup.mk' (NarrowPrincipalIdeals K)

@[simp]
theorem NCGroup.mk_one_iff (I : (FractionalIdeal (𝓞 K)⁰ K)ˣ) :
    NCGroup.mk K I = 1 ↔
      ∃ x : Kˣ, ITPos K (x : K) ∧ toPrincipalIdeal (𝓞 K) K x = I := by
  change
    (I : (FractionalIdeal (𝓞 K)⁰ K)ˣ ⧸ NarrowPrincipalIdeals K) = 1 ↔ _
  rw [QuotientGroup.eq_one_iff]
  exact narrow_principal K I

/-- Every narrow-principal fractional ideal is principal. -/
theorem narrow_ideals :
    NarrowPrincipalIdeals K ≤ (toPrincipalIdeal (𝓞 K) K).range := by
  intro I hI
  obtain ⟨x, _, rfl⟩ := (narrow_principal K I).mp hI
  exact ⟨x, rfl⟩

/-- The quotient map from narrow ideal classes to fractional ideals modulo all principal
ideals, before identifying the latter quotient with Mathlib's `ClassGroup`. -/
noncomputable def narrowPrincipalQuotient :
    NCGroup K →*
      (FractionalIdeal (𝓞 K)⁰ K)ˣ ⧸ (toPrincipalIdeal (𝓞 K) K).range :=
  QuotientGroup.map (NarrowPrincipalIdeals K) (toPrincipalIdeal (𝓞 K) K).range
    (MonoidHom.id _) (by
      simpa using narrow_ideals K)

/-- The canonical surjection from the narrow ideal class group to the ordinary ideal class
group. -/
noncomputable def narrowClassGroup :
    NCGroup K →* ClassGroup (𝓞 K) :=
  (ClassGroup.equiv K).symm.toMonoidHom.comp
    (narrowPrincipalQuotient K)

@[simp]
theorem narrow_class_mk
    (I : (FractionalIdeal (𝓞 K)⁰ K)ˣ) :
    narrowClassGroup K (NCGroup.mk K I) = ClassGroup.mk K I := by
  apply (ClassGroup.equiv K).injective
  rw [narrowClassGroup, MonoidHom.comp_apply]
  change
    (ClassGroup.equiv K) ((ClassGroup.equiv K).symm
      (narrowPrincipalQuotient K (NCGroup.mk K I))) = _
  rw [MulEquiv.apply_symm_apply, narrowPrincipalQuotient, NCGroup.mk]
  change
    (I : (FractionalIdeal (𝓞 K)⁰ K)ˣ ⧸ (toPrincipalIdeal (𝓞 K) K).range) =
      (ClassGroup.equiv K) (ClassGroup.mk K I)
  rw [ClassGroup.equiv_mk]
  congr 1
  simp [← Units.val_inj]

/-- The canonical map from the narrow class group onto the ordinary class group is
surjective. -/
theorem narrow_class_surjective :
    Function.Surjective (narrowClassGroup K) := by
  intro C
  exact ClassGroup.induction K
    (fun I ↦ ⟨NCGroup.mk K I, narrow_class_mk K I⟩) C

/-- A represented narrow class maps to the identity in the ordinary class group exactly
when its fractional-ideal representative is principal. -/
theorem narrow_mk_one
    (I : (FractionalIdeal (𝓞 K)⁰ K)ˣ) :
    narrowClassGroup K (NCGroup.mk K I) = 1 ↔
      I ∈ (toPrincipalIdeal (𝓞 K) K).range := by
  rw [narrow_class_mk]
  constructor
  · intro h
    have h' := congrArg (ClassGroup.equiv K) h
    simpa using h'
  · intro h
    apply (ClassGroup.equiv K).injective
    simpa using h

/-- Kernel criterion for the canonical map: it consists of narrow classes represented by
ordinary principal fractional ideals. -/
theorem ker_narrow_group (C : NCGroup K) :
    C ∈ (narrowClassGroup K).ker ↔
      ∃ I : (FractionalIdeal (𝓞 K)⁰ K)ˣ,
        C = NCGroup.mk K I ∧ I ∈ (toPrincipalIdeal (𝓞 K) K).range := by
  constructor
  · intro hC
    obtain ⟨I, rfl⟩ := QuotientGroup.mk_surjective C
    refine ⟨I, rfl, ?_⟩
    exact (narrow_mk_one K I).mp hC
  · rintro ⟨I, rfl, hI⟩
    exact (narrow_mk_one K I).mpr hI

omit [NumberField K] in
/-- If `K` has no real embeddings, every nonzero element is totally positive. -/
theorem totally_positive_top [IsEmpty (K →+* ℝ)] :
    TotallyPositiveUnits K = ⊤ := by
  ext x
  constructor
  · intro _
    trivial
  · intro _ φ
    exact isEmptyElim φ

/-- If `K` has no real embeddings, narrow-principal ideals are precisely the principal ideals. -/
theorem narrow_principal_ideals [IsEmpty (K →+* ℝ)] :
    NarrowPrincipalIdeals K = (toPrincipalIdeal (𝓞 K) K).range := by
  ext I
  rw [narrow_principal]
  constructor
  · rintro ⟨x, _, rfl⟩
    exact ⟨x, rfl⟩
  · rintro ⟨x, rfl⟩
    exact ⟨x, fun φ ↦ isEmptyElim φ, rfl⟩

/-- For a number field without real embeddings, the narrow and ordinary ideal class groups
are canonically isomorphic. -/
noncomputable def narrowClassEquiv [IsEmpty (K →+* ℝ)] :
    NCGroup K ≃* ClassGroup (𝓞 K) :=
  (QuotientGroup.congr (NarrowPrincipalIdeals K) (toPrincipalIdeal (𝓞 K) K).range
      (MulEquiv.refl _) (by
        simpa using narrow_principal_ideals K)).trans
    (ClassGroup.equiv K).symm

end Submission.NumberTheory.Milne
