import Towers.ClassField.CyclotomicBrauer.Cyclotomic
import Towers.ClassField.CyclotomicBrauer.RationalPrimesBelow
import Towers.ClassField.CyclotomicBrauer.TotallyComplex

/-!
# Lemma VII.7.3: the two-primary global field

The full Galois group of a `2`-power cyclotomic field is not cyclic.  Its
quotient by the order-two subgroup generated by `-1` is cyclic, however.
The corresponding fixed field supplies the cyclic extension of degree
`2 ^ a` needed for the two-primary block of Lemma VII.7.3.
-/

namespace Towers.CField.CBrauer

open IntermediateField
open Towers.NumberTheory.Milne

noncomputable section

universe u

/-- The full two-primary fixed-field witness, retaining the ambient
cyclotomic field and its relative degree two over the cyclic fixed field. -/
def TwoOverfieldWitness (a : ℕ) : Prop :=
  ∃ C : Type, ∃ fieldC : Field C,
  letI : Field C := fieldC
  ∃ numberFieldC : NumberField C,
  letI : NumberField C := numberFieldC
  ∃ cyclotomicC : IsCyclotomicExtension {2 ^ (a + 2)} ℚ C,
  letI : IsCyclotomicExtension {2 ^ (a + 2)} ℚ C := cyclotomicC
  ∃ E : IntermediateField ℚ C,
  ∃ numberFieldE : NumberField E,
  letI : NumberField E := numberFieldE
  ∃ galoisE : IsGalois ℚ E,
  letI : IsGalois ℚ E := galoisE
  ∃ _cyclicE : IsCyclic Gal(E/ℚ),
  ∃ _galoisEC : IsGalois E C,
    Module.finrank ℚ E = 2 ^ a ∧
      Module.finrank E C = 2

/-- The complex two-primary variant.  It uses the diagonal order-two
subgroup rather than `<-1>`, retaining the same degree and relative-degree
formulas while making the fixed field totally complex. -/
def ComplexOverfieldWitness (a : ℕ) : Prop :=
  ∃ C : Type, ∃ fieldC : Field C,
  letI : Field C := fieldC
  ∃ numberFieldC : NumberField C,
  letI : NumberField C := numberFieldC
  ∃ cyclotomicC : IsCyclotomicExtension {2 ^ (a + 2)} ℚ C,
  letI : IsCyclotomicExtension {2 ^ (a + 2)} ℚ C := cyclotomicC
  ∃ E : IntermediateField ℚ C,
  ∃ numberFieldE : NumberField E,
  letI : NumberField E := numberFieldE
  ∃ galoisE : IsGalois ℚ E,
  letI : IsGalois ℚ E := galoisE
  ∃ _cyclicE : IsCyclic Gal(E/ℚ),
  ∃ _galoisEC : IsGalois E C,
  ∃ _totallyComplexE : NumberField.IsTotallyComplex E,
    Module.finrank ℚ E = 2 ^ a ∧
      Module.finrank E C = 2

/-- Passing from the full `2`-power cyclotomic field to the fixed field of
its order-two subgroup loses at most one factor of `2` from a local degree.
Thus divisibility by `2 ^ (a + 1)` upstairs implies divisibility by `2 ^ a`
in the fixed field. -/
theorem dvd_fixed_degree
    (a fullDegree relativeDegree fixedDegree : ℕ)
    (htower : fullDegree = relativeDegree * fixedDegree)
    (hrelative : relativeDegree ∣ 2)
    (hfull : 2 ^ (a + 1) ∣ fullDegree) :
    2 ^ a ∣ fixedDegree := by
  rcases (Nat.dvd_prime Nat.prime_two).mp hrelative with hrelative | hrelative
  · subst relativeDegree
    have hpow : 2 ^ a ∣ 2 ^ (a + 1) := pow_dvd_pow 2 (by omega)
    have hfixed : 2 ^ a ∣ fullDegree := hpow.trans hfull
    rwa [htower, one_mul] at hfixed
  · subst relativeDegree
    obtain ⟨c, hc⟩ := hfull
    have hcancel : 2 * fixedDegree = 2 * (2 ^ a * c) := by
      calc
        2 * fixedDegree = fullDegree := htower.symm
        _ = 2 ^ (a + 1) * c := hc
        _ = 2 * (2 ^ a * c) := by rw [pow_succ]; ring
    have hfixed : fixedDegree = 2 ^ a * c :=
      Nat.eq_of_mul_eq_mul_left (by norm_num) hcancel
    exact ⟨c, hfixed⟩

/-- For every exponent `a`, there is a cyclic cyclotomic extension of `ℚ`
of degree exactly `2 ^ a`, obtained as the fixed field of the order-two
factor in `ℚ(ζ_(2 ^ (a + 2)))`. -/
theorem two_overfield_witness
    (a : ℕ) : TwoOverfieldWitness a := by
  let n := 2 ^ (a + 2)
  letI : NeZero n := ⟨pow_ne_zero (a + 2) (by norm_num)⟩
  let C := CyclotomicField n ℚ
  letI : Field C := inferInstance
  letI : NumberField C := inferInstance
  letI : Algebra ℚ C := inferInstance
  letI : IsCyclotomicExtension {n} ℚ C :=
    CyclotomicField.isCyclotomicExtension n ℚ
  letI : FiniteDimensional ℚ C := inferInstance
  letI : IsGalois ℚ C := cyclotomic_isGalois (n := n)
  letI : Finite Gal(C/ℚ) := inferInstance
  let U := (ZMod n)ˣ
  let e : Gal(C/ℚ) ≃* U :=
    IsCyclotomicExtension.Rat.galEquivZMod n C
  letI : CommGroup Gal(C/ℚ) :=
    e.toMonoidHom.commGroupOfInjective e.injective
  let HU : Subgroup U := Subgroup.zpowers (-1 : U)
  let HG : Subgroup Gal(C/ℚ) := HU.comap e.toMonoidHom
  letI : HG.Normal := by infer_instance
  have hn_eq : n = 2 ^ (a + 2) := rfl
  have hr : 2 ≤ a + 2 := by omega
  have hUQuotCyclic : IsCyclic (U ⧸ HU) := by
    simpa only [U, HU, n] using
      (exercise_six_cyclic
        (r := a + 2) hr)
  letI : IsCyclic (U ⧸ HU) := hUQuotCyclic
  let phi : Gal(C/ℚ) →* U ⧸ HU :=
    (QuotientGroup.mk' HU).comp e.toMonoidHom
  have hphiSurj : Function.Surjective phi :=
    (QuotientGroup.mk'_surjective HU).comp e.surjective
  have hphiKer : phi.ker = HG := by
    ext sigma
    change (QuotientGroup.mk' HU) (e sigma) = 1 ↔ e sigma ∈ HU
    exact QuotientGroup.eq_one_iff (e sigma)
  let eQuot : Gal(C/ℚ) ⧸ HG ≃* U ⧸ HU :=
    (QuotientGroup.quotientMulEquivOfEq hphiKer.symm).trans
      (QuotientGroup.quotientKerEquivOfSurjective phi hphiSurj)
  letI : IsCyclic (Gal(C/ℚ) ⧸ HG) :=
    eQuot.isCyclic.mpr inferInstance
  have hcardC : Nat.card Gal(C/ℚ) = 2 ^ (a + 1) := by
    rw [IsGalois.card_aut_eq_finrank]
    have hdegree := rational_cyclotomic_finrank
      (p := 2) (r := a + 2) Nat.prime_two (by omega) C
    simpa only [n, Nat.reduceSubDiff, Nat.mul_one] using hdegree
  have hmapHG : HG.map e.toMonoidHom = HU := by
    exact Subgroup.map_comap_eq_self_of_surjective e.surjective HU
  have hcardHU : Nat.card HU = 2 := by
    have horderNeg : orderOf (-1 : U) = 2 := by
      letI : Fact (1 < n) :=
        ⟨one_lt_pow' (by norm_num) (by omega)⟩
      have hn4 : 4 ≤ n := by
        change 2 ^ 2 ≤ 2 ^ (a + 2)
        exact pow_le_pow_right' (by norm_num) (by omega)
      have hn2 : n ≠ 2 := by omega
      rw [← orderOf_units, Units.coe_neg_one, orderOf_neg_one,
        ringChar.eq (ZMod n) n, if_neg hn2]
    change Nat.card (Subgroup.zpowers (-1 : U)) = 2
    rw [Nat.card_zpowers, horderNeg]
  have hcardHG : Nat.card HG = 2 := by
    calc
      Nat.card HG = Nat.card (HG.map e.toMonoidHom) :=
        Nat.card_congr
          (HG.equivMapOfInjective e.toMonoidHom e.injective).toEquiv
      _ = Nat.card HU := by rw [hmapHG]
      _ = 2 := hcardHU
  have hindexHG : HG.index = 2 ^ a := by
    have hmul := HG.card_mul_index
    rw [hcardHG, hcardC] at hmul
    have hpow : 2 ^ (a + 1) = 2 * 2 ^ a := by
      rw [pow_succ]
      ring
    rw [hpow] at hmul
    omega
  let E : IntermediateField ℚ C := IntermediateField.fixedField HG
  letI : IsGalois ℚ E := by
    dsimp only [E]
    exact IsGalois.of_fixedField_normal_subgroup HG
  letI : NumberField E := NumberField.of_module_finite ℚ E
  letI : IsCyclic Gal(E/ℚ) := by
    exact (IsGalois.normalAutEquivQuotient HG).isCyclic.mp inferInstance
  have hEdegree : Module.finrank ℚ E = 2 ^ a := by
    rw [IntermediateField.finrank_eq_fixingSubgroup_index (L := E),
      IntermediateField.fixingSubgroup_fixedField, hindexHG]
  have hrelative : Module.finrank E C = 2 := by
    change Module.finrank (IntermediateField.fixedField HG) C = 2
    rw [IntermediateField.finrank_fixedField_eq_card HG, hcardHG]
  refine ⟨C, inferInstance, inferInstance, inferInstance, E, inferInstance,
    inferInstance, inferInstance, inferInstance, hEdegree, hrelative⟩

set_option synthInstance.maxHeartbeats 200000 in
-- The two transported quotient groups and fixed-field towers require a larger search budget.
set_option maxHeartbeats 2000000 in
/-- For every positive exponent, the diagonal order-two subgroup produces
a totally complex cyclic cyclotomic field of degree `2 ^ a`. -/
theorem complex_overfield_witness
    (a : ℕ) (ha : 0 < a) :
    ComplexOverfieldWitness a := by
  let n := 2 ^ (a + 2)
  letI : NeZero n := ⟨pow_ne_zero (a + 2) (by norm_num)⟩
  let C := CyclotomicField n ℚ
  letI : Field C := inferInstance
  letI : NumberField C := inferInstance
  letI : Algebra ℚ C := inferInstance
  letI : IsCyclotomicExtension {n} ℚ C :=
    CyclotomicField.isCyclotomicExtension n ℚ
  letI : FiniteDimensional ℚ C := inferInstance
  letI : IsGalois ℚ C := cyclotomic_isGalois (n := n)
  letI : Finite Gal(C/ℚ) := inferInstance
  let U := (ZMod n)ˣ
  let e : Gal(C/ℚ) ≃* U :=
    IsCyclotomicExtension.Rat.galEquivZMod n C
  letI : CommGroup Gal(C/ℚ) :=
    e.toMonoidHom.commGroupOfInjective e.injective
  let HU : Subgroup U :=
    exercise_six_subgroup (a + 2)
  letI : HU.Normal := by infer_instance
  let HG : Subgroup Gal(C/ℚ) := HU.comap e.toMonoidHom
  letI : HG.Normal := by infer_instance
  have hdiag := exercise_six_spec
    (r := a + 2) (by omega)
  have hUQuotCyclic : IsCyclic (U ⧸ HU) := by
    simpa only [U, HU, n] using hdiag.2.2
  letI : IsCyclic (U ⧸ HU) := hUQuotCyclic
  let phi : Gal(C/ℚ) →* U ⧸ HU :=
    (QuotientGroup.mk' HU).comp e.toMonoidHom
  have hphiSurj : Function.Surjective phi :=
    (QuotientGroup.mk'_surjective HU).comp e.surjective
  have hphiKer : phi.ker = HG := by
    ext sigma
    change (QuotientGroup.mk' HU) (e sigma) = 1 ↔ e sigma ∈ HU
    exact QuotientGroup.eq_one_iff (e sigma)
  let eQuot : Gal(C/ℚ) ⧸ HG ≃* U ⧸ HU :=
    (QuotientGroup.quotientMulEquivOfEq hphiKer.symm).trans
      (QuotientGroup.quotientKerEquivOfSurjective phi hphiSurj)
  letI : IsCyclic (Gal(C/ℚ) ⧸ HG) :=
    eQuot.isCyclic.mpr inferInstance
  have hcardC : Nat.card Gal(C/ℚ) = 2 ^ (a + 1) := by
    rw [IsGalois.card_aut_eq_finrank]
    have hdegree := rational_cyclotomic_finrank
      (p := 2) (r := a + 2) Nat.prime_two (by omega) C
    simpa only [n, Nat.reduceSubDiff, Nat.mul_one] using hdegree
  have hmapHG : HG.map e.toMonoidHom = HU :=
    Subgroup.map_comap_eq_self_of_surjective e.surjective HU
  have hcardHU : Nat.card HU = 2 := by
    simpa only [HU, U, n] using hdiag.1
  have hcardHG : Nat.card HG = 2 := by
    calc
      Nat.card HG = Nat.card (HG.map e.toMonoidHom) :=
        Nat.card_congr
          (HG.equivMapOfInjective e.toMonoidHom e.injective).toEquiv
      _ = Nat.card HU := by rw [hmapHG]
      _ = 2 := hcardHU
  have hindexHG : HG.index = 2 ^ a := by
    have hmul := HG.card_mul_index
    rw [hcardHG, hcardC] at hmul
    have hpow : 2 ^ (a + 1) = 2 * 2 ^ a := by
      rw [pow_succ]
      ring
    rw [hpow] at hmul
    omega
  let E : IntermediateField ℚ C := IntermediateField.fixedField HG
  letI : IsGalois ℚ E :=
    IsGalois.of_fixedField_normal_subgroup HG
  letI : NumberField E := NumberField.of_module_finite ℚ E
  letI : IsCyclic Gal(E/ℚ) :=
    (IsGalois.normalAutEquivQuotient HG).isCyclic.mp inferInstance
  have hnegMap : (-1 : U) ∉ HG.map e.toMonoidHom := by
    rw [hmapHG]
    simpa only [HU, U, n] using hdiag.2.1
  letI : NumberField.IsTotallyComplex E := by
    exact totally_complex_not
      n C HG hnegMap
  have hEdegree : Module.finrank ℚ E = 2 ^ a := by
    rw [IntermediateField.finrank_eq_fixingSubgroup_index (L := E),
      IntermediateField.fixingSubgroup_fixedField, hindexHG]
  have hrelative : Module.finrank E C = 2 := by
    change Module.finrank (IntermediateField.fixedField HG) C = 2
    rw [IntermediateField.finrank_fixedField_eq_card HG, hcardHG]
  refine ⟨C, inferInstance, inferInstance, inferInstance, E, inferInstance,
    inferInstance, inferInstance, inferInstance, inferInstance,
    hEdegree, hrelative⟩

/-- The stronger overfield witness packages to the original finite
two-primary extension output. -/
theorem two_extension_data
    (a : ℕ) :
    ∃ data : FEData ℚ,
      data.IsCyclicCyclotomic ∧
        letI : Field data.L := data.fieldL
        letI : Algebra ℚ data.L := data.algebraKL
        Module.finrank ℚ data.L = 2 ^ a := by
  rcases two_overfield_witness a with
    ⟨C, fieldC, numberFieldC, cyclotomicC, E, numberFieldE,
      galoisE, cyclicE, galoisEC, hEdegree, _hrelative⟩
  letI : Field C := fieldC
  letI : NumberField C := numberFieldC
  letI : IsCyclotomicExtension {2 ^ (a + 2)} ℚ C := cyclotomicC
  letI : NumberField E := numberFieldE
  letI : IsGalois ℚ E := galoisE
  letI : IsCyclic Gal(E/ℚ) := cyclicE
  letI : IsGalois E C := galoisEC
  let data : FEData ℚ :=
    { L := E
      fieldL := inferInstance
      numberFieldL := inferInstance
      algebraKL := E.algebra'
      finiteDimensionalKL := inferInstance
      isGaloisKL := galoisE }
  refine ⟨data, ?_, ?_⟩
  · change IsCyclic Gal(E/ℚ) ∧ _
    refine ⟨inferInstance, 2 ^ (a + 2), C, inferInstance, inferInstance,
      inferInstance, inferInstance, inferInstance, inferInstance, trivial⟩
  · exact hEdegree

/-- The complex diagonal witness packaged as finite extension data. -/
theorem complex_extension_data
    (a : ℕ) (ha : 0 < a) :
    ∃ data : FEData ℚ,
      data.IsCyclicCyclotomic ∧
        data.IsTotallyComplex ∧
        letI : Field data.L := data.fieldL
        letI : Algebra ℚ data.L := data.algebraKL
        Module.finrank ℚ data.L = 2 ^ a := by
  rcases complex_overfield_witness a ha with
    ⟨C, fieldC, numberFieldC, cyclotomicC, E, numberFieldE,
      galoisE, cyclicE, galoisEC, totallyComplexE,
      hEdegree, _hrelative⟩
  letI : Field C := fieldC
  letI : NumberField C := numberFieldC
  letI : IsCyclotomicExtension {2 ^ (a + 2)} ℚ C := cyclotomicC
  letI : NumberField E := numberFieldE
  letI : IsGalois ℚ E := galoisE
  letI : IsCyclic Gal(E/ℚ) := cyclicE
  letI : IsGalois E C := galoisEC
  letI : NumberField.IsTotallyComplex E := totallyComplexE
  let data : FEData ℚ :=
    { L := E
      fieldL := inferInstance
      numberFieldL := inferInstance
      algebraKL := E.algebra'
      finiteDimensionalKL := inferInstance
      isGaloisKL := galoisE }
  refine ⟨data, ?_, totallyComplexE, hEdegree⟩
  change IsCyclic Gal(E/ℚ) ∧ _
  refine ⟨inferInstance, 2 ^ (a + 2), C, inferInstance, inferInstance,
    inferInstance, inferInstance, inferInstance, inferInstance, trivial⟩

end

end Towers.CField.CBrauer
