import Towers.ClassField.KummerNormIndex.SecondInequalityPlaces
import Towers.ClassField.KummerNormIndex.PrincipalIdeleHom
import Towers.ClassField.KummerNormIndex.GeneratedPthRoots

/-!
# The Kummer extension generated by all `S`-units

For the set `S` chosen before Lemma VII.6.2, Milne considers the finite
subgroup `U(S) Kˣᵖ / Kˣᵖ` of the power-class group.  Its order is
`p ^ |S|`, and the corresponding Kummer field is the extension denoted by
`M = K[U(S)^(1/p)]` in the source.
-/

namespace Towers.CField.KNIndex

open IsDedekindDomain NumberField
open Towers.NumberTheory.Milne
open Towers.CField.Ideles
open Towers.CField.KTheory
open Towers.CField.NIndex

noncomputable section

universe u

private abbrev SU
    (K : Type u) [Field K] [NumberField K]
    (S : Finset (NumberFieldPlace K)) :=
  ArithmeticSUnits K (finitePrimePart K S)

/-- The map from `S`-units to global `p`-power classes. -/
noncomputable def sClassHom
    (K : Type u) [Field K] [NumberField K]
    (p : ℕ) (S : Finset (NumberFieldPlace K)) :
    SU K S →* PowerClassGroup K p :=
  (powerClass p).comp (Set.unit (finitePrimePart K S) K).subtype

@[simp]
theorem s_unit_hom
    (K : Type u) [Field K] [NumberField K]
    (p : ℕ) (S : Finset (NumberFieldPlace K)) (a : SU K S) :
    sClassHom K p S a = powerClass p (a : Kˣ) :=
  rfl

/-- A global `p`th root of an `S`-unit is again an `S`-unit.  Consequently
the kernel of the power-class map is exactly `U(S)^p`. -/
theorem s_unit_ker
    (K : Type u) [Field K] [NumberField K]
    (p : ℕ) (hp : p ≠ 0) (S : Finset (NumberFieldPlace K)) :
    (sClassHom K p S).ker = pthPowerSubgroup p (SU K S) := by
  ext a
  constructor
  · intro ha
    rw [MonoidHom.mem_ker] at ha
    change powerClass p (a : Kˣ) = 1 at ha
    have ha' : (a : Kˣ) ∈ (powMonoidHom p : Kˣ →* Kˣ).range :=
      (QuotientGroup.eq_one_iff (N :=
        (powMonoidHom p : Kˣ →* Kˣ).range) (a : Kˣ)).mp ha
    obtain ⟨y, hy⟩ := ha'
    let yS : SU K S := ⟨y, fun P hP ↦ by
      apply (pow_eq_one_iff_left hp).mp
      have hy' : (y : K) ^ p = ((a : Kˣ) : K) :=
        congrArg Units.val hy
      rw [← map_pow, hy', a.property P hP]⟩
    refine ⟨yS, ?_⟩
    apply Subtype.ext
    exact hy
  · rintro ⟨y, rfl⟩
    rw [MonoidHom.mem_ker]
    change powerClass p (((y ^ p : SU K S) : Kˣ)) = 1
    rw [show (((y ^ p : SU K S) : Kˣ)) = (y : Kˣ) ^ p from rfl,
      map_pow, power_class_pow]

/-- The `S`-unit power classes, before bundling their finiteness. -/
def sUnitCarrier
    (K : Type u) [Field K] [NumberField K]
    (p : ℕ) (S : Finset (NumberFieldPlace K)) :
    Subgroup (PowerClassGroup K p) :=
  (sClassHom K p S).range

private theorem s_class_carrier
    (K : Type u) [Field K] [NumberField K]
    (p : ℕ) (hp : p.Prime) (hroots : (primitiveRoots p K).Nonempty)
    (S : Finset (NumberFieldPlace K))
    (hInfinite : ContainsAllPlaces K S) :
    Set.Finite
      (sUnitCarrier K p S : Set (PowerClassGroup K p)) := by
  let f := sClassHom K p S
  have hindex : (pthPowerSubgroup p (SU K S)).index = p ^ S.card := by
    have h := sunit_index_combined
      p K hp hroots S ∅ hInfinite (by simp)
    have hcombined : combinedPlaces K S ∅ = S := by
      simp [combinedPlaces]
    change (pthPowerSubgroup p
      (ArithmeticSUnits K (finitePrimePart K
        (combinedPlaces K S ∅)))).index = _ at h
    rw [hcombined] at h
    change (pthPowerSubgroup p (SU K S)).index = p ^ S.card at h
    exact h
  have hkerIndex : f.ker.index ≠ 0 := by
    rw [s_unit_ker K p hp.ne_zero S, hindex]
    exact (pow_pos hp.pos S.card).ne'
  letI : Finite (SU K S ⧸ f.ker) :=
    (Subgroup.index_ne_zero_iff_finite.mp hkerIndex)
  letI : Finite f.range :=
    Finite.of_equiv (SU K S ⧸ f.ker)
      (QuotientGroup.quotientKerEquivRange f)
  change Set.Finite (f.range : Set (PowerClassGroup K p))
  exact Set.finite_coe_iff.mp (inferInstance : Finite f.range)

/-- The actual finite subgroup `U(S) Kˣᵖ / Kˣᵖ`. -/
noncomputable def sUnitSubgroup
    (K : Type u) [Field K] [NumberField K]
    (p : ℕ) (hp : p.Prime) (hroots : (primitiveRoots p K).Nonempty)
    (S : Finset (NumberFieldPlace K))
    (hInfinite : ContainsAllPlaces K S) :
    PCSubgro K p where
  carrier := sUnitCarrier K p S
  finite_carrier :=
    s_class_carrier K p hp hroots S hInfinite

@[simp]
theorem s_unit_carrier
    (K : Type u) [Field K] [NumberField K]
    (p : ℕ) (hp : p.Prime) (hroots : (primitiveRoots p K).Nonempty)
    (S : Finset (NumberFieldPlace K))
    (hInfinite : ContainsAllPlaces K S) :
    (sUnitSubgroup K p hp hroots S hInfinite).carrier =
      sUnitCarrier K p S :=
  rfl

/-- The source calculation
`|U(S) Kˣᵖ / Kˣᵖ| = p ^ |S|`. -/
theorem s_unit_card
    (K : Type u) [Field K] [NumberField K]
    (p : ℕ) (hp : p.Prime) (hroots : (primitiveRoots p K).Nonempty)
    (S : Finset (NumberFieldPlace K))
    (hInfinite : ContainsAllPlaces K S) :
    (sUnitSubgroup K p hp hroots S hInfinite).card =
      p ^ S.card := by
  let f := sClassHom K p S
  let B := sUnitSubgroup K p hp hroots S hInfinite
  have hindex : (pthPowerSubgroup p (SU K S)).index = p ^ S.card := by
    have h := sunit_index_combined
      p K hp hroots S ∅ hInfinite (by simp)
    have hcombined : combinedPlaces K S ∅ = S := by
      simp [combinedPlaces]
    change (pthPowerSubgroup p
      (ArithmeticSUnits K (finitePrimePart K
        (combinedPlaces K S ∅)))).index = _ at h
    rw [hcombined] at h
    change (pthPowerSubgroup p (SU K S)).index = p ^ S.card at h
    exact h
  calc
    B.card = Nat.card B.carrier :=
      PCSubgro.card_eq_card K B
    _ = Nat.card f.range := rfl
    _ = Nat.card (SU K S ⧸ f.ker) :=
      Nat.card_congr (QuotientGroup.quotientKerEquivRange f).symm.toEquiv
    _ = f.ker.index := (Subgroup.index_eq_card f.ker).symm
    _ = (pthPowerSubgroup p (SU K S)).index := by
      rw [s_unit_ker K p hp.ne_zero S]
    _ = p ^ S.card := hindex

section KummerField

variable (K Omega : Type u) [Field K] [NumberField K]
  [Field Omega] [Algebra K Omega] [IsAlgClosure K Omega]

/-- Milne's field `M = K[U(S)^(1/p)]`, constructed inside a fixed
algebraic closure. -/
abbrev sKummerField
    (p : ℕ) (hp : p.Prime) (hroots : (primitiveRoots p K).Nonempty)
    (S : Finset (NumberFieldPlace K))
    (hInfinite : ContainsAllPlaces K S) :=
  kummerField K Omega p hp.pos
    (sUnitSubgroup K p hp hroots S hInfinite)

/-- The Kummer field generated by the `S`-unit classes is finite over `K`. -/
@[implicit_reducible]
noncomputable def sKummerDimensional
    (p : ℕ) (hp : p.Prime) (hroots : (primitiveRoots p K).Nonempty)
    (S : Finset (NumberFieldPlace K))
    (hInfinite : ContainsAllPlaces K S) :
    FiniteDimensional K
      (sKummerField K Omega p hp hroots S hInfinite) :=
  dimensional_kummer_field K Omega p hp.pos
    (sUnitSubgroup K p hp hroots S hInfinite)

/-- As a finite extension of the number field `K`, the `S`-unit Kummer
field is again a number field. -/
@[implicit_reducible]
noncomputable def sKummerNumber
    (p : ℕ) (hp : p.Prime) (hroots : (primitiveRoots p K).Nonempty)
    (S : Finset (NumberFieldPlace K))
    (hInfinite : ContainsAllPlaces K S) :
    NumberField (sKummerField K Omega p hp hroots S hInfinite) := by
  letI : FiniteDimensional K
      (sKummerField K Omega p hp hroots S hInfinite) :=
    sKummerDimensional K Omega p hp hroots S hInfinite
  exact NumberField.of_module_finite K
    (sKummerField K Omega p hp hroots S hInfinite)

/-- The exact degree calculation `[M : K] = p ^ |S|`. -/
theorem finrank_s_kummer
    (p : ℕ) (hp : p.Prime) (hroots : (primitiveRoots p K).Nonempty)
    (S : Finset (NumberFieldPlace K))
    (hInfinite : ContainsAllPlaces K S) :
    Module.finrank K (sKummerField K Omega p hp hroots S hInfinite) =
      p ^ S.card := by
  rw [finrank_kummer_field p hp.pos hroots,
    s_unit_card K p hp hroots S hInfinite]

/-- The `S`-unit Kummer field is Galois over `K`. -/
@[implicit_reducible]
noncomputable def sKummerGalois
    (p : ℕ) (hp : p.Prime) (hroots : (primitiveRoots p K).Nonempty)
    (S : Finset (NumberFieldPlace K))
    (hInfinite : ContainsAllPlaces K S) :
    IsGalois K (sKummerField K Omega p hp hroots S hInfinite) := by
  let zeta : K := hroots.choose
  have hzeta : IsPrimitiveRoot zeta p :=
    (mem_primitiveRoots hp.pos).mp hroots.choose_spec
  exact kummer_galois K Omega p hp.pos hzeta
    (sUnitSubgroup K p hp hroots S hInfinite)

/-- The extension `M/K` is abelian, exactly as asserted in the Kummer
setup preceding Lemma VII.6.2. -/
@[implicit_reducible]
noncomputable def sAbelianGalois
    (p : ℕ) (hp : p.Prime) (hroots : (primitiveRoots p K).Nonempty)
    (S : Finset (NumberFieldPlace K))
    (hInfinite : ContainsAllPlaces K S) :
    IsAbelianGalois K
      (sKummerField K Omega p hp hroots S hInfinite) := by
  let zeta : K := hroots.choose
  have hzeta : IsPrimitiveRoot zeta p :=
    (mem_primitiveRoots hp.pos).mp hroots.choose_spec
  letI : IsGalois K
      (sKummerField K Omega p hp hroots S hInfinite) :=
    sKummerGalois K Omega p hp hroots S hInfinite
  letI : IsMulCommutative
      Gal(sKummerField K Omega p hp hroots S hInfinite/K) :=
    ⟨⟨fun sigma tau ↦ kummer_galois_commute
      K Omega p hp.pos hzeta
      (sUnitSubgroup K p hp hroots S hInfinite) sigma tau⟩⟩
  exact
    { toIsGalois := inferInstance
      toIsMulCommutative := inferInstance }

/-- Every automorphism of `M/K` has exponent dividing `p`. -/
theorem s_kummer_galois
    (p : ℕ) (hp : p.Prime) (hroots : (primitiveRoots p K).Nonempty)
    (S : Finset (NumberFieldPlace K))
    (hInfinite : ContainsAllPlaces K S)
    (sigma : Gal(sKummerField K Omega p hp hroots S hInfinite/K)) :
    sigma ^ p = 1 := by
  let zeta : K := hroots.choose
  have hzeta : IsPrimitiveRoot zeta p :=
    (mem_primitiveRoots hp.pos).mp hroots.choose_spec
  exact kummer_field_galois
    K Omega p hp.pos hzeta
      (sUnitSubgroup K p hp hroots S hInfinite) sigma

omit [NumberField K] in
private theorem power_representative_pow
    (p : ℕ) (a : Kˣ) :
    ∃ d : Kˣ, powerClassRepresentative K p (powerClass p a) * d ^ p = a := by
  have hclasses :
      powerClass p (powerClassRepresentative K p (powerClass p a)) =
        powerClass p a := by
    rw [power_class_representative]
  obtain ⟨z, hz, heq⟩ := (QuotientGroup.mk'_eq_mk' _).mp hclasses
  obtain ⟨d, rfl⟩ := hz
  exact ⟨d, heq⟩

/-- The base-field correction which changes the canonical root of the
chosen power-class representative into a root of the actual `S`-unit. -/
noncomputable def sKummerCorrection
    (p : ℕ) (S : Finset (NumberFieldPlace K)) (a : SU K S) : Kˣ :=
  Classical.choose
    (power_representative_pow K p (a : Kˣ))

theorem s_kummer_spec
    (p : ℕ) (S : Finset (NumberFieldPlace K)) (a : SU K S) :
    powerClassRepresentative K p (powerClass p (a : Kˣ)) *
        sKummerCorrection K p S a ^ p = (a : Kˣ) :=
  Classical.choose_spec
    (power_representative_pow K p (a : Kˣ))

/-- The power class of an `S`-unit as an element of the finite subgroup
used to define `M`. -/
noncomputable def sUnitClass
    (p : ℕ) (hp : p.Prime) (hroots : (primitiveRoots p K).Nonempty)
    (S : Finset (NumberFieldPlace K))
    (hInfinite : ContainsAllPlaces K S) (a : SU K S) :
    (sUnitSubgroup K p hp hroots S hInfinite).carrier :=
  ⟨powerClass p (a : Kˣ), ⟨a, rfl⟩⟩

/-- A concrete `p`th root in `M` of the actual `S`-unit `a`. -/
noncomputable def sKummerRoot
    (p : ℕ) (hp : p.Prime) (hroots : (primitiveRoots p K).Nonempty)
    (S : Finset (NumberFieldPlace K))
    (hInfinite : ContainsAllPlaces K S) (a : SU K S) :
    sKummerField K Omega p hp hroots S hInfinite :=
  let B := sUnitSubgroup K p hp hroots S hInfinite
  let b : B.carrier := sUnitClass K p hp hroots S hInfinite a
  let rb : kummerField K Omega p hp.pos B :=
    ⟨kummerRoot K Omega p hp.pos b.1,
      kummer_root_field K Omega p hp.pos B b⟩
  rb * algebraMap K (kummerField K Omega p hp.pos B)
    ((sKummerCorrection K p S a : Kˣ) : K)

/-- The chosen root really has `p`th power equal to the given `S`-unit,
not merely to an arbitrary representative of its global power class. -/
theorem s_kummer_pow
    (p : ℕ) (hp : p.Prime) (hroots : (primitiveRoots p K).Nonempty)
    (S : Finset (NumberFieldPlace K))
    (hInfinite : ContainsAllPlaces K S) (a : SU K S) :
    sKummerRoot K Omega p hp hroots S hInfinite a ^ p =
      algebraMap K (sKummerField K Omega p hp hroots S hInfinite)
        (((a : Kˣ) : K)) := by
  apply Subtype.ext
  change (kummerRoot K Omega p hp.pos (powerClass p (a : Kˣ)) *
      algebraMap K Omega ((sKummerCorrection K p S a : Kˣ) : K)) ^ p =
    algebraMap K Omega (((a : Kˣ) : K))
  rw [mul_pow, kummerRoot_pow, ← map_pow, ← map_mul]
  exact congrArg (algebraMap K Omega)
    (congrArg Units.val (s_kummer_spec K p S a))

/-- Every `S`-unit has a `p`th root in the constructed Kummer field. -/
theorem contains_pth_roots
    (p : ℕ) (hp : p.Prime) (hroots : (primitiveRoots p K).Nonempty)
    (S : Finset (NumberFieldPlace K))
    (hInfinite : ContainsAllPlaces K S) :
    ContainsPthRoots K
      (sKummerField K Omega p hp hroots S hInfinite) p S := by
  intro a
  exact ⟨sKummerRoot K Omega p hp hroots S hInfinite a,
    s_kummer_pow K Omega p hp hroots S hInfinite a⟩

/-- The corrected roots of the actual `S`-units still generate the whole
Kummer field.  Multiplying a canonical radical by an element of the base
field does not change the generated extension. -/
theorem generated_pth_roots
    (p : ℕ) (hp : p.Prime) (hroots : (primitiveRoots p K).Nonempty)
    (S : Finset (NumberFieldPlace K))
    (hInfinite : ContainsAllPlaces K S) :
    SPthRoots K
      (sKummerField K Omega p hp hroots S hInfinite) p S := by
  classical
  let B := sUnitSubgroup K p hp hroots S hInfinite
  let M := sKummerField K Omega p hp hroots S hInfinite
  let root : SU K S → M :=
    sKummerRoot K Omega p hp hroots S hInfinite
  refine ⟨root, ?_, ?_⟩
  · intro a
    exact s_kummer_pow K Omega p hp hroots S hInfinite a
  · apply top_unique
    rw [← adjoin_kummer_top K Omega p hp.pos B]
    rw [IntermediateField.adjoin_le_iff]
    rintro x ⟨b, rfl⟩
    obtain ⟨a, ha⟩ := b.2
    have hclass : powerClass p (a : Kˣ) = b.1 := ha
    let A : IntermediateField K M :=
      IntermediateField.adjoin K (Set.range root)
    let rb : M :=
      ⟨kummerRoot K Omega p hp.pos b.1,
        kummer_root_field K Omega p hp.pos B b⟩
    let dc : M := algebraMap K M
      ((sKummerCorrection K p S a : Kˣ) : K)
    have hroot : root a ∈ A :=
      IntermediateField.subset_adjoin K (Set.range root)
        (Set.mem_range_self a)
    have hdc : dc ∈ A := A.algebraMap_mem _
    have hdc0 : dc ≠ 0 := by
      exact (map_ne_zero (algebraMap K M)).2
        (sKummerCorrection K p S a).ne_zero
    have hrelation : root a = rb * dc := by
      apply Subtype.ext
      change kummerRoot K Omega p hp.pos (powerClass p (a : Kˣ)) *
          algebraMap K Omega
            ((sKummerCorrection K p S a : Kˣ) : K) =
        kummerRoot K Omega p hp.pos b.1 *
          algebraMap K Omega
            ((sKummerCorrection K p S a : Kˣ) : K)
      rw [hclass]
    have hrb : rb ∈ A := by
      have heq : rb = root a * dc⁻¹ := by
        calc
          rb = (rb * dc) * dc⁻¹ :=
            (mul_inv_cancel_right₀ hdc0 rb).symm
          _ = root a * dc⁻¹ := by rw [hrelation]
      rw [heq]
      exact A.mul_mem hroot (A.inv_mem hdc)
    exact hrb

end KummerField

end

end Towers.CField.KNIndex
