import Towers.ClassField.LocalExistence.IsDivisibleSubgroup

/-!
# Milne, Class Field Theory, Theorem III.5.1: final group argument

This file formalizes the last paragraph of Milne's proof of the local
existence theorem.  The local work supplies a candidate norm group `N` with
`N ∩ U_K ≤ I`.  Step 5 handles the subgroup generated by `U_K` and `N ∩ I`,
and the two standard closure properties of norm groups finish the proof.
-/

namespace Towers.CField.LExist

universe u

variable {Z : Type u} [CommGroup Z]

/-- **Theorem III.5.1, final abstract deduction.** Any family of finite-index
subgroups which is upward closed and cofiltered under intersections, and
which contains all finite-index subgroups above `U`, contains a target `I`
as soon as one family member `N` satisfies `N ∩ U ≤ I`. -/
theorem family_inf
    (P : Subgroup Z → Prop) (U I : Subgroup Z) [I.FiniteIndex]
    (hfinite : ∀ N, P N → N.FiniteIndex)
    (hupward : ∀ N J, P N → N ≤ J → J.FiniteIndex → P J)
    (hinter : ∀ N₁ N₂, P N₁ → P N₂ →
      ∃ M, P M ∧ M ≤ N₁ ⊓ N₂)
    (hcontainsU : ∀ J, J.FiniteIndex → U ≤ J → P J)
    (N : Subgroup Z) (hN : P N) (hNU : N ⊓ U ≤ I) :
    P I := by
  haveI : N.FiniteIndex := hfinite N hN
  let J : Subgroup Z := U ⊔ (N ⊓ I)
  have hJfinite : J.FiniteIndex := by
    dsimp [J]
    exact index_sup_inf U N I
  have hJ : P J := hcontainsU J hJfinite le_sup_left
  obtain ⟨M, hM, hMle⟩ := hinter N J hN hJ
  apply hupward M I hM _ (inferInstance : I.FiniteIndex)
  exact hMle.trans (by
    dsimp [J]
    exact inf_inf_le hNU)

end Towers.CField.LExist
