import Mathlib.GroupTheory.OrderOfElement

/-!
# Milne, Class Field Theory, Remark III.5.2

Milne isolates an abstract group-theoretic ingredient of the local existence
theorem.  A finite-index subgroup of an abelian group contains every power
whose exponent is its index.  Consequently, a divisible subgroup is contained
in every finite-index subgroup.

This file also records the corresponding statement for the intersection of a
family of candidate norm groups.  The later proof that the actual intersection
of local norm groups is divisible uses Proposition III.4.1 and compactness of
norm fibres, which require local reciprocity infrastructure not yet available
in Mathlib.
-/

namespace Towers.CField.LExist

universe u v

variable {Z : Type u} [CommGroup Z]

/-- A subgroup is divisible if each positive power map is surjective on it.
This elementwise formulation is convenient for Milne's argument. -/
def IDSubgro (D : Subgroup Z) : Prop :=
  ∀ n : ℕ, n ≠ 0 → ∀ d ∈ D, ∃ e ∈ D, e ^ n = d

/-- A finite-index subgroup of an abelian group contains the power of every
element by the subgroup index. -/
theorem pow_index_finite (I : Subgroup Z) [I.FiniteIndex] (z : Z) :
    z ^ I.index ∈ I :=
  I.pow_index_mem z

/-- Milne's key observation in Remark III.5.2: a divisible subgroup is
contained in every finite-index subgroup. -/
theorem IDSubgro.le_finiteIndex
    {D I : Subgroup Z} (hD : IDSubgro D) [I.FiniteIndex] :
    D ≤ I := by
  intro d hd
  obtain ⟨e, he, hpow⟩ :=
    hD I.index Subgroup.FiniteIndex.index_ne_zero d hd
  rw [← hpow]
  exact I.pow_index_mem e

variable {ι : Type v}

/-- The intersection of a family of candidate norm subgroups. -/
def familyCore (N : ι → Subgroup Z) : Subgroup Z :=
  ⨅ i, N i

/-- If a subgroup contains one member of the family, it contains the family
core. -/
theorem family_core
    (N : ι → Subgroup Z) (I : Subgroup Z)
    (hI : ∃ i, N i ≤ I) :
    familyCore N ≤ I := by
  obtain ⟨i, hi⟩ := hI
  exact (iInf_le N i).trans hi

/-- If the family core is divisible, then it lies in every finite-index
subgroup, independently of any cofinality property of the family. -/
theorem family_core_divisible
    (N : ι → Subgroup Z) (I : Subgroup Z) [I.FiniteIndex]
    (hdiv : IDSubgro (familyCore N)) :
    familyCore N ≤ I :=
  hdiv.le_finiteIndex

/-- Finite intersections preserve finite index, the other elementary fact
used repeatedly in the existence-theorem argument. -/
theorem finiteIndex_inf (H I : Subgroup Z) [H.FiniteIndex] [I.FiniteIndex] :
    (H ⊓ I).FiniteIndex :=
  inferInstance

/-- The subgroup generated by an arbitrary subgroup and a finite-index
subgroup again has finite index.  In an abelian group this is Milne's product
`U · (N ∩ I)`. -/
theorem index_sup_inf
    (U N I : Subgroup Z) [N.FiniteIndex] [I.FiniteIndex] :
    (U ⊔ (N ⊓ I)).FiniteIndex := by
  haveI : (N ⊓ I).FiniteIndex := inferInstance
  exact Subgroup.finiteIndex_of_le le_sup_right

/-- The elementary subgroup calculation at the end of Milne's proof of the
existence theorem. -/
theorem inf_inf_le
    {N U I : Subgroup Z} (hNU : N ⊓ U ≤ I) :
    N ⊓ (U ⊔ (N ⊓ I)) ≤ I := by
  rintro x ⟨hxN, hx⟩
  change x ∈ U ⊔ (N ⊓ I) at hx
  rw [Subgroup.mem_sup_of_normal_right] at hx
  obtain ⟨u, hu, y, hy, rfl⟩ := hx
  have huN : u ∈ N := by
    simpa only [mul_assoc, mul_inv_cancel, mul_one] using
      N.mul_mem hxN (N.inv_mem hy.1)
  exact I.mul_mem (hNU ⟨huN, hu⟩) hy.2

end Towers.CField.LExist
