import Towers.ClassField.LubinTate.IntertwinerConjugation
import Towers.ClassField.FormalGroups.AdicSubstitutionEvaluation
import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic

/-!
# Class Field Theory, Chapter I: independence of the uniformizer

Immediately after Proposition 3.10, Milne uses the conjugating series and
its inverse to identify the finite-level torsion sets, then compares the
fields generated by those sets.  This file isolates the set-theoretic and
field-generation parts of that argument.
-/

namespace Towers.CField.LTate

open Towers.CField.FGroups

noncomputable section

/-- The zero locus of an endomorphism. -/
def zeroLocus {alpha : Type*} [Zero alpha] (f : alpha → alpha) : Set alpha :=
  {x | f x = 0}

@[simp]
theorem mem_zeroLocus
    {alpha : Type*} [Zero alpha] (f : alpha → alpha) (x : alpha) :
    x ∈ zeroLocus f ↔ f x = 0 :=
  Iff.rfl

/-- An equivalence which fixes zero and intertwines two endomorphisms
restricts to an equivalence of their zero loci.  This is the abstract root
bijection used after Proposition 3.10. -/
def zeroLocusIntertwines
    {alpha : Type*} [Zero alpha] (f g : alpha → alpha)
    (e : alpha ≃ alpha) (hzero : e 0 = 0)
    (hintertwines : ∀ x, g (e x) = e (f x)) :
    zeroLocus f ≃ zeroLocus g where
  toFun x :=
    ⟨e x, by
      change g (e x) = 0
      rw [hintertwines, x.property, hzero]⟩
  invFun y :=
    ⟨e.symm y, by
      change f (e.symm y) = 0
      apply e.injective
      calc
        e (f (e.symm y)) = g (e (e.symm y)) :=
          (hintertwines (e.symm y)).symm
        _ = g y := by rw [e.apply_symm_apply]
        _ = 0 := y.property
        _ = e 0 := hzero.symm⟩
  left_inv x := Subtype.ext (e.symm_apply_apply x)
  right_inv y := Subtype.ext (e.apply_symm_apply y)

@[simp]
theorem zero_locus_intertwines
    {alpha : Type*} [Zero alpha] (f g : alpha → alpha)
    (e : alpha ≃ alpha) (hzero : e 0 = 0)
    (hintertwines : ∀ x, g (e x) = e (f x))
    (x : zeroLocus f) :
    (zeroLocusIntertwines f g e hzero hintertwines x : alpha) = e x :=
  rfl

variable {R : Type*} [CommRing R] [UniformSpace R] [IsUniformAddGroup R]
  [IsTopologicalRing R] [T2Space R] [CompleteSpace R]

/-- Evaluation of a zero-constant ordinary power series gives a self-map of
an ideal defining the complete adic topology. -/
noncomputable def seriesAdic
    {I : Ideal R} (hI : IsAdic I)
    (f : PowerSeries R) (hf0 : PowerSeries.constantCoeff f = 0) : I → I :=
  fun x =>
    ⟨PowerSeries.eval₂ (RingHom.id R) (x : R) f,
      constant_coeff_adic hI f x.2
        (by rw [hf0]; exact I.zero_mem)⟩

@[simp]
theorem coe_series_adic
    {I : Ideal R} (hI : IsAdic I)
    (f : PowerSeries R) (hf0 : PowerSeries.constantCoeff f = 0) (x : I) :
    (seriesAdic hI f hf0 x : R) =
      PowerSeries.eval₂ (RingHom.id R) (x : R) f :=
  rfl

/-- Convergent evaluation carries formal substitution to composition on the
adic ideal. -/
theorem series_adic_subst
    {I : Ideal R} (hI : IsAdic I)
    (f g : PowerSeries R)
    (hf0 : PowerSeries.constantCoeff f = 0)
    (hg0 : PowerSeries.constantCoeff g = 0) (x : I) :
    seriesAdic hI (PowerSeries.subst g f)
        (PowerSeries.constantCoeff_subst_eq_zero hg0 f hf0) x =
      seriesAdic hI f hf0 (seriesAdic hI g hg0 x) := by
  apply Subtype.ext
  have heval := mv_series_eval₂_subst_of_forall_constantCoeff_zero_adic
    (sigma := Unit) (tau := Unit) hI (fun _ => g)
    (fun _ => hg0) (fun _ => (x : R)) (fun _ => x.2) f
  simpa only [seriesAdic, PowerSeries.eval₂, PowerSeries.subst] using heval

@[simp]
theorem series_adic_x
    {I : Ideal R} (hI : IsAdic I) (x : I) :
    seriesAdic hI PowerSeries.X PowerSeries.constantCoeff_X x = x := by
  apply Subtype.ext
  exact PowerSeries.eval₂_X (RingHom.id R) (x : R)

@[simp]
theorem series_adic_zero
    {I : Ideal R} (hI : IsAdic I)
    (f : PowerSeries R) (hf0 : PowerSeries.constantCoeff f = 0) :
    seriesAdic hI f hf0 0 = 0 := by
  letI : IsLinearTopology R R :=
    IsLinearTopology.mk_of_hasBasis R hI.hasBasis_nhds_zero
  apply Subtype.ext
  change PowerSeries.eval₂ (RingHom.id R) 0 f = 0
  rw [show f = PowerSeries.X *
      PowerSeries.mk (fun n => PowerSeries.coeff (n + 1) f) +
        PowerSeries.C (PowerSeries.constantCoeff f) from
      PowerSeries.eq_X_mul_shift_add_const f]
  rw [← PowerSeries.coe_eval₂Hom continuous_id PowerSeries.HasEval.zero]
  rw [map_add, map_mul]
  have hX :
      (PowerSeries.eval₂Hom (φ := RingHom.id R) (a := (0 : R))
        continuous_id PowerSeries.HasEval.zero)
        PowerSeries.X = 0 := by
    rw [PowerSeries.coe_eval₂Hom, PowerSeries.eval₂_X]
  rw [hX, zero_mul, zero_add]
  rw [PowerSeries.coe_eval₂Hom, PowerSeries.eval₂_C, hf0, map_zero]

/-- Two-sided compositional inverses evaluate to mutually inverse maps of
the adic ideal. -/
noncomputable def powerSeriesAdic
    {I : Ideal R} (hI : IsAdic I)
    (theta inverseTheta : PowerSeries R)
    (htheta0 : PowerSeries.constantCoeff theta = 0)
    (hinverse0 : PowerSeries.constantCoeff inverseTheta = 0)
    (hthetaInverse : PowerSeries.subst inverseTheta theta = PowerSeries.X)
    (hinverseTheta : PowerSeries.subst theta inverseTheta = PowerSeries.X) :
    I ≃ I where
  toFun := seriesAdic hI theta htheta0
  invFun := seriesAdic hI inverseTheta hinverse0
  left_inv x := by
    rw [← series_adic_subst hI inverseTheta theta hinverse0 htheta0]
    simpa only [hinverseTheta] using series_adic_x hI x
  right_inv x := by
    rw [← series_adic_subst hI theta inverseTheta htheta0 hinverse0]
    simpa only [hthetaInverse] using series_adic_x hI x

@[simp]
theorem series_adic_equiv
    {I : Ideal R} (hI : IsAdic I)
    (theta inverseTheta : PowerSeries R)
    (htheta0 : PowerSeries.constantCoeff theta = 0)
    (hinverse0 : PowerSeries.constantCoeff inverseTheta = 0)
    (hthetaInverse : PowerSeries.subst inverseTheta theta = PowerSeries.X)
    (hinverseTheta : PowerSeries.subst theta inverseTheta = PowerSeries.X)
    (x : I) :
    powerSeriesAdic hI theta inverseTheta htheta0 hinverse0
        hthetaInverse hinverseTheta x =
      seriesAdic hI theta htheta0 x :=
  rfl

/-- An exact formal-series intertwining equation remains exact after
convergent evaluation on the adic ideal. -/
theorem series_adic_intertwines
    {I : Ideal R} (hI : IsAdic I)
    (f g theta : PowerSeries R)
    (hf0 : PowerSeries.constantCoeff f = 0)
    (hg0 : PowerSeries.constantCoeff g = 0)
    (htheta0 : PowerSeries.constantCoeff theta = 0)
    (hintertwines : PowerSeries.subst theta g = PowerSeries.subst f theta)
    (x : I) :
    seriesAdic hI g hg0 (seriesAdic hI theta htheta0 x) =
      seriesAdic hI theta htheta0
        (seriesAdic hI f hf0 x) := by
  calc
    seriesAdic hI g hg0
        (seriesAdic hI theta htheta0 x) =
        seriesAdic hI (PowerSeries.subst theta g)
          (PowerSeries.constantCoeff_subst_eq_zero htheta0 g hg0) x :=
      (series_adic_subst hI g theta hg0 htheta0 x).symm
    _ = seriesAdic hI (PowerSeries.subst f theta)
          (PowerSeries.constantCoeff_subst_eq_zero hf0 theta htheta0) x := by
      apply Subtype.ext
      change PowerSeries.eval₂ (RingHom.id R) (x : R)
          (PowerSeries.subst theta g) =
        PowerSeries.eval₂ (RingHom.id R) (x : R)
          (PowerSeries.subst f theta)
      rw [hintertwines]
    _ = seriesAdic hI theta htheta0
          (seriesAdic hI f hf0 x) :=
      series_adic_subst hI theta f htheta0 hf0 x

/-- The convergent version of Milne's torsion-root bijection: mutually
inverse zero-constant series carrying `f` to `g` identify their zero loci in
the adic ideal. -/
noncomputable def seriesAdicLocus
    {I : Ideal R} (hI : IsAdic I)
    (f g theta inverseTheta : PowerSeries R)
    (hf0 : PowerSeries.constantCoeff f = 0)
    (hg0 : PowerSeries.constantCoeff g = 0)
    (htheta0 : PowerSeries.constantCoeff theta = 0)
    (hinverse0 : PowerSeries.constantCoeff inverseTheta = 0)
    (hthetaInverse : PowerSeries.subst inverseTheta theta = PowerSeries.X)
    (hinverseTheta : PowerSeries.subst theta inverseTheta = PowerSeries.X)
    (hintertwines : PowerSeries.subst theta g = PowerSeries.subst f theta) :
    zeroLocus (seriesAdic hI f hf0) ≃
      zeroLocus (seriesAdic hI g hg0) :=
  zeroLocusIntertwines
    (seriesAdic hI f hf0)
    (seriesAdic hI g hg0)
    (powerSeriesAdic hI theta inverseTheta htheta0 hinverse0
      hthetaInverse hinverseTheta)
    (series_adic_zero hI theta htheta0)
    (series_adic_intertwines
      hI f g theta hf0 hg0 htheta0 hintertwines)

@[simp]
theorem series_adic_locus
    {I : Ideal R} (hI : IsAdic I)
    (f g theta inverseTheta : PowerSeries R)
    (hf0 : PowerSeries.constantCoeff f = 0)
    (hg0 : PowerSeries.constantCoeff g = 0)
    (htheta0 : PowerSeries.constantCoeff theta = 0)
    (hinverse0 : PowerSeries.constantCoeff inverseTheta = 0)
    (hthetaInverse : PowerSeries.subst inverseTheta theta = PowerSeries.X)
    (hinverseTheta : PowerSeries.subst theta inverseTheta = PowerSeries.X)
    (hintertwines : PowerSeries.subst theta g = PowerSeries.subst f theta)
    (x : zeroLocus (seriesAdic hI f hf0)) :
    (seriesAdicLocus hI f g theta inverseTheta
        hf0 hg0 htheta0 hinverse0 hthetaInverse hinverseTheta
        hintertwines x : I) =
      seriesAdic hI theta htheta0 x :=
  rfl

/-- The evaluated cancellation in the proof that the local Artin map is
independent of the uniformizer:
`(sigma theta)([u^-1]_f(lambda)) = theta(lambda)`. -/
theorem frobenius_twist_inverse
    {I : Ideal R} (hI : IsAdic I)
    (sigma : R →+* R) {theta u v : PowerSeries R}
    (hu0 : PowerSeries.constantCoeff u = 0)
    (hv0 : PowerSeries.constantCoeff v = 0)
    (hsigma : PowerSeries.map sigma theta = PowerSeries.subst u theta)
    (huv : PowerSeries.subst v u = PowerSeries.X)
    (x : I) :
    PowerSeries.eval₂ (RingHom.id R)
        (PowerSeries.eval₂ (RingHom.id R) (x : R) v)
        (PowerSeries.map sigma theta) =
      PowerSeries.eval₂ (RingHom.id R) (x : R) theta := by
  have heval :=
    mv_series_eval₂_subst_of_forall_constantCoeff_zero_adic
      (sigma := Unit) (tau := Unit) hI (fun _ ↦ v)
      (fun _ ↦ hv0) (fun _ ↦ (x : R)) (fun _ ↦ x.2)
      (PowerSeries.map sigma theta)
  have hformal :
      MvPowerSeries.subst (fun _ : Unit ↦ v)
          (PowerSeries.map sigma theta) = theta :=
    frobenius_twist_subst sigma hu0 hv0 hsigma huv
  rw [hformal] at heval
  simpa only [PowerSeries.eval₂] using heval.symm

/-- Two sets generate the same intermediate field when every generator of
each set belongs to the field generated by the other set. -/
theorem IntermediateField.adjoin_eqadj_subse
    {K L : Type*} [Field K] [Field L] [Algebra K L]
    {S T : Set L}
    (hST : S ⊆ IntermediateField.adjoin K T)
    (hTS : T ⊆ IntermediateField.adjoin K S) :
    IntermediateField.adjoin K S = IntermediateField.adjoin K T := by
  apply le_antisymm
  · exact IntermediateField.adjoin_le_iff.mpr hST
  · exact IntermediateField.adjoin_le_iff.mpr hTS

/-- A function and a two-sided inverse identify the fields generated by two
sets, provided each evaluated series lies in the field generated by its
input set.  This is Milne's chain of inclusions after Proposition 3.10. -/
theorem IntermediateField.adjoin_eqadj_invma
    {K L : Type*} [Field K] [Field L] [Algebra K L]
    {S T : Set L} {theta inverseTheta : L → L}
    (hthetaMaps : Set.MapsTo theta S T)
    (hinverseMaps : Set.MapsTo inverseTheta T S)
    (hleftInverse : Set.LeftInvOn inverseTheta theta S)
    (hrightInverse : Set.RightInvOn inverseTheta theta T)
    (hthetaMem : ∀ x ∈ S,
      theta x ∈ IntermediateField.adjoin K S)
    (hinverseMem : ∀ y ∈ T,
      inverseTheta y ∈ IntermediateField.adjoin K T) :
    IntermediateField.adjoin K S = IntermediateField.adjoin K T := by
  apply IntermediateField.adjoin_eqadj_subse
  · intro x hx
    rw [← hleftInverse hx]
    exact hinverseMem (theta x) (hthetaMaps hx)
  · intro y hy
    rw [← hrightInverse hy]
    exact hthetaMem (inverseTheta y) (hinverseMaps hy)

/-- The preceding field-generation result, phrased with a bijection on the
source and target sets. -/
theorem IntermediateField.adjoin_eq_adjoinbij
    {K L : Type*} [Field K] [Field L] [Algebra K L]
    {S T : Set L} {theta inverseTheta : L → L}
    (hbij : Set.BijOn theta S T)
    (hleftInverse : Set.LeftInvOn inverseTheta theta S)
    (hrightInverse : Set.RightInvOn inverseTheta theta T)
    (hinverseMaps : Set.MapsTo inverseTheta T S)
    (hthetaMem : ∀ x ∈ S,
      theta x ∈ IntermediateField.adjoin K S)
    (hinverseMem : ∀ y ∈ T,
      inverseTheta y ∈ IntermediateField.adjoin K T) :
    IntermediateField.adjoin K S = IntermediateField.adjoin K T :=
  IntermediateField.adjoin_eqadj_invma hbij.mapsTo
    hinverseMaps hleftInverse hrightInverse hthetaMem hinverseMem

end

end Towers.CField.LTate
