import Towers.ClassField.NormCorrespondence.SubgroupOpenClosed
import Towers.ClassField.NormCorrespondence.PrimeElementsGenerate
import Towers.ClassField.NormCorrespondence.PrincipalUnitQuotients
import Towers.ClassField.LocalBrauer.LocalFieldOrder

/-!
# Standard open subgroups of a local multiplicative group

A chosen prime element splits the multiplicative group into units and an
integral valuation exponent.  The subgroups generated by deep principal
units and a power of the prime element are the standard finite-index open
subgroups used throughout the local existence argument.
-/

namespace Towers.CField.NCorr

open Filter IsLocalRing ValuativeRel
open Towers.CField.LBrauer
open Towers.CField.LFTheory
open scoped Topology

noncomputable section

universe u

variable (K : Type u) [NontriviallyNormedField K] [IsUltrametricDist K]
  [ValuativeRel K]
  [Valuation.Compatible (NormedField.valuation (K := K))]
  [IsNonarchimedeanLocalField K]

/-- Units of the valuation integer ring are canonically the local-unit
subgroup defined using the intrinsic valuative relation. -/
noncomputable def integerUnitsUnit :
    𝒪[K]ˣ ≃* localUnitSubgroup K where
  toFun u :=
    ⟨Units.map (𝒪[K]).subtype u, by
      change valuation K
        ((((u : 𝒪[K]ˣ) : 𝒪[K]) : K)) = 1
      exact (Valuation.integer.integers (valuation K)).valuation_unit u⟩
  invFun x :=
    { val := ⟨((x : Kˣ) : K), by
        change valuation K ((x : Kˣ) : K) ≤ 1
        exact ((local_subgroup K (x : Kˣ)).1 x.property).le⟩
      inv := ⟨(((x : Kˣ)⁻¹ : Kˣ) : K), by
        change valuation K ((((x : Kˣ)⁻¹ : Kˣ) : K)) ≤ 1
        rw [Units.val_inv_eq_inv_val, map_inv₀,
          (local_subgroup K (x : Kˣ)).1 x.property, inv_one]⟩
      val_inv := by ext; simp
      inv_val := by ext; simp }
  left_inv u := by ext; rfl
  right_inv x := by apply Subtype.ext; rfl
  map_mul' x y := by apply Subtype.ext; rfl

/-- The preceding multiplicative equivalence is a homeomorphism for the
subspace topologies. -/
noncomputable def integerUnitsContinuous :
    𝒪[K]ˣ ≃ₜ* localUnitSubgroup K where
  __ := integerUnitsUnit K
  continuous_toFun :=
    (continuous_subtype_val.units_map).subtype_mk _
  continuous_invFun := by
    apply Units.continuous_iff.mpr
    constructor
    · exact
        ((Units.continuous_val.comp continuous_subtype_val).subtype_mk _)
    · exact
        ((Units.continuous_coe_inv.comp continuous_subtype_val).subtype_mk _)

/-- The `m`th principal-unit subgroup, viewed inside `Kˣ`. -/
noncomputable def principalUnitField (m : ℕ) : Subgroup Kˣ :=
  (principalUnitSubgroup 𝒪[K] m).map (Units.map (𝒪[K]).subtype)

/-- The same principal-unit subgroup, with codomain restricted to the local
unit subgroup. -/
noncomputable def principalUnitLocal (m : ℕ) :
    Subgroup (localUnitSubgroup K) :=
  (principalUnitSubgroup 𝒪[K] m).map
    (integerUnitsUnit K).toMonoidHom

omit [IsUltrametricDist K]
  [Valuation.Compatible (NormedField.valuation (K := K))] in
/-- Principal units form an open subgroup of the local-unit group. -/
theorem principal_unit_open (m : ℕ) :
    IsOpen (principalUnitLocal K m :
      Set (localUnitSubgroup K)) := by
  let P := principalUnitSubgroup 𝒪[K] m
  have hPopen : IsOpen (P : Set 𝒪[K]ˣ) :=
    P.isOpen_of_mem_nhds (principal_unit_nhds K m)
  simpa [principalUnitLocal, P] using
    (integerUnitsContinuous K).isOpenMap
      (P : Set 𝒪[K]ˣ) hPopen

omit [IsUltrametricDist K]
  [Valuation.Compatible (NormedField.valuation (K := K))] in
/-- Principal units are open in the full multiplicative group as well. -/
theorem principal_field_open (m : ℕ) :
    IsOpen (principalUnitField K m : Set Kˣ) := by
  let U := localUnitSubgroup K
  let P := principalUnitLocal K m
  have himageOpen : IsOpen (((↑) : U → Kˣ) '' (P : Set U)) :=
    (local_unit_open K).isOpenMap_subtype_val
      (P : Set U) (principal_unit_open K m)
  convert himageOpen using 1
  ext x
  constructor
  · rintro ⟨u, hu, rfl⟩
    let y : U := integerUnitsUnit K u
    refine ⟨y, ?_, rfl⟩
    exact ⟨u, hu, rfl⟩
  · rintro ⟨y, ⟨u, hu, huy⟩, rfl⟩
    refine ⟨u, hu, ?_⟩
    exact congrArg Subtype.val huy

/-- The usual subgroup `(1 + 𝔪^m) · ⟨π^n⟩` of `Kˣ`.  In the commutative
multiplicative group this product is the join of the two subgroups. -/
noncomputable def standardOpenSubgroup
    (pi : Kˣ) (m n : ℕ) : Subgroup Kˣ :=
  principalUnitField K m ⊔ Subgroup.zpowers (pi ^ n)

omit [Valuation.Compatible (NormedField.valuation (K := K))] in
/-- Adjoining all powers of one prime element to a principal-unit subgroup
gives an open subgroup of finite index.  Its quotient is a quotient of the
finite principal-unit quotient of the compact local-unit group. -/
theorem standard_open_index
    (pi : Kˣ) (hpi : LocalPrimeElement K pi) (m : ℕ) :
    OFSubgro (standardOpenSubgroup K pi m 1) := by
  let U := localUnitSubgroup K
  let P := principalUnitLocal K m
  let J := standardOpenSubgroup K pi m 1
  have hJopen : IsOpen (J : Set Kˣ) := by
    apply Subgroup.isOpen_mono
      (show principalUnitField K m ≤ J from le_sup_left)
    exact principal_field_open K m
  refine ⟨hJopen, ?_⟩
  letI : CompactSpace U :=
    isCompact_iff_compactSpace.mp (local_unit_compact K)
  letI : Finite (U ⧸ P) :=
    P.quotient_finite_of_isOpen
      (principal_unit_open K m)
  let q : U →* Kˣ ⧸ J :=
    (QuotientGroup.mk' J).comp U.subtype
  have hPker : P ≤ q.ker := by
    intro x hx
    obtain ⟨u, hu, rfl⟩ := hx
    rw [MonoidHom.mem_ker]
    apply (QuotientGroup.eq_one_iff
      ((integerUnitsUnit K) u : Kˣ)).2
    apply (show principalUnitField K m ≤ J from le_sup_left)
    exact ⟨u, hu, rfl⟩
  let qbar : U ⧸ P →* Kˣ ⧸ J :=
    QuotientGroup.lift P q hPker
  have hqbar_surjective : Function.Surjective qbar := by
    intro z
    obtain ⟨x, rfl⟩ := QuotientGroup.mk'_surjective J z
    let a : ℤ := localUnitOrder K (Additive.ofMul x)
    let u : Kˣ := x * pi ^ (-a)
    have hpiorder :
        localUnitOrder K (Additive.ofMul pi) = 1 :=
      (local_element_order K pi).1 hpi
    have huorder :
        localUnitOrder K (Additive.ofMul u) = 0 := by
      change localUnitOrder K
        (Additive.ofMul x + (-a) • Additive.ofMul pi) = 0
      rw [map_add, map_zsmul, hpiorder]
      simp [a]
    have huval : valuation K (u : K) = 1 := by
      apply le_antisymm
      · have hle :
          localUnitOrder K (Additive.ofMul (1 : Kˣ)) ≤
            localUnitOrder K (Additive.ofMul u) := by
          simp [huorder]
        simpa using
          (local_order_valuation K (1 : Kˣ) u).1 hle
      · have hle :
          localUnitOrder K (Additive.ofMul u) ≤
            localUnitOrder K (Additive.ofMul (1 : Kˣ)) := by
          simp [huorder]
        simpa using
          (local_order_valuation K u (1 : Kˣ)).1 hle
    let uU : U := ⟨u, (local_subgroup K u).2 huval⟩
    refine ⟨QuotientGroup.mk' P uU, ?_⟩
    change QuotientGroup.mk' J u = QuotientGroup.mk' J x
    have hpiJ : pi ∈ J := by
      apply (show Subgroup.zpowers (pi ^ 1) ≤ J from le_sup_right)
      rw [pow_one]
      exact Subgroup.mem_zpowers pi
    have hpowaJ : pi ^ (-a) ∈ J := J.zpow_mem hpiJ (-a)
    have hpowaClass :
        QuotientGroup.mk' J (pi ^ (-a)) = 1 :=
      (QuotientGroup.eq_one_iff (pi ^ (-a))).2 hpowaJ
    rw [show u = x * pi ^ (-a) by rfl, map_mul, hpowaClass, mul_one]
  letI : Finite (Kˣ ⧸ J) :=
    Finite.of_surjective qbar hqbar_surjective
  exact Subgroup.finiteIndex_of_finite_quotient

omit [Valuation.Compatible (NormedField.valuation (K := K))] in
/-- Under the Local Existence Theorem, the standard subgroup generated by
deep principal units and one prime element is the norm group of a finite
abelian subextension. -/
theorem standard_open_group
    (hExistence : LocalExistenceTheorem K)
    (pi : Kˣ) (hpi : LocalPrimeElement K pi) (m : ℕ) :
    LGroup K (standardOpenSubgroup K pi m 1) :=
  (hExistence (standardOpenSubgroup K pi m 1)).2
    (standard_open_index K pi hpi m)

/-- Every open subgroup of `Kˣ` contains all sufficiently deep principal
units. -/
theorem principal_unit_field
    (H : Subgroup Kˣ) (hH : IsOpen (H : Set Kˣ)) :
    ∃ m : ℕ, principalUnitField K m ≤ H := by
  let j : 𝒪[K]ˣ →* Kˣ := Units.map (𝒪[K]).subtype
  have hj : Continuous j := continuous_subtype_val.units_map
  have hpre : j ⁻¹' (H : Set Kˣ) ∈ 𝓝 (1 : 𝒪[K]ˣ) :=
    (hH.preimage hj).mem_nhds (by simp [j])
  obtain ⟨m, -, hm⟩ :=
    (principal_unit_basis K).mem_iff.mp hpre
  refine ⟨m, ?_⟩
  rintro _ ⟨u, hu, rfl⟩
  exact hm hu

/-- Milne's standard-subgroup cofinality argument: if `H` is open and has
finite index, then for every chosen prime element `π`, `H` contains
`(1 + 𝔪^m) · ⟨π^[Kˣ:H]⟩` for some `m`.  The containment of the prime power is
the finite-index group-theoretic argument; openness supplies the principal
units. -/
theorem standard_open_subgroup
    (H : Subgroup Kˣ) (hopen : IsOpen (H : Set Kˣ))
    [H.FiniteIndex] (pi : Kˣ) :
    ∃ m : ℕ, standardOpenSubgroup K pi m H.index ≤ H := by
  obtain ⟨m, hm⟩ := principal_unit_field K H hopen
  refine ⟨m, sup_le hm ?_⟩
  exact Subgroup.zpowers_le.mpr (H.pow_index_mem pi)

end

end Towers.CField.NCorr
