import Mathlib.LinearAlgebra.BilinearForm.Orthogonal
import Mathlib.LinearAlgebra.QuadraticForm.Basic

/-!
# Chapter VIII, Section 6: splitting off a represented line

This is Proposition 6.1 in the source.  The associated bilinear form of a
quadratic form takes the value `Q(e)` on `(e,e)`.  Thus a line generated by a
vector of nonzero value is nonisotropic and is complementary to its orthogonal
complement.
-/

namespace Towers.CField.QForms

variable {k V : Type*} [Field k] [AddCommGroup V] [Module k V]

/-- **Proposition 6.1.** If `Q` represents a nonzero scalar `a`, the line of a
representing vector is complementary, and orthogonal, to its orthogonal
complement. -/
theorem orthogonal_decomposition
    [NeZero (2 : k)] (Q : QuadraticForm k V) {a : k} (ha : a ≠ 0)
    (hrep : ∃ e : V, Q e = a) :
    ∃ e : V, Q e = a ∧
      IsCompl (k ∙ e)
        (LinearMap.BilinForm.orthogonal Q.polarBilin (k ∙ e)) := by
  obtain ⟨e, he⟩ := hrep
  refine ⟨e, he, LinearMap.BilinForm.isCompl_span_singleton_orthogonal ?_⟩
  intro hortho
  have hzero : 2 * Q e = 0 := by
    change Q.polarBilin e e = 0 at hortho
    rw [QuadraticMap.polarBilin_apply_apply, QuadraticMap.polar_self] at hortho
    simpa [nsmul_eq_mul] using hortho
  exact ha (by
    rw [he] at hzero
    exact (mul_eq_zero.mp hzero).resolve_left (NeZero.ne (2 : k)))

/-- A representing vector for a nonzero scalar is itself nonzero. -/
theorem representing_vector_ne
    (Q : QuadraticForm k V) {a : k} (ha : a ≠ 0) {e : V} (he : Q e = a) :
    e ≠ 0 := by
  intro h
  subst e
  exact ha (by simpa using he.symm)

end Towers.CField.QForms
