import Submission.ClassField.LocalBrauer.DivisionIdealPowers

/-!
# Chapter IV, Section 4: products and powers of division-algebra ideals

Mathlib currently equips two-sided ideals with their lattice structure but
not with multiplication.  We therefore define the product directly as the
two-sided ideal spanned by pairwise products, and define powers recursively.
For the integer ring of a local division algebra, order thresholds then show
that products of nonzero principal ideals are principal and their orders add.
-/

namespace Submission.CField.LBrauer

noncomputable section

universe u v

open ValuativeRel

/-- The product of two two-sided ideals, defined as the ideal generated by
all pairwise products. -/
def twoSidedProduct {R : Type v} [Ring R]
    (I J : TwoSidedIdeal R) : TwoSidedIdeal R :=
  TwoSidedIdeal.span {z | ∃ x ∈ I, ∃ y ∈ J, x * y = z}

/-- Recursive powers for the explicit product of two-sided ideals. -/
def twoSidedPower {R : Type v} [Ring R]
    (I : TwoSidedIdeal R) : ℕ → TwoSidedIdeal R
  | 0 => ⊤
  | n + 1 => twoSidedProduct I (twoSidedPower I n)

@[simp]
theorem two_sided_zero {R : Type v} [Ring R]
    (I : TwoSidedIdeal R) : twoSidedPower I 0 = ⊤ :=
  rfl

@[simp]
theorem sided_ideal_succ {R : Type v} [Ring R]
    (I : TwoSidedIdeal R) (n : ℕ) :
    twoSidedPower I (n + 1) =
      twoSidedProduct I (twoSidedPower I n) :=
  rfl

variable (K D : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
  [IsNonarchimedeanLocalField K] [DivisionRing D] [Algebra K D]
  [Algebra.IsCentral K D] [Module.Finite K D]

local instance : UniformSpace K := IsTopologicalAddGroup.rightUniformSpace K
local instance : IsUniformAddGroup K := isUniformAddGroup_of_addCommGroup
local instance : Valuation.RankOne
    (Valued.v (R := K) (Γ₀ := ValueGroupWithZero K)) := by
  change Valuation.RankOne (valuation K)
  infer_instance
local instance : NontriviallyNormedField K :=
  Valued.toNontriviallyNormedField K (ValueGroupWithZero K)

private abbrev OD := divisionIntegerSubring K D

omit [Algebra.IsCentral K D] in
/-- Products of nonzero principal ideals in the division-algebra integer
ring are generated by the product of their generators. -/
theorem sided_span_singleton
    (x y : OD K D) (hx0 : (x : D) ≠ 0) (hy0 : (y : D) ≠ 0) :
    twoSidedProduct
        (TwoSidedIdeal.span ({x} : Set (OD K D)))
        (TwoSidedIdeal.span ({y} : Set (OD K D))) =
      TwoSidedIdeal.span ({x * y} : Set (OD K D)) := by
  apply le_antisymm
  · rw [twoSidedProduct, TwoSidedIdeal.span_le]
    rintro z ⟨a, ha, b, hb, rfl⟩
    have hxa := (span_singleton_order K D x a hx0).1 ha
    have hyb := (span_singleton_order K D y b hy0).1 hb
    have hxy0 : ((x * y : OD K D) : D) ≠ 0 := mul_ne_zero hx0 hy0
    apply (span_singleton_order K D (x * y) (a * b) hxy0).2
    change divisionAlgebraOrder K (D := D) ((x : D) * (y : D)) ≤
      divisionAlgebraOrder K (D := D) ((a : D) * (b : D))
    rw [division_algebra_mul, division_algebra_mul]
    exact add_le_add hxa hyb
  · rw [TwoSidedIdeal.span_le]
    intro z hz
    rw [Set.mem_singleton_iff] at hz
    subst z
    apply TwoSidedIdeal.subset_span
    exact ⟨x, TwoSidedIdeal.subset_span (Set.mem_singleton x),
      y, TwoSidedIdeal.subset_span (Set.mem_singleton y), rfl⟩

omit [Algebra.IsCentral K D] in
/-- Powers of a nonzero principal ideal are generated by the corresponding
power of its generator. -/
theorem two_sided_singleton
    (x : OD K D) (hx0 : (x : D) ≠ 0) (m : ℕ) :
    twoSidedPower (TwoSidedIdeal.span ({x} : Set (OD K D))) m =
      TwoSidedIdeal.span ({x ^ m} : Set (OD K D)) := by
  induction m with
  | zero =>
      rw [two_sided_zero, pow_zero]
      exact (TwoSidedIdeal.eq_top _
        (TwoSidedIdeal.subset_span (Set.mem_singleton (1 : OD K D)))).symm
  | succ m ih =>
      rw [sided_ideal_succ, ih,
        sided_span_singleton K D x (x ^ m) hx0]
      · rw [pow_succ']
      · exact pow_ne_zero m hx0

omit [Algebra.IsCentral K D] [Module.Finite K D] in
/-- The division-algebra order of a power is the corresponding natural
multiple of the order. -/
theorem division_algebra_pow (z : D) (m : ℕ) :
    divisionAlgebraOrder K (D := D) (z ^ m) =
      m • divisionAlgebraOrder K (D := D) z := by
  induction m with
  | zero => simp
  | succ m ih =>
      rw [pow_succ, division_algebra_mul, ih, succ_nsmul]

omit [Algebra.IsCentral K D] in
/-- Principal ideals with nonzero generators of the same order coincide. -/
theorem singleton_order
    (x y : OD K D) (hx0 : (x : D) ≠ 0) (hy0 : (y : D) ≠ 0)
    (hxy : divisionAlgebraOrder K (D := D) (x : D) =
      divisionAlgebraOrder K (D := D) (y : D)) :
    TwoSidedIdeal.span ({x} : Set (OD K D)) =
      TwoSidedIdeal.span ({y} : Set (OD K D)) := by
  apply TwoSidedIdeal.ext
  intro z
  rw [span_singleton_order K D x z hx0,
    span_singleton_order K D y z hy0, hxy]

omit [Algebra.IsCentral K D] in
/-- An element of order `1 / e` generates the maximal ideal when the full
value group is `(1 / e) * ℤ`. -/
theorem division_maximal_div
    (e : ℕ) (he : 0 < e)
    (hrange : ∀ q : ℚ,
      q ∈ (divisionUnitOrder K D).range ↔
        ∃ z : ℤ, q = (z : ℚ) / (e : ℚ))
    (π : OD K D) (hπ0 : (π : D) ≠ 0)
    (hπorder : divisionUnitOrder K D
        (Additive.ofMul (Units.mk0 (π : D) hπ0)) =
      (1 : ℚ) / (e : ℚ)) :
    divisionMaximalIdeal K D =
      TwoSidedIdeal.span ({π} : Set (OD K D)) := by
  apply TwoSidedIdeal.ext
  intro y
  rw [division_maximal_pos K D,
    span_singleton_order K D π y hπ0]
  by_cases hy0 : (y : D) = 0
  · rw [hy0, division_algebra_zero]
    simp
  rw [division_ne_zero K (D := D) (π : D) hπ0,
    division_ne_zero K (D := D) (y : D) hy0,
    WithTop.coe_pos, WithTop.coe_le_coe, hπorder]
  let q := divisionUnitOrder K D
    (Additive.ofMul (Units.mk0 (y : D) hy0))
  have hqmem : q ∈ (divisionUnitOrder K D).range :=
    ⟨Additive.ofMul (Units.mk0 (y : D) hy0), rfl⟩
  obtain ⟨z, hz⟩ := (hrange q).1 hqmem
  change 0 < q ↔ (1 : ℚ) / (e : ℚ) ≤ q
  rw [hz]
  have heQ : (0 : ℚ) < (e : ℚ) := by exact_mod_cast he
  rw [div_pos_iff_of_pos_right heQ,
    div_le_div_iff_of_pos_right heQ]
  norm_cast

omit [Algebra.IsCentral K D] in
/-- Consequently, powers of the maximal ideal are generated by powers of
any element of order `1 / e`. -/
theorem division_maximal_pow
    (e : ℕ) (he : 0 < e)
    (hrange : ∀ q : ℚ,
      q ∈ (divisionUnitOrder K D).range ↔
        ∃ z : ℤ, q = (z : ℚ) / (e : ℚ))
    (π : OD K D) (hπ0 : (π : D) ≠ 0)
    (hπorder : divisionUnitOrder K D
        (Additive.ofMul (Units.mk0 (π : D) hπ0)) =
      (1 : ℚ) / (e : ℚ)) (m : ℕ) :
    twoSidedPower (divisionMaximalIdeal K D) m =
      TwoSidedIdeal.span ({π ^ m} : Set (OD K D)) := by
  rw [division_maximal_div K D e he hrange π hπ0 hπorder,
    two_sided_singleton K D π hπ0]

omit [Algebra.IsCentral K D] in
/-- The exact value-group description supplies an integer of order `1 / e`. -/
theorem division_integer_div
    (e : ℕ) (he : 0 < e)
    (hrange : ∀ q : ℚ,
      q ∈ (divisionUnitOrder K D).range ↔
        ∃ z : ℤ, q = (z : ℚ) / (e : ℚ)) :
    ∃ π : OD K D, ∃ hπ0 : (π : D) ≠ 0,
      divisionUnitOrder K D
          (Additive.ofMul (Units.mk0 (π : D) hπ0)) =
        (1 : ℚ) / (e : ℚ) := by
  let q : ℚ := (1 : ℚ) / (e : ℚ)
  have hqmem : q ∈ (divisionUnitOrder K D).range :=
    (hrange q).2 ⟨1, rfl⟩
  obtain ⟨u, hu⟩ := hqmem
  let d : D := (u.toMul : D)
  have hd0 : d ≠ 0 := u.toMul.ne_zero
  have hunit : Units.mk0 d hd0 = u.toMul := by
    apply Units.ext
    rfl
  have hdOrder : 0 ≤ divisionAlgebraOrder K (D := D) d := by
    rw [division_ne_zero K (D := D) d hd0, hunit]
    change (0 : WithTop ℚ) ≤ (divisionUnitOrder K D u : ℚ)
    rw [hu, WithTop.coe_nonneg]
    dsimp [q]
    positivity
  let π : OD K D :=
    ⟨d, (integer_subring_nonneg K D d).2 hdOrder⟩
  refine ⟨π, ?_, ?_⟩
  · exact hd0
  · change divisionUnitOrder K D
      (Additive.ofMul (Units.mk0 d hd0)) = _
    rw [hunit]
    simpa [q] using hu

omit [Algebra.IsCentral K D] in
private theorem division_nat_div
    (e m : ℕ) (π : OD K D) (hπ0 : (π : D) ≠ 0)
    (hπorder : divisionUnitOrder K D
        (Additive.ofMul (Units.mk0 (π : D) hπ0)) =
      (1 : ℚ) / (e : ℚ)) :
    divisionAlgebraOrder K (D := D) ((π ^ m : OD K D) : D) =
      (((m : ℚ) / (e : ℚ) : ℚ) : WithTop ℚ) := by
  change divisionAlgebraOrder K (D := D) ((π : D) ^ m) = _
  rw [division_algebra_pow,
    division_ne_zero K (D := D) (π : D) hπ0, hπorder]
  rw [← WithTop.coe_nsmul]
  norm_cast
  simp only [nsmul_eq_mul]
  ring

/-- Under an exact `(1 / e) * ℤ` value-group description, every nonzero
two-sided ideal is a power of the maximal ideal. -/
theorem nonzero_sided_uniformizer
    (e : ℕ) (he : 0 < e)
    (hrange : ∀ q : ℚ,
      q ∈ (divisionUnitOrder K D).range ↔
        ∃ z : ℤ, q = (z : ℚ) / (e : ℚ))
    (π : OD K D) (hπ0 : (π : D) ≠ 0)
    (hπorder : divisionUnitOrder K D
        (Additive.ofMul (Units.mk0 (π : D) hπ0)) =
      (1 : ℚ) / (e : ℚ))
    (J : TwoSidedIdeal (OD K D)) (hJ : J ≠ ⊥) :
    ∃ m : ℕ, J = twoSidedPower (divisionMaximalIdeal K D) m := by
  obtain ⟨x, hxJ, hx0, _, hspan, _⟩ :=
    nonzero_sided_threshold K D J hJ
  obtain ⟨m, hxOrder⟩ :=
    division_integer_numerator K D e he hrange x hx0
  have hxOrder' : divisionAlgebraOrder K (D := D) (x : D) =
      (((m : ℚ) / (e : ℚ) : ℚ) : WithTop ℚ) := by
    rw [division_ne_zero K (D := D) (x : D) hx0,
      hxOrder]
  have hπm0 : (((π ^ m : OD K D) : D)) ≠ 0 := pow_ne_zero m hπ0
  have hspanEq : TwoSidedIdeal.span ({x} : Set (OD K D)) =
      TwoSidedIdeal.span ({π ^ m} : Set (OD K D)) :=
    singleton_order K D x (π ^ m) hx0 hπm0
      (hxOrder'.trans
        (division_nat_div K D e m π hπ0 hπorder).symm)
  refine ⟨m, ?_⟩
  rw [hspan, hspanEq]
  exact (division_maximal_pow K D e he hrange π hπ0 hπorder m).symm

/-- Exact value-group data alone suffice to classify every nonzero ideal as
a power of the maximal ideal. -/
theorem nonzero_sided_maximal
    (e : ℕ) (he : 0 < e)
    (hrange : ∀ q : ℚ,
      q ∈ (divisionUnitOrder K D).range ↔
        ∃ z : ℤ, q = (z : ℚ) / (e : ℚ))
    (J : TwoSidedIdeal (OD K D)) (hJ : J ≠ ⊥) :
    ∃ m : ℕ, J = twoSidedPower (divisionMaximalIdeal K D) m := by
  obtain ⟨π, hπ0, hπorder⟩ :=
    division_integer_div K D e he hrange
  exact nonzero_sided_uniformizer
    K D e he hrange π hπ0 hπorder J hJ

/-- Unconditionally, every nonzero two-sided ideal of `O_D` is a power of
its maximal ideal. -/
theorem nonzero_two_sided
    (J : TwoSidedIdeal (OD K D)) (hJ : J ≠ ⊥) :
    ∃ m : ℕ, J = twoSidedPower (divisionMaximalIdeal K D) m := by
  obtain ⟨e, he, _, _, hrange⟩ := ramification_value_group K D
  exact nonzero_sided_maximal
    K D e he hrange J hJ

/-- A base-field unit of nonnegative order, regarded as an integer of the
division algebra. -/
def algebraUnitInteger (x : Kˣ)
    (hx : 0 ≤ localUnitOrder K (Additive.ofMul x)) : OD K D :=
  ⟨algebraMap K D (x : K),
    (division_subring_nonneg K D x).2 hx⟩

omit [Algebra.IsCentral K D] in
@[simp]
theorem algebra_integer_coe (x : Kˣ)
    (hx : 0 ≤ localUnitOrder K (Additive.ofMul x)) :
    (algebraUnitInteger K D x hx : D) = algebraMap K D (x : K) :=
  rfl

omit [Algebra.IsCentral K D] in
/-- The order of an embedded base-field unit is its normalized base-field
order. -/
theorem division_algebra_integer
    (x : Kˣ) (hx : 0 ≤ localUnitOrder K (Additive.ofMul x)) :
    divisionAlgebraOrder K (D := D) (algebraUnitInteger K D x hx : D) =
      (((localUnitOrder K (Additive.ofMul x) : ℚ) : ℚ) : WithTop ℚ) := by
  have hx0 : algebraMap K D (x : K) ≠ 0 :=
    (map_ne_zero (algebraMap K D)).2 x.ne_zero
  rw [algebra_integer_coe,
    division_ne_zero K (D := D) _ hx0]
  have hunit : Units.mk0 (algebraMap K D (x : K)) hx0 =
      Units.map (algebraMap K D).toMonoidHom x := by
    apply Units.ext
    rfl
  rw [hunit]
  have h := division_algebra_order K D (Additive.ofMul x)
  change divisionUnitOrder K D
      (Additive.ofMul (Units.map (algebraMap K D).toMonoidHom x)) =
    (localUnitOrder K (Additive.ofMul x) : ℚ) at h
  exact congrArg (fun q : ℚ ↦ (q : WithTop ℚ)) h

omit [Algebra.IsCentral K D] in
/-- If `varpi_K` is a base-field uniformizer (normalized order one), then
the `e`th power of the maximal ideal is the principal ideal generated by its
image in the division algebra: `P ^ e = varpi_K O_D`. -/
theorem division_maximal_uniformizer
    (e : ℕ) (he : 0 < e)
    (hrange : ∀ q : ℚ,
      q ∈ (divisionUnitOrder K D).range ↔
        ∃ z : ℤ, q = (z : ℚ) / (e : ℚ))
    (π : OD K D) (hπ0 : (π : D) ≠ 0)
    (hπorder : divisionUnitOrder K D
        (Additive.ofMul (Units.mk0 (π : D) hπ0)) =
      (1 : ℚ) / (e : ℚ))
    (varpiK : Kˣ)
    (hvarpiK : localUnitOrder K (Additive.ofMul varpiK) = 1) :
    let hnonneg : 0 ≤ localUnitOrder K (Additive.ofMul varpiK) :=
      hvarpiK.symm ▸ (by omega)
    twoSidedPower (divisionMaximalIdeal K D) e =
      TwoSidedIdeal.span
        ({algebraUnitInteger K D varpiK hnonneg} : Set (OD K D)) := by
  let hnonneg : 0 ≤ localUnitOrder K (Additive.ofMul varpiK) :=
    hvarpiK.symm ▸ (by omega)
  let a : OD K D := algebraUnitInteger K D varpiK hnonneg
  have ha0 : (a : D) ≠ 0 := by
    change algebraMap K D (varpiK : K) ≠ 0
    exact (map_ne_zero (algebraMap K D)).2 varpiK.ne_zero
  rw [division_maximal_pow K D e he hrange π hπ0 hπorder e]
  apply singleton_order K D (π ^ e) a
  · exact pow_ne_zero e hπ0
  · exact ha0
  · rw [division_nat_div K D e e π hπ0 hπorder,
      division_algebra_integer K D varpiK hnonneg,
      hvarpiK]
    have heQ : (e : ℚ) ≠ 0 := by exact_mod_cast he.ne'
    rw [div_self heQ]
    norm_num

omit [Algebra.IsCentral K D] in
/-- The source relation `P ^ e = varpi_K O_D`, using only the exact value
group and a base-field unit `varpi_K` of normalized order one. -/
theorem division_maximal_algebra
    (e : ℕ) (he : 0 < e)
    (hrange : ∀ q : ℚ,
      q ∈ (divisionUnitOrder K D).range ↔
        ∃ z : ℤ, q = (z : ℚ) / (e : ℚ))
    (varpiK : Kˣ)
    (hvarpiK : localUnitOrder K (Additive.ofMul varpiK) = 1) :
    let hnonneg : 0 ≤ localUnitOrder K (Additive.ofMul varpiK) :=
      hvarpiK.symm ▸ (by omega)
    twoSidedPower (divisionMaximalIdeal K D) e =
      TwoSidedIdeal.span
        ({algebraUnitInteger K D varpiK hnonneg} : Set (OD K D)) := by
  obtain ⟨π, hπ0, hπorder⟩ :=
    division_integer_div K D e he hrange
  exact division_maximal_uniformizer
    K D e he hrange π hπ0 hπorder varpiK hvarpiK

end

end Submission.CField.LBrauer
