import Mathlib.RingTheory.TwoSidedIdeal.Operations
import Submission.ClassField.LocalBrauer.DivisionAlgebraRamification
import Submission.ClassField.LocalBrauer.DivisionIntegers

/-!
# Chapter IV, Section 4: ideals in the integer ring of a division algebra

The order on a local division algebra totally orders its principal ideals.
In particular, a nonzero two-sided ideal is generated by any one of its
elements having least order.  The discreteness theorem for the value group
will supply such a least-order element.
-/

namespace Submission.CField.LBrauer

noncomputable section

universe u

open ValuativeRel

variable (K D : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
  [IsNonarchimedeanLocalField K] [DivisionRing D] [Algebra K D]
  [Algebra.IsCentral K D] [Module.Finite K D]

local instance : UniformSpace K := IsTopologicalAddGroup.rightUniformSpace K
local instance : IsUniformAddGroup K := isUniformAddGroup_of_addCommGroup
local instance : Valuation.RankOne
    (Valued.v (R := K) (Γ₀ := ValueGroupWithZero K)) := by
  change Valuation.RankOne (valuation K)
  infer_instance
local instance : NontriviallyNormedField K :=
  Valued.toNontriviallyNormedField K (ValueGroupWithZero K)

private abbrev OD := divisionIntegerSubring K D

omit [Algebra.IsCentral K D] [Module.Finite K D] in
/-- Negation does not change the order on a local division algebra. -/
theorem division_algebra_neg (z : D) :
    divisionAlgebraOrder K (D := D) (-z) =
      divisionAlgebraOrder K (D := D) z := by
  have hneg : (-1 : D) ≠ 0 := neg_ne_zero.mpr one_ne_zero
  let u : Dˣ := Units.mk0 (-1 : D) hneg
  have huu : Additive.ofMul u + Additive.ofMul u = 0 := by
    apply Additive.ext
    apply Units.ext
    simp [u]
  have huOrder : divisionUnitOrder K D (Additive.ofMul u) = 0 := by
    have h := congrArg (divisionUnitOrder K D) huu
    simp only [map_add, map_zero] at h
    linarith
  calc
    divisionAlgebraOrder K (D := D) (-z) =
        divisionAlgebraOrder K (D := D) ((-1 : D) * z) := by rw [neg_one_mul]
    _ = divisionAlgebraOrder K (D := D) (-1 : D) +
        divisionAlgebraOrder K (D := D) z :=
      division_algebra_mul K (D := D) _ _
    _ = divisionAlgebraOrder K (D := D) z := by
      rw [division_ne_zero K (D := D) (-1 : D) hneg]
      change
        (divisionUnitOrder K D (Additive.ofMul u) : WithTop ℚ) + _ = _
      rw [huOrder, WithTop.coe_zero, zero_add]

/-- The two-sided ideal of integers whose order is at least the order of
`x`. -/
def divisionThresholdIdeal (x : OD K D) : TwoSidedIdeal (OD K D) :=
  TwoSidedIdeal.mk'
    {y | divisionAlgebraOrder K (D := D) (x : D) ≤
      divisionAlgebraOrder K (D := D) (y : D)}
    (by simp)
    (by
      intro y z hy hz
      exact (le_min hy hz).trans
        (division_algebra_min K (D := D) (y : D) (z : D)))
    (by
      intro y hy
      change divisionAlgebraOrder K (D := D) (x : D) ≤
        divisionAlgebraOrder K (D := D) (-(y : D))
      rw [division_algebra_neg]
      exact hy)
    (by
      intro a y hy
      have ha : 0 ≤ divisionAlgebraOrder K (D := D) (a : D) :=
        (integer_subring_nonneg K D (a : D)).1 a.property
      change divisionAlgebraOrder K (D := D) (x : D) ≤
        divisionAlgebraOrder K (D := D) ((a : D) * (y : D))
      rw [division_algebra_mul]
      exact hy.trans (by
        calc
          divisionAlgebraOrder K (D := D) (y : D) =
              0 + divisionAlgebraOrder K (D := D) (y : D) := (zero_add _).symm
          _ ≤ divisionAlgebraOrder K (D := D) (a : D) +
              divisionAlgebraOrder K (D := D) (y : D) :=
            add_le_add_left ha _
        ))
    (by
      intro y a hy
      have ha : 0 ≤ divisionAlgebraOrder K (D := D) (a : D) :=
        (integer_subring_nonneg K D (a : D)).1 a.property
      change divisionAlgebraOrder K (D := D) (x : D) ≤
        divisionAlgebraOrder K (D := D) ((y : D) * (a : D))
      rw [division_algebra_mul]
      exact hy.trans (by
        calc
          divisionAlgebraOrder K (D := D) (y : D) =
              divisionAlgebraOrder K (D := D) (y : D) + 0 := (add_zero _).symm
          _ ≤ divisionAlgebraOrder K (D := D) (y : D) +
              divisionAlgebraOrder K (D := D) (a : D) :=
            add_le_add_right ha _))

omit [Algebra.IsCentral K D] in
@[simp]
theorem division_threshold_ideal (x y : OD K D) :
    y ∈ divisionThresholdIdeal K D x ↔
      divisionAlgebraOrder K (D := D) (x : D) ≤
        divisionAlgebraOrder K (D := D) (y : D) := by
  simp [divisionThresholdIdeal]

omit [Algebra.IsCentral K D] in
/-- An element of least order in a two-sided ideal generates that ideal. -/
theorem sided_singleton_minimal
    (J : TwoSidedIdeal (OD K D)) (x : OD K D)
    (hxJ : x ∈ J) (hx0 : (x : D) ≠ 0)
    (hmin : ∀ y : OD K D, y ∈ J → (y : D) ≠ 0 →
      divisionAlgebraOrder K (D := D) (x : D) ≤
        divisionAlgebraOrder K (D := D) (y : D)) :
    J = TwoSidedIdeal.span ({x} : Set (OD K D)) := by
  apply le_antisymm
  · intro y hyJ
    by_cases hy0 : (y : D) = 0
    · have : y = 0 := Subtype.ext hy0
      subst y
      exact TwoSidedIdeal.zero_mem _
    let ux : Dˣ := Units.mk0 (x : D) hx0
    let uy : Dˣ := Units.mk0 (y : D) hy0
    have hxy : divisionUnitOrder K D (Additive.ofMul ux) ≤
        divisionUnitOrder K D (Additive.ofMul uy) := by
      have h := hmin y hyJ hy0
      rw [division_ne_zero K (D := D) (x : D) hx0,
        division_ne_zero K (D := D) (y : D) hy0] at h
      exact WithTop.coe_le_coe.mp h
    let cD : D := (x : D)⁻¹ * (y : D)
    have hc0 : cD ≠ 0 := mul_ne_zero (inv_ne_zero hx0) hy0
    have hcunit : Units.mk0 cD hc0 = ux⁻¹ * uy := by
      apply Units.ext
      rfl
    have hcOrder : 0 ≤ divisionAlgebraOrder K (D := D) cD := by
      rw [division_ne_zero K (D := D) cD hc0, hcunit]
      change
        (0 : WithTop ℚ) ≤
          (divisionUnitOrder K D
            (-Additive.ofMul ux + Additive.ofMul uy) : ℚ)
      rw [map_add, map_neg, WithTop.coe_nonneg]
      simpa only [sub_eq_add_neg, add_comm] using sub_nonneg.mpr hxy
    let c : OD K D :=
      ⟨cD, (integer_subring_nonneg K D cD).2 hcOrder⟩
    have hxspan : x ∈ TwoSidedIdeal.span ({x} : Set (OD K D)) :=
      TwoSidedIdeal.subset_span (Set.mem_singleton x)
    have hmul := (TwoSidedIdeal.span ({x} : Set (OD K D))).mul_mem_right x c hxspan
    have hy_eq : y = x * c := by
      apply Subtype.ext
      change (y : D) = (x : D) * ((x : D)⁻¹ * (y : D))
      rw [← mul_assoc, mul_inv_cancel₀ hx0, one_mul]
    rw [hy_eq]
    exact hmul
  · rw [TwoSidedIdeal.span_le]
    intro y hy
    simpa only [Set.mem_singleton_iff] using hy ▸ hxJ

omit [Algebra.IsCentral K D] in
/-- The ideal generated by a nonzero integer is exactly its order-threshold
ideal. -/
theorem division_threshold_singleton
    (x : OD K D) (hx0 : (x : D) ≠ 0) :
    divisionThresholdIdeal K D x =
      TwoSidedIdeal.span ({x} : Set (OD K D)) := by
  apply sided_singleton_minimal K D
  · exact (division_threshold_ideal K D x x).2 le_rfl
  · exact hx0
  · intro y hy _
    exact (division_threshold_ideal K D x y).1 hy

omit [Algebra.IsCentral K D] in
/-- Membership in the principal ideal generated by a nonzero integer is
equivalent to the corresponding order inequality. -/
theorem span_singleton_order
    (x y : OD K D) (hx0 : (x : D) ≠ 0) :
    y ∈ TwoSidedIdeal.span ({x} : Set (OD K D)) ↔
      divisionAlgebraOrder K (D := D) (x : D) ≤
        divisionAlgebraOrder K (D := D) (y : D) := by
  rw [← division_threshold_singleton K D x hx0,
    division_threshold_ideal]

omit [Algebra.IsCentral K D] in
/-- A nonzero division-algebra integer has order `m / e` for a natural
number `m`, once the value group is identified with `(1 / e) * ℤ`. -/
theorem division_integer_numerator
    (e : ℕ) (he : 0 < e)
    (hrange : ∀ q : ℚ,
      q ∈ (divisionUnitOrder K D).range ↔
        ∃ z : ℤ, q = (z : ℚ) / (e : ℚ))
    (x : OD K D) (hx0 : (x : D) ≠ 0) :
    ∃ m : ℕ,
      divisionUnitOrder K D
          (Additive.ofMul (Units.mk0 (x : D) hx0)) =
        (m : ℚ) / (e : ℚ) := by
  let q := divisionUnitOrder K D
    (Additive.ofMul (Units.mk0 (x : D) hx0))
  have hqmem : q ∈ (divisionUnitOrder K D).range := by
    exact ⟨Additive.ofMul (Units.mk0 (x : D) hx0), rfl⟩
  obtain ⟨z, hz⟩ := (hrange q).1 hqmem
  have hqnonneg : 0 ≤ q := by
    have horder : 0 ≤ divisionAlgebraOrder K (D := D) (x : D) :=
      (integer_subring_nonneg K D (x : D)).1 x.property
    rw [division_ne_zero K (D := D) (x : D) hx0,
      WithTop.coe_nonneg] at horder
    exact horder
  have heQ : (0 : ℚ) < (e : ℚ) := by exact_mod_cast he
  have hznonnegQ : (0 : ℚ) ≤ (z : ℚ) := by
    rcases div_nonneg_iff.mp (hz ▸ hqnonneg) with h | h
    · exact h.1
    · exact (not_le_of_gt heQ h.2).elim
  have hznonneg : (0 : ℤ) ≤ z := by exact_mod_cast hznonnegQ
  refine ⟨z.toNat, ?_⟩
  change q = _
  rw [hz]
  congr 1
  exact_mod_cast (Int.toNat_of_nonneg hznonneg).symm

/-- Every nonzero two-sided ideal of the integer ring is both principal and
an order-threshold ideal.  The generator may be chosen to have the least
order among all nonzero elements of the ideal. -/
theorem nonzero_sided_threshold
    (J : TwoSidedIdeal (OD K D)) (hJ : J ≠ ⊥) :
    ∃ x : OD K D,
      x ∈ J ∧
      (x : D) ≠ 0 ∧
      J = divisionThresholdIdeal K D x ∧
      J = TwoSidedIdeal.span ({x} : Set (OD K D)) ∧
      ∀ y : OD K D, y ∈ J → (y : D) ≠ 0 →
        divisionAlgebraOrder K (D := D) (x : D) ≤
          divisionAlgebraOrder K (D := D) (y : D) := by
  classical
  obtain ⟨e, he, _, _, hrange⟩ := ramification_value_group K D
  let P : ℕ → Prop := fun m ↦
    ∃ x : OD K D,
      x ∈ J ∧
      ∃ hx0 : (x : D) ≠ 0,
        divisionUnitOrder K D
            (Additive.ofMul (Units.mk0 (x : D) hx0)) =
          (m : ℚ) / (e : ℚ)
  have hP : ∃ m, P m := by
    obtain ⟨x, hxJ, hx0⟩ :=
      SetLike.exists_of_lt (bot_lt_iff_ne_bot.mpr hJ :
        (⊥ : TwoSidedIdeal (OD K D)) < J)
    have hx0' : (x : D) ≠ 0 := by simpa using hx0
    obtain ⟨m, hm⟩ := division_integer_numerator K D e he hrange x hx0'
    exact ⟨m, x, hxJ, hx0', hm⟩
  let m := Nat.find hP
  obtain ⟨x, hxJ, hx0, hxOrder⟩ := Nat.find_spec hP
  have hmin : ∀ y : OD K D, y ∈ J → (y : D) ≠ 0 →
      divisionAlgebraOrder K (D := D) (x : D) ≤
        divisionAlgebraOrder K (D := D) (y : D) := by
    intro y hyJ hy0
    obtain ⟨k, hyOrder⟩ :=
      division_integer_numerator K D e he hrange y hy0
    have hkP : P k := ⟨y, hyJ, hy0, hyOrder⟩
    have hmk : m ≤ k := Nat.find_min' hP hkP
    rw [division_ne_zero K (D := D) (x : D) hx0,
      division_ne_zero K (D := D) (y : D) hy0]
    apply WithTop.coe_le_coe.mpr
    rw [hxOrder, hyOrder]
    have heQ : (0 : ℚ) < (e : ℚ) := by exact_mod_cast he
    rw [div_le_div_iff_of_pos_right heQ]
    exact_mod_cast hmk
  have hspan : J = TwoSidedIdeal.span ({x} : Set (OD K D)) :=
    sided_singleton_minimal K D J x hxJ hx0 hmin
  have hthreshold : J = divisionThresholdIdeal K D x := by
    rw [hspan, ← division_threshold_singleton K D x hx0]
  exact ⟨x, hxJ, hx0, hthreshold, hspan, hmin⟩

/-- The least-order generator of a nonzero ideal has order `m / e` for some
natural `m`, where the ramification index `e` divides the degree of `D`. -/
theorem nonzero_sided_numerator
    (J : TwoSidedIdeal (OD K D)) (hJ : J ≠ ⊥) :
    ∃ e : ℕ,
      0 < e ∧
      e ∣ Nat.sqrt (Module.finrank K D) ∧
      ∃ m : ℕ, ∃ x : OD K D,
        x ∈ J ∧
        ∃ hx0 : (x : D) ≠ 0,
          divisionUnitOrder K D
              (Additive.ofMul (Units.mk0 (x : D) hx0)) =
            (m : ℚ) / (e : ℚ) ∧
          J = divisionThresholdIdeal K D x ∧
          J = TwoSidedIdeal.span ({x} : Set (OD K D)) := by
  obtain ⟨x, hxJ, hx0, hthreshold, hspan, _⟩ :=
    nonzero_sided_threshold K D J hJ
  obtain ⟨e, he, hediv, _, hrange⟩ :=
    ramification_value_group K D
  obtain ⟨m, hm⟩ :=
    division_integer_numerator K D e he hrange x hx0
  exact ⟨e, he, hediv, m, x, hxJ, hx0, hm, hthreshold, hspan⟩

end

end Submission.CField.LBrauer
