import Submission.ClassField.NormLimitation.FiniteQuotients
import Submission.ClassField.NormLimitation.PrimeIndexSupergroup
import Submission.ClassField.NormLimitation.ExistenceStatement
import Submission.ClassField.NormLimitation.SubgroupQuotientMap
import Submission.ClassField.NormLimitation.OfGlobalReciprocity
import Submission.ClassField.NormLimitation.IsUnitOutside
import Submission.ClassField.NormLimitation.SubgroupIntermediate
import Submission.ClassField.NormLimitation.ExistenceInterface
import Submission.ClassField.NormLimitation.CoreDefinitions
import Submission.ClassField.NormLimitation.OpenCoreStatement
import Submission.ClassField.NormLimitation.KummerCoreStatement
import Submission.ClassField.NormLimitation.PlaceSelection
import Submission.ClassField.NormLimitation.ExponentGroupAssembly
import Submission.ClassField.NormLimitation.OpenCore
import Submission.ClassField.NormLimitation.KummerCore
import Submission.ClassField.NormLimitation.ExponentGroupReciprocity
import Submission.ClassField.NormLimitation.NormLimitationBridge
import Submission.ClassField.NormLimitation.NormLimitation
import Submission.ClassField.NormLimitation.ReductionData
import Submission.ClassField.NormLimitation.PrimeReduction
import Submission.ClassField.NormLimitation.GlobalReduction

/-! # Chapter VII, Section 9: the existence theorem -/
