import Mathlib.RingTheory.Polynomial.Eisenstein.Basic
import Mathlib.RingTheory.Polynomial.GaussLemma
import Mathlib.RingTheory.Ideal.Over
import Mathlib.RingTheory.Polynomial.Eisenstein.Distinguished
import Towers.NumberTheory.Ramification.KummerFactorization

/-!
# Milne, Algebraic Number Theory, Proposition 3.53: Eisenstein extensions

We record Eisenstein irreducibility and the ideal-theoretic containment underlying the
ramification assertion.  If `x` is a root of a monic polynomial Eisenstein at `p`, then its
degree-th power belongs to the extension of `p`.  Consequently, the degree-th power of the
ideal generated by the extension of `p` and `x` is contained in the extension of `p`.
-/

namespace Towers.NumberTheory.Milne

open Polynomial

attribute [local instance] Ideal.Quotient.field

/-- The irreducibility assertion of Proposition 3.53. -/
theorem eisenstein_irreducible
    {A : Type*} [CommRing A] [IsDomain A]
    {p : Ideal A} (hp : p.IsPrime)
    {f : A[X]} (hf : f.IsEisensteinAt p) (hmonic : f.Monic)
    (hdeg : 0 < f.natDegree) :
    Irreducible f := by
  exact hf.irreducible hp hmonic.isPrimitive hdeg

/-- The fraction-field formulation of Eisenstein irreducibility used in Milne's statement. -/
theorem eisenstein_irreducible_fraction
    {A K : Type*} [CommRing A] [IsDomain A] [IsIntegrallyClosed A]
    [Field K] [Algebra A K] [IsFractionRing A K]
    {p : Ideal A} (hp : p.IsPrime)
    {f : A[X]} (hf : f.IsEisensteinAt p) (hmonic : f.Monic)
    (hdeg : 0 < f.natDegree) :
    Irreducible (f.map (algebraMap A K)) := by
  exact hmonic.irreducible_iff_irreducible_map_fraction_map.mp
    (eisenstein_irreducible hp hf hmonic hdeg)

/-- A root of a monic Eisenstein polynomial has its degree-th power in the extended prime.
This is the basic ideal containment used in the proof of total ramification. -/
theorem nat_degree_eisenstein
    {A B : Type*} [CommRing A] [CommRing B] [Nontrivial B] [Algebra A B]
    {p : Ideal A} {f : A[X]} (hf : f.IsEisensteinAt p)
    (hmonic : f.Monic) {x : B} (hx : aeval x f = 0) :
    x ^ f.natDegree ∈ p.map (algebraMap A B) := by
  refine hf.isWeaklyEisensteinAt.pow_natDegree_le_of_aeval_zero_of_monic_mem_map
    hx hmonic f.natDegree ?_
  rw [hmonic.natDegree_map]

/-- If `x` is a root of a monic polynomial Eisenstein at `p`, then the degree-th power of
the ideal `(p, x)` is contained in the extension of `p`. -/
theorem root_degree_eisenstein
    {A B : Type*} [CommRing A] [CommRing B] [Nontrivial B] [Algebra A B]
    {p : Ideal A} {f : A[X]} (hf : f.IsEisensteinAt p)
    (hmonic : f.Monic) {x : B} (hx : aeval x f = 0) :
    (p.map (algebraMap A B) ⊔ Ideal.span {x}) ^ f.natDegree ≤
      p.map (algebraMap A B) := by
  let I := p.map (algebraMap A B)
  change (I ⊔ Ideal.span {x}) ^ f.natDegree ≤ I
  rw [← Ideal.mk_ker (I := I)]
  apply Ideal.le_comap_of_map_le
  rw [Ideal.map_pow, Ideal.map_sup, Ideal.map_span, Set.image_singleton]
  have hxpow : (Ideal.Quotient.mk I x) ^ f.natDegree = 0 := by
    rw [← map_pow]
    exact Ideal.Quotient.eq_zero_iff_mem.mpr
      (nat_degree_eisenstein hf hmonic hx)
  simpa [I, Ideal.span_singleton_pow] using hxpow

/-- The ideal `(p, x)` and the extended prime `pB` have the same radical.  Thus they have
exactly the same prime support; the remaining content of total ramification is the
multiplicity statement. -/
theorem radical_root_eisenstein
    {A B : Type*} [CommRing A] [CommRing B] [Nontrivial B] [Algebra A B]
    {p : Ideal A} {f : A[X]} (hf : f.IsEisensteinAt p)
    (hmonic : f.Monic) {x : B} (hx : aeval x f = 0) :
    (p.map (algebraMap A B) ⊔ Ideal.span {x}).radical =
      (p.map (algebraMap A B)).radical := by
  apply le_antisymm
  · rw [Ideal.radical_le_radical_iff]
    intro y hy
    refine ⟨f.natDegree, ?_⟩
    exact root_degree_eisenstein hf hmonic hx
      (Ideal.pow_mem_pow hy f.natDegree)
  · exact Ideal.radical_mono le_sup_left

/-- Every prime above `p` contains a root of a monic Eisenstein polynomial at `p`. -/
theorem lies_eisenstein
    {A B : Type*} [CommRing A] [CommRing B] [Nontrivial B] [Algebra A B]
    {p : Ideal A} {P : Ideal B} [P.IsPrime] [P.LiesOver p]
    {f : A[X]} (hf : f.IsEisensteinAt p) (hmonic : f.Monic)
    {x : B} (hx : aeval x f = 0) :
    x ∈ P := by
  apply (inferInstance : P.IsPrime).mem_of_pow_mem f.natDegree
  exact (Ideal.map_le_iff_le_comap.mpr Ideal.LiesOver.over.le)
    (nat_degree_eisenstein hf hmonic hx)

/-- Thus the ideal `(p, x)` is contained in every prime lying over `p`. -/
theorem root_lies_eisenstein
    {A B : Type*} [CommRing A] [CommRing B] [Nontrivial B] [Algebra A B]
    {p : Ideal A} {P : Ideal B} [P.IsPrime] [P.LiesOver p]
    {f : A[X]} (hf : f.IsEisensteinAt p) (hmonic : f.Monic)
    {x : B} (hx : aeval x f = 0) :
    p.map (algebraMap A B) ⊔ Ideal.span {x} ≤ P := by
  refine sup_le (Ideal.map_le_iff_le_comap.mpr Ideal.LiesOver.over.le) ?_
  exact Ideal.span_le.mpr (Set.singleton_subset_iff.mpr
    (lies_eisenstein hf hmonic hx))

open Algebra Ideal UniqueFactorizationMonoid

/-- Proposition 3.53 under the local maximality hypothesis required by Kummer--Dedekind.
It is enough that the conductor of `A[alpha]` be coprime to `p`; no global monogenicity of `B`
is required. -/
theorem eisenstein_conductor_coprime
    {A B : Type*} [CommRing A] [IsDedekindDomain A]
    [CommRing B] [IsDedekindDomain B] [Algebra A B]
    [Module.IsTorsionFree A B]
    {p : Ideal A} (hp : p.IsPrime) (hp0 : p ≠ ⊥)
    {alpha : B} (halpha_int : IsIntegral A alpha)
    (hcond : (conductor A alpha).comap (algebraMap A B) ⊔ p = ⊤)
    (hf : (minpoly A alpha).IsEisensteinAt p) :
    let P := p.map (algebraMap A B) ⊔ Ideal.span {alpha}
    P.IsPrime ∧
      p.map (algebraMap A B) = P ^ (minpoly A alpha).natDegree ∧
      Ideal.ramificationIdx p P = (minpoly A alpha).natDegree ∧
      ∀ Q : Ideal B, Q.IsPrime → Q.LiesOver p → Q = P := by
  classical
  letI : p.IsMaximal := hp.isMaximal hp0
  let F := minpoly A alpha
  let P := p.map (algebraMap A B) ⊔ Ideal.span {alpha}
  have hdeg : 0 < F.natDegree := minpoly.natDegree_pos halpha_int
  have hred : F.map (Ideal.Quotient.mk p) = X ^ F.natDegree := by
    exact (⟨hf.isWeaklyEisensteinAt, minpoly.monic halpha_int⟩ : F.IsDistinguishedAt p).map_eq_X_pow
  have hX : X ∈ normalizedFactors (F.map (Ideal.Quotient.mk p)) := by
    rw [hred, irreducible_X.normalizedFactors_pow]
    exact Multiset.mem_replicate.mpr ⟨hdeg.ne', monic_X.normalize_eq_self.symm⟩
  let E := KummerDedekind.normalizedFactorsMapEquivNormalizedFactorsMinPolyMk
    (x := alpha) (inferInstance : p.IsMaximal) hp0 hcond halpha_int
  let g : {d : (A ⧸ p)[X] | d ∈ normalizedFactors (F.map (Ideal.Quotient.mk p))} := ⟨X, hX⟩
  let P' : Ideal B := E.symm g
  have hP'mem : P' ∈ normalizedFactors (p.map (algebraMap A B)) := (E.symm g).prop
  have hmap0 : p.map (algebraMap A B) ≠ ⊥ := map_ne_bot_of_ne_bot hp0
  have hP'prime : P'.IsPrime := (Ideal.mem_normalizedFactors_iff hmap0).mp hP'mem |>.1
  have hP'eq : P' = P := by
    have heq :=
      KummerDedekind.normalizedFactorsMapEquivNormalizedFactorsMinPolyMk_symm_apply_eq_span
        (x := alpha) (Q := X) (inferInstance : p.IsMaximal) (by simpa [F] using hX)
        hp0 hcond halpha_int
    rw [Set.union_singleton, Ideal.span_insert, Ideal.span_eq, sup_comm] at heq
    simpa [P, P', E, g, F] using heq
  have hPprime : P.IsPrime := hP'eq ▸ hP'prime
  have hP0 : P ≠ ⊥ := by
    intro hP
    apply hmap0
    exact le_bot_iff.mp (le_trans le_sup_left (le_of_eq hP))
  have hram : Ideal.ramificationIdx p P = F.natDegree := by
    rw [Ideal.IsDedekindDomain.ramificationIdx_eq_multiplicity hmap0 hPprime]
    have hem := KummerDedekind.emultiplicity_factors_map_eq_emultiplicity
      (x := alpha) (inferInstance : p.IsMaximal) hp0 hcond halpha_int (E.symm g).prop
    rw [E.apply_symm_apply g] at hem
    have hem0 : emultiplicity P' (p.map (algebraMap A B)) =
        emultiplicity (X : (A ⧸ p)[X]) (F.map (Ideal.Quotient.mk p)) := by
      simpa [P', E, g, F] using hem
    rw [hP'eq, hred] at hem0
    have hmul := multiplicity_eq_of_emultiplicity_eq hem0
    rw [multiplicity_pow_self_of_prime (prime_X (R := A ⧸ p))] at hmul
    exact hmul
  have hunique : ∀ Q : Ideal B, Q.IsPrime → Q.LiesOver p → Q = P := by
    intro Q hQprime hQover
    letI : Q.IsPrime := hQprime
    letI : Q.LiesOver p := hQover
    have hPQ : P ≤ Q := root_lies_eisenstein
      hf (minpoly.monic halpha_int) (minpoly.aeval A alpha)
    exact (hPprime.isMaximal hP0).eq_of_le hQprime.ne_top hPQ |>.symm
  have hall : ∀ Q ∈ normalizedFactors (p.map (algebraMap A B)), Q = P := by
    intro Q hQ
    have hQdata := (Ideal.mem_normalizedFactors_iff hmap0).mp hQ
    letI : Q.IsPrime := hQdata.1
    have hQover : Q.LiesOver p :=
      (Ideal.mem_primesOver_iff_mem_normalizedFactors B hp0).mpr hQ |>.2
    exact hunique Q hQdata.1 hQover
  have hcount : (normalizedFactors (p.map (algebraMap A B))).count P = F.natDegree := by
    simpa [Ideal.IsDedekindDomain.ramificationIdx_eq_normalizedFactors_count
      hmap0 hPprime hP0] using hram
  have hfac : normalizedFactors (p.map (algebraMap A B)) =
      Multiset.replicate F.natDegree P := by
    have hcardForm := Multiset.eq_replicate_card.mpr hall
    have hcard : (normalizedFactors (p.map (algebraMap A B))).card = F.natDegree := by
      rw [hcardForm, Multiset.count_replicate_self] at hcount
      exact hcount
    exact Multiset.eq_replicate.mpr ⟨hcard, hall⟩
  have hpow : p.map (algebraMap A B) = P ^ F.natDegree := by
    rw [← Ideal.prod_normalizedFactors_eq_self hmap0, hfac, Multiset.prod_replicate]
  exact ⟨hPprime, hpow, hram, hunique⟩

/-- Proposition 3.53 under the explicit monogenic hypothesis on the integral closure.
The prime generated by `p` and the Eisenstein root is the unique prime above `p`, the extended
prime is its `deg f`-th power, and its ramification index is `deg f`. -/
theorem eisenstein_total_monic
    {A B : Type*} [CommRing A] [IsDedekindDomain A]
    [CommRing B] [IsDedekindDomain B] [Algebra A B]
    [Module.IsTorsionFree A B]
    {p : Ideal A} (hp : p.IsPrime) (hp0 : p ≠ ⊥)
    {f : A[X]} (hf : f.IsEisensteinAt p)
    (h : IsAdjoinRootMonic B f) :
    let P := p.map (algebraMap A B) ⊔ Ideal.span {h.root}
    P.IsPrime ∧
      p.map (algebraMap A B) = P ^ f.natDegree ∧
      Ideal.ramificationIdx p P = f.natDegree ∧
      ∀ Q : Ideal B, Q.IsPrime → Q.LiesOver p → Q = P := by
  classical
  letI : p.IsMaximal := hp.isMaximal hp0
  let P := p.map (algebraMap A B) ⊔ Ideal.span {h.root}
  have hdeg : 0 < f.natDegree := h.deg_pos
  have hirr : Irreducible f := eisenstein_irreducible hp hf h.monic hdeg
  have hmin : minpoly A h.root = f := h.minpoly_eq hirr
  have hred : f.map (Ideal.Quotient.mk p) = X ^ f.natDegree := by
    exact (⟨hf.isWeaklyEisensteinAt, h.monic⟩ : f.IsDistinguishedAt p).map_eq_X_pow
  have hX : X ∈ normalizedFactors ((minpoly A h.root).map (Ideal.Quotient.mk p)) := by
    rw [hmin, hred, irreducible_X.normalizedFactors_pow]
    exact Multiset.mem_replicate.mpr ⟨hdeg.ne', monic_X.normalize_eq_self.symm⟩
  let E := KummerDedekind.normalizedFactorsMapEquivNormalizedFactorsMinPolyMk
    (x := h.root) (inferInstance : p.IsMaximal) hp0
      (by
        rw [conductor_eq_top_iff_adjoin_eq_top.mpr h.adjoin_root_eq_top,
          Ideal.comap_top, top_sup_eq])
      h.isIntegral_root
  let g : {d : (A ⧸ p)[X] |
      d ∈ normalizedFactors ((minpoly A h.root).map (Ideal.Quotient.mk p))} := ⟨X, hX⟩
  let P' : Ideal B := E.symm g
  have hP'mem : P' ∈ normalizedFactors (p.map (algebraMap A B)) := (E.symm g).prop
  have hmap0 : p.map (algebraMap A B) ≠ ⊥ := map_ne_bot_of_ne_bot hp0
  have hP'prime : P'.IsPrime := (Ideal.mem_normalizedFactors_iff hmap0).mp hP'mem |>.1
  have hP'eq : P' = P := by
    have heq := GKDedeki.pair_adjoin_top
      hp0 h.adjoin_root_eq_top h.isIntegral_root
      (G := X) (by simpa using hX)
    rw [Set.union_singleton, Ideal.span_insert, Ideal.span_eq, sup_comm] at heq
    simpa [P, P', E, g] using heq
  have hPprime : P.IsPrime := hP'eq ▸ hP'prime
  have hP0 : P ≠ ⊥ := by
    intro hP
    apply hmap0
    exact le_bot_iff.mp (le_trans le_sup_left (le_of_eq hP))
  have hram : Ideal.ramificationIdx p P = f.natDegree := by
    rw [Ideal.IsDedekindDomain.ramificationIdx_eq_multiplicity hmap0 hPprime]
    have hem :=
      GKDedeki.emulti_minpo_top
        hp0 h.adjoin_root_eq_top h.isIntegral_root (G := X) (by simpa using hX)
    rw [Set.union_singleton, Ideal.span_insert, Ideal.span_eq, sup_comm] at hem
    have hem' : emultiplicity P (p.map (algebraMap A B)) =
        emultiplicity (X : (A ⧸ p)[X]) (X ^ f.natDegree) := by
      simpa [P, hmin, hred] using hem
    have hmul := multiplicity_eq_of_emultiplicity_eq hem'
    rw [multiplicity_pow_self_of_prime (prime_X (R := A ⧸ p))] at hmul
    exact hmul
  have hunique : ∀ Q : Ideal B, Q.IsPrime → Q.LiesOver p → Q = P := by
    intro Q hQprime hQover
    letI : Q.IsPrime := hQprime
    letI : Q.LiesOver p := hQover
    have hPQ : P ≤ Q := root_lies_eisenstein
      hf h.monic h.aeval_root_self
    exact (hPprime.isMaximal hP0).eq_of_le hQprime.ne_top hPQ |>.symm
  have hall : ∀ Q ∈ normalizedFactors (p.map (algebraMap A B)), Q = P := by
    intro Q hQ
    have hQdata := (Ideal.mem_normalizedFactors_iff hmap0).mp hQ
    have hQ0 : Q ≠ ⊥ := by
      intro hbot
      exact hmap0 (le_bot_iff.mp (hbot ▸ hQdata.2))
    letI : Q.IsPrime := hQdata.1
    have hQover : Q.LiesOver p := by
      exact (Ideal.mem_primesOver_iff_mem_normalizedFactors B hp0).mpr hQ |>.2
    exact hunique Q hQdata.1 hQover
  have hcount : (normalizedFactors (p.map (algebraMap A B))).count P = f.natDegree := by
    simpa [Ideal.IsDedekindDomain.ramificationIdx_eq_normalizedFactors_count
      hmap0 hPprime hP0] using hram
  have hfac : normalizedFactors (p.map (algebraMap A B)) =
      Multiset.replicate f.natDegree P := by
    have hcardForm := Multiset.eq_replicate_card.mpr hall
    have hcard : (normalizedFactors (p.map (algebraMap A B))).card = f.natDegree := by
      rw [hcardForm, Multiset.count_replicate_self] at hcount
      exact hcount
    exact Multiset.eq_replicate.mpr ⟨hcard, hall⟩
  have hpow : p.map (algebraMap A B) = P ^ f.natDegree := by
    rw [← Ideal.prod_normalizedFactors_eq_self hmap0, hfac, Multiset.prod_replicate]
  exact ⟨hPprime, hpow, hram, hunique⟩

end Towers.NumberTheory.Milne
