import Towers.Group.OpenRelators.Comparison


open scoped Topology

noncomputable section

namespace Towers
namespace ONObstr

open PRFact
open PRQuotie
open ONFact
open ONCompar

universe u w

variable
    {p : ℕ}
    {F G : Type u}
    [Group F]
    [TopologicalSpace F]
    [IsTopologicalGroup F]
    [Group G]
    {ι : Type w}
    {q : F →* G}
    {relator : ι → F}

/--
The canonical homomorphism from the ambient group to the relator quotient of one
open-normal finite layer.
-/
abbrev openNormalRelator
    (relator : ι → F)
    (N : OpenNormalSubgroup F) :
    F →* RelatorImageQuotient relator N :=
  (QuotientGroup.mk' (relatorImage relator N)).comp (openNormalLayer N)

omit [IsTopologicalGroup F] in
/--
The canonical finite-layer relator quotient kills every displayed relator.
-/
lemma open_kills_relators
    (relator : ι → F)
    (N : OpenNormalSubgroup F) :
    KillsRelators relator (openNormalRelator relator N) := by
  intro i
  apply (QuotientGroup.eq_one_iff
    (N := relatorImage relator N)
    (openNormalLayer N (relator i))).2
  exact ⟨relator i, relator_relation_subgroup relator i, rfl⟩

omit [IsTopologicalGroup F] in
/--
An ambient element dies in the canonical finite-layer relator quotient exactly
when its finite-layer image lies in the finite-layer relator image.
-/
lemma open_normal_kernel
    (relator : ι → F)
    (N : OpenNormalSubgroup F)
    (x : F) :
    x ∈ (openNormalRelator relator N).ker ↔
      openNormalLayer N x ∈ relatorImage relator N := by
  change
    QuotientGroup.mk' (relatorImage relator N) (openNormalLayer N x) = 1 ↔
      openNormalLayer N x ∈ relatorImage relator N
  exact QuotientGroup.eq_one_iff _

/--
A candidate-kernel image element in one finite layer that is not generated by
the finite-layer relator image.
-/
def ImageElementObstruction
    (q : F →* G)
    (relator : ι → F)
    (N : OpenNormalSubgroup F) :
    Prop :=
  ∃ z : kernelImage q N, (z : OpenNormalLayer N) ∉ relatorImage relator N

/--
An ambient candidate-kernel element whose image in one finite layer is not
generated by the finite-layer relator image.
-/
def KernelElementObstruction
    (q : F →* G)
    (relator : ι → F)
    (N : OpenNormalSubgroup F) :
    Prop :=
  ∃ x : F, x ∈ q.ker ∧ openNormalLayer N x ∉ relatorImage relator N

/--
A concrete surjective finite relator quotient together with one candidate-kernel
element that survives in it.
-/
structure RelatorKernelCounterexample
    (p : ℕ)
    (F G : Type u)
    [Group F]
    [TopologicalSpace F]
    [Group G]
    {ι : Type w}
    (relator : ι → F)
    (q : F →* G) where
  shadow : RQShadow p F relator
  witness : F
  witness_candidate_kernel : witness ∈ q.ker
  witness_not_shadow : witness ∉ shadow.map.ker

omit [IsTopologicalGroup F] in
/--
Failure of finite-layer candidate-kernel generation is exactly existence of a
finite-layer candidate-kernel-image obstruction.
-/
lemma element_obstruction_relator
    (q : F →* G)
    (relator : ι → F)
    (N : OpenNormalSubgroup F) :
    ImageElementObstruction q relator N ↔
      ¬ kernelImage q N ≤ relatorImage relator N := by
  constructor
  · rintro ⟨z, hznot⟩ hle
    exact hznot (hle z.property)
  · intro hnot
    rcases SetLike.not_le_iff_exists.mp hnot with ⟨z, hz, hznot⟩
    exact ⟨⟨z, hz⟩, hznot⟩

omit [IsTopologicalGroup F] in
/--
Finite-layer candidate-kernel-image obstructions and ambient candidate-kernel
element obstructions are equivalent presentations of the same failed layer.
-/
lemma image_element_obstruction
    (q : F →* G)
    (relator : ι → F)
    (N : OpenNormalSubgroup F) :
    ImageElementObstruction q relator N ↔
      KernelElementObstruction q relator N := by
  constructor
  · rintro ⟨⟨z, hz⟩, hznot⟩
    rcases hz with ⟨x, hx, rfl⟩
    exact ⟨x, hx, hznot⟩
  · rintro ⟨x, hx, hxnot⟩
    exact ⟨⟨openNormalLayer N x, ⟨x, hx, rfl⟩⟩, hxnot⟩

omit [IsTopologicalGroup F] in
/--
An ambient finite-layer obstruction is exactly a candidate-kernel element that
survives in the canonical finite-layer relator quotient.
-/
lemma element_obstruction_open
    (q : F →* G)
    (relator : ι → F)
    (N : OpenNormalSubgroup F) :
    KernelElementObstruction q relator N ↔
      ∃ x : F, x ∈ q.ker ∧ x ∉ (openNormalRelator relator N).ker := by
  simp only [KernelElementObstruction, open_normal_kernel]

omit [IsTopologicalGroup F] in
/--
Algebraic candidate-kernel generation fails in one open-normal finite layer
exactly when that layer contains a candidate-kernel-image obstruction.
-/
lemma algebraically_element_obstruction
    (q : F →* G)
    (relator : ι → F)
    (N : OpenNormalSubgroup F) :
    ¬ GeneratedAlgebraicallyOpen q relator N ↔
      ImageElementObstruction q relator N := by
  rw [ONCompar.algebraically_open_relator]
  exact element_obstruction_relator q relator N |>.symm

omit [IsTopologicalGroup F] in
/--
Algebraic candidate-kernel generation fails in one open-normal finite layer
exactly when an ambient candidate-kernel element survives in that layer's
canonical relator quotient.
-/
lemma not_algebraically_obstruction
    (q : F →* G)
    (relator : ι → F)
    (N : OpenNormalSubgroup F) :
    ¬ GeneratedAlgebraicallyOpen q relator N ↔
      KernelElementObstruction q relator N := by
  exact
    (algebraically_element_obstruction
      q relator N).trans
      (image_element_obstruction q relator N)

omit [IsTopologicalGroup F] in
/--
For a relator-killing candidate quotient, failure of the canonical finite-layer
comparison is exactly existence of a candidate-kernel-image obstruction.
-/
lemma obstruction_kills_relators
    (q : F →* G)
    (relator : ι → F)
    (N : OpenNormalSubgroup F)
    (hkill : KillsRelators relator q) :
    ¬ ImageComparisonIsomorphism q relator N hkill ↔
      ImageElementObstruction q relator N := by
  exact
    (not_congr
      (ONCompar.algebraically_iso_kills
        q relator N hkill)).symm.trans
      (algebraically_element_obstruction
        q relator N)

/--
For a pro-`p` source, the packaged canonical open-normal relator quotient has
the same kernel test as the explicit finite-layer relator quotient map.
-/
lemma algebraic_open_normal
    [CompactSpace F]
    (hProP : ProP.ProPGroup p F)
    (relator : ι → F)
    (N : OpenNormalSubgroup F)
    (x : F) :
    x ∈ (algebraicOpenNormal hProP N (relator := relator)).map.ker ↔
      x ∈ (openNormalRelator relator N).ker := by
  rw [ONFact.algebraic_open_relator]
  exact open_normal_kernel relator N x |>.symm

/--
An ambient finite-layer obstruction is exactly a candidate-kernel element that
survives in the packaged canonical finite `p`-group relator quotient.
-/
lemma element_obstruction_not
    [CompactSpace F]
    (hProP : ProP.ProPGroup p F)
    (q : F →* G)
    (relator : ι → F)
    (N : OpenNormalSubgroup F) :
    KernelElementObstruction q relator N ↔
      ∃ x : F, x ∈ q.ker ∧
        x ∉ (algebraicOpenNormal hProP N (relator := relator)).map.ker := by
  exact
    (element_obstruction_open
      q relator N).trans
      (exists_congr fun x => and_congr Iff.rfl
        ((not_congr
          (algebraic_open_normal
            hProP relator N x)).symm))

/--
A concrete open-normal finite-layer obstruction packages directly as an actual
surjective finite relator-killing `p`-group quotient counterexample.
-/
def relatorCounterexampleWitness
    [CompactSpace F]
    (hProP : ProP.ProPGroup p F)
    (q : F →* G)
    (relator : ι → F)
    (N : OpenNormalSubgroup F)
    (x : F)
    (hxker : x ∈ q.ker)
    (hxnot : openNormalLayer N x ∉ relatorImage relator N) :
    RelatorKernelCounterexample p F G relator q :=
  {
    shadow := algebraicOpenNormal hProP N
    witness := x
    witness_candidate_kernel := hxker
    witness_not_shadow :=
      (ONFact.algebraic_open_relator
        hProP N x).not.mpr hxnot
  }

/--
A concrete open-normal finite-layer obstruction gives an actual surjective
finite relator-killing `p`-group quotient counterexample.
-/
lemma counterexample_element_obstruction
    [CompactSpace F]
    (hProP : ProP.ProPGroup p F)
    (q : F →* G)
    (relator : ι → F)
    (N : OpenNormalSubgroup F)
    (hobs : KernelElementObstruction q relator N) :
    Nonempty (RelatorKernelCounterexample p F G relator q) := by
  rcases hobs with ⟨x, hxker, hxnot⟩
  exact ⟨relatorCounterexampleWitness hProP q relator N x hxker hxnot⟩

/--
For a pro-`p` source, failure of finite quotient relator factorization is
equivalent to one open-normal finite layer containing a candidate-kernel-image
obstruction.
-/
lemma property_image_pro
    [CompactSpace F]
    (hProP : ProP.ProPGroup p F)
    (q : F →* G)
    (relator : ι → F) :
    ¬ QuotientFactorizationProperty p relator q ↔
      ∃ N : OpenNormalSubgroup F, ImageElementObstruction q relator N := by
  rw [ONFact.property_every_pro
    hProP q]
  change (¬ ∀ N : OpenNormalSubgroup F,
    GeneratedAlgebraicallyOpen q relator N) ↔ _
  simp only [not_forall]
  exact exists_congr fun N =>
    algebraically_element_obstruction
      q relator N

/--
For a pro-`p` source, failure of finite quotient relator factorization is
equivalent to one ambient candidate-kernel element surviving in one canonical
open-normal finite-layer relator quotient.
-/
lemma property_obstruction_pro
    [CompactSpace F]
    (hProP : ProP.ProPGroup p F)
    (q : F →* G)
    (relator : ι → F) :
    ¬ QuotientFactorizationProperty p relator q ↔
      ∃ N : OpenNormalSubgroup F, KernelElementObstruction q relator N := by
  exact
    (property_image_pro
      hProP q relator).trans
      (exists_congr fun N => image_element_obstruction
        q relator N)

/--
For a pro-`p` source, failure of finite quotient relator factorization is
witnessed by one canonical packaged open-normal finite `p`-group relator
quotient and one candidate-kernel element surviving in it.
-/
lemma not_property_pro
    [CompactSpace F]
    (hProP : ProP.ProPGroup p F)
    (q : F →* G)
    (relator : ι → F) :
    ¬ QuotientFactorizationProperty p relator q ↔
      ∃ N : OpenNormalSubgroup F, ∃ x : F, x ∈ q.ker ∧
        x ∉ (algebraicOpenNormal hProP N (relator := relator)).map.ker := by
  exact
    (property_obstruction_pro
      hProP q relator).trans
      (exists_congr fun N =>
        element_obstruction_not
          hProP q relator N)

/--
For a pro-`p` source, failure of finite quotient relator factorization produces
an actual surjective finite relator-killing `p`-group quotient counterexample
chosen from the canonical open-normal relator quotient family.
-/
lemma counterexample_property_pro
    [CompactSpace F]
    (hProP : ProP.ProPGroup p F)
    (q : F →* G)
    (relator : ι → F)
    (hnot : ¬ QuotientFactorizationProperty p relator q) :
    Nonempty (RelatorKernelCounterexample p F G relator q) := by
  rcases (property_obstruction_pro
    hProP q relator).mp hnot with ⟨N, hobs⟩
  exact counterexample_element_obstruction
    hProP q relator N hobs

end ONObstr
end Towers
