import Mathlib.NumberTheory.NumberField.Discriminant.Different
import Mathlib.FieldTheory.Relrank
import Submission.NumberTheory.Dedekind.DedekindLocalizations
import Submission.NumberTheory.Globals.HermiteFiniteness

/-!
# Milne, Chapter 8, Theorem 8.42: the Hermite reduction

Milne deduces finiteness of fixed-degree extensions unramified outside a
finite set from two inputs.  The local finiteness theorem bounds the norm of
the relative different, and Hermite's theorem then gives the global
finiteness statement.

The pinned Mathlib contains the exact discriminant tower formula and
Hermite's theorem.  The Henselian-DVR bound is proved in
`LocalDifferentTowerBound`; this file proves the Hermite reduction and
isolates the remaining compatibility between completed local differents and
the localization of the global different.
-/

namespace Submission.NumberTheory.Milne

open NumberField
open scoped IntermediateField

/-- A number field embedded in a fixed characteristic-zero ambient field. -/
abbrev EmbeddedNumberField (A : Type*) [Field A] [CharZero A] :=
  {F : IntermediateField ℚ A // FiniteDimensional ℚ F}

section

variable (A : Type*) [Field A] [CharZero A]

/-- The absolute norm of the relative different of an inclusion of embedded
number fields. -/
noncomputable def relativeDifferentAbs
    (K L : EmbeddedNumberField A) (hKL : K.1 ≤ L.1) : ℕ := by
  letI : NumberField K := @NumberField.mk _ _ inferInstance K.prop
  letI : NumberField L := @NumberField.mk _ _ inferInstance L.prop
  letI : Algebra K L := RingHom.toAlgebra (IntermediateField.inclusion hKL)
  exact Ideal.absNorm
    (differentIdeal (NumberField.RingOfIntegers K) (NumberField.RingOfIntegers L))

/-- The absolute discriminant of an embedded number field, viewed as a
natural number. -/
noncomputable def embeddedDiscriminantAbs
    (K : EmbeddedNumberField A) : ℕ := by
  letI : NumberField K := @NumberField.mk _ _ inferInstance K.prop
  exact (discr K).natAbs

/-- The relative degree attached to an inclusion of embedded number fields. -/
noncomputable def embeddedRelativeDegree
    (K L : EmbeddedNumberField A) (hKL : K.1 ≤ L.1) : ℕ := by
  letI : Algebra K L := RingHom.toAlgebra (IntermediateField.inclusion hKL)
  exact Module.finrank K L

/-- An embedded extension is unramified outside `S` when every prime divisor
of its relative different lies over a prime in `S`.  By the different
criterion, this is equivalent to the usual local definition. -/
noncomputable def IsUnramifiedOutside
    (K L : EmbeddedNumberField A) (hKL : K.1 ≤ L.1)
    (S : Finset (Ideal (NumberField.RingOfIntegers K))) : Prop := by
  letI : NumberField K := @NumberField.mk _ _ inferInstance K.prop
  letI : NumberField L := @NumberField.mk _ _ inferInstance L.prop
  letI : Algebra K L := RingHom.toAlgebra (IntermediateField.inclusion hKL)
  exact ∀ P : Ideal (NumberField.RingOfIntegers L), Ideal.IsPrime P → P ≠ ⊥ →
    P ∣ differentIdeal
      (NumberField.RingOfIntegers K) (NumberField.RingOfIntegers L) →
      P.under (NumberField.RingOfIntegers K) ∈ S

/-- The product in `L` of the extensions of the primes in a prescribed
ramification set of `K`.  A local bound for the different is naturally
expressed by saying that the relative different divides a fixed power of
this ideal. -/
noncomputable def ramificationSupportIdeal
    (K L : EmbeddedNumberField A) (hKL : K.1 ≤ L.1)
    (S : Finset (Ideal (NumberField.RingOfIntegers K))) :
    Ideal (NumberField.RingOfIntegers L) := by
  letI : NumberField K := @NumberField.mk _ _ inferInstance K.prop
  letI : NumberField L := @NumberField.mk _ _ inferInstance L.prop
  letI : Algebra K L := RingHom.toAlgebra (IntermediateField.inclusion hKL)
  exact ∏ P ∈ S,
    P.map (algebraMap (NumberField.RingOfIntegers K)
      (NumberField.RingOfIntegers L))

/-- The explicit numerical bound obtained by taking the absolute norm of a
fixed power of `ramificationSupportIdeal`. -/
noncomputable def ramificationSupportBound
    (K L : EmbeddedNumberField A) (hKL : K.1 ≤ L.1)
    (S : Finset (Ideal (NumberField.RingOfIntegers K))) (m : ℕ) : ℕ := by
  letI : NumberField K := @NumberField.mk _ _ inferInstance K.prop
  exact (∏ P ∈ S, Ideal.absNorm P) ^
    (embeddedRelativeDegree A K L hKL * m)

/-- The support bound after fixing the relative degree. -/
noncomputable def fixedRamificationBound
    (K : EmbeddedNumberField A)
    (S : Finset (Ideal (NumberField.RingOfIntegers K))) (N m : ℕ) : ℕ := by
  letI : NumberField K := @NumberField.mk _ _ inferInstance K.prop
  exact (∏ P ∈ S, Ideal.absNorm P) ^ (N * m)

/-- The norm of a power of the ideal generated by the allowed ramification
support.  This wrapper installs the number-field structures carried by the
embedded fields. -/
noncomputable def ramificationSupportAbs
    (K L : EmbeddedNumberField A) (hKL : K.1 ≤ L.1)
    (S : Finset (Ideal (NumberField.RingOfIntegers K))) (m : ℕ) : ℕ := by
  letI : NumberField K := @NumberField.mk _ _ inferInstance K.prop
  letI : NumberField L := @NumberField.mk _ _ inferInstance L.prop
  exact Ideal.absNorm (ramificationSupportIdeal A K L hKL S ^ m)

/-- The ideal form of a uniform local different-exponent estimate. -/
noncomputable def DifferentDividesRamification
    (K L : EmbeddedNumberField A) (hKL : K.1 ≤ L.1)
    (S : Finset (Ideal (NumberField.RingOfIntegers K))) (m : ℕ) : Prop := by
  letI : NumberField K := @NumberField.mk _ _ inferInstance K.prop
  letI : NumberField L := @NumberField.mk _ _ inferInstance L.prop
  letI : Algebra K L := RingHom.toAlgebra (IntermediateField.inclusion hKL)
  exact differentIdeal (NumberField.RingOfIntegers K)
      (NumberField.RingOfIntegers L) ∣
    ramificationSupportIdeal A K L hKL S ^ m

/-- The relative different after localization at a prime of the upper
integer ring.  Packaging it as a definition lets the canonical algebra
structure associated to `hKL` remain internal. -/
noncomputable def localizedDifferent
    (K L : EmbeddedNumberField A) (hKL : K.1 ≤ L.1)
    (P : Ideal (NumberField.RingOfIntegers L)) [P.IsPrime] :
    Ideal (Localization.AtPrime P) := by
  letI : NumberField K := @NumberField.mk _ _ inferInstance K.prop
  letI : NumberField L := @NumberField.mk _ _ inferInstance L.prop
  letI : Algebra K L := RingHom.toAlgebra (IntermediateField.inclusion hKL)
  exact Ideal.map (algebraMap (NumberField.RingOfIntegers L)
      (Localization.AtPrime P))
    (differentIdeal (NumberField.RingOfIntegers K)
      (NumberField.RingOfIntegers L))

/-- The contraction of an upper prime along the inclusion `K ≤ L`. -/
noncomputable def contractedPrime
    (K L : EmbeddedNumberField A) (hKL : K.1 ≤ L.1)
    (P : Ideal (NumberField.RingOfIntegers L)) :
    Ideal (NumberField.RingOfIntegers K) := by
  letI : NumberField K := @NumberField.mk _ _ inferInstance K.prop
  letI : NumberField L := @NumberField.mk _ _ inferInstance L.prop
  letI : Algebra K L := RingHom.toAlgebra (IntermediateField.inclusion hKL)
  exact P.under (NumberField.RingOfIntegers K)

/-- The discriminant tower formula in the notation used for the embedded
extensions in Theorem 8.42. -/
theorem embedded_discriminant_different
    (K L : EmbeddedNumberField A) (hKL : K.1 ≤ L.1) :
    embeddedDiscriminantAbs A L = relativeDifferentAbs A K L hKL *
      embeddedDiscriminantAbs A K ^ embeddedRelativeDegree A K L hKL := by
  letI : NumberField K := @NumberField.mk _ _ inferInstance K.prop
  letI : NumberField L := @NumberField.mk _ _ inferInstance L.prop
  letI : Algebra K L := RingHom.toAlgebra (IntermediateField.inclusion hKL)
  exact NumberField.natAbs_discr_eq_absNorm_differentIdeal_mul_natAbs_discr_pow
    K (NumberField.RingOfIntegers K) L (NumberField.RingOfIntegers L)

/-- The absolute norm of the standard ideal supported on the allowed
ramified primes is independent of `L`, apart from the relative degree. -/
theorem abs_ramification_support
    (K L : EmbeddedNumberField A) (hKL : K.1 ≤ L.1)
    (S : Finset (Ideal (NumberField.RingOfIntegers K))) (m : ℕ) :
    ramificationSupportAbs A K L hKL S m =
      ramificationSupportBound A K L hKL S m := by
  letI : NumberField K := @NumberField.mk _ _ inferInstance K.prop
  letI : NumberField L := @NumberField.mk _ _ inferInstance L.prop
  letI : Algebra K L := RingHom.toAlgebra (IntermediateField.inclusion hKL)
  letI : Algebra (FractionRing (NumberField.RingOfIntegers K))
      (FractionRing (NumberField.RingOfIntegers L)) :=
    FractionRing.liftAlgebra _ _
  simp only [ramificationSupportAbs, ramificationSupportIdeal,
    ramificationSupportBound, map_pow, map_prod, Ideal.absNorm_algebraMap]
  have hdegree :
      Module.finrank (FractionRing (NumberField.RingOfIntegers K))
          (FractionRing (NumberField.RingOfIntegers L)) =
        embeddedRelativeDegree A K L hKL := by
    apply Algebra.finrank_eq_of_equiv_equiv
      (FractionRing.algEquiv (NumberField.RingOfIntegers K) K).toRingEquiv
      (FractionRing.algEquiv (NumberField.RingOfIntegers L) L).toRingEquiv
    ext x
    exact congrArg (fun y : L.1 => (y : A))
      (IsFractionRing.algEquiv_commutes
        (FractionRing.algEquiv (NumberField.RingOfIntegers K) K)
        (FractionRing.algEquiv (NumberField.RingOfIntegers L) L) x)
  rw [hdegree]
  simp only [← pow_mul, ← Finset.prod_pow]

/-- For one fixed extension, being unramified outside `S` already implies
that its different divides some power of the extended support ideal.  Thus
the genuinely local content needed in Theorem 8.42 is uniformity of this
exponent as the extension varies with fixed degree. -/
theorem different_dvd_ramification
    (K L : EmbeddedNumberField A) (hKL : K.1 ≤ L.1)
    (S : Finset (Ideal (NumberField.RingOfIntegers K)))
    (hunramified : IsUnramifiedOutside A K L hKL S) :
    ∃ m, DifferentDividesRamification A K L hKL S m := by
  letI : NumberField K := @NumberField.mk _ _ inferInstance K.prop
  letI : NumberField L := @NumberField.mk _ _ inferInstance L.prop
  letI : Algebra K L := RingHom.toAlgebra (IntermediateField.inclusion hKL)
  let D := differentIdeal (NumberField.RingOfIntegers K)
    (NumberField.RingOfIntegers L)
  let J := ramificationSupportIdeal A K L hKL S
  have hJrad : J ≤ D.radical := by
    rw [Ideal.radical_eq_sInf]
    refine le_sInf fun P hP => ?_
    rcases hP with ⟨hDP, hPprime⟩
    have hPbot : P ≠ ⊥ := by
      intro hPzero
      subst P
      exact differentIdeal_ne_bot (le_bot_iff.mp hDP)
    have hPdvdD : P ∣ D := Ideal.dvd_iff_le.mpr hDP
    have hPS : P.under (NumberField.RingOfIntegers K) ∈ S :=
      hunramified P hPprime hPbot hPdvdD
    have hPdvdMap : P ∣
        (P.under (NumberField.RingOfIntegers K)).map
          (algebraMap (NumberField.RingOfIntegers K)
            (NumberField.RingOfIntegers L)) := by
      rw [Ideal.dvd_iff_le, Ideal.map_le_iff_le_comap, Ideal.under_def]
    have hmapDvdJ :
        (P.under (NumberField.RingOfIntegers K)).map
            (algebraMap (NumberField.RingOfIntegers K)
              (NumberField.RingOfIntegers L)) ∣ J := by
      simpa only [J, ramificationSupportIdeal] using
        (Finset.dvd_prod_of_mem
          (s := S)
          (f := fun Q : Ideal (NumberField.RingOfIntegers K) =>
            Q.map (algebraMap (NumberField.RingOfIntegers K)
              (NumberField.RingOfIntegers L))) hPS)
    exact Ideal.dvd_iff_le.mp (dvd_trans hPdvdMap hmapDvdJ)
  obtain ⟨m, hm⟩ := Ideal.exists_pow_le_of_le_radical_of_fg hJrad
    (isNoetherian_def.mp inferInstance J)
  refine ⟨m, ?_⟩
  change D ∣ J ^ m
  exact Ideal.dvd_iff_le.mpr hm

/-- An ideal-theoretic local bound on the different implies the corresponding
numerical bound required by Hermite's theorem.  This is the precise global
step used after the local different-exponent estimate. -/
theorem relative_different_abs
    (K L : EmbeddedNumberField A) (hKL : K.1 ≤ L.1)
    (S : Finset (Ideal (NumberField.RingOfIntegers K))) (m : ℕ)
    (hS : ∀ P ∈ S, P ≠ ⊥)
    (hdifferent : DifferentDividesRamification A K L hKL S m) :
    relativeDifferentAbs A K L hKL ≤
      ramificationSupportBound A K L hKL S m := by
  letI : NumberField K := @NumberField.mk _ _ inferInstance K.prop
  letI : NumberField L := @NumberField.mk _ _ inferInstance L.prop
  letI : Algebra K L := RingHom.toAlgebra (IntermediateField.inclusion hKL)
  change differentIdeal (NumberField.RingOfIntegers K)
      (NumberField.RingOfIntegers L) ∣
    ramificationSupportIdeal A K L hKL S ^ m at hdifferent
  have hnormdvd :
      Ideal.absNorm
          (differentIdeal (NumberField.RingOfIntegers K)
            (NumberField.RingOfIntegers L)) ∣
        Ideal.absNorm (ramificationSupportIdeal A K L hKL S ^ m) :=
    map_dvd Ideal.absNorm hdifferent
  have hboundpos : 0 < ramificationSupportBound A K L hKL S m := by
    apply pow_pos
    exact Finset.prod_pos fun P hP =>
      Nat.pos_of_ne_zero ((Ideal.absNorm_eq_zero_iff).not.mpr (hS P hP))
  apply Nat.le_of_dvd hboundpos
  change relativeDifferentAbs A K L hKL ∣
    ramificationSupportAbs A K L hKL S m at hnormdvd
  rwa [abs_ramification_support A K L hKL S m] at hnormdvd

/-- The local-to-global ideal step in Milne's proof of Theorem 8.42.
To bound the relative different by the prescribed support ideal, it is
enough to prove the divisibility after localization at every nonzero prime
of the upper ring of integers. -/
theorem divide_ramif_local
    (K L : EmbeddedNumberField A) (hKL : K.1 ≤ L.1)
    (S : Finset (Ideal (NumberField.RingOfIntegers K))) (m : ℕ)
    (hlocal : ∀ (P : Ideal (NumberField.RingOfIntegers L)) (_ : P ≠ ⊥)
      [P.IsPrime],
      localizedDifferent A K L hKL P ∣
        Ideal.map (algebraMap (NumberField.RingOfIntegers L)
          (Localization.AtPrime P))
          (ramificationSupportIdeal A K L hKL S ^ m)) :
    DifferentDividesRamification A K L hKL S m := by
  letI : NumberField K := @NumberField.mk _ _ inferInstance K.prop
  letI : NumberField L := @NumberField.mk _ _ inferInstance L.prop
  letI : Algebra K L := RingHom.toAlgebra (IntermediateField.inclusion hKL)
  change differentIdeal (NumberField.RingOfIntegers K)
      (NumberField.RingOfIntegers L) ∣
    ramificationSupportIdeal A K L hKL S ^ m
  rw [Ideal.dvd_iff_le]
  apply (ideal_localization_nonzero
    (NumberField.RingOfIntegers L) (RingOfIntegers.not_isField L)
    (ramificationSupportIdeal A K L hKL S ^ m)
    (differentIdeal (NumberField.RingOfIntegers K)
      (NumberField.RingOfIntegers L))).mpr
  intro P hP _
  exact Ideal.dvd_iff_le.mp (hlocal P hP)

/-- In the localization criterion, primes outside the prescribed set need
no estimate: unramifiedness says that they do not divide the different, so
the different becomes the unit ideal after localization.  Consequently only
the primes lying over members of `S` carry local content. -/
theorem different_divides_localizations
    (K L : EmbeddedNumberField A) (hKL : K.1 ≤ L.1)
    (S : Finset (Ideal (NumberField.RingOfIntegers K))) (m : ℕ)
    (hunramified : IsUnramifiedOutside A K L hKL S)
    (hlocal : ∀ (P : Ideal (NumberField.RingOfIntegers L)) (_ : P ≠ ⊥)
      [P.IsPrime],
      contractedPrime A K L hKL P ∈ S →
        localizedDifferent A K L hKL P ∣
          Ideal.map (algebraMap (NumberField.RingOfIntegers L)
            (Localization.AtPrime P))
            (ramificationSupportIdeal A K L hKL S ^ m)) :
    DifferentDividesRamification A K L hKL S m := by
  letI : NumberField K := @NumberField.mk _ _ inferInstance K.prop
  letI : NumberField L := @NumberField.mk _ _ inferInstance L.prop
  letI : Algebra K L := RingHom.toAlgebra (IntermediateField.inclusion hKL)
  apply divide_ramif_local
    A K L hKL S m
  intro P hP _
  by_cases hPS : contractedPrime A K L hKL P ∈ S
  · exact hlocal P hP hPS
  · have hnotdvd : ¬ P ∣ differentIdeal
        (NumberField.RingOfIntegers K) (NumberField.RingOfIntegers L) := by
      intro hPdifferent
      exact hPS (hunramified P inferInstance hP hPdifferent)
    have hnotle : ¬ differentIdeal
        (NumberField.RingOfIntegers K) (NumberField.RingOfIntegers L) ≤ P := by
      simpa only [Ideal.dvd_iff_le] using hnotdvd
    change Ideal.map (algebraMap (NumberField.RingOfIntegers L)
      (Localization.AtPrime P))
      (differentIdeal (NumberField.RingOfIntegers K)
        (NumberField.RingOfIntegers L)) ∣ _
    rw [IsLocalization.AtPrime.map_eq_top_of_not_le
      (Localization.AtPrime P)
      (I := differentIdeal (NumberField.RingOfIntegers K)
        (NumberField.RingOfIntegers L)) (p := P) hnotle]
    simpa only [← Ideal.one_eq_top] using
      (one_dvd (Ideal.map (algebraMap (NumberField.RingOfIntegers L)
        (Localization.AtPrime P))
        (ramificationSupportIdeal A K L hKL S ^ m)))

/-- The Hermite step in Milne's Theorem 8.42: fixed relative degree and a
uniform bound on the norm of the relative different give only finitely many
embedded extensions. -/
theorem extensions_different_abs
    (K : EmbeddedNumberField A) (N B : ℕ) :
    {L : EmbeddedNumberField A |
      ∃ hKL : K.1 ≤ L.1,
        embeddedRelativeDegree A K L hKL = N ∧
          relativeDifferentAbs A K L hKL ≤ B}.Finite := by
  apply (NumberField.finite_of_discr_bdd A
    (B * embeddedDiscriminantAbs A K ^ N)).subset
  rintro L ⟨hKL, hdegree, hdifferent⟩
  letI : NumberField K := @NumberField.mk _ _ inferInstance K.prop
  letI : NumberField L := @NumberField.mk _ _ inferInstance L.prop
  have hnat : embeddedDiscriminantAbs A L ≤
      B * embeddedDiscriminantAbs A K ^ N := by
    rw [embedded_discriminant_different
      A K L hKL, hdegree]
    exact Nat.mul_le_mul_right (embeddedDiscriminantAbs A K ^ N) hdifferent
  change |discr L| ≤ (B * embeddedDiscriminantAbs A K ^ N : ℕ)
  rw [Int.abs_eq_natAbs]
  change (↑(embeddedDiscriminantAbs A L) : ℤ) ≤ _
  exact_mod_cast hnat

/-- Milne's Theorem 8.42 after isolating its unavailable local input.  Once
fixed degree and ramification support provide a uniform bound for the norm
of the relative different, Hermite gives finiteness of the corresponding
extensions. -/
theorem extensions_outside_different
    (K : EmbeddedNumberField A)
    (S : Finset (Ideal (NumberField.RingOfIntegers K))) (N B : ℕ)
    (hbound : ∀ L hKL,
      embeddedRelativeDegree A K L hKL = N →
      IsUnramifiedOutside A K L hKL S →
      relativeDifferentAbs A K L hKL ≤ B) :
    {L : EmbeddedNumberField A |
      ∃ hKL : K.1 ≤ L.1,
        embeddedRelativeDegree A K L hKL = N ∧
          IsUnramifiedOutside A K L hKL S}.Finite := by
  apply (extensions_different_abs A K N B).subset
  rintro L ⟨hKL, hdegree, hunramified⟩
  exact ⟨hKL, hdegree, hbound L hKL hdegree hunramified⟩

/-- Theorem 8.42 reduced to its standard local ideal estimate.  It is enough
to bound every local different exponent by one integer `m`: globally this
says that the different divides the `m`-th power of the product of the
extended primes in `S`.  The resulting Hermite bound is explicit. -/
theorem extensions_unramified_outside
    (K : EmbeddedNumberField A)
    (S : Finset (Ideal (NumberField.RingOfIntegers K))) (N m : ℕ)
    (hS : ∀ P ∈ S, P ≠ ⊥)
    (hlocal : ∀ L hKL,
      embeddedRelativeDegree A K L hKL = N →
      IsUnramifiedOutside A K L hKL S →
      DifferentDividesRamification A K L hKL S m) :
    {L : EmbeddedNumberField A |
      ∃ hKL : K.1 ≤ L.1,
        embeddedRelativeDegree A K L hKL = N ∧
          IsUnramifiedOutside A K L hKL S}.Finite := by
  apply extensions_outside_different
    A K S N (fixedRamificationBound A K S N m)
  intro L hKL hdegree hunramified
  have hle := relative_different_abs
    A K L hKL S m hS (hlocal L hKL hdegree hunramified)
  simpa only [ramificationSupportBound, fixedRamificationBound,
    hdegree] using hle

/-- Milne's local-discriminant proof packaged prime by prime.  A uniform
localized different bound is needed only at primes above `S`; the preceding
localization theorem assembles those bounds into the global support-ideal
bound used by Hermite. -/
theorem extensions_localized_different
    (K : EmbeddedNumberField A)
    (S : Finset (Ideal (NumberField.RingOfIntegers K))) (N m : ℕ)
    (hS : ∀ P ∈ S, P ≠ ⊥)
    (hlocal : ∀ L hKL,
      embeddedRelativeDegree A K L hKL = N →
      IsUnramifiedOutside A K L hKL S →
      ∀ (P : Ideal (NumberField.RingOfIntegers L)) (_ : P ≠ ⊥)
        [P.IsPrime],
        contractedPrime A K L hKL P ∈ S →
          localizedDifferent A K L hKL P ∣
            Ideal.map (algebraMap (NumberField.RingOfIntegers L)
              (Localization.AtPrime P))
              (ramificationSupportIdeal A K L hKL S ^ m)) :
    {L : EmbeddedNumberField A |
      ∃ hKL : K.1 ≤ L.1,
        embeddedRelativeDegree A K L hKL = N ∧
          IsUnramifiedOutside A K L hKL S}.Finite := by
  apply extensions_unramified_outside
    A K S N m hS
  intro L hKL hdegree hunramified
  exact different_divides_localizations
    A K L hKL S m hunramified (hlocal L hKL hdegree hunramified)

/-- A more directly local form of the preceding reduction.  At a prime
`P` above the allowed support, it is enough to bound the localized different
by a fixed power of the maximal ideal of `B_P`.  The localized support ideal
is contained in that maximal ideal, since one of its factors is the prime
contracted from `P`; hence the same exponent gives the support-ideal bound
required by Hermite. -/
theorem extensions_outside_localized
    (K : EmbeddedNumberField A)
    (S : Finset (Ideal (NumberField.RingOfIntegers K))) (N m : ℕ)
    (hS : ∀ P ∈ S, P ≠ ⊥)
    (hlocal : ∀ L hKL,
      embeddedRelativeDegree A K L hKL = N →
      IsUnramifiedOutside A K L hKL S →
      ∀ (P : Ideal (NumberField.RingOfIntegers L)) (_ : P ≠ ⊥)
        [P.IsPrime],
        contractedPrime A K L hKL P ∈ S →
          localizedDifferent A K L hKL P ∣
            (IsLocalRing.maximalIdeal (Localization.AtPrime P)) ^ m) :
    {L : EmbeddedNumberField A |
      ∃ hKL : K.1 ≤ L.1,
        embeddedRelativeDegree A K L hKL = N ∧
          IsUnramifiedOutside A K L hKL S}.Finite := by
  apply extensions_localized_different
    A K S N m hS
  intro L hKL hdegree hunramified P hP _ hPS
  letI : NumberField K := @NumberField.mk _ _ inferInstance K.prop
  letI : NumberField L := @NumberField.mk _ _ inferInstance L.prop
  letI : Algebra K L := RingHom.toAlgebra (IntermediateField.inclusion hKL)
  change P.under (NumberField.RingOfIntegers K) ∈ S at hPS
  let J := ramificationSupportIdeal A K L hKL S
  have hJleP : J ≤ P := by
    change (∏ Q ∈ S,
      Q.map (algebraMap (NumberField.RingOfIntegers K)
        (NumberField.RingOfIntegers L))) ≤ P
    refine Ideal.prod_le_inf.trans ((Finset.inf_le hPS).trans ?_)
    exact Ideal.map_le_iff_le_comap.mpr Ideal.LiesOver.over.le
  have hmapJ : J.map (algebraMap (NumberField.RingOfIntegers L)
      (Localization.AtPrime P)) ≤
      IsLocalRing.maximalIdeal (Localization.AtPrime P) := by
    exact (Ideal.map_mono hJleP).trans_eq
      (Localization.AtPrime.map_eq_maximalIdeal (I := P))
  rw [Ideal.dvd_iff_le]
  calc
    Ideal.map (algebraMap (NumberField.RingOfIntegers L)
        (Localization.AtPrime P)) (J ^ m) =
        J.map (algebraMap (NumberField.RingOfIntegers L)
          (Localization.AtPrime P)) ^ m := Ideal.map_pow _ J m
    _ ≤ (IsLocalRing.maximalIdeal (Localization.AtPrime P)) ^ m :=
      pow_le_pow_left' hmapJ m
    _ ≤ localizedDifferent A K L hKL P :=
      Ideal.dvd_iff_le.mp (hlocal L hKL hdegree hunramified P hP hPS)

/-- The everywhere-unramified case of Milne's Theorem 8.42 is
unconditional.  With empty ramification support, the support ideal is the
unit ideal, so the extension-dependent exponent supplied above is already a
uniform bound. -/
theorem extensions_outside_empty
    (K : EmbeddedNumberField A) (N : ℕ) :
    {L : EmbeddedNumberField A |
      ∃ hKL : K.1 ≤ L.1,
        embeddedRelativeDegree A K L hKL = N ∧
          IsUnramifiedOutside A K L hKL ∅}.Finite := by
  apply extensions_unramified_outside
    A K ∅ N 0
  · simp
  · intro L hKL _ hunramified
    obtain ⟨m, hm⟩ :=
      different_dvd_ramification A K L hKL ∅ hunramified
    simpa [DifferentDividesRamification,
      ramificationSupportIdeal, ← Ideal.one_eq_top] using hm

/-- Milne's Theorem 8.42 in relative degree one, without any local input.
An embedded extension of relative degree one is the base field itself, so
the collection is a subset of a singleton for every ramification set. -/
theorem extensions_outside_degree
    (K : EmbeddedNumberField A)
    (S : Finset (Ideal (NumberField.RingOfIntegers K))) :
    {L : EmbeddedNumberField A |
      ∃ hKL : K.1 ≤ L.1,
        embeddedRelativeDegree A K L hKL = 1 ∧
          IsUnramifiedOutside A K L hKL S}.Finite := by
  apply (Set.finite_singleton K).subset
  rintro L ⟨hKL, hdegree, _⟩
  have hrel : IntermediateField.relfinrank K.1 L.1 = 1 := by
    rw [IntermediateField.relfinrank_eq_finrank_of_le hKL]
    exact hdegree
  apply Subtype.ext
  exact le_antisymm
    (IntermediateField.relfinrank_eq_one_iff.mp hrel) hKL

end


end Submission.NumberTheory.Milne
