import Mathlib.Algebra.Order.Floor.Div
import Mathlib.GroupTheory.Commutator.Basic
import Towers.Group.PowerWidth.PowerSubgroups
import Towers.Group.Zassenhaus.MultiplicativelyDescending


/-!
# The recursively defined q-Zassenhaus filtration

This file develops the recursive filtration from Section 8 of
Efrat--Chapman and proves that it is decreasing.
-/

namespace EChapma

open Towers

variable {G : Type*} [Group G]

/-- The ambient normal subgroup generated by the `q`th powers of elements of `H`. -/
def subgroupPower (H : Subgroup G) (q : ℕ) : Subgroup G :=
  Subgroup.normalClosure {y | ∃ x ∈ H, x ^ q = y}

instance subgroupPower_normal (H : Subgroup G) (q : ℕ) :
    (subgroupPower H q).Normal := by
  unfold subgroupPower
  infer_instance

theorem pow_subgroup_power (H : Subgroup G) (q : ℕ)
    {x : G} (hx : x ∈ H) :
    x ^ q ∈ subgroupPower H q :=
  Subgroup.subset_normalClosure ⟨x, hx, rfl⟩

theorem subgroupPower_mono {H K : Subgroup G} (hHK : H ≤ K) (q : ℕ) :
    subgroupPower H q ≤ subgroupPower K q := by
  unfold subgroupPower
  apply Subgroup.normalClosure_le_normal
  rintro y ⟨x, hx, rfl⟩
  exact Subgroup.subset_normalClosure ⟨x, hHK hx, rfl⟩

/-- Taking an `(a * b)`th power factors through taking `a`th powers
and then `b`th powers. -/
theorem subgroup_power_mul
    (H : Subgroup G) (a b : ℕ) :
    subgroupPower H (a * b) ≤ subgroupPower (subgroupPower H a) b := by
  unfold subgroupPower
  apply Subgroup.normalClosure_le_normal
  rintro y ⟨x, hx, rfl⟩
  rw [pow_mul]
  exact pow_subgroup_power (subgroupPower H a) b
    (pow_subgroup_power H a hx)

/-- For a normal subgroup, the subgroup generated by first powers is
the subgroup itself. -/
@[simp]
theorem subgroupPower_one (H : Subgroup G) [H.Normal] :
    subgroupPower H 1 = H := by
  apply le_antisymm
  · unfold subgroupPower
    apply Subgroup.normalClosure_le_normal
    rintro y ⟨x, hx, rfl⟩
    simpa using hx
  · intro x hx
    simpa using pow_subgroup_power H 1 hx

theorem ceil_div_self
    (p n : ℕ) (hp : p.Prime) (hn : 2 ≤ n) :
    n ⌈/⌉ p < n := by
  have hceil : n ⌈/⌉ p ≤ n - 1 := by
    apply (ceilDiv_le_iff_le_mul hp.pos).mpr
    calc
      n ≤ 2 * (n - 1) := by omega
      _ ≤ p * (n - 1) := Nat.mul_le_mul_right (n - 1) hp.two_le
  exact hceil.trans_lt (by omega)

/-- The recursive `q`-Zassenhaus filtration from Section 8. -/
noncomputable def qZassenhausFiltration
    (G : Type*) [Group G] (p q : ℕ) (hp : p.Prime) :
    ℕ → Subgroup G
  | 0 => ⊤
  | 1 => ⊤
  | n + 2 =>
      subgroupPower
          (qZassenhausFiltration G p q hp ((n + 2) ⌈/⌉ p)) q ⊔
        ⨆ st : {st : ℕ × ℕ //
            1 ≤ st.1 ∧ 1 ≤ st.2 ∧ st.1 + st.2 = n + 2},
          ⁅qZassenhausFiltration G p q hp st.1.1,
            qZassenhausFiltration G p q hp st.1.2⁆
termination_by n => n
decreasing_by
  · exact ceil_div_self p (n + 2) hp (by omega)
  · omega
  · omega

@[simp]
theorem q_filtration_zero
    (p q : ℕ) (hp : p.Prime) :
    qZassenhausFiltration G p q hp 0 = ⊤ :=
  qZassenhausFiltration.eq_1 G p q hp

@[simp]
theorem q_filtration_one
    (p q : ℕ) (hp : p.Prime) :
    qZassenhausFiltration G p q hp 1 = ⊤ :=
  qZassenhausFiltration.eq_2 G p q hp

theorem q_filtration_succ
    (p q n : ℕ) (hp : p.Prime) :
    qZassenhausFiltration G p q hp (n + 2) =
      subgroupPower
          (qZassenhausFiltration G p q hp ((n + 2) ⌈/⌉ p)) q ⊔
        ⨆ st : {st : ℕ × ℕ //
            1 ≤ st.1 ∧ 1 ≤ st.2 ∧ st.1 + st.2 = n + 2},
          ⁅qZassenhausFiltration G p q hp st.1.1,
            qZassenhausFiltration G p q hp st.1.2⁆ :=
  qZassenhausFiltration.eq_3 G p q hp n

/-- Every commutator factor appearing in the recursive definition is
contained in the term indexed by the sum of its levels. -/
theorem q_filtration_commutator
    (p q s t : ℕ) (hp : p.Prime)
    (hs : 1 ≤ s) (ht : 1 ≤ t) :
    ⁅qZassenhausFiltration G p q hp s,
        qZassenhausFiltration G p q hp t⁆ ≤
      qZassenhausFiltration G p q hp (s + t) := by
  have hsum : 2 ≤ s + t := by omega
  obtain ⟨k, hk⟩ : ∃ k, s + t = k + 2 :=
    ⟨s + t - 2, by omega⟩
  rw [hk, q_filtration_succ]
  apply le_sup_right.trans'
  let st : {uv : ℕ × ℕ //
      1 ≤ uv.1 ∧ 1 ≤ uv.2 ∧ uv.1 + uv.2 = k + 2} :=
    ⟨(s, t), ⟨hs, ht, by omega⟩⟩
  apply le_iSup_of_le st
  rfl

/-- The recursive power factor sends level `m` into level `m p`. -/
theorem q_filtration_prime
    (p q m : ℕ) (hp : p.Prime) (hm : 1 ≤ m) :
    subgroupPower (qZassenhausFiltration G p q hp m) q ≤
      qZassenhausFiltration G p q hp (m * p) := by
  have hmp : 2 ≤ m * p := by
    nlinarith [hp.two_le]
  obtain ⟨k, hk⟩ : ∃ k, m * p = k + 2 :=
    ⟨m * p - 2, by omega⟩
  rw [hk, q_filtration_succ]
  apply le_sup_left.trans'
  have hceil : (m * p) ⌈/⌉ p = m := by
    rw [Nat.mul_comm]
    exact smul_ceilDiv hp.pos m
  simp [← hk, hceil]

/-- Every lower-central term lies in the q-Zassenhaus term with the same
one-based index. -/
theorem lower_q_filtration
    (p q : ℕ) (hp : p.Prime) (k : ℕ) :
    Subgroup.lowerCentralSeries G k ≤
      qZassenhausFiltration G p q hp (k + 1) := by
  induction k with
  | zero => simp
  | succ k ih =>
      rw [Subgroup.lowerCentralSeries_succ]
      exact
        (Subgroup.commutator_mono ih
          (show (⊤ : Subgroup G) ≤
            qZassenhausFiltration G p q hp 1 by simp)).trans
          (q_filtration_commutator p q (k + 1) 1 hp
            (by omega) le_rfl)

/-- Iterating the recursive q-power step sends the `q^j`th powers of
`γ_i(G)` into level `i p^j`. -/
theorem q_filtration_pow
    (p q i j : ℕ) (hp : p.Prime) (hi : 1 ≤ i) :
    subgroupPower (Subgroup.lowerCentralSeries G (i - 1)) (q ^ j) ≤
      qZassenhausFiltration G p q hp (i * p ^ j) := by
  induction j with
  | zero =>
      simp only [pow_zero, mul_one]
      rw [subgroupPower_one]
      simpa [Nat.sub_add_cancel hi] using
        lower_q_filtration
          (G := G) p q hp (i - 1)
  | succ j ih =>
      rw [pow_succ, show i * p ^ (j + 1) = (i * p ^ j) * p by
        rw [pow_succ]
        ac_rfl]
      exact
        (subgroup_power_mul
          (Subgroup.lowerCentralSeries G (i - 1)) (q ^ j) q).trans
          ((subgroupPower_mono ih q).trans
            (q_filtration_prime
              p q (i * p ^ j) hp
              (Nat.one_le_iff_ne_zero.mpr
                (mul_ne_zero (Nat.ne_of_gt hi)
                  (pow_ne_zero _ hp.ne_zero)))))

private theorem antitone_succ
    (Q : ℕ → Subgroup G) (N : ℕ)
    (hstep : ∀ m, 1 ≤ m → m < N → Q (m + 1) ≤ Q m)
    {a b : ℕ} (ha : 1 ≤ a) (hab : a ≤ b) (hbN : b ≤ N) :
    Q b ≤ Q a := by
  induction hab with
  | refl => exact le_rfl
  | @step b hab ih =>
      exact
        (hstep b (ha.trans hab) (Nat.lt_of_succ_le hbN)).trans
          (ih (Nat.le_of_succ_le hbN))

theorem one_ceil_div
    (p n : ℕ) (hp : p.Prime) (hn : 1 ≤ n) :
    1 ≤ n ⌈/⌉ p := by
  have hbound : n ≤ p * (n ⌈/⌉ p) :=
    (ceilDiv_le_iff_le_mul hp.pos).mp le_rfl
  by_contra h
  have hzero : n ⌈/⌉ p = 0 := Nat.eq_zero_of_not_pos h
  rw [hzero, mul_zero] at hbound
  omega

private theorem ceil_div_mono
    (p a b : ℕ) (hp : p.Prime) (hab : a ≤ b) :
    a ⌈/⌉ p ≤ b ⌈/⌉ p := by
  apply (ceilDiv_le_iff_le_mul hp.pos).mpr
  exact hab.trans ((ceilDiv_le_iff_le_mul hp.pos).mp le_rfl)

/-- Efrat--Chapman, Lemma 8.1: the recursive q-Zassenhaus filtration is decreasing. -/
theorem q_zassenhaus_succ
    (p q : ℕ) (hp : p.Prime) :
    ∀ n, 1 ≤ n →
      qZassenhausFiltration G p q hp (n + 1) ≤
        qZassenhausFiltration G p q hp n := by
  intro n
  induction n using Nat.strong_induction_on with
  | h n ih =>
      intro hn
      rcases n with (_ | _ | k)
      · omega
      · simp
      · rw [q_filtration_succ p q (k + 1) hp]
        rw [q_filtration_succ p q k hp]
        apply sup_le
        · have hceil :
              (k + 2) ⌈/⌉ p ≤ (k + 3) ⌈/⌉ p :=
            ceil_div_mono p (k + 2) (k + 3) hp (by omega)
          have hceil_bound : (k + 3) ⌈/⌉ p ≤ k + 2 :=
            by
              have := ceil_div_self p (k + 3) hp (by omega)
              omega
          have hlevels :
              qZassenhausFiltration G p q hp ((k + 3) ⌈/⌉ p) ≤
                qZassenhausFiltration G p q hp ((k + 2) ⌈/⌉ p) := by
            apply antitone_succ
                (qZassenhausFiltration G p q hp) (k + 2)
            · intro m hm hmk
              exact ih m (by omega) hm
            · exact one_ceil_div p (k + 2) hp (by omega)
            · exact hceil
            · exact hceil_bound
          exact
            (subgroupPower_mono hlevels q).trans <|
              le_sup_left
        · refine iSup_le ?_
          intro st
          apply le_sup_right.trans'
          by_cases hs : 2 ≤ st.1.1
          · let st' : {uv : ℕ × ℕ //
                1 ≤ uv.1 ∧ 1 ≤ uv.2 ∧ uv.1 + uv.2 = k + 2} :=
              ⟨(st.1.1 - 1, st.1.2), by
                rcases st.property with ⟨hs1, ht1, hsum⟩
                exact ⟨by omega, ht1, by omega⟩⟩
            have hsstep :
                qZassenhausFiltration G p q hp st.1.1 ≤
                  qZassenhausFiltration G p q hp (st.1.1 - 1) := by
              have hlt : st.1.1 - 1 < k + 2 := by
                rcases st.property with ⟨hs1, ht1, hsum⟩
                omega
              have hraw := ih (st.1.1 - 1) hlt (by omega)
              have heq : st.1.1 - 1 + 1 = st.1.1 :=
                Nat.sub_add_cancel (by omega)
              rw [heq] at hraw
              exact hraw
            exact
              (Subgroup.commutator_mono hsstep le_rfl).trans <|
                le_iSup (fun uv : {uv : ℕ × ℕ //
                  1 ≤ uv.1 ∧ 1 ≤ uv.2 ∧ uv.1 + uv.2 = k + 2} =>
                    ⁅qZassenhausFiltration G p q hp uv.1.1,
                      qZassenhausFiltration G p q hp uv.1.2⁆) st'
          · have hs1 : st.1.1 = 1 := by
              rcases st.property with ⟨hs1, ht1, hsum⟩
              omega
            let st' : {uv : ℕ × ℕ //
                1 ≤ uv.1 ∧ 1 ≤ uv.2 ∧ uv.1 + uv.2 = k + 2} :=
              ⟨(st.1.1, st.1.2 - 1), by
                rcases st.property with ⟨hspos, htpos, hsum⟩
                exact ⟨hspos, by omega, by omega⟩⟩
            have htstep :
                qZassenhausFiltration G p q hp st.1.2 ≤
                  qZassenhausFiltration G p q hp (st.1.2 - 1) := by
              have hlt : st.1.2 - 1 < k + 2 := by
                rcases st.property with ⟨hspos, htpos, hsum⟩
                omega
              have ht2 : 2 ≤ st.1.2 := by
                rcases st.property with ⟨hspos, htpos, hsum⟩
                omega
              have hraw := ih (st.1.2 - 1) hlt (by omega)
              have heq : st.1.2 - 1 + 1 = st.1.2 :=
                Nat.sub_add_cancel (by omega)
              rw [heq] at hraw
              exact hraw
            exact
              (Subgroup.commutator_mono le_rfl htstep).trans <|
                le_iSup (fun uv : {uv : ℕ × ℕ //
                  1 ≤ uv.1 ∧ 1 ≤ uv.2 ∧ uv.1 + uv.2 = k + 2} =>
                    ⁅qZassenhausFiltration G p q hp uv.1.1,
                      qZassenhausFiltration G p q hp uv.1.2⁆) st'

/-- The recursive q-Zassenhaus filtration is antitone on its positive
indices. -/
theorem q_filtration_antitone
    (p q : ℕ) (hp : p.Prime)
    {a b : ℕ} (ha : 1 ≤ a) (hab : a ≤ b) :
    qZassenhausFiltration G p q hp b ≤
      qZassenhausFiltration G p q hp a := by
  apply antitone_succ
    (qZassenhausFiltration G p q hp) b
  · intro m hm hmb
    exact q_zassenhaus_succ p q hp m hm
  · exact ha
  · exact hab
  · exact le_rfl

/-- The logarithmic closed-form product from Theorem 8.3. -/
noncomputable def logarithmicLowerProduct
    (p r : ℕ) (hp : p.Prime) (n : ℕ) : Subgroup G :=
  ⨆ i : {i : ℕ // 1 ≤ i ∧ i ≤ n},
    subgroupPower (Subgroup.lowerCentralSeries G (i.1 - 1))
      (MDescen.logarithmicPrimePower p r hp n i.1)

/-- The group-theoretic inclusion in Efrat--Chapman, Theorem 8.3:
the logarithmic lower-central product is contained in the recursively
defined q-Zassenhaus filtration for `q = p^r`. -/
theorem logarithmic_q_filtration
    (p r n : ℕ) (hp : p.Prime) :
    logarithmicLowerProduct (G := G) p r hp n ≤
      qZassenhausFiltration G p (p ^ r) hp n := by
  unfold logarithmicLowerProduct
  apply iSup_le
  intro i
  let j :=
    MDescen.ceilingLogExponent p hp n i.1
  rw [MDescen.logarithmic_prime_power, pow_mul]
  have hpower :=
    q_filtration_pow
      (G := G) p (p ^ r) i.1 j hp i.property.1
  exact hpower.trans <|
    q_filtration_antitone p (p ^ r) hp
      (i.property.1.trans i.property.2)
      (MDescen.mul_ceiling_log
        p hp n i.1 i.property.1)

end EChapma
