import Submission.ClassField.NormLimitation.OpenCoreStatement
import Submission.ClassField.NormLimitation.ExistenceInterface

/-! # The Kummer norm-core interface in Lemma VII.9.3 -/

namespace Submission.CField.NLimita

open NumberField
open Submission.CField.LFTheory
open Submission.CField.Ideles
open Submission.CField.Recip
open Submission.CField.NIndex
open Submission.CField.KNIndex

noncomputable section

universe u

/-- The Kummer-theoretic arithmetic core of Lemma 9.3. For the concrete
subgroup generated by `p`th powers and outside-`S` units, it constructs a
finite abelian norm group lying inside it. -/
def KummerCoreBridge : Prop :=
  ∀ (p : ℕ) (K : Type u) [Field K] [NumberField K],
    p.Prime → (primitiveRoots p K).Nonempty →
    ∀ S : Finset (NumberFieldPlace K),
      ContainsAllPlaces K S →
      (∀ v : NumberFieldPlace K,
        normalizedPlaceValue K v (p : K) ≠ 1 → v ∈ S) →
      CIGenera K S →
      ∃ L : FASubext K,
        ideleClassSubgroup L ≤ kummerCore K p S

end

end Submission.CField.NLimita
