import Towers.NumberTheory.TraceNorm.IntegralTraceNorm
import Towers.NumberTheory.Quadratic.QuadraticIntegerRings
import Towers.NumberTheory.Quadratic.BiquadraticIntegerRings
import Mathlib.NumberTheory.RamificationInertia.Basic


/-!
# Milne, Chapter 2, Exercise 6

The biquadratic field `Q(sqrt 7, sqrt 10)` is not monogenic.  We use nested
quadratic coordinates.  The four integers

`(1 plus-or-minus sqrt 7) * (1 plus-or-minus sqrt 10)`

become four nonzero orthogonal idempotents modulo `3`.  If the ring of
integers were generated by one element, its reduction modulo `3` would also
be generated by one element.  Multiplication by that generator has four
eigenvalues in a three-element field, which is impossible.
-/

namespace Towers.NumberTheory.Milne

open Polynomial NumberField
open Towers.NumberTheory

noncomputable section

attribute [-instance] DivisionRing.toRatAlgebra

/-- The evident integer order `Z[sqrt 7, sqrt 10]`. -/
abbrev NonmonogenicBiquadraticOrder :=
  QuadraticAlgebra (QuadraticAlgebra ℤ 7 0)
    (10 : QuadraticAlgebra ℤ 7 0) 0

/-- The nested coordinate model for `Q(sqrt 7, sqrt 10)`. -/
abbrev NonmonogenicBiquadraticField :=
  QuadraticAlgebra (QFModel 7)
    (10 : QFModel 7) 0

private theorem rat_sq_seven (q : ℚ) : q ^ 2 ≠ 7 := by
  intro h
  have hsquare : IsSquare (7 : ℚ) := ⟨q, by simpa [pow_two] using h.symm⟩
  norm_num at hsquare

private theorem rat_sq_ten (q : ℚ) : q ^ 2 ≠ 10 := by
  intro h
  have hsquare : IsSquare (10 : ℚ) := ⟨q, by simpa [pow_two] using h.symm⟩
  norm_num at hsquare

private theorem rat_seven_ten (q : ℚ) : 7 * q ^ 2 ≠ 10 := by
  intro h
  have hsquare : IsSquare (10 / 7 : ℚ) := ⟨q, by
    field_simp
    nlinarith⟩
  norm_num at hsquare

private local instance sqrtSeven_irreducible :
    Fact (∀ r : ℚ, r ^ 2 ≠ (7 : ℚ) + 0 * r) :=
  ⟨fun r hr ↦ rat_sq_seven r (by simpa using hr)⟩

private theorem no_ten_seven
    (r : QFModel 7) : r ^ 2 ≠ 10 := by
  intro hr
  have hre := congrArg QuadraticAlgebra.re hr
  have him := congrArg QuadraticAlgebra.im hr
  norm_num [pow_two, QuadraticAlgebra.re_mul, QuadraticAlgebra.im_mul,
    QuadraticAlgebra.re_ofNat, QuadraticAlgebra.im_ofNat] at hre him
  have hprod : r.re * r.im = 0 := by nlinarith
  rcases mul_eq_zero.mp hprod with hre0 | him0
  · rw [hre0] at hre
    exact rat_seven_ten r.im (by
      norm_num [pow_two, mul_assoc] at hre ⊢
      exact hre)
  · rw [him0] at hre
    exact rat_sq_ten r.re (by simpa [pow_two] using hre)

private local instance nonmonogenicBiquadraticbiquadratic_irreducible :
    Fact (∀ r : QFModel 7,
      r ^ 2 ≠ (10 : QFModel 7) + 0 * r) :=
  ⟨fun r hr ↦ no_ten_seven r (by simpa using hr)⟩

private local instance sqrtSeven_moduleFinite :
    Module.Finite ℚ (QFModel 7) :=
  Module.Finite.of_basis (QuadraticAlgebra.basis (7 : ℚ) 0)

private local instance nonmonogenicBiquadraticrelative_moduleFinite :
    Module.Finite (QFModel 7) NonmonogenicBiquadraticField :=
  Module.Finite.of_basis (QuadraticAlgebra.basis (10 : QFModel 7) 0)

private local instance nonmonogenicBiquadraticmoduleFinite :
    Module.Finite ℚ NonmonogenicBiquadraticField :=
  Module.Finite.trans (QFModel 7) NonmonogenicBiquadraticField

private local instance nonmonogenicBiquadraticnumberField :
    NumberField NonmonogenicBiquadraticField :=
  @NumberField.of_module_finite ℚ NonmonogenicBiquadraticField _ _ _ _
    nonmonogenicBiquadraticmoduleFinite

/-- The coordinatewise inclusion of the evident integer order. -/
def nonmonogenicBiquadraticEmbedding :
    NonmonogenicBiquadraticOrder →+* NonmonogenicBiquadraticField where
  toFun z :=
    ⟨QuadraticOrderEmbedding 7 z.re,
      QuadraticOrderEmbedding 7 z.im⟩
  map_zero' := by apply QuadraticAlgebra.ext <;> simp
  map_one' := by
    apply QuadraticAlgebra.ext
    · exact map_one (QuadraticOrderEmbedding 7)
    · exact map_zero (QuadraticOrderEmbedding 7)
  map_add' x y := by apply QuadraticAlgebra.ext <;> simp
  map_mul' x y := by
    apply QuadraticAlgebra.ext <;>
      apply QuadraticAlgebra.ext <;>
        simp [QuadraticAlgebra.re_mul, QuadraticAlgebra.im_mul,
          QuadraticOrderEmbedding,
          QuadraticAlgebra.re_ofNat, QuadraticAlgebra.im_ofNat]

theorem nonmon_biqua_injec :
    Function.Injective nonmonogenicBiquadraticEmbedding := by
  intro x y hxy
  apply QuadraticAlgebra.ext
  · exact quadratic_order_injective 7
      (congrArg QuadraticAlgebra.re hxy)
  · exact quadratic_order_injective 7
      (congrArg QuadraticAlgebra.im hxy)

private local instance innerOrder_moduleFinite :
    Module.Finite ℤ (QuadraticAlgebra ℤ 7 0) :=
  Module.Finite.of_basis (QuadraticAlgebra.basis 7 0)

private local instance order_relative_moduleFinite :
    Module.Finite (QuadraticAlgebra ℤ 7 0) NonmonogenicBiquadraticOrder :=
  Module.Finite.of_basis (QuadraticAlgebra.basis 10 0)

private local instance order_moduleFinite :
    Module.Finite ℤ NonmonogenicBiquadraticOrder :=
  Module.Finite.trans (QuadraticAlgebra ℤ 7 0) NonmonogenicBiquadraticOrder

private theorem orderElement_integral (z : NonmonogenicBiquadraticOrder) :
    IsIntegral ℤ (nonmonogenicBiquadraticEmbedding z) := by
  exact (Algebra.IsIntegral.isIntegral z).map nonmonogenicBiquadraticEmbedding.toIntAlgHom

/-- The integer `(1 + a*sqrt 7)(1 + b*sqrt 10)`, for signs `a,b`. -/
def AlphaOrder (a b : ℤ) : NonmonogenicBiquadraticOrder :=
  ⟨⟨1, a⟩, ⟨b, a * b⟩⟩

/-- The same integer in the number field. -/
def nonmonogenicBiquadraticAlpha (a b : ℤ) : NonmonogenicBiquadraticField :=
  nonmonogenicBiquadraticEmbedding (AlphaOrder a b)

theorem nonmonogenic_biquadratic_alpha (a b : ℤ) :
    IsIntegral ℤ (nonmonogenicBiquadraticAlpha a b) :=
  orderElement_integral _

/-- Milne's four integers, in the order displayed in the exercise. -/
def Alphas : Fin 4 → NonmonogenicBiquadraticField
  | 0 => nonmonogenicBiquadraticAlpha 1 1
  | 1 => nonmonogenicBiquadraticAlpha 1 (-1)
  | 2 => nonmonogenicBiquadraticAlpha (-1) 1
  | 3 => nonmonogenicBiquadraticAlpha (-1) (-1)

theorem Alphas_isIntegral (i : Fin 4) :
    IsIntegral ℤ (Alphas i) := by
  fin_cases i <;> exact nonmonogenic_biquadratic_alpha _ _

/-- The quotient `(alpha_i^2 - alpha_i) / 3` in the evident order. -/
def IdempotentQuotientOrder : Fin 4 → NonmonogenicBiquadraticOrder
  | 0 => ⟨⟨29, 7⟩, ⟨5, 1⟩⟩
  | 1 => ⟨⟨29, 7⟩, ⟨-5, -1⟩⟩
  | 2 => ⟨⟨29, -7⟩, ⟨5, -1⟩⟩
  | 3 => ⟨⟨29, -7⟩, ⟨-5, 1⟩⟩

theorem alphas_sq_self (i : Fin 4) :
    ∃ d : NonmonogenicBiquadraticField, IsIntegral ℤ d ∧
      Alphas i ^ 2 - Alphas i = 3 * d := by
  refine ⟨nonmonogenicBiquadraticEmbedding (IdempotentQuotientOrder i),
    orderElement_integral _, ?_⟩
  fin_cases i
  all_goals
    apply QuadraticAlgebra.ext <;>
      apply QuadraticAlgebra.ext <;>
        norm_num [Alphas, nonmonogenicBiquadraticAlpha, AlphaOrder,
          IdempotentQuotientOrder, nonmonogenicBiquadraticEmbedding,
          QuadraticOrderEmbedding, pow_two,
          QuadraticAlgebra.re_mul, QuadraticAlgebra.im_mul,
          QuadraticAlgebra.re_ofNat, QuadraticAlgebra.im_ofNat]

/-- The quotient of `alpha_i * alpha_j` by `3` for distinct indices. -/
def PairQuotientOrder : Fin 4 → Fin 4 → NonmonogenicBiquadraticOrder
  | 0, 1 | 1, 0 => ⟨⟨-24, -6⟩, 0⟩
  | 0, 2 | 2, 0 => ⟨⟨-22, 0⟩, ⟨-4, 0⟩⟩
  | 0, 3 | 3, 0 => 18
  | 1, 2 | 2, 1 => 18
  | 1, 3 | 3, 1 => ⟨⟨-22, 0⟩, ⟨4, 0⟩⟩
  | 2, 3 | 3, 2 => ⟨⟨-24, 6⟩, 0⟩
  | _, _ => 0

/-- Distinct displayed integers have product divisible by `3` in the ring of integers. -/
theorem alphas_divisible_three
    (i j : Fin 4) (hij : i ≠ j) :
    ∃ d : NonmonogenicBiquadraticField, IsIntegral ℤ d ∧
      Alphas i * Alphas j = 3 * d := by
  refine ⟨nonmonogenicBiquadraticEmbedding (PairQuotientOrder i j),
    orderElement_integral _, ?_⟩
  fin_cases i <;> fin_cases j <;> simp at hij
  all_goals
    apply QuadraticAlgebra.ext <;>
      apply QuadraticAlgebra.ext <;>
        norm_num [Alphas, nonmonogenicBiquadraticAlpha, AlphaOrder,
          PairQuotientOrder, nonmonogenicBiquadraticEmbedding,
          QuadraticOrderEmbedding,
          QuadraticAlgebra.re_mul, QuadraticAlgebra.im_mul,
          QuadraticAlgebra.re_ofNat, QuadraticAlgebra.im_ofNat]

/-- The four displayed integers sum to `4`. -/
theorem Alphas_sum : ∑ i, Alphas i = 4 := by
  rw [Fin.sum_univ_four]
  apply QuadraticAlgebra.ext <;>
    apply QuadraticAlgebra.ext <;>
      norm_num [Alphas, nonmonogenicBiquadraticAlpha, AlphaOrder,
        nonmonogenicBiquadraticEmbedding, QuadraticOrderEmbedding,
        QuadraticAlgebra.re_ofNat, QuadraticAlgebra.im_ofNat]

private theorem relative_trace (x : NonmonogenicBiquadraticField) :
    Algebra.trace (QFModel 7) NonmonogenicBiquadraticField x = 2 * x.re := by
  have hmat : Algebra.leftMulMatrix
      (QuadraticAlgebra.basis (10 : QFModel 7) 0) x =
      !![x.re, 10 * x.im; x.im, x.re] := by
    apply Matrix.ext
    intro i j
    fin_cases i <;> fin_cases j <;>
      apply QuadraticAlgebra.ext <;>
        simp [Algebra.leftMulMatrix_eq_repr_mul, QuadraticAlgebra.basis,
          QuadraticAlgebra.linearEquivTuple, QuadraticAlgebra.equivProd,
          QuadraticAlgebra.re_mul, QuadraticAlgebra.im_mul]
  rw [Algebra.trace_eq_matrix_trace
      (QuadraticAlgebra.basis (10 : QFModel 7) 0), hmat,
    Matrix.trace_fin_two_of]
  ring

private theorem inner_trace (x : QFModel 7) :
    Algebra.trace ℚ (QFModel 7) x = 2 * x.re := by
  have hmat : Algebra.leftMulMatrix (QuadraticAlgebra.basis (7 : ℚ) 0) x =
      !![x.re, 7 * x.im; x.im, x.re] := by
    apply Matrix.ext
    intro i j
    fin_cases i <;> fin_cases j <;>
      simp [Algebra.leftMulMatrix_eq_repr_mul, QuadraticAlgebra.basis,
        QuadraticAlgebra.linearEquivTuple, QuadraticAlgebra.equivProd,
        QuadraticAlgebra.re_mul, QuadraticAlgebra.im_mul]
  change Algebra.trace ℚ (QuadraticAlgebra ℚ 7 0) x = 2 * x.re
  rw [Algebra.trace_eq_matrix_trace (QuadraticAlgebra.basis (7 : ℚ) 0), hmat,
    Matrix.trace_fin_two_of]
  ring

/-- The absolute trace in nested coordinates. -/
theorem nonmonogenicBiquadratictrace (x : NonmonogenicBiquadraticField) :
    Algebra.trace ℚ NonmonogenicBiquadraticField x = 4 * x.re.re := by
  rw [← Algebra.trace_trace_of_basis
    (QuadraticAlgebra.basis (7 : ℚ) 0)
    (QuadraticAlgebra.basis (10 : QFModel 7) 0)]
  change Algebra.trace ℚ (QFModel 7)
      (Algebra.trace (QFModel 7) NonmonogenicBiquadraticField x) = 4 * x.re.re
  rw [relative_trace, inner_trace]
  simp only [QuadraticAlgebra.re_mul, QuadraticAlgebra.re_ofNat,
    QuadraticAlgebra.im_ofNat]
  ring

theorem Alphas_trace (i : Fin 4) :
    Algebra.trace ℚ NonmonogenicBiquadraticField (Alphas i) = 4 := by
  rw [nonmonogenicBiquadratictrace]
  fin_cases i <;>
    norm_num [Alphas, nonmonogenicBiquadraticAlpha, AlphaOrder,
      nonmonogenicBiquadraticEmbedding, QuadraticOrderEmbedding]

private theorem pow_congr_self
    (i : Fin 4) (n : ℕ) (hn : 0 < n) :
    ∃ d : NonmonogenicBiquadraticField, IsIntegral ℤ d ∧
      Alphas i ^ n = Alphas i + 3 * d := by
  have aux : ∀ m : ℕ, ∃ d : NonmonogenicBiquadraticField, IsIntegral ℤ d ∧
      Alphas i ^ (m + 1) = Alphas i + 3 * d := by
    intro m
    induction m with
    | zero => exact ⟨0, isIntegral_zero, by simp⟩
    | succ m ih =>
        obtain ⟨d, hdint, hd⟩ := ih
        obtain ⟨c, hcint, hc⟩ := alphas_sq_self i
        refine ⟨c + d * Alphas i,
          hcint.add (hdint.mul (Alphas_isIntegral i)), ?_⟩
        have hc' : Alphas i * Alphas i =
            Alphas i + 3 * c := by
          rw [← pow_two]
          linear_combination hc
        rw [Nat.succ_add, pow_succ, hd, add_mul, hc']
        ring
  obtain ⟨m, hm⟩ := Nat.exists_eq_add_of_le (Nat.succ_le_iff.mpr hn)
  subst n
  simpa [Nat.add_comm, Nat.add_left_comm, Nat.add_assoc] using aux m

/-- Exercise 2-6(a): no positive power of any `alpha_i` is divisible by `3`
in the ring of algebraic integers. -/
theorem alphas_no_divisible
    (i : Fin 4) (n : ℕ) (hn : 0 < n) :
    ¬ ∃ d : NonmonogenicBiquadraticField, IsIntegral ℤ d ∧
      Alphas i ^ n = 3 * d := by
  rintro ⟨d, hdint, hd⟩
  obtain ⟨c, hcint, hc⟩ := pow_congr_self i n hn
  obtain ⟨⟨zd, hzd⟩, -⟩ :=
    integral_norm_base ℤ ℚ NonmonogenicBiquadraticField hdint
  obtain ⟨⟨zc, hzc⟩, -⟩ :=
    integral_norm_base ℤ ℚ NonmonogenicBiquadraticField hcint
  have htraceD : Algebra.trace ℚ NonmonogenicBiquadraticField (Alphas i ^ n) =
      3 * Algebra.trace ℚ NonmonogenicBiquadraticField d := by
    rw [hd]
    rw [show (3 : NonmonogenicBiquadraticField) * d = (3 : ℚ) • d by
      simp [Algebra.smul_def]]
    simp [smul_eq_mul]
  have htraceC : Algebra.trace ℚ NonmonogenicBiquadraticField (Alphas i ^ n) =
      4 + 3 * Algebra.trace ℚ NonmonogenicBiquadraticField c := by
    rw [hc, map_add, Alphas_trace]
    congr 1
    rw [show (3 : NonmonogenicBiquadraticField) * c = (3 : ℚ) • c by
      simp [Algebra.smul_def]]
    simp [smul_eq_mul]
  change (zd : ℚ) = Algebra.trace ℚ NonmonogenicBiquadraticField d at hzd
  change (zc : ℚ) = Algebra.trace ℚ NonmonogenicBiquadraticField c at hzc
  rw [← hzd] at htraceD
  rw [← hzc] at htraceC
  have hZ : (3 : ℤ) * zd = 4 + 3 * zc := by
    exact_mod_cast htraceD.symm.trans htraceC
  omega

/-- The four displayed algebraic integers as elements of the full ring of integers. -/
def nonmonogenicAlphaInt (i : Fin 4) : RingOfIntegers NonmonogenicBiquadraticField :=
  ⟨Alphas i, Alphas_isIntegral i⟩

private theorem span_three
    (x : RingOfIntegers NonmonogenicBiquadraticField) :
    x ∈ (Ideal.span ({(3 : ℤ)} : Set ℤ)).map
        (algebraMap ℤ (RingOfIntegers NonmonogenicBiquadraticField)) ↔
      ∃ y : RingOfIntegers NonmonogenicBiquadraticField, x = 3 * y := by
  rw [Ideal.map_span, Set.image_singleton]
  constructor
  · intro hx
    obtain ⟨y, hy⟩ := Ideal.mem_span_singleton'.mp hx
    refine ⟨y, ?_⟩
    simpa [mul_comm] using hy.symm
  · rintro ⟨y, rfl⟩
    exact Ideal.mem_span_singleton'.mpr ⟨y, by simp [mul_comm]⟩

private theorem field_finrank :
    Module.finrank ℚ NonmonogenicBiquadraticField = 4 := by
  rw [← Module.finrank_mul_finrank ℚ (QFModel 7) NonmonogenicBiquadraticField,
    QuadraticAlgebra.finrank_eq_two, QuadraticAlgebra.finrank_eq_two]

private theorem polynomial_eigenvector
    {k A : Type*} [Field k] [CommRing A] [Algebra k A]
    (theta v : A) (lambda : k) (h : theta * v = lambda • v)
    (g : k[X]) :
    aeval theta g * v = aeval lambda g • v := by
  have hpow : ∀ n : ℕ, theta ^ n * v = lambda ^ n • v := by
    intro n
    induction n with
    | zero => simp
    | succ n ih =>
        calc
          theta ^ (n + 1) * v = theta ^ n * (theta * v) := by
            rw [pow_succ, mul_assoc]
          _ = theta ^ n * (lambda • v) := by rw [h]
          _ = lambda • (theta ^ n * v) := Algebra.mul_smul_comm _ _ _
          _ = lambda • (lambda ^ n • v) := by rw [ih]
          _ = lambda ^ (n + 1) • v := by
            rw [smul_smul, pow_succ]
            congr 1
            exact mul_comm _ _
  induction g using Polynomial.induction_on' with
  | add p q hp hq =>
      simp only [map_add, add_mul, hp, hq, add_smul]
  | monomial n a =>
      simp only [aeval_def, eval₂_monomial]
      rw [mul_assoc, hpow]
      simp [Algebra.smul_def, mul_left_comm, mul_comm]

set_option maxHeartbeats 800000 in
-- The quotient, basis, and polynomial-eigenvector argument elaborates a large tower of instances.
/-- Exercise 2-6: the full ring of integers of `Q(sqrt 7, sqrt 10)` is not
generated over `Z` by one algebraic integer. -/
theorem nonmonoge_monogeni
    (theta : RingOfIntegers NonmonogenicBiquadraticField) :
    Algebra.adjoin ℤ ({theta} : Set (RingOfIntegers NonmonogenicBiquadraticField)) ≠ ⊤ := by
  intro htheta
  let p : Ideal ℤ := Ideal.span ({(3 : ℤ)} : Set ℤ)
  let O := RingOfIntegers NonmonogenicBiquadraticField
  let P : Ideal O := p.map (algebraMap ℤ O)
  let k := ℤ ⧸ p
  let A := O ⧸ P
  letI : p.IsMaximal := Int.ideal_span_isMaximal_of_prime 3
  letI : Field k := Ideal.Quotient.field p
  letI : Fintype k := Fintype.ofFinite k
  let e : Fin 4 → A := fun i ↦ Ideal.Quotient.mk P (nonmonogenicAlphaInt i)
  have hfinrank : Module.finrank k A = 4 := by
    have hq := Ideal.finrank_quotient_map (R := ℤ) (S := O)
        (K := ℚ) (L := NonmonogenicBiquadraticField)
        (Ideal.span ({(3 : ℤ)} : Set ℤ))
    exact (by simpa [k, A, O, P, p] using hq.trans field_finrank)
  have he_ne (i : Fin 4) : e i ≠ 0 := by
    intro hi
    have hmem : nonmonogenicAlphaInt i ∈ P :=
      Ideal.Quotient.eq_zero_iff_mem.mp hi
    rw [show P = (Ideal.span ({(3 : ℤ)} : Set ℤ)).map
        (algebraMap ℤ O) by rfl,
      span_three] at hmem
    obtain ⟨y, hy⟩ := hmem
    apply alphas_no_divisible i 1 (by norm_num)
    refine ⟨(y : NonmonogenicBiquadraticField), y.property, ?_⟩
    simpa [nonmonogenicAlphaInt] using congrArg Subtype.val hy
  have he_sq (i : Fin 4) : e i * e i = e i := by
    obtain ⟨d, hdint, hd⟩ := alphas_sq_self i
    let dInt : O := ⟨d, hdint⟩
    rw [← sub_eq_zero, ← map_mul, ← map_sub]
    apply Ideal.Quotient.eq_zero_iff_mem.mpr
    rw [show P = (Ideal.span ({(3 : ℤ)} : Set ℤ)).map
        (algebraMap ℤ O) by rfl,
      span_three]
    refine ⟨dInt, ?_⟩
    apply Subtype.ext
    change Alphas i * Alphas i - Alphas i = 3 * d
    simpa [pow_two] using hd
  have he_mul (i j : Fin 4) (hij : i ≠ j) : e i * e j = 0 := by
    obtain ⟨d, hdint, hd⟩ := alphas_divisible_three i j hij
    let dInt : O := ⟨d, hdint⟩
    rw [← map_mul]
    apply Ideal.Quotient.eq_zero_iff_mem.mpr
    rw [show P = (Ideal.span ({(3 : ℤ)} : Set ℤ)).map
        (algebraMap ℤ O) by rfl,
      span_three]
    refine ⟨dInt, ?_⟩
    apply Subtype.ext
    exact hd
  have he_mul_ite (i j : Fin 4) : e i * e j = if i = j then e i else 0 := by
    split_ifs with hij
    · subst j
      exact he_sq i
    · exact he_mul i j hij
  have he_li : LinearIndependent k e := by
    rw [Fintype.linearIndependent_iff]
    intro g hg i
    have hmul : g i • e i = 0 := calc
      g i • e i = (∑ j, g j • e j) * e i := by
        rw [Finset.sum_mul]
        simp only [smul_mul_assoc, he_mul_ite, smul_ite, smul_zero,
          Finset.sum_ite_eq', Finset.mem_univ, if_true]
      _ = 0 := by rw [hg, zero_mul]
    exact (smul_eq_zero.mp hmul).resolve_right (he_ne i)
  let b : Module.Basis (Fin 4) k A :=
    basisOfLinearIndependentOfCardEqFinrank he_li (by simpa using hfinrank.symm)
  have hb (i : Fin 4) : b i = e i := by
    exact congrFun (coe_basisOfLinearIndependentOfCardEqFinrank he_li
      (by simpa using hfinrank.symm)) i
  let thetaBar : A := Ideal.Quotient.mk P theta
  let lambda : Fin 4 → k := fun i ↦ b.repr thetaBar i
  have heigen (i : Fin 4) : thetaBar * e i = lambda i • e i := by
    calc
      thetaBar * e i = (∑ j, b.repr thetaBar j • b j) * e i := by
        rw [b.sum_repr]
      _ = lambda i • e i := by
        rw [Finset.sum_mul]
        simp_rw [hb, smul_mul_assoc, he_mul_ite]
        simp [lambda]
  have hkcard : Fintype.card k = 3 := by
    change Fintype.card (ℤ ⧸ Ideal.span ({(3 : ℤ)} : Set ℤ)) = 3
    rw [← Nat.card_eq_fintype_card]
    exact (Nat.card_congr (Int.quotientSpanNatEquivZMod 3).toEquiv).trans
      (Nat.card_zmod 3)
  have hlambda_not_inj : ¬ Function.Injective lambda := by
    apply Fintype.not_injective_of_card_lt lambda
    simp [hkcard]
  obtain ⟨i, j, hlambda, hij⟩ := Function.not_injective_iff.mp hlambda_not_inj
  let PB : PowerBasis ℤ O :=
    PowerBasis.ofAdjoinEqTop' (Algebra.IsIntegral.isIntegral theta) htheta
  choose f hf using fun i ↦ PB.exists_eq_aeval' (nonmonogenicAlphaInt i)
  let g : Fin 4 → k[X] := fun i ↦ (f i).map (Ideal.Quotient.mk p)
  have hepoly (i : Fin 4) : e i = aeval thetaBar (g i) := by
    have hmap := congrArg (Ideal.Quotient.mk P) (hf i)
    rw [PowerBasis.ofAdjoinEqTop'_gen] at hmap
    have hcompat : (algebraMap k A).comp (Ideal.Quotient.mk p) =
        (Ideal.Quotient.mk P).comp (algebraMap ℤ O) := by
      ext z
      rfl
    simpa [e, thetaBar, g] using hmap.trans
      (map_aeval_eq_aeval_map hcompat (f i) theta)
  have hone : aeval (lambda i) (g i) = 1 := by
    have hmul := polynomial_eigenvector thetaBar (e i) (lambda i)
      (heigen i) (g i)
    rw [← hepoly i, he_sq] at hmul
    by_contra hne
    have hz : (aeval (lambda i) (g i) - 1) • e i = 0 := by
      rw [sub_smul, one_smul, ← hmul]
      exact sub_self _
    exact hne (sub_eq_zero.mp ((smul_eq_zero.mp hz).resolve_right (he_ne i)))
  have hzero : aeval (lambda j) (g i) = 0 := by
    have hmul := polynomial_eigenvector thetaBar (e j) (lambda j)
      (heigen j) (g i)
    rw [← hepoly i, he_mul i j hij] at hmul
    exact (smul_eq_zero.mp hmul.symm).resolve_right (he_ne j)
  rw [← hlambda] at hzero
  exact zero_ne_one (hzero.symm.trans hone)

end

end Towers.NumberTheory.Milne
