import Towers.ClassField.KummerNormIndex.KummerExtension
import Towers.ClassField.NormIndex.SplitAwayNorm
import Towers.ClassField.LocalGlobalPowers.LocalRootSplitting

/-!
# Local splitting for Proposition VII.6.10

If the radicand already has an `n`th root in a completion, the Kummer
polynomial splits there.  Since the global extension is generated by one
of its roots, every corresponding completed factor has degree one.
-/

namespace Towers.CField.KNIndex

open AbsoluteValue IsDedekindDomain NumberField Polynomial
open Towers.NumberTheory.Milne
open Towers.CField.Ideles
open Towers.CField.ICohomo
open Towers.CField.NIndex
open Towers.CField.LGPowers

noncomputable section

universe u

/-- The Proposition 6.10 radical data, viewed as the identical radical data
used by the later local-splitting theorem. -/
noncomputable def KEData.toData
    {K : Type u} [Field K] [NumberField K]
    {n : ℕ} {b : Kˣ} (data : KEData K n b) :
    REData K n b where
  L := data.L
  fieldL := data.fieldL
  numberFieldL := data.numberFieldL
  algebraKL := data.algebraKL
  finiteDimensionalKL := data.finiteDimensionalKL
  isGaloisKL := data.isGaloisKL
  isSolvableGal := data.isSolvableGal
  root := data.root
  root_pow := data.root_pow
  adjoin_root_top := data.adjoin_root_top

/-- A finite place where the radicand is locally an `n`th power splits
completely in the one-root Kummer extension. -/
theorem place_splits_completely
    (n : ℕ) (K : Type u) [Field K] [NumberField K] (b : Kˣ)
    (hroots : (primitiveRoots n K).Nonempty)
    (data : KEData K n b)
    (P : FinitePrime K)
    (hlocal : nthPowerPlace K n b (Sum.inl P)) :
    letI : Field data.L := data.fieldL
    letI : NumberField data.L := data.numberFieldL
    letI : Algebra K data.L := data.algebraKL
    letI : FiniteDimensional K data.L := data.finiteDimensionalKL
    letI : IsGalois K data.L := data.isGaloisKL
    SplitsCompletelyAt K data.L P := by
  letI : Field data.L := data.fieldL
  letI : NumberField data.L := data.numberFieldL
  letI : Algebra K data.L := data.algebraKL
  letI : FiniteDimensional K data.L := data.finiteDimensionalKL
  letI : IsGalois K data.L := data.isGaloisKL
  exact splits_completely_completion K data.L P
    (local_splits_completely n K b data.toData P
      hroots hlocal)

set_option maxHeartbeats 4000000 in
-- The infinite-place splitting comparison transports the radical extension
-- through normalized completions and their local degree formulas.
set_option synthInstance.maxHeartbeats 1000000 in
/-- At an infinite place where the radicand is an `n`th power, every
completed factor of the radical extension has degree one. -/
theorem infinite_completion_finrank
    (n : ℕ) (K : Type u) [Field K] [NumberField K] (b : Kˣ)
    (hroots : (primitiveRoots n K).Nonempty)
    (data : KEData K n b)
    (v : InfinitePlace K)
    (hlocal : nthPowerPlace K n b (Sum.inr v)) :
    letI : Field data.L := data.fieldL
    letI : NumberField data.L := data.numberFieldL
    letI : Algebra K data.L := data.algebraKL
    letI : FiniteDimensional K data.L := data.finiteDimensionalKL
    ∀ (w : InfinitePlacesAbove (K := K) (L := data.L) v),
    letI : Algebra v.1.Completion w.1.1.Completion :=
      (completionLies v.1 w.1.1
        (infinite_lies_comap v w.1 w.2)).toAlgebra
    Module.finrank v.1.Completion w.1.1.Completion = 1 := by
  letI : Field data.L := data.fieldL
  letI : NumberField data.L := data.numberFieldL
  letI : Algebra K data.L := data.algebraKL
  letI : FiniteDimensional K data.L := data.finiteDimensionalKL
  intro w
  letI : Fact v.1.IsNontrivial := ⟨infinite_place_nontrivial v⟩
  have hn : n ≠ 0 := by
    intro hn
    subst n
    simp [primitiveRoots_zero] at hroots
  let F := v.Completion
  letI : Algebra F w.1.Completion :=
    (completionLies v.1 w.1.1
      (infinite_lies_comap v w.1 w.2)).toAlgebra
  letI : FiniteDimensional F w.1.Completion :=
    infinite_completion_module (K := K) (L := data.L) v w
  obtain ⟨x, hx⟩ := hlocal
  have hxF : x ^ n = completionEmbedding v.1 (b : K) := by
    simpa only [show algebraMap K F (b : K) = completionEmbedding v.1 (b : K)
      from rfl] using hx
  let zetaF : F := completionEmbedding v.1 hroots.choose
  have hzetaF : IsPrimitiveRoot zetaF n :=
    ((mem_primitiveRoots (Nat.pos_of_ne_zero hn)).mp
      hroots.choose_spec).map_of_injective (completionEmbedding v.1).injective
  let q : F[X] := X ^ n - C (completionEmbedding v.1 (b : K))
  have hqsplit : q.Splits := radical_splits_root hzetaF hxF
  have hq0 : q ≠ 0 :=
    (monic_X_pow_sub_C (completionEmbedding v.1 (b : K)) hn).ne_zero
  let y : w.1.Completion := completionEmbedding w.1.1 data.root
  have hbase (c : K) :
      algebraMap F w.1.Completion (completionEmbedding v.1 c) =
        completionEmbedding w.1.1 (algebraMap K data.L c) :=
    RingHom.congr_fun (completion_lies_comp v.1 w.1.1
      (infinite_lies_comap v w.1 w.2)) c
  have hy : y ^ n =
      algebraMap F w.1.Completion (completionEmbedding v.1 (b : K)) := by
    calc
      y ^ n = completionEmbedding w.1.1 (data.root ^ n) := by rw [map_pow]
      _ = completionEmbedding w.1.1 (algebraMap K data.L (b : K)) := by
        rw [data.root_pow]
      _ = algebraMap F w.1.Completion (completionEmbedding v.1 (b : K)) :=
        (hbase (b : K)).symm
  have hqeval : aeval y q = 0 := by simp [q, hy]
  have hmindvd : minpoly F y ∣ q := minpoly.dvd F y hqeval
  have hminsplit : (minpoly F y).Splits := hqsplit.of_dvd hq0 hmindvd
  have hyint : IsIntegral F y := IsIntegral.of_finite F y
  have hmindeg : (minpoly F y).natDegree = 1 :=
    hminsplit.natDegree_eq_one_of_irreducible (minpoly.irreducible hyint)
  have hgen : Algebra.adjoin K {data.root} = ⊤ := by
    have h := congrArg IntermediateField.toSubalgebra data.adjoin_root_top
    simpa [IntermediateField.adjoin_toSubalgebra_of_isAlgebraic
      (fun z _ ↦ IsAlgebraic.of_finite K z)] using h
  let ew := completionAdjoinMinpoly v.1 data.root hgen
    ⟨w.1.1, infinite_lies_comap v w.1 w.2⟩
  calc
    Module.finrank F w.1.Completion =
        Module.finrank F (AdjoinRoot (minpoly F y)) :=
      ew.toLinearEquiv.finrank_eq.symm
    _ = (minpoly F y).natDegree := by
      let pbw := AdjoinRoot.powerBasis
        (show minpoly F y ≠ 0 from (minpoly.irreducible hyint).ne_zero)
      rw [pbw.finrank, AdjoinRoot.powerBasis_dim]
    _ = 1 := hmindeg

/-- At a split infinite completion, the completed norm is onto. -/
theorem infinite_completion_surjective
    (n : ℕ) (K : Type u) [Field K] [NumberField K] (b : Kˣ)
    (hroots : (primitiveRoots n K).Nonempty)
    (data : KEData K n b)
    (v : InfinitePlace K)
    (hlocal : nthPowerPlace K n b (Sum.inr v)) :
    letI : Field data.L := data.fieldL
    letI : NumberField data.L := data.numberFieldL
    letI : Algebra K data.L := data.algebraKL
    letI : FiniteDimensional K data.L := data.finiteDimensionalKL
    ∀ (w : InfinitePlacesAbove (K := K) (L := data.L) v),
    Function.Surjective
      (infiniteCompletionNorm (K := K) (L := data.L) v w) := by
  letI : Field data.L := data.fieldL
  letI : NumberField data.L := data.numberFieldL
  letI : Algebra K data.L := data.algebraKL
  letI : FiniteDimensional K data.L := data.finiteDimensionalKL
  intro w
  letI : Algebra v.1.Completion w.1.1.Completion :=
    (completionLies v.1 w.1.1
      (infinite_lies_comap v w.1 w.2)).toAlgebra
  letI : Module.Finite v.1.Completion w.1.1.Completion :=
    infinite_completion_module (K := K) (L := data.L) v w
  letI : Module.Free v.1.Completion w.1.1.Completion :=
    Module.Free.of_divisionRing v.1.Completion w.1.1.Completion
  intro x
  let y : w.1.Completionˣ := Units.map
    (algebraMap v.1.Completion w.1.1.Completion).toMonoidHom x
  refine ⟨y, ?_⟩
  apply Units.ext
  change Algebra.norm v.1.Completion
      (algebraMap v.1.Completion w.1.1.Completion (x : v.1.Completion)) = x
  rw [Algebra.norm_algebraMap,
    infinite_completion_finrank
      n K b hroots data v hlocal w, pow_one]

/-- Surjectivity of one completed infinite norm supplies a norm lift
supported at that upper place. -/
theorem infinite_lift_surjective
    {K L : Type u} [Field K] [Field L]
    [NumberField K] [NumberField L] [Algebra K L]
    [FiniteDimensional K L]
    (v : InfinitePlace K)
    (w : InfinitePlacesAbove (K := K) (L := L) v)
    (hsurjective : Function.Surjective
      (infiniteCompletionNorm (K := K) (L := L) v w))
    (x : v.Completionˣ) : InfiniteNormLift K L v x := by
  classical
  obtain ⟨y, hy⟩ := hsurjective x
  let z : ∀ q : InfinitePlace L, q.Completionˣ :=
    Pi.mulSingle (M := fun q : InfinitePlace L ↦ q.Completionˣ) w.1 y
  refine ⟨z, ?_, ?_⟩
  · intro q hq
    apply Pi.mulSingle_eq_of_ne
      (M := fun q : InfinitePlace L ↦ q.Completionˣ)
    intro hqw
    apply hq
    rw [hqw, w.2]
  · rw [Finset.prod_eq_single w]
    · change infiniteCompletionNorm (K := K) (L := L) v w (z w.1) = x
      rw [show z w.1 = y from Pi.mulSingle_eq_same
        (M := fun q : InfinitePlace L ↦ q.Completionˣ) w.1 y]
      exact hy
    · intro q _ hq
      have hUpper : q.1 ≠ w.1 := by
        intro h
        exact hq (Subtype.ext h)
      change infiniteCompletionNorm (K := K) (L := L) v q (z q.1) = 1
      rw [show z q.1 = 1 from Pi.mulSingle_eq_of_ne
        (M := fun q : InfinitePlace L ↦ q.Completionˣ) hUpper y]
      exact map_one _
    · intro hw
      exact (hw (by simp)).elim

end

end Towers.CField.KNIndex
