import Towers.Group.FiniteContinuousShadows


open scoped Topology

noncomputable section

namespace Towers
namespace PRFact

open PCShadow

universe u

/-- A homomorphism kills a displayed relator family pointwise. -/
def KillsRelators
    {F P : Type u}
    [Group F]
    [Group P]
    {ι : Type*}
    (relator : ι → F)
    (α : F →* P) :
    Prop :=
  ∀ i, α (relator i) = 1

/-- The ordinary normal subgroup generated by a displayed relator family. -/
def relationSubgroup
    {F : Type u}
    [Group F]
    {ι : Type*}
    (relator : ι → F) :
    Subgroup F :=
  Subgroup.normalClosure (Set.range relator)

/--
The closed normal subgroup topologically generated by a displayed relator
family.
-/
def completedRelationSubgroup
    {F : Type u}
    [Group F]
    [TopologicalSpace F]
    [IsTopologicalGroup F]
    {ι : Type*}
    (relator : ι → F) :
    Subgroup F :=
  (relationSubgroup relator).topologicalClosure

variable
    {F P : Type u}
    [Group F]
    [TopologicalSpace F]
    [IsTopologicalGroup F]
    [Group P]
    {ι : Type*}
    (relator : ι → F)

omit [TopologicalSpace F] [IsTopologicalGroup F] in
lemma relator_relation_subgroup
    (i : ι) :
    relator i ∈ relationSubgroup relator := by
  exact Subgroup.subset_normalClosure (Set.mem_range_self i)

lemma relation_completed :
    relationSubgroup relator ≤ completedRelationSubgroup relator := by
  exact (relationSubgroup relator).le_topologicalClosure

lemma relator_completed_subgroup
    (i : ι) :
    relator i ∈ completedRelationSubgroup relator := by
  exact relation_completed relator
    (relator_relation_subgroup relator i)

lemma completed_relation_closed :
    IsClosed ((completedRelationSubgroup relator : Subgroup F) : Set F) := by
  exact Subgroup.isClosed_topologicalClosure (relationSubgroup relator)

instance relationSubgroup_normal :
    (relationSubgroup relator).Normal :=
  Subgroup.normalClosure_normal

instance completed_relation_normal :
    (completedRelationSubgroup relator).Normal :=
  Subgroup.is_normal_topologicalClosure (relationSubgroup relator)

omit [TopologicalSpace F] [IsTopologicalGroup F] in
/--
Pointwise relator vanishing is exactly the algebraic normal-closure
containment needed for a quotient factorization argument.
-/
lemma kills_relators_relation
    (α : F →* P) :
    KillsRelators relator α ↔ relationSubgroup relator ≤ α.ker := by
  constructor
  · intro hkill
    apply Subgroup.normalClosure_le_normal
    rintro x ⟨i, rfl⟩
    exact MonoidHom.mem_ker.mpr (hkill i)
  · intro hnormal i
    exact MonoidHom.mem_ker.mp (hnormal (relator_relation_subgroup relator i))

/--
A continuous map into a `T1` target kills the whole completed relation
subgroup as soon as it kills the displayed relators.
-/
lemma completed_kills_relators
    [TopologicalSpace P]
    [T1Space P]
    (α : F →* P)
    (hα : Continuous α)
    (hkill : KillsRelators relator α) :
    completedRelationSubgroup relator ≤ α.ker := by
  apply Subgroup.topologicalClosure_minimal
  · exact (kills_relators_relation relator α).mp hkill
  · change IsClosed ((fun x : F => α x) ⁻¹' ({1} : Set P))
    exact isClosed_singleton.preimage hα

/--
A finite `p`-shadow carrying the extra information that it kills a displayed
relator family.
-/
structure RShadow
    (p : ℕ)
    (F : Type u)
    [Group F]
    [TopologicalSpace F]
    {ι : Type*}
    (relator : ι → F) where
  toShadow : Shadow p F
  relator_killed : KillsRelators relator toShadow.map

namespace RShadow

variable
    {p : ℕ}
    {F H : Type u}
    [Group F]
    [TopologicalSpace F]
    [IsTopologicalGroup F]
    [Group H]
    [TopologicalSpace H]
    [IsTopologicalGroup H]
    {ι κ : Type*}
    {relator : ι → F}
    {targetRelator : κ → H}

abbrev Target
    (S : RShadow p F relator) :
    Type u :=
  S.toShadow.Target

abbrev map
    (S : RShadow p F relator) :
    F →* S.Target :=
  S.toShadow.map

/-- Package an actual continuous finite discrete `p`-group map killing the relators. -/
def ofMap
    {P : Type u}
    [Group P]
    [TopologicalSpace P]
    [DiscreteTopology P]
    [Finite P]
    (α : F →* P)
    (hα : Continuous α)
    (hP : IsPGroup p P)
    (hkill : KillsRelators relator α) :
    RShadow p F relator where
  toShadow := {
    Target := P
    map := α
    map_continuous := hα
    target_p_group := hP
  }
  relator_killed := hkill

lemma completed_subgroup_kernel
    (S : RShadow p F relator) :
    completedRelationSubgroup relator ≤ S.map.ker := by
  exact completed_kills_relators
    relator S.map S.toShadow.map_continuous S.relator_killed

/--
Pull a relator-killing shadow back along a continuous map after proving that
the pulled-back map kills the new source relators.
-/
def pullback
    (S : RShadow p H targetRelator)
    (φ : F →* H)
    (hφ : Continuous φ)
    (hkill : KillsRelators relator (S.map.comp φ)) :
    RShadow p F relator where
  toShadow := S.toShadow.pullback φ hφ
  relator_killed := hkill

/--
Combine two relator-killing finite `p`-shadows into one simultaneous test.
-/
def prod
    [Fact p.Prime]
    (S T : RShadow p F relator) :
    RShadow p F relator where
  toShadow := S.toShadow.prod T.toShadow
  relator_killed := by
    intro i
    change (S.map.prod T.map) (relator i) = 1
    simp [S.relator_killed i, T.relator_killed i]

omit [IsTopologicalGroup F] in
@[simp] lemma prod_kernel
    [Fact p.Prime]
    (S T : RShadow p F relator) :
    (S.prod T).map.ker = S.map.ker ⊓ T.map.ker := by
  exact S.toShadow.prod_kernel T.toShadow

omit [IsTopologicalGroup F] in
lemma prod_kernel_iff
    [Fact p.Prime]
    (S T : RShadow p F relator)
    (x : F) :
    x ∈ (S.prod T).map.ker ↔ x ∈ S.map.ker ∧ x ∈ T.map.ker := by
  rw [prod_kernel, Subgroup.mem_inf]

end RShadow

/--
The subgroup invisible to every continuous finite `p`-group shadow killing the
displayed relators.
-/
def relatorKernel
    (p : ℕ)
    {F : Type u}
    [Group F]
    [TopologicalSpace F]
    {ι : Type*}
    (relator : ι → F) :
    Subgroup F :=
  sInf (Set.range fun S : RShadow p F relator => S.map.ker)

variable
    {p : ℕ}
    {F : Type u}
    [Group F]
    [TopologicalSpace F]
    [IsTopologicalGroup F]
    {ι : Type*}
    {relator : ι → F}

omit [IsTopologicalGroup F] in
lemma relator_kernel
    (S : RShadow p F relator) :
    relatorKernel p relator ≤ S.map.ker := by
  exact sInf_le ⟨S, rfl⟩

omit [IsTopologicalGroup F] in
lemma mem_relator_iff
    (x : F) :
    x ∈ relatorKernel p relator ↔
      ∀ S : RShadow p F relator, x ∈ S.map.ker := by
  constructor
  · intro hx S
    exact relator_kernel S hx
  · intro hx
    change x ∈ sInf (Set.range fun S : RShadow p F relator => S.map.ker)
    rw [Subgroup.mem_sInf]
    rintro K ⟨S, rfl⟩
    exact hx S

lemma completed_relation_relator :
    completedRelationSubgroup relator ≤ relatorKernel p relator := by
  apply le_sInf
  rintro K ⟨S, rfl⟩
  exact S.completed_subgroup_kernel

instance relatorKernel_normal :
    (relatorKernel p relator).Normal where
  conj_mem x hx g := by
    change x ∈ sInf (Set.range fun S : RShadow p F relator => S.map.ker) at hx
    change g * x * g⁻¹ ∈ sInf (Set.range fun S : RShadow p F relator => S.map.ker)
    rw [Subgroup.mem_sInf] at hx ⊢
    rintro K ⟨S, rfl⟩
    exact (show S.map.ker.Normal from inferInstance).conj_mem x (hx S.map.ker ⟨S, rfl⟩) g

/--
If the relation quotient is residually finite `p`, then finite
relator-killing `p`-shadows detect exactly the completed relation subgroup.
-/
lemma relator_relation_residually
    [Fact p.Prime]
    (hres :
      RFP p (F ⧸ completedRelationSubgroup relator)) :
    relatorKernel p relator ≤ completedRelationSubgroup relator := by
  intro x hxKernel
  by_contra hxRelation
  let R : Subgroup F := completedRelationSubgroup relator
  let π : F →* F ⧸ R := QuotientGroup.mk' R
  have hπ_cont : Continuous π := by
    change Continuous (QuotientGroup.mk : F → F ⧸ R)
    exact QuotientGroup.continuous_mk
  have hπx : π x ≠ 1 := by
    intro hπx_one
    exact hxRelation ((QuotientGroup.eq_one_iff x).mp hπx_one)
  rcases
      (residually_separates_nontrivial p (F ⧸ R)).mp hres
        (π x) hπx with
    ⟨S, hS⟩
  let A : RShadow p F relator := {
    toShadow := Shadow.pullback S π hπ_cont
    relator_killed := by
      intro i
      change S.map (π (relator i)) = 1
      have hri : relator i ∈ R := by
        exact relator_completed_subgroup relator i
      have hπri : π (relator i) = 1 := by
        change (relator i : F ⧸ R) = 1
        exact (QuotientGroup.eq_one_iff (relator i)).mpr hri
      rw [hπri]
      exact S.map.map_one
  }
  have hxA : x ∈ A.map.ker := relator_kernel A hxKernel
  apply hS
  exact MonoidHom.mem_ker.mp hxA

lemma relator_completed_residually
    [Fact p.Prime]
    (hres :
      RFP p (F ⧸ completedRelationSubgroup relator)) :
    relatorKernel p relator = completedRelationSubgroup relator := by
  apply le_antisymm
  · exact relator_relation_residually hres
  · exact completed_relation_relator

/-- A homomorphism factors through another homomorphism. -/
def FactorsThrough
    {F G P : Type u}
    [Group F]
    [Group G]
    [Group P]
    (q : F →* G)
    (α : F →* P) :
    Prop :=
  ∃ β : G →* P, β.comp q = α

/-- A homomorphism factors uniquely through another homomorphism. -/
def FactorsUniquelyThrough
    {F G P : Type u}
    [Group F]
    [Group G]
    [Group P]
    (q : F →* G)
    (α : F →* P) :
    Prop :=
  ∃! β : G →* P, β.comp q = α

variable
    {G P : Type u}
    [Group G]
    [Group P]
    (q : F →* G)
    (α : F →* P)

/-- The canonical factor map through a surjective homomorphism. -/
noncomputable def rightInverseSurjective
    (hq : Function.Surjective q) :
    G → F :=
  Classical.choose hq.hasRightInverse

omit [TopologicalSpace F] [IsTopologicalGroup F] in
lemma right_surjective_spec
    (hq : Function.Surjective q) :
    Function.RightInverse (rightInverseSurjective q hq) q :=
  Classical.choose_spec hq.hasRightInverse

noncomputable def factorSurjective
    (hq : Function.Surjective q)
    (hker : q.ker ≤ α.ker) :
    G →* P :=
  q.liftOfRightInverse
    (rightInverseSurjective q hq)
    (right_surjective_spec q hq)
    ⟨α, hker⟩

omit [TopologicalSpace F] [IsTopologicalGroup F] in
lemma factor_map_of
    (hq : Function.Surjective q)
    (hker : q.ker ≤ α.ker) :
    (factorSurjective q α hq hker).comp q = α := by
  exact
    q.liftOfRightInverse_comp
      (rightInverseSurjective q hq)
      (right_surjective_spec q hq)
      ⟨α, hker⟩

omit [TopologicalSpace F] [IsTopologicalGroup F] in
lemma ker_factors_through
    (hfactor : FactorsThrough q α) :
    q.ker ≤ α.ker := by
  rcases hfactor with ⟨β, hβ⟩
  intro x hx
  rw [MonoidHom.mem_ker] at hx ⊢
  have hβx := congrArg (fun φ : F →* P => φ x) hβ
  change β (q x) = α x at hβx
  calc
    α x = β (q x) := hβx.symm
    _ = β 1 := by rw [hx]
    _ = 1 := β.map_one

omit [TopologicalSpace F] [IsTopologicalGroup F] in
lemma factors_uniquely_ker
    (hq : Function.Surjective q)
    (hker : q.ker ≤ α.ker) :
    FactorsUniquelyThrough q α := by
  let β := factorSurjective q α hq hker
  refine ⟨β, factor_map_of q α hq hker, ?_⟩
  intro γ hγ
  apply MonoidHom.ext
  intro y
  rcases hq y with ⟨x, rfl⟩
  have hβx := congrArg (fun φ : F →* P => φ x) (factor_map_of q α hq hker)
  have hγx := congrArg (fun φ : F →* P => φ x) hγ
  change β (q x) = α x at hβx
  change γ (q x) = α x at hγx
  exact hγx.trans hβx.symm

omit [TopologicalSpace F] [IsTopologicalGroup F] in
lemma uniquely_through_ker
    (hq : Function.Surjective q) :
    FactorsUniquelyThrough q α ↔ q.ker ≤ α.ker := by
  constructor
  · rintro ⟨β, hβ, _hunique⟩
    exact ker_factors_through q α ⟨β, hβ⟩
  · exact factors_uniquely_ker q α hq

/--
The finite `p`-relator factorization property for a quotient candidate: every
continuous finite `p`-group shadow killing the relators also kills the kernel
of the candidate quotient.
-/
def FactorizationProperty
    (p : ℕ)
    {F G : Type u}
    [Group F]
    [TopologicalSpace F]
    [Group G]
    {ι : Type*}
    (relator : ι → F)
    (q : F →* G) :
    Prop :=
  ∀ S : RShadow p F relator, q.ker ≤ S.map.ker

variable
    {q : F →* G}
    {α : F →* P}

omit [IsTopologicalGroup F] in
lemma factorization_property_kernel :
    FactorizationProperty p relator q ↔ q.ker ≤ relatorKernel p relator := by
  constructor
  · intro hfactor
    apply le_sInf
    rintro K ⟨S, rfl⟩
    exact hfactor S
  · intro hkernel S
    exact hkernel.trans (relator_kernel S)

lemma factorization_property_completed
    (hkernel : q.ker ≤ completedRelationSubgroup relator) :
    FactorizationProperty p relator q := by
  intro S
  exact hkernel.trans S.completed_subgroup_kernel

omit [IsTopologicalGroup F] in
lemma factorization_property_p
    [TopologicalSpace P]
    [DiscreteTopology P]
    [Finite P]
    (hfactor : FactorizationProperty p relator q)
    (hα : Continuous α)
    (hP : IsPGroup p P)
    (hkill : KillsRelators relator α) :
    q.ker ≤ α.ker := by
  exact hfactor (RShadow.ofMap α hα hP hkill)

lemma kills_relators_completed
    [TopologicalSpace P]
    [T1Space P]
    (hkernel : q.ker ≤ completedRelationSubgroup relator)
    (hα : Continuous α)
    (hkill : KillsRelators relator α) :
    q.ker ≤ α.ker := by
  exact hkernel.trans (completed_kills_relators relator α hα hkill)

lemma uniquely_kills_completed
    [TopologicalSpace P]
    [T1Space P]
    (hq : Function.Surjective q)
    (hkernel : q.ker ≤ completedRelationSubgroup relator)
    (hα : Continuous α)
    (hkill : KillsRelators relator α) :
    FactorsUniquelyThrough q α := by
  apply factors_uniquely_ker q α hq
  exact kills_relators_completed
    (relator := relator) hkernel hα hkill

omit [IsTopologicalGroup F] in
lemma uniquely_factorization_property
    [TopologicalSpace P]
    [DiscreteTopology P]
    [Finite P]
    (hq : Function.Surjective q)
    (hfactor : FactorizationProperty p relator q)
    (hα : Continuous α)
    (hP : IsPGroup p P)
    (hkill : KillsRelators relator α) :
    FactorsUniquelyThrough q α := by
  apply factors_uniquely_ker q α hq
  exact factorization_property_p
    hfactor hα hP hkill

omit [IsTopologicalGroup F] in
lemma property_shadows_uniquely
    (hq : Function.Surjective q) :
    FactorizationProperty p relator q ↔
      ∀ S : RShadow p F relator, FactorsUniquelyThrough q S.map := by
  constructor
  · intro hfactor S
    exact factors_uniquely_ker q S.map hq (hfactor S)
  · intro hfactor S
    exact (uniquely_through_ker q S.map hq).mp (hfactor S)

end PRFact
end Towers
