import Towers.Algebra.DenseGenerators.FiniteGroupAlgebra
import Towers.Group.Frattini


open scoped Topology Pointwise IsMulCommutative

noncomputable section

namespace Towers

universe u

/-- The ordinary commutator subgroup is contained in the second Zassenhaus term. -/
lemma commutator_filtration_two
    (p : ℕ)
    (Λ : Type u) [Group Λ] :
    commutator Λ ≤ zassenhausFiltration p Λ 2 := by
  rw [← Subgroup.lowerCentralSeries_one]
  intro x hx
  exact
    Subgroup.subset_closure
      (show x ∈ zassenhausGeneratorSet p Λ 2 from
        ⟨1, 0, x, hx, by norm_num, by simp⟩)

/-- The subgroup generated by `p`th powers is contained in the second Zassenhaus term. -/
lemma p_filtration_two
    (p : ℕ) [Fact p.Prime]
    (Λ : Type u) [Group Λ] :
    pPowerSubgroup p Λ ≤ zassenhausFiltration p Λ 2 := by
  haveI : (zassenhausFiltration p Λ 2).Normal :=
    zassenhausFiltration_normal p Λ 2
  dsimp [pPowerSubgroup]
  apply Subgroup.normalClosure_le_normal
  intro x hx
  rcases hx with ⟨g, rfl⟩
  exact
    Subgroup.subset_closure
      (show g ^ p ∈ zassenhausGeneratorSet p Λ 2 from
        ⟨0, 1, g, by simp [Subgroup.lowerCentralSeries_zero], by
          simpa using (Nat.Prime.two_le (Fact.out : Nat.Prime p)), by
          simp⟩)

/-- The mod-`p` Frattini subgroup lies in `D₂` for the generator-set Zassenhaus filtration. -/
lemma mod_frattini_filtration
    {p : ℕ} [Fact p.Prime]
    (Λ : Type u) [Group Λ] :
    modPFrattini p Λ ≤ zassenhausFiltration p Λ 2 := by
  dsimp [modPFrattini]
  exact sup_le
    (p_filtration_two p Λ)
    (commutator_filtration_two p Λ)

/-- Positive lower-central terms lie in the ordinary commutator subgroup. -/
lemma lower_series_commutator
    {Λ : Type u} [Group Λ] {i : ℕ}
    (hi : 1 ≤ i) :
    Subgroup.lowerCentralSeries Λ i ≤ commutator Λ := by
  cases i with
  | zero =>
      omega
  | succ i =>
      rw [Subgroup.lowerCentralSeries_succ, commutator_eq_closure]
      refine Subgroup.closure_mono ?_
      intro z hz
      rcases hz with ⟨a, _ha, b, _hb, hz⟩
      rw [← hz]
      rw [commutatorSet_def]
      exact ⟨a, b, by simp [commutatorElement_def]⟩

/-- Every depth-two generator lies in the mod-`p` Frattini subgroup. -/
lemma set_subset_frattini
    {p : ℕ} [Fact p.Prime]
    (Λ : Type u) [Group Λ] :
    zassenhausGeneratorSet p Λ 2 ⊆ (modPFrattini p Λ : Set Λ) := by
  intro g hg
  rcases hg with ⟨i, j, x, hx_lower, hbound, hpow⟩
  by_cases hj : j = 0
  · subst j
    have hi : 1 ≤ i := by
      simpa [pow_zero, Nat.mul_one] using hbound
    have hx_comm : x ∈ commutator Λ :=
      lower_series_commutator hi hx_lower
    have hx_mod : x ∈ modPFrattini p Λ := by
      exact (le_sup_right : commutator Λ ≤ modPFrattini p Λ) hx_comm
    have hxg : x = g := by
      simpa using hpow
    simpa [← hxg] using hx_mod
  · rcases Nat.exists_eq_succ_of_ne_zero hj with ⟨k, rfl⟩
    have hx_power :
        x ^ (p ^ (k + 1)) = (x ^ (p ^ k)) ^ p := by
      rw [pow_succ, pow_mul]
    have hpow_mem : x ^ (p ^ (k + 1)) ∈ pPowerSubgroup p Λ := by
      rw [hx_power]
      exact p_power_subgroup p Λ (x ^ (p ^ k))
    have hmod : x ^ (p ^ (k + 1)) ∈ modPFrattini p Λ := by
      exact (le_sup_left : pPowerSubgroup p Λ ≤ modPFrattini p Λ) hpow_mem
    simpa [hpow] using hmod

/-- The second generator-set Zassenhaus term is contained in the mod-`p` Frattini subgroup. -/
lemma filtration_mod_frattini
    {p : ℕ} [Fact p.Prime]
    (Λ : Type u) [Group Λ] :
    zassenhausFiltration p Λ 2 ≤ modPFrattini p Λ := by
  rw [zassenhausFiltration]
  exact
    (Subgroup.closure_le _).mpr
      (set_subset_frattini (p := p) Λ)

/-- The second generator-set Zassenhaus term is the mod-`p` Frattini subgroup. -/
theorem filtration_p_frattini
    {p : ℕ} [Fact p.Prime]
    (Λ : Type u) [Group Λ] :
    zassenhausFiltration p Λ 2 = modPFrattini p Λ := by
  exact le_antisymm
    (filtration_mod_frattini (p := p) Λ)
    (mod_frattini_filtration (p := p) Λ)

/-- The quotient by `D₂` is commutative. -/
instance inst_commutative_self
    (p : ℕ)
    (Λ : Type u) [Group Λ] :
    IsMulCommutative (zassenhausSelfQuotient p Λ 2) := by
  letI : (zassenhausFiltration p Λ 2).Normal :=
    zassenhausFiltration_normal p Λ 2
  dsimp [zassenhausSelfQuotient]
  exact Subgroup.Normal.quotient_commutative_iff_commutator_le.mpr
    (commutator_filtration_two p Λ)

instance inst_comm_self
    (p : ℕ) (Λ : Type u) [Group Λ] :
    CommGroup (zassenhausSelfQuotient p Λ 2) :=
  { (inferInstance : Group (zassenhausSelfQuotient p Λ 2)) with
    mul_comm := mul_comm' }

/-- The quotient by `D₂` is naturally an elementary abelian `p`-group. -/
noncomputable instance inst_z_self
    {p : ℕ} [Fact p.Prime]
    (Λ : Type u) [Group Λ] :
    Module (ZMod p) (Additive (zassenhausSelfQuotient p Λ 2)) := by
  letI : IsMulCommutative (zassenhausSelfQuotient p Λ 2) :=
    inst_commutative_self p Λ
  have hp_torsion :
      ∀ y : Additive (zassenhausSelfQuotient p Λ 2), p • y = 0 := by
    intro y
    rw [← ofMul_toMul y]
    rw [← ofMul_pow]
    change Additive.ofMul (Additive.toMul y ^ p) = Additive.ofMul (1 :
      zassenhausSelfQuotient p Λ 2)
    rw [zassenhaus_self_one]
  exact AddCommGroup.zmodModule hp_torsion

end Towers
