import Mathlib.Algebra.Polynomial.OfFn
import Mathlib.RingTheory.Polynomial.Eisenstein.Basic
import Mathlib.Topology.LocallyConstant.Basic
import Mathlib.RingTheory.Polynomial.GaussLemma
import Submission.NumberTheory.Locals.CompactValuationSubsets
import Submission.NumberTheory.Locals.PolynomialStability
import Submission.NumberTheory.Locals.TotallyRamifiedEisenstein


/-!
# Milne, Algebraic Number Theory, Proposition 7.64

Milne parametrizes degree `n + 1` Eisenstein polynomials by `n` coefficients in the maximal
ideal and a constant coefficient in `Aˣ * π`.  Proposition 7.63 says that the finite set of
extensions generated by the roots is locally constant on this parameter space.  Compactness then
shows that only finitely many root fields occur.  The final theorem packages Proposition 7.64:
any family of totally ramified intermediate fields covered by these root fields is finite.
-/

namespace Submission.NumberTheory.Milne

open Filter Set Valued
open scoped NNReal
open scoped NormedField
open scoped Topology

variable (K Γ₀ : Type*) [Field K] [LinearOrderedCommGroupWithZero Γ₀]
variable [Valued K Γ₀] [(Valued.v : Valuation K Γ₀).RankOne]
variable [CompleteSpace 𝒪[K]] [IsDiscreteValuationRing 𝒪[K]]
variable [Finite (Valued.ResidueField K)]

/-- The possible constant coefficients `u * π`, with `u` a unit of the valuation ring. -/
def unitMultipleSet (π : 𝒪[K]) : Set 𝒪[K] :=
  (fun u : 𝒪[K] ↦ u * π) '' {u : 𝒪[K] | IsUnit u}

/-- The set `Aˣ * π` is compact when the residue field is finite. -/
theorem multiple_set_compact (π : 𝒪[K]) :
    IsCompact (unitMultipleSet K Γ₀ π) := by
  exact (valuation_units_compact K Γ₀).image (continuous_id.mul continuous_const)

/-- The coefficient parameter space used in Milne's proof for Eisenstein polynomials of degree
`n + 1`: `n` coefficients in the maximal ideal, followed by a constant coefficient in
`Aˣ * π`. -/
abbrev EisensteinCoefficientParameters (n : ℕ) (π : 𝒪[K]) :=
  (Fin n → ↑(↑(IsLocalRing.maximalIdeal 𝒪[K]) : Set 𝒪[K])) ×
    ↑(unitMultipleSet K Γ₀ π)

/-- Milne's Eisenstein coefficient parameter space is compact. -/
theorem eisenstein_parameters_space (n : ℕ) (π : 𝒪[K]) :
    CompactSpace (EisensteinCoefficientParameters K Γ₀ n π) := by
  letI : CompactSpace ↑(↑(IsLocalRing.maximalIdeal 𝒪[K]) : Set 𝒪[K]) :=
    isCompact_iff_compactSpace.mp <| by
      simpa using maximal_ideal_compact K Γ₀ 1
  letI : CompactSpace ↑(unitMultipleSet K Γ₀ π) :=
    isCompact_iff_compactSpace.mp (multiple_set_compact K Γ₀ π)
  dsimp only [EisensteinCoefficientParameters]
  infer_instance

/-- The compactness step in Proposition 7.64: any locally constant classification of the
Eisenstein coefficient parameter space has finite range. -/
theorem eisenstein_classification_range
    (n : ℕ) (π : 𝒪[K]) {Classification : Type*}
    (classify : EisensteinCoefficientParameters K Γ₀ n π → Classification)
    (hclassify : IsLocallyConstant classify) :
    (Set.range classify).Finite := by
  letI := eisenstein_parameters_space K Γ₀ n π
  exact hclassify.range_finite

/-- Equivalently, finitely many values suffice to contain all classifications arising from
Eisenstein coefficient parameters. -/
theorem finset_eisenstein_classifications
    (n : ℕ) (π : 𝒪[K]) {Classification : Type*}
    (classify : EisensteinCoefficientParameters K Γ₀ n π → Classification)
    (hclassify : IsLocallyConstant classify) :
    ∃ classes : Finset Classification, ∀ a, classify a ∈ classes := by
  let hfinite :=
    eisenstein_classification_range K Γ₀ n π classify hclassify
  refine ⟨hfinite.toFinset, fun a ↦ hfinite.mem_toFinset.mpr ?_⟩
  exact ⟨a, rfl⟩

section RootFields

variable {Ω : Type*} [Field Ω] [Algebra K Ω]

/-- Compactness plus local constancy makes the union of finite
classifications finite.  This is the finite-cover argument at the heart of
Milne, Proposition 7.64. -/
theorem eisenstein_classification_i
    (n : ℕ) (pi : 𝒪[K]) {Classification : Type*}
    (classify : EisensteinCoefficientParameters K Γ₀ n pi → Set Classification)
    (hclassify : IsLocallyConstant classify)
    (hfinite : ∀ a, (classify a).Finite) :
    (⋃ a, classify a).Finite := by
  rw [← Set.sUnion_range]
  exact (eisenstein_classification_range K Γ₀ n pi classify hclassify).sUnion
    (by rintro s ⟨a, rfl⟩; exact hfinite a)

/-- Only finitely many root fields arise from a locally constant family of
polynomials on Milne's compact Eisenstein coefficient space. -/
theorem eisenstein_fields_i
    (n : ℕ) (pi : 𝒪[K])
    (polynomial : EisensteinCoefficientParameters K Γ₀ n pi → Polynomial K)
    (hclassify : IsLocallyConstant fun a ↦
      polynomialRootFields K Ω (polynomial a)) :
    (⋃ a, polynomialRootFields K Ω (polynomial a)).Finite := by
  exact eisenstein_classification_i K Γ₀ n pi
    (fun a ↦ polynomialRootFields K Ω (polynomial a))
    hclassify fun a ↦ polynomial_root_fields K Ω (polynomial a)

/-- Milne, Proposition 7.64, in a fixed algebraic ambient field.

If the totally ramified degree-`n + 1` intermediate fields are represented by
the root fields of the Eisenstein polynomials parametrized above, and that
root-field classification is locally constant (the conclusion supplied by
Proposition 7.63), then there are only finitely many such fields.  Choosing
one embedding of each finite extension into an algebraic closure converts
this into Milne's finiteness statement up to `K`-isomorphism. -/
theorem totally_fields_parameterization
    (n : ℕ) (pi : 𝒪[K])
    (polynomial : EisensteinCoefficientParameters K Γ₀ n pi → Polynomial K)
    (TotallyRamifiedOfDegree : IntermediateField K Ω → Prop)
    (hclassify : IsLocallyConstant fun a ↦
      polynomialRootFields K Ω (polynomial a))
    (hparam : ∀ E, TotallyRamifiedOfDegree E →
      ∃ a, E ∈ polynomialRootFields K Ω (polynomial a)) :
    {E : IntermediateField K Ω | TotallyRamifiedOfDegree E}.Finite := by
  apply (eisenstein_fields_i K Γ₀ n pi polynomial hclassify).subset
  intro E hE
  obtain ⟨a, ha⟩ := hparam E hE
  exact Set.mem_iUnion.mpr ⟨a, ha⟩

end RootFields

section CompactPolynomialFamily

variable {K Ω P : Type*} [NontriviallyNormedField K] [CompleteSpace K]
  [IsUltrametricDist K]
  [NormedField Ω] [NormedAlgebra K Ω] [Algebra.IsAlgebraic K Ω]
  [IsGalois K Ω] [IsAlgClosed Ω]
  [TopologicalSpace P] [CompactSpace P]

omit [CompactSpace P] in
/-- The root-field classification of a continuous fixed-degree family is
locally constant.  This supplies the Krasner-theoretic hypothesis that was
left explicit in the abstract compactness formulation above. -/
theorem fields_locally_compact
    (hna : IsNonarchimedean (norm : Ω → ℝ))
    (poly : P → Polynomial K) (d : ℕ)
    (hmonic : ∀ a, (poly a).Monic)
    (hirred : ∀ a, Irreducible (poly a))
    (hdegree : ∀ a, (poly a).natDegree = d)
    (hcoeff : ∀ i : ℕ, Continuous fun a ↦ (poly a).coeff i) :
    IsLocallyConstant fun a ↦
      polynomialRootFields K Ω (poly a) := by
  rw [IsLocallyConstant.iff_eventually_eq]
  intro a
  obtain ⟨ε, hε, hstable⟩ :=
    radius_irreducible_fields
      (K := K) (Ω := Ω) hna (hirred a) (hmonic a)
  have heach : ∀ i : ℕ, ∀ᶠ b in 𝓝 a,
      ‖(poly b).coeff i - (poly a).coeff i‖ < ε := by
    intro i
    have hmem := (hcoeff i).continuousAt.eventually
      (Metric.ball_mem_nhds ((poly a).coeff i) hε)
    filter_upwards [hmem] with b hb
    simpa [Metric.mem_ball, dist_eq_norm, norm_sub_rev] using hb
  have hfinite : ∀ᶠ b in 𝓝 a, ∀ i ∈ Finset.range (d + 1),
      ‖(poly b).coeff i - (poly a).coeff i‖ < ε :=
    (Finset.range (d + 1)).eventually_all.2 fun i _ ↦ heach i
  filter_upwards [hfinite] with b hb
  have hclose : ∀ i : ℕ, ‖(poly b).coeff i - (poly a).coeff i‖ < ε := by
    intro i
    by_cases hi : i < d + 1
    · exact hb i (Finset.mem_range.2 hi)
    · have hia : (poly a).coeff i = 0 := by
        apply Polynomial.coeff_eq_zero_of_natDegree_lt
        rw [hdegree a]
        omega
      have hib : (poly b).coeff i = 0 := by
        apply Polynomial.coeff_eq_zero_of_natDegree_lt
        rw [hdegree b]
        omega
      simp [hia, hib, hε]
  exact (hstable (hmonic b) ((hdegree b).trans (hdegree a).symm) hclose).2.symm

/-- Milne, Proposition 7.64, in the compact-family form used by its proof.
There are only finitely many intermediate fields generated by roots anywhere
in a compact continuous family of fixed-degree irreducible monic
polynomials. -/
theorem fields_compact_family
    (hna : IsNonarchimedean (norm : Ω → ℝ))
    (poly : P → Polynomial K) (d : ℕ)
    (hmonic : ∀ a, (poly a).Monic)
    (hirred : ∀ a, Irreducible (poly a))
    (hdegree : ∀ a, (poly a).natDegree = d)
    (hcoeff : ∀ i : ℕ, Continuous fun a ↦ (poly a).coeff i) :
    (⋃ a, polynomialRootFields K Ω (poly a)).Finite := by
  have hlocal := fields_locally_compact
    hna poly d hmonic hirred hdegree hcoeff
  rw [← Set.sUnion_range]
  exact hlocal.range_finite.sUnion
    (by rintro s ⟨a, rfl⟩; exact polynomial_root_fields K Ω (poly a))

end CompactPolynomialFamily

section EisensteinPolynomialFamily

open Polynomial

variable {K : Type*} [NontriviallyNormedField K] [CompleteSpace K]
  [IsUltrametricDist K]
variable [(Valued.v : Valuation K NNReal).RankOne]
variable [CompleteSpace 𝒪[K]] [IsDiscreteValuationRing 𝒪[K]]
variable [Finite (Valued.ResidueField K)]

noncomputable local instance : DecidableEq 𝒪[K] := Classical.decEq _

/-- The integral Eisenstein polynomial represented by one point of Milne's
coefficient parameter space.  A parameter in dimension `n` represents a
monic polynomial of degree `n + 1`. -/
noncomputable def eisensteinParameterIntegral
    (n : ℕ) (pi : 𝒪[K])
    (a : EisensteinCoefficientParameters K NNReal n pi) : Polynomial 𝒪[K] :=
  X ^ (n + 1) + Polynomial.ofFn (n + 1)
    (Fin.cases a.2.1 fun i ↦ (a.1 i).1)

omit [CompleteSpace K] [CompleteSpace ↥𝒪[K]] [Finite 𝓀[K]] in
theorem eisenstein_parameter_monic
    (n : ℕ) (pi : 𝒪[K])
    (a : EisensteinCoefficientParameters K NNReal n pi) :
    (eisensteinParameterIntegral n pi a).Monic := by
  rw [eisensteinParameterIntegral]
  apply Polynomial.monic_X_pow_add
  exact Polynomial.ofFn_degree_lt _

omit [CompleteSpace K] [CompleteSpace ↥𝒪[K]] [Finite 𝓀[K]] in
theorem eisenstein_parameter_degree
    (n : ℕ) (pi : 𝒪[K])
    (a : EisensteinCoefficientParameters K NNReal n pi) :
    (eisensteinParameterIntegral n pi a).natDegree = n + 1 := by
  have hlt := Polynomial.ofFn_degree_lt
    (Fin.cases a.2.1 fun i ↦ (a.1 i).1)
  rw [eisensteinParameterIntegral,
    Polynomial.natDegree_add_eq_left_of_degree_lt]
  · exact Polynomial.natDegree_X_pow (R := 𝒪[K]) (n + 1)
  · simpa using hlt

omit [CompleteSpace K] [(Valued.v : Valuation K NNReal).RankOne]
  [CompleteSpace ↥𝒪[K]] [Finite 𝓀[K]] in
private theorem uniformizer_maximal_sq
    (pi : 𝒪[K]) (hpi : Irreducible pi)
    {u : 𝒪[K]} (hu : IsUnit u) :
    u * pi ∉ IsLocalRing.maximalIdeal 𝒪[K] ^ 2 := by
  rw [hpi.maximalIdeal_eq, Ideal.span_singleton_pow, Ideal.mem_span_singleton]
  intro hdvd
  have hsquare : pi ^ 2 ∣ pi := (hu.dvd_mul_left).mp hdvd
  rcases hsquare with ⟨c, hc⟩
  apply hpi.not_dvd_one
  refine ⟨c, ?_⟩
  apply mul_left_cancel₀ hpi.ne_zero
  simpa [pow_two, mul_assoc] using hc

omit [CompleteSpace K] [CompleteSpace ↥𝒪[K]] [Finite 𝓀[K]] in
/-- Every polynomial represented by Milne's parameter space is Eisenstein at
the maximal ideal when `pi` is a uniformizer. -/
theorem eisenstein_parameter_integral
    (n : ℕ) (pi : 𝒪[K]) (hpi : Irreducible pi)
    (a : EisensteinCoefficientParameters K NNReal n pi) :
    (eisensteinParameterIntegral n pi a).IsEisensteinAt
      (IsLocalRing.maximalIdeal 𝒪[K]) := by
  apply (eisenstein_parameter_monic n pi a).isEisensteinAt_of_mem_of_notMem
  · exact (IsLocalRing.maximalIdeal.isMaximal _).ne_top
  · intro i hi
    rw [eisenstein_parameter_degree n pi a] at hi
    rw [eisensteinParameterIntegral, Polynomial.coeff_add,
      Polynomial.coeff_X_pow]
    have hne : i ≠ n + 1 := by omega
    rw [if_neg hne, zero_add]
    have hilow : i < n + 1 := hi
    rw [Polynomial.ofFn_coeff_eq_val_of_lt _ hilow]
    cases i with
    | zero =>
        change a.2.1 ∈ IsLocalRing.maximalIdeal 𝒪[K]
        rcases a.2.2 with ⟨u, hu, hua⟩
        rw [← hua]
        exact (IsLocalRing.maximalIdeal 𝒪[K]).mul_mem_left u
          (hpi.maximalIdeal_eq ▸ Ideal.mem_span_singleton_self pi)
    | succ j =>
        have hj : j < n := by omega
        change (a.1 ⟨j, hj⟩).1 ∈ IsLocalRing.maximalIdeal 𝒪[K]
        exact (a.1 ⟨j, hj⟩).2
  · rw [eisensteinParameterIntegral, Polynomial.coeff_add,
      Polynomial.coeff_X_pow]
    rw [if_neg (Nat.zero_ne_add_one n), zero_add,
      Polynomial.ofFn_coeff_eq_val_of_lt _ (Nat.zero_lt_succ n)]
    change a.2.1 ∉ IsLocalRing.maximalIdeal 𝒪[K] ^ 2
    rcases a.2.2 with ⟨u, hu, hua⟩
    rw [← hua]
    exact uniformizer_maximal_sq pi hpi hu

omit [CompleteSpace K] [CompleteSpace ↥𝒪[K]] [Finite 𝓀[K]] in
/-- Every monic Eisenstein polynomial of degree `n + 1` occurs in Milne's
compact coefficient parameter space.  The only point needing proof beyond
reading off the coefficients is that its constant coefficient is a unit
multiple of the chosen uniformizer. -/
theorem eisenstein_coefficient_parameters
    (n : ℕ) (pi : 𝒪[K]) (hpi : Irreducible pi)
    (f : Polynomial 𝒪[K]) (hmonic : f.Monic)
    (hdegree : f.natDegree = n + 1)
    (heis : f.IsEisensteinAt (IsLocalRing.maximalIdeal 𝒪[K])) :
    ∃ a : EisensteinCoefficientParameters K NNReal n pi,
      eisensteinParameterIntegral n pi a = f := by
  have hc0 : f.coeff 0 ≠ 0 := by
    intro hzero
    apply heis.notMem
    simp [hzero]
  obtain ⟨m, u, hu⟩ :=
    IsDiscreteValuationRing.eq_unit_mul_pow_irreducible hc0 hpi
  have hmpos : 0 < m := by
    have hdvd : pi ∣ f.coeff 0 := by
      rw [← Ideal.mem_span_singleton, ← hpi.maximalIdeal_eq]
      exact heis.mem (by omega)
    by_contra hm
    have hm0 : m = 0 := Nat.eq_zero_of_not_pos hm
    rw [hu, hm0, pow_zero, mul_one] at hdvd
    exact hpi.not_dvd_unit u hdvd
  have hmlt : m < 2 := by
    by_contra hm
    have hpow : pi ^ 2 ∣ pi ^ m := pow_dvd_pow pi (by omega)
    apply heis.notMem
    rw [hpi.maximalIdeal_eq, Ideal.span_singleton_pow,
      Ideal.mem_span_singleton, hu]
    exact dvd_mul_of_dvd_right hpow u
  have hm : m = 1 := by omega
  have hu' : f.coeff 0 = (u : 𝒪[K]) * pi := by
    simpa [hm] using hu
  let a : EisensteinCoefficientParameters K NNReal n pi :=
    (fun i ↦
      ⟨f.coeff (i + 1), heis.mem (by rw [hdegree]; omega)⟩,
      ⟨f.coeff 0, ⟨(u : 𝒪[K]), u.isUnit, hu'.symm⟩⟩)
  refine ⟨a, ?_⟩
  apply Polynomial.ext
  intro i
  by_cases hi : i = n + 1
  · subst i
    have hleft :=
      (eisenstein_parameter_monic n pi a).coeff_natDegree
    rw [eisenstein_parameter_degree] at hleft
    have hright := hmonic.coeff_natDegree
    rw [hdegree] at hright
    rw [hleft, hright]
  by_cases hilow : i < n + 1
  · rw [eisensteinParameterIntegral, Polynomial.coeff_add,
      Polynomial.coeff_X_pow, if_neg hi, zero_add,
      Polynomial.ofFn_coeff_eq_val_of_lt _ hilow]
    cases i with
    | zero => rfl
    | succ j => rfl
  · have hihigh : n + 1 < i :=
      lt_of_le_of_ne (Nat.le_of_not_gt hilow) (Ne.symm hi)
    rw [Polynomial.coeff_eq_zero_of_natDegree_lt,
      Polynomial.coeff_eq_zero_of_natDegree_lt]
    · exact hdegree ▸ hihigh
    · rw [eisenstein_parameter_degree]
      exact hihigh

omit [CompleteSpace K] [CompleteSpace ↥𝒪[K]] [Finite 𝓀[K]] in
theorem eisenstein_parameter_irreducible
    (n : ℕ) (pi : 𝒪[K]) (hpi : Irreducible pi)
    (a : EisensteinCoefficientParameters K NNReal n pi) :
    Irreducible (eisensteinParameterIntegral n pi a) := by
  apply (eisenstein_parameter_integral n pi hpi a).irreducible
  · exact (IsLocalRing.maximalIdeal.isMaximal _).isPrime
  · exact (eisenstein_parameter_monic n pi a).isPrimitive
  · rw [eisenstein_parameter_degree n pi a]
    omega

/-- The degree `n + 1` Eisenstein polynomial over `K` associated to a
coefficient parameter. -/
noncomputable def eisensteinParameterPolynomial
    (n : ℕ) (pi : 𝒪[K])
    (a : EisensteinCoefficientParameters K NNReal n pi) : Polynomial K :=
  (eisensteinParameterIntegral n pi a).map (algebraMap 𝒪[K] K)

omit [CompleteSpace K] [CompleteSpace ↥𝒪[K]] [Finite 𝓀[K]] in
theorem eisenstein_polynomial_monic
    (n : ℕ) (pi : 𝒪[K])
    (a : EisensteinCoefficientParameters K NNReal n pi) :
    (eisensteinParameterPolynomial n pi a).Monic :=
  (eisenstein_parameter_monic n pi a).map _

omit [CompleteSpace K] [CompleteSpace ↥𝒪[K]] [Finite 𝓀[K]] in
theorem eisenstein_parameter_nat
    (n : ℕ) (pi : 𝒪[K])
    (a : EisensteinCoefficientParameters K NNReal n pi) :
    (eisensteinParameterPolynomial n pi a).natDegree = n + 1 := by
  rw [eisensteinParameterPolynomial,
    (eisenstein_parameter_monic n pi a).natDegree_map,
    eisenstein_parameter_degree]

omit [CompleteSpace K] [CompleteSpace ↥𝒪[K]] [Finite 𝓀[K]] in
theorem eisenstein_polynomial_irreducible
    (n : ℕ) (pi : 𝒪[K]) (hpi : Irreducible pi)
    (a : EisensteinCoefficientParameters K NNReal n pi) :
    Irreducible (eisensteinParameterPolynomial n pi a) := by
  have hmonic := eisenstein_parameter_monic n pi a
  exact (hmonic.irreducible_iff_irreducible_map_fraction_map).1
    (eisenstein_parameter_irreducible n pi hpi a)

omit [CompleteSpace K] [CompleteSpace ↥𝒪[K]] [Finite 𝓀[K]] in
/-- Every monic Eisenstein polynomial of degree `n + 1` occurs in Milne's
compact coefficient parameter space.  This is the algebraic bridge between
Proposition 7.55's Eisenstein generator and Proposition 7.64's compactness
argument. -/
theorem eisenstein_coefficient_parameter
    (n : ℕ) (pi : 𝒪[K]) (hpi : Irreducible pi)
    (f : Polynomial 𝒪[K]) (hfm : f.Monic)
    (hdegree : f.natDegree = n + 1)
    (heis : f.IsEisensteinAt (IsLocalRing.maximalIdeal 𝒪[K])) :
    ∃ a : EisensteinCoefficientParameters K NNReal n pi,
      eisensteinParameterIntegral n pi a = f :=
  eisenstein_coefficient_parameters n pi hpi f hfm hdegree heis

omit [CompleteSpace K] [CompleteSpace ↥𝒪[K]] [Finite 𝓀[K]] in
theorem eisenstein_parameter_continuous
    (n : ℕ) (pi : 𝒪[K]) (i : ℕ) :
    Continuous fun a : EisensteinCoefficientParameters K NNReal n pi ↦
      (eisensteinParameterPolynomial n pi a).coeff i := by
  by_cases hlead : i = n + 1
  · subst i
    rw [show (fun a : EisensteinCoefficientParameters K NNReal n pi ↦
        (eisensteinParameterPolynomial n pi a).coeff (n + 1)) =
      fun _ ↦ (1 : K) by
        funext a
        rw [← eisenstein_parameter_nat n pi a]
        exact (eisenstein_polynomial_monic n pi a).coeff_natDegree]
    exact continuous_const
  by_cases hi : i < n + 1
  · have hcoeff (a : EisensteinCoefficientParameters K NNReal n pi) :
        (eisensteinParameterPolynomial n pi a).coeff i =
          algebraMap 𝒪[K] K
            (Fin.cases a.2.1 (fun j ↦ (a.1 j).1) ⟨i, hi⟩) := by
      simp [eisensteinParameterPolynomial, eisensteinParameterIntegral,
        Polynomial.coeff_map, hlead,
        Polynomial.ofFn_coeff_eq_val_of_lt _ hi]
    cases i with
    | zero =>
        rw [show (fun a : EisensteinCoefficientParameters K NNReal n pi ↦
            (eisensteinParameterPolynomial n pi a).coeff 0) =
          fun a ↦ (a.2.1.1 : K) by
            funext a
            simpa only [Fin.cases_zero] using hcoeff a]
        fun_prop
    | succ j =>
        have hj : j < n := by omega
        rw [show (fun a : EisensteinCoefficientParameters K NNReal n pi ↦
            (eisensteinParameterPolynomial n pi a).coeff (j + 1)) =
          fun a ↦ ((a.1 ⟨j, hj⟩).1.1 : K) by
            funext a
            simpa only [Fin.cases_succ] using hcoeff a]
        fun_prop
  · have hgt : n + 1 < i :=
      lt_of_le_of_ne (Nat.le_of_not_gt hi) (Ne.symm hlead)
    rw [show (fun a : EisensteinCoefficientParameters K NNReal n pi ↦
        (eisensteinParameterPolynomial n pi a).coeff i) =
      fun _ ↦ (0 : K) by
        funext a
        exact Polynomial.coeff_eq_zero_of_natDegree_lt <| by
          rw [eisenstein_parameter_nat n pi a]
          exact hgt]
    exact continuous_const

variable {Ω : Type*} [NormedField Ω] [NormedAlgebra K Ω]
  [Algebra.IsAlgebraic K Ω] [IsGalois K Ω] [IsAlgClosed Ω]

/-- Milne, Proposition 7.64, for the actual compact family of degree
`n + 1` Eisenstein polynomials.  Only finitely many root-generated
intermediate fields occur in a fixed algebraic closure. -/
theorem fields_eisenstein_parameters
    (n : ℕ) (pi : 𝒪[K]) (hpi : Irreducible pi)
    (hna : IsNonarchimedean (norm : Ω → ℝ)) :
    (⋃ a : EisensteinCoefficientParameters K NNReal n pi,
      polynomialRootFields K Ω (eisensteinParameterPolynomial n pi a)).Finite := by
  letI := eisenstein_parameters_space K NNReal n pi
  apply fields_compact_family hna
    (fun a ↦ eisensteinParameterPolynomial n pi a) (n + 1)
  · exact eisenstein_polynomial_monic n pi
  · exact eisenstein_polynomial_irreducible n pi hpi
  · exact eisenstein_parameter_nat n pi
  · exact eisenstein_parameter_continuous n pi

/-- An intermediate field is Eisenstein-presented in degree `n + 1` if it is
generated by a root of a monic degree `n + 1` polynomial over the valuation
ring that is Eisenstein at the maximal ideal.  Proposition 7.55 identifies
these with the totally ramified extensions once the extension's valuation
ring is supplied. -/
def EisensteinPresentedExtension
    (n : ℕ) (E : IntermediateField K Ω) : Prop :=
  ∃ f : Polynomial 𝒪[K], f.Monic ∧ f.natDegree = n + 1 ∧
    f.IsEisensteinAt (IsLocalRing.maximalIdeal 𝒪[K]) ∧
    E ∈ polynomialRootFields K Ω (f.map (algebraMap 𝒪[K] K))

omit [CompleteSpace K] [(Valued.v : Valuation K NNReal).RankOne]
  [CompleteSpace ↥𝒪[K]] [Finite 𝓀[K]] [IsGalois K Ω] [IsAlgClosed Ω] in
/-- Proposition 7.55 supplies exactly the field presentation used in
Proposition 7.64.  If an integral order has an Eisenstein generator and `L`
is its fraction field, then the image of `L` under any `K`-embedding into the
chosen algebraic closure is Eisenstein-presented. -/
theorem eisenstein_presented_generator
    {B L : Type*} [CommRing B] [IsDomain B] [Algebra 𝒪[K] B]
    [Module.Finite 𝒪[K] B] [Module.IsTorsionFree 𝒪[K] B]
    [Field L] [Algebra B L] [IsFractionRing B L]
    [Algebra K L] [FiniteDimensional K L] [Algebra 𝒪[K] L]
    [IsScalarTower 𝒪[K] B L] [IsScalarTower 𝒪[K] K L]
    (n : ℕ) (j : L →ₐ[K] Ω)
    (hdegree : Module.finrank K L = n + 1)
    (hgen : HasEisensteinGenerator 𝒪[K] B
      (IsLocalRing.maximalIdeal 𝒪[K])) :
    EisensteinPresentedExtension n j.fieldRange := by
  rcases hgen with ⟨alpha, halpha, hadjoinB, heis⟩
  let alphaL : L := algebraMap B L alpha
  let beta : Ω := j alphaL
  have halphaL : IsIntegral 𝒪[K] alphaL :=
    halpha.map (IsScalarTower.toAlgHom 𝒪[K] B L)
  have hbeta : IsIntegral 𝒪[K] beta :=
    halphaL.map (j.restrictScalars 𝒪[K])
  have hminAlphaL : minpoly 𝒪[K] alphaL = minpoly 𝒪[K] alpha := by
    exact minpoly.algebraMap_eq (IsFractionRing.injective B L) alpha
  have hminBeta : minpoly 𝒪[K] beta = minpoly 𝒪[K] alpha := by
    have hmap : minpoly 𝒪[K] beta = minpoly 𝒪[K] alphaL := by
      simpa only [beta, AlgHom.restrictScalars_apply] using
        minpoly.algHom_eq (j.restrictScalars 𝒪[K]) j.injective alphaL
    exact hmap.trans hminAlphaL
  let hroot : IsAdjoinRootMonic B (minpoly 𝒪[K] alpha) :=
    IsAdjoinRootMonic.mkOfAdjoinEqTop halpha hadjoinB
  have hadjoin : IntermediateField.adjoin K ({alphaL} : Set L) = ⊤ := by
    apply (Field.primitive_element_iff_minpoly_natDegree_eq K alphaL).2
    rw [minpoly.isIntegrallyClosed_eq_field_fractions K L halpha,
      (minpoly.monic halpha).natDegree_map, ← hroot.finrank,
      Algebra.IsAlgebraic.finrank_of_isFractionRing 𝒪[K] K B L]
  have hpolyDegree : (minpoly 𝒪[K] beta).natDegree = n + 1 := by
    rw [hminBeta, ← hroot.finrank,
      ← Algebra.IsAlgebraic.finrank_of_isFractionRing 𝒪[K] K B L,
      hdegree]
  have hfieldRange :
      j.fieldRange = IntermediateField.adjoin K {beta} := by
    calc
      j.fieldRange = ( ⊤ : IntermediateField K L).map j :=
        AlgHom.fieldRange_eq_map j
      _ = (IntermediateField.adjoin K {alphaL}).map j := by rw [hadjoin]
      _ = IntermediateField.adjoin K (j '' ({alphaL} : Set L)) :=
        IntermediateField.adjoin_map (F := K) (S := ({alphaL} : Set L)) j
      _ = IntermediateField.adjoin K {beta} := by simp [beta]
  refine ⟨minpoly 𝒪[K] beta, minpoly.monic hbeta, hpolyDegree, ?_, ?_⟩
  · simpa [hminBeta] using heis
  · refine ⟨beta, ?_, hfieldRange⟩
    have hpoly :
        (minpoly 𝒪[K] beta).map (algebraMap 𝒪[K] K) =
          minpoly K beta :=
      (minpoly.isIntegrallyClosed_eq_field_fractions' K hbeta).symm
    rw [hpoly, Polynomial.mem_aroots]
    exact ⟨minpoly.ne_zero hbeta.tower_top, minpoly.aeval K beta⟩

omit [CompleteSpace K] [(Valued.v : Valuation K NNReal).RankOne]
  [CompleteSpace ↥𝒪[K]] [Finite 𝓀[K]] [IsGalois K Ω] [IsAlgClosed Ω] in
/-- The intrinsic Proposition 7.55-to-7.64 bridge.  A totally ramified
extension of discrete valuation rings, embedded into the chosen algebraic
closure through its fraction field, lands in the compact Eisenstein family. -/
theorem eisenstein_totally_ramified
    {B L : Type*} [CommRing B] [IsDomain B] [IsDiscreteValuationRing B]
    [Algebra 𝒪[K] B] [Module.Finite 𝒪[K] B]
    [Module.IsTorsionFree 𝒪[K] B]
    [Field L] [Algebra B L] [IsFractionRing B L]
    [Algebra K L] [FiniteDimensional K L] [Algebra 𝒪[K] L]
    [IsScalarTower 𝒪[K] B L] [IsScalarTower 𝒪[K] K L]
    [Algebra.IsSeparable K L] [PerfectField (FractionRing 𝒪[K])]
    (n : ℕ) (j : L →ₐ[K] Ω)
    (hdegree : Module.finrank K L = n + 1)
    (htr : TotallyRamified 𝒪[K] B
      (IsLocalRing.maximalIdeal 𝒪[K])) :
    EisensteinPresentedExtension n j.fieldRange := by
  apply eisenstein_presented_generator
    (B := B) (L := L) n j hdegree
  exact eisenstein_generator_ramified 𝒪[K] B K L htr

/-- Milne, Proposition 7.64, for embedded extensions presented by their
Eisenstein generators.  Unlike the earlier abstract wrapper, this theorem
constructs the coefficient parameter from the Eisenstein polynomial rather
than taking that construction as a hypothesis. -/
theorem eisenstein_presented_fields
    (n : ℕ) (pi : 𝒪[K]) (hpi : Irreducible pi)
    (hna : IsNonarchimedean (norm : Ω → ℝ)) :
    {E : IntermediateField K Ω |
      EisensteinPresentedExtension n E}.Finite := by
  apply (fields_eisenstein_parameters
    (Ω := Ω) n pi hpi hna).subset
  intro E hE
  rcases hE with ⟨f, hfm, hdegree, heis, hroot⟩
  obtain ⟨a, ha⟩ :=
    eisenstein_coefficient_parameters n pi hpi f hfm hdegree heis
  apply Set.mem_iUnion.mpr
  refine ⟨a, ?_⟩
  rw [eisensteinParameterPolynomial, ha]
  exact hroot

/-- Milne, Proposition 7.64, in a fixed algebraic closure.  If every totally
ramified degree `n + 1` field in the chosen ambient algebraic extension is
generated by a root of its Eisenstein polynomial, then the collection of
such fields is finite.  Passing from abstract extensions to chosen images in
an algebraic closure turns this into finiteness up to `K`-isomorphism. -/
theorem totally_fields_representation
    (n : ℕ) (pi : 𝒪[K]) (hpi : Irreducible pi)
    (hna : IsNonarchimedean (norm : Ω → ℝ))
    (TotallyRamifiedOfDegree : IntermediateField K Ω → Prop)
    (hrepresentation : ∀ E, TotallyRamifiedOfDegree E →
      ∃ a : EisensteinCoefficientParameters K NNReal n pi,
        E ∈ polynomialRootFields K Ω
          (eisensteinParameterPolynomial n pi a)) :
    {E : IntermediateField K Ω | TotallyRamifiedOfDegree E}.Finite := by
  apply (fields_eisenstein_parameters
    (Ω := Ω) n pi hpi hna).subset
  intro E hE
  obtain ⟨a, ha⟩ := hrepresentation E hE
  exact Set.mem_iUnion.mpr ⟨a, ha⟩

/-- Milne, Proposition 7.64, with the coefficient parameterization discharged
from intrinsic Eisenstein-generator data.  It is enough to choose, in every
field under consideration, a generator whose integral minimal polynomial is
Eisenstein of the prescribed degree. -/
theorem totally_ramified_fields
    (n : ℕ) (pi : 𝒪[K]) (hpi : Irreducible pi)
    (hna : IsNonarchimedean (norm : Ω → ℝ))
    (TotallyRamifiedOfDegree : IntermediateField K Ω → Prop)
    (hgenerator : ∀ E, TotallyRamifiedOfDegree E →
      ∃ alpha : Ω,
        IsIntegral 𝒪[K] alpha ∧
          (minpoly 𝒪[K] alpha).natDegree = n + 1 ∧
          (minpoly 𝒪[K] alpha).IsEisensteinAt
            (IsLocalRing.maximalIdeal 𝒪[K]) ∧
          E = IntermediateField.adjoin K {alpha}) :
    {E : IntermediateField K Ω | TotallyRamifiedOfDegree E}.Finite := by
  apply totally_fields_representation
    n pi hpi hna TotallyRamifiedOfDegree
  intro E hE
  obtain ⟨alpha, halpha, hdegree, heis, hE⟩ := hgenerator E hE
  obtain ⟨a, ha⟩ := eisenstein_coefficient_parameters
    n pi hpi (minpoly 𝒪[K] alpha) (minpoly.monic halpha) hdegree heis
  refine ⟨a, alpha, ?_, hE⟩
  have hpoly : eisensteinParameterPolynomial n pi a = minpoly K alpha := by
    rw [eisensteinParameterPolynomial, ha]
    exact (minpoly.isIntegrallyClosed_eq_field_fractions' K halpha).symm
  rw [hpoly, Polynomial.mem_aroots]
  exact ⟨minpoly.ne_zero halpha.tower_top,
    minpoly.aeval K alpha⟩

/-- Milne, Proposition 7.64, in fixed-degree generator form.  The degree of
the integral minimal polynomial is deduced from the degree of the generated
intermediate field, so the hypotheses now match the two mathematical inputs:
fixed degree and the Eisenstein-generator characterization of total
ramification from Proposition 7.55. -/
theorem totally_fields_eisenstein
    (n : ℕ) (pi : 𝒪[K]) (hpi : Irreducible pi)
    (hna : IsNonarchimedean (norm : Ω → ℝ))
    (TotallyRamifiedOfDegree : IntermediateField K Ω → Prop)
    (hfinrank : ∀ E, TotallyRamifiedOfDegree E →
      Module.finrank K E = n + 1)
    (hgenerator : ∀ E, TotallyRamifiedOfDegree E →
      ∃ alpha : Ω,
        IsIntegral 𝒪[K] alpha ∧
          (minpoly 𝒪[K] alpha).IsEisensteinAt
            (IsLocalRing.maximalIdeal 𝒪[K]) ∧
          E = IntermediateField.adjoin K {alpha}) :
    {E : IntermediateField K Ω | TotallyRamifiedOfDegree E}.Finite := by
  apply totally_ramified_fields
    n pi hpi hna TotallyRamifiedOfDegree
  intro E hE
  obtain ⟨alpha, halpha, heis, hEalpha⟩ := hgenerator E hE
  refine ⟨alpha, halpha, ?_, heis, hEalpha⟩
  have halphaK : IsIntegral K alpha := halpha.tower_top
  have hadjoinDegree :
      Module.finrank K (IntermediateField.adjoin K {alpha}) = n + 1 := by
    rw [← hEalpha]
    exact hfinrank E hE
  have hminDegreeK : (minpoly K alpha).natDegree = n + 1 := by
    rw [← IntermediateField.adjoin.finrank halphaK]
    exact hadjoinDegree
  calc
    (minpoly 𝒪[K] alpha).natDegree =
        ((minpoly 𝒪[K] alpha).map (algebraMap 𝒪[K] K)).natDegree :=
      ((minpoly.monic halpha).natDegree_map (algebraMap 𝒪[K] K)).symm
    _ = (minpoly K alpha).natDegree := by
      exact congrArg Polynomial.natDegree
        (minpoly.isIntegrallyClosed_eq_field_fractions' K halpha).symm
    _ = n + 1 := hminDegreeK

/-- The intrinsic data asserting that an embedded finite extension is totally
ramified of degree `n + 1`.  The auxiliary ring `B` is its discrete valuation
ring; in the local-field application it is the integral closure of `𝒪[K]` in
`E`, equipped with the uniquely extended valuation. -/
structure TotallyRamifiedDVR
    (n : ℕ) (E : IntermediateField K Ω) where
  B : Type*
  [commRing : CommRing B]
  [isDomain : IsDomain B]
  [discreteValuationRing : IsDiscreteValuationRing B]
  [algebra : Algebra 𝒪[K] B]
  [moduleFinite : Module.Finite 𝒪[K] B]
  [moduleTorsionFree : Module.IsTorsionFree 𝒪[K] B]
  [fractionAlgebra : Algebra B E]
  [isFractionRing : IsFractionRing B E]
  [isScalarTower : IsScalarTower 𝒪[K] B E]
  [finiteDimensional : FiniteDimensional K E]
  finrank_eq : Module.finrank K E = n + 1
  totallyRamified :
    TotallyRamified 𝒪[K] B (IsLocalRing.maximalIdeal 𝒪[K])

/-- Milne, Proposition 7.64, for genuinely totally ramified embedded
extensions.  Proposition 7.55 is used internally: an upstairs uniformizer
has Eisenstein minimal polynomial and generates the fraction field.  Thus the
only family hypothesis is the intrinsic DVR formulation of total
ramification, rather than a preselected Eisenstein generator or coefficient
parameter. -/
theorem totally_dvr_fields
    [CharZero K]
    (n : ℕ) (pi : 𝒪[K]) (hpi : Irreducible pi)
    (hna : IsNonarchimedean (norm : Ω → ℝ)) :
    {E : IntermediateField K Ω |
      Nonempty (TotallyRamifiedDVR n E)}.Finite := by
  apply totally_fields_eisenstein
    n pi hpi hna
    (fun E ↦ Nonempty (TotallyRamifiedDVR n E))
  · intro E hE
    obtain ⟨data⟩ := hE
    exact data.finrank_eq
  · intro E hE
    obtain ⟨data⟩ := hE
    let B := data.B
    letI : CommRing B := data.commRing
    letI : IsDomain B := data.isDomain
    letI : IsDiscreteValuationRing B := data.discreteValuationRing
    letI : Algebra 𝒪[K] B := data.algebra
    letI : Module.Finite 𝒪[K] B := data.moduleFinite
    letI : Module.IsTorsionFree 𝒪[K] B := data.moduleTorsionFree
    letI : Algebra B E := data.fractionAlgebra
    letI : IsFractionRing B E := data.isFractionRing
    letI : IsScalarTower 𝒪[K] B E := data.isScalarTower
    letI : FiniteDimensional K E := data.finiteDimensional
    obtain ⟨Pi, hPi⟩ := IsDiscreteValuationRing.exists_irreducible B
    let beta : E := algebraMap B E Pi
    let alpha : Ω := beta
    have heisB : (minpoly 𝒪[K] Pi).IsEisensteinAt
        (IsLocalRing.maximalIdeal 𝒪[K]) :=
      minpoly_eisenstein_ramified
        𝒪[K] B K E data.totallyRamified Pi hPi
    have hfield : IntermediateField.adjoin K ({beta} : Set E) = ⊤ :=
      fraction_weakly_eisenstein
        𝒪[K] B K E data.totallyRamified Pi hPi
          heisB.isWeaklyEisensteinAt
    have halpha : IsIntegral 𝒪[K] alpha := by
      have hPiInt : IsIntegral 𝒪[K] Pi := Algebra.IsIntegral.isIntegral Pi
      have hbetaInt : IsIntegral 𝒪[K] beta :=
        hPiInt.map (IsScalarTower.toAlgHom 𝒪[K] B E)
      exact hbetaInt.map (E.val.restrictScalars 𝒪[K])
    have hminBeta : minpoly 𝒪[K] beta = minpoly 𝒪[K] Pi := by
      exact minpoly.algebraMap_eq (IsFractionRing.injective B E) Pi
    have hminAlpha : minpoly 𝒪[K] alpha = minpoly 𝒪[K] Pi := by
      calc
        minpoly 𝒪[K] alpha = minpoly 𝒪[K] beta := by
          exact minpoly.algHom_eq
            (E.val.restrictScalars 𝒪[K]) Subtype.val_injective beta
        _ = minpoly 𝒪[K] Pi := hminBeta
    have heisAlpha : (minpoly 𝒪[K] alpha).IsEisensteinAt
        (IsLocalRing.maximalIdeal 𝒪[K]) := by
      rw [hminAlpha]
      exact heisB
    have hE : E = IntermediateField.adjoin K {alpha} := by
      have hmap := congrArg (fun F : IntermediateField K E ↦ F.map E.val) hfield
      change (IntermediateField.adjoin K {beta}).map E.val =
        (⊤ : IntermediateField K E).map E.val at hmap
      rw [← AlgHom.fieldRange_eq_map, IntermediateField.fieldRange_val] at hmap
      simpa [IntermediateField.adjoin_map, beta, alpha] using hmap.symm
    exact ⟨alpha, halpha, heisAlpha, hE⟩

end EisensteinPolynomialFamily

end Submission.NumberTheory.Milne
