import Towers.NumberTheory.ClassGroup.NoExtensionQ
import Mathlib.NumberTheory.RamificationInertia.Galois

/-!
# Milne, Algebraic Number Theory, Two-hour examination, Question 6

For a finite Galois extension of `ℚ`, the inertia groups at the nonzero prime ideals generate
the whole Galois group.  The proof takes the fixed field of the generated subgroup.  Comparison
of absolute and relative inertia groups shows that this fixed field is unramified at every finite
prime, so Theorem 4.9 forces it to be `ℚ`.
-/

namespace Towers.NumberTheory.Milne

open NumberField

noncomputable section

/-- The subgroup generated by the inertia groups at all nonzero prime ideals of a number field. -/
def primeInertiaSubgroup
    (K : Type*) [Field K] [NumberField K] [Algebra ℚ K] :
    Subgroup Gal(K/ℚ) :=
  ⨆ P : {P : Ideal (NumberField.RingOfIntegers K) // P.IsPrime ∧ P ≠ ⊥},
    P.1.inertia Gal(K/ℚ)

/-- Examination Question 6: the inertia groups at all finite primes generate the Galois group
of a finite Galois extension of `ℚ`. -/
theorem inertia_subgroup_top
    (K : Type*) [Field K] [NumberField K] [Algebra ℚ K]
    [FiniteDimensional ℚ K] [IsGalois ℚ K] :
    primeInertiaSubgroup K = ⊤ := by
  classical
  let H : Subgroup Gal(K/ℚ) := primeInertiaSubgroup K
  let E : IntermediateField ℚ K := IntermediateField.fixedField H
  letI : Field E := E.toField
  letI : Algebra ℚ E := E.algebra'
  letI : FiniteDimensional ℚ E := inferInstance
  letI : NumberField E := NumberField.of_module_finite ℚ E
  have hunramified : ∀ (Q : Ideal (NumberField.RingOfIntegers E)) (_ : Q.IsPrime),
      Q ≠ ⊥ → Algebra.IsUnramifiedAt ℤ Q := by
    intro Q hQprime hQ0
    letI : Q.IsPrime := hQprime
    letI : Q.IsMaximal := hQprime.isMaximal hQ0
    obtain ⟨P, hPmax, hPlies⟩ :=
      Ideal.exists_maximal_ideal_liesOver_of_isIntegral Q
        (S := NumberField.RingOfIntegers K)
    letI : P.IsMaximal := hPmax
    letI : P.IsPrime := hPmax.isPrime
    letI : P.LiesOver Q := hPlies
    have hP0 : P ≠ ⊥ := Ideal.ne_bot_of_liesOver_of_ne_bot hQ0 P
    let p : Ideal ℤ := Q.under ℤ
    letI : Q.LiesOver p := by
      exact ⟨rfl⟩
    letI : P.LiesOver p := Ideal.LiesOver.trans P Q p
    have hp0 : p ≠ ⊥ := by
      intro hp
      apply hQ0
      apply Ideal.eq_bot_of_comap_eq_bot (R := ℤ)
      simpa [p] using hp
    letI : p.IsMaximal := Ideal.IsMaximal.under ℤ Q
    letI : Field (ℤ ⧸ p) := Ideal.Quotient.field p
    letI : Field (NumberField.RingOfIntegers K ⧸ P) :=
      Ideal.Quotient.field P
    letI : Finite (ℤ ⧸ p) :=
      Ring.HasFiniteQuotients.finiteQuotient hp0
    letI : PerfectField (ℤ ⧸ p) := PerfectField.ofFinite
    letI : Finite (NumberField.RingOfIntegers K ⧸ P) := inferInstance
    letI : Module.Finite (ℤ ⧸ p) (NumberField.RingOfIntegers K ⧸ P) :=
      Module.Finite.of_finite
    letI : Algebra.IsSeparable (ℤ ⧸ p)
        (NumberField.RingOfIntegers K ⧸ P) := inferInstance
    letI : Finite Gal(K/ℚ) := IsGaloisGroup.finite Gal(K/ℚ) ℚ K
    letI : IsGaloisGroup Gal(K/ℚ) ℤ (NumberField.RingOfIntegers K) :=
      IsGaloisGroup.of_isFractionRing
        Gal(K/ℚ) ℤ (NumberField.RingOfIntegers K) ℚ K
    letI : IsGaloisGroup E.fixingSubgroup E K :=
      IsGaloisGroup.intermediateField Gal(K/ℚ) ℚ K E
    letI := IsIntegralClosure.MulSemiringAction
      (NumberField.RingOfIntegers E) E K
      (NumberField.RingOfIntegers K)
    letI : IsGaloisGroup E.fixingSubgroup
        (NumberField.RingOfIntegers E) (NumberField.RingOfIntegers K) :=
      IsGaloisGroup.of_isFractionRing
        E.fixingSubgroup (NumberField.RingOfIntegers E)
          (NumberField.RingOfIntegers K) E K
    letI : Field (NumberField.RingOfIntegers E ⧸ Q) :=
      Ideal.Quotient.field Q
    letI : IsGalois (NumberField.RingOfIntegers E ⧸ Q)
        (NumberField.RingOfIntegers K ⧸ P) :=
      { __ := Ideal.Quotient.normal
          (A := NumberField.RingOfIntegers E)
          (G := E.fixingSubgroup) Q P }
    letI : Algebra.IsSeparable (NumberField.RingOfIntegers E ⧸ Q)
        (NumberField.RingOfIntegers K ⧸ P) := inferInstance
    have hI_le_H : P.inertia Gal(K/ℚ) ≤ H := by
      exact le_iSup (fun R : {R : Ideal (NumberField.RingOfIntegers K) //
          R.IsPrime ∧ R ≠ ⊥} ↦
        R.1.inertia Gal(K/ℚ)) ⟨P, inferInstance, hP0⟩
    have hI_le_fixing : P.inertia Gal(K/ℚ) ≤ E.fixingSubgroup := by
      change P.inertia Gal(K/ℚ) ≤ (IntermediateField.fixedField H).fixingSubgroup
      rw [IntermediateField.fixingSubgroup_fixedField H]
      exact hI_le_H
    let inertiaEquiv : P.inertia Gal(K/ℚ) ≃
        P.inertia E.fixingSubgroup :=
      { toFun := fun σ ↦ ⟨⟨σ.1, hI_le_fixing σ.2⟩, σ.2⟩
        invFun := fun σ ↦ ⟨σ.1.1, σ.2⟩
        left_inv := fun σ ↦ rfl
        right_inv := fun σ ↦ rfl }
    have hcard :
        Nat.card (P.inertia Gal(K/ℚ)) =
          Nat.card (P.inertia E.fixingSubgroup) :=
      Nat.card_congr inertiaEquiv
    have habsolute :
        Nat.card (P.inertia Gal(K/ℚ)) = p.ramificationIdx P := by
      calc
        Nat.card (P.inertia Gal(K/ℚ)) =
            p.ramificationIdxIn (NumberField.RingOfIntegers K) :=
          Ideal.card_inertia_eq_ramificationIdxIn p hp0 P
        _ = p.ramificationIdx P :=
          Ideal.ramificationIdxIn_eq_ramificationIdx p P Gal(K/ℚ)
    have hrelative :
        Nat.card (P.inertia E.fixingSubgroup) = Q.ramificationIdx P := by
      calc
        Nat.card (P.inertia E.fixingSubgroup) =
            Q.ramificationIdxIn (NumberField.RingOfIntegers K) :=
          Ideal.card_inertia_eq_ramificationIdxIn Q hQ0 P
        _ = Q.ramificationIdx P :=
          Ideal.ramificationIdxIn_eq_ramificationIdx
            Q P E.fixingSubgroup
    have hequal : p.ramificationIdx P = Q.ramificationIdx P := by
      rw [← habsolute, hcard, hrelative]
    have htower := Ideal.ramificationIdx_algebra_tower' p Q P
    rw [hequal] at htower
    have hrelative0 : Q.ramificationIdx P ≠ 0 :=
      Ideal.IsDedekindDomain.ramificationIdx_ne_zero_of_liesOver P hQ0
    have hbase : p.ramificationIdx Q = 1 := by
      have hcancel : 1 * Q.ramificationIdx P =
          p.ramificationIdx Q * Q.ramificationIdx P := by
        simpa using htower
      exact (Nat.mul_right_cancel (Nat.pos_of_ne_zero hrelative0) hcancel).symm
    rw [Algebra.isUnramifiedAt_iff_of_isDedekindDomain (R := ℤ) hQ0]
    simpa [p] using hbase
  set n := Module.finrank ℚ E with hn
  have hn_one : n = 1 := by
    letI : Algebra ℚ E := DivisionRing.toRatAlgebra
    letI : Module ℚ E := Algebra.toModule
    have hfinrankCanonical : Module.finrank ℚ E = 1 :=
      finrank_all_primes E hunramified
    have hfinrankEq : n = Module.finrank ℚ E := by
      rw [hn]
      exact
        @Algebra.finrank_eq_of_equiv_equiv ℚ E _ _ E.algebra' ℚ E _ _
          DivisionRing.toRatAlgebra (RingEquiv.refl ℚ) (RingEquiv.refl E) (by
            ext q
            simp)
    exact hfinrankEq.trans hfinrankCanonical
  have hfinrank : Module.finrank ℚ E = 1 := by
    rw [← hn]
    exact hn_one
  have hE : E = ⊥ := IntermediateField.finrank_eq_one_iff.mp hfinrank
  change H = ⊤
  rw [← IntermediateField.fixingSubgroup_fixedField H]
  change E.fixingSubgroup = ⊤
  rw [hE, IntermediateField.fixingSubgroup_bot]

end

end Towers.NumberTheory.Milne
