import Mathlib.GroupTheory.Commutator.Basic
import Mathlib.GroupTheory.Subgroup.Center
import Mathlib.Algebra.Group.Commute.Basic

/-!
# The Edmonton Notes on Nilpotent Groups: normal generation

This file formalizes Hall's Lemma 1.6.
-/

namespace Submission
namespace Edmonton

open scoped commutatorElement

universe u

/-- The set of basic commutators `[a,b]` with `a ∈ A` and `b ∈ B`. -/
def basicCommutatorSet {G : Type u} [Group G] (A B : Set G) : Set G :=
  {c | ∃ a ∈ A, ∃ b ∈ B, ⁅a, b⁆ = c}

/-- Hall, Lemma 1.6: if `A` generates `G`, then the commutator of the
normal closure of `B` with `G` is normally generated by the basic
commutators `[a,b]`. -/
theorem commutator_closure_commutators
    {G : Type u} [Group G] {A B : Set G}
    (hA : Subgroup.closure A = ⊤) :
    ⁅Subgroup.normalClosure B, (⊤ : Subgroup G)⁆ =
      Subgroup.normalClosure (basicCommutatorSet A B) := by
  let K : Subgroup G := Subgroup.normalClosure (basicCommutatorSet A B)
  let q : G →* G ⧸ K := QuotientGroup.mk' K
  have hb_center : ∀ b ∈ B, q b ∈ Subgroup.center (G ⧸ K) := by
    intro b hb
    rw [Subgroup.mem_center_iff]
    intro z
    obtain ⟨g, rfl⟩ := QuotientGroup.mk'_surjective K z
    have hg : g ∈ Subgroup.closure A := by
      rw [hA]
      exact Subgroup.mem_top g
    change Commute (q g) (q b)
    induction hg using Subgroup.closure_induction with
    | mem a ha =>
        rw [← commutatorElement_eq_one_iff_commute, ← map_commutatorElement]
        simpa only [QuotientGroup.mk'_apply] using
          (QuotientGroup.eq_one_iff (N := K) ⁅a, b⁆).mpr
            (Subgroup.subset_normalClosure ⟨a, ha, b, hb, rfl⟩)
    | one => simp
    | mul a₁ a₂ _ _ ha₁ ha₂ => simpa using ha₁.mul_left ha₂
    | inv a _ ha => simpa using Commute.inv_left ha
  have hmap_center :
      (Subgroup.normalClosure B).map q ≤ Subgroup.center (G ⧸ K) := by
    rw [Subgroup.map_normalClosure B q (QuotientGroup.mk'_surjective K)]
    apply Subgroup.normalClosure_le_normal
    rintro z ⟨b, hb, rfl⟩
    exact hb_center b hb
  apply le_antisymm
  · rw [Subgroup.commutator_le]
    intro h hh g _
    apply (QuotientGroup.eq_one_iff (N := K) ⁅h, g⁆).mp
    change q ⁅h, g⁆ = 1
    rw [map_commutatorElement, commutatorElement_eq_one_iff_commute]
    exact (Subgroup.mem_center_iff.mp
      (hmap_center (Subgroup.mem_map_of_mem q hh)) (q g)).symm
  · change K ≤ ⁅Subgroup.normalClosure B, (⊤ : Subgroup G)⁆
    apply Subgroup.normalClosure_le_normal
    rintro c ⟨a, ha, b, hb, rfl⟩
    rw [Subgroup.commutator_comm]
    exact Subgroup.commutator_mem_commutator
      (Subgroup.mem_top a) (Subgroup.subset_normalClosure hb)

end Edmonton
end Submission
