import Submission.Group.Edmonton.CyclicCentralSeries
import Mathlib.GroupTheory.Solvable
import Mathlib.GroupTheory.QuotientGroup.Basic
import Mathlib.GroupTheory.SpecificGroups.Cyclic.Basic

/-!
# The Edmonton Notes on Nilpotent Groups: polycyclic and supersoluble groups

This file introduces the series conditions appearing after Hall's Theorem 1.8
and begins the formalization of Lemma 1.9.
-/

namespace Submission
namespace Edmonton

open Group
open scoped commutatorElement

universe u

/-- A finite series with cyclic factors, subject to a chosen normality
condition on each adjacent pair.

The explicit commutator condition records that each generated factor is
abelian.  It is mathematically redundant with normality and one-generator
generation, but is useful when consuming a series without repeatedly
reconstructing its quotient group.
-/
inductive HCSeries (G : Type u) [Group G]
    (NormalStep : Subgroup G → Subgroup G → Prop) :
    Subgroup G → Subgroup G → Prop
  | refl (H : Subgroup G) : HCSeries G NormalStep H H
  | step {H K L : Subgroup G}
      (hK_le_H : K ≤ H)
      (hnormal : NormalStep K H)
      (hcomm : ⁅H, H⁆ ≤ K)
      (hcyclic : ∃ x ∈ H, H = Subgroup.closure ((K : Set G) ∪ {x}))
      (tail : HCSeries G NormalStep K L) :
      HCSeries G NormalStep H L

namespace HCSeries

/-- Concatenation of cyclic series with the same normality condition. -/
theorem trans {G : Type u} [Group G]
    {NormalStep : Subgroup G → Subgroup G → Prop}
    {H K L : Subgroup G}
    (hHK : HCSeries G NormalStep H K)
    (hKL : HCSeries G NormalStep K L) :
    HCSeries G NormalStep H L := by
  induction hHK with
  | refl => exact hKL
  | step hM_le_H hnormal hcomm hcyclic _ ih =>
      exact .step hM_le_H hnormal hcomm hcyclic (ih hKL)

end HCSeries

/-- A group is polycyclic if it has a finite cyclic series in which every
lower term is normal in the preceding term. -/
def IsPolycyclic (G : Type u) [Group G] : Prop :=
  HCSeries G
    (fun K H ↦ (K.subgroupOf H).Normal)
    (⊤ : Subgroup G) (⊥ : Subgroup G)

/-- A group is supersoluble if it has a finite cyclic series all of whose
terms are normal in the ambient group. -/
def IsSupersoluble (G : Type u) [Group G] : Prop :=
  HCSeries G
    (fun K _ ↦ K.Normal)
    (⊤ : Subgroup G) (⊥ : Subgroup G)

/-- Hall's maximal condition `Max`: every subgroup is finitely generated. -/
def SatisfiesMaximalCondition (G : Type u) [Group G] : Prop :=
  ∀ H : Subgroup G, H.FG

/-- A cyclic central series is, in particular, a supersoluble series. -/
theorem CSeries.toSupersolubleSeries
    {G : Type u} [Group G] {H L : Subgroup G}
    (h : CSeries G H L) :
    HCSeries G (fun K _ ↦ K.Normal) H L := by
  induction h with
  | refl => exact .refl _
  | step hK_le_H hK_normal hcentral hcyclic _ ih =>
      exact .step hK_le_H hK_normal
        ((Subgroup.commutator_mono le_rfl le_top).trans hcentral)
        hcyclic ih

/-- A supersoluble series is, in particular, a polycyclic series. -/
theorem supersoluble_series_polycyclic
    {G : Type u} [Group G] {H L : Subgroup G}
    (h : HCSeries G (fun K _ ↦ K.Normal) H L) :
    HCSeries G (fun K H ↦ (K.subgroupOf H).Normal) H L := by
  induction h with
  | refl => exact .refl _
  | step hK_le_H hK_normal hcomm hcyclic _ ih =>
      have hK_normal_H : _ :=
        (Subgroup.normal_subgroupOf_iff hK_le_H).mpr fun k h hk _ ↦
          hK_normal.conj_mem k hk h
      exact .step hK_le_H hK_normal_H hcomm hcyclic ih

/-- The first implication in Hall, Lemma 1.9(i). -/
theorem fg_implies_supersoluble
    {G : Type u} [Group G] [Group.FG G] [Group.IsNilpotent G] :
    IsSupersoluble G :=
  cyclic_central_series.toSupersolubleSeries

/-- The second implication in Hall, Lemma 1.9(i). -/
theorem supersoluble_implies_polycyclic
    {G : Type u} [Group G] :
    IsSupersoluble G → IsPolycyclic G :=
  supersoluble_series_polycyclic

/-- If the commutator subgroup of `H` lies in `K ≤ H`, then `K` is normal
in `H`. -/
theorem normal_subgroup_commutator
    {G : Type u} [Group G] {K H : Subgroup G}
    (hK_le_H : K ≤ H) (hcomm : ⁅H, H⁆ ≤ K) :
    (K.subgroupOf H).Normal := by
  rw [Subgroup.normal_subgroupOf_iff hK_le_H]
  intro k h hk hh
  have hhk : ⁅h, k⁆ ∈ K :=
    hcomm (Subgroup.commutator_mem_commutator hh (hK_le_H hk))
  rw [show h * k * h⁻¹ = ⁅h, k⁆ * k by
    simp [commutatorElement_def, mul_assoc]]
  exact K.mul_mem hhk hk

/-- A subgroup generated by a normal subgroup and one element has cyclic
quotient by that normal subgroup. -/
theorem cyclic_subgroup_generated
    {G : Type u} [Group G] {K H : Subgroup G}
    (hK_le_H : K ≤ H) (hK_normal : (K.subgroupOf H).Normal)
    {x : G} (hx : x ∈ H)
    (hgen : H = Subgroup.closure ((K : Set G) ∪ {x})) :
    (let _ : (K.subgroupOf H).Normal := hK_normal;
      IsCyclic (H ⧸ K.subgroupOf H)) := by
  subst H
  let K' : Subgroup (Subgroup.closure ((K : Set G) ∪ {x})) :=
    K.subgroupOf (Subgroup.closure ((K : Set G) ∪ {x}))
  letI : K'.Normal := hK_normal
  let xH : Subgroup.closure ((K : Set G) ∪ {x}) := ⟨x, hx⟩
  let q := QuotientGroup.mk' K'
  apply isCyclic_iff_exists_zpowers_eq_top.mpr
  refine ⟨q xH, ?_⟩
  apply eq_top_iff.mpr
  rintro z -
  obtain ⟨h, rfl⟩ := QuotientGroup.mk'_surjective K' z
  have hh :
      h ∈ Subgroup.closure
        ((Subgroup.closure ((K : Set G) ∪ {x})).subtype ⁻¹'
          ((K : Set G) ∪ {x})) := by
    rw [Subgroup.closure_preimage_eq_top]
    exact Subgroup.mem_top h
  induction hh using Subgroup.closure_induction with
  | mem h hh =>
      rcases hh with hhK | hhx
      · have hq : q h = 1 := (QuotientGroup.eq_one_iff h).mpr hhK
        rw [hq]
        exact Subgroup.one_mem _
      · have hhxH : h = xH := Subtype.ext (Set.mem_singleton_iff.mp hhx)
        rw [hhxH]
        exact Subgroup.mem_zpowers _
  | one => simp
  | mul a b _ _ ha hb => simpa using (Subgroup.zpowers (q xH)).mul_mem ha hb
  | inv a _ ha => simpa using (Subgroup.zpowers (q xH)).inv_mem ha

/-- If `H / K` is generated by one element, then the image of every subgroup
`P ≤ H` is generated by one element as well.  Equivalently, `P` is generated
by `P ∩ K` and one element of `P`. -/
theorem generator_inf_generated
    {G : Type u} [Group G] {K H P : Subgroup G}
    (hK_le_H : K ≤ H) (hK_normal : (K.subgroupOf H).Normal)
    (hP_le_H : P ≤ H) {x : G} (hx : x ∈ H)
    (hgen : H = Subgroup.closure ((K : Set G) ∪ {x})) :
    ∃ y ∈ P, P = Subgroup.closure (((P ⊓ K : Subgroup G) : Set G) ∪ {y}) := by
  classical
  let K' : Subgroup H := K.subgroupOf H
  letI : K'.Normal := hK_normal
  let P' : Subgroup H := P.subgroupOf H
  let q := QuotientGroup.mk' K'
  haveI hquotient_cyclic : IsCyclic (H ⧸ K') :=
    cyclic_subgroup_generated hK_le_H hK_normal hx hgen
  let M : Subgroup (H ⧸ K') := P'.map q
  haveI hM_cyclic : IsCyclic M := Subgroup.isCyclic M
  obtain ⟨z, hz⟩ :=
    (M.isCyclic_iff_exists_zpowers_eq_top).mp hM_cyclic
  have hzM : z ∈ M := by
    rw [← hz]
    exact Subgroup.mem_zpowers z
  obtain ⟨yH, hyP, hyq⟩ := hzM
  refine ⟨yH.1, hyP, ?_⟩
  let R : Subgroup G :=
    Subgroup.closure (((P ⊓ K : Subgroup G) : Set G) ∪ {yH.1})
  change P = R
  apply le_antisymm
  · intro p hp
    let pH : H := ⟨p, hP_le_H hp⟩
    have hqpM : q pH ∈ M := Subgroup.mem_map_of_mem q hp
    have hqpZ : q pH ∈ Subgroup.zpowers z := by
      rw [hz]
      exact hqpM
    obtain ⟨a, ha⟩ := Subgroup.mem_zpowers_iff.mp hqpZ
    have hdP : p * (yH.1 ^ a)⁻¹ ∈ P :=
      P.mul_mem hp (P.inv_mem (P.zpow_mem hyP a))
    have hdK : p * (yH.1 ^ a)⁻¹ ∈ K := by
      have hdK' : pH * (yH ^ a)⁻¹ ∈ K' := by
        apply (QuotientGroup.eq_one_iff
          (pH * (yH ^ a)⁻¹)).mp
        change q (pH * (yH ^ a)⁻¹) = 1
        simp [hyq, ha]
      exact hdK'
    have hdR : p * (yH.1 ^ a)⁻¹ ∈ R :=
      Subgroup.subset_closure (Or.inl ⟨hdP, hdK⟩)
    have hyR : yH.1 ^ a ∈ R :=
      R.zpow_mem (Subgroup.subset_closure (Or.inr (Set.mem_singleton yH.1))) a
    rw [show p = (p * (yH.1 ^ a)⁻¹) * yH.1 ^ a by simp]
    exact R.mul_mem hdR hyR
  · rw [Subgroup.closure_le]
    rintro y (hy | hy)
    · exact hy.1
    · rw [Set.mem_singleton_iff.mp hy]
      exact hyP

/-- If the endpoint of a polycyclic series has all its subgroups finitely
generated, then so does its starting subgroup. -/
theorem HCSeries.all_subgroups_fgbelow
    {G : Type u} [Group G] {H L : Subgroup G}
    (h : HCSeries G (fun K J ↦ (K.subgroupOf J).Normal) H L)
    (hL : ∀ P : Subgroup G, P ≤ L → P.FG) :
    ∀ P : Subgroup G, P ≤ H → P.FG := by
  induction h with
  | refl => exact hL
  | @step H K L hK_le_H hK_normal _ hcyclic _ ih =>
      intro P hP_le_H
      obtain ⟨x, hx, hgen⟩ := hcyclic
      obtain ⟨y, hy, hPgen⟩ :=
        generator_inf_generated
          hK_le_H hK_normal hP_le_H hx hgen
      have hInfFG : (P ⊓ K).FG := ih hL (P ⊓ K) inf_le_right
      have hyFG : (Subgroup.closure ({y} : Set G)).FG :=
        (Subgroup.fg_iff _).mpr ⟨{y}, rfl, Set.finite_singleton y⟩
      rw [hPgen, Subgroup.closure_union, Subgroup.closure_eq]
      exact hInfFG.sup hyFG

/-- A finite set of generators modulo a subgroup containing the upper
subgroup's commutator gives a polycyclic refinement. -/
theorem polycyclic_series_closure {G : Type u} [Group G]
    (N : Subgroup G) :
    ∀ (S : Set G), S.Finite →
      ⁅Subgroup.closure ((N : Set G) ∪ S),
        Subgroup.closure ((N : Set G) ∪ S)⁆ ≤ N →
      HCSeries G (fun K H ↦ (K.subgroupOf H).Normal)
        (Subgroup.closure ((N : Set G) ∪ S)) N := by
  intro S hS
  induction S, hS using Set.Finite.induction_on with
  | empty =>
      intro _
      simpa using
        (HCSeries.refl N :
          HCSeries G (fun K H ↦ (K.subgroupOf H).Normal) N N)
  | @insert a S ha hS ih =>
      intro hcomm
      let K : Subgroup G := Subgroup.closure ((N : Set G) ∪ S)
      let H : Subgroup G := Subgroup.closure ((N : Set G) ∪ insert a S)
      have hK_le_H : K ≤ H := by
        apply Subgroup.closure_mono
        intro x hx
        rcases hx with hx | hx
        · exact Or.inl hx
        · exact Or.inr (Set.mem_insert_of_mem a hx)
      have hN_le_K : N ≤ K := by
        intro x hx
        exact Subgroup.subset_closure (Or.inl hx)
      have hKcomm : ⁅K, K⁆ ≤ N :=
        (Subgroup.commutator_mono hK_le_H hK_le_H).trans hcomm
      have htail :
          HCSeries G (fun M J ↦ (M.subgroupOf J).Normal) K N :=
        ih hKcomm
      have haH : a ∈ H :=
        Subgroup.subset_closure (Or.inr (Set.mem_insert a S))
      have hcyclic : H = Subgroup.closure ((K : Set G) ∪ {a}) := by
        change Subgroup.closure ((N : Set G) ∪ insert a S) =
          Subgroup.closure
            ((Subgroup.closure ((N : Set G) ∪ S) : Set G) ∪ {a})
        simp only [Set.insert_eq, Subgroup.closure_union, Subgroup.closure_eq]
        ac_rfl
      have hcommK : ⁅H, H⁆ ≤ K := hcomm.trans hN_le_K
      exact HCSeries.step hK_le_H
        (normal_subgroup_commutator hK_le_H hcommK)
        hcommK ⟨a, haH, hcyclic⟩ htail

/-- Named-upper-subgroup form of the finite polycyclic refinement lemma. -/
theorem polycyclic_generators_mod
    {G : Type u} [Group G] {H N : Subgroup G} {S : Set G}
    (hS : S.Finite) (hcomm : ⁅H, H⁆ ≤ N)
    (hgen : H = Subgroup.closure ((N : Set G) ∪ S)) :
    HCSeries G (fun K J ↦ (K.subgroupOf J).Normal) H N := by
  subst H
  exact polycyclic_series_closure N S hS hcomm

/-- Under `Max`, each adjacent pair in the derived series has a finite
polycyclic refinement. -/
theorem derived_polycyclic_succ
    {G : Type u} [Group G] (hmax : SatisfiesMaximalCondition G) (n : ℕ) :
    HCSeries G (fun K H ↦ (K.subgroupOf H).Normal)
      (derivedSeries G n) (derivedSeries G (n + 1)) := by
  obtain ⟨S, hSgen, hSfin⟩ :=
    (Subgroup.fg_iff (derivedSeries G n)).mp (hmax (derivedSeries G n))
  apply polycyclic_generators_mod hSfin
  · exact le_rfl
  · apply le_antisymm
    · rw [← hSgen]
      exact Subgroup.closure_mono fun _ hx ↦ Or.inr hx
    · rw [Subgroup.closure_le]
      rintro x (hx | hx)
      · exact derivedSeries_antitone G (Nat.le_succ n) hx
      · rw [← hSgen]
        exact Subgroup.subset_closure hx

/-- A cyclic series from `H` to `L` forces some sufficiently late derived
term lying in `H` to lie in `L`. -/
theorem HCSeries.exists_derivedseries_leendpt
    {G : Type u} [Group G]
    {NormalStep : Subgroup G → Subgroup G → Prop}
    {H L : Subgroup G} (h : HCSeries G NormalStep H L) :
  ∀ {n : ℕ}, derivedSeries G n ≤ H →
      ∃ m : ℕ, derivedSeries G m ≤ L := by
  intro n hn
  induction h generalizing n with
  | refl => exact ⟨n, hn⟩
  | step _ _ hcomm _ _ ih =>
      apply ih (n := n + 1)
      exact (Subgroup.commutator_mono hn hn).trans hcomm

/-- Every polycyclic group is soluble. -/
theorem polycyclic_implies_solvable {G : Type u} [Group G] :
    IsPolycyclic G → IsSolvable G := by
  intro hpoly
  obtain ⟨n, hn⟩ :=
    hpoly.exists_derivedseries_leendpt
      (n := 0) (by exact le_top)
  exact ⟨⟨n, le_bot_iff.mp hn⟩⟩

/-- Every polycyclic group satisfies Hall's maximal condition `Max`. -/
theorem polycyclic_implies_condition {G : Type u} [Group G] :
    IsPolycyclic G → SatisfiesMaximalCondition G := by
  intro hpoly
  unfold SatisfiesMaximalCondition
  intro P
  apply hpoly.all_subgroups_fgbelow
    (fun Q hQ ↦ by
      rw [le_bot_iff.mp hQ]
      exact Subgroup.FG.bot)
    P le_top

/-- The reverse implication in Hall, Lemma 1.9(i): a soluble group
satisfying `Max` is polycyclic. -/
theorem condition_implies_polycyclic
    {G : Type u} [Group G] [hsolv : IsSolvable G]
    (hmax : SatisfiesMaximalCondition G) :
    IsPolycyclic G := by
  obtain ⟨n, hn⟩ := hsolv.solvable
  have hseries :
      ∀ m : ℕ,
        HCSeries G (fun K H ↦ (K.subgroupOf H).Normal)
          (derivedSeries G 0) (derivedSeries G m) := by
    intro m
    induction m with
    | zero => exact .refl _
    | succ m ih =>
        exact ih.trans (derived_polycyclic_succ hmax m)
  simpa [IsPolycyclic, hn] using hseries n

/-- Hall, Lemma 1.9(i), equivalence clause. -/
theorem polycyclic_solvable_condition
    {G : Type u} [Group G] :
    IsPolycyclic G ↔ IsSolvable G ∧ SatisfiesMaximalCondition G := by
  constructor
  · intro hpoly
    exact ⟨polycyclic_implies_solvable hpoly,
      polycyclic_implies_condition hpoly⟩
  · rintro ⟨hsolv, hmax⟩
    letI : IsSolvable G := hsolv
    exact condition_implies_polycyclic hmax

end Edmonton
end Submission
