import Mathlib.GroupTheory.FreeGroup.Basic
import Mathlib.GroupTheory.Commutator.Basic
import Mathlib.GroupTheory.Nilpotent
import Mathlib.Algebra.Group.Commute.Basic

/-!
# The Edmonton Notes on Nilpotent Groups: verbal subgroups

This file formalizes Hall's definition of a word and Lemma 1.5. A word in
variables indexed by `α` is represented by an element of the free group on
`α`. Its verbal subgroup in `G` is generated by all evaluations of the word
in `G`.
-/

namespace Submission
namespace Edmonton

open scoped commutatorElement

universe u v w

/-- Evaluate a group word under an assignment of its variables. -/
def wordEval {α : Type u} {G : Type v} [Group G] (word : FreeGroup α) (f : α → G) : G :=
  FreeGroup.lift f word

/-- The set of all values of a group word in a group. -/
def wordValueSet {α : Type u} (word : FreeGroup α) (G : Type v) [Group G] : Set G :=
  Set.range (wordEval word)

/-- The verbal subgroup generated by all values of a group word. -/
def verbalSubgroup {α : Type u} (word : FreeGroup α) (G : Type v) [Group G] : Subgroup G :=
  Subgroup.closure (wordValueSet word G)

theorem wordEval_map {α : Type u} {β : Type v} {G : Type w} [Group G]
    (word : FreeGroup α) (f : α → β) (g : β → G) :
    wordEval (FreeGroup.map f word) g = wordEval word (g ∘ f) := by
  simpa [wordEval, MonoidHom.comp_apply] using
    (FreeGroup.lift_unique (f := g ∘ f)
      ((FreeGroup.lift g).comp (FreeGroup.map f)) (by intro x; simp) (x := word))

theorem wordEval_conjugate {α : Type u} {G : Type v} [Group G]
    (word : FreeGroup α) (f : α → G) (g : G) :
    wordEval word (fun x ↦ g * f x * g⁻¹) = g * wordEval word f * g⁻¹ := by
  symm
  simpa [wordEval, MonoidHom.comp_apply, MulAut.conj_apply] using
    (FreeGroup.lift_unique (f := fun x ↦ g * f x * g⁻¹)
      ((MulAut.conj g).toMonoidHom.comp (FreeGroup.lift f))
      (by intro x; simp [MulAut.conj_apply]) (x := word))

theorem value_set_conj {α : Type u} {G : Type v} [Group G]
    {word : FreeGroup α} {x : G} (hx : x ∈ wordValueSet word G) (g : G) :
    g * x * g⁻¹ ∈ wordValueSet word G := by
  obtain ⟨f, rfl⟩ := hx
  exact ⟨fun a ↦ g * f a * g⁻¹, wordEval_conjugate word f g⟩

instance verbalSubgroup_normal {α : Type u} {G : Type v} [Group G]
    (word : FreeGroup α) : (verbalSubgroup word G).Normal := by
  rw [verbalSubgroup]
  constructor
  intro x hx g
  induction hx using Subgroup.closure_induction with
  | mem x hx =>
      exact Subgroup.subset_closure (value_set_conj hx g)
  | one => simp
  | mul x y _ _ hx hy =>
      rw [← conj_mul]
      exact Subgroup.mul_mem _ hx hy
  | inv x _ hx =>
      rw [← conj_inv]
      exact Subgroup.inv_mem _ hx

/-- Hall's observation that a verbal subgroup is fully invariant. -/
theorem verbal_subgroup {α : Type u} {G : Type v} [Group G]
    (word : FreeGroup α) (f : G →* G) :
    (verbalSubgroup word G).map f ≤ verbalSubgroup word G := by
  rw [verbalSubgroup, MonoidHom.map_closure, Subgroup.closure_le]
  rintro _ ⟨x, ⟨a, rfl⟩, rfl⟩
  exact Subgroup.subset_closure
    ⟨fun i ↦ f (a i), by
      simpa [wordEval, MonoidHom.comp_apply] using
        (FreeGroup.lift_unique (f := fun i ↦ f (a i))
          (f.comp (FreeGroup.lift a)) (by intro i; simp) (x := word)).symm⟩

/-- A reusable quotient argument: pairwise commutators of generating sets
control the commutator of the generated subgroups. -/
theorem commutator_closure_pairwise {G : Type u} [Group G]
    {A B : Set G} {N : Subgroup G} [N.Normal]
    (h : ∀ a ∈ A, ∀ b ∈ B, ⁅a, b⁆ ∈ N) :
    ⁅Subgroup.closure A, Subgroup.closure B⁆ ≤ N := by
  rw [Subgroup.commutator_le]
  intro x hx y hy
  let q : G →* G ⧸ N := QuotientGroup.mk' N
  have hcomm : Commute (q x) (q y) := by
    induction hy using Subgroup.closure_induction with
    | mem b hb =>
        induction hx using Subgroup.closure_induction with
        | mem a ha =>
            rw [← commutatorElement_eq_one_iff_commute, ← map_commutatorElement]
            simpa only [QuotientGroup.mk'_apply] using
              (QuotientGroup.eq_one_iff (N := N) ⁅a, b⁆).mpr (h a ha b hb)
        | one => simp
        | mul a₁ a₂ _ _ ha₁ ha₂ => simpa using ha₁.mul_left ha₂
        | inv a _ ha => simpa using Commute.inv_left ha
    | one => simp
    | mul b₁ b₂ _ _ hb₁ hb₂ => simpa using hb₁.mul_right hb₂
    | inv b _ hb => simpa using Commute.inv_right hb
  apply (QuotientGroup.eq_one_iff _).mp
  change q ⁅x, y⁆ = 1
  rw [map_commutatorElement, commutatorElement_eq_one_iff_commute]
  exact hcomm

/-- The commutator of two words on disjoint sets of variables. -/
def wordCommutator {α : Type u} {β : Type v}
    (theta : FreeGroup α) (phi : FreeGroup β) : FreeGroup (α ⊕ β) :=
  ⁅FreeGroup.map (Sum.inl : α → α ⊕ β) theta,
    FreeGroup.map (Sum.inr : β → α ⊕ β) phi⁆

theorem commutator_value_set {α : Type u} {β : Type v}
    {G : Type w} [Group G] {theta : FreeGroup α} {phi : FreeGroup β}
    {a b : G} (ha : a ∈ wordValueSet theta G) (hb : b ∈ wordValueSet phi G) :
    ⁅a, b⁆ ∈ wordValueSet (wordCommutator theta phi) G := by
  obtain ⟨f, rfl⟩ := ha
  obtain ⟨g, rfl⟩ := hb
  refine ⟨Sum.elim f g, ?_⟩
  rw [wordCommutator, wordEval, map_commutatorElement]
  change
    ⁅wordEval (FreeGroup.map (Sum.inl : α → α ⊕ β) theta) (Sum.elim f g),
      wordEval (FreeGroup.map (Sum.inr : β → α ⊕ β) phi) (Sum.elim f g)⁆ =
      ⁅wordEval theta f, wordEval phi g⁆
  rw [wordEval_map, wordEval_map]
  rfl

/-- Hall, Lemma 1.5: the verbal subgroup of the commutator of two words is
the commutator of their verbal subgroups. -/
theorem verbal_subgroup_commutator {α : Type u} {β : Type v} {G : Type w} [Group G]
    (theta : FreeGroup α) (phi : FreeGroup β) :
    verbalSubgroup (wordCommutator theta phi) G =
      ⁅verbalSubgroup theta G, verbalSubgroup phi G⁆ := by
  apply le_antisymm
  · rw [verbalSubgroup, Subgroup.closure_le]
    intro x hx
    obtain ⟨f, rfl⟩ := hx
    rw [wordCommutator, wordEval, map_commutatorElement]
    change
      ⁅wordEval (FreeGroup.map (Sum.inl : α → α ⊕ β) theta) f,
        wordEval (FreeGroup.map (Sum.inr : β → α ⊕ β) phi) f⁆ ∈
        ⁅verbalSubgroup theta G, verbalSubgroup phi G⁆
    rw [wordEval_map, wordEval_map]
    exact Subgroup.commutator_mem_commutator
      (Subgroup.subset_closure ⟨f ∘ Sum.inl, rfl⟩)
      (Subgroup.subset_closure ⟨f ∘ Sum.inr, rfl⟩)
  · apply commutator_closure_pairwise
    intro a ha b hb
    exact Subgroup.subset_closure (commutator_value_set ha hb)

/-- The verbal subgroup of a single free generator is the whole group. -/
theorem verbal_variable_top
    (G : Type v) [Group G] :
    verbalSubgroup (FreeGroup.of PUnit.unit) G = ⊤ := by
  rw [verbalSubgroup, eq_top_iff]
  intro g _
  apply Subgroup.subset_closure
  refine ⟨fun _ => g, ?_⟩
  simp [wordEval]

/-- **Corollary to Hall, Lemma 1.5.** Every lower-central term is a
verbal subgroup: for each zero-based index `n`, there is a finite-variable
word whose verbal subgroup is `γ_(n+1)(G)`. -/
theorem lower_series_verbal
    (G : Type v) [Group G] :
    ∀ n : ℕ, ∃ α : Type, ∃ word : FreeGroup α,
      verbalSubgroup word G = Subgroup.lowerCentralSeries G n := by
  intro n
  induction n with
  | zero =>
      exact ⟨PUnit, FreeGroup.of PUnit.unit,
        verbal_variable_top G⟩
  | succ n ih =>
      obtain ⟨α, word, hword⟩ := ih
      refine ⟨α ⊕ PUnit,
        wordCommutator word (FreeGroup.of PUnit.unit), ?_⟩
      rw [verbal_subgroup_commutator, hword, verbal_variable_top]
      rfl

end Edmonton
end Submission
