import Mathlib.NumberTheory.NumberField.CMField
import Mathlib.NumberTheory.NumberField.Cyclotomic.Ideal
import Mathlib.Algebra.Polynomial.Degree.IsMonicOfDegree

/-!
# Milne, Algebraic Number Theory, the maximal real cyclotomic subfield

For a primitive `n`th root of unity `ζ`, with `n > 2`, the maximal real subfield of
`ℚ(ζ)` is generated by `ζ + ζ⁻¹`.
-/

namespace Submission.NumberTheory.Milne

open Algebra NumberField NumberField.Units Polynomial
open scoped NumberField Polynomial

namespace CMReal

variable {n : ℕ} {K : Type*} [Field K] [CharZero K] [NeZero n]
  [IsCyclotomicExtension {n} ℚ K]

noncomputable def rootUnit {ζ : K} (hζ : IsPrimitiveRoot ζ n) : (𝓞 K)ˣ :=
  (hζ.toInteger_isPrimitiveRoot.isUnit (NeZero.ne n)).unit

omit [CharZero K] [IsCyclotomicExtension {n} ℚ K] in
theorem rootUnit_coe {ζ : K} (hζ : IsPrimitiveRoot ζ n) :
    ((rootUnit hζ : (𝓞 K)ˣ) : 𝓞 K) = hζ.toInteger := by
  exact (hζ.toInteger_isPrimitiveRoot.isUnit (NeZero.ne n)).unit_spec

omit [CharZero K] [IsCyclotomicExtension {n} ℚ K] in
theorem root_unit_torsion {ζ : K} (hζ : IsPrimitiveRoot ζ n) :
    rootUnit hζ ∈ torsion K := by
  rw [torsion, CommGroup.mem_torsion]
  exact (hζ.toInteger_isPrimitiveRoot.isUnit_unit (NeZero.ne n)).isOfFinOrder (NeZero.ne n)

variable [NumberField K] [NumberField.IsCMField K]

omit [IsCyclotomicExtension {n} ℚ K] in
@[simp]
theorem complexConj_zeta {ζ : K} (hζ : IsPrimitiveRoot ζ n) :
    NumberField.IsCMField.complexConj K ζ = ζ⁻¹ := by
  let η : torsion K := ⟨rootUnit hζ, root_unit_torsion hζ⟩
  have ht := NumberField.IsCMField.complexConj_torsion K η
  simpa [η, rootUnit_coe] using ht

omit [IsCyclotomicExtension {n} ℚ K] in
/-- Complex conjugation sends the integral primitive root to its inverse unit. -/
theorem ring_integers_complex {ζ : K} (hζ : IsPrimitiveRoot ζ n) :
    NumberField.IsCMField.ringOfIntegersComplexConj K (rootUnit hζ : 𝓞 K) =
      ((rootUnit hζ)⁻¹ : (𝓞 K)ˣ) := by
  apply RingOfIntegers.ext
  simpa [rootUnit_coe] using complexConj_zeta hζ

end CMReal

open CMReal

variable {n : ℕ} {K : Type*} [Field K] [CharZero K] [NeZero n]
  [IsCyclotomicExtension {n} ℚ K]

/-- If `ζ` is a primitive `n`th root of unity with `n > 2`, then `ζ + ζ⁻¹`
generates the maximal real subfield of the cyclotomic field. -/
theorem maximal_real_subfield
    {ζ : K} (hζ : IsPrimitiveRoot ζ n) (hn : 2 < n) :
    (IntermediateField.adjoin ℚ ({ζ + ζ⁻¹} : Set K)).toSubfield =
      NumberField.maximalRealSubfield K := by
  letI : NumberField K := IsCyclotomicExtension.numberField {n} ℚ K
  letI : NumberField.IsCMField K :=
    IsCyclotomicExtension.Rat.isCMField K ⟨n, Set.mem_singleton n, hn⟩
  let E : IntermediateField ℚ K := IntermediateField.adjoin ℚ {ζ + ζ⁻¹}
  have hfixed : NumberField.IsCMField.complexConj K (ζ + ζ⁻¹) = ζ + ζ⁻¹ := by
    simp [complexConj_zeta hζ, add_comm]
  have hgen : ζ + ζ⁻¹ ∈ NumberField.maximalRealSubfield K :=
    (NumberField.IsCMField.complexConj_eq_self_iff K (ζ + ζ⁻¹)).mp hfixed
  have hE_le : E.toSubfield ≤ NumberField.maximalRealSubfield K := by
    let M : IntermediateField ℚ K :=
      (NumberField.maximalRealSubfield K).toIntermediateField fun x ↦ by
        rw [NumberField.mem_maximalRealSubfield_iff]
        intro φ
        simp
    have hEM : E ≤ M := by
      apply IntermediateField.adjoin_le_iff.mpr
      intro x hx
      rw [Set.mem_singleton_iff] at hx
      subst x
      exact hgen
    intro x hx
    exact hEM hx
  haveI : NumberField.IsTotallyReal E.toSubfield :=
    (NumberField.isTotallyReal_iff_le_maximalRealSubfield).2 hE_le
  let a : E := ⟨ζ + ζ⁻¹, IntermediateField.subset_adjoin ℚ {ζ + ζ⁻¹}
    (Set.mem_singleton (ζ + ζ⁻¹))⟩
  let p : E[X] := X ^ 2 - C a * X + 1
  have hp_degree : p.IsMonicOfDegree 2 := by
    simpa [p] using Polynomial.isMonicOfDegree_sub_add_two a (1 : E)
  have hp_monic : p.Monic := by
    exact hp_degree.monic
  have hp_root : aeval ζ p = 0 := by
    dsimp [p]
    simp only [map_add, map_sub, map_pow, aeval_X, aeval_C, aeval_one, map_mul]
    change ζ ^ 2 - (ζ + ζ⁻¹) * ζ + 1 = 0
    field_simp [hζ.ne_zero (NeZero.ne n)]
    ring
  have hzeta_int : IsIntegral E ζ := ⟨p, hp_monic, hp_root⟩
  have hQ_top : IntermediateField.adjoin ℚ ({ζ} : Set K) = ⊤ :=
    IntermediateField.adjoin_eq_top_of_algebra ℚ ({ζ} : Set K)
      (IsCyclotomicExtension.adjoin_primitive_root_eq_top hζ)
  have hE_top : IntermediateField.adjoin E ({ζ} : Set K) = ⊤ :=
    IntermediateField.adjoin_eq_top_of_adjoin_eq_top ℚ hQ_top
  let pb0 : PowerBasis E (IntermediateField.adjoin E ({ζ} : Set K)) :=
    IntermediateField.adjoin.powerBasis hzeta_int
  let pb : PowerBasis E K :=
    pb0.map ((IntermediateField.equivOfEq hE_top).trans IntermediateField.topEquiv)
  have hpb_gen : pb.gen = ζ := by
    simp [pb, pb0]
  have hfin_le : Module.finrank E K ≤ 2 := by
    rw [PowerBasis.finrank pb]
    have hdim := pb.dim_le_natDegree_of_root hp_monic.ne_zero (by simpa [hpb_gen] using hp_root)
    rw [hp_degree.natDegree_eq] at hdim
    exact hdim
  have hE_ne_top : E ≠ ⊤ := by
    intro htop
    have hz_mem : ζ ∈ NumberField.maximalRealSubfield K := by
      apply hE_le
      change ζ ∈ E
      rw [htop]
      trivial
    have hz_fixed : NumberField.IsCMField.complexConj K ζ = ζ :=
      (NumberField.IsCMField.complexConj_eq_self_iff K ζ).2 hz_mem
    have hinv : ζ⁻¹ = ζ := by
      rw [← complexConj_zeta hζ]
      exact hz_fixed
    have hz_sq : ζ ^ 2 = 1 := by
      calc
        ζ ^ 2 = ζ⁻¹ * ζ := by rw [pow_two, hinv]
        _ = 1 := inv_mul_cancel₀ (hζ.ne_zero (NeZero.ne n))
    have hdiv : n ∣ 2 := (hζ.pow_eq_one_iff_dvd 2).mp hz_sq
    exact (Nat.not_le_of_gt hn) (Nat.le_of_dvd (by norm_num) hdiv)
  have hfin_ne_one : Module.finrank E K ≠ 1 := by
    intro hfin
    exact hE_ne_top (IntermediateField.finrank_eq_one_iff_eq_top.mp hfin)
  have hfin_pos : 0 < Module.finrank E K := Module.finrank_pos
  have hfin : Module.finrank E K = 2 := by omega
  letI : Algebra.IsQuadraticExtension E.toSubfield K :=
    { finrank_eq_two' := by simpa using hfin }
  exact NumberField.CMExtension.eq_maximalRealSubfield K E.toSubfield

end Submission.NumberTheory.Milne
