import Towers.NumberTheory.Cyclotomic.CyclotomicUnits
import Towers.NumberTheory.Fermat.FermatAuxiliary
import Towers.NumberTheory.Fermat.FermatFactorization
import Towers.NumberTheory.Fermat.FermatSmallCases
import Mathlib.NumberTheory.NumberField.ClassNumber


/-!
# Milne, Algebraic Number Theory, Theorem 6.8

This file formalizes the final coefficient argument in Kummer's proof of the first case of
Fermat's last theorem for regular primes.  The ideal-theoretic principalization step is stated
separately below, so that the exact remaining interface to the class group is visible.
-/

namespace Towers.NumberTheory.Milne

open Algebra Module NumberField
open scoped Cyclotomic nonZeroDivisors

variable {p : ℕ} {K : Type*} [Field K] [NumberField K] [hp : Fact p.Prime]
variable [IsCyclotomicExtension {p} ℚ K]

omit [IsCyclotomicExtension {p} ℚ K] in
/-- The class-group step in Milne's proof: when `p` does not divide the class number, an ideal
whose `p`th power is principal is itself principal. -/
theorem principal_dvd_number
    (I : Ideal (NumberField.RingOfIntegers K)) (hI : I ≠ 0)
    (hclass : ¬p ∣ NumberField.classNumber K) (hpow : (I ^ p).IsPrincipal) :
    I.IsPrincipal := by
  let I0 : (Ideal (NumberField.RingOfIntegers K))⁰ :=
    ⟨I, mem_nonZeroDivisors_iff_ne_zero.mpr hI⟩
  let C : ClassGroup (NumberField.RingOfIntegers K) := ClassGroup.mk0 I0
  have hCpow : C ^ p = 1 := by
    have hIp : I ^ p ≠ 0 := pow_ne_zero p hI
    have hprincipal : ClassGroup.mk0
        (⟨I ^ p, mem_nonZeroDivisors_iff_ne_zero.mpr hIp⟩ :
          (Ideal (NumberField.RingOfIntegers K))⁰) = 1 :=
      (ClassGroup.mk0_eq_one_iff _).mpr hpow
    have hsub : I0 ^ p =
        (⟨I ^ p, mem_nonZeroDivisors_iff_ne_zero.mpr hIp⟩ :
          (Ideal (NumberField.RingOfIntegers K))⁰) := by
      apply Subtype.ext
      simp [I0]
    rw [← hsub] at hprincipal
    simpa [C, map_pow] using hprincipal
  have hordp : orderOf C ∣ p := orderOf_dvd_of_pow_eq_one hCpow
  have hordclass : orderOf C ∣ NumberField.classNumber K := by
    simpa [NumberField.classNumber, Nat.card_eq_fintype_card] using orderOf_dvd_natCard C
  have hcoprime : p.Coprime (NumberField.classNumber K) :=
    hp.out.coprime_iff_not_dvd.mpr hclass
  have hordcoprime : (orderOf C).Coprime (NumberField.classNumber K) :=
    hcoprime.of_dvd_left hordp
  have hord : orderOf C = 1 := hordcoprime.eq_one_of_dvd hordclass
  apply (ClassGroup.mk0_eq_one_iff I0.property).mp
  exact orderOf_eq_one_iff.mp hord

omit [IsCyclotomicExtension {p} ℚ K] in
/-- The ideal-class argument in the form needed by Kummer's proof.  If the principal ideal
generated by `s` is a `p`th ideal power and `p` does not divide the class number, then `s` is a
unit times a `p`th power. -/
theorem unit_span_ideal
    (s : NumberField.RingOfIntegers K) (I : Ideal (NumberField.RingOfIntegers K))
    (hI : I ≠ 0) (hclass : ¬p ∣ NumberField.classNumber K)
    (hspan : Ideal.span {s} = I ^ p) :
    ∃ u : (NumberField.RingOfIntegers K)ˣ,
      ∃ alpha : NumberField.RingOfIntegers K,
        s = (u : NumberField.RingOfIntegers K) * alpha ^ p := by
  have hIp : (I ^ p).IsPrincipal := by
    rw [← hspan]
    infer_instance
  obtain ⟨alpha, halpha⟩ :=
    principal_dvd_number I hI hclass hIp
  have halpha' : Ideal.span {alpha} = I := by
    simpa [Ideal.submodule_span_eq] using halpha.symm
  have hspan' : Ideal.span {s} = Ideal.span {alpha ^ p} := by
    rw [hspan, ← Ideal.span_singleton_pow, halpha']
  obtain ⟨u, hu⟩ := (Ideal.span_singleton_eq_span_singleton.mp hspan').symm
  refine ⟨u, alpha, ?_⟩
  rw [← hu]
  ring

omit hp in
private lemma pow_mod_order {M : Type*} [CommMonoid M]
    (zeta : M) (hzeta : IsPrimitiveRoot zeta p) (m : ℕ) :
    zeta ^ m = zeta ^ (m % p) := by
  exact pow_eq_pow_mod m hzeta.pow_eq_one

omit [NumberField K] hp [IsCyclotomicExtension {p} ℚ K] in
private lemma sum_indicator_pow (zeta : NumberField.RingOfIntegers K) (c : ℤ) {j : ℕ}
    (hj : j < p) :
    (∑ i ∈ Finset.range p,
        algebraMap ℤ (NumberField.RingOfIntegers K) (if i = j then c else 0) * zeta ^ i) =
      algebraMap ℤ (NumberField.RingOfIntegers K) c * zeta ^ j := by
  simp [hj]

omit [IsCyclotomicExtension {p} ℚ K] in
private theorem integers_complex_primitive
    [NumberField.IsCMField K] {zeta : K} (hzeta : IsPrimitiveRoot zeta p) :
    NumberField.IsCMField.ringOfIntegersComplexConj K hzeta.toInteger =
      hzeta.toInteger ^ (p - 1) := by
  letI : NeZero p := ⟨hp.out.ne_zero⟩
  let zu : (NumberField.RingOfIntegers K)ˣ :=
    (hzeta.toInteger_isPrimitiveRoot.isUnit hp.out.ne_zero).unit
  have hzu : (zu : NumberField.RingOfIntegers K) = hzeta.toInteger := by
    exact (hzeta.toInteger_isPrimitiveRoot.isUnit hp.out.ne_zero).unit_spec
  let zt : NumberField.Units.torsion K :=
    ⟨zu, by
      rw [NumberField.Units.torsion, CommGroup.mem_torsion]
      exact (hzeta.toInteger_isPrimitiveRoot.isUnit_unit hp.out.ne_zero).isOfFinOrder
        hp.out.ne_zero⟩
  apply RingOfIntegers.ext
  rw [NumberField.IsCMField.coe_ringOfIntegersComplexConj]
  have hc := NumberField.IsCMField.complexConj_torsion K zt
  change NumberField.IsCMField.complexConj K (hzeta.toInteger : K) =
    ((hzeta.toInteger : NumberField.RingOfIntegers K) ^ (p - 1) : K)
  rw [← hzu]
  rw [hc]
  change zeta⁻¹ = zeta ^ (p - 1)
  apply inv_eq_of_mul_eq_one_right
  rw [← pow_succ']
  simpa [Nat.sub_add_cancel hp.out.one_le] using hzeta.pow_eq_one

/-- The coefficient argument following equation (20) in Milne's proof of Theorem 6.8.

If
`x + ζy - ζ^(2r)x - ζ^(2r-1)y` is divisible by `p` in the cyclotomic integer ring, then
`p` divides `x`, `y`, or `x-y`.  This is the precise contradiction used after the class-group
and unit arguments. -/
theorem cyclotomic_four_congruence
    {zeta : K} (hzeta : IsPrimitiveRoot zeta p) (hp5 : 5 < p)
    (x y : ℤ) (r : ℕ)
    (hdiv : ∃ beta : NumberField.RingOfIntegers K,
      algebraMap ℤ (NumberField.RingOfIntegers K) x +
          hzeta.toInteger * algebraMap ℤ (NumberField.RingOfIntegers K) y -
          hzeta.toInteger ^ (2 * r) * algebraMap ℤ (NumberField.RingOfIntegers K) x -
          hzeta.toInteger ^ (p + 2 * r - 1) * algebraMap ℤ (NumberField.RingOfIntegers K) y =
        algebraMap ℤ (NumberField.RingOfIntegers K) (p : ℤ) * beta) :
    (p : ℤ) ∣ x ∨ (p : ℤ) ∣ y ∨ (p : ℤ) ∣ x - y := by
  let a := (2 * r) % p
  let b := (p + 2 * r - 1) % p
  let coeff : ℕ → ℤ := fun i ↦
    (if i = 0 then x else 0) + (if i = 1 then y else 0) -
      (if i = a then x else 0) - (if i = b then y else 0)
  have hp0 : 0 < p := hp.out.pos
  have hp1 : 1 < p := by omega
  have ha : a < p := Nat.mod_lt _ hp0
  have hb : b < p := Nat.mod_lt _ hp0
  have hsum :
      (∑ i ∈ Finset.range p,
          algebraMap ℤ (NumberField.RingOfIntegers K) (coeff i) *
            hzeta.toInteger ^ i) =
        algebraMap ℤ (NumberField.RingOfIntegers K) x +
          hzeta.toInteger * algebraMap ℤ (NumberField.RingOfIntegers K) y -
          hzeta.toInteger ^ (2 * r) * algebraMap ℤ (NumberField.RingOfIntegers K) x -
          hzeta.toInteger ^ (p + 2 * r - 1) * algebraMap ℤ (NumberField.RingOfIntegers K) y := by
    simp only [coeff, map_sub, map_add, add_mul, sub_mul]
    rw [Finset.sum_sub_distrib, Finset.sum_sub_distrib, Finset.sum_add_distrib]
    rw [
      sum_indicator_pow hzeta.toInteger x hp0,
      sum_indicator_pow hzeta.toInteger y hp1,
      sum_indicator_pow hzeta.toInteger x ha,
      sum_indicator_pow hzeta.toInteger y hb]
    simp only [pow_zero, pow_one, mul_one]
    rw [mul_comm (algebraMap ℤ (NumberField.RingOfIntegers K) y),
      mul_comm (algebraMap ℤ (NumberField.RingOfIntegers K) x),
      mul_comm (algebraMap ℤ (NumberField.RingOfIntegers K) y)]
    have hza : hzeta.toInteger ^ (2 * r) = hzeta.toInteger ^ a :=
      pow_mod_order hzeta.toInteger hzeta.toInteger_isPrimitiveRoot (2 * r)
    have hzb : hzeta.toInteger ^ (p + 2 * r - 1) = hzeta.toInteger ^ b :=
      pow_mod_order hzeta.toInteger hzeta.toInteger_isPrimitiveRoot (p + 2 * r - 1)
    rw [hza, hzb]
  have hzero : ∃ i < p, coeff i = 0 := by
    let forbidden : Finset ℕ := {0, 1, a, b}
    have hcard_forbidden : forbidden.card ≤ 4 := by
      have h0 := Finset.card_insert_le 0 {1, a, b}
      have h1 := Finset.card_insert_le 1 {a, b}
      have ha' := Finset.card_insert_le a {b}
      simp only [forbidden]
      rw [Finset.card_singleton] at ha'
      omega
    have hcard_lt : forbidden.card < (Finset.range p).card := by
      simp only [Finset.card_range]
      omega
    have hnsub : ¬Finset.range p ⊆ forbidden := by
      intro hsub
      exact (not_lt_of_ge (Finset.card_le_card hsub)) hcard_lt
    obtain ⟨i, hi, hnot⟩ := Finset.not_subset.mp hnsub
    refine ⟨i, Finset.mem_range.mp hi, ?_⟩
    simp only [coeff]
    have hi0 : i ≠ 0 := by
      intro h
      apply hnot
      simp [forbidden, h]
    have hi1 : i ≠ 1 := by
      intro h
      apply hnot
      simp [forbidden, h]
    have hia : i ≠ a := by
      intro h
      apply hnot
      simp [forbidden, h]
    have hib : i ≠ b := by
      intro h
      apply hnot
      simp [forbidden, h]
    simp [hi0, hi1, hia, hib]
  have hall : ∀ i < p, (p : ℤ) ∣ coeff i := by
    apply cyclotomic_coefficients_dvd hzeta coeff (p : ℤ) hzero
    obtain ⟨beta, hbeta⟩ := hdiv
    exact ⟨beta, hsum.trans hbeta⟩
  have hb_succ : (b + 1) % p = a := by
    simp only [a, b]
    rw [Nat.mod_add_mod]
    rw [Nat.sub_add_cancel (by omega : 1 ≤ p + 2 * r)]
    simp
  by_cases ha0 : a = 0
  · right; left
    have hb1 : b ≠ 1 := by
      intro hb1
      rw [hb1, Nat.mod_eq_of_lt (by omega : 2 < p), ha0] at hb_succ
      omega
    have h := hall 1 hp1
    simpa [coeff, ha0, Ne.symm hb1] using h
  · by_cases ha1 : a = 1
    · right; right
      have hb0 : b = 0 := by
        by_cases heq : b + 1 = p
        · rw [heq, Nat.mod_self, ha1] at hb_succ
          omega
        · have hlt : b + 1 < p := by omega
          rw [Nat.mod_eq_of_lt hlt, ha1] at hb_succ
          omega
      have h := hall 0 hp0
      simpa [coeff, ha1, hb0] using h
    · left
      have hb0 : b ≠ 0 := by
        intro hb0
        rw [hb0, Nat.mod_eq_of_lt (by omega : 1 < p)] at hb_succ
        exact ha1 hb_succ.symm
      have h := hall 0 hp0
      simpa [coeff, Ne.symm ha0, Ne.symm hb0] using h

/-- A normalized principal factor gives Milne's equation (20).  This packages all of the
post-principalization input: the factor is a `p`th power times a cyclotomic root and a unit fixed
by complex conjugation. -/
theorem cyclotomic_congruence_normalized
    [NumberField.IsCMField K] {zeta : K} (hzeta : IsPrimitiveRoot zeta p)
    (x y : ℤ) (r : ℕ) (v : (NumberField.RingOfIntegers K)ˣ)
    (alpha : NumberField.RingOfIntegers K)
    (hv : NumberField.IsCMField.unitsComplexConj K v = v)
    (hfactor :
      algebraMap ℤ (NumberField.RingOfIntegers K) x +
          hzeta.toInteger * algebraMap ℤ (NumberField.RingOfIntegers K) y =
        hzeta.toInteger ^ r * (v : NumberField.RingOfIntegers K) * alpha ^ p) :
    ∃ beta : NumberField.RingOfIntegers K,
      algebraMap ℤ (NumberField.RingOfIntegers K) x +
          hzeta.toInteger * algebraMap ℤ (NumberField.RingOfIntegers K) y -
          hzeta.toInteger ^ (2 * r) * algebraMap ℤ (NumberField.RingOfIntegers K) x -
          hzeta.toInteger ^ (p + 2 * r - 1) *
            algebraMap ℤ (NumberField.RingOfIntegers K) y =
        algebraMap ℤ (NumberField.RingOfIntegers K) (p : ℤ) * beta := by
  let c := NumberField.IsCMField.ringOfIntegersComplexConj K
  let P := algebraMap ℤ (NumberField.RingOfIntegers K) (p : ℤ)
  obtain ⟨a, beta, hpow⟩ := cyclotomic_integer_add hzeta alpha
  have hcv : c (v : NumberField.RingOfIntegers K) = (v : NumberField.RingOfIntegers K) := by
    exact congrArg Units.val hv
  have hcz : c hzeta.toInteger = hzeta.toInteger ^ (p - 1) :=
    integers_complex_primitive hzeta
  have hconjfactor :
      algebraMap ℤ (NumberField.RingOfIntegers K) x +
          c hzeta.toInteger * algebraMap ℤ (NumberField.RingOfIntegers K) y =
        (c hzeta.toInteger) ^ r * (v : NumberField.RingOfIntegers K) * c (alpha ^ p) := by
    have h := congrArg c hfactor
    simpa [map_add, map_mul, map_pow, hcv] using h
  have hconjpow :
      c (alpha ^ p) = algebraMap ℤ (NumberField.RingOfIntegers K) a + P * c beta := by
    rw [hpow]
    simp [P, map_add, map_mul]
  have hrootcancel :
      hzeta.toInteger ^ (2 * r) * (c hzeta.toInteger) ^ r = hzeta.toInteger ^ r := by
    have hp1 : 1 ≤ p := hp.out.one_le
    rw [hcz, ← pow_mul, ← pow_add]
    rw [show 2 * r + (p - 1) * r = p * r + r by
      calc
        2 * r + (p - 1) * r = (2 + (p - 1)) * r := (Nat.add_mul _ _ _).symm
        _ = (p + 1) * r := by congr 1; omega
        _ = p * r + r := by rw [Nat.add_mul, one_mul]]
    rw [pow_add, pow_mul,
      hzeta.toInteger_isPrimitiveRoot.pow_eq_one, one_pow, one_mul]
  refine ⟨hzeta.toInteger ^ r * (v : NumberField.RingOfIntegers K) * beta -
    hzeta.toInteger ^ (2 * r) * (c hzeta.toInteger) ^ r *
      (v : NumberField.RingOfIntegers K) * c beta, ?_⟩
  calc
    algebraMap ℤ (NumberField.RingOfIntegers K) x +
          hzeta.toInteger * algebraMap ℤ (NumberField.RingOfIntegers K) y -
          hzeta.toInteger ^ (2 * r) * algebraMap ℤ (NumberField.RingOfIntegers K) x -
          hzeta.toInteger ^ (p + 2 * r - 1) *
            algebraMap ℤ (NumberField.RingOfIntegers K) y =
        (algebraMap ℤ (NumberField.RingOfIntegers K) x +
          hzeta.toInteger * algebraMap ℤ (NumberField.RingOfIntegers K) y) -
        hzeta.toInteger ^ (2 * r) *
          (algebraMap ℤ (NumberField.RingOfIntegers K) x +
            c hzeta.toInteger * algebraMap ℤ (NumberField.RingOfIntegers K) y) := by
      rw [hcz, show p + 2 * r - 1 = 2 * r + (p - 1) by
        rw [Nat.sub_add_comm hp.out.one_le]
        omega, pow_add]
      ring
    _ = hzeta.toInteger ^ r * (v : NumberField.RingOfIntegers K) * alpha ^ p -
        hzeta.toInteger ^ (2 * r) *
          ((c hzeta.toInteger) ^ r * (v : NumberField.RingOfIntegers K) * c (alpha ^ p)) := by
      rw [hfactor, hconjfactor]
    _ = hzeta.toInteger ^ r * (v : NumberField.RingOfIntegers K) *
          (algebraMap ℤ (NumberField.RingOfIntegers K) a + P * beta) -
        hzeta.toInteger ^ (2 * r) *
          ((c hzeta.toInteger) ^ r * (v : NumberField.RingOfIntegers K) *
            (algebraMap ℤ (NumberField.RingOfIntegers K) a + P * c beta)) := by
      rw [hconjpow, hpow]
    _ = P * (hzeta.toInteger ^ r * (v : NumberField.RingOfIntegers K) * beta -
        hzeta.toInteger ^ (2 * r) * (c hzeta.toInteger) ^ r *
          (v : NumberField.RingOfIntegers K) * c beta) := by
      linear_combination
        -(algebraMap ℤ (NumberField.RingOfIntegers K) a *
          (v : NumberField.RingOfIntegers K)) * hrootcancel

/-- The contradiction in the last paragraph of Milne's proof, with equation (20) as the sole
input from the preceding ideal-class and unit argument. -/
theorem no_case_congruence
    {zeta : K} (hzeta : IsPrimitiveRoot zeta p) (hp5 : 5 < p)
    (x y : ℤ) (r : ℕ)
    (hpx : ¬(p : ℤ) ∣ x) (hpy : ¬(p : ℤ) ∣ y) (hpxy : ¬(p : ℤ) ∣ x - y)
    (hdiv : ∃ beta : NumberField.RingOfIntegers K,
      algebraMap ℤ (NumberField.RingOfIntegers K) x +
          hzeta.toInteger * algebraMap ℤ (NumberField.RingOfIntegers K) y -
          hzeta.toInteger ^ (2 * r) * algebraMap ℤ (NumberField.RingOfIntegers K) x -
          hzeta.toInteger ^ (p + 2 * r - 1) * algebraMap ℤ (NumberField.RingOfIntegers K) y =
        algebraMap ℤ (NumberField.RingOfIntegers K) (p : ℤ) * beta) :
    False := by
  rcases cyclotomic_four_congruence hzeta hp5 x y r hdiv with hx | hy | hxy
  · exact hpx hx
  · exact hpy hy
  · exact hpxy hxy

/-- Milne's first-case contradiction after the ideal-class argument has principalized the
factor `(x + ζy)`: if it is a unit times a `p`th power, then the hypotheses
`p ∤ x`, `p ∤ y`, and `p ∤ x-y` are inconsistent.

Thus the only remaining input for the full Theorem 6.8 is the ideal-theoretic deduction of this
principal-factor hypothesis from pairwise coprimality and `p ∤ classNumber K`. -/
theorem no_case_solution
    [NumberField.IsCMField K] {zeta : K} (hzeta : IsPrimitiveRoot zeta p) (hp5 : 5 < p)
    (x y : ℤ) (hpx : ¬(p : ℤ) ∣ x) (hpy : ¬(p : ℤ) ∣ y)
    (hpxy : ¬(p : ℤ) ∣ x - y)
    (hprincipal : ∃ u : (NumberField.RingOfIntegers K)ˣ,
      ∃ alpha : NumberField.RingOfIntegers K,
        algebraMap ℤ (NumberField.RingOfIntegers K) x +
            hzeta.toInteger * algebraMap ℤ (NumberField.RingOfIntegers K) y =
          (u : NumberField.RingOfIntegers K) * alpha ^ p) :
    False := by
  obtain ⟨u, alpha, hfactor⟩ := hprincipal
  have hp2 : p ≠ 2 := by omega
  letI : IsCyclotomicExtension {p ^ (0 + 1)} ℚ K := by
    simpa using (inferInstance : IsCyclotomicExtension {p} ℚ K)
  obtain ⟨t, v, hv, hu⟩ :=
    odd_torsion_fixed (k := 0) (K := K) hp2 u
  have htfinite : IsOfFinOrder ((((t : (NumberField.RingOfIntegers K)ˣ) :
      NumberField.RingOfIntegers K) : K)) := by
    have htunit : IsOfFinOrder (t : (NumberField.RingOfIntegers K)ˣ) :=
      (CommGroup.mem_torsion _ (t : (NumberField.RingOfIntegers K)ˣ)).mp t.property
    simpa using ((algebraMap (NumberField.RingOfIntegers K) K).toMonoidHom.comp
      (Units.coeHom (NumberField.RingOfIntegers K))).isOfFinOrder htunit
  obtain ⟨r, -, htr | htr⟩ :=
    hzeta.exists_pow_or_neg_mul_pow_of_isOfFinOrder (hp.out.odd_of_ne_two hp2) htfinite
  · have htr_int : ((t : (NumberField.RingOfIntegers K)ˣ) :
        NumberField.RingOfIntegers K) = hzeta.toInteger ^ r := by
      apply RingOfIntegers.ext
      exact htr
    have hnormalized :
        algebraMap ℤ (NumberField.RingOfIntegers K) x +
            hzeta.toInteger * algebraMap ℤ (NumberField.RingOfIntegers K) y =
          hzeta.toInteger ^ r * (v : NumberField.RingOfIntegers K) * alpha ^ p := by
      rw [hfactor, hu, Units.val_mul, htr_int]
    apply no_case_congruence hzeta hp5 x y r
      hpx hpy hpxy
    exact cyclotomic_congruence_normalized hzeta x y r v alpha hv hnormalized
  · let v' : (NumberField.RingOfIntegers K)ˣ := -v
    have hv' : NumberField.IsCMField.unitsComplexConj K v' = v' := by
      apply Units.ext
      simpa [v'] using congrArg Units.val hv
    have htr_int : ((t : (NumberField.RingOfIntegers K)ˣ) :
        NumberField.RingOfIntegers K) = -hzeta.toInteger ^ r := by
      apply RingOfIntegers.ext
      exact htr
    have hnormalized :
        algebraMap ℤ (NumberField.RingOfIntegers K) x +
            hzeta.toInteger * algebraMap ℤ (NumberField.RingOfIntegers K) y =
          hzeta.toInteger ^ r * (v' : NumberField.RingOfIntegers K) * alpha ^ p := by
      rw [hfactor, hu, Units.val_mul, htr_int]
      simp only [v', Units.val_neg]
      ring
    apply no_case_congruence hzeta hp5 x y r
      hpx hpy hpxy
    exact cyclotomic_congruence_normalized hzeta x y r v' alpha hv' hnormalized

/-- Theorem 6.8 after the pairwise-coprime factorization step: once the ideal generated by
`x + ζy` is known to be a `p`th ideal power, the class-number hypothesis and Proposition 6.7
give the contradiction. -/
theorem no_first_case
    [NumberField.IsCMField K] {zeta : K} (hzeta : IsPrimitiveRoot zeta p) (hp5 : 5 < p)
    (x y : ℤ) (hpx : ¬(p : ℤ) ∣ x) (hpy : ¬(p : ℤ) ∣ y)
    (hpxy : ¬(p : ℤ) ∣ x - y) (hclass : ¬p ∣ NumberField.classNumber K)
    (I : Ideal (NumberField.RingOfIntegers K)) (hI : I ≠ 0)
    (hideal : Ideal.span
      {algebraMap ℤ (NumberField.RingOfIntegers K) x +
        hzeta.toInteger * algebraMap ℤ (NumberField.RingOfIntegers K) y} = I ^ p) :
    False := by
  apply no_case_solution hzeta hp5 x y hpx hpy hpxy
  exact unit_span_ideal _ I hI hclass hideal

end Towers.NumberTheory.Milne
