import Submission.FieldTheory.CentralFactorSet
import Submission.Group.Presentation
import Mathlib.GroupTheory.OrderOfElement


/-!
# The two-generator tame local presentation

This file isolates the purely group-theoretic universal property behind the
local Koch relation.  The arithmetic step is to identify the maximal tame
pro-`3` local Galois group with the pro-`3` completion of this presentation.
-/

noncomputable section

namespace Submission
namespace TBluepr

open scoped commutatorElement

universe u

/-- The generator assignment sending `0` to tame inertia and `1` to
arithmetic Frobenius. -/
def tameLocalGenerator {G : Type u} [Group G] (x y : G) : Fin 2 → G :=
  fun i => if i = 0 then x else y

@[simp]
theorem tame_generator_zero
    {G : Type u} [Group G] (x y : G) :
    tameLocalGenerator x y 0 = x := by
  simp [tameLocalGenerator]

@[simp]
theorem tame_local_generator
    {G : Type u} [Group G] (x y : G) :
    tameLocalGenerator x y 1 = y := by
  simp [tameLocalGenerator]

/-- The standard tame relator `tau^(n-1) [tau,sigma]`. -/
def tameLocalRelator (n : ℕ) : FreeGroup (Fin 2) :=
  FreeGroup.of (0 : Fin 2) ^ (n - 1) *
    ⁅FreeGroup.of (0 : Fin 2), FreeGroup.of (1 : Fin 2)⁆

/-- The abstract two-generator, one-relator tame group. -/
def tameLocalPresentation (n : ℕ) : Presentation where
  Gen := Fin 2
  rels := {tameLocalRelator n}

/-- The inertia generator of the abstract tame presentation. -/
def tameLocalInertia (n : ℕ) : (tameLocalPresentation n).Gen :=
  (0 : Fin 2)

/-- The Frobenius generator of the abstract tame presentation. -/
def tameFrobeniusGenerator (n : ℕ) : (tameLocalPresentation n).Gen :=
  (1 : Fin 2)

theorem free_tame_relator
    {G : Type u} [Group G] (n : ℕ) (x y : G) :
    FreeGroup.lift (tameLocalGenerator x y) (tameLocalRelator n) =
      x ^ (n - 1) * ⁅x, y⁆ := by
  simp [tameLocalRelator, map_mul, map_pow, map_commutatorElement]

/-- A pair satisfying the tame relation receives the canonical homomorphism
from the abstract tame presentation. -/
def tamePresentationLift
    {G : Type u} [Group G] (n : ℕ) (x y : G)
    (hrelation : x ^ (n - 1) * ⁅x, y⁆ = 1) :
    (tameLocalPresentation n).Group →* G :=
  (tameLocalPresentation n).lift (tameLocalGenerator x y) (by
    intro r hr
    change r ∈ ({tameLocalRelator n} : Set (FreeGroup (Fin 2))) at hr
    change r = tameLocalRelator n at hr
    subst r
    exact (free_tame_relator n x y).trans hrelation)

@[simp]
theorem tame_presentation_inertia
    {G : Type u} [Group G] (n : ℕ) (x y : G)
    (hrelation : x ^ (n - 1) * ⁅x, y⁆ = 1) :
    tamePresentationLift n x y hrelation
        ((tameLocalPresentation n).of (tameLocalInertia n)) = x := by
  simp [tamePresentationLift, tameLocalInertia]

@[simp]
theorem tame_presentation_frobenius
    {G : Type u} [Group G] (n : ℕ) (x y : G)
    (hrelation : x ^ (n - 1) * ⁅x, y⁆ = 1) :
    tamePresentationLift n x y hrelation
        ((tameLocalPresentation n).of (tameFrobeniusGenerator n)) = y := by
  simp [tamePresentationLift, tameFrobeniusGenerator]

/-- Raising a finite-order element to a coprime exponent does not change the
cyclic subgroup that it generates. -/
theorem tame_zpowers_coprime
    {G : Type u} [Group G] (x : G) (n : ℕ)
    (hn : n.Coprime (orderOf x)) :
    Subgroup.zpowers (x ^ n) = Subgroup.zpowers x := by
  apply le_antisymm
  · exact Subgroup.zpowers_le_of_mem (Subgroup.npow_mem_zpowers x n)
  · exact Subgroup.zpowers_le.mpr
      ((mem_zpowers_pow_iff (g := x) (k := n)).2 hn)

/-- If conjugation by `y` raises `x` to a power coprime to its order, then
`y` normalizes the cyclic subgroup generated by `x`. -/
theorem normalizer_zpowers_coprime
    {G : Type u} [Group G] (x y : G) (n : ℕ)
    (hn : n.Coprime (orderOf x))
    (hconj : y * x * y⁻¹ = x ^ n) :
    y ∈ Subgroup.normalizer (Subgroup.zpowers x) := by
  let c : MulAut G := MulAut.conj y
  have hc : (Subgroup.zpowers x).map c.toMonoidHom = Subgroup.zpowers x := by
    rw [MonoidHom.map_zpowers]
    change Subgroup.zpowers (y * x * y⁻¹) = Subgroup.zpowers x
    rw [hconj]
    exact tame_zpowers_coprime x n hn
  rw [Subgroup.mem_normalizer_iff]
  intro z
  constructor
  · intro hz
    change c z ∈ Subgroup.zpowers x
    rw [← hc]
    exact ⟨z, hz, rfl⟩
  · intro hz
    change c z ∈ Subgroup.zpowers x at hz
    rw [← hc] at hz
    obtain ⟨w, hw, hwz⟩ := hz
    have hw_eq : w = z := c.injective hwz
    simpa [hw_eq] using hw

/-- Inside the subgroup generated by a tame inertia/Frobenius pair, the
cyclic inertia subgroup is normal. -/
theorem tame_inertia_closure
    {G : Type u} [Group G] (x y : G) (n : ℕ)
    (hn : n.Coprime (orderOf x))
    (hconj : y * x * y⁻¹ = x ^ n) :
    let H : Subgroup G := Subgroup.closure ({x, y} : Set G)
    let I : Subgroup H := (Subgroup.zpowers x).subgroupOf H
    I.Normal := by
  let H : Subgroup G := Subgroup.closure ({x, y} : Set G)
  have hxH : x ∈ H := Subgroup.subset_closure (Set.mem_insert x {y})
  have hyH : y ∈ H :=
    Subgroup.subset_closure (Set.mem_insert_of_mem x (Set.mem_singleton y))
  have hcyclic_le : Subgroup.zpowers x ≤ H :=
    Subgroup.zpowers_le.mpr hxH
  rw [Subgroup.normal_subgroupOf_iff_le_normalizer hcyclic_le]
  change Subgroup.closure ({x, y} : Set G) ≤
    Subgroup.normalizer (Subgroup.zpowers x)
  apply (Subgroup.closure_le
    (Subgroup.normalizer ((Subgroup.zpowers x : Subgroup G) : Set G))).2
  intro z hz
  rcases hz with hz | hz
  · have : z = x := hz
    subst z
    exact Subgroup.le_normalizer (Subgroup.mem_zpowers x)
  · have : z = y := Set.mem_singleton_iff.mp hz
    subst z
    exact normalizer_zpowers_coprime x y n hn hconj

/-- Modulo tame inertia, the image of Frobenius generates the quotient of the
subgroup generated by the tame pair. -/
theorem tame_frobenius_zpowers
    {G : Type u} [Group G] (x y : G) (n : ℕ)
    (hn : n.Coprime (orderOf x))
    (hconj : y * x * y⁻¹ = x ^ n) :
    let H : Subgroup G := Subgroup.closure ({x, y} : Set G)
    let I : Subgroup H := (Subgroup.zpowers x).subgroupOf H
    letI : I.Normal := tame_inertia_closure x y n hn hconj
    Subgroup.zpowers
        (QuotientGroup.mk' I
          (⟨y, Subgroup.subset_closure
            (Set.mem_insert_of_mem x (Set.mem_singleton y))⟩ : H)) = ⊤ := by
  let H : Subgroup G := Subgroup.closure ({x, y} : Set G)
  have hxH : x ∈ H := Subgroup.subset_closure (Set.mem_insert x {y})
  have hyH : y ∈ H :=
    Subgroup.subset_closure (Set.mem_insert_of_mem x (Set.mem_singleton y))
  let xH : H := ⟨x, hxH⟩
  let yH : H := ⟨y, hyH⟩
  let I : Subgroup H := (Subgroup.zpowers x).subgroupOf H
  letI : I.Normal := tame_inertia_closure x y n hn hconj
  let q : H →* H ⧸ I := QuotientGroup.mk' I
  let J : Subgroup H := (Subgroup.zpowers (q yH)).comap q
  have hxJ : xH ∈ J := by
    change q xH ∈ Subgroup.zpowers (q yH)
    have hxI : xH ∈ I := by
      exact Subgroup.mem_zpowers x
    have hqx : q xH = 1 := (QuotientGroup.eq_one_iff xH).2 hxI
    rw [hqx]
    exact Subgroup.one_mem _
  have hyJ : yH ∈ J := by
    exact Subgroup.mem_zpowers (q yH)
  have hgen : Subgroup.closure ({xH, yH} : Set H) = ⊤ := by
    have hset : ({xH, yH} : Set H) =
        H.subtype ⁻¹' ({x, y} : Set G) := by
      ext z
      constructor
      · rintro (rfl | hz)
        · exact Set.mem_insert x {y}
        · have : z = yH := Set.mem_singleton_iff.mp hz
          subst z
          exact Set.mem_insert_of_mem x (Set.mem_singleton y)
      · intro hz
        rcases hz with hz | hz
        · left
          exact Subtype.ext hz
        · right
          apply Set.mem_singleton_iff.mpr
          exact Subtype.ext (Set.mem_singleton_iff.mp hz)
    rw [hset]
    exact Subgroup.closure_preimage_eq_top ({x, y} : Set G)
  have hJ : J = ⊤ := by
    apply top_unique
    rw [← hgen]
    apply (Subgroup.closure_le J).2
    intro z hz
    rcases hz with hz | hz
    · simpa [hz] using hxJ
    · have : z = yH := Set.mem_singleton_iff.mp hz
      simpa [this] using hyJ
  apply top_unique
  intro z _
  obtain ⟨w, rfl⟩ := QuotientGroup.mk'_surjective I z
  have hwJ : w ∈ J := by rw [hJ]; exact Subgroup.mem_top w
  exact hwJ

/-- Modulo tame inertia, the subgroup generated by inertia and Frobenius is
cyclic, generated by the image of Frobenius. -/
theorem tame_inertia_cyclic
    {G : Type u} [Group G] (x y : G) (n : ℕ)
    (hn : n.Coprime (orderOf x))
    (hconj : y * x * y⁻¹ = x ^ n) :
    let H : Subgroup G := Subgroup.closure ({x, y} : Set G)
    let I : Subgroup H := (Subgroup.zpowers x).subgroupOf H
    letI : I.Normal := tame_inertia_closure x y n hn hconj
    IsCyclic (H ⧸ I) := by
  let H : Subgroup G := Subgroup.closure ({x, y} : Set G)
  have hyH : y ∈ H :=
    Subgroup.subset_closure (Set.mem_insert_of_mem x (Set.mem_singleton y))
  let yH : H := ⟨y, hyH⟩
  let I : Subgroup H := (Subgroup.zpowers x).subgroupOf H
  letI : I.Normal := tame_inertia_closure x y n hn hconj
  apply isCyclic_iff_exists_zpowers_eq_top.mpr
  exact ⟨QuotientGroup.mk' I yH,
    tame_frobenius_zpowers x y n hn hconj⟩

/-- The order of Frobenius modulo inertia is the cardinality of the tame
pair quotient. -/
theorem tame_frobenius_order
    {G : Type u} [Group G] [Finite G] (x y : G) (n : ℕ)
    (hn : n.Coprime (orderOf x))
    (hconj : y * x * y⁻¹ = x ^ n) :
    let H : Subgroup G := Subgroup.closure ({x, y} : Set G)
    let I : Subgroup H := (Subgroup.zpowers x).subgroupOf H
    letI : I.Normal := tame_inertia_closure x y n hn hconj
    orderOf
        (QuotientGroup.mk' I
          (⟨y, Subgroup.subset_closure
            (Set.mem_insert_of_mem x (Set.mem_singleton y))⟩ : H)) =
      Nat.card (H ⧸ I) := by
  let H : Subgroup G := Subgroup.closure ({x, y} : Set G)
  have hyH : y ∈ H :=
    Subgroup.subset_closure (Set.mem_insert_of_mem x (Set.mem_singleton y))
  let yH : H := ⟨y, hyH⟩
  let I : Subgroup H := (Subgroup.zpowers x).subgroupOf H
  letI : I.Normal := tame_inertia_closure x y n hn hconj
  exact orderOf_eq_card_of_zpowers_eq_top
    (tame_frobenius_zpowers x y n hn hconj)

/-- A specified generator of a cyclic normal subgroup together with a
specified lift of a generator of the quotient generate the whole subgroup.

This supplied-generator form is useful for decomposition groups: the first
element is the chosen tame inertia generator and the second is the chosen
arithmetic Frobenius, rather than arbitrary generators obtained from
cyclicity. -/
theorem closure_pair_cyclic
    {Q : Type u} [Group Q]
    (H : Subgroup Q) (I : Subgroup H) [I.Normal]
    (tau : I) (sigma : H)
    (htau : Subgroup.zpowers tau = ⊤)
    (hsigma : Subgroup.zpowers (QuotientGroup.mk' I sigma) = ⊤) :
    Subgroup.closure ({((tau : I) : Q), ((sigma : H) : Q)} : Set Q) = H := by
  apply le_antisymm
  · apply (Subgroup.closure_le H).2
    rintro x (rfl | hx)
    · exact (tau : H).2
    · have hx' : x = (sigma : Q) := Set.mem_singleton_iff.mp hx
      simp [hx']
  · intro q hq
    let qH : H := ⟨q, hq⟩
    have hqbar : QuotientGroup.mk' I qH ∈
        Subgroup.zpowers (QuotientGroup.mk' I sigma) := by
      rw [hsigma]
      exact Subgroup.mem_top _
    obtain ⟨n, hn⟩ := Subgroup.mem_zpowers_iff.mp hqbar
    have hdiff : qH * sigma ^ (-n) ∈ I := by
      apply (QuotientGroup.eq_one_iff _).mp
      change QuotientGroup.mk' I qH *
          (QuotientGroup.mk' I sigma) ^ (-n) = 1
      rw [← hn]
      simp
    let delta : I := ⟨qH * sigma ^ (-n), hdiff⟩
    have hdelta : delta ∈ Subgroup.zpowers tau := by
      rw [htau]
      exact Subgroup.mem_top _
    obtain ⟨m, hmI⟩ := Subgroup.mem_zpowers_iff.mp hdelta
    have hm : (tau : H) ^ m = qH * sigma ^ (-n) := by
      simpa [delta] using congrArg Subtype.val hmI
    let C : Subgroup Q :=
      Subgroup.closure ({((tau : I) : Q), ((sigma : H) : Q)} : Set Q)
    have htauC : ((tau : I) : Q) ∈ C :=
      Subgroup.subset_closure (Set.mem_insert _ _)
    have hsigmaC : ((sigma : H) : Q) ∈ C :=
      Subgroup.subset_closure
        (Set.mem_insert_of_mem _ (Set.mem_singleton _))
    have htauPow : ((tau : I) : Q) ^ m ∈ C :=
      (Subgroup.zpowers_le.2 htauC)
        (Subgroup.mem_zpowers_iff.mpr ⟨m, rfl⟩)
    have hsigmaPow : ((sigma : H) : Q) ^ n ∈ C :=
      (Subgroup.zpowers_le.2 hsigmaC)
        (Subgroup.mem_zpowers_iff.mpr ⟨n, rfl⟩)
    have hqH : qH = (tau : H) ^ m * sigma ^ n := by
      calc
        qH = (qH * sigma ^ (-n)) * sigma ^ n := by simp [mul_assoc]
        _ = (tau : H) ^ m * sigma ^ n := by rw [← hm]
    have hqQ : q = ((tau : I) : Q) ^ m * ((sigma : H) : Q) ^ n := by
      simpa using congrArg Subtype.val hqH
    rw [hqQ]
    exact C.mul_mem htauPow hsigmaPow

/-- The quotient-order power of Frobenius belongs to tame inertia. -/
theorem tame_frobenius_inertia
    {G : Type u} [Group G] [Finite G] (x y : G) (n : ℕ)
    (hn : n.Coprime (orderOf x))
    (hconj : y * x * y⁻¹ = x ^ n) :
    let H : Subgroup G := Subgroup.closure ({x, y} : Set G)
    let I : Subgroup H := (Subgroup.zpowers x).subgroupOf H
    letI : I.Normal := tame_inertia_closure x y n hn hconj
    (⟨y, Subgroup.subset_closure
          (Set.mem_insert_of_mem x (Set.mem_singleton y))⟩ : H) ^
        Nat.card (H ⧸ I) ∈ I := by
  let H : Subgroup G := Subgroup.closure ({x, y} : Set G)
  have hyH : y ∈ H :=
    Subgroup.subset_closure (Set.mem_insert_of_mem x (Set.mem_singleton y))
  let yH : H := ⟨y, hyH⟩
  let I : Subgroup H := (Subgroup.zpowers x).subgroupOf H
  letI : I.Normal := tame_inertia_closure x y n hn hconj
  apply (QuotientGroup.eq_one_iff (yH ^ Nat.card (H ⧸ I))).mp
  change (QuotientGroup.mk' I yH) ^ Nat.card (H ⧸ I) = 1
  rw [← tame_frobenius_order x y n hn hconj]
  exact pow_orderOf_eq_one _

/-- Iterating the tame conjugation relation raises the inertia exponent by
the corresponding power of the residue cardinality. -/
theorem tame_conjugation_pow
    {G : Type u} [Group G] (x y : G) (n m : ℕ)
    (hconj : y * x * y⁻¹ = x ^ n) :
    y ^ m * x * (y ^ m)⁻¹ = x ^ (n ^ m) := by
  induction m with
  | zero => simp
  | succ m ih =>
      calc
        y ^ (m + 1) * x * (y ^ (m + 1))⁻¹ =
            y ^ m * (y * x * y⁻¹) * (y ^ m)⁻¹ := by
          rw [pow_succ]
          group
        _ = y ^ m * x ^ n * (y ^ m)⁻¹ := by rw [hconj]
        _ = (y ^ m * x * (y ^ m)⁻¹) ^ n := by
          rw [conj_pow]
        _ = (x ^ (n ^ m)) ^ n := by rw [ih]
        _ = x ^ (n ^ (m + 1)) := by rw [← pow_mul, pow_succ]

/-- The inertia order divides `n^f - 1`, where `f` is the order of
Frobenius modulo inertia.  This is the finite-group form of the familiar
tame condition `e ∣ q^f - 1`. -/
theorem tame_inertia_dvd
    {G : Type u} [Group G] [Finite G] (x y : G) (n : ℕ)
    (hnpos : 0 < n)
    (hn : n.Coprime (orderOf x))
    (hconj : y * x * y⁻¹ = x ^ n) :
    let H : Subgroup G := Subgroup.closure ({x, y} : Set G)
    let I : Subgroup H := (Subgroup.zpowers x).subgroupOf H
    letI : I.Normal := tame_inertia_closure x y n hn hconj
    orderOf x ∣ n ^ Nat.card (H ⧸ I) - 1 := by
  let H : Subgroup G := Subgroup.closure ({x, y} : Set G)
  have hyH : y ∈ H :=
    Subgroup.subset_closure (Set.mem_insert_of_mem x (Set.mem_singleton y))
  let yH : H := ⟨y, hyH⟩
  let I : Subgroup H := (Subgroup.zpowers x).subgroupOf H
  letI : I.Normal := tame_inertia_closure x y n hn hconj
  let f := Nat.card (H ⧸ I)
  have hyfI : yH ^ f ∈ I :=
    tame_frobenius_inertia
      x y n hn hconj
  have hyf : y ^ f ∈ Subgroup.zpowers x := hyfI
  let a : Subgroup.zpowers x := ⟨y ^ f, hyf⟩
  let b : Subgroup.zpowers x := ⟨x, Subgroup.mem_zpowers x⟩
  letI : CommGroup (Subgroup.zpowers x) := IsCyclic.commGroup
  have hcomm : y ^ f * x = x * y ^ f :=
    congrArg Subtype.val (mul_comm a b)
  have hconjtrivial : y ^ f * x * (y ^ f)⁻¹ = x := by
    rw [hcomm]
    group
  have hpow : x ^ (n ^ f) = x := by
    rw [← tame_conjugation_pow x y n f hconj]
    exact hconjtrivial
  have hnfpos : 0 < n ^ f := pow_pos hnpos f
  have hsub : x ^ (n ^ f - 1) = 1 := by
    apply mul_right_cancel (b := x)
    calc
      x ^ (n ^ f - 1) * x = x ^ (n ^ f) := by
        rw [← pow_succ, Nat.sub_add_cancel hnfpos]
      _ = x := hpow
      _ = 1 * x := by rw [one_mul]
  exact (orderOf_dvd_iff_pow_eq_one).2 hsub

/-- The cyclic subgroup generated by `x`, with the coordinate normalized so
that `1 : ZMod (orderOf x)` maps to `x`. -/
noncomputable def tameZMod
    {G : Type u} [Group G] (x : G) :
    Multiplicative (ZMod (orderOf x)) ≃* Subgroup.zpowers x := by
  let xI : Subgroup.zpowers x := ⟨x, Subgroup.mem_zpowers x⟩
  apply zmodMulEquivOfGenerator (g := xI)
  · intro z
    obtain ⟨i, hi⟩ := z.property
    exact ⟨i, Subtype.ext hi⟩
  · show Nat.card (Subgroup.zpowers x) = orderOf x
    exact Nat.card_zpowers (a := x)

@[simp]
theorem tame_inertia_z
    {G : Type u} [Group G] (x : G) :
    tameZMod x (Multiplicative.ofAdd 1) =
      (⟨x, Subgroup.mem_zpowers x⟩ : Subgroup.zpowers x) := by
  simp [tameZMod]

/-- Conjugation in the usual Frobenius form is an equivalent input for the
universal map out of the tame presentation. -/
def tamePresentationConjugation
    {G : Type u} [Group G] {n : ℕ} (hn : 1 ≤ n) (x y : G)
    (hconj : y * x * y⁻¹ = x ^ n) :
    (tameLocalPresentation n).Group →* G :=
  tamePresentationLift n x y
    ((tame_relation_conjugation x y hn).2 hconj)

end TBluepr
end Submission
