import Submission.Group.Petresco.CommutatorBounds
import Mathlib.GroupTheory.Solvable

/-!
# Petresco's 1954 paper: derived-series results

Petresco numbers the initial subgroup as `K¹(A)`. Here
`ambientDerivedSeries A 0 = A`, so the Lean index is one less than the
index printed in the paper.
-/

namespace Submission
namespace Edmonton
namespace P1954

open scoped commutatorElement

universe u

variable {G : Type u} [Group G]

/-- The derived series of a subgroup, viewed in the ambient group. -/
def ambientDerivedSeries (H : Subgroup G) (n : ℕ) : Subgroup G :=
  (derivedSeries H n).map H.subtype

@[simp]
lemma ambient_derived_series (H : Subgroup G) :
    ambientDerivedSeries H 0 = H := by
  simp [ambientDerivedSeries, ← MonoidHom.range_eq_map, H.range_subtype]

lemma ambient_derived_succ (H : Subgroup G) (n : ℕ) :
    ambientDerivedSeries H (n + 1) =
      ⁅ambientDerivedSeries H n, ambientDerivedSeries H n⁆ := by
  simp [ambientDerivedSeries, derivedSeries_succ, Subgroup.map_commutator]

lemma ambient_derived (H : Subgroup G) (n : ℕ) :
    ambientDerivedSeries H n ≤ H := by
  rw [ambientDerivedSeries]
  exact Subgroup.map_subtype_le (derivedSeries H n)

/-- Derived terms are monotone with respect to the ambient subgroup. -/
lemma ambient_derived_mono
    {H K : Subgroup G} (hHK : H ≤ K) :
    ∀ n : ℕ, ambientDerivedSeries H n ≤ ambientDerivedSeries K n
  | 0 => by simpa using hHK
  | n + 1 => by
      rw [ambient_derived_succ, ambient_derived_succ]
      exact Subgroup.commutator_mono
        (ambient_derived_mono hHK n)
        (ambient_derived_mono hHK n)

/-- Iterating the ambient derived series adds the indices. -/
lemma ambient_derived_add (H : Subgroup G) (j k : ℕ) :
    ambientDerivedSeries (ambientDerivedSeries H j) k =
      ambientDerivedSeries H (j + k) := by
  induction k with
  | zero =>
      simp
  | succ k ih =>
      rw [ambient_derived_succ, ih, Nat.add_succ,
        ambient_derived_succ]

/-- Each ambient derived term is normal in the subgroup from which it came. -/
lemma ambient_derived_subgroup (H : Subgroup G) (n : ℕ) :
    ((ambientDerivedSeries H n).subgroupOf H).Normal := by
  have heq :
      (ambientDerivedSeries H n).subgroupOf H = derivedSeries H n := by
    apply Subgroup.map_subtype_inj.mp
    rw [Subgroup.map_subgroupOf_eq_of_le (ambient_derived H n)]
    rfl
  rw [heq]
  exact derivedSeries_normal H n

/-- If `K` is normal in `H`, then `[H,K] ≤ K`. -/
lemma commutator_normal_subgroup
    {H K : Subgroup G} (hKH : K ≤ H) [(K.subgroupOf H).Normal] :
    ⁅H, K⁆ ≤ K := by
  rw [Subgroup.commutator_comm H K]
  exact commutator_left_subgroup hKH

/-- **Petresco 6.1.** The derived subgroup of a join is generated by the
two internal derived subgroups and the mixed commutator subgroup. -/
theorem join_internal_mixed (A B : Subgroup G) :
    ⁅A ⊔ B, A ⊔ B⁆ =
      (⁅A, A⁆ ⊔ ⁅A, B⁆) ⊔ ⁅B, B⁆ := by
  apply le_antisymm
  · letI : (A.subgroupOf A).Normal := by
      rw [Subgroup.subgroupOf_self]
      infer_instance
    letI : (B.subgroupOf B).Normal := by
      rw [Subgroup.subgroupOf_self]
      infer_instance
    have h := commutator_mixed_product
      (Astar := A) (A := A) (Bstar := B) (B := B) le_rfl le_rfl
    rw [sup_commutator_join A B] at h
    exact h
  · exact sup_le
      (sup_le
        (Subgroup.commutator_mono le_sup_left le_sup_left)
        (Subgroup.commutator_mono le_sup_left le_sup_right))
      (Subgroup.commutator_mono le_sup_right le_sup_right)

/-- **Petresco 6.2.** If `B` is normal in `A ⊔ B`, then the derived subgroup
of the join is contained in `[A,A]B`. -/
theorem join_internal_sup
    (A B : Subgroup G) [(B.subgroupOf (A ⊔ B)).Normal] :
    ⁅A ⊔ B, A ⊔ B⁆ ≤ ⁅A, A⁆ ⊔ B := by
  rw [join_internal_mixed]
  have hBH : B ≤ A ⊔ B := le_sup_right
  have hAB : ⁅A, B⁆ ≤ B :=
    (Subgroup.commutator_mono le_sup_left le_rfl).trans
      (commutator_normal_subgroup hBH)
  exact sup_le
    (sup_le le_sup_left (hAB.trans le_sup_right))
    ((Subgroup.commutator_mono le_rfl le_rfl).trans B.commutator_le_self
      |>.trans le_sup_right)

/-- **Petresco 6.3.** If `B` is normal in `A ⊔ B`, every derived term of
the join is contained in the corresponding derived term of `A`, times `B`. -/
theorem derived_join_sup
    (A B : Subgroup G) [(B.subgroupOf (A ⊔ B)).Normal] :
    ∀ n : ℕ,
      ambientDerivedSeries (A ⊔ B) n ≤ ambientDerivedSeries A n ⊔ B
  | 0 => by simp
  | n + 1 => by
      rw [ambient_derived_succ]
      have ih := derived_join_sup A B n
      have hmono :
          ⁅ambientDerivedSeries (A ⊔ B) n,
              ambientDerivedSeries (A ⊔ B) n⁆ ≤
            ⁅ambientDerivedSeries A n ⊔ B,
              ambientDerivedSeries A n ⊔ B⁆ :=
        Subgroup.commutator_mono ih ih
      apply hmono.trans
      have hsmall :
          ambientDerivedSeries A n ⊔ B ≤ A ⊔ B :=
        sup_le
          ((ambient_derived A n).trans le_sup_left)
          le_sup_right
      letI :
          (B.subgroupOf (ambientDerivedSeries A n ⊔ B)).Normal := by
        rw [Subgroup.normal_subgroupOf_iff_le_normalizer le_sup_right]
        exact hsmall.trans
          (Subgroup.le_normalizer_of_normal_subgroupOf le_sup_right)
      simpa [ambient_derived_succ] using
        join_internal_sup (ambientDerivedSeries A n) B

/-- **Petresco 6.4.** In the source indexing, `j + k = i + 1`.
With zero-based Lean indices this becomes the term `j + k` on the left. -/
theorem derived_join_mixed (A B : Subgroup G) (j k : ℕ) :
    ambientDerivedSeries (A ⊔ B) (j + k) ≤
      (ambientDerivedSeries A j ⊔ ⁅A, B⁆) ⊔
        ambientDerivedSeries B k := by
  let H : Subgroup G := A ⊔ B
  let C : Subgroup G := ⁅A, B⁆ ⊔ B
  let D : Subgroup G := ambientDerivedSeries A j ⊔ ⁅A, B⁆
  have hAC : A ⊔ C = H := by
    calc
      A ⊔ C = (A ⊔ ⁅A, B⁆) ⊔ B := by
        simp only [C, sup_assoc]
      _ = H := sup_commutator_join A B
  letI : (C.subgroupOf H).Normal := by
    simpa [C, H, commutatorExtensionRight, sup_comm] using
      commutator_extension_sup A B
  letI : (C.subgroupOf (A ⊔ C)).Normal := by
    rw [hAC]
    infer_instance
  have hfirst : ambientDerivedSeries H j ≤ D ⊔ B := by
    have h := derived_join_sup A C j
    rw [hAC] at h
    simpa [C, D, sup_assoc] using h
  have hDH : D ≤ H := by
    exact sup_le
      ((ambient_derived A j).trans le_sup_left)
      ((Subgroup.commutator_mono le_sup_left le_sup_right).trans
        H.commutator_le_self)
  letI : ((ambientDerivedSeries A j).subgroupOf A).Normal :=
    ambient_derived_subgroup A j
  letI : ((⊥ : Subgroup G).subgroupOf B).Normal := by
    rw [Subgroup.bot_subgroupOf]
    infer_instance
  letI : (D.subgroupOf H).Normal := by
    simpa [D, H] using
      (sup_commutator_normal
        (Astar := ambientDerivedSeries A j) (A := A)
        (Bstar := (⊥ : Subgroup G)) (B := B)
        (ambient_derived A j) bot_le)
  have hBDH : B ⊔ D ≤ H := sup_le le_sup_right hDH
  letI : (D.subgroupOf (B ⊔ D)).Normal := by
    rw [Subgroup.normal_subgroupOf_iff_le_normalizer le_sup_right]
    exact hBDH.trans
      (Subgroup.le_normalizer_of_normal_subgroupOf hDH)
  rw [← ambient_derived_add H j k]
  calc
    ambientDerivedSeries (ambientDerivedSeries H j) k ≤
        ambientDerivedSeries (B ⊔ D) k :=
      ambient_derived_mono (hfirst.trans_eq (sup_comm D B)) k
    _ ≤ ambientDerivedSeries B k ⊔ D :=
      derived_join_sup B D k
    _ = D ⊔ ambientDerivedSeries B k := sup_comm _ _

/-! ## The anti-solvable radical -/

/-- A subgroup is perfect when it equals its own derived subgroup. -/
def IsPerfectSubgroup (P : Subgroup G) : Prop :=
  ⁅P, P⁆ = P

/-- Petresco's anti-solvable radical: the largest perfect subgroup
contained in `H`. This intrinsic definition does not require a chain
condition. Under the descending chain condition it agrees with the stable
term of the derived series. -/
def antiSolvableRadical (H : Subgroup G) : Subgroup G :=
  ⨆ P : {P : Subgroup G // P ≤ H ∧ IsPerfectSubgroup P}, P.1

lemma anti_solvable (H : Subgroup G) :
    antiSolvableRadical H ≤ H := by
  rw [antiSolvableRadical]
  exact iSup_le fun P => P.2.1

lemma le_anti_radical
    {P H : Subgroup G} (hPH : P ≤ H) (hP : IsPerfectSubgroup P) :
    P ≤ antiSolvableRadical H := by
  exact le_iSup
    (fun Q : {Q : Subgroup G // Q ≤ H ∧ IsPerfectSubgroup Q} => Q.1)
    ⟨P, hPH, hP⟩

lemma anti_solvable_mono
    {H K : Subgroup G} (hHK : H ≤ K) :
    antiSolvableRadical H ≤ antiSolvableRadical K := by
  rw [antiSolvableRadical]
  refine iSup_le fun P => ?_
  exact le_anti_radical (P.2.1.trans hHK) P.2.2

/-- Homomorphisms carry the anti-solvable radical into the radical of
any subgroup containing the image. -/
lemma anti_radical
    {G' : Type*} [Group G'] (f : G →* G')
    {H : Subgroup G} {K : Subgroup G'}
    (hmap : H.map f ≤ K) :
    (antiSolvableRadical H).map f ≤ antiSolvableRadical K := by
  rw [antiSolvableRadical, Subgroup.map_iSup]
  refine iSup_le fun P => ?_
  apply le_anti_radical
  · exact (Subgroup.map_mono P.2.1).trans hmap
  · rw [IsPerfectSubgroup, ← Subgroup.map_commutator, P.2.2]

/-- The anti-solvable radical is characteristic in the normalizer sense. -/
lemma normalizer_anti_radical (H : Subgroup G) :
    Subgroup.normalizer (H : Set G) ≤
      Subgroup.normalizer (antiSolvableRadical H : Set G) := by
  intro g hg
  rw [Subgroup.mem_normalizer_iff] at hg ⊢
  intro x
  constructor
  · intro hx
    let f : G →* G := (MulAut.conj g).toMonoidHom
    have hmapH : H.map f ≤ H := by
      rintro y ⟨z, hz, rfl⟩
      exact (hg z).mp hz
    have hmapR := anti_radical f hmapH
    have hxmap := hmapR (Subgroup.mem_map_of_mem f hx)
    simpa [f, MulAut.conj_apply] using hxmap
  · intro hx
    let f : G →* G := (MulAut.conj g⁻¹).toMonoidHom
    have hginv :
        g⁻¹ ∈ Subgroup.normalizer (H : Set G) :=
      (Subgroup.normalizer (H : Set G)).inv_mem
        (by
          rw [Subgroup.mem_normalizer_iff]
          exact hg)
    have hginv' := (Subgroup.mem_normalizer_iff.mp hginv)
    have hmapH : H.map f ≤ H := by
      rintro y ⟨z, hz, rfl⟩
      exact (hginv' z).mp hz
    have hmapR := anti_radical f hmapH
    have hxmap := hmapR (Subgroup.mem_map_of_mem f hx)
    simpa [f, MulAut.conj_apply, mul_assoc] using hxmap

lemma anti_solvable_perfect (H : Subgroup G) :
    IsPerfectSubgroup (antiSolvableRadical H) := by
  apply le_antisymm
  · exact (antiSolvableRadical H).commutator_le_self
  · rw [antiSolvableRadical]
    refine iSup_le fun P => ?_
    rw [← P.2.2]
    exact Subgroup.commutator_mono
      (le_iSup
        (fun Q : {Q : Subgroup G // Q ≤ H ∧ IsPerfectSubgroup Q} => Q.1)
        P)
      (le_iSup
        (fun Q : {Q : Subgroup G // Q ≤ H ∧ IsPerfectSubgroup Q} => Q.1)
        P)

/-- The anti-solvable radical lies in every term of the derived series. -/
lemma anti_solvable_derived
    (H : Subgroup G) :
    ∀ n : ℕ, antiSolvableRadical H ≤ ambientDerivedSeries H n
  | 0 => by simpa using anti_solvable H
  | n + 1 => by
      rw [ambient_derived_succ,
        ← anti_solvable_perfect H]
      exact Subgroup.commutator_mono
        (anti_solvable_derived H n)
        (anti_solvable_derived H n)

/-- A stabilized derived term is exactly the anti-solvable radical. -/
theorem derived_anti_stable
    (H : Subgroup G) (n : ℕ)
    (hstable :
      ambientDerivedSeries H (n + 1) = ambientDerivedSeries H n) :
    ambientDerivedSeries H n = antiSolvableRadical H := by
  apply le_antisymm
  · apply le_anti_radical (ambient_derived H n)
    rw [IsPerfectSubgroup, ← ambient_derived_succ]
    exact hstable
  · exact anti_solvable_derived H n

/-- Under the descending chain condition, every subgroup's derived series
has a stable term. -/
lemma ambient_derived_stable
    [WellFoundedLT (Subgroup G)] (H : Subgroup G) :
    ∃ n : ℕ,
      ambientDerivedSeries H (n + 1) = ambientDerivedSeries H n := by
  by_contra h
  push Not at h
  have hstrict : StrictAnti (ambientDerivedSeries H) :=
    strictAnti_nat_of_succ_lt fun n =>
      lt_of_le_of_ne
        (by
          rw [ambient_derived_succ]
          exact (ambientDerivedSeries H n).commutator_le_self)
        (h n)
  exact (not_strictAnti_of_wellFoundedLT (ambientDerivedSeries H)) hstrict

/-- **Petresco 6.5.** Under the descending chain condition, the
anti-solvable radical of a join is bounded by the two radicals and the
mixed commutator subgroup. -/
theorem solvable_radical_join
    [WellFoundedLT (Subgroup G)] (A B : Subgroup G) :
    antiSolvableRadical (A ⊔ B) ≤
      (antiSolvableRadical A ⊔ ⁅A, B⁆) ⊔
        antiSolvableRadical B := by
  obtain ⟨j, hj⟩ := ambient_derived_stable A
  obtain ⟨k, hk⟩ := ambient_derived_stable B
  calc
    antiSolvableRadical (A ⊔ B) ≤
        ambientDerivedSeries (A ⊔ B) (j + k) :=
      anti_solvable_derived (A ⊔ B) (j + k)
    _ ≤
        (ambientDerivedSeries A j ⊔ ⁅A, B⁆) ⊔
          ambientDerivedSeries B k :=
      derived_join_mixed A B j k
    _ =
        (antiSolvableRadical A ⊔ ⁅A, B⁆) ⊔
          antiSolvableRadical B := by
      rw [derived_anti_stable A j hj,
        derived_anti_stable B k hk]

/-- **Petresco 6.6.** If `A` and `B` are normal in their join, the
anti-solvable radical of the join is the join of their radicals. -/
theorem anti_solvable_join
    [WellFoundedLT (Subgroup G)] (A B : Subgroup G)
    [(A.subgroupOf (A ⊔ B)).Normal]
    [(B.subgroupOf (A ⊔ B)).Normal] :
    antiSolvableRadical (A ⊔ B) =
      antiSolvableRadical A ⊔ antiSolvableRadical B := by
  let H : Subgroup G := A ⊔ B
  let RA : Subgroup G := antiSolvableRadical A
  obtain ⟨j, hj⟩ := ambient_derived_stable A
  obtain ⟨k, hk⟩ := ambient_derived_stable B
  have hRAA : RA ≤ A := anti_solvable A
  have hRAH : RA ≤ H := hRAA.trans le_sup_left
  have hHnormalizesA :
      H ≤ Subgroup.normalizer (A : Set G) :=
    Subgroup.le_normalizer_of_normal_subgroupOf le_sup_left
  have hHnormalizesRA :
      H ≤ Subgroup.normalizer (RA : Set G) :=
    hHnormalizesA.trans
      (normalizer_anti_radical A)
  letI : (RA.subgroupOf H).Normal := by
    rw [Subgroup.normal_subgroupOf_iff_le_normalizer hRAH]
    exact hHnormalizesRA
  have hfirst :
      ambientDerivedSeries H j ≤ RA ⊔ B := by
    have h := derived_join_sup A B j
    rw [derived_anti_stable A j hj] at h
    exact h
  have hBRAH : B ⊔ RA ≤ H :=
    sup_le le_sup_right hRAH
  letI : (RA.subgroupOf (B ⊔ RA)).Normal := by
    rw [Subgroup.normal_subgroupOf_iff_le_normalizer le_sup_right]
    exact hBRAH.trans
      (Subgroup.le_normalizer_of_normal_subgroupOf hRAH)
  apply le_antisymm
  · calc
      antiSolvableRadical H ≤
          ambientDerivedSeries H (j + k) :=
        anti_solvable_derived H (j + k)
      _ = ambientDerivedSeries (ambientDerivedSeries H j) k := by
        rw [ambient_derived_add]
      _ ≤ ambientDerivedSeries (RA ⊔ B) k :=
        ambient_derived_mono hfirst k
      _ = ambientDerivedSeries (B ⊔ RA) k := by
        rw [sup_comm]
      _ ≤ ambientDerivedSeries B k ⊔ RA :=
        derived_join_sup B RA k
      _ = RA ⊔ antiSolvableRadical B := by
        rw [derived_anti_stable B k hk,
          sup_comm]
  · exact sup_le
      (anti_solvable_mono le_sup_left)
      (anti_solvable_mono le_sup_right)

/-- A solvable subgroup has trivial anti-solvable radical. -/
lemma anti_solvable_radical
    (H : Subgroup G) [IsSolvable H] :
    antiSolvableRadical H = ⊥ := by
  obtain ⟨n, hn⟩ := IsSolvable.solvable (G := H)
  apply le_bot_iff.mp
  apply (anti_solvable_derived H n).trans
  simp [ambientDerivedSeries, hn]

/-- **Petresco 6.7.** If `A` and `B` are solvable, the anti-solvable
radical of their join is the anti-solvable radical of `[A,B]`. -/
theorem anti_radical_join
    (A B : Subgroup G) [IsSolvable A] [IsSolvable B] :
    antiSolvableRadical (A ⊔ B) =
      antiSolvableRadical ⁅A, B⁆ := by
  obtain ⟨j, hj⟩ := IsSolvable.solvable (G := A)
  obtain ⟨k, hk⟩ := IsSolvable.solvable (G := B)
  have hjambient : ambientDerivedSeries A j = ⊥ := by
    simp [ambientDerivedSeries, hj]
  have hkambient : ambientDerivedSeries B k = ⊥ := by
    simp [ambientDerivedSeries, hk]
  have hradical_le : antiSolvableRadical (A ⊔ B) ≤ ⁅A, B⁆ := by
    calc
      antiSolvableRadical (A ⊔ B) ≤
          ambientDerivedSeries (A ⊔ B) (j + k) :=
        anti_solvable_derived (A ⊔ B) (j + k)
      _ ≤
          (ambientDerivedSeries A j ⊔ ⁅A, B⁆) ⊔
            ambientDerivedSeries B k :=
        derived_join_mixed A B j k
      _ = ⁅A, B⁆ := by simp [hjambient, hkambient]
  apply le_antisymm
  · apply le_anti_radical
    · exact hradical_le
    · exact anti_solvable_perfect (A ⊔ B)
  · apply anti_solvable_mono
    exact
      (Subgroup.commutator_mono le_sup_left le_sup_right).trans
        (A ⊔ B).commutator_le_self

end P1954
end Edmonton
end Submission
