import Submission.Group.Petresco.LowerCentralSeries
import Submission.Group.Edmonton.HallEmbeddings

/-!
# Petresco's 1954 paper: commutator forms and collection

This file connects Sections 8 and 9 of Petresco's paper to the formal
support-collection machinery already developed in
`Submission.Group.Edmonton.HallEmbeddings`.
-/

namespace Submission
namespace Edmonton
namespace P1954

universe u v w

variable {G : Type u} [Group G]

/-- The endomorphism of a free group which retains precisely the variables
whose labels lie in `S`. -/
def freeProjectedProjection
    {X : Type v} {L : Type w} [DecidableEq L]
    (label : X → L) (S : Finset L) :
    FreeGroup X →* FreeGroup X :=
  FreeGroup.lift
    (retainProjectedVariables label S (fun x => FreeGroup.of x))

/-- Petresco's `E^μ` in the universal free-group model: the words killed by
every projection onto fewer than `μ` labels. -/
def projectionVanishingSubgroup
    {X : Type v} {L : Type w} [DecidableEq L]
    (label : X → L) (μ : ℕ) :
    Subgroup (FreeGroup X) :=
  ⨅ S : Finset L, ⨅ (_hS : S.card < μ),
    (freeProjectedProjection label S).ker

lemma projection_vanishing_subgroup
    {X : Type v} {L : Type w} [DecidableEq L]
    (label : X → L) (μ : ℕ) (x : FreeGroup X) :
    x ∈ projectionVanishingSubgroup label μ ↔
      ∀ S : Finset L, S.card < μ →
        freeProjectedProjection label S x = 1 := by
  simp [projectionVanishingSubgroup, MonoidHom.mem_ker]

/-- **Petresco 8.1.** The universal projection-vanishing subgroup `E^μ`
is normal in the free group generated by all labelled variables. -/
theorem projection_vanishing_normal
    {X : Type v} {L : Type w} [DecidableEq L]
    (label : X → L) (μ : ℕ) :
    (projectionVanishingSubgroup label μ).Normal := by
  unfold projectionVanishingSubgroup
  apply Subgroup.normal_iInf_normal
  intro S
  apply Subgroup.normal_iInf_normal
  intro hS
  infer_instance

/-- Projection commutes with evaluation of a formal commutator in the
universal free group. -/
lemma projected_projection_formal
    {X : Type v} {L : Type w} [DecidableEq L]
    (label : X → L) (S : Finset L) (c : FormalCommutator X) :
    freeProjectedProjection label S
        (formalGroupCommutator (fun x => FreeGroup.of x) c) =
      formalGroupCommutator
        (retainProjectedVariables label S (fun x => FreeGroup.of x)) c := by
  induction c with
  | of x =>
      simp [freeProjectedProjection]
  | mul a b iha ihb =>
      change
        freeProjectedProjection label S
            (hallCommutator
              (formalGroupCommutator (fun x => FreeGroup.of x) a)
              (formalGroupCommutator (fun x => FreeGroup.of x) b)) =
          hallCommutator
            (formalGroupCommutator
              (retainProjectedVariables label S
                (fun x => FreeGroup.of x)) a)
            (formalGroupCommutator
              (retainProjectedVariables label S
                (fun x => FreeGroup.of x)) b)
      simp [hallCommutator, iha, ihb]

/-- Universal subgroup form of Petresco 8.3: a commutator word belongs to
`E^μ` whenever it involves at least `μ` distinct labels. -/
theorem formal_projection_vanishing
    {X : Type v} {L : Type w} [DecidableEq L]
    (label : X → L) (μ : ℕ) (c : FormalCommutator X)
    (hμ : μ ≤ (projectedFormalSupport label c).card) :
    formalGroupCommutator (fun x => FreeGroup.of x) c ∈
      projectionVanishingSubgroup label μ := by
  rw [projection_vanishing_subgroup]
  intro S hS
  rw [projected_projection_formal]
  apply formal_retain_variables
  intro hsubset
  have hcard := Finset.card_le_card hsubset
  omega

/-- **Petresco 8.2, formal-support form.** A commutator involving every
variable becomes trivial after projection onto fewer variables. -/
theorem retain_variables_support
    {X : Type v} [Fintype X] [DecidableEq X]
    (f : X → G) (c : FormalCommutator X)
    (hc : formalSupport c = Finset.univ)
    (S : Finset X) (hS : S.card < Fintype.card X) :
    formalGroupCommutator (retainVariables S f) c = 1 := by
  apply commutator_retain_variables
  intro hsub
  have hcard := Finset.card_le_card hsub
  rw [hc, Finset.card_univ] at hcard
  exact (Nat.not_le_of_lt hS) hcard

/-- **Petresco 8.3.** A commutator form whose set of distinct labels has
cardinality `ℓ` becomes trivial under every projection onto fewer than `ℓ`
labels. -/
theorem retain_variables_card
    {X : Type v} {L : Type w} [DecidableEq L]
    (label : X → L) (f : X → G) (c : FormalCommutator X)
    (S : Finset L)
    (hS : S.card < (projectedFormalSupport label c).card) :
    formalGroupCommutator
        (retainProjectedVariables label S f) c = 1 := by
  apply formal_retain_variables
  intro hsub
  exact (Nat.not_le_of_lt hS) (Finset.card_le_card hsub)

/-- The universal commutator aggregate of index at least `ℓ`. The normal
closure is harmless here: Proposition 9.1 asserts that the subgroup
generated by these forms is already normal. -/
def commutatorAggregate
    {X : Type v} {L : Type w} [DecidableEq L]
    (label : X → L) (ℓ : ℕ) :
    Subgroup (FreeGroup X) :=
  Subgroup.normalClosure
    {x | ∃ c : FormalCommutator X,
      ℓ ≤ (projectedFormalSupport label c).card ∧
        formalGroupCommutator (fun y => FreeGroup.of y) c = x}

/-- **Petresco 9.1.** The commutator aggregate is normal in the universal
group generated by the labelled variables. -/
theorem commutatorAggregate_normal
    {X : Type v} {L : Type w} [DecidableEq L]
    (label : X → L) (ℓ : ℕ) :
    (commutatorAggregate label ℓ).Normal :=
  Subgroup.normalClosure_normal

/-- The inclusion `O^ℓ ≤ E^ℓ` used in Petresco 9.2 and 9.3. -/
theorem commutator_aggregate_vanishing
    {X : Type v} {L : Type w} [DecidableEq L]
    (label : X → L) (ℓ : ℕ) :
    commutatorAggregate label ℓ ≤
      projectionVanishingSubgroup label ℓ := by
  letI : (projectionVanishingSubgroup label ℓ).Normal :=
    projection_vanishing_normal label ℓ
  unfold commutatorAggregate
  apply Subgroup.normalClosure_le_normal
  rintro x ⟨c, hc, rfl⟩
  exact
    formal_projection_vanishing
      label ℓ c hc

/-- **Petresco 9.3--9.4, exact-support collection form.** Every finite
product of commutator forms collects into blocks indexed by their precise
sets of distinct labels, ordered by increasing index. -/
theorem projected_support_collection
    {X : Type v} {L : Type w} [Fintype L] [DecidableEq L]
    (f : X → G) (label : X → L) (l : List (FormalCommutator X)) :
    ∃ blocks : List (List (FormalCommutator X)),
      List.Forall₂
          (fun S q => ∀ c ∈ q, projectedFormalSupport label c = S)
          (cardinalityNonemptySupports L) blocks ∧
        evalFormalWord f l = evalFormalWord f blocks.flatten :=
  collect_projected_support f label l

/-- Petresco's correction `c_λ(a,b)`. The input list is exactly the
three-factor word `b⁻¹ a⁻¹ (ab)` used in the proof of Proposition 9.5. -/
def correction (a b : G) (k : ℕ) : G :=
  petrescoTerm [b⁻¹, a⁻¹, a * b] k

@[simp]
lemma correction_zero (a b : G) :
    correction a b 0 = 1 :=
  petrescoTerm_zero _

@[simp]
lemma correction_one (a b : G) :
    correction a b 1 = 1 := by
  rw [correction, petrescoTerm_one]
  simp

/-- The recursive formula printed in Petresco 9.5. The inverse of the
ascending prior product is the displayed descending product of inverse
binomial powers. -/
theorem correction_succ_recurrence (a b : G) (n : ℕ) :
    correction a b (n + 1) =
      (petrescoPriorProduct (correction a b) (n + 1))⁻¹ *
        (b⁻¹) ^ (n + 1) * (a⁻¹) ^ (n + 1) * (a * b) ^ (n + 1) := by
  change
    petrescoTerm [b⁻¹, a⁻¹, a * b] (n + 1) =
      (petrescoPriorProduct
        (petrescoTerm [b⁻¹, a⁻¹, a * b]) (n + 1))⁻¹ *
        (b⁻¹) ^ (n + 1) * (a⁻¹) ^ (n + 1) * (a * b) ^ (n + 1)
  rw [petrescoTerm_succ]
  simp [mul_assoc]

/-- **Petresco 9.5.** The correction `c_λ(a,b)` belongs to the
`λ`th one-based lower-central term. -/
theorem correction_central_series (a b : G) (k : ℕ) :
    correction a b k ∈ Subgroup.lowerCentralSeries G (k - 1) := by
  exact petresco_lower_series [b⁻¹, a⁻¹, a * b] k

/-- The binomial collection identity underlying Petresco 9.5. -/
theorem correction_collection_identity (a b : G) (w : ℕ) :
    (b⁻¹) ^ w * (a⁻¹) ^ w * (a * b) ^ w =
      petrescoBinomialProduct (correction a b) w := by
  simpa [correction, mul_assoc] using
    petresco_term_family [b⁻¹, a⁻¹, a * b] w

/-- The subgroup generated by the two elements occurring in Petresco 9.5. -/
def twoGeneratorSubgroup (a b : G) : Subgroup G :=
  Subgroup.closure ({a, b} : Set G)

lemma left_generator_subgroup (a b : G) :
    a ∈ twoGeneratorSubgroup a b := by
  exact Subgroup.subset_closure (by simp)

lemma right_generator_subgroup (a b : G) :
    b ∈ twoGeneratorSubgroup a b := by
  exact Subgroup.subset_closure (by simp)

/-- Petresco's correction commutes with the inclusion of the subgroup
generated by `a` and `b`. -/
lemma correction_generator_subgroup
    (a b : G) (k : ℕ) :
    (twoGeneratorSubgroup a b).subtype
        (correction
          (⟨a, left_generator_subgroup a b⟩ :
            twoGeneratorSubgroup a b)
          (⟨b, right_generator_subgroup a b⟩ :
            twoGeneratorSubgroup a b) k) =
      correction a b k := by
  unfold correction
  rw [map_petrescoTerm]
  rfl

/-- **Petresco 9.5, intrinsic two-generator form.** The correction belongs
to the `k`th one-based lower-central term of the subgroup generated by
`a` and `b`, not merely to the corresponding term of the ambient group. -/
theorem correction_generator_series (a b : G) (k : ℕ) :
    correction a b k ∈
      petrescoLowerSeries (twoGeneratorSubgroup a b) (k - 1) := by
  let H := twoGeneratorSubgroup a b
  let aH : H := ⟨a, left_generator_subgroup a b⟩
  let bH : H := ⟨b, right_generator_subgroup a b⟩
  refine ⟨correction aH bH k, correction_central_series aH bH k, ?_⟩
  exact correction_generator_subgroup a b k

/-- P. Hall's identity displayed after Proposition 9.5. -/
theorem hall_power_identity (a b : G) (w : ℕ) :
    (a * b) ^ w =
      a ^ w * b ^ w *
        petrescoBinomialProduct (correction a b) w := by
  rw [← correction_collection_identity a b w]
  simp [inv_pow, mul_assoc]

end P1954
end Edmonton
end Submission
