import Mathlib


open scoped Topology Pointwise

noncomputable section

namespace Towers

universe u
universe v w z

/-- The normal subgroup generated by all `m`th powers in a group. -/
def powerSubgroup (G : Type*) [Group G] (m : ℕ) : Subgroup G :=
  Subgroup.normalClosure { y : G | ∃ x : G, x ^ m = y }
instance powerSubgroup_normal (G : Type*) [Group G] (m : ℕ) :
    (powerSubgroup G m).Normal := by
  dsimp [powerSubgroup]
  infer_instance
/-- Every literal `m`th power belongs to the `m`th power subgroup. -/
lemma pow_power_subgroup
    {G : Type*} [Group G] (m : ℕ) (x : G) :
    x ^ m ∈ powerSubgroup G m := by
  exact Subgroup.subset_normalClosure ⟨x, rfl⟩
/-- If `m` divides `m'`, then every `m'`th power lies in the subgroup generated by `m`th
powers. -/
lemma power_subgroup_dvd
    {G : Type u} [Group G] {m m' : ℕ}
    (hdiv : m ∣ m') :
    powerSubgroup G m' ≤ powerSubgroup G m := by
  rcases hdiv with ⟨c, rfl⟩
  dsimp [powerSubgroup]
  exact
    Subgroup.normalClosure_le_normal (by
      rintro y ⟨x, rfl⟩
      have hx : x ^ (m * c) = (x ^ c) ^ m := by
        rw [Nat.mul_comm, pow_mul]
      rw [hx]
      exact Subgroup.subset_normalClosure ⟨x ^ c, rfl⟩)
/-- Ordered products of `m`th powers.

The indexing is deliberately by `Fin k` rather than by a finset product, since the ambient group is
not assumed commutative. -/
def powerWordMap (G : Type*) [Group G] (m : ℕ) :
    (k : ℕ) → (Fin k → G) → G
  | 0, _ => 1
  | k + 1, x =>
      powerWordMap G m k (fun i : Fin k => x i.castSucc) *
        x (Fin.last k) ^ m
/-- Bounded width for the subgroup generated by `m`th powers. -/
def HPWidth (G : Type*) [Group G] (m k : ℕ) : Prop :=
  ∀ g : G,
    g ∈ powerSubgroup G m →
      ∃ x : Fin k → G, powerWordMap G m k x = g
/-- `t` generates `G` as an abstract group. -/
def GeneratedBy {G : Type u} [Group G] {d : ℕ} (t : Fin d → G) : Prop :=
  Subgroup.closure (Set.range t) = ⊤
/-- Uniform finite power width for finite `d`-generated groups. -/
def PWBound.{q} (d m k : ℕ) : Prop :=
  ∀ (G : Type q) [Group G] [Finite G] (t : Fin d → G),
    GeneratedBy t →
      HPWidth G m k
/-- Restricted-Burnside-style cardinal bound for finite `d`-generated exponent-`m` groups. -/
def RBBound.{q} (d m B : ℕ) : Prop :=
  ∀ (G : Type q) [Group G] [Finite G],
    (∃ t : Fin d → G, GeneratedBy t) →
      (∀ x : G, x ^ m = 1) →
        Nat.card G ≤ B
/-- Combined finite Nikolov-Segal/RBT package needed later. -/
def WIBound.{q} (d m k B : ℕ) : Prop :=
  ∀ (G : Type q) [Group G] [Finite G] (t : Fin d → G),
    GeneratedBy t →
      HPWidth G m k ∧
        Nat.card (G ⧸ powerSubgroup G m) ≤ B
/-- The finite prime-power package eventually needed for the profinite power-subgroup theorem. -/
def NPPower.{q} (d p e : ℕ) [Fact p.Prime] : Prop :=
  ∃ k B : ℕ,
    WIBound.{q} d (p ^ e) k B
/-- Finite Nikolov-Segal power-width input, prime-power case. -/
def NWPrime.{q} (d p e : ℕ) [Fact p.Prime] : Prop :=
  ∃ k : ℕ, PWBound.{q} d (p ^ e) k
/-- Restricted Burnside cardinal-bound input, prime-power case. -/
def RBPower.{q} (d p e : ℕ) [Fact p.Prime] : Prop :=
  ∃ B : ℕ, RBBound.{q} d (p ^ e) B
/-- Every bounded power word belongs to the power subgroup. -/
lemma power_subgroup
    {G : Type*} [Group G] (m : ℕ) :
    ∀ (k : ℕ) (x : Fin k → G),
      powerWordMap G m k x ∈ powerSubgroup G m
  | 0, _ => by
      simp [powerWordMap]
  | k + 1, x => by
      have hprev :
          powerWordMap G m k (fun i : Fin k => x i.castSucc) ∈
            powerSubgroup G m :=
        power_subgroup (G := G) m k
          (fun i : Fin k => x i.castSucc)
      have hlast : x (Fin.last k) ^ m ∈ powerSubgroup G m :=
        pow_power_subgroup m (x (Fin.last k))
      simpa [powerWordMap] using (powerSubgroup G m).mul_mem hprev hlast
/-- Appending one trivial power leaves a power word unchanged. -/
lemma succ_extend_one
    {G : Type u} [Group G]
    (m k : ℕ) (x : Fin k → G) :
    powerWordMap G m (k + 1)
      (fun i : Fin (k + 1) =>
        if h : (i : ℕ) < k then x ⟨(i : ℕ), h⟩ else 1)
      =
    powerWordMap G m k x := by
  simp [powerWordMap]
/-- A width bound with `k` slots gives one with `k + 1` slots by padding with `1`. -/
lemma HPWidth.succ
    {G : Type u} [Group G] {m k : ℕ}
    (hwidth : HPWidth G m k) :
    HPWidth G m (k + 1) := by
  intro g hg
  rcases hwidth g hg with ⟨x, hx⟩
  refine
    ⟨fun i : Fin (k + 1) =>
      if h : (i : ℕ) < k then x ⟨(i : ℕ), h⟩ else 1, ?_⟩
  rw [succ_extend_one]
  exact hx
/-- A width bound remains valid after adding any number of padding slots. -/
lemma HPWidth.add_right
    {G : Type u} [Group G] {m k : ℕ}
    (hwidth : HPWidth G m k) :
    ∀ r : ℕ, HPWidth G m (k + r) := by
  intro r
  induction r with
  | zero =>
      simpa using hwidth
  | succ r ih =>
      simpa [Nat.add_assoc] using
        (HPWidth.succ (G := G) (m := m) (k := k + r) ih)
/-- A width bound is monotone in the number of available power-word slots. -/
lemma HPWidth.mono_k
    {G : Type u} [Group G] {m k k' : ℕ}
    (hwidth : HPWidth G m k)
    (hkk' : k ≤ k') :
    HPWidth G m k' := by
  have h :=
    HPWidth.add_right
      (G := G) (m := m) hwidth (k' - k)
  simpa [Nat.add_sub_of_le hkk'] using h
/-- Append one final letter to a power word. -/
lemma power_succ_extend
    {G : Type u} [Group G]
    (m k : ℕ) (x : Fin k → G) (a : G) :
    powerWordMap G m (k + 1)
      (fun i : Fin (k + 1) =>
        if h : (i : ℕ) < k then x ⟨(i : ℕ), h⟩ else a)
      =
    powerWordMap G m k x * a ^ m := by
  simp [powerWordMap]
/-- The product of two power words is itself some power word. -/
lemma power_word_mul
    {G : Type u} [Group G] (m : ℕ)
    {k l : ℕ} (x : Fin k → G) (y : Fin l → G) :
    ∃ r : ℕ, ∃ z : Fin r → G,
      powerWordMap G m r z =
        powerWordMap G m k x * powerWordMap G m l y := by
  induction l generalizing k with
  | zero =>
      refine ⟨k, x, ?_⟩
      simp [powerWordMap]
  | succ l ih =>
      let y₀ : Fin l → G := fun i => y i.castSucc
      rcases ih (k := k) x y₀ with ⟨r, z, hz⟩
      refine
        ⟨r + 1,
          (fun i : Fin (r + 1) =>
            if h : (i : ℕ) < r then z ⟨(i : ℕ), h⟩ else y (Fin.last l)),
          ?_⟩
      rw [power_succ_extend]
      calc
        powerWordMap G m r z * (y (Fin.last l)) ^ m =
            (powerWordMap G m k x * powerWordMap G m l y₀) *
              (y (Fin.last l)) ^ m := by
          rw [hz]
        _ = powerWordMap G m k x *
              (powerWordMap G m l y₀ * (y (Fin.last l)) ^ m) := by
          simp [mul_assoc]
        _ = powerWordMap G m k x * powerWordMap G m (l + 1) y := by
          simp [powerWordMap, y₀]
/-- The inverse of a power word is itself some power word. -/
lemma power_word_inv
    {G : Type u} [Group G] (m : ℕ)
    {k : ℕ} (x : Fin k → G) :
    ∃ r : ℕ, ∃ z : Fin r → G,
      powerWordMap G m r z =
        (powerWordMap G m k x)⁻¹ := by
  induction k with
  | zero =>
      refine ⟨0, (fun i : Fin 0 => Fin.elim0 i), ?_⟩
      simp [powerWordMap]
  | succ k ih =>
      let x₀ : Fin k → G := fun i => x i.castSucc
      rcases ih x₀ with ⟨r, z, hz⟩
      let lastInv : Fin 1 → G := fun _ => (x (Fin.last k))⁻¹
      rcases power_word_mul
          (G := G) (m := m)
          lastInv z with
        ⟨s, w, hw⟩
      refine ⟨s, w, ?_⟩
      have hlast :
          powerWordMap G m 1 lastInv =
            ((x (Fin.last k)) ^ m)⁻¹ := by
        simp [powerWordMap, lastInv]
      calc
        powerWordMap G m s w =
            powerWordMap G m 1 lastInv * powerWordMap G m r z := hw
        _ = ((x (Fin.last k)) ^ m)⁻¹ *
              (powerWordMap G m k x₀)⁻¹ := by
          rw [hlast, hz]
        _ = (powerWordMap G m (k + 1) x)⁻¹ := by
          simp [powerWordMap, x₀]
/-- Conjugating an element commutes with taking natural powers. -/
lemma conj_pow_aux
    {G : Type u} [Group G]
    (a x : G) (n : ℕ) :
    (a * x * a⁻¹) ^ n = a * x ^ n * a⁻¹ := by
  induction n with
  | zero =>
      simp
  | succ n ih =>
      rw [pow_succ, ih, pow_succ]
      group
/-- Power words commute with simultaneous conjugation of all letters. -/
lemma power_word_conj
    {G : Type u} [Group G]
    (m k : ℕ) (a : G) (x : Fin k → G) :
    powerWordMap G m k (fun i => a * x i * a⁻¹) =
      a * powerWordMap G m k x * a⁻¹ := by
  induction k with
  | zero =>
      simp [powerWordMap]
  | succ k ih =>
      let x₀ : Fin k → G := fun i => x i.castSucc
      calc
        powerWordMap G m (k + 1) (fun i : Fin (k + 1) => a * x i * a⁻¹) =
            powerWordMap G m k (fun i : Fin k => a * x₀ i * a⁻¹) *
              (a * x (Fin.last k) * a⁻¹) ^ m := by
          simp [powerWordMap, x₀]
        _ = (a * powerWordMap G m k x₀ * a⁻¹) *
              (a * (x (Fin.last k)) ^ m * a⁻¹) := by
          rw [ih x₀, conj_pow_aux]
        _ = a *
              (powerWordMap G m k x₀ * (x (Fin.last k)) ^ m) *
              a⁻¹ := by
          group
        _ = a * powerWordMap G m (k + 1) x * a⁻¹ := by
          simp [powerWordMap, x₀, mul_assoc]
/-- The subgroup of all finite products of `m`th powers. -/
def powerWordSubgroup (G : Type u) [Group G] (m : ℕ) : Subgroup G where
  carrier := {g : G | ∃ k : ℕ, ∃ x : Fin k → G, powerWordMap G m k x = g}
  one_mem' := by
    refine ⟨0, (fun i : Fin 0 => Fin.elim0 i), ?_⟩
    simp [powerWordMap]
  mul_mem' := by
    rintro a b ⟨ka, xa, hxa⟩ ⟨kb, xb, hxb⟩
    rcases power_word_mul
        (G := G) (m := m) xa xb with
      ⟨r, z, hz⟩
    refine ⟨r, z, ?_⟩
    rw [hz, hxa, hxb]
  inv_mem' := by
    rintro a ⟨k, x, hx⟩
    rcases power_word_inv
        (G := G) (m := m) x with
      ⟨r, z, hz⟩
    refine ⟨r, z, ?_⟩
    rw [hz, hx]
/-- The finite-products-of-powers subgroup is normal. -/
lemma power_subgroup_normal
    (G : Type u) [Group G] (m : ℕ) :
    (powerWordSubgroup G m).Normal := by
  refine ⟨?_⟩
  intro n hn g
  rcases hn with ⟨k, x, hx⟩
  refine ⟨k, (fun i : Fin k => g * x i * g⁻¹), ?_⟩
  rw [power_word_conj]
  rw [hx]
/-- The normal subgroup generated by `m`th powers lies in the subgroup of all finite products of
`m`th powers. -/
lemma power_word
    {G : Type u} [Group G] (m : ℕ) :
    powerSubgroup G m ≤ powerWordSubgroup G m := by
  dsimp [powerSubgroup]
  haveI : (powerWordSubgroup G m).Normal :=
    power_subgroup_normal G m
  exact
    Subgroup.normalClosure_le_normal (by
      rintro y ⟨x, rfl⟩
      refine ⟨1, (fun _ : Fin 1 => x), ?_⟩
      simp [powerWordMap])
/-- Every finite product of `m`th powers lies in the normal power subgroup. -/
lemma power_word_subgroup
    {G : Type u} [Group G] (m : ℕ) :
    powerWordSubgroup G m ≤ powerSubgroup G m := by
  intro g hg
  rcases hg with ⟨k, x, hx⟩
  rw [← hx]
  exact power_subgroup (G := G) m k x
/-- The power subgroup is exactly the subgroup of finite products of `m`th powers. -/
lemma power_subgroup_word
    (G : Type u) [Group G] (m : ℕ) :
    powerSubgroup G m = powerWordSubgroup G m :=
  le_antisymm
    (power_word (G := G) m)
    (power_word_subgroup (G := G) m)
/-- Pad a concrete power word on the right by trivial powers. -/
lemma power_pad_right
    {G : Type u} [Group G] (m : ℕ)
    {k : ℕ} (x : Fin k → G) :
    ∀ r : ℕ,
      ∃ y : Fin (k + r) → G,
        powerWordMap G m (k + r) y =
          powerWordMap G m k x := by
  intro r
  induction r with
  | zero =>
      exact ⟨x, rfl⟩
  | succ r ih =>
      rcases ih with ⟨y, hy⟩
      refine
        ⟨fun i : Fin (k + (r + 1)) =>
          if h : (i : ℕ) < k + r then
            y ⟨(i : ℕ), h⟩
          else
            1,
          ?_⟩
      have h :=
        power_succ_extend
          (G := G) (m := m) (k := k + r)
          y 1
      simpa [Nat.add_assoc, hy] using h
/-- A width bound identifies the power subgroup as the range of one compact-domain word map. -/
lemma power_range_width
    {G : Type*} [Group G]
    {m k : ℕ}
    (hwidth : HPWidth G m k) :
    ((powerSubgroup G m : Subgroup G) : Set G) =
      Set.range (powerWordMap G m k) := by
  ext g
  constructor
  · intro hg
    rcases hwidth g hg with ⟨x, rfl⟩
    exact ⟨x, rfl⟩
  · rintro ⟨x, rfl⟩
    exact power_subgroup (G := G) m k x
/-- Every finite group has some finite, non-uniform width for its `m`th-power subgroup. -/
theorem power_width_finite
    (G : Type u) [Group G] [Finite G] (m : ℕ) :
    ∃ k : ℕ, HPWidth G m k := by
  classical
  let P : Subgroup G := powerSubgroup G m
  letI : Fintype P := Fintype.ofFinite P
  have hex :
      ∀ a : P,
        ∃ k : ℕ, ∃ x : Fin k → G,
          powerWordMap G m k x = (a : G) := by
    intro a
    have ha : (a : G) ∈ powerWordSubgroup G m := by
      have haP : (a : G) ∈ powerSubgroup G m := a.property
      simpa [power_subgroup_word (G := G) m] using haP
    exact ha
  let len : P → ℕ := fun a => Classical.choose (hex a)
  let word : ∀ a : P, Fin (len a) → G :=
    fun a => Classical.choose (Classical.choose_spec (hex a))
  have hword :
      ∀ a : P,
        powerWordMap G m (len a) (word a) = (a : G) := by
    intro a
    exact Classical.choose_spec (Classical.choose_spec (hex a))
  let K : ℕ := Finset.univ.sup len
  refine ⟨K, ?_⟩
  intro g hg
  let a : P := ⟨g, hg⟩
  have hlen_le : len a ≤ K := by
    exact Finset.le_sup (s := Finset.univ) (f := len) (by simp : a ∈ Finset.univ)
  rcases power_pad_right
      (G := G) (m := m) (x := word a)
      (K - len a) with
    ⟨y, hy⟩
  have hrep :
      ∃ y : Fin (len a + (K - len a)) → G,
        powerWordMap G m (len a + (K - len a)) y = g := by
    refine ⟨y, ?_⟩
    rw [hy, hword a]
  have hsum : len a + (K - len a) = K := Nat.add_sub_of_le hlen_le
  rw [hsum] at hrep
  exact hrep
/-- The minimal finite power width of a finite group for exponent `m`. -/
noncomputable def powerWidthNumber
    (G : Type u) [Group G] [Finite G] (m : ℕ) : ℕ :=
  by
    classical
    exact Nat.find (power_width_finite (G := G) m)
/-- The minimal finite power width satisfies the width predicate. -/
lemma width_number_spec
    (G : Type u) [Group G] [Finite G] (m : ℕ) :
    HPWidth G m (powerWidthNumber G m) := by
  classical
  unfold powerWidthNumber
  exact Nat.find_spec (power_width_finite (G := G) m)
/-- The minimal finite power width is bounded by any other witnessed width. -/
lemma power_width_number
    {G : Type u} [Group G] [Finite G] {m k : ℕ}
    (h : HPWidth G m k) :
    powerWidthNumber G m ≤ k := by
  classical
  unfold powerWidthNumber
  exact Nat.find_min'
    (p := fun k => HPWidth G m k)
    (power_width_finite (G := G) m)
    h
/-- Uniform boundedness of the minimal individual finite power-width invariant. -/
def UMBound.{q}
    (d m k : ℕ) : Prop :=
  ∀ (G : Type q) [Group G] [Finite G] (t : Fin d → G),
    GeneratedBy t →
      powerWidthNumber G m ≤ k
/-- A uniform minimal-width bound gives the original finite power-width bound. -/
lemma bound_uniform_minimal
    {d m k : ℕ}
    (h : UMBound.{u} d m k) :
    PWBound.{u} d m k := by
  intro G _instGroup _instFinite t ht
  exact
    HPWidth.mono_k
      (width_number_spec G m)
      (h G t ht)
/-- The original finite power-width bound gives a uniform minimal-width bound. -/
lemma uniform_minimal_width
    {d m k : ℕ}
    (h : PWBound.{u} d m k) :
    UMBound.{u} d m k := by
  intro G _instGroup _instFinite t ht
  exact
    power_width_number
      (G := G) (m := m)
      (h G t ht)
/-- Uniform boundedness of minimal finite widths is equivalent to the original finite-width
package. -/
theorem width_uniform_minimal
    {d m k : ℕ} :
    PWBound.{u} d m k ↔
      UMBound.{u} d m k := by
  constructor
  · exact uniform_minimal_width
  · exact bound_uniform_minimal
/-- Uniform minimal-width input, prime-power case. -/
def UMWidth.{q}
    (d p e k : ℕ) [Fact p.Prime] : Prop :=
  UMBound.{q} d (p ^ e) k
/-- Uniform minimal-width bounds imply the finite Nikolov-Segal width input. -/
theorem ns_uniform_minimal
    {d p e k : ℕ} [Fact p.Prime]
    (h : UMWidth.{u} d p e k) :
    NWPrime.{u} d p e := by
  exact
    ⟨k,
      bound_uniform_minimal
        (d := d) (m := p ^ e) (k := k) h⟩
/-- The finite Nikolov-Segal width input is equivalent to the existence of a uniform bound on the
minimal finite widths. -/
theorem uniform_minimal_ns
    {d p e : ℕ} [Fact p.Prime]
    (h : NWPrime.{u} d p e) :
    ∃ k : ℕ, UMWidth.{u} d p e k := by
  rcases h with ⟨k, hk⟩
  exact
    ⟨k,
      uniform_minimal_width
        (d := d) (m := p ^ e) (k := k) hk⟩
end Towers
