import Submission.Group.NilpotentProducts.TripleCommutators
import Mathlib.GroupTheory.SpecificGroups.Dihedral


/-!
# The two-involution induction in Struik's ill-behaved case

For two involutions `a` and `b`, conjugation by `b` inverts their Hall
commutator.  This gives Struik's induction
`(a,b)^(2^(n-2)) ∈ F_n` without any nilpotency assumption.
-/

namespace Struik
namespace P1960

open Submission
open Submission.Edmonton
open scoped commutatorElement

universe u

variable {G : Type u} [Group G]

/-- Conjugation by the second of two involutions inverts their Hall
commutator. -/
lemma involutions_conjugate_commutator
    (a b : G) (ha : a ^ 2 = 1) (hb : b ^ 2 = 1) :
    b⁻¹ * hallCommutator a b * b =
      (hallCommutator a b)⁻¹ := by
  have hamul : a * a = 1 := by
    simpa [pow_two] using ha
  have hbmul : b * b = 1 := by
    simpa [pow_two] using hb
  have hainv : a⁻¹ = a :=
    inv_eq_of_mul_eq_one_right hamul
  have hbinv : b⁻¹ = b :=
    inv_eq_of_mul_eq_one_right hbmul
  simp [hallCommutator, hainv, hbinv, hbmul, mul_assoc]

/-- The commutator of a power of `(a,b)` with `b` is the inverse square of
that power. -/
lemma two_involutions_right
    (a b : G) (ha : a ^ 2 = 1) (hb : b ^ 2 = 1) (m : ℕ) :
    hallCommutator ((hallCommutator a b) ^ m) b =
      (((hallCommutator a b) ^ m) ^ 2)⁻¹ := by
  let C := hallCommutator a b
  have hconj : b⁻¹ * C * b = C⁻¹ := by
    simpa [C] using involutions_conjugate_commutator a b ha hb
  have hconjPow : b⁻¹ * C ^ m * b = (C ^ m)⁻¹ := by
    calc
      b⁻¹ * C ^ m * b =
          (MulAut.conj b⁻¹) (C ^ m) := by
            simp
      _ = ((MulAut.conj b⁻¹) C) ^ m := by
            rw [map_pow]
      _ = (C⁻¹) ^ m := by
            rw [show (MulAut.conj b⁻¹) C = C⁻¹ by
              simpa [MulAut.conj_apply] using hconj]
      _ = (C ^ m)⁻¹ := by simp
  change hallCommutator (C ^ m) b = ((C ^ m) ^ 2)⁻¹
  rw [hallCommutator]
  calc
    (C ^ m)⁻¹ * b⁻¹ * C ^ m * b =
        (C ^ m)⁻¹ * (b⁻¹ * C ^ m * b) := by group
    _ = (C ^ m)⁻¹ * (C ^ m)⁻¹ := by rw [hconjPow]
    _ = ((C ^ m) ^ 2)⁻¹ := by simp [pow_two]

/-- Subtraction-free form of Struik's induction:
`(a,b)^(2^k)` lies in the `(k+2)`nd one-based lower-central term. -/
theorem involutions_lower_series
    (a b : G) (ha : a ^ 2 = 1) (hb : b ^ 2 = 1) :
    ∀ k : ℕ,
      (hallCommutator a b) ^ (2 ^ k) ∈
        Subgroup.lowerCentralSeries G (k + 1) := by
  intro k
  induction k with
  | zero =>
      have haTop : a ∈ Subgroup.lowerCentralSeries G 0 := by simp
      have hbTop : b ∈ Subgroup.lowerCentralSeries G 0 := by simp
      simpa using
        commutator_lower_series haTop hbTop
  | succ k ih =>
      have hbTop : b ∈ Subgroup.lowerCentralSeries G 0 := by simp
      have hcomm :
          hallCommutator
              ((hallCommutator a b) ^ (2 ^ k)) b ∈
            Subgroup.lowerCentralSeries G (k + 2) := by
        simpa [Nat.add_assoc] using
          commutator_lower_series ih hbTop
      rw [two_involutions_right a b ha hb] at hcomm
      have hsquare :
          ((hallCommutator a b) ^ (2 ^ k)) ^ 2 ∈
            Subgroup.lowerCentralSeries G (k + 2) := by
        simpa using
          (Subgroup.lowerCentralSeries G (k + 2)).inv_mem hcomm
      simpa only [Nat.pow_succ, pow_mul] using hsquare

/-- Struik's displayed indexing: for `2 ≤ n`,
`(a,b)^(2^(n-2))` belongs to the paper's `F_n`. -/
theorem two_involutions_series
    (a b : G) (ha : a ^ 2 = 1) (hb : b ^ 2 = 1)
    (n : ℕ) (hn : 2 ≤ n) :
    (hallCommutator a b) ^ (2 ^ (n - 2)) ∈
      Subgroup.lowerCentralSeries G (n - 1) := by
  have hindex : n - 2 + 1 = n - 1 := by omega
  simpa only [hindex] using
    involutions_lower_series
      a b ha hb (n - 2)

/-- The two standard normal-form shapes for a group generated by
involutions `a` and `b`. -/
def twoInvolutionForm
    (a b : G) (side : Fin 2) (z : ℤ) : G :=
  if side = 0 then (a * b) ^ z else a * (a * b) ^ z

/-- Conjugation by the first involution inverts the rotation `a*b`. -/
lemma involutions_rotation_zpow
    (a b : G) (ha : a ^ 2 = 1) (hb : b ^ 2 = 1) (z : ℤ) :
    a * (a * b) ^ z * a = (a * b) ^ (-z) := by
  have hamul : a * a = 1 := by
    simpa [pow_two] using ha
  have hbmul : b * b = 1 := by
    simpa [pow_two] using hb
  have hainv : a⁻¹ = a :=
    inv_eq_of_mul_eq_one_right hamul
  have hbinv : b⁻¹ = b :=
    inv_eq_of_mul_eq_one_right hbmul
  have hrotation :
      a * (a * b) * a⁻¹ = (a * b)⁻¹ := by
    rw [hainv, mul_inv_rev, hbinv, hainv]
    calc
      a * (a * b) * a = (a * a) * (b * a) := by group
      _ = b * a := by rw [hamul, one_mul]
  calc
    a * (a * b) ^ z * a =
        a * (a * b) ^ z * a⁻¹ := by rw [hainv]
    _ = (a * (a * b) * a⁻¹) ^ z := conj_zpow.symm
    _ = ((a * b)⁻¹) ^ z := by rw [hrotation]
    _ = (a * b) ^ (-z) := by
      rw [inv_zpow, zpow_neg]

/-- Right multiplication of a two-involution normal form by either
generator stays in normal form. -/
lemma involution_form_generator
    (a b : G) (ha : a ^ 2 = 1) (hb : b ^ 2 = 1)
    (side : Fin 2) (z : ℤ) (i : Fin 2) :
    ∃ side' : Fin 2, ∃ z' : ℤ,
      twoInvolutionForm a b side z *
          (if i = 0 then a else b) =
        twoInvolutionForm a b side' z' := by
  have hamul : a * a = 1 := by
    simpa [pow_two] using ha
  have hconj :=
    involutions_rotation_zpow a b ha hb z
  have hmulA :
      (a * b) ^ z * a = a * (a * b) ^ (-z) := by
    calc
      (a * b) ^ z * a =
          1 * ((a * b) ^ z * a) := by simp
      _ = (a * a) * ((a * b) ^ z * a) := by rw [hamul]
      _ = a * (a * (a * b) ^ z * a) := by group
      _ = a * (a * b) ^ (-z) := by rw [hconj]
  have hmulB :
      (a * b) ^ z * b = a * (a * b) ^ (1 - z) := by
    calc
      (a * b) ^ z * b =
          (a * b) ^ z * (1 * b) := by simp
      _ = (a * b) ^ z * ((a * a) * b) := by rw [hamul]
      _ = ((a * b) ^ z * a) * (a * b) := by group
      _ = (a * (a * b) ^ (-z)) * (a * b) := by rw [hmulA]
      _ = a * ((a * b) ^ (-z) * (a * b)) := by group
      _ = a * (a * b) ^ (1 - z) := by
        rw [show 1 - z = -z + 1 by ring, zpow_add, zpow_one]
  fin_cases side <;> fin_cases i
  · refine ⟨1, -z, ?_⟩
    simpa [twoInvolutionForm] using hmulA
  · refine ⟨1, 1 - z, ?_⟩
    simpa [twoInvolutionForm] using hmulB
  · refine ⟨0, -z, ?_⟩
    simpa [twoInvolutionForm] using hconj
  · refine ⟨0, 1 - z, ?_⟩
    change
      (a * (a * b) ^ z) * b =
        (a * b) ^ (1 - z)
    calc
      (a * (a * b) ^ z) * b =
          a * ((a * b) ^ z * b) := by group
      _ = a * (a * (a * b) ^ (1 - z)) := by rw [hmulB]
      _ = (a * a) * (a * b) ^ (1 - z) := by group
      _ = (a * b) ^ (1 - z) := by rw [hamul, one_mul]

/-- Every element of the subgroup generated by two involutions has one of
the two standard dihedral normal forms. -/
theorem involution_form_closure
    (a b : G) (ha : a ^ 2 = 1) (hb : b ^ 2 = 1)
    {x : G}
    (hx :
      x ∈ Subgroup.closure
        (Set.range fun i : Fin 2 => if i = 0 then a else b)) :
    ∃ side : Fin 2, ∃ z : ℤ,
      x = twoInvolutionForm a b side z := by
  induction hx using Subgroup.closure_induction_right with
  | one =>
      exact ⟨0, 0, by simp [twoInvolutionForm]⟩
  | mul_right x hx i hi ih =>
      obtain ⟨side, z, rfl⟩ := ih
      obtain ⟨j, rfl⟩ := hi
      obtain ⟨side', z', hnormal⟩ :=
        involution_form_generator
          a b ha hb side z j
      exact ⟨side', z', hnormal⟩
  | mul_inv_cancel x hx i hi ih =>
      obtain ⟨side, z, rfl⟩ := ih
      obtain ⟨j, rfl⟩ := hi
      have hinvolution :
          (if j = 0 then a else b)⁻¹ =
            (if j = 0 then a else b) := by
        fin_cases j
        · simp only [Fin.zero_eta, Fin.isValue, ↓reduceIte]
          exact inv_eq_of_mul_eq_one_right
            (by simpa [pow_two] using ha)
        · simp only [Fin.mk_one, OfNat.ofNat]
          exact inv_eq_of_mul_eq_one_right
            (by simpa [pow_two] using hb)
      rw [hinvolution]
      obtain ⟨side', z', hnormal⟩ :=
        involution_form_generator
          a b ha hb side z j
      exact ⟨side', z', hnormal⟩

/-- Reduce the rotation exponent in a two-involution normal form modulo a
known annihilating exponent. -/
def involutionResidueForm
    (a b : G) (N : ℕ) (p : Fin 2 × ZMod N) : G :=
  twoInvolutionForm a b p.1 p.2.val

/-- If two involutions generate the group and `(a*b)^N=1`, the two residue
normal-form families cover the whole group. -/
theorem involution_form_surjective
    (a b : G) (ha : a ^ 2 = 1) (hb : b ^ 2 = 1)
    (N : ℕ) [NeZero N]
    (hgenerate :
      Subgroup.closure
          (Set.range fun i : Fin 2 => if i = 0 then a else b) =
        ⊤)
    (hrotation : (a * b) ^ N = 1) :
    Function.Surjective
      (involutionResidueForm a b N) := by
  intro x
  have hx :
      x ∈ Subgroup.closure
        (Set.range fun i : Fin 2 => if i = 0 then a else b) := by
    rw [hgenerate]
    simp
  obtain ⟨side, z, hxnormal⟩ :=
    involution_form_closure
      a b ha hb hx
  let k : ZMod N := z
  have hmod : z ≡ (k.val : ℤ) [ZMOD (N : ℤ)] := by
    apply (ZMod.intCast_eq_intCast_iff z (k.val : ℤ) N).mp
    calc
      (z : ZMod N) = k := rfl
      _ = ((k.val : ℤ) : ZMod N) := by
        simpa only [Int.cast_natCast] using
          (ZMod.natCast_zmod_val k).symm
  have horder : orderOf (a * b) ∣ N :=
    orderOf_dvd_iff_pow_eq_one.mpr hrotation
  have hpower :
      (a * b) ^ z = (a * b) ^ (k.val : ℤ) := by
    apply orderOf_dvd_sub_iff_zpow_eq_zpow.mp
    exact
      (Int.natCast_dvd_natCast.mpr horder).trans
        ((Int.modEq_iff_dvd).mp hmod.symm)
  refine ⟨(side, k), ?_⟩
  rw [hxnormal]
  unfold involutionResidueForm twoInvolutionForm
  by_cases hside : side = 0 <;> simp [hside, hpower]

/-- The constant order-two family on two generators. -/
def orderTwoPair (_ : Fin 2) : ℕ := 2

theorem order_pair_pow
    (i : Fin 2) :
    cyclicGenerator orderTwoPair i ^ 2 = 1 := by
  simpa [orderTwoPair] using
    cyclic_generator_order orderTwoPair i

/-- The two canonical generators generate every nilpotent quotient of
`C₂ * C₂`. -/
theorem closure_nilpotent_top
    (n : ℕ) :
    Subgroup.closure
        (Set.range
          (nilpotentCyclicGenerator orderTwoPair n)) =
      (⊤ : Subgroup (NilpotentCyclicProduct orderTwoPair n)) := by
  apply top_unique
  intro x _
  obtain ⟨y, rfl⟩ :=
    QuotientGroup.mk'_surjective
      (Subgroup.lowerCentralSeries
        (CyclicFreeProduct orderTwoPair) (n - 1)) x
  let q : CyclicFreeProduct orderTwoPair →*
      NilpotentCyclicProduct orderTwoPair n :=
    QuotientGroup.mk'
      (Subgroup.lowerCentralSeries
        (CyclicFreeProduct orderTwoPair) (n - 1))
  let H : Subgroup (NilpotentCyclicProduct orderTwoPair n) :=
    Subgroup.closure
      (Set.range
        (nilpotentCyclicGenerator orderTwoPair n))
  change q y ∈ H
  have hy : y ∈ H.comap q := by
    apply PresentedGroup.generated_by
      (cyclicOrderRelators orderTwoPair)
    intro i
    change q (cyclicGenerator orderTwoPair i) ∈ H
    exact Subgroup.subset_closure (Set.mem_range_self i)
  exact hy

/-- Struik's induction specialized to the free product `C₂ * C₂`. -/
theorem order_pair_series
    (n : ℕ) (hn : 2 ≤ n) :
    (hallCommutator
        (cyclicGenerator orderTwoPair 0)
        (cyclicGenerator orderTwoPair 1)) ^ (2 ^ (n - 2)) ∈
      Subgroup.lowerCentralSeries (CyclicFreeProduct orderTwoPair) (n - 1) :=
  two_involutions_series
    (cyclicGenerator orderTwoPair 0)
    (cyclicGenerator orderTwoPair 1)
    (order_pair_pow 0)
    (order_pair_pow 1)
    n hn

/-- Consequently, in Struik's quotient `F/F_n`, the basic commutator is
killed by `2^(n-2)`. -/
theorem order_pair_nilpotent
    (n : ℕ) (hn : 2 ≤ n) :
    (hallCommutator
        (nilpotentCyclicGenerator orderTwoPair n 0)
        (nilpotentCyclicGenerator orderTwoPair n 1)) ^
        (2 ^ (n - 2)) =
      1 := by
  have hmem :=
    two_involutions_series
      (nilpotentCyclicGenerator orderTwoPair n 0)
      (nilpotentCyclicGenerator orderTwoPair n 1)
      (by simpa [orderTwoPair] using
        nilpotent_cyclic_generator orderTwoPair n 0)
      (by simpa [orderTwoPair] using
        nilpotent_cyclic_generator orderTwoPair n 1)
      n hn
  rw [nilpotent_cyclic_bot
    orderTwoPair n] at hmem
  exact Subgroup.mem_bot.mp hmem

/-- The product of the two canonical involutions is killed by
`2^(n-1)` in `F/F_n`. -/
theorem order_nilpotent_rotation
    (n : ℕ) (hn : 2 ≤ n) :
    (nilpotentCyclicGenerator orderTwoPair n 0 *
        nilpotentCyclicGenerator orderTwoPair n 1) ^
        (2 ^ (n - 1)) =
      1 := by
  let a := nilpotentCyclicGenerator orderTwoPair n (0 : Fin 2)
  let b := nilpotentCyclicGenerator orderTwoPair n (1 : Fin 2)
  have ha : a ^ 2 = 1 := by
    simpa [a, orderTwoPair] using
      nilpotent_cyclic_generator
        orderTwoPair n (0 : Fin 2)
  have hb : b ^ 2 = 1 := by
    simpa [b, orderTwoPair] using
      nilpotent_cyclic_generator
        orderTwoPair n (1 : Fin 2)
  have hamul : a * a = 1 := by
    simpa [pow_two] using ha
  have hbmul : b * b = 1 := by
    simpa [pow_two] using hb
  have hainv : a⁻¹ = a :=
    inv_eq_of_mul_eq_one_right hamul
  have hbinv : b⁻¹ = b :=
    inv_eq_of_mul_eq_one_right hbmul
  have hcommutator :
      hallCommutator a b = (a * b) ^ 2 := by
    simp [hallCommutator, hainv, hbinv, pow_two,
      mul_assoc]
  have hpow :=
    order_pair_nilpotent
      n hn
  change
    (hallCommutator a b) ^ (2 ^ (n - 2)) = 1
    at hpow
  rw [hcommutator, ← pow_mul] at hpow
  have hindex : n - 1 = (n - 2) + 1 := by omega
  have hexponent :
      2 * 2 ^ (n - 2) = 2 ^ (n - 1) := by
    rw [hindex, pow_succ]
    ring
  simpa [a, b, hexponent] using hpow

/-- The two finite dihedral normal-form families in the nilpotent
two-involution quotient. -/
def orderNilpotentForm
    (n : ℕ)
    (p : Fin 2 × ZMod (2 ^ (n - 1))) :
    NilpotentCyclicProduct orderTwoPair n :=
  involutionResidueForm
    (nilpotentCyclicGenerator orderTwoPair n 0)
    (nilpotentCyclicGenerator orderTwoPair n 1)
    (2 ^ (n - 1)) p

/-- Every element of the nilpotent two-involution quotient has one of the
`2 * 2^(n-1)` finite normal forms. -/
theorem nilpotent_form_surjective
    (n : ℕ) (hn : 2 ≤ n) :
    Function.Surjective
      (orderNilpotentForm n) := by
  letI : NeZero (2 ^ (n - 1)) :=
    ⟨pow_ne_zero _ (by norm_num)⟩
  let a :=
    nilpotentCyclicGenerator orderTwoPair n (0 : Fin 2)
  let b :=
    nilpotentCyclicGenerator orderTwoPair n (1 : Fin 2)
  apply involution_form_surjective
    a b
  · simpa [a, orderTwoPair] using
      nilpotent_cyclic_generator
        orderTwoPair n (0 : Fin 2)
  · simpa [b, orderTwoPair] using
      nilpotent_cyclic_generator
        orderTwoPair n (1 : Fin 2)
  · have hvalues :
        (fun i : Fin 2 => if i = 0 then a else b) =
          nilpotentCyclicGenerator orderTwoPair n := by
      funext i
      fin_cases i <;> simp [a, b]
    rw [hvalues]
    exact
      closure_nilpotent_top n
  · simpa [a, b] using
      order_nilpotent_rotation n hn

private lemma dihedral_even_rotations
    {m : ℕ} [NeZero m] (x y : DihedralGroup m) :
    ⁅x, y⁆ ∈
      Subgroup.zpowers (DihedralGroup.r (2 : ZMod m)) := by
  rw [Subgroup.mem_zpowers_iff]
  cases x with
  | r i =>
      cases y with
      | r j =>
          exact ⟨0, by simp [commutatorElement_def]⟩
      | sr j =>
          refine ⟨(i.val : ℤ), ?_⟩
          simp only [ZMod.natCast_val, DihedralGroup.r_zpow,
            ZMod.intCast_cast, ZMod.cast_id', id_eq]
          rw [← ZMod.natCast_zmod_val i]
          simp only [commutatorElement_def, DihedralGroup.inv_r,
            DihedralGroup.inv_sr, DihedralGroup.r_mul_sr,
            DihedralGroup.sr_mul_r, DihedralGroup.sr_mul_sr]
          congr 1
          ring
  | sr i =>
      cases y with
      | r j =>
          refine ⟨-(j.val : ℤ), ?_⟩
          simp only [ZMod.natCast_val, zpow_neg, DihedralGroup.r_zpow,
            ZMod.intCast_cast, ZMod.cast_id', id_eq, DihedralGroup.inv_r]
          rw [← ZMod.natCast_zmod_val j]
          simp only [commutatorElement_def, DihedralGroup.inv_r,
            DihedralGroup.inv_sr, DihedralGroup.r_mul_r,
            DihedralGroup.sr_mul_r, DihedralGroup.sr_mul_sr]
          congr 1
          ring
      | sr j =>
          refine ⟨(j.val : ℤ) - (i.val : ℤ), ?_⟩
          simp only [ZMod.natCast_val, DihedralGroup.r_zpow,
            Int.cast_sub, ZMod.intCast_cast, ZMod.cast_id', id_eq]
          rw [← ZMod.natCast_zmod_val i,
            ← ZMod.natCast_zmod_val j]
          simp only [commutatorElement_def, DihedralGroup.inv_sr,
            DihedralGroup.r_mul_sr, DihedralGroup.sr_mul_sr]
          congr 1
          ring

private lemma dihedral_rotation_next
    {m : ℕ} [NeZero m] (k : ℕ) {x : DihedralGroup m}
    (hx :
      x ∈ Subgroup.zpowers
        (DihedralGroup.r ((2 ^ k : ℕ) : ZMod m)))
    (y : DihedralGroup m) :
    ⁅x, y⁆ ∈
      Subgroup.zpowers
        (DihedralGroup.r ((2 ^ (k + 1) : ℕ) : ZMod m)) := by
  obtain ⟨z, rfl⟩ := Subgroup.mem_zpowers_iff.mp hx
  rw [Subgroup.mem_zpowers_iff]
  cases y with
  | r j =>
      exact ⟨0, by simp [commutatorElement_def]⟩
  | sr j =>
      refine ⟨z, ?_⟩
      simp [commutatorElement_def, Nat.pow_succ]
      ring

/-- In a dihedral group, the `(k+2)`nd one-based lower-central term is
contained in the rotations generated by `r(2^(k+1))`. -/
theorem dihedral_rotation_powers
    (m : ℕ) [NeZero m] :
    ∀ k : ℕ,
      Subgroup.lowerCentralSeries (DihedralGroup m) (k + 1) ≤
        Subgroup.zpowers
          (DihedralGroup.r ((2 ^ (k + 1) : ℕ) : ZMod m)) := by
  intro k
  induction k with
  | zero =>
      change ⁅(⊤ : Subgroup (DihedralGroup m)), ⊤⁆ ≤
        Subgroup.zpowers (DihedralGroup.r (2 : ZMod m))
      rw [Subgroup.commutator_le]
      intro x _ y _
      exact dihedral_even_rotations x y
  | succ k ih =>
      change
        ⁅Subgroup.lowerCentralSeries (DihedralGroup m) (k + 1), ⊤⁆ ≤
          Subgroup.zpowers
            (DihedralGroup.r
              ((2 ^ ((k + 1) + 1) : ℕ) : ZMod m))
      rw [Subgroup.commutator_le]
      intro x hx y _
      exact
        dihedral_rotation_next
          (k + 1) (ih hx) y

/-- The dihedral group with `2^(n-1)` rotations has trivial `n`th
one-based lower-central term. -/
theorem dihedral_series_bot
    (n : ℕ) (hn : 2 ≤ n) :
    Subgroup.lowerCentralSeries (DihedralGroup (2 ^ (n - 1))) (n - 1) = ⊥ := by
  letI : NeZero (2 ^ (n - 1)) :=
    ⟨pow_ne_zero _ (by norm_num)⟩
  apply le_bot_iff.mp
  have hindex : n - 2 + 1 = n - 1 := by omega
  have hle :=
    dihedral_rotation_powers
      (2 ^ (n - 1)) (n - 2)
  rw [hindex] at hle
  simpa using hle

/-- The two standard reflections used to realize `C₂ * C₂` in a dihedral
group. -/
def orderDihedralReflection (m : ℕ) : Fin 2 → DihedralGroup m :=
  fun i =>
    if i = 0 then DihedralGroup.sr 0 else DihedralGroup.sr 1

/-- The canonical surjection from `C₂ * C₂` to a dihedral group. -/
noncomputable def orderPairDihedral (m : ℕ) :
    CyclicFreeProduct orderTwoPair →* DihedralGroup m := by
  refine PresentedGroup.toGroup
    (f := orderDihedralReflection m) ?_
  rintro _ ⟨i, rfl⟩
  simp only [map_pow, FreeGroup.lift_apply_of]
  fin_cases i <;>
    simp [orderDihedralReflection, orderTwoPair, pow_two]

@[simp] theorem order_dihedral_generator
    (m : ℕ) (i : Fin 2) :
    orderPairDihedral m (cyclicGenerator orderTwoPair i) =
      orderDihedralReflection m i := by
  simp [orderPairDihedral, cyclicGenerator]

theorem order_dihedral_surjective
    (m : ℕ) [NeZero m] :
    Function.Surjective (orderPairDihedral m) := by
  intro x
  let a := cyclicGenerator orderTwoPair (0 : Fin 2)
  let b := cyclicGenerator orderTwoPair (1 : Fin 2)
  cases x with
  | r i =>
      refine ⟨(a * b) ^ i.val, ?_⟩
      rw [map_pow, map_mul,
        order_dihedral_generator,
        order_dihedral_generator]
      change
        (DihedralGroup.sr 0 * DihedralGroup.sr 1) ^ i.val =
          DihedralGroup.r i
      rw [DihedralGroup.sr_mul_sr, sub_zero,
        DihedralGroup.r_one_pow]
      exact congrArg DihedralGroup.r
        (ZMod.natCast_zmod_val i)
  | sr i =>
      refine ⟨a * (a * b) ^ i.val, ?_⟩
      rw [map_mul, map_pow, map_mul,
        order_dihedral_generator,
        order_dihedral_generator]
      change
        DihedralGroup.sr 0 *
            (DihedralGroup.sr 0 * DihedralGroup.sr 1) ^ i.val =
          DihedralGroup.sr i
      rw [DihedralGroup.sr_mul_sr, sub_zero,
        DihedralGroup.r_one_pow, DihedralGroup.sr_mul_r, zero_add]
      exact congrArg DihedralGroup.sr
        (ZMod.natCast_zmod_val i)

/-- The dihedral realization factors through Struik's quotient `F/F_n`. -/
noncomputable def orderNilpotentDihedral
    (n : ℕ) (hn : 2 ≤ n) :
    NilpotentCyclicProduct orderTwoPair n →*
      DihedralGroup (2 ^ (n - 1)) := by
  letI : NeZero (2 ^ (n - 1)) :=
    ⟨pow_ne_zero _ (by norm_num)⟩
  let f :=
    orderPairDihedral (2 ^ (n - 1))
  apply QuotientGroup.lift
    (Subgroup.lowerCentralSeries (CyclicFreeProduct orderTwoPair) (n - 1)) f
  intro x hx
  have hfx :
      f x ∈
        Subgroup.lowerCentralSeries (DihedralGroup (2 ^ (n - 1))) (n - 1) :=
    Subgroup.lowerCentralSeries.map f (n - 1)
      (Subgroup.mem_map_of_mem f hx)
  rw [dihedral_series_bot n hn] at hfx
  exact Subgroup.mem_bot.mp hfx

@[simp] theorem nilpotent_dihedral_generator
    (n : ℕ) (hn : 2 ≤ n) (i : Fin 2) :
    orderNilpotentDihedral n hn
        (nilpotentCyclicGenerator orderTwoPair n i) =
      orderDihedralReflection (2 ^ (n - 1)) i := by
  simp [orderNilpotentDihedral,
    nilpotentCyclicGenerator]

theorem nilpotent_dihedral_surjective
    (n : ℕ) (hn : 2 ≤ n) :
    Function.Surjective
      (orderNilpotentDihedral n hn) := by
  letI : NeZero (2 ^ (n - 1)) :=
    ⟨pow_ne_zero _ (by norm_num)⟩
  intro y
  obtain ⟨x, rfl⟩ :=
    order_dihedral_surjective
      (2 ^ (n - 1)) y
  refine
    ⟨QuotientGroup.mk'
        (Subgroup.lowerCentralSeries
      (CyclicFreeProduct orderTwoPair) (n - 1)) x, ?_⟩
  rfl

@[simp] theorem nilpotent_dihedral_rotation
    (n : ℕ) (hn : 2 ≤ n) :
    orderNilpotentDihedral n hn
        (nilpotentCyclicGenerator orderTwoPair n 0 *
          nilpotentCyclicGenerator orderTwoPair n 1) =
      DihedralGroup.r (1 : ZMod (2 ^ (n - 1))) := by
  rw [map_mul,
    nilpotent_dihedral_generator,
    nilpotent_dihedral_generator]
  simp [orderDihedralReflection]

private theorem dihedral_r_modulus
    (L : ℕ) (hL : 0 < L) :
    orderOf
        (DihedralGroup.r (2 : ZMod (2 * L)) :
          DihedralGroup (2 * L)) =
      L := by
  rw [orderOf_eq_iff hL]
  constructor
  · rw [DihedralGroup.r_pow]
    rw [← DihedralGroup.r_zero]
    apply congrArg DihedralGroup.r
    have hcast : ((2 * L : ℕ) : ZMod (2 * L)) = 0 :=
      (ZMod.natCast_eq_zero_iff (2 * L) (2 * L)).mpr dvd_rfl
    simpa only [Nat.cast_mul, Nat.cast_ofNat] using hcast
  · intro k hk hkpos hpow
    have hzmod : ((2 * k : ℕ) : ZMod (2 * L)) = 0 := by
      rw [DihedralGroup.r_pow] at hpow
      rw [← DihedralGroup.r_zero] at hpow
      have hz : (2 : ZMod (2 * L)) * k = 0 :=
        DihedralGroup.r.inj hpow
      simpa only [Nat.cast_ofNat, Nat.cast_mul] using hz
    have hdvd : 2 * L ∣ 2 * k :=
      (ZMod.natCast_eq_zero_iff (2 * k) (2 * L)).mp hzmod
    have hLdvd : L ∣ k :=
      Nat.dvd_of_mul_dvd_mul_left (by omega) hdvd
    exact (Nat.not_le_of_lt hk) (Nat.le_of_dvd hkpos hLdvd)

@[simp] theorem nilpotent_dihedral_commutator
    (n : ℕ) (hn : 2 ≤ n) :
    orderNilpotentDihedral n hn
        (hallCommutator
          (nilpotentCyclicGenerator orderTwoPair n 0)
          (nilpotentCyclicGenerator orderTwoPair n 1)) =
      DihedralGroup.r (2 : ZMod (2 ^ (n - 1))) := by
  simp [hallCommutator, orderDihedralReflection]
  norm_num

/-- The source's corrected exact order: in `F/F_n`, the commutator subgroup
generator `(a,b)` has order `2^(n-2)`, not `2^(n-1)`. -/
theorem order_nilpotent_commutator
    (n : ℕ) (hn : 2 ≤ n) :
    orderOf
        (hallCommutator
          (nilpotentCyclicGenerator orderTwoPair n 0)
          (nilpotentCyclicGenerator orderTwoPair n 1)) =
      2 ^ (n - 2) := by
  let c :=
    hallCommutator
      (nilpotentCyclicGenerator orderTwoPair n 0)
      (nilpotentCyclicGenerator orderTwoPair n 1)
  have hupper : orderOf c ∣ 2 ^ (n - 2) :=
    orderOf_dvd_of_pow_eq_one
      (order_pair_nilpotent n hn)
  have hindex : n - 1 = (n - 2) + 1 := by omega
  have hmodulus :
      2 ^ (n - 1) = 2 * 2 ^ (n - 2) := by
    rw [hindex, pow_succ]
    ring
  have himage :
      orderOf
          (orderNilpotentDihedral n hn c) =
        2 ^ (n - 2) := by
    rw [nilpotent_dihedral_commutator]
    rw [hmodulus]
    exact
      dihedral_r_modulus
        (2 ^ (n - 2)) (pow_pos (by omega) _)
  have hlower : 2 ^ (n - 2) ∣ orderOf c := by
    rw [← himage]
    exact orderOf_map_dvd
      (orderNilpotentDihedral n hn) c
  exact Nat.dvd_antisymm hupper hlower

/-- The rotation `ab` in `F/F_n` has exact order `2^(n-1)`. -/
theorem pair_nilpotent_rotation
    (n : ℕ) (hn : 2 ≤ n) :
    orderOf
        (nilpotentCyclicGenerator orderTwoPair n 0 *
          nilpotentCyclicGenerator orderTwoPair n 1) =
      2 ^ (n - 1) := by
  let x :=
    nilpotentCyclicGenerator orderTwoPair n 0 *
      nilpotentCyclicGenerator orderTwoPair n 1
  have hupper : orderOf x ∣ 2 ^ (n - 1) :=
    orderOf_dvd_of_pow_eq_one
      (order_nilpotent_rotation n hn)
  have himage :
      orderOf (orderNilpotentDihedral n hn x) =
        2 ^ (n - 1) := by
    rw [nilpotent_dihedral_rotation,
      DihedralGroup.orderOf_r_one]
  have hlower : 2 ^ (n - 1) ∣ orderOf x := by
    rw [← himage]
    exact orderOf_map_dvd
      (orderNilpotentDihedral n hn) x
  exact Nat.dvd_antisymm hupper hlower

/-- Struik's total-order assertion for two involutions:
`|F/F_n| = 2^n`. -/
theorem pair_nilpotent_card
    (n : ℕ) (hn : 2 ≤ n) :
    Nat.card (NilpotentCyclicProduct orderTwoPair n) =
      2 ^ n := by
  letI : NeZero (2 ^ (n - 1)) :=
    ⟨pow_ne_zero _ (by norm_num)⟩
  have hnormal :=
    nilpotent_form_surjective n hn
  letI : Finite (NilpotentCyclicProduct orderTwoPair n) :=
    Finite.of_surjective
      (orderNilpotentForm n) hnormal
  have hpow :
      2 * 2 ^ (n - 1) = 2 ^ n := by
    calc
      2 * 2 ^ (n - 1) =
          2 ^ (n - 1) * 2 := by ring
      _ = 2 ^ ((n - 1) + 1) := by
        rw [pow_succ]
      _ = 2 ^ n := by
        congr 1
        omega
  have hupper :
      Nat.card (NilpotentCyclicProduct orderTwoPair n) ≤
        2 ^ n := by
    calc
      Nat.card (NilpotentCyclicProduct orderTwoPair n) ≤
          Nat.card (Fin 2 × ZMod (2 ^ (n - 1))) :=
        Nat.card_le_card_of_surjective
          (orderNilpotentForm n) hnormal
      _ = 2 * 2 ^ (n - 1) := by
        rw [Nat.card_prod, Nat.card_fin, Nat.card_zmod]
      _ = 2 ^ n := hpow
  have hlower :
      2 ^ n ≤
        Nat.card (NilpotentCyclicProduct orderTwoPair n) := by
    calc
      2 ^ n =
          Nat.card (DihedralGroup (2 ^ (n - 1))) := by
        rw [DihedralGroup.nat_card, hpow]
      _ ≤ Nat.card (NilpotentCyclicProduct orderTwoPair n) :=
        Nat.card_le_card_of_surjective
          (orderNilpotentDihedral n hn)
          (nilpotent_dihedral_surjective n hn)
  exact Nat.le_antisymm hupper hlower

/-- Equation (23): the second nilpotent product of two cyclic groups of
order two has order eight. -/
theorem natCard :
    Nat.card (NilpotentCyclicProduct orderTwoPair 3) = 8 := by
  simpa using pair_nilpotent_card 3 (by omega)

end P1960
end Struik
