import Submission.NumberTheory.Discriminant.FiniteIndexDiscriminant
import Submission.NumberTheory.Discriminant.PolynomialExamples
import Submission.NumberTheory.Discriminant.PowerBasisDiscriminant

/-!
# The integral basis of a small quintic field

Milne's Example 2.39 considers a root `alpha` of `X^5 - X - 1`. The polynomial has
squarefree discriminant `2869 = 19 * 151`, so the powers of `alpha` form an integral basis
and the full ring of integers is `Z[alpha]`.
-/

namespace Submission.NumberTheory.Milne

open Module NumberField Polynomial
open scoped NumberField

noncomputable section

private theorem quintic_basispower_dim
    {K : Type*} [Field K] [NumberField K]
    (B : PowerBasis ℚ K)
    (hmin : minpoly ℚ B.gen = X ^ 5 - X - 1) :
    B.dim = 5 := by
  rw [← B.natDegree_minpoly, hmin]
  compute_degree
  norm_num

/-- The rational power basis attached to a root of `X^5 - X - 1` has discriminant
`2869 = 19 * 151`. -/
theorem quintic_basispower_discr
    {K : Type*} [Field K] [NumberField K]
    (B : PowerBasis ℚ K)
    (hmin : minpoly ℚ B.gen = X ^ 5 - X - 1) :
    Algebra.discr ℚ B.basis = 2869 := by
  rw [basis_discr_minpoly B, hmin]
  exact discr_x_five

private theorem thousand_hundred_sixty :
    Squarefree (2869 : ℤ) := by
  rw [show (2869 : ℤ) = 19 * 151 by norm_num, squarefree_mul_iff]
  have h19 : Prime (19 : ℤ) := by norm_num
  have h151 : Prime (151 : ℤ) := by norm_num
  exact ⟨h19.irreducible.isRelPrime_iff_not_dvd.mpr (by norm_num),
    h19.squarefree, h151.squarefree⟩

/-- Example 2.39: `1, alpha, ..., alpha^4` form an integral basis. -/
theorem quintic_basisexists_basis
    {K : Type*} [Field K] [NumberField K]
    (alpha : RingOfIntegers K)
    (B : PowerBasis ℚ K)
    (hgen : B.gen = (alpha : K))
    (hmin : minpoly ℚ B.gen = X ^ 5 - X - 1) :
    ∃ PB : PowerBasis ℤ (RingOfIntegers K),
      PB.gen = alpha ∧ PB.dim = 5 := by
  obtain ⟨PB, hPBgen, hPBdim⟩ :=
    integers_discr_squarefree
      alpha B hgen 2869 (quintic_basispower_discr B hmin)
        thousand_hundred_sixty
  exact ⟨PB, hPBgen, hPBdim.trans (quintic_basispower_dim B hmin)⟩

/-- Example 2.39: the full ring of integers is generated by `alpha` over `Z`. -/
theorem quintic_basisring_adjoin
    {K : Type*} [Field K] [NumberField K]
    (alpha : RingOfIntegers K)
    (B : PowerBasis ℚ K)
    (hgen : B.gen = (alpha : K))
    (hmin : minpoly ℚ B.gen = X ^ 5 - X - 1) :
    Algebra.adjoin ℤ ({alpha} : Set (RingOfIntegers K)) = ⊤ := by
  exact adjoin_discr_squarefree
    alpha B hgen 2869 (quintic_basispower_discr B hmin)
      thousand_hundred_sixty

private theorem quintic_basispolynomial_monic :
    (X ^ 5 - X - 1 : ℚ[X]).Monic := by
  rw [show (X ^ 5 - X - 1 : ℚ[X]) = X ^ 5 + (-X - 1) by ring]
  apply monic_X_pow_add
  compute_degree
  norm_num

/-- Example 2.39 in the source's literal presentation. A root of `X^5 - X - 1`
which generates the number field lifts to an algebraic integer whose first five powers are
an integral basis and which generates the full ring of integers. -/
theorem quintic_basisof_top
    {K : Type*} [Field K] [NumberField K]
    (alpha : K)
    (hroot : Polynomial.aeval alpha (X ^ 5 - X - 1 : ℚ[X]) = 0)
    (hadjoin : Algebra.adjoin ℚ ({alpha} : Set K) = ⊤) :
    ∃ alphaInt : RingOfIntegers K,
      (alphaInt : K) = alpha ∧
      (∃ PB : PowerBasis ℤ (RingOfIntegers K),
        PB.gen = alphaInt ∧ PB.dim = 5) ∧
      Algebra.adjoin ℤ ({alphaInt} : Set (RingOfIntegers K)) = ⊤ := by
  have halphaIntegral : IsIntegral ℤ alpha := by
    refine ⟨X ^ 5 - X - 1, ?_, ?_⟩
    · rw [show (X ^ 5 - X - 1 : ℤ[X]) = X ^ 5 + (-X - 1) by ring]
      apply monic_X_pow_add
      compute_degree
      norm_num
    · change Polynomial.aeval alpha (X ^ 5 - X - 1 : ℤ[X]) = 0
      rw [← Polynomial.aeval_map_algebraMap ℚ]
      simpa using hroot
  let alphaInt : RingOfIntegers K := ⟨alpha, halphaIntegral⟩
  let B : PowerBasis ℚ K :=
    PowerBasis.ofAdjoinEqTop (Algebra.IsIntegral.isIntegral alpha) hadjoin
  have hBgen : B.gen = alpha := by
    exact PowerBasis.ofAdjoinEqTop_gen
      (Algebra.IsIntegral.isIntegral alpha) hadjoin
  have hmin : minpoly ℚ B.gen = X ^ 5 - X - 1 := by
    exact (minpoly.eq_of_irreducible_of_monic
      irreducible_x_five (by simpa [hBgen] using hroot)
        quintic_basispolynomial_monic).symm
  have hgenInt : B.gen = (alphaInt : K) := hBgen
  refine ⟨alphaInt, rfl, ?_, ?_⟩
  · exact quintic_basisexists_basis alphaInt B hgenInt hmin
  · exact quintic_basisring_adjoin alphaInt B hgenInt hmin

end

end Submission.NumberTheory.Milne
