import Towers.ClassField.NormCorrespondence.LocalStatement

/-!
# Chapter I, Corollary 1.2: the local norm correspondence

This file states all five parts of Milne's Corollary 1.2 using finite abelian
intermediate fields of the fixed separable closure.  In particular,
composita and intersections are genuine joins and meets of intermediate
fields, not operations on arbitrary representatives of extension types.
-/

namespace Towers.CField.LFTheory

noncomputable section

universe u

variable (K : Type u) [NontriviallyNormedField K]
  [IsUltrametricDist K] [ValuativeRel K] [IsNonarchimedeanLocalField K]

namespace FASubext

/-- The underlying intermediate field in the fixed separable closure. -/
abbrev intermediateField (L : FASubext K) :
    IntermediateField K (SeparableClosure K) :=
  L.finiteIntermediateField.toIntermediateField

/-- `M` is the compositum of `L` and `L'` inside the fixed separable
closure. -/
def IsCompositum (M L L' : FASubext K) : Prop :=
  M.intermediateField = L.intermediateField ⊔ L'.intermediateField

/-- `M` is the intersection of `L` and `L'` inside the fixed separable
closure. -/
def IsIntersection (M L L' : FASubext K) : Prop :=
  M.intermediateField = L.intermediateField ⊓ L'.intermediateField

end FASubext

/-- A norm group represented by a finite abelian subextension of the fixed
separable closure. -/
def SubextensionNormGroup (H : Subgroup Kˣ) : Prop :=
  ∃ L : FASubext K, L.normGroup = H

omit [IsUltrametricDist K] [ValuativeRel K] [IsNonarchimedeanLocalField K] in
/-- The two names for a local norm group agree. -/
theorem subextension_norm_local
    (H : Subgroup Kˣ) :
    SubextensionNormGroup K H ↔ LGroup K H :=
  Iff.rfl

/-- The type of norm groups in `Kˣ`, bundled with the fact that they arise
from a finite abelian subextension. -/
abbrev LocalNormGroup :=
  {H : Subgroup Kˣ // SubextensionNormGroup K H}

/-- The norm-group map on finite abelian subextensions. -/
def abelianNormGroup :
    FASubext K → LocalNormGroup K :=
  fun L ↦ ⟨L.normGroup, L, rfl⟩

/-- The five conclusions of Corollary I.1.2. -/
structure LocalNormCorrespondence : Prop where
  /-- (a) Finite abelian subextensions correspond bijectively to norm
  groups. -/
  normGroup_bijective : Function.Bijective (abelianNormGroup K)
  /-- (b) The correspondence reverses inclusions. -/
  inclusion_iff (L L' : FASubext K) :
    L.intermediateField ≤ L'.intermediateField ↔
      L'.normGroup ≤ L.normGroup
  /-- (c) The norm group of a compositum is the intersection of the norm
  groups. -/
  norm_compositum (L L' : FASubext K) :
    ∃ M : FASubext K,
      FASubext.IsCompositum K M L L' ∧
        M.normGroup = L.normGroup ⊓ L'.normGroup
  /-- (d) The norm group of an intersection is the subgroup generated by
  the two norm groups.  For subgroups of the abelian group `Kˣ`, this is
  their lattice supremum. -/
  norm_intersection (L L' : FASubext K) :
    ∃ M : FASubext K,
      FASubext.IsIntersection K M L L' ∧
        M.normGroup = L.normGroup ⊔ L'.normGroup
  /-- (e) Every subgroup containing a norm group is a norm group. -/
  supergroup_norm_group (L : FASubext K)
      (I : Subgroup Kˣ) :
    L.normGroup ≤ I → SubextensionNormGroup K I

end

end Towers.CField.LFTheory
