import Mathlib.NumberTheory.NumberField.InfinitePlace.Ramification
import Mathlib.NumberTheory.NumberField.Norm
import Mathlib.RingTheory.Ideal.Norm.RelNorm


/-!
# Extension of places in a number-field extension

This file records the extension and relative-norm infrastructure underlying
Milne's Lemma 7.16.  Mathlib packages finite places as prime ideals and infinite
places as conjugacy classes of complex embeddings.
-/

namespace Submission.NumberTheory.Milne

open NumberField

noncomputable section

variable {K L : Type*} [Field K] [Field L] [NumberField K] [NumberField L]
  [Algebra K L]

omit [NumberField K] in
/-- Milne, Lemma 7.16(a), finite-place part: only finitely many primes of
`L` lie over a fixed prime of `K`. -/
theorem finite_places (p : Ideal (RingOfIntegers K)) [p.IsMaximal] :
    (p.primesOver (RingOfIntegers L)).Finite :=
  IsDedekindDomain.primesOver_finite p (RingOfIntegers L)

omit [NumberField K] [NumberField L] in
/-- Every finite prime of `K` has at least one prime of `L` above it. -/
theorem finite_places_nonempty (p : Ideal (RingOfIntegers K)) [p.IsMaximal] :
    (p.primesOver (RingOfIntegers L)).Nonempty := by
  obtain ⟨P, hP, hPp⟩ :=
    Ideal.exists_maximal_ideal_liesOver_of_isIntegral
      (S := RingOfIntegers L) p
  exact ⟨P, hP.isPrime, hPp⟩

/-- Milne, Lemma 7.16(a), infinite-place existence: every infinite place of
`K` is the restriction of an infinite place of `L`. -/
theorem infinite_place (v : InfinitePlace K) :
    ∃ w : InfinitePlace L, w.comap (algebraMap K L) = v :=
  InfinitePlace.comap_surjective v

omit [NumberField K] in
/-- There are only finitely many infinite places of `L` above a fixed infinite
place of `K`. -/
theorem infinite_places_finite (v : InfinitePlace K) :
    Set.Finite {w : InfinitePlace L | w.comap (algebraMap K L) = v} :=
  Set.toFinite _

omit [NumberField K] in
/-- The factorization of a lifted finite prime into the finite primes above it,
with their ramification indices.  This is the ideal-theoretic form of the
finite-place part of Milne's Lemma 7.16. -/
theorem prime_product
    (p : Ideal (RingOfIntegers K)) [p.IsMaximal] (hp : p ≠ ⊥) :
    p.map (algebraMap (RingOfIntegers K) (RingOfIntegers L)) =
      ∏ P ∈ p.primesOver (RingOfIntegers L), P ^ p.ramificationIdx P :=
  Ideal.map_algebraMap_eq_finsetProd_pow hp

/-- The relative norm of a prime above `p` is `p` to its residue degree. -/
theorem relativeNorm_prime
    (p : Ideal (RingOfIntegers K)) (P : Ideal (RingOfIntegers L))
    [p.IsMaximal] [P.IsMaximal] [P.LiesOver p] :
    Ideal.relNorm (RingOfIntegers K) P = p ^ p.inertiaDeg P :=
  Ideal.relNorm_eq_pow_of_isMaximal P p

/-- The absolute norm of a prime above `p` is the absolute norm of `p`
raised to its residue degree.  This is the normalization relation between
the finite-place absolute values in `K` and `L`. -/
theorem abs_norm_prime
    (p : Ideal (RingOfIntegers K)) (P : Ideal (RingOfIntegers L))
    [P.LiesOver p] (hp : p.IsPrime) (hp0 : p ≠ ⊥) :
    Ideal.absNorm P = Ideal.absNorm p ^ p.inertiaDeg P :=
  Ideal.absNorm_eq_pow_inertiaDeg_of_liesOver P p hp hp0

/-- Relative ideal norm sends a principal integral ideal to the principal ideal
generated by the integral norm. -/
theorem relative_span_singleton (x : RingOfIntegers L) :
    Ideal.relNorm (RingOfIntegers K) (Ideal.span {x}) =
      Ideal.span {Algebra.intNorm (RingOfIntegers K) (RingOfIntegers L) x} :=
  Ideal.relNorm_singleton (RingOfIntegers K) x

/-- Field norms are transitive in a tower.  This is the algebraic norm identity
on the right-hand side of Milne's Lemma 7.16(b). -/
theorem relativeNorm_transitive {F : Type*} [Field F] [NumberField F]
    [Algebra K F] [Algebra F L] [IsScalarTower K F L] (x : L) :
    Algebra.norm K (Algebra.norm F x) = Algebra.norm K x :=
  Algebra.norm_norm

end

end Submission.NumberTheory.Milne
