import Submission.NumberTheory.Valuations.DiscreteValuationRings

/-!
# Milne, Algebraic Number Theory, the calculation preceding Proposition 3.2

For a prime element `π` in a discrete valuation ring and `n < m`, Milne computes the
annihilator of `π ^ n` modulo `π ^ m`.  The ideal-colon calculation used here only needs an
integral domain and `π ≠ 0`.
-/

namespace Submission.NumberTheory.Milne

/-- The ideal quotient `( π ^ m : π ^ n )` is generated by `π ^ (m - n)` when `n ≤ m`.
This is the ideal-theoretic form of the annihilator calculation before Proposition 3.2. -/
theorem span_pow_colon
    {A : Type*} [CommRing A] [IsDomain A]
    {π : A} (hπ : π ≠ 0) {m n : ℕ} (hnm : n ≤ m) :
    (Ideal.span {π ^ m}).colon (Ideal.span {π ^ n}) =
      Ideal.span {π ^ (m - n)} := by
  ext x
  rw [Ideal.mem_colon_span_singleton, Ideal.mem_span_singleton,
    Ideal.mem_span_singleton]
  constructor
  · rintro ⟨c, hc⟩
    refine ⟨c, ?_⟩
    apply mul_right_cancel₀ (pow_ne_zero n hπ)
    calc
      x * π ^ n = π ^ m * c := hc
      _ = (π ^ (m - n) * π ^ n) * c := by
        rw [← pow_add, Nat.sub_add_cancel hnm]
      _ = (π ^ (m - n) * c) * π ^ n := by
        ac_rfl
  · rintro ⟨c, rfl⟩
    refine ⟨c, ?_⟩
    calc
      (π ^ (m - n) * c) * π ^ n = (π ^ (m - n) * π ^ n) * c := by
        ac_rfl
      _ = π ^ m * c := by rw [← pow_add, Nat.sub_add_cancel hnm]

/-- The annihilator of the class of `π ^ n` modulo `π ^ m` is generated by
`π ^ (m - n)`. -/
theorem annihilator_mod_span
    {A : Type*} [CommRing A] [IsDomain A]
    {π : A} (hπ : π ≠ 0) {m n : ℕ} (hnm : n ≤ m) :
    (⊥ : Submodule A (A ⧸ Ideal.span {π ^ m})).colon
        {Ideal.Quotient.mk (Ideal.span {π ^ m}) (π ^ n)} =
      Ideal.span {π ^ (m - n)} := by
  ext x
  rw [Submodule.mem_colon_singleton, Submodule.mem_bot]
  change Ideal.Quotient.mk (Ideal.span {π ^ m}) (x * π ^ n) = 0 ↔ _
  rw [Ideal.Quotient.eq_zero_iff_mem]
  simpa only [Ideal.mem_colon_span_singleton] using
    SetLike.ext_iff.mp (span_pow_colon hπ hnm) x

/-- Multiplying the chosen quotient representative by a unit does not change its
annihilator.  This is Milne's form `b = v * π ^ n` with `v` a unit. -/
theorem annihilator_mk_span
    {A : Type*} [CommRing A] [IsDomain A]
    {π v : A} (hπ : π ≠ 0) (hv : IsUnit v) {m n : ℕ} (hnm : n ≤ m) :
    (⊥ : Submodule A (A ⧸ Ideal.span {π ^ m})).colon
        {Ideal.Quotient.mk (Ideal.span {π ^ m}) (v * π ^ n)} =
      Ideal.span {π ^ (m - n)} := by
  ext x
  rw [Submodule.mem_colon_singleton, Submodule.mem_bot]
  change Ideal.Quotient.mk (Ideal.span {π ^ m}) (x * (v * π ^ n)) = 0 ↔ _
  rw [Ideal.Quotient.eq_zero_iff_mem]
  rw [show x * (v * π ^ n) = v * (x * π ^ n) by ring]
  calc
    v * (x * π ^ n) ∈ Ideal.span {π ^ m} ↔
        x * π ^ n ∈ Ideal.span {π ^ m} :=
      (Ideal.span {π ^ m}).unit_mul_mem_iff_mem hv
    _ ↔ x ∈ Ideal.span {π ^ (m - n)} := by
      simpa only [Ideal.mem_colon_span_singleton] using
        SetLike.ext_iff.mp (span_pow_colon hπ hnm) x

/-- Milne's calculation with both unit factors present: if `c = u * π ^ m` and
`b = v * π ^ n`, then the annihilator of `b + (c)` is generated by `π ^ (m - n)`. -/
theorem annihilator_mk_mod
    {A : Type*} [CommRing A] [IsDomain A]
    {π u v : A} (hπ : π ≠ 0) (hu : IsUnit u) (hv : IsUnit v)
    {m n : ℕ} (hnm : n ≤ m) :
    (⊥ : Submodule A (A ⧸ Ideal.span {u * π ^ m})).colon
        {Ideal.Quotient.mk (Ideal.span {u * π ^ m}) (v * π ^ n)} =
      Ideal.span {π ^ (m - n)} := by
  rw [Ideal.span_singleton_mul_left_unit hu]
  exact annihilator_mk_span hπ hv hnm

/-- In a DVR, the quotient class in Milne's calculation is nonzero when `n < m`. -/
theorem mk_span_ne
    {A : Type*} [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    {π : A} (hπ : Irreducible π) {m n : ℕ} (hnm : n < m) :
    Ideal.Quotient.mk (Ideal.span {π ^ m}) (π ^ n) ≠ 0 := by
  rw [ne_eq, Ideal.Quotient.eq_zero_iff_mem, Ideal.mem_span_singleton]
  exact fun hdiv ↦
    (Nat.not_le_of_gt hnm) ((pow_dvd_pow_iff hπ.ne_zero hπ.not_isUnit).mp hdiv)

/-- Among Milne's nonzero classes `v * π ^ n` modulo `u * π ^ m`, the annihilator is
maximal exactly when `n = m - 1`. -/
theorem annihilator_mk_maximal
    {A : Type*} [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    {π : A} (hπ : Irreducible π) (u v : Aˣ)
    {m n : ℕ} (hnm : n < m) :
    (⊥ : Submodule A (A ⧸ Ideal.span {(u : A) * π ^ m})).colon
        {Ideal.Quotient.mk (Ideal.span {(u : A) * π ^ m}) ((v : A) * π ^ n)} =
      IsLocalRing.maximalIdeal A ↔
        n + 1 = m := by
  rw [annihilator_mk_mod hπ.ne_zero u.isUnit v.isUnit hnm.le,
    hπ.maximalIdeal_eq]
  constructor
  · intro hspan
    have hassociated : Associated (π ^ (m - n)) (π ^ 1) :=
      Ideal.span_singleton_eq_span_singleton.mp (by simpa using hspan)
    obtain ⟨w, hw⟩ := hassociated
    have hexponent : m - n = 1 := by
      apply IsDiscreteValuationRing.unit_mul_pow_congr_pow hπ hπ w 1 (m - n) 1
      simpa [mul_comm] using hw
    omega
  · intro hmn
    simp [show m - n = 1 by omega]

/-- In the maximal-annihilator case, a representative of `c / b` in the DVR is the
unit quotient `(u / v) * π`; it generates the annihilator and multiplying it by `b`
recovers `c`. -/
theorem maximal_annihilator_prime
    {A : Type*} [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    {π : A} (hπ : Irreducible π) (u v : Aˣ)
    {m n : ℕ} (hmn : n + 1 = m) :
    (⊥ : Submodule A (A ⧸ Ideal.span {(u : A) * π ^ m})).colon
        {Ideal.Quotient.mk (Ideal.span {(u : A) * π ^ m}) ((v : A) * π ^ n)} =
        Ideal.span {((u * v⁻¹ : Aˣ) : A) * π} ∧
      ((v : A) * π ^ n) * (((u * v⁻¹ : Aˣ) : A) * π) =
        (u : A) * π ^ m := by
  have hnm : n ≤ m := by omega
  constructor
  · rw [annihilator_mk_mod
      hπ.ne_zero u.isUnit v.isUnit hnm]
    rw [show m - n = 1 by omega, pow_one]
    apply Ideal.span_singleton_eq_span_singleton.mpr
    exact ⟨u * v⁻¹, by simp [mul_comm]⟩
  · rw [← hmn, pow_succ]
    simp only [Units.val_mul]
    calc
      ((v : A) * π ^ n) * ((u : A) * ↑v⁻¹ * π) =
          ((v : A) * ↑v⁻¹) * (u : A) * (π ^ n * π) := by ring
      _ = (u : A) * (π ^ n * π) := by simp

end Submission.NumberTheory.Milne
