import Mathlib.Algebra.Ring.GeomSum
import Towers.ClassField.LocalBrauer.InvariantTorsionLimit
import Towers.ClassField.LocalBrauer.UnramifiedIntermediateField


/-!
# Chapter IV, Section 4: the canonical unramified tower

For a local field with residue cardinality `q`, the roots of
`X ^ (q ^ n) - X` are the Teichmuller representatives at level `n`.  Taking
the finite Galois subfield of a fixed separable closure generated by these
roots makes the unramified levels canonical.  The elementary divisibility
`X ^ (q ^ n) - X ∣ X ^ (q ^ m) - X` for `n ∣ m` gives their nesting.
-/

namespace Towers.CField.LBrauer

noncomputable section

universe u v

-- Canonical finite Galois levels unfold deeply during field-instance synthesis.

open Polynomial
open scoped NormedField
open scoped Valued

variable (K : Type u) [NontriviallyNormedField K] [IsUltrametricDist K]
  [ValuativeRel K] [IsNonarchimedeanLocalField K]
  [Valuation.Compatible (NormedField.valuation (K := K))]

private abbrev normInteger :=
  Valuation.integer (NormedField.valuation (K := K))

omit [IsNonarchimedeanLocalField K] in
private theorem canonical_integer_norm :
    Valuation.integer (ValuativeRel.valuation K) = normInteger K := by
  ext x
  simp only [Valuation.mem_integer_iff]
  rw [← (ValuativeRel.valuation K).vle_one_iff,
    ← (NormedField.valuation (K := K)).vle_one_iff]

private noncomputable def canonicalIntegerNorm :
    Valuation.integer (ValuativeRel.valuation K) ≃+* normInteger K :=
  RingEquiv.subringCongr (canonical_integer_norm K)

/-- The cardinality of the residue field of a nonarchimedean local field. -/
def localResidueCard : ℕ := Nat.card 𝓀[K]

theorem one_local_card : 1 < localResidueCard K := by
  letI : Finite (IsLocalRing.ResidueField
      (Valuation.integer (ValuativeRel.valuation K))) :=
    local_field_residue K
  letI : Finite 𝓀[K] := Finite.of_equiv
    (IsLocalRing.ResidueField
      (Valuation.integer (ValuativeRel.valuation K)))
    (IsLocalRing.ResidueField.mapEquiv
      (canonicalIntegerNorm K)).toEquiv
  letI : Fintype 𝓀[K] := Fintype.ofFinite 𝓀[K]
  simpa [localResidueCard, Nat.card_eq_fintype_card] using
    Fintype.one_lt_card (α := 𝓀[K])

/-- The Frobenius polynomial whose roots generate the degree-`n`
unramified level. -/
def localFrobeniusPolynomial (n : ℕ) : K[X] :=
  X ^ (localResidueCard K) ^ n - X

theorem local_frobenius_monic {n : ℕ} (hn : 0 < n) :
    (localFrobeniusPolynomial K n).Monic := by
  apply monic_X_pow_sub
  rw [degree_X]
  exact_mod_cast Nat.one_lt_pow hn.ne' (one_local_card K)

theorem local_frobenius_x {n : ℕ} :
    localFrobeniusPolynomial K n =
      (X : K[X]) *
        ((X : K[X]) ^ ((localResidueCard K) ^ n - 1) - (1 : K[X])) := by
  have hpow : 0 < (localResidueCard K) ^ n :=
    pow_pos (Nat.zero_lt_one.trans (one_local_card K)) n
  rw [localFrobeniusPolynomial]
  calc
    (X : K[X]) ^ (localResidueCard K) ^ n - (X : K[X]) =
        (X : K[X]) ^ (((localResidueCard K) ^ n - 1) + 1) - (X : K[X]) := by
      rw [Nat.sub_add_cancel hpow]
    _ = (X : K[X]) ^ ((localResidueCard K) ^ n - 1) * X - X := by
      rw [pow_succ]
    _ = (X : K[X]) * X ^ ((localResidueCard K) ^ n - 1) - X := by
      rw [mul_comm]
    _ = (X : K[X]) *
        (X ^ ((localResidueCard K) ^ n - 1) - (1 : K[X])) := by
      simpa using
        (mul_sub (X : K[X])
          (X ^ ((localResidueCard K) ^ n - 1)) (1 : K[X])).symm

/-- Frobenius polynomials form a divisibility system under divisibility of
their level indices. -/
theorem local_frobenius_dvd {n m : ℕ}
    (hnm : n ∣ m) :
    localFrobeniusPolynomial K n ∣ localFrobeniusPolynomial K m := by
  rw [local_frobenius_x K,
    local_frobenius_x K]
  have hexponents :
      (localResidueCard K) ^ n - 1 ∣
        (localResidueCard K) ^ m - 1 :=
    Nat.pow_sub_one_dvd_pow_sub_one (localResidueCard K) hnm
  obtain ⟨c, hc⟩ := hexponents
  apply mul_dvd_mul_left (X : K[X])
  rw [hc, pow_mul]
  simpa using sub_dvd_pow_sub_pow
    (X ^ ((localResidueCard K) ^ n - 1) : K[X]) (1 : K[X]) c

/-- The finite Galois subextension generated by all roots of the degree-`n`
Frobenius polynomial. -/
def canonicalUnramifiedLevel (n : ℕ) :
    FiniteGaloisIntermediateField K (SeparableClosure K) :=
  FiniteGaloisIntermediateField.adjoin K
    ((localFrobeniusPolynomial K n).rootSet (SeparableClosure K) :
      Set (SeparableClosure K))

/-- The defining Frobenius polynomial splits in its canonical unramified level. -/
theorem unramified_level_splits (n : ℕ) [NeZero n] :
    ((localFrobeniusPolynomial K n).map
      (algebraMap K (canonicalUnramifiedLevel K n))).Splits := by
  obtain ⟨L, hField, hAlgebra, hFinite, hGalois,
      _hdegree, _hcyclic, hsplit, _, _alpha, _halpha, _halphaDegree⟩ :=
    cyclic_galois_extension K n
  letI : Field L := hField
  letI : Algebra K L := hAlgebra
  letI : Module.Finite K L := hFinite
  letI : IsGalois K L := hGalois
  let i : L →ₐ[K] SeparableClosure K := IsSepClosed.lift
  have hsplitClosure :
      ((localFrobeniusPolynomial K n).map
        (algebraMap K (SeparableClosure K))).Splits := by
    have := hsplit.map i.toRingHom
    simpa [localFrobeniusPolynomial, localResidueCard, map_map] using this
  apply (IntermediateField.splits_iff_mem hsplitClosure).2
  intro x hx
  change x ∈ (canonicalUnramifiedLevel K n :
    IntermediateField K (SeparableClosure K))
  change x ∈ IntermediateField.normalClosure K
      (IntermediateField.adjoin K
        ((localFrobeniusPolynomial K n).rootSet (SeparableClosure K) :
          Set (SeparableClosure K))) (SeparableClosure K)
  exact IntermediateField.le_normalClosure _
    (IntermediateField.subset_adjoin K _ hx)

/-- Canonical unramified levels are nested when their indices divide. -/
theorem unramified_level {n m : ℕ}
    (hn : 0 < n) (hm : 0 < m) (hnm : n ∣ m) :
    canonicalUnramifiedLevel K n ≤ canonicalUnramifiedLevel K m := by
  change IntermediateField.normalClosure K
      (IntermediateField.adjoin K
        ((localFrobeniusPolynomial K n).rootSet (SeparableClosure K) :
          Set (SeparableClosure K))) (SeparableClosure K) ≤
    IntermediateField.normalClosure K
      (IntermediateField.adjoin K
        ((localFrobeniusPolynomial K m).rootSet (SeparableClosure K) :
          Set (SeparableClosure K))) (SeparableClosure K)
  apply IntermediateField.normalClosure_mono
  rw [IntermediateField.adjoin_le_iff]
  intro x hx
  apply IntermediateField.subset_adjoin K
  rw [(local_frobenius_monic K hm).mem_rootSet]
  rw [(local_frobenius_monic K hn).mem_rootSet] at hx
  obtain ⟨g, hg⟩ := local_frobenius_dvd K hnm
  rw [hg, map_mul, hx, zero_mul]

set_option synthInstance.maxHeartbeats 100000 in
-- Extra heartbeats are needed for the typeclass search in this proof.
set_option maxHeartbeats 1000000 in
-- The proof unfolds several finite intermediate-field structures.
private theorem unramified_level_structure (n : ℕ) [NeZero n] :
    Module.finrank K (canonicalUnramifiedLevel K n) = n ∧
      IsCyclic Gal(canonicalUnramifiedLevel K n / K) := by
  obtain ⟨L, hField, hAlgebra, hFinite, hGalois,
      hdegree, hcyclic, hsplit, _, alpha, halpha, halphaDegree⟩ :=
    cyclic_galois_extension K n
  letI : Field L := hField
  letI : Algebra K L := hAlgebra
  letI : Module.Finite K L := hFinite
  letI : IsGalois K L := hGalois
  let i : L →ₐ[K] SeparableClosure K := IsSepClosed.lift
  let E : IntermediateField K (SeparableClosure K) := i.fieldRange
  let e : L ≃ₐ[K] E := AlgEquiv.ofInjectiveField i
  letI : Module.Finite K E := Module.Finite.equiv e.toLinearEquiv
  letI : IsGalois K E := IsGalois.of_algEquiv e
  have hdegreeE : Module.finrank K E = n := by
    rw [← e.toLinearEquiv.finrank_eq, hdegree]
  have hsplitE :
      ((localFrobeniusPolynomial K n).map (algebraMap K E)).Splits := by
    have := hsplit.map e.toAlgHom.toRingHom
    simpa [localFrobeniusPolynomial, localResidueCard, map_map] using this
  have hsplitClosure :
      ((localFrobeniusPolynomial K n).map
        (algebraMap K (SeparableClosure K))).Splits := by
    have := hsplitE.map E.val.toRingHom
    simpa [map_map] using this
  have hcanonical_le :
      (canonicalUnramifiedLevel K n :
        IntermediateField K (SeparableClosure K)) ≤ E := by
    change IntermediateField.normalClosure K
        (IntermediateField.adjoin K
          ((localFrobeniusPolynomial K n).rootSet (SeparableClosure K) :
            Set (SeparableClosure K))) (SeparableClosure K) ≤ E
    rw [IntermediateField.normalClosure_le_iff_of_normal,
      IntermediateField.adjoin_le_iff]
    exact (IntermediateField.splits_iff_mem hsplitClosure).mp hsplitE
  have hupper : Module.finrank K (canonicalUnramifiedLevel K n) ≤ n := by
    calc
      Module.finrank K (canonicalUnramifiedLevel K n) ≤
          Module.finrank K E :=
        IntermediateField.finrank_le_of_le_right hcanonical_le
      _ = n := hdegreeE
  let alphaClosure : SeparableClosure K := i alpha
  have halphaClosure :
      ((localFrobeniusPolynomial K n).map
        (algebraMap K (SeparableClosure K))).IsRoot alphaClosure := by
    have := Polynomial.IsRoot.map (f := i.toRingHom) halpha
    simpa [alphaClosure, localFrobeniusPolynomial, localResidueCard, map_map] using this
  have halpha_mem :
      alphaClosure ∈ (canonicalUnramifiedLevel K n :
        IntermediateField K (SeparableClosure K)) := by
    apply FiniteGaloisIntermediateField.subset_adjoin K
    rw [(local_frobenius_monic K (NeZero.pos n)).mem_rootSet]
    simpa [IsRoot, aeval_def] using halphaClosure
  have hadjoin_le :
      IntermediateField.adjoin K {alphaClosure} ≤
        (canonicalUnramifiedLevel K n :
          IntermediateField K (SeparableClosure K)) := by
    rw [IntermediateField.adjoin_le_iff, Set.singleton_subset_iff]
    exact halpha_mem
  have halphaClosureDegree :
      (minpoly K alphaClosure).natDegree = n := by
    rw [minpoly.algHom_eq i i.injective]
    exact halphaDegree
  have hlower : n ≤ Module.finrank K (canonicalUnramifiedLevel K n) := by
    have hadjoinDegree :
        Module.finrank K (IntermediateField.adjoin K {alphaClosure}) = n :=
      (IntermediateField.adjoin.finrank
        (Algebra.IsIntegral.isIntegral alphaClosure)).trans halphaClosureDegree
    calc
      n = Module.finrank K (IntermediateField.adjoin K {alphaClosure}) :=
        hadjoinDegree.symm
      _ ≤ Module.finrank K (canonicalUnramifiedLevel K n) :=
        IntermediateField.finrank_le_of_le_right hadjoin_le
  have hcanonicalDegree :
      Module.finrank K (canonicalUnramifiedLevel K n) = n :=
    le_antisymm hupper hlower
  have hcanonical_eq :
      (canonicalUnramifiedLevel K n :
        IntermediateField K (SeparableClosure K)) = E :=
    IntermediateField.eq_of_le_of_finrank_eq hcanonical_le
      (hcanonicalDegree.trans hdegreeE.symm)
  let eAut : Gal(L / K) ≃* Gal(E / K) := e.autCongr
  have hcyclicE : IsCyclic Gal(E / K) := eAut.isCyclic.mp hcyclic
  have hcyclicCanonical :
      IsCyclic Gal(canonicalUnramifiedLevel K n / K) := by
    change IsCyclic
      ((canonicalUnramifiedLevel K n :
        IntermediateField K (SeparableClosure K)) ≃ₐ[K]
          (canonicalUnramifiedLevel K n :
            IntermediateField K (SeparableClosure K)))
    rw [hcanonical_eq]
    exact hcyclicE
  exact ⟨hcanonicalDegree, hcyclicCanonical⟩

set_option synthInstance.maxHeartbeats 100000 in
-- Canonical intermediate-field structures unfold during typeclass search.
/-- The canonical level generated by the roots of the `n`-th Frobenius
polynomial has degree exactly `n`. -/
theorem unramified_level_finrank (n : ℕ) [NeZero n] :
    Module.finrank K (canonicalUnramifiedLevel K n) = n :=
  (unramified_level_structure K n).1

/-- The Galois group of the degree-`n` canonical unramified level is cyclic. -/
theorem unramified_level_cyclic (n : ℕ) [NeZero n] :
    IsCyclic Gal(canonicalUnramifiedLevel K n / K) :=
  (unramified_level_structure K n).2

set_option synthInstance.maxHeartbeats 100000 in
-- Extra heartbeats are needed for the typeclass search in this proof.
set_option maxHeartbeats 1000000 in
-- Comparing field ranges unfolds the canonical finite Galois level.
/-- A degree-`n` finite Galois extension in which the canonical Frobenius
polynomial splits is isomorphic to the canonical unramified level. -/
theorem alg_level_splits
    (L : Type v) [Field L] [Algebra K L] [Module.Finite K L]
    [IsGalois K L] (n : ℕ) [NeZero n]
    (hdegree : Module.finrank K L = n)
    (hsplit : ((localFrobeniusPolynomial K n).map
      (algebraMap K L)).Splits) :
    Nonempty (L ≃ₐ[K] canonicalUnramifiedLevel K n) := by
  let i : L →ₐ[K] SeparableClosure K := IsSepClosed.lift
  let E : IntermediateField K (SeparableClosure K) := i.fieldRange
  let e : L ≃ₐ[K] E := AlgEquiv.ofInjectiveField i
  letI : Module.Finite K E := Module.Finite.equiv e.toLinearEquiv
  letI : IsGalois K E := IsGalois.of_algEquiv e
  have hdegreeE : Module.finrank K E = n := by
    rw [← e.toLinearEquiv.finrank_eq, hdegree]
  have hsplitE :
      ((localFrobeniusPolynomial K n).map (algebraMap K E)).Splits := by
    have hs := hsplit.map e.toAlgHom.toRingHom
    simpa [localFrobeniusPolynomial, localResidueCard, map_map] using hs
  have hsplitClosure :
      ((localFrobeniusPolynomial K n).map
        (algebraMap K (SeparableClosure K))).Splits := by
    have hs := hsplitE.map E.val.toRingHom
    simpa [map_map] using hs
  have hcanonical_le :
      (canonicalUnramifiedLevel K n :
        IntermediateField K (SeparableClosure K)) ≤ E := by
    change IntermediateField.normalClosure K
        (IntermediateField.adjoin K
          ((localFrobeniusPolynomial K n).rootSet (SeparableClosure K) :
            Set (SeparableClosure K))) (SeparableClosure K) ≤ E
    rw [IntermediateField.normalClosure_le_iff_of_normal,
      IntermediateField.adjoin_le_iff]
    exact (IntermediateField.splits_iff_mem hsplitClosure).mp hsplitE
  have hcanonical_eq :
      (canonicalUnramifiedLevel K n :
        IntermediateField K (SeparableClosure K)) = E :=
    IntermediateField.eq_of_le_of_finrank_eq hcanonical_le (by
      rw [unramified_level_finrank K n, hdegreeE])
  exact ⟨e.trans (IntermediateField.equivOfEq hcanonical_eq.symm)⟩

/-- The Galois group of the degree-`n` canonical unramified level is the
cyclic group of order `n`. -/
noncomputable def galZMod
    (n : ℕ) [NeZero n] :
    Multiplicative (ZMod n) ≃* Gal(canonicalUnramifiedLevel K n / K) := by
  have hcard : Nat.card Gal(canonicalUnramifiedLevel K n / K) = n := by
    rw [IsGalois.card_aut_eq_finrank,
      unramified_level_finrank K n]
  exact (AddEquiv.toMultiplicative
      (ZMod.ringEquivCongr hcard.symm).toAddEquiv).trans
    (zmodCyclicMulEquiv (unramified_level_cyclic K n))

/-- The factorial canonical levels used for the local-invariant direct
limit. -/
def unramifiedFactorialLevel (r : ℕ) :
    FiniteGaloisIntermediateField K (SeparableClosure K) :=
  canonicalUnramifiedLevel K (invariantLevelDegree r)

theorem factorial_level_monotone :
    Monotone (unramifiedFactorialLevel K) := by
  intro r s hrs
  exact unramified_level K
    (invariant_level_pos r)
    (invariant_level_pos s)
    (invariant_level_dvd hrs)

set_option synthInstance.maxHeartbeats 100000 in
-- The factorial level unfolds to a canonical intermediate field.
theorem factorial_level_finrank (r : ℕ) :
    Module.finrank K (unramifiedFactorialLevel K r) =
      invariantLevelDegree r := by
  letI : NeZero (invariantLevelDegree r) :=
    ⟨(invariant_level_pos r).ne'⟩
  exact unramified_level_finrank K (invariantLevelDegree r)

end

end Towers.CField.LBrauer
