import Mathlib.FieldTheory.Minpoly.IsIntegrallyClosed
import Mathlib.RingTheory.Polynomial.Subring
import Mathlib.RingTheory.Valuation.Integral
import Towers.ClassField.LocalBrauer.DivisionAlgebraIntegers

/-!
# Chapter IV, Section 4: integral elements of a division algebra

For a finite central division algebra over a local field, the canonical
integer ring is precisely the set of elements integral over the integer ring
of the centre.  The proof takes place in the commutative subfield generated by
one element and uses the coefficient description of the spectral unit ball.
-/

namespace Towers.CField.LBrauer

noncomputable section

open Polynomial
open scoped Valued

universe u

variable (K D : Type u) [NontriviallyNormedField K] [IsUltrametricDist K]
  [ValuativeRel K] [IsNonarchimedeanLocalField K] [DivisionRing D]
  [Algebra K D] [Module.Finite K D]

/-- The valuation ring attached to the norm of the local field. -/
abbrev baseIntegerRing : Subring K :=
  (NormedField.valuation (K := K)).integer

/-- The canonical map from the valuation ring of the centre into the
division algebra. -/
def integerDivision : baseIntegerRing K →+* D :=
  (algebraMap K D).comp (baseIntegerRing K).subtype

omit [ValuativeRel K] [IsNonarchimedeanLocalField K] [Module.Finite K D] in
@[simp]
theorem base_division (x : baseIntegerRing K) :
    integerDivision K D x = algebraMap K D (x : K) :=
  rfl

set_option synthInstance.maxHeartbeats 100000 in
-- The generated subfield carries the scalar tower from the valuation ring.
set_option maxHeartbeats 1000000 in
-- Minimal-polynomial transport through that tower is elaboration-intensive.
/-- **Milne IV.4.** The integer ring of a finite central division algebra
over a local field consists exactly of the elements integral over the
integer ring of the centre. -/
theorem division_subring_elem (x : D) :
    x ∈ divisionIntegerSubring K D ↔
      (integerDivision K D).IsIntegralElem x := by
  let E : Subalgebra K D := Algebra.adjoin K ({x} : Set D)
  have hset : ∀ a ∈ ({x} : Set D), ∀ b ∈ ({x} : Set D), a * b = b * a := by
    intro a ha b hb
    simp only [Set.mem_singleton_iff] at ha hb
    subst a
    subst b
    rfl
  have hcomm : ∀ a b : E, a * b = b * a :=
    by
      letI : IsMulCommutative E := Algebra.isMulCommutative_adjoin K hset
      exact mul_comm'
  letI : CommRing E := { (inferInstance : Ring E) with mul_comm := hcomm }
  letI : Module.Finite K E :=
    Module.Finite.of_injective E.val.toLinearMap Subtype.val_injective
  letI : IsDomain E :=
    Function.Injective.isDomain E.val.toRingHom Subtype.val_injective
  letI : Field E := fieldOfFiniteDimensional K E
  let e : E := ⟨x, Algebra.subset_adjoin (Set.mem_singleton x)⟩
  let f : baseIntegerRing K →+* E :=
    (algebraMap K E).comp (baseIntegerRing K).subtype
  rw [coe_subring_spectral K D E hcomm e]
  constructor
  · intro he
    let p : K[X] := minpoly K e
    have hpmonic : p.Monic := minpoly.monic (Algebra.IsIntegral.isIntegral e)
    have hspectral : spectralValue p ≤ 1 := by
      exact he
    have hcoeff : ∀ n : ℕ, ‖p.coeff n‖ ≤ 1 :=
      (spectralValue_le_one_iff hpmonic).mp hspectral
    have hpcoeffs :
        (↑p.coeffs : Set K) ⊆
          (baseIntegerRing K : Set K) := by
      intro c hc
      obtain ⟨n, _hn, rfl⟩ := Polynomial.mem_coeffs_iff.mp hc
      change NormedField.valuation (p.coeff n) ≤ 1
      change ‖p.coeff n‖₊ ≤ 1
      exact_mod_cast hcoeff n
    let q : (baseIntegerRing K)[X] :=
      p.toSubring (baseIntegerRing K) hpcoeffs
    have hqmonic : q.Monic :=
      (Polynomial.monic_toSubring p (baseIntegerRing K) hpcoeffs).mpr hpmonic
    have hqmap : q.map (baseIntegerRing K).subtype = p := by
      exact Polynomial.map_toSubring p (baseIntegerRing K) hpcoeffs
    have hqroot : eval₂ f e q = 0 := by
      change
        eval₂ ((algebraMap K E).comp (baseIntegerRing K).subtype) e q = 0
      rw [← eval₂_map]
      rw [hqmap]
      exact minpoly.aeval K e
    have heint : f.IsIntegralElem e := ⟨q, hqmonic, hqroot⟩
    have hmap := heint.map E.val.toRingHom
    simpa [f, integerDivision, e] using hmap
  · intro hx
    have hxE : f.IsIntegralElem e := by
      apply RingHom.IsIntegralElem.of_map
        (f := f) (g := E.val.toRingHom) Subtype.val_injective
      simpa [f, integerDivision, e] using hx
    letI : Algebra (baseIntegerRing K) E := f.toAlgebra
    letI : IsScalarTower (baseIntegerRing K) K E :=
      IsScalarTower.of_algebraMap_eq' (by rfl)
    have heint : IsIntegral (baseIntegerRing K) e := hxE
    have hmin :
        minpoly K e =
          (minpoly (baseIntegerRing K) e).map
            (algebraMap (baseIntegerRing K) K) :=
      minpoly.isIntegrallyClosed_eq_field_fractions' K heint
    have hpmonic : (minpoly K e).Monic :=
      minpoly.monic (Algebra.IsIntegral.isIntegral e)
    have hcoeff : ∀ n : ℕ, ‖(minpoly K e).coeff n‖ ≤ 1 := by
      intro n
      rw [hmin, coeff_map]
      change
        ‖(((minpoly (baseIntegerRing K) e).coeff n :
          baseIntegerRing K) : K)‖ ≤ 1
      have hmem := ((minpoly (baseIntegerRing K) e).coeff n).property
      change
        NormedField.valuation
          (((minpoly (baseIntegerRing K) e).coeff n :
            baseIntegerRing K) : K) ≤ 1 at hmem
      change
        ‖(((minpoly (baseIntegerRing K) e).coeff n :
          baseIntegerRing K) : K)‖₊ ≤ 1 at hmem
      exact_mod_cast hmem
    change spectralValue (minpoly K e) ≤ 1
    exact (spectralValue_le_one_iff hpmonic).mpr hcoeff

end

end Towers.CField.LBrauer
