import Towers.ClassField.CrossedProducts.SubalgebraField
import Towers.ClassField.CrossedProducts.EndRestrictScalars
import Towers.ClassField.LocalBrauer.LocalField

/-!
# Chapter IV, Section 4: degree bounds inside a local division algebra

The first algebraic estimate in Milne's local-field calculation does not
depend on the valuation: a commutative subfield of a central division algebra
of dimension `n²` has degree at most `n`.  We prove the slightly more general
square-root bound for every commutative subalgebra, and then apply it to the
subalgebra generated by one element.
-/

namespace Towers.CField.LBrauer

noncomputable section

universe u

open CProduca

variable (K D : Type u) [Field K] [DivisionRing D] [Algebra K D]
  [Algebra.IsCentral K D] [Module.Finite K D]

/-- A commutative subalgebra of a finite-dimensional central division algebra
has degree at most the square root of the dimension of the ambient algebra. -/
theorem commutative_subalgebra_finrank
    (L : Subalgebra K D) (hcomm : ∀ x y : L, x * y = y * x) :
    Module.finrank K L ≤ Nat.sqrt (Module.finrank K D) := by
  let C := Subalgebra.centralizer K (L : Set D)
  letI : Module.Finite K L :=
    Module.Finite.of_injective L.val.toLinearMap Subtype.val_injective
  letI : IsSimpleRing L :=
    commutative_subalgebra_simple K D L hcomm
  letI : Module.Finite K C :=
    Module.Finite.of_injective C.val.toLinearMap Subtype.val_injective
  have hle : L ≤ C := by
    intro x hx
    rw [Subalgebra.mem_centralizer_iff]
    intro y hy
    exact congrArg Subtype.val (hcomm ⟨y, hy⟩ ⟨x, hx⟩)
  have hLC : Module.finrank K L ≤ Module.finrank K C :=
    (Subalgebra.inclusion hle).toLinearMap.finrank_le_finrank_of_injective
      (Subalgebra.inclusion_injective hle)
  have hdim :
      Module.finrank K L * Module.finrank K C = Module.finrank K D :=
    finrank_mul_centralizer K D L
  rw [Nat.le_sqrt']
  rw [pow_two, ← hdim]
  exact Nat.mul_le_mul_left _ hLC

/-- If a central division algebra has dimension `n²`, every commutative
subalgebra has degree at most `n`. -/
theorem commutative_subalgebra_sq
    (n : ℕ) (hD : Module.finrank K D = n ^ 2)
    (L : Subalgebra K D) (hcomm : ∀ x y : L, x * y = y * x) :
    Module.finrank K L ≤ n := by
  have h := commutative_subalgebra_finrank K D L hcomm
  rw [hD, Nat.sqrt_eq'] at h
  exact h

/-- The subalgebra `K[alpha]` generated by one element is commutative and has
degree at most the degree of the ambient central division algebra. -/
theorem adjoin_singleton_sq
    (n : ℕ) (hD : Module.finrank K D = n ^ 2) (alpha : D) :
    Module.finrank K (Algebra.adjoin K ({alpha} : Set D)) ≤ n := by
  let L := Algebra.adjoin K ({alpha} : Set D)
  have hset : ∀ x ∈ ({alpha} : Set D), ∀ y ∈ ({alpha} : Set D),
      x * y = y * x := by
    intro x hx y hy
    simp only [Set.mem_singleton_iff] at hx hy
    subst x
    subst y
    rfl
  have hcomm : ∀ x y : L, x * y = y * x :=
    by
      letI : IsMulCommutative L := Algebra.isMulCommutative_adjoin K hset
      exact mul_comm'
  exact commutative_subalgebra_sq K D n hD L hcomm

end

end Towers.CField.LBrauer
