import Submission.NumberTheory.ClassGroup.NarrowClassGroup
import Submission.NumberTheory.Quadratic.OrientedIdealBases

/-!
# Milne, Algebraic Number Theory, Theorem 4.29: principal scaling

This file proves the key compatibility needed to descend ideal norm forms to narrow ideal
classes.  Multiplying a nonzero integral ideal and its ordered basis by an algebraic integer of
positive norm leaves the normalized binary norm form unchanged.  In a quadratic field, total
positivity implies precisely this norm-sign condition; positive rational integers, and hence the
squares used to clear denominators of fractional ideals, satisfy it directly.
-/

namespace Submission.NumberTheory.Milne

open scoped NumberField nonZeroDivisors
open Module

noncomputable section

namespace INForm

variable {K : Type*} [Field K] [NumberField K]

/-- Multiplication of an integral ideal by the principal ideal generated by `alpha`. -/
def principalScaleIdeal (alpha : 𝓞 K) (I : Ideal (𝓞 K)) : Ideal (𝓞 K) :=
  Ideal.span {alpha} * I

/-- Multiplication by `alpha`, regarded as a map from `I` to `(alpha) I`. -/
def principalScale (alpha : 𝓞 K) (I : Ideal (𝓞 K)) :
    I →ₗ[ℤ] principalScaleIdeal alpha I where
  toFun x := ⟨alpha * x.1, Ideal.mem_span_singleton_mul.mpr ⟨x.1, x.2, rfl⟩⟩
  map_add' x y := by
    apply Subtype.ext
    simp only [Submodule.coe_add]
    ring
  map_smul' n x := by
    apply Subtype.ext
    simp only [RingHom.id_apply, Submodule.coe_smul_of_tower]
    rw [Algebra.smul_def, Algebra.smul_def]
    ring

omit [NumberField K] in
@[simp]
theorem principal_scale (alpha : 𝓞 K) (I : Ideal (𝓞 K)) (x : I) :
    (principalScale alpha I x : 𝓞 K) = alpha * (x : 𝓞 K) :=
  rfl

/-- For nonzero `alpha`, multiplication identifies `I` linearly with `(alpha) I`. -/
def principalScaleLinear (alpha : 𝓞 K) (halpha : alpha ≠ 0)
    (I : Ideal (𝓞 K)) : I ≃ₗ[ℤ] principalScaleIdeal alpha I :=
  LinearEquiv.ofBijective (principalScale alpha I) ⟨by
    intro x y hxy
    apply Subtype.ext
    apply mul_left_cancel₀ halpha
    exact congrArg Subtype.val hxy, by
    intro y
    obtain ⟨z, hzI, hz⟩ := Ideal.mem_span_singleton_mul.mp y.2
    refine ⟨⟨z, hzI⟩, ?_⟩
    apply Subtype.ext
    exact hz⟩

omit [NumberField K] in
@[simp]
theorem principal_scale_linear (alpha : 𝓞 K) (halpha : alpha ≠ 0)
    (I : Ideal (𝓞 K)) (x : I) :
    (principalScaleLinear alpha halpha I x : 𝓞 K) = alpha * (x : 𝓞 K) :=
  rfl

/-- Transport an ordered basis of `I` to the basis obtained by multiplying every vector by
`alpha`. -/
def principalScaleBasis (alpha : 𝓞 K) (halpha : alpha ≠ 0) (I : Ideal (𝓞 K))
    (b : Basis (Fin 2) ℤ I) : Basis (Fin 2) ℤ (principalScaleIdeal alpha I) :=
  b.map (principalScaleLinear alpha halpha I)

omit [NumberField K] in
@[simp]
theorem principal_scale_basis (alpha : 𝓞 K) (halpha : alpha ≠ 0)
    (I : Ideal (𝓞 K)) (b : Basis (Fin 2) ℤ I) (i : Fin 2) :
    (principalScaleBasis alpha halpha I b i : 𝓞 K) = alpha * (b i : 𝓞 K) := by
  simp [principalScaleBasis]

omit [NumberField K] in
/-- Scaling a basis multiplies its coordinate matrix on the left by the multiplication matrix of
the scaling element. -/
theorem basis_matrix_scale
    (B : Basis (Fin 2) ℤ (𝓞 K)) (alpha : 𝓞 K) (halpha : alpha ≠ 0)
    (I : Ideal (𝓞 K)) (b : Basis (Fin 2) ℤ I) :
    basisCoordinateMatrix B (principalScaleBasis alpha halpha I b) =
      Algebra.leftMulMatrix B alpha * basisCoordinateMatrix B b := by
  change B.toMatrix (fun i ↦ (principalScaleBasis alpha halpha I b i : 𝓞 K)) =
    Algebra.leftMulMatrix B alpha * B.toMatrix (fun i ↦ (b i : 𝓞 K))
  convert Basis.toMatrix_smul alpha B (fun i ↦ (b i : 𝓞 K)) using 1

/-- Multiplication by an element of positive norm preserves the positive orientation of an
ordered ideal basis. -/
theorem scale_positively_oriented
    (B : Basis (Fin 2) ℤ (𝓞 K)) (alpha : 𝓞 K)
    (halphaNorm : 0 < Algebra.norm ℤ alpha) (I : Ideal (𝓞 K))
    (b : Basis (Fin 2) ℤ I) (hb : IsPositivelyOriented B b) :
    IsPositivelyOriented B
      (principalScaleBasis alpha (Algebra.norm_ne_zero_iff.mp halphaNorm.ne') I b) := by
  rw [IsPositivelyOriented, basis_matrix_scale, Matrix.det_mul,
    ← Algebra.norm_eq_matrix_det B]
  exact mul_pos halphaNorm hb

/-- The absolute norm of `(alpha) I` is the absolute value of the element norm times the norm
of `I`. -/
theorem abs_principal_scale (alpha : 𝓞 K) (I : Ideal (𝓞 K)) :
    Ideal.absNorm (principalScaleIdeal alpha I) =
      (Algebra.norm ℤ alpha).natAbs * Ideal.absNorm I := by
  rw [principalScaleIdeal, map_mul, Ideal.absNorm_span_singleton]

/-- With positive element norm, the ideal-norm scaling identity has no absolute-value sign. -/
theorem abs_scale_pos (alpha : 𝓞 K)
    (halphaNorm : 0 < Algebra.norm ℤ alpha) (I : Ideal (𝓞 K)) :
    (Ideal.absNorm (principalScaleIdeal alpha I) : ℤ) =
      Algebra.norm ℤ alpha * (Ideal.absNorm I : ℤ) := by
  rw [abs_principal_scale, Nat.cast_mul, Int.natCast_natAbs,
    abs_of_pos halphaNorm]

/-- Evaluation of the transported basis is multiplication by `alpha` before taking the norm. -/
theorem abs_scale_basis
    (B : Basis (Fin 2) ℤ (𝓞 K)) (alpha : 𝓞 K) (halpha : alpha ≠ 0)
    (I : Ideal (𝓞 K)) (b : Basis (Fin 2) ℤ I) (x y : ℤ) :
    (Ideal.absNorm (principalScaleIdeal alpha I) : ℤ) *
        (formOfBasis (principalScaleIdeal alpha I)
          (principalScaleBasis alpha halpha I b)).eval x y =
      Algebra.norm ℤ alpha *
        Algebra.norm ℤ (x • (b 0 : 𝓞 K) + y • (b 1 : 𝓞 K)) := by
  have h := abs_norm_form B (principalScaleIdeal alpha I)
    (principalScaleBasis alpha halpha I b 0) (principalScaleBasis alpha halpha I b 1) x y
  rw [principal_scale_basis, principal_scale_basis] at h
  rw [← mul_smul_comm, ← mul_smul_comm, ← mul_add] at h
  change _ = Algebra.norm ℤ (alpha *
    (x • (b 0 : 𝓞 K) + y • (b 1 : 𝓞 K))) at h
  rw [map_mul] at h
  simpa only [formOfBasis] using h

/-- **Theorem 4.29 (positive principal-scaling compatibility).**  Scaling an integral ideal and
its ordered basis by a nonzero algebraic integer of positive norm does not change its normalized
binary norm form. -/
theorem form_scale_pos
    (B : Basis (Fin 2) ℤ (𝓞 K)) (alpha : 𝓞 K)
    (halphaNorm : 0 < Algebra.norm ℤ alpha) (I : Ideal (𝓞 K))
    (b : Basis (Fin 2) ℤ I) :
    formOfBasis (principalScaleIdeal alpha I)
        (principalScaleBasis alpha (Algebra.norm_ne_zero_iff.mp halphaNorm.ne') I b) =
      formOfBasis I b := by
  have halpha : alpha ≠ 0 := Algebra.norm_ne_zero_iff.mp halphaNorm.ne'
  let J := principalScaleIdeal alpha I
  let bJ := principalScaleBasis alpha halpha I b
  have hnalpha : Algebra.norm ℤ alpha ≠ 0 := halphaNorm.ne'
  have hscale (x y : ℤ) :
      (Ideal.absNorm J : ℤ) * (formOfBasis J bJ).eval x y =
        Algebra.norm ℤ alpha * (Ideal.absNorm I : ℤ) *
          (formOfBasis I b).eval x y := by
    calc
      (Ideal.absNorm J : ℤ) * (formOfBasis J bJ).eval x y =
          Algebra.norm ℤ alpha *
            Algebra.norm ℤ (x • (b 0 : 𝓞 K) + y • (b 1 : 𝓞 K)) := by
        exact abs_scale_basis B alpha halpha I b x y
      _ = Algebra.norm ℤ alpha * (Ideal.absNorm I : ℤ) *
            (formOfBasis I b).eval x y := by
        have h := abs_norm_form B I (b 0) (b 1) x y
        change (Ideal.absNorm I : ℤ) * (formOfBasis I b).eval x y =
          Algebra.norm ℤ (x • (b 0 : 𝓞 K) + y • (b 1 : 𝓞 K)) at h
        rw [← h]
        ring
  have hnormJ : (Ideal.absNorm J : ℤ) =
      Algebra.norm ℤ alpha * (Ideal.absNorm I : ℤ) :=
    abs_scale_pos alpha halphaNorm I
  have heval (x y : ℤ) : (formOfBasis J bJ).eval x y = (formOfBasis I b).eval x y := by
    have h := hscale x y
    rw [hnormJ] at h
    have hI : I ≠ ⊥ := by
      intro hI
      have hb0 := Basis.ne_zero b (0 : Fin 2)
      apply hb0
      have : Subsingleton I := by
        rw [hI]
        infer_instance
      exact Subsingleton.elim _ _
    have hnI : (Ideal.absNorm I : ℤ) ≠ 0 := by
      exact_mod_cast (absNorm_pos hI).ne'
    exact mul_left_cancel₀ (mul_ne_zero hnalpha hnI) h
  change formOfBasis J bJ = formOfBasis I b
  apply BQForm.ext
  · simpa [BQForm.eval] using heval 1 0
  · have h11 := heval 1 1
    have h10 := heval 1 0
    have h01 := heval 0 1
    simp only [BQForm.eval] at h11 h10 h01 ⊢
    linarith
  · simpa [BQForm.eval] using heval 0 1

end INForm

end

end Submission.NumberTheory.Milne
