import Mathlib.RingTheory.Ideal.Norm.AbsNorm
import Mathlib.NumberTheory.LegendreSymbol.ZModChar
import Submission.NumberTheory.Quadratic.BiquadraticIntegerRings
import Submission.NumberTheory.Quadratic.GaussianPrimeSplitting
import Submission.NumberTheory.Quadratic.PrimeFactorization
import Submission.NumberTheory.Quadratic.HeegnerNumberOne

/-!
# Milne, Chapter 3, Exercise 3

This file records Fermat's prime-representation criteria.  Part (a) is already the
two-squares theorem proved with Example 3.45.  For part (b), the sufficiency direction is
the ideal-theoretic argument suggested by Milne: a prime for which `-2` is a square splits
in `ℤ[√-2]`; this ring has class number one, so a prime above `p` is generated by an element
of norm `p`.
-/

namespace Submission.NumberTheory.Milne

open Ideal
open Submission.NumberTheory
open scoped NumberField QuadraticAlgebra

noncomputable section

attribute [-instance] DivisionRing.toRatAlgebra

/-- Exercise 3-3(a), already established in the development of Example 3.45. -/
theorem sum_two_squares
    (p : ℕ) [Fact p.Prime] (hp2 : p ≠ 2) :
    (∃ x y : ℤ, (p : ℤ) = x ^ 2 + y ^ 2) ↔ p % 4 = 1 :=
  int_sq_four p hp2

private abbrev NegTwoOrder := QOrd (-2) 0
private abbrev NegTwoField := QFModel (-2)

private local instance negTwoOrderAlgebra : Algebra NegTwoOrder NegTwoField :=
  (QuadraticOrderEmbedding (-2)).toAlgebra

private local instance negTwoOrderScalarTower :
    IsScalarTower ℤ NegTwoOrder NegTwoField :=
  IsScalarTower.of_algebraMap_eq' rfl

@[reducible] private def negIntegralClosure :
    IsIntegralClosure NegTwoOrder ℤ NegTwoField where
  algebraMap_injective := quadratic_order_injective (-2)
  isIntegral_iff {x} := by
    have hm : Squarefree (-2 : ℤ) := by
      rw [← Int.squarefree_natAbs]
      norm_num
      exact Nat.squarefree_two
    rw [quadratic_integer_coordinates (-2) hm (by norm_num)]
    constructor
    · rintro ⟨a, b, ha, hb⟩
      refine ⟨(⟨a, b⟩ : NegTwoOrder), ?_⟩
      apply QuadraticAlgebra.ext
      · exact ha.symm
      · exact hb.symm
    · rintro ⟨y, rfl⟩
      exact ⟨y.re, y.im, rfl, rfl⟩

private theorem neg_principal_ring :
    IsPrincipalIdealRing NegTwoOrder := by
  letI : Fact (∀ r : ℚ, r ^ 2 ≠ ((-2 : ℤ) : ℚ) + 0 * r) :=
    ⟨fun r hr => by norm_num at hr; nlinarith [sq_nonneg r]⟩
  letI : Module ℚ NegTwoField := (inferInstance : Algebra ℚ NegTwoField).toModule
  let coordinateEquiv : NegTwoField ≃ₗ[ℚ] (Fin 2 → ℚ) :=
    { toFun := fun x => ![x.re, x.im]
      invFun := fun x => ⟨x 0, x 1⟩
      left_inv := fun _ => rfl
      right_inv := by intro x; funext i; fin_cases i <;> rfl
      map_add' := by intro x y; ext i; fin_cases i <;> rfl
      map_smul' := by
        intro c x
        have hc_re : ((c : NegTwoField).re) = c := by
          rw [← algebraMap.coe_ratCast ℚ NegTwoField c]
          rfl
        have hc_im : ((c : NegTwoField).im) = 0 := by
          rw [← algebraMap.coe_ratCast ℚ NegTwoField c]
          rfl
        ext i
        fin_cases i <;>
          simp [Algebra.smul_def, QuadraticAlgebra.re_mul,
            QuadraticAlgebra.im_mul, hc_re, hc_im] }
  let coordinateBasis : Module.Basis (Fin 2) ℚ NegTwoField :=
    Module.Basis.ofEquivFun coordinateEquiv
  let hfinite : Module.Finite ℚ NegTwoField :=
    Module.Finite.of_basis coordinateBasis
  letI : Module.Finite ℚ NegTwoField := hfinite
  letI : NumberField NegTwoField :=
    @NumberField.of_module_finite ℚ NegTwoField inferInstance inferInstance
      inferInstance inferInstance hfinite
  let hclosure : IsIntegralClosure NegTwoOrder ℤ NegTwoField :=
    negIntegralClosure
  letI : IsIntegralClosure NegTwoOrder ℤ NegTwoField := hclosure
  have hclass : NumberField.classNumber NegTwoField = 1 := by
    simpa [CNOne.negativeQuadraticNumber] using
      CNOne.negative_number_neg
  letI : IsPrincipalIdealRing (𝓞 NegTwoField) :=
    NumberField.classNumber_eq_one_iff.mp hclass
  let e : 𝓞 NegTwoField ≃+* NegTwoOrder :=
    @NumberField.RingOfIntegers.equiv NegTwoField inferInstance NegTwoOrder inferInstance
      negTwoOrderAlgebra hclosure
  exact IsPrincipalIdealRing.of_surjective e.toRingHom e.surjective

private def negTwoMod (p : ℕ) (r : ℤ)
    (hr : (r : ZMod p) ^ 2 = (-2 : ZMod p)) :
    NegTwoOrder →+* ZMod p :=
  QOrd.evalMod (-2) 0 p r (by simpa using hr)

private theorem neg_root_ker (p : ℕ) (r : ℤ)
    (hr : (r : ZMod p) ^ 2 = (-2 : ZMod p)) :
    QOrd.rootIdeal (-2) 0 p r = RingHom.ker (negTwoMod p r hr) := by
  apply le_antisymm
  · rw [QOrd.rootIdeal, Ideal.span_le]
    intro z hz
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hz
    rcases hz with rfl | rfl
    · simp [negTwoMod, QOrd.evalMod]
    · simp [negTwoMod, QOrd.evalMod]
  · intro z hz
    rw [RingHom.mem_ker] at hz
    have hz' : (z.re : ZMod p) + (z.im : ZMod p) * (r : ZMod p) = 0 := by
      simpa [negTwoMod, QOrd.evalMod] using hz
    have hdiv : (p : ℤ) ∣ z.re + z.im * r := by
      rw [← ZMod.intCast_zmod_eq_zero_iff_dvd]
      simpa [Int.cast_add, Int.cast_mul] using hz'
    obtain ⟨q, hq⟩ := hdiv
    rw [QOrd.rootIdeal, Ideal.mem_span_pair]
    refine ⟨(⟨q, 0⟩ : NegTwoOrder), (⟨z.im, 0⟩ : NegTwoOrder), ?_⟩
    apply QuadraticAlgebra.ext
    · simp only [QuadraticAlgebra.re_add, QuadraticAlgebra.re_mul,
        QuadraticAlgebra.re_intCast, QuadraticAlgebra.re_sub,
        QuadraticAlgebra.omega_re]
      dsimp
      nlinarith [hq]
    · simp only [QuadraticAlgebra.im_add, QuadraticAlgebra.im_mul,
        QuadraticAlgebra.im_intCast, QuadraticAlgebra.im_sub,
        QuadraticAlgebra.omega_im]
      dsimp
      ring

private theorem neg_mod_surjective (p : ℕ) (r : ℤ)
    (hr : (r : ZMod p) ^ 2 = (-2 : ZMod p)) :
    Function.Surjective (negTwoMod p r hr) := by
  intro x
  obtain ⟨z, rfl⟩ := ZMod.ringHom_surjective (Int.castRingHom (ZMod p)) x
  refine ⟨(z : NegTwoOrder), ?_⟩
  simp [negTwoMod, QOrd.evalMod]

private theorem neg_card_quot (p : ℕ) (r : ℤ)
    (hr : (r : ZMod p) ^ 2 = (-2 : ZMod p)) :
    Submodule.cardQuot (QOrd.rootIdeal (-2) 0 p r) = p := by
  rw [Submodule.cardQuot_apply]
  let e₁ : NegTwoOrder ⧸ QOrd.rootIdeal (-2) 0 p r ≃+
      NegTwoOrder ⧸ RingHom.ker (negTwoMod p r hr) :=
    (Ideal.quotEquivOfEq (neg_root_ker p r hr)).toAddEquiv
  let e₂ : NegTwoOrder ⧸ RingHom.ker (negTwoMod p r hr) ≃+ ZMod p :=
    (RingHom.quotientKerEquivOfSurjective (neg_mod_surjective p r hr)).toAddEquiv
  calc
    Nat.card (NegTwoOrder ⧸ QOrd.rootIdeal (-2) 0 p r) =
        Nat.card (ZMod p) := Nat.card_congr (e₁.trans e₂).toEquiv
    _ = p := Nat.card_zmod p

private theorem neg_algebra_norm (z : NegTwoOrder) :
    Algebra.norm ℤ z = z.re ^ 2 + 2 * z.im ^ 2 := by
  have hmat : Algebra.leftMulMatrix (QuadraticAlgebra.basis (-2) 0) z =
      !![z.re, -2 * z.im; z.im, z.re] := by
    ext i j
    fin_cases i <;> fin_cases j <;>
      simp [Algebra.leftMulMatrix_eq_repr_mul, QuadraticAlgebra.basis,
        QuadraticAlgebra.linearEquivTuple, QuadraticAlgebra.equivProd,
        QuadraticAlgebra.re_mul, QuadraticAlgebra.im_mul]
  rw [Algebra.norm_eq_matrix_det (QuadraticAlgebra.basis (-2) 0)]
  rw [hmat, Matrix.det_fin_two_of]
  ring

private theorem sq_square_neg
    (p : ℕ) [Fact p.Prime]
    (hsquare : IsSquare (-2 : ZMod p)) :
    ∃ x y : ℤ, (p : ℤ) = x ^ 2 + 2 * y ^ 2 := by
  obtain ⟨r, hr⟩ := hsquare
  obtain ⟨a, rfl⟩ := ZMod.ringHom_surjective (Int.castRingHom (ZMod p)) r
  have hroot : ((a : ℤ) : ZMod p) ^ 2 = (-2 : ZMod p) := by
    simpa [pow_two] using hr.symm
  letI : Fact (∀ r : ℚ, r ^ 2 ≠ ((-2 : ℤ) : ℚ) + 0 * r) :=
    ⟨fun r hr => by norm_num at hr; nlinarith [sq_nonneg r]⟩
  letI : IsDomain NegTwoOrder :=
    (quadratic_order_injective (-2)).isDomain
      (QuadraticOrderEmbedding (-2))
  letI : IsPrincipalIdealRing NegTwoOrder := neg_principal_ring
  obtain ⟨g, hg⟩ := IsPrincipalIdealRing.principal
    (QOrd.rootIdeal (-2) 0 p a)
  have hcard : Submodule.cardQuot (Ideal.span ({g} : Set NegTwoOrder)) = p := by
    change Submodule.cardQuot (NegTwoOrder ∙ g) = p
    rw [← hg]
    exact neg_card_quot p a hroot
  have habs : (Algebra.norm ℤ g).natAbs = p := by
    calc
      (Algebra.norm ℤ g).natAbs = Ideal.absNorm (Ideal.span ({g} : Set NegTwoOrder)) :=
        (Ideal.absNorm_span_singleton g).symm
      _ = Submodule.cardQuot (Ideal.span ({g} : Set NegTwoOrder)) := rfl
      _ = p := hcard
  have hnorm : Algebra.norm ℤ g = (p : ℤ) := by
    have hnonneg : 0 ≤ Algebra.norm ℤ g := by
      rw [neg_algebra_norm]
      positivity
    exact Int.natAbs_of_nonneg hnonneg ▸ congrArg Int.ofNat habs
  refine ⟨g.re, g.im, ?_⟩
  rw [← hnorm, neg_algebra_norm]

/-- The easy congruence obstruction for Exercise 3-3(b). -/
private theorem mod_eight_sq
    {p : ℕ} (hpodd : p % 2 = 1)
    (hrep : ∃ x y : ℤ, (p : ℤ) = x ^ 2 + 2 * y ^ 2) :
    p % 8 = 1 ∨ p % 8 = 3 := by
  rcases hrep with ⟨x, y, hxy⟩
  have hcast := congrArg (fun z : ℤ ↦ (z : ZMod 8)) hxy
  have hcast' : (p : ZMod 8) = (x : ZMod 8) ^ 2 + 2 * (y : ZMod 8) ^ 2 := by
    simpa using hcast
  have hcases : ∀ x y : ZMod 8,
      x ^ 2 + 2 * y ^ 2 = 1 ∨ x ^ 2 + 2 * y ^ 2 = 3 ∨
      x ^ 2 + 2 * y ^ 2 = 0 ∨ x ^ 2 + 2 * y ^ 2 = 2 ∨
      x ^ 2 + 2 * y ^ 2 = 4 ∨ x ^ 2 + 2 * y ^ 2 = 6 := by decide
  have hpmododd : p % 8 % 2 = 1 := by omega
  have residue_of_eq (n : ℕ) (hn : n < 8)
      (h : (x : ZMod 8) ^ 2 + 2 * (y : ZMod 8) ^ 2 = (n : ZMod 8)) :
      p % 8 = n := by
    have heq : (p : ZMod 8) = (n : ZMod 8) := by
      exact hcast'.trans h
    rw [ZMod.natCast_eq_natCast_iff'] at heq
    simpa [Nat.mod_eq_of_lt hn] using heq
  rcases hcases (x : ZMod 8) (y : ZMod 8) with h | h | h | h | h | h
  · exact Or.inl (residue_of_eq 1 (by norm_num) h)
  · exact Or.inr (residue_of_eq 3 (by norm_num) h)
  · have hp0 := residue_of_eq 0 (by norm_num) h
    omega
  · have hp0 := residue_of_eq 2 (by norm_num) h
    omega
  · have hp0 := residue_of_eq 4 (by norm_num) h
    omega
  · have hp0 := residue_of_eq 6 (by norm_num) h
    omega

/-- Exercise 3-3(b): an odd prime is represented by `x² + 2y²` exactly in the
congruence classes `1` and `3` modulo `8`. -/
theorem sq_two_mul
    (p : ℕ) [Fact p.Prime] (hp2 : p ≠ 2) :
    (∃ x y : ℤ, (p : ℤ) = x ^ 2 + 2 * y ^ 2) ↔
      p % 8 = 1 ∨ p % 8 = 3 := by
  constructor
  · exact mod_eight_sq
      ((Nat.Prime.mod_two_eq_one_iff_ne_two (Fact.out : p.Prime)).2 hp2)
  · intro hp
    apply sq_square_neg p
    exact (ZMod.exists_sq_eq_neg_two_iff hp2).2 hp

private abbrev EisensteinOrder := QOrd (-1) 1
private abbrev EisensteinField := QFModel (-3)

private def eisensteinOrderEmbedding : EisensteinOrder →+* EisensteinField where
  toFun z := ⟨(z.re : ℚ) + (z.im : ℚ) / 2, (z.im : ℚ) / 2⟩
  map_zero' := by apply QuadraticAlgebra.ext <;> norm_num
  map_one' := by
    apply QuadraticAlgebra.ext <;>
      norm_num [QuadraticAlgebra.re_one, QuadraticAlgebra.im_one]
  map_add' x y := by
    apply QuadraticAlgebra.ext <;>
      simp only [QuadraticAlgebra.re_add, QuadraticAlgebra.im_add] <;>
      push_cast <;> ring
  map_mul' x y := by
    apply QuadraticAlgebra.ext
    · simp only [QuadraticAlgebra.re_mul, QuadraticAlgebra.im_mul]
      push_cast
      ring
    · simp only [QuadraticAlgebra.im_mul]
      push_cast
      ring

private theorem eisenstein_embedding_injective :
    Function.Injective eisensteinOrderEmbedding := by
  intro x y hxy
  have him := congrArg QuadraticAlgebra.im hxy
  change (x.im : ℚ) / 2 = (y.im : ℚ) / 2 at him
  have him' : (x.im : ℚ) = (y.im : ℚ) := by linarith
  have hre := congrArg QuadraticAlgebra.re hxy
  change (x.re : ℚ) + (x.im : ℚ) / 2 =
    (y.re : ℚ) + (y.im : ℚ) / 2 at hre
  have hre' : (x.re : ℚ) = (y.re : ℚ) := by linarith
  apply QuadraticAlgebra.ext
  · exact Rat.intCast_injective hre'
  · exact Rat.intCast_injective him'

private local instance eisensteinOrderAlgebra :
    Algebra EisensteinOrder EisensteinField :=
  eisensteinOrderEmbedding.toAlgebra

private local instance eisensteinOrderScalarTower :
    IsScalarTower ℤ EisensteinOrder EisensteinField :=
  IsScalarTower.of_algebraMap_eq' (by
    ext z <;> norm_num [eisensteinOrderEmbedding])

@[reducible] private def eisensteinIntegralClosure :
    IsIntegralClosure EisensteinOrder ℤ EisensteinField where
  algebraMap_injective := eisenstein_embedding_injective
  isIntegral_iff {x} := by
    have hm : Squarefree (-3 : ℤ) := by
      rw [← Int.squarefree_natAbs]
      norm_num
      exact Nat.prime_three.squarefree
    rw [quadratic_half_coordinates
      (-3) hm (by norm_num)]
    constructor
    · rintro ⟨a, b, ha, hb⟩
      refine ⟨(⟨a, b⟩ : EisensteinOrder), ?_⟩
      apply QuadraticAlgebra.ext
      · exact ha.symm
      · exact hb.symm
    · rintro ⟨y, rfl⟩
      exact ⟨y.re, y.im, rfl, rfl⟩

private theorem eisenstein_principal_ring :
    IsPrincipalIdealRing EisensteinOrder := by
  letI : Fact (∀ r : ℚ, r ^ 2 ≠ ((-3 : ℤ) : ℚ) + 0 * r) :=
    ⟨fun r hr => by norm_num at hr; nlinarith [sq_nonneg r]⟩
  letI : Module ℚ EisensteinField := (inferInstance : Algebra ℚ EisensteinField).toModule
  let coordinateEquiv : EisensteinField ≃ₗ[ℚ] (Fin 2 → ℚ) :=
    { toFun := fun x => ![x.re, x.im]
      invFun := fun x => ⟨x 0, x 1⟩
      left_inv := fun _ => rfl
      right_inv := by intro x; funext i; fin_cases i <;> rfl
      map_add' := by intro x y; ext i; fin_cases i <;> rfl
      map_smul' := by
        intro c x
        have hc_re : ((c : EisensteinField).re) = c := by
          rw [← algebraMap.coe_ratCast ℚ EisensteinField c]
          rfl
        have hc_im : ((c : EisensteinField).im) = 0 := by
          rw [← algebraMap.coe_ratCast ℚ EisensteinField c]
          rfl
        ext i
        fin_cases i <;>
          simp [Algebra.smul_def, QuadraticAlgebra.re_mul,
            QuadraticAlgebra.im_mul, hc_re, hc_im] }
  let coordinateBasis : Module.Basis (Fin 2) ℚ EisensteinField :=
    Module.Basis.ofEquivFun coordinateEquiv
  let hfinite : Module.Finite ℚ EisensteinField :=
    Module.Finite.of_basis coordinateBasis
  letI : Module.Finite ℚ EisensteinField := hfinite
  letI : NumberField EisensteinField :=
    @NumberField.of_module_finite ℚ EisensteinField inferInstance inferInstance
      inferInstance inferInstance hfinite
  let hclosure : IsIntegralClosure EisensteinOrder ℤ EisensteinField :=
    eisensteinIntegralClosure
  letI : IsIntegralClosure EisensteinOrder ℤ EisensteinField := hclosure
  have hclass : NumberField.classNumber EisensteinField = 1 := by
    simpa [CNOne.negativeQuadraticNumber] using
      CNOne.negative_quadratic_neg
  letI : IsPrincipalIdealRing (𝓞 EisensteinField) :=
    NumberField.classNumber_eq_one_iff.mp hclass
  let e : 𝓞 EisensteinField ≃+* EisensteinOrder :=
    @NumberField.RingOfIntegers.equiv EisensteinField inferInstance EisensteinOrder inferInstance
      eisensteinOrderAlgebra hclosure
  exact IsPrincipalIdealRing.of_surjective e.toRingHom e.surjective

private theorem square_neg_mod
    (p : ℕ) [Fact p.Prime] (hp2 : p ≠ 2) (hp3 : p ≠ 3) :
    IsSquare (-3 : ZMod p) ↔ p % 3 = 1 := by
  have hnegThree : (-3 : ZMod p) ≠ 0 := by
    intro h
    have h3 : (3 : ZMod p) = 0 := by
      have := congrArg Neg.neg h
      simpa using this
    have hdvd : p ∣ 3 := (ZMod.natCast_eq_zero_iff 3 p).mp h3
    exact hp3 ((Nat.prime_dvd_prime_iff_eq (Fact.out : p.Prime) Nat.prime_three).mp hdvd)
  rw [show (-3 : ZMod p) = (((-3 : ℤ) : ZMod p)) by norm_num]
  have hnegThree' : (((-3 : ℤ) : ZMod p)) ≠ 0 := by simpa using hnegThree
  rw [← legendreSym.eq_one_iff p hnegThree']
  have hodd : p % 2 = 1 :=
    (Nat.Prime.mod_two_eq_one_iff_ne_two (Fact.out : p.Prime)).2 hp2
  have hleg : legendreSym p (-3) = legendreSym 3 p := by
    rw [show (-3 : ℤ) = (-1) * 3 by norm_num, legendreSym.mul]
    rcases Nat.odd_mod_four_iff.mp hodd with hp1 | hp4
    · have hm1 : legendreSym p (-1) = 1 := by
        rw [legendreSym.at_neg_one hp2, ZMod.χ₄_nat_one_mod_four hp1]
      have hrec := legendreSym.quadratic_reciprocity_one_mod_four
        (p := p) (q := 3) hp1 (by norm_num)
      rw [hm1, one_mul]
      simpa using hrec.symm
    · have hm1 : legendreSym p (-1) = -1 := by
        rw [legendreSym.at_neg_one hp2, ZMod.χ₄_nat_three_mod_four hp4]
      have hrec := legendreSym.quadratic_reciprocity_three_mod_four
        (p := p) (q := 3) hp4 (by norm_num)
      rw [hm1]
      calc
        (-1 : ℤ) * legendreSym p 3 = -legendreSym p 3 := by ring
        _ = legendreSym 3 p := by simpa using hrec.symm
  rw [hleg]
  have hpmod3 : p % 3 = 1 ∨ p % 3 = 2 := by
    have hne0 : p % 3 ≠ 0 := by
      intro hzero
      have hdvd : 3 ∣ p := Nat.dvd_of_mod_eq_zero hzero
      exact hp3 ((Nat.prime_dvd_prime_iff_eq Nat.prime_three
        (Fact.out : p.Prime)).mp hdvd).symm
    omega
  have hpcast : ((p : ℕ) : ZMod 3) ≠ 0 := by
    intro h
    have hdvd : 3 ∣ p := (ZMod.natCast_eq_zero_iff p 3).mp h
    exact hp3 ((Nat.prime_dvd_prime_iff_eq Nat.prime_three
      (Fact.out : p.Prime)).mp hdvd).symm
  rw [legendreSym.eq_one_iff' 3 hpcast]
  rcases hpmod3 with hp1 | hp2mod
  · rw [← ZMod.natCast_mod p 3, hp1]
    decide
  · rw [← ZMod.natCast_mod p 3, hp2mod]
    decide

private def eisensteinEvalMod (p : ℕ) (r : ℤ)
    (hr : (r : ZMod p) ^ 2 = (-1 : ZMod p) + (r : ZMod p)) :
    EisensteinOrder →+* ZMod p :=
  QOrd.evalMod (-1) 1 p r (by simpa using hr)

private theorem eisenstein_root_ker (p : ℕ) (r : ℤ)
    (hr : (r : ZMod p) ^ 2 = (-1 : ZMod p) + (r : ZMod p)) :
    QOrd.rootIdeal (-1) 1 p r = RingHom.ker (eisensteinEvalMod p r hr) := by
  apply le_antisymm
  · rw [QOrd.rootIdeal, Ideal.span_le]
    intro z hz
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hz
    rcases hz with rfl | rfl
    · simp [eisensteinEvalMod, QOrd.evalMod]
    · simp [eisensteinEvalMod, QOrd.evalMod]
  · intro z hz
    rw [RingHom.mem_ker] at hz
    have hz' : (z.re : ZMod p) + (z.im : ZMod p) * (r : ZMod p) = 0 := by
      simpa [eisensteinEvalMod, QOrd.evalMod] using hz
    have hdiv : (p : ℤ) ∣ z.re + z.im * r := by
      rw [← ZMod.intCast_zmod_eq_zero_iff_dvd]
      simpa [Int.cast_add, Int.cast_mul] using hz'
    obtain ⟨q, hq⟩ := hdiv
    rw [QOrd.rootIdeal, Ideal.mem_span_pair]
    refine ⟨(⟨q, 0⟩ : EisensteinOrder), (⟨z.im, 0⟩ : EisensteinOrder), ?_⟩
    apply QuadraticAlgebra.ext
    · simp only [QuadraticAlgebra.re_add, QuadraticAlgebra.re_mul,
        QuadraticAlgebra.re_intCast, QuadraticAlgebra.re_sub,
        QuadraticAlgebra.omega_re]
      dsimp
      nlinarith [hq]
    · simp only [QuadraticAlgebra.im_add, QuadraticAlgebra.im_mul,
        QuadraticAlgebra.im_intCast, QuadraticAlgebra.im_sub,
        QuadraticAlgebra.omega_im]
      dsimp
      ring

private theorem eisenstein_mod_surjective (p : ℕ) (r : ℤ)
    (hr : (r : ZMod p) ^ 2 = (-1 : ZMod p) + (r : ZMod p)) :
    Function.Surjective (eisensteinEvalMod p r hr) := by
  intro x
  obtain ⟨z, rfl⟩ := ZMod.ringHom_surjective (Int.castRingHom (ZMod p)) x
  refine ⟨(z : EisensteinOrder), ?_⟩
  simp [eisensteinEvalMod, QOrd.evalMod]

private theorem eisenstein_card_quot (p : ℕ) (r : ℤ)
    (hr : (r : ZMod p) ^ 2 = (-1 : ZMod p) + (r : ZMod p)) :
    Submodule.cardQuot (QOrd.rootIdeal (-1) 1 p r) = p := by
  rw [Submodule.cardQuot_apply]
  let e₁ : EisensteinOrder ⧸ QOrd.rootIdeal (-1) 1 p r ≃+
      EisensteinOrder ⧸ RingHom.ker (eisensteinEvalMod p r hr) :=
    (Ideal.quotEquivOfEq (eisenstein_root_ker p r hr)).toAddEquiv
  let e₂ : EisensteinOrder ⧸ RingHom.ker (eisensteinEvalMod p r hr) ≃+ ZMod p :=
    (RingHom.quotientKerEquivOfSurjective
      (eisenstein_mod_surjective p r hr)).toAddEquiv
  calc
    Nat.card (EisensteinOrder ⧸ QOrd.rootIdeal (-1) 1 p r) =
        Nat.card (ZMod p) := Nat.card_congr (e₁.trans e₂).toEquiv
    _ = p := Nat.card_zmod p

private theorem eisenstein_algebraNorm (z : EisensteinOrder) :
    Algebra.norm ℤ z = z.re ^ 2 + z.re * z.im + z.im ^ 2 := by
  have hmat : Algebra.leftMulMatrix (QuadraticAlgebra.basis (-1) 1) z =
      !![z.re, -z.im; z.im, z.re + z.im] := by
    ext i j
    fin_cases i <;> fin_cases j <;>
      simp [Algebra.leftMulMatrix_eq_repr_mul, QuadraticAlgebra.basis,
        QuadraticAlgebra.linearEquivTuple, QuadraticAlgebra.equivProd,
        QuadraticAlgebra.re_mul, QuadraticAlgebra.im_mul]
  rw [Algebra.norm_eq_matrix_det (QuadraticAlgebra.basis (-1) 1)]
  rw [hmat, Matrix.det_fin_two_of]
  ring

private theorem eisenstein_sq_mul
    (a b : ℤ) :
    ∃ x y : ℤ, a ^ 2 + a * b + b ^ 2 = x ^ 2 + 3 * y ^ 2 := by
  by_cases hb : Even b
  · obtain ⟨y, rfl⟩ := hb
    exact ⟨a + y, y, by ring⟩
  · by_cases ha : Even a
    · obtain ⟨y, rfl⟩ := ha
      exact ⟨b + y, y, by ring⟩
    · have hab : Even (a + b) := by
        exact (Int.not_even_iff_odd.mp ha).add_odd (Int.not_even_iff_odd.mp hb)
      obtain ⟨y, hy⟩ := hab
      refine ⟨-a + y, y, ?_⟩
      have hbexpr : b = 2 * y - a := by linarith
      rw [hbexpr]
      ring

private theorem sq_mod_one
    (p : ℕ) [Fact p.Prime] (hp2 : p ≠ 2) (hp3 : p ≠ 3)
    (hpmod : p % 3 = 1) :
    ∃ x y : ℤ, (p : ℤ) = x ^ 2 + 3 * y ^ 2 := by
  have hsquare : IsSquare (-3 : ZMod p) :=
    (square_neg_mod p hp2 hp3).2 hpmod
  obtain ⟨s, hs⟩ := hsquare
  have hs' : s ^ 2 = (-3 : ZMod p) := by simpa [pow_two] using hs.symm
  have htwo : (2 : ZMod p) ≠ 0 := by
    intro h
    apply hp2
    exact (Nat.prime_dvd_prime_iff_eq (Fact.out : p.Prime) Nat.prime_two).mp
      ((ZMod.natCast_eq_zero_iff 2 p).mp h)
  let r : ZMod p := (1 + s) / 2
  have hr : r ^ 2 = (-1 : ZMod p) + r := by
    dsimp [r]
    field_simp [htwo]
    linear_combination hs'
  obtain ⟨a, ha⟩ := ZMod.ringHom_surjective (Int.castRingHom (ZMod p)) r
  have ha' : ((a : ℤ) : ZMod p) = r := ha
  have hroot : ((a : ℤ) : ZMod p) ^ 2 =
      (-1 : ZMod p) + ((a : ℤ) : ZMod p) := by
    rw [ha']
    exact hr
  letI : Fact (∀ r : ℚ, r ^ 2 ≠ ((-3 : ℤ) : ℚ) + 0 * r) :=
    ⟨fun r hr => by norm_num at hr; nlinarith [sq_nonneg r]⟩
  letI : IsDomain EisensteinOrder :=
    eisenstein_embedding_injective.isDomain eisensteinOrderEmbedding
  letI : IsPrincipalIdealRing EisensteinOrder := eisenstein_principal_ring
  obtain ⟨g, hg⟩ := IsPrincipalIdealRing.principal
    (QOrd.rootIdeal (-1) 1 p a)
  have hcard : Submodule.cardQuot (Ideal.span ({g} : Set EisensteinOrder)) = p := by
    change Submodule.cardQuot (EisensteinOrder ∙ g) = p
    rw [← hg]
    exact eisenstein_card_quot p a hroot
  have habs : (Algebra.norm ℤ g).natAbs = p := by
    calc
      (Algebra.norm ℤ g).natAbs =
          Ideal.absNorm (Ideal.span ({g} : Set EisensteinOrder)) :=
        (Ideal.absNorm_span_singleton g).symm
      _ = Submodule.cardQuot (Ideal.span ({g} : Set EisensteinOrder)) := rfl
      _ = p := hcard
  have hnorm : Algebra.norm ℤ g = (p : ℤ) := by
    have hnonneg : 0 ≤ Algebra.norm ℤ g := by
      rw [eisenstein_algebraNorm]
      nlinarith [sq_nonneg (2 * g.re + g.im), sq_nonneg g.im]
    exact Int.natAbs_of_nonneg hnonneg ▸ congrArg Int.ofNat habs
  obtain ⟨x, y, hxy⟩ := eisenstein_sq_mul g.re g.im
  exact ⟨x, y, by rw [← hxy, ← eisenstein_algebraNorm, hnorm]⟩

private theorem mod_sq_mul
    {p : ℕ} [Fact p.Prime] (hp3 : p ≠ 3)
    (hrep : ∃ x y : ℤ, (p : ℤ) = x ^ 2 + 3 * y ^ 2) :
    p % 3 = 1 := by
  rcases hrep with ⟨x, y, hxy⟩
  have hcast := congrArg (fun z : ℤ ↦ (z : ZMod 3)) hxy
  have hrem : p % 3 = 1 ∨ p % 3 = 2 := by
    have hne0 : p % 3 ≠ 0 := by
      intro hzero
      have hdvd : 3 ∣ p := Nat.dvd_of_mod_eq_zero hzero
      exact hp3 ((Nat.prime_dvd_prime_iff_eq Nat.prime_three
        (Fact.out : p.Prime)).mp hdvd).symm
    omega
  rcases hrem with hp1 | hp2mod
  · exact hp1
  · exfalso
    have hbad : ∀ z : ZMod 3, z ^ 2 ≠ 2 := by decide
    apply hbad (x : ZMod 3)
    have hcast' : (p : ZMod 3) = (x : ZMod 3) ^ 2 := by
      calc
        (p : ZMod 3) = (x : ZMod 3) ^ 2 + 3 * (y : ZMod 3) ^ 2 := by
          simpa using hcast
        _ = (x : ZMod 3) ^ 2 := by
          have hthree : (3 : ZMod 3) = 0 := by decide
          rw [hthree, zero_mul, add_zero]
    rw [← hcast']
    simp [← ZMod.natCast_mod p 3, hp2mod]

/-- Exercise 3-3(c): for `p ≠ 3`, a prime is represented by `x² + 3y²`
exactly when it is `1` modulo `3`. -/
theorem sq_add_mul
    (p : ℕ) [Fact p.Prime] (hp3 : p ≠ 3) :
    (∃ x y : ℤ, (p : ℤ) = x ^ 2 + 3 * y ^ 2) ↔ p % 3 = 1 := by
  constructor
  · exact mod_sq_mul hp3
  · intro hpmod
    have hp2 : p ≠ 2 := by
      intro hp
      subst p
      norm_num at hpmod
    exact sq_mod_one p hp2 hp3 hpmod

end

end Submission.NumberTheory.Milne
