import Towers.NumberTheory.Completions.DifferentSemilocalRecovery
import Mathlib.RingTheory.FractionalIdeal.Extended

/-!
# Images of fractional-ideal lattices in semilocal products

The coefficient ring of a semilocal completion is a finite product.  Hence
its idempotents separate coordinates: the submodule generated by a set of
product-valued elements is exactly the product of the submodules generated
by their coordinate images.  This observation converts completed spans into
coordinatewise extensions of fractional ideals.
-/

namespace Towers.NumberTheory.Milne

open Module Submodule nonZeroDivisors
open scoped TensorProduct

noncomputable section

universe u

section ProductSpan

variable {C ι : Type*} [CommRing C] [Finite ι]
variable (B E : ι → Type u)
  [∀ i, CommRing (B i)] [∀ i, CommRing (E i)]
  [∀ i, Algebra C (B i)] [∀ i, Algebra (B i) (E i)]
  [∀ i, Algebra C (E i)] [∀ i, IsScalarTower C (B i) (E i)]

/-- Over a finite product of coefficient rings, the span of a set of
product-valued elements is the product of its coordinate spans. -/
theorem restrict_scalars_pi
    (T : Set (∀ i, E i)) :
    (Submodule.span (∀ i, B i) T).restrictScalars C =
      Submodule.pi Set.univ
        (fun i ↦
          (Submodule.span (B i) ((fun x : ∀ i, E i => x i) '' T)).restrictScalars C) := by
  classical
  letI := Fintype.ofFinite ι
  ext y
  constructor
  · intro hy
    rw [Submodule.restrictScalars_mem] at hy
    rw [Submodule.mem_pi]
    refine Submodule.span_induction
      (p := fun z _ => ∀ i, i ∈ Set.univ →
        z i ∈ Submodule.span (B i) ((fun x : ∀ i, E i => x i) '' T))
      ?_ ?_ ?_ ?_ hy
    · intro z hz i _
      exact Submodule.subset_span ⟨z, hz, rfl⟩
    · intro i _
      exact Submodule.zero_mem _
    · intro x z _ _ hx hz i hi
      exact Submodule.add_mem _ (hx i hi) (hz i hi)
    · intro b z _ hz i hi
      change b i • z i ∈ _
      exact Submodule.smul_mem _ (b i) (hz i hi)
  · intro hy
    rw [Submodule.mem_pi] at hy
    rw [Submodule.restrictScalars_mem]
    rw [← Finset.univ_sum_single y]
    apply Submodule.sum_mem
    intro i _
    have hyi : y i ∈
        Submodule.span (B i) ((fun x : ∀ i, E i => x i) '' T) :=
      hy i (Set.mem_univ i)
    refine Submodule.span_induction
      (p := fun z _ => Pi.single i z ∈ Submodule.span (∀ i, B i) T)
      ?_ ?_ ?_ ?_ hyi
    · rintro z ⟨t, ht, rfl⟩
      have ht' : t ∈ Submodule.span (∀ i, B i) T :=
        Submodule.subset_span ht
      have hmem := Submodule.smul_mem
        (Submodule.span (∀ i, B i) T) (Pi.single i 1) ht'
      have heq : Pi.single i (t i) = (Pi.single i 1 : ∀ i, B i) • t := by
        funext j
        by_cases hji : j = i
        · subst j
          simp
        · simp [hji]
      rw [heq]
      exact hmem
    · simp
    · intro x z _ _ hx hz
      simpa only [Pi.single_add] using Submodule.add_mem _ hx hz
    · intro b z _ hz
      have hmem := Submodule.smul_mem
        (Submodule.span (∀ i, B i) T) (Pi.single i b) hz
      have heq : Pi.single i (b • z) =
          (Pi.single i b : ∀ i, B i) • Pi.single i z := by
        funext j
        by_cases hji : j = i
        · subst j
          simp
        · simp [hji]
      rw [heq]
      exact hmem

end ProductSpan

section FractionalIdealSpan

variable {A K C ι : Type*}
  [CommRing A] [IsDomain A] [Field K]
  [Algebra A K] [IsFractionRing A K]
  [CommRing C] [Finite ι]
variable (B E : ι → Type u)
  [∀ i, CommRing (B i)] [∀ i, IsDomain (B i)]
  [∀ i, Field (E i)]
  [∀ i, Algebra A (B i)] [∀ i, IsTorsionFree A (B i)]
  [∀ i, Algebra (B i) (E i)] [∀ i, IsFractionRing (B i) (E i)]
  [∀ i, Algebra K (E i)] [∀ i, Algebra A (E i)]
  [∀ i, IsScalarTower A (B i) (E i)]
  [∀ i, IsScalarTower A K (E i)]
  [∀ i, Algebra C (B i)] [∀ i, Algebra C (E i)]
  [∀ i, IsScalarTower C (B i) (E i)]

/-- Extending a fractional ideal into every factor is the same lattice as
spanning its diagonal fraction-field image over the product of the factor
integer rings. -/
theorem restrict_scalars_extended
    (I : FractionalIdeal (nonZeroDivisors A) K) :
    (Submodule.span (∀ i, B i)
        ((fun x : K => fun i => algebraMap K (E i) x) '' (I : Set K))).restrictScalars C =
      Submodule.pi Set.univ
        (fun i ↦
          (((FractionalIdeal.extendedHom (E i) (B i) I :
              FractionalIdeal (nonZeroDivisors (B i)) (E i)) :
                Submodule (B i) (E i)).restrictScalars C)) := by
  classical
  letI := Fintype.ofFinite ι
  rw [restrict_scalars_pi B E]
  congr 1
  funext i
  apply congrArg (Submodule.restrictScalars C)
  rw [FractionalIdeal.extendedHom'_apply,
    FractionalIdeal.coe_extended_eq_span]
  have hmap : IsLocalization.map (S := K) (E i)
      (algebraMap A (B i))
        (nonZeroDivisors_le_comap_nonZeroDivisors_of_injective _
          (FaithfulSMul.algebraMap_injective A (B i))) =
      algebraMap K (E i) := by
    apply IsLocalization.ringHom_ext A⁰
    ext a
    change IsLocalization.map (S := K) (E i)
        (algebraMap A (B i))
          (nonZeroDivisors_le_comap_nonZeroDivisors_of_injective _
            (FaithfulSMul.algebraMap_injective A (B i)))
          (algebraMap A K a) =
        algebraMap K (E i) (algebraMap A K a)
    rw [IsLocalization.map_eq]
    rw [← IsScalarTower.algebraMap_apply A (B i) (E i),
      ← IsScalarTower.algebraMap_apply A K (E i)]
  rw [hmap]
  congr 1
  rw [Set.image_image]

end FractionalIdealSpan

section ScalarClosure

variable {C ι : Type*} [CommRing C]
variable (B E : ι → Type u)
  [∀ i, CommRing (B i)] [∀ i, CommRing (E i)]
  [∀ i, Algebra C (B i)] [∀ i, Algebra (B i) (E i)]
  [∀ i, Algebra C (E i)] [∀ i, IsScalarTower C (B i) (E i)]

/-- If a `C`-span in a product module is already stable under the product
coefficient ring, it agrees with the restriction of the corresponding
product-ring span. -/
theorem restrict_scalars_smul
    (T : Set (∀ i, E i))
    (hstable : ∀ (a : ∀ i, B i) y,
      y ∈ Submodule.span C T → a • y ∈ Submodule.span C T) :
    Submodule.span C T =
      (Submodule.span (∀ i, B i) T).restrictScalars C := by
  apply le_antisymm
  · rw [Submodule.span_le]
    intro x hx
    change x ∈ Submodule.span (∀ i, B i) T
    exact Submodule.subset_span hx
  · intro x hx
    rw [Submodule.restrictScalars_mem] at hx
    exact Submodule.span_induction
      (p := fun y _ => y ∈ Submodule.span C T)
      (fun y hy => Submodule.subset_span hy)
      (Submodule.zero_mem _)
      (fun _ _ _ _ hy hz => Submodule.add_mem _ hy hz)
      (fun a y _ hy => hstable a y hy) hx

end ScalarClosure

section TensorScalarClosure

variable {R S C L ι : Type*}
  [CommRing R] [CommRing S] [Algebra R S]
  [CommRing C] [Algebra R C]
  [Field L] [Algebra S L]
variable (B E : ι → Type u)
  [∀ i, CommRing (B i)] [∀ i, CommRing (E i)]
  [∀ i, Algebra C (B i)] [∀ i, Algebra S (B i)]
  [∀ i, Algebra (B i) (E i)]
  [∀ i, Algebra C (E i)] [∀ i, Algebra S (E i)]
  [∀ i, Algebra L (E i)]
  [∀ i, IsScalarTower C (B i) (E i)]
  [∀ i, IsScalarTower S (B i) (E i)]
  [∀ i, IsScalarTower S L (E i)]

/-- The diagonal image of an `S`-submodule is stable under the whole
integral product ring whenever that product is obtained from `C ⊗[R] S`
with the expected pure-tensor formula. -/
theorem smul_diagonal_tensor
    (e₀ : (C ⊗[R] S) ≃ₐ[C] (∀ i, B i))
    (I : Submodule S L)
    (htmul : ∀ (c : C) (s : S) i,
      e₀ (c ⊗ₜ[R] s) i =
        algebraMap C (B i) c * algebraMap S (B i) s) :
    ∀ (a : ∀ i, B i) y,
      y ∈ Submodule.span C
          ((fun x : L => fun i => algebraMap L (E i) x) '' (I : Set L)) →
      a • y ∈ Submodule.span C
          ((fun x : L => fun i => algebraMap L (E i) x) '' (I : Set L)) := by
  classical
  let T : Set (∀ i, E i) :=
    (fun x : L => fun i => algebraMap L (E i) x) '' (I : Set L)
  let M : Submodule C (∀ i, E i) := Submodule.span C T
  intro a y hy
  have hgenerator (x : L) (hx : x ∈ I) :
      a • (fun i => algebraMap L (E i) x) ∈ M := by
    let z : C ⊗[R] S := e₀.symm a
    have hz : e₀ z • (fun i => algebraMap L (E i) x) ∈ M := by
      induction z using TensorProduct.induction_on with
      | zero => simp [M]
      | add z w hz hw =>
          rw [map_add, add_smul]
          exact Submodule.add_mem M hz hw
      | tmul c s =>
          have heq :
              e₀ (c ⊗ₜ[R] s) • (fun i => algebraMap L (E i) x) =
                c • (fun i => algebraMap L (E i) (s • x)) := by
            funext i
            simp only [Algebra.smul_def, Pi.mul_apply]
            rw [show algebraMap (∀ i, B i) (∀ i, E i)
                (e₀ (c ⊗ₜ[R] s)) i =
              algebraMap (B i) (E i) (e₀ (c ⊗ₜ[R] s) i) by rfl]
            rw [Pi.algebraMap_apply]
            rw [htmul]
            rw [map_mul, map_mul]
            rw [← IsScalarTower.algebraMap_apply C (B i) (E i),
              ← IsScalarTower.algebraMap_apply S (B i) (E i),
              ← IsScalarTower.algebraMap_apply S L (E i)]
            simp [mul_assoc]
          rw [heq]
          apply Submodule.smul_mem M c
          apply Submodule.subset_span
          exact ⟨s • x, I.smul_mem s hx, rfl⟩
    simpa [z] using hz
  refine Submodule.span_induction
    (p := fun z _ => a • z ∈ M)
    ?_ ?_ ?_ ?_ hy
  · rintro _ ⟨x, hx, rfl⟩
    exact hgenerator x hx
  · simp [M]
  · intro x z _ _ hx hz
    rw [smul_add]
    exact Submodule.add_mem M hx hz
  · intro c z _ hz
    rw [smul_comm]
    exact Submodule.smul_mem M c hz

end TensorScalarClosure

section TransportedFractionalIdeal

variable {R S K L C F Q ι : Type u}
  [CommRing R] [CommRing S] [IsDomain S]
  [Field K] [Field L]
  [Algebra R S] [Algebra R K] [IsFractionRing R K]
  [Algebra S L] [IsFractionRing S L]
  [Algebra R L] [Algebra K L]
  [IsScalarTower R S L] [IsScalarTower R K L]
  [IsLocalization (Algebra.algebraMapSubmonoid S R⁰) L]
  [CommRing C] [Algebra R C]
  [Field F] [Algebra C F] [IsFractionRing C F]
  [Algebra R F] [IsScalarTower R C F]
  [Algebra K F] [IsScalarTower R K F]
  [CommRing Q] [Algebra (C ⊗[R] S) Q]
  [Algebra C Q] [IsScalarTower C (C ⊗[R] S) Q]
  [Algebra F Q] [IsScalarTower C F Q]
  [IsLocalization
    (Algebra.algebraMapSubmonoid (C ⊗[R] S) C⁰) Q]
  [Finite ι]
variable (B E : ι → Type u)
  [∀ i, CommRing (B i)] [∀ i, IsDomain (B i)]
  [∀ i, Field (E i)]
  [∀ i, Algebra S (B i)] [∀ i, IsTorsionFree S (B i)]
  [∀ i, Algebra (B i) (E i)] [∀ i, IsFractionRing (B i) (E i)]
  [∀ i, Algebra L (E i)] [∀ i, Algebra S (E i)]
  [∀ i, IsScalarTower S (B i) (E i)]
  [∀ i, IsScalarTower S L (E i)]
  [∀ i, Algebra C (B i)] [∀ i, Algebra C (E i)]
  [∀ i, IsScalarTower C (B i) (E i)]
  [∀ i, Algebra F (E i)] [∀ i, IsScalarTower C F (E i)]

/-- The completed pure-tensor image of a fractional ideal becomes the
product of its coordinatewise extensions.

`hpure` is the pure-tensor formula for the chosen product equivalence.
`hstable` records that the diagonal image is stable under the integral
product coefficient ring; for a concrete tensor-product decomposition this
is proved by tensor induction from the fact that `I` is an `S`-submodule. -/
theorem span_pi_extended
    (eQ : Q ≃ₐ[F] (∀ i, E i))
    (I : FractionalIdeal (nonZeroDivisors S) L)
    (hpure : ∀ x : L,
      eQ (scalarFractionTensor
          (R := R) (S := S) (K := K) (L := L)
          (C := C) (F := F) (Q := Q) ((1 : F) ⊗ₜ[K] x)) =
        (fun i => algebraMap L (E i) x))
    (hstable : ∀ (a : ∀ i, B i) y,
      y ∈ Submodule.span C
          ((fun x : L => fun i => algebraMap L (E i) x) '' (I : Set L)) →
      a • y ∈ Submodule.span C
          ((fun x : L => fun i => algebraMap L (E i) x) '' (I : Set L))) :
    (Submodule.span C
        ((fun x : L =>
          scalarFractionTensor
            (R := R) (S := S) (K := K) (L := L)
            (C := C) (F := F) (Q := Q) ((1 : F) ⊗ₜ[K] x)) ''
          (I : Set L))).map
        (eQ.toLinearEquiv.restrictScalars C).toLinearMap =
      Submodule.pi Set.univ
        (fun i ↦
          (((FractionalIdeal.extendedHom (E i) (B i) I :
              FractionalIdeal (nonZeroDivisors (B i)) (E i)) :
                Submodule (B i) (E i)).restrictScalars C)) := by
  classical
  letI := Fintype.ofFinite ι
  rw [Submodule.map_span]
  have himage :
      (eQ.toLinearEquiv.restrictScalars C :
          Q →ₗ[C] (∀ i, E i)) ''
          ((fun x : L =>
            scalarFractionTensor
              (R := R) (S := S) (K := K) (L := L)
              (C := C) (F := F) (Q := Q) ((1 : F) ⊗ₜ[K] x)) ''
            (I : Set L)) =
        ((fun x : L => fun i => algebraMap L (E i) x) '' (I : Set L)) := by
    ext y
    constructor
    · rintro ⟨_, ⟨x, hx, rfl⟩, rfl⟩
      exact ⟨x, hx, (hpure x).symm⟩
    · rintro ⟨x, hx, rfl⟩
      refine ⟨scalarFractionTensor
          (R := R) (S := S) (K := K) (L := L)
          (C := C) (F := F) (Q := Q) ((1 : F) ⊗ₜ[K] x),
        ⟨x, hx, rfl⟩, ?_⟩
      exact hpure x
  rw [himage]
  rw [restrict_scalars_smul B E _ hstable]
  exact restrict_scalars_extended B E I

/-- Version of `span_pi_extended` in which scalar
closure is discharged from an integral tensor-product decomposition. -/
theorem completed_pi_extended
    (e₀ : (C ⊗[R] S) ≃ₐ[C] (∀ i, B i))
    (eQ : Q ≃ₐ[F] (∀ i, E i))
    (I : FractionalIdeal (nonZeroDivisors S) L)
    (htmul : ∀ (c : C) (s : S) i,
      e₀ (c ⊗ₜ[R] s) i =
        algebraMap C (B i) c * algebraMap S (B i) s)
    (hpure : ∀ x : L,
      eQ (scalarFractionTensor
          (R := R) (S := S) (K := K) (L := L)
          (C := C) (F := F) (Q := Q) ((1 : F) ⊗ₜ[K] x)) =
        (fun i => algebraMap L (E i) x)) :
    (Submodule.span C
        ((fun x : L =>
          scalarFractionTensor
            (R := R) (S := S) (K := K) (L := L)
            (C := C) (F := F) (Q := Q) ((1 : F) ⊗ₜ[K] x)) ''
          (I : Set L))).map
        (eQ.toLinearEquiv.restrictScalars C).toLinearMap =
      Submodule.pi Set.univ
        (fun i ↦
          (((FractionalIdeal.extendedHom (E i) (B i) I :
              FractionalIdeal (nonZeroDivisors (B i)) (E i)) :
                Submodule (B i) (E i)).restrictScalars C)) := by
  apply span_pi_extended B E eQ I hpure
  exact smul_diagonal_tensor B E e₀
    (I : Submodule S L) htmul

end TransportedFractionalIdeal

end

end Towers.NumberTheory.Milne
