import Mathlib.FieldTheory.Finiteness
import Mathlib.GroupTheory.Index
import Mathlib.LinearAlgebra.Dimension.Free
import Mathlib.LinearAlgebra.Quotient.Pi
import Mathlib.RingTheory.QuotSMulTop
import Submission.ClassField.LocalBrauer.DivisionIdealProduct
import Submission.ClassField.LocalBrauer.DivisionIntegerModule
import Submission.ClassField.LocalBrauer.LocalFieldOrder
import Submission.ClassField.LocalBrauer.RamificationIndex

/-!
# Chapter IV, Section 4: the ramification-residue degree formula

We formalize Milne's filtration argument for a central division algebra over
a nonarchimedean local field.  The powers of the maximal ideal give a chain
whose successive additive indices are all the cardinality of the division
residue field.  At the ramification index, this power is the scalar maximal
ideal times `O_D`; finite freeness over `O_K` computes its index from the
base residue field.
-/

namespace Submission.CField.LBrauer

noncomputable section

universe u v

open ValuativeRel
open scoped Pointwise TensorProduct

/-- The additive subgroup underlying a two-sided ideal. -/
def twoSidedSubgroup {R : Type v} [Ring R]
    (I : TwoSidedIdeal R) : AddSubgroup R where
  carrier := I
  zero_mem' := I.zero_mem
  add_mem' := I.add_mem
  neg_mem' := I.neg_mem

@[simp]
theorem two_sided_subgroup {R : Type v} [Ring R]
    (I : TwoSidedIdeal R) (x : R) :
    x ∈ twoSidedSubgroup I ↔ x ∈ I :=
  Iff.rfl

/-- Multiplication of ideals is contained in the right factor. -/
theorem two_sided_right {R : Type v} [Ring R]
    (I J : TwoSidedIdeal R) : twoSidedProduct I J ≤ J := by
  rw [twoSidedProduct, TwoSidedIdeal.span_le]
  rintro z ⟨x, _hx, y, hy, rfl⟩
  exact J.mul_mem_left x y hy

/-- Powers of a two-sided ideal form a descending chain. -/
theorem two_sided_succ {R : Type v} [Ring R]
    (I : TwoSidedIdeal R) (m : ℕ) :
    twoSidedPower I (m + 1) ≤ twoSidedPower I m := by
  rw [sided_ideal_succ]
  exact two_sided_right I _

variable (K D : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
  [IsNonarchimedeanLocalField K] [DivisionRing D]
  [Algebra K D] [Algebra.IsCentral K D] [Module.Finite K D]

local instance : UniformSpace K := IsTopologicalAddGroup.rightUniformSpace K
local instance : IsUniformAddGroup K := isUniformAddGroup_of_addCommGroup
local instance : Valuation.RankOne
    (Valued.v (R := K) (Γ₀ := ValueGroupWithZero K)) := by
  change Valuation.RankOne (valuation K)
  infer_instance
local instance : NontriviallyNormedField K :=
  Valued.toNontriviallyNormedField K (ValueGroupWithZero K)

variable [Valuation.Compatible (NormedField.valuation (K := K))]

/-- Left multiplication, regarded only as an additive homomorphism. -/
def integerLeftMul (x : divisionIntegerSubring K D) :
    divisionIntegerSubring K D →+ divisionIntegerSubring K D where
  toFun y := x * y
  map_zero' := mul_zero x
  map_add' y z := mul_add x y z

set_option maxHeartbeats 1000000 in
-- Unfolding the local absolute-value and order instances in the quotient
-- calculation is expensive.
omit [Algebra.IsCentral K D]
  [Valuation.Compatible (NormedField.valuation (K := K))] in
/-- For a nonzero integer `x`, the additive range of multiplication by `x`
is the additive subgroup underlying the two-sided ideal generated by `x`. -/
theorem integer_range_span
    (x : divisionIntegerSubring K D) (hx0 : (x : D) ≠ 0) :
    (integerLeftMul K D x).range =
      twoSidedSubgroup (TwoSidedIdeal.span ({x} : Set (divisionIntegerSubring K D))) := by
  ext y
  constructor
  · rintro ⟨c, rfl⟩
    exact TwoSidedIdeal.mul_mem_right _ x c
      (TwoSidedIdeal.subset_span (Set.mem_singleton x))
  · intro hy
    have horder := (span_singleton_order K D x y hx0).1 hy
    by_cases hy0 : (y : D) = 0
    · refine ⟨0, ?_⟩
      apply Subtype.ext
      simpa using hy0.symm
    let cD : D := (x : D)⁻¹ * (y : D)
    have hc0 : cD ≠ 0 := mul_ne_zero (inv_ne_zero hx0) hy0
    have hcOrder : 0 ≤ divisionAlgebraOrder K (D := D) cD := by
      rw [division_ne_zero K (D := D) cD hc0]
      have hunit : Units.mk0 cD hc0 =
          (Units.mk0 (x : D) hx0)⁻¹ * Units.mk0 (y : D) hy0 := by
        apply Units.ext
        rfl
      rw [hunit]
      change
        (0 : WithTop ℚ) ≤
          (divisionUnitOrder K D
            (-Additive.ofMul (Units.mk0 (x : D) hx0) +
              Additive.ofMul (Units.mk0 (y : D) hy0)) : ℚ)
      rw [map_add, map_neg, WithTop.coe_nonneg]
      rw [division_ne_zero K (D := D) (x : D) hx0,
        division_ne_zero K (D := D) (y : D) hy0] at horder
      simpa only [sub_eq_add_neg, add_comm] using
        sub_nonneg.mpr (WithTop.coe_le_coe.mp horder)
    let c : divisionIntegerSubring K D :=
      ⟨cD, (integer_subring_nonneg K D cD).2 hcOrder⟩
    refine ⟨c, ?_⟩
    apply Subtype.ext
    change (x : D) * ((x : D)⁻¹ * (y : D)) = (y : D)
    rw [← mul_assoc, mul_inv_cancel₀ hx0, one_mul]

omit [Algebra.IsCentral K D]
  [Valuation.Compatible (NormedField.valuation (K := K))] in
/-- Multiplication by a nonzero division-algebra integer is injective. -/
theorem integer_left_injective
    (x : divisionIntegerSubring K D) (hx0 : (x : D) ≠ 0) :
    Function.Injective (integerLeftMul K D x) := by
  intro y z hyz
  apply Subtype.ext
  apply mul_left_cancel₀ hx0
  exact congrArg Subtype.val hyz

/-- The additive quotient by the subgroup underlying a two-sided ideal is
additively equivalent to the quotient by its ring congruence. -/
noncomputable def twoSidedIdeal {R : Type v} [Ring R]
    (I : TwoSidedIdeal R) :
    R ⧸ twoSidedSubgroup I ≃+ I.ringCon.Quotient := by
  let f := I.ringCon.mk'.toAddMonoidHom
  have hf : Function.Surjective f := I.ringCon.mk'_surjective
  have hker : f.ker = twoSidedSubgroup I := by
    ext x
    change I.ringCon.mk' x = 0 ↔ x ∈ I
    change I.ringCon.mk' x = I.ringCon.mk' 0 ↔ x ∈ I
    exact I.ringCon.eq.trans ((I.rel_iff x 0).trans (by simp))
  exact (QuotientAddGroup.quotientAddEquivOfEq hker.symm).trans
    (QuotientAddGroup.quotientKerEquivOfSurjective f hf)

omit [Algebra.IsCentral K D]
  [Valuation.Compatible (NormedField.valuation (K := K))] in
/-- The additive index of a two-sided ideal is the cardinality of its ring
quotient. -/
theorem two_sided_index (I : TwoSidedIdeal (divisionIntegerSubring K D)) :
    (twoSidedSubgroup I).index = Nat.card I.ringCon.Quotient := by
  rw [AddSubgroup.index]
  exact Nat.card_congr (twoSidedIdeal I).toEquiv

omit [Algebra.IsCentral K D]
  [Valuation.Compatible (NormedField.valuation (K := K))] in
/-- The additive index of the maximal ideal is the cardinality of the
division residue field. -/
theorem division_maximal_index :
    (twoSidedSubgroup (divisionMaximalIdeal K D)).index =
      Nat.card (divisionResidueRing K D) :=
  two_sided_index K D (divisionMaximalIdeal K D)

set_option maxHeartbeats 1000000 in
-- Rewriting principal two-sided ideals through additive ranges is instance-intensive.
omit [Algebra.IsCentral K D]
  [Valuation.Compatible (NormedField.valuation (K := K))] in
/-- Multiplication by a division-algebra uniformizer identifies every
successive quotient `P^m/P^(m+1)` with `O_D/P` at the level of additive
indices. -/
theorem division_maximal_rel
    (e : ℕ) (he : 0 < e)
    (hrange : ∀ q : ℚ,
      q ∈ (divisionUnitOrder K D).range ↔
        ∃ z : ℤ, q = (z : ℚ) / (e : ℚ))
    (π : divisionIntegerSubring K D) (hπ0 : (π : D) ≠ 0)
    (hπorder : divisionUnitOrder K D
        (Additive.ofMul (Units.mk0 (π : D) hπ0)) =
      (1 : ℚ) / (e : ℚ)) (m : ℕ) :
    (twoSidedSubgroup
        (twoSidedPower (divisionMaximalIdeal K D) (m + 1))).relIndex
      (twoSidedSubgroup (twoSidedPower (divisionMaximalIdeal K D) m)) =
        (twoSidedSubgroup (divisionMaximalIdeal K D)).index := by
  let fm := integerLeftMul K D (π ^ m)
  have hπm0 : (((π ^ m : divisionIntegerSubring K D) : D)) ≠ 0 := pow_ne_zero m hπ0
  have hπsucc0 : (((π ^ (m + 1) : divisionIntegerSubring K D) : D)) ≠ 0 :=
    pow_ne_zero (m + 1) hπ0
  have hPm := division_maximal_pow
    K D e he hrange π hπ0 hπorder m
  have hPsucc := division_maximal_pow
    K D e he hrange π hπ0 hπorder (m + 1)
  have hPone : divisionMaximalIdeal K D =
      TwoSidedIdeal.span ({π} : Set (divisionIntegerSubring K D)) := by
    simpa using division_maximal_div
      K D e he hrange π hπ0 hπorder
  have hmapTop :
      (⊤ : AddSubgroup (divisionIntegerSubring K D)).map fm =
        twoSidedSubgroup (twoSidedPower (divisionMaximalIdeal K D) m) := by
    rw [hPm]
    rw [← integer_range_span K D (π ^ m) hπm0]
    ext y
    constructor
    · rintro ⟨x, _hx, rfl⟩
      exact ⟨x, rfl⟩
    · rintro ⟨x, rfl⟩
      exact ⟨x, trivial, rfl⟩
  have hmapP :
      (twoSidedSubgroup (divisionMaximalIdeal K D)).map fm =
        twoSidedSubgroup
          (twoSidedPower (divisionMaximalIdeal K D) (m + 1)) := by
    rw [hPsucc, hPone]
    rw [← integer_range_span K D (π ^ (m + 1)) hπsucc0]
    ext y
    constructor
    · rintro ⟨x, hx, rfl⟩
      have hx' : x ∈ (integerLeftMul K D π).range := by
        rw [integer_range_span K D π hπ0]
        exact hx
      obtain ⟨c, rfl⟩ := hx'
      refine ⟨c, ?_⟩
      apply Subtype.ext
      dsimp [fm, integerLeftMul]
      change ((π : D) ^ (m + 1)) * (c : D) =
        ((π : D) ^ m) * ((π : D) * (c : D))
      rw [pow_succ, mul_assoc]
    · rintro ⟨c, rfl⟩
      refine ⟨π * c, ?_, ?_⟩
      · exact TwoSidedIdeal.mul_mem_right _ π c
          (TwoSidedIdeal.subset_span (Set.mem_singleton π))
      · apply Subtype.ext
        dsimp [fm, integerLeftMul]
        change ((π : D) ^ m) * ((π : D) * (c : D)) =
          ((π : D) ^ (m + 1)) * (c : D)
        rw [pow_succ, mul_assoc]
  have h := AddSubgroup.relIndex_map_map_of_injective
    (twoSidedSubgroup (divisionMaximalIdeal K D))
    (⊤ : AddSubgroup (divisionIntegerSubring K D))
    (integer_left_injective K D (π ^ m) hπm0)
  rw [hmapP, hmapTop, AddSubgroup.relIndex_top_right] at h
  exact h

omit [Algebra.IsCentral K D]
  [Valuation.Compatible (NormedField.valuation (K := K))] in
/-- The index of `P^m` in `O_D` is the `m`th power of the residue-field
cardinality. -/
theorem division_ideal_index
    (e : ℕ) (he : 0 < e)
    (hrange : ∀ q : ℚ,
      q ∈ (divisionUnitOrder K D).range ↔
        ∃ z : ℤ, q = (z : ℚ) / (e : ℚ))
    (π : divisionIntegerSubring K D) (hπ0 : (π : D) ≠ 0)
    (hπorder : divisionUnitOrder K D
        (Additive.ofMul (Units.mk0 (π : D) hπ0)) =
      (1 : ℚ) / (e : ℚ)) (m : ℕ) :
    (twoSidedSubgroup
        (twoSidedPower (divisionMaximalIdeal K D) m)).index =
      (Nat.card (divisionResidueRing K D)) ^ m := by
  induction m with
  | zero =>
      change (⊤ : AddSubgroup (divisionIntegerSubring K D)).index = 1
      exact AddSubgroup.index_top
  | succ m ih =>
      have hle :
          twoSidedSubgroup
              (twoSidedPower (divisionMaximalIdeal K D) (m + 1)) ≤
            twoSidedSubgroup (twoSidedPower (divisionMaximalIdeal K D) m) :=
        two_sided_succ (divisionMaximalIdeal K D) m
      have htower := AddSubgroup.relIndex_mul_index hle
      rw [division_maximal_rel K D e he hrange π hπ0 hπorder m,
        division_maximal_index K D, ih] at htower
      simpa [pow_succ'] using htower.symm

omit [Algebra.IsCentral K D] in
/-- Reducing `O_D` modulo a scalar generator has the cardinality predicted
by its free rank over `O_K`. -/
theorem quot_s_top
    (r : 𝒪[K])
    (hr : IsLocalRing.maximalIdeal 𝒪[K] = Ideal.span {r}) :
    letI : Algebra 𝒪[K] (divisionIntegerSubring K D) := divisionIntegerAlgebra K D
    letI : Module.Finite 𝒪[K] (divisionIntegerSubring K D) :=
      division_integer_module K D
    letI : Module.Free 𝒪[K] (divisionIntegerSubring K D) :=
      division_integer_free K D
    Nat.card (QuotSMulTop r (divisionIntegerSubring K D)) =
      (Nat.card (𝒪[K] ⧸ IsLocalRing.maximalIdeal 𝒪[K])) ^
        Module.finrank K D := by
  letI : Algebra 𝒪[K] (divisionIntegerSubring K D) := divisionIntegerAlgebra K D
  letI : Module.Finite 𝒪[K] (divisionIntegerSubring K D) :=
    division_integer_module K D
  letI : Module.Free 𝒪[K] (divisionIntegerSubring K D) :=
    division_integer_free K D
  let n := Module.finrank 𝒪[K] (divisionIntegerSubring K D)
  let b := Module.finBasis 𝒪[K] (divisionIntegerSubring K D)
  let p : Fin n → Submodule 𝒪[K] 𝒪[K] := fun _ =>
    r • (⊤ : Submodule 𝒪[K] 𝒪[K])
  have hpi :
      r • (⊤ : Submodule 𝒪[K] (Fin n → 𝒪[K])) =
        Submodule.pi Set.univ p := by
    ext x
    constructor
    · intro hx
      rw [Submodule.mem_smul_pointwise_iff_exists] at hx
      obtain ⟨y, _hy, rfl⟩ := hx
      rw [Submodule.mem_pi]
      intro i _hi
      rw [Submodule.mem_smul_pointwise_iff_exists]
      exact ⟨y i, trivial, rfl⟩
    · intro hx
      rw [Submodule.mem_pi] at hx
      have hx' : ∀ i, x i ∈ r • (⊤ : Submodule 𝒪[K] 𝒪[K]) :=
        fun i => hx i (Set.mem_univ i)
      choose y _hy hy using fun i =>
        (Submodule.mem_smul_pointwise_iff_exists
          (x i) r (⊤ : Submodule 𝒪[K] 𝒪[K])).mp (hx' i)
      rw [Submodule.mem_smul_pointwise_iff_exists]
      refine ⟨fun i => y i, trivial, ?_⟩
      funext i
      exact hy i
  let ePi :
      QuotSMulTop r (Fin n → 𝒪[K]) ≃ₗ[𝒪[K]]
        (∀ _ : Fin n, QuotSMulTop r 𝒪[K]) :=
    (Submodule.quotEquivOfEq _ _ hpi).trans (Submodule.quotientPi p)
  let e :
      QuotSMulTop r (divisionIntegerSubring K D) ≃ₗ[𝒪[K]]
        (∀ _ : Fin n, QuotSMulTop r 𝒪[K]) :=
    (QuotSMulTop.congr r b.equivFun).trans ePi
  let eBase : QuotSMulTop r 𝒪[K] ≃ₗ[𝒪[K]]
      (𝒪[K] ⧸ Ideal.span {r}) :=
    (QuotSMulTop.equivQuotTensor r 𝒪[K]).trans
      (TensorProduct.rid 𝒪[K] (𝒪[K] ⧸ Ideal.span {r}))
  calc
    Nat.card (QuotSMulTop r (divisionIntegerSubring K D)) =
        Nat.card (∀ _ : Fin n, QuotSMulTop r 𝒪[K]) :=
      Nat.card_congr e.toEquiv
    _ = (Nat.card (QuotSMulTop r 𝒪[K])) ^ n := by
      rw [Nat.card_pi]
      simp
    _ = (Nat.card (𝒪[K] ⧸ Ideal.span {r})) ^ n := by
      rw [Nat.card_congr eBase.toEquiv]
    _ = (Nat.card (𝒪[K] ⧸ IsLocalRing.maximalIdeal 𝒪[K])) ^
        Module.finrank K D := by
      rw [show n = Module.finrank K D from division_integer_finrank K D]
      exact congrArg (fun q : ℕ => q ^ Module.finrank K D)
        (Nat.card_congr (Ideal.quotientEquivAlgOfEq 𝒪[K] hr.symm).toEquiv)

omit [Valuation.Compatible (NormedField.valuation (K := K))] in
/-- An integer of normalized order zero is a unit of the integer ring. -/
theorem integer_unit_order
    (x : 𝒪[K]) (hx0 : (x : K) ≠ 0)
    (hxorder : localUnitOrder K
      (Additive.ofMul (Units.mk0 (x : K) hx0)) = 0) :
    IsUnit x := by
  have hxval : valuation K (x : K) = 1 := by
    apply le_antisymm x.property
    have hle : localUnitOrder K
        (Additive.ofMul (Units.mk0 (x : K) hx0)) ≤
          localUnitOrder K (0 : Additive Kˣ) := by
      simp [hxorder]
    have := (local_order_valuation K _ _).1 hle
    simpa using this
  exact (Valuation.Integers.isUnit_iff_valuation_eq_one
    (Valuation.integer.integers (valuation K))).2 hxval

omit [Valuation.Compatible (NormedField.valuation (K := K))] in
/-- A base-field element of normalized order one generates the maximal
ideal of the base integer ring. -/
theorem maximal_span_order
    (varpiK : Kˣ)
    (hvarpiK : localUnitOrder K (Additive.ofMul varpiK) = 1) :
    let hval : valuation K (varpiK : K) ≤ 1 := by
      have horder : localUnitOrder K (0 : Additive Kˣ) ≤
          localUnitOrder K (Additive.ofMul varpiK) := by
        simp [hvarpiK]
      simpa using
        (local_order_valuation K
          (1 : Kˣ) varpiK).1 horder
    IsLocalRing.maximalIdeal 𝒪[K] =
      Ideal.span ({⟨(varpiK : K), hval⟩} : Set 𝒪[K]) := by
  letI : IsDiscreteValuationRing 𝒪[K] :=
    discrete_valuation_ring K
  let hval : valuation K (varpiK : K) ≤ 1 := by
    have horder : localUnitOrder K (0 : Additive Kˣ) ≤
        localUnitOrder K (Additive.ofMul varpiK) := by
      simp [hvarpiK]
    simpa using
      (local_order_valuation K
        (1 : Kˣ) varpiK).1 horder
  let r : 𝒪[K] := ⟨(varpiK : K), hval⟩
  have hr0 : (r : K) ≠ 0 := varpiK.ne_zero
  apply Irreducible.maximalIdeal_eq
  refine ⟨?_, ?_⟩
  · intro hrUnit
    have hrval : valuation K (r : K) = 1 :=
      (Valuation.Integers.isUnit_iff_valuation_eq_one
        (Valuation.integer.integers (valuation K))).1 hrUnit
    have hzero : localUnitOrder K (Additive.ofMul varpiK) = 0 := by
      change -WithZero.log
        (local_value_int K (valuation K (varpiK : K))) = 0
      rw [show valuation K (varpiK : K) = 1 from hrval]
      simp
    omega
  · intro a b hab
    have habK : (r : K) = (a : K) * (b : K) := congrArg Subtype.val hab
    have ha0 : (a : K) ≠ 0 := by
      intro ha
      rw [ha, zero_mul] at habK
      exact hr0 habK
    have hb0 : (b : K) ≠ 0 := by
      intro hb
      rw [hb, mul_zero] at habK
      exact hr0 habK
    let ua : Kˣ := Units.mk0 (a : K) ha0
    let ub : Kˣ := Units.mk0 (b : K) hb0
    have haOrder : 0 ≤ localUnitOrder K (Additive.ofMul ua) := by
      have hle : localUnitOrder K (0 : Additive Kˣ) ≤
          localUnitOrder K (Additive.ofMul ua) :=
        (local_order_valuation K (1 : Kˣ) ua).2
          (by
            change valuation K (a : K) ≤ valuation K (1 : K)
            simpa only [map_one] using a.property)
      simpa using hle
    have hbOrder : 0 ≤ localUnitOrder K (Additive.ofMul ub) := by
      have hle : localUnitOrder K (0 : Additive Kˣ) ≤
          localUnitOrder K (Additive.ofMul ub) :=
        (local_order_valuation K (1 : Kˣ) ub).2
          (by
            change valuation K (b : K) ≤ valuation K (1 : K)
            simpa only [map_one] using b.property)
      simpa using hle
    have hur : ua * ub = varpiK := by
      apply Units.ext
      exact habK.symm
    have hsum : localUnitOrder K (Additive.ofMul ua) +
        localUnitOrder K (Additive.ofMul ub) = 1 := by
      rw [← map_add, show Additive.ofMul ua + Additive.ofMul ub =
        Additive.ofMul (ua * ub) from rfl, hur, hvarpiK]
    rcases (by omega :
        localUnitOrder K (Additive.ofMul ua) = 0 ∨
          localUnitOrder K (Additive.ofMul ub) = 0) with ha | hb
    · exact Or.inl (integer_unit_order K a ha0 (by simpa [ua] using ha))
    · exact Or.inr (integer_unit_order K b hb0 (by simpa [ub] using hb))

set_option maxHeartbeats 1000000 in
-- Rewriting a principal two-sided ideal as a pointwise scalar submodule is instance-intensive.
omit [Algebra.IsCentral K D] in
/-- The principal two-sided ideal generated by a scalar integer is, as an
additive subgroup, the scalar multiple of the whole integer module. -/
theorem sided_integer_smul
    (r : 𝒪[K]) (hr0 : (r : K) ≠ 0) :
    letI : Algebra 𝒪[K] (divisionIntegerSubring K D) := divisionIntegerAlgebra K D
    letI : SMulCommClass 𝒪[K] 𝒪[K] (divisionIntegerSubring K D) :=
      ⟨fun a b x => by rw [← mul_smul, mul_comm, mul_smul]⟩
    twoSidedSubgroup
        (TwoSidedIdeal.span
          ({baseDivision K D r} : Set (divisionIntegerSubring K D))) =
      (r • (⊤ : Submodule 𝒪[K] (divisionIntegerSubring K D))).toAddSubgroup := by
  letI : Algebra 𝒪[K] (divisionIntegerSubring K D) := divisionIntegerAlgebra K D
  letI : SMulCommClass 𝒪[K] 𝒪[K] (divisionIntegerSubring K D) :=
    ⟨fun a b x => by rw [← mul_smul, mul_comm, mul_smul]⟩
  let a : divisionIntegerSubring K D := baseDivision K D r
  have ha0 : (a : D) ≠ 0 := by
    change algebraMap K D (r : K) ≠ 0
    exact (map_ne_zero (algebraMap K D)).2 hr0
  rw [← integer_range_span K D a ha0]
  ext y
  constructor
  · rintro ⟨c, rfl⟩
    change a * c ∈ r • (⊤ : Submodule 𝒪[K] (divisionIntegerSubring K D))
    rw [Submodule.mem_smul_pointwise_iff_exists]
    refine ⟨c, trivial, ?_⟩
    apply Subtype.ext
    rfl
  · intro hy
    change y ∈ r • (⊤ : Submodule 𝒪[K] (divisionIntegerSubring K D)) at hy
    rw [Submodule.mem_smul_pointwise_iff_exists] at hy
    obtain ⟨c, _hc, hc⟩ := hy
    refine ⟨c, ?_⟩
    rw [← hc]
    apply Subtype.ext
    rfl

omit [Algebra.IsCentral K D] in
/-- The additive index of a scalar principal ideal in `O_D`. -/
theorem sided_integer_index
    (r : 𝒪[K]) (hr0 : (r : K) ≠ 0)
    (hr : IsLocalRing.maximalIdeal 𝒪[K] = Ideal.span {r}) :
    (twoSidedSubgroup
        (TwoSidedIdeal.span
          ({baseDivision K D r} : Set (divisionIntegerSubring K D)))).index =
      (fieldResidueCard K) ^ Module.finrank K D := by
  letI : Algebra 𝒪[K] (divisionIntegerSubring K D) := divisionIntegerAlgebra K D
  letI : Module.Finite 𝒪[K] (divisionIntegerSubring K D) :=
    division_integer_module K D
  letI : Module.Free 𝒪[K] (divisionIntegerSubring K D) :=
    division_integer_free K D
  rw [sided_integer_smul K D r hr0]
  change Nat.card (QuotSMulTop r (divisionIntegerSubring K D)) = _
  simpa [fieldResidueCard] using quot_s_top K D r hr

omit [Algebra.IsCentral K D] in
/-- The division residue field has `q^f` elements. -/
theorem nat_division_ring :
    Nat.card (divisionResidueRing K D) =
      (fieldResidueCard K) ^ residueDegree K D := by
  letI : Field (divisionResidueRing K D) := divisionResidueField K D
  letI : Algebra 𝓀[K] (divisionResidueRing K D) :=
    divisionResidueAlgebra K D
  letI : Module.Finite 𝓀[K] (divisionResidueRing K D) :=
    division_residue_module K D
  simpa [fieldResidueCard, residueDegree] using
    (Module.natCard_eq_pow_finrank
      (K := 𝓀[K]) (V := divisionResidueRing K D))

set_option maxHeartbeats 1000000 in
-- The final filtration comparison unfolds several local-field and finite-module equivalences.
/-- Milne's formula `[D : K] = e f` for a central division algebra over a
nonarchimedean local field. -/
theorem division_ramification_degree :
    Module.finrank K D = ramificationIndex K D * residueDegree K D := by
  let e := ramificationIndex K D
  have he : 0 < e := ramificationIndex_pos K D
  have hrange : ∀ q : ℚ,
      q ∈ (divisionUnitOrder K D).range ↔
        ∃ z : ℤ, q = (z : ℚ) / (e : ℚ) := by
    simpa [e] using division_algebra_range K D
  obtain ⟨π, hπ0, hπorder⟩ :=
    division_integer_div K D e he hrange
  obtain ⟨varpiKAdd, hvarpiKAdd⟩ :=
    local_order_surjective K (1 : ℤ)
  let varpiK : Kˣ := varpiKAdd.toMul
  have hvarpiK : localUnitOrder K (Additive.ofMul varpiK) = 1 := by
    simpa [varpiK] using hvarpiKAdd
  let hnonneg : 0 ≤ localUnitOrder K (Additive.ofMul varpiK) :=
    hvarpiK.symm ▸ (by omega)
  let hval : valuation K (varpiK : K) ≤ 1 := by
    have horder : localUnitOrder K (0 : Additive Kˣ) ≤
        localUnitOrder K (Additive.ofMul varpiK) := by
      simp [hvarpiK]
    simpa using
      (local_order_valuation K
        (1 : Kˣ) varpiK).1 horder
  let r : 𝒪[K] := ⟨(varpiK : K), hval⟩
  have hr0 : (r : K) ≠ 0 := varpiK.ne_zero
  have hrmax : IsLocalRing.maximalIdeal 𝒪[K] = Ideal.span {r} := by
    simpa [r, hval] using
      maximal_span_order K varpiK hvarpiK
  let a : divisionIntegerSubring K D := algebraUnitInteger K D varpiK hnonneg
  have haeq : a = baseDivision K D r := by
    apply Subtype.ext
    rfl
  have hPe : twoSidedPower (divisionMaximalIdeal K D) e =
      TwoSidedIdeal.span ({a} : Set (divisionIntegerSubring K D)) := by
    simpa [a, hnonneg] using
      division_maximal_algebra
        K D e he hrange varpiK hvarpiK
  have hindexFree :
      (twoSidedSubgroup (twoSidedPower (divisionMaximalIdeal K D) e)).index =
        (fieldResidueCard K) ^ Module.finrank K D := by
    rw [hPe, haeq]
    exact sided_integer_index K D r hr0 hrmax
  have hindexFiltration :
      (twoSidedSubgroup (twoSidedPower (divisionMaximalIdeal K D) e)).index =
        (Nat.card (divisionResidueRing K D)) ^ e :=
    division_ideal_index
      K D e he hrange π hπ0 hπorder e
  have hpowers :
      (fieldResidueCard K) ^ Module.finrank K D =
        (fieldResidueCard K) ^ (residueDegree K D * e) := by
    calc
      (fieldResidueCard K) ^ Module.finrank K D =
          (twoSidedSubgroup
            (twoSidedPower (divisionMaximalIdeal K D) e)).index := hindexFree.symm
      _ = (Nat.card (divisionResidueRing K D)) ^ e := hindexFiltration
      _ = ((fieldResidueCard K) ^ residueDegree K D) ^ e := by
        rw [nat_division_ring K D]
      _ = (fieldResidueCard K) ^ (residueDegree K D * e) := by
        rw [pow_mul]
  have hexponents : Module.finrank K D = residueDegree K D * e :=
    Nat.pow_right_injective
      (local_residue_card K) hpowers
  simpa [e, Nat.mul_comm] using hexponents

/-- The same degree formula in the source's `e f = [D : K]` orientation. -/
theorem ramification_residue_finrank :
    ramificationIndex K D * residueDegree K D = Module.finrank K D :=
  (division_ramification_degree K D).symm

end

end Submission.CField.LBrauer
