import Towers.NumberTheory.Ideals.FractionalFreeAbelian

/-!
# Milne, Algebraic Number Theory, Remark 3.21 and Proposition 3.23

Nonzero primes of a localization correspond to the nonzero primes of the original
Dedekind domain that avoid the multiplicative set. Combining this correspondence with
Theorem 3.20 gives Milne's isomorphism on fractional ideal groups.
-/

namespace Towers.NumberTheory.Milne

open scoped nonZeroDivisors

open IsDedekindDomain

variable (A B : Type*) [CommRing A] [IsDomain A] [IsDedekindDomain A]
  [CommRing B] [IsDomain B] [IsDedekindDomain B] [Algebra A B]
  (M : Submonoid A) (hM : M ≤ A⁰) [IsLocalization M B]

/-- The prime-ideal correspondence underlying Proposition 3.23. The nonzero primes of
`B = M⁻¹A` correspond exactly to the nonzero primes of `A` disjoint from `M`. -/
noncomputable def localizationHeightSpectrum :
    HeightOneSpectrum B ≃
      {v : HeightOneSpectrum A // Disjoint (M : Set A) (v.asIdeal : Set A)} where
  toFun v :=
    ⟨⟨v.asIdeal.under A,
        (IsLocalization.isPrime_iff_isPrime_disjoint M B v.asIdeal).mp v.isPrime |>.1,
        ne_of_gt (IsLocalization.bot_lt_under_prime M B hM v.asIdeal v.ne_bot)⟩,
      (IsLocalization.isPrime_iff_isPrime_disjoint M B v.asIdeal).mp v.isPrime |>.2⟩
  invFun v :=
    ⟨v.1.asIdeal.map (algebraMap A B),
      IsLocalization.isPrime_of_isPrime_disjoint M B v.1.asIdeal v.1.isPrime v.2,
      by
        intro h
        have hc := congrArg (fun I : Ideal B => I.under A) h
        change (v.1.asIdeal.map (algebraMap A B)).under A =
          (⊥ : Ideal B).under A at hc
        rw [IsLocalization.under_map_of_isPrime_disjoint M B v.1.isPrime v.2,
          Ideal.under_def, Ideal.comap_bot_of_injective (algebraMap A B)
            (IsLocalization.injective B hM)] at hc
        exact v.1.ne_bot hc⟩
  left_inv v := by
    apply HeightOneSpectrum.ext
    exact IsLocalization.map_under M B v.asIdeal
  right_inv v := by
    apply Subtype.ext
    apply HeightOneSpectrum.ext
    exact IsLocalization.under_map_of_isPrime_disjoint M B v.1.isPrime v.2

variable (L : Type*) [Field L] [Algebra B L] [IsFractionRing B L]

/-- Proposition 3.23: the free subgroup generated by primes of `A` not meeting `M` is
isomorphic to the group of nonzero fractional ideals of `M⁻¹A`. The source is written in
its canonical free-abelian exponent model. -/
noncomputable def localizationFractionalIdeal :
    Multiplicative
        ({v : HeightOneSpectrum A // Disjoint (M : Set A) (v.asIdeal : Set A)} →₀ ℤ) ≃*
      (FractionalIdeal B⁰ L)ˣ :=
  ((Finsupp.domCongr
      (localizationHeightSpectrum A B M hM).symm).toMultiplicative).trans
    (fractionalIdealFactorization B L)

omit [IsDedekindDomain A] [IsDomain B] in
/-- Under the isomorphism of Proposition 3.23, a prime generator is sent to its extension
to the localization. -/
theorem localization_fractional_single
    (v : {v : HeightOneSpectrum A // Disjoint (M : Set A) (v.asIdeal : Set A)}) (n : ℤ) :
    ((localizationFractionalIdeal A B M hM L
        (Multiplicative.ofAdd (Finsupp.single v n))) : FractionalIdeal B⁰ L) =
      (v.1.asIdeal.map (algebraMap A B) : FractionalIdeal B⁰ L) ^ n := by
  change ((fractionalIdealFactorization B L
      (Multiplicative.ofAdd
        ((Finsupp.domCongr (localizationHeightSpectrum A B M hM).symm)
          (Finsupp.single v n)))) : FractionalIdeal B⁰ L) = _
  rw [Finsupp.domCongr_apply, Finsupp.equivMapDomain_single,
    fractional_ideal_single]
  simp [localizationHeightSpectrum]

section ExtensionIdentities

variable {R S K F : Type*} [CommRing R] [CommRing S] [CommRing K] [CommRing F]
variable {N : Submonoid R} {P : Submonoid S}
variable [Algebra R K] [IsLocalization N K] [Algebra S F] [IsLocalization P F]
variable {f : R →+* S} (hf : N ≤ Submonoid.comap f P)

/-- Remark 3.21(b): extension of fractional ideals through a localization preserves
products. -/
theorem fractional_extended_mul (I J : FractionalIdeal N K) :
    FractionalIdeal.extended F hf (I * J) =
      FractionalIdeal.extended F hf I * FractionalIdeal.extended F hf J := by
  exact FractionalIdeal.extended_mul F hf I J

end ExtensionIdentities

section InverseIdentities

variable {R S K F : Type*} [CommRing R] [IsDomain R] [IsDedekindDomain R]
variable [CommRing S] [IsDomain S] [IsDedekindDomain S]
variable [Algebra R S] [Module.IsTorsionFree R S]
variable [Field K] [Field F] [Algebra R K] [Algebra S F]
variable [IsFractionRing R K] [IsFractionRing S F]

/-- Remark 3.21(b): extension from one Dedekind domain to another, in particular to a
localization, preserves inverse fractional ideals. -/
theorem fractional_extended_inv (I : FractionalIdeal R⁰ K) :
    FractionalIdeal.extendedHom F S I⁻¹ = (FractionalIdeal.extendedHom F S I)⁻¹ := by
  exact map_inv₀ (FractionalIdeal.extendedHom F S) I

omit [IsDedekindDomain R] in
/-- Remark 3.21(c): the inverse fractional ideal consists of the elements that carry the
original ideal into the ring under multiplication. -/
theorem fractional_ideal_inv
    (I : FractionalIdeal R⁰ K) (hI : I ≠ 0) (x : K) :
    x ∈ I⁻¹ ↔ ∀ y ∈ I, x * y ∈ (1 : FractionalIdeal R⁰ K) := by
  exact FractionalIdeal.mem_inv_iff hI

end InverseIdentities

end Towers.NumberTheory.Milne
