import Mathlib.RingTheory.Adjoin.Polynomial.Basic
import Mathlib.RingTheory.Polynomial.Chebyshev
import Towers.NumberTheory.Cyclotomic.CyclotomicMaximalReal

/-!
# Milne, Algebraic Number Theory, Exercise 6-2

This file proves the exercise in fixed-subring form and also formalizes the recursive step in
Milne's second solution: every symmetric power `ζ^i + ζ⁻ⁱ` is an integral polynomial in
`ζ + ζ⁻¹`.
-/

namespace Towers.NumberTheory.Milne

open Algebra NumberField Polynomial
open scoped NumberField

/-- Every element of `R[u]`, for a unit `u`, has a quadratic normal form over
`R[u + u⁻¹]`. -/
theorem adjoin_add_mul
    {R S : Type*} [CommRing R] [CommRing S] [Algebra R S]
    (u : Sˣ) {x : S} (hx : x ∈ Algebra.adjoin R ({(u : S)} : Set S)) :
    ∃ a b : S,
      a ∈ Algebra.adjoin R ({(u : S) + (u⁻¹ : Sˣ)} : Set S) ∧
      b ∈ Algebra.adjoin R ({(u : S) + (u⁻¹ : Sˣ)} : Set S) ∧
      x = a + (u : S) * b := by
  let A : Subalgebra R S := Algebra.adjoin R {(u : S) + (u⁻¹ : Sˣ)}
  have ht : (u : S) + (u⁻¹ : Sˣ) ∈ A := Algebra.self_mem_adjoin_singleton R _
  have hquad : (u : S) ^ 2 = ((u : S) + (u⁻¹ : Sˣ)) * u - 1 := by
    rw [add_mul]
    simp
    ring
  induction hx using Algebra.adjoin_induction with
  | mem y hy =>
      rw [Set.mem_singleton_iff] at hy
      subst y
      exact ⟨0, 1, A.zero_mem, A.one_mem, by ring⟩
  | algebraMap r =>
      exact ⟨algebraMap R S r, 0, A.algebraMap_mem r, A.zero_mem, by ring⟩
  | add x y _ _ hx hy =>
      obtain ⟨a, b, ha, hb, rfl⟩ := hx
      obtain ⟨c, d, hc, hd, rfl⟩ := hy
      exact ⟨a + c, b + d, A.add_mem ha hc, A.add_mem hb hd, by ring⟩
  | mul x y _ _ hx hy =>
      obtain ⟨a, b, ha, hb, rfl⟩ := hx
      obtain ⟨c, d, hc, hd, rfl⟩ := hy
      refine ⟨a * c - b * d,
        a * d + b * c + ((u : S) + (u⁻¹ : Sˣ)) * (b * d),
        A.sub_mem (A.mul_mem ha hc) (A.mul_mem hb hd),
        A.add_mem (A.add_mem (A.mul_mem ha hd) (A.mul_mem hb hc))
          (A.mul_mem ht (A.mul_mem hb hd)), ?_⟩
      calc
        (a + (u : S) * b) * (c + (u : S) * d) =
            a * c + (u : S) * (a * d + b * c) + (u : S) ^ 2 * (b * d) := by ring
        _ = a * c - b * d + (u : S) *
            (a * d + b * c + ((u : S) + (u⁻¹ : Sˣ)) * (b * d)) := by
          rw [hquad]
          ring

/-- The rescaled Chebyshev polynomial evaluates at `z + z⁻¹` to `z^n + z⁻ⁿ`. -/
theorem chebyshev_c_inv
    {K : Type*} [Field K] {z : K} (hz : z ≠ 0) (n : ℕ) :
    (Chebyshev.C K n).eval (z + z⁻¹) = z ^ n + (z⁻¹) ^ n := by
  induction n using Nat.twoStepInduction with
  | zero => simp; ring
  | one => simp
  | more n hn hn1 =>
      rw [show ((n + 2 : ℕ) : ℤ) = (n : ℤ) + 2 by omega, Chebyshev.C_add_two]
      have hn1' :
          (Chebyshev.C K ((n : ℤ) + 1)).eval (z + z⁻¹) =
            z ^ (n + 1) + (z⁻¹) ^ (n + 1) := by
        simpa using hn1
      simp only [eval_sub, eval_mul, eval_X, hn, hn1']
      have hcross₁ : z * (z⁻¹) ^ (n + 1) = (z⁻¹) ^ n := by
        rw [pow_succ]
        calc
          z * ((z⁻¹) ^ n * z⁻¹) = (z⁻¹) ^ n * (z * z⁻¹) := by ring
          _ = (z⁻¹) ^ n := by rw [mul_inv_cancel₀ hz, mul_one]
      have hcross₂ : z⁻¹ * z ^ (n + 1) = z ^ n := by
        rw [pow_succ]
        calc
          z⁻¹ * (z ^ n * z) = z ^ n * (z⁻¹ * z) := by ring
          _ = z ^ n := by rw [inv_mul_cancel₀ hz, mul_one]
      calc
        (z + z⁻¹) * (z ^ (n + 1) + (z⁻¹) ^ (n + 1)) -
              (z ^ n + (z⁻¹) ^ n) =
            z ^ (n + 1) * z + (z⁻¹) ^ (n + 1) * z⁻¹ +
              (z * (z⁻¹) ^ (n + 1) - (z⁻¹) ^ n) +
              (z⁻¹ * z ^ (n + 1) - z ^ n) := by ring
        _ = z ^ (n + 1) * z + (z⁻¹) ^ (n + 1) * z⁻¹ := by
          rw [hcross₁, hcross₂]
          ring
        _ = z ^ (n + 2) + (z⁻¹) ^ (n + 2) := by
          apply congrArg₂ (· + ·)
          · rw [show n + 2 = (n + 1) + 1 by omega]
            exact (pow_succ z (n + 1)).symm
          · rw [show n + 2 = (n + 1) + 1 by omega]
            exact (pow_succ z⁻¹ (n + 1)).symm

/-- The induction step in the second solution of Exercise 6-2: every symmetric power of a
nonzero element belongs to the ring generated by `z + z⁻¹`. -/
theorem exercise_six_symmetric
    {K : Type*} [Field K] [CharZero K] {z : K} (hz : z ≠ 0) (n : ℕ) :
    z ^ n + (z⁻¹) ^ n ∈ Algebra.adjoin ℤ ({z + z⁻¹} : Set K) := by
  have heval :
      aeval (z + z⁻¹) (Chebyshev.C ℤ n) = z ^ n + (z⁻¹) ^ n := by
    rw [Chebyshev.aeval_C]
    exact chebyshev_c_inv hz n
  rw [← heval]
  exact Polynomial.aeval_mem_adjoin_singleton ℤ (z + z⁻¹)

/-- Exercise 6-2 in fixed-subring form.  For a primitive `n`th root `ζ`,
`n > 2`, the image of the integers of the maximal real subfield inside the
cyclotomic integer ring is exactly the ring generated by `ζ + ζ⁻¹`.

Combined with `maximal_real_subfield`, this is the
claim that the ring of integers of `ℚ(cos (2π/n))` is
`ℤ[2 cos (2π/n)]`. -/
theorem exercise_six_adjoin
    {n : ℕ} {K : Type*} [Field K] [CharZero K] [NeZero n]
    [IsCyclotomicExtension {n} ℚ K] [NumberField K]
    [NumberField.IsCMField K]
    {ζ : K} (hζ : IsPrimitiveRoot ζ n) (hn : 2 < n) :
    Set.range (algebraMap (𝓞 (NumberField.maximalRealSubfield K)) (𝓞 K)) =
      ↑(Algebra.adjoin ℤ
        ({(CMReal.rootUnit hζ : 𝓞 K) +
          ((CMReal.rootUnit hζ)⁻¹ : (𝓞 K)ˣ)} : Set (𝓞 K))) := by
  let u : (𝓞 K)ˣ := CMReal.rootUnit hζ
  let c := NumberField.IsCMField.ringOfIntegersComplexConj K
  let A : Subalgebra ℤ (𝓞 K) :=
    Algebra.adjoin ℤ ({(u : 𝓞 K) + (u⁻¹ : (𝓞 K)ˣ)} : Set (𝓞 K))
  have hcu : c (u : 𝓞 K) = (u⁻¹ : (𝓞 K)ˣ) := by
    exact CMReal.ring_integers_complex hζ
  have hcuinv : c ((u⁻¹ : (𝓞 K)ˣ) : 𝓞 K) = (u : 𝓞 K) := by
    apply RingOfIntegers.ext
    simp [c, u, NumberField.IsCMField.coe_ringOfIntegersComplexConj,
      CMReal.rootUnit_coe,
      CMReal.complexConj_zeta hζ]
  have hgen_fixed : c ((u : 𝓞 K) + (u⁻¹ : (𝓞 K)ˣ)) =
      (u : 𝓞 K) + (u⁻¹ : (𝓞 K)ˣ) := by
    rw [map_add, hcu, hcuinv, add_comm]
  have hfixed {x : 𝓞 K} (hx : x ∈ A) : c x = x := by
    induction hx using Algebra.adjoin_induction with
    | mem y hy =>
        rw [Set.mem_singleton_iff] at hy
        subst y
        exact hgen_fixed
    | algebraMap z => simp [c]
    | add x y _ _ hx hy => simp only [map_add, hx, hy]
    | mul x y _ _ hx hy => simp only [map_mul, hx, hy]
  have hadjoin : Algebra.adjoin ℤ ({(u : 𝓞 K)} : Set (𝓞 K)) = ⊤ := by
    rw [← hζ.integralPowerBasis.adjoin_gen_eq_top,
      hζ.integralPowerBasis_gen, CMReal.rootUnit_coe]
  have hu_ne_inv : (u : 𝓞 K) ≠ (u⁻¹ : (𝓞 K)ˣ) := by
    intro hu
    have hzeta_inv : ζ = ζ⁻¹ := by
      have hcoe := congrArg (fun x : 𝓞 K ↦ (x : K)) hu
      simpa [u, CMReal.rootUnit_coe] using hcoe
    have hzeta_sq : ζ ^ 2 = 1 := by
      calc
        ζ ^ 2 = ζ * ζ := pow_two ζ
        _ = ζ⁻¹ * ζ := congrArg (fun z ↦ z * ζ) hzeta_inv
        _ = 1 := inv_mul_cancel₀ (hζ.ne_zero (NeZero.ne n))
    have hdiv : n ∣ 2 := (hζ.pow_eq_one_iff_dvd 2).mp hzeta_sq
    exact (Nat.not_le_of_gt hn) (Nat.le_of_dvd (by norm_num) hdiv)
  ext x
  change x ∈ Set.range (algebraMap (𝓞 (NumberField.maximalRealSubfield K)) (𝓞 K)) ↔
    x ∈ A
  constructor
  · intro hx
    have hcx : c x = x :=
      (NumberField.IsCMField.ringOfIntegersComplexConj_eq_self_iff K x).2 hx
    have hx_top : x ∈ Algebra.adjoin ℤ ({(u : 𝓞 K)} : Set (𝓞 K)) := by
      rw [hadjoin]
      trivial
    obtain ⟨a, b, ha, hb, hab⟩ := adjoin_add_mul u hx_top
    have hca : c a = a := hfixed ha
    have hcb : c b = b := hfixed hb
    have hub : (u : 𝓞 K) * b = (u⁻¹ : (𝓞 K)ˣ) * b := by
      apply add_left_cancel (a := a)
      calc
        a + (u : 𝓞 K) * b = x := hab.symm
        _ = c x := hcx.symm
        _ = c (a + (u : 𝓞 K) * b) := congrArg c hab
        _ = a + (u⁻¹ : (𝓞 K)ˣ) * b := by
          rw [map_add, map_mul, hca, hcb, hcu]
    have hb_zero : b = 0 := by
      have hzero : ((u : 𝓞 K) - (u⁻¹ : (𝓞 K)ˣ)) * b = 0 := by
        rw [sub_mul, hub, sub_self]
      rcases mul_eq_zero.mp hzero with h | h
      · exact (sub_ne_zero.mpr hu_ne_inv) h |>.elim
      · exact h
    rw [hb_zero, mul_zero, add_zero] at hab
    exact hab ▸ ha
  · intro hx
    exact (NumberField.IsCMField.ringOfIntegersComplexConj_eq_self_iff K x).1
      (hfixed hx)

/-- Exercise 6-2 for a cyclotomic field, with its number-field and CM-field structures
constructed from the cyclotomic hypotheses.  Thus no auxiliary CM-field assumption appears in
the final statement. -/
theorem exercise_six_integers
    {n : ℕ} {K : Type*} [Field K] [CharZero K] [NeZero n]
    [IsCyclotomicExtension {n} ℚ K]
    {ζ : K} (hζ : IsPrimitiveRoot ζ n) (hn : 2 < n) :
    Set.range (algebraMap (𝓞 (NumberField.maximalRealSubfield K)) (𝓞 K)) =
      ↑(Algebra.adjoin ℤ
        ({(CMReal.rootUnit hζ : 𝓞 K) +
          ((CMReal.rootUnit hζ)⁻¹ : (𝓞 K)ˣ)} : Set (𝓞 K))) := by
  letI : NumberField K := IsCyclotomicExtension.numberField {n} ℚ K
  letI : NumberField.IsCMField K :=
    IsCyclotomicExtension.Rat.isCMField K ⟨n, Set.mem_singleton n, hn⟩
  exact exercise_six_adjoin hζ hn

end Towers.NumberTheory.Milne
