import Towers.Group.Edmonton.BasicCommutators

/-!
# Petresco's 1954 paper on commutators: foundational results

This file formalizes the subgroup-theoretic core of Sections 3 and 4 of
J. Petresco, *Sur les commutateurs* (1954).

Petresco uses `aba⁻¹b⁻¹` for the element commutator. Mathlib uses the same
convention, while some of the Edmonton notes use its inverse. The generated
subgroup is therefore unchanged.
-/

namespace Towers
namespace Edmonton
namespace P1954

open scoped commutatorElement Pointwise

universe u

variable {G : Type u} [Group G]

/-- A nontrivial normal subgroup with no smaller nontrivial normal subgroup.
This local definition avoids coupling Petresco's argument to later Edmonton
developments. -/
def IMNormal (M : Subgroup G) : Prop :=
  M.Normal ∧ M ≠ ⊥ ∧
    ∀ N : Subgroup G, N.Normal → N ≤ M → N ≠ ⊥ → N = M

/-- The commutator of a minimal normal subgroup with the ambient group is
either trivial or the whole subgroup. -/
lemma IMNormal.commtop_eqbot_oreqself
    {M : Subgroup G} (hM : IMNormal M) :
    ⁅M, (⊤ : Subgroup G)⁆ = ⊥ ∨ ⁅M, (⊤ : Subgroup G)⁆ = M := by
  letI : M.Normal := hM.1
  by_cases hbot : ⁅M, (⊤ : Subgroup G)⁆ = ⊥
  · exact Or.inl hbot
  · exact Or.inr
      (hM.2.2 _ inferInstance (Subgroup.commutator_le_left _ _) hbot)

/-- If `K` is normal in `H`, then `[K,H] ≤ K`. -/
lemma commutator_left_subgroup
    {H K : Subgroup G} (hKH : K ≤ H) [(K.subgroupOf H).Normal] :
    ⁅K, H⁆ ≤ K := by
  have hsub :
      ⁅K.subgroupOf H, (⊤ : Subgroup H)⁆ ≤ K.subgroupOf H :=
    Subgroup.commutator_le_left _ _
  have hmap := Subgroup.map_mono (f := H.subtype) hsub
  simpa [Subgroup.map_commutator,
    Subgroup.map_subgroupOf_eq_of_le hKH,
    ← MonoidHom.range_eq_map, H.range_subtype] using hmap

/-- The relative normal closure of `A` in `A ⊔ B` is contained in the join.
This is the ambient-subgroup fact used in Petresco's Proposition 4.2. -/
lemma relative_closure_sup (A B : Subgroup G) :
    relativeNormalClosure (A : Set G) (A ⊔ B) ≤ A ⊔ B :=
  relative_normal_closure
    (fun _ ha ↦ Subgroup.mem_sup_left ha)
    Subgroup.le_normalizer

/-- The commutator subgroup `[A,B]` is contained in the relative normal
closure of `A` in `A ⊔ B`. -/
lemma commutator_relative_closure (A B : Subgroup G) :
    ⁅A, B⁆ ≤ relativeNormalClosure (A : Set G) (A ⊔ B) := by
  let N := relativeNormalClosure (A : Set G) (A ⊔ B)
  have hNH : N ≤ A ⊔ B := relative_closure_sup A B
  letI : (N.subgroupOf (A ⊔ B)).Normal := by
    rw [Subgroup.normal_subgroupOf_iff_le_normalizer hNH]
    exact normalizer_relative_closure (A : Set G) (A ⊔ B)
  apply (Subgroup.commutator_mono
    (show A ≤ N from fun _ ha ↦ subset_relative_closure _ _ ha)
    le_sup_right).trans
  exact commutator_left_subgroup hNH

/-- **Petresco 4.2.** The normal closure of `A` in the subgroup generated by
`A` and `B` is `A[A,B]`. The product is represented as a supremum because
`[A,B]` is normalized by `A`. -/
theorem relative_sup_commutator (A B : Subgroup G) :
    relativeNormalClosure (A : Set G) (A ⊔ B) = A ⊔ ⁅A, B⁆ := by
  apply le_antisymm
  · let C := A ⊔ ⁅A, B⁆
    have hCH : C ≤ A ⊔ B := by
      exact sup_le le_sup_left
        ((Subgroup.commutator_mono le_sup_left le_sup_right).trans
          (A ⊔ B).commutator_le_self)
    letI : (C.subgroupOf (A ⊔ B)).Normal := by
      simpa [C, commutatorExtensionLeft] using
        commutator_normal_sup A B
    apply relative_normal_closure
    · exact fun _ ha ↦ Subgroup.mem_sup_left ha
    · exact Subgroup.le_normalizer_of_normal_subgroupOf hCH
  · exact sup_le
      (fun _ ha ↦ subset_relative_closure _ _ ha)
      (commutator_relative_closure A B)

/-- The ambient normal closure form of Petresco 4.2:
`N_G(A) = A[A,G]`. -/
theorem normal_sup_commutator (A : Subgroup G) :
    relativeNormalClosure (A : Set G) ⊤ = A ⊔ ⁅A, (⊤ : Subgroup G)⁆ := by
  simpa using relative_sup_commutator A (⊤ : Subgroup G)

/-- **Petresco 4.3, subgroup form.** The subgroups `A`, `[A,B]`, and `B`
generate `A ⊔ B`. -/
theorem sup_commutator_join (A B : Subgroup G) :
    (A ⊔ ⁅A, B⁆) ⊔ B = A ⊔ B := by
  apply le_antisymm
  · exact sup_le
      (sup_le le_sup_left
        ((Subgroup.commutator_mono le_sup_left le_sup_right).trans
          (A ⊔ B).commutator_le_self))
      le_sup_right
  · exact sup_le
      (le_sup_left.trans le_sup_left)
      le_sup_right

/-- A subgroup centralizes the ambient group exactly when its commutator with
the ambient group is trivial. -/
lemma top_bot_center (A : Subgroup G) :
    ⁅A, (⊤ : Subgroup G)⁆ = ⊥ ↔ A ≤ Subgroup.center G := by
  rw [Subgroup.commutator_eq_bot_iff_le_centralizer]
  simp only [Subgroup.coe_top, Subgroup.centralizer_univ]

/-- Petresco's first consequence after Proposition 4.2: a normal subgroup is
central, or has nontrivial intersection with the derived subgroup. -/
theorem center_inf_bot
    (A : Subgroup G) (hA : A.Normal) :
    A ≤ Subgroup.center G ∨ A ⊓ commutator G ≠ ⊥ := by
  by_cases hcentral : A ≤ Subgroup.center G
  · exact Or.inl hcentral
  · right
    letI : A.Normal := hA
    have hcomm_ne : ⁅A, (⊤ : Subgroup G)⁆ ≠ ⊥ :=
      fun h ↦ hcentral ((top_bot_center A).mp h)
    intro hinf
    apply hcomm_ne
    apply le_bot_iff.mp
    rw [← hinf]
    exact le_inf
      (Subgroup.commutator_le_left A ⊤)
      (by
        rw [commutator_def]
        exact Subgroup.commutator_mono le_top le_rfl)

/-- Petresco's second consequence after Proposition 4.2: every minimal normal
subgroup is central or lies in the derived subgroup. -/
theorem minimal_center_or
    {M : Subgroup G} (hM : IMNormal M) :
    M ≤ Subgroup.center G ∨ M ≤ commutator G := by
  rcases hM.commtop_eqbot_oreqself with hbot | hself
  · exact Or.inl ((top_bot_center M).mp hbot)
  · right
    rw [← hself, commutator_def]
    exact Subgroup.commutator_mono le_top le_rfl

end P1954
end Edmonton
end Towers
