import Mathlib.Algebra.Module.CharacterModule
import Submission.ClassField.Shifting.RationalAllDegrees

/-!
# The character boundary in Proposition III.3.6

This file identifies the concrete `Q/Z` used in Lemma II.3.3 with
Mathlib's `AddCircle 1`, and packages the resulting boundary
`Hom(G,Q/Z) -> H^2(G,Z)` on `CharacterModule`.
-/

namespace Submission.CField.LRecip

open CategoryTheory Rep
open Submission.CField.Shifting

noncomputable section

/-- The integral lattice in `Q` used by Lemma II.3.3 is the additive
subgroup generated by `1`. -/
theorem rational_integer_lattice :
    rationalIntegerLattice.toAddSubgroup =
      AddSubgroup.zmultiples (1 : ℚ) := by
  ext x
  change (∃ z : ℤ, (z : ℚ) = x) ↔ ∃ z : ℤ, z • (1 : ℚ) = x
  simp

/-- The quotient model `Q / range(Z -> Q)` used in Lemma II.3.3 is
canonically the unit rational circle used by `CharacterModule`. -/
noncomputable def rationalIntegersInvariant :
    rationalModIntegers ≃+ AddCircle (1 : ℚ) :=
  QuotientAddGroup.quotientAddEquivOfEq
    rational_integer_lattice

@[simp]
theorem rational_integers_mk (q : ℚ) :
    rationalIntegersInvariant
        (Submodule.Quotient.mk q) = (q : AddCircle (1 : ℚ)) := by
  rfl

/-- A `Q/Z`-valued character of a group.  When `G` is commutative this is
definitionally the same function type as `CharacterModule (Additive G)`,
but it does not require installing a second group structure on `G`. -/
abbrev RationalCharacter (G : Type u) [Group G] :=
  Additive G →+ AddCircle (1 : ℚ)

variable (G : Type) [Group G] [Fintype G]

/-- Convert a `Q/Z`-valued character to the quotient model used by the
coefficient exact sequence. -/
noncomputable def characterRationalIntegers
    (χ : RationalCharacter G) :
    Additive G →+ rationalModIntegers :=
  rationalIntegersInvariant.symm.toAddMonoidHom.comp χ

omit [Fintype G] in
@[simp]
theorem character_integers_add
    (χ ψ : RationalCharacter G) :
    characterRationalIntegers G (χ + ψ) =
      characterRationalIntegers G χ +
        characterRationalIntegers G ψ := by
  apply AddMonoidHom.ext
  intro g
  exact map_add rationalIntegersInvariant.symm (χ g) (ψ g)

omit [Fintype G] in
@[simp]
theorem character_rational_integers :
    characterRationalIntegers G 0 = 0 := by
  ext g
  rfl

/-- Milne's connecting class `δχ : H²(G,Z)`, defined using the exact
coefficient sequence `0 -> Z -> Q -> Q/Z -> 0`. -/
noncomputable def characterBoundary
    (χ : RationalCharacter G) :
    groupCohomology (Rep.trivial ℤ G ℤ) 2 :=
  (integersIso2 G).hom
    (characterRationalIntegers G χ)

@[simp]
theorem characterBoundary_add
    (χ ψ : RationalCharacter G) :
    characterBoundary G (χ + ψ) =
      characterBoundary G χ + characterBoundary G ψ := by
  simp only [characterBoundary, character_integers_add, map_add]

@[simp]
theorem characterBoundary_zero :
    characterBoundary G 0 = 0 := by
  simp only [characterBoundary, character_rational_integers, map_zero]

end

end Submission.CField.LRecip
