import Mathlib
import Submission.NumberTheory.Fields.PowerMinusTwo
import Submission.NumberTheory.Units.UnitTheorem
import Submission.NumberTheory.Locals.TotallyRamifiedEisenstein
import Submission.NumberTheory.Completions.PlaceFactorCorrespondence


/-!
# Milne, Algebraic Number Theory: two-hour examination, Question 2(b)-(d)

The polynomial `X ^ n - 2` has one real root when `n` is odd and two real roots when
`n` is even.  Consequently the field generated by one of its roots has `n / 2 + 1`
archimedean places and unit rank `n / 2`.  Its only roots of unity are `1` and `-1`.

For the 2-adic question, the completion-factor correspondence identifies extensions of
the 2-adic absolute value with irreducible factors of the completed minimal polynomial.
The polynomial `X ^ n - 2` remains Eisenstein over the 2-adic integers, so there is exactly
one such factor and hence exactly one extension.
-/

namespace Submission.NumberTheory.Milne

noncomputable section

open Module Polynomial NumberField NumberField.InfinitePlace
open scoped NumberField

/-- The positive real `n`th root of `2`. -/
private noncomputable def realRootTwo (n : ℕ) : ℝ :=
  (2 : ℝ) ^ ((n : ℝ)⁻¹)

private theorem real_root_pow {n : ℕ} (hn : n ≠ 0) :
    realRootTwo n ^ n = 2 := by
  exact Real.rpow_inv_natCast_pow (by positivity) hn

private theorem real_root_pos (n : ℕ) : 0 < realRootTwo n := by
  exact Real.rpow_pos_of_pos (by positivity) _

/-- The real roots of `X ^ n - 2`, for odd `n`, consist of the positive real root. -/
theorem x_real_odd {n : ℕ} (hn : Odd n) :
    (X ^ n - C (2 : ℚ)).rootSet ℝ = {realRootTwo n} := by
  ext x
  rw [Set.mem_singleton_iff]
  have hn0 : n ≠ 0 := by
    rintro rfl
    simp at hn
  rw [mem_rootSet_of_ne (X_pow_sub_C_ne_zero (Nat.pos_of_ne_zero hn0) (2 : ℚ))]
  have hpow : x ^ n = (2 : ℝ) ↔ x = realRootTwo n := by
    rw [← real_root_pow hn0]
    exact hn.pow_injective.eq_iff
  simpa [aeval_def, sub_eq_zero] using hpow

/-- The real roots of `X ^ n - 2`, for even positive `n`, are the two opposite real roots. -/
theorem x_real_even {n : ℕ} (hn : Even n) (hn0 : n ≠ 0) :
    (X ^ n - C (2 : ℚ)).rootSet ℝ = {realRootTwo n, -realRootTwo n} := by
  ext x
  rw [Set.mem_insert_iff, Set.mem_singleton_iff]
  rw [mem_rootSet_of_ne (X_pow_sub_C_ne_zero (Nat.pos_of_ne_zero hn0) (2 : ℚ))]
  have hpow : x ^ n = (2 : ℝ) ↔ x = realRootTwo n ∨ x = -realRootTwo n := by
    rw [← real_root_pow hn0, pow_eq_pow_iff_of_ne_zero hn0]
    aesop
  simpa [aeval_def, sub_eq_zero] using hpow

/-- `X ^ n - 2` has one real root for odd `n` and two for even positive `n`. -/
theorem set_x_real {n : ℕ} (hn : 0 < n) :
    Fintype.card ((X ^ n - C (2 : ℚ)).rootSet ℝ) = if Even n then 2 else 1 := by
  classical
  by_cases heven : Even n
  · rw [if_pos heven, ← Nat.card_eq_fintype_card, Nat.card_coe_set_eq,
      x_real_even heven hn.ne']
    apply Set.ncard_pair
    linarith [real_root_pos n]
  · have hodd : Odd n := Nat.not_even_iff_odd.mp heven
    rw [if_neg heven, ← Nat.card_eq_fintype_card, Nat.card_coe_set_eq,
      x_real_odd hodd]
    simp

set_option backward.isDefEq.respectTransparency false in
/-- A number field with a real place has no roots of unity other than `1` and `-1`. -/
theorem or_real_place
    {K : Type*} [Field K] [NumberField K]
    (hreal : 0 < nrRealPlaces K) (x : NumberField.Units.torsion K) :
    (x : (𝓞 K)ˣ) = 1 ∨ (x : (𝓞 K)ˣ) = -1 := by
  by_cases! hc : 2 < orderOf (x : (𝓞 K)ˣ)
  · rw [← orderOf_units, ← orderOf_submonoid] at hc
    linarith [IsPrimitiveRoot.nrRealPlaces_eq_zero_of_two_lt hc
      (IsPrimitiveRoot.orderOf (x.1 : K))]
  · interval_cases hi : orderOf (x : (𝓞 K)ˣ)
    · have hpos : 0 < orderOf (x : (𝓞 K)ˣ) :=
        orderOf_pos_iff.mpr ((CommGroup.mem_torsion _ x.1).1 x.2)
      omega
    · exact Or.intro_left _ (orderOf_eq_one_iff.1 hi)
    · rw [← orderOf_units, CharP.orderOf_eq_two_iff 0 (by decide)] at hi
      simp [← Units.val_inj, Units.val_neg, Units.val_one, hi]

/-- In particular, a number field with a real place has exactly two roots of unity. -/
theorem torsion_real_place
    {K : Type*} [Field K] [NumberField K]
    (hreal : 0 < nrRealPlaces K) :
    NumberField.Units.torsionOrder K = 2 := by
  classical
  refine (Finset.card_eq_two.mpr ⟨1, ⟨-1, neg_one_mem_torsion⟩,
    by simp [← Subtype.coe_ne_coe], Finset.ext fun x ↦ ⟨fun _ ↦ ?_, fun _ ↦ Finset.mem_univ _⟩⟩)
  rw [Finset.mem_insert, Finset.mem_singleton, ← Subtype.val_inj, ← Subtype.val_inj]
  exact or_real_place hreal x

/-- For a simple number field, real embeddings are parametrized by the real roots of the
minimal polynomial of a generator. -/
noncomputable def realEmbeddingsSet
    {K : Type*} [Field K] [NumberField K] {alpha : K}
    (hgen : IntermediateField.adjoin ℚ {alpha} = ⊤) :
    {phi : K →+* ℂ // NumberField.ComplexEmbedding.IsReal phi} ≃
      (minpoly ℚ alpha).rootSet ℝ := by
  have hint : IsIntegral ℚ alpha := Algebra.IsIntegral.isIntegral alpha
  have halgGen : Algebra.adjoin ℚ {alpha} = ⊤ := by
    rw [← IntermediateField.adjoin_simple_toSubalgebra_of_isAlgebraic hint.isAlgebraic]
    exact congrArg IntermediateField.toSubalgebra hgen
  let f : {phi : K →+* ℂ // NumberField.ComplexEmbedding.IsReal phi} →
      (minpoly ℚ alpha).rootSet ℝ := fun phi ↦
    ⟨phi.2.embedding alpha, by
      rw [mem_rootSet]
      refine ⟨minpoly.ne_zero hint, ?_⟩
      simpa using Polynomial.aeval_algHom_apply
        phi.2.embedding.toRatAlgHom alpha (minpoly ℚ alpha)⟩
  refine Equiv.ofBijective f ⟨?_, ?_⟩
  · intro phi psi h
    have hval : phi.2.embedding alpha = psi.2.embedding alpha :=
      congrArg Subtype.val h
    apply Subtype.ext
    apply RingHom.equivRatAlgHom.injective
    apply AlgHom.ext_of_adjoin_eq_top halgGen
    intro x hx
    rw [Set.mem_singleton_iff.mp hx]
    calc
      phi.1 alpha = (phi.2.embedding alpha : ℂ) :=
        (NumberField.ComplexEmbedding.IsReal.coe_embedding_apply phi.2 alpha).symm
      _ = (psi.2.embedding alpha : ℂ) :=
        congrArg (fun z : ℝ ↦ (z : ℂ)) hval
      _ = psi.1 alpha :=
        NumberField.ComplexEmbedding.IsReal.coe_embedding_apply psi.2 alpha
  · intro y
    have hyc : ((y : ℝ) : ℂ) ∈ (minpoly ℚ alpha).rootSet ℂ := by
      rw [mem_rootSet]
      refine ⟨minpoly.ne_zero hint, ?_⟩
      have hmap := Polynomial.aeval_algHom_apply
        (algebraMap ℝ ℂ).toRatAlgHom (y : ℝ) (minpoly ℚ alpha)
      rw [(mem_rootSet.mp y.2).2, map_zero] at hmap
      exact hmap
    have hyrange : ((y : ℝ) : ℂ) ∈ Set.range (fun phi : K →+* ℂ ↦ phi alpha) := by
      rw [NumberField.Embeddings.range_eval_eq_rootSet_minpoly K ℂ alpha]
      exact hyc
    obtain ⟨phi, hphiAlpha⟩ := hyrange
    have hreal : NumberField.ComplexEmbedding.IsReal phi := by
      rw [NumberField.ComplexEmbedding.isReal_iff]
      apply RingHom.equivRatAlgHom.injective
      apply AlgHom.ext_of_adjoin_eq_top halgGen
      intro x hx
      rw [Set.mem_singleton_iff] at hx
      rw [hx]
      change star (phi alpha) = phi alpha
      change phi alpha = ((y : ℝ) : ℂ) at hphiAlpha
      rw [hphiAlpha]
      simp
    refine ⟨⟨phi, hreal⟩, ?_⟩
    apply Subtype.ext
    apply Complex.ofReal_injective
    rw [NumberField.ComplexEmbedding.IsReal.coe_embedding_apply hreal]
    exact hphiAlpha

/-- The number of real places is the number of real roots of a simple generator's minpoly. -/
theorem nr_real_minpoly
    {K : Type*} [Field K] [NumberField K] {alpha : K}
    (hgen : IntermediateField.adjoin ℚ {alpha} = ⊤) :
    nrRealPlaces K = Fintype.card ((minpoly ℚ alpha).rootSet ℝ) := by
  classical
  rw [← NumberField.InfinitePlace.card_real_embeddings]
  exact Fintype.card_congr (realEmbeddingsSet hgen)

/-- Question 2(b), real part: `Q(alpha)` has two real places for even `n` and one for odd `n`. -/
theorem nr_real_places
    {K : Type*} [Field K] [NumberField K]
    {n : ℕ} (hn : 2 ≤ n) {alpha : K}
    (halpha : alpha ^ n = algebraMap ℚ K 2)
    (hgen : IntermediateField.adjoin ℚ {alpha} = ⊤) :
    nrRealPlaces K = if Even n then 2 else 1 := by
  rw [nr_real_minpoly hgen,
    minpoly_x_two (by omega) halpha,
    set_x_real (by omega)]

/-- The number of complex-conjugate pairs of embeddings is `(n - 1) / 2`. -/
theorem nr_complex_two
    {K : Type*} [Field K] [NumberField K]
    {n : ℕ} (hn : 2 ≤ n) {alpha : K}
    (halpha : alpha ^ n = algebraMap ℚ K 2)
    (hgen : IntermediateField.adjoin ℚ {alpha} = ⊤) :
    nrComplexPlaces K = (n - 1) / 2 := by
  have hr := nr_real_places hn halpha hgen
  have hdegree := NumberField.InfinitePlace.card_add_two_mul_card_eq_rank K
  rw [two_adjoin_top hn halpha hgen] at hdegree
  by_cases heven : Even n
  · rw [if_pos heven] at hr
    rcases heven with ⟨k, rfl⟩
    omega
  · rw [if_neg heven] at hr
    rcases Nat.not_even_iff_odd.mp heven with ⟨k, rfl⟩
    omega

/-- Question 2(b): the usual absolute value has `n / 2 + 1` extensions to `Q(alpha)`. -/
theorem nr_archimedean_places
    {K : Type*} [Field K] [NumberField K]
    {n : ℕ} (hn : 2 ≤ n) {alpha : K}
    (halpha : alpha ^ n = algebraMap ℚ K 2)
    (hgen : IntermediateField.adjoin ℚ {alpha} = ⊤) :
    Fintype.card (InfinitePlace K) = n / 2 + 1 := by
  rw [NumberField.InfinitePlace.card_eq_nrRealPlaces_add_nrComplexPlaces,
    nr_real_places hn halpha hgen,
    nr_complex_two hn halpha hgen]
  by_cases heven : Even n
  · rw [if_pos heven]
    rcases heven with ⟨k, rfl⟩
    omega
  · rw [if_neg heven]
    rcases Nat.not_even_iff_odd.mp heven with ⟨k, rfl⟩
    omega

/-- Question 2(d): the unit rank is `n / 2`. -/
theorem unit_rank_two
    {K : Type*} [Field K] [NumberField K]
    {n : ℕ} (hn : 2 ≤ n) {alpha : K}
    (halpha : alpha ^ n = algebraMap ℚ K 2)
    (hgen : IntermediateField.adjoin ℚ {alpha} = ⊤) :
    NumberField.Units.rank K = n / 2 := by
  rw [real_places_complex,
    nr_real_places hn halpha hgen,
    nr_complex_two hn halpha hgen]
  by_cases heven : Even n
  · rw [if_pos heven]
    rcases heven with ⟨k, rfl⟩
    omega
  · rw [if_neg heven]
    rcases Nat.not_even_iff_odd.mp heven with ⟨k, rfl⟩
    omega

/-- Question 2(d): the torsion subgroup of the unit group has order two. -/
theorem torsion_order_two
    {K : Type*} [Field K] [NumberField K]
    {n : ℕ} (hn : 2 ≤ n) {alpha : K}
    (halpha : alpha ^ n = algebraMap ℚ K 2)
    (hgen : IntermediateField.adjoin ℚ {alpha} = ⊤) :
    NumberField.Units.torsionOrder K = 2 := by
  apply torsion_real_place
  rw [nr_real_places hn halpha hgen]
  split_ifs <;> omega

private noncomputable def placeRingAdic
    {K : Type*} [Field K] [NumberField K]
    (v : IsDedekindDomain.HeightOneSpectrum (𝓞 K)) :
    (FinitePlace.mk v).val.Completion ≃+* v.adicCompletion K := by
  let h := completion_universal (FinitePlace.mk v).val
    (FinitePlace.embedding v) (by
      intro x
      exact (FinitePlace.mk_apply v x).symm)
  let F := h.choose
  have hFisometry : Isometry F := h.choose_spec.1.1
  have hFcomp : F.comp (completionEmbedding (FinitePlace.mk v).val) =
      FinitePlace.embedding v := h.choose_spec.1.2
  apply RingEquiv.ofBijective F
  refine ⟨hFisometry.injective, ?_⟩
  have hfun :
      (F : (FinitePlace.mk v).val.Completion → v.adicCompletion K) ∘
        completionEmbedding (FinitePlace.mk v).val =
      algebraMap K (v.adicCompletion K) := by
    funext x
    exact RingHom.congr_fun hFcomp x
  have hdense : DenseRange F := by
    apply DenseRange.of_comp
    rw [hfun]
    exact v.denseRange_algebraMap K
  apply Set.range_eq_univ.mp
  calc
    Set.range F = closure (Set.range F) :=
      hFisometry.isClosedEmbedding.isClosed_range.closure_eq.symm
    _ = Set.univ := dense_iff_closure_eq.mp hdense

@[simp]
private theorem place_completion_adic
    {K : Type*} [Field K] [NumberField K]
    (v : IsDedekindDomain.HeightOneSpectrum (𝓞 K)) (x : K) :
    placeRingAdic v
        (completionEmbedding (FinitePlace.mk v).val x) =
      FinitePlace.embedding v x := by
  let h := completion_universal (FinitePlace.mk v).val
    (FinitePlace.embedding v) (by
      intro y
      exact (FinitePlace.mk_apply v y).symm)
  exact RingHom.congr_fun h.choose_spec.1.2 x

private theorem padic_x_eisenstein
    (n : ℕ) (hn : 0 < n) :
    (X ^ n - C (2 : ℤ_[2])).IsEisensteinAt
      (Ideal.span {(2 : ℤ_[2])}) := by
  have hp : (Ideal.span {(2 : ℤ_[2])}).IsPrime :=
    (Ideal.span_singleton_prime (by norm_num : (2 : ℤ_[2]) ≠ 0)).mpr
      PadicInt.prime_p
  refine (monic_X_pow_sub_C (2 : ℤ_[2]) hn.ne').isEisensteinAt_of_mem_of_notMem
    hp.ne_top ?_ ?_
  · intro i hi
    rw [natDegree_X_pow_sub_C] at hi
    rw [coeff_sub, coeff_X_pow, coeff_C]
    by_cases hi0 : i = 0
    · subst i
      rw [if_neg hn.ne'.symm, if_pos rfl]
      simp
    · have hin : i ≠ n := Nat.ne_of_lt hi
      rw [if_neg hin, if_neg hi0, sub_zero]
      exact Ideal.zero_mem _
  · rw [coeff_zero_eq_eval_zero, eval_sub, eval_pow, eval_X, eval_C,
      zero_pow hn.ne', zero_sub, Ideal.span_singleton_pow,
      Ideal.mem_span_singleton]
    intro h
    rcases h with ⟨c, hc⟩
    have heq : (2 : ℤ_[2]) * ((2 : ℤ_[2]) * c) =
        (2 : ℤ_[2]) * (-1) := by
      calc
        (2 : ℤ_[2]) * ((2 : ℤ_[2]) * c) =
            (2 : ℤ_[2]) ^ 2 * c := by ring
        _ = -(2 : ℤ_[2]) := hc.symm
        _ = (2 : ℤ_[2]) * (-1) := by ring
    have hcunit : (2 : ℤ_[2]) * c = -1 :=
      mul_left_cancel₀ (by norm_num : (2 : ℤ_[2]) ≠ 0) heq
    have hdvd : (2 : ℤ_[2]) ∣ -1 := ⟨c, hcunit.symm⟩
    exact PadicInt.prime_p.not_unit
      (isUnit_iff_dvd_one.mpr (by simpa using hdvd))

private theorem irreducible_x_padic
    (n : ℕ) (hn : 0 < n) :
    Irreducible (X ^ n - C (2 : ℚ_[2])) := by
  have h := eisenstein_irreducible_fraction
    (A := ℤ_[2]) (K := ℚ_[2])
    ((Ideal.span_singleton_prime
      (by norm_num : (2 : ℤ_[2]) ≠ 0)).mpr PadicInt.prime_p)
    (padic_x_eisenstein n hn)
    (monic_X_pow_sub_C (2 : ℤ_[2]) hn.ne')
    (by rw [natDegree_X_pow_sub_C]; exact hn)
  simpa using h

/-- The prime number `2`, regarded as an element of the type of rational primes. -/
abbrev rationalTwoPrime : Nat.Primes := ⟨2, Nat.prime_two⟩

/-- The height-one prime of `𝓞 ℚ` corresponding to the rational prime `2`. -/
noncomputable def rationalTwoHeight :
    IsDedekindDomain.HeightOneSpectrum (𝓞 ℚ) :=
  Rat.HeightOneSpectrum.primesEquiv.symm rationalTwoPrime

/-- The normalized 2-adic finite place of `ℚ`. -/
noncomputable def rationalAdicPlace : FinitePlace ℚ :=
  FinitePlace.mk rationalTwoHeight

private theorem rational_two_height :
    algebraMap ℤ (𝓞 ℚ) 2 ∈ rationalTwoHeight.asIdeal := by
  rw [← Ideal.apply_mem_of_equiv_iff
    (f := Rat.IsIntegralClosure.intEquiv (𝓞 ℚ))]
  have hgen : Rat.HeightOneSpectrum.natGenerator rationalTwoHeight = 2 :=
    congrArg Subtype.val
      (Rat.HeightOneSpectrum.primesEquiv.apply_symm_apply rationalTwoPrime)
  have h :=
    (Rat.HeightOneSpectrum.natGenerator_dvd_iff rationalTwoHeight).mp
      (show Rat.HeightOneSpectrum.natGenerator rationalTwoHeight ∣ 2 by
        rw [hgen])
  have hmap : Rat.IsIntegralClosure.intEquiv (𝓞 ℚ)
      (algebraMap ℤ (𝓞 ℚ) 2) = 2 := by
    rw [Rat.IsIntegralClosure.intEquiv_apply_eq_ringOfIntegersEquiv]
    apply (Int.cast_injective : Function.Injective (fun z : ℤ => (z : ℚ)))
    rw [Rat.ringOfIntegersEquiv_apply_coe]
    norm_num only [map_ofNat]
  rw [hmap]
  exact h

private theorem rational_adic_nontrivial :
    rationalAdicPlace.val.IsNontrivial := by
  refine ⟨2, by norm_num, ?_⟩
  have hlt : rationalAdicPlace.val 2 < 1 := by
    change ‖FinitePlace.embedding rationalTwoHeight 2‖ < 1
    have h :=
      (FinitePlace.norm_lt_one_iff_mem (K := ℚ) rationalTwoHeight
        (algebraMap ℤ (𝓞 ℚ) 2)).2 rational_two_height
    simpa only [map_ofNat] using h
  exact ne_of_lt hlt

noncomputable local instance rationalTwoAdicFinitePlace_factNontrivial :
    Fact rationalAdicPlace.val.IsNontrivial :=
  ⟨rational_adic_nontrivial⟩

noncomputable local instance rationalTwoAbsoluteCompletionAlgebra :
    Algebra ℚ rationalAdicPlace.val.Completion :=
  (completionEmbedding rationalAdicPlace.val).toAlgebra

/-- The absolute-value completion at the rational 2-adic place is `ℚ_[2]`. -/
noncomputable def rationalAbsolutePadic :
    rationalAdicPlace.val.Completion ≃ₐ[ℚ] ℚ_[2] := by
  let eRing :=
    placeRingAdic rationalTwoHeight
  let e₁ : rationalAdicPlace.val.Completion ≃ₐ[ℚ]
      rationalTwoHeight.adicCompletion ℚ :=
    AlgEquiv.ofRingEquiv (f := eRing) (fun x => by
      change eRing
          (completionEmbedding (FinitePlace.mk rationalTwoHeight).val x) =
        algebraMap ℚ (rationalTwoHeight.adicCompletion ℚ) x
      rw [place_completion_adic]
      rfl)
  let e₂ :=
    Rat.HeightOneSpectrum.adicCompletion.padicEquiv rationalTwoHeight
  have hp : Rat.HeightOneSpectrum.primesEquiv rationalTwoHeight =
      rationalTwoPrime :=
    Rat.HeightOneSpectrum.primesEquiv.apply_symm_apply rationalTwoPrime
  rw [hp] at e₂
  simpa [rationalTwoPrime] using e₁.trans e₂.toAlgEquiv

private theorem irreducible_x_completion
    (n : ℕ) (hn : 0 < n) :
    Irreducible (X ^ n - C
      (algebraMap ℚ rationalAdicPlace.val.Completion 2)) := by
  have h := (irreducible_x_padic n hn).map
    (Polynomial.mapAlgEquiv rationalAbsolutePadic.symm)
  change Irreducible ((X ^ n - C (2 : ℚ_[2])).map
    rationalAbsolutePadic.symm.toRingHom) at h
  have htwo : rationalAbsolutePadic.symm (2 : ℚ_[2]) =
      algebraMap ℚ rationalAdicPlace.val.Completion 2 := by
    simp only [map_ofNat]
  have htwo' :
      rationalAbsolutePadic.symm.toRingEquiv.toRingHom
          (2 : ℚ_[2]) =
        algebraMap ℚ rationalAdicPlace.val.Completion 2 :=
    htwo
  rw [Polynomial.map_sub, Polynomial.map_pow, Polynomial.map_X,
    Polynomial.map_C] at h
  rw [htwo'] at h
  exact h

noncomputable local instance rationalTwoAbsoluteCompletionUltrametric :
    IsUltrametricDist rationalAdicPlace.val.Completion := by
  apply IsUltrametricDist.isUltrametricDist_of_forall_norm_natCast_le_one
  intro m
  rw [← map_natCast (completionEmbedding rationalAdicPlace.val),
    norm_completionEmbedding]
  exact
    (show IsNonarchimedean rationalAdicPlace.val from
      fun x y => rationalAdicPlace.add_le x y)
        |>.apply_natCast_le_one

private theorem unique_completed_minpoly
    {K : Type*} [Field K] [NumberField K]
    {n : ℕ} (hn : 0 < n) {alpha : K}
    (halpha : alpha ^ n = algebraMap ℚ K 2) :
    ∃ g₀ : CompletedMinpolyFactor rationalAdicPlace.val alpha,
      ∀ g : CompletedMinpolyFactor rationalAdicPlace.val alpha,
        g = g₀ := by
  let f : rationalAdicPlace.val.Completion[X] :=
    (minpoly ℚ alpha).map
      (completionEmbedding rationalAdicPlace.val)
  have hf : f = X ^ n - C
      (algebraMap ℚ rationalAdicPlace.val.Completion 2) := by
    dsimp [f]
    rw [minpoly_x_two hn halpha]
    simp
  have hfirr : Irreducible f := by
    rw [hf]
    exact irreducible_x_completion n hn
  have hfmonic : f.Monic :=
    (minpoly.monic (Algebra.IsIntegral.isIntegral alpha)).map
      (completionEmbedding rationalAdicPlace.val)
  let g₀ : CompletedMinpolyFactor
      rationalAdicPlace.val alpha :=
    ⟨f, hfirr, hfmonic, dvd_rfl⟩
  refine ⟨g₀, fun g => Subtype.ext ?_⟩
  exact eq_of_monic_of_associated g.2.2.1 hfmonic
    (g.2.1.associated_of_dvd hfirr g.2.2.2)

/-- Question 2(c): the 2-adic absolute value has exactly one extension to
`Q(alpha)` when `alpha ^ n = 2` and `alpha` generates the field. -/
theorem card_absolute_extensions
    {K : Type*} [Field K] [NumberField K]
    {n : ℕ} (hn : 2 ≤ n) {alpha : K}
    (halpha : alpha ^ n = algebraMap ℚ K 2)
    (hgen : IntermediateField.adjoin ℚ {alpha} = ⊤) :
    Nat.card {w : AbsoluteValue K ℝ //
      AbsoluteValue.LiesOver w rationalAdicPlace.val} = 1 := by
  have hgenAlg : Algebra.adjoin ℚ {alpha} = ⊤ := by
    rw [← IntermediateField.adjoin_simple_toSubalgebra_of_isAlgebraic
      (Algebra.IsAlgebraic.isAlgebraic alpha)]
    exact congrArg IntermediateField.toSubalgebra hgen
  let equiv := completedMinpolyExtensions
    rationalAdicPlace.val alpha hgenAlg
  rw [Nat.card_eq_one_iff_unique]
  obtain ⟨g₀, hg₀⟩ :=
    unique_completed_minpoly (by omega) halpha
  refine ⟨⟨fun w₁ w₂ => ?_⟩, ⟨equiv g₀⟩⟩
  apply equiv.symm.injective
  rw [hg₀ (equiv.symm w₁), hg₀ (equiv.symm w₂)]

/-- Question 2(c), in the ideal-theoretic form underlying extensions of the 2-adic value.
If the Eisenstein generator is locally maximal at `2` (expressed by the conductor condition),
there is exactly one prime of the ring of integers above `2`. -/
theorem unique_minpoly_x
    {K : Type*} [Field K] [NumberField K]
    {n : ℕ} (hn : 0 < n) {alpha : 𝓞 K}
    (hmin : minpoly ℤ alpha = X ^ n - C (2 : ℤ))
    (hcond :
      (conductor ℤ alpha).comap (algebraMap ℤ (𝓞 K)) ⊔
        Ideal.span {(2 : ℤ)} = ⊤) :
    ∃! P : Ideal (𝓞 K),
      P.IsPrime ∧ P.LiesOver (Ideal.span {(2 : ℤ)}) := by
  let p : Ideal ℤ := Ideal.span {(2 : ℤ)}
  have hp : p.IsPrime :=
    (Ideal.span_singleton_prime (by norm_num : (2 : ℤ) ≠ 0)).mpr
      (Nat.prime_iff_prime_int.mp Nat.prime_two)
  have hp0 : p ≠ ⊥ := by
    dsimp [p]
    rw [Ideal.span_singleton_eq_bot]
    norm_num
  have heis : (minpoly ℤ alpha).IsEisensteinAt p := by
    rw [hmin]
    exact x_sub_eisenstein n hn
  have hram := eisenstein_conductor_coprime
    (A := ℤ) (B := 𝓞 K) hp hp0 alpha.isIntegral
    (by simpa [p] using hcond) heis
  let P : Ideal (𝓞 K) :=
    p.map (algebraMap ℤ (𝓞 K)) ⊔ Ideal.span {alpha}
  dsimp only at hram
  rcases hram with ⟨hPprime, _, _, hunique⟩
  have hPover : P.LiesOver p := by
    have hmap_le : p.map (algebraMap ℤ (𝓞 K)) ≤ P := le_sup_left
    have hp_le : p ≤ P.comap (algebraMap ℤ (𝓞 K)) :=
      Ideal.map_le_iff_le_comap.mp hmap_le
    have hcomapPrime : (P.comap (algebraMap ℤ (𝓞 K))).IsPrime :=
      hPprime.comap (algebraMap ℤ (𝓞 K))
    have hcomap : P.comap (algebraMap ℤ (𝓞 K)) = p := by
      exact ((hp.isMaximal hp0).eq_of_le hcomapPrime.ne_top hp_le).symm
    exact ⟨hcomap.symm⟩
  refine ⟨P, ⟨hPprime, hPover⟩, ?_⟩
  intro Q hQ
  exact hunique Q hQ.1 hQ.2

end

end Submission.NumberTheory.Milne
