import Mathlib.RepresentationTheory.Homological.GroupCohomology.Hilbert90
import Submission.ClassField.NormCorrespondence.SubgroupOpenClosed
import Submission.ClassField.UnramifiedCohom.CohomologicalReduction
import Submission.ClassField.LocalReciprocity.TateZeroQuotient
import Submission.ClassField.CrossedProducts.Multiplicative2Comparison
import Submission.ClassField.LocalBrauer.FiniteExtensionData
import Submission.ClassField.LocalBrauer.SpectralNormData
import Submission.ClassField.LocalBrauer.UnramifiedExtensionGalois
import Submission.ClassField.LocalBrauer.IntegralModelFrobenius
import Submission.ClassField.LocalBrauer.UnitH2
import Submission.NumberTheory.Locals.UnramifiedExtensions

