import Towers.ClassField.CyclotomicBrauer.LocalGlobal
import Towers.ClassField.CyclotomicBrauer.Cyclotomic
import Towers.ClassField.CyclotomicBrauer.LocalizationStatements
import Towers.ClassField.CyclotomicBrauer.CohomologicalInjection
import Towers.ClassField.CyclotomicBrauer.IdeleClassRepresentation
import Towers.ClassField.CyclotomicBrauer.FiniteBrauerLocalization
import Towers.ClassField.CyclotomicBrauer.LocalizationInjectivity
import Towers.ClassField.CyclotomicBrauer.DirectLimitInjection
import Towers.ClassField.CyclotomicBrauer.FinitePrime
import Towers.ClassField.CyclotomicBrauer.PlaceAlgEquiv
import Towers.ClassField.CyclotomicBrauer.RationalPrimesBelow
import Towers.ClassField.CyclotomicBrauer.CompletionDegree
import Towers.ClassField.CyclotomicBrauer.CompletionEquiv
import Towers.ClassField.CyclotomicBrauer.OrderGrowth
import Towers.ClassField.CyclotomicBrauer.RationalPrimeTransport
import Towers.ClassField.CyclotomicBrauer.CyclotomicLocalDegree
import Towers.ClassField.CyclotomicBrauer.OddPowerField
import Towers.ClassField.CyclotomicBrauer.TwoPowerField
import Towers.ClassField.CyclotomicBrauer.PrimePowerBlocks
import Towers.ClassField.CyclotomicBrauer.CompositumArithmetic
import Towers.ClassField.CyclotomicBrauer.CoprimeCompositum
import Towers.ClassField.CyclotomicBrauer.CyclotomicCompositum
import Towers.ClassField.CyclotomicBrauer.RationalCompositum
import Towers.ClassField.CyclotomicBrauer.RationalBaseChange
import Towers.ClassField.CyclotomicBrauer.TotallyComplex
import Towers.ClassField.CyclotomicBrauer.PlaceAlgEquiv

/-! # Chapter VII, Section 7: application to the Brauer group -/
