import Towers.ClassField.HasseNorm.QuadraticForms
import Towers.ClassField.HasseNorm.QuadraticNormValue
import Towers.ClassField.HasseNorm.LocalGlobalCriterion
import Towers.ClassField.HasseNorm.FiniteSupport
import Towers.ClassField.HasseNorm.LocalOpenness
import Towers.ClassField.HasseNorm.InfiniteBasicSubgroup
import Towers.ClassField.HasseNorm.IdeleOpenness
import Towers.ClassField.HasseNorm.ModulusUnitCofinality
import Towers.ClassField.HasseNorm.ModulusContainedSubgroup
import Towers.ClassField.HasseNorm.IdealMapBridge
import Towers.ClassField.HasseNorm.WeakApproximation
import Towers.ClassField.HasseNorm.IdeleIdealCompatibility
import Towers.ClassField.HasseNorm.GlobalComparison
import Towers.ClassField.HasseNorm.LocalComparison
import Towers.ClassField.HasseNorm.LocalOpenness
import Towers.ClassField.HasseNorm.LocalStabilizerComparison
import Towers.ClassField.HasseNorm.ULiftShapiro
import Towers.ClassField.HasseNorm.IdeleDecomposition
import Towers.ClassField.HasseNorm.ClassH1
import Towers.ClassField.HasseNorm.ResizedIdeleSequence
import Towers.ClassField.HasseNorm.Class1Vanishing
import Towers.ClassField.HasseNorm.LiftedH2
import Towers.ClassField.HasseNorm.IdeleCochainSupport
import Towers.ClassField.HasseNorm.H2Limit
import Towers.ClassField.HasseNorm.FinitePlaceBridge
import Towers.ClassField.HasseNorm.FiniteStageDecomposition
import Towers.ClassField.HasseNorm.FiniteStageCohomology
import Towers.ClassField.HasseNorm.FiniteRestrictedShapiro
import Towers.ClassField.HasseNorm.UnramifiedH2
import Towers.ClassField.HasseNorm.FiniteStageAssembly
import Towers.ClassField.HasseNorm.ExceptionalDirectSum
import Towers.ClassField.HasseNorm.FiniteDirectLimit
import Towers.ClassField.HasseNorm.InfiniteStageLimit
import Towers.ClassField.HasseNorm.InfiniteCompletionPlaces
import Towers.ClassField.HasseNorm.HCompletionProduct
import Towers.ClassField.HasseNorm.TateZeroSum
import Towers.ClassField.HasseNorm.QuadraticFormPlace
import Towers.ClassField.HasseNorm.RepresentationBaseChange
import Towers.ClassField.HasseNorm.LocalQuadraticConsequences

/-! # Chapter VIII, Section 3: local-global principles for norms and quadratic forms -/
