import Submission.ClassField.Reciprocity.ArtinMapStatements

/-!
# Chapter V, Section 5, Corollary 5.6

Finite abelian subextensions of a number field correspond bijectively to
open finite-index subgroups of its idèle class group by sending `L` to the
image of the idèle-class norm from `L`.  The correspondence reverses
inclusions, sends composita to intersections of norm groups, and sends field
intersections to the subgroup generated by the two norm groups.

This file states all clauses literally.  It also proves the bijection clause
formally from Theorem V.5.5 once the standard consequence of reciprocity—that
every finite abelian norm group is open and of finite index—is supplied.
-/

namespace Submission.CField.Recip

open NumberField Topology
open Submission.CField.LFTheory
open Submission.CField.Ideles

noncomputable section

universe u

variable {K : Type u} [Field K] [NumberField K]

local notation "𝓞K" => NumberField.RingOfIntegers K

/-- An open finite-index subgroup of the idèle class group. -/
structure OISubgro where
  carrier : Subgroup (IdeleClassGroup 𝓞K K)
  isOpen : IsOpen (carrier : Set (IdeleClassGroup 𝓞K K))
  finiteIndex : carrier.FiniteIndex

instance : Coe (OISubgro (K := K))
    (Subgroup (IdeleClassGroup 𝓞K K)) :=
  ⟨OISubgro.carrier⟩

@[ext]
theorem OISubgro.ext
    {H H' : OISubgro (K := K)}
    (h : H.carrier = H'.carrier) : H = H' := by
  cases H
  cases H'
  simp_all

/-- The standard openness and finite-index consequence of global
reciprocity, separated from the purely formal use of the existence theorem. -/
def IdeleGroupsIndex : Prop :=
  ∀ L : FASubext K,
    IsOpen (ideleClassSubgroup L : Set (IdeleClassGroup 𝓞K K)) ∧
      (ideleClassSubgroup L).FiniteIndex

/-- The norm-group correspondence, with its codomain restricted exactly as
in Corollary V.5.6. -/
def abelianIdeleNorm
    (hnorm : IdeleGroupsIndex (K := K)) :
    FASubext K →
      OISubgro (K := K) :=
  fun L =>
    { carrier := ideleClassSubgroup L
      isOpen := (hnorm L).1
      finiteIndex := (hnorm L).2 }

/-- The existence theorem and the fact that finite abelian norm groups have
the advertised topology imply the bijection clause of Corollary V.5.6. -/
theorem abelian_idele_bijective
    (hnorm : IdeleGroupsIndex (K := K))
    (hexistence : IdeleExistenceTheorem (K := K)) :
    Function.Bijective
      (abelianIdeleNorm hnorm) := by
  constructor
  · intro L M hLM
    have hnormEq : ideleClassSubgroup L =
        ideleClassSubgroup M :=
      congrArg OISubgro.carrier hLM
    obtain ⟨E, hE, hEunique⟩ :=
      hexistence (ideleClassSubgroup L) (hnorm L).1 (hnorm L).2
    exact (hEunique L rfl).trans
      (hEunique M hnormEq.symm).symm
  · intro H
    obtain ⟨L, hL, _⟩ :=
      hexistence H.carrier H.isOpen H.finiteIndex
    refine ⟨L, ?_⟩
    apply OISubgro.ext
    exact hL

/-- `M` is the compositum of `L₁` and `L₂` inside the fixed separable
closure used to model finite abelian extensions. -/
def IsGlobalCompositum
    (M L₁ L₂ : FASubext K) : Prop :=
  M.finiteIntermediateField.toIntermediateField =
    L₁.finiteIntermediateField.toIntermediateField ⊔
      L₂.finiteIntermediateField.toIntermediateField

/-- `M` is the intersection of `L₁` and `L₂` inside the fixed separable
closure. -/
def IsGlobalIntersection
    (M L₁ L₂ : FASubext K) : Prop :=
  M.finiteIntermediateField.toIntermediateField =
    L₁.finiteIntermediateField.toIntermediateField ⊓
      L₂.finiteIntermediateField.toIntermediateField

/-- The three order identities in Corollary V.5.6.  Composita and
intersections are expressed intrinsically inside the fixed separable
closure, so no choice of a representative extension is hidden. -/
def OrderRelations : Prop :=
  ∀ L₁ L₂ : FASubext K,
    (L₁.finiteIntermediateField.toIntermediateField ≤
        L₂.finiteIntermediateField.toIntermediateField ↔
      ideleClassSubgroup L₂ ≤ ideleClassSubgroup L₁) ∧
    (∃ M : FASubext K,
      IsGlobalCompositum M L₁ L₂ ∧
        ideleClassSubgroup M =
          ideleClassSubgroup L₁ ⊓ ideleClassSubgroup L₂) ∧
    ∃ M : FASubext K,
      IsGlobalIntersection M L₁ L₂ ∧
        ideleClassSubgroup M =
          ideleClassSubgroup L₁ ⊔ ideleClassSubgroup L₂

/-- Corollary V.5.6 follows from its topological norm-group consequence,
the existence theorem, and the three explicit order identities. -/
theorem existence_order_relations
    (hnorm : IdeleGroupsIndex (K := K))
    (hexistence : IdeleExistenceTheorem (K := K))
    (hrelations : OrderRelations (K := K)) :
    IdeleGroupsIndex (K := K) ∧
    OrderRelations (K := K) ∧
    ∀ hnorm : IdeleGroupsIndex (K := K),
      Function.Bijective (abelianIdeleNorm hnorm)
  := by
  refine ⟨hnorm, hrelations, ?_⟩
  intro hnorm'
  exact abelian_idele_bijective hnorm' hexistence

end

end Submission.CField.Recip
