import Mathlib.Analysis.Normed.Field.Approximation
import Mathlib.Analysis.Polynomial.CauchyBound
import Mathlib.Topology.MetricSpace.Infsep
import Towers.NumberTheory.Locals.KrasnerLemma

/-!
# Stability of irreducible polynomials under coefficient approximation

This file gives quantitative algebraic-Galois versions of Milne, Propositions
7.61 and 7.63.  Mathlib's continuity-of-roots estimate supplies nearby roots;
Krasner's lemma then identifies the generated intermediate fields.
-/

namespace Towers.NumberTheory.Milne

open IntermediateField

/-- The intermediate fields generated by the roots of `f` in `Ω`.  This is
the finite set that occurs on each side of Milne, Proposition 7.63. -/
def polynomialRootFields (K Ω : Type*) [Field K] [Field Ω] [Algebra K Ω]
    (f : Polynomial K) : Set (IntermediateField K Ω) :=
  {E | ∃ α ∈ f.aroots Ω, E = K⟮α⟯}

/-- A polynomial has only finitely many root-generated intermediate fields. -/
theorem polynomial_root_fields
    (K Ω : Type*) [Field K] [Field Ω] [Algebra K Ω]
    (f : Polynomial K) : (polynomialRootFields K Ω f).Finite := by
  classical
  exact ((f.aroots Ω).finite_toSet.image fun α ↦ K⟮α⟯).subset fun E ↦ by
    rintro ⟨α, hα, rfl⟩
    exact ⟨α, hα, rfl⟩

section AlgebraicCore

variable {K Ω : Type*} [Field K] [Field Ω] [Algebra K Ω]
  [FiniteDimensional K Ω] [IsGalois K Ω]

/-- A single Krasner-close pair of roots of equal-degree monic polynomials
forces equality of the generated fields and irreducibility of the second
polynomial.  This is the algebraic core of Milne, Proposition 7.61. -/
theorem adjoin_krasner_close
    (v : AbsoluteValue Ω ℝ) (hv : IsNonarchimedean v)
    (hinv : ∀ (σ : Ω ≃ₐ[K] Ω) (x : Ω), v (σ x) = v x)
    {f g : Polynomial K} (hfi : Irreducible f) (hfm : f.Monic)
    (hgm : g.Monic) (hdeg : g.natDegree = f.natDegree)
    {α β : Ω} (hα : α ∈ f.aroots Ω) (hβ : β ∈ g.aroots Ω)
    (hclose : ∀ σ : Ω ≃ₐ[K] Ω, σ α ≠ α → v (α - β) < v (σ α - α)) :
    Irreducible g ∧ K⟮α⟯ = K⟮β⟯ := by
  have hαeval : Polynomial.aeval α f = 0 := (Polynomial.mem_aroots.mp hα).2
  have hβeval : Polynomial.aeval β g = 0 := (Polynomial.mem_aroots.mp hβ).2
  have hαint : IsIntegral K α := ⟨f, hfm, hαeval⟩
  have hβint : IsIntegral K β := ⟨g, hgm, hβeval⟩
  have hfmin : f = minpoly K α :=
    minpoly.eq_of_irreducible_of_monic hfi hαeval hfm
  have hle : K⟮α⟯ ≤ K⟮β⟯ := krasner_le_adjoin v hv hinv hclose
  have hfinle : Module.finrank K K⟮α⟯ ≤ Module.finrank K K⟮β⟯ := by
    rw [← IntermediateField.finrank_eq_finrank_subalgebra,
      ← IntermediateField.finrank_eq_finrank_subalgebra]
    exact Submodule.finrank_mono
      (s := K⟮α⟯.toSubalgebra.toSubmodule) (t := K⟮β⟯.toSubalgebra.toSubmodule)
      (fun x hx ↦ hle hx)
  have hmindvd : minpoly K β ∣ g := minpoly.dvd K β hβeval
  have hmindege : (minpoly K β).natDegree ≤ g.natDegree :=
    Polynomial.natDegree_le_of_dvd hmindvd hgm.ne_zero
  have hfinα : Module.finrank K K⟮α⟯ = f.natDegree := by
    rw [IntermediateField.adjoin.finrank hαint, ← hfmin]
  have hfinβ : Module.finrank K K⟮β⟯ = (minpoly K β).natDegree :=
    IntermediateField.adjoin.finrank hβint
  have hdegree : (minpoly K β).natDegree = g.natDegree := by
    omega
  have hfields : K⟮α⟯ = K⟮β⟯ :=
    IntermediateField.eq_of_le_of_finrank_eq hle (by omega)
  have hgmin : g = minpoly K β :=
    Polynomial.eq_of_monic_of_dvd_of_natDegree_le
      (minpoly.monic hβint) hgm hmindvd hdegree.ge
  exact ⟨hgmin.symm ▸ minpoly.irreducible hβint, hfields⟩

end AlgebraicCore

section CompleteAlgebraicCore

variable {K Ω : Type*} [NontriviallyNormedField K] [CompleteSpace K]
  [IsUltrametricDist K] [NormedField Ω] [NormedAlgebra K Ω]
  [Algebra.IsAlgebraic K Ω]

/-- The complete-field algebraic core of Milne, Proposition 7.61, phrased in
terms of conjugate roots as in the classical Krasner lemma. -/
theorem krasner_close_complete
    {f g : Polynomial K} (hfi : Irreducible f) (hfsep : f.Separable)
    (hfm : f.Monic) (hgm : g.Monic) (hdeg : g.natDegree = f.natDegree)
    (hfs : (f.map (algebraMap K Ω)).Splits)
    {α β : Ω} (hα : α ∈ f.aroots Ω) (hβ : β ∈ g.aroots Ω)
    (hclose : ∀ α' : Ω, IsConjRoot K α α' → α ≠ α' →
      ‖α - β‖ < ‖α - α'‖) :
    Irreducible g ∧ K⟮α⟯ = K⟮β⟯ := by
  have hαeval : Polynomial.aeval α f = 0 := (Polynomial.mem_aroots.mp hα).2
  have hβeval : Polynomial.aeval β g = 0 := (Polynomial.mem_aroots.mp hβ).2
  have hαint : IsIntegral K α := ⟨f, hfm, hαeval⟩
  have hβint : IsIntegral K β := ⟨g, hgm, hβeval⟩
  have hfmin : f = minpoly K α :=
    minpoly.eq_of_irreducible_of_monic hfi hαeval hfm
  have hαsep : (minpoly K α).Separable := by
    simpa [← hfmin] using hfsep
  have hminsplits : ((minpoly K α).map (algebraMap K Ω)).Splits := by
    simpa [← hfmin] using hfs
  have hle : K⟮α⟯ ≤ K⟮β⟯ :=
    krasner_complete hαsep hminsplits hβint hclose
  letI : FiniteDimensional K K⟮β⟯ :=
    IntermediateField.adjoin.finiteDimensional hβint
  have hfinle : Module.finrank K K⟮α⟯ ≤ Module.finrank K K⟮β⟯ :=
    IntermediateField.finrank_le_of_le_right hle
  have hmindvd : minpoly K β ∣ g := minpoly.dvd K β hβeval
  have hmindege : (minpoly K β).natDegree ≤ g.natDegree :=
    Polynomial.natDegree_le_of_dvd hmindvd hgm.ne_zero
  have hfinα : Module.finrank K K⟮α⟯ = f.natDegree := by
    rw [IntermediateField.adjoin.finrank hαint, ← hfmin]
  have hfinβ : Module.finrank K K⟮β⟯ = (minpoly K β).natDegree :=
    IntermediateField.adjoin.finrank hβint
  have hdegree : (minpoly K β).natDegree = g.natDegree := by
    omega
  have hfields : K⟮α⟯ = K⟮β⟯ :=
    IntermediateField.eq_of_le_of_finrank_eq hle (by omega)
  have hgmin : g = minpoly K β :=
    Polynomial.eq_of_monic_of_dvd_of_natDegree_le
      (minpoly.monic hβint) hgm hmindvd hdegree.ge
  exact ⟨hgmin.symm ▸ minpoly.irreducible hβint, hfields⟩

end CompleteAlgebraicCore

section AlgebraicGaloisCore

variable {K Ω : Type*} [NontriviallyNormedField K] [CompleteSpace K]
  [IsUltrametricDist K]
  [NormedField Ω] [NormedAlgebra K Ω] [Algebra.IsAlgebraic K Ω]
  [IsGalois K Ω]

/-- The algebraic-Galois version of the core of Milne, Proposition 7.61.
Unlike `adjoin_krasner_close`, this theorem applies in
an infinite algebraic closure: Krasner's lemma is reduced internally to the
finite normal closure of the two roots, while the two simple extensions remain
finite-dimensional because their generators are integral. -/
theorem irreducible_krasner_close
    (hna : IsNonarchimedean (norm : Ω → ℝ))
    {f g : Polynomial K} (hfi : Irreducible f) (hfm : f.Monic)
    (hgm : g.Monic) (hdeg : g.natDegree = f.natDegree)
    {α β : Ω} (hα : α ∈ f.aroots Ω) (hβ : β ∈ g.aroots Ω)
    (hclose : ∀ σ : Ω ≃ₐ[K] Ω, σ α ≠ α → ‖α - β‖ < ‖σ α - α‖) :
    Irreducible g ∧ K⟮α⟯ = K⟮β⟯ := by
  have hαeval : Polynomial.aeval α f = 0 := (Polynomial.mem_aroots.mp hα).2
  have hβeval : Polynomial.aeval β g = 0 := (Polynomial.mem_aroots.mp hβ).2
  have hαint : IsIntegral K α := ⟨f, hfm, hαeval⟩
  have hβint : IsIntegral K β := ⟨g, hgm, hβeval⟩
  have hfmin : f = minpoly K α :=
    minpoly.eq_of_irreducible_of_monic hfi hαeval hfm
  have hle : K⟮α⟯ ≤ K⟮β⟯ := krasner_adjoin_galois hna hclose
  letI : FiniteDimensional K K⟮β⟯ :=
    IntermediateField.adjoin.finiteDimensional hβint
  have hfinle : Module.finrank K K⟮α⟯ ≤ Module.finrank K K⟮β⟯ :=
    IntermediateField.finrank_le_of_le_right hle
  have hmindvd : minpoly K β ∣ g := minpoly.dvd K β hβeval
  have hmindege : (minpoly K β).natDegree ≤ g.natDegree :=
    Polynomial.natDegree_le_of_dvd hmindvd hgm.ne_zero
  have hfinα : Module.finrank K K⟮α⟯ = f.natDegree := by
    rw [IntermediateField.adjoin.finrank hαint, ← hfmin]
  have hfinβ : Module.finrank K K⟮β⟯ = (minpoly K β).natDegree :=
    IntermediateField.adjoin.finrank hβint
  have hdegree : (minpoly K β).natDegree = g.natDegree := by
    omega
  have hfields : K⟮α⟯ = K⟮β⟯ :=
    IntermediateField.eq_of_le_of_finrank_eq hle (by omega)
  have hgmin : g = minpoly K β :=
    Polynomial.eq_of_monic_of_dvd_of_natDegree_le
      (minpoly.monic hβint) hgm hmindvd hdegree.ge
  exact ⟨hgmin.symm ▸ minpoly.irreducible hβint, hfields⟩

end AlgebraicGaloisCore

section ExistentialStability

variable {K Ω : Type*} [NontriviallyNormedField K] [CompleteSpace K]
  [IsUltrametricDist K]
  [NormedField Ω] [NormedAlgebra K Ω] [Algebra.IsAlgebraic K Ω]
  [IsGalois K Ω] [IsAlgClosed Ω]

/-- Milne, Proposition 7.63, in its qualitative neighborhood form.

For every monic irreducible polynomial `f`, there is a positive coefficient
radius such that every monic polynomial of the same degree in that radius is
irreducible and has exactly the same embedded root fields in the chosen
algebraic closure. -/
theorem radius_irreducible_fields
    (hna : IsNonarchimedean (norm : Ω → ℝ))
    {f : Polynomial K} (hfi : Irreducible f) (hfm : f.Monic) :
    ∃ ε : ℝ, 0 < ε ∧ ∀ {g : Polynomial K}, g.Monic →
      g.natDegree = f.natDegree →
      (∀ i : ℕ, ‖g.coeff i - f.coeff i‖ < ε) →
      Irreducible g ∧ polynomialRootFields K Ω f = polynomialRootFields K Ω g := by
  classical
  have hfdeg0 : f.natDegree ≠ 0 := hfi.natDegree_pos.ne'
  have hfs : (f.map (algebraMap K Ω)).Splits := IsAlgClosed.splits _
  obtain ⟨α, hα⟩ := Multiset.exists_mem_of_ne_zero
    (hfs.roots_ne_zero (by simpa [hfm.natDegree_map] using hfdeg0))
  have hαeval : Polynomial.aeval α f = 0 := (Polynomial.mem_aroots.mp hα).2
  have hαint : IsIntegral K α := ⟨f, hfm, hαeval⟩
  have hfmin : f = minpoly K α :=
    minpoly.eq_of_irreducible_of_monic hfi hαeval hfm
  let S : Finset Ω := {x ∈ (f.rootSet Ω).toFinset | x ≠ α}
  let δ : ℝ := if hS : S.Nonempty then
      Finset.min' (S.image fun x ↦ ‖α - x‖) (Finset.image_nonempty.mpr hS)
    else 1
  have hδle : ∀ α' ∈ f.aroots Ω, α' ≠ α → δ ≤ ‖α - α'‖ := by
    intro α' hα' hne
    have hα'rootSet : α' ∈ f.rootSet Ω := by
      exact Polynomial.mem_rootSet.mpr ⟨hfi.ne_zero, (Polynomial.mem_aroots.mp hα').2⟩
    have hα'S : α' ∈ S := by
      simp only [Finset.mem_filter, Set.mem_toFinset, S]
      exact ⟨hα'rootSet, hne⟩
    have hS : S.Nonempty := ⟨α', hα'S⟩
    simp only [hS, ↓reduceDIte, δ]
    exact Finset.min'_le _ _ (Finset.mem_image_of_mem _ hα'S)
  have hδpos : 0 < δ := by
    by_cases hS : S.Nonempty <;> simp only [hS, ↓reduceDIte, δ]
    · simp only [Finset.lt_min'_iff, Finset.mem_image, forall_exists_index,
        and_imp, forall_apply_eq_imp_iff₂]
      intro α' hα'S
      have hne : α' ≠ α := by
        have hmem := hα'S
        simp only [Finset.mem_filter, Set.mem_toFinset, S] at hmem
        exact hmem.2
      rw [norm_pos_iff, sub_ne_zero]
      exact hne.symm
    · positivity
  let ε : ℝ := (δ / max ‖α‖ 1) ^ f.natDegree / (f.natDegree + 1)
  have hε : 0 < ε := by
    dsimp [ε]
    positivity
  refine ⟨ε, hε, ?_⟩
  intro g hgm hdeg hcoeff
  have hgs : (g.map (algebraMap K Ω)).Splits := IsAlgClosed.splits _
  obtain ⟨β, hβ, hαβ⟩ :=
    Polynomial.exists_aroots_norm_sub_lt_of_norm_coeff_sub_lt
      (f := f) (g := g) hε hαeval hfm hgm hdeg hcoeff hgs
  have hαβδ : ‖α - β‖ < δ := by
    dsimp [ε] at hαβ
    rw [← Real.rpow_natCast, ← mul_comm_div, div_self, one_mul,
      ← Real.rpow_mul (div_pos hδpos (by positivity)).le, mul_inv_cancel₀] at hαβ
    · simpa [mul_assoc, div_mul_cancel₀ _
        (by positivity : (max ‖α‖ 1) > 0).ne'] using hαβ
    · exact_mod_cast hfdeg0
    · positivity
  have hclose : ∀ σ : Ω ≃ₐ[K] Ω, σ α ≠ α → ‖α - β‖ < ‖σ α - α‖ := by
    intro σ hσαne
    have hσα : σ α ∈ f.aroots Ω := Polynomial.mem_aroots.mpr ⟨hfi.ne_zero, by
      rw [Polynomial.aeval_algHom_apply, hαeval, map_zero]⟩
    calc
      ‖α - β‖ < δ := hαβδ
      _ ≤ ‖α - σ α‖ := hδle (σ α) hσα hσαne
      _ = ‖σ α - α‖ := norm_sub_rev _ _
  have hcore := irreducible_krasner_close
    hna hfi hfm hgm hdeg hα hβ hclose
  refine ⟨hcore.1, Set.ext ?_⟩
  intro E
  constructor
  · rintro ⟨a, ha, rfl⟩
    have haeval : Polynomial.aeval a f = 0 := (Polynomial.mem_aroots.mp ha).2
    have hconj : IsConjRoot K α a := by
      rw [isConjRoot_iff_aeval_eq_zero hαint, ← hfmin]
      exact haeval
    obtain ⟨σ, hσα⟩ := hconj.symm.exists_algEquiv
    let b : Ω := σ β
    have hb : b ∈ g.aroots Ω := Polynomial.mem_aroots.mpr ⟨hcore.1.ne_zero, by
      dsimp [b]
      rw [Polynomial.aeval_algHom_apply, (Polynomial.mem_aroots.mp hβ).2, map_zero]⟩
    refine ⟨b, hb, ?_⟩
    have hmapped := congrArg
      (fun F : IntermediateField K Ω ↦ F.map σ.toAlgHom) hcore.2
    simpa [IntermediateField.adjoin_map, b, hσα] using hmapped
  · rintro ⟨b, hb, rfl⟩
    have hβeval : Polynomial.aeval β g = 0 := (Polynomial.mem_aroots.mp hβ).2
    have hβint : IsIntegral K β := ⟨g, hgm, hβeval⟩
    have hconj : IsConjRoot K β b := by
      rw [isConjRoot_iff_aeval_eq_zero hβint]
      have hgmin : g = minpoly K β :=
        minpoly.eq_of_irreducible_of_monic hcore.1 hβeval hgm
      rw [← hgmin]
      exact (Polynomial.mem_aroots.mp hb).2
    obtain ⟨σ, hσβ⟩ := hconj.symm.exists_algEquiv
    let a : Ω := σ α
    have ha : a ∈ f.aroots Ω := Polynomial.mem_aroots.mpr ⟨hfi.ne_zero, by
      dsimp [a]
      rw [Polynomial.aeval_algHom_apply, hαeval, map_zero]⟩
    refine ⟨a, ha, ?_⟩
    have hmapped := congrArg
      (fun F : IntermediateField K Ω ↦ F.map σ.toAlgHom) hcore.2
    simpa [IntermediateField.adjoin_map, a, hσβ] using hmapped.symm

end ExistentialStability

section QuantitativeStability

variable {K Ω : Type*} [NontriviallyNormedField K] [CompleteSpace K]
  [IsUltrametricDist K]
  [NormedField Ω] [NormedAlgebra K Ω] [Algebra.IsAlgebraic K Ω]
  [IsGalois K Ω]

/-- The root-displacement scale in Mathlib's coefficientwise continuity
estimate, after replacing the norm of the root by a common bound `R`. -/
noncomputable def rootApproximationScale (n : ℕ) (ε R : ℝ) : ℝ :=
  ((n + 1) * ε) ^ (n : ℝ)⁻¹ * R

/-- A common Cauchy bound for roots of two polynomials after extending
scalars to `Ω`. -/
noncomputable def commonCauchyBound (Ω : Type*) [NormedField Ω]
    [NormedAlgebra K Ω] (f g : Polynomial K) : ℝ :=
  max ((f.map (algebraMap K Ω)).cauchyBound : ℝ)
    ((g.map (algebraMap K Ω)).cauchyBound : ℝ)

omit [CompleteSpace K] [Algebra.IsAlgebraic K Ω] [IsGalois K Ω] in
private theorem cauchy_max_close
    {f g : Polynomial K} (hfm : f.Monic) (hgm : g.Monic)
    (hdeg : g.natDegree = f.natDegree)
    (hcoeff : ∀ i : ℕ, ‖g.coeff i - f.coeff i‖ < 1) :
    (g.map (algebraMap K Ω)).cauchyBound ≤
      max (f.map (algebraMap K Ω)).cauchyBound 2 := by
  rw [Polynomial.cauchyBound, Polynomial.cauchyBound,
    (hgm.map _).leadingCoeff, (hfm.map _).leadingCoeff]
  simp only [nnnorm_one, div_one, hgm.natDegree_map, hfm.natDegree_map,
    hdeg]
  have hsup :
      Finset.sup (Finset.range f.natDegree)
          (‖(g.map (algebraMap K Ω)).coeff ·‖₊) ≤
        max (Finset.sup (Finset.range f.natDegree)
          (‖(f.map (algebraMap K Ω)).coeff ·‖₊)) 1 := by
    apply Finset.sup_le
    intro i hi
    have hle : ‖g.coeff i‖ ≤ max ‖f.coeff i‖ 1 := by
      calc
        ‖g.coeff i‖ = ‖(g.coeff i - f.coeff i) + f.coeff i‖ := by
          congr 1
          abel
        _ ≤ max ‖g.coeff i - f.coeff i‖ ‖f.coeff i‖ :=
          IsUltrametricDist.norm_add_le_max _ _
        _ ≤ max 1 ‖f.coeff i‖ :=
          max_le_max (hcoeff i).le le_rfl
        _ = max ‖f.coeff i‖ 1 := max_comm _ _
    have hle' : ‖g.coeff i‖₊ ≤ max ‖f.coeff i‖₊ 1 := by
      exact_mod_cast hle
    calc
      ‖(g.map (algebraMap K Ω)).coeff i‖₊ = ‖g.coeff i‖₊ := by
        simp
      _ ≤ max ‖f.coeff i‖₊ 1 := hle'
      _ = max ‖(f.map (algebraMap K Ω)).coeff i‖₊ 1 := by simp
      _ ≤ max (Finset.sup (Finset.range f.natDegree)
          (‖(f.map (algebraMap K Ω)).coeff ·‖₊)) 1 :=
        max_le_max
          (Finset.le_sup (f := fun x ↦ ‖(f.map (algebraMap K Ω)).coeff x‖₊) hi)
          le_rfl
  calc
    _ ≤ max (Finset.sup (Finset.range f.natDegree)
        (‖(f.map (algebraMap K Ω)).coeff ·‖₊)) 1 + 1 :=
      by simpa [add_comm] using add_le_add_right hsup 1
    _ = max
        (Finset.sup (Finset.range f.natDegree)
          (‖(f.map (algebraMap K Ω)).coeff ·‖₊) + 1) 2 := by
      rw [← max_add_add_right]
      norm_num

omit [CompleteSpace K] [IsUltrametricDist K] [Algebra.IsAlgebraic K Ω] [IsGalois K Ω] in
private theorem max_common_cauchy
    {f g : Polynomial K} (hfm : f.Monic) (hgm : g.Monic) {x : Ω}
    (hx : x ∈ f.aroots Ω ∨ x ∈ g.aroots Ω) :
    max ‖x‖ 1 ≤ commonCauchyBound Ω f g := by
  rcases hx with hxf | hxg
  · have hxroot : (f.map (algebraMap K Ω)).IsRoot x :=
      (Polynomial.mem_roots (hfm.map _).ne_zero).mp hxf
    have hxnorm : ‖x‖ < ((f.map (algebraMap K Ω)).cauchyBound : ℝ) := by
      exact_mod_cast hxroot.norm_lt_cauchyBound (hfm.map _).ne_zero
    have hone : 1 ≤ ((f.map (algebraMap K Ω)).cauchyBound : ℝ) := by
      exact_mod_cast Polynomial.one_le_cauchyBound (f.map (algebraMap K Ω))
    exact (max_le hxnorm.le hone).trans (le_max_left _ _)
  · have hxroot : (g.map (algebraMap K Ω)).IsRoot x :=
      (Polynomial.mem_roots (hgm.map _).ne_zero).mp hxg
    have hxnorm : ‖x‖ < ((g.map (algebraMap K Ω)).cauchyBound : ℝ) := by
      exact_mod_cast hxroot.norm_lt_cauchyBound (hgm.map _).ne_zero
    have hone : 1 ≤ ((g.map (algebraMap K Ω)).cauchyBound : ℝ) := by
      exact_mod_cast Polynomial.one_le_cauchyBound (g.map (algebraMap K Ω))
    exact (max_le hxnorm.le hone).trans (le_max_right _ _)

/-- Quantitative algebraic-Galois versions of Milne, Propositions 7.61 and 7.63.

The common root bound `R` and the separation hypothesis turn Mathlib's
coefficientwise continuity estimate into disjoint Krasner neighborhoods.  The
conclusions say that `g` is irreducible, every root of `g` belongs to a unique
root of `f` and generates the same intermediate field, and the sets of fields
generated by roots of the two polynomials agree. -/
theorem stability_coeff_close
    (hna : IsNonarchimedean (norm : Ω → ℝ))
    {f g : Polynomial K} (hfi : Irreducible f) (hfm : f.Monic)
    (hgm : g.Monic) (hdeg : g.natDegree = f.natDegree)
    (hfs : (f.map (algebraMap K Ω)).Splits)
    (hgs : (g.map (algebraMap K Ω)).Splits)
    {ε R : ℝ} (hε : 0 < ε)
    (hcoeff : ∀ i : ℕ, ‖g.coeff i - f.coeff i‖ < ε)
    (hrootBound : ∀ x : Ω, x ∈ f.aroots Ω ∨ x ∈ g.aroots Ω → max ‖x‖ 1 ≤ R)
    (hsep : ∀ α ∈ f.aroots Ω, ∀ α' ∈ f.aroots Ω, α' ≠ α →
      rootApproximationScale f.natDegree ε R < ‖α' - α‖) :
    Irreducible g ∧
      (∀ β ∈ g.aroots Ω, ∃! α : Ω,
        α ∈ f.aroots Ω ∧
          ‖α - β‖ < rootApproximationScale f.natDegree ε R ∧
          K⟮α⟯ = K⟮β⟯) ∧
      {E : IntermediateField K Ω | ∃ α ∈ f.aroots Ω, E = K⟮α⟯} =
        {E : IntermediateField K Ω | ∃ β ∈ g.aroots Ω, E = K⟮β⟯} := by
  let A : ℝ := ((f.natDegree + 1) * ε) ^ (f.natDegree : ℝ)⁻¹
  let δ : ℝ := rootApproximationScale f.natDegree ε R
  have hA : 0 ≤ A := by
    dsimp [A]
    positivity
  have hδ : δ = A * R := by rfl
  have associateβ : ∀ β ∈ g.aroots Ω, ∃ α ∈ f.aroots Ω,
      ‖α - β‖ < δ ∧ Irreducible g ∧ K⟮α⟯ = K⟮β⟯ := by
    intro β hβ
    have hβeval : Polynomial.aeval β g = 0 := (Polynomial.mem_aroots.mp hβ).2
    obtain ⟨α, hα, hαβ⟩ :=
      Polynomial.exists_aroots_norm_sub_lt_of_norm_coeff_sub_lt
        (f := g) (g := f) hε hβeval hgm hfm hdeg.symm
        (by
          intro i
          simpa [norm_sub_rev] using hcoeff i)
        hfs
    have hαβ' : ‖α - β‖ < A * max ‖β‖ 1 := by
      simpa [A, hdeg, norm_sub_rev] using hαβ
    have hcloseδ : ‖α - β‖ < δ := by
      rw [hδ]
      exact hαβ'.trans_le (mul_le_mul_of_nonneg_left (hrootBound β (Or.inr hβ)) hA)
    have hkclose : ∀ σ : Ω ≃ₐ[K] Ω, σ α ≠ α → ‖α - β‖ < ‖σ α - α‖ := by
      intro σ hσαne
      have hσα : σ α ∈ f.aroots Ω := Polynomial.mem_aroots.mpr ⟨hfi.ne_zero, by
        rw [Polynomial.aeval_algHom_apply, (Polynomial.mem_aroots.mp hα).2, map_zero]⟩
      exact hcloseδ.trans (hsep α hα (σ α) hσα hσαne)
    have hcore := irreducible_krasner_close
      hna hfi hfm hgm hdeg hα hβ hkclose
    exact ⟨α, hα, hcloseδ, hcore.1, hcore.2⟩
  have hirr : Irreducible g := by
    have hgne : g.natDegree ≠ 0 := by
      rw [hdeg]
      exact hfi.natDegree_pos.ne'
    obtain ⟨β, hβ⟩ := Multiset.exists_mem_of_ne_zero
      (hgs.roots_ne_zero (by simpa using hgne))
    obtain ⟨-, -, -, hg, -⟩ := associateβ β hβ
    exact hg
  have hmatching : ∀ β ∈ g.aroots Ω, ∃! α : Ω,
      α ∈ f.aroots Ω ∧ ‖α - β‖ < δ ∧ K⟮α⟯ = K⟮β⟯ := by
    intro β hβ
    obtain ⟨α, hα, hαβ, -, hfields⟩ := associateβ β hβ
    refine ⟨α, ⟨hα, hαβ, hfields⟩, ?_⟩
    intro α' hα'
    by_contra hne
    have hlarge : δ < ‖α' - α‖ := hsep α hα α' hα'.1 hne
    have htri : ‖α - α'‖ ≤ max ‖α - β‖ ‖β - α'‖ := by
      calc
        ‖α - α'‖ = ‖(α - β) + (β - α')‖ := by congr 1; ring
        _ ≤ max ‖α - β‖ ‖β - α'‖ := hna _ _
    have hsmall : ‖α' - α‖ < δ := by
      rw [norm_sub_rev]
      exact htri.trans_lt (max_lt hαβ (by simpa [norm_sub_rev] using hα'.2.1))
    exact lt_asymm hlarge hsmall
  refine ⟨hirr, ?_, ?_⟩
  · simpa [δ] using hmatching
  · ext E
    constructor
    · rintro ⟨α, hα, rfl⟩
      have hαeval : Polynomial.aeval α f = 0 := (Polynomial.mem_aroots.mp hα).2
      obtain ⟨β, hβ, hαβ⟩ :=
        Polynomial.exists_aroots_norm_sub_lt_of_norm_coeff_sub_lt
          (f := f) (g := g) hε hαeval hfm hgm hdeg hcoeff hgs
      have hαβ' : ‖α - β‖ < A * max ‖α‖ 1 := by
        simpa [A] using hαβ
      have hcloseδ : ‖α - β‖ < δ := by
        rw [hδ]
        exact hαβ'.trans_le (mul_le_mul_of_nonneg_left (hrootBound α (Or.inl hα)) hA)
      have hkclose : ∀ σ : Ω ≃ₐ[K] Ω, σ α ≠ α → ‖α - β‖ < ‖σ α - α‖ := by
        intro σ hσαne
        have hσα : σ α ∈ f.aroots Ω := Polynomial.mem_aroots.mpr ⟨hfi.ne_zero, by
          rw [Polynomial.aeval_algHom_apply, hαeval, map_zero]⟩
        exact hcloseδ.trans (hsep α hα (σ α) hσα hσαne)
      have hcore := irreducible_krasner_close
        hna hfi hfm hgm hdeg hα hβ hkclose
      exact ⟨β, hβ, hcore.2⟩
    · rintro ⟨β, hβ, rfl⟩
      obtain ⟨α, hα, -, -, hfields⟩ := associateβ β hβ
      exact ⟨α, hα, hfields.symm⟩

/-- A Cauchy-bound specialization of `stability_coeff_close`.
This is the directly checkable quantitative form of Milne, Propositions 7.61
and 7.63: the only size bound appearing in the separation hypothesis is the
standard Cauchy bound computed from the two polynomials. -/
theorem stability_close_cauchy
    (hna : IsNonarchimedean (norm : Ω → ℝ))
    {f g : Polynomial K} (hfi : Irreducible f) (hfm : f.Monic)
    (hgm : g.Monic) (hdeg : g.natDegree = f.natDegree)
    (hfs : (f.map (algebraMap K Ω)).Splits)
    (hgs : (g.map (algebraMap K Ω)).Splits)
    {ε : ℝ} (hε : 0 < ε)
    (hcoeff : ∀ i : ℕ, ‖g.coeff i - f.coeff i‖ < ε)
    (hsep : ∀ α ∈ f.aroots Ω, ∀ α' ∈ f.aroots Ω, α' ≠ α →
      rootApproximationScale f.natDegree ε
        (commonCauchyBound Ω f g) < ‖α' - α‖) :
    Irreducible g ∧
      (∀ β ∈ g.aroots Ω, ∃! α : Ω,
        α ∈ f.aroots Ω ∧
          ‖α - β‖ < rootApproximationScale f.natDegree ε
            (commonCauchyBound Ω f g) ∧
          K⟮α⟯ = K⟮β⟯) ∧
      {E : IntermediateField K Ω | ∃ α ∈ f.aroots Ω, E = K⟮α⟯} =
        {E : IntermediateField K Ω | ∃ β ∈ g.aroots Ω, E = K⟮β⟯} := by
  exact stability_coeff_close hna hfi hfm hgm hdeg hfs hgs hε hcoeff
    (fun _ hx ↦ max_common_cauchy (Ω := Ω) hfm hgm hx) hsep

/-- Milne's phrase "sufficiently close" in Propositions 7.61 and 7.63, made
uniform under a common root bound.  For a fixed irreducible polynomial, the
finite set of its roots has a positive minimum separation (unless it has only
one root, when the separation condition is vacuous).  Choosing the
coefficient radius from that separation makes the quantitative stability
theorem apply to every polynomial whose roots satisfy the same bound. -/
theorem stability_radius_bound
    (hna : IsNonarchimedean (norm : Ω → ℝ))
    {f : Polynomial K} (hfi : Irreducible f) (hfm : f.Monic)
    (hfs : (f.map (algebraMap K Ω)).Splits)
    {R : ℝ} (hR : 0 < R)
    (hfrootBound : ∀ x : Ω, x ∈ f.aroots Ω → max ‖x‖ 1 ≤ R) :
    ∃ ε : ℝ, 0 < ε ∧
      ∀ (g : Polynomial K), g.Monic → g.natDegree = f.natDegree →
        (g.map (algebraMap K Ω)).Splits →
        (∀ i : ℕ, ‖g.coeff i - f.coeff i‖ < ε) →
        (∀ x : Ω, x ∈ g.aroots Ω → max ‖x‖ 1 ≤ R) →
        Irreducible g ∧
          (∀ β ∈ g.aroots Ω, ∃! α : Ω,
            α ∈ f.aroots Ω ∧
              ‖α - β‖ < rootApproximationScale f.natDegree ε R ∧
              K⟮α⟯ = K⟮β⟯) ∧
          {E : IntermediateField K Ω | ∃ α ∈ f.aroots Ω, E = K⟮α⟯} =
            {E : IntermediateField K Ω | ∃ β ∈ g.aroots Ω, E = K⟮β⟯} := by
  classical
  let roots : Set Ω := {x | x ∈ f.aroots Ω}
  have hrootsFinite : roots.Finite := by
    exact (f.aroots Ω).finite_toSet
  let δ : ℝ := if roots.Nontrivial then roots.infsep else 1
  have hδ : 0 < δ := by
    by_cases hr : roots.Nontrivial
    · simp only [δ, hr, if_pos]
      exact (hrootsFinite.infsep_pos_iff_nontrivial).2 hr
    · simp [δ, hr]
  have hδle : ∀ α ∈ f.aroots Ω, ∀ α' ∈ f.aroots Ω, α' ≠ α →
      δ ≤ ‖α' - α‖ := by
    intro α hα α' hα' hne
    have hαroots : α ∈ roots := by
      change α ∈ f.aroots Ω
      exact hα
    have hα'roots : α' ∈ roots := by
      change α' ∈ f.aroots Ω
      exact hα'
    have hr : roots.Nontrivial := ⟨α, hαroots, α', hα'roots, hne.symm⟩
    dsimp only [δ]
    rw [if_pos hr]
    calc
      roots.infsep ≤ dist α α' :=
        Set.infsep_le_dist_of_mem hαroots hα'roots hne.symm
      _ = ‖α' - α‖ := by rw [dist_eq_norm, norm_sub_rev]
  have hn : f.natDegree ≠ 0 := hfi.natDegree_pos.ne'
  let ε : ℝ := ((δ / 2) / R) ^ f.natDegree / (f.natDegree + 1)
  have hε : 0 < ε := by
    dsimp [ε]
    positivity
  have hscale : rootApproximationScale f.natDegree ε R = δ / 2 := by
    dsimp only [ε]
    rw [rootApproximationScale, ← Real.rpow_natCast, ← mul_comm_div,
      div_self, one_mul,
      ← Real.rpow_mul (div_pos (half_pos hδ) hR).le, mul_inv_cancel₀]
    · simpa using div_mul_cancel₀ (δ / 2) hR.ne'
    · exact_mod_cast hn
    · positivity
  refine ⟨ε, hε, ?_⟩
  intro g hgm hdeg hgs hcoeff hgrootBound
  apply stability_coeff_close hna hfi hfm hgm hdeg hfs hgs hε hcoeff
  · intro x hx
    exact hx.elim (hfrootBound x) (hgrootBound x)
  · intro α hα α' hα' hne
    rw [hscale]
    exact (half_lt_self hδ).trans_le (hδle α hα α' hα' hne)

/-- Milne, Propositions 7.61 and 7.63, in their qualitative
"sufficiently close" form.  The coefficient radius and the root radius
depend only on `f`.  Every nearby monic polynomial of the same degree is
irreducible, each of its roots belongs to exactly one root of `f`, paired
roots generate the same intermediate field, and the two sets of root fields
coincide. -/
theorem radius_unique_fields
    [IsAlgClosed Ω]
    (hna : IsNonarchimedean (norm : Ω → ℝ))
    {f : Polynomial K} (hfi : Irreducible f) (hfm : f.Monic) :
    ∃ ε δ : ℝ, 0 < ε ∧ 0 < δ ∧
      ∀ (g : Polynomial K), g.Monic → g.natDegree = f.natDegree →
        (∀ i : ℕ, ‖g.coeff i - f.coeff i‖ < ε) →
        Irreducible g ∧
          (∀ β ∈ g.aroots Ω, ∃! α : Ω,
            α ∈ f.aroots Ω ∧ ‖α - β‖ < δ ∧ K⟮α⟯ = K⟮β⟯) ∧
          polynomialRootFields K Ω f = polynomialRootFields K Ω g := by
  let R : ℝ := max ((f.map (algebraMap K Ω)).cauchyBound : ℝ) 2
  have hR : 0 < R := by
    exact lt_of_lt_of_le (by norm_num) (le_max_right _ _)
  have hfrootBound : ∀ x : Ω, x ∈ f.aroots Ω → max ‖x‖ 1 ≤ R := by
    intro x hx
    have hxroot : (f.map (algebraMap K Ω)).IsRoot x :=
      (Polynomial.mem_roots (hfm.map _).ne_zero).mp hx
    have hxnorm : ‖x‖ < ((f.map (algebraMap K Ω)).cauchyBound : ℝ) := by
      exact_mod_cast hxroot.norm_lt_cauchyBound (hfm.map _).ne_zero
    have hone : 1 ≤ ((f.map (algebraMap K Ω)).cauchyBound : ℝ) := by
      exact_mod_cast Polynomial.one_le_cauchyBound (f.map (algebraMap K Ω))
    exact (max_le hxnorm.le hone).trans (le_max_left _ _)
  have hfs : (f.map (algebraMap K Ω)).Splits := IsAlgClosed.splits _
  obtain ⟨ε₀, hε₀, hstable⟩ :=
    stability_radius_bound
      hna hfi hfm hfs hR hfrootBound
  let ε : ℝ := min ε₀ 1
  let δ : ℝ := rootApproximationScale f.natDegree ε₀ R
  have hε : 0 < ε := lt_min hε₀ zero_lt_one
  have hδ : 0 < δ := by
    dsimp [δ, rootApproximationScale]
    positivity
  refine ⟨ε, δ, hε, hδ, ?_⟩
  intro g hgm hdeg hcoeff
  have hcoeff₀ : ∀ i : ℕ, ‖g.coeff i - f.coeff i‖ < ε₀ := by
    intro i
    exact (hcoeff i).trans_le (min_le_left _ _)
  have hcoeffOne : ∀ i : ℕ, ‖g.coeff i - f.coeff i‖ < 1 := by
    intro i
    exact (hcoeff i).trans_le (min_le_right _ _)
  have hgs : (g.map (algebraMap K Ω)).Splits := IsAlgClosed.splits _
  have hgCauchy :
      ((g.map (algebraMap K Ω)).cauchyBound : ℝ) ≤ R := by
    exact_mod_cast cauchy_max_close
      (K := K) (Ω := Ω) hfm hgm hdeg hcoeffOne
  have hgrootBound : ∀ x : Ω, x ∈ g.aroots Ω → max ‖x‖ 1 ≤ R := by
    intro x hx
    have hxroot : (g.map (algebraMap K Ω)).IsRoot x :=
      (Polynomial.mem_roots (hgm.map _).ne_zero).mp hx
    have hxnorm : ‖x‖ < ((g.map (algebraMap K Ω)).cauchyBound : ℝ) := by
      exact_mod_cast hxroot.norm_lt_cauchyBound (hgm.map _).ne_zero
    have hone : 1 ≤ ((g.map (algebraMap K Ω)).cauchyBound : ℝ) := by
      exact_mod_cast Polynomial.one_le_cauchyBound (g.map (algebraMap K Ω))
    exact (max_le hxnorm.le hone).trans hgCauchy
  simpa [δ, polynomialRootFields] using
    hstable g hgm hdeg hgs hcoeff₀ hgrootBound

end QuantitativeStability

section CharacteristicZeroAlgebraicClosure

variable {K Ω : Type*} [NontriviallyNormedField K] [CompleteSpace K]
  [IsUltrametricDist K] [CharZero K]
  [NormedField Ω] [NormedAlgebra K Ω] [Algebra.IsAlgebraic K Ω]
  [IsAlgClosed Ω]

/-- Milne, Propositions 7.61 and 7.63, in the characteristic-zero
algebraic-closure setting used in the book.

The algebraic closure is automa normal over `K`, and characteristic
zero supplies separability.  Thus the Galois hypothesis used by the
quantitative proof is constructed internally rather than exported. -/
theorem radius_fields_char
    (hna : IsNonarchimedean (norm : Ω → ℝ))
    {f : Polynomial K} (hfi : Irreducible f) (hfm : f.Monic) :
    ∃ ε δ : ℝ, 0 < ε ∧ 0 < δ ∧
      ∀ (g : Polynomial K), g.Monic → g.natDegree = f.natDegree →
        (∀ i : ℕ, ‖g.coeff i - f.coeff i‖ < ε) →
        Irreducible g ∧
          (∀ β ∈ g.aroots Ω, ∃! α : Ω,
            α ∈ f.aroots Ω ∧ ‖α - β‖ < δ ∧ K⟮α⟯ = K⟮β⟯) ∧
          polynomialRootFields K Ω f = polynomialRootFields K Ω g := by
  letI : Normal K Ω := normal_iff.mpr fun x ↦
    ⟨Algebra.IsAlgebraic.isIntegral.isIntegral x, IsAlgClosed.splits _⟩
  letI : IsGalois K Ω := IsGalois.mk
  exact radius_unique_fields hna hfi hfm

end CharacteristicZeroAlgebraicClosure

end Towers.NumberTheory.Milne
