import Towers.NumberTheory.Locals.TeichmullerLifts
import Towers.NumberTheory.Locals.UnramifiedExtensions
import Mathlib.FieldTheory.SplittingField.IsSplittingField


/-!
# Splitting by Teichmuller representatives

The Teichmuller representatives of a finite residue field give all roots of
`X ^ #k - X` in the fraction field of a Henselian local domain.  This is the
root-count input to the splitting-field assertion in Milne, Example 7.54.
-/

namespace Towers.NumberTheory.Milne

noncomputable section

open Polynomial IsLocalRing

variable (U F : Type*) [CommRing U] [HenselianLocalRing U]
  [Field F] [Algebra U F] [IsFractionRing U F]
  [Finite (ResidueField U)]

/-- All Teichmuller representatives lie in the fraction field, so
`X ^ #k - X` splits there. -/
theorem splits_x_fraction :
    (Polynomial.X ^ Nat.card (ResidueField U) - Polynomial.X : F[X]).Splits := by
  classical
  letI : Fintype (ResidueField U) := Fintype.ofFinite (ResidueField U)
  let N := Fintype.card (ResidueField U)
  let P : F[X] := Polynomial.X ^ N - Polynomial.X
  have hN : 1 < N := Fintype.one_lt_card
  have hPdegree : P.natDegree = N :=
    FiniteField.X_pow_card_sub_X_natDegree_eq F hN
  have hPne : P ≠ 0 := ne_zero_of_natDegree_gt <| by
    rw [hPdegree]
    exact Nat.zero_lt_of_lt hN
  let rootEmbedding : ResidueField U ↪ {x // x ∈ P.roots.toFinset} :=
    { toFun := fun x =>
        ⟨algebraMap U F (teichmullerLift U x), by
          rw [Multiset.mem_toFinset, Polynomial.mem_roots hPne]
          simpa [P] using
            (teichmuller_lift_root U x).map (f := algebraMap U F)⟩
      inj' := by
        intro x y hxy
        have ht : teichmullerLift U x = teichmullerLift U y :=
          IsFractionRing.injective U F (congrArg Subtype.val hxy)
        calc
          x = residue U (teichmullerLift U x) := (residue_teichmullerLift U x).symm
          _ = residue U (teichmullerLift U y) := congrArg (residue U) ht
          _ = y := residue_teichmullerLift U y }
  have hNleFinset : N ≤ P.roots.toFinset.card := by
    simpa [N] using Fintype.card_le_of_injective rootEmbedding rootEmbedding.injective
  have hNleRoots : N ≤ P.roots.card :=
    hNleFinset.trans (Multiset.toFinset_card_le P.roots)
  have hrootsLeN : P.roots.card ≤ N := by
    rw [← hPdegree]
    exact Polynomial.card_roots' P
  have hsplit : P.Splits :=
    Polynomial.splits_iff_card_roots.mpr <| by
      rw [hPdegree]
      exact Nat.le_antisymm hrootsLeN hNleRoots
  simpa [P, N, Nat.card_eq_fintype_card] using hsplit

section SplittingField

variable (A U K F : Type*)
  [CommRing A] [IsDomain A] [HenselianLocalRing A]
  [CommRing U] [IsDomain U] [HenselianLocalRing U]
  [Algebra A U] [IsLocalHom (algebraMap A U)]
  [Module.Finite A U] [Algebra.IsIntegral A U]
  [Algebra.FormallyUnramified A U]
  [Finite (ResidueField A)] [Finite (ResidueField U)]
  [Field K] [Algebra A K] [IsFractionRing A K]
  [Field F] [Algebra U F] [IsFractionRing U F]
  [Algebra K F] [Algebra A F]
  [IsScalarTower A U F] [IsScalarTower A K F]

noncomputable local instance : Fintype (ResidueField U) :=
  Fintype.ofFinite (ResidueField U)

include A

omit [IsDomain A] [IsDomain U] [Finite (ResidueField A)] [IsFractionRing A K] in
/-- The fraction field of a finite unramified local algebra is generated by
the Teichmuller lift of a primitive residue element. -/
theorem teichmuller_fraction_generator :
    ∃ x : ResidueField U,
      IntermediateField.adjoin K
        {algebraMap U F (teichmullerLift U x)} = ⊤ := by
  obtain ⟨x, hx⟩ :=
    Field.exists_primitive_element_of_finite_top
      (ResidueField A) (ResidueField U)
  have hxgen : Algebra.adjoin (ResidueField A) {x} = ⊤ :=
    Algebra.adjoin_eq_top_of_primitive_element
      (Algebra.IsAlgebraic.isAlgebraic x) hx
  let w : U := teichmullerLift U x
  let W : Subalgebra A U := Algebra.adjoin A {w}
  have hresidue : residueImage A U W = residueImage A U ⊤ := by
    rw [show W = Algebra.adjoin A {w} from rfl,
      residue_adjoin_singleton, show w = teichmullerLift U x from rfl,
      residue_teichmullerLift, hxgen, residueImage_top]
  letI : Module.Finite A (⊤ : Subalgebra A U) :=
    Module.Finite.equiv
      (Subalgebra.topEquiv (R := A) (A := U)).symm.toLinearEquiv
  letI : Algebra.FormallyUnramified A (⊤ : Subalgebra A U) :=
    Algebra.FormallyUnramified.of_equiv
      (Subalgebra.topEquiv (R := A) (A := U)).symm
  have hW : W = ⊤ :=
    formally_unramified_image
      A U W ⊤ le_top hresidue
  let E : IntermediateField K F :=
    IntermediateField.adjoin K {algebraMap U F w}
  have hUle : ∀ u : U, algebraMap U F u ∈ E := by
    intro u
    let V : Subalgebra A U :=
      (E.toSubalgebra.restrictScalars A).comap
        (IsScalarTower.toAlgHom A U F)
    have hwV : w ∈ V := by
      change algebraMap U F w ∈ E
      exact IntermediateField.subset_adjoin K {algebraMap U F w}
        (Set.mem_singleton _)
    have hWV : W ≤ V := by
      apply Algebra.adjoin_le
      simpa [W] using hwV
    have huW : u ∈ W := by rw [hW]; trivial
    exact hWV huW
  have hE : E = ⊤ := by
    apply top_unique
    intro y _
    obtain ⟨u, v, hv, huv⟩ := IsFractionRing.div_surjective U y
    rw [← huv]
    exact E.div_mem (hUle u) (hUle v)
  refine ⟨x, ?_⟩
  simpa [E, w] using hE

omit [IsDomain A] [IsDomain U] [Finite (ResidueField A)] [IsFractionRing A K] in
/-- Milne, Example 7.54: a finite unramified local extension is the
splitting field of `X ^ #k_U - X`.  Splitting comes from all Teichmuller
representatives, while one primitive representative generates the field. -/
theorem splitting_x_fraction :
    Polynomial.IsSplittingField K F
      (Polynomial.X ^ Nat.card (ResidueField U) - Polynomial.X) := by
  let P : K[X] := Polynomial.X ^ Nat.card (ResidueField U) - Polynomial.X
  have hsplits : (P.map (algebraMap K F)).Splits := by
    simpa [P] using splits_x_fraction U F
  rw [isSplittingField_iff_intermediateField]
  refine ⟨hsplits, ?_⟩
  obtain ⟨x, hxgen⟩ :=
    teichmuller_fraction_generator A U K F
  let w : U := teichmullerLift U x
  let z : F := algebraMap U F w
  have hP0 : P ≠ 0 := by
    have hcard : 1 < Nat.card (ResidueField U) := Finite.one_lt_card
    have hdegree : P.natDegree = Nat.card (ResidueField U) :=
      FiniteField.X_pow_card_sub_X_natDegree_eq K hcard
    exact ne_zero_of_natDegree_gt (hdegree ▸ Nat.zero_lt_of_lt hcard)
  have hzroot : z ∈ P.rootSet F := by
    apply Polynomial.mem_rootSet.mpr
    refine ⟨hP0, ?_⟩
    have hwroot :
        (((Polynomial.X ^ Fintype.card (ResidueField U) - Polynomial.X : U[X]).map
          (algebraMap U F)).IsRoot
            (algebraMap U F (teichmullerLift U x))) :=
      (teichmuller_lift_root U x).map
    simpa [P, w, z, Polynomial.IsRoot.def, aeval_def] using hwroot
  apply top_unique
  rw [← hxgen]
  exact IntermediateField.adjoin.mono K {z} (P.rootSet F)
    (Set.singleton_subset_iff.mpr hzroot)

end SplittingField

end

end Towers.NumberTheory.Milne
