import
  Towers.Group.Zassenhaus.SelectedProfileAlgebra

/-!
# Operational erased-shape programs for retained scheduler corrections

The cutoff-full collector already records its retained corrections in the
literal recursive insertion order.  This file erases concrete decorated terms
to Hall shapes while retaining that recursive program:

* an empty trace;
* concatenation of collection branches;
* recursive left corrections, one retained crossing, and recursive right
  corrections.

The selected endpoint correction-shape trace is therefore the output of a
finite operational program.  A profiled realization of those programs is
enough to recover the endpoint interpolation package used by the
power-coordinate pipeline.

This file is intentionally not imported by the existing collection proof.
-/

noncomputable section

namespace Towers
namespace TCTex


namespace
  RTProgra

open
  HACoeff
open
  CFCollec.DFTerm
open
  CRLayer
open
  CRInv
open
  CRInv.DFTerm
open
  FIProf
open
  OCPartit
open
  SEAlg

/-- Erase a concrete retained-correction inventory to its literal Hall-shape
trace. -/
def erasedShapeTrace
    {M N K : ℕ}
    (corrections : List (DFTerm M N K)) :
    List (CWord HPAtom) :=
  corrections.map fun term =>
    term.family.recipe.erasedShape

/--
Finite recursive program generated by the operational cutoff-full scheduler
after concrete decorated terms have been erased to Hall shapes.
-/
inductive ESProgra where
  | empty
  | append
      (left right : ESProgra)
  | retained
      (left : ESProgra)
      (shape : CWord HPAtom)
      (right : ESProgra)

namespace ESProgra

/-- Literal ordered Hall-shape trace emitted by one operational program. -/
def trace :
    ESProgra →
      List (CWord HPAtom)
  | .empty =>
      []
  | .append left right =>
      left.trace ++ right.trace
  | .retained left shape right =>
      left.trace ++ [shape] ++ right.trace

@[simp]
lemma trace_empty :
    ESProgra.empty.trace = [] := by
  rfl

@[simp]
lemma trace_append
    (left right : ESProgra) :
    (ESProgra.append left right).trace =
      left.trace ++ right.trace := by
  rfl

@[simp]
lemma trace_retained
    (left right : ESProgra)
    (shape : CWord HPAtom) :
    (ESProgra.retained left shape right).trace =
      left.trace ++ [shape] ++ right.trace := by
  rfl

end ESProgra

/--
Every traced cutoff insertion produces an erased-shape program with exactly
its literal retained-correction trace.
-/
lemma program_inserts_corrections
    {M N K n leftWeight rightWeight : ℕ}
    {L R corrections : List (DFTerm M N K)}
    {A : DFTerm M N K}
    (hinsert :
      CICorrec
        n leftWeight rightWeight L A R corrections) :
    ∃ program : ESProgra,
      program.trace =
        erasedShapeTrace corrections := by
  induction hinsert with
  | nil A =>
      exact ⟨.empty, rfl⟩
  | append P B A hBA =>
      exact ⟨.empty, rfl⟩
  | retained P B A hAB hweight hcorrection hinsert
      ihcorrection ihinsert =>
      rcases ihcorrection with ⟨left, hleft⟩
      rcases ihinsert with ⟨right, hright⟩
      refine
        ⟨.retained left (B.correction A).family.recipe.erasedShape right, ?_⟩
      simp [erasedShapeTrace, hleft, hright]
  | residual P B A hAB hweight hinsert ihinsert =>
      exact ihinsert

/--
Every traced cutoff collection produces an erased-shape program with exactly
its literal retained-correction trace.
-/
lemma program_collects_corrections
    {M N K n leftWeight rightWeight : ℕ}
    {L R corrections : List (DFTerm M N K)}
    (hcollect :
      CCCorrec
        n leftWeight rightWeight L R corrections) :
    ∃ program : ESProgra,
      program.trace =
        erasedShapeTrace corrections := by
  induction hcollect with
  | nil =>
      exact ⟨.empty, rfl⟩
  | retained P A hweight hcollect hinsert ihcollect =>
      rcases ihcollect with ⟨collectProgram, hcollectProgram⟩
      rcases
        program_inserts_corrections
          hinsert with
        ⟨insertProgram, hinsertProgram⟩
      refine ⟨.append collectProgram insertProgram, ?_⟩
      simp [erasedShapeTrace, hcollectProgram,
        hinsertProgram]
  | residual P A hweight hcollect ihcollect =>
      exact ihcollect

/--
One recursively structured erased-shape program selected from the actual
cutoff-full endpoint scheduler.
-/
noncomputable def endpointErasedProgram
    {n leftWeight rightWeight : ℕ}
    (layer : NRLayer n leftWeight rightWeight)
    (M N : ℕ) :
    ESProgra :=
  Classical.choose
    (program_collects_corrections
      (EndpointCorrectionInventory.family_collects_corrections
        (endpointCorrectionInventory layer M N)))

/--
The selected endpoint program emits exactly the literal correction-shape trace
used by the erased-shape profile compiler.
-/
lemma endpoint_erased_program
    {n leftWeight rightWeight : ℕ}
    (layer : NRLayer n leftWeight rightWeight)
    (M N : ℕ) :
    (endpointErasedProgram layer M N).trace =
      selectedErasedShape layer M N := by
  simpa [
    endpointErasedProgram,
    selectedErasedShape,
    erasedShapeTrace,
    DFTerm.erased_shape_family] using
      (Classical.choose_spec
        (program_collects_corrections
          (EndpointCorrectionInventory.family_collects_corrections
            (endpointCorrectionInventory layer M N))))

/--
A symbolic realization of the operational endpoint programs: one profiled
erased-shape family whose trace agrees with the concrete scheduler program at
every pair of natural input multiplicities.
-/
structure EPRealiz
    {n leftWeight rightWeight : ℕ}
    (layer : NRLayer n leftWeight rightWeight) where
  family :
    PEFam
  trace_eq :
    ∀ M N,
      family.trace M N =
        (endpointErasedProgram layer M N).trace

namespace EPRealiz

/--
A profiled realization of the operational endpoint programs is a profiled
realization of the selected correction-shape trace.
-/
noncomputable def selectedErasedProfiled
    {n leftWeight rightWeight : ℕ}
    {layer : NRLayer n leftWeight rightWeight}
    (realization :
      EPRealiz
        layer) :
    SEProfil layer where
  family :=
    realization.family
  trace_eq M N :=
    (realization.trace_eq M N).trans
      (endpoint_erased_program layer M N)

/--
Together with raw-source profiles, a symbolic realization of the operational
endpoint programs compiles directly to selected endpoint shape-fiber
profiles.
-/
noncomputable def
    selectedFullFiber
    {n leftWeight rightWeight : ℕ}
    {layer : NRLayer n leftWeight rightWeight}
    (realization :
      EPRealiz
        layer)
    (hleftWeight : 0 < leftWeight)
    (hrightWeight : 0 < rightWeight)
    (raw :
      RFProf
        n leftWeight rightWeight hleftWeight hrightWeight) :=
  realization.selectedErasedProfiled
    |>.selectedFullFiber
      hleftWeight hrightWeight raw

/--
Together with raw-source profiles, a symbolic realization of the operational
endpoint programs compiles directly to the interpolation package consumed by
the power-coordinate pipeline.
-/
noncomputable def fiberProfileInterpolation
    {n leftWeight rightWeight : ℕ}
    {layer : NRLayer n leftWeight rightWeight}
    (realization :
      EPRealiz
        layer)
    (hleftWeight : 0 < leftWeight)
    (hrightWeight : 0 < rightWeight)
    (raw :
      RFProf
        n leftWeight rightWeight hleftWeight hrightWeight) :=
  realization.selectedFullFiber
    hleftWeight hrightWeight raw
      |>.fiberProfileInterpolation

end EPRealiz

end RTProgra
end TCTex
end Towers
