import Mathlib

/-!
# Milne, Algebraic Number Theory, Examples 3.1 and Proposition 3.2

We record the localization of `ℤ` at a prime as a discrete valuation ring and the
noetherian, integrally closed, unique-nonzero-prime characterization of DVRs.
-/

namespace Submission.NumberTheory.Milne

/-- The opening characterization of discrete valuation rings: a domain is a DVR exactly
when it is a PID with a unique nonzero prime ideal. -/
theorem discrete_pid_nonzero
    (R : Type*) [CommRing R] [IsDomain R] :
    IsDiscreteValuationRing R ↔
      IsPrincipalIdealRing R ∧
        ∃! P : Ideal R, P ≠ ⊥ ∧ P.IsPrime := by
  exact IsDiscreteValuationRing.iff_pid_with_one_nonzero_prime R

/-- Proposition 3.2: a domain is a DVR exactly when it is noetherian, integrally closed,
and has a unique nonzero prime ideal. -/
theorem discrete_noetherian_integrally
    (R : Type*) [CommRing R] [IsDomain R] :
    IsDiscreteValuationRing R ↔
      IsNoetherianRing R ∧ IsIntegrallyClosed R ∧
        ∃! P : Ideal R, P ≠ ⊥ ∧ P.IsPrime := by
  constructor
  · intro hDVR
    letI : IsDiscreteValuationRing R := hDVR
    exact ⟨inferInstance, inferInstance,
      (IsDiscreteValuationRing.iff_pid_with_one_nonzero_prime R).mp hDVR |>.2⟩
  · rintro ⟨hNoetherian, hIntegrallyClosed, hPrime⟩
    letI : IsNoetherianRing R := hNoetherian
    letI : IsIntegrallyClosed R := hIntegrallyClosed
    letI : IsLocalRing R := IsLocalRing.of_unique_nonzero_prime hPrime
    have hNotField : ¬IsField R := by
      obtain ⟨P, ⟨hP0, hP⟩, -⟩ := hPrime
      exact Ring.not_isField_iff_exists_prime.mpr ⟨P, hP0, hP⟩
    apply ((IsDiscreteValuationRing.TFAE R hNotField).out 0 3).mpr
    exact And.intro hIntegrallyClosed hPrime

/-- The normal form for a nonzero element of a DVR, including both uniqueness assertions
made after Example 3.1: once a prime element `π` is fixed, every nonzero `x` is uniquely a
unit times a power of `π`. -/
theorem dvr_unit_unique
    (A : Type*) [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    {π x : A} (hπ : Irreducible π) (hx : x ≠ 0) :
    ∃ n : ℕ, ∃ u : Aˣ,
      x = (u : A) * π ^ n ∧
        ∀ (n' : ℕ) (u' : Aˣ),
          x = (u' : A) * π ^ n' → n' = n ∧ u' = u := by
  obtain ⟨n, u, hxu⟩ :=
    IsDiscreteValuationRing.eq_unit_mul_pow_irreducible hx hπ
  refine ⟨n, u, hxu, ?_⟩
  intro n' u' hxu'
  have heq : (u' : A) * π ^ n' = (u : A) * π ^ n := hxu'.symm.trans hxu
  have hn : n' = n :=
    IsDiscreteValuationRing.unit_mul_pow_congr_pow hπ hπ u' u n' n heq
  subst n'
  exact ⟨rfl, IsDiscreteValuationRing.unit_mul_pow_congr_unit hπ u' u n n heq⟩

/-- In the normal form of a nonzero DVR element, the exponent is positive exactly when
the element is not a unit. -/
theorem dvr_pos_not
    (A : Type*) [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    {π x : A} (hπ : Irreducible π) (u : Aˣ) (n : ℕ)
    (hx : x = (u : A) * π ^ n) :
    0 < n ↔ ¬IsUnit x := by
  rw [hx, IsUnit.mul_iff]
  simp only [Units.isUnit, true_and]
  constructor
  · intro hn hunit
    exact hπ.not_isUnit ((isUnit_pow_iff hn.ne').mp hunit)
  · intro hunit
    exact Nat.pos_of_ne_zero fun hn ↦ hunit (by simp [hn])

/-- Every nonzero ideal in a DVR is generated by a unique power of any fixed prime
element. -/
theorem dvr_span_unique
    (A : Type*) [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    {π : A} (hπ : Irreducible π) (I : Ideal A) (hI : I ≠ ⊥) :
    ∃! n : ℕ, I = Ideal.span {π ^ n} := by
  obtain ⟨n, hn⟩ :=
    IsDiscreteValuationRing.ideal_eq_span_pow_irreducible hI hπ
  refine ⟨n, hn, ?_⟩
  intro n' hn'
  have hassociated : Associated (π ^ n') (π ^ n) :=
    Ideal.span_singleton_eq_span_singleton.mp (hn'.symm.trans hn)
  obtain ⟨u, hu⟩ := hassociated
  apply IsDiscreteValuationRing.unit_mul_pow_congr_pow hπ hπ u 1 n' n
  simpa [mul_comm] using hu

/-- Equivalently, every nonzero ideal of a DVR is a unique power of its maximal ideal. -/
theorem dvr_maximal_unique
    (A : Type*) [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    {π : A} (hπ : Irreducible π) (I : Ideal A) (hI : I ≠ ⊥) :
    ∃! n : ℕ, I = IsLocalRing.maximalIdeal A ^ n := by
  simpa [hπ.maximalIdeal_eq, Ideal.span_singleton_pow] using
    dvr_span_unique A hπ I hI

/-- The prime ideal `(p)` of `ℤ`. -/
abbrev integerPrimeIdeal (p : ℕ) : Ideal ℤ := Ideal.span {(p : ℤ)}

theorem integer_prime_ideal {p : ℕ} (hp : p.Prime) :
    (integerPrimeIdeal p).IsPrime := by
  rw [integerPrimeIdeal, Ideal.span_singleton_prime]
  · exact (Nat.prime_iff_prime_int).mp hp
  · exact_mod_cast hp.ne_zero

local instance integerPrimeIdeal.instIsPrime (p : ℕ) [hp : Fact p.Prime] :
    (integerPrimeIdeal p).IsPrime :=
  integer_prime_ideal hp.out

/-- Example 3.1: the localization `ℤ_(p)` is a discrete valuation ring. -/
theorem localization_discrete_valuation
    (p : ℕ) [hp : Fact p.Prime] :
    IsDiscreteValuationRing (Localization.AtPrime (integerPrimeIdeal p)) := by
  exact IsLocalization.AtPrime.isDiscreteValuationRing_of_dedekind_domain
    ℤ (P := integerPrimeIdeal p) (by simp [integerPrimeIdeal, hp.out.ne_zero])
    (Localization.AtPrime (integerPrimeIdeal p))

/-- In `ℤ_(p)`, the maximal ideal is generated by the image of `p`. -/
theorem integer_localization_maximal
    (p : ℕ) [hp : Fact p.Prime] :
    IsLocalRing.maximalIdeal (Localization.AtPrime (integerPrimeIdeal p)) =
      Ideal.span
        ({algebraMap ℤ (Localization.AtPrime (integerPrimeIdeal p)) p} :
          Set (Localization.AtPrime (integerPrimeIdeal p))) := by
  rw [← Localization.AtPrime.map_eq_maximalIdeal
    (I := integerPrimeIdeal p)]
  simp [integerPrimeIdeal, Ideal.map_span]

/-- The image of `p` is a prime element of the DVR `ℤ_(p)`. -/
theorem integer_irreducible_localization
    (p : ℕ) [hp : Fact p.Prime] :
    Irreducible
      (algebraMap ℤ (Localization.AtPrime (integerPrimeIdeal p)) p) := by
  letI : IsDiscreteValuationRing
      (Localization.AtPrime (integerPrimeIdeal p)) :=
    localization_discrete_valuation p
  rw [IsDiscreteValuationRing.irreducible_iff_uniformizer]
  exact integer_localization_maximal p

/-- The localization `ℤ_(p)` has a unique nonzero prime ideal. -/
theorem localization_unique_nonzero
    (p : ℕ) [hp : Fact p.Prime] :
    ∃! P : Ideal (Localization.AtPrime (integerPrimeIdeal p)),
      P ≠ ⊥ ∧ P.IsPrime := by
  letI : IsDiscreteValuationRing
      (Localization.AtPrime (integerPrimeIdeal p)) :=
    localization_discrete_valuation p
  exact (IsDiscreteValuationRing.iff_pid_with_one_nonzero_prime
    (Localization.AtPrime (integerPrimeIdeal p))).mp inferInstance |>.2

/-- A fraction in `ℤ_(p)` is a unit exactly when its numerator is outside `(p)`; its
denominator is outside `(p)` by construction. -/
theorem integer_localization_fraction
    (p : ℕ) [hp : Fact p.Prime] (x : ℤ)
    (y : (integerPrimeIdeal p).primeCompl) :
    IsUnit
        (IsLocalization.mk'
          (Localization.AtPrime (integerPrimeIdeal p)) x y) ↔
      x ∈ (integerPrimeIdeal p).primeCompl := by
  exact IsLocalization.AtPrime.isUnit_mk'_iff
    (Localization.AtPrime (integerPrimeIdeal p)) (integerPrimeIdeal p) x y

/-- Every prime element of `ℤ_(p)` is associated to the image of `p`. -/
theorem locali_irred_assoc
    (p : ℕ) [hp : Fact p.Prime]
    {x : Localization.AtPrime (integerPrimeIdeal p)} (hx : Irreducible x) :
    Associated x
      (algebraMap ℤ (Localization.AtPrime (integerPrimeIdeal p)) p) := by
  letI : IsDiscreteValuationRing
      (Localization.AtPrime (integerPrimeIdeal p)) :=
    localization_discrete_valuation p
  exact IsDiscreteValuationRing.associated_of_irreducible
    (Localization.AtPrime (integerPrimeIdeal p)) hx
    (integer_irreducible_localization p)

/-- Every nonzero element of `ℤ_(p)` is a unit times a power of `p`. -/
theorem integer_localization_prime
    (p : ℕ) [hp : Fact p.Prime]
    (x : Localization.AtPrime (integerPrimeIdeal p)) (hx : x ≠ 0) :
    ∃ n : ℕ, ∃ u : (Localization.AtPrime (integerPrimeIdeal p))ˣ,
      x = (u : Localization.AtPrime (integerPrimeIdeal p)) *
        algebraMap ℤ (Localization.AtPrime (integerPrimeIdeal p)) p ^ n := by
  letI : IsDiscreteValuationRing
      (Localization.AtPrime (integerPrimeIdeal p)) :=
    localization_discrete_valuation p
  exact IsDiscreteValuationRing.eq_unit_mul_pow_irreducible hx
    (integer_irreducible_localization p)

/-- The exponent in the unit-times-a-power-of-`p` expression is unique. -/
theorem integer_localization_unique
    (p : ℕ) [hp : Fact p.Prime]
    (u v : (Localization.AtPrime (integerPrimeIdeal p))ˣ) (m n : ℕ)
    (h : (u : Localization.AtPrime (integerPrimeIdeal p)) *
        algebraMap ℤ (Localization.AtPrime (integerPrimeIdeal p)) p ^ m =
      (v : Localization.AtPrime (integerPrimeIdeal p)) *
        algebraMap ℤ (Localization.AtPrime (integerPrimeIdeal p)) p ^ n) :
    m = n := by
  letI : IsDiscreteValuationRing
      (Localization.AtPrime (integerPrimeIdeal p)) :=
    localization_discrete_valuation p
  exact IsDiscreteValuationRing.unit_mul_pow_congr_pow
    (integer_irreducible_localization p)
    (integer_irreducible_localization p) u v m n h

/-- Every nonzero ideal of `ℤ_(p)` is a power of its maximal ideal. -/
theorem integer_localization_pow
    (p : ℕ) [hp : Fact p.Prime]
    (I : Ideal (Localization.AtPrime (integerPrimeIdeal p))) (hI : I ≠ ⊥) :
    ∃ n : ℕ, I =
      IsLocalRing.maximalIdeal (Localization.AtPrime (integerPrimeIdeal p)) ^ n := by
  letI : IsDiscreteValuationRing
      (Localization.AtPrime (integerPrimeIdeal p)) :=
    localization_discrete_valuation p
  obtain ⟨n, hn⟩ := IsDiscreteValuationRing.ideal_eq_span_pow_irreducible hI
    (integer_irreducible_localization p)
  refine ⟨n, ?_⟩
  rw [hn, integer_localization_maximal,
    Ideal.span_singleton_pow]

end Submission.NumberTheory.Milne
