import Submission.Group.FinitePRelator.RelatorKernelFactorization


open scoped Topology

noncomputable section

namespace Submission
namespace FPQuotie

open PCShadow
open PRFact

universe u

/--
The quotient by the closed normal subgroup topologically generated by a
displayed relator family.
-/
abbrev completedRelatorQuotient
    {F : Type u}
    [Group F]
    [TopologicalSpace F]
    [IsTopologicalGroup F]
    {ι : Type*}
    (relator : ι → F) :=
  F ⧸ completedRelationSubgroup relator

variable
    {p : ℕ}
    {F P : Type u}
    [Group F]
    [TopologicalSpace F]
    [IsTopologicalGroup F]
    [Group P]
    {ι : Type*}
    (relator : ι → F)

/-- The canonical map to the completed relator quotient. -/
def quotientMap :
    F →* completedRelatorQuotient relator :=
  QuotientGroup.mk' (completedRelationSubgroup relator)

lemma quotientMap_surjective :
    Function.Surjective (quotientMap relator) := by
  exact QuotientGroup.mk'_surjective (completedRelationSubgroup relator)

lemma quotientMap_continuous :
    Continuous (quotientMap relator) := by
  change Continuous (QuotientGroup.mk : F → completedRelatorQuotient relator)
  exact QuotientGroup.continuous_mk

@[simp] lemma ker_quotientMap :
    (quotientMap relator).ker = completedRelationSubgroup relator := by
  exact QuotientGroup.ker_mk' (completedRelationSubgroup relator)

@[simp] lemma quotient_relator_one
    (i : ι) :
    quotientMap relator (relator i) = 1 := by
  exact
    (QuotientGroup.eq_one_iff (relator i)).mpr
      (relator_completed_subgroup relator i)

/--
Descend a continuous homomorphism killing the displayed relators to the
completed relator quotient.
-/
def descendMap
    [TopologicalSpace P]
    [T1Space P]
    (α : F →* P)
    (hα : Continuous α)
    (hkill : KillsRelators relator α) :
    completedRelatorQuotient relator →* P :=
  QuotientGroup.lift
    (completedRelationSubgroup relator)
    α
    (completed_kills_relators relator α hα hkill)

lemma descend_comp
    [TopologicalSpace P]
    [T1Space P]
    (α : F →* P)
    (hα : Continuous α)
    (hkill : KillsRelators relator α) :
    (descendMap relator α hα hkill).comp (quotientMap relator) = α := by
  exact QuotientGroup.lift_comp_mk'
    (completedRelationSubgroup relator)
    α
    (completed_kills_relators relator α hα hkill)

lemma descendMap_continuous
    [TopologicalSpace P]
    [T1Space P]
    (α : F →* P)
    (hα : Continuous α)
    (hkill : KillsRelators relator α) :
    Continuous (descendMap relator α hα hkill) := by
  apply
    (QuotientGroup.isQuotientMap_mk
      (completedRelationSubgroup relator)).continuous_iff.mpr
  change Continuous (fun x : F => descendMap relator α hα hkill (quotientMap relator x))
  simpa [Function.comp_def] using hα

lemma descendMap_unique
    [TopologicalSpace P]
    [T1Space P]
    (α : F →* P)
    (hα : Continuous α)
    (hkill : KillsRelators relator α)
    (β : completedRelatorQuotient relator →* P)
    (hβ : β.comp (quotientMap relator) = α) :
    β = descendMap relator α hα hkill := by
  apply MonoidHom.ext
  intro y
  rcases quotientMap_surjective relator y with ⟨x, rfl⟩
  have hβx := congrArg (fun φ : F →* P => φ x) hβ
  have hdescx := congrArg
    (fun φ : F →* P => φ x)
    (descend_comp relator α hα hkill)
  change β (quotientMap relator x) = α x at hβx
  change descendMap relator α hα hkill (quotientMap relator x) = α x at hdescx
  exact hβx.trans hdescx.symm

lemma uniquely_kills_relators
    [TopologicalSpace P]
    [T1Space P]
    (α : F →* P)
    (hα : Continuous α)
    (hkill : KillsRelators relator α) :
    FactorsUniquelyThrough (quotientMap relator) α := by
  apply factors_uniquely_ker
    (quotientMap relator) α (quotientMap_surjective relator)
  rw [ker_quotientMap]
  exact completed_kills_relators relator α hα hkill

namespace RShadow

variable
    {p : ℕ}
    {F : Type u}
    [Group F]
    [TopologicalSpace F]
    [IsTopologicalGroup F]
    {ι : Type*}
    {relator : ι → F}

/--
Descend a finite relator-killing `p`-shadow to a finite `p`-shadow of the
completed relator quotient.
-/
def descend
    (S : RShadow p F relator) :
    Shadow p (completedRelatorQuotient relator) where
  Target := S.Target
  map := descendMap relator S.map S.toShadow.map_continuous S.relator_killed
  map_continuous := descendMap_continuous
    relator S.map S.toShadow.map_continuous S.relator_killed
  target_p_group := S.toShadow.target_p_group

lemma descend_comp_quotient
    (S : RShadow p F relator) :
    (descend S).map.comp (quotientMap relator) = S.map := by
  exact descend_comp
    relator S.map S.toShadow.map_continuous S.relator_killed

lemma descend_kernel_quotient
    (S : RShadow p F relator)
    (x : F) :
    quotientMap relator x ∈ (descend S).map.ker ↔ x ∈ S.map.ker := by
  change (descend S).map (quotientMap relator x) = 1 ↔ S.map x = 1
  rw [show (descend S).map (quotientMap relator x) = S.map x by
    exact congrArg (fun φ : F →* S.Target => φ x) (descend_comp_quotient S)]
  rfl

end RShadow

namespace Shadow

variable
    {p : ℕ}
    {F : Type u}
    [Group F]
    [TopologicalSpace F]
    [IsTopologicalGroup F]
    {ι : Type*}
    {relator : ι → F}

/--
Pull a finite `p`-shadow of the completed relator quotient back to a finite
relator-killing `p`-shadow of the original group.
-/
def pullbackAlongQuotient
    (S : Shadow p (completedRelatorQuotient relator)) :
    RShadow p F relator where
  toShadow := S.pullback (quotientMap relator) (quotientMap_continuous relator)
  relator_killed := by
    intro i
    change S.map (quotientMap relator (relator i)) = 1
    rw [quotient_relator_one relator i]
    exact S.map.map_one

lemma pullback_along
    (S : Shadow p (completedRelatorQuotient relator)) :
    (pullbackAlongQuotient S).map = S.map.comp (quotientMap relator) := rfl

lemma pullback_along_kernel
    (S : Shadow p (completedRelatorQuotient relator))
    (x : F) :
    x ∈ (pullbackAlongQuotient S).map.ker ↔
      quotientMap relator x ∈ S.map.ker := by
  exact S.pullback_kernel (quotientMap relator) (quotientMap_continuous relator) x

lemma descend_along_quotient
    (S : Shadow p (completedRelatorQuotient relator)) :
    (RShadow.descend (pullbackAlongQuotient S)).map = S.map := by
  apply MonoidHom.ext
  intro y
  rcases quotientMap_surjective relator y with ⟨x, rfl⟩
  have hcomp :=
    RShadow.descend_comp_quotient (pullbackAlongQuotient S)
  have happ := congrArg
    (fun φ : F →* S.Target => φ x)
    hcomp
  change (RShadow.descend (pullbackAlongQuotient S)).map (quotientMap relator x) =
    (pullbackAlongQuotient S).map x at happ
  simpa [pullback_along] using happ

end Shadow

variable
    {p : ℕ}
    {F G : Type u}
    [Group F]
    [TopologicalSpace F]
    [IsTopologicalGroup F]
    [Group G]
    {ι : Type*}
    {relator : ι → F}

/--
The universal relator kernel is exactly the pullback of the continuous finite
`p` residual kernel of the completed relator quotient.
-/
lemma kernel_comap_residual :
    relatorKernel p relator =
      (residualKernel p (completedRelatorQuotient relator)).comap
        (quotientMap relator) := by
  ext x
  constructor
  · intro hx
    rw [Subgroup.mem_comap, residual_kernel_iff]
    intro S
    have hxPullback :
        x ∈ (Shadow.pullbackAlongQuotient S).map.ker := by
      exact relator_kernel (Shadow.pullbackAlongQuotient S) hx
    exact (Shadow.pullback_along_kernel S x).mp hxPullback
  · intro hx
    rw [mem_relator_iff]
    intro S
    rw [Subgroup.mem_comap, residual_kernel_iff] at hx
    have hxDescend :
        quotientMap relator x ∈ (RShadow.descend S).map.ker :=
      hx (RShadow.descend S)
    exact (RShadow.descend_kernel_quotient S x).mp hxDescend

lemma factorization_property_comap
    {q : F →* G} :
    FactorizationProperty p relator q ↔
      q.ker ≤
        (residualKernel p (completedRelatorQuotient relator)).comap
          (quotientMap relator) := by
  rw [factorization_property_kernel, kernel_comap_residual]

lemma factorization_property_residually
    [Fact p.Prime]
    {q : F →* G}
    (hres : RFP p (completedRelatorQuotient relator)) :
    FactorizationProperty p relator q ↔ q.ker ≤ completedRelationSubgroup relator := by
  rw [factorization_property_kernel]
  rw [relator_completed_residually hres]

lemma quotient_factorization_property :
    FactorizationProperty p relator (quotientMap relator) := by
  apply factorization_property_completed
  rw [ker_quotientMap]

end FPQuotie
end Submission
