import Mathlib

namespace Towers.NumberTheory.Milne

open MvPolynomial

/-- Milne, Proposition 1.3: a ring is Noetherian exactly when every
ascending chain of ideals stabilizes and every nonempty set of ideals has a
maximal member. -/
theorem noetherian_stabilizes_maximal
    (A : Type*) [CommRing A] :
    IsNoetherianRing A ↔
      (∀ f : ℕ →o Ideal A, ∃ n, ∀ m, n ≤ m → f n = f m) ∧
      (∀ S : Set (Ideal A), S.Nonempty →
        ∃ I ∈ S, ∀ J ∈ S, ¬ I < J) := by
  constructor
  · intro h
    exact ⟨monotone_stabilizes_iff_noetherian.mpr h,
      set_has_maximal_iff_noetherian.mpr h⟩
  · rintro ⟨h, -⟩
    exact monotone_stabilizes_iff_noetherian.mp h

/-- Milne, Proposition 1.4: every nonzero nonunit in a Noetherian integral
domain is a nonempty finite product of irreducible elements. -/
theorem nonemp_irred_facto
    (A : Type*) [CommRing A] [IsDomain A] [IsNoetherianRing A]
    (a : A) (ha0 : a ≠ 0) (ha : ¬ IsUnit a) :
    ∃ factors : Multiset A,
      (∀ b ∈ factors, Irreducible b) ∧
        factors.prod = a ∧ factors ≠ 0 := by
  exact (WfDvdMonoid.not_unit_iff_exists_factors_eq a ha0).mp ha

/-- Milne, Proposition 1.6: the chain and maximal-member criteria for a
Noetherian module. -/
theorem noetherian_chain_stabilizes
    (A M : Type*) [Ring A] [AddCommGroup M] [Module A M] :
    IsNoetherian A M ↔
      (∀ f : ℕ →o Submodule A M, ∃ n, ∀ m, n ≤ m → f n = f m) ∧
      (∀ S : Set (Submodule A M), S.Nonempty →
        ∃ N ∈ S, ∀ P ∈ S, ¬ N < P) := by
  constructor
  · intro h
    exact ⟨monotone_stabilizes_iff_noetherian.mpr h,
      set_has_maximal_iff_noetherian.mpr h⟩
  · rintro ⟨h, -⟩
    exact monotone_stabilizes_iff_noetherian.mp h

/-- Milne, Proposition 1.7: an extension of Noetherian modules is
Noetherian. -/
theorem noetherian_submodule_quotient
    (A M : Type*) [Ring A] [AddCommGroup M] [Module A M]
    (N : Submodule A M) (hN : IsNoetherian A N)
    (hquotient : IsNoetherian A (M ⧸ N)) : IsNoetherian A M := by
  exact (isNoetherian_iff_submodule_quotient N).mpr ⟨hN, hquotient⟩

/-- Milne, Proposition 1.8: a finitely generated module over a Noetherian
ring is Noetherian. -/
theorem noetherian_finite_ring
    (A M : Type*) [Ring A] [AddCommGroup M] [Module A M]
    (hA : IsNoetherianRing A) (hM : Module.Finite A M) :
    IsNoetherian A M := by
  letI : IsNoetherianRing A := hA
  letI : Module.Finite A M := hM
  infer_instance

namespace IPRing

variable (k : Type*) [Field k]

/-- The ideal generated by the first `n` variables in `k[X₀, X₁, ...]`. -/
noncomputable def initialVariableIdeal (n : ℕ) : Ideal (MvPolynomial ℕ k) :=
  Ideal.span (MvPolynomial.X '' Set.Iio n)

theorem variable_ideal_mono {m n : ℕ} (hmn : m ≤ n) :
    initialVariableIdeal k m ≤ initialVariableIdeal k n := by
  exact Ideal.span_mono (Set.image_mono fun _ hi => lt_of_lt_of_le hi hmn)

noncomputable def initialVariableHom :
    ℕ →o Ideal (MvPolynomial ℕ k) where
  toFun := initialVariableIdeal k
  monotone' := fun _ _ h => variable_ideal_mono k h

theorem x_variable_succ (n : ℕ) :
    X n ∈ initialVariableIdeal k (n + 1) := by
  exact Ideal.subset_span ⟨n, Nat.lt_succ_self n, rfl⟩

theorem x_variable_ideal (n : ℕ) :
    X n ∉ initialVariableIdeal k n := by
  rw [initialVariableIdeal, MvPolynomial.mem_ideal_span_X_image]
  intro h
  obtain ⟨i, hi, hnonzero⟩ := h (Finsupp.single n 1) (by simp)
  exact hnonzero (by simp [Nat.ne_of_lt hi])

theorem initial_variable_mono :
    StrictMono (initialVariableHom k) := by
  intro m n hmn
  refine lt_of_le_of_ne (variable_ideal_mono k hmn.le) ?_
  intro hEq
  change initialVariableIdeal k m = initialVariableIdeal k n at hEq
  have hx : X m ∈ initialVariableIdeal k m := by
    rw [hEq]
    exact variable_ideal_mono k (Nat.succ_le_iff.mp hmn)
      (x_variable_succ k m)
  exact x_variable_ideal k m hx

/-- Milne, Chapter 1, after Proposition 1.3: a polynomial ring in infinitely many
variables over a field is not Noetherian. -/
theorem not_noetherian_ring :
    ¬ IsNoetherianRing (MvPolynomial ℕ k) := by
  intro h
  letI : IsNoetherianRing (MvPolynomial ℕ k) := h
  have hNoetherian : IsNoetherian (MvPolynomial ℕ k) (MvPolynomial ℕ k) :=
    isNoetherianRing_iff.mp h
  obtain ⟨n, hn⟩ :=
    monotone_stabilizes_iff_noetherian.mpr hNoetherian (initialVariableHom k)
  exact (initial_variable_mono k (Nat.lt_succ_self n)).ne
    (hn (n + 1) (Nat.le_succ n))

end IPRing

namespace AAInts

/-- The ring of all algebraic integers inside `ℂ`. -/
abbrev Ring := integralClosure ℤ ℂ

theorem two_not_unit : ¬ IsUnit (2 : Ring) := by
  intro htwo
  let u : Ringˣ := htwo.unit
  let v : Ring := (u⁻¹ : Ringˣ)
  have hu : (u : Ring) = 2 := htwo.unit_spec
  have huv : (2 : Ring) * v = 1 := by
    rw [← hu]
    simp [v]
  have huvComplex := congrArg (fun x : Ring => (x : ℂ)) huv
  have hv : (v : ℂ) = ((1 / 2 : ℚ) : ℂ) := by
    calc
      (v : ℂ) = (1 : ℂ) / 2 := by
        apply (eq_div_iff (by norm_num : (2 : ℂ) ≠ 0)).2
        simpa [mul_comm] using huvComplex
      _ = ((1 / 2 : ℚ) : ℂ) := by norm_num
  have hvIntegralComplex : IsIntegral ℤ ((1 / 2 : ℚ) : ℂ) := by
    rw [← hv]
    exact v.property
  have hvIntegralRat : IsIntegral ℤ (1 / 2 : ℚ) :=
    IsIntegral.tower_bot_of_field hvIntegralComplex
  obtain ⟨z, hz⟩ := IsIntegrallyClosed.isIntegral_iff.mp hvIntegralRat
  have hz' : (z : ℚ) = 1 / 2 := by simpa using hz
  have hzRat : (2 : ℚ) * z = 1 := by rw [hz']; norm_num
  have hzInt : (2 * z : ℤ) = 1 := by exact_mod_cast hzRat
  omega

theorem no_irreducible (x : Ring) : ¬ Irreducible x := by
  intro hx
  obtain ⟨z, hz⟩ := IsAlgClosed.exists_pow_nat_eq (x : ℂ) (by norm_num : 0 < 2)
  have hzIntegralPow : IsIntegral ℤ (z ^ 2) := by
    rw [hz]
    exact x.property
  let y : Ring :=
    ⟨z, IsIntegral.of_pow (by norm_num : 0 < 2) hzIntegralPow⟩
  have hxy : x = y * y := by
    apply Subtype.ext
    change (x : ℂ) = z * z
    simpa [pow_two] using hz.symm
  have hyy : Irreducible (y * y) := hxy ▸ hx
  rcases of_irreducible_mul hyy with hy | hy
  · exact hyy.not_isUnit (hy.mul hy)
  · exact hyy.not_isUnit (hy.mul hy)

/-- Milne, Remark 1.5: the ring of all algebraic integers is not Noetherian. -/
theorem not_noetherian_ring : ¬ IsNoetherianRing Ring := by
  intro h
  letI : IsNoetherianRing Ring := h
  obtain ⟨p, hp, -⟩ :=
    WfDvdMonoid.exists_irreducible_factor (two_not_unit) (by norm_num : (2 : Ring) ≠ 0)
  exact no_irreducible p hp

end AAInts

end Towers.NumberTheory.Milne
