import Towers.Group.Edmonton.LowerCentralGenerators
import Mathlib.GroupTheory.Finiteness

/-!
# The Edmonton Notes on Nilpotent Groups: cyclic central series

This file formalizes Hall's Theorem 1.8.  Instead of explicitly forming every
quotient, a cyclic factor `H / K` is recorded by an element `x ∈ H` such that
`H` is generated by `K` and `x`.
-/

namespace Towers
namespace Edmonton

open Group

universe u

/-- A finite central series from `H` down to `L`, with every factor cyclic.

In a step from `H` to `K`, the condition
`H = closure ((K : Set G) ∪ {x})` says precisely that `H / K` is generated by
the coset of `x`.  The commutator condition says that this factor is central
in `G / K`.
-/
inductive CSeries (G : Type u) [Group G] :
    Subgroup G → Subgroup G → Prop
  | refl (H : Subgroup G) : CSeries G H H
  | step {H K L : Subgroup G}
      (hK_le_H : K ≤ H)
      (hK_normal : K.Normal)
      (hcentral : ⁅H, (⊤ : Subgroup G)⁆ ≤ K)
      (hcyclic : ∃ x ∈ H, H = Subgroup.closure ((K : Set G) ∪ {x}))
      (tail : CSeries G K L) :
      CSeries G H L

namespace CSeries

/-- Concatenation of two finite cyclic central series. -/
theorem trans {G : Type u} [Group G] {H K L : Subgroup G}
    (hHK : CSeries G H K)
    (hKL : CSeries G K L) :
    CSeries G H L := by
  induction hHK with
  | refl => exact hKL
  | step hM_le_H hM_normal hcentral hcyclic _ ih =>
      exact .step hM_le_H hM_normal hcentral hcyclic (ih hKL)

end CSeries

/-- A finite set of generators gives only finitely many left-normed
commutators of any fixed weight. -/
theorem left_normed_set {G : Type u} [Group G]
    {A : Set G} (hA : A.Finite) (n : ℕ) :
    (leftNormedSet A n).Finite := by
  classical
  letI : Fintype A := hA.fintype
  let f : (Fin (n + 1) → A) → G :=
    fun a ↦ leftNormedValue n (fun i ↦ a i)
  apply (Set.finite_range f).subset
  rintro x ⟨a, ha, rfl⟩
  exact ⟨fun i ↦ ⟨a i, ha i⟩, rfl⟩

/-- If `N` is central below the subgroup generated by `N` and a finite set,
then those finite generators can be inserted one at a time to produce a
cyclic central series. -/
theorem cyclic_series_closure {G : Type u} [Group G]
    (N : Subgroup G) :
    ∀ (S : Set G), S.Finite →
      ⁅Subgroup.closure ((N : Set G) ∪ S), (⊤ : Subgroup G)⁆ ≤ N →
      CSeries G (Subgroup.closure ((N : Set G) ∪ S)) N := by
  intro S hS
  induction S, hS using Set.Finite.induction_on with
  | empty =>
      intro _
      simpa using CSeries.refl N
  | @insert a S ha hS ih =>
      intro hcentral
      let K : Subgroup G := Subgroup.closure ((N : Set G) ∪ S)
      let H : Subgroup G := Subgroup.closure ((N : Set G) ∪ insert a S)
      have hK_le_H : K ≤ H := by
        apply Subgroup.closure_mono
        intro x hx
        rcases hx with hx | hx
        · exact Or.inl hx
        · exact Or.inr (Set.mem_insert_of_mem a hx)
      have hN_le_K : N ≤ K := by
        intro x hx
        exact Subgroup.subset_closure (Or.inl hx)
      have hKcentral : ⁅K, (⊤ : Subgroup G)⁆ ≤ N :=
        (Subgroup.commutator_mono hK_le_H le_rfl).trans hcentral
      have hK_normal : K.Normal :=
        Subgroup.commutator_top_right_le_iff.mp (hKcentral.trans hN_le_K)
      have htail : CSeries G K N := ih hKcentral
      have haH : a ∈ H :=
        Subgroup.subset_closure (Or.inr (Set.mem_insert a S))
      have hcyclic : H = Subgroup.closure ((K : Set G) ∪ {a}) := by
        change Subgroup.closure ((N : Set G) ∪ insert a S) =
          Subgroup.closure
            ((Subgroup.closure ((N : Set G) ∪ S) : Set G) ∪ {a})
        simp only [Set.insert_eq, Subgroup.closure_union, Subgroup.closure_eq]
        ac_rfl
      exact CSeries.step hK_le_H hK_normal
        (hcentral.trans hN_le_K) ⟨a, haH, hcyclic⟩ htail

/-- A convenient form of the finite-refinement result for a named upper
subgroup. -/
theorem cyclic_generators_mod
    {G : Type u} [Group G] {H N : Subgroup G} {S : Set G}
    (hS : S.Finite)
    (hcentral : ⁅H, (⊤ : Subgroup G)⁆ ≤ N)
    (hgen : H = Subgroup.closure ((N : Set G) ∪ S)) :
    CSeries G H N := by
  subst H
  exact cyclic_series_closure N S hS hcentral

/-- Each adjacent pair of lower-central terms in a finitely generated group
admits a finite cyclic central refinement. -/
theorem lower_cyclic_succ
    {G : Type u} [Group G] {A : Set G}
    (hA : Subgroup.closure A = ⊤) (hAfin : A.Finite) (n : ℕ) :
    CSeries G
      (Subgroup.lowerCentralSeries G n) (Subgroup.lowerCentralSeries G (n + 1)) := by
  apply cyclic_generators_mod
    (left_normed_set hAfin n)
  · exact le_rfl
  · exact lower_union_normed hA n

/-- Hall, Theorem 1.8: every finitely generated nilpotent group has a finite
central series from `G` to `1`, all of whose factors are cyclic. -/
theorem cyclic_central_series {G : Type u} [Group G] [Group.FG G] [Group.IsNilpotent G] :
    CSeries G (⊤ : Subgroup G) (⊥ : Subgroup G) := by
  obtain ⟨A, hA, hAfin⟩ := Group.fg_iff.mp (inferInstance : Group.FG G)
  have hseries :
      ∀ n : ℕ,
        CSeries G
          (Subgroup.lowerCentralSeries G 0) (Subgroup.lowerCentralSeries G n) := by
    intro n
    induction n with
    | zero => exact CSeries.refl _
    | succ n ih =>
        exact ih.trans
          (lower_cyclic_succ hA hAfin n)
  simpa using hseries (Group.nilpotencyClass G)

end Edmonton
end Towers
