import Submission.FieldTheory.HMRProThree
import Submission.FieldTheory.HMRProPresentation
import Submission.Group.DenseGenerators.ZassenhausSurjective
import Submission.Group.HMRProfiniteGS
import Submission.Group.ProNormalGeneration


open Filter
open scoped Pointwise EuclideanGeometry Topology

noncomputable section

open NumberField

namespace Submission
namespace TBluepr

/- Now `K = ℚ` has signature `(r₁,r₂) = (1,0)`. -/
def initialSignature : ℕ × ℕ := (1, 0)

/- Since `S ≠ ∅`, the HMR constant is `α_{ℚ,S} = 4`. -/
def initialAlpha : ℝ := hmrAlpha initialBaseField

theorem initial_alpha_four :
    initialAlpha = 4 := by
  have hR : NumberField.InfinitePlace.nrRealPlaces ℚ = 1 := by
    unfold NumberField.InfinitePlace.nrRealPlaces
    classical
    let w : NumberField.InfinitePlace ℚ := NumberField.InfinitePlace.mk (algebraMap ℚ ℂ)
    have hw : w.IsReal := by
      refine ⟨algebraMap ℚ ℂ, ?_, rfl⟩
      change IsSelfAdjoint (algebraMap ℚ ℂ)
      ext q
      simp
    rw [Fintype.card_eq_one_iff]
    refine ⟨⟨w, hw⟩, ?_⟩
    intro y
    exact Subsingleton.elim _ _
  have hC : NumberField.InfinitePlace.nrComplexPlaces ℚ = 0 := by
    unfold NumberField.InfinitePlace.nrComplexPlaces
    classical
    rw [Fintype.card_eq_zero_iff]
    refine ⟨?_⟩
    intro y
    rcases y.2 with ⟨φ, hφ, _⟩
    have hreal : NumberField.ComplexEmbedding.IsReal φ := by
      have hφeq : φ = algebraMap ℚ ℂ := Subsingleton.elim _ _
      rw [hφeq]
      change IsSelfAdjoint (algebraMap ℚ ℂ)
      ext q
      simp
    exact hφ hreal
  norm_num [initialAlpha, hmrAlpha, initialBaseField, hR, hC]

/- The set `S` is nonempty. -/
theorem ramified_primes_nonempty : initialRamifiedPrimes.Nonempty := by
  simp [initialRamifiedPrimes]

/- Thus `d_3 G ≥ 5 > 4 = α_{ℚ,S}`. -/
theorem initial_pro_alpha :
    (initialProRank : ℝ) > initialAlpha := by
  rw [initial_alpha_four]
  have h5 : (5 : ℝ) ≤ initialProRank := by
    exact_mod_cast initial_pro_five
  linarith

/- A cutting level for the initial HMR tower is one that is at least `2` and already forces
infinitude of the quotient by the closed normal subgroup generated by any sequence whose
`i`-th term lies in `G_{k+i}`. This packages the depth-choice part of the TeX proof into a
reusable predicate. -/
def HMRCuttingLevel (k : ℕ) : Prop :=
  2 ≤ k ∧
    ∀ x : ℕ → initialGaloisGroup,
      (∀ i, x i ∈ initialZassenhausFiltration (k + i)) →
        Infinite (hmrCutQuotient (K := ℚ) (KS := initialProExtension) x)

/- The sequences cut in the HMR argument are precisely sequences of ambient Frobenius elements,
indexed by the depth at which each term is required to lie in the Zassenhaus filtration. -/
abbrev HMRCutSequence : Type := ℕ → initialGaloisGroup

/- A sequence is admissible at level `k` when its `i`-th term lies in `G_{k+i}`. This is the
input condition fed into the Golod--Shafarevich cutting lemma in the TeX proof. -/
def HMRCutAdmissible
    (k : ℕ) (x : HMRCutSequence) : Prop :=
  ∀ i, x i ∈ initialZassenhausFiltration (k + i)

/- The initial HMR strict Golod--Shafarevich value. In the concrete `ℚ` case, the
Shafarevich relation bound gives the quadratic relation count `r ≤ d`, so the
strict input is measured by `1 - d t + d t^2` for the initial generator rank `d`.
-/
def initialHMRGSValue (t : ℚ) : ℚ :=
  HPGs.quadraticGSValue initialProRank t

/- A genuine strict GS deficit for the initial tower: the actual GS value at `t₀`
is at most `-ε`. This is a real mathematical condition, not an uninterpreted
placeholder. -/
def HMRGSDeficit (t0 ε : ℚ) : Prop :=
  initialHMRGSValue t0 ≤ -ε

/- The strict Golod--Shafarevich step in the TeX proof produces a point `t₀ ∈ (0,1)`
together with a positive deficit `ε` such that the concrete initial GS value is
at most `-ε`. This packages exactly the numerical data needed by the later
geometric-series and cutting-lemma consequences. -/
structure HParame where
  t0 : ℚ
  ε : ℚ
  t0_pos : 0 < t0
  t_0_one : t0 < 1
  ε_pos : 0 < ε
  gs_deficit : HMRGSDeficit t0 ε

/- For a fixed strict GS witness `(t₀, ε)`, a level `k` is deep enough for the TeX argument when
the tail `∑_{i ≥ 0} t₀^(k+i)` is controlled by the closed-form geometric bound
`t₀^k / (1 - t₀) < ε`. -/
def HMRCuttingBound
    (c : HParame) (k : ℕ) : Prop :=
  c.t0 ^ k / (1 - c.t0) < c.ε

/- Once the tail bound is available, the missing formal bridge is the claim that every admissible
sequence of elements in `G_{k+i}` yields an infinite quotient after cutting by its closed normal
closure. This isolates exactly the Golod--Shafarevich cutting step from the later choice of `k`.
-/
def HMRGSCuttingCriterion
    (c : HParame) : Prop :=
  ∀ ⦃k : ℕ⦄,
    2 ≤ k →
      HMRCuttingBound c k →
      ∀ x : HMRCutSequence,
        HMRCutAdmissible k x →
          Infinite (hmrCutQuotient (K := ℚ) (KS := initialProExtension) x)

/- The numerical GS witness automa has `1 - t₀ > 0`, so the geometric tail bound makes
sense without hidden side conditions. Keeping this tiny lemma explicit avoids reproving the same
positivity fact in every later sub-lemma. -/
theorem hmr_denominator_pos
    (c : HParame) :
    0 < 1 - c.t0 := by
  linarith [c.t_0_one]

/- The strict GS parameters come from the generator-rank inequality
`d₃ G > α_{ℚ,S}` proved just above. In the concrete initial case this means:
there is a point `t₀ ∈ (0,1)` and a positive `ε` such that the actual quadratic
GS value `1 - d t₀ + d t₀^2` is at most `-ε`. -/
theorem hmr_parameters_alpha :
    Nonempty HParame := by
  refine
    ⟨{
      t0 := (1 : ℚ) / 2
      ε := (1 : ℚ) / 4
      t0_pos := by norm_num
      t_0_one := by norm_num
      ε_pos := by norm_num
      gs_deficit := ?_
    }⟩
  have h5 : (5 : ℚ) ≤ (initialProRank : ℚ) := by
    exact_mod_cast initial_pro_five
  dsimp [HMRGSDeficit, initialHMRGSValue, HPGs.quadraticGSValue]
  nlinarith

/- Specializing the previous lemma to the initial tower gives a named strict GS witness for the
rest of the argument. -/
theorem hmr_gs_parameters :
    Nonempty HParame := by
  exact hmr_parameters_alpha

/- Because `0 < t₀ < 1`, the geometric tail tends to `0`; hence some depth `k ≥ 2` satisfies
`t₀^k / (1 - t₀) < ε`. This isolates the depth-choice line from the TeX proof. -/
/-
Before dividing by `1 - t₀`, it is convenient to work with the equivalent numerator estimate
`t₀^k < ε * (1 - t₀)`. This keeps the geometric-series step separate from the later algebraic
rearrangement back to the original tail bound.
-/
def CuttingSmallNumerator
    (c : HParame) (k : ℕ) : Prop :=
  c.t0 ^ k < c.ε * (1 - c.t0)

/- The comparison target `ε * (1 - t₀)` is positive, since both factors are positive for a
strict GS witness. This is the number whose neighborhood around `0` will eventually contain the
powers `t₀^k`. -/
theorem hmr_small_numerator
    (c : HParame) :
    0 < c.ε * (1 - c.t0) := by
  exact mul_pos c.ε_pos (hmr_denominator_pos c)

/- Because `0 ≤ t₀ < 1`, the powers `t₀^k` tend to `0`. This isolates the analytic input from
the later extraction of an explicit depth `k`. -/
theorem cutting_powers_tendsto
    (c : HParame) :
    Tendsto (fun k : ℕ => c.t0 ^ k) atTop (𝓝 (0 : ℚ)) := by
  exact tendsto_pow_atTop_nhds_zero_of_lt_one c.t0_pos.le c.t_0_one

/- Applying the previous convergence statement to the positive threshold `ε * (1 - t₀)` shows
that eventually the numerator `t₀^k` is already small enough. This is the exact geometric-tail
estimate from the TeX proof, but still without the bookkeeping condition `k ≥ 2`. -/
theorem cutting_numerator_eventually
    (c : HParame) :
    ∀ᶠ k : ℕ in atTop, CuttingSmallNumerator c k := by
  have hpow : Tendsto (fun k : ℕ => c.t0 ^ k) atTop (𝓝 (0 : ℚ)) :=
    cutting_powers_tendsto c
  have htarget : 0 < c.ε * (1 - c.t0) :=
    hmr_small_numerator c
  have hIio : Set.Iio (c.ε * (1 - c.t0)) ∈ 𝓝 (0 : ℚ) :=
    Iio_mem_nhds htarget
  simpa [CuttingSmallNumerator] using hpow hIio

/- The eventual estimate already implies the existence of some depth with small numerator. This
separates “analytic convergence” from the later step of forcing the bound to occur at a depth at
least `2`. -/
theorem hmr_cutting_small
    (c : HParame) :
    ∃ k : ℕ, CuttingSmallNumerator c k := by
  rcases (eventually_atTop.1 (cutting_numerator_eventually c)) with ⟨N, hN⟩
  exact ⟨N, hN N le_rfl⟩

/- For the HMR application we need a depth `k ≥ 2`, so we push the first eventual witness beyond
that threshold by replacing it with `max N 2`. Because the numerator estimate is eventual, it
persists after moving further out in the sequence. -/
theorem cutting_small_numerator
    (c : HParame) :
    ∃ k : ℕ, 2 ≤ k ∧ CuttingSmallNumerator c k := by
  rcases (eventually_atTop.1 (cutting_numerator_eventually c)) with ⟨N, hN⟩
  refine ⟨max N 2, le_max_right N 2, ?_⟩
  exact hN (max N 2) (le_max_left N 2)

/- A small numerator immediately yields the original HMR tail bound after dividing by the
positive denominator `1 - t₀`. This is the algebraic conversion from the closed-form geometric
estimate back to the predicate used in the rest of the file. -/
theorem hmr_cutting_numerator
    (c : HParame)
    {k : ℕ}
    (hkSmall : CuttingSmallNumerator c k) :
    HMRCuttingBound c k := by
  dsimp [HMRCuttingBound, CuttingSmallNumerator] at hkSmall ⊢
  exact (div_lt_iff₀ (hmr_denominator_pos c)).2 hkSmall

/- It is convenient to package the previous existence statement as a concrete witness carrying
both the lower bound `2 ≤ k` and the small-numerator inequality. The final theorem then becomes a
one-line projection from this bundled witness. -/
structure HMRCuttingWitness
    (c : HParame) where
  k : ℕ
  hk_two : 2 ≤ k
  hk_small : CuttingSmallNumerator c k

/- The geometric-series argument produces a bundled witness for the required cutting depth. This
packages the output of the analytic part of the proof before the final translation to
`HMRCuttingBound`. -/
theorem initial_cutting_witness
    (c : HParame) :
    Nonempty (HMRCuttingWitness c) := by
  rcases cutting_small_numerator c with ⟨k, hk, hkSmall⟩
  exact
    ⟨{
      k := k
      hk_two := hk
      hk_small := hkSmall
    }⟩

/- Unpacking the bundled witness gives a depth `k ≥ 2` together with the original tail bound. -/
theorem hmr_cutting_witness
    {c : HParame}
    (w : HMRCuttingWitness c) :
    2 ≤ w.k ∧ HMRCuttingBound c w.k := by
  exact
    ⟨w.hk_two,
      hmr_cutting_numerator c w.hk_small⟩

theorem hmr_cutting_bound
    (c : HParame) :
    ∃ k : ℕ, 2 ≤ k ∧ HMRCuttingBound c k := by
  rcases initial_cutting_witness c with ⟨w⟩
  exact ⟨w.k, hmr_cutting_witness w⟩

/- Package the initial numerical witness in the reusable group-level HMR interface. -/
def HParame.toGeneric
    (c : HParame) :
    HPGs.StrictGSParameters initialProRank where
  t0 := c.t0
  ε := c.ε
  t0_pos := c.t0_pos
  t_0_one := c.t_0_one
  ε_pos := c.ε_pos
  base_deficit := c.gs_deficit

/- The specialized and generic geometric tail predicates are definitionally identical. -/
theorem hmr_cutting_generic
    (c : HParame) (k : ℕ) :
    HMRCuttingBound c k ↔
      HPGs.CuttingTailBound c.toGeneric k := by
  rfl

/- The initial field-theory quotient family viewed as a reusable HMR cutting system. -/
def hmrCuttingSystem :
    HPGs.CSystem initialPrimeParameter initialGaloisGroup where
  quotient := fun x =>
    hmrCutQuotient (K := ℚ) (KS := initialProExtension) x
  quotientGroup := fun _ => inferInstance
  admissible := HMRCutAdmissible

/- The remaining finite-shadow adapter. Under a temporary finiteness assumption on an
admissible cut quotient, it constructs the filtered presentation whose relators inject into
the disjoint union of base relators and selected depth-`k+i` cut relators.

This is presentation and cutting bookkeeping, not the arithmetic Shafarevich theorem. The
bare arithmetic inequality is `initial_shafarevich_rank`. -/
namespace HSScaffo

/- The finite-shadow construction starts from the chosen minimal free pro-`3`
presentation of the initial Galois group.  Its arithmetic relators are already
known to have depth at least two, and Shafarevich bounds their number by the
generator rank. -/
abbrev BasePresentation :=
  minimalProPresentation

/- The quotient obtained by killing the HMR cut sequence. -/
abbrev CutQuotient (x : HMRCutSequence) :=
  hmrCutQuotient (K := ℚ) (KS := initialProExtension) x

/- The field-theoretic cut quotient is canonically equivalent to the quotient
of the initial Galois group by the closed normal subgroup generated by the cut
sequence. -/
noncomputable def cutQuotientEquiv
    (x : HMRCutSequence) :
    initialGaloisGroup ⧸
        hmrCutSubgroup (K := ℚ) (KS := initialProExtension) x ≃*
      CutQuotient x :=
  Classical.choice
    (hmr_cut_quotient
      (K := ℚ) (KS := initialProExtension) x)

/- The quotient map from the initial Galois group to the field-theoretic HMR
cut quotient. -/
noncomputable def cutProjection
    (x : HMRCutSequence) :
    initialGaloisGroup →* CutQuotient x :=
  (cutQuotientEquiv x).toMonoidHom.comp
    (QuotientGroup.mk'
      (hmrCutSubgroup (K := ℚ) (KS := initialProExtension) x))

/- The free pro-`3` quotient map obtained by composing the chosen minimal
presentation with the HMR cut projection. -/
noncomputable def freeCutProjection
    (x : HMRCutSequence) :
    BasePresentation.free.Carrier →* CutQuotient x :=
  (cutProjection x).comp BasePresentation.quotientMap

/- The raw topological quotient by the HMR cut subgroup.  The direct pro-`3`
finite-shadow adapter uses this quotient so that continuity remains visible. -/
abbrev TopologicalCutQuotient
    (x : HMRCutSequence) :=
  initialGaloisGroup ⧸
    hmrCutSubgroup (K := ℚ) (KS := initialProExtension) x

/- The canonical projection to the raw topological cut quotient. -/
noncomputable def topologicalCutProjection
    (x : HMRCutSequence) :
    initialGaloisGroup →* TopologicalCutQuotient x :=
  QuotientGroup.mk'
    (hmrCutSubgroup (K := ℚ) (KS := initialProExtension) x)

/- The free pro-`3` projection to the raw topological cut quotient. -/
noncomputable def freeTopologicalProjection
    (x : HMRCutSequence) :
    BasePresentation.free.Carrier →* TopologicalCutQuotient x :=
  (topologicalCutProjection x).comp BasePresentation.quotientMap

/- Passing from the raw quotient to its field-theoretic model does not alter
the kernel of the free pro-`3` projection. -/
theorem topological_cut_projection
    (x : HMRCutSequence) :
    MonoidHom.ker (freeTopologicalProjection x) =
      MonoidHom.ker (freeCutProjection x) := by
  ext w
  change
    topologicalCutProjection x (BasePresentation.quotientMap w) = 1 ↔
      cutQuotientEquiv x
          (topologicalCutProjection x (BasePresentation.quotientMap w)) =
        1
  constructor
  · intro hw
    rw [hw]
    exact map_one (cutQuotientEquiv x)
  · intro hw
    rw [← map_one (cutQuotientEquiv x)] at hw
    exact (cutQuotientEquiv x).injective hw

/- The raw free cut projection is continuous. -/
theorem topological_cut_continuous
    (x : HMRCutSequence) :
    Continuous (freeTopologicalProjection x) := by
  exact
    continuous_quotient_mk'.comp
      BasePresentation.quotientMap_continuous

/- The raw free cut projection is onto. -/
theorem topological_cut_surjective
    (x : HMRCutSequence) :
    Function.Surjective (freeTopologicalProjection x) := by
  exact
    (QuotientGroup.mk'_surjective
      (hmrCutSubgroup (K := ℚ) (KS := initialProExtension) x)).comp
      BasePresentation.quotientMap_surjective

/- Every member of the closed normal HMR cut subgroup maps trivially to the
field-theoretic quotient. -/
theorem cut_projection_subgroup
    (x : HMRCutSequence)
    {g : initialGaloisGroup}
    (hg :
      g ∈ hmrCutSubgroup (K := ℚ) (KS := initialProExtension) x) :
    cutProjection x g = 1 := by
  change
    cutQuotientEquiv x
        (QuotientGroup.mk'
          (hmrCutSubgroup (K := ℚ) (KS := initialProExtension) x) g) =
      1
  rw [← map_one (cutQuotientEquiv x)]
  exact
    congrArg (cutQuotientEquiv x)
      ((QuotientGroup.eq_one_iff g).2 hg)

/- Each member of the cut sequence belongs to the closed normal subgroup that
the sequence generates. -/
theorem sequence_cut_subgroup
    (x : HMRCutSequence)
    (i : ℕ) :
    x i ∈ hmrCutSubgroup (K := ℚ) (KS := initialProExtension) x := by
  apply
    (Subgroup.normalClosure (Set.range x)).le_topologicalClosure
  apply
    Subgroup.subset_normalClosure
  exact
    Set.mem_range_self i

/- Consequently, every selected cut element maps trivially to the HMR cut
quotient. -/
theorem cut_projection_sequence
    (x : HMRCutSequence)
    (i : ℕ) :
    cutProjection x (x i) = 1 := by
  apply
    cut_projection_subgroup x
  exact
    sequence_cut_subgroup x i

/- The base relators of the minimal free pro-`3` presentation lie in the
kernel of its quotient map to the initial Galois group. -/
theorem base_relator_initial
    (j : Fin proRelationRank) :
    BasePresentation.relator j ∈
      MonoidHom.ker BasePresentation.quotientMap := by
  rw [BasePresentation.kernel_eq]
  apply
    (Subgroup.normalClosure
      (Set.range BasePresentation.relator)).le_topologicalClosure
  apply
    Subgroup.subset_normalClosure
  exact
    Set.mem_range_self j

/- The base relators therefore remain trivial after imposing the additional
HMR cut relations. -/
theorem free_cut_projection
    (x : HMRCutSequence)
    (j : Fin proRelationRank) :
    freeCutProjection x (BasePresentation.relator j) = 1 := by
  change
    cutProjection x
        (BasePresentation.quotientMap (BasePresentation.relator j)) =
      1
  rw [
    MonoidHom.mem_ker.mp
      (base_relator_initial j)
  ]
  exact
    map_one (cutProjection x)

/- A finite cut-kernel certificate records the genuinely profinite part of the
HMR adapter.  Under a temporary finiteness assumption, only finitely many cut
relations are needed.  Each selected relation is lifted back to the chosen
free pro-`3` group at the required depth, and together with the arithmetic
relators it topologically normally generates the kernel of the free map to
the cut quotient. -/
structure CKCert
    (k : ℕ)
    (x : HMRCutSequence) where
  cutIndex : Finset ℕ
  liftedCutRelator :
    cutIndex → BasePresentation.free.Carrier
  lifted_cut_maps :
    ∀ i : cutIndex,
      BasePresentation.quotientMap (liftedCutRelator i) = x i.1
  lifted_cut_depth :
    ∀ i : cutIndex,
      liftedCutRelator i ∈
        (zassenhausFiltration
          initialPrimeParameter BasePresentation.free.Carrier
          (k + i.1)).topologicalClosure
  kernel_eq :
    MonoidHom.ker (freeCutProjection x) =
      (Subgroup.normalClosure
        (Set.range BasePresentation.relator ∪
          Set.range liftedCutRelator)).topologicalClosure

/- A selected lifted cut relator is killed by the composed map to the cut
quotient. -/
theorem CKCert.lifted_relat_proje
    {k : ℕ}
    {x : HMRCutSequence}
    (C : CKCert k x)
    (i : C.cutIndex) :
    freeCutProjection x (C.liftedCutRelator i) = 1 := by
  change
    cutProjection x
        (BasePresentation.quotientMap (C.liftedCutRelator i)) =
      1
  rw [C.lifted_cut_maps i]
  exact
    cut_projection_sequence x i.1

/- A selected lifted cut relator belongs to the kernel of the free cut
projection. -/
theorem CKCert.lifted_relat_cutpr
    {k : ℕ}
    {x : HMRCutSequence}
    (C : CKCert k x)
    (i : C.cutIndex) :
    C.liftedCutRelator i ∈ MonoidHom.ker (freeCutProjection x) := by
  apply
    MonoidHom.mem_ker.mpr
  exact
    C.lifted_relat_proje i

/- Every base relator belongs to the kernel appearing in a finite cut-kernel
certificate. -/
theorem CKCert.base_relator_memkernel
    {k : ℕ}
    {x : HMRCutSequence}
    (_C : CKCert k x)
    (j : Fin proRelationRank) :
    BasePresentation.relator j ∈ MonoidHom.ker (freeCutProjection x) := by
  apply
    MonoidHom.mem_ker.mpr
  exact
    free_cut_projection x j

/- Surjectivity of the chosen minimal presentation transports each algebraic
Zassenhaus term onto the corresponding term of the initial Galois group. -/
theorem base_presentation_filtration
    (n : ℕ) :
    Subgroup.map BasePresentation.quotientMap
        (zassenhausFiltration
          initialPrimeParameter BasePresentation.free.Carrier n) =
      initialZassenhausFiltration n := by
  simpa [initialZassenhausFiltration] using
    (filtration_without_width
      (p := initialPrimeParameter)
      n
      BasePresentation.quotientMap
      BasePresentation.quotientMap_surjective)

/- Every element in an initial Zassenhaus term therefore has a lift in the
matching algebraic term of the free pro-`3` group. -/
theorem presentation_lift_filtration
    {n : ℕ}
    {g : initialGaloisGroup}
    (hg : g ∈ initialZassenhausFiltration n) :
    ∃ w : BasePresentation.free.Carrier,
      w ∈
          zassenhausFiltration
            initialPrimeParameter BasePresentation.free.Carrier n ∧
        BasePresentation.quotientMap w = g := by
  have hg' :
      g ∈
        Subgroup.map BasePresentation.quotientMap
          (zassenhausFiltration
            initialPrimeParameter BasePresentation.free.Carrier n) := by
    rw [base_presentation_filtration n]
    exact
      hg
  rcases hg' with ⟨w, hw, rfl⟩
  exact
    ⟨w, hw, rfl⟩

/- The same lift also lies in the topological closure used by the
presentation-depth interface. -/
theorem presentation_topological_closure
    {n : ℕ}
    {g : initialGaloisGroup}
    (hg : g ∈ initialZassenhausFiltration n) :
    ∃ w : BasePresentation.free.Carrier,
      w ∈
          (zassenhausFiltration
            initialPrimeParameter BasePresentation.free.Carrier n).topologicalClosure ∧
        BasePresentation.quotientMap w = g := by
  rcases
      presentation_lift_filtration hg with
    ⟨w, hw, hmap⟩
  refine
    ⟨w, ?_, hmap⟩
  exact
    (zassenhausFiltration
      initialPrimeParameter BasePresentation.free.Carrier n).le_topologicalClosure hw

/- Choose a depth-controlled free lift for every member of an admissible cut
sequence.  Keeping the family indexed by all natural numbers lets the later
compactness step select a finite subset without making any further choices. -/
noncomputable def liftedCutAdmissible
    {k : ℕ}
    (x : HMRCutSequence)
    (hx : HMRCutAdmissible k x)
    (i : ℕ) :
    BasePresentation.free.Carrier :=
  Classical.choose
    (presentation_lift_filtration
      (hx i))

/- The chosen lift maps to the original cut-sequence element. -/
theorem lifted_admissible_maps
    {k : ℕ}
    (x : HMRCutSequence)
    (hx : HMRCutAdmissible k x)
    (i : ℕ) :
    BasePresentation.quotientMap
        (liftedCutAdmissible x hx i) =
      x i := by
  exact
    (Classical.choose_spec
      (presentation_lift_filtration
        (hx i))).2

/- The chosen lift belongs to the required algebraic Zassenhaus term. -/
theorem lifted_cut_filtration
    {k : ℕ}
    (x : HMRCutSequence)
    (hx : HMRCutAdmissible k x)
    (i : ℕ) :
    liftedCutAdmissible x hx i ∈
      zassenhausFiltration
        initialPrimeParameter BasePresentation.free.Carrier (k + i) := by
  exact
    (Classical.choose_spec
      (presentation_lift_filtration
        (hx i))).1

/- In particular, the chosen lift satisfies the depth condition expected by
`CKCert`. -/
theorem lifted_cut_topological
    {k : ℕ}
    (x : HMRCutSequence)
    (hx : HMRCutAdmissible k x)
    (i : ℕ) :
    liftedCutAdmissible x hx i ∈
      (zassenhausFiltration
        initialPrimeParameter BasePresentation.free.Carrier
        (k + i)).topologicalClosure := by
  apply
    (zassenhausFiltration
      initialPrimeParameter BasePresentation.free.Carrier
      (k + i)).le_topologicalClosure
  exact
    lifted_cut_filtration x hx i

/- Every chosen lift dies in the HMR cut quotient. -/
theorem lifted_cut_projection
    {k : ℕ}
    (x : HMRCutSequence)
    (hx : HMRCutAdmissible k x)
    (i : ℕ) :
    freeCutProjection x (liftedCutAdmissible x hx i) = 1 := by
  change
    cutProjection x
        (BasePresentation.quotientMap
          (liftedCutAdmissible x hx i)) =
      1
  rw [lifted_admissible_maps x hx i]
  exact
    cut_projection_sequence x i

/- Equivalently, each chosen lift belongs to the kernel of the free cut
projection. -/
theorem lifted_cut_admissible
    {k : ℕ}
    (x : HMRCutSequence)
    (hx : HMRCutAdmissible k x)
    (i : ℕ) :
    liftedCutAdmissible x hx i ∈
      MonoidHom.ker (freeCutProjection x) := by
  apply
    MonoidHom.mem_ker.mpr
  exact
    lifted_cut_projection x hx i

/- Restrict the canonical family of chosen lifts to a proposed finite set of
cut indices. -/
noncomputable def selectedLiftedAdmissible
    {k : ℕ}
    (x : HMRCutSequence)
    (hx : HMRCutAdmissible k x)
    (cutIndex : Finset ℕ)
    (i : cutIndex) :
    BasePresentation.free.Carrier :=
  liftedCutAdmissible x hx i.1

/- Restriction to a finite index set preserves the map-to-cut-element
property. -/
theorem selected_lifted_maps
    {k : ℕ}
    (x : HMRCutSequence)
    (hx : HMRCutAdmissible k x)
    (cutIndex : Finset ℕ)
    (i : cutIndex) :
    BasePresentation.quotientMap
        (selectedLiftedAdmissible x hx cutIndex i) =
      x i.1 := by
  exact
    lifted_admissible_maps x hx i.1

/- Restriction to a finite index set also preserves the algebraic depth
bound. -/
theorem selected_lifted_filtration
    {k : ℕ}
    (x : HMRCutSequence)
    (hx : HMRCutAdmissible k x)
    (cutIndex : Finset ℕ)
    (i : cutIndex) :
    selectedLiftedAdmissible x hx cutIndex i ∈
      zassenhausFiltration
        initialPrimeParameter BasePresentation.free.Carrier
        (k + i.1) := by
  exact
    lifted_cut_filtration x hx i.1

/- Restriction to a finite index set gives the topological depth condition
stored in the final certificate. -/
theorem selected_lifted_topological
    {k : ℕ}
    (x : HMRCutSequence)
    (hx : HMRCutAdmissible k x)
    (cutIndex : Finset ℕ)
    (i : cutIndex) :
    selectedLiftedAdmissible x hx cutIndex i ∈
      (zassenhausFiltration
        initialPrimeParameter BasePresentation.free.Carrier
        (k + i.1)).topologicalClosure := by
  exact
    lifted_cut_topological x hx i.1

/- Restriction to a finite index set preserves triviality in the HMR cut
quotient. -/
theorem selected_lifted_admissible
    {k : ℕ}
    (x : HMRCutSequence)
    (hx : HMRCutAdmissible k x)
    (cutIndex : Finset ℕ)
    (i : cutIndex) :
    freeCutProjection x
        (selectedLiftedAdmissible x hx cutIndex i) =
      1 := by
  exact
    lifted_cut_projection x hx i.1

/- Restriction to a finite index set therefore lands inside the free cut
kernel. -/
theorem selected_lifted_cut
    {k : ℕ}
    (x : HMRCutSequence)
    (hx : HMRCutAdmissible k x)
    (cutIndex : Finset ℕ)
    (i : cutIndex) :
    selectedLiftedAdmissible x hx cutIndex i ∈
      MonoidHom.ker (freeCutProjection x) := by
  apply
    MonoidHom.mem_ker.mpr
  exact
    selected_lifted_admissible
      x hx cutIndex i

/- The relation set attached to a proposed finite selection consists of the
base arithmetic relators and the selected lifted cut relators. -/
noncomputable def selectedCutSet
    {k : ℕ}
    (x : HMRCutSequence)
    (hx : HMRCutAdmissible k x)
    (cutIndex : Finset ℕ) :
    Set BasePresentation.free.Carrier :=
  Set.range BasePresentation.relator ∪
    Set.range (selectedLiftedAdmissible x hx cutIndex)

/- Every base relator belongs to every finite selected relation set. -/
theorem base_selected_cut
    {k : ℕ}
    (x : HMRCutSequence)
    (hx : HMRCutAdmissible k x)
    (cutIndex : Finset ℕ)
    (j : Fin proRelationRank) :
    BasePresentation.relator j ∈
      selectedCutSet x hx cutIndex := by
  apply
    Set.mem_union_left
  exact
    Set.mem_range_self j

/- Every selected lifted cut relator belongs to the corresponding finite
selected relation set. -/
theorem selected_lifted_set
    {k : ℕ}
    (x : HMRCutSequence)
    (hx : HMRCutAdmissible k x)
    (cutIndex : Finset ℕ)
    (i : cutIndex) :
    selectedLiftedAdmissible x hx cutIndex i ∈
      selectedCutSet x hx cutIndex := by
  apply
    Set.mem_union_right
  exact
    Set.mem_range_self i

/- Every relation in a finite selected relation set already lies in the free
cut kernel. -/
theorem selected_subset_projection
    {k : ℕ}
    (x : HMRCutSequence)
    (hx : HMRCutAdmissible k x)
    (cutIndex : Finset ℕ) :
    selectedCutSet x hx cutIndex ⊆
      MonoidHom.ker (freeCutProjection x) := by
  intro w hw
  rcases hw with hw | hw
  · rcases hw with ⟨j, rfl⟩
    apply
      MonoidHom.mem_ker.mpr
    exact
      free_cut_projection x j
  · rcases hw with ⟨i, rfl⟩
    exact
      selected_lifted_cut
        x hx cutIndex i

/- Thus the ordinary normal closure of any finite selected relation set lies
inside the free cut kernel. -/
theorem selected_cut_projection
    {k : ℕ}
    (x : HMRCutSequence)
    (hx : HMRCutAdmissible k x)
    (cutIndex : Finset ℕ) :
    Subgroup.normalClosure (selectedCutSet x hx cutIndex) ≤
      MonoidHom.ker (freeCutProjection x) := by
  apply
    Subgroup.normalClosure_le_normal
  exact
    selected_subset_projection
      x hx cutIndex

/- The canonical relation set before finite extraction records all chosen cut
lifts. -/
noncomputable def admissibleCutSet
    {k : ℕ}
    (x : HMRCutSequence)
    (hx : HMRCutAdmissible k x) :
    Set BasePresentation.free.Carrier :=
  Set.range BasePresentation.relator ∪
    Set.range (liftedCutAdmissible x hx)

/- Every finite selected relation set is contained in the canonical
all-indices relation set. -/
theorem selected_cut_admissible
    {k : ℕ}
    (x : HMRCutSequence)
    (hx : HMRCutAdmissible k x)
    (cutIndex : Finset ℕ) :
    selectedCutSet x hx cutIndex ⊆
      admissibleCutSet x hx := by
  intro w hw
  rcases hw with hw | hw
  · exact
      Set.mem_union_left _ hw
  · rcases hw with ⟨i, rfl⟩
    apply
      Set.mem_union_right
    exact
      Set.mem_range_self i.1

/- Every relation in the canonical all-indices set lies in the free cut
kernel. -/
theorem admissible_subset_projection
    {k : ℕ}
    (x : HMRCutSequence)
    (hx : HMRCutAdmissible k x) :
    admissibleCutSet x hx ⊆
      MonoidHom.ker (freeCutProjection x) := by
  intro w hw
  rcases hw with hw | hw
  · rcases hw with ⟨j, rfl⟩
    apply
      MonoidHom.mem_ker.mpr
    exact
      free_cut_projection x j
  · rcases hw with ⟨i, rfl⟩
    exact
      lifted_cut_admissible x hx i

/- Consequently, the ordinary normal closure of all canonical relations lies
in the free cut kernel as well. -/
theorem admissible_cut_projection
    {k : ℕ}
    (x : HMRCutSequence)
    (hx : HMRCutAdmissible k x) :
    Subgroup.normalClosure (admissibleCutSet x hx) ≤
      MonoidHom.ker (freeCutProjection x) := by
  apply
    Subgroup.normalClosure_le_normal
  exact
    admissible_subset_projection x hx

/- Closed normal generation is monotone in the underlying relation set.  The
topological-closure step is kept explicit here because the compactness
argument below repeatedly moves between finite relation sets and the
canonical all-indices family. -/
theorem normal_topological_mono
    {S T : Set BasePresentation.free.Carrier}
    (hST : S ⊆ T) :
    (Subgroup.normalClosure S).topologicalClosure ≤
      (Subgroup.normalClosure T).topologicalClosure := by
  apply
    (Subgroup.normalClosure S).topologicalClosure_minimal
  · exact
      (Subgroup.normalClosure_mono hST).trans
        (Subgroup.normalClosure T).le_topologicalClosure
  · exact
      Subgroup.isClosed_topologicalClosure
        (Subgroup.normalClosure T)

/- Enlarging the finite set of selected cut indices enlarges the associated
relation set.  The arithmetic branch is unchanged, while an element in the
cut branch is transported to the larger subtype by the inclusion of
indices. -/
theorem selected_set_mono
    {k : ℕ}
    (x : HMRCutSequence)
    (hx : HMRCutAdmissible k x)
    {cutIndex cutIndex' : Finset ℕ}
    (hcut : cutIndex ⊆ cutIndex') :
    selectedCutSet x hx cutIndex ⊆
      selectedCutSet x hx cutIndex' := by
  intro w hw
  rcases hw with hw | hw
  · apply
      Set.mem_union_left
    exact
      hw
  · rcases hw with
      ⟨i, rfl⟩
    apply
      Set.mem_union_right
    refine
      ⟨⟨i.1, hcut i.2⟩, ?_⟩
    rfl

/- The preceding set-theoretic inclusion immediately transports ordinary
normal closures.  Naming this intermediate step keeps later topological
arguments readable. -/
theorem selected_cut_mono
    {k : ℕ}
    (x : HMRCutSequence)
    (hx : HMRCutAdmissible k x)
    {cutIndex cutIndex' : Finset ℕ}
    (hcut : cutIndex ⊆ cutIndex') :
    Subgroup.normalClosure
        (selectedCutSet x hx cutIndex) ≤
      Subgroup.normalClosure
        (selectedCutSet x hx cutIndex') := by
  apply
    Subgroup.normalClosure_mono
  exact
    selected_set_mono x hx hcut

/- Closed normal closures of selected cut relation sets are monotone as
well.  This is the form used when finite selections are combined by union. -/
theorem selected_topological_mono
    {k : ℕ}
    (x : HMRCutSequence)
    (hx : HMRCutAdmissible k x)
    {cutIndex cutIndex' : Finset ℕ}
    (hcut : cutIndex ⊆ cutIndex') :
    (Subgroup.normalClosure
        (selectedCutSet x hx cutIndex)).topologicalClosure ≤
      (Subgroup.normalClosure
        (selectedCutSet x hx cutIndex')).topologicalClosure := by
  apply
    normal_topological_mono
  exact
    selected_set_mono x hx hcut

/- Every finite selected relation set lies in the canonical all-indices
family, so its closed normal closure lies in the canonical closed normal
closure. -/
theorem selected_topological_admissible
    {k : ℕ}
    (x : HMRCutSequence)
    (hx : HMRCutAdmissible k x)
    (cutIndex : Finset ℕ) :
    (Subgroup.normalClosure
        (selectedCutSet x hx cutIndex)).topologicalClosure ≤
      (Subgroup.normalClosure
        (admissibleCutSet x hx)).topologicalClosure := by
  apply
    normal_topological_mono
  exact
    selected_cut_admissible
      x hx cutIndex

/- A single relation from the canonical family is already covered by a
finite cut selection.  Base relators need no cut index at all; a lifted cut
relator is covered by the singleton containing its source index. -/
theorem cut_cover_set
    {k : ℕ}
    (x : HMRCutSequence)
    (hx : HMRCutAdmissible k x)
    {w : BasePresentation.free.Carrier}
    (hw : w ∈ admissibleCutSet x hx) :
    ∃ cutIndex : Finset ℕ,
      ({w} : Set BasePresentation.free.Carrier) ⊆
        selectedCutSet x hx cutIndex := by
  classical
  rcases hw with hw | hw
  · refine
      ⟨∅, ?_⟩
    intro y hy
    rw [Set.mem_singleton_iff] at hy
    subst y
    apply
      Set.mem_union_left
    exact
      hw
  · rcases hw with
      ⟨i, rfl⟩
    refine
      ⟨{i}, ?_⟩
    intro y hy
    rw [Set.mem_singleton_iff] at hy
    subst y
    apply
      Set.mem_union_right
    refine
      ⟨⟨i, by simp⟩, ?_⟩
    rfl

/- Any finite family drawn from the canonical relation set can therefore be
covered by a finite set of cut indices.  This induction is the bookkeeping
step that converts a compactness theorem stated for finite relation subsets
into the index-based certificate required by the HMR adapter. -/
theorem cut_cover_admissible
    {k : ℕ}
    (x : HMRCutSequence)
    (hx : HMRCutAdmissible k x)
    (relations : Finset BasePresentation.free.Carrier)
    (hrelations :
      ∀ w, w ∈ relations →
        w ∈ admissibleCutSet x hx) :
    ∃ cutIndex : Finset ℕ,
      ∀ w, w ∈ relations →
        w ∈ selectedCutSet x hx cutIndex := by
  classical
  induction relations using Finset.induction_on with
  | empty =>
      refine
        ⟨∅, ?_⟩
      intro w hw
      simp at hw
  | @insert w relations hwNotMem ih =>
      have hwCanonical :
          w ∈ admissibleCutSet x hx := by
        apply
          hrelations
        simp
      have hrelationsRest :
          ∀ y, y ∈ relations →
            y ∈ admissibleCutSet x hx := by
        intro y hy
        apply
          hrelations
        exact
          Finset.mem_insert_of_mem hy
      rcases
          cut_cover_set
            x hx hwCanonical with
        ⟨cutIndexHead, hcoverHead⟩
      rcases
          ih hrelationsRest with
        ⟨cutIndexTail, hcoverTail⟩
      refine
        ⟨cutIndexHead ∪ cutIndexTail, ?_⟩
      intro y hy
      rcases
          Finset.mem_insert.mp hy with
        rfl | hyTail
      · apply
          selected_set_mono
            x hx Finset.subset_union_left
        apply
          hcoverHead
        simp
      · apply
          selected_set_mono
            x hx Finset.subset_union_right
        exact
          hcoverTail y hyTail

/- Covering a finite relation family by selected cut indices transports the
ordinary normal closure of that finite family into the selected ordinary
normal closure.  Keeping this algebraic step separate makes the later
topological passage explicit. -/
theorem selected_cut_set
    {k : ℕ}
    (x : HMRCutSequence)
    (hx : HMRCutAdmissible k x)
    (relations : Finset BasePresentation.free.Carrier)
    (cutIndex : Finset ℕ)
    (hcover :
      ∀ w, w ∈ relations →
        w ∈ selectedCutSet x hx cutIndex) :
    Subgroup.normalClosure
        (relations : Set BasePresentation.free.Carrier) ≤
      Subgroup.normalClosure
        (selectedCutSet x hx cutIndex) := by
  apply
    Subgroup.normalClosure_mono
  intro w hw
  exact
    hcover w hw

/- Covering a finite relation family by selected cut indices transports the
closed normal closure of that finite family into the selected closed normal
closure. -/
theorem topological_selected_cut
    {k : ℕ}
    (x : HMRCutSequence)
    (hx : HMRCutAdmissible k x)
    (relations : Finset BasePresentation.free.Carrier)
    (cutIndex : Finset ℕ)
    (hcover :
      ∀ w, w ∈ relations →
        w ∈ selectedCutSet x hx cutIndex) :
    (Subgroup.normalClosure
        (relations : Set BasePresentation.free.Carrier)).topologicalClosure ≤
      (Subgroup.normalClosure
        (selectedCutSet x hx cutIndex)).topologicalClosure := by
  apply
    (Subgroup.normalClosure
      (relations : Set BasePresentation.free.Carrier)).topologicalClosure_minimal
  · exact
      (selected_cut_set
        x hx relations cutIndex hcover).trans
        (Subgroup.normalClosure
          (selectedCutSet x hx cutIndex)).le_topologicalClosure
  · exact
      Subgroup.isClosed_topologicalClosure
        (Subgroup.normalClosure
          (selectedCutSet x hx cutIndex))

/- The first mathematical input is the relative kernel-generation statement
before compactness: the base presentation relators together with every
depth-controlled lifted cut relator topologically normally generate the
kernel of the map to the HMR cut quotient.  It is strictly smaller than
finite extraction because it does not select or encode any finite family. -/
theorem admissible_topological_projection
    {k : ℕ}
    (x : HMRCutSequence)
    (hx : HMRCutAdmissible k x) :
    MonoidHom.ker (freeCutProjection x) =
      (Subgroup.normalClosure
        (admissibleCutSet x hx)).topologicalClosure := by
  let N :=
    hmrCutSubgroup (K := ℚ) (KS := initialProExtension) x
  let C :=
    (Subgroup.normalClosure
      (admissibleCutSet x hx)).topologicalClosure
  have hC_closed :
      IsClosed (C : Set BasePresentation.free.Carrier) := by
    dsimp [C]
    exact
      Subgroup.isClosed_topologicalClosure
        (Subgroup.normalClosure
          (admissibleCutSet x hx))
  have hC_le_comap :
      C ≤ Subgroup.comap BasePresentation.quotientMap N := by
    dsimp [C]
    apply
      (Subgroup.normalClosure
        (admissibleCutSet x hx)).topologicalClosure_minimal
    · apply
        Subgroup.normalClosure_le_normal
      intro w hw
      rcases hw with hw | hw
      · rcases hw with
          ⟨j, rfl⟩
        change
          BasePresentation.quotientMap (BasePresentation.relator j) ∈ N
        rw [
          MonoidHom.mem_ker.mp
            (base_relator_initial j)
        ]
        exact
          N.one_mem
      · rcases hw with
          ⟨i, rfl⟩
        change
          BasePresentation.quotientMap
              (liftedCutAdmissible x hx i) ∈
            N
        rw [lifted_admissible_maps x hx i]
        exact
          sequence_cut_subgroup x i
    · change
        IsClosed
          (BasePresentation.quotientMap ⁻¹' (N : Set initialGaloisGroup))
      exact
        (Subgroup.isClosed_topologicalClosure
          (Subgroup.normalClosure (Set.range x))).preimage
          BasePresentation.quotientMap_continuous
  have hkernel_le_C :
      MonoidHom.ker BasePresentation.quotientMap ≤ C := by
    rw [BasePresentation.kernel_eq]
    apply
      normal_topological_mono
    exact
      Set.subset_union_left
  letI : C.Normal := by
    dsimp [C]
    exact
      Subgroup.is_normal_topologicalClosure
        (Subgroup.normalClosure
          (admissibleCutSet x hx))
  letI :
      (Subgroup.map BasePresentation.quotientMap C).Normal :=
    Subgroup.Normal.map
      inferInstance BasePresentation.quotientMap
        BasePresentation.quotientMap_surjective
  have hN_le_map_C :
      N ≤ Subgroup.map BasePresentation.quotientMap C := by
    dsimp [N]
    apply
      (Subgroup.normalClosure (Set.range x)).topologicalClosure_minimal
    · apply
        Subgroup.normalClosure_le_normal
      intro g hg
      rcases hg with
        ⟨i, rfl⟩
      refine
        ⟨liftedCutAdmissible x hx i, ?_, ?_⟩
      · apply
          (Subgroup.normalClosure
            (admissibleCutSet x hx)).le_topologicalClosure
        apply
          Subgroup.subset_normalClosure
        apply
          Set.mem_union_right
        exact
          Set.mem_range_self i
      · exact
          lifted_admissible_maps x hx i
    · change
        IsClosed
          (BasePresentation.quotientMap '' (C : Set BasePresentation.free.Carrier))
      exact
        (hC_closed.isCompact.image
          BasePresentation.quotientMap_continuous).isClosed
  have hcomap_le_C :
      Subgroup.comap BasePresentation.quotientMap N ≤ C := by
    intro w hw
    rcases hN_le_map_C hw with
      ⟨z, hz, hzw⟩
    have hdiff :
        w * z⁻¹ ∈ MonoidHom.ker BasePresentation.quotientMap := by
      rw [MonoidHom.mem_ker, map_mul, map_inv, hzw, mul_inv_cancel]
    simpa only [mul_assoc, inv_mul_cancel, mul_one] using
      C.mul_mem (hkernel_le_C hdiff) hz
  have hcomap_eq :
      Subgroup.comap BasePresentation.quotientMap N = C := by
    exact
      le_antisymm hcomap_le_C hC_le_comap
  change
    MonoidHom.ker (freeCutProjection x) = C
  rw [← hcomap_eq]
  ext w
  change
    cutQuotientEquiv x
        (QuotientGroup.mk'
          (hmrCutSubgroup (K := ℚ) (KS := initialProExtension) x)
          (BasePresentation.quotientMap w)) =
      1 ↔
    BasePresentation.quotientMap w ∈ N
  constructor
  · intro hw
    apply
      (QuotientGroup.eq_one_iff
        (BasePresentation.quotientMap w)).mp
    apply
      (cutQuotientEquiv x).injective
    simpa using
      hw
  · intro hw
    rw [← map_one (cutQuotientEquiv x)]
    exact
      congrArg (cutQuotientEquiv x)
        ((QuotientGroup.eq_one_iff
          (BasePresentation.quotientMap w)).mpr hw)

/- The second mathematical input is the relative pro-`3` finite-selection
theorem.  Once the canonical all-indices family is known to generate the
open kernel, one uses finite-rank Frattini control for that open subgroup to
select a finite subfamily with the same closed normal closure.  Compactness
and finiteness of the quotient enter the proof, but do not by themselves
supply the selection.  This deliberately avoids the additional
index-decoding work proved above. -/
theorem admissible_cut_generates
    {k : ℕ}
    (x : HMRCutSequence)
    (hx : HMRCutAdmissible k x)
    [Finite (CutQuotient x)]
    (hkernel :
      MonoidHom.ker (freeCutProjection x) =
        (Subgroup.normalClosure
          (admissibleCutSet x hx)).topologicalClosure) :
    ∃ relations : Finset BasePresentation.free.Carrier,
      (∀ w, w ∈ relations →
        w ∈ admissibleCutSet x hx) ∧
      MonoidHom.ker (freeCutProjection x) =
        (Subgroup.normalClosure
          (relations : Set BasePresentation.free.Carrier)).topologicalClosure := by
  letI : IsClosed
      ((hmrCutSubgroup
        (K := ℚ) (KS := initialProExtension) x :
          Subgroup initialGaloisGroup) : Set initialGaloisGroup) :=
    Subgroup.isClosed_topologicalClosure
      (Subgroup.normalClosure (Set.range x))
  letI : Finite (TopologicalCutQuotient x) :=
    Finite.of_equiv
      (CutQuotient x) (cutQuotientEquiv x).symm.toEquiv
  letI : DiscreteTopology (TopologicalCutQuotient x) :=
    Finite.instDiscreteTopology
  have hopen :
      IsOpen
        (((MonoidHom.ker (freeCutProjection x)) :
          Subgroup BasePresentation.free.Carrier) :
          Set BasePresentation.free.Carrier) := by
    rw [← topological_cut_projection x]
    exact
      pro_monoid_discrete
        (freeTopologicalProjection x)
        (topological_cut_continuous x)
  letI :
      (MonoidHom.ker (freeCutProjection x)).Normal :=
    MonoidHom.normal_ker (freeCutProjection x)
  let _ : Fact initialPrimeParameter.Prime := by
    dsimp [initialPrimeParameter]
    exact ⟨Nat.prime_three⟩
  exact
    ProP.finset_topological_pro
      initialPrimeParameter
      BasePresentation.free.isProP
      BasePresentation.free.generator
      BasePresentation.free.dense_generator
      (MonoidHom.ker (freeCutProjection x))
      hopen
      hkernel

/- The original compactness boundary now follows from the two smaller
mathematical inputs and the completed finite-index bookkeeping above. -/
theorem cut_generates_projection
    {k : ℕ}
    (x : HMRCutSequence)
    (hx : HMRCutAdmissible k x)
    [Finite (CutQuotient x)] :
    ∃ cutIndex : Finset ℕ,
      MonoidHom.ker (freeCutProjection x) =
        (Subgroup.normalClosure
          (selectedCutSet x hx cutIndex)).topologicalClosure := by
  have hcanonical :
      MonoidHom.ker (freeCutProjection x) =
        (Subgroup.normalClosure
          (admissibleCutSet x hx)).topologicalClosure :=
    admissible_topological_projection
      x hx
  rcases
      admissible_cut_generates
        x hx hcanonical with
    ⟨relations, hrelations, hkernel⟩
  rcases
      cut_cover_admissible
        x hx relations hrelations with
    ⟨cutIndex, hcover⟩
  refine
    ⟨cutIndex, ?_⟩
  apply
    le_antisymm
  · rw [hkernel]
    exact
      topological_selected_cut
        x hx relations cutIndex hcover
  · rw [hcanonical]
    exact
      selected_topological_admissible
        x hx cutIndex

/- The finite extraction theorem packages directly into the profinite kernel
certificate consumed by the filtered-presentation adapter. -/
theorem cut_kernel_certificate
    {k : ℕ}
    (x : HMRCutSequence)
    (hx : HMRCutAdmissible k x)
    [Finite (CutQuotient x)] :
    Nonempty (CKCert k x) := by
  classical
  rcases
      cut_generates_projection x hx with
    ⟨cutIndex, hkernel⟩
  refine
    ⟨{
      cutIndex := cutIndex
      liftedCutRelator :=
        selectedLiftedAdmissible x hx cutIndex
      lifted_cut_maps := ?_
      lifted_cut_depth := ?_
      kernel_eq := ?_ }⟩
  · intro i
    exact
      selected_lifted_maps x hx cutIndex i
  · intro i
    exact
      selected_lifted_topological
        x hx cutIndex i
  · simpa [selectedCutSet] using
      hkernel

abbrev CutAlgebraicIndex
    {k : ℕ}
    {x : HMRCutSequence}
    (C : CKCert k x) :=
  Fin proRelationRank ⊕ C.cutIndex

/- The direct pro-`3` adapter uses the arithmetic relators and selected cut
relators already stored in the profinite certificate. -/
def CKCert.proPRelator
    {k : ℕ}
    {x : HMRCutSequence}
    (C : CKCert k x) :
    CutAlgebraicIndex C → BasePresentation.free.Carrier
  | Sum.inl j => BasePresentation.relator j
  | Sum.inr i => C.liftedCutRelator i

/- The range of the combined direct pro-`3` relator family is exactly the
union appearing in the finite cut-kernel certificate. -/
theorem CKCert.pro_p_relatorrange
    {k : ℕ}
    {x : HMRCutSequence}
    (C : CKCert k x) :
    Set.range C.proPRelator =
      Set.range BasePresentation.relator ∪
        Set.range C.liftedCutRelator := by
  ext w
  constructor
  · rintro ⟨r, rfl⟩
    cases r with
    | inl j =>
        exact Or.inl ⟨j, rfl⟩
    | inr i =>
        exact Or.inr ⟨i, rfl⟩
  · intro hw
    rcases hw with ⟨j, rfl⟩ | ⟨i, rfl⟩
    · exact ⟨Sum.inl j, rfl⟩
    · exact ⟨Sum.inr i, rfl⟩

/- Arithmetic relators inject into the generator-rank-sized branch by
Shafarevich's inequality; selected cut relators retain their natural-number
labels. -/
def CKCert.pro_p_relatorcode
    {k : ℕ}
    {x : HMRCutSequence}
    (C : CKCert k x) :
    CutAlgebraicIndex C ↪
      (Fin initialProRank ⊕ ℕ) where
  toFun
    | Sum.inl j =>
        Sum.inl
          ⟨j.1, lt_of_lt_of_le j.2 initial_shafarevich_rank⟩
    | Sum.inr i =>
        Sum.inr i.1
  inj' := by
    intro a b hab
    cases a with
    | inl a =>
        cases b with
        | inl b =>
            dsimp only at hab
            apply congrArg Sum.inl
            apply Fin.ext
            simpa only [Sum.inl.injEq, Fin.mk.injEq] using hab
        | inr b =>
            cases hab
    | inr a =>
        cases b with
        | inl b =>
            cases hab
        | inr b =>
            dsimp only at hab
            apply congrArg Sum.inr
            apply Subtype.ext
            simpa only [Sum.inr.injEq] using hab

/- The direct pro-`3` depth assignment is the actual certified lower bound on
each branch. -/
def CKCert.pro_p_relatordepth
    {k : ℕ}
    {x : HMRCutSequence}
    (C : CKCert k x) :
    CutAlgebraicIndex C → ℕ
  | Sum.inl _ => 2
  | Sum.inr i => k + i.1

/- Package the finite profinite certificate directly for the reusable HMR
theorem, without constructing an ordinary free-group presentation. -/
noncomputable def CKCert.prop_finshadow_relbound
    {k : ℕ}
    {x : HMRCutSequence}
    (C : CKCert k x) :
    HPGs.PSRel
      initialPrimeParameter initialProRank k (CutQuotient x) where
  fact_prime := ⟨Nat.prime_three⟩
  target := TopologicalCutQuotient x
  targetGroup := inferInstance
  targetTopologicalSpace := inferInstance
  free := BasePresentation.free
  quotientMap := freeTopologicalProjection x
  quotientMap_continuous :=
    topological_cut_continuous x
  quotientMap_surjective :=
    topological_cut_surjective x
  targetEquiv := cutQuotientEquiv x
  RelatorIndex := CutAlgebraicIndex C
  fintype_relator := inferInstance
  relator := C.proPRelator
  kernel_eq := by
    rw [
      topological_cut_projection,
      C.kernel_eq,
      C.pro_p_relatorrange
    ]
  relatorCode := C.pro_p_relatorcode
  depth := C.pro_p_relatordepth
  relator_depth := by
    intro r
    cases r with
    | inl j =>
        exact
          minimal_pro_presentation j
    | inr i =>
        exact
          C.lifted_cut_depth i
  depth_ge := by
    intro r
    cases r <;> simp [CKCert.pro_p_relatorcode,
      CKCert.pro_p_relatordepth]

/- For one admissible sequence, the profinite kernel certificate packages
directly into the closed-normal-generation relation bound required by the
pro-`3` HMR theorem. -/
theorem pro_shadow_admissible
    {k : ℕ}
    (x : HMRCutSequence)
    (hx : HMRCutAdmissible k x) :
    HPGs.ProShadowBound
      initialPrimeParameter initialProRank k (CutQuotient x) := by
  intro hfinite
  letI : Finite (CutQuotient x) :=
    hfinite
  rcases cut_kernel_certificate x hx with ⟨C⟩
  exact
    ⟨C.prop_finshadow_relbound⟩

end HSScaffo

theorem hmr_pro_shadow :
    hmrCuttingSystem.PropFinshadowRelbounds
      initialProRank := by
  intro k x hx
  exact
    HSScaffo.pro_shadow_admissible x hx

/- The GS cutting criterion is now a proved consequence of the explicit Shafarevich relation
bound, the geometric tail estimate, and the reusable rational GS contradiction. -/
theorem cutting_criterion_parameters
    (c : HParame) :
    HMRGSCuttingCriterion c := by
  intro k hkTwo hkTail x hx
  have hxGeneric : hmrCuttingSystem.admissible k x := by
    simpa [hmrCuttingSystem] using hx
  simpa [hmrCuttingSystem] using
    HPGs.CSystem.infinitequot_prop_tailbound
      hmrCuttingSystem c.toGeneric hmr_pro_shadow
      hkTwo ((hmr_cutting_generic c k).mp hkTail) x hxGeneric

end TBluepr
end Submission
