import Submission.Group.Edmonton.TorsionGeneratedGroups

/-!
# The Edmonton Notes on Nilpotent Groups: commutator identities

Hall uses the element commutator

`[x,y] = x⁻¹ y⁻¹ x y`

and the right-conjugation notation `x^y = y⁻¹ x y`.  Mathlib's
`commutatorElement` uses the inverse convention `x y x⁻¹ y⁻¹`, so the
element-level identities in this section are stated with the explicit
definitions below.  The subgroup generated by either convention is the same.
-/

namespace Submission
namespace Edmonton

open Group
open scoped commutatorElement

universe u

variable {G : Type u} [Group G]

/-- Hall's right conjugate `x^y = y⁻¹ x y`. -/
def hallConjugate (x y : G) : G :=
  y⁻¹ * x * y

/-- Hall's element commutator `[x,y] = x⁻¹ y⁻¹ x y`. -/
def hallCommutator (x y : G) : G :=
  x⁻¹ * y⁻¹ * x * y

/-- Hall's commutator is Mathlib's commutator of the inverses. -/
lemma hall_element_inv (x y : G) :
    hallCommutator x y = ⁅x⁻¹, y⁻¹⁆ := by
  simp [hallCommutator, commutatorElement_def, mul_assoc]

/-- Mathlib's commutator is Hall's commutator of the inverses. -/
lemma commutator_element_inv (x y : G) :
    ⁅x, y⁆ = hallCommutator x⁻¹ y⁻¹ := by
  simp [hallCommutator, commutatorElement_def, mul_assoc]

/-- **Hall, Lemma 2.1, first identity.** -/
theorem commutator_mul_right (x y z : G) :
    hallCommutator x (y * z) =
      hallCommutator x z * hallConjugate (hallCommutator x y) z := by
  simp [hallCommutator, hallConjugate, mul_assoc]

/-- **Hall, Lemma 2.1, second identity.** -/
theorem commutator_mul_left (x y z : G) :
    hallCommutator (x * y) z =
      hallConjugate (hallCommutator x z) y * hallCommutator y z := by
  simp [hallCommutator, hallConjugate, mul_assoc]

/-- **Hall, Lemma 2.1.** The two elementary commutator product identities. -/
theorem commutator_product_identities (x y z : G) :
    hallCommutator x (y * z) =
        hallCommutator x z * hallConjugate (hallCommutator x y) z ∧
      hallCommutator (x * y) z =
        hallConjugate (hallCommutator x z) y * hallCommutator y z :=
  ⟨commutator_mul_right x y z, commutator_mul_left x y z⟩

/-- The first equality in Hall's note following Lemma 2.1.  The printed
left-hand side `[y,z]` is necessarily a typo; the identities have left-hand
side `[y,x]`. -/
lemma swap_conjugate_inv (x y : G) :
    hallCommutator y x =
      hallConjugate (hallCommutator x y⁻¹) y := by
  simp [hallCommutator, hallConjugate, mul_assoc]

/-- The second equality in Hall's note following Lemma 2.1. -/
lemma conjugate_inv_left (x y : G) :
    hallCommutator y x =
      hallConjugate (hallCommutator x⁻¹ y) x := by
  simp [hallCommutator, hallConjugate, mul_assoc]

/-- The third equality in Hall's note following Lemma 2.1. -/
lemma swap_conjugate_inverses (x y : G) :
    hallCommutator y x =
      hallConjugate (hallCommutator y⁻¹ x⁻¹) (x * y) := by
  simp [hallCommutator, hallConjugate, mul_assoc]

/-- The final equality in Hall's note following Lemma 2.1. -/
lemma commutator_swap_inv (x y : G) :
    hallCommutator y x = (hallCommutator x y)⁻¹ := by
  simp [hallCommutator, mul_assoc]

/-- Hall's commutator convention generates the same subgroup commutator as
Mathlib's convention. -/
lemma hall_commutator
    {X Y : Subgroup G} {x y : G} (hx : x ∈ X) (hy : y ∈ Y) :
    hallCommutator x y ∈ ⁅X, Y⁆ := by
  rw [hall_element_inv]
  exact Subgroup.commutator_mem_commutator (X.inv_mem hx) (Y.inv_mem hy)

/-- Conjugation by an element of the left input preserves the subgroup
commutator. -/
lemma conjugate_commutator_left
    {X Y : Subgroup G} {g c : G} (hg : g ∈ X) (hc : c ∈ ⁅X, Y⁆) :
    g * c * g⁻¹ ∈ ⁅X, Y⁆ := by
  rw [Subgroup.commutator_def] at hc
  refine Subgroup.closure_induction ?_ ?_ ?_ ?_ hc
  · rintro _ ⟨x, hx, y, hy, rfl⟩
    rw [commutator_element_inv]
    have hleft :
        hallCommutator (x⁻¹ * g⁻¹) y⁻¹ ∈ ⁅X, Y⁆ :=
      hall_commutator
        (X.mul_mem (X.inv_mem hx) (X.inv_mem hg)) (Y.inv_mem hy)
    have hright :
        hallCommutator g⁻¹ y⁻¹ ∈ ⁅X, Y⁆ :=
      hall_commutator (X.inv_mem hg) (Y.inv_mem hy)
    have hprod := (⁅X, Y⁆).mul_mem hleft ((⁅X, Y⁆).inv_mem hright)
    rw [commutator_mul_left, mul_inv_cancel_right] at hprod
    simpa [hallConjugate] using hprod
  · simp
  · intro a b _ _ ha hb
    rw [← conj_mul]
    exact (⁅X, Y⁆).mul_mem ha hb
  · intro a _ ha
    rw [← conj_inv]
    exact (⁅X, Y⁆).inv_mem ha

/-- Conjugation by an element of the right input preserves the subgroup
commutator. -/
lemma conjugate_commutator_right
    {X Y : Subgroup G} {g c : G} (hg : g ∈ Y) (hc : c ∈ ⁅X, Y⁆) :
    g * c * g⁻¹ ∈ ⁅X, Y⁆ := by
  rw [Subgroup.commutator_def] at hc
  refine Subgroup.closure_induction ?_ ?_ ?_ ?_ hc
  · rintro _ ⟨x, hx, y, hy, rfl⟩
    rw [commutator_element_inv]
    have hleft :
        hallCommutator x⁻¹ (y⁻¹ * g⁻¹) ∈ ⁅X, Y⁆ :=
      hall_commutator
        (X.inv_mem hx) (Y.mul_mem (Y.inv_mem hy) (Y.inv_mem hg))
    have hright :
        hallCommutator x⁻¹ g⁻¹ ∈ ⁅X, Y⁆ :=
      hall_commutator (X.inv_mem hx) (Y.inv_mem hg)
    have hprod := (⁅X, Y⁆).mul_mem ((⁅X, Y⁆).inv_mem hright) hleft
    rw [commutator_mul_right, inv_mul_cancel_left] at hprod
    simpa [hallConjugate] using hprod
  · simp
  · intro a b _ _ ha hb
    rw [← conj_mul]
    exact (⁅X, Y⁆).mul_mem ha hb
  · intro a _ ha
    rw [← conj_inv]
    exact (⁅X, Y⁆).inv_mem ha

/-- Every element of the left input normalizes the subgroup commutator. -/
lemma normalizer_commutator_left (X Y : Subgroup G) :
    X ≤ Subgroup.normalizer (⁅X, Y⁆ : Subgroup G) := by
  intro g hg
  rw [Subgroup.mem_normalizer_iff]
  intro c
  constructor
  · exact conjugate_commutator_left hg
  · intro hc
    have h :=
      conjugate_commutator_left (X.inv_mem hg) hc
    simpa [mul_assoc] using h

/-- Every element of the right input normalizes the subgroup commutator. -/
lemma normalizer_commutator_right (X Y : Subgroup G) :
    Y ≤ Subgroup.normalizer (⁅X, Y⁆ : Subgroup G) := by
  intro g hg
  rw [Subgroup.mem_normalizer_iff]
  intro c
  constructor
  · exact conjugate_commutator_right hg
  · intro hc
    have h :=
      conjugate_commutator_right (Y.inv_mem hg) hc
    simpa [mul_assoc] using h

/-- The subgroup commutator of two subgroups is normal in the subgroup they
generate. -/
theorem commutator_sup (X Y : Subgroup G) :
    (⁅X, Y⁆.subgroupOf (X ⊔ Y)).Normal := by
  rw [Subgroup.normal_subgroupOf_iff_le_normalizer
    (Subgroup.commutator_mono le_sup_left le_sup_right
      |>.trans (X ⊔ Y).commutator_le_self)]
  exact sup_le (normalizer_commutator_left X Y)
    (normalizer_commutator_right X Y)

end Edmonton
end Submission
