import Towers.Group.ProPPresentation


/-!
# Finite normal generation in finitely generated pro-p groups

This file records the topological Schreier--Frattini input used when a
closed-normal relation family presents an open normal subgroup of a finitely
generated pro-`p` group.
-/

open scoped Pointwise Topology IsMulCommutative

noncomputable section

namespace Towers
namespace ProP

universe u

private lemma topological_frattini_fg
    (p : ℕ) [Fact p.Prime]
    {K L : Type u} [Group K] [TopologicalSpace K] [IsTopologicalGroup K]
    [T2Space K] [Group L] [Group.FG L]
    (ι : L →* K)
    (hι : DenseRange ι) :
    IsOpen
      (((modPFrattini p K).topologicalClosure : Subgroup K) : Set K) := by
  let Φ : Subgroup K := modPFrattini p K
  let C : Subgroup K := Φ.topologicalClosure
  letI : Φ.Normal := by
    dsimp [Φ]
    infer_instance
  letI : C.Normal := by
    dsimp [C]
    exact Subgroup.is_normal_topologicalClosure Φ
  letI : IsClosed (C : Set K) := by
    dsimp [C]
    exact Subgroup.isClosed_topologicalClosure Φ
  let q : K →* K ⧸ C := QuotientGroup.mk' C
  let r : L →* K ⧸ C := q.comp ι
  let P : Subgroup (K ⧸ C) := r.range
  letI : IsMulCommutative (K ⧸ C) :=
    (Subgroup.Normal.quotient_commutative_iff_commutator_le
      (N := C)).2
      ((le_sup_right : _root_.commutator K ≤ modPFrattini p K).trans
        Φ.le_topologicalClosure)
  letI : CommGroup (K ⧸ C) := inferInstance
  have hpow : ∀ y : K ⧸ C, y ^ p = 1 := by
    intro y
    refine QuotientGroup.induction_on y ?_
    intro k
    apply (QuotientGroup.eq_one_iff (N := C) (k ^ p)).2
    exact Φ.le_topologicalClosure (pow_mod_frattini p K k)
  haveI : Group.FG P := by
    dsimp [P]
    infer_instance
  have hP_torsion : Monoid.IsTorsion P := by
    intro y
    exact
      isOfFinOrder_iff_pow_eq_one.mpr
        ⟨p, (Fact.out : Nat.Prime p).pos, by
          apply Subtype.ext
          exact hpow y⟩
  letI : Finite P :=
    CommGroup.finite_of_fg_torsion P hP_torsion
  have hr_dense : DenseRange r := by
    exact
      (QuotientGroup.mk'_surjective C).denseRange.comp hι
        QuotientGroup.continuous_mk
  have hP_dense :
      closure ((P : Subgroup (K ⧸ C)) : Set (K ⧸ C)) =
        Set.univ := by
    simpa [P, r, q] using hr_dense.closure_range
  letI : Finite (K ⧸ C) :=
    pro_dense_subgroup P hP_dense
  letI : C.FiniteIndex :=
    Subgroup.finiteIndex_of_finite_quotient
  exact C.isOpen_of_isClosed_of_finiteIndex inferInstance

/--
An open normal subgroup of a finitely generated pro-`p` group is topologically
normally generated by finitely many members of any closed-normal generating
family.

This is the remaining topological Schreier--Frattini input for finite
relation extraction.  Compactness of the ambient group and openness of the
subgroup are not sufficient on their own: the proof must use finite-rank
Frattini control for the open subgroup.
-/
theorem finset_topological_pro
    (p : ℕ) [Fact p.Prime]
    {G : Type u} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    [CompactSpace G] [TotallyDisconnectedSpace G]
    (_hProP : ProPGroup p G)
    {d : ℕ} (_s : Fin d → G)
    (_hs : TopologicallyGenerates _s)
    (K : Subgroup G) [K.Normal]
    (_hKopen : IsOpen ((K : Subgroup G) : Set G))
    {S : Set G}
    (hKS :
      K = (Subgroup.normalClosure S).topologicalClosure) :
    ∃ T : Finset G,
      (∀ g, g ∈ T → g ∈ S) ∧
      K =
        (Subgroup.normalClosure
          (T : Set G)).topologicalClosure := by
  classical
  letI : T2Space G :=
    t_space_disconnected G
  have hKclosed : IsClosed (K : Set G) :=
    K.isClosed_of_isOpen _hKopen
  letI : CompactSpace K :=
    isCompact_iff_compactSpace.mp hKclosed.isCompact
  let H : Subgroup G := Subgroup.closure (Set.range _s)
  have hHdense : Dense (H : Set G) := by
    rw [dense_iff_closure_eq]
    simpa [H, Subgroup.topologicalClosure_coe] using
      congrArg (fun L : Subgroup G => (L : Set G)) _hs
  letI : Finite (G ⧸ K) :=
    K.quotient_finite_of_isOpen _hKopen
  letI : K.FiniteIndex :=
    Subgroup.finiteIndex_of_finite_quotient
  let L : Subgroup H := K.subgroupOf H
  haveI : Group.FG H := by
    dsimp [H]
    infer_instance
  haveI : L.FiniteIndex := by
    dsimp [L]
    infer_instance
  haveI : Group.FG L := by
    infer_instance
  let ι : L →* K :=
    { toFun := fun x => ⟨x, x.property⟩
      map_one' := rfl
      map_mul' := fun _ _ => rfl }
  have hιdense : DenseRange ι := by
    rw [DenseRange, dense_iff_closure_eq]
    apply Set.eq_univ_of_forall
    intro k
    rw [closure_subtype]
    have hk :
        (k : G) ∈ closure ((K : Set G) ∩ (H : Set G)) :=
      hHdense.open_subset_closure_inter _hKopen k.property
    apply closure_mono _ hk
    rintro g ⟨hgK, hgH⟩
    refine ⟨⟨g, hgK⟩, ?_, rfl⟩
    exact ⟨⟨⟨g, hgH⟩, hgK⟩, rfl⟩
  let Φ : Subgroup K := modPFrattini p K
  let CΦ : Subgroup K := Φ.topologicalClosure
  have hCΦopen : IsOpen (CΦ : Set K) := by
    dsimp [CΦ, Φ]
    exact
      topological_frattini_fg
        p ι hιdense
  let M : Subgroup G := CΦ.map K.subtype
  have hMopen : IsOpen (M : Set G) := by
    rw [Subgroup.coe_map]
    exact _hKopen.isOpenMap_subtype_val _ hCΦopen
  have hΦchar : Φ.Characteristic := by
    dsimp [Φ]
    rw [← filtration_p_frattini (p := p) K]
    exact zassenhausFiltration_characteristic p K 2
  letI : M.Normal := by
    dsimp [M]
    constructor
    intro n hn g
    rcases hn with ⟨n, hn, rfl⟩
    refine ⟨MulAut.conjNormal g n, ?_, by simp⟩
    apply map_mem_closure
      (show Continuous (fun x : K => MulAut.conjNormal g x) by
        apply Continuous.subtype_mk
        simpa only [MulAut.conjNormal_apply] using
          (IsTopologicalGroup.continuous_conj g).comp
            continuous_subtype_val)
      hn
    intro m hm
    change
      m ∈ Φ.comap (MulAut.conjNormal g).toMonoidHom
    rw [hΦchar.fixed (MulAut.conjNormal g)]
    exact hm
  let NΦ : OpenNormalSubgroup G :=
    { toOpenSubgroup := ⟨M, hMopen⟩
      isNormal' := inferInstance }
  let q : G →* G ⧸ M := QuotientGroup.mk' M
  let R : Subgroup (G ⧸ M) := Subgroup.normalClosure (q '' S)
  have hS_le_K : S ⊆ (K : Set G) := by
    intro g hg
    rw [hKS]
    exact
      (Subgroup.normalClosure S).le_topologicalClosure
        (Subgroup.subset_normalClosure hg)
  have hKmap : K.map q = R := by
    apply le_antisymm
    · intro y hy
      rcases hy with ⟨k, hk, rfl⟩
      have hRclosed : IsClosed (R : Set (G ⧸ M)) := by
        letI : DiscreteTopology (G ⧸ M) :=
          pro_discrete_topology NΦ
        exact isClosed_discrete _
      have hpreclosed : IsClosed ((R.comap q : Subgroup G) : Set G) := by
        change IsClosed ((fun x : G => q x) ⁻¹' (R : Set (G ⧸ M)))
        exact hRclosed.preimage QuotientGroup.continuous_mk
      have hnormal_le : Subgroup.normalClosure S ≤ R.comap q := by
        apply Subgroup.normalClosure_le_normal
        intro s hs
        exact Subgroup.subset_normalClosure ⟨s, hs, rfl⟩
      have hK_le_pre : K ≤ R.comap q := by
        rw [hKS]
        exact
          (Subgroup.normalClosure S).topologicalClosure_minimal
            hnormal_le hpreclosed
      exact hK_le_pre hk
    · apply Subgroup.normalClosure_le_normal
      rintro y ⟨s, hs, rfl⟩
      exact Subgroup.mem_map_of_mem q (hS_le_K hs)
  letI : Finite (G ⧸ M) :=
    pro_p_open NΦ
  have hqSfinite : (q '' S).Finite := Set.toFinite _
  rcases
      hqSfinite.exists_subset_finite_image_eq
        (s := S) (f := q) (u := q '' S) (by rfl) with
    ⟨t, htS, htfinite, hqt⟩
  let T : Finset G := htfinite.toFinset
  have hTsubset : ∀ g, g ∈ T → g ∈ S := by
    intro g hg
    apply htS
    simpa [T] using hg
  refine ⟨T, hTsubset, ?_⟩
  let C : Subgroup G :=
    (Subgroup.normalClosure (T : Set G)).topologicalClosure
  have hT_le_K : (T : Set G) ⊆ (K : Set G) := by
    intro g hg
    exact hS_le_K (hTsubset g hg)
  have hC_le_K : C ≤ K := by
    dsimp [C]
    exact
      (Subgroup.normalClosure (T : Set G)).topologicalClosure_minimal
        (Subgroup.normalClosure_le_normal hT_le_K) hKclosed
  have hK_le_CM : K ≤ C ⊔ M := by
    intro k hk
    have hqk : q k ∈ K.map q :=
      Subgroup.mem_map_of_mem q hk
    rw [hKmap] at hqk
    change q k ∈ Subgroup.normalClosure (q '' S) at hqk
    rw [← hqt] at hqk
    have hqkC : q k ∈ C.map q := by
      apply
        (Subgroup.map_mono
          (Subgroup.normalClosure (T : Set G)).le_topologicalClosure)
      rw [Subgroup.map_normalClosure (T : Set G) q
        (QuotientGroup.mk'_surjective M)]
      simpa [T] using hqk
    rcases hqkC with ⟨c, hc, hck⟩
    have hcik : c⁻¹ * k ∈ M := by
      apply (QuotientGroup.eq_one_iff (N := M) (c⁻¹ * k)).mp
      simpa using congrArg (fun y => y⁻¹ * q k) hck
    have hmem : c * (c⁻¹ * k) ∈ C ⊔ M :=
      (C ⊔ M).mul_mem
        ((show C ≤ C ⊔ M from le_sup_left) hc)
        ((show M ≤ C ⊔ M from le_sup_right) hcik)
    simpa using hmem
  let CK : Subgroup K := C.subgroupOf K
  have hCK_sup_CΦ : CK ⊔ CΦ = ⊤ := by
    apply (Subgroup.map_subtype_inj).mp
    have hmaptop : (⊤ : Subgroup K).map K.subtype = K := by
      rw [← MonoidHom.range_eq_map, K.range_subtype]
    rw [Subgroup.map_sup, hmaptop]
    dsimp [CK, M] at hK_le_CM ⊢
    rw [Subgroup.map_subgroupOf_eq_of_le hC_le_K]
    exact
      le_antisymm
        (sup_le hC_le_K (Subgroup.map_subtype_le CΦ))
        hK_le_CM
  symm
  apply le_antisymm hC_le_K
  by_contra hKnotle
  have hCne : C ≠ K := by
    intro hCK
    apply hKnotle
    rw [← hCK]
  have hCKne : CK ≠ ⊤ := by
    intro hCK
    apply hCne
    apply le_antisymm hC_le_K
    intro k hk
    have hk' : (⟨k, hk⟩ : K) ∈ CK := by
      rw [hCK]
      exact Subgroup.mem_top _
    exact hk'
  obtain ⟨x, _hx, hxCK⟩ :=
    SetLike.exists_of_lt (lt_top_iff_ne_top.mpr hCKne)
  have hxC : (x : G) ∉ C := hxCK
  have hCclosed : IsClosed (C : Set G) := by
    dsimp [C]
    exact
      Subgroup.isClosed_topologicalClosure
        (Subgroup.normalClosure (T : Set G))
  rcases
      separate_sets_disconnected
        hCclosed (x : G) hxC with
    ⟨N, hxN⟩
  letI : DiscreteTopology (G ⧸ N.toSubgroup) :=
    pro_discrete_topology N
  letI : Finite (G ⧸ N.toSubgroup) :=
    pro_p_open N
  let qN : G →* G ⧸ N.toSubgroup :=
    QuotientGroup.mk' N.toSubgroup
  let f₀ : K →* G ⧸ N.toSubgroup := qN.comp K.subtype
  let B : Subgroup (G ⧸ N.toSubgroup) := f₀.range
  let f : K →* B := f₀.rangeRestrict
  let A : Subgroup B := CK.map f
  have hAne : A ≠ ⊤ := by
    intro hA
    have hfx : f x ∈ A := by
      rw [hA]
      exact Subgroup.mem_top _
    rcases hfx with ⟨c, hc, hcx⟩
    apply hxN
    refine ⟨(c : G), hc, ?_⟩
    exact congrArg Subtype.val hcx
  have hfcont : Continuous (fun k : K => f k) := by
    have hf₀cont : Continuous (fun k : K => f₀ k) := by
      dsimp [f₀, qN]
      exact
        (pro_open_continuous N).comp
          continuous_subtype_val
    have hf₀mem : ∀ k : K, f₀ k ∈ B := by
      intro k
      exact ⟨k, rfl⟩
    simpa [f] using hf₀cont.codRestrict hf₀mem
  have hCΦmap : CΦ.map f ≤ modPFrattini p B := by
    rw [Subgroup.map_le_iff_le_comap]
    change Φ.topologicalClosure ≤ _
    apply Φ.topologicalClosure_minimal
    · exact mod_frattini_comap (p := p) f
    · change
        IsClosed
          ((fun k : K => f k) ⁻¹'
            (((modPFrattini p B : Subgroup B) : Set B)))
      exact (isClosed_discrete _).preimage hfcont
  have hBProP : IsPGroup p B :=
    (_hProP N).to_subgroup B
  have hsupB : A ⊔ modPFrattini p B = ⊤ := by
    apply top_unique
    intro b _hb
    rcases f₀.rangeRestrict_surjective b with ⟨k, rfl⟩
    have hk : k ∈ CK ⊔ CΦ := by
      rw [hCK_sup_CΦ]
      exact Subgroup.mem_top _
    have hfk : f k ∈ A ⊔ CΦ.map f := by
      rw [← Subgroup.map_sup]
      exact Subgroup.mem_map_of_mem f hk
    exact (sup_le_sup le_rfl hCΦmap) hfk
  have hΦB_le_frattini : modPFrattini p B ≤ frattini B := by
    dsimp [modPFrattini]
    apply sup_le
    · dsimp [pPowerSubgroup]
      apply Subgroup.normalClosure_le_normal
      rintro y ⟨b, rfl⟩
      exact p_group_frattini hBProP b
    · rw [_root_.commutator_eq_closure]
      apply (Subgroup.closure_le (frattini B)).2
      intro y hy
      rcases hy with ⟨a, b, rfl⟩
      exact p_commutator_frattini hBProP a b
  have hsup_frattini : A ⊔ frattini B = ⊤ := by
    apply le_antisymm le_top
    rw [← hsupB]
    exact sup_le_sup le_rfl hΦB_le_frattini
  exact hAne (frattini_nongenerating hsup_frattini)

end ProP
end Towers
