import Submission.ClassField.KummerNormIndex.SUnitExtension
import Submission.ClassField.KummerNormIndex.OutsideUnramified

/-!
# Ramification of the S-unit Kummer extension

The Kummer extension `K[U(S)^(1/p)]` occurring before Lemma VII.6.2 is
unramified away from `S`.  Indeed, outside `S`, every chosen radical has
valuation one and `p` is a unit.  The inertia argument from Proposition
VII.6.10 therefore fixes every radical, hence fixes the field they generate.
-/

namespace Submission.CField.KNIndex

open IsDedekindDomain NumberField
open Submission.NumberTheory.Milne
open Submission.CField.Ideles
open Submission.CField.KTheory
open Submission.CField.NIndex

noncomputable section

universe u

private abbrev OK (K : Type u) [Field K] [NumberField K] :=
  NumberField.RingOfIntegers K

/-- An extension generated by radicals of `S`-units is unramified at every
finite prime lying outside `S`, provided `S` contains the finite places
dividing `p`.  The index type may be any family of generators. -/
theorem unramified_generated_radicals
    (p : ℕ) (hp : p.Prime)
    (K M : Type u) [Field K] [NumberField K]
    [Field M] [NumberField M] [Algebra K M]
    [FiniteDimensional K M] [IsGalois K M]
    (S : Finset (NumberFieldPlace K))
    (hDividing : ∀ v,
      normalizedPlaceValue K v (p : K) ≠ 1 → v ∈ S)
    {ι : Type*} (b : ι → Kˣ) (root : ι → M)
    (hrootPow : ∀ i, root i ^ p = algebraMap K M (((b i : Kˣ) : K)))
    (hUnit : ∀ i (P : FinitePrime K),
      (Sum.inl P : NumberFieldPlace K) ∉ S → P.valuation K (b i : K) = 1)
    (hgen : IntermediateField.adjoin K (Set.range root) = ⊤)
    (Q : FinitePrime M)
    (hQ : (Sum.inl (Q.under (OK K)) : NumberFieldPlace K) ∉ S) :
    Algebra.IsUnramifiedAt (OK K) Q.asIdeal := by
  classical
  let P : FinitePrime K := Q.under (OK K)
  have hpValue :
      normalizedPlaceValue K (Sum.inl P) (p : K) = 1 := by
    by_contra hne
    exact hQ (hDividing (Sum.inl P) hne)
  have hpP : P.valuation K (p : K) = 1 :=
    valuation_normalized_value K P hpValue
  letI : P.asIdeal.IsMaximal := P.isMaximal
  letI : Q.asIdeal.IsMaximal := Q.isMaximal
  letI : Q.asIdeal.LiesOver P.asIdeal := by
    refine ⟨?_⟩
    rfl
  letI : Field (OK K ⧸ P.asIdeal) := Ideal.Quotient.field P.asIdeal
  letI : Field (OK M ⧸ Q.asIdeal) := Ideal.Quotient.field Q.asIdeal
  letI : Finite (OK K ⧸ P.asIdeal) :=
    Ring.HasFiniteQuotients.finiteQuotient P.ne_bot
  letI : Finite (OK M ⧸ Q.asIdeal) :=
    Ring.HasFiniteQuotients.finiteQuotient Q.ne_bot
  letI : Algebra.IsSeparable (OK K ⧸ P.asIdeal) (OK M ⧸ Q.asIdeal) :=
    Algebra.IsAlgebraic.isSeparable_of_perfectField
  letI : IsGaloisGroup Gal(M/K) (OK K) (OK M) :=
    IsGaloisGroup.of_isFractionRing Gal(M/K) (OK K) (OK M) K M
  have hpPmem : (p : OK K) ∉ P.asIdeal := by
    rw [← P.intValuation_eq_one_iff,
      ← P.valuation_of_algebraMap (K := K)]
    exact hpP
  have hpQmem : (p : OK M) ∉ Q.asIdeal := by
    intro hpQ
    apply hpPmem
    change algebraMap (OK K) (OK M) (p : OK K) ∈ Q.asIdeal
    simpa only [map_natCast] using hpQ
  have hrootVal : ∀ i, Q.valuation M (root i) = 1 := by
    intro i
    apply (pow_eq_one_iff_left hp.ne_zero).mp
    rw [← map_pow, hrootPow i,
      valuation_ramification_idx P Q,
      hUnit i P hQ, one_pow]
  have hgenAlg : Algebra.adjoin K (Set.range root) = ⊤ := by
    rw [← IntermediateField.adjoin_toSubalgebra_of_isAlgebraic]
    · have h := congrArg IntermediateField.toSubalgebra hgen
      simpa using h
    · intro x _
      exact IsAlgebraic.of_finite K x
  have hinertia : Q.asIdeal.inertia Gal(M/K) = ⊥ := by
    apply le_antisymm
    · intro sigma hsigma
      rw [Subgroup.mem_bot]
      let sigmaI : Q.asIdeal.inertia Gal(M/K) := ⟨sigma, hsigma⟩
      have hfix : ∀ i, sigma (root i) = root i := by
        intro i
        exact inertia_fixes_radical K M p hp.ne_zero (b i) (root i)
          (hrootPow i) Q hpQmem (hrootVal i) sigmaI
      have heq : sigma.toAlgHom = (1 : Gal(M/K)).toAlgHom := by
        apply AlgHom.ext_of_adjoin_eq_top hgenAlg
        intro x hx
        obtain ⟨i, rfl⟩ := hx
        simpa only [AlgEquiv.one_apply] using hfix i
      exact AlgEquiv.ext fun x ↦ DFunLike.congr_fun heq x
    · exact bot_le
  have hramification :
      Ideal.ramificationIdx P.asIdeal Q.asIdeal = 1 := by
    calc
      Ideal.ramificationIdx P.asIdeal Q.asIdeal =
          Ideal.ramificationIdxIn P.asIdeal (OK M) :=
        (Ideal.ramificationIdxIn_eq_ramificationIdx
          P.asIdeal Q.asIdeal Gal(M/K)).symm
      _ = Nat.card (Q.asIdeal.inertia Gal(M/K)) :=
        (Ideal.card_inertia_eq_ramificationIdxIn
          (G := Gal(M/K)) P.asIdeal P.ne_bot Q.asIdeal).symm
      _ = 1 := by rw [hinertia]; simp
  exact (unramified_ramification_idx
    P.asIdeal Q.asIdeal Q.ne_bot).2 hramification

/-- The preceding generator-wise criterion specialized to the literal
identity `M = K[U(S)^(1/p)]`. -/
theorem s_pth_roots
    (p : ℕ) (hp : p.Prime)
    (K M : Type u) [Field K] [NumberField K]
    [Field M] [NumberField M] [Algebra K M]
    [FiniteDimensional K M] [IsGalois K M]
    (S : Finset (NumberFieldPlace K))
    (hDividing : ∀ v,
      normalizedPlaceValue K v (p : K) ≠ 1 → v ∈ S)
    (hGenerated : SPthRoots K M p S)
    (Q : FinitePrime M)
    (hQ : (Sum.inl (Q.under (OK K)) : NumberFieldPlace K) ∉ S) :
    Algebra.IsUnramifiedAt (OK K) Q.asIdeal := by
  obtain ⟨root, hrootPow, hgen⟩ := hGenerated
  exact unramified_generated_radicals p hp K M S hDividing
    (fun a : ArithmeticSUnits K (finitePrimePart K S) ↦ (a : Kˣ)) root hrootPow
    (fun a P hP ↦ a.property P hP) hgen Q hQ

section ArbitraryKummerField

variable (K Omega : Type u) [Field K] [NumberField K]
  [Field Omega] [Algebra K Omega] [IsAlgClosure K Omega]

/-- A finite Kummer field is unramified outside any set containing the
divisors of `p` and the supports of its chosen power-class representatives. -/
theorem outside_representatives_s
    (p : ℕ) (hp : p.Prime) (hroots : (primitiveRoots p K).Nonempty)
    (B : PCSubgro K p)
    (S : Finset (NumberFieldPlace K))
    (hDividing : ∀ v,
      normalizedPlaceValue K v (p : K) ≠ 1 → v ∈ S)
    (hRepresentatives : ∀ b : B.carrier,
      powerClassRepresentative K p b.1 ∈
        Set.unit (finitePrimePart K S) K) :
    letI : FiniteDimensional K (kummerField K Omega p hp.pos B) :=
      dimensional_kummer_field K Omega p hp.pos B
    letI : NumberField (kummerField K Omega p hp.pos B) :=
      NumberField.of_module_finite K (kummerField K Omega p hp.pos B)
    ∀ Q : FinitePrime (kummerField K Omega p hp.pos B),
      (Sum.inl (Q.under (OK K)) : NumberFieldPlace K) ∉ S →
        Algebra.IsUnramifiedAt (OK K) Q.asIdeal := by
  letI : FiniteDimensional K (kummerField K Omega p hp.pos B) :=
    dimensional_kummer_field K Omega p hp.pos B
  letI : NumberField (kummerField K Omega p hp.pos B) :=
    NumberField.of_module_finite K (kummerField K Omega p hp.pos B)
  let zeta : K := hroots.choose
  have hzeta : IsPrimitiveRoot zeta p :=
    (mem_primitiveRoots hp.pos).mp hroots.choose_spec
  letI : IsGalois K (kummerField K Omega p hp.pos B) :=
    kummer_galois K Omega p hp.pos hzeta B
  let root : B.carrier → kummerField K Omega p hp.pos B := fun b ↦
    ⟨kummerRoot K Omega p hp.pos b.1,
      kummer_root_field K Omega p hp.pos B b⟩
  have hrootPow : ∀ b,
      root b ^ p = algebraMap K (kummerField K Omega p hp.pos B)
        (((powerClassRepresentative K p b.1 : Kˣ) : K)) := by
    intro b
    apply Subtype.ext
    exact kummerRoot_pow K Omega p hp.pos b.1
  have hgen : IntermediateField.adjoin K (Set.range root) = ⊤ := by
    exact adjoin_kummer_top K Omega p hp.pos B
  intro Q hQ
  exact unramified_generated_radicals p hp K
    (kummerField K Omega p hp.pos B) S hDividing
    (fun b : B.carrier ↦ powerClassRepresentative K p b.1) root
    hrootPow (fun b P hP ↦ hRepresentatives b P hP) hgen Q hQ

end ArbitraryKummerField

section ConstructedField

variable (K Omega : Type u) [Field K] [NumberField K]
  [Field Omega] [Algebra K Omega] [IsAlgClosure K Omega]

/-- The literal field `K[U(S)^(1/p)]` constructed from the S-unit power
classes is unramified outside `S`. -/
theorem s_kummer_outside
    (p : ℕ) (hp : p.Prime) (hroots : (primitiveRoots p K).Nonempty)
    (S : Finset (NumberFieldPlace K))
    (hInfinite : ContainsAllPlaces K S)
    (hDividing : ∀ v,
      normalizedPlaceValue K v (p : K) ≠ 1 → v ∈ S) :
    letI : FiniteDimensional K
        (sKummerField K Omega p hp hroots S hInfinite) :=
      sKummerDimensional K Omega p hp hroots S hInfinite
    letI : NumberField
        (sKummerField K Omega p hp hroots S hInfinite) :=
      sKummerNumber K Omega p hp hroots S hInfinite
    ∀ Q : FinitePrime
        (sKummerField K Omega p hp hroots S hInfinite),
      (Sum.inl (Q.under (OK K)) : NumberFieldPlace K) ∉ S →
        Algebra.IsUnramifiedAt (OK K) Q.asIdeal := by
  letI : FiniteDimensional K
      (sKummerField K Omega p hp hroots S hInfinite) :=
    sKummerDimensional K Omega p hp hroots S hInfinite
  letI : NumberField
      (sKummerField K Omega p hp hroots S hInfinite) :=
    sKummerNumber K Omega p hp hroots S hInfinite
  letI : IsGalois K
      (sKummerField K Omega p hp hroots S hInfinite) :=
    sKummerGalois K Omega p hp hroots S hInfinite
  intro Q hQ
  exact s_pth_roots p hp K
    (sKummerField K Omega p hp hroots S hInfinite) S hDividing
    (generated_pth_roots
      K Omega p hp hroots S hInfinite) Q hQ

end ConstructedField

end

end Submission.CField.KNIndex
