import Submission.NumberTheory.Locals.FunctionFieldFormula
import Mathlib.FieldTheory.IsAlgClosed.Basic
import Mathlib.NumberTheory.FunctionField
import Mathlib.RingTheory.DedekindDomain.Ideal.Lemmas
import Mathlib.RingTheory.UniqueFactorizationDomain.Multiplicity

/-!
# Product formulas for rational function fields

For a rational function `g / h`, the finite-prime contributions are the
degrees of the irreducible factors of `g` minus those of `h`; their sum is
`deg g - deg h`, which is cancelled by the place at infinity.

The final section formalizes the finite-extension transfer used in Milne's
Remark 7.17.  Once the local products (or sums of orders) over the places
above a fixed base place are identified with the corresponding value of the
field norm, the product formula upstairs follows from the one downstairs.
-/

namespace Submission.NumberTheory.Milne

open Polynomial UniqueFactorizationMonoid
open scoped NNReal

noncomputable section

section AdditiveFormula

variable {k : Type*} [Field k] [NormalizationMonoid k]

/-- Milne, Exercise 8-4, algebraic product-formula identity.  The two
multisets retain the orders at every monic irreducible polynomial, while the
right side is the negative of the order at infinity. -/
theorem rational_function_orders
    (g h : k[X]) (hg : g ≠ 0) (hh : h ≠ 0) :
    (((normalizedFactors g).map Polynomial.natDegree).sum : ℤ) -
        (((normalizedFactors h).map Polynomial.natDegree).sum : ℤ) =
      (g.natDegree : ℤ) - (h.natDegree : ℤ) := by
  rw [nat_normalized_factors g hg,
    nat_normalized_factors h hh]

/-- Milne, Exercise 8-4: after adding the order at infinity, the weighted
sum of all orders of a nonzero rational function is zero.  Exponentiating
this identity gives the normalized product formula. -/
theorem rational_function_exponent
    (g h : k[X]) (hg : g ≠ 0) (hh : h ≠ 0) :
    ((((normalizedFactors g).map Polynomial.natDegree).sum : ℤ) -
        (((normalizedFactors h).map Polynomial.natDegree).sum : ℤ)) +
      ((h.natDegree : ℤ) - (g.natDegree : ℤ)) = 0 := by
  rw [rational_function_orders g h hg hh]
  omega

end AdditiveFormula

section MultiplicativeFormula

variable {k : Type*} [Field k]

/-- Monic irreducible polynomials, indexing the finite places of `k(X)`. -/
def FFPlace (k : Type*) [Field k] :=
  {p : k[X] // p.Monic ∧ Irreducible p}

noncomputable local instance rationalFunctionFinitePlaceBaseDecidableEq : DecidableEq k :=
  Classical.decEq k
noncomputable local instance rationalFunctionFinitePlaceDecidableEq :
    DecidableEq (FFPlace k) :=
  Subtype.instDecidableEq

namespace FFPlace

instance : Coe (FFPlace k) k[X] := ⟨Subtype.val⟩

@[simp] theorem monic (p : FFPlace k) : (p : k[X]).Monic := p.2.1

@[simp] theorem irreducible (p : FFPlace k) :
    Irreducible (p : k[X]) := p.2.2

@[simp] theorem ne_zero (p : FFPlace k) : (p : k[X]) ≠ 0 :=
  p.irreducible.ne_zero

/-- The height-one prime generated by a monic irreducible polynomial. -/
def prime (p : FFPlace k) :
    IsDedekindDomain.HeightOneSpectrum k[X] where
  asIdeal := Ideal.span {(p : k[X])}
  isPrime := (Ideal.span_singleton_prime p.ne_zero).2 p.irreducible.prime
  ne_bot := Ideal.span_singleton_eq_bot.not.mpr p.ne_zero

@[simp] theorem prime_asIdeal (p : FFPlace k) :
    p.prime.asIdeal = Ideal.span {(p : k[X])} := rfl

theorem natDegree_pos (p : FFPlace k) :
    0 < (p : k[X]).natDegree := p.irreducible.natDegree_pos

/-- The residue-field cardinality `q ^ deg p`, as a nonnegative real. -/
def residueCard [Fintype k] (p : FFPlace k) : ℝ≥0 :=
  (Fintype.card k : ℝ≥0) ^ (p : k[X]).natDegree

theorem residue_card [Fintype k] (p : FFPlace k) :
    1 < p.residueCard := by
  apply one_lt_pow₀
  · exact_mod_cast Fintype.one_lt_card
  · exact p.natDegree_pos.ne'

/-- The normalized finite-place absolute value on `k(X)`. -/
def absoluteValue [Fintype k] (p : FFPlace k) :
    AbsoluteValue (RatFunc k) ℝ :=
  p.prime.adicAbv p.residue_card

/-- The normalized irreducible factors of `f`, regarded as finite places. -/
def factors (f : k[X]) : Multiset (FFPlace k) := by
  classical
  exact (normalizedFactors f).attach.map fun p =>
    ⟨p.1, by
      have hp0 : p.1 ≠ 0 := ne_zero_of_mem_normalizedFactors p.2
      have hmonic : (normalize p.1).Monic := monic_normalize hp0
      rw [normalize_normalized_factor p.1 p.2] at hmonic
      exact ⟨hmonic, irreducible_of_normalized_factor p.1 p.2⟩⟩

@[simp] theorem factors_map_val (f : k[X]) :
    (factors f).map (fun p : FFPlace k => p.1) =
      normalizedFactors f := by
  classical
  unfold factors
  rw [Multiset.map_map]
  exact Multiset.attach_map_val _

theorem count_factors (f : k[X]) (p : FFPlace k) :
    (factors f).count p = (normalizedFactors f).count (p : k[X]) := by
  classical
  rw [← factors_map_val f]
  exact (Multiset.count_map_eq_count' _ _ Subtype.val_injective p).symm

theorem int_valuation_ne (p : FFPlace k)
    {f : k[X]} (hf : f ≠ 0) :
    p.prime.intValuation f = WithZero.exp (-(factors f).count p : ℤ) := by
  classical
  rw [p.prime.intValuation_if_neg hf]
  congr 2
  rw [Ideal.count_associates_factors_eq]
  · rw [count_factors]
    change (Multiset.count (Ideal.span {(p : k[X])})
      (normalizedFactors (Ideal.span {f})) : ℤ) =
        (Multiset.count (p : k[X]) (normalizedFactors f) : ℤ)
    rw [Ideal.count_span_normalizedFactors_eq hf p.irreducible.prime]
    simp [p.monic.normalize_eq_self]
  · simpa only [ne_eq, Ideal.zero_eq_bot, Ideal.span_singleton_eq_bot]
  · exact p.prime.isPrime
  · exact p.prime.ne_bot

/-- The order of a rational function at a finite place. -/
def order (p : FFPlace k) (x : RatFunc k) : ℤ :=
  ((factors x.num).count p : ℤ) - ((factors x.denom).count p : ℤ)

theorem nn_real_exp {b : ℝ≥0} (hb : b ≠ 0) (z : ℤ) :
    WithZeroMulInt.toNNReal hb (WithZero.exp z) = b ^ z := by
  unfold WithZero.exp
  rw [WithZeroMulInt.toNNReal_neg_apply hb WithZero.coe_ne_zero,
    WithZero.unzero_coe]
  rfl

theorem int_adic_abv
    [Fintype k]
    (p : FFPlace k) {f : k[X]} (hf : f ≠ 0) :
    p.prime.intAdicAbv p.residue_card f =
      (p.residueCard : ℝ) ^ (-(factors f).count p : ℤ) := by
  simp [IsDedekindDomain.HeightOneSpectrum.intAdicAbv,
    IsDedekindDomain.HeightOneSpectrum.intAdicAbvDef,
    int_valuation_ne p hf, nn_real_exp]

theorem absolute_value_ne
    [Fintype k]
    (p : FFPlace k) {x : RatFunc k} (hx : x ≠ 0) :
    p.absoluteValue x = (p.residueCard : ℝ) ^ (-p.order x) := by
  conv_lhs => rw [← x.num_div_denom, map_div₀]
  rw [show p.absoluteValue (algebraMap k[X] (RatFunc k) x.num) =
      p.prime.intAdicAbv p.residue_card x.num by
        exact p.prime.adicAbv_of_algebraMap p.residue_card x.num,
    show p.absoluteValue (algebraMap k[X] (RatFunc k) x.denom) =
      p.prime.intAdicAbv p.residue_card x.denom by
        exact p.prime.adicAbv_of_algebraMap p.residue_card x.denom]
  rw [int_adic_abv p (RatFunc.num_ne_zero hx),
    int_adic_abv p x.denom_ne_zero]
  have hp0 : (p.residueCard : ℝ) ≠ 0 := by
    exact_mod_cast ne_of_gt (lt_trans zero_lt_one p.residue_card)
  rw [← zpow_sub₀ hp0]
  congr 1
  rw [order]
  ring

/-- The finite places at which `x` can have nonzero order. -/
def support (x : RatFunc k) : Finset (FFPlace k) :=
  (factors x.num).toFinset ∪ (factors x.denom).toFinset

/-- Only the irreducible factors of the numerator and denominator can have
nonzero order. -/
theorem order_support_subset (x : RatFunc k) :
    Function.support (fun p : FFPlace k => p.order x) ⊆
      support x := by
  intro p hp
  contrapose! hp
  have hp' : p ∉ support x := by simpa using hp
  have hnmem : p ∉ (factors x.num).toFinset := fun h =>
    hp' (Finset.mem_union_left _ h)
  have hdmem : p ∉ (factors x.denom).toFinset := fun h =>
    hp' (Finset.mem_union_right _ h)
  have hn : (factors x.num).count p = 0 := Multiset.count_eq_zero.mpr <| by
    simpa using hnmem
  have hd : (factors x.denom).count p = 0 := Multiset.count_eq_zero.mpr <| by
    simpa using hdmem
  simp only [Function.mem_support, ne_eq, not_not]
  change ((factors x.num).count p : ℤ) -
    ((factors x.denom).count p : ℤ) = 0
  rw [hn, hd]
  simp

theorem absolute_support_subset [Fintype k] {x : RatFunc k} (hx : x ≠ 0) :
    Function.mulSupport (fun p : FFPlace k => p.absoluteValue x) ⊆
      support x := by
  intro p hp
  change p.absoluteValue x ≠ 1 at hp
  contrapose! hp
  have hnmem : p ∉ (factors x.num).toFinset := fun h =>
    hp (by simp [support, h])
  have hdmem : p ∉ (factors x.denom).toFinset := fun h =>
    hp (by simp [support, h])
  have hn : (factors x.num).count p = 0 := Multiset.count_eq_zero.mpr <| by
    simpa using hnmem
  have hd : (factors x.denom).count p = 0 := Multiset.count_eq_zero.mpr <| by
    simpa using hdmem
  rw [absolute_value_ne p hx]
  simp [order, hn, hd]

theorem weighted_count_sum (m : Multiset (FFPlace k)) :
    ∑ p ∈ m.toFinset, (m.count p : ℤ) * ((p : k[X]).natDegree : ℤ) =
      (((m.map fun p : FFPlace k =>
        (p : k[X]).natDegree).sum : ℕ) : ℤ) := by
  norm_cast
  simpa [nsmul_eq_mul] using
    (Finset.sum_multiset_map_count m
      (fun p : FFPlace k =>
        (p : k[X]).natDegree)).symm

theorem weighted_count_support
    (m n : Multiset (FFPlace k)) :
    ∑ p ∈ m.toFinset ∪ n.toFinset,
        (m.count p : ℤ) * ((p : k[X]).natDegree : ℤ) =
      (((m.map fun p : FFPlace k =>
        (p : k[X]).natDegree).sum : ℕ) : ℤ) := by
  rw [← weighted_count_sum m]
  symm
  apply Finset.sum_subset (Finset.subset_union_left)
  intro p hp hpm
  simp only [Multiset.mem_toFinset] at hpm
  simp [Multiset.count_eq_zero.mpr hpm]

theorem weighted_order_sum (x : RatFunc k) :
    ∑ p ∈ support x, ((p : k[X]).natDegree : ℤ) * p.order x =
      rationalFunctionDegree x := by
  simp only [support, order, mul_sub, Finset.sum_sub_distrib]
  rw [show (∑ p ∈ (factors x.num).toFinset ∪ (factors x.denom).toFinset,
      ((p : k[X]).natDegree : ℤ) * (factors x.num).count p) =
        (((factors x.num).map fun p : FFPlace k =>
          (p : k[X]).natDegree).sum : ℕ) by
      simpa [mul_comm] using weighted_count_support
        (factors x.num) (factors x.denom)]
  rw [show (∑ p ∈ (factors x.num).toFinset ∪ (factors x.denom).toFinset,
      ((p : k[X]).natDegree : ℤ) * (factors x.denom).count p) =
        (((factors x.denom).map fun p : FFPlace k =>
          (p : k[X]).natDegree).sum : ℕ) by
      simpa [mul_comm, Finset.union_comm] using weighted_count_support
        (factors x.denom) (factors x.num)]
  simp only [rationalFunctionDegree]
  congr 1 <;> norm_cast <;>
    rw [← factors_map_val, Multiset.map_map] <;>
    rfl

/-- Over an algebraically closed constant field all irreducible polynomials
are linear, so the weighted finite-order sum is the unweighted sum. -/
theorem sum_order_degree [IsAlgClosed k] (x : RatFunc k) :
    ∑ p ∈ support x, p.order x = rationalFunctionDegree x := by
  calc
    ∑ p ∈ support x, p.order x =
        ∑ p ∈ support x, ((p : k[X]).natDegree : ℤ) * p.order x := by
      apply Finset.sum_congr rfl
      intro p hp
      have hpdeg : (p : k[X]).natDegree = 1 :=
        Polynomial.natDegree_eq_of_degree_eq_some
          (IsAlgClosed.degree_eq_one_of_irreducible k p.irreducible)
      simp [hpdeg]
    _ = rationalFunctionDegree x := weighted_order_sum x

theorem absolute_value_zpow
    [Fintype k]
    (p : FFPlace k) {x : RatFunc k} (hx : x ≠ 0) :
    p.absoluteValue x = (Fintype.card k : ℝ) ^
      (-((p : k[X]).natDegree : ℤ) * p.order x) := by
  rw [absolute_value_ne p hx, residueCard, NNReal.coe_pow]
  rw [← zpow_natCast, ← zpow_mul]
  congr 1
  ring

end FFPlace

theorem finset_const_zpow {ι : Type*} (s : Finset ι) (b : ℝ) (hb : b ≠ 0)
    (e : ι → ℤ) :
    ∏ i ∈ s, b ^ e i = b ^ ∑ i ∈ s, e i := by
  induction s using Finset.induction_on with
  | empty => simp
  | @insert a s ha ih =>
      rw [Finset.prod_insert ha, Finset.sum_insert ha, ih, ← zpow_add₀ hb]

variable [Fintype k]

/-- The normalized absolute value at infinity on `k(X)`. -/
def rationalFunctionInfinity :
    AbsoluteValue (RatFunc k) ℝ := by
  letI := Classical.decEq (RatFunc k)
  exact {
  toFun := fun x => WithZeroMulInt.toNNReal
    (ne_zero_of_lt (show (1 : ℝ≥0) < Fintype.card k by exact_mod_cast Fintype.one_lt_card))
    (RatFunc.inftyValuation k x)
  map_mul' x y := by simp
  nonneg' x := NNReal.zero_le_coe
  eq_zero' x := by simp
  add_le' x y := by
    norm_cast
    have hmono := (WithZeroMulInt.toNNReal_strictMono
      (show (1 : ℝ≥0) < Fintype.card k by
        exact_mod_cast Fintype.one_lt_card)).monotone
    calc
      _ ≤ max
          (WithZeroMulInt.toNNReal _ (RatFunc.inftyValuation k x))
          (WithZeroMulInt.toNNReal _ (RatFunc.inftyValuation k y)) := by
        rw [← hmono.map_max]
        exact hmono ((RatFunc.inftyValuation k).map_add x y)
      _ ≤ _ + _ := max_le_add_of_nonneg (by positivity) (by positivity) }

theorem rational_function_infinity
    {x : RatFunc k} (hx : x ≠ 0) :
    rationalFunctionInfinity x =
      (Fintype.card k : ℝ) ^ x.intDegree := by
  classical
  simp [rationalFunctionInfinity,
    RatFunc.inftyValuation_apply, RatFunc.inftyValuation_of_nonzero k hx,
    WithZeroMulInt.toNNReal_neg_apply, NNReal.coe_zpow]
  congr 1

theorem rationalFunctionAbsolute
    {x : RatFunc k} (hx : x ≠ 0) :
    (∏ᶠ p : FFPlace k, p.absoluteValue x) =
      (Fintype.card k : ℝ) ^ (-rationalFunctionDegree x) := by
  rw [finprod_eq_prod_of_mulSupport_subset _
    (FFPlace.absolute_support_subset hx)]
  simp_rw [FFPlace.absolute_value_zpow _ hx]
  have hq0 : (Fintype.card k : ℝ) ≠ 0 := by
    exact ne_of_gt (by exact_mod_cast (Fintype.card_pos : 0 < Fintype.card k))
  rw [finset_const_zpow _ _ hq0]
  congr 1
  calc
    (∑ p ∈ FFPlace.support x,
        (-((p : k[X]).natDegree : ℤ)) * p.order x) =
        -(∑ p ∈ FFPlace.support x,
          ((p : k[X]).natDegree : ℤ) * p.order x) := by
      calc
        _ = ∑ p ∈ FFPlace.support x,
            -(((p : k[X]).natDegree : ℤ) * p.order x) := by
          apply Finset.sum_congr rfl
          intro p hp
          ring
        _ = _ := Finset.sum_neg_distrib
          (fun p : FFPlace k =>
            ((p : k[X]).natDegree : ℤ) * p.order x)
    _ = -rationalFunctionDegree x := by
      rw [FFPlace.weighted_order_sum]

/-- Milne, Exercise 8-4: the normalized absolute values on `k(X)`,
including the place at infinity, satisfy the multiplicative product formula. -/
theorem rational_function_formula
    (x : RatFunc k) (hx : x ≠ 0) :
    (∏ᶠ p : FFPlace k, p.absoluteValue x) *
      rationalFunctionInfinity x = 1 := by
  rw [rationalFunctionAbsolute hx,
    rational_function_infinity hx]
  have hq0 : (Fintype.card k : ℝ) ≠ 0 := by
    exact ne_of_gt (by exact_mod_cast (Fintype.card_pos : 0 < Fintype.card k))
  rw [← zpow_add₀ hq0]
  have hadd := function_additive_formula x hx
  have hzero : -rationalFunctionDegree x + x.intDegree = 0 := by
    omega
  rw [hzero, zpow_zero]

/-- All finite places and the place at infinity of `k(T)`. -/
def RFPlace (k : Type*) [Field k] :=
  Option (FFPlace k)

namespace RFPlace

/-- The normalized absolute value belonging to a place of `k(T)`. -/
def absoluteValue (v : RFPlace k) : AbsoluteValue (RatFunc k) ℝ :=
  v.elim rationalFunctionInfinity
    FFPlace.absoluteValue

@[simp] theorem absoluteValue_none :
    absoluteValue (k := k) none = rationalFunctionInfinity := rfl

@[simp] theorem absoluteValue_some (v : FFPlace k) :
    absoluteValue (some v) = v.absoluteValue := rfl

/-- The normalized product formula over the single type containing all
places of `k(T)`. -/
theorem multip_produ_formu (x : (RatFunc k)ˣ) :
    (∏ᶠ v : RFPlace k, v.absoluteValue (x : RatFunc k)) = 1 := by
  have hfinite : (Function.mulSupport fun v : FFPlace k =>
      FFPlace.absoluteValue v (x : RatFunc k)).Finite :=
    (FFPlace.support (x : RatFunc k)).finite_toSet.subset
      (FFPlace.absolute_support_subset x.ne_zero)
  change (∏ᶠ v : Option (FFPlace k),
    absoluteValue v (x : RatFunc k)) = 1
  rw [finprod_option (f := fun v : RFPlace k =>
    absoluteValue v (x : RatFunc k)) hfinite]
  change rationalFunctionInfinity (x : RatFunc k) *
      (∏ᶠ v : FFPlace k,
        FFPlace.absoluteValue v (x : RatFunc k)) = 1
  rw [mul_comm]
  exact rational_function_formula (x : RatFunc k) x.ne_zero

end RFPlace

end MultiplicativeFormula

section AlgebraicallyClosedConstants

namespace RFPlace

variable {k : Type*} [Field k]

noncomputable local instance rationalFunctionPlaceBaseDecidableEq : DecidableEq k :=
  Classical.decEq k

/-- The order at a finite place, or at infinity, of `k(T)`. -/
def order (v : RFPlace k) (x : (RatFunc k)ˣ) : ℤ :=
  v.elim (-((x : RatFunc k).intDegree))
    (fun p => p.order (x : RatFunc k))

@[simp] theorem order_none (x : (RatFunc k)ˣ) :
    order (k := k) none x = -((x : RatFunc k).intDegree) := rfl

@[simp] theorem order_some (p : FFPlace k)
    (x : (RatFunc k)ˣ) : order (some p) x = p.order (x : RatFunc k) := rfl

/-- Milne, Remark 7.17(b), for `k(T)` with algebraically closed constants:
the unweighted sum of all orders is zero. -/
theorem additiveProductFormula [IsAlgClosed k] (x : (RatFunc k)ˣ) :
    (∑ᶠ v : RFPlace k, v.order x) = 0 := by
  have hfinite : (Function.support fun p : FFPlace k =>
      p.order (x : RatFunc k)).Finite :=
    (FFPlace.support (x : RatFunc k)).finite_toSet.subset
      (FFPlace.order_support_subset (x : RatFunc k))
  change (∑ᶠ v : Option (FFPlace k), order v x) = 0
  rw [finsum_option (f := fun v : RFPlace k => order v x) hfinite]
  change -((x : RatFunc k).intDegree) +
      (∑ᶠ p : FFPlace k, p.order (x : RatFunc k)) = 0
  rw [finsum_eq_sum_of_support_subset _
    (FFPlace.order_support_subset (x : RatFunc k)),
    FFPlace.sum_order_degree]
  have h := function_additive_formula (x : RatFunc k) x.ne_zero
  omega

end RFPlace

end AlgebraicallyClosedConstants

section FiniteExtensionTransfer

variable {W V M : Type*} [CommMonoid M]

/-- A finite product can be regrouped along the fibers of any map.  This is
the bookkeeping step in the passage from a product formula on a field to the
product formula on a finite extension. -/
@[to_additive
  /-- A finite sum can be regrouped along the fibers of any map.  This is the
  bookkeeping step in the additive form of the function-field product
  formula. -/]
theorem finprod_fiberwise_support (down : W → V) (f : W → M)
    (hf : (Function.mulSupport f).Finite) :
    (∏ᶠ w, f w) = (∏ᶠ v, (∏ᶠ (w) (_ : down w = v), f w)) := by
  classical
  let S : Finset W := hf.toFinset
  have hsupport : Function.mulSupport f ⊆ (S : Set W) := by
    intro w hw
    exact hf.mem_toFinset.mpr hw
  have hfiber (v : V) :
      (∏ᶠ (w) (_ : down w = v), f w) =
        ∏ w ∈ S with down w = v, f w := by
    change (∏ᶠ (w) (_ : w ∈ {w | down w = v}), f w) = _
    rw [finprod_mem_eq_prod_of_inter_mulSupport_eq
      (t := S.filter fun w => down w = v)]
    ext w
    simp only [Set.mem_inter_iff, Set.mem_setOf_eq, Finset.mem_coe,
      Finset.mem_filter]
    constructor
    · intro hw
      exact ⟨⟨hsupport hw.2, hw.1⟩, hw.2⟩
    · intro hw
      exact ⟨hw.1.2, hw.2⟩
  calc
    (∏ᶠ w, f w) = ∏ w ∈ S, f w :=
      finprod_eq_prod_of_mulSupport_subset f hsupport
    _ = ∏ v ∈ S.image down, ∏ w ∈ S with down w = v, f w := by
      symm
      exact Finset.prod_fiberwise_of_maps_to
        (fun w hw => Finset.mem_image.mpr ⟨w, hw, rfl⟩) f
    _ = ∏ᶠ v, ∏ w ∈ S with down w = v, f w := by
      symm
      apply finprod_eq_prod_of_mulSupport_subset
      exact S.mulSupport_of_fiberwise_prod_subset_image f down
    _ = ∏ᶠ v, (∏ᶠ (w) (_ : down w = v), f w) := by
      apply finprod_congr
      intro v
      exact (hfiber v).symm

section Multiplicative

variable {k K : Type*} [Field k] [Field K] [Algebra k K]

/-- Milne, Remark 7.17, finite-extension transfer in multiplicative form.
The hypothesis `hlocal` is the analogue of Lemma 7.16(b): the product over
the places above `v` is the value at `v` of the field norm.  Thus no global
product-formula hypothesis is left upstairs. -/
theorem multiplicative_formula_fiberwise
    (down : W → V) (baseAbv : V → AbsoluteValue k ℝ)
    (extensionAbv : W → AbsoluteValue K ℝ)
    (hfinite : ∀ x : Kˣ,
      (Function.mulSupport fun w => extensionAbv w (x : K)).Finite)
    (hlocal : ∀ (x : Kˣ) (v : V),
      (∏ᶠ (w) (_ : down w = v), extensionAbv w (x : K)) =
        baseAbv v (Units.map (Algebra.norm k) x : k))
    (hbase : ∀ y : kˣ, (∏ᶠ v, baseAbv v (y : k)) = 1)
    (x : Kˣ) :
    (∏ᶠ w, extensionAbv w (x : K)) = 1 := by
  calc
    (∏ᶠ w, extensionAbv w (x : K)) =
        ∏ᶠ v, (∏ᶠ (w) (_ : down w = v), extensionAbv w (x : K)) :=
      finprod_fiberwise_support down _ (hfinite x)
    _ = ∏ᶠ v, baseAbv v (Units.map (Algebra.norm k) x : k) := by
      apply finprod_congr
      exact hlocal x
    _ = 1 := hbase (Units.map (Algebra.norm k) x)

/-- Milne, Remark 7.17(a), for a finite extension of `k(T)` with `k`
finite.  The base product formula is discharged here; the remaining local
norm identity is precisely the finite-extension input that Milne delegates
to a result like Lemma 7.16. -/
theorem function_multiplicative_formula
    {k L : Type*} [Field k] [Fintype k] [Field L]
    [Algebra (RatFunc k) L] [FiniteDimensional (RatFunc k) L]
    (down : W → RFPlace k)
    (extensionAbv : W → AbsoluteValue L ℝ)
    (hfinite : ∀ x : Lˣ,
      (Function.mulSupport fun w => extensionAbv w (x : L)).Finite)
    (hlocal : ∀ (x : Lˣ) (v : RFPlace k),
      (∏ᶠ (w) (_ : down w = v), extensionAbv w (x : L)) =
        v.absoluteValue
          (Units.map (Algebra.norm (RatFunc k)) x : RatFunc k))
    (x : Lˣ) :
    (∏ᶠ w, extensionAbv w (x : L)) = 1 :=
  multiplicative_formula_fiberwise down
    RFPlace.absoluteValue extensionAbv hfinite hlocal
    RFPlace.multip_produ_formu x

end Multiplicative

section Additive

variable {k K : Type*} [Field k] [Field K] [Algebra k K]

/-- Milne, Remark 7.17(b), finite-extension transfer for sums of orders.
This is the form used when the constant field is algebraically closed, so
all residue-degree weights are one. -/
theorem additive_formula_fiberwise
    (down : W → V) (baseOrder : V → kˣ → ℤ)
    (extensionOrder : W → Kˣ → ℤ)
    (hfinite : ∀ x : Kˣ,
      (Function.support fun w => extensionOrder w x).Finite)
    (hlocal : ∀ (x : Kˣ) (v : V),
      (∑ᶠ (w) (_ : down w = v), extensionOrder w x) =
        baseOrder v (Units.map (Algebra.norm k) x))
    (hbase : ∀ y : kˣ, (∑ᶠ v, baseOrder v y) = 0)
    (x : Kˣ) :
    (∑ᶠ w, extensionOrder w x) = 0 := by
  calc
    (∑ᶠ w, extensionOrder w x) =
        ∑ᶠ v, (∑ᶠ (w) (_ : down w = v), extensionOrder w x) :=
      finsum_fiberwise_support down _ (hfinite x)
    _ = ∑ᶠ v, baseOrder v (Units.map (Algebra.norm k) x) := by
      apply finsum_congr
      exact hlocal x
    _ = 0 := hbase (Units.map (Algebra.norm k) x)

/-- Milne, Remark 7.17(b), for a finite extension of `k(T)` with `k`
algebraically closed.  The base formula is discharged here, leaving only the
local norm identity delegated in the source. -/
theorem algebraically_function_formula
    {k L : Type*} [Field k] [IsAlgClosed k] [Field L]
    [Algebra (RatFunc k) L] [FiniteDimensional (RatFunc k) L]
    (down : W → RFPlace k)
    (extensionOrder : W → Lˣ → ℤ)
    (hfinite : ∀ x : Lˣ,
      (Function.support fun w => extensionOrder w x).Finite)
    (hlocal : ∀ (x : Lˣ) (v : RFPlace k),
      (∑ᶠ (w) (_ : down w = v), extensionOrder w x) =
        v.order (Units.map (Algebra.norm (RatFunc k)) x))
    (x : Lˣ) :
    (∑ᶠ w, extensionOrder w x) = 0 :=
  additive_formula_fiberwise down
    RFPlace.order extensionOrder hfinite hlocal
    RFPlace.additiveProductFormula x

end Additive

end FiniteExtensionTransfer

end

end Submission.NumberTheory.Milne
