import Towers.ClassField.HilbertSymbols.FiniteCharacter
import Towers.ClassField.LocalReciprocity.Continuity
import Towers.ClassField.LocalReciprocity.GlobalBrauer
import Towers.ClassField.KummerTheory.KummerCorrespondenceProof
import Towers.ClassField.KummerTheory.KummerOrderCorrespondence
import Towers.ClassField.KummerNormIndex.ComplexAbsoluteValue
import Mathlib.RingTheory.Adjoin.PowerBasis

open scoped IsMulCommutative

/-!
# Milne, Theorem III.4.4: Kummer--Hilbert nondegeneracy

This file supplies the substantive field-theoretic argument missing from the
formalization of Theorem III.4.4.  For a power class `a`, it constructs the
finite Kummer extension generated by the cyclic subgroup `⟨a⟩`, factors local
Artin reciprocity through `Kˣ / Kˣⁿ`, and evaluates the perfect Kummer pairing.
Surjectivity of local reciprocity and injectivity of the Kummer pairing then
show that a class pairing trivially with every second argument is trivial.

In characteristic zero the local power-index theorem makes the entire
power-class group finite.  Adjoining roots of all its classes produces the
full exponent-`n` Kummer extension; local reciprocity is a bijection onto its
Galois group.  This upgrades the construction to a bilinear pairing with
trivial kernels in both variables.
-/

namespace Towers.CField.HSymbol

open Polynomial
open Towers.CField.LFTheory
open Towers.CField.LRecip
open Towers.CField.LBrauer
open Towers.CField.KTheory
open Towers.CField.KNIndex

noncomputable section

variable (K : Type) [NontriviallyNormedField K] [IsUltrametricDist K]

local instance nondegeneracyValuativeRel : ValuativeRel K :=
  ValuativeRel.ofValuation (NormedField.valuation (K := K))

local instance nondegeneracyValuationCompatible :
    Valuation.Compatible (NormedField.valuation (K := K)) :=
  Valuation.Compatible.ofValuation (NormedField.valuation (K := K))

variable [IsNonarchimedeanLocalField K]

/-- Forget the exponent bound while retaining the finite Galois
intermediate-field structure.  This is the object expected by finite Galois
restriction. -/
def intermediateExponentSubextension
    {Omega : Type} [Field Omega] [Algebra K Omega] {n : ℕ}
    (L : AESubext K Omega n) :
    FiniteGaloisIntermediateField K Omega where
  toIntermediateField := L.carrier
  finiteDimensional := inferInstance
  isGalois := inferInstance

set_option maxHeartbeats 1000000 in
-- Comparing independently chosen radical roots requires normalizing the
-- complete Kummer restriction tower.
omit [IsUltrametricDist K] [IsNonarchimedeanLocalField K] in
/-- The perfect radical Kummer pairing is natural under restriction to a
smaller finite Kummer field.  The proof compares the two independently
chosen radical roots: their quotient is an `n`th root of unity, hence lies
in the base field and is fixed by the upper Galois automorphism. -/
theorem radical_kummer_restriction
    {Omega : Type} [Field Omega] [Algebra K Omega] [IsAlgClosure K Omega]
    (n : ℕ) (hn : 0 < n) (hroots : (primitiveRoots n K).Nonempty)
    (L M : AESubext K Omega n)
    (hLM : L.carrier ≤ M.carrier)
    (bL : radicalPowerClasses K Omega n L.carrier)
    (bM : radicalPowerClasses K Omega n M.carrier)
    (hb : bL.1 = bM.1) (sigma : Gal(M.carrier/K)) :
    radicalRootCharacter K Omega n M hn hroots sigma bM =
      radicalRootCharacter K Omega n L hn hroots
        (galoisRestrictionHom K
          (F := intermediateExponentSubextension K L)
          (E := intermediateExponentSubextension K M)
          hLM sigma) bL := by
  letI : NeZero n := ⟨hn.ne'⟩
  let LF := intermediateExponentSubextension K L
  let MF := intermediateExponentSubextension K M
  let iU : L.carrierˣ →* M.carrierˣ :=
    coefficientUnitsHom K (F := LF) (E := MF) hLM
  let sigmaL : Gal(L.carrier/K) :=
    galoisRestrictionHom K (F := LF) (E := MF) hLM sigma
  let rL : L.carrierˣ := radicalRootUnit K Omega n L bL
  let rM : M.carrierˣ := radicalRootUnit K Omega n M bM
  have hpowL : iU rL ^ n =
      Units.map (algebraMap K M.carrier).toMonoidHom
        (powerClassRepresentative K n bL.1) := by
    rw [← map_pow, radical_unit_pow]
    apply Units.ext
    rfl
  have hpowM : rM ^ n =
      Units.map (algebraMap K M.carrier).toMonoidHom
        (powerClassRepresentative K n bL.1) := by
    rw [radical_unit_pow]
    congr 2
    exact hb.symm
  let q : M.carrierˣ := iU rL * rM⁻¹
  have hqpow : q ^ n = 1 := by
    change (iU rL * rM⁻¹) ^ n = 1
    rw [mul_pow, inv_pow, hpowL, hpowM]
    exact mul_inv_cancel _
  have hqfix : Units.map sigma q = q :=
    alg_fix_unit K n hn hroots sigma q hqpow
  have hmap : iU (Units.map sigmaL rL) = Units.map sigma (iU rL) := by
    exact coefficient_units_hom K
      (F := LF) (E := MF) hLM sigma rL
  have hraw :
      iU (radicalKummerRatio K Omega n L bL sigmaL) =
        radicalKummerRatio K Omega n M bM sigma := by
    change iU (Units.map sigmaL rL * rL⁻¹) =
      Units.map sigma rM * rM⁻¹
    rw [map_mul, map_inv, hmap]
    have hqdef : q = iU rL * rM⁻¹ := rfl
    have hir : iU rL = q * rM := by
      rw [hqdef]
      group
    have hsir := congrArg (Units.map (sigma : M.carrier →* M.carrier)) hir
    simp only [map_mul, hqfix] at hsir
    rw [hsir, hir]
    calc
      q * Units.map sigma rM * (q * rM)⁻¹ =
          (q * q⁻¹) * (Units.map sigma rM * rM⁻¹) := by
            rw [mul_inv_rev]
            ac_rfl
      _ = Units.map sigma rM * rM⁻¹ := by rw [mul_inv_cancel, one_mul]
  apply Subtype.ext
  have hM := rootsOfUnityEquivOfPrimitiveRoots_symm_apply
    (algebraMap K M.carrier).injective hroots
    (radicalKummerExtension K Omega n M hn hroots sigma bM)
  have hL := rootsOfUnityEquivOfPrimitiveRoots_symm_apply
    (algebraMap K L.carrier).injective hroots
    (radicalKummerExtension K Omega n L hn hroots sigmaL bL)
  apply Units.map_injective (algebraMap K M.carrier).injective
  rw [show Units.map (algebraMap K M.carrier).toMonoidHom
      ((radicalRootCharacter K Omega n M hn hroots sigma bM :
        rootsOfUnity n K) : Kˣ) =
      radicalKummerRatio K Omega n M bM sigma by
        apply Units.ext
        exact hM]
  have hLU : Units.map (algebraMap K L.carrier).toMonoidHom
      ((radicalRootCharacter K Omega n L hn hroots sigmaL bL :
        rootsOfUnity n K) : Kˣ) =
      radicalKummerRatio K Omega n L bL sigmaL := by
    apply Units.ext
    exact hL
  have hLmap := congrArg iU hLU
  calc
    radicalKummerRatio K Omega n M bM sigma =
        iU (radicalKummerRatio K Omega n L bL sigmaL) := hraw.symm
    _ = Units.map (algebraMap K M.carrier).toMonoidHom
        ((radicalRootCharacter K Omega n L hn hroots sigmaL bL :
          rootsOfUnity n K) : Kˣ) := by
      apply Units.ext
      exact (congrArg Units.val hLmap).symm

/-- The finite cyclic subgroup generated by one local power class. -/
def cyclicClassSubgroup
    (n : ℕ) (hn : 0 < n) (a : PowerClassGroup K n) :
    PCSubgro K n where
  carrier := Subgroup.zpowers a
  finite_carrier :=
    (isOfFinOrder_iff_pow_eq_one.mpr
      ⟨n, hn, power_class_pow n a⟩).finite_zpowers

/-- The finite Kummer extension attached to the cyclic subgroup generated
by a single power class. -/
def cyclicKummerExtension
    (n : ℕ) (hn : 0 < n) {ζ : K} (hζ : IsPrimitiveRoot ζ n)
    (a : PowerClassGroup K n) :
    AESubext K (AlgebraicClosure K) n :=
  kummerFieldSubextension K (AlgebraicClosure K) n hn hζ
    (cyclicClassSubgroup K n hn a)

/-- The generating power class, regarded as a radical class in its cyclic
Kummer extension. -/
def cyclicKummerRadical
    (n : ℕ) (hn : 0 < n) {ζ : K} (hζ : IsPrimitiveRoot ζ n)
    (a : PowerClassGroup K n) :
    radicalPowerClasses K (AlgebraicClosure K) n
      (cyclicKummerExtension K n hn hζ a).carrier := by
  let hroots : (primitiveRoots n K).Nonempty :=
    ⟨ζ, (mem_primitiveRoots hn).2 hζ⟩
  refine ⟨a, ?_⟩
  rw [show (cyclicKummerExtension K n hn hζ a).carrier =
      kummerField K (AlgebraicClosure K) n hn
        (cyclicClassSubgroup K n hn a) from rfl]
  rw [radical_classes_field n hn hroots]
  exact Subgroup.mem_zpowers a

/-- The globally chosen radical which generates the cyclic Kummer field. -/
def cyclicKummerGenerator
    (n : ℕ) (hn : 0 < n) {ζ : K} (hζ : IsPrimitiveRoot ζ n)
    (a : PowerClassGroup K n) :
    (cyclicKummerExtension K n hn hζ a).carrier :=
  ((kummerGeneratorUnit K (AlgebraicClosure K) n hn
    (cyclicClassSubgroup K n hn a)
    ⟨a, Subgroup.mem_zpowers a⟩ :
      (kummerField K (AlgebraicClosure K) n hn
        (cyclicClassSubgroup K n hn a))ˣ) :
    kummerField K (AlgebraicClosure K) n hn
      (cyclicClassSubgroup K n hn a))

omit [IsUltrametricDist K] [IsNonarchimedeanLocalField K] in
@[simp]
theorem cyclic_kummer_pow
    (n : ℕ) (hn : 0 < n) {ζ : K} (hζ : IsPrimitiveRoot ζ n)
    (a : PowerClassGroup K n) :
    cyclicKummerGenerator K n hn hζ a ^ n =
      algebraMap K (cyclicKummerExtension K n hn hζ a).carrier
        ((powerClassRepresentative K n a : Kˣ) : K) := by
  change ((kummerGeneratorUnit K (AlgebraicClosure K) n hn
      (cyclicClassSubgroup K n hn a)
      ⟨a, Subgroup.mem_zpowers a⟩ :
        (kummerField K (AlgebraicClosure K) n hn
          (cyclicClassSubgroup K n hn a))ˣ) :
      kummerField K (AlgebraicClosure K) n hn
        (cyclicClassSubgroup K n hn a)) ^ n = _
  exact congrArg Units.val (kummer_generator_pow K (AlgebraicClosure K) n hn
      (cyclicClassSubgroup K n hn a)
      ⟨a, Subgroup.mem_zpowers a⟩)

set_option maxHeartbeats 1000000 in
-- The fixed-field argument expands the faithful Kummer character on every
-- power of the chosen generator.
omit [IsUltrametricDist K] [IsNonarchimedeanLocalField K] in
/-- The radical indexed by `a` generates the entire cyclic Kummer field
attached to `⟨a⟩`.  Faithfulness of the Kummer character is the key point:
an automorphism fixing this one radical has trivial character on every
power of `a`, hence is the identity. -/
theorem kummer_adjoin_top
    (n : ℕ) (hn : 0 < n) {ζ : K} (hζ : IsPrimitiveRoot ζ n)
    (a : PowerClassGroup K n) :
    IntermediateField.adjoin K {cyclicKummerGenerator K n hn hζ a} = ⊤ := by
  letI : NeZero n := ⟨hn.ne'⟩
  let B := cyclicClassSubgroup K n hn a
  let F := (cyclicKummerExtension K n hn hζ a).carrier
  letI : CommGroup Gal(kummerField K (AlgebraicClosure K) n hn B/K) :=
    { (inferInstance : Group
        Gal(kummerField K (AlgebraicClosure K) n hn B/K)) with
      mul_comm := kummer_galois_commute K
        (AlgebraicClosure K) n hn hζ B }
  let hroots : (primitiveRoots n K).Nonempty :=
    ⟨ζ, (mem_primitiveRoots hn).2 hζ⟩
  let ba : B.carrier := ⟨a, Subgroup.mem_zpowers a⟩
  let r : Fˣ := kummerGeneratorUnit K (AlgebraicClosure K) n hn B ba
  let alpha : F := cyclicKummerGenerator K n hn hζ a
  apply IsGalois.intermediateFieldEquivSubgroup.injective
  rw [map_top, eq_top_iff]
  intro sigma hsigma
  have hfix : sigma alpha = alpha :=
    hsigma ⟨alpha, IntermediateField.mem_adjoin_simple_self K alpha⟩
  have hba :
      kummerCharacter K (AlgebraicClosure K) n hn hroots B sigma ba = 1 := by
    apply Units.ext
    apply (algebraMap K F).injective
    have he := rootsOfUnityEquivOfPrimitiveRoots_symm_apply
      (algebraMap K F).injective hroots
      (kummerCharacterExtension K (AlgebraicClosure K) n hn hroots B sigma ba)
    dsimp [F, B] at he ⊢
    change algebraMap K F
        (((kummerRootCharacter K (AlgebraicClosure K) n hn hroots B sigma ba :
          rootsOfUnity n K) : Kˣ) : K) = algebraMap K F (1 : K)
    rw [show algebraMap K F
        (((kummerRootCharacter K (AlgebraicClosure K) n hn hroots B sigma ba :
          rootsOfUnity n K) : Kˣ) : K) =
      ((kummerRatio K (AlgebraicClosure K) n hn
          (cyclicClassSubgroup K n hn a) sigma ba :
        (kummerField K (AlgebraicClosure K) n hn
          (cyclicClassSubgroup K n hn a))ˣ) :
        kummerField K (AlgebraicClosure K) n hn
          (cyclicClassSubgroup K n hn a)) by
        exact he]
    change sigma alpha * alpha⁻¹ = 1
    rw [hfix]
    apply mul_inv_cancel₀
    change (r : F) ≠ 0
    exact Units.ne_zero r
  apply kummer_character_injective K (AlgebraicClosure K) n hn hroots B
  apply MonoidHom.ext
  intro b
  have hbmem : b.1 ∈ Subgroup.zpowers a := b.2
  obtain ⟨z, hz⟩ := Subgroup.mem_zpowers_iff.mp hbmem
  have hbeq : b = ba ^ z := by
    apply Subtype.ext
    exact hz.symm
  rw [show kummerCharacterHom K (AlgebraicClosure K) n hn hroots B sigma =
      kummerCharacter K (AlgebraicClosure K) n hn hroots B sigma from rfl]
  rw [hbeq, map_zpow, hba, one_zpow]
  exact DFunLike.congr_fun
    (map_one (kummerCharacterHom K (AlgebraicClosure K) n hn hroots B))
      (ba ^ z) |>.symm

set_option maxHeartbeats 1000000 in
-- Relating the power-basis degree to the Kummer extension finrank requires a
-- sizeable chain of integral and adjoin computations.
omit [IsUltrametricDist K] [IsNonarchimedeanLocalField K] in
/-- The `d`th power of the cyclic Kummer generator descends to the base
field, where `d` is the degree of the cyclic Kummer extension. -/
theorem cyclic_kummer_bot
    (n : ℕ) (hn : 0 < n) {ζ : K} (hζ : IsPrimitiveRoot ζ n)
    (a : PowerClassGroup K n) :
    cyclicKummerGenerator K n hn hζ a ^
        Module.finrank K (cyclicKummerExtension K n hn hζ a).carrier ∈
      (⊥ : IntermediateField K
        (cyclicKummerExtension K n hn hζ a).carrier) := by
  letI : NeZero n := ⟨hn.ne'⟩
  let B := cyclicClassSubgroup K n hn a
  let F := (cyclicKummerExtension K n hn hζ a).carrier
  letI : CommGroup Gal(kummerField K (AlgebraicClosure K) n hn B/K) :=
    { (inferInstance : Group
        Gal(kummerField K (AlgebraicClosure K) n hn B/K)) with
      mul_comm := kummer_galois_commute K
        (AlgebraicClosure K) n hn hζ B }
  let d := Module.finrank K F
  let hroots : (primitiveRoots n K).Nonempty :=
    ⟨ζ, (mem_primitiveRoots hn).2 hζ⟩
  let ba : B.carrier := ⟨a, Subgroup.mem_zpowers a⟩
  let r : Fˣ := kummerGeneratorUnit K (AlgebraicClosure K) n hn B ba
  let alpha : F := cyclicKummerGenerator K n hn hζ a
  apply (IsGalois.mem_bot_iff_fixed (alpha ^ d)).2
  intro sigma
  let epsilon : Kˣ :=
    kummerCharacter K (AlgebraicClosure K) n hn hroots B sigma ba
  have hcard : Nat.card Gal(F/K) = d :=
    IsGalois.card_aut_eq_finrank K F
  have hsigmapow : sigma ^ d = 1 := by
    rw [← hcard]
    exact pow_card_eq_one'
  have hepsilonpow : epsilon ^ d = 1 := by
    change (kummerCharacterHom K (AlgebraicClosure K) n hn hroots B sigma ba) ^ d = 1
    calc
      (kummerCharacterHom K (AlgebraicClosure K) n hn hroots B sigma ba) ^ d =
          ((kummerCharacterHom K (AlgebraicClosure K) n hn hroots B sigma) ^ d) ba := by
            rw [MonoidHom.pow_apply]
      _ = (kummerCharacterHom K (AlgebraicClosure K) n hn hroots B
            (sigma ^ d)) ba := by
          exact congrArg (fun f => f ba)
            (map_pow (kummerCharacterHom K (AlgebraicClosure K) n hn hroots B)
              sigma d).symm
      _ = 1 := by
        rw [hsigmapow]
        exact DFunLike.congr_fun
          (map_one (kummerCharacterHom K (AlgebraicClosure K) n hn hroots B)) ba
  have hratio :
      Units.map (algebraMap K F).toMonoidHom epsilon =
        kummerRatio K (AlgebraicClosure K) n hn B sigma ba := by
    have he := rootsOfUnityEquivOfPrimitiveRoots_symm_apply
      (algebraMap K F).injective hroots
      (kummerCharacterExtension K (AlgebraicClosure K) n hn hroots B sigma ba)
    apply Units.ext
    exact he
  have haction : sigma alpha = algebraMap K F (epsilon : K) * alpha := by
    have hactionU : Units.map sigma r =
        Units.map (algebraMap K F).toMonoidHom epsilon * r := by
      have h := hratio
      change Units.map (algebraMap K F).toMonoidHom epsilon =
        Units.map sigma r * r⁻¹ at h
      rw [h]
      group
    exact congrArg Units.val hactionU
  rw [map_pow, haction, mul_pow]
  have hepsilonpowK : (epsilon : K) ^ d = 1 :=
    congrArg Units.val hepsilonpow
  rw [← map_pow, hepsilonpowK, map_one, one_mul]

omit [IsUltrametricDist K] [IsNonarchimedeanLocalField K] in
/-- The halfway power of a primitive root of even order is `-1`. -/
theorem primitive_div_neg
    (n : ℕ) (hn : 0 < n) {ζ : K} (hζ : IsPrimitiveRoot ζ n)
    (heven : Even n) : ζ ^ (n / 2) = -1 := by
  obtain ⟨k, hk⟩ := heven
  have hkpos : 0 < k := by omega
  have hhalf : n / 2 = k := by omega
  have hsquare : (ζ ^ (n / 2)) ^ 2 = 1 := by
    rw [← pow_mul]
    rw [hhalf, show k * 2 = n by omega, hζ.pow_eq_one]
  rcases (sq_eq_one_iff.mp hsquare) with hone | hneg
  · have hdvd : n ∣ n / 2 := hζ.dvd_of_pow_eq_one (n / 2) hone
    have hle : n ≤ n / 2 := Nat.le_of_dvd (by rw [hhalf]; exact hkpos) hdvd
    omega
  · exact hneg

set_option maxHeartbeats 2000000 in
-- The explicit norm witness splits into parity cases and expands a full
-- power-basis norm calculation.
omit [IsUltrametricDist K] [IsNonarchimedeanLocalField K] in
/-- The negative of the canonical representative of a power class is a norm
from its cyclic Kummer field.  This is the diagonal norm calculation behind
skew symmetry.  If `d` is the degree and `n = d m`, the generator has
minimal polynomial `X^d-c`; its norm is `(-1)^(d+1)c`.  The three parity
cases are corrected by `-1` or by the halfway power of the chosen primitive
root. -/
theorem neg_representative_kummer
    (n : ℕ) (hn : 0 < n) {ζ : K} (hζ : IsPrimitiveRoot ζ n)
    (a : PowerClassGroup K n) :
    (-1 : Kˣ) * powerClassRepresentative K n a ∈
      normSubgroup K (cyclicKummerExtension K n hn hζ a).carrier := by
  let B := cyclicClassSubgroup K n hn a
  let F := (cyclicKummerExtension K n hn hζ a).carrier
  let d := Module.finrank K F
  let m := n / d
  let arep : Kˣ := powerClassRepresentative K n a
  let ba : B.carrier := ⟨a, Subgroup.mem_zpowers a⟩
  let r : Fˣ := kummerGeneratorUnit K (AlgebraicClosure K) n hn B ba
  let alpha : F := cyclicKummerGenerator K n hn hζ a
  have hdpos : 0 < d := Module.finrank_pos
  have hdegree : d = B.card :=
    finrank_kummer_field n hn
      ⟨ζ, (mem_primitiveRoots hn).2 hζ⟩ B
  have hBcard : B.card = orderOf a := by
    calc
      B.card = Nat.card B.carrier :=
        PCSubgro.card_eq_card K B
      _ = orderOf a := Nat.card_zpowers a
  have hdvd : d ∣ n := by
    rw [hdegree, hBcard]
    exact orderOf_dvd_of_pow_eq_one (power_class_pow n a)
  have hdm : d * m = n := by
    exact Nat.mul_div_cancel' hdvd
  obtain ⟨c, hc⟩ := IntermediateField.mem_bot.mp
    (cyclic_kummer_bot K n hn hζ a)
  have hcne : c ≠ 0 := by
    intro hzero
    have halphaZero : alpha ^ d = 0 := by simpa [hzero] using hc.symm
    apply pow_ne_zero d
      (show alpha ≠ 0 by
        change (r : F) ≠ 0
        exact Units.ne_zero r)
    exact halphaZero
  let cU : Kˣ := Units.mk0 c hcne
  have hcm : cU ^ m = arep := by
    apply Units.ext
    apply (algebraMap K F).injective
    change algebraMap K F (c ^ m) = algebraMap K F (arep : K)
    rw [map_pow, hc, ← pow_mul, hdm]
    exact cyclic_kummer_pow K n hn hζ a
  have hadjoin := kummer_adjoin_top K n hn hζ a
  have hminDegree : (minpoly K alpha).natDegree = d := by
    rw [← IntermediateField.adjoin.finrank (IsIntegral.of_finite K alpha), hadjoin,
      IntermediateField.finrank_top']
  have hmin : minpoly K alpha = X ^ d - C c := by
    symm
    apply Polynomial.eq_of_monic_of_dvd_of_natDegree_le
      (minpoly.monic (IsIntegral.of_finite K alpha))
      (monic_X_pow_sub_C c hdpos.ne')
    · apply minpoly.dvd K alpha
      simpa [aeval_def] using sub_eq_zero.mpr hc.symm
    · rw [natDegree_X_pow_sub_C, hminDegree]
  have hadjoinAlg : Algebra.adjoin K {alpha} = ⊤ := by
    rw [← IntermediateField.adjoin_simple_toSubalgebra_of_isAlgebraic
      (Algebra.IsAlgebraic.isAlgebraic alpha), hadjoin]
    rfl
  let pb : PowerBasis K F :=
    PowerBasis.ofAdjoinEqTop (IsIntegral.of_finite K alpha) hadjoinAlg
  have hpbdim : pb.dim = d := by
    rw [← pb.natDegree_minpoly]
    simpa [pb] using hminDegree
  have hnormAlpha : Algebra.norm K alpha = (-1 : K) ^ d * (-c) := by
    rw [← PowerBasis.ofAdjoinEqTop_gen (IsIntegral.of_finite K alpha) hadjoinAlg]
    rw [Algebra.PowerBasis.norm_gen_eq_coeff_zero_minpoly, hpbdim]
    change (-1 : K) ^ d * (minpoly K alpha).coeff 0 = _
    rw [hmin]
    have hcoeff : (X ^ d - C c).coeff 0 = -c := by
      rw [Polynomial.coeff_sub, Polynomial.coeff_X_pow]
      simp [ne_of_lt hdpos]
    rw [hcoeff]
  have hnormr : normOnUnits K F r =
      (-1 : Kˣ) ^ d * ((-1 : Kˣ) * cU) := by
    apply Units.ext
    change Algebra.norm K alpha =
      ((-1 : K) ^ d * ((-1 : K) * c))
    calc
      Algebra.norm K alpha = (-1 : K) ^ d * (-c) := hnormAlpha
      _ = (-1 : K) ^ d * ((-1 : K) * c) := by
        exact congrArg ((-1 : K) ^ d * ·) (neg_eq_neg_one_mul c)
  have hnormBase (u : Kˣ) :
      normOnUnits K F (Units.map (algebraMap K F).toMonoidHom u) = u ^ d := by
    apply Units.ext
    exact Algebra.norm_algebraMap (u : K)
  by_cases hdodd : Odd d
  · refine ⟨Units.map (algebraMap K F).toMonoidHom (-1 : Kˣ) * r ^ m, ?_⟩
    have hnegD : (-1 : Kˣ) ^ d = -1 := by
      apply Units.ext
      exact hdodd.neg_one_pow
    have hnormrOdd : normOnUnits K F r = cU := by
      rw [hnormr, hnegD]
      apply Units.ext
      simp
    rw [map_mul, hnormBase, map_pow, hnormrOdd, hnegD, hcm]
  · have hdeven : Even d := Nat.not_odd_iff_even.mp hdodd
    have hnegD : (-1 : Kˣ) ^ d = 1 := by
      apply Units.ext
      exact hdeven.neg_one_pow
    have hnormrEven : normOnUnits K F r = (-1 : Kˣ) * cU := by
      rw [hnormr, hnegD, one_mul]
    by_cases hmodd : Odd m
    · refine ⟨r ^ m, ?_⟩
      have hnegM : (-1 : Kˣ) ^ m = -1 := by
        apply Units.ext
        exact hmodd.neg_one_pow
      rw [map_pow, hnormrEven, mul_pow, hnegM, hcm]
    · have hmeven : Even m := Nat.not_odd_iff_even.mp hmodd
      have hneven : Even n := by rw [← hdm]; exact hdeven.mul_right m
      let zetaU : Kˣ := Units.mk0 ζ (hζ.ne_zero hn.ne')
      refine ⟨Units.map (algebraMap K F).toMonoidHom (zetaU ^ (m / 2)) * r ^ m, ?_⟩
      have hnegM : (-1 : Kˣ) ^ m = 1 := by
        apply Units.ext
        exact hmeven.neg_one_pow
      rw [map_mul, hnormBase, map_pow, hnormrEven]
      have hzeta : zetaU ^ (m / 2 * d) = -1 := by
        apply Units.ext
        change ζ ^ (m / 2 * d) = -1
        rw [show m / 2 * d = n / 2 by
          rw [← hdm, Nat.mul_div_assoc d hmeven.two_dvd, mul_comm]]
        exact primitive_div_neg K n hn hζ hneven
      rw [← pow_mul, hzeta, mul_pow, hnegM, one_mul, hcm]

/-- Local reciprocity on the cyclic Kummer extension attached to `a`,
factored through all `n`th-power classes. -/
def cyclicKummerArtin
    (n : ℕ) (hn : 0 < n) {ζ : K} (hζ : IsPrimitiveRoot ζ n)
    (a : PowerClassGroup K n) :
    PowerClassGroup K n →*
      Gal((cyclicKummerExtension K n hn hζ a).carrier/K) := by
  let E := cyclicKummerExtension K n hn hζ a
  apply QuotientGroup.lift (powMonoidHom n : Kˣ →* Kˣ).range
    (abelianArtinHom K E.carrier)
  rintro _ ⟨x, rfl⟩
  change abelianArtinHom K E.carrier (x ^ n) = 1
  rw [map_pow]
  exact E.exponent_dvd _

theorem cyclic_kummer_surjective
    (n : ℕ) (hn : 0 < n) {ζ : K} (hζ : IsPrimitiveRoot ζ n)
    (a : PowerClassGroup K n) :
    Function.Surjective (cyclicKummerArtin K n hn hζ a) := by
  intro σ
  obtain ⟨x, hx⟩ := abelian_artin_surjective K
    (cyclicKummerExtension K n hn hζ a).carrier σ
  refine ⟨powerClass n x, ?_⟩
  simpa [cyclicKummerArtin, powerClass] using hx

/-- The Kummer--Artin Hilbert symbol: the Artin symbol of the second power
class acts on an `n`th root of the first through this root of unity. -/
def kummerHilbertSymbol
    (n : ℕ) (hn : 0 < n) {ζ : K} (hζ : IsPrimitiveRoot ζ n)
    (a b : PowerClassGroup K n) : rootsOfUnity n K :=
  let E := cyclicKummerExtension K n hn hζ a
  letI : CommGroup Gal(E.carrier/K) :=
    { (inferInstance : Group Gal(E.carrier/K)) with
      mul_comm := mul_comm' }
  let hroots : (primitiveRoots n K).Nonempty :=
    ⟨ζ, (mem_primitiveRoots hn).2 hζ⟩
  radicalRootCharacter K (AlgebraicClosure K) n E hn hroots
    (cyclicKummerArtin K n hn hζ a b)
    (cyclicKummerRadical K n hn hζ a)

/-- **The substantive Kummer nondegeneracy argument in Theorem III.4.4.**
If the Hilbert multiplier attached to `a` is trivial on every local Artin
symbol, then the Kummer character is trivial; perfect Kummer duality then
forces `a` to be an `n`th power. -/
theorem kummer_artin_hilbert
    (n : ℕ) (hn : 0 < n) {ζ : K} (hζ : IsPrimitiveRoot ζ n)
    (a : PowerClassGroup K n)
    (ha : ∀ b, kummerHilbertSymbol K n hn hζ a b = 1) :
    a = 1 := by
  let E := cyclicKummerExtension K n hn hζ a
  let hroots : (primitiveRoots n K).Nonempty :=
    ⟨ζ, (mem_primitiveRoots hn).2 hζ⟩
  let r := cyclicKummerRadical K n hn hζ a
  have hpair :
      radicalKummerPairing K (AlgebraicClosure K) n E hn hroots r = 1 := by
    apply MonoidHom.ext
    intro σ
    obtain ⟨b, rfl⟩ := cyclic_kummer_surjective K n hn hζ a σ
    have h := congrArg Subtype.val (ha b)
    exact h
  have hr : r = 1 := by
    apply kummer_pairing_injective K (AlgebraicClosure K) n E hn hroots
    simpa using hpair
  exact congrArg Subtype.val hr

/-- Evaluation at the generating radical detects the complete Artin symbol
of the cyclic Kummer extension.  This is the missing faithful-character
step behind the norm criterion. -/
theorem artin_hilbert_symbol
    (n : ℕ) (hn : 0 < n) {ζ : K} (hζ : IsPrimitiveRoot ζ n)
    (a b : PowerClassGroup K n) :
    kummerHilbertSymbol K n hn hζ a b = 1 ↔
      cyclicKummerArtin K n hn hζ a b = 1 := by
  let E := cyclicKummerExtension K n hn hζ a
  let hroots : (primitiveRoots n K).Nonempty :=
    ⟨ζ, (mem_primitiveRoots hn).2 hζ⟩
  let r₀ := cyclicKummerRadical K n hn hζ a
  let σ := cyclicKummerArtin K n hn hζ a b
  constructor
  · intro hvalue
    have hgen :
        radicalRootCharacter K (AlgebraicClosure K) n E hn hroots σ r₀ = 1 :=
      hvalue
    letI : NeZero n := ⟨hn.ne'⟩
    have hexp : Monoid.exponent Gal(E.carrier/K) ∣ n :=
      Monoid.exponent_dvd_of_forall_pow_eq_one E.exponent_dvd
    letI : HasEnoughRootsOfUnity K n :=
      HasEnoughRootsOfUnity.of_card_le (by rw [hζ.card_rootsOfUnity])
    letI : HasEnoughRootsOfUnity K (Monoid.exponent Gal(E.carrier/K)) :=
      HasEnoughRootsOfUnity.of_dvd K hexp
    rw [← CommGroup.forall_apply_eq_apply_iff
      (G := Gal(E.carrier/K)) (M := K)]
    intro φ
    obtain ⟨r, hr⟩ := radical_kummer_pairing
      K (AlgebraicClosure K) n E hn hroots φ
    have hrmem : r.1 ∈ Subgroup.zpowers a := by
      have hrad := radical_classes_field
        (K := K) (Omega := AlgebraicClosure K) n hn hroots
        (cyclicClassSubgroup K n hn a)
      change r.1 ∈ (cyclicClassSubgroup K n hn a).carrier
      rw [← hrad]
      exact r.2
    obtain ⟨z, hz⟩ := Subgroup.mem_zpowers_iff.mp hrmem
    have hre : r = r₀ ^ z := by
      apply Subtype.ext
      exact hz.symm
    calc
      φ σ = (radicalKummerPairing K (AlgebraicClosure K) n E hn hroots r) σ := by
        rw [hr]
      _ = (radicalKummerPairing K (AlgebraicClosure K) n E hn hroots (r₀ ^ z)) σ := by
        rw [hre]
      _ = ((radicalKummerPairing K (AlgebraicClosure K) n E hn hroots r₀) σ) ^ z := by
        rw [map_zpow]
        rfl
      _ = 1 := by
        change ((radicalRootCharacter K (AlgebraicClosure K) n E hn hroots σ r₀ :
          rootsOfUnity n K) : Kˣ) ^ z = 1
        rw [show ((radicalRootCharacter K (AlgebraicClosure K) n E hn hroots σ r₀ :
          rootsOfUnity n K) : Kˣ) = 1 by
            exact congrArg Subtype.val hgen, one_zpow]
      _ = φ 1 := by simp
  · intro hσ
    change radicalRootCharacter K (AlgebraicClosure K) n E hn hroots σ r₀ = 1
    have hσ' : σ = 1 := hσ
    rw [hσ']
    apply Subtype.ext
    exact map_one
      (radicalKummerPairing K (AlgebraicClosure K) n E hn hroots r₀)

/-- **The norm criterion for the canonical cyclic Kummer field.**  A
Hilbert multiplier vanishes precisely when the second entry is a field
norm.  This follows from faithful Kummer evaluation and the exact kernel of
finite local reciprocity. -/
theorem kummer_artin_symbol
    (n : ℕ) (hn : 0 < n) {ζ : K} (hζ : IsPrimitiveRoot ζ n)
    (a : PowerClassGroup K n) (b : Kˣ) :
    kummerHilbertSymbol K n hn hζ a (powerClass n b) = 1 ↔
      b ∈ normSubgroup K (cyclicKummerExtension K n hn hζ a).carrier := by
  rw [artin_hilbert_symbol K n hn hζ]
  change abelianArtinHom K
      (cyclicKummerExtension K n hn hζ a).carrier b = 1 ↔ _
  rw [← MonoidHom.mem_ker,
    abelian_artin_ker K
      (cyclicKummerExtension K n hn hζ a).carrier]

/-- Skew-symmetry transports the preceding substantive left-kernel theorem
to the right kernel, completing Theorem III.4.4(c). -/
theorem kummer_symbol_skew
    (n : ℕ) (hn : 0 < n) {ζ : K} (hζ : IsPrimitiveRoot ζ n)
    (hskew : ∀ a b : PowerClassGroup K n,
      kummerHilbertSymbol K n hn hζ b a =
        (kummerHilbertSymbol K n hn hζ a b)⁻¹)
    (b : PowerClassGroup K n)
    (hb : ∀ a, kummerHilbertSymbol K n hn hζ a b = 1) :
    b = 1 := by
  apply kummer_artin_hilbert K n hn hζ b
  intro a
  rw [hskew a b, hb a, inv_one]

set_option maxHeartbeats 1000000 in
-- Transporting the splitting-field structure through the cyclic Kummer
-- generator requires a large adjoin/minimal-polynomial calculation.
omit [IsUltrametricDist K] [IsNonarchimedeanLocalField K] in
/-- If `X^n-a` is irreducible, the canonical cyclic Kummer field generated
by the class of `a` is itself a splitting field of that polynomial.  The
degree comparison uses the exact multiradical Kummer degree formula; it is
what permits transport of the norm criterion to an arbitrary splitting
field model. -/
theorem cyclic_kummer_splitting
    (n : ℕ) (hn : 0 < n) {ζ : K} (hζ : IsPrimitiveRoot ζ n)
    (a : Kˣ) (hirr : Irreducible (X ^ n - C (a : K))) :
    IsSplittingField K
      (cyclicKummerExtension K n hn hζ (powerClass n a)).carrier
      (X ^ n - C (a : K)) := by
  let B := cyclicClassSubgroup K n hn (powerClass n a)
  let F := (cyclicKummerExtension K n hn hζ (powerClass n a)).carrier
  let hroots : (primitiveRoots n K).Nonempty :=
    ⟨ζ, (mem_primitiveRoots hn).2 hζ⟩
  have hclasses :
      powerClass n (powerClassRepresentative K n (powerClass n a)) =
        powerClass n a := by
    rw [power_class_representative]
  obtain ⟨z, hz, heq⟩ := (QuotientGroup.mk'_eq_mk' _).mp hclasses
  obtain ⟨d, rfl⟩ := hz
  let alpha : F :=
    cyclicKummerGenerator K n hn hζ (powerClass n a) *
      algebraMap K F (d : K)
  have halphaPow : alpha ^ n = algebraMap K F (a : K) := by
    dsimp [alpha]
    rw [mul_pow, cyclic_kummer_pow, ← map_pow, ← map_mul]
    exact congrArg (fun u : Kˣ ↦ algebraMap K F (u : K)) heq
  have hupper : Module.finrank K F ≤ n := by
    calc
      Module.finrank K F = B.card :=
        finrank_kummer_field n hn hroots B
      _ = Nat.card B.carrier :=
        PCSubgro.card_eq_card K B
      _ = orderOf (powerClass n a) := Nat.card_zpowers _
      _ ≤ n := orderOf_le_of_pow_eq_one hn
        (power_class_pow n (powerClass n a))
  have hmin : X ^ n - C (a : K) = minpoly K alpha := by
    apply minpoly.eq_of_irreducible_of_monic hirr
    · simp [aeval_def, halphaPow]
    · exact monic_X_pow_sub_C (a : K) hn.ne'
  have hlower : n ≤ Module.finrank K F := by
    rw [← natDegree_X_pow_sub_C (R := K) (n := n) (r := (a : K)), hmin]
    exact minpoly.natDegree_le alpha
  have hfin : Module.finrank K F = n := le_antisymm hupper hlower
  have hadjoin : IntermediateField.adjoin K {alpha} = ⊤ := by
    apply IntermediateField.eq_of_le_of_finrank_eq le_top
    rw [IntermediateField.adjoin.finrank (IsIntegral.of_finite K alpha), ← hmin,
      natDegree_X_pow_sub_C, IntermediateField.finrank_top', hfin]
  have halphaPow' :
      alpha ^ (Module.finrank K F) = algebraMap K F (a : K) := by
    rw [hfin]
    exact halphaPow
  have hroots' : (primitiveRoots (Module.finrank K F) K).Nonempty := by
    simpa only [hfin] using hroots
  have hsplit : IsSplittingField K F
      (X ^ Module.finrank K F - C (a : K)) :=
    isSplittingField_X_pow_sub_C_of_root_adjoin_eq_top
      (K := K) (L := F) hroots' halphaPow' hadjoin
  simpa only [hfin] using hsplit

set_option maxHeartbeats 1000000 in
-- The arbitrary splitting-field model is compared through an algebraic
-- equivalence, including preservation of the field norm.
/-- **Theorem III.4.4(d), with an arbitrary splitting-field model.**
Algebraic equivalence of splitting fields preserves the field norm, so the
canonical norm criterion transports to every irreducible Kummer splitting
field. -/
theorem kummer_hilbert_symbol
    (n : ℕ) (hn : 0 < n) {ζ : K} (hζ : IsPrimitiveRoot ζ n)
    (E : Type) [Field E] [Algebra K E]
    (a b : Kˣ)
    (hsplit : IsSplittingField K E (X ^ n - C (a : K)))
    (hirr : Irreducible (X ^ n - C (a : K))) :
    kummerHilbertSymbol K n hn hζ
        (powerClass n a) (powerClass n b) = 1 ↔
      b ∈ normSubgroup K E := by
  let F := (cyclicKummerExtension K n hn hζ (powerClass n a)).carrier
  letI : IsSplittingField K E (X ^ n - C (a : K)) := hsplit
  letI : FiniteDimensional K E :=
    IsSplittingField.finiteDimensional E (X ^ n - C (a : K))
  letI : IsSplittingField K F (X ^ n - C (a : K)) :=
    cyclic_kummer_splitting K n hn hζ a hirr
  let e : E ≃ₐ[K] F :=
    (IsSplittingField.algEquiv E (X ^ n - C (a : K))).trans
      (IsSplittingField.algEquiv F (X ^ n - C (a : K))).symm
  rw [kummer_artin_symbol K n hn hζ]
  rw [norm_alg_equiv K E F e]

section CharacteristicZero

variable [CharZero K]

theorem local_power_class
    (n : ℕ) (hn : 0 < n) {ζ : K} (hζ : IsPrimitiveRoot ζ n) :
    Set.Finite (Set.univ : Set (PowerClassGroup K n)) := by
  letI : NeZero n := ⟨hn.ne'⟩
  have hformula := nonarchimedean_field_formula
    exponentialHerbrandBridge
    valuationIndexBridge K n hn
  have hindex : (powMonoidHom n : Kˣ →* Kˣ).range.index ≠ 0 := by
    intro hi
    rw [hi] at hformula
    simp only [Nat.cast_zero, zero_mul] at hformula
    have hcard : Nat.card (rootsOfUnity n K) = n := by
      rw [Nat.card_eq_fintype_card, hζ.card_rootsOfUnity]
    rw [hcard] at hformula
    have hnR : (n : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr hn.ne'
    exact (mul_ne_zero hnR hnR) hformula.symm
  letI : Finite (PowerClassGroup K n) :=
    Subgroup.index_ne_zero_iff_finite.mp hindex
  exact Set.toFinite _

/-- The full finite subgroup of local `n`th-power classes. -/
def localClassSubgroup
    (n : ℕ) (hn : 0 < n) {ζ : K} (hζ : IsPrimitiveRoot ζ n) :
    PCSubgro K n where
  carrier := ⊤
  finite_carrier := local_power_class K n hn hζ

/-- The Kummer extension obtained by adjoining roots of all local
`n`th-power classes. -/
def fullKummerExtension
    (n : ℕ) (hn : 0 < n) {ζ : K} (hζ : IsPrimitiveRoot ζ n) :
    AESubext K (AlgebraicClosure K) n :=
  kummerFieldSubextension K (AlgebraicClosure K) n hn hζ
    (localClassSubgroup K n hn hζ)

theorem kummer_radical_top
    (n : ℕ) (hn : 0 < n) {ζ : K} (hζ : IsPrimitiveRoot ζ n) :
    radicalPowerClasses K (AlgebraicClosure K) n
        (fullKummerExtension K n hn hζ).carrier = ⊤ := by
  let hroots : (primitiveRoots n K).Nonempty :=
    ⟨ζ, (mem_primitiveRoots hn).2 hζ⟩
  simpa [fullKummerExtension, localClassSubgroup] using
    (radical_classes_field
      (K := K) (Omega := AlgebraicClosure K) n hn hroots
      (localClassSubgroup K n hn hζ))

/-- Every local power class is canonically a radical class in the full
Kummer extension. -/
def localRadicalEquiv
    (n : ℕ) (hn : 0 < n) {ζ : K} (hζ : IsPrimitiveRoot ζ n) :
    PowerClassGroup K n ≃*
      radicalPowerClasses K (AlgebraicClosure K) n
        (fullKummerExtension K n hn hζ).carrier :=
  Subgroup.topEquiv.symm.trans <|
    MulEquiv.subgroupCongr
      (kummer_radical_top K n hn hζ).symm

/-- Local reciprocity on the full Kummer extension factors through
`Kˣ / Kˣⁿ`, since every Galois automorphism has exponent dividing `n`. -/
def fullKummerArtin
    (n : ℕ) (hn : 0 < n) {ζ : K} (hζ : IsPrimitiveRoot ζ n) :
    PowerClassGroup K n →*
      Gal((fullKummerExtension K n hn hζ).carrier/K) := by
  let E := fullKummerExtension K n hn hζ
  apply QuotientGroup.lift (powMonoidHom n : Kˣ →* Kˣ).range
    (abelianArtinHom K E.carrier)
  rintro _ ⟨x, rfl⟩
  change abelianArtinHom K E.carrier (x ^ n) = 1
  rw [map_pow]
  exact E.exponent_dvd _

theorem full_kummer_surjective
    (n : ℕ) (hn : 0 < n) {ζ : K} (hζ : IsPrimitiveRoot ζ n) :
    Function.Surjective (fullKummerArtin K n hn hζ) := by
  intro σ
  obtain ⟨x, hx⟩ := abelian_artin_surjective K
    (fullKummerExtension K n hn hζ).carrier σ
  refine ⟨powerClass n x, ?_⟩
  simpa [fullKummerArtin, powerClass] using hx

theorem full_kummer_artin
    (n : ℕ) (hn : 0 < n) {ζ : K} (hζ : IsPrimitiveRoot ζ n) :
    Nat.card (PowerClassGroup K n) =
      Nat.card Gal((fullKummerExtension K n hn hζ).carrier/K) := by
  let hroots : (primitiveRoots n K).Nonempty :=
    ⟨ζ, (mem_primitiveRoots hn).2 hζ⟩
  let B := localClassSubgroup K n hn hζ
  calc
    Nat.card (PowerClassGroup K n) = Nat.card B.carrier :=
      Nat.card_congr Subgroup.topEquiv.symm.toEquiv
    _ = B.card := (PCSubgro.card_eq_card K B).symm
    _ = Module.finrank K (kummerField K (AlgebraicClosure K) n hn B) :=
      (finrank_kummer_field n hn hroots B).symm
    _ = Module.finrank K (fullKummerExtension K n hn hζ).carrier := rfl
    _ = Nat.card Gal((fullKummerExtension K n hn hζ).carrier/K) :=
      (IsGalois.card_aut_eq_finrank K
        (fullKummerExtension K n hn hζ).carrier).symm

theorem full_kummer_injective
    (n : ℕ) (hn : 0 < n) {ζ : K} (hζ : IsPrimitiveRoot ζ n) :
    Function.Injective (fullKummerArtin K n hn hζ) := by
  letI : Finite (PowerClassGroup K n) :=
    Finite.of_finite_univ (local_power_class K n hn hζ)
  exact ((Nat.bijective_iff_surjective_and_card
    (fullKummerArtin K n hn hζ)).2
      ⟨full_kummer_surjective K n hn hζ,
        full_kummer_artin K n hn hζ⟩).1

/-- The unit-valued Hilbert pairing obtained by evaluating Kummer
characters at local Artin symbols. -/
def kummerHilbertPairing
    (n : ℕ) (hn : 0 < n) {ζ : K} (hζ : IsPrimitiveRoot ζ n) :
    PowerClassGroup K n →* (PowerClassGroup K n →* Kˣ) := by
  let E := fullKummerExtension K n hn hζ
  letI : CommGroup Gal(E.carrier/K) :=
    { (inferInstance : Group Gal(E.carrier/K)) with
      mul_comm := mul_comm' }
  let hroots : (primitiveRoots n K).Nonempty :=
    ⟨ζ, (mem_primitiveRoots hn).2 hζ⟩
  let radicalEquiv := localRadicalEquiv K n hn hζ
  let artin := fullKummerArtin K n hn hζ
  exact
    { toFun := fun a =>
        (radicalKummerPairing K (AlgebraicClosure K) n E hn hroots
          (radicalEquiv a)).comp artin
      map_one' := by
        apply MonoidHom.ext
        intro b
        simp
      map_mul' := fun a c => by
        apply MonoidHom.ext
        intro b
        simp }

/-- The root-of-unity-valued Hilbert symbol attached to the full Kummer
extension and local reciprocity. -/
def localKummerSymbol
    (n : ℕ) (hn : 0 < n) {ζ : K} (hζ : IsPrimitiveRoot ζ n)
    (a b : PowerClassGroup K n) : rootsOfUnity n K :=
  let E := fullKummerExtension K n hn hζ
  let hroots : (primitiveRoots n K).Nonempty :=
    ⟨ζ, (mem_primitiveRoots hn).2 hζ⟩
  radicalRootCharacter K (AlgebraicClosure K) n E hn hroots
    (fullKummerArtin K n hn hζ b)
    (localRadicalEquiv K n hn hζ a)

set_option maxHeartbeats 1000000 in
-- Restricting the full Kummer symbol to the cyclic subextension unfolds the
-- radical equivalence and Artin-map naturality data.
/-- The full Kummer construction restricts to the cyclic Kummer
construction generated by its first entry.  Thus the bilinear full symbol
and the norm-detecting cyclic symbol are the same pairing. -/
theorem hilbert_symbol_artin
    (n : ℕ) (hn : 0 < n) {ζ : K} (hζ : IsPrimitiveRoot ζ n)
    (a b : PowerClassGroup K n) :
    localKummerSymbol K n hn hζ a b =
      kummerHilbertSymbol K n hn hζ a b := by
  let L := cyclicKummerExtension K n hn hζ a
  let M := fullKummerExtension K n hn hζ
  let LF := intermediateExponentSubextension K L
  let MF := intermediateExponentSubextension K M
  letI : IsMulCommutative Gal(LF.toIntermediateField/K) := by
    change IsMulCommutative Gal(L.carrier/K)
    infer_instance
  letI : IsMulCommutative Gal(MF.toIntermediateField/K) := by
    change IsMulCommutative Gal(M.carrier/K)
    infer_instance
  have hsub : (cyclicClassSubgroup K n hn a).carrier ≤
      (localClassSubgroup K n hn hζ).carrier := by
    intro x hx
    simp [localClassSubgroup]
  have hLM : L.carrier ≤ M.carrier := kummerField_mono hn hsub
  let rL := cyclicKummerRadical K n hn hζ a
  let rM := localRadicalEquiv K n hn hζ a
  let sigma := fullKummerArtin K n hn hζ b
  have hartin :
      galoisRestrictionHom K (F := LF) (E := MF) hLM sigma =
        cyclicKummerArtin K n hn hζ a b := by
    obtain ⟨x, rfl⟩ := QuotientGroup.mk'_surjective
      (powMonoidHom n : Kˣ →* Kˣ).range b
    change galoisRestrictionHom K (F := LF) (E := MF) hLM
        (abelianArtinHom K M.carrier x) =
      abelianArtinHom K L.carrier x
    exact DFunLike.congr_fun
      (abelian_artin_restriction K (AlgebraicClosure K)
        (F := LF) (E := MF) hLM) x
  have hnat := radical_kummer_restriction K n hn
    ⟨ζ, (mem_primitiveRoots hn).2 hζ⟩ L M hLM rL rM (by rfl) sigma
  change radicalRootCharacter K (AlgebraicClosure K) n M hn
      ⟨ζ, (mem_primitiveRoots hn).2 hζ⟩ sigma rM =
    radicalRootCharacter K (AlgebraicClosure K) n L hn
      ⟨ζ, (mem_primitiveRoots hn).2 hζ⟩
      (cyclicKummerArtin K n hn hζ a b) rL
  rw [← hartin]
  exact hnat

set_option maxHeartbeats 1000000 in
-- The norm criterion transports the cyclic result through the full Kummer
-- extension and its splitting-field comparison.
/-- The norm criterion for the same full Hilbert symbol used in the
bilinearity and nondegeneracy theorems. -/
theorem hilbert_symbol_subgroup
    (n : ℕ) (hn : 0 < n) {ζ : K} (hζ : IsPrimitiveRoot ζ n)
    (E : Type) [Field E] [Algebra K E]
    (a b : Kˣ)
    (hsplit : IsSplittingField K E (X ^ n - C (a : K)))
    (hirr : Irreducible (X ^ n - C (a : K))) :
    localKummerSymbol K n hn hζ
        (powerClass n a) (powerClass n b) = 1 ↔
      b ∈ normSubgroup K E := by
  rw [hilbert_symbol_artin K n hn hζ]
  exact
    kummer_hilbert_symbol
      K n hn hζ E a b hsplit hirr

/-- The diagonal norm identity: `(a,-a)_n = 1`.  Unlike the irreducible
norm criterion, this holds for every power class because the preceding norm
calculation works in the possibly lower-degree cyclic Kummer field. -/
theorem hilbert_symbol_diagonal
    (n : ℕ) (hn : 0 < n) {ζ : K} (hζ : IsPrimitiveRoot ζ n)
    (a : PowerClassGroup K n) :
    localKummerSymbol K n hn hζ a
      (powerClass n (-1 : Kˣ) * a) = 1 := by
  let b : Kˣ := (-1 : Kˣ) * powerClassRepresentative K n a
  have hbclass : powerClass n b = powerClass n (-1 : Kˣ) * a := by
    dsimp [b]
    rw [map_mul, power_class_representative]
  rw [hilbert_symbol_artin K n hn hζ]
  rw [← hbclass]
  exact (kummer_artin_symbol K n hn hζ a b).2
    (neg_representative_kummer K n hn hζ a)

@[simp]
theorem hilbert_symbol_coe
    (n : ℕ) (hn : 0 < n) {ζ : K} (hζ : IsPrimitiveRoot ζ n)
    (a b : PowerClassGroup K n) :
    ((localKummerSymbol K n hn hζ a b : rootsOfUnity n K) : Kˣ) =
      kummerHilbertPairing K n hn hζ a b :=
  rfl

@[simp]
theorem local_hilbert_pairing
    (n : ℕ) (hn : 0 < n) {ζ : K} (hζ : IsPrimitiveRoot ζ n)
    (a b : PowerClassGroup K n) :
    kummerHilbertPairing K n hn hζ a b =
      radicalKummerPairing K (AlgebraicClosure K) n
        (fullKummerExtension K n hn hζ) hn
        ⟨ζ, (mem_primitiveRoots hn).2 hζ⟩
        (localRadicalEquiv K n hn hζ a)
        (fullKummerArtin K n hn hζ b) :=
  rfl

theorem hilbert_symbol_left
    (n : ℕ) (hn : 0 < n) {ζ : K} (hζ : IsPrimitiveRoot ζ n)
    (a c b : PowerClassGroup K n) :
    localKummerSymbol K n hn hζ (a * c) b =
      localKummerSymbol K n hn hζ a b *
        localKummerSymbol K n hn hζ c b := by
  apply Subtype.ext
  simp

theorem hilbert_symbol_right
    (n : ℕ) (hn : 0 < n) {ζ : K} (hζ : IsPrimitiveRoot ζ n)
    (a b c : PowerClassGroup K n) :
    localKummerSymbol K n hn hζ a (b * c) =
      localKummerSymbol K n hn hζ a b *
        localKummerSymbol K n hn hζ a c := by
  apply Subtype.ext
  exact map_mul (kummerHilbertPairing K n hn hζ a) b c

/-- **Theorem III.4.4(b), skew symmetry.**  Polarizing the diagonal identity
`(x,-x)=1` gives `(a,b)(b,a)=1`; hence `(b,a)=(a,b)⁻¹`. -/
theorem kummer_hilbert_skew
    (n : ℕ) (hn : 0 < n) {ζ : K} (hζ : IsPrimitiveRoot ζ n)
    (a b : PowerClassGroup K n) :
    localKummerSymbol K n hn hζ b a =
      (localKummerSymbol K n hn hζ a b)⁻¹ := by
  let mone : PowerClassGroup K n := powerClass n (-1 : Kˣ)
  have ha :
      localKummerSymbol K n hn hζ a mone *
          localKummerSymbol K n hn hζ a a = 1 := by
    rw [← hilbert_symbol_right K n hn hζ a mone a]
    exact hilbert_symbol_diagonal K n hn hζ a
  have hb :
      localKummerSymbol K n hn hζ b mone *
          localKummerSymbol K n hn hζ b b = 1 := by
    rw [← hilbert_symbol_right K n hn hζ b mone b]
    exact hilbert_symbol_diagonal K n hn hζ b
  have haa : localKummerSymbol K n hn hζ a a =
      (localKummerSymbol K n hn hζ a mone)⁻¹ :=
    eq_inv_of_mul_eq_one_right ha
  have hbb : localKummerSymbol K n hn hζ b b =
      (localKummerSymbol K n hn hζ b mone)⁻¹ :=
    eq_inv_of_mul_eq_one_right hb
  have hab := hilbert_symbol_diagonal K n hn hζ (a * b)
  rw [hilbert_symbol_left K n hn hζ a b,
    hilbert_symbol_right K n hn hζ a mone (a * b),
    hilbert_symbol_right K n hn hζ a a b,
    hilbert_symbol_right K n hn hζ b mone (a * b),
    hilbert_symbol_right K n hn hζ b a b,
    haa, hbb] at hab
  have hcross :
      localKummerSymbol K n hn hζ a b *
        localKummerSymbol K n hn hζ b a = 1 := by
    simpa [mul_assoc, mul_comm, mul_left_comm] using hab
  exact eq_inv_of_mul_eq_one_right hcross

theorem kummer_hilbert_pairing
    (n : ℕ) (hn : 0 < n) {ζ : K} (hζ : IsPrimitiveRoot ζ n) :
    Function.Injective (kummerHilbertPairing K n hn hζ) := by
  intro a c hac
  apply (localRadicalEquiv K n hn hζ).injective
  apply kummer_pairing_injective K (AlgebraicClosure K) n
    (fullKummerExtension K n hn hζ) hn
    ⟨ζ, (mem_primitiveRoots hn).2 hζ⟩
  apply MonoidHom.ext
  intro σ
  obtain ⟨b, rfl⟩ := full_kummer_surjective K n hn hζ σ
  exact DFunLike.congr_fun hac b

/-- The Kummer--Artin Hilbert pairing has trivial left kernel. -/
theorem hilbert_symbol_kernel
    (n : ℕ) (hn : 0 < n) {ζ : K} (hζ : IsPrimitiveRoot ζ n)
    (a : PowerClassGroup K n)
    (ha : ∀ b, localKummerSymbol K n hn hζ a b = 1) :
    a = 1 := by
  apply kummer_hilbert_pairing K n hn hζ
  apply MonoidHom.ext
  intro b
  have h := congrArg Subtype.val (ha b)
  simpa using h

/-- The Kummer--Artin Hilbert pairing has trivial right kernel. -/
theorem local_hilbert_symbol
    (n : ℕ) (hn : 0 < n) {ζ : K} (hζ : IsPrimitiveRoot ζ n)
    (b : PowerClassGroup K n)
    (hb : ∀ a, localKummerSymbol K n hn hζ a b = 1) :
    b = 1 := by
  letI : NeZero n := ⟨hn.ne'⟩
  apply full_kummer_injective K n hn hζ
  let E := fullKummerExtension K n hn hζ
  let hroots : (primitiveRoots n K).Nonempty :=
    ⟨ζ, (mem_primitiveRoots hn).2 hζ⟩
  have hexp : Monoid.exponent Gal(E.carrier/K) ∣ n :=
    Monoid.exponent_dvd_of_forall_pow_eq_one E.exponent_dvd
  letI : HasEnoughRootsOfUnity K n :=
    HasEnoughRootsOfUnity.of_card_le (by rw [hζ.card_rootsOfUnity])
  letI : HasEnoughRootsOfUnity K (Monoid.exponent Gal(E.carrier/K)) :=
    HasEnoughRootsOfUnity.of_dvd K hexp
  rw [← CommGroup.forall_apply_eq_apply_iff
    (G := Gal(E.carrier/K)) (M := K)]
  intro φ
  obtain ⟨r, hr⟩ := radical_kummer_pairing
    K (AlgebraicClosure K) n E hn hroots φ
  obtain ⟨a, ha⟩ :=
    (localRadicalEquiv K n hn hζ).surjective r
  have hb' : kummerHilbertPairing K n hn hζ a b = 1 := by
    have h := congrArg Subtype.val (hb a)
    simpa using h
  calc
    φ (fullKummerArtin K n hn hζ b) =
        (radicalKummerPairing K (AlgebraicClosure K) n E hn hroots r)
          (fullKummerArtin K n hn hζ b) := by rw [hr]
    _ = kummerHilbertPairing K n hn hζ a b := by
      rw [← ha]
      rfl
    _ = 1 := hb'
    _ = φ (fullKummerArtin K n hn hζ 1) := by simp

/-- In characteristic zero, the full Kummer--Artin Hilbert symbol is
bilinear and nondegenerate in both variables. -/
theorem symbol_bilinear_nondegenerate
    (n : ℕ) (hn : 0 < n) {ζ : K} (hζ : IsPrimitiveRoot ζ n) :
    (∀ a a' b : PowerClassGroup K n,
      localKummerSymbol K n hn hζ (a * a') b =
        localKummerSymbol K n hn hζ a b *
          localKummerSymbol K n hn hζ a' b) ∧
    (∀ a b b' : PowerClassGroup K n,
      localKummerSymbol K n hn hζ a (b * b') =
        localKummerSymbol K n hn hζ a b *
          localKummerSymbol K n hn hζ a b') ∧
    (∀ a : PowerClassGroup K n,
      (∀ b, localKummerSymbol K n hn hζ a b = 1) → a = 1) ∧
    (∀ b : PowerClassGroup K n,
      (∀ a, localKummerSymbol K n hn hζ a b = 1) → b = 1) :=
  ⟨hilbert_symbol_left K n hn hζ,
    hilbert_symbol_right K n hn hζ,
    hilbert_symbol_kernel K n hn hζ,
    local_hilbert_symbol K n hn hζ⟩

end CharacteristicZero

end

end Towers.CField.HSymbol
