import Submission.ClassField.CyclotomicBrauer.CompletionDegree

/-!
# Lemma VII.7.3: transport of rational prime ideals

Mathlib's cyclotomic ramification formulas use the ideal `(p)` of `ℤ`,
whereas the finite-place completion API uses a height-one prime of
`NumberField.RingOfIntegers ℚ`.  This file transports the ramification and
inertia degrees across the canonical equivalence `𝓞 ℚ ≃+* ℤ`.
-/

namespace Submission.CField.CBrauer

open AbsoluteValue IsDedekindDomain NumberField
open Submission.NumberTheory.Milne
open Submission.CField.Ideles
open Submission.CField.ICohomo

noncomputable section

universe u

/-- A height-one prime of `𝓞 ℚ` lies over the principal ideal generated by
its positive rational-prime generator. -/
theorem rational_lies_generator
    (P : HeightOneSpectrum (NumberField.RingOfIntegers ℚ)) :
    P.asIdeal.LiesOver
      (Ideal.span ({(Rat.HeightOneSpectrum.natGenerator P : ℤ)} : Set ℤ)) := by
  let e : NumberField.RingOfIntegers ℚ ≃+* ℤ :=
    Rat.IsIntegralClosure.intEquiv (NumberField.RingOfIntegers ℚ)
  have halg : algebraMap ℤ (NumberField.RingOfIntegers ℚ) = e.symm.toRingHom := by
    ext n
    simp [e]
  rw [Ideal.liesOver_iff, Ideal.under_def, halg]
  change Ideal.span ({(Rat.HeightOneSpectrum.natGenerator P : ℤ)} : Set ℤ) =
    P.asIdeal.comap e.symm
  rw [Ideal.comap_symm]
  exact Rat.HeightOneSpectrum.span_natGenerator P

/-- The absolute norm of a rational height-one prime is its positive prime
generator. -/
theorem abs_rational_prime
    (P : HeightOneSpectrum (NumberField.RingOfIntegers ℚ)) :
    Ideal.absNorm P.asIdeal = Rat.HeightOneSpectrum.natGenerator P := by
  let e : NumberField.RingOfIntegers ℚ ≃+* ℤ := Rat.ringOfIntegersEquiv
  let J : Ideal ℤ := P.asIdeal.map e
  have hint :
      Rat.IsIntegralClosure.intEquiv (NumberField.RingOfIntegers ℚ) = e := by
    ext x
    exact Rat.IsIntegralClosure.intEquiv_apply_eq_ringOfIntegersEquiv x
  have hcard : Ideal.absNorm J = Ideal.absNorm P.asIdeal := by
    rw [Ideal.absNorm_apply, Ideal.absNorm_apply]
    let qequiv :
        (NumberField.RingOfIntegers ℚ ⧸ P.asIdeal) ≃+* (ℤ ⧸ J) :=
      Ideal.quotientEquiv P.asIdeal J e rfl
    exact Nat.card_congr qequiv.toEquiv.symm
  have hspan :
      J = Ideal.span
        ({(Rat.HeightOneSpectrum.natGenerator P : ℤ)} : Set ℤ) := by
    simpa [J, e, hint] using
      (Rat.HeightOneSpectrum.span_natGenerator
        (R := NumberField.RingOfIntegers ℚ) P).symm
  rw [← hcard, hspan, Ideal.absNorm_apply]
  simpa [Submodule.cardQuot_apply] using
    (Int.card_ideal_quot (Rat.HeightOneSpectrum.natGenerator P))

/-- Extending a rational height-one prime from `𝓞 ℚ` to the ring of
integers of a number field gives the same ideal as first identifying it
with `(p) ⊂ ℤ` and extending from `ℤ`. -/
theorem rational_span_generator
    (P : HeightOneSpectrum (NumberField.RingOfIntegers ℚ))
    (C : Type u) [Field C] [NumberField C] [Algebra ℚ C] :
    P.asIdeal.map
        (algebraMap (NumberField.RingOfIntegers ℚ)
          (NumberField.RingOfIntegers C)) =
      (Ideal.span
        ({(Rat.HeightOneSpectrum.natGenerator P : ℤ)} : Set ℤ)).map
          (algebraMap ℤ (NumberField.RingOfIntegers C)) := by
  let e : NumberField.RingOfIntegers ℚ ≃+* ℤ :=
    Rat.IsIntegralClosure.intEquiv (NumberField.RingOfIntegers ℚ)
  have he : e = Rat.ringOfIntegersEquiv := by
    ext x
    exact Rat.IsIntegralClosure.intEquiv_apply_eq_ringOfIntegersEquiv x
  have hspan :
      Ideal.span ({(Rat.HeightOneSpectrum.natGenerator P : ℤ)} : Set ℤ) =
        P.asIdeal.map e :=
    Rat.HeightOneSpectrum.span_natGenerator P
  calc
    P.asIdeal.map (algebraMap (NumberField.RingOfIntegers ℚ)
        (NumberField.RingOfIntegers C)) =
        P.asIdeal.map
          ((algebraMap ℤ (NumberField.RingOfIntegers C)).comp e.toRingHom) := by
      congr 1
      ext x
      change algebraMap ℚ C (x : ℚ) = ((e x : ℤ) : C)
      rw [he]
      calc
        algebraMap ℚ C (x : ℚ) =
            algebraMap ℚ C ((Rat.ringOfIntegersEquiv x : ℤ) : ℚ) := by
          exact congrArg (algebraMap ℚ C)
            (Rat.ringOfIntegersEquiv_apply_coe x).symm
        _ = ((Rat.ringOfIntegersEquiv x : ℤ) : C) := by
          exact map_intCast (algebraMap ℚ C) _
    _ = (P.asIdeal.map e.toRingHom).map
          (algebraMap ℤ (NumberField.RingOfIntegers C)) :=
      (P.asIdeal.map_map e.toRingHom
        (algebraMap ℤ (NumberField.RingOfIntegers C))).symm
    _ = (Ideal.span
          ({(Rat.HeightOneSpectrum.natGenerator P : ℤ)} : Set ℤ)).map
            (algebraMap ℤ (NumberField.RingOfIntegers C)) := by
      congr 2
      exact hspan.symm

set_option maxHeartbeats 2000000 in
-- Constructing both integral Galois actions makes instance synthesis deep.
/-- Ramification indices computed from a rational height-one prime agree
with the cyclotomic API's computation from the corresponding ideal of
`ℤ`. -/
theorem ramification_idx_span
    (P : HeightOneSpectrum (NumberField.RingOfIntegers ℚ))
    (C : Type u) [Field C] [NumberField C] [Algebra ℚ C]
    [FiniteDimensional ℚ C] [IsGalois ℚ C] :
    P.asIdeal.ramificationIdxIn (NumberField.RingOfIntegers C) =
      (Ideal.span
        ({(Rat.HeightOneSpectrum.natGenerator P : ℤ)} : Set ℤ)).ramificationIdxIn
          (NumberField.RingOfIntegers C) := by
  let pZ : Ideal ℤ := Ideal.span
    ({(Rat.HeightOneSpectrum.natGenerator P : ℤ)} : Set ℤ)
  let pQ : Ideal (NumberField.RingOfIntegers ℚ) := P.asIdeal
  letI : Fact (Nat.Prime (Rat.HeightOneSpectrum.natGenerator P)) :=
    ⟨Rat.HeightOneSpectrum.prime_natGenerator P⟩
  letI : pQ.IsMaximal := inferInstance
  letI : pZ.IsMaximal :=
    Int.ideal_span_isMaximal_of_prime
      (Rat.HeightOneSpectrum.natGenerator P)
  letI : pQ.LiesOver pZ :=
    rational_lies_generator P
  letI : IsGaloisGroup Gal(C/ℚ)
      (NumberField.RingOfIntegers ℚ) (NumberField.RingOfIntegers C) :=
    IsGaloisGroup.of_isFractionRing Gal(C/ℚ)
      (NumberField.RingOfIntegers ℚ) (NumberField.RingOfIntegers C) ℚ C
  letI : IsGaloisGroup Gal(C/ℚ) ℤ (NumberField.RingOfIntegers C) :=
    IsGaloisGroup.of_isFractionRing Gal(C/ℚ)
      ℤ (NumberField.RingOfIntegers C) ℚ C
  obtain ⟨⟨Q, hQprime, hQover⟩⟩ :=
    pQ.nonempty_primesOver (S := NumberField.RingOfIntegers C)
  letI : Q.IsPrime := hQprime
  letI : Q.LiesOver pQ := hQover
  letI : Q.LiesOver pZ := Ideal.LiesOver.trans Q pQ pZ
  rw [Ideal.ramificationIdxIn_eq_ramificationIdx pQ Q Gal(C/ℚ),
    Ideal.ramificationIdxIn_eq_ramificationIdx pZ Q Gal(C/ℚ)]
  unfold Ideal.ramificationIdx
  rw [rational_span_generator P C]

set_option maxHeartbeats 2000000 in
-- Constructing both integral Galois actions makes instance synthesis deep.
/-- Inertia degrees computed from a rational height-one prime agree with
the cyclotomic API's computation from the corresponding ideal of `ℤ`. -/
theorem rational_deg_span
    (P : HeightOneSpectrum (NumberField.RingOfIntegers ℚ))
    (C : Type u) [Field C] [NumberField C] [Algebra ℚ C]
    [FiniteDimensional ℚ C] [IsGalois ℚ C] :
    P.asIdeal.inertiaDegIn (NumberField.RingOfIntegers C) =
      (Ideal.span
        ({(Rat.HeightOneSpectrum.natGenerator P : ℤ)} : Set ℤ)).inertiaDegIn
          (NumberField.RingOfIntegers C) := by
  let p := Rat.HeightOneSpectrum.natGenerator P
  let pZ : Ideal ℤ := Ideal.span ({(p : ℤ)} : Set ℤ)
  let pQ : Ideal (NumberField.RingOfIntegers ℚ) := P.asIdeal
  have hp : p.Prime := Rat.HeightOneSpectrum.prime_natGenerator P
  letI : Fact p.Prime := ⟨hp⟩
  letI : pQ.IsMaximal := inferInstance
  letI : pZ.IsMaximal := Int.ideal_span_isMaximal_of_prime p
  letI : pQ.LiesOver pZ :=
    rational_lies_generator P
  letI : IsGaloisGroup Gal(C/ℚ)
      (NumberField.RingOfIntegers ℚ) (NumberField.RingOfIntegers C) :=
    IsGaloisGroup.of_isFractionRing Gal(C/ℚ)
      (NumberField.RingOfIntegers ℚ) (NumberField.RingOfIntegers C) ℚ C
  letI : IsGaloisGroup Gal(C/ℚ) ℤ (NumberField.RingOfIntegers C) :=
    IsGaloisGroup.of_isFractionRing Gal(C/ℚ)
      ℤ (NumberField.RingOfIntegers C) ℚ C
  obtain ⟨⟨Q, hQprime, hQover⟩⟩ :=
    pQ.nonempty_primesOver (S := NumberField.RingOfIntegers C)
  letI : Q.IsPrime := hQprime
  letI : Q.LiesOver pQ := hQover
  letI : Q.LiesOver pZ := Ideal.LiesOver.trans Q pQ pZ
  rw [Ideal.inertiaDegIn_eq_inertiaDeg pQ Q Gal(C/ℚ),
    Ideal.inertiaDegIn_eq_inertiaDeg pZ Q Gal(C/ℚ)]
  rw [← Nat.pow_right_inj hp.one_lt]
  have hnorm : Ideal.absNorm pQ = p := by
    simpa only [pQ, p] using abs_rational_prime P
  calc
    p ^ pQ.inertiaDeg Q = Ideal.absNorm pQ ^ pQ.inertiaDeg Q := by
      rw [hnorm]
    _ = Ideal.absNorm Q :=
      (Ideal.absNorm_eq_pow_inertiaDeg_of_liesOver Q pQ
        (show pQ.IsPrime from inferInstance) P.ne_bot).symm
    _ = p ^ pZ.inertiaDeg Q := by
      exact Ideal.absNorm_eq_pow_inertiaDeg' Q hp

end

end Submission.CField.CBrauer
