import Submission.Group.Edmonton.BurnsideWielandt
import Mathlib.GroupTheory.Finiteness
import Mathlib.GroupTheory.SpecificGroups.Cyclic.Basic
import Mathlib.Order.Zorn

/-!
# The Edmonton Notes on Nilpotent Groups: locally nilpotent groups

This file begins the formalization of Hall's Theorem 2.8.
-/

namespace Submission
namespace Edmonton

open Group
open scoped commutatorElement Pointwise

universe u

variable {G : Type u} [Group G]

/-- A group is locally nilpotent in Hall's sense if each of its finitely
generated subgroups is nilpotent. -/
def Group.IsLocallyNilpotent (G : Type u) [Group G] : Prop :=
  ∀ H : Subgroup G, H.FG → Group.IsNilpotent H

/-- A finitely generated ambient subgroup contained in a locally nilpotent
subgroup is nilpotent. -/
lemma nilpotent_fg_locally
    {H K : Subgroup G} (hH : Group.IsLocallyNilpotent H)
    (hKfg : K.FG) (hKH : K ≤ H) :
    Group.IsNilpotent K := by
  let e : K.subgroupOf H ≃* K := Subgroup.subgroupOfEquivOfLe hKH
  letI : Group.FG K := (Group.fg_iff_subgroup_fg K).mpr hKfg
  letI : Group.FG (K.subgroupOf H) :=
    Group.fg_of_surjective (f := e.symm.toMonoidHom) e.symm.surjective
  have hsubfg : (K.subgroupOf H).FG :=
    (Group.fg_iff_subgroup_fg (K.subgroupOf H)).mp inferInstance
  letI : Group.IsNilpotent (K.subgroupOf H) := hH _ hsubfg
  exact Group.nilpotent_of_mulEquiv e

/-- Every subgroup of a finitely generated nilpotent group is finitely
generated, stated for ambient subgroups. -/
lemma fg_nilpotent
    {H K : Subgroup G} (hHfg : H.FG) [Group.IsNilpotent H]
    (hKH : K ≤ H) :
    K.FG := by
  letI : Group.FG H := (Group.fg_iff_subgroup_fg H).mpr hHfg
  have hpoly : IsPolycyclic H :=
    supersoluble_implies_polycyclic
      fg_implies_supersoluble
  have hsubfg : (K.subgroupOf H).FG :=
    polycyclic_implies_condition hpoly (K.subgroupOf H)
  letI : Group.FG (K.subgroupOf H) :=
    (Group.fg_iff_subgroup_fg (K.subgroupOf H)).mpr hsubfg
  let e : K.subgroupOf H ≃* K := Subgroup.subgroupOfEquivOfLe hKH
  letI : Group.FG K :=
    Group.fg_of_surjective (f := e.toMonoidHom) e.surjective
  exact (Group.fg_iff_subgroup_fg K).mp inferInstance

/-- Nilpotence inherited by an ambient subgroup. -/
lemma is_le_is
    {H K : Subgroup G} (hKH : K ≤ H) (hH : Group.IsNilpotent H) :
    Group.IsNilpotent K := by
  letI : Group.IsNilpotent H := hH
  letI : Group.IsNilpotent (K.subgroupOf H) := inferInstance
  exact Group.nilpotent_of_mulEquiv (Subgroup.subgroupOfEquivOfLe hKH)

/-- Every element of the derived subgroup lies in the derived subgroup of a
finitely generated subgroup. -/
lemma fg_commutator {x : G} (hx : x ∈ commutator G) :
    ∃ H : Subgroup G, H.FG ∧ x ∈ ⁅H, H⁆ := by
  classical
  rw [commutator_eq_closure] at hx
  induction hx using Subgroup.closure_induction with
  | mem z hz =>
      obtain ⟨a, b, rfl⟩ := (mem_commutatorSet_iff.mp hz)
      let H : Subgroup G := Subgroup.closure ({a, b} : Set G)
      refine ⟨H, ⟨{a, b}, by simp [H]⟩, ?_⟩
      exact Subgroup.commutator_mem_commutator
        (Subgroup.subset_closure (by simp))
        (Subgroup.subset_closure (by simp))
  | one =>
      exact ⟨⊥, Subgroup.FG.bot, by simp⟩
  | mul a b _ _ iha ihb =>
      obtain ⟨A, hAfg, ha⟩ := iha
      obtain ⟨B, hBfg, hb⟩ := ihb
      refine ⟨A ⊔ B, hAfg.sup hBfg, ?_⟩
      exact (⁅A ⊔ B, A ⊔ B⁆).mul_mem
        (Subgroup.commutator_mono le_sup_left le_sup_left ha)
        (Subgroup.commutator_mono le_sup_right le_sup_right hb)
  | inv a _ iha =>
      obtain ⟨A, hAfg, ha⟩ := iha
      exact ⟨A, hAfg, (⁅A, A⁆).inv_mem ha⟩

/-- If `g` lies in the subgroup generated by `M` and `x`, then only a
finitely generated part of `M` is needed to generate `g` together with `x`. -/
lemma fg_sup_closure
    {M : Subgroup G} {x g : G}
    (hg : g ∈ M ⊔ Subgroup.closure ({x} : Set G)) :
    ∃ K : Subgroup G, K.FG ∧ K ≤ M ∧
      g ∈ K ⊔ Subgroup.closure ({x} : Set G) := by
  classical
  rw [Subgroup.sup_eq_closure] at hg
  induction hg using Subgroup.closure_induction with
  | mem z hz =>
      rcases hz with hzM | hzx
      · refine ⟨Subgroup.closure ({z} : Set G), ⟨{z}, by simp⟩, ?_, ?_⟩
        · rw [Subgroup.closure_le]
          simpa using hzM
        · exact Subgroup.mem_sup_left
            (Subgroup.subset_closure (Set.mem_singleton z))
      · exact ⟨⊥, Subgroup.FG.bot, bot_le, Subgroup.mem_sup_right hzx⟩
  | one =>
      exact ⟨⊥, Subgroup.FG.bot, bot_le, Subgroup.one_mem _⟩
  | mul a b _ _ iha ihb =>
      obtain ⟨A, hAfg, hAM, ha⟩ := iha
      obtain ⟨B, hBfg, hBM, hb⟩ := ihb
      refine ⟨A ⊔ B, hAfg.sup hBfg, sup_le hAM hBM, ?_⟩
      apply (A ⊔ B ⊔ Subgroup.closure ({x} : Set G)).mul_mem
      · have hle :
            A ⊔ Subgroup.closure ({x} : Set G) ≤
              A ⊔ B ⊔ Subgroup.closure ({x} : Set G) :=
          sup_le (le_sup_left.trans le_sup_left) le_sup_right
        exact hle ha
      · have hle :
            B ⊔ Subgroup.closure ({x} : Set G) ≤
              A ⊔ B ⊔ Subgroup.closure ({x} : Set G) :=
          sup_le (le_sup_right.trans le_sup_left) le_sup_right
        exact hle hb
  | inv a _ iha =>
      obtain ⟨A, hAfg, hAM, ha⟩ := iha
      exact ⟨A, hAfg, hAM,
        (A ⊔ Subgroup.closure ({x} : Set G)).inv_mem ha⟩

/-- A finitely generated subgroup contained in `M ⊔ ⟨x⟩` is contained in
`K ⊔ ⟨x⟩` for some finitely generated subgroup `K ≤ M`. -/
lemma fg_sup_singleton
    {H M : Subgroup G} {x : G} (hHfg : H.FG)
    (hH : H ≤ M ⊔ Subgroup.closure ({x} : Set G)) :
    ∃ K : Subgroup G, K.FG ∧ K ≤ M ∧
      H ≤ K ⊔ Subgroup.closure ({x} : Set G) := by
  classical
  obtain ⟨S, rfl⟩ := hHfg
  choose K hKfg hKM hKmem using fun s : S ↦
    fg_sup_closure
      (hH (Subgroup.subset_closure s.property))
  let L : Subgroup G := ⨆ s : S, K s
  refine ⟨L, Subgroup.FG.iSup K hKfg, iSup_le hKM, ?_⟩
  rw [Subgroup.closure_le]
  intro y hy
  let s : S := ⟨y, hy⟩
  have hle :
      K s ⊔ Subgroup.closure ({x} : Set G) ≤
        L ⊔ Subgroup.closure ({x} : Set G) :=
    sup_le ((le_iSup K s).trans le_sup_left) le_sup_right
  exact hle (hKmem s)

/-- **Hall, Theorem 2.8(i) (McLain).** Every maximal subgroup of a locally
nilpotent group is normal. -/
theorem maximal_locally_nilpotent
    (hG : Group.IsLocallyNilpotent G) (M : Subgroup G) (hM : IsCoatom M) :
    M.Normal := by
  by_contra hMnormal
  have hcomm_not_le : ¬ commutator G ≤ M := by
    intro hcomm
    exact hMnormal (Subgroup.Normal.of_commutator_le (G := G) hcomm)
  obtain ⟨x, hxcomm, hxM⟩ := SetLike.not_le_iff_exists.mp hcomm_not_le
  have hMlt :
      M < M ⊔ Subgroup.closure ({x} : Set G) := by
    constructor
    · exact (le_sup_left :
        M ≤ M ⊔ Subgroup.closure ({x} : Set G))
    intro h
    exact hxM (h (Subgroup.mem_sup_right
      (Subgroup.mem_closure_singleton_self x)))
  have hsup :
      M ⊔ Subgroup.closure ({x} : Set G) = ⊤ :=
    hM.2 _ hMlt
  obtain ⟨H, hHfg, hxHcomm⟩ := fg_commutator hxcomm
  obtain ⟨K, hKfg, hKM, hHL⟩ :=
    fg_sup_singleton hHfg
      (by rw [hsup]; exact le_top)
  let L : Subgroup G := K ⊔ Subgroup.closure ({x} : Set G)
  have hLfg : L.FG :=
    hKfg.sup ⟨{x}, by simp⟩
  have hxLcomm : x ∈ ⁅L, L⁆ :=
    Subgroup.commutator_mono hHL hHL hxHcomm
  have hxK : x ∉ K := fun hx ↦ hxM (hKM hx)
  have hKltL : K < L := by
    constructor
    · exact (le_sup_left : K ≤ L)
    intro h
    exact hxK (h (Subgroup.mem_sup_right
      (Subgroup.mem_closure_singleton_self x)))
  have hLnilpotent : Group.IsNilpotent L :=
    hG L hLfg
  letI : Group.IsNilpotent L := hLnilpotent
  let KL : Subgroup L := K.subgroupOf L
  have hKLlt : KL < ⊤ := by
    rw [lt_top_iff_ne_top, ne_eq, Subgroup.subgroupOf_eq_top]
    exact hKltL.2
  have hproper :
      commutator L ⊔ KL < (⊤ : Subgroup L) :=
    sup_top hKLlt
  have htop_le :
      (⊤ : Subgroup L) ≤ commutator L ⊔ KL := by
    rw [← Subgroup.map_subtype_le_map_subtype,
      Subgroup.map_sup, Subgroup.map_subtype_commutator,
      Subgroup.map_subgroupOf_eq_of_le le_sup_left,
      ← MonoidHom.range_eq_map, L.range_subtype]
    dsimp [L]
    apply sup_le le_sup_right
    rw [Subgroup.closure_le]
    intro y hy
    rw [Set.mem_singleton_iff.mp hy]
    exact Subgroup.mem_sup_left hxLcomm
  exact hproper.2 htop_le

/-- Basic Hall commutators formed from two finite sets form a finite set. -/
lemma basic_commutators_finite
    {A B : Set G} (hA : A.Finite) (hB : B.Finite) :
    (basicHallCommutators A B).Finite := by
  apply ((hA.prod hB).image (fun p : G × G ↦ hallCommutator p.1 p.2)).subset
  rintro c ⟨a, ha, b, hb, rfl⟩
  exact ⟨(a, b), ⟨ha, hb⟩, rfl⟩

/-- Ambient form of Hirsch's argument: a finitely generated subgroup of the
supremum of two normal locally nilpotent subgroups is nilpotent. -/
lemma fg_locally_nilpotent
    {H K J : Subgroup G} [H.Normal] [K.Normal]
    (hHloc : Group.IsLocallyNilpotent H)
    (hKloc : Group.IsLocallyNilpotent K)
    (hJfg : J.FG) (hJle : J ≤ H ⊔ K) :
    Group.IsNilpotent J := by
  classical
  obtain ⟨S, hS⟩ := hJfg
  choose a ha b hb hab using fun s : S ↦
    Subgroup.mem_sup_of_normal_right.mp
      (hJle (hS ▸ Subgroup.subset_closure s.property))
  let A : Set G := Set.range a
  let B : Set G := Set.range b
  let X : Subgroup G := Subgroup.closure A
  let Y : Subgroup G := Subgroup.closure B
  have hAfinite : A.Finite := Set.finite_range a
  have hBfinite : B.Finite := Set.finite_range b
  have hXfg : X.FG :=
    (Subgroup.fg_iff X).mpr ⟨A, rfl, hAfinite⟩
  have hYfg : Y.FG :=
    (Subgroup.fg_iff Y).mpr ⟨B, rfl, hBfinite⟩
  have hXH : X ≤ H := by
    change Subgroup.closure A ≤ H
    rw [Subgroup.closure_le]
    rintro _ ⟨s, rfl⟩
    exact ha s
  have hYK : Y ≤ K := by
    change Subgroup.closure B ≤ K
    rw [Subgroup.closure_le]
    rintro _ ⟨s, rfl⟩
    exact hb s
  have hJXY : J ≤ X ⊔ Y := by
    rw [← hS, Subgroup.closure_le]
    intro z hz
    let s : S := ⟨z, hz⟩
    have hprod : a s * b s ∈ X ⊔ Y :=
      (X ⊔ Y).mul_mem
      (Subgroup.mem_sup_left
        (Subgroup.subset_closure ⟨s, rfl⟩))
      (Subgroup.mem_sup_right
        (Subgroup.subset_closure ⟨s, rfl⟩))
    simpa [s, hab s] using hprod
  let C : Set G := basicHallCommutators A B
  have hCfinite : C.Finite :=
    basic_commutators_finite hAfinite hBfinite
  have hCH : C ⊆ H := by
    rintro _ ⟨x, hx, y, hy, rfl⟩
    have hxH : x ∈ H := hXH (Subgroup.subset_closure hx)
    have hyK : y ∈ K := hYK (Subgroup.subset_closure hy)
    exact Subgroup.commutator_le_left H K
      (hall_commutator hxH hyK)
  have hCK : C ⊆ K := by
    rintro _ ⟨x, hx, y, hy, rfl⟩
    have hxH : x ∈ H := hXH (Subgroup.subset_closure hx)
    have hyK : y ∈ K := hYK (Subgroup.subset_closure hy)
    exact Subgroup.commutator_le_right H K
      (hall_commutator hxH hyK)
  let P : Subgroup G := relativeNormalClosure C X
  have hPleH : P ≤ H :=
    relative_normal_closure hCH
      (hXH.trans Subgroup.le_normalizer_of_normal)
  have hPleK : P ≤ K :=
    relative_normal_closure hCK Subgroup.le_normalizer_of_normal
  have hPleCX : P ≤ Subgroup.closure C ⊔ X := by
    apply relative_normal_closure
    · exact fun z hz ↦
        Subgroup.mem_sup_left (Subgroup.subset_closure hz)
    · exact le_sup_right.trans Subgroup.le_normalizer
  have hCXfg : (Subgroup.closure C ⊔ X).FG := by
    apply Subgroup.FG.sup
    · exact (Subgroup.fg_iff (Subgroup.closure C)).mpr
        ⟨C, rfl, hCfinite⟩
    · exact hXfg
  have hclosureCleH : Subgroup.closure C ≤ H := by
    rw [Subgroup.closure_le]
    exact hCH
  have hCXleH : Subgroup.closure C ⊔ X ≤ H :=
    sup_le hclosureCleH hXH
  have hCXnil :
      Group.IsNilpotent (Subgroup.closure C ⊔ X : Subgroup G) :=
    nilpotent_fg_locally hHloc hCXfg hCXleH
  letI : Group.IsNilpotent (Subgroup.closure C ⊔ X : Subgroup G) := hCXnil
  have hPfg : P.FG :=
    fg_nilpotent hCXfg hPleCX
  let Q : Subgroup G := relativeNormalClosure (P : Set G) Y
  have hQlePY : Q ≤ P ⊔ Y := by
    apply relative_normal_closure
    · exact fun z hz ↦ Subgroup.mem_sup_left hz
    · exact le_sup_right.trans Subgroup.le_normalizer
  have hPYfg : (P ⊔ Y).FG := hPfg.sup hYfg
  have hPYleK : P ⊔ Y ≤ K := sup_le hPleK hYK
  have hPYnil : Group.IsNilpotent (P ⊔ Y : Subgroup G) :=
    nilpotent_fg_locally hKloc hPYfg hPYleK
  letI : Group.IsNilpotent (P ⊔ Y : Subgroup G) := hPYnil
  have hQfg : Q.FG :=
    fg_nilpotent hPYfg hQlePY
  have hQeq : Q = ⁅X, Y⁆ := by
    simpa [Q, P, X, Y, C] using (commutator_closures_iterated A B).symm
  let Xbar : Subgroup G := commutatorExtensionLeft X Y
  let Ybar : Subgroup G := commutatorExtensionRight X Y
  have hXbarfg : Xbar.FG := by
    change (X ⊔ ⁅X, Y⁆).FG
    rw [← hQeq]
    exact hXfg.sup hQfg
  have hYbarfg : Ybar.FG := by
    change (Y ⊔ ⁅X, Y⁆).FG
    rw [← hQeq]
    exact hYfg.sup hQfg
  have hXbarH : Xbar ≤ H := by
    change X ⊔ ⁅X, Y⁆ ≤ H
    exact sup_le hXH
      ((Subgroup.commutator_mono hXH hYK).trans
        (Subgroup.commutator_le_left H K))
  have hYbarK : Ybar ≤ K := by
    change Y ⊔ ⁅X, Y⁆ ≤ K
    exact sup_le hYK
      ((Subgroup.commutator_mono hXH hYK).trans
        (Subgroup.commutator_le_right H K))
  have hXbarnil : Group.IsNilpotent Xbar :=
    nilpotent_fg_locally hHloc hXbarfg hXbarH
  have hYbarnil : Group.IsNilpotent Ybar :=
    nilpotent_fg_locally hKloc hYbarfg hYbarK
  let L : Subgroup G := X ⊔ Y
  have hXbarL : Xbar ≤ L := by
    change Xbar ≤ X ⊔ Y
    rw [← commutator_extensions_sup X Y]
    exact le_sup_left
  have hYbarL : Ybar ≤ L := by
    change Ybar ≤ X ⊔ Y
    rw [← commutator_extensions_sup X Y]
    exact le_sup_right
  let XL : Subgroup L := Xbar.subgroupOf L
  let YL : Subgroup L := Ybar.subgroupOf L
  letI : XL.Normal := by
    exact commutator_normal_sup X Y
  letI : YL.Normal := by
    exact commutator_extension_sup X Y
  letI : Group.IsNilpotent XL := by
    letI : Group.IsNilpotent Xbar := hXbarnil
    exact Group.nilpotent_of_mulEquiv (Subgroup.subgroupOfEquivOfLe hXbarL).symm
  letI : Group.IsNilpotent YL := by
    letI : Group.IsNilpotent Ybar := hYbarnil
    exact Group.nilpotent_of_mulEquiv (Subgroup.subgroupOfEquivOfLe hYbarL).symm
  have hsupTop : XL ⊔ YL = (⊤ : Subgroup L) := by
    change Xbar.subgroupOf L ⊔ Ybar.subgroupOf L = ⊤
    rw [← Subgroup.subgroupOf_sup hXbarL hYbarL,
      commutator_extensions_sup X Y]
    exact Subgroup.subgroupOf_self L
  have htopNil : Group.IsNilpotent (⊤ : Subgroup L) := by
    rw [← hsupTop]
    exact (fitting_nilpotent XL YL).1
  have hLnil : Group.IsNilpotent L := by
    letI : Group.IsNilpotent (⊤ : Subgroup L) := htopNil
    exact Group.nilpotent_of_mulEquiv Subgroup.topEquiv
  exact is_le_is hJXY hLnil

/-- **Hall, Theorem 2.8(ii) (Hirsch).** The product of two normal locally
nilpotent subgroups is locally nilpotent. -/
theorem sup_locally_nilpotent
    (H K : Subgroup G) [H.Normal] [K.Normal]
    (hH : Group.IsLocallyNilpotent H)
    (hK : Group.IsLocallyNilpotent K) :
    Group.IsLocallyNilpotent (H ⊔ K : Subgroup G) := by
  intro J hJfg
  let L : Subgroup G := H ⊔ K
  let JG : Subgroup G := J.map L.subtype
  letI : Group.FG J := (Group.fg_iff_subgroup_fg J).mpr hJfg
  let e : J ≃* JG :=
    Subgroup.equivMapOfInjective J L.subtype L.subtype_injective
  letI : Group.FG JG :=
    Group.fg_of_surjective (f := e.toMonoidHom) e.surjective
  have hJGfg : JG.FG :=
    (Group.fg_iff_subgroup_fg JG).mp inferInstance
  have hJGle : JG ≤ H ⊔ K := by
    exact Subgroup.map_subtype_le J
  have hJGnil : Group.IsNilpotent JG :=
    fg_locally_nilpotent
      hH hK hJGfg hJGle
  letI : Group.IsNilpotent JG := hJGnil
  exact Group.nilpotent_of_mulEquiv e.symm

/-- A nilpotent group is locally nilpotent. -/
lemma locally_nilpotent
    (hG : Group.IsNilpotent G) :
    Group.IsLocallyNilpotent G := by
  intro H _
  letI : Group.IsNilpotent G := hG
  infer_instance

/-- Local nilpotence of a subgroup can be tested on finitely generated
subgroups of the ambient group which it contains. -/
lemma locally_nilpotent_ambient (H : Subgroup G) :
    Group.IsLocallyNilpotent H ↔
      ∀ K : Subgroup G, K.FG → K ≤ H → Group.IsNilpotent K := by
  constructor
  · intro hH K hKfg hKH
    exact nilpotent_fg_locally hH hKfg hKH
  · intro hH K hKfg
    let KG : Subgroup G := K.map H.subtype
    letI : Group.FG K := (Group.fg_iff_subgroup_fg K).mpr hKfg
    let e : K ≃* KG :=
      Subgroup.equivMapOfInjective K H.subtype H.subtype_injective
    letI : Group.FG KG :=
      Group.fg_of_surjective (f := e.toMonoidHom) e.surjective
    have hKGfg : KG.FG :=
      (Group.fg_iff_subgroup_fg KG).mp inferInstance
    have hKGnil : Group.IsNilpotent KG :=
      hH KG hKGfg (Subgroup.map_subtype_le K)
    letI : Group.IsNilpotent KG := hKGnil
    exact Group.nilpotent_of_mulEquiv e.symm

/-- Local nilpotence is invariant under an isomorphism of groups. -/
lemma locally_nilpotent_congr
    {G' : Type u} [Group G'] (e : G ≃* G') :
    Group.IsLocallyNilpotent G ↔ Group.IsLocallyNilpotent G' := by
  constructor
  · intro hG H hHfg
    let K : Subgroup G := H.map e.symm.toMonoidHom
    let f : H ≃* K := e.symm.subgroupMap H
    letI : Group.FG H := (Group.fg_iff_subgroup_fg H).mpr hHfg
    letI : Group.FG K :=
      Group.fg_of_surjective (f := f.toMonoidHom) f.surjective
    have hKfg : K.FG :=
      (Group.fg_iff_subgroup_fg K).mp inferInstance
    have hKnil : Group.IsNilpotent K := hG K hKfg
    letI : Group.IsNilpotent K := hKnil
    exact Group.nilpotent_of_mulEquiv f.symm
  · intro hG' H hHfg
    let K : Subgroup G' := H.map e.toMonoidHom
    let f : H ≃* K := e.subgroupMap H
    letI : Group.FG H := (Group.fg_iff_subgroup_fg H).mpr hHfg
    letI : Group.FG K :=
      Group.fg_of_surjective (f := f.toMonoidHom) f.surjective
    have hKfg : K.FG :=
      (Group.fg_iff_subgroup_fg K).mp inferInstance
    have hKnil : Group.IsNilpotent K := hG' K hKfg
    letI : Group.IsNilpotent K := hKnil
    exact Group.nilpotent_of_mulEquiv f.symm

/-- The carrier union of a nonempty chain of subgroups is a subgroup. -/
def subgroupUnionChain
    (c : Set (Subgroup G)) (hc : IsChain (· ≤ ·) c) (hne : c.Nonempty) :
    Subgroup G where
  carrier := ⋃ H ∈ c, (H : Set G)
  one_mem' := by
    obtain ⟨H, hH⟩ := hne
    exact Set.mem_iUnion.2 ⟨H, Set.mem_iUnion.2 ⟨hH, H.one_mem⟩⟩
  mul_mem' := by
    intro x y hx hy
    rcases Set.mem_iUnion.mp hx with ⟨H, hx⟩
    rcases Set.mem_iUnion.mp hx with ⟨hH, hxH⟩
    rcases Set.mem_iUnion.mp hy with ⟨K, hy⟩
    rcases Set.mem_iUnion.mp hy with ⟨hK, hyK⟩
    rcases hc.total hH hK with hHK | hKH
    · exact Set.mem_iUnion.2
        ⟨K, Set.mem_iUnion.2 ⟨hK, K.mul_mem (hHK hxH) hyK⟩⟩
    · exact Set.mem_iUnion.2
        ⟨H, Set.mem_iUnion.2 ⟨hH, H.mul_mem hxH (hKH hyK)⟩⟩
  inv_mem' := by
    intro x hx
    rcases Set.mem_iUnion.mp hx with ⟨H, hx⟩
    rcases Set.mem_iUnion.mp hx with ⟨hH, hxH⟩
    exact Set.mem_iUnion.2
      ⟨H, Set.mem_iUnion.2 ⟨hH, H.inv_mem hxH⟩⟩

@[simp]
lemma subgroup_union_chain
    {c : Set (Subgroup G)} {hc : IsChain (· ≤ ·) c} {hne : c.Nonempty}
    {x : G} :
    x ∈ subgroupUnionChain c hc hne ↔ ∃ H ∈ c, x ∈ H := by
  simp [subgroupUnionChain]

lemma union_chain
    {c : Set (Subgroup G)} {hc : IsChain (· ≤ ·) c} {hne : c.Nonempty}
    {H : Subgroup G} (hH : H ∈ c) :
    H ≤ subgroupUnionChain c hc hne := by
  intro x hx
  exact subgroup_union_chain.mpr ⟨H, hH, hx⟩

/-- The union of a nonempty chain of locally nilpotent subgroups is locally
nilpotent. -/
lemma chain_locally_nilpotent
    (c : Set (Subgroup G)) (hc : IsChain (· ≤ ·) c) (hne : c.Nonempty)
    (hloc : ∀ H ∈ c, Group.IsLocallyNilpotent H) :
    Group.IsLocallyNilpotent (subgroupUnionChain c hc hne) := by
  classical
  rw [locally_nilpotent_ambient]
  intro J hJfg hJU
  obtain ⟨S, hS⟩ := hJfg
  have hgen : ∀ s ∈ S, ∃ H ∈ c, s ∈ H := by
    intro s hs
    exact subgroup_union_chain.mp
      (hJU (hS ▸ Subgroup.subset_closure hs))
  have finite_chain_bound :
      ∀ T : Finset G, (∀ s ∈ T, ∃ H ∈ c, s ∈ H) →
        ∃ H ∈ c, ∀ s ∈ T, s ∈ H := by
    intro T
    induction T using Finset.induction_on with
    | empty =>
        intro _
        obtain ⟨H, hH⟩ := hne
        exact ⟨H, hH, by simp⟩
    | @insert x T hx ih =>
        intro hT
        obtain ⟨H, hH, hxH⟩ := hT x (by simp)
        obtain ⟨K, hK, hTK⟩ := ih (by
          intro s hs
          exact hT s (by simp [hs]))
        rcases hc.total hH hK with hHK | hKH
        · exact ⟨K, hK, by
            intro s hs
            rcases Finset.mem_insert.mp hs with rfl | hs
            · exact hHK hxH
            · exact hTK s hs⟩
        · exact ⟨H, hH, by
            intro s hs
            rcases Finset.mem_insert.mp hs with rfl | hs
            · exact hxH
            · exact hKH (hTK s hs)⟩
  obtain ⟨H, hH, hSH⟩ := finite_chain_bound S hgen
  have hJH : J ≤ H := by
    rw [← hS, Subgroup.closure_le]
    exact hSH
  exact nilpotent_fg_locally (hloc H hH) ⟨S, hS⟩ hJH

/-- Every element is contained in a maximal locally nilpotent subgroup. -/
lemma maximal_locally_subgroup (x : G) :
    ∃ M : Subgroup G, x ∈ M ∧ Group.IsLocallyNilpotent M ∧
      Maximal (fun H : Subgroup G ↦ Group.IsLocallyNilpotent H) M := by
  have hxloc : Group.IsLocallyNilpotent (Subgroup.zpowers x) := by
    letI : CommGroup (Subgroup.zpowers x) := IsCyclic.commGroup
    exact locally_nilpotent inferInstance
  obtain ⟨M, hxM, hMmax⟩ :=
    zorn_le_nonempty₀
      {H : Subgroup G | Group.IsLocallyNilpotent H}
      (by
        intro c hcloc hc y hy
        let U := subgroupUnionChain c hc ⟨y, hy⟩
        refine ⟨U, ?_, ?_⟩
        · exact chain_locally_nilpotent c hc ⟨y, hy⟩
            (fun H hH ↦ hcloc hH)
        · exact fun H hH ↦ union_chain hH)
      (Subgroup.zpowers x) hxloc
  exact ⟨M, hxM (Subgroup.mem_zpowers x), hMmax.1, hMmax⟩

/-- Conjugating a subgroup by an element which normalizes its normalizer
does not change that normalizer. -/
lemma normalizer_conj_smul
    {M : Subgroup G} {y : G}
    (hy : y ∈ Subgroup.normalizer
      (Subgroup.normalizer (M : Set G) : Set G)) :
    Subgroup.normalizer ((MulAut.conj y • M : Subgroup G) : Set G) =
      Subgroup.normalizer (M : Set G) := by
  change Subgroup.normalizer
      (M.map (MulAut.conj y).toMonoidHom : Set G) =
    Subgroup.normalizer (M : Set G)
  rw [← Subgroup.map_equiv_normalizer_eq M (MulAut.conj y)]
  change MulAut.conj y • Subgroup.normalizer (M : Set G) =
    Subgroup.normalizer (M : Set G)
  simpa only [Subgroup.pointwise_smul_def,
    ConjAct.toConjAct_smul_eq_mulAut_conj] using
    (Subgroup.conjAct_pointwise_smul_eq_self hy)

/-- Conjugation preserves maximal locally nilpotent subgroups. -/
lemma maximal_locally_smul
    {M : Subgroup G}
    (hMmax : Maximal (fun H : Subgroup G ↦ Group.IsLocallyNilpotent H) M)
    (y : G) :
    Maximal (fun H : Subgroup G ↦ Group.IsLocallyNilpotent H)
      (MulAut.conj y • M : Subgroup G) := by
  let f : Subgroup G ≃o Subgroup G :=
    MulEquiv.mapSubgroup (MulAut.conj y)
  have hMyloc :
      Group.IsLocallyNilpotent (MulAut.conj y • M : Subgroup G) := by
    exact
      (locally_nilpotent_congr
        (Subgroup.equivSMul (MulAut.conj y) M)).mp hMmax.1
  refine ⟨hMyloc, ?_⟩
  intro L hLloc hMyL
  let Lback : Subgroup G := f.symm L
  have hmapM :
      f M = (MulAut.conj y • M : Subgroup G) := by
    rfl
  have hLbackloc : Group.IsLocallyNilpotent Lback := by
    let e : L ≃* Lback := (MulAut.conj y).symm.subgroupMap L
    exact (locally_nilpotent_congr e).mp hLloc
  have hMback : M ≤ Lback := by
    have hmap : f M ≤ f Lback := by
      rw [show f Lback = L by
        change f (f.symm L) = L
        exact f.apply_symm_apply L, hmapM]
      exact hMyL
    exact f.le_iff_le.mp hmap
  have hbackeq : Lback = M :=
    hMmax.eq_of_ge hLbackloc hMback
  calc
    L ≤ f Lback := (f.apply_symm_apply L).symm.le
    _ ≤ f M := (congrArg f hbackeq).le
    _ ≤ (MulAut.conj y • M : Subgroup G) := hmapM.le

/-- The normalizer of a maximal locally nilpotent subgroup is
self-normalizing. -/
lemma normalizer_locally_nilpotent
    (M : Subgroup G)
    (hMmax : Maximal (fun H : Subgroup G ↦ Group.IsLocallyNilpotent H) M) :
    Subgroup.normalizer
        (Subgroup.normalizer (M : Set G) : Set G) =
      Subgroup.normalizer (M : Set G) := by
  apply le_antisymm
  · intro y hy
    let N : Subgroup G := Subgroup.normalizer (M : Set G)
    let My : Subgroup G := MulAut.conj y • M
    have hnormMy : Subgroup.normalizer (My : Set G) = N := by
      exact normalizer_conj_smul hy
    have hMN : M ≤ N := Subgroup.le_normalizer
    have hMyN : My ≤ N := by
      rw [← hnormMy]
      exact Subgroup.le_normalizer
    let MN : Subgroup N := M.subgroupOf N
    let MyN : Subgroup N := My.subgroupOf N
    letI : MN.Normal := Subgroup.normal_in_normalizer
    letI : MyN.Normal := by
      rw [Subgroup.normal_subgroupOf_iff_le_normalizer hMyN, hnormMy]
    have hMNloc : Group.IsLocallyNilpotent MN :=
      (locally_nilpotent_congr
        (Subgroup.subgroupOfEquivOfLe hMN)).mpr hMmax.1
    have hMymax :=
      maximal_locally_smul hMmax y
    have hMyNloc : Group.IsLocallyNilpotent MyN :=
      (locally_nilpotent_congr
        (Subgroup.subgroupOfEquivOfLe hMyN)).mpr hMymax.1
    have hsupNloc : Group.IsLocallyNilpotent (MN ⊔ MyN : Subgroup N) :=
      sup_locally_nilpotent MN MyN hMNloc hMyNloc
    have hsupLeN : M ⊔ My ≤ N := sup_le hMN hMyN
    have hsubSupLoc :
        Group.IsLocallyNilpotent ((M ⊔ My).subgroupOf N) := by
      rw [Subgroup.subgroupOf_sup hMN hMyN]
      exact hsupNloc
    have hsupLoc : Group.IsLocallyNilpotent (M ⊔ My : Subgroup G) :=
      (locally_nilpotent_congr
        (Subgroup.subgroupOfEquivOfLe hsupLeN)).mp hsubSupLoc
    have hsupEq : M ⊔ My = M :=
      hMmax.eq_of_ge hsupLoc le_sup_left
    have hMyM : My ≤ M := by
      rw [← hsupEq]
      exact le_sup_right
    have hMyEq : My = M :=
      (hMymax.eq_of_ge hMmax.1 hMyM).symm
    exact Subgroup.conjAct_pointwise_smul_iff.mp (by
      simpa [My, Subgroup.pointwise_smul_def] using hMyEq)
  · exact Subgroup.le_normalizer

/-- Under the normalizer condition, every maximal locally nilpotent subgroup
is normal. -/
lemma maximal_locally_normal
    (hnc : NormalizerCondition G) (M : Subgroup G)
    (hMmax : Maximal (fun H : Subgroup G ↦ Group.IsLocallyNilpotent H) M) :
    M.Normal := by
  have hnormalizerTop :
      Subgroup.normalizer (M : Set G) = (⊤ : Subgroup G) := by
    apply
      (normalizerCondition_iff_only_full_group_self_normalizing.mp hnc)
        (Subgroup.normalizer (M : Set G))
    exact normalizer_locally_nilpotent M hMmax
  exact Subgroup.normalizer_eq_top_iff.mp hnormalizerTop

/-- Under the normalizer condition, maximal locally nilpotent subgroups are
unique. -/
lemma maximal_locally
    (hnc : NormalizerCondition G) {M K : Subgroup G}
    (hMmax : Maximal (fun H : Subgroup G ↦ Group.IsLocallyNilpotent H) M)
    (hKmax : Maximal (fun H : Subgroup G ↦ Group.IsLocallyNilpotent H) K) :
    M = K := by
  letI : M.Normal := maximal_locally_normal hnc M hMmax
  letI : K.Normal := maximal_locally_normal hnc K hKmax
  have hsupLoc : Group.IsLocallyNilpotent (M ⊔ K : Subgroup G) :=
    sup_locally_nilpotent M K hMmax.1 hKmax.1
  have hsupEq : M ⊔ K = M :=
    hMmax.eq_of_ge hsupLoc le_sup_left
  have hKM : K ≤ M := by
    rw [← hsupEq]
    exact le_sup_right
  exact hKmax.eq_of_ge hMmax.1 hKM

/-- **Hall, Theorem 2.8(iii) (Plotkin).** A group satisfying the normalizer
condition is locally nilpotent. -/
theorem locally_normalizer_condition (hnc : NormalizerCondition G) :
    Group.IsLocallyNilpotent G := by
  obtain ⟨M, _, hMloc, hMmax⟩ :=
    maximal_locally_subgroup (1 : G)
  have hMtop : M = (⊤ : Subgroup G) := by
    apply top_unique
    intro x _
    obtain ⟨K, hxK, _, hKmax⟩ :=
      maximal_locally_subgroup x
    have hMK : M = K :=
      maximal_locally hnc hMmax hKmax
    simpa [hMK] using hxK
  have htopLoc : Group.IsLocallyNilpotent (⊤ : Subgroup G) := by
    rw [← hMtop]
    exact hMloc
  exact (locally_nilpotent_congr Subgroup.topEquiv).mp htopLoc

end Edmonton
end Submission
