import Submission.Group.Edmonton.NormalGeneration
import Mathlib.GroupTheory.Nilpotent
import Mathlib.Data.Fin.Tuple.Basic

/-!
# The Edmonton Notes on Nilpotent Groups: generators of lower-central terms

This file formalizes Hall's Lemma 1.7. Mathlib numbers the lower central
series from zero, so `Subgroup.lowerCentralSeries G n` is Hall's `Γ_{n+1}`.
-/

namespace Submission
namespace Edmonton

open Group
open scoped commutatorElement

universe u

/-- The left-normed `(n + 1)`-fold commutator
`[[...[a₀,a₁],a₂],...,aₙ]`. -/
def leftNormedValue {G : Type u} [Group G] :
    (n : ℕ) → (Fin (n + 1) → G) → G
  | 0, a => a 0
  | n + 1, a =>
      ⁅leftNormedValue n (fun i ↦ a i.castSucc),
        a (Fin.last (n + 1))⁆

/-- Left-normed `(n + 1)`-fold commutators whose entries all lie in `A`. -/
def leftNormedSet {G : Type u} [Group G] (A : Set G) (n : ℕ) : Set G :=
  {x | ∃ a : Fin (n + 1) → G,
    (∀ i, a i ∈ A) ∧ leftNormedValue n a = x}

@[simp]
theorem normed_set_zero {G : Type u} [Group G] (A : Set G) :
    leftNormedSet A 0 = A := by
  ext x
  constructor
  · rintro ⟨a, ha, hax⟩
    simpa [leftNormedValue] using hax ▸ ha 0
  · intro hx
    exact ⟨fun _ ↦ x, fun _ ↦ hx, by simp [leftNormedValue]⟩

theorem normed_set_succ {G : Type u} [Group G]
    {A : Set G} {n : ℕ} {x : G} :
    x ∈ leftNormedSet A (n + 1) ↔
      ∃ b ∈ leftNormedSet A n, ∃ a ∈ A, ⁅b, a⁆ = x := by
  constructor
  · rintro ⟨f, hf, rfl⟩
    refine ⟨leftNormedValue n (fun i ↦ f i.castSucc), ?_,
      f (Fin.last (n + 1)), hf _, rfl⟩
    exact ⟨fun i ↦ f i.castSucc, fun i ↦ hf i.castSucc, rfl⟩
  · rintro ⟨b, ⟨f, hf, rfl⟩, a, ha, rfl⟩
    refine ⟨Fin.snoc f a, ?_, ?_⟩
    · intro i
      exact Fin.lastCases (by simpa using ha) (fun j ↦ by simpa using hf j) i
    · simp [leftNormedValue]

theorem normed_value_series
    {G : Type u} [Group G] :
    ∀ (n : ℕ) (a : Fin (n + 1) → G),
      leftNormedValue n a ∈ Subgroup.lowerCentralSeries G n := by
  intro n
  induction n with
  | zero =>
      intro a
      exact Subgroup.mem_top _
  | succ n ih =>
      intro a
      exact Subgroup.commutator_mem_commutator
        (ih (fun i ↦ a i.castSucc)) (Subgroup.mem_top _)

theorem normed_subset_series
    {G : Type u} [Group G] (A : Set G) (n : ℕ) :
    leftNormedSet A n ⊆ Subgroup.lowerCentralSeries G n := by
  rintro x ⟨a, _, rfl⟩
  exact normed_value_series n a

theorem set_normed_succ
    {G : Type u} [Group G] (A : Set G) (n : ℕ) :
    Subgroup.normalClosure
        (basicCommutatorSet A (leftNormedSet A n)) =
      Subgroup.normalClosure (leftNormedSet A (n + 1)) := by
  apply le_antisymm
  · apply Subgroup.normalClosure_le_normal
    rintro x ⟨a, ha, b, hb, rfl⟩
    rw [← commutatorElement_inv b a]
    apply Subgroup.inv_mem
    apply Subgroup.subset_normalClosure
    exact normed_set_succ.mpr ⟨b, hb, a, ha, rfl⟩
  · apply Subgroup.normalClosure_le_normal
    intro x hx
    obtain ⟨b, hb, a, ha, hba⟩ :=
      normed_set_succ.mp hx
    rw [← hba, ← commutatorElement_inv a b]
    apply Subgroup.inv_mem
    exact Subgroup.subset_normalClosure ⟨a, ha, b, hb, rfl⟩

/-- Each lower-central term is normally generated by the left-normed
commutators in a generating set. -/
theorem lower_normed_set
    {G : Type u} [Group G] {A : Set G}
    (hA : Subgroup.closure A = ⊤) :
    ∀ n : ℕ,
      Subgroup.lowerCentralSeries G n =
        Subgroup.normalClosure (leftNormedSet A n) := by
  intro n
  induction n with
  | zero =>
      change (⊤ : Subgroup G) =
        Subgroup.normalClosure (leftNormedSet A 0)
      rw [normed_set_zero]
      apply le_antisymm
      · rw [← hA]
        exact Subgroup.closure_le_normalClosure
      · exact le_top
  | succ n ih =>
      change ⁅Subgroup.lowerCentralSeries G n, (⊤ : Subgroup G)⁆ =
        Subgroup.normalClosure (leftNormedSet A (n + 1))
      rw [ih, commutator_closure_commutators hA,
        set_normed_succ]

/-- Hall, Lemma 1.7: a lower-central term is generated by the next term
together with the corresponding left-normed commutators in a generating set. -/
theorem lower_union_normed {G : Type u} [Group G] {A : Set G}
    (hA : Subgroup.closure A = ⊤) (n : ℕ) :
    Subgroup.lowerCentralSeries G n =
      Subgroup.closure
        ((Subgroup.lowerCentralSeries G (n + 1) : Set G) ∪
          leftNormedSet A n) := by
  let K : Subgroup G :=
    Subgroup.closure
      ((Subgroup.lowerCentralSeries G (n + 1) : Set G) ∪
        leftNormedSet A n)
  have hK_le : K ≤ Subgroup.lowerCentralSeries G n := by
    change Subgroup.closure
      ((Subgroup.lowerCentralSeries G (n + 1) : Set G) ∪
        leftNormedSet A n) ≤ Subgroup.lowerCentralSeries G n
    rw [Subgroup.closure_le]
    rintro x (hx | hx)
    · exact Subgroup.lowerCentralSeries_antitone (Nat.le_succ n) hx
    · exact normed_subset_series A n hx
  have hK_normal : K.Normal := by
    constructor
    intro x hx g
    induction hx using Subgroup.closure_induction with
    | mem x hx =>
        rcases hx with hxNext | hxValue
        · exact Subgroup.subset_closure
            (Or.inl ((inferInstance : (Subgroup.lowerCentralSeries G (n + 1)).Normal).conj_mem x
              hxNext g))
        · have hxSeries : x ∈ Subgroup.lowerCentralSeries G n :=
            normed_subset_series A n hxValue
          have hcomm : ⁅g, x⁆ ∈ Subgroup.lowerCentralSeries G (n + 1) := by
            change ⁅g, x⁆ ∈ ⁅Subgroup.lowerCentralSeries G n, (⊤ : Subgroup G)⁆
            rw [Subgroup.commutator_comm]
            exact Subgroup.commutator_mem_commutator (Subgroup.mem_top g) hxSeries
          rw [show g * x * g⁻¹ = ⁅g, x⁆ * x by
            simp [commutatorElement_def, mul_assoc]]
          exact K.mul_mem
            (Subgroup.subset_closure (Or.inl hcomm))
            (Subgroup.subset_closure (Or.inr hxValue))
    | one => simp
    | mul x y _ _ hx hy =>
        rw [← conj_mul]
        exact K.mul_mem hx hy
    | inv x _ hx =>
        rw [← conj_inv]
        exact K.inv_mem hx
  change Subgroup.lowerCentralSeries G n = K
  apply le_antisymm
  · rw [lower_normed_set hA n]
    letI : K.Normal := hK_normal
    apply Subgroup.normalClosure_le_normal
    intro x hx
    exact Subgroup.subset_closure (Or.inr hx)
  · exact hK_le

end Edmonton
end Submission
