import Towers.ClassField.LocalGlobalPowers.RadicalExtension
import Towers.ClassField.HilbertSymbols.KummerPowerInflation
import Towers.ClassField.LocalFields.NormSubgroups
import Towers.NumberTheory.Completions.DifferentCompletionConcrete
import Mathlib.RingTheory.DedekindDomain.Ideal.Lemmas
import Mathlib.RingTheory.Ideal.GoingUp

/-!
# Completion splitting used in Theorem VIII.1.4

This file isolates the local factor argument in Step 2, so its substantial
completion-field elaboration can be compiled and cached independently.
-/

namespace Towers.CField.LGPowers

open IsDedekindDomain NumberField Polynomial
open Towers.NumberTheory.Milne
open Towers.CField.HSymbol
open Towers.CField.Ideles
open Towers.CField.KTheory
open Towers.CField.ICohomo
open Towers.CField.NIndex

noncomputable section

universe u

private abbrev OK (K : Type u) [Field K] [NumberField K] :=
  NumberField.RingOfIntegers K

attribute [local instance] IsCyclic.commGroup

set_option synthInstance.maxHeartbeats 500000 in
-- Comparing decomposition stabilizers across completions requires deeper instance search.
set_option maxHeartbeats 3000000 in
/-- In a finite Galois extension, one degree-one completed factor already
implies complete splitting. -/
theorem splits_completely_finrank
    (K L : Type u) [Field K] [NumberField K]
    [Field L] [NumberField L] [Algebra K L]
    [FiniteDimensional K L] [IsGalois K L]
    (p : HeightOneSpectrum (OK K))
    (w : CompletionPlacesAbove (L := L) (FinitePlace.mk p).val)
    (hlocal :
      letI : Algebra (FinitePlace.mk p).val.Completion w.1.Completion :=
        (completionLies (FinitePlace.mk p).val w.1 w.2).toAlgebra
      Module.finrank (FinitePlace.mk p).val.Completion w.1.Completion = 1) :
    SplitsCompletelyAt K L p := by
  let v := (FinitePlace.mk p).val
  letI : Fact v.IsNontrivial :=
    ⟨absolute_value_nontrivial p⟩
  letI : IsUltrametricDist v.Completion :=
    placeUltrametricDist p
  have hw : w.1.IsNontrivial := absolute_extension_nontrivial v w
  have hwna : IsNonarchimedean w.1 :=
    absolute_extension_nonarchimedean v w
  let Q := nonarchimedeanHeightSpectrum w.1 hw hwna
  letI : Q.asIdeal.LiesOver p.asIdeal :=
    nonarchimedean_spectrum_lies p w.1 w.2 hw hwna
  letI : Algebra v.Completion w.1.Completion :=
    (completionLies v w.1 w.2).toAlgebra
  letI : MulSemiringAction Gal(L/K) (OK L) :=
    IsIntegralClosure.MulSemiringAction (OK K) K L (OK L)
  letI : MulSemiringAction Gal(L/K) (Ideal (OK L)) :=
    Ideal.pointwiseMulSemiringAction
  letI : IsGaloisGroup Gal(L/K) (OK K) (OK L) :=
    IsGaloisGroup.of_isFractionRing Gal(L/K) (OK K) (OK L) K L
  letI : p.asIdeal.IsMaximal := p.isMaximal
  letI : Q.asIdeal.IsMaximal := Q.isMaximal
  letI : Field (OK K ⧸ p.asIdeal) := Ideal.Quotient.field p.asIdeal
  letI : Field (OK L ⧸ Q.asIdeal) := Ideal.Quotient.field Q.asIdeal
  letI : Finite (OK K ⧸ p.asIdeal) :=
    Ring.HasFiniteQuotients.finiteQuotient p.ne_bot
  letI : Finite (OK L ⧸ Q.asIdeal) :=
    Ring.HasFiniteQuotients.finiteQuotient Q.ne_bot
  letI : Algebra.IsSeparable (OK K ⧸ p.asIdeal) (OK L ⧸ Q.asIdeal) :=
    Algebra.IsAlgebraic.isSeparable_of_perfectField
  have hstabilizer :
      Nat.card (MulAction.stabilizer Gal(L/K) Q.asIdeal) = 1 := by
    calc
      Nat.card (MulAction.stabilizer Gal(L/K) Q.asIdeal) =
          Nat.card (absoluteValueDecomposition v w.1) := by
        rw [centered_stabilizer_decomposition v w.1 hw hwna]
      _ = Module.finrank v.Completion w.1.Completion := by
        rw [finrank_decomposition_card p w]
      _ = 1 := hlocal
  have hQmem : Q.asIdeal ∈ Ideal.primesOver p.asIdeal (OK L) :=
    ⟨Q.isPrime, inferInstance⟩
  apply (splits_completely_bot p Q.asIdeal hQmem).mpr
  exact (MulAction.stabilizer Gal(L/K) Q.asIdeal).eq_bot_of_card_eq hstabilizer

set_option synthInstance.maxHeartbeats 500000 in
-- Elaborating the generated subfield and its completed factor requires deeper instance search.
set_option maxHeartbeats 3000000 in
/-- If an irreducible factor has a local root, the field generated by any
of its roots inside a cyclic Galois extension splits completely there. -/
theorem splits_completely_minpoly
    (K C : Type u) [Field K] [NumberField K]
    [Field C] [NumberField C] [Algebra K C]
    [FiniteDimensional K C] [IsGalois K C] [IsCyclic Gal(C/K)]
    (alpha : C) (P : HeightOneSpectrum (OK K))
    (x : P.adicCompletion K)
    (hx : ((minpoly K alpha).map
      (algebraMap K (P.adicCompletion K))).IsRoot x) :
    SplitsCompletelyAt K (IntermediateField.adjoin K {alpha}) P := by
  let E : IntermediateField K C := IntermediateField.adjoin K {alpha}
  let alphaE : E :=
    ⟨alpha, IntermediateField.subset_adjoin K {alpha}
      (Set.mem_singleton alpha)⟩
  have hgen : IntermediateField.adjoin K {alphaE} = ⊤ := by
    apply IntermediateField.map_injective E.val
    rw [IntermediateField.adjoin_map, ← AlgHom.fieldRange_eq_map,
      IntermediateField.fieldRange_val]
    change IntermediateField.adjoin K (Subtype.val '' {alphaE}) = E
    simp [E, alphaE]
  have hgenAlg : Algebra.adjoin K {alphaE} = ⊤ := by
    rw [← IntermediateField.adjoin_simple_toSubalgebra_of_isAlgebraic
      (IsAlgebraic.of_finite K alphaE)]
    exact congrArg IntermediateField.toSubalgebra hgen
  letI : FiniteDimensional K E := inferInstance
  letI : FiniteDimensional ℚ E := FiniteDimensional.trans ℚ K E
  letI : NumberField E := {}
  have hnormal : E.fixingSubgroup.Normal := inferInstance
  letI : IsGalois K E :=
    (InfiniteGalois.normal_iff_isGalois E).mp hnormal
  let v := (FinitePlace.mk P).val
  let F := v.Completion
  letI : Fact v.IsNontrivial :=
    ⟨absolute_value_nontrivial P⟩
  letI : IsUltrametricDist F :=
    placeUltrametricDist P
  let eP : F ≃+* P.adicCompletion K :=
    placeCompletionAdic P
  let xF : F := eP.symm x
  have hcomp : eP.toRingHom.comp (completionEmbedding v) =
      algebraMap K (P.adicCompletion K) := by
    ext z
    exact finite_place_adic P z
  have hxF : ((minpoly K alphaE).map (completionEmbedding v)).IsRoot xF := by
    have hmin : minpoly K alphaE = minpoly K alpha :=
      (minpoly.algHom_eq E.val E.val.injective alphaE).symm
    rw [hmin]
    rw [Polynomial.IsRoot, eval_map]
    apply eP.injective
    change eP.toRingHom
      (eval₂ (completionEmbedding v) xF (minpoly K alpha)) =
        eP.toRingHom 0
    rw [map_zero, hom_eval₂, hcomp]
    have hxFmap : eP.toRingHom xF = x := by
      exact eP.apply_symm_apply x
    rw [hxFmap]
    simpa [Polynomial.IsRoot, eval_map] using hx
  let g : F[X] := X - Polynomial.C xF
  have hgdiv : g ∣ (minpoly K alphaE).map (completionEmbedding v) :=
    dvd_iff_isRoot.mpr hxF
  let G : CompletedMinpolyFactor v alphaE :=
    ⟨g, irreducible_X_sub_C xF, monic_X_sub_C xF, hgdiv⟩
  let w : CompletionPlacesAbove (L := E) v :=
    completedMinpolyExtension v alphaE hgenAlg G
  letI : Algebra F w.1.Completion :=
    (completionLies v w.1 w.2).toAlgebra
  have hround := congrArg Subtype.val
    (minpoly_place_roundtrip v alphaE hgenAlg G)
  have hminround : minpoly F (completionEmbedding w.1 alphaE) = g := by
    exact hround
  let ew := completionAdjoinMinpoly v alphaE hgenAlg w
  have hminne : minpoly F (completionEmbedding w.1 alphaE) ≠ 0 := by
    rw [hminround]
    exact (monic_X_sub_C xF).ne_zero
  let pbw := AdjoinRoot.powerBasis hminne
  letI : FiniteDimensional F
      (AdjoinRoot (minpoly F (completionEmbedding w.1 alphaE))) :=
    pbw.basis.finiteDimensional_of_finite
  letI : FiniteDimensional F w.1.Completion :=
    ew.toLinearEquiv.finiteDimensional
  have hdegree : Module.finrank F w.1.Completion = 1 := by
    calc
      Module.finrank F w.1.Completion =
          Module.finrank F
            (AdjoinRoot (minpoly F (completionEmbedding w.1 alphaE))) :=
        ew.toLinearEquiv.finrank_eq.symm
      _ = (minpoly F (completionEmbedding w.1 alphaE)).natDegree := by
        rw [pbw.finrank, AdjoinRoot.powerBasis_dim]
      _ = g.natDegree := by rw [hminround]
      _ = 1 := natDegree_X_sub_C xF
  exact splits_completely_finrank
    K E P w hdegree

end

end Towers.CField.LGPowers
