import Mathlib


/-!
# Milne, fractional ideals before Example 3.19

This file records the elementary assertions in the introduction to the ideal class group:
fractional ideals over a noetherian domain are finitely generated, finitely generated
submodules of the fraction field have a common denominator, and principal fractional ideals
multiply as expected.
-/

namespace Towers.NumberTheory.Milne

open scoped nonZeroDivisors

variable (A K : Type*) [CommRing A] [IsDomain A] [Field K]
  [Algebra A K] [IsFractionRing A K]

/-- Every fractional ideal over a noetherian domain is finitely generated as a module. -/
theorem fractional_fg_noetherian
    [IsNoetherianRing A] (I : FractionalIdeal A⁰ K) :
    (I : Submodule A K).FG := by
  exact FractionalIdeal.fg_of_isNoetherianRing le_rfl I

/-- Conversely, a finitely generated submodule of the fraction field has a common
denominator and hence defines a fractional ideal. -/
noncomputable def fractionalIdealFG
    (M : Submodule A K) (hM : M.FG) : FractionalIdeal A⁰ K :=
  ⟨M, FractionalIdeal.isFractional_of_fg hM⟩

omit [IsDomain A] in
@[simp]
theorem fractional_fg_coe
    (M : Submodule A K) (hM : M.FG) :
    (fractionalIdealFG A K M hM : Submodule A K) = M := rfl

omit [IsDomain A] in
/-- A nonzero finitely generated submodule gives a nonzero fractional ideal. -/
theorem fractional_fg_ne
    (M : Submodule A K) (hM : M.FG) (hM0 : M ≠ ⊥) :
    fractionalIdealFG A K M hM ≠ 0 := by
  intro hzero
  apply hM0
  simpa using congrArg
    (fun I : FractionalIdeal A⁰ K ↦ (I : Submodule A K)) hzero

/-- Every fractional ideal admits a nonzero denominator that turns it into an integral
ideal.  This is Milne's condition `d * I ⊆ A`, expressed as equality with the numerator
ideal inside the fraction field. -/
theorem fractional_nonzero_denominator
    (I : FractionalIdeal A⁰ K) :
    ∃ (d : A), d ≠ 0 ∧ ∃ J : Ideal A,
      FractionalIdeal.spanSingleton A⁰ (algebraMap A K d) * I =
        (J : FractionalIdeal A⁰ K) := by
  exact ⟨I.den, nonZeroDivisors.coe_ne_zero I.den, I.num, I.den_mul_self_eq_num'⟩

omit [IsDomain A] in
/-- The principal fractional ideal generated by `b` is nonzero exactly when `b` is. -/
theorem principal_fractional_ne (b : K) :
    FractionalIdeal.spanSingleton A⁰ b ≠ 0 ↔ b ≠ 0 := by
  exact FractionalIdeal.spanSingleton_ne_zero_iff

omit [IsDomain A] in
/-- Membership in the principal fractional ideal `(b) = bA`. -/
theorem principal_fractional_ideal (x b : K) :
    x ∈ FractionalIdeal.spanSingleton A⁰ b ↔
      ∃ a : A, algebraMap A K a * b = x := by
  simp [Algebra.smul_def]

omit [IsDomain A] in
/-- Principal fractional ideals multiply according to `(a)(b) = (ab)`. -/
theorem principal_fractional_mul (a b : K) :
    FractionalIdeal.spanSingleton A⁰ a * FractionalIdeal.spanSingleton A⁰ b =
      FractionalIdeal.spanSingleton A⁰ (a * b) := by
  exact FractionalIdeal.spanSingleton_mul_spanSingleton a b

end Towers.NumberTheory.Milne
