import Submission.Topology.ClosedSeparation
import Submission.Topology.CompactTotallyDisconnected
import Submission.Topology.LightweightTopology
import Submission.Topology.OpenNormal
import Submission.Topology.ProfiniteQuotients
