import Mathlib
import Submission.Algebra.DenseGenerators.FiniteGroupAlgebra
import Submission.Group.PowerWidth.Topology


open scoped Topology Pointwise

noncomputable section

namespace Submission

universe u
universe v w z

/-- A power subgroup whose exponent appears among the Zassenhaus generators lies in `D_n`. -/
lemma power_filtration_pow
    {p : ℕ}
    {G : Type*} [Group G]
    {n j : ℕ}
    (h : n ≤ p ^ j) :
    powerSubgroup G (p ^ j) ≤ zassenhausFiltration p G n := by
  letI : (zassenhausFiltration p G n).Normal :=
    zassenhausFiltration_normal p G n
  apply Subgroup.normalClosure_le_normal
  intro y hy
  rcases hy with ⟨x, rfl⟩
  exact Subgroup.subset_closure
    ⟨0, j, x, by simp, by simpa using h, rfl⟩
/-- For a prime base, `n ≤ p ^ n`; useful for the power-subgroup bridge to `D_n`. -/
lemma nat_pow_self {p n : ℕ} (hp : 2 ≤ p) :
    n ≤ p ^ n := by
  exact (n.lt_two_pow_self).le.trans (Nat.pow_le_pow_left hp n)
/-- Abstract generation descends to quotients. -/
lemma GeneratedBy.quotient
    {G : Type u} [Group G]
    {d : ℕ} {t : Fin d → G}
    (ht : GeneratedBy t)
    (H : Subgroup G) [H.Normal] :
    GeneratedBy (fun i : Fin d => QuotientGroup.mk' H (t i)) := by
  let q : G →* G ⧸ H := QuotientGroup.mk' H
  let K : Subgroup (G ⧸ H) :=
    Subgroup.closure (Set.range (fun i : Fin d => q (t i)))
  have hle : Subgroup.closure (Set.range t) ≤ K.comap q := by
    apply (Subgroup.closure_le _).mpr
    rintro x ⟨i, rfl⟩
    exact Subgroup.subset_closure ⟨i, rfl⟩
  have htop_pre : (⊤ : Subgroup G) ≤ K.comap q := by
    rw [← ht]
    exact hle
  have htop : (⊤ : Subgroup (G ⧸ H)) ≤ K := by
    intro y _hy
    rcases QuotientGroup.mk'_surjective H y with ⟨x, rfl⟩
    exact htop_pre trivial
  exact top_unique htop
/-- A group generated by a finite tuple is finitely generated. -/
lemma GeneratedBy.groupFG
    {G : Type u} [Group G]
    {d : ℕ} {t : Fin d → G}
    (ht : GeneratedBy t) :
    Group.FG G := by
  rw [Group.fg_iff]
  exact ⟨Set.range t, ht, Set.finite_range t⟩
/-- The abstract rank of a group generated by a `d`-tuple is at most `d`. -/
lemma GeneratedBy.rank_le
    {G : Type u} [Group G] [Group.FG G]
    {d : ℕ} {t : Fin d → G}
    (ht : GeneratedBy t) :
    Group.rank G ≤ d := by
  classical
  let S : Finset G := Finset.univ.image t
  have hS : Subgroup.closure ((S : Finset G) : Set G) = ⊤ := by
    rw [← ht]
    congr 1
    ext x
    simp [S]
  have hcard : S.card ≤ d := by
    dsimp [S]
    simpa using
      (Finset.card_image_le (s := (Finset.univ : Finset (Fin d))) (f := t))
  exact (Group.rank_le hS).trans hcard
/-- Pad a finite tuple of generators by identities. -/
def padGenerators
    {G : Type u} [One G] {d d' : ℕ}
    (_hd : d ≤ d') (t : Fin d → G) :
    Fin d' → G :=
  fun j => if hj : (j : ℕ) < d then t ⟨j, hj⟩ else 1
/-- Padding a generating tuple by identities preserves generation. -/
lemma GeneratedBy.pad
    {G : Type u} [Group G] {d d' : ℕ}
    (hd : d ≤ d') {t : Fin d → G}
    (ht : GeneratedBy t) :
    GeneratedBy (padGenerators hd t) := by
  have hle :
      Subgroup.closure (Set.range t) ≤
        Subgroup.closure (Set.range (padGenerators hd t)) := by
    refine (Subgroup.closure_le _).mpr ?_
    rintro x ⟨i, rfl⟩
    exact
      Subgroup.subset_closure
        ⟨⟨(i : ℕ), lt_of_lt_of_le i.isLt hd⟩, by
          simp [padGenerators, i.isLt]⟩
  exact top_unique (by
    rw [← ht]
    exact hle)
/-- A surjective homomorphic image of a generated group is generated by the image tuple. -/
lemma GeneratedBy.map_surjective
    {G H : Type u} [Group G] [Group H]
    (φ : G →* H) (hφ : Function.Surjective φ)
    {d : ℕ} {t : Fin d → G}
    (ht : GeneratedBy t) :
    GeneratedBy (fun i : Fin d => φ (t i)) := by
  have hmap :
      (Subgroup.closure (Set.range t)).map φ =
        Subgroup.closure (Set.range (fun i : Fin d => φ (t i))) := by
    rw [MonoidHom.map_closure]
    congr 1
    ext y
    constructor
    · rintro ⟨x, ⟨i, rfl⟩, rfl⟩
      exact ⟨i, rfl⟩
    · rintro ⟨i, rfl⟩
      exact ⟨t i, ⟨i, rfl⟩, rfl⟩
  have htop :
      (Subgroup.closure (Set.range t)).map φ = (⊤ : Subgroup H) := by
    rw [ht]
    exact Subgroup.map_top_of_surjective φ hφ
  change Subgroup.closure (Set.range (fun i : Fin d => φ (t i))) = (⊤ : Subgroup H)
  rw [← hmap]
  exact htop
/-- The standard appended tuple of product generators. -/
def prodGenerators
    {G H : Type u} [One G] [One H]
    {d e : ℕ} (s : Fin d → G) (t : Fin e → H) :
    Fin (d + e) → G × H :=
  Fin.append (fun i : Fin d => (s i, 1)) (fun j : Fin e => (1, t j))
/-- Product groups are generated by appending lifted generators from each factor. -/
lemma GeneratedBy.prod
    {G H : Type u} [Group G] [Group H]
    {d e : ℕ} {s : Fin d → G} {t : Fin e → H}
    (hs : GeneratedBy s) (ht : GeneratedBy t) :
    GeneratedBy (prodGenerators s t) := by
  let K : Subgroup (G × H) :=
    Subgroup.closure (Set.range (prodGenerators s t))
  have hleft :
      (Subgroup.closure (Set.range s)).map (MonoidHom.inl G H) ≤ K := by
    rw [MonoidHom.map_closure]
    refine (Subgroup.closure_le _).mpr ?_
    rintro y ⟨x, ⟨i, rfl⟩, rfl⟩
    exact
      Subgroup.subset_closure
        ⟨Fin.castAdd e i, by simp [prodGenerators]⟩
  have hright :
      (Subgroup.closure (Set.range t)).map (MonoidHom.inr G H) ≤ K := by
    rw [MonoidHom.map_closure]
    refine (Subgroup.closure_le _).mpr ?_
    rintro y ⟨x, ⟨i, rfl⟩, rfl⟩
    exact
      Subgroup.subset_closure
        ⟨Fin.natAdd d i, by simp [prodGenerators]⟩
  refine top_unique ?_
  intro y _hy
  have hy_left : (y.1, 1) ∈ K := by
    apply hleft
    refine ⟨y.1, ?_, rfl⟩
    rw [hs]
    trivial
  have hy_right : (1, y.2) ∈ K := by
    apply hright
    refine ⟨y.2, ?_, rfl⟩
    rw [ht]
    trivial
  have hmul : (y.1, 1) * (1, y.2) ∈ K :=
    K.mul_mem hy_left hy_right
  simpa using hmul
/-- The quotient by the `m`th power subgroup has exponent dividing `m`. -/
lemma subgroup_pow_one
    {G : Type u} [Group G] (m : ℕ)
    (x : G ⧸ powerSubgroup G m) :
    x ^ m = 1 := by
  rcases QuotientGroup.mk'_surjective (powerSubgroup G m) x with ⟨g, rfl⟩
  have hmem : g ^ m ∈ powerSubgroup G m :=
    pow_power_subgroup m g
  simpa using
    ((QuotientGroup.eq_one_iff (N := powerSubgroup G m) (g ^ m)).mpr hmem)
/-- Width plus restricted Burnside cardinal bounds combine into the finite quotient package. -/
lemma bound_restricted_burnside
    {d m k B : ℕ}
    (hwidth : PWBound.{u} d m k)
    (hrbt : RBBound.{u} d m B) :
    WIBound.{u} d m k B := by
  intro G _instGroupG _instFiniteG t ht
  constructor
  · exact hwidth G t ht
  · have hgen :
        ∃ u : Fin d → G ⧸ powerSubgroup G m, GeneratedBy u := by
      refine ⟨fun i : Fin d => QuotientGroup.mk' (powerSubgroup G m) (t i), ?_⟩
      exact GeneratedBy.quotient (G := G) (t := t) ht (powerSubgroup G m)
    have hexp : ∀ x : G ⧸ powerSubgroup G m, x ^ m = 1 := by
      intro x
      exact subgroup_pow_one (G := G) m x
    exact hrbt (G ⧸ powerSubgroup G m) hgen hexp
/-- Split finite width and RBT inputs can be bundled into the combined finite package. -/
lemma width_restricted_burnside
    {d m : ℕ}
    (hwidth : ∃ k : ℕ, PWBound.{u} d m k)
    (hrbt : ∃ B : ℕ, RBBound.{u} d m B) :
    ∃ k B : ℕ, WIBound.{u} d m k B := by
  rcases hwidth with ⟨k, hk⟩
  rcases hrbt with ⟨B, hB⟩
  exact ⟨k, B, bound_restricted_burnside hk hB⟩
/-- Separate finite-width and restricted-Burnside bounds give the prime-power finite package. -/
lemma nsrbt_width_burnside
    {d p e : ℕ} [Fact p.Prime]
    (hwidth : ∃ k : ℕ, PWBound.{u} d (p ^ e) k)
    (hrbt : ∃ B : ℕ, RBBound.{u} d (p ^ e) B) :
    NPPower.{u} d p e := by
  exact width_restricted_burnside hwidth hrbt
/-- Named split finite width and Burnside inputs imply the finite prime-power package. -/
theorem nsrbt_prime_burnside
    {d p e : ℕ} [Fact p.Prime]
    (hwidth : NWPrime.{u} d p e)
    (hrbt : RBPower.{u} d p e) :
    NPPower.{u} d p e := by
  exact
    nsrbt_width_burnside
      (d := d) (p := p) (e := e) hwidth hrbt
/-- Uniform minimal-width bounds plus the restricted Burnside input give the finite prime-power
package. -/
theorem nsrbt_minimal_burnside
    {d p e k : ℕ} [Fact p.Prime]
    (hwidth : UMWidth.{u} d p e k)
    (hrbt : RBPower.{u} d p e) :
    NPPower.{u} d p e := by
  exact
    nsrbt_prime_burnside
      (d := d) (p := p) (e := e)
      (ns_uniform_minimal
        (d := d) (p := p) (e := e) (k := k) hwidth)
      hrbt
/-- A subsingleton inhabited type has natural cardinal at most one. -/
lemma nat_card_subsingleton
    (α : Type u) [Finite α] [Subsingleton α] :
    Nat.card α ≤ 1 := by
  exact (Finite.card_le_one_iff_subsingleton (α := α)).mpr inferInstance
/-- A group generated by no elements is a subsingleton. -/
lemma GeneratedBy.subsingleton_fin_zero
    {G : Type u} [Group G] {t : Fin 0 → G}
    (ht : GeneratedBy t) :
    Subsingleton G := by
  classical
  have hclosure_bot :
      Subgroup.closure (Set.range t) = (⊥ : Subgroup G) := by
    apply le_antisymm
    · refine (Subgroup.closure_le _).mpr ?_
      intro x hx
      rcases hx with ⟨i, rfl⟩
      exact Fin.elim0 i
    · exact bot_le
  refine ⟨?_⟩
  intro a b
  have ha_mem : a ∈ Subgroup.closure (Set.range t) := by
    rw [ht]
    trivial
  have hb_mem : b ∈ Subgroup.closure (Set.range t) := by
    rw [ht]
    trivial
  have ha_one : a = 1 := by
    have : a ∈ (⊥ : Subgroup G) := by
      simpa [hclosure_bot] using ha_mem
    simpa using this
  have hb_one : b = 1 := by
    have : b ∈ (⊥ : Subgroup G) := by
      simpa [hclosure_bot] using hb_mem
    simpa using this
  exact ha_one.trans hb_one.symm
/-- A subsingleton group has zero power width. -/
lemma power_width_subsingleton
    (G : Type u) [Group G] [Subsingleton G] (m : ℕ) :
    HPWidth G m 0 := by
  intro g _hg
  refine ⟨fun i : Fin 0 => Fin.elim0 i, ?_⟩
  have h : (1 : G) = g := Subsingleton.elim _ _
  simpa [powerWordMap] using h
/-- Zero-generated finite groups have zero power width. -/
lemma width_bound_generators
    (m : ℕ) :
    PWBound.{u} 0 m 0 := by
  intro G _instGroup _instFinite t ht
  haveI : Subsingleton G :=
    GeneratedBy.subsingleton_fin_zero (G := G) (t := t) ht
  exact power_width_subsingleton (G := G) m
/-- Zero-generated finite exponent-`m` groups have cardinal at most one. -/
lemma restricted_burnside_generators
    (m : ℕ) :
    RBBound.{u} 0 m 1 := by
  intro G _instGroup _instFinite hgen _hexp
  rcases hgen with ⟨t, ht⟩
  haveI : Subsingleton G :=
    GeneratedBy.subsingleton_fin_zero (G := G) (t := t) ht
  exact nat_card_subsingleton G
/-- The finite prime-power package is proved for zero generators. -/
theorem nsrbt_prime_generators
    (p e : ℕ) [Fact p.Prime] :
    NPPower.{u} 0 p e := by
  exact
    width_restricted_burnside
      (d := 0) (m := p ^ e)
      ⟨0, width_bound_generators (m := p ^ e)⟩
      ⟨1, restricted_burnside_generators (m := p ^ e)⟩
/-- Every group has width one for first powers. -/
lemma power_width_one
    (G : Type u) [Group G] :
    HPWidth G 1 1 := by
  intro g _hg
  refine ⟨fun _ : Fin 1 => g, ?_⟩
  simp [powerWordMap]
/-- Finite groups have a uniform width-one bound for first powers. -/
lemma width_bound_one
    (d : ℕ) :
    PWBound.{u} d 1 1 := by
  intro G _instGroup _instFinite _t _ht
  exact power_width_one G
/-- A group whose first powers are all trivial is a subsingleton. -/
lemma subsingleton_forall_pow
    {G : Type u} [Group G]
    (h : ∀ x : G, x ^ 1 = 1) :
    Subsingleton G := by
  refine ⟨fun x y => ?_⟩
  have hx : x = 1 := by
    simpa using h x
  have hy : y = 1 := by
    simpa using h y
  exact hx.trans hy.symm
/-- Finite exponent-one groups have cardinal at most one. -/
lemma burnside_bound_one
    (d : ℕ) :
    RBBound.{u} d 1 1 := by
  intro G _instGroup _instFinite _hgen hexp
  haveI : Subsingleton G :=
    subsingleton_forall_pow (G := G) hexp
  exact nat_card_subsingleton G
/-- The finite prime-power package is proved at exponent `p^0 = 1`. -/
theorem nsrbt_exponent_zero
    (d p : ℕ) [Fact p.Prime] :
    NPPower.{u} d p 0 := by
  change ∃ k B : ℕ, WIBound.{u} d 1 k B
  exact
    width_restricted_burnside
      (d := d) (m := 1)
      ⟨1, width_bound_one (d := d)⟩
      ⟨1, burnside_bound_one (d := d)⟩
/-- A group generated by one element is cyclic. -/
lemma GeneratedBy.cyclic_fin_one
    {G : Type u} [Group G] {t : Fin 1 → G}
    (ht : GeneratedBy t) :
    IsCyclic G := by
  rw [isCyclic_iff_exists_zpowers_eq_top]
  refine ⟨t 0, ?_⟩
  rw [Subgroup.zpowers_eq_closure]
  have hrange : Set.range t = ({t 0} : Set G) := by
    ext x
    constructor
    · rintro ⟨i, rfl⟩
      fin_cases i
      simp
    · intro hx
      rcases hx with rfl
      exact ⟨0, rfl⟩
  simpa [GeneratedBy, hrange] using ht
/-- In a commutative group, the normal subgroup generated by `m`th powers is the range of the
`m`th-power homomorphism. -/
lemma monoid_range_comm
    (G : Type u) [CommGroup G] (m : ℕ) :
    powerSubgroup G m = (powMonoidHom (α := G) m).range := by
  apply le_antisymm
  · dsimp [powerSubgroup]
    exact
      Subgroup.normalClosure_le_normal (by
        rintro y ⟨x, rfl⟩
        exact ⟨x, rfl⟩)
  · rintro y ⟨x, rfl⟩
    exact pow_power_subgroup m x
/-- Commutative groups have width one for the subgroup of `m`th powers. -/
lemma power_width_comm
    (G : Type u) [CommGroup G] (m : ℕ) :
    HPWidth G m 1 := by
  intro g hg
  have hmem : g ∈ (powMonoidHom (α := G) m).range := by
    simpa [monoid_range_comm (G := G) m] using hg
  rcases hmem with ⟨x, rfl⟩
  refine ⟨fun _ : Fin 1 => x, ?_⟩
  simp [powerWordMap]
/-- One-generated finite groups have width one for every power subgroup. -/
lemma width_bound_generator
    (m : ℕ) :
    PWBound.{u} 1 m 1 := by
  intro G _instGroup _instFinite t ht
  have hcyc : IsCyclic G :=
    GeneratedBy.cyclic_fin_one (G := G) (t := t) ht
  letI : CommGroup G := IsCyclic.commGroup
  exact power_width_comm G m
/-- One-generated finite exponent-`m` groups have cardinal at most `m`, for positive `m`. -/
lemma restricted_burnside_pos
    {m : ℕ} (hm : 0 < m) :
    RBBound.{u} 1 m m := by
  intro G _instGroup _instFinite hgen hexp
  rcases hgen with ⟨t, ht⟩
  have hcyc : IsCyclic G :=
    GeneratedBy.cyclic_fin_one (G := G) (t := t) ht
  letI : CommGroup G := IsCyclic.commGroup
  haveI : Group.FG G :=
    GeneratedBy.groupFG (G := G) (t := t) ht
  have hrank : Group.rank G ≤ 1 :=
    GeneratedBy.rank_le (G := G) (t := t) ht
  have hdvd : Nat.card G ∣ m ^ Group.rank G :=
    card_dvd_exponent_pow_rank' (G := G) hexp
  have hcard_le_rank_pow : Nat.card G ≤ m ^ Group.rank G :=
    Nat.le_of_dvd (pow_pos hm _) hdvd
  have hpow_le : m ^ Group.rank G ≤ m ^ 1 :=
    Nat.pow_le_pow_right hm hrank
  simpa using hcard_le_rank_pow.trans hpow_le
/-- The restricted Burnside input is proved for one generator and prime-power exponent. -/
lemma restricted_burnside_generator
    (p e : ℕ) [Fact p.Prime] :
    RBPower.{u} 1 p e := by
  exact
    ⟨p ^ e,
      restricted_burnside_pos
        (m := p ^ e) (pow_pos (Fact.out : Nat.Prime p).pos e)⟩
/-- The finite Nikolov-Segal width input is proved for one generator. -/
theorem ns_width_generator
    (p e : ℕ) [Fact p.Prime] :
    NWPrime.{u} 1 p e := by
  exact ⟨1, width_bound_generator (m := p ^ e)⟩
/-- The finite prime-power package is proved for one generator. -/
theorem nsrbt_prime_generator
    (p e : ℕ) [Fact p.Prime] :
    NPPower.{u} 1 p e := by
  exact
    nsrbt_prime_burnside
      (d := 1) (p := p) (e := e)
      (ns_width_generator (p := p) (e := e))
      (restricted_burnside_generator (p := p) (e := e))
/-- The finite prime-power package is proved for at most one generator. -/
theorem nsrbt_generators_one
    {d p e : ℕ} [Fact p.Prime]
    (hd : d ≤ 1) :
    NPPower.{u} d p e := by
  rcases Nat.le_one_iff_eq_zero_or_eq_one.mp hd with rfl | rfl
  · exact nsrbt_prime_generators p e
  · exact nsrbt_prime_generator p e
/-- Finite `d`-generated exponent-two groups have cardinal at most `2 ^ d`. -/
lemma restricted_burnside_two
    (d : ℕ) :
    RBBound.{u} d 2 (2 ^ d) := by
  intro G _instGroup _instFinite hgen hexp
  rcases hgen with ⟨t, ht⟩
  have horders : ∀ g : G, orderOf g ∣ 2 := by
    intro g
    exact orderOf_dvd_iff_pow_eq_one.mpr (hexp g)
  have hcomm : Std.Commutative (α := G) (· * ·) := by
    exact ⟨fun a b => (Commute.of_orderOf_dvd_two horders a b).eq⟩
  haveI : IsMulCommutative G := ⟨hcomm⟩
  letI : CommGroup G := { _instGroup with mul_comm := hcomm.comm }
  haveI : Group.FG G :=
    GeneratedBy.groupFG (G := G) (t := t) ht
  have hrank : Group.rank G ≤ d :=
    GeneratedBy.rank_le (G := G) (t := t) ht
  have hdvd : Nat.card G ∣ 2 ^ Group.rank G :=
    card_dvd_exponent_pow_rank' (G := G) hexp
  have hcard_le_rank_pow : Nat.card G ≤ 2 ^ Group.rank G :=
    Nat.le_of_dvd (pow_pos (by norm_num) _) hdvd
  exact hcard_le_rank_pow.trans (Nat.pow_le_pow_right (by norm_num) hrank)
/-- The restricted Burnside prime-power input is proved for exponent `2 = 2 ^ 1`. -/
lemma restricted_burnside_one
    (d : ℕ) [Fact (Nat.Prime 2)] :
    RBPower.{u} d 2 1 := by
  exact ⟨2 ^ d, by simpa using restricted_burnside_two (d := d)⟩
/-- An exponent bound for a larger exponent also applies to any divisor exponent. -/
lemma RBBound.of_dvd_exponent
    {d mSmall mBig B : ℕ}
    (hdiv : mSmall ∣ mBig)
    (h : RBBound.{u} d mBig B) :
    RBBound.{u} d mSmall B := by
  intro G _instGroup _instFinite hgen hexpSmall
  apply h G hgen
  intro x
  rcases hdiv with ⟨c, rfl⟩
  calc
    x ^ (mSmall * c) = (x ^ mSmall) ^ c := by rw [pow_mul]
    _ = 1 := by simp [hexpSmall x]
/-- A finite power-width bound for more generators applies to fewer generators by padding with
identities. -/
lemma PWBound.mono_generators
    {d d' m k : ℕ}
    (hd : d ≤ d')
    (h : PWBound.{u} d' m k) :
    PWBound.{u} d m k := by
  intro G _instGroup _instFinite t ht
  exact h G (padGenerators hd t) (GeneratedBy.pad hd ht)
/-- A restricted-Burnside bound for more generators applies to fewer generators by padding with
identities. -/
lemma RBBound.mono_generators
    {d d' m B : ℕ}
    (hd : d ≤ d')
    (h : RBBound.{u} d' m B) :
    RBBound.{u} d m B := by
  intro G _instGroup _instFinite hgen hexp
  rcases hgen with ⟨t, ht⟩
  exact h G ⟨padGenerators hd t, GeneratedBy.pad hd ht⟩ hexp
/-- A finite width/index package for more generators applies to fewer generators by padding with
identities. -/
lemma WIBound.mono_generators
    {d d' m k B : ℕ}
    (hd : d ≤ d')
    (h : WIBound.{u} d' m k B) :
    WIBound.{u} d m k B := by
  intro G _instGroup _instFinite t ht
  exact h G (padGenerators hd t) (GeneratedBy.pad hd ht)
/-- The finite prime-power package is monotone when the number of generators is decreased. -/
theorem NPPower.mono_generators
    {d d' p e : ℕ} [Fact p.Prime]
    (hd : d ≤ d')
    (h : NPPower.{u} d' p e) :
    NPPower.{u} d p e := by
  rcases h with ⟨k, B, hfin⟩
  exact ⟨k, B, WIBound.mono_generators hd hfin⟩
/-- Restricted-Burnside cardinal bounds are monotone in the numeric bound. -/
lemma RBBound.mono_bound
    {d m B B' : ℕ}
    (h : RBBound.{u} d m B)
    (hBB' : B ≤ B') :
    RBBound.{u} d m B' := by
  intro G _instGroup _instFinite hgen hexp
  exact (h G hgen hexp).trans hBB'
/-- The index part of the finite width/index package is monotone in the numeric bound. -/
lemma WIBound.mono_bound
    {d m k B B' : ℕ}
    (h : WIBound.{u} d m k B)
    (hBB' : B ≤ B') :
    WIBound.{u} d m k B' := by
  intro G _instGroup _instFinite t ht
  exact ⟨(h G t ht).1, (h G t ht).2.trans hBB'⟩
/-- A closed overgroup contains the topological closure. -/
lemma topological_closure_closed
    {G : Type u} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    {H K : Subgroup G}
    (hHK : H ≤ K)
    (hK : IsClosed ((K : Subgroup G) : Set G)) :
    Subgroup.topologicalClosure H ≤ K := by
  exact H.topologicalClosure_minimal hHK hK
end Submission
