import Mathlib.Algebra.Group.Subgroup.Lattice
import Mathlib.Algebra.Algebra.Operations
import Mathlib.Algebra.Module.Submodule.Pointwise
import Mathlib.Algebra.Ring.Regular
import Mathlib.Data.Nat.Choose.Sum
import Mathlib.Data.Finset.Interval
import Mathlib.LinearAlgebra.Span.Basic
import Towers.Group.Zassenhaus.MultiplicativelyDescending

/-!
# Binomial powers in multiplicative filtrations

This file isolates the filtered-ring calculation used in the left inclusion
of Theorem 4.3 and in the inductive argument of Theorem 6.1.
-/

namespace EChapma

open scoped Pointwise

variable {A : Type*} [Ring A]

/-- An additive filtration compatible with multiplication. -/
structure MAFilt (A : Type*) [Ring A] where
  term : ℕ → AddSubgroup A
  antitone : Antitone term
  mul_mem :
    ∀ {i j : ℕ} {x y : A},
      x ∈ term i → y ∈ term j → x * y ∈ term (i + j)

namespace MAFilt

/-- Positive powers multiply filtration degree. -/
theorem pow_mem (F : MAFilt A)
    {i l : ℕ} {x : A} (hx : x ∈ F.term i) (hl : 1 ≤ l) :
    x ^ l ∈ F.term (i * l) := by
  induction l with
  | zero => omega
  | succ l ih =>
      by_cases hl0 : l = 0
      · subst l
        simpa
      · have hlpos : 1 ≤ l := Nat.one_le_iff_ne_zero.mpr hl0
        have hpow := ih hlpos
        rw [pow_succ]
        simpa [Nat.mul_add] using F.mul_mem hpow hx

/--
The additive subgroup generated by the weighted filtration terms
`e(n,i) F_i`, for `1 ≤ i ≤ n`.
-/
def weightedSubgroup
    (F : MAFilt A)
    (e : MDescen) (n : ℕ) : AddSubgroup A :=
  AddSubgroup.closure {x |
    ∃ i, 1 ≤ i ∧ i ≤ n ∧
      ∃ y ∈ F.term i, (e n i) • y = x}

/-- The `i`th weighted summand, regarded as an integer submodule. -/
def weightedTermSubmodule
    (F : MAFilt A)
    (e : MDescen) (n i : ℕ) : Submodule ℤ A :=
  (e n i : ℤ) • (F.term i).toIntSubmodule

/-- The weighted subgroup, regarded as an integer submodule. -/
def weightedSubmodule
    (F : MAFilt A)
    (e : MDescen) (n : ℕ) : Submodule ℤ A :=
  (F.weightedSubgroup e n).toIntSubmodule

/-- The weighted submodule is the sum of its valid weighted filtration terms. -/
theorem submodule_i_sup
    (F : MAFilt A)
    (e : MDescen) (n : ℕ) :
    F.weightedSubmodule e n =
      ⨆ i : {i : ℕ // 1 ≤ i ∧ i ≤ n},
        F.weightedTermSubmodule e n i.1 := by
  apply le_antisymm
  · intro x hx
    change x ∈ F.weightedSubgroup e n at hx
    induction hx using AddSubgroup.closure_induction with
    | mem x hx =>
        rcases hx with ⟨i, hi, hin, y, hy, rfl⟩
        apply Submodule.mem_iSup_of_mem
          (⟨i, hi, hin⟩ : {i : ℕ // 1 ≤ i ∧ i ≤ n})
        simpa [weightedTermSubmodule] using
          Submodule.smul_mem_pointwise_smul y (e n i : ℤ)
            (F.term i).toIntSubmodule hy
    | zero => exact Submodule.zero_mem _
    | add x y _ _ hx hy => exact Submodule.add_mem _ hx hy
    | neg x _ hx => exact Submodule.neg_mem _ hx
  · apply iSup_le
    intro i x hx
    change x ∈ (e n i.1 : ℤ) • (F.term i.1).toIntSubmodule at hx
    rw [← Submodule.singleton_set_smul] at hx
    rcases (Submodule.mem_singleton_set_smul
      (N := (F.term i.1).toIntSubmodule) (e n i.1 : ℤ) x).mp hx with
      ⟨y, hy, rfl⟩
    change (e n i.1 : ℤ) • y ∈ F.weightedSubgroup e n
    apply AddSubgroup.subset_closure
    exact ⟨i.1, i.property.1, i.property.2, y, hy, by simp⟩

theorem weightedGenerator_mem
    (F : MAFilt A)
    (e : MDescen) {n i : ℕ}
    (hi : 1 ≤ i) (hin : i ≤ n)
    {x : A} (hx : x ∈ F.term i) :
    (e n i) • x ∈ F.weightedSubgroup e n :=
  AddSubgroup.subset_closure ⟨i, hi, hin, x, hx, rfl⟩

/--
Each nonconstant binomial term in `(1 + x)^(e(n,i))` belongs to the
weighted subgroup.
-/
theorem choose_nsmul_weighted
    (F : MAFilt A)
    (e : MDescen) (he : e.IsBinomial)
    {n i l : ℕ} (hi : 1 ≤ i) (hin : i ≤ n)
    (hl : 1 ≤ l) (hle : l ≤ e n i)
    {x : A} (hx : x ∈ F.term i) :
    Nat.choose (e n i) l • x ^ l ∈ F.weightedSubgroup e n := by
  have hxpow : x ^ l ∈ F.term (i * l) :=
    F.pow_mem hx hl
  by_cases hil : i * l ≤ n
  · obtain ⟨q, hq⟩ := he hi hin hl hle hil
    have hqpow : q • x ^ l ∈ F.term (i * l) :=
      (F.term (i * l)).nsmul_mem hxpow q
    have hgen :=
      F.weightedGenerator_mem e (by
        exact Nat.one_le_iff_ne_zero.mpr <|
          mul_ne_zero (Nat.ne_of_gt hi) (Nat.ne_of_gt hl))
        hil hqpow
    rw [hq, Nat.mul_comm, mul_nsmul]
    exact hgen
  · have hn : 1 ≤ n := hi.trans hin
    have hdeep : x ^ l ∈ F.term n :=
      F.antitone (Nat.le_of_not_ge hil) hxpow
    have hmultiple :
        Nat.choose (e n i) l • x ^ l ∈ F.term n :=
      (F.term n).nsmul_mem hdeep _
    simpa [e.diagonal n hn] using
      F.weightedGenerator_mem e hn le_rfl hmultiple

/-- The nonconstant binomial tail associated to `(e,n,i,x)`. -/
def binomialTail
    (e : MDescen) (n i : ℕ) (x : A) : A :=
  ∑ k ∈ Finset.range (e n i),
    Nat.choose (e n i) (k + 1) • x ^ (k + 1)

/-- The binomial tail is exactly `(1 + x)^m - 1`. -/
theorem sub_binomial_tail
    (e : MDescen) (n i : ℕ) (x : A) :
    (1 + x) ^ (e n i) - 1 = binomialTail e n i x := by
  rw [add_comm 1 x, (Commute.one_right x).add_pow]
  simp only [one_pow, mul_one]
  rw [Finset.sum_range_succ']
  simp [binomialTail, nsmul_eq_mul, Nat.cast_comm]

/--
The complete nonconstant binomial tail belongs to the weighted subgroup.
-/
theorem binomial_weighted_subgroup
    (F : MAFilt A)
    (e : MDescen) (he : e.IsBinomial)
    {n i : ℕ} (hi : 1 ≤ i) (hin : i ≤ n)
    {x : A} (hx : x ∈ F.term i) :
    binomialTail e n i x ∈ F.weightedSubgroup e n := by
  apply (F.weightedSubgroup e n).sum_mem
  intro k hk
  rw [Finset.mem_range] at hk
  exact F.choose_nsmul_weighted e he hi hin
    (by omega) (by omega) hx

end MAFilt

end EChapma
