import Submission.ClassField.NormIndex.ContainsAllRamified
import Submission.ClassField.NormIndex.FrobeniusGeneration
import Submission.ClassField.NormIndex.ClassCokernelComparison
import Submission.ClassField.NormIndex.IdeleExtensionMap
import Submission.ClassField.NormIndex.IdeleExtensionTower
import Submission.ClassField.NormIndex.IdeleTowerPlaces
import Submission.ClassField.NormIndex.IdeleTowerLocal
import Submission.ClassField.NormIndex.IdeleTowerFinite
import Submission.ClassField.NormIndex.IdeleTowerTransitivity
import Submission.ClassField.NormIndex.ClassGenerators
import Submission.ClassField.NormIndex.RestrictedQuotient
import Submission.ClassField.NormIndex.CyclicSubextension
import Submission.ClassField.NormIndex.NormCompatibility
import Submission.ClassField.NormIndex.CanonicalTateFormula
import Submission.ClassField.NormIndex.CompletionOrbitEquiv
import Submission.ClassField.NormIndex.CompletionProductNorm
import Submission.ClassField.NormIndex.CompletionPlaceBridge
import Submission.ClassField.NormIndex.CompletionPlaceComparison
import Submission.ClassField.NormIndex.FiniteIdeleContinuity
import Submission.ClassField.NormIndex.FiniteLocalStabilizer
import Submission.ClassField.NormIndex.SplitAwayNorm

/-! # Chapter VII, Section 4: the first inequality -/
