import Submission.NumberTheory.ClassGroup.ClassNumberFinite
import Mathlib.RingTheory.DedekindDomain.Factorization
import Mathlib.RingTheory.Ideal.IsPrincipal
import Mathlib.RingTheory.UniqueFactorizationDomain.Basic
import Mathlib.RingTheory.UniqueFactorizationDomain.NormalizedFactors


/-!
# Half-factorial number rings and Carlitz's theorem

The length of a factorization ignores order and associates, so a factorization
is represented by a multiset of irreducibles whose product is associated to
the element being factored.  A monoid is half-factorial when any two such
factorizations have the same cardinality.

Milne cites Carlitz's characterization of number fields of class number two
in the Introduction, without proof.  The forward implication is proved here
from ideal factorization.  The exact equivalence, whose converse uses the
existence of prime ideals in prescribed ideal classes, is also exposed as a
proposition that can be passed explicitly to its consequences.  No axiom is
introduced.
-/

namespace Submission.NumberTheory.Milne

open scoped NumberField
open scoped nonZeroDivisors
open UniqueFactorizationMonoid

universe u

/-- A factorization of `a` into irreducibles, modulo a unit in the product. -/
def IsIrreducibleFactorization {R : Type*} [CommMonoidWithZero R]
    (a : R) (f : Multiset R) : Prop :=
  (∀ p ∈ f, Irreducible p) ∧ Associated f.prod a

/-- Every irreducible factorization of each element has the same length. -/
def HalfFactorialMonoid (R : Type*) [CommMonoidWithZero R] : Prop :=
  ∀ (a : R) (f g : Multiset R),
    IsIrreducibleFactorization a f →
      IsIrreducibleFactorization a g → f.card = g.card

/-- A unique-factorization monoid is half-factorial. -/
theorem half_factorial_factorization
    (R : Type*) [CommMonoidWithZero R] [UniqueFactorizationMonoid R] :
    HalfFactorialMonoid R := by
  intro a f g hf hg
  apply Multiset.card_eq_card_of_rel
  apply UniqueFactorizationMonoid.factors_unique hf.1 hg.1
  exact hf.2.trans hg.2.symm

/-- The class-number-one case is unconditionally half-factorial, since its
integer ring is a principal ideal ring and hence a unique-factorization
monoid. -/
theorem integers_half_factorial
    (K : Type u) [Field K] [NumberField K]
    (hK : NumberField.classNumber K = 1) :
    HalfFactorialMonoid (𝓞 K) := by
  letI : IsPrincipalIdealRing (𝓞 K) :=
    NumberField.classNumber_eq_one_iff.mp hK
  exact half_factorial_factorization (𝓞 K)

section CarlitzForward

variable {R : Type*} [CommRing R] [IsDomain R] [IsDedekindDomain R]

/-- Give a principal prime-ideal factor weight two and a nonprincipal
prime-ideal factor weight one.  For class group of order two, every
irreducible element has total ideal-factor weight two. -/
noncomputable def idealFactorWeight (P : Ideal R) : ℕ :=
  by
    classical
    exact if _h : P.IsPrincipal then 2 else 1

/-- The weighted number of prime ideals in the principal ideal generated by
`a`. -/
noncomputable def principalFactorWeight (a : R) : ℕ :=
  ((normalizedFactors (Ideal.span {a})).map
    (idealFactorWeight (R := R))).sum

omit [IsDomain R] in
private theorem principal_right_mul
    {I J : Ideal R} (hI0 : I ≠ ⊥) (hI : I.IsPrincipal)
    (hIJ : (I * J).IsPrincipal) : J.IsPrincipal := by
  rcases hI with ⟨x, hxI⟩
  change I = Ideal.span ({x} : Set R) at hxI
  subst I
  rcases hIJ with ⟨z, hz⟩
  change Ideal.span ({x} : Set R) * J = Ideal.span ({z} : Set R) at hz
  have hx : x ≠ 0 := by
    intro hx
    subst x
    simp at hI0
  have hzmem : z ∈ Ideal.span ({x} : Set R) * J := by
    rw [hz]
    exact Ideal.mem_span_singleton_self z
  obtain ⟨y, hyJ, hxy⟩ := Ideal.mem_span_singleton_mul.mp hzmem
  refine ⟨y, ?_⟩
  apply mul_left_cancel₀ (show Ideal.span ({x} : Set R) ≠ 0 by
    intro h
    exact hx (Ideal.span_singleton_eq_bot.mp h))
  calc
    Ideal.span ({x} : Set R) * J = Ideal.span ({z} : Set R) := hz
    _ = Ideal.span ({x * y} : Set R) := by rw [hxy]
    _ = Ideal.span ({x} : Set R) * Ideal.span ({y} : Set R) :=
      (Ideal.span_singleton_mul_span_singleton x y).symm

omit [IsDedekindDomain R] in
private theorem irreducible_generator_or
    {p : R} (hp : Irreducible p)
    {I J : Ideal R} (hI : I.IsPrincipal) (hJ : J.IsPrincipal)
    (h : Ideal.span ({p} : Set R) = I * J) :
    IsUnit I ∨ IsUnit J := by
  rcases hI with ⟨x, hxI⟩
  rcases hJ with ⟨y, hyJ⟩
  change I = Ideal.span ({x} : Set R) at hxI
  change J = Ideal.span ({y} : Set R) at hyJ
  subst I
  subst J
  have hassoc : Associated p (x * y) := by
    apply Ideal.span_singleton_eq_span_singleton.mp
    rw [Ideal.span_singleton_mul_span_singleton] at h
    exact h
  rcases (hassoc.irreducible hp).isUnit_or_isUnit rfl with hx | hy
  · left
    exact Ideal.isUnit_iff.mpr (Ideal.span_singleton_eq_top.mpr hx)
  · right
    exact Ideal.isUnit_iff.mpr (Ideal.span_singleton_eq_top.mpr hy)

omit [IsDomain R] in
private theorem multiset_normalized_factors
    {I : Ideal R} {t : Multiset (Ideal R)}
    (ht : ∀ P ∈ t, P ∈ normalizedFactors I) (ht0 : t ≠ 0) :
    ¬ IsUnit t.prod := by
  obtain ⟨P, hPt⟩ := Multiset.exists_mem_of_ne_zero ht0
  have hPs : P ∈ normalizedFactors I := ht P hPt
  have hPnonunit : ¬ IsUnit P :=
    (UniqueFactorizationMonoid.irreducible_of_normalized_factor P hPs).not_isUnit
  intro hprod
  apply hPnonunit
  apply Ideal.isUnit_iff.mpr
  apply top_unique
  rw [← Ideal.isUnit_iff.mp hprod]
  obtain ⟨u, rfl⟩ := Multiset.exists_cons_of_mem hPt
  simp only [Multiset.prod_cons]
  exact Ideal.mul_le_right

/-- In a Dedekind domain with two ideal classes, the product of two nonzero
nonprincipal ideals is principal. -/
theorem principal_card_two
    (hcard : Nat.card (ClassGroup R) = 2)
    {I J : Ideal R} (hI0 : I ≠ ⊥) (hJ0 : J ≠ ⊥)
    (hI : ¬ I.IsPrincipal) (hJ : ¬ J.IsPrincipal) :
    (I * J).IsPrincipal := by
  let I0 : (Ideal R)⁰ :=
    ⟨I, mem_nonZeroDivisors_iff_ne_zero.mpr hI0⟩
  let J0 : (Ideal R)⁰ :=
    ⟨J, mem_nonZeroDivisors_iff_ne_zero.mpr hJ0⟩
  have hIc : ClassGroup.mk0 I0 ≠ 1 := by
    intro hc
    exact hI ((ClassGroup.mk0_eq_one_iff I0.prop).mp hc)
  have hJc : ClassGroup.mk0 J0 ≠ 1 := by
    intro hc
    exact hJ ((ClassGroup.mk0_eq_one_iff J0.prop).mp hc)
  obtain ⟨c, hc, hc_unique⟩ :=
    (Nat.card_eq_two_iff' (1 : ClassGroup R)).mp hcard
  have hclasses : ClassGroup.mk0 I0 = ClassGroup.mk0 J0 :=
    (hc_unique _ hIc).trans (hc_unique _ hJc).symm
  have hinv_ne : (ClassGroup.mk0 I0)⁻¹ ≠ 1 := by simpa using hIc
  have hinv_eq : (ClassGroup.mk0 I0)⁻¹ = ClassGroup.mk0 I0 :=
    (hc_unique _ hinv_ne).trans (hc_unique _ hIc).symm
  let IJ0 : (Ideal R)⁰ := I0 * J0
  apply (ClassGroup.mk0_eq_one_iff IJ0.prop).mp
  change ClassGroup.mk0 (I0 * J0) = 1
  calc
    ClassGroup.mk0 (I0 * J0) = ClassGroup.mk0 I0 * ClassGroup.mk0 J0 := by
      rw [map_mul]
    _ = ClassGroup.mk0 I0 * ClassGroup.mk0 I0 := by rw [hclasses]
    _ = (ClassGroup.mk0 I0)⁻¹ * ClassGroup.mk0 I0 := by rw [hinv_eq]
    _ = 1 := inv_mul_cancel _

/-- The ideal-factor weight of an irreducible element is two when the class
group has order two.  This is the algebraic heart of the forward implication
in Carlitz's theorem. -/
theorem principal_irreducible_two
    (hcard : Nat.card (ClassGroup R) = 2)
    {p : R} (hp : Irreducible p) :
    principalFactorWeight p = 2 := by
  classical
  let I : Ideal R := Ideal.span {p}
  let s : Multiset (Ideal R) := normalizedFactors I
  have hI0 : I ≠ ⊥ := by
    intro h
    exact hp.ne_zero (Ideal.span_singleton_eq_bot.mp h)
  have hsprod : s.prod = I := by
    exact Ideal.prod_normalizedFactors_eq_self hI0
  have hs_mem (P : Ideal R) (hP : P ∈ s) :
      P ∈ normalizedFactors I := hP
  by_cases hex : ∃ P ∈ s, P.IsPrincipal
  · obtain ⟨P, hPs, hPprincipal⟩ := hex
    obtain ⟨u, hsu⟩ := Multiset.exists_cons_of_mem hPs
    have hP0 : P ≠ ⊥ :=
      (UniqueFactorizationMonoid.irreducible_of_normalized_factor P
        (hs_mem P hPs)).ne_zero
    have huPrincipal : u.prod.IsPrincipal := by
      apply principal_right_mul hP0 hPprincipal
      refine ⟨p, ?_⟩
      change P * u.prod = Ideal.span ({p} : Set R)
      calc
        P * u.prod = s.prod := by rw [hsu, Multiset.prod_cons]
        _ = I := hsprod
        _ = Ideal.span ({p} : Set R) := rfl
    have hu0 : u = 0 := by
      by_contra hu0
      have hPnonunit : ¬ IsUnit P :=
        (UniqueFactorizationMonoid.irreducible_of_normalized_factor P
          (hs_mem P hPs)).not_isUnit
      have hunonunit : ¬ IsUnit u.prod := by
        apply multiset_normalized_factors
        · intro Q hQu
          apply hs_mem Q
          rw [hsu]
          exact Multiset.mem_cons_of_mem hQu
        · exact hu0
      have hirr := irreducible_generator_or hp
        hPprincipal huPrincipal (by
          calc
            Ideal.span ({p} : Set R) = I := rfl
            _ = s.prod := hsprod.symm
            _ = P * u.prod := by rw [hsu, Multiset.prod_cons])
      exact hirr.elim hPnonunit hunonunit
    have hs_exp : normalizedFactors (Ideal.span ({p} : Set R)) = P ::ₘ u := by
      simpa [s, I] using hsu
    rw [principalFactorWeight, hs_exp, hu0]
    simp [idealFactorWeight, hPprincipal]
  · have hall (P : Ideal R) (hP : P ∈ s) : ¬ P.IsPrincipal := by
      intro h
      exact hex ⟨P, hP, h⟩
    have hs0 : s ≠ 0 := by
      intro hs0
      have hItop : I = ⊤ := by
        rw [← hsprod, hs0]
        simp
      exact hp.not_isUnit (Ideal.span_singleton_eq_top.mp hItop)
    obtain ⟨P, hPs⟩ := Multiset.exists_mem_of_ne_zero hs0
    obtain ⟨u, hsu⟩ := Multiset.exists_cons_of_mem hPs
    have hu0 : u ≠ 0 := by
      intro hu0
      have hPI : P = I := by
        rw [← hsprod, hsu, hu0]
        simp
      exact hall P hPs (hPI ▸ (inferInstance : I.IsPrincipal))
    obtain ⟨Q, hQu⟩ := Multiset.exists_mem_of_ne_zero hu0
    obtain ⟨v, huv⟩ := Multiset.exists_cons_of_mem hQu
    have hQs : Q ∈ s := by
      rw [hsu, huv]
      exact Multiset.mem_cons_of_mem (Multiset.mem_cons_self Q v)
    have hP0 : P ≠ ⊥ :=
      (UniqueFactorizationMonoid.irreducible_of_normalized_factor P
        (hs_mem P hPs)).ne_zero
    have hQ0 : Q ≠ ⊥ :=
      (UniqueFactorizationMonoid.irreducible_of_normalized_factor Q
        (hs_mem Q hQs)).ne_zero
    have hPQPrincipal : (P * Q).IsPrincipal :=
      principal_card_two hcard hP0 hQ0
        (hall P hPs) (hall Q hQs)
    have hPQ0 : P * Q ≠ ⊥ := mul_ne_zero hP0 hQ0
    have hvPrincipal : v.prod.IsPrincipal := by
      apply principal_right_mul hPQ0 hPQPrincipal
      refine ⟨p, ?_⟩
      change (P * Q) * v.prod = Ideal.span ({p} : Set R)
      calc
        (P * Q) * v.prod = s.prod := by
          rw [hsu, huv]
          simp only [Multiset.prod_cons, mul_assoc]
        _ = I := hsprod
        _ = Ideal.span ({p} : Set R) := rfl
    have hv0 : v = 0 := by
      by_contra hv0
      have hPQnonunit : ¬ IsUnit (P * Q) := by
        have h := multiset_normalized_factors
          (I := I) (t := ({P, Q} : Multiset (Ideal R))) (by
            intro T hT
            have hT' : T = P ∨ T = Q := by simpa using hT
            rcases hT' with hTP | hTQ
            · simpa [hTP] using hs_mem P hPs
            · simpa [hTQ] using hs_mem Q hQs) (by simp)
        simpa using h
      have hvnonunit : ¬ IsUnit v.prod := by
        apply multiset_normalized_factors
        · intro T hTv
          apply hs_mem T
          rw [hsu, huv]
          exact Multiset.mem_cons_of_mem (Multiset.mem_cons_of_mem hTv)
        · exact hv0
      have hirr := irreducible_generator_or hp
        hPQPrincipal hvPrincipal (by
          calc
            Ideal.span ({p} : Set R) = I := rfl
            _ = s.prod := hsprod.symm
            _ = (P * Q) * v.prod := by
              rw [hsu, huv]
              simp only [Multiset.prod_cons, mul_assoc])
      exact hirr.elim hPQnonunit hvnonunit
    have hs_exp : normalizedFactors (Ideal.span ({p} : Set R)) = P ::ₘ Q ::ₘ v := by
      simpa [s, I, huv] using hsu
    rw [principalFactorWeight, hs_exp, hv0]
    simp [idealFactorWeight, hall P hPs, hall Q hQs]

omit [IsDomain R] in
/-- The weighted ideal-factor count is additive under multiplication of
nonzero elements. -/
theorem principal_factor_mul {a b : R} (ha : a ≠ 0) (hb : b ≠ 0) :
    principalFactorWeight (a * b) =
      principalFactorWeight a + principalFactorWeight b := by
  have haI : Ideal.span ({a} : Set R) ≠ ⊥ := by
    intro h
    exact ha (Ideal.span_singleton_eq_bot.mp h)
  have hbI : Ideal.span ({b} : Set R) ≠ ⊥ := by
    intro h
    exact hb (Ideal.span_singleton_eq_bot.mp h)
  rw [principalFactorWeight,
    ← Ideal.span_singleton_mul_span_singleton,
    normalizedFactors_mul haI hbI, Multiset.map_add, Multiset.sum_add]
  rfl

/-- Associated elements have the same weighted ideal-factor count. -/
theorem principal_factor_associated {a b : R}
    (h : Associated a b) :
    principalFactorWeight a = principalFactorWeight b := by
  unfold principalFactorWeight
  rw [Ideal.span_singleton_eq_span_singleton.mpr h]

private theorem principal_prod_irreducibles
    (hcard : Nat.card (ClassGroup R) = 2)
    {f : Multiset R} (hf : ∀ p ∈ f, Irreducible p) :
    principalFactorWeight f.prod = 2 * f.card := by
  induction f using Multiset.induction_on with
  | empty =>
      simp only [Multiset.prod_zero, Multiset.card_zero, mul_zero,
        principalFactorWeight, Ideal.span_singleton_one,
        ← Ideal.one_eq_top, normalizedFactors_one, Multiset.map_zero,
        Multiset.sum_zero]
  | cons p f ih =>
      have hp : Irreducible p := hf p (Multiset.mem_cons_self p f)
      have hf' : ∀ q ∈ f, Irreducible q := by
        intro q hq
        exact hf q (Multiset.mem_cons_of_mem hq)
      have hfprod0 : f.prod ≠ 0 :=
        Multiset.prod_ne_zero fun hq ↦ (hf' 0 hq).ne_zero rfl
      rw [Multiset.prod_cons,
        principal_factor_mul hp.ne_zero hfprod0,
        principal_irreducible_two hcard hp,
        ih hf', Multiset.card_cons]
      omega

/-- The unconditional forward implication in Carlitz's theorem: a Dedekind
domain whose class group has order two is half-factorial. -/
theorem half_factorial_monoid
    (hcard : Nat.card (ClassGroup R) = 2) :
    HalfFactorialMonoid R := by
  intro a f g hf hg
  have hfw := principal_prod_irreducibles hcard hf.1
  have hgw := principal_prod_irreducibles hcard hg.1
  have hfa := principal_factor_associated hf.2
  have hga := principal_factor_associated hg.2
  omega

/-- If a number field has class number two, its ring of integers is
half-factorial.  This is the forward half of the theorem cited by Milne. -/
theorem ring_half_factorial
    (K : Type u) [Field K] [NumberField K]
    (hK : NumberField.classNumber K = 2) :
    HalfFactorialMonoid (𝓞 K) := by
  apply half_factorial_monoid
  rw [Nat.card_eq_fintype_card]
  exact hK

end CarlitzForward

/-- Carlitz's theorem, cited without proof in the Introduction to ANT.

Under Milne's standing assumption that the class number is not one, the
class number is two exactly when the integer ring is half-factorial.
The definition records the external theorem as an explicit proposition,
following the treatment of the source-delegated Chebotarev theorem.
-/
def CarlitzHalfTheorem : Prop :=
  ∀ (K : Type u) [Field K] [NumberField K],
    NumberField.classNumber K ≠ 1 →
      (NumberField.classNumber K = 2 ↔
        HalfFactorialMonoid (𝓞 K))

/-- The fieldwise form of Carlitz's theorem, from the explicit global
statement above. -/
theorem carlitz_half_factorial
    (hCarlitz : CarlitzHalfTheorem.{u})
    (K : Type u) [Field K] [NumberField K]
    (hK : NumberField.classNumber K ≠ 1) :
    NumberField.classNumber K = 2 ↔ HalfFactorialMonoid (𝓞 K) :=
  hCarlitz K hK

end Submission.NumberTheory.Milne
