import Mathlib

/-!
# The note after Milne, Proposition 3.6

Milne records two facts after the local characterization of Dedekind domains.  The first is
the existence of a nonnoetherian domain whose localizations at all nonzero prime ideals are
DVRs.  His source gives neither a construction nor a proof, so its exact content is exposed
below as a proposition rather than postulated as an axiom.

The second fact is proved here: if every localization at a maximal ideal is noetherian and
every nonzero element lies in only finitely many maximal ideals, then the ring is noetherian.
-/

namespace Submission.NumberTheory.Milne

universe u

/-- **Note after Proposition 3.6 (existence statement).** There is a nonnoetherian domain
whose localization at every nonzero prime ideal is a discrete valuation ring.  Milne states
this without a construction or proof. -/
def NonnoetherianLocallyDVR : Prop :=
  ∃ (A : Type u) (ringA : CommRing A),
    letI : CommRing A := ringA
    ∃ domainA : IsDomain A,
      letI : IsDomain A := domainA
      ¬IsNoetherianRing A ∧
        ∀ (P : Ideal A), P ≠ ⊥ → ∀ hP : P.IsPrime,
          letI : P.IsPrime := hP
          IsDiscreteValuationRing (Localization.AtPrime P)

/-- If an ideal becomes finitely generated after localization at `P`, its localized ideal
is already generated by the images of finitely many elements of the original ideal. -/
private theorem finset_subset_span
    (A : Type*) [CommRing A] (P : Ideal A) [P.IsPrime]
    (I : Ideal A) [IsNoetherianRing (Localization.AtPrime P)] :
    ∃ s : Finset A, (s : Set A) ⊆ I ∧
      Ideal.map (algebraMap A (Localization.AtPrime P)) (Ideal.span (s : Set A)) =
        Ideal.map (algebraMap A (Localization.AtPrime P)) I := by
  classical
  let S := Localization.AtPrime P
  let f : A →+* S := algebraMap A S
  obtain ⟨t, ht⟩ :=
    (Ideal.fg_of_isNoetherianRing (Ideal.map f I) : (Ideal.map f I).FG)
  have htmem : ∀ z : S, z ∈ t → z ∈ Ideal.map f I := by
    intro z hz
    rw [← ht]
    exact Ideal.subset_span hz
  choose data hdata using fun z : {z : S // z ∈ t} ↦
    (IsLocalization.mem_map_algebraMap_iff P.primeCompl S).mp (htmem z z.2)
  let numerator (z : {z : S // z ∈ t}) : A := (data z).1.1
  let s : Finset A := Finset.univ.image numerator
  have hsI : (s : Set A) ⊆ I := by
    intro x hx
    simp only [s, Finset.coe_image, Finset.coe_univ, Set.image_univ, Set.mem_range] at hx
    obtain ⟨z, rfl⟩ := hx
    exact (data z).1.2
  refine ⟨s, hsI, le_antisymm (Ideal.map_mono (Ideal.span_le.mpr hsI)) ?_⟩
  rw [← ht]
  apply Ideal.span_le.mpr
  intro z hz
  let zt : {z : S // z ∈ t} := ⟨z, hz⟩
  have hnum : numerator zt ∈ Ideal.span (s : Set A) := by
    apply Ideal.subset_span
    simp [s, numerator]
  have hmapnum : f (numerator zt) ∈
      Ideal.map f (Ideal.span (s : Set A)) :=
    Ideal.mem_map_of_mem f hnum
  change z ∈ Ideal.map f (Ideal.span (s : Set A))
  apply (Ideal.unit_mul_mem_iff_mem _ (IsLocalization.map_units S (data zt).2)).mp
  rw [mul_comm, hdata zt]
  exact hmapnum

/-- **Note after Proposition 3.6 (finite-character criterion).** If all localizations of a
commutative ring at maximal ideals are noetherian and every nonzero element is contained in
only finitely many maximal ideals, then the ring itself is noetherian. -/
theorem noethe_local_chara
    (A : Type*) [CommRing A]
    (hlocal : ∀ (P : Ideal A), ∀ hP : P.IsMaximal,
      letI : P.IsPrime := hP.isPrime
      IsNoetherianRing (Localization.AtPrime P))
    (hfinite : ∀ (a : A), a ≠ 0 →
      {P : MaximalSpectrum A | a ∈ P.asIdeal}.Finite) :
    IsNoetherianRing A := by
  classical
  rw [isNoetherianRing_iff_ideal_fg]
  intro I
  by_cases hI : I = ⊥
  · subst I
    exact Submodule.fg_bot
  obtain ⟨a, haI, ha0⟩ := Submodule.exists_mem_ne_zero_of_ne_bot hI
  let T : Set (MaximalSpectrum A) := {P | a ∈ P.asIdeal}
  have hTfinite : T.Finite := hfinite a ha0
  let F : Finset (MaximalSpectrum A) := hTfinite.toFinset
  have hgenerators : ∀ P : {P // P ∈ F},
      ∃ s : Finset A, (s : Set A) ⊆ I ∧
        Ideal.map (algebraMap A (Localization.AtPrime P.1.asIdeal))
            (Ideal.span (s : Set A)) =
          Ideal.map (algebraMap A (Localization.AtPrime P.1.asIdeal)) I := by
    intro P
    letI : P.1.asIdeal.IsPrime := P.1.isMaximal.isPrime
    letI : IsNoetherianRing (Localization.AtPrime P.1.asIdeal) :=
      hlocal P.1.asIdeal P.1.isMaximal
    exact finset_subset_span A P.1.asIdeal I
  choose generators hgeneratorsI hgeneratorsMap using hgenerators
  let g : Finset A := insert a (Finset.univ.biUnion generators)
  have hgI : (g : Set A) ⊆ I := by
    intro x hx
    simp only [g, Finset.mem_coe, Finset.mem_insert, Finset.mem_biUnion,
      Finset.mem_univ, true_and] at hx
    rcases hx with rfl | ⟨P, hxP⟩
    · exact haI
    · exact hgeneratorsI P hxP
  refine ⟨g, Ideal.eq_of_localization_maximal fun Q hQ ↦ ?_⟩
  letI : Q.IsPrime := hQ.isPrime
  have hspan_le : Ideal.span (g : Set A) ≤ I := Ideal.span_le.mpr hgI
  apply le_antisymm (Ideal.map_mono hspan_le)
  by_cases haQ : a ∈ Q
  · let q : MaximalSpectrum A := ⟨Q, hQ⟩
    have hqF : q ∈ F := by
      simp [F, T, q, haQ]
    let qF : {P // P ∈ F} := ⟨q, hqF⟩
    calc
      Ideal.map (algebraMap A (Localization.AtPrime Q)) I =
          Ideal.map (algebraMap A (Localization.AtPrime Q))
            (Ideal.span (generators qF : Set A)) := by
              simpa [qF, q] using (hgeneratorsMap qF).symm
      _ ≤ Ideal.map (algebraMap A (Localization.AtPrime Q))
          (Ideal.span (g : Set A)) := Ideal.map_mono (Ideal.span_mono (by
            intro x hx
            change x ∈ g
            simp only [g, Finset.mem_insert, Finset.mem_biUnion,
              Finset.mem_univ, true_and]
            exact Or.inr ⟨qF, hx⟩))
  · have ha_span : a ∈ Ideal.span (g : Set A) :=
      Ideal.subset_span (by simp [g])
    have hspan_not_le : ¬Ideal.span (g : Set A) ≤ Q := fun h ↦ haQ (h ha_span)
    have hI_not_le : ¬I ≤ Q := fun h ↦ haQ (h haI)
    rw [IsLocalization.AtPrime.map_eq_top_of_not_le
        (R := A) (S := Localization.AtPrime Q) hI_not_le,
      IsLocalization.AtPrime.map_eq_top_of_not_le
        (R := A) (S := Localization.AtPrime Q) hspan_not_le]

end Submission.NumberTheory.Milne
