import Mathlib.NumberTheory.NumberField.Cyclotomic.Ideal

/-!
# Prime-power cyclotomic fields

This file formalizes Proposition 6.2 of Milne's *Algebraic Number Theory* notes.
The exponent is written as `k + 1`, corresponding to Milne's positive integer
`r`.
-/

namespace Submission.NumberTheory.Milne

open Algebra Ideal IsCyclotomicExtension NumberField Polynomial

open scoped Cyclotomic

variable {p k : ℕ} {K : Type*} [Field K] [CharZero K] [hp : Fact p.Prime]
variable [hK : IsCyclotomicExtension {p ^ (k + 1)} ℚ K]

/-- Milne, Proposition 6.2(a): the degree of a prime-power cyclotomic field is
Euler's totient, with its explicit prime-power value. -/
theorem prime_cyclotomic_finrank :
    Module.finrank ℚ K = (p ^ (k + 1)).totient ∧
      (p ^ (k + 1)).totient = p ^ k * (p - 1) := by
  constructor
  · exact IsCyclotomicExtension.Rat.finrank (p ^ (k + 1)) K
  · simpa using Nat.totient_prime_pow hp.out (Nat.succ_pos k)

/-- Milne, Proposition 6.2(b): adjoining a primitive prime-power root of unity
to `ℤ` gives the full ring of integers. -/
theorem cyclotomic_integral_closure {zeta : K}
    (hzeta : IsPrimitiveRoot zeta (p ^ (k + 1))) :
    IsIntegralClosure (Algebra.adjoin ℤ ({zeta} : Set K)) ℤ K :=
  IsCyclotomicExtension.Rat.isIntegralClosure_adjoin_singleton_of_prime_pow hzeta

/-- Milne, Proposition 6.2(b), in integral-power-basis form. -/
theorem cyclotomic_integral_basis {zeta : K}
    (hzeta : IsPrimitiveRoot zeta (p ^ (k + 1))) :
    ∃ B : PowerBasis ℤ (𝓞 K),
      B.gen = hzeta.toInteger ∧ B.dim = (p ^ (k + 1)).totient := by
  refine ⟨hzeta.integralPowerBasisOfPrimePow, ?_, ?_⟩
  · exact hzeta.integralPowerBasisOfPrimePow_gen
  · exact hzeta.integralPowerBasisOfPrimePow_dim

/-- The ideals generated by `1 - ζ` and `ζ - 1` agree. -/
private theorem span_one_sub {R : Type*} [CommRing R] [IsDomain R] (zeta : R) :
    Ideal.span {1 - zeta} = Ideal.span {zeta - 1} := by
  apply Ideal.span_singleton_eq_span_singleton.mpr
  refine ⟨-1, ?_⟩
  simp

/-- Milne, Proposition 6.2(c): `π = 1 - ζ` is a prime element of the ring of
integers. -/
theorem sub_primitive_prime {zeta : K}
    (hzeta : IsPrimitiveRoot zeta (p ^ (k + 1))) :
    Prime (1 - hzeta.toInteger) := by
  simpa only [neg_sub] using hzeta.zeta_sub_one_prime.neg

/-- Milne's ideal identity `(p) = (1 - ζ)^φ(p^(k+1))`. -/
theorem prime_sub_totient {zeta : K}
    (hzeta : IsPrimitiveRoot zeta (p ^ (k + 1))) :
    Ideal.map (algebraMap ℤ (𝓞 K)) (Ideal.span {(p : ℤ)}) =
      Ideal.span {1 - hzeta.toInteger} ^ (p ^ (k + 1)).totient := by
  letI : NumberField K := IsCyclotomicExtension.numberField {p ^ (k + 1)} ℚ K
  rw [span_one_sub]
  rw [← (prime_cyclotomic_finrank (p := p) (k := k) (K := K)).1]
  exact IsCyclotomicExtension.Rat.map_eq_span_zeta_sub_one_pow p k hzeta

/-- Milne, Proposition 6.2(c): the prime generated by `1 - ζ` has residue
degree one. -/
theorem inertia_deg_primitive {zeta : K}
    (hzeta : IsPrimitiveRoot zeta (p ^ (k + 1))) :
    Ideal.inertiaDeg (Ideal.span {(p : ℤ)})
      (Ideal.span {1 - hzeta.toInteger}) = 1 := by
  letI : NumberField K := IsCyclotomicExtension.numberField {p ^ (k + 1)} ℚ K
  rw [span_one_sub]
  exact IsCyclotomicExtension.Rat.inertiaDeg_span_zeta_sub_one p k hzeta

/-- Milne, Proposition 6.2(c): the ramification index of the unique prime over
`p` is `φ(p^(k+1))`. -/
theorem ramification_idx_primitive {zeta : K}
    (hzeta : IsPrimitiveRoot zeta (p ^ (k + 1))) :
    Ideal.ramificationIdx (Ideal.span {(p : ℤ)})
      (Ideal.span {1 - hzeta.toInteger}) = (p ^ (k + 1)).totient := by
  letI : NumberField K := IsCyclotomicExtension.numberField {p ^ (k + 1)} ℚ K
  rw [span_one_sub,
    IsCyclotomicExtension.Rat.ramificationIdx_span_zeta_sub_one p k hzeta]
  exact (Nat.totient_prime_pow hp.out (Nat.succ_pos k)).symm

/-- Milne, Proposition 6.2(c): there is exactly one prime ideal above `p`. -/
theorem unique_ideal_above {p' k' : ℕ} {K' : Type*} [Field K'] [CharZero K']
    [hp' : Fact p'.Prime] [hK' : IsCyclotomicExtension {p' ^ (k' + 1)} ℚ K'] :
    letI : NumberField K' := IsCyclotomicExtension.numberField {p' ^ (k' + 1)} ℚ K'
    (Ideal.primesOver (Ideal.span {(p' : ℤ)}) (𝓞 K')).ncard = 1 := by
  letI : NumberField K' := IsCyclotomicExtension.numberField {p' ^ (k' + 1)} ℚ K'
  exact IsCyclotomicExtension.Rat.ncard_primesOver_of_prime_pow p' k' K'

/-- Milne, Proposition 6.2(d): the exact absolute discriminant formula, with
Milne's exponent `p^k * (p(k+1) - (k+1) - 1)`. -/
theorem prime_cyclotomic_discriminant :
    letI : NumberField K := IsCyclotomicExtension.numberField {p ^ (k + 1)} ℚ K
    NumberField.discr K =
      (-1) ^ (p ^ k * (p - 1) / 2) *
        p ^ (p ^ k * (p * (k + 1) - (k + 1) - 1)) := by
  simpa [Nat.sub_mul] using IsCyclotomicExtension.Rat.discr_prime_pow_succ p k K

/-- Milne's weaker discriminant conclusion: up to a unit, the discriminant is
a power of `p`. -/
theorem cyclotomic_discriminant_pow :
    letI : NumberField K := IsCyclotomicExtension.numberField {p ^ (k + 1)} ℚ K
    ∃ (u : ℤˣ) (c : ℕ), NumberField.discr K = u * p ^ c := by
  letI : NumberField K := IsCyclotomicExtension.numberField {p ^ (k + 1)} ℚ K
  refine ⟨(-1 : ℤˣ) ^ (p ^ k * (p - 1) / 2),
    p ^ k * (p * (k + 1) - (k + 1) - 1), ?_⟩
  simpa using
    (prime_cyclotomic_discriminant (p := p) (k := k) (K := K))

/-- Milne, Proposition 6.2(d): every rational prime other than `p` is
unramified in the `p^(k+1)`-th cyclotomic field. -/
theorem other_ramification_idx {p' k' : ℕ} {K' : Type*}
    [Field K'] [CharZero K'] [hp' : Fact p'.Prime]
    [hK' : IsCyclotomicExtension {p' ^ (k' + 1)} ℚ K']
    (q : ℕ) [hq : Fact q.Prime] (hqp : q ≠ p') :
    letI : NumberField K' := IsCyclotomicExtension.numberField {p' ^ (k' + 1)} ℚ K'
    (Ideal.span {(q : ℤ)}).ramificationIdxIn (𝓞 K') = 1 := by
  letI : NumberField K' := IsCyclotomicExtension.numberField {p' ^ (k' + 1)} ℚ K'
  apply IsCyclotomicExtension.Rat.ramificationIdxIn_eq_of_not_dvd
    (m := p' ^ (k' + 1)) q K'
  intro hdiv
  have hqp_dvd : q ∣ p' := hq.out.dvd_of_dvd_pow hdiv
  rcases (Nat.dvd_prime hp'.out).mp hqp_dvd with hq1 | hqp'
  · exact hq.out.ne_one hq1
  · exact hqp hqp'

end Submission.NumberTheory.Milne
