import Towers.ClassField.RayClassGroups.Modulus
import Towers.ClassField.RayClassGroups.ForbiddenIdeal
import Towers.ClassField.ArtinReciprocity.ArtinMap
import Mathlib.NumberTheory.NumberField.InfinitePlace.Ramification


/-!
# Chapter V, Section 3: statements of the main theorems

This file supplies the ray-principal and ideal-norm subgroups needed to state
the global reciprocity and existence theorems.  The norm subgroup is defined
from the prime-ideal formula `N(P) = p ^ f(P/p)`, so it does not rely on a
missing fractional-ideal norm API.
-/

namespace Towers.CField.ARecip

open IsDedekindDomain NumberField
open Towers.NumberTheory.Milne
open RCGroups
open scoped nonZeroDivisors

noncomputable section

universe u

/-- A finite abelian extension of a number field. -/
structure ANExt
    (K : Type u) [Field K] [NumberField K] where
  carrier : Type u
  [field : Field carrier]
  [numberField : NumberField carrier]
  [algebra : Algebra K carrier]
  [finiteDimensional : FiniteDimensional K carrier]
  [isGalois : IsGalois K carrier]
  [isAbelian : IsMulCommutative Gal(carrier/K)]

attribute [instance]
  ANExt.field
  ANExt.numberField
  ANExt.algebra
  ANExt.finiteDimensional
  ANExt.isGalois
  ANExt.isAbelian

variable {K : Type u} [Field K] [NumberField K]

namespace ANExt

/-- A prime of `L` together with the prime of `K` below it. -/
structure PAbove (L : ANExt K) where
  downstairs : HeightOneSpectrum (𝓞 K)
  upstairs : HeightOneSpectrum (𝓞 L.carrier)
  liesOver : upstairs.asIdeal.LiesOver downstairs.asIdeal

/-- The fractional ideal associated with a nonzero prime ideal. -/
def primeFractionalIdeal (p : HeightOneSpectrum (𝓞 K)) :
    (FractionalIdeal (𝓞 K)⁰ K)ˣ :=
  FractionalIdeal.mk0 K
    ⟨p.asIdeal, mem_nonZeroDivisors_iff_ne_zero.mpr p.ne_bot⟩

/-- The norm of a prime generator, expressed by the defining formula
`N(P) = p ^ f(P/p)`. -/
def PAbove.normGenerator (L : ANExt K)
    (P : L.PAbove) : (FractionalIdeal (𝓞 K)⁰ K)ˣ := by
  letI : P.upstairs.asIdeal.LiesOver P.downstairs.asIdeal := P.liesOver
  exact primeFractionalIdeal P.downstairs ^
    P.downstairs.asIdeal.inertiaDeg P.upstairs.asIdeal

/-- The image of the norm on all nonzero fractional ideals, generated by
the norms of prime ideals. -/
def totalIdealSubgroup (L : ANExt K) :
    Subgroup (FractionalIdeal (𝓞 K)⁰ K)ˣ :=
  Subgroup.closure (Set.range fun P : L.PAbove ↦ P.normGenerator L)

/-- The norm subgroup inside the ideals prime to `S`.

Intersecting the total norm subgroup with `I^S` is equivalent to taking
norms of ideals upstairs prime to the primes above `S`, since prime norms at
different base primes have disjoint support. -/
def idealNormSubgroup (L : ANExt K)
    (S : Finset (HeightOneSpectrum (𝓞 K))) :
    Subgroup (IdealsPrimeTo (𝓞 K) K S) :=
  L.totalIdealSubgroup.comap (IdealsPrimeTo (𝓞 K) K S).subtype

/-- Arithmetic Frobenius at a prime above an unramified base prime. -/
def PAbove.arithmeticFrobenius
    (L : ANExt K) (P : L.PAbove)
    (_hP : Algebra.IsUnramifiedAt (𝓞 K) P.upstairs.asIdeal) :
    Gal(L.carrier/K) := by
  letI : P.upstairs.asIdeal.LiesOver P.downstairs.asIdeal := P.liesOver
  letI : Algebra.IsUnramifiedAt (𝓞 K) P.upstairs.asIdeal := _hP
  letI : MulSemiringAction Gal(L.carrier/K) (𝓞 L.carrier) :=
    IsIntegralClosure.MulSemiringAction (𝓞 K) K L.carrier (𝓞 L.carrier)
  letI : IsGaloisGroup Gal(L.carrier/K) (𝓞 K) (𝓞 L.carrier) :=
    IsGaloisGroup.of_isFractionRing Gal(L.carrier/K)
      (𝓞 K) (𝓞 L.carrier) K L.carrier
  exact arithFrobAt (𝓞 K) Gal(L.carrier/K) P.upstairs.asIdeal

/-- The finite primes ramified in `L/K`. -/
def RamifiedPrimes (L : ANExt K) :
    Set (HeightOneSpectrum (𝓞 K)) :=
  {p | ∃ P : L.PAbove, P.downstairs = p ∧
      ¬Algebra.IsUnramifiedAt (𝓞 K) P.upstairs.asIdeal}

/-- `L/K` is unramified away from the finite and infinite primes occurring
in `m`. -/
def IsUnramifiedOutside (L : ANExt K)
    (m : Modulus K) : Prop :=
  (∀ P : L.PAbove, P.downstairs ∉ m.finiteSupport →
    Algebra.IsUnramifiedAt (𝓞 K) P.upstairs.asIdeal) ∧
  ∀ w : RealInfinitePlace K, w ∉ m.infinite →
    w.1.IsUnramifiedIn L.carrier

/-- The support of `m` is exactly the set of finite and infinite primes
ramified in `L/K`. -/
def ExactRamificationSupport
    (L : ANExt K) (m : Modulus K) : Prop :=
  L.RamifiedPrimes = (m.finiteSupport : Set _) ∧
    ∀ w : RealInfinitePlace K,
      w ∈ m.infinite ↔ ¬w.1.IsUnramifiedIn L.carrier

end ANExt

variable (K)

/-- Finite congruence to `1` for a field element.  The separate equality
case gives the zero difference its usual infinite valuation. -/
def CongruentOneFinite
    (m : Modulus K) (x : Kˣ) : Prop :=
  x = 1 ∨ ∀ p : HeightOneSpectrum (𝓞 K), p ∈ m.finiteSupport →
    (m.finite p : ℤ) ≤
      FractionalIdeal.count K p
        (FractionalIdeal.spanSingleton (𝓞 K)⁰ ((x : K) - 1))

/-- The elements `K_{m,1}` used to define the ray principal subgroup. -/
def IsRayElement (m : Modulus K)
    (x : ElementsPrimeTo (𝓞 K) K m.finiteSupport) : Prop :=
  CongruentOneFinite K m x.1 ∧
    Modulus.PositiveInfinity (K := K) m (x.1 : K)

/-- The subgroup `i(K_{m,1})` of fractional ideals prime to the modulus. -/
def rayPrincipalSubgroup (m : Modulus K) :
    Subgroup (IdealsPrimeTo (𝓞 K) K m.finiteSupport) :=
  Subgroup.closure
    {I | ∃ x : ElementsPrimeTo (𝓞 K) K m.finiteSupport,
      IsRayElement K m x ∧
        principalIdealPrime (𝓞 K) K m.finiteSupport x = I}

/-- A congruence subgroup modulo `m` contains the ray principal subgroup. -/
def IsCongruenceSubgroup (m : Modulus K)
    (H : Subgroup (IdealsPrimeTo (𝓞 K) K m.finiteSupport)) : Prop :=
  rayPrincipalSubgroup K m ≤ H

variable {K}

/-- A homomorphism on ideals prime to `S` is the Artin map when every prime
generator is sent to arithmetic Frobenius.  The existentially bundled
generator also records, without a separate factorization lemma, that the
prime ideal belongs to `I^S`. -/
def IsArtinMap (L : ANExt K)
    (S : Finset (HeightOneSpectrum (𝓞 K)))
    (ψ : IdealsPrimeTo (𝓞 K) K S →* Gal(L.carrier/K)) : Prop :=
  ∀ (P : L.PAbove) (_hP : P.downstairs ∉ S)
    (hunramified : Algebra.IsUnramifiedAt (𝓞 K) P.upstairs.asIdeal),
    ∃ I : IdealsPrimeTo (𝓞 K) K S,
      (I.1 : (FractionalIdeal (𝓞 K)⁰ K)ˣ) =
          ANExt.primeFractionalIdeal P.downstairs ∧
        ψ I = P.arithmeticFrobenius L hunramified

/-- The subgroup `i(K_{m,1}) Nm(I_L^m)` in Theorems V.3.5--3.6. -/
def rayNormSubgroup (L : ANExt K)
    (m : Modulus K) :
    Subgroup (IdealsPrimeTo (𝓞 K) K m.finiteSupport) :=
  rayPrincipalSubgroup K m ⊔ L.idealNormSubgroup m.finiteSupport

/-- **Theorem V.3.5 (Recip Law), statement.**

For every finite abelian extension, there is a modulus supported exactly at
the ramified finite and real infinite primes such that the Artin map induces
the displayed norm-and-ray quotient isomorphism. -/
def IdealReciprocityLaw (K : Type u) [Field K] [NumberField K] : Prop :=
  ∀ L : ANExt K,
    ∃ (m : Modulus K)
      (ψ : IdealsPrimeTo (𝓞 K) K m.finiteSupport →* Gal(L.carrier/K)),
      L.ExactRamificationSupport m ∧
      IsArtinMap L m.finiteSupport ψ ∧
      ∃ e :
          (IdealsPrimeTo (𝓞 K) K m.finiteSupport ⧸
            rayNormSubgroup L m) ≃* Gal(L.carrier/K),
        ∀ I : IdealsPrimeTo (𝓞 K) K m.finiteSupport,
          e (QuotientGroup.mk' (rayNormSubgroup L m) I) = ψ I

/-- **Theorem V.3.6 (Existence Theorem), statement.**

Every congruence subgroup is the product of the ray principal subgroup and
the ideal norm subgroup of a finite abelian extension unramified outside the
modulus. -/
def GlobalExistenceTheorem
    (K : Type u) [Field K] [NumberField K] : Prop :=
  ∀ (m : Modulus K)
    (H : Subgroup (IdealsPrimeTo (𝓞 K) K m.finiteSupport)),
    IsCongruenceSubgroup K m H →
      ∃ L : ANExt K,
        L.IsUnramifiedOutside m ∧
          H = rayNormSubgroup L m

end

end Towers.CField.ARecip
