import Towers.Group.DegreeOneMinimal
import Mathlib.LinearAlgebra.Dimension.Constructions
import Mathlib.LinearAlgebra.Dimension.RankNullity
import Mathlib.LinearAlgebra.Dimension.DivisionRing
import Mathlib.LinearAlgebra.Finsupp.Pi
import Mathlib.Algebra.Field.ZMod
import Mathlib.FieldTheory.Finiteness

namespace Towers
namespace Presentation

noncomputable section

variable (p : ℕ) (P : Presentation) [Fact p.Prime] [Fintype P.Gen]

/-- The free degree-one module has dimension equal to the number of generators. -/
theorem finrank_free_module :
    Module.finrank (ZMod p) (degreeFreeModule p P) = Fintype.card P.Gen := by
  classical
  rw [LinearEquiv.finrank_eq (Finsupp.linearEquivFunOnFinite (ZMod p) (ZMod p) P.Gen)]
  exact Module.finrank_fintype_fun_eq_card (ZMod p)

end
end Presentation
end Towers

namespace Towers
namespace Presentation

noncomputable section

variable (p : ℕ) (P : Presentation) [Fact p.Prime] [Fintype P.Gen]

/-- Rank-nullity for the degree-one presentation: quotient dimension plus relation-span dimension
is the number of generators. -/
theorem finrank_frattini_span :
    Module.finrank (ZMod p) (mFAdditi p P.Group) +
      Module.finrank (ZMod p) (degreeRelatorSpan p P) = Fintype.card P.Gen := by
  classical
  rw [← finrank_free_module (p := p) (P := P)]
  rw [← LinearEquiv.finrank_eq (degreeRelationFrattini p P)]
  exact Submodule.finrank_quotient_add_finrank (degreeRelatorSpan p P)

end
end Presentation
end Towers

namespace Towers
namespace Presentation

noncomputable section

variable (p : ℕ) (P : Presentation) [Fact p.Prime] [Fintype P.Gen]

/-- In a degree-one minimal finite-generator presentation, the Frattini quotient dimension is
exactly the number of generators. -/
theorem finrank_frattini_minimal (h : degreeOneMinimal p P) :
    Module.finrank (ZMod p) (mFAdditi p P.Group) = Fintype.card P.Gen := by
  classical
  have hs : degreeRelatorSpan p P = ⊥ :=
    (degree_minimal_bot p P).1 h
  have hf := finrank_frattini_span (p := p) (P := P)
  rw [hs] at hf
  simpa using hf

end
end Presentation
end Towers

namespace Towers
namespace Presentation

noncomputable section

variable (p : ℕ) (P : Presentation) [Fact p.Prime] [Fintype P.Gen]

/-- For finite-generator presentations, degree-one minimality is equivalent to the expected
Frattini quotient dimension. -/
theorem minimal_frattini_card :
    degreeOneMinimal p P ↔
      Module.finrank (ZMod p) (mFAdditi p P.Group) = Fintype.card P.Gen := by
  constructor
  · exact finrank_frattini_minimal p P
  · intro hdim
    have hf := finrank_frattini_span (p := p) (P := P)
    rw [hdim] at hf
    have hzero : Module.finrank (ZMod p) (degreeRelatorSpan p P) = 0 := by
      omega
    have hs : degreeRelatorSpan p P = ⊥ := by
      exact (Submodule.finrank_eq_zero).1 hzero
    exact (degree_minimal_bot p P).2 hs

end
end Presentation
end Towers

namespace Towers
namespace Presentation

noncomputable section

variable (p : ℕ) (P : Presentation) [Fact p.Prime]

/-- Relator span can equivalently be generated by the bundled relator subtype. -/
theorem degree_span_range :
    degreeRelatorSpan p P =
      Submodule.span (ZMod p)
        (Set.range (fun r : P.Relator => exponentVector p P.Gen (r : P.Free))) := by
  have hset : Set.image (fun r : P.Free => exponentVector p P.Gen r) P.rels =
      Set.range (fun r : P.Relator => exponentVector p P.Gen (r : P.Free)) := by
    ext v
    constructor
    · intro hv
      rcases hv with ⟨r, hr, rfl⟩
      exact ⟨⟨r, hr⟩, rfl⟩
    · intro hv
      rcases hv with ⟨r, rfl⟩
      exact ⟨(r : P.Free), r.property, rfl⟩
  simp [degreeRelatorSpan, hset]


variable [Fintype P.Relator]

/-- The relator exponent-span has dimension at most the number of bundled relators. -/
theorem finrank_span_relators :
    Module.finrank (ZMod p) (degreeRelatorSpan p P) ≤ Fintype.card P.Relator := by
  classical
  rw [degree_span_range (p := p) (P := P)]
  exact finrank_range_le_card (R := ZMod p)
    (fun r : P.Relator => exponentVector p P.Gen (r : P.Free))

end
end Presentation
end Towers

namespace Towers
namespace Presentation

noncomputable section

variable (p : ℕ) (P : Presentation) [Fact p.Prime] [Fintype P.Gen] [Fintype P.Relator]

/-- The basic finite-relator dimension inequality: generators are bounded by degree-one
dimension plus the number of relators. -/
theorem card_frattini_relators :
    Fintype.card P.Gen ≤
      Module.finrank (ZMod p) (mFAdditi p P.Group) + Fintype.card P.Relator := by
  classical
  have hf := finrank_frattini_span (p := p) (P := P)
  have hb := finrank_span_relators (p := p) (P := P)
  omega

end
end Presentation
end Towers

namespace Towers
namespace Presentation

noncomputable section

variable (p : ℕ) (P : Presentation) [Fact p.Prime] [Fintype P.Gen] [Fintype P.Relator]

/-- Naive degree-one deficiency of a finite presentation (generators minus relators). -/
def degreeOneDeficiency : ℕ := Fintype.card P.Gen - Fintype.card P.Relator

/-- The naive deficiency is bounded above by the dimension of the degree-one quotient. -/
theorem deficiency_finrank_frattini :
    degreeOneDeficiency P ≤
      Module.finrank (ZMod p) (mFAdditi p P.Group) := by
  classical
  unfold degreeOneDeficiency
  have h := card_frattini_relators (p := p) (P := P)
  omega

end
end Presentation
end Towers

namespace Towers
namespace Presentation

noncomputable section

variable (p : ℕ) (P : Presentation) [Fact p.Prime] [Fintype P.Gen] [Fintype P.Relator]

/-- Integer-valued generator-minus-relator count, avoiding truncated subtraction. -/
def degreeEulerDeficiency : ℤ := (Fintype.card P.Gen : ℤ) - (Fintype.card P.Relator : ℤ)

/-- Integer deficiency is bounded by the degree-one quotient dimension. -/
theorem euler_deficiency_frattini :
    degreeEulerDeficiency P ≤
      (Module.finrank (ZMod p) (mFAdditi p P.Group) : ℤ) := by
  classical
  unfold degreeEulerDeficiency
  have h := card_frattini_relators (p := p) (P := P)
  omega

end
end Presentation
end Towers

namespace Towers
namespace Presentation

noncomputable section

variable (p : ℕ) (P : Presentation) [Fact p.Prime] [Fintype P.Gen] [Fintype P.Relator]

/-- Independence of the degree-one exponent vectors of the bundled relators. -/
def degreeRelatorsIndependent : Prop :=
  LinearIndependent (ZMod p) (fun r : P.Relator => exponentVector p P.Gen (r : P.Free))

omit [Fintype P.Gen] in
/-- If relator exponent vectors are independent, their span has dimension `#relators`. -/
theorem finrank_relators_independent
    (h : degreeRelatorsIndependent p P) :
    Module.finrank (ZMod p) (degreeRelatorSpan p P) = Fintype.card P.Relator := by
  classical
  rw [degree_span_range (p := p) (P := P)]
  exact finrank_span_eq_card h

/-- With independent degree-one relator vectors, rank-nullity is an exact
generator/relator count. -/
theorem finrank_frattini_independent
    (h : degreeRelatorsIndependent p P) :
    Module.finrank (ZMod p) (mFAdditi p P.Group) + Fintype.card P.Relator =
      Fintype.card P.Gen := by
  classical
  have hf := finrank_frattini_span (p := p) (P := P)
  rw [finrank_relators_independent (p := p) (P := P) h] at hf
  exact hf

end
end Presentation
end Towers

namespace Towers
namespace Presentation

open GroupAlgebra

noncomputable section

variable (p : ℕ) (P : Presentation) [Fact p.Prime]

/-- Under the reverse degree-one containment, the first Zassenhaus quotient has the same
finite dimension as the mod-`p` Frattini quotient. -/
theorem two_frattini_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group) :
    Module.finrank (ZMod p) (zTAdditi p P.Group) =
      Module.finrank (ZMod p) (mFAdditi p P.Group) := by
  rw [← LinearEquiv.finrank_eq
    (mFAdditi.zass_twolin_equivreverse p P.Group hrev)]

/-- The first layer kernel has the same finite dimension as the Frattini quotient under
the reverse degree-one containment. -/
theorem finrank_frattini_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group) :
    Module.finrank (ZMod p) (Additive (zLKern p P.Group 1)) =
      Module.finrank (ZMod p) (mFAdditi p P.Group) := by
  rw [← LinearEquiv.finrank_eq
    (mFAdditi.zasslayer_onelin_equivreverse p P.Group hrev)]

variable [Fintype P.Gen]

/-- Rank-nullity with the first Zassenhaus quotient as target, conditional on the reverse
containment `D₂ ≤ G^p [G,G]`. -/
theorem finrank_relator_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group) :
    Module.finrank (ZMod p) (zTAdditi p P.Group) +
      Module.finrank (ZMod p) (degreeRelatorSpan p P) = Fintype.card P.Gen := by
  classical
  have hf := finrank_frattini_span (p := p) (P := P)
  have he := two_frattini_reverse (p := p) (P := P) hrev
  rw [he]
  exact hf

/-- Rank-nullity with the first layer kernel as target, conditional on the reverse
containment `D₂ ≤ G^p [G,G]`. -/
theorem finrank_span_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group) :
    Module.finrank (ZMod p) (Additive (zLKern p P.Group 1)) +
      Module.finrank (ZMod p) (degreeRelatorSpan p P) = Fintype.card P.Gen := by
  classical
  have hf := finrank_frattini_span (p := p) (P := P)
  have he := finrank_frattini_reverse (p := p) (P := P) hrev
  rw [he]
  exact hf

/-- Conditional finite-dimensional criterion for degree-one minimality using `G/D₂`. -/
theorem minimal_finrank_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group) :
    degreeOneMinimal p P ↔
      Module.finrank (ZMod p) (zTAdditi p P.Group) =
        Fintype.card P.Gen := by
  constructor
  · intro h
    have hf := finrank_frattini_minimal (p := p) (P := P) h
    rw [two_frattini_reverse (p := p) (P := P) hrev]
    exact hf
  · intro hz
    apply (minimal_frattini_card (p := p) (P := P)).2
    rw [← two_frattini_reverse (p := p) (P := P) hrev]
    exact hz

/-- Conditional finite-dimensional criterion for degree-one minimality using the first
Zassenhaus layer kernel. -/
theorem degree_minimal_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group) :
    degreeOneMinimal p P ↔
      Module.finrank (ZMod p) (Additive (zLKern p P.Group 1)) =
        Fintype.card P.Gen := by
  constructor
  · intro h
    have hf := finrank_frattini_minimal (p := p) (P := P) h
    rw [finrank_frattini_reverse (p := p) (P := P) hrev]
    exact hf
  · intro hz
    apply (minimal_frattini_card (p := p) (P := P)).2
    rw [← finrank_frattini_reverse (p := p) (P := P) hrev]
    exact hz

variable [Fintype P.Relator]

/-- The naive deficiency is bounded by the dimension of the first Zassenhaus quotient,
under the reverse degree-one containment. -/
theorem deficiency_two_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group) :
    degreeOneDeficiency P ≤
      Module.finrank (ZMod p) (zTAdditi p P.Group) := by
  classical
  have h := deficiency_finrank_frattini (p := p) (P := P)
  have he := two_frattini_reverse (p := p) (P := P) hrev
  omega

/-- Integer deficiency is bounded by the dimension of the first Zassenhaus quotient,
under the reverse degree-one containment. -/
theorem euler_deficiency_finrank
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group) :
    degreeEulerDeficiency P ≤
      (Module.finrank (ZMod p) (zTAdditi p P.Group) : ℤ) := by
  classical
  have h := euler_deficiency_frattini (p := p) (P := P)
  have he := two_frattini_reverse (p := p) (P := P) hrev
  omega

/-- The naive deficiency is bounded by the dimension of the first Zassenhaus layer kernel,
under the reverse degree-one containment. -/
theorem deficiency_finrank_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group) :
    degreeOneDeficiency P ≤
      Module.finrank (ZMod p) (Additive (zLKern p P.Group 1)) := by
  classical
  have h := deficiency_finrank_frattini (p := p) (P := P)
  have he := finrank_frattini_reverse (p := p) (P := P) hrev
  omega

/-- Integer deficiency is bounded by the dimension of the first Zassenhaus layer kernel,
under the reverse degree-one containment. -/
theorem degree_euler_deficiency
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group) :
    degreeEulerDeficiency P ≤
      (Module.finrank (ZMod p) (Additive (zLKern p P.Group 1)) : ℤ) := by
  classical
  have h := euler_deficiency_frattini (p := p) (P := P)
  have he := finrank_frattini_reverse (p := p) (P := P) hrev
  omega

/-- With independent degree-one relator vectors, the conditional Zassenhaus quotient
rank-nullity formula has the relator count in place of the relator-span dimension. -/
theorem card_independent_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group)
    (h : degreeRelatorsIndependent p P) :
    Module.finrank (ZMod p) (zTAdditi p P.Group) +
      Fintype.card P.Relator = Fintype.card P.Gen := by
  classical
  have hf := finrank_relator_reverse (p := p) (P := P) hrev
  rw [finrank_relators_independent (p := p) (P := P) h] at hf
  exact hf

/-- With independent degree-one relator vectors, the conditional first-layer rank-nullity
formula has the relator count in place of the relator-span dimension. -/
theorem finrank_independent_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group)
    (h : degreeRelatorsIndependent p P) :
    Module.finrank (ZMod p) (Additive (zLKern p P.Group 1)) +
      Fintype.card P.Relator = Fintype.card P.Gen := by
  classical
  have hf := finrank_span_reverse (p := p) (P := P) hrev
  rw [finrank_relators_independent (p := p) (P := P) h] at hf
  exact hf

end
end Presentation
end Towers

namespace Towers
namespace Presentation

open GroupAlgebra

noncomputable section

variable (p : ℕ) (P : Presentation) [Fact p.Prime] [Fintype P.Gen] [Fintype P.Relator]

/-- Under independence of degree-one relator vectors, the integer Euler deficiency is exactly
 the Frattini quotient dimension. -/
theorem finrank_deficiency_independent
    (h : degreeRelatorsIndependent p P) :
    (Module.finrank (ZMod p) (mFAdditi p P.Group) : ℤ) =
      degreeEulerDeficiency P := by
  classical
  unfold degreeEulerDeficiency
  have hf := finrank_frattini_independent (p := p) (P := P) h
  omega

/-- Conditional Zassenhaus-quotient version of the Euler deficiency equality under
independent degree-one relator vectors. -/
theorem euler_deficiency_independent
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group)
    (h : degreeRelatorsIndependent p P) :
    (Module.finrank (ZMod p) (zTAdditi p P.Group) : ℤ) =
      degreeEulerDeficiency P := by
  classical
  unfold degreeEulerDeficiency
  have hf := card_independent_reverse
    (p := p) (P := P) hrev h
  omega

/-- Conditional first-layer version of the Euler deficiency equality under independent
 degree-one relator vectors. -/
theorem euler_deficiency_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group)
    (h : degreeRelatorsIndependent p P) :
    (Module.finrank (ZMod p) (Additive (zLKern p P.Group 1)) : ℤ) =
      degreeEulerDeficiency P := by
  classical
  unfold degreeEulerDeficiency
  have hf := finrank_independent_reverse
    (p := p) (P := P) hrev h
  omega

end
end Presentation
end Towers

namespace Towers
namespace Presentation

open GroupAlgebra

noncomputable section

variable (p : ℕ) (P : Presentation) [Fact p.Prime] [Fintype P.Gen] [Fintype P.Relator]

/-- Conditional generator bound using the first Zassenhaus quotient. -/
theorem card_generators_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group) :
    Fintype.card P.Gen ≤
      Module.finrank (ZMod p) (zTAdditi p P.Group) +
        Fintype.card P.Relator := by
  classical
  have hf := finrank_relator_reverse
    (p := p) (P := P) hrev
  have hb := finrank_span_relators (p := p) (P := P)
  omega

/-- Conditional generator bound using the first Zassenhaus layer kernel. -/
theorem card_relators_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group) :
    Fintype.card P.Gen ≤
      Module.finrank (ZMod p) (Additive (zLKern p P.Group 1)) +
        Fintype.card P.Relator := by
  classical
  have hf := finrank_span_reverse
    (p := p) (P := P) hrev
  have hb := finrank_span_relators (p := p) (P := P)
  omega

end
end Presentation
end Towers

namespace Towers
namespace Presentation

open GroupAlgebra

noncomputable section

variable (p : ℕ) (P : Presentation) [Fact p.Prime] [Fintype P.Gen] [Fintype P.Relator]

/-- Under independent degree-one relators, the truncated deficiency equals the Frattini
quotient dimension. -/
theorem deficiency_frattini_independent
    (h : degreeRelatorsIndependent p P) :
    degreeOneDeficiency P =
      Module.finrank (ZMod p) (mFAdditi p P.Group) := by
  classical
  unfold degreeOneDeficiency
  have hf := finrank_frattini_independent (p := p) (P := P) h
  omega

/-- Conditional first-Zassenhaus-quotient version of the truncated deficiency equality. -/
theorem degree_deficiency_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group)
    (h : degreeRelatorsIndependent p P) :
    degreeOneDeficiency P =
      Module.finrank (ZMod p) (zTAdditi p P.Group) := by
  classical
  unfold degreeOneDeficiency
  have hf := card_independent_reverse
    (p := p) (P := P) hrev h
  omega

/-- Conditional first-layer version of the truncated deficiency equality. -/
theorem deficiency_independent_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group)
    (h : degreeRelatorsIndependent p P) :
    degreeOneDeficiency P =
      Module.finrank (ZMod p) (Additive (zLKern p P.Group 1)) := by
  classical
  unfold degreeOneDeficiency
  have hf := finrank_independent_reverse
    (p := p) (P := P) hrev h
  omega

end
end Presentation
end Towers

namespace Towers
namespace Presentation

noncomputable section

variable (p : ℕ) (P : Presentation) [Fact p.Prime] [Fintype P.Gen] [Fintype P.Relator]

omit [Fintype P.Gen] in
/-- A finite degree-one minimal presentation with independent degree-one relator vectors has
no bundled relators (in cardinality). -/
theorem card_minimal_independent
    (hmin : degreeOneMinimal p P) (hind : degreeRelatorsIndependent p P) :
    Fintype.card P.Relator = 0 := by
  classical
  have hs := relator_bot_minimal (p := p) (P := P) hmin
  have hf := finrank_relators_independent (p := p) (P := P) hind
  rw [hs] at hf
  simpa using hf.symm

/-- In the same situation, the naive deficiency is just the number of generators. -/
theorem deficiency_minimal_independent
    (hmin : degreeOneMinimal p P) (hind : degreeRelatorsIndependent p P) :
    degreeOneDeficiency P = Fintype.card P.Gen := by
  classical
  unfold degreeOneDeficiency
  have hc := card_minimal_independent
    (p := p) (P := P) hmin hind
  omega

end
end Presentation
end Towers


namespace Towers
namespace Presentation

noncomputable section

variable (p : ℕ) (P : Presentation)

/-- The relation quotient of a finite-generator presentation is finite as a type. -/
noncomputable instance dRQuot.fintype [Fact p.Prime] [Fintype P.Gen] :
    Fintype (dRQuot p P) := by
  infer_instance

/-- The mod-`p` Frattini quotient of a finitely generated presentation is finite (additive form). -/
noncomputable instance pFAdditi.fintype [Fact p.Prime] [Fintype P.Gen] :
    Fintype (mFAdditi p P.Group) := by
  classical
  exact Fintype.ofEquiv (dRQuot p P)
    (degreeRelationFrattini p P).toEquiv

/-- The mod-`p` Frattini quotient of a finitely generated presentation is finite. -/
noncomputable instance pFQuot.fintype [Fact p.Prime] [Fintype P.Gen] :
    Fintype (mFQuot p P.Group) := by
  classical
  exact Fintype.ofEquiv (mFAdditi p P.Group) Additive.ofMul.symm

/-- Cardinality of a finitely generated presented Frattini quotient, in terms of its finrank. -/
@[simp] theorem card_presented_additive [Fact p.Prime] [Fintype P.Gen] :
    Fintype.card (mFAdditi p P.Group) =
      p ^ Module.finrank (ZMod p) (mFAdditi p P.Group) := by
  classical
  rw [Module.card_eq_pow_finrank (K := ZMod p)
    (V := mFAdditi p P.Group)]
  rw [ZMod.card]

/-- Multiplicative form of the cardinality formula for a finitely generated presentation. -/
@[simp] theorem card_presented_frattini [Fact p.Prime] [Fintype P.Gen] :
    Fintype.card (mFQuot p P.Group) =
      p ^ Module.finrank (ZMod p) (mFAdditi p P.Group) := by
  classical
  calc
    Fintype.card (mFQuot p P.Group) =
        Fintype.card (mFAdditi p P.Group) :=
      Fintype.card_congr Additive.ofMul
    _ = p ^ Module.finrank (ZMod p) (mFAdditi p P.Group) :=
      card_presented_additive p P

/-- Cardinality in terms of generators minus the degree-one relator-span dimension. -/
theorem card_presented_span
    [Fact p.Prime] [Fintype P.Gen] :
    Fintype.card (mFAdditi p P.Group) =
      p ^ (Fintype.card P.Gen -
        Module.finrank (ZMod p) (degreeRelatorSpan p P)) := by
  rw [card_presented_additive]
  have h := finrank_frattini_span (p := p) (P := P)
  congr 1
  omega

/-- Multiplicative quotient cardinality in generator-minus-relator-span form. -/
theorem card_frattini_span
    [Fact p.Prime] [Fintype P.Gen] :
    Fintype.card (mFQuot p P.Group) =
      p ^ (Fintype.card P.Gen -
        Module.finrank (ZMod p) (degreeRelatorSpan p P)) := by
  rw [card_presented_frattini]
  have h := finrank_frattini_span (p := p) (P := P)
  congr 1
  omega

end
end Presentation
end Towers

namespace Towers
namespace Presentation

noncomputable section

variable (p : ℕ) (P : Presentation)

/-- If degree-one relator vectors are independent, the Frattini quotient cardinality is the
expected generator-minus-relator power. -/
theorem additive_relators_independent
    [Fact p.Prime] [Fintype P.Gen] [Fintype P.Relator]
    (h : degreeRelatorsIndependent p P) :
    Fintype.card (mFAdditi p P.Group) =
      p ^ (Fintype.card P.Gen - Fintype.card P.Relator) := by
  rw [card_presented_span]
  rw [finrank_relators_independent (p := p) (P := P) h]

/-- Multiplicative quotient version of the independent-relator cardinality formula. -/
theorem presented_frattini_independent
    [Fact p.Prime] [Fintype P.Gen] [Fintype P.Relator]
    (h : degreeRelatorsIndependent p P) :
    Fintype.card (mFQuot p P.Group) =
      p ^ (Fintype.card P.Gen - Fintype.card P.Relator) := by
  rw [card_frattini_span]
  rw [finrank_relators_independent (p := p) (P := P) h]

/-- In the degree-one minimal case, the Frattini quotient has cardinality `p ^ #Gen`. -/
theorem presented_frattini_minimal
    [Fact p.Prime] [Fintype P.Gen] (h : degreeOneMinimal p P) :
    Fintype.card (mFAdditi p P.Group) = p ^ Fintype.card P.Gen := by
  rw [card_presented_additive]
  rw [finrank_frattini_minimal (p := p) (P := P) h]

/-- Multiplicative quotient version of the degree-one minimal cardinality formula. -/
theorem card_presented_minimal
    [Fact p.Prime] [Fintype P.Gen] (h : degreeOneMinimal p P) :
    Fintype.card (mFQuot p P.Group) = p ^ Fintype.card P.Gen := by
  rw [card_presented_frattini]
  rw [finrank_frattini_minimal (p := p) (P := P) h]

end
end Presentation
end Towers

namespace Towers
namespace Presentation

noncomputable section

variable (p : ℕ) (P : Presentation)

/-- `Nat.card` version of the finite presented Frattini quotient cardinality formula. -/
theorem nat_presented_frattini [Fact p.Prime] [Finite P.Gen] :
    Nat.card (mFQuot p P.Group) =
      p ^ Module.finrank (ZMod p) (mFAdditi p P.Group) := by
  classical
  letI := Fintype.ofFinite P.Gen
  rw [Nat.card_eq_fintype_card]
  exact card_presented_frattini p P

/-- `Nat.card` version for the additive Frattini quotient. -/
theorem nat_presented_additive [Fact p.Prime] [Finite P.Gen] :
    Nat.card (mFAdditi p P.Group) =
      p ^ Module.finrank (ZMod p) (mFAdditi p P.Group) := by
  classical
  letI := Fintype.ofFinite P.Gen
  rw [Nat.card_eq_fintype_card]
  exact card_presented_additive p P

/-- `Nat.card` generator-minus-relator-span formula for the multiplicative quotient. -/
theorem presented_frattini_span
    [Fact p.Prime] [Fintype P.Gen] :
    Nat.card (mFQuot p P.Group) =
      p ^ (Fintype.card P.Gen -
        Module.finrank (ZMod p) (degreeRelatorSpan p P)) := by
  rw [Nat.card_eq_fintype_card]
  exact card_frattini_span p P

end
end Presentation
end Towers

namespace Towers
namespace Presentation

open GroupAlgebra

noncomputable section

variable (p : ℕ) (P : Presentation) [Fact p.Prime] [Finite P.Gen]

/-- `Nat.card` of the first Zassenhaus quotient, transported across the conditional
Frattini/Zassenhaus equivalence.  This form keeps the exponent written with the Frattini
quotient dimension. -/
theorem card_additive_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group) :
    Nat.card (zTAdditi p P.Group) =
      p ^ Module.finrank (ZMod p) (mFAdditi p P.Group) := by
  classical
  have hc := Nat.card_congr
    (mFAdditi.zass_twolin_equivreverse p P.Group hrev).toEquiv.symm
  rw [hc]
  exact nat_presented_additive p P

/-- Intrinsic `Nat.card = p ^ finrank` formula for the first Zassenhaus quotient under the
reverse degree-one containment. -/
theorem nat_finrank_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group) :
    Nat.card (zTAdditi p P.Group) =
      p ^ Module.finrank (ZMod p) (zTAdditi p P.Group) := by
  classical
  rw [card_additive_reverse (p := p) (P := P) hrev]
  rw [← two_frattini_reverse (p := p) (P := P) hrev]

/-- Multiplicative type-synonym version of the conditional `Nat.card` formula for the first
Zassenhaus quotient. -/
theorem nat_zassenhaus_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group) :
    Nat.card (zQuot p P.Group 2) =
      p ^ Module.finrank (ZMod p) (mFAdditi p P.Group) := by
  classical
  have hsyn : Nat.card (zQuot p P.Group 2) =
      Nat.card (zTAdditi p P.Group) :=
    Nat.card_congr (Additive.ofMul (α := zQuot p P.Group 2))
  rw [hsyn]
  exact card_additive_reverse (p := p) (P := P) hrev

/-- `Nat.card` of the first Zassenhaus layer kernel, transported across the conditional
Frattini/layer equivalence. -/
theorem layer_additive_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group) :
    Nat.card (Additive (zLKern p P.Group 1)) =
      p ^ Module.finrank (ZMod p) (mFAdditi p P.Group) := by
  classical
  have hc := Nat.card_congr
    (mFAdditi.zasslayer_onelin_equivreverse p P.Group hrev).toEquiv.symm
  rw [hc]
  exact nat_presented_additive p P

/-- Intrinsic `Nat.card = p ^ finrank` formula for the first Zassenhaus layer kernel under
the reverse degree-one containment. -/
theorem additive_finrank_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group) :
    Nat.card (Additive (zLKern p P.Group 1)) =
      p ^ Module.finrank (ZMod p) (Additive (zLKern p P.Group 1)) := by
  classical
  rw [layer_additive_reverse (p := p) (P := P) hrev]
  rw [← finrank_frattini_reverse (p := p) (P := P) hrev]

end
end Presentation
end Towers

namespace Towers
namespace Presentation

open GroupAlgebra

noncomputable section

variable (p : ℕ) (P : Presentation) [Fact p.Prime] [Fintype P.Gen]

/-- Generator-minus-relator-span `Nat.card` formula for the conditional first Zassenhaus
quotient. -/
theorem nat_additive_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group) :
    Nat.card (zTAdditi p P.Group) =
      p ^ (Fintype.card P.Gen -
        Module.finrank (ZMod p) (degreeRelatorSpan p P)) := by
  rw [card_additive_reverse (p := p) (P := P) hrev]
  have h := finrank_frattini_span (p := p) (P := P)
  congr 1
  omega

/-- Multiplicative type-synonym version of the generator-minus-relator-span formula. -/
theorem nat_sub_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group) :
    Nat.card (zQuot p P.Group 2) =
      p ^ (Fintype.card P.Gen -
        Module.finrank (ZMod p) (degreeRelatorSpan p P)) := by
  rw [nat_zassenhaus_reverse (p := p) (P := P) hrev]
  have h := finrank_frattini_span (p := p) (P := P)
  congr 1
  omega

/-- Generator-minus-relator-span `Nat.card` formula for the conditional first Zassenhaus
layer kernel. -/
theorem nat_span_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group) :
    Nat.card (Additive (zLKern p P.Group 1)) =
      p ^ (Fintype.card P.Gen -
        Module.finrank (ZMod p) (degreeRelatorSpan p P)) := by
  rw [layer_additive_reverse (p := p) (P := P) hrev]
  have h := finrank_frattini_span (p := p) (P := P)
  congr 1
  omega

end
end Presentation
end Towers

namespace Towers
namespace Presentation

open GroupAlgebra

noncomputable section

variable (p : ℕ) (P : Presentation) [Fact p.Prime] [Finite P.Gen]

/-- Conditional finiteness of the first Zassenhaus quotient, transported from the finitely
generated presented Frattini quotient. -/
theorem two_additive_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group) :
    Finite (zTAdditi p P.Group) := by
  classical
  letI := Fintype.ofFinite P.Gen
  letI : Fintype (zTAdditi p P.Group) :=
    Fintype.ofEquiv (mFAdditi p P.Group)
      (mFAdditi.zass_twolin_equivreverse p P.Group hrev).toEquiv
  infer_instance

/-- Multiplicative type-synonym version of conditional finiteness for the first Zassenhaus
quotient. -/
theorem finite_two_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group) :
    Finite (zQuot p P.Group 2) := by
  classical
  haveI := two_additive_reverse (p := p) (P := P) hrev
  exact Finite.of_equiv (zTAdditi p P.Group)
    (Additive.ofMul (α := zQuot p P.Group 2)).symm

/-- Conditional finiteness of the first Zassenhaus layer kernel. -/
theorem zassenhaus_additive_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group) :
    Finite (Additive (zLKern p P.Group 1)) := by
  classical
  letI := Fintype.ofFinite P.Gen
  letI : Fintype (Additive (zLKern p P.Group 1)) :=
    Fintype.ofEquiv (mFAdditi p P.Group)
      (mFAdditi.zasslayer_onelin_equivreverse p P.Group hrev).toEquiv
  infer_instance

end
end Presentation
end Towers

namespace Towers
namespace Presentation

open GroupAlgebra

noncomputable section

variable (p : ℕ) (P : Presentation) [Fact p.Prime] [Finite P.Gen]

/-- Multiplicative type-synonym version of the conditional `Nat.card` formula for the first
Zassenhaus layer kernel. -/
theorem nat_layer_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group) :
    Nat.card (zLKern p P.Group 1) =
      p ^ Module.finrank (ZMod p) (mFAdditi p P.Group) := by
  classical
  have hsyn : Nat.card (zLKern p P.Group 1) =
      Nat.card (Additive (zLKern p P.Group 1)) :=
    Nat.card_congr (Additive.ofMul (α := zLKern p P.Group 1))
  rw [hsyn]
  exact layer_additive_reverse (p := p) (P := P) hrev

/-- Multiplicative type-synonym version of conditional finiteness for the first Zassenhaus
layer kernel. -/
theorem finite_layer_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group) :
    Finite (zLKern p P.Group 1) := by
  classical
  haveI := zassenhaus_additive_reverse (p := p) (P := P) hrev
  exact Finite.of_equiv (Additive (zLKern p P.Group 1))
    (Additive.ofMul (α := zLKern p P.Group 1)).symm

end
end Presentation
end Towers

namespace Towers
namespace Presentation

open GroupAlgebra

noncomputable section

variable (p : ℕ) (P : Presentation) [Fact p.Prime] [Fintype P.Gen]

/-- Multiplicative layer-kernel version of the generator-minus-relator-span `Nat.card`
formula. -/
theorem nat_card_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group) :
    Nat.card (zLKern p P.Group 1) =
      p ^ (Fintype.card P.Gen -
        Module.finrank (ZMod p) (degreeRelatorSpan p P)) := by
  rw [nat_layer_reverse (p := p) (P := P) hrev]
  have h := finrank_frattini_span (p := p) (P := P)
  congr 1
  omega

end
end Presentation
end Towers

namespace Towers
namespace Presentation

open GroupAlgebra

noncomputable section

variable (p : ℕ) (P : Presentation) [Fact p.Prime] [Fintype P.Gen] [Fintype P.Relator]

/-- Conditional first-Zassenhaus quotient cardinality with independent degree-one relators. -/
theorem nat_independent_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group)
    (h : degreeRelatorsIndependent p P) :
    Nat.card (zTAdditi p P.Group) =
      p ^ (Fintype.card P.Gen - Fintype.card P.Relator) := by
  rw [nat_additive_reverse
    (p := p) (P := P) hrev]
  rw [finrank_relators_independent (p := p) (P := P) h]

/-- Multiplicative quotient version with independent degree-one relators. -/
theorem two_independent_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group)
    (h : degreeRelatorsIndependent p P) :
    Nat.card (zQuot p P.Group 2) =
      p ^ (Fintype.card P.Gen - Fintype.card P.Relator) := by
  rw [nat_sub_reverse
    (p := p) (P := P) hrev]
  rw [finrank_relators_independent (p := p) (P := P) h]

/-- Conditional first-layer cardinality with independent degree-one relators. -/
theorem additive_independent_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group)
    (h : degreeRelatorsIndependent p P) :
    Nat.card (Additive (zLKern p P.Group 1)) =
      p ^ (Fintype.card P.Gen - Fintype.card P.Relator) := by
  rw [nat_span_reverse
    (p := p) (P := P) hrev]
  rw [finrank_relators_independent (p := p) (P := P) h]

/-- Multiplicative first-layer version with independent degree-one relators. -/
theorem layer_independent_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group)
    (h : degreeRelatorsIndependent p P) :
    Nat.card (zLKern p P.Group 1) =
      p ^ (Fintype.card P.Gen - Fintype.card P.Relator) := by
  rw [nat_card_reverse
    (p := p) (P := P) hrev]
  rw [finrank_relators_independent (p := p) (P := P) h]

end
end Presentation
end Towers

namespace Towers
namespace Presentation

open GroupAlgebra

noncomputable section

variable (p : ℕ) (P : Presentation) [Fact p.Prime] [Fintype P.Gen]

/-- Conditional first-Zassenhaus quotient cardinality for degree-one minimal presentations. -/
theorem nat_minimal_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group)
    (h : degreeOneMinimal p P) :
    Nat.card (zTAdditi p P.Group) = p ^ Fintype.card P.Gen := by
  rw [card_additive_reverse (p := p) (P := P) hrev]
  rw [finrank_frattini_minimal (p := p) (P := P) h]

/-- Multiplicative quotient version for degree-one minimal presentations. -/
theorem zassenhaus_minimal_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group)
    (h : degreeOneMinimal p P) :
    Nat.card (zQuot p P.Group 2) = p ^ Fintype.card P.Gen := by
  rw [nat_zassenhaus_reverse (p := p) (P := P) hrev]
  rw [finrank_frattini_minimal (p := p) (P := P) h]

/-- Conditional first-layer cardinality for degree-one minimal presentations. -/
theorem card_minimal_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group)
    (h : degreeOneMinimal p P) :
    Nat.card (Additive (zLKern p P.Group 1)) = p ^ Fintype.card P.Gen := by
  rw [layer_additive_reverse (p := p) (P := P) hrev]
  rw [finrank_frattini_minimal (p := p) (P := P) h]

/-- Multiplicative first-layer version for degree-one minimal presentations. -/
theorem one_minimal_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group)
    (h : degreeOneMinimal p P) :
    Nat.card (zLKern p P.Group 1) = p ^ Fintype.card P.Gen := by
  rw [nat_layer_reverse (p := p) (P := P) hrev]
  rw [finrank_frattini_minimal (p := p) (P := P) h]

end
end Presentation
end Towers

namespace Towers
namespace Presentation

noncomputable section

variable (p : ℕ) (P : Presentation) [Fact p.Prime]

/-- The degree-one relation quotient has the same finrank as the presented Frattini quotient. -/
theorem finrank_relation_frattini :
    Module.finrank (ZMod p) (dRQuot p P) =
      Module.finrank (ZMod p) (mFAdditi p P.Group) := by
  exact (degreeRelationFrattini p P).finrank_eq

variable [Fintype P.Gen]

/-- Cardinality of the degree-one relation quotient in terms of its own finrank. -/
@[simp] theorem card_degree_relation :
    Fintype.card (dRQuot p P) =
      p ^ Module.finrank (ZMod p) (dRQuot p P) := by
  classical
  rw [Module.card_eq_pow_finrank (K := ZMod p) (V := dRQuot p P)]
  rw [ZMod.card]

/-- Cardinality of the degree-one relation quotient in Frattini-finrank form. -/
theorem card_frattini_finrank :
    Fintype.card (dRQuot p P) =
      p ^ Module.finrank (ZMod p) (mFAdditi p P.Group) := by
  rw [card_degree_relation]
  rw [finrank_relation_frattini (p := p) (P := P)]

/-- Cardinality of the relation quotient in generator-minus-relator-span form. -/
theorem card_relation_span :
    Fintype.card (dRQuot p P) =
      p ^ (Fintype.card P.Gen -
        Module.finrank (ZMod p) (degreeRelatorSpan p P)) := by
  rw [card_frattini_finrank]
  have h := finrank_frattini_span (p := p) (P := P)
  congr 1
  omega

end
end Presentation
end Towers

namespace Towers
namespace Presentation

noncomputable section

variable (p : ℕ) (P : Presentation) [Fact p.Prime] [Finite P.Gen]

/-- Finiteness of the degree-one relation quotient for finite generator types. -/
theorem degree_relation_quotient :
    Finite (dRQuot p P) := by
  classical
  letI := Fintype.ofFinite P.Gen
  letI : Fintype (dRQuot p P) := dRQuot.fintype p P
  infer_instance

/-- `Nat.card` of the degree-one relation quotient in Frattini-finrank form. -/
theorem nat_card_relation :
    Nat.card (dRQuot p P) =
      p ^ Module.finrank (ZMod p) (mFAdditi p P.Group) := by
  classical
  letI := Fintype.ofFinite P.Gen
  rw [Nat.card_eq_fintype_card]
  exact card_frattini_finrank p P

/-- Finiteness of the additive presented Frattini quotient for finite generator types. -/
theorem presented_frattini_additive :
    Finite (mFAdditi p P.Group) := by
  classical
  letI := Fintype.ofFinite P.Gen
  letI : Fintype (mFAdditi p P.Group) := pFAdditi.fintype p P
  infer_instance

/-- Finiteness of the multiplicative presented Frattini quotient for finite generator types. -/
theorem presented_frattini_quotient :
    Finite (mFQuot p P.Group) := by
  classical
  letI := Fintype.ofFinite P.Gen
  letI : Fintype (mFQuot p P.Group) := pFQuot.fintype p P
  infer_instance

end
end Presentation
end Towers

namespace Towers
namespace Presentation

noncomputable section

variable (p : ℕ) (P : Presentation) [Fact p.Prime] [Fintype P.Gen]

/-- Relation-quotient cardinality for degree-one minimal presentations. -/
theorem card_relation_minimal
    (h : degreeOneMinimal p P) :
    Fintype.card (dRQuot p P) = p ^ Fintype.card P.Gen := by
  rw [card_frattini_finrank]
  rw [finrank_frattini_minimal (p := p) (P := P) h]

variable [Fintype P.Relator]

/-- Relation-quotient cardinality for independent degree-one relator vectors. -/
theorem card_relators_independent
    (h : degreeRelatorsIndependent p P) :
    Fintype.card (dRQuot p P) =
      p ^ (Fintype.card P.Gen - Fintype.card P.Relator) := by
  rw [card_relation_span]
  rw [finrank_relators_independent (p := p) (P := P) h]

end
end Presentation
end Towers

namespace Towers
namespace Presentation

open GroupAlgebra

noncomputable section

variable (p : ℕ) (P : Presentation) [Fact p.Prime]

/-- Conditional finrank transport from the degree-one relation quotient to the first
Zassenhaus quotient. -/
theorem finrank_degree_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group) :
    Module.finrank (ZMod p) (dRQuot p P) =
      Module.finrank (ZMod p) (zTAdditi p P.Group) := by
  exact (degreeLinearReverse p P hrev).finrank_eq

/-- Conditional finrank transport from the degree-one relation quotient to the first
Zassenhaus layer kernel. -/
theorem finrank_relation_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group) :
    Module.finrank (ZMod p) (dRQuot p P) =
      Module.finrank (ZMod p) (Additive (zLKern p P.Group 1)) := by
  exact (degreeRelationReverse p P hrev).finrank_eq

omit [Fact p.Prime] in
/-- `Nat.card` transport from the relation quotient to the first Zassenhaus quotient. -/
theorem nat_two_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group) :
    Nat.card (dRQuot p P) =
      Nat.card (zTAdditi p P.Group) := by
  exact Nat.card_congr
    (degreeLinearReverse p P hrev).toEquiv

/-- `Nat.card` transport from the relation quotient to the first Zassenhaus layer kernel. -/
theorem nat_degree_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group) :
    Nat.card (dRQuot p P) =
      Nat.card (Additive (zLKern p P.Group 1)) := by
  exact Nat.card_congr
    (degreeRelationReverse p P hrev).toEquiv

end
end Presentation
end Towers

namespace Towers
namespace Presentation

open GroupAlgebra

noncomputable section

variable (p : ℕ) (P : Presentation) [Fact p.Prime]

omit [Fact p.Prime] in
/-- `Nat.card` transport from the relation quotient to the multiplicative first Zassenhaus
quotient. -/
theorem card_relation_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group) :
    Nat.card (dRQuot p P) =
      Nat.card (zQuot p P.Group 2) := by
  exact Nat.card_congr <|
    (degreeLinearReverse p P hrev).toEquiv.trans Additive.toMul

/-- `Nat.card` transport from the relation quotient to the multiplicative first Zassenhaus
layer kernel. -/
theorem nat_relation_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group) :
    Nat.card (dRQuot p P) =
      Nat.card (zLKern p P.Group 1) := by
  exact Nat.card_congr <|
    (degreeRelationReverse p P hrev).toEquiv.trans Additive.toMul

end
end Presentation
end Towers

namespace Towers
namespace Presentation

open GroupAlgebra

noncomputable section

variable (p : ℕ) (P : Presentation) [Fact p.Prime] [Fintype P.Gen]

/-- Canonical fintype structure on the conditional first Zassenhaus quotient (additive form). -/
@[reducible] noncomputable def fintype_zassenhaus_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group) :
    Fintype (zTAdditi p P.Group) := by
  exact Fintype.ofEquiv (mFAdditi p P.Group)
    (mFAdditi.zass_twolin_equivreverse p P.Group hrev).toEquiv

/-- Canonical fintype structure on the conditional first Zassenhaus quotient. -/
@[reducible] noncomputable def zassenhaus_two_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group) :
    Fintype (zQuot p P.Group 2) := by
  letI : Fintype (zTAdditi p P.Group) :=
    fintype_zassenhaus_reverse p P hrev
  exact Fintype.ofEquiv (zTAdditi p P.Group)
    (Additive.ofMul (α := zQuot p P.Group 2)).symm

/-- Canonical fintype structure on the conditional first Zassenhaus layer kernel (additive form). -/
@[reducible] noncomputable def fintype_one_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group) :
    Fintype (Additive (zLKern p P.Group 1)) := by
  exact Fintype.ofEquiv (mFAdditi p P.Group)
    (mFAdditi.zasslayer_onelin_equivreverse p P.Group hrev).toEquiv

/-- Canonical fintype structure on the conditional first Zassenhaus layer kernel. -/
@[reducible] noncomputable def zassenhaus_layer_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group) :
    Fintype (zLKern p P.Group 1) := by
  letI : Fintype (Additive (zLKern p P.Group 1)) :=
    fintype_one_reverse p P hrev
  exact Fintype.ofEquiv (Additive (zLKern p P.Group 1))
    (Additive.ofMul (α := zLKern p P.Group 1)).symm

/-- `Fintype.card` form of the conditional first Zassenhaus quotient cardinality. -/
theorem fintype_two_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group) :
    @Fintype.card (zTAdditi p P.Group)
        (fintype_zassenhaus_reverse p P hrev) =
      p ^ Module.finrank (ZMod p) (mFAdditi p P.Group) := by
  have h := card_additive_reverse (p := p) (P := P) hrev
  rw [@Nat.card_eq_fintype_card (zTAdditi p P.Group)
    (fintype_zassenhaus_reverse p P hrev)] at h
  exact h

/-- `Fintype.card` form of the conditional multiplicative first Zassenhaus quotient. -/
theorem fintype_quotient_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group) :
    @Fintype.card (zQuot p P.Group 2)
        (zassenhaus_two_reverse p P hrev) =
      p ^ Module.finrank (ZMod p) (mFAdditi p P.Group) := by
  have h := nat_zassenhaus_reverse (p := p) (P := P) hrev
  rw [@Nat.card_eq_fintype_card (zQuot p P.Group 2)
    (zassenhaus_two_reverse p P hrev)] at h
  exact h

/-- `Fintype.card` form of the conditional first Zassenhaus layer cardinality (additive). -/
theorem fintype_layer_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group) :
    @Fintype.card (Additive (zLKern p P.Group 1))
        (fintype_one_reverse p P hrev) =
      p ^ Module.finrank (ZMod p) (mFAdditi p P.Group) := by
  have h := layer_additive_reverse (p := p) (P := P) hrev
  rw [@Nat.card_eq_fintype_card (Additive (zLKern p P.Group 1))
    (fintype_one_reverse p P hrev)] at h
  exact h

/-- `Fintype.card` form of the conditional first Zassenhaus layer cardinality. -/
theorem card_layer_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group) :
    @Fintype.card (zLKern p P.Group 1)
        (zassenhaus_layer_reverse p P hrev) =
      p ^ Module.finrank (ZMod p) (mFAdditi p P.Group) := by
  have h := nat_layer_reverse (p := p) (P := P) hrev
  rw [@Nat.card_eq_fintype_card (zLKern p P.Group 1)
    (zassenhaus_layer_reverse p P hrev)] at h
  exact h

end
end Presentation
end Towers

namespace Towers
namespace Presentation

open GroupAlgebra

noncomputable section

variable (p : ℕ) (P : Presentation) [Fact p.Prime] [Fintype P.Gen]

/-- `Fintype.card` generator-minus-relator-span formula for the conditional first quotient. -/
theorem fintype_additive_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group) :
    @Fintype.card (zTAdditi p P.Group)
        (fintype_zassenhaus_reverse p P hrev) =
      p ^ (Fintype.card P.Gen -
        Module.finrank (ZMod p) (degreeRelatorSpan p P)) := by
  have h := nat_additive_reverse
    (p := p) (P := P) hrev
  rw [@Nat.card_eq_fintype_card (zTAdditi p P.Group)
    (fintype_zassenhaus_reverse p P hrev)] at h
  exact h

/-- Multiplicative `Fintype.card` generator-minus-relator-span formula for the first quotient. -/
theorem fintype_sub_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group) :
    @Fintype.card (zQuot p P.Group 2)
        (zassenhaus_two_reverse p P hrev) =
      p ^ (Fintype.card P.Gen -
        Module.finrank (ZMod p) (degreeRelatorSpan p P)) := by
  have h := nat_sub_reverse
    (p := p) (P := P) hrev
  rw [@Nat.card_eq_fintype_card (zQuot p P.Group 2)
    (zassenhaus_two_reverse p P hrev)] at h
  exact h

/-- `Fintype.card` generator-minus-relator-span formula for the first layer (additive). -/
theorem fintype_span_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group) :
    @Fintype.card (Additive (zLKern p P.Group 1))
        (fintype_one_reverse p P hrev) =
      p ^ (Fintype.card P.Gen -
        Module.finrank (ZMod p) (degreeRelatorSpan p P)) := by
  have h := nat_span_reverse
    (p := p) (P := P) hrev
  rw [@Nat.card_eq_fintype_card (Additive (zLKern p P.Group 1))
    (fintype_one_reverse p P hrev)] at h
  exact h

/-- Multiplicative `Fintype.card` generator-minus-relator-span formula for the first layer. -/
theorem fintype_card_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group) :
    @Fintype.card (zLKern p P.Group 1)
        (zassenhaus_layer_reverse p P hrev) =
      p ^ (Fintype.card P.Gen -
        Module.finrank (ZMod p) (degreeRelatorSpan p P)) := by
  have h := nat_card_reverse
    (p := p) (P := P) hrev
  rw [@Nat.card_eq_fintype_card (zLKern p P.Group 1)
    (zassenhaus_layer_reverse p P hrev)] at h
  exact h

end
end Presentation
end Towers

namespace Towers
namespace Presentation

open GroupAlgebra

noncomputable section

variable (p : ℕ) (P : Presentation) [Fact p.Prime] [Fintype P.Gen] [Fintype P.Relator]

/-- `Fintype.card` first-quotient formula for independent degree-one relators (additive). -/
theorem fintype_independent_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group)
    (h : degreeRelatorsIndependent p P) :
    @Fintype.card (zTAdditi p P.Group)
        (fintype_zassenhaus_reverse p P hrev) =
      p ^ (Fintype.card P.Gen - Fintype.card P.Relator) := by
  have hc := nat_independent_reverse
    (p := p) (P := P) hrev h
  rw [@Nat.card_eq_fintype_card (zTAdditi p P.Group)
    (fintype_zassenhaus_reverse p P hrev)] at hc
  exact hc

/-- `Fintype.card` first-quotient formula for independent degree-one relators. -/
theorem fintype_relators_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group)
    (h : degreeRelatorsIndependent p P) :
    @Fintype.card (zQuot p P.Group 2)
        (zassenhaus_two_reverse p P hrev) =
      p ^ (Fintype.card P.Gen - Fintype.card P.Relator) := by
  have hc := two_independent_reverse
    (p := p) (P := P) hrev h
  rw [@Nat.card_eq_fintype_card (zQuot p P.Group 2)
    (zassenhaus_two_reverse p P hrev)] at hc
  exact hc

/-- `Fintype.card` first-layer formula for independent degree-one relators (additive). -/
theorem relators_independent_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group)
    (h : degreeRelatorsIndependent p P) :
    @Fintype.card (Additive (zLKern p P.Group 1))
        (fintype_one_reverse p P hrev) =
      p ^ (Fintype.card P.Gen - Fintype.card P.Relator) := by
  have hc := additive_independent_reverse
    (p := p) (P := P) hrev h
  rw [@Nat.card_eq_fintype_card (Additive (zLKern p P.Group 1))
    (fintype_one_reverse p P hrev)] at hc
  exact hc

/-- `Fintype.card` first-layer formula for independent degree-one relators. -/
theorem fintype_relators_independent
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group)
    (h : degreeRelatorsIndependent p P) :
    @Fintype.card (zLKern p P.Group 1)
        (zassenhaus_layer_reverse p P hrev) =
      p ^ (Fintype.card P.Gen - Fintype.card P.Relator) := by
  have hc := layer_independent_reverse
    (p := p) (P := P) hrev h
  rw [@Nat.card_eq_fintype_card (zLKern p P.Group 1)
    (zassenhaus_layer_reverse p P hrev)] at hc
  exact hc

end
end Presentation
end Towers

namespace Towers
namespace Presentation

open GroupAlgebra

noncomputable section

variable (p : ℕ) (P : Presentation) [Fact p.Prime] [Fintype P.Gen]

/-- `Fintype.card` first-quotient formula for degree-one minimal presentations (additive). -/
theorem fintype_minimal_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group)
    (h : degreeOneMinimal p P) :
    @Fintype.card (zTAdditi p P.Group)
        (fintype_zassenhaus_reverse p P hrev) =
      p ^ Fintype.card P.Gen := by
  have hc := nat_minimal_reverse
    (p := p) (P := P) hrev h
  rw [@Nat.card_eq_fintype_card (zTAdditi p P.Group)
    (fintype_zassenhaus_reverse p P hrev)] at hc
  exact hc

/-- `Fintype.card` first-quotient formula for degree-one minimal presentations. -/
theorem two_minimal_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group)
    (h : degreeOneMinimal p P) :
    @Fintype.card (zQuot p P.Group 2)
        (zassenhaus_two_reverse p P hrev) =
      p ^ Fintype.card P.Gen := by
  have hc := zassenhaus_minimal_reverse
    (p := p) (P := P) hrev h
  rw [@Nat.card_eq_fintype_card (zQuot p P.Group 2)
    (zassenhaus_two_reverse p P hrev)] at hc
  exact hc

/-- `Fintype.card` first-layer formula for degree-one minimal presentations (additive). -/
theorem additive_minimal_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group)
    (h : degreeOneMinimal p P) :
    @Fintype.card (Additive (zLKern p P.Group 1))
        (fintype_one_reverse p P hrev) =
      p ^ Fintype.card P.Gen := by
  have hc := card_minimal_reverse
    (p := p) (P := P) hrev h
  rw [@Nat.card_eq_fintype_card (Additive (zLKern p P.Group 1))
    (fintype_one_reverse p P hrev)] at hc
  exact hc

/-- `Fintype.card` first-layer formula for degree-one minimal presentations. -/
theorem layer_minimal_reverse
    (hrev : zSubgro p P.Group 2 ≤ modPFrattini p P.Group)
    (h : degreeOneMinimal p P) :
    @Fintype.card (zLKern p P.Group 1)
        (zassenhaus_layer_reverse p P hrev) =
      p ^ Fintype.card P.Gen := by
  have hc := one_minimal_reverse
    (p := p) (P := P) hrev h
  rw [@Nat.card_eq_fintype_card (zLKern p P.Group 1)
    (zassenhaus_layer_reverse p P hrev)] at hc
  exact hc

end
end Presentation
end Towers
