import Towers.FieldTheory.ElementaryAbelian
import Towers.Group.GolodShafarevichCore


noncomputable section

namespace Towers
namespace TBluepr

open GShafar

theorem nontrivial_surjects_elementary
    {G : Type} [Group G]
    (h : SurjectsElementaryRank G 5) :
    Nontrivial G := by
  rcases h with ⟨φ, hφ⟩
  have htarget : Nontrivial (ElementaryAbelianGroup 5) := by
    infer_instance
  letI : Nontrivial (ElementaryAbelianGroup 5) := htarget
  rcases exists_pair_ne (ElementaryAbelianGroup 5) with ⟨a, b, hab⟩
  rcases hφ a with ⟨ga, hga⟩
  rcases hφ b with ⟨gb, hgb⟩
  exact
    ⟨⟨ga, gb, by
      intro hgb_eq
      apply hab
      calc
        a = φ ga := hga.symm
        _ = φ gb := by rw [hgb_eq]
        _ = b := hgb⟩⟩

theorem elementary_abelian_pow
    {n : ℕ} (y : ElementaryAbelianGroup n) :
    y ^ (3 : ℕ) = 1 := by
  ext i
  have hcard : Nat.card (Multiplicative (ZMod 3)) = 3 := by
    simp [Nat.card_eq_fintype_card, Fintype.card_multiplicative, ZMod.card]
  have hpow := pow_card_eq_one' (x := y i)
  rw [hcard] at hpow
  exact hpow

/- Consequently every multiple of `3` also annihilates an elementary abelian group element. -/

theorem elementary_abelian_dvd
    {n m : ℕ} (y : ElementaryAbelianGroup n)
    (hm : 3 ∣ m) :
    y ^ m = 1 := by
  rcases hm with ⟨q, rfl⟩
  calc
    y ^ (3 * q) = (y ^ (3 : ℕ)) ^ q := by
      rw [pow_mul]
    _ = 1 ^ q := by
      rw [elementary_abelian_pow y]
    _ = 1 := one_pow q

/- A positive power of `3` is divisible by `3`.  This tiny arithmetic lemma keeps the
Zassenhaus generator proof readable when the generator comes from a `3^j`-power with `j > 0`. -/

theorem three_dvd_pos
    {j : ℕ} (hj : 0 < j) :
    3 ∣ 3 ^ j := by
  cases j with
  | zero =>
      cases hj
  | succ j =>
      refine ⟨3 ^ j, ?_⟩
      rw [pow_succ]
      exact Nat.mul_comm (3 ^ j) 3

/- Homomorphisms into a commutative group kill the commutator subgroup.  This is the usual
universal property of abelianization, stated in the subgroup form needed for the Zassenhaus
generator argument. -/

theorem commutative_kills_commutator
    {G A : Type*} [Group G] [CommGroup A]
    (φ : G →* A) :
    _root_.commutator G ≤ φ.ker := by
  rw [commutator_eq_closure]
  refine (Subgroup.closure_le _).mpr ?_
  intro g hg
  rw [commutatorSet_def] at hg
  rcases hg with ⟨a, b, hg⟩
  change φ g = 1
  rw [← hg]
  simp [commutatorElement_def, mul_assoc]

/- Every positive lower-central term lies in the commutator subgroup.  With this file's indexing
`Subgroup.lowerCentralSeries G 0 = G`, the first positive term is the commutator subgroup itself. -/

theorem lower_succ_commutator
    {G : Type*} [Group G] (i : ℕ) :
    Subgroup.lowerCentralSeries G (i + 1) ≤ _root_.commutator G := by
  rw [Subgroup.lowerCentralSeries_succ, commutator_eq_closure]
  refine Subgroup.closure_mono ?_
  intro z hz
  rcases hz with ⟨a, _ha, b, _hb, hz⟩
  rw [← hz]
  rw [commutatorSet_def]
  exact ⟨a, b, by simp [commutatorElement_def]⟩

theorem lower_series_commutator
    {G : Type*} [Group G] {i : ℕ}
    (hi : 1 ≤ i) :
    Subgroup.lowerCentralSeries G i ≤ _root_.commutator G := by
  cases i with
  | zero =>
      omega
  | succ i =>
      simpa [Nat.succ_eq_add_one] using
        lower_succ_commutator (G := G) i

/- A depth-two Zassenhaus generator maps trivially to every elementary abelian `3`-group.  If
the generator comes from a positive lower-central term, it dies because the target is abelian;
if it comes from a positive `3`-power, it dies because the target has exponent `3`. -/

theorem subset_elementary_abelian
    {G : Type*} [Group G] {n : ℕ}
    (φ : G →* ElementaryAbelianGroup n) :
    zassenhausGeneratorSet 3 G 2 ⊆ (φ.ker : Set G) := by
  intro g hg
  change φ g = 1
  rcases hg with ⟨i, j, x, hx_lower, hbound, hpow⟩
  by_cases hj : j = 0
  · subst j
    have hi : 1 ≤ i := by
      omega
    have hx_comm : x ∈ _root_.commutator G :=
      lower_series_commutator hi hx_lower
    have hx_ker_mem : x ∈ φ.ker :=
      commutative_kills_commutator φ hx_comm
    have hx_ker : φ x = 1 :=
      MonoidHom.mem_ker.mp hx_ker_mem
    have hxg : x = g := by
      simpa using hpow
    rw [← hxg]
    exact hx_ker
  · have hj_pos : 0 < j := Nat.pos_of_ne_zero hj
    have hdiv : 3 ∣ 3 ^ j :=
      three_dvd_pos hj_pos
    calc
      φ g = φ (x ^ (3 ^ j)) := by
        rw [← hpow]
      _ = φ x ^ (3 ^ j) := by
        rw [map_pow]
      _ = 1 :=
        elementary_abelian_dvd (φ x) hdiv

/- Therefore the entire second Zassenhaus subgroup maps trivially: it is generated by the
depth-two Zassenhaus generators just handled. -/

theorem filtration_elementary_abelian
    {G : Type*} [Group G] {n : ℕ}
    (φ : G →* ElementaryAbelianGroup n) :
    zassenhausFiltration 3 G 2 ≤ φ.ker := by
  rw [zassenhausFiltration]
  exact
    (Subgroup.closure_le _).mpr
      (subset_elementary_abelian φ)

end TBluepr
end Towers
