import Towers.Group.GSHilbert

namespace Towers

universe u

/-!
Basic functoriality and filtration lemmas for augmentation ideals.
-/

namespace GroupAlgebra

noncomputable section

section Functoriality

variable (K : Type*) [CommRing K]
variable {G H : Type*} [_root_.Group G] [_root_.Group H]

/-- The map on group algebras induced by a group homomorphism. -/
def mapGroupHom (φ : G →* H) :
    MonoidAlgebra K G →ₐ[K] MonoidAlgebra K H := by
  exact MonoidAlgebra.mapDomainAlgHom K K φ

@[simp]
lemma group_hom_single (φ : G →* H) (g : G) (a : K) :
    mapGroupHom K φ (MonoidAlgebra.single g a) =
      MonoidAlgebra.single (φ g) a := by
  simp [mapGroupHom]

lemma augmentation_group_hom (φ : G →* H) (x : MonoidAlgebra K G) :
    augmentation K H (mapGroupHom K φ x) = augmentation K G x := by
  exact augmentation_domain φ x

lemma group_augmentation_power
    (φ : G →* H) {n : ℕ} {x : MonoidAlgebra K G}
    (hx : x ∈ augmentationPower K G n) :
    mapGroupHom K φ x ∈ augmentationPower K H n := by
  apply augmentation_power_domain φ n
  exact Ideal.mem_map_of_mem _ hx

end Functoriality

section Filtration

variable (K : Type*) [CommRing K]
variable (G : Type*) [_root_.Group G]

lemma augmentation_anti_mono {m n : ℕ} (hmn : m ≤ n) :
    augmentationPower K G n ≤ augmentationPower K G m := by
  exact augmentationPower_antitone K G hmn

lemma submodule_anti_mono {m n : ℕ} (hmn : m ≤ n) :
    augmentationPowerSubmodule K G n ≤ augmentationPowerSubmodule K G m := by
  exact augmentation_submodule_antitone K G hmn

lemma augmentation_power_succ (n : ℕ) :
    augmentationPower K G (n + 1) =
      augmentationPower K G n * augmentationIdeal K G := by
  exact Submodule.pow_succ _

lemma single_sub_power (g : G) :
    (MonoidAlgebra.single g (1 : K) - 1 : MonoidAlgebra K G) ∈
      augmentationPower K G 1 := by
  rw [show augmentationPower K G 1 = augmentationIdeal K G by
    simp [augmentationPower, Submodule.pow_one]]
  simp

lemma mul_augmentation_power
    {m n : ℕ} {a b : MonoidAlgebra K G}
    (ha : a ∈ augmentationPower K G m)
    (hb : b ∈ augmentationPower K G n) :
    a * b ∈ augmentationPower K G (m + n) := by
  exact mul_augmentation_add (R := K) (G := G) ha hb

lemma single_sub_succ
    {m : ℕ} {a : MonoidAlgebra K G}
    (ha : a ∈ augmentationPower K G m) (g : G) :
    a * (MonoidAlgebra.single g (1 : K) - 1) ∈
      augmentationPower K G (m + 1) := by
  exact mul_augmentation_power K G ha
    (single_sub_power K G g)

/-- If `ι : X → G` generates `G`, then the augmentation ideal is generated by
the elements `ι x - 1`. -/
lemma single_sub_top
    {X : Type*} (ι : X → G)
    (hι : Subgroup.closure (Set.range ι) = ⊤) :
    augmentationIdeal K G =
      Ideal.span
        (Set.range
          (fun x : X =>
            (MonoidAlgebra.single (ι x) (1 : K) - 1 :
              MonoidAlgebra K G))) := by
  classical
  let J : Ideal (MonoidAlgebra K G) :=
    Ideal.span
      (Set.range
        (fun x : X =>
          (MonoidAlgebra.single (ι x) (1 : K) - 1 :
            MonoidAlgebra K G)))
  apply le_antisymm
  · rw [← augmentation_generator_ideal K G]
    apply Ideal.span_le.mpr
    rintro _ ⟨g, rfl⟩
    change (MonoidAlgebra.of K G g - 1 : MonoidAlgebra K G) ∈ J
    have hg : g ∈ Subgroup.closure (Set.range ι) := by
      rw [hι]
      exact Subgroup.mem_top g
    have hdiff : augmentationDifference K G g ∈ J := by
      refine Subgroup.closure_induction
        (k := Set.range ι)
        (p := fun g _ =>
          augmentationDifference K G g ∈ J)
        ?mem ?one ?mul ?inv hg
      · rintro _ ⟨x, rfl⟩
        exact Ideal.subset_span ⟨x, by simp [augmentationDifference]⟩
      · simp [augmentationDifference, MonoidAlgebra.one_def]
      · intro g h _ _ hg hh
        rw [augmentation_difference_left]
        exact J.add_mem hg (J.mul_mem_left (MonoidAlgebra.single g 1) hh)
      · intro g _ hg
        rw [difference_inv_neg]
        exact J.mul_mem_left (-MonoidAlgebra.single g⁻¹ 1) hg
    simpa [augmentationDifference, MonoidAlgebra.of_apply] using hdiff
  · apply Ideal.span_le.mpr
    rintro _ ⟨x, rfl⟩
    simp

end Filtration

section Rank

variable (K : Type*) [Field K]
variable (G : Type*) [_root_.Group G]

/-- The degree-`m` multiplication map attached to a finite generating family. -/
def augmentationGeneratorLayer
    {X : Type*} (ι : X → G) (m : ℕ) :
    (X →₀ augmentationLayer K G m) →ₗ[K] augmentationLayer K G (m + 1) := by
  exact Finsupp.lsum K fun x : X =>
    (LinearMap.applyₗ (Submodule.Quotient.mk
      (⟨MonoidAlgebra.single (ι x) (1 : K) - 1,
        single_sub_power K G (ι x)⟩ :
        augmentationPowerSubmodule K G 1))).comp
      (augmentationLayerMul K G m 1)

@[simp]
lemma augmentation_generator_single
    {X : Type*} (ι : X → G) (m : ℕ)
    (x : X) (a : augmentationLayer K G m) :
    augmentationGeneratorLayer K G ι m (Finsupp.single x a) =
      (augmentationLayerMul K G m 1 a)
        (Submodule.Quotient.mk
          (⟨MonoidAlgebra.single (ι x) (1 : K) - 1,
            single_sub_power K G (ι x)⟩ :
            augmentationPowerSubmodule K G 1)) := by
  simp [augmentationGeneratorLayer]

/-- Finite group generators right-generate every positive augmentation power
from the preceding power. -/
lemma generated_single_top
    {X : Type*} [Fintype X] (ι : X → G)
    (hι : Subgroup.closure (Set.range ι) = ⊤)
    (n : ℕ) (hn : 1 ≤ n) :
    ∀ a : augmentationPowerSubmodule K G n,
      ∃ c : X → augmentationPowerSubmodule K G (n - 1),
        (a : MonoidAlgebra K G) =
          ∑ x, (c x : MonoidAlgebra K G) *
            (MonoidAlgebra.single (ι x) (1 : K) - 1) := by
  classical
  let I : Ideal (MonoidAlgebra K G) := augmentationIdeal K G
  have hI_right :
      ∀ {z : MonoidAlgebra K G}, z ∈ I →
        ∃ c : X → MonoidAlgebra K G,
          z = ∑ x, c x * (MonoidAlgebra.single (ι x) (1 : K) - 1) := by
    intro z hz
    simpa [I, TBluepr.golod_shafarevich_algebra,
      augmentationDifference, MonoidAlgebra.of_apply] using
      (TBluepr.augmentation_generated_closure
        K G X ι hι
        (by simpa [I, TBluepr.golod_shafarevich_algebra]
          using hz))
  intro a
  have hamul : (a : MonoidAlgebra K G) ∈ I ^ (n - 1) * I := by
    have hdegree : (n - 1) + 1 = n := by omega
    have hpow : I ^ n = I ^ (n - 1) * I := by
      calc
        I ^ n = I ^ ((n - 1) + 1) := by rw [hdegree]
        _ = I ^ (n - 1) * I ^ 1 := by rw [Ideal.IsTwoSided.pow_add]
        _ = I ^ (n - 1) * I := by rw [Submodule.pow_one]
    simpa [I, augmentationPowerSubmodule, augmentationPower, hpow] using a.property
  let P : MonoidAlgebra K G → Prop := fun z =>
    ∃ c : X → augmentationPowerSubmodule K G (n - 1),
      z = ∑ x, (c x : MonoidAlgebra K G) *
        (MonoidAlgebra.single (ι x) (1 : K) - 1)
  have haP : P (a : MonoidAlgebra K G) := by
    refine Submodule.mul_induction_on hamul ?mul_mem ?add_mem
    · intro b hb z hz
      rcases hI_right hz with ⟨c, hc⟩
      let d : X → augmentationPowerSubmodule K G (n - 1) :=
        fun x => ⟨b * c x, (I ^ (n - 1)).mul_mem_right (c x) hb⟩
      refine ⟨d, ?_⟩
      calc
        b * z = b * (∑ x, c x *
            (MonoidAlgebra.single (ι x) (1 : K) - 1)) := by rw [hc]
        _ = ∑ x, (d x : MonoidAlgebra K G) *
            (MonoidAlgebra.single (ι x) (1 : K) - 1) := by
              rw [Finset.mul_sum]
              apply Finset.sum_congr rfl
              intro x _hx
              dsimp [d]
              rw [mul_assoc]
    · intro b c hb hc
      rcases hb with ⟨db, hdb⟩
      rcases hc with ⟨dc, hdc⟩
      refine ⟨fun x => db x + dc x, ?_⟩
      rw [hdb, hdc]
      simp [add_mul, Finset.sum_add_distrib]
  simpa [P] using haP

lemma augmentation_generator_surjective
    {X : Type*} [Finite X] (ι : X → G)
    (hι : Subgroup.closure (Set.range ι) = ⊤) (m : ℕ) :
    Function.Surjective (augmentationGeneratorLayer K G ι m) := by
  classical
  letI := Fintype.ofFinite X
  intro z
  refine Quotient.inductionOn' z ?_
  intro a
  rcases generated_single_top
      K G ι hι (m + 1) (by omega) a with ⟨c, hc⟩
  refine ⟨Finsupp.equivFunOnFinite.symm
    (fun x => Submodule.Quotient.mk (c x)), ?_⟩
  rw [Finsupp.equivFunOnFinite_symm_eq_sum]
  rw [map_sum]
  simp only [augmentation_generator_single]
  simp only [augmentation_mul_mk]
  change
    ∑ x, (augmentationLayerDenom K G (m + 1)).mkQ
      (⟨(c x : MonoidAlgebra K G) *
          (MonoidAlgebra.single (ι x) (1 : K) - 1), by
        exact mul_augmentation_power K G (c x).property
          (single_sub_power K G (ι x))⟩ :
        augmentationPowerSubmodule K G (m + 1)) =
      (augmentationLayerDenom K G (m + 1)).mkQ a
  rw [← map_sum]
  apply (Submodule.Quotient.eq (augmentationLayerDenom K G (m + 1))).mpr
  rw [augmentation_layer_denom]
  simp only [Submodule.coe_sub, Submodule.coe_sum]
  rw [← hc]
  simp

lemma dimensional_closure_top
    {X : Type*} [Finite X] (ι : X → G)
    (hι : Subgroup.closure (Set.range ι) = ⊤) (n : ℕ) :
    FiniteDimensional K (augmentationLayer K G n) := by
  letI := Fintype.ofFinite X
  induction n with
  | zero =>
      exact Module.Finite.equiv (augmentationZeroEquiv K G).symm
  | succ n ih =>
      letI : Module.Finite K (X →₀ augmentationLayer K G n) :=
        Module.Finite.finsupp
      exact Module.Finite.of_surjective
        (augmentationGeneratorLayer K G ι n)
        (augmentation_generator_surjective K G ι hι n)

end Rank

end

end GroupAlgebra


/-!
Canonical maps associated to a presentation.
-/

namespace Presentation

noncomputable section

variable (P : Presentation.{u})

/-- The image in the presented group of a free generator. -/
def generatorImage (x : P.Gen) : P.Group :=
  quotientMap P (FreeGroup.of x)

lemma quotientMap_relator (r : P.Relator) :
    quotientMap P (r : P.Free) = 1 := by
  exact P.quotient_rel_one r.property

lemma generator_image_top :
    Subgroup.closure (Set.range (fun x : P.Gen => generatorImage P x)) = ⊤ := by
  simpa [generatorImage] using P.closure_range_of

end

end Presentation


/-!
Fox derivatives over `ZMod p`.
-/

namespace Fox

noncomputable section

variable (p : ℕ) (P : Presentation.{u})

/-- The Fox derivative of a word with respect to a generator, reduced modulo `p`. -/
def derivative (x : P.Gen) (w : P.Free) :
    MonoidAlgebra (ZMod p) P.Free := by
  classical
  exact groupFoxDerivative (ZMod p) x w

/-- The fundamental Fox identity. -/
lemma fundamental_identity [Fintype P.Gen] (w : P.Free) :
    (MonoidAlgebra.single w (1 : ZMod p) - 1 :
        MonoidAlgebra (ZMod p) P.Free)
      =
    ∑ x : P.Gen,
      derivative p P x w *
        (MonoidAlgebra.single (FreeGroup.of x) (1 : ZMod p) - 1) := by
  classical
  simpa [derivative, augmentationDifference] using
    free_derivative_fundamental (ZMod p) w

/-- Fox differentiation lowers Jennings/augmentation degree by one.  For `q = 0`,
the right hand side is interpreted as degree `0`, so the statement is harmless. -/
lemma derivative_augmentation_pred
    [Finite P.Gen]
    {q : ℕ} {w : P.Free}
    (hw :
      (MonoidAlgebra.single w (1 : ZMod p) - 1 :
          MonoidAlgebra (ZMod p) P.Free) ∈
        GroupAlgebra.augmentationPower (ZMod p) P.Free q)
    (x : P.Gen) :
    derivative p P x w ∈
      GroupAlgebra.augmentationPower (ZMod p) P.Free (q - 1) := by
  classical
  letI := Fintype.ofFinite P.Gen
  have hw' :
      augmentationDifference (ZMod p) P.Free w ∈
        (GShafar.augmentationIdeal (ZMod p) P.Free) ^ q := by
    simpa only [augmentationDifference, MonoidAlgebra.of_apply,
      TBluepr.golod_shafarevich_algebra] using hw
  simpa only [derivative, GroupAlgebra.augmentationPower,
    TBluepr.golod_shafarevich_algebra,
    TBluepr.derivative_augmentation_difference] using
    (TBluepr.fox_derivative_pred
      (ZMod p) P.Gen x hw')

end

end Fox


/-!
Filtered presentations and the missing Jennings-depth hypothesis.
-/

namespace FPres

noncomputable section

variable {p : ℕ} (FP : FPres.{u} p)

lemma shift_contribution_pos
    (b : ℕ → ℕ) {n : ℕ} (hn : 0 < n) :
    generatorShiftContribution FP b n =
      FP.generatorCount * b (n - 1) := by
  simp [generatorShiftContribution, hn]

lemma generator_fintype_card [Fintype FP.Gen] :
    FP.generatorCount = Fintype.card FP.Gen := by
  simp [generatorCount, Nat.card_eq_fintype_card]

lemma generator_count_infinite [Infinite FP.Gen] :
    FP.generatorCount = 0 := by
  simp [generatorCount, Nat.card_eq_zero_of_infinite]

lemma relator_convolution_sum
    [Fintype FP.toPresentation.Relator] (b : ℕ → ℕ) (n : ℕ) :
    relatorDepthConvolution FP b n =
      ∑ r : FP.toPresentation.Relator,
        if FP.depths.depth r ≤ n then b (n - FP.depths.depth r) else 0 := by
  rfl

/-- The element `r - 1` in the free group algebra over `ZMod p`. -/
def relatorElement (r : FP.toPresentation.Relator) :
    MonoidAlgebra (ZMod p) FP.toPresentation.Free :=
  MonoidAlgebra.single (r : FP.toPresentation.Free) (1 : ZMod p) - 1

lemma relator_element_augmentation
    (r : FP.toPresentation.Relator) :
    relatorElement FP r ∈
      GroupAlgebra.augmentationPower (ZMod p) FP.toPresentation.Free 1 := by
  rw [show GroupAlgebra.augmentationPower
      (ZMod p) FP.toPresentation.Free 1 =
      GroupAlgebra.augmentationIdeal (ZMod p) FP.toPresentation.Free by
    simp [GroupAlgebra.augmentationPower, Submodule.pow_one]]
  simp [relatorElement]

/-- The declared depth is at most the actual Jennings depth. -/
def RelatorDepthsJennings : Prop :=
  ∀ r : FP.toPresentation.Relator,
    relatorElement FP r ∈
      GroupAlgebra.augmentationPower
        (ZMod p) FP.toPresentation.Free (FP.depths.depth r)

/-- The declared depth is the exact Jennings depth, except that the zero element
`r - 1 = 0` is allowed to have arbitrary declared depth. -/
def ExactJenningsDepth (r : FP.toPresentation.Relator) : Prop :=
  relatorElement FP r = 0 ∨
    (relatorElement FP r ∈
        GroupAlgebra.augmentationPower
          (ZMod p) FP.toPresentation.Free (FP.depths.depth r) ∧
      ∀ m : ℕ,
        relatorElement FP r ∈
          GroupAlgebra.augmentationPower (ZMod p) FP.toPresentation.Free m →
        m ≤ FP.depths.depth r)

def DepthsJennings : Prop :=
  ∀ r : FP.toPresentation.Relator, ExactJenningsDepth FP r

lemma relator_depths_jennings
    (h : DepthsJennings FP)
    (r : FP.toPresentation.Relator) :
    relatorElement FP r ∈
      GroupAlgebra.augmentationPower
        (ZMod p) FP.toPresentation.Free (FP.depths.depth r) := by
  rcases h r with hzero | hmem
  · rw [hzero]
    exact (GroupAlgebra.augmentationPower
      (ZMod p) FP.toPresentation.Free (FP.depths.depth r)).zero_mem
  · exact hmem.1

lemma depths_jennings_bounded
    (h : DepthsJennings FP) :
    RelatorDepthsJennings FP := by
  exact fun r => relator_depths_jennings FP h r

lemma depths_jennings_pos
    (h : DepthsJennings FP)
    {r : FP.toPresentation.Relator}
    (hr : relatorElement FP r ≠ 0) :
    0 < FP.depths.depth r := by
  by_contra hdepth
  have hdepth_zero : FP.depths.depth r = 0 := Nat.eq_zero_of_not_pos hdepth
  rcases h r with hzero | hmem
  · exact hr hzero
  · have hle : 1 ≤ FP.depths.depth r :=
      hmem.2 1 (relator_element_augmentation FP r)
    omega

/-- The rank sequence used in the GS inequality. -/
noncomputable abbrev layerRank [Fact p.Prime]
    (FP : FPres.{u} p) : ℕ → ℕ :=
  GroupAlgebra.augmentationLayerRank (ZMod p) FP.Group

/-- The Fox Jacobian entry associated to a relator and a generator,
viewed in the quotient group algebra. -/
def foxJacobianEntry
    (r : FP.toPresentation.Relator) (x : FP.Gen) :
    MonoidAlgebra (ZMod p) FP.Group :=
  GroupAlgebra.mapGroupHom (ZMod p) (Presentation.quotientMap FP.toPresentation)
    (Fox.derivative p FP.toPresentation x (r : FP.toPresentation.Free))

lemma jacobian_entry_pred
    [Finite FP.Gen]
    (hdepth : RelatorDepthsJennings FP)
    (r : FP.toPresentation.Relator) (x : FP.Gen) :
    foxJacobianEntry FP r x ∈
      GroupAlgebra.augmentationPower
        (ZMod p) FP.Group (FP.depths.depth r - 1) := by
  apply GroupAlgebra.group_augmentation_power
  exact Fox.derivative_augmentation_pred p FP.toPresentation (hdepth r) x

/-- A relator gives a syzygy among the elements `x - 1`. -/
lemma relatorFox_syzygy
    [Fintype FP.Gen] (r : FP.toPresentation.Relator) :
    ((∑ x : FP.Gen,
        foxJacobianEntry FP r x *
          (MonoidAlgebra.single
              (Presentation.generatorImage FP.toPresentation x)
              (1 : ZMod p) - 1) :
      MonoidAlgebra (ZMod p) FP.Group) = 0) := by
  classical
  have h := congrArg
    (GroupAlgebra.mapGroupHom
      (ZMod p) (Presentation.quotientMap FP.toPresentation))
    (Fox.fundamental_identity p FP.toPresentation (r : FP.toPresentation.Free))
  simpa [foxJacobianEntry, Presentation.generatorImage,
    Presentation.quotientMap_relator, MonoidAlgebra.one_def,
    map_sub, map_mul, map_sum] using h.symm

/-- The Fox derivative extended linearly to the free group algebra. -/
noncomputable def algebraFoxDerivative
    [Fintype FP.Gen]
    (x : FP.Gen) :
    MonoidAlgebra (ZMod p) FP.toPresentation.Free →ₗ[ZMod p]
      MonoidAlgebra (ZMod p) FP.toPresentation.Free := by
  classical
  exact TBluepr.freeFoxDerivative (ZMod p) FP.Gen x

lemma fox_derivative_mul
    [Fintype FP.Gen]
    (x : FP.Gen)
    (a b : MonoidAlgebra (ZMod p) FP.toPresentation.Free) :
    algebraFoxDerivative FP x (a * b) =
      (GShafar.augmentationHom
          (ZMod p) FP.toPresentation.Free b) •
        algebraFoxDerivative FP x a +
      a * algebraFoxDerivative FP x b := by
  classical
  simpa [algebraFoxDerivative] using
    TBluepr.algebra_fox_derivative
      (ZMod p) FP.Gen x a b

@[simp]
lemma algebra_fox_difference
    [Fintype FP.Gen]
    (x : FP.Gen) (g : FP.toPresentation.Free) :
    algebraFoxDerivative FP x
        (augmentationDifference (ZMod p) FP.toPresentation.Free g) =
      Fox.derivative p FP.toPresentation x g := by
  classical
  simp [algebraFoxDerivative, Fox.derivative,
    TBluepr.derivative_augmentation_difference
      (ZMod p) FP.Gen x g]

@[simp]
lemma fox_derivative_single
    [Fintype FP.Gen]
    (x : FP.Gen) (g : FP.toPresentation.Free) :
    algebraFoxDerivative FP x
        (MonoidAlgebra.single g (1 : ZMod p) - 1) =
      Fox.derivative p FP.toPresentation x g := by
  simpa [augmentationDifference] using
    algebra_fox_difference FP x g

@[simp]
lemma algebra_derivative_difference
    [Fintype FP.Gen]
    (coeff : FP.Gen →
      MonoidAlgebra (ZMod p) FP.toPresentation.Free)
    (x : FP.Gen) :
    algebraFoxDerivative FP x
        (∑ y, coeff y *
          augmentationDifference
            (ZMod p) FP.toPresentation.Free (FreeGroup.of y)) =
      coeff x := by
  classical
  simpa [algebraFoxDerivative] using
    TBluepr.fox_derivative_difference
      (ZMod p) FP.Gen coeff x

/-- The augmentation ideal of the presented group algebra is generated by
the images of the free generators minus `1`. -/
lemma presented_span_generators :
    GroupAlgebra.augmentationIdeal (ZMod p) FP.Group =
      Ideal.span
        (Set.range
          (fun x : FP.Gen =>
            (MonoidAlgebra.single
                (Presentation.generatorImage FP.toPresentation x)
                (1 : ZMod p) - 1 :
              MonoidAlgebra (ZMod p) FP.Group))) := by
  exact GroupAlgebra.single_sub_top
    (ZMod p) FP.Group (Presentation.generatorImage FP.toPresentation)
    (Presentation.generator_image_top FP.toPresentation)

/-- The algebra-level map sending coefficients `(a_x)` to
`∑ a_x (x - 1)`. -/
def generatorAugmentationMap :
    (FP.Gen →₀ MonoidAlgebra (ZMod p) FP.Group) →ₗ[ZMod p]
      MonoidAlgebra (ZMod p) FP.Group := by
  exact Finsupp.lsum (ZMod p) fun x : FP.Gen =>
    { toFun := fun a =>
        a * (MonoidAlgebra.single
          (Presentation.generatorImage FP.toPresentation x) (1 : ZMod p) - 1)
      map_add' := by
        intro a b
        rw [add_mul]
      map_smul' := by
        intro c a
        simp [Algebra.smul_def, mul_assoc] }

@[simp]
lemma generator_augmentation_single (x : FP.Gen)
    (a : MonoidAlgebra (ZMod p) FP.Group) :
    generatorAugmentationMap FP (Finsupp.single x a) =
      a * (MonoidAlgebra.single
        (Presentation.generatorImage FP.toPresentation x) (1 : ZMod p) - 1) := by
  simp [generatorAugmentationMap]

lemma range_generator_augmentation :
    LinearMap.range (generatorAugmentationMap FP) =
      GroupAlgebra.augmentationPowerSubmodule (ZMod p) FP.Group 1 := by
  classical
  apply le_antisymm
  · rintro _ ⟨c, rfl⟩
    induction c using Finsupp.induction_linear with
    | zero =>
        simp [generatorAugmentationMap]
    | add c d hc hd =>
        simpa [map_add] using
          (GroupAlgebra.augmentationPowerSubmodule
            (ZMod p) FP.Group 1).add_mem hc hd
    | single x a =>
        simpa only [generator_augmentation_single] using
          (GroupAlgebra.augmentationPower (ZMod p) FP.Group 1).mul_mem_left a
            (GroupAlgebra.single_sub_power
              (ZMod p) FP.Group
              (Presentation.generatorImage FP.toPresentation x))
  · rw [GroupAlgebra.augmentation_submodule_one]
    rw [presented_span_generators FP]
    intro z hz
    refine Submodule.span_induction
      (p := fun z _ => z ∈ LinearMap.range (generatorAugmentationMap FP))
      ?mem ?zero ?add ?smul hz
    · rintro _ ⟨x, rfl⟩
      refine ⟨Finsupp.single x 1, ?_⟩
      simp
    · exact (LinearMap.range (generatorAugmentationMap FP)).zero_mem
    · intro a b _ _ ha hb
      exact (LinearMap.range (generatorAugmentationMap FP)).add_mem ha hb
    · intro a b _ hb
      rcases hb with ⟨c, rfl⟩
      have hleft :
          ∀ c, a * generatorAugmentationMap FP c ∈
            LinearMap.range (generatorAugmentationMap FP) := by
        intro c
        induction c using Finsupp.induction_linear with
        | zero =>
            simp
        | add c d hc hd =>
            simpa [map_add, mul_add] using
              (LinearMap.range (generatorAugmentationMap FP)).add_mem hc hd
        | single x c =>
            refine ⟨Finsupp.single x (a * c), ?_⟩
            simp only [generator_augmentation_single, mul_assoc]
      simpa [Algebra.smul_def] using hleft c

/-- The Fox Jacobian map from relators to syzygies among the generators. -/
def foxJacobianMap [Fintype FP.Gen] :
    (FP.toPresentation.Relator →₀ MonoidAlgebra (ZMod p) FP.Group) →ₗ[ZMod p]
      (FP.Gen →₀ MonoidAlgebra (ZMod p) FP.Group) := by
  classical
  exact Finsupp.lsum (ZMod p) fun r : FP.toPresentation.Relator =>
    { toFun := fun a =>
        Finsupp.equivFunOnFinite.symm
          (fun x => a * foxJacobianEntry FP r x)
      map_add' := by
        intro a b
        ext x
        simp [add_mul]
      map_smul' := by
        intro c a
        ext x
        simp [Algebra.smul_def, mul_assoc] }

@[simp]
lemma fox_jacobian [Fintype FP.Gen]
    (r : FP.toPresentation.Relator)
    (a : MonoidAlgebra (ZMod p) FP.Group) :
    foxJacobianMap FP (Finsupp.single r a) =
      Finsupp.equivFunOnFinite.symm
        (fun x => a * foxJacobianEntry FP r x) := by
  ext x
  simp [foxJacobianMap]

@[simp]
lemma jacobian_single [Fintype FP.Gen]
    (r : FP.toPresentation.Relator)
    (a : MonoidAlgebra (ZMod p) FP.Group) (x : FP.Gen) :
    foxJacobianMap FP (Finsupp.single r a) x =
      a * foxJacobianEntry FP r x := by
  simp

lemma fox_jacobian_single
    [Fintype FP.Gen]
    (r : FP.toPresentation.Relator)
    (a : MonoidAlgebra (ZMod p) FP.Group) :
    generatorAugmentationMap FP (foxJacobianMap FP (Finsupp.single r a)) = 0 := by
  classical
  rw [fox_jacobian]
  rw [Finsupp.equivFunOnFinite_symm_eq_sum]
  rw [map_sum]
  simp only [generator_augmentation_single]
  calc
    ∑ x : FP.Gen,
        (a * foxJacobianEntry FP r x) *
          (MonoidAlgebra.single
            (Presentation.generatorImage FP.toPresentation x)
            (1 : ZMod p) - 1) =
      a * ∑ x : FP.Gen,
        foxJacobianEntry FP r x *
          (MonoidAlgebra.single
            (Presentation.generatorImage FP.toPresentation x)
            (1 : ZMod p) - 1) := by
        rw [Finset.mul_sum]
        apply Finset.sum_congr rfl
        intro x _hx
        rw [mul_assoc]
    _ = 0 := by rw [relatorFox_syzygy FP r, mul_zero]

lemma fox_jacobian_range
    [Fintype FP.Gen]
    (a : MonoidAlgebra (ZMod p) FP.Group)
    {y : FP.Gen →₀ MonoidAlgebra (ZMod p) FP.Group}
    (hy : y ∈ LinearMap.range (foxJacobianMap FP)) :
    Finsupp.equivFunOnFinite.symm (fun x => a * y x) ∈
      LinearMap.range (foxJacobianMap FP) := by
  classical
  rcases hy with ⟨c, rfl⟩
  refine ⟨Finsupp.mapRange (fun b => a * b) (by simp) c, ?_⟩
  apply Finsupp.ext
  intro x
  change
    ((Finsupp.mapRange (fun b => a * b) (by simp) c).sum
        fun r b =>
          Finsupp.equivFunOnFinite.symm
            (fun y => b * foxJacobianEntry FP r y)) x =
      a * (c.sum fun r b =>
        Finsupp.equivFunOnFinite.symm
          (fun y => b * foxJacobianEntry FP r y)) x
  rw [Finsupp.sum_apply]
  rw [Finsupp.sum_mapRange_index (by intro; simp)]
  rw [Finsupp.sum_apply]
  rw [Finsupp.mul_sum]
  apply Finsupp.sum_congr
  intro r hr
  simp [mul_assoc]

lemma derivative_tuple_jacobian
    [Fintype FP.Gen]
    {z : MonoidAlgebra (ZMod p) FP.toPresentation.Free}
    (hz : z ∈ GShafar.relatorDifferenceIdeal
      (R := ZMod p) (fun r : FP.toPresentation.Relator =>
        (r : FP.toPresentation.Free))) :
    Finsupp.equivFunOnFinite.symm
        (fun x =>
          GroupAlgebra.mapGroupHom
            (ZMod p) (Presentation.quotientMap FP.toPresentation)
            (algebraFoxDerivative FP x z)) ∈
      LinearMap.range (foxJacobianMap FP) := by
  classical
  let F := FP.toPresentation.Free
  let qmap :
      MonoidAlgebra (ZMod p) F →ₐ[ZMod p]
        MonoidAlgebra (ZMod p) FP.Group :=
    GroupAlgebra.mapGroupHom
      (ZMod p) (Presentation.quotientMap FP.toPresentation)
  let aug : MonoidAlgebra (ZMod p) F →+* ZMod p :=
    (GShafar.augmentationHom (ZMod p) F).toRingHom
  let rangeS : Submodule (ZMod p)
      (FP.Gen →₀ MonoidAlgebra (ZMod p) FP.Group) :=
    LinearMap.range (foxJacobianMap FP)
  let Dtuple : MonoidAlgebra (ZMod p) F →
      FP.Gen →₀ MonoidAlgebra (ZMod p) FP.Group :=
    fun w => Finsupp.equivFunOnFinite.symm
      (fun x => qmap (algebraFoxDerivative FP x w))
  let P : TwoSidedIdeal (MonoidAlgebra (ZMod p) F) :=
    TwoSidedIdeal.mk'
      {w | qmap w = 0 ∧ aug w = 0 ∧ Dtuple w ∈ rangeS}
      (by
        constructor
        · exact map_zero qmap
        constructor
        · exact map_zero aug
        · have hD : Dtuple 0 = 0 := by
            apply Finsupp.ext
            intro x
            simp [Dtuple]
          rw [hD]
          exact rangeS.zero_mem)
      (by
        intro x y hx hy
        rcases hx with ⟨hxq, hxaug, hxD⟩
        rcases hy with ⟨hyq, hyaug, hyD⟩
        constructor
        · rw [map_add, hxq, hyq, add_zero]
        constructor
        · rw [map_add, hxaug, hyaug, add_zero]
        · have hD : Dtuple (x + y) = Dtuple x + Dtuple y := by
            apply Finsupp.ext
            intro j
            simp [Dtuple, map_add]
          rw [hD]
          exact rangeS.add_mem hxD hyD)
      (by
        intro x hx
        rcases hx with ⟨hxq, hxaug, hxD⟩
        constructor
        · rw [map_neg, hxq, neg_zero]
        constructor
        · rw [map_neg, hxaug, neg_zero]
        · have hD : Dtuple (-x) = -Dtuple x := by
            apply Finsupp.ext
            intro j
            simp [Dtuple, map_neg]
          rw [hD]
          exact rangeS.neg_mem hxD)
      (by
        intro x y hy
        rcases hy with ⟨hyq, hyaug, hyD⟩
        constructor
        · rw [map_mul, hyq, mul_zero]
        constructor
        · rw [map_mul, hyaug, mul_zero]
        · have hD :
            Dtuple (x * y) =
              Finsupp.equivFunOnFinite.symm
                (fun j => qmap x * Dtuple y j) := by
            apply Finsupp.ext
            intro j
            change
              qmap (algebraFoxDerivative FP j (x * y)) =
                qmap x *
                  qmap (algebraFoxDerivative FP j y)
            rw [fox_derivative_mul]
            have hyaug' :
                GShafar.augmentationHom
                  (ZMod p) (FreeGroup FP.Gen) y = 0 := by
              simpa [aug, F] using hyaug
            simp only [map_add, map_smul, map_mul, add_eq_right]
            rw [hyaug', zero_smul]
          rw [hD]
          exact fox_jacobian_range FP (qmap x) hyD)
      (by
        intro x y hx
        rcases hx with ⟨hxq, hxaug, hxD⟩
        constructor
        · rw [map_mul, hxq, zero_mul]
        constructor
        · rw [map_mul, hxaug, zero_mul]
        · have hD :
            Dtuple (x * y) = aug y • Dtuple x := by
            apply Finsupp.ext
            intro j
            change
              qmap (algebraFoxDerivative FP j (x * y)) =
                aug y •
                  qmap (algebraFoxDerivative FP j x)
            rw [fox_derivative_mul]
            simp [hxq, aug, F, qmap, map_add, map_mul, Algebra.smul_def]
          rw [hD]
          exact rangeS.smul_mem (aug y) hxD)
  have hspan :
      TwoSidedIdeal.span
          (Set.range fun r : FP.toPresentation.Relator =>
            MonoidAlgebra.of (ZMod p) F (r : FP.toPresentation.Free) - 1) ≤
        P := by
    rw [TwoSidedIdeal.span_le]
    rintro _ ⟨r, rfl⟩
    change
      (MonoidAlgebra.of (ZMod p) F (r : FP.toPresentation.Free) - 1 :
        MonoidAlgebra (ZMod p) F) ∈ P
    have hgen :
        (MonoidAlgebra.of (ZMod p) F (r : FP.toPresentation.Free) - 1 :
          MonoidAlgebra (ZMod p) F) =
          augmentationDifference (ZMod p) F (r : FP.toPresentation.Free) := by
      simp [augmentationDifference, MonoidAlgebra.of_apply]
    rw [hgen]
    constructor
    · rw [sub_zero]
      change
        GroupAlgebra.mapGroupHom
            (ZMod p) (Presentation.quotientMap FP.toPresentation)
            (MonoidAlgebra.single (r : FP.toPresentation.Free) 1 - 1) =
          0
      rw [map_sub, GroupAlgebra.group_hom_single,
        Presentation.quotientMap_relator]
      simp [MonoidAlgebra.one_def]
    constructor
    · simp [aug, F, augmentationDifference,
        GShafar.augmentationHom,
        GShafar.augmentationCharacter]
    · refine ⟨Finsupp.single r 1, ?_⟩
      apply Finsupp.ext
      intro x
      simp [Dtuple, qmap, F, foxJacobianEntry, Fox.derivative,
        augmentationDifference]
  have hzP : z ∈ P := by
    change z ∈ TwoSidedIdeal.span
      (Set.range fun r : FP.toPresentation.Relator =>
        MonoidAlgebra.of (ZMod p) F (r : FP.toPresentation.Free) - 1) at hz
    exact hspan hz
  simpa [Dtuple, rangeS, qmap, F] using hzP.2.2

/-- Fox-Lyndon exactness: all syzygies among the `x - 1` are generated by
the relators. -/
lemma foxLyndon_exact [Fintype FP.Gen] :
    LinearMap.range (foxJacobianMap FP) =
      LinearMap.ker (generatorAugmentationMap FP) := by
  classical
  apply le_antisymm
  · rintro _ ⟨c, rfl⟩
    rw [LinearMap.mem_ker]
    induction c using Finsupp.induction_linear with
    | zero =>
        simp
    | add c d hc hd =>
        calc
          generatorAugmentationMap FP (foxJacobianMap FP (c + d)) =
              generatorAugmentationMap FP (foxJacobianMap FP c) +
                generatorAugmentationMap FP (foxJacobianMap FP d) := by
            rw [map_add, map_add]
          _ = 0 := by rw [hc, hd, add_zero]
    | single r a =>
        exact fox_jacobian_single FP r a
  · intro y hy
    let F := FP.toPresentation.Free
    let qmap :
        MonoidAlgebra (ZMod p) F →ₐ[ZMod p]
          MonoidAlgebra (ZMod p) FP.Group :=
      GroupAlgebra.mapGroupHom
        (ZMod p) (Presentation.quotientMap FP.toPresentation)
    have hsurj : Function.Surjective qmap := by
      simpa [qmap, GroupAlgebra.mapGroupHom] using
        GroupAlgebra.domain_hom_surjective
          (R := ZMod p) (Presentation.quotientMap FP.toPresentation)
          FP.toPresentation.quotientMap_surjective
    choose Y hY using fun x : FP.Gen => hsurj (y x)
    let B : MonoidAlgebra (ZMod p) F :=
      ∑ x, Y x *
        augmentationDifference (ZMod p) F (FreeGroup.of x)
    have hqB :
        qmap B = 0 := by
      have hqB_boundary :
          qmap B = generatorAugmentationMap FP y := by
        dsimp [B]
        rw [map_sum]
        calc
          ∑ x : FP.Gen,
              qmap
                (Y x * augmentationDifference
                  (ZMod p) F (FreeGroup.of x)) =
            ∑ x : FP.Gen,
              y x *
                (MonoidAlgebra.single
                  (Presentation.generatorImage FP.toPresentation x)
                  (1 : ZMod p) - 1) := by
                    apply Finset.sum_congr rfl
                    intro x _hx
                    rw [map_mul, hY x]
                    simp [qmap, F, augmentationDifference,
                      Presentation.generatorImage]
          _ = generatorAugmentationMap FP
              (∑ x : FP.Gen, Finsupp.single x (y x)) := by
                rw [map_sum]
                simp only [generator_augmentation_single]
          _ = generatorAugmentationMap FP y := by
                rw [← Finsupp.equivFunOnFinite_symm_eq_sum]
                congr 1
                ext x
                simp
      rw [hqB_boundary]
      exact LinearMap.mem_ker.mp hy
    have hrels :
        Set.range (fun r : FP.toPresentation.Relator =>
          (r : FP.toPresentation.Free)) =
          FP.toPresentation.rels := by
      ext r
      constructor
      · rintro ⟨s, rfl⟩
        exact s.property
      · intro hr
        exact ⟨⟨r, hr⟩, rfl⟩
    have hBideal :
        B ∈ GShafar.relatorDifferenceIdeal
          (R := ZMod p) (fun r : FP.toPresentation.Relator =>
            (r : FP.toPresentation.Free)) := by
      rw [relator_difference_algebra
        (R := ZMod p)
        (fun r : FP.toPresentation.Relator =>
          (r : FP.toPresentation.Free))]
      rw [RingHom.mem_ker]
      rw [hrels]
      simpa [GShafar.presentedAlgebra, qmap, F,
        GroupAlgebra.mapGroupHom, Presentation.quotientMap] using hqB
    have hDrange :
        Finsupp.equivFunOnFinite.symm
            (fun x =>
              qmap (algebraFoxDerivative FP x B)) ∈
          LinearMap.range (foxJacobianMap FP) := by
      simpa [qmap, F] using
        derivative_tuple_jacobian
          FP hBideal
    have hDtuple :
        Finsupp.equivFunOnFinite.symm
            (fun x =>
              qmap (algebraFoxDerivative FP x B)) =
          y := by
      apply Finsupp.ext
      intro x
      change
        qmap (algebraFoxDerivative FP x B) = y x
      rw [show algebraFoxDerivative FP x B = Y x by
        exact algebra_derivative_difference FP Y x]
      exact hY x
    simpa [hDtuple] using hDrange

/-- The degree-`m` generator multiplication map

`⊕_x I^m/I^{m+1} → I^{m+1}/I^{m+2}`. -/
def generatorLayerMap [Fact p.Prime] (m : ℕ) :
    (FP.Gen →₀ GroupAlgebra.augmentationLayer (ZMod p) FP.Group m) →ₗ[ZMod p]
      GroupAlgebra.augmentationLayer (ZMod p) FP.Group (m + 1) := by
  exact GroupAlgebra.augmentationGeneratorLayer
    (ZMod p) FP.Group (Presentation.generatorImage FP.toPresentation) m

lemma generator_layer_surjective [Fact p.Prime] [Finite FP.Gen] (m : ℕ) :
    Function.Surjective (generatorLayerMap FP m) := by
  letI := Fintype.ofFinite FP.Gen
  exact GroupAlgebra.augmentation_generator_surjective
    (ZMod p) FP.Group (Presentation.generatorImage FP.toPresentation)
    (Presentation.generator_image_top FP.toPresentation) m

lemma dimensional_augmentation_layer
    [Fact p.Prime] [Finite FP.Gen] (n : ℕ) :
    FiniteDimensional (ZMod p)
      (GroupAlgebra.augmentationLayer (ZMod p) FP.Group n) := by
  exact GroupAlgebra.dimensional_closure_top
    (ZMod p) FP.Group (Presentation.generatorImage FP.toPresentation)
    (Presentation.generator_image_top FP.toPresentation) n

lemma dimensional_generator_domain
    [Fact p.Prime] [Finite FP.Gen] (m : ℕ) :
    FiniteDimensional (ZMod p)
      (FP.Gen →₀ GroupAlgebra.augmentationLayer (ZMod p) FP.Group m) := by
  letI := dimensional_augmentation_layer FP m
  exact Module.Finite.finsupp

lemma dimensional_generator_ker
    [Fact p.Prime] [Finite FP.Gen] (m : ℕ) :
    FiniteDimensional (ZMod p)
      (LinearMap.ker (generatorLayerMap FP m)) := by
  letI := dimensional_generator_domain FP m
  infer_instance

lemma generator_domain_finrank
    [Fact p.Prime] [Finite FP.Gen] (m : ℕ) :
    Module.finrank (ZMod p)
      (FP.Gen →₀ GroupAlgebra.augmentationLayer (ZMod p) FP.Group m)
      =
    FP.generatorCount * layerRank FP m := by
  letI := Fintype.ofFinite FP.Gen
  rw [Module.finrank_finsupp]
  rw [generator_fintype_card FP]
  rfl

set_option synthInstance.maxHeartbeats 200000 in
-- Synthesizing the quotient-kernel module instance is expensive.
noncomputable def generatorLayerRank
    [Fact p.Prime] [Finite FP.Gen] (m : ℕ) : ℕ :=
  Module.finrank (ZMod p) (LinearMap.ker (generatorLayerMap FP m))

set_option synthInstance.maxHeartbeats 200000 in
-- Rank-nullity crosses quotient layers and their finite-dimensional kernel.
lemma generator_rank_nullity
    [Fact p.Prime] [Finite FP.Gen] (m : ℕ) :
    FP.generatorCount * layerRank FP m =
      layerRank FP (m + 1) +
        Module.finrank (ZMod p) (LinearMap.ker (generatorLayerMap FP m)) := by
  letI := dimensional_generator_domain FP m
  rw [← generator_domain_finrank FP m]
  have h := (generatorLayerMap FP m).finrank_range_add_finrank_ker
  rw [LinearMap.range_eq_top.mpr (generator_layer_surjective FP m)] at h
  simpa [layerRank] using h.symm

set_option synthInstance.maxHeartbeats 200000 in
-- Reusing rank-nullity needs the same kernel finite-dimensional synthesis.
lemma generator_shift_contribution
    [Fact p.Prime] [Finite FP.Gen] {n : ℕ} (hn : 0 < n) :
    generatorShiftContribution FP (layerRank FP) n =
      layerRank FP n +
        generatorLayerRank FP (n - 1) := by
  rw [shift_contribution_pos FP (layerRank FP) hn]
  simpa [generatorLayerRank, Nat.sub_add_cancel (by omega : 1 ≤ n)] using
    generator_rank_nullity FP (n - 1)

end

end FPres


namespace Theorems

noncomputable section

variable {p : ℕ} (FP : FPres.{u} p)

/-- Filtered Vinberg form of the Golod-Shafarevich inequality.

For a filtered presentation the meaningful coefficient sequence is the prefix
sum of the augmentation-layer ranks.  A raw-layer statement would require the
separate relator-ideal strictness condition from `PresentedFox`; exact depths of
the individual relators do not provide that condition. -/
theorem inequalities_jennings_fox
    [Fact p.Prime] [Finite FP.Gen] [Fintype FP.toPresentation.Relator]
    (hsilent : FP.depths.degreeOneSilent) :
    FP.gsCoefficientInequalities
      (fun n =>
        ∑ k ∈ Finset.range (n + 1),
          GroupAlgebra.augmentationLayerRank (ZMod p) FP.Group k) := by
  exact
    FPres.gs_jennings_fox
      FP hsilent

/-- The augmentation-layer prefix-rank sequence appearing in the filtered
Vinberg inequality. -/
def prefixRankSequence [Fact p.Prime] :
    ℕ → ℕ :=
  fun n =>
    ∑ k ∈ Finset.range (n + 1),
      GroupAlgebra.augmentationLayerRank (ZMod p) FP.Group k

/-- Unfold the prefix-rank sequence at one degree. -/
@[simp] theorem augmentation_rank_sequence
    [Fact p.Prime] (n : ℕ) :
    prefixRankSequence FP n =
      ∑ k ∈ Finset.range (n + 1),
        GroupAlgebra.augmentationLayerRank (ZMod p) FP.Group k :=
  rfl

/-- The prefix-rank sequence starts at one. -/
@[simp] theorem rank_sequence_zero
    [Fact p.Prime] :
    prefixRankSequence FP 0 = 1 := by
  simp [prefixRankSequence,
    GroupAlgebra.augmentation_rank_zero]

/-- In particular, the initial prefix rank is positive. -/
theorem rank_sequence_pos
    [Fact p.Prime] :
    0 < prefixRankSequence FP 0 := by
  simpa [prefixRankSequence] using
    (GroupAlgebra.augmentation_rank_pos
      (K := ZMod p) (G := FP.Group))

/-- If the presented group is finite, every augmentation-layer prefix rank is
bounded by the cardinality of the group. -/
theorem rank_sequence_upper
    [Fact p.Prime] [Finite FP.Group] :
    FPres.SUBound
      (prefixRankSequence FP) (Nat.card FP.Group) := by
  letI := Fintype.ofFinite FP.Group
  intro n
  simpa [prefixRankSequence, Nat.card_eq_fintype_card] using
    (GroupAlgebra.sum_layer_card (K := ZMod p) (G := FP.Group) (n + 1))

/-- Finite groups therefore give bounded prefix-rank sequences. -/
theorem prefix_rank_sequence
    [Fact p.Prime] [Finite FP.Group] :
    FPres.SBounde
      (prefixRankSequence FP) :=
  ⟨Nat.card FP.Group,
    rank_sequence_upper FP⟩

/-- Named-sequence form of the filtered Jennings-Fox Vinberg inequality. -/
theorem gs_inequalities_fox
    [Fact p.Prime] [Finite FP.Gen] [Fintype FP.toPresentation.Relator]
    (hsilent : FP.depths.degreeOneSilent) :
    FP.gsCoefficientInequalities
      (prefixRankSequence FP) := by
  simpa [prefixRankSequence] using
    inequalities_jennings_fox FP hsilent

/-- A rational certificate is incompatible with the prefix-rank recurrence
when the presented group is finite. -/
theorem not_gs_inequalities
    [Fact p.Prime] [Finite FP.Group] [Fintype FP.toPresentation.Relator]
    (C : FP.RGCert) :
    ¬ FP.gsCoefficientInequalities
      (prefixRankSequence FP) := by
  apply
    FP.inequalities_certificate_bounded
      C (prefix_rank_sequence FP)
  exact rank_sequence_pos FP

/-- A negative rational GS certificate forces the presented group to be infinite. -/
theorem golod_shafarevich_certificate
    [Fact p.Prime] [Finite FP.Gen] [Fintype FP.toPresentation.Relator]
    (hsilent : FP.depths.degreeOneSilent)
    (C : FP.RGCert) :
    Infinite FP.Group := by
  apply not_finite_iff_infinite.mp
  intro hfinite
  letI : Finite FP.Group := hfinite
  exact
    (not_gs_inequalities
      FP C)
      (gs_inequalities_fox
        FP hsilent)

/-- Classical depth-two quadratic Golod--Shafarevich infinitude criterion. -/
theorem golod_shafarevich_silent
    [Fact p.Prime] [Finite FP.Gen] [Finite FP.toPresentation.Relator]
    {d r : ℕ}
    (hd2 : 2 < d)
    (hgen : d ≤ FP.generatorCount)
    (hsilent : FP.depths.degreeOneSilent)
    (hcount : Nat.card FP.toPresentation.Relator ≤ r)
    (hquad : 4 * r < d * d) :
    Infinite FP.Group := by
  letI := Fintype.ofFinite FP.toPresentation.Relator
  let C := FPres.RGCert.depth_two_quadraticbounda
    FP d r hd2 hgen hsilent hcount hquad
  exact golod_shafarevich_certificate FP hsilent C

end

end Theorems

end Towers
