import Mathlib.GroupTheory.FreeGroup.Basic
import Mathlib.GroupTheory.Commutator.Basic
import Mathlib.GroupTheory.Nilpotent
import Mathlib.Algebra.MonoidAlgebra.Basic
import Mathlib.Data.ZMod.Basic
import Mathlib.Algebra.Field.ZMod
import Mathlib.Data.Fintype.Card
import Mathlib.LinearAlgebra.Dimension.Basic
import Mathlib.LinearAlgebra.Quotient.Basic
import Towers.Group.Filtration
import Towers.Group.Presentation
import Towers.Algebra.Augmentation

namespace Towers
namespace Group

universe u v w

/-- A chosen set of generators for a group. -/
abbrev generators (G : Type u) [Group G] : Type u := Set G

/-- The free group on a type of generators. -/
abbrev freeGroups (α : Type u) : Type u := FreeGroup α

/-- Relators for generators `α`: a set of words in the free group. -/
abbrev relators (α : Type u) : Type u := Set (FreeGroup α)


namespace generators

/-- The subgroup generated by a chosen generator set. -/
def subgroup {G : Type u} [Group G] (S : generators G) : Subgroup G :=
  Subgroup.closure S

/-- Predicate that a chosen generator set generates the whole group. -/
def generates {G : Type u} [Group G] (S : generators G) : Prop :=
  subgroup S = ⊤

/-- The inclusion of generators into the generated subgroup. -/
def inclusion {G : Type u} [Group G] (S : generators G) : S → subgroup S :=
  fun s => ⟨s.1, Subgroup.subset_closure s.2⟩

end generators

namespace relators

/-- Normal closure of a set of relators in the free group. -/
def normalClosure {α : Type u} (R : relators α) : Subgroup (FreeGroup α) :=
  Subgroup.normalClosure R

/-- The presented quotient determined by a relator set. -/
abbrev quotient {α : Type u} (R : relators α) : Type u :=
  FreeGroup α ⧸ normalClosure R

end relators

/-- The coefficient field `𝔽_p`, represented as `ZMod p`.
The prime fact is part of the alias so uses cannot silently instantiate
field-level constructions at composite moduli. -/
abbrev cFFp (p : ℕ) [Fact p.Prime] : Type := ZMod p

instance cFFp.instField (p : ℕ) [Fact p.Prime] : Field (cFFp p) :=
  inferInstance

/-- The set of `p`-th powers in a group. -/
def pPowers (p : ℕ) (G : Type u) [Group G] : Set G :=
  Set.range (fun g : G => g ^ p)

theorem mem_pPowers {p : ℕ} {G : Type u} [Group G] {x : G} :
    x ∈ pPowers p G ↔ ∃ g : G, g ^ p = x := Iff.rfl

/-- A finite `p`-group, expressed as a predicate on a group type. -/
def fPGroups (p : ℕ) (G : Type u) [Group G] : Prop :=
  Nat.Prime p ∧ Finite G ∧ (∃ n : ℕ, Nat.card G = p ^ n)

theorem fPGroups.prime {p : ℕ} {G : Type u} [Group G]
    (h : fPGroups p G) : Nat.Prime p := h.1

theorem fPGroups.finite {p : ℕ} {G : Type u} [Group G]
    (h : fPGroups p G) : Finite G := h.2.1

theorem fPGroups.card_power {p : ℕ} {G : Type u} [Group G]
    (h : fPGroups p G) : ∃ n : ℕ, Nat.card G = p ^ n := h.2.2

theorem fPGroups.element_order_power {p : ℕ} {G : Type u} [Group G]
    (h : fPGroups p G) (g : G) : ∃ k : ℕ, g ^ (p ^ k) = 1 := by
  rcases h.card_power with ⟨k, hk⟩
  refine ⟨k, ?_⟩
  rw [← hk]
  exact pow_card_eq_one'

/-- A finite `p`-group hypothesis supplies the usual `Fact` witness for `p` prime. -/
@[reducible] def fPGroups.fact_prime {p : ℕ} {G : Type u} [Group G]
    (h : fPGroups p G) : Fact p.Prime :=
  ⟨h.prime⟩

/-- The group algebra of `G` over a coefficient semiring `R`. -/
abbrev groupAlgebra (R : Type u) (G : Type v) [Semiring R] [Group G] : Type (max u v) :=
  MonoidAlgebra R G

/-- A family of Fox derivatives with the defining product rule and generator
values.  This is no longer an arbitrary family of functions. -/
structure fDeriva (R : Type u) (α : Type v) [Ring R] [DecidableEq α] where
  deriv : α → FreeGroup α → MonoidAlgebra R (FreeGroup α)
  deriv_one : ∀ a, deriv a 1 = 0
  deriv_mul : ∀ a (u v : FreeGroup α),
    deriv a (u * v) = deriv a u + MonoidAlgebra.single u (1 : R) * deriv a v
  deriv_generator : ∀ a x : α,
    deriv a (FreeGroup.of x) =
      (if x = a then MonoidAlgebra.single 1 (1 : R) else 0)
  deriv_inv : ∀ a (u : FreeGroup α),
    deriv a u⁻¹ = - MonoidAlgebra.single u⁻¹ (1 : R) * deriv a u

/-- Fox derivative inverse rule, as a named accessor. -/
theorem fDeriva.deriv_inv_apply {R : Type u} {α : Type v} [Ring R] [DecidableEq α]
    (D : fDeriva R α) (a : α) (u : FreeGroup α) :
    D.deriv a u⁻¹ = - MonoidAlgebra.single u⁻¹ (1 : R) * D.deriv a u :=
  D.deriv_inv a u

/-- A set which algebraically generates the group. -/
def generatingSet (G : Type u) [Group G] (S : Set G) : Prop :=
  Subgroup.closure S = ⊤

/-- Inclusion-minimal generating set: no proper subset still generates. -/
def inclusionMinimalGenerating (G : Type u) [Group G] (S : Set G) : Prop :=
  generatingSet G S ∧ ∀ T : Set G, T ⊂ S → ¬ generatingSet G T

/-- Cardinal-minimal generating set: no generating set has smaller cardinality.
This is the usual notion of a minimal number of generators; it is intentionally
separate from inclusion-minimality, especially for infinite groups. -/
def minimalGeneratingSet (G : Type u) [Group G] (S : Set G) : Prop :=
  generatingSet G S ∧
    ∀ T : Set G, generatingSet G T → Cardinal.mk S ≤ Cardinal.mk T

/-- A generating set satisfying both common minimality notions. -/
def stronglyMinimalGenerating (G : Type u) [Group G] (S : Set G) : Prop :=
  inclusionMinimalGenerating G S ∧ minimalGeneratingSet G S

/-- A filtration degree is a natural-number index. -/
abbrev filtrationDegree : Type := ℕ

/-- A cutoff degree is a filtration degree used to truncate constructions. -/
abbrev cutoffDegree : Type := ℕ

/-- The `n`th quotient layer `F n / F (n+1)` of a descending filtration.  This is
one of the first places where normality infrastructure matters: Lean needs the
subgroup `F (n+1)` viewed inside `F n`, together with its normality instance. -/
abbrev filtrationLayer {G : Type u} [Group G] (F : DFilt G) (n : ℕ) : Type u :=
  (F n) ⧸ ((F (n + 1)).subgroupOf (F n))

/-- Graded pieces coming from a particular filtration, with an explicit
identification with the quotient layers.  Keeping the equivalence as data lets
later constructions use alternate normal forms for the same layer. -/
structure gPieces (G : Type u) [Group G] (F : DFilt G) where
  piece : ℕ → Type u
  equivLayer : ∀ n, piece n ≃ filtrationLayer F n
  /-- Send a representative in `F n` to its chosen model of the quotient layer. -/
  ofTerm : ∀ n, F n → piece n := fun n x => (equivLayer n).symm (QuotientGroup.mk x)
  /-- The chosen model has representatives in the filtration term. -/
  ofTerm_surjective : ∀ n, Function.Surjective (ofTerm n)

/-- The chosen representative map onto a graded piece is surjective. -/
theorem gPieces.ofTerm_surj {G : Type u} [Group G]
    {F : DFilt G} (P : gPieces G F) (n : ℕ) :
    Function.Surjective (P.ofTerm n) :=
  P.ofTerm_surjective n

/-- The canonical graded pieces of a filtration. -/
noncomputable def canonicalGradedPieces {G : Type u} [Group G]
    (F : DFilt G) : gPieces G F where
  piece := fun n => filtrationLayer F n
  equivLayer := fun _ => Equiv.refl _
  ofTerm := fun _ x => QuotientGroup.mk x
  ofTerm_surjective := fun n => by
    simpa using QuotientGroup.mk'_surjective ((F (n + 1)).subgroupOf (F n))

/-- An associated graded object of a filtered group: a filtration together with
chosen models for its successive quotient layers.  Multiplication/bracket maps
are tied to representatives by explicit well-definedness/closure certificates. -/
structure aGObject (G : Type u) [Group G] where
  filtration : DFilt G
  pieces : gPieces G filtration := canonicalGradedPieces filtration
  oneClass : ∀ n, pieces.piece n
  commutatorClass : ∀ m n, pieces.piece m → pieces.piece n → pieces.piece (m + n)
  powerClass : ∀ k n, pieces.piece n → pieces.piece (k * n)
  oneClass_eq : ∀ n, oneClass n = pieces.ofTerm n ⟨1, (filtration n).one_mem⟩
  commutator_mem : ∀ m n (x : filtration m) (y : filtration n),
    x.1 * y.1 * x.1⁻¹ * y.1⁻¹ ∈ filtration (m + n)
  commutatorClass_mk : ∀ m n (x : filtration m) (y : filtration n),
    commutatorClass m n (pieces.ofTerm m x) (pieces.ofTerm n y) =
      pieces.ofTerm (m + n)
        ⟨x.1 * y.1 * x.1⁻¹ * y.1⁻¹, commutator_mem m n x y⟩
  power_mem : ∀ k n (x : filtration n), x.1 ^ k ∈ filtration (k * n)
  powerClass_mk : ∀ k n (x : filtration n),
    powerClass k n (pieces.ofTerm n x) =
      pieces.ofTerm (k * n) ⟨x.1 ^ k, power_mem k n x⟩
  commutator_one_left : ∀ m n x, commutatorClass m n (oneClass m) x = oneClass (m + n)
  commutator_one_right : ∀ m n x, commutatorClass m n x (oneClass n) = oneClass (m + n)
  power_one : ∀ k n, powerClass k n (oneClass n) = oneClass (k * n)

/-- Left unit law for the recorded commutator operation. -/
theorem aGObject.comm_one_leftapply {G : Type u} [Group G]
    (A : aGObject G) (m n : ℕ) (x : A.pieces.piece n) :
    A.commutatorClass m n (A.oneClass m) x = A.oneClass (m + n) :=
  A.commutator_one_left m n x

/-- Right unit law for the recorded commutator operation. -/
theorem aGObject.comm_one_rightapply {G : Type u} [Group G]
    (A : aGObject G) (m n : ℕ) (x : A.pieces.piece m) :
    A.commutatorClass m n x (A.oneClass n) = A.oneClass (m + n) :=
  A.commutator_one_right m n x

/-- Powers of the distinguished unit class remain distinguished unit classes. -/
theorem aGObject.power_one_apply {G : Type u} [Group G]
    (A : aGObject G) (k n : ℕ) :
    A.powerClass k n (A.oneClass n) = A.oneClass (k * n) :=
  A.power_one k n

/-- The distinguished unit class is represented by the identity element. -/
theorem aGObject.one_classeq_termone {G : Type u} [Group G]
    (A : aGObject G) (n : ℕ) :
    A.oneClass n = A.pieces.ofTerm n ⟨1, (A.filtration n).one_mem⟩ :=
  A.oneClass_eq n

/-- The recorded commutator operation agrees with the class of the group commutator
on displayed representatives. -/
theorem aGObject.comm_class_term {G : Type u} [Group G]
    (A : aGObject G) (m n : ℕ) (x : A.filtration m) (y : A.filtration n) :
    A.commutatorClass m n (A.pieces.ofTerm m x) (A.pieces.ofTerm n y) =
      A.pieces.ofTerm (m + n)
        ⟨x.1 * y.1 * x.1⁻¹ * y.1⁻¹, A.commutator_mem m n x y⟩ :=
  A.commutatorClass_mk m n x y

/-- The recorded power operation agrees with the class of the group power on
displayed representatives. -/
theorem aGObject.power_class_term {G : Type u} [Group G]
    (A : aGObject G) (k n : ℕ) (x : A.filtration n) :
    A.powerClass k n (A.pieces.ofTerm n x) =
      A.pieces.ofTerm (k * n) ⟨x.1 ^ k, A.power_mem k n x⟩ :=
  A.powerClass_mk k n x


/-- A group homomorphism, named to match the vocabulary list. -/
abbrev groupHomomorphism (G : Type u) (H : Type v) [Group G] [Group H] : Type (max u v) :=
  G →* H

/-- A surjective group homomorphism.  The kernel is not an independent field;
it is definitionally the kernel of `hom`, preventing inconsistent quotient data. -/
structure sHoma (G : Type u) (H : Type v) [Group G] [Group H] where
  hom : G →* H
  surjective : Function.Surjective hom
  quotientEquiv : (G ⧸ MonoidHom.ker hom) ≃* H
  quotient_comm : ∀ g : G, quotientEquiv (QuotientGroup.mk g) = hom g


/-- Canonical packaged epimorphism from a surjective homomorphism, using the first
isomorphism theorem for the quotient equivalence. -/
noncomputable def sHoma.ofSurjective {G : Type u} {H : Type v}
    [Group G] [Group H] (f : G →* H) (hf : Function.Surjective f) :
    sHoma G H where
  hom := f
  surjective := hf
  quotientEquiv := QuotientGroup.quotientKerEquivOfSurjective (φ := f) hf
  quotient_comm := by
    intro g
    simp [QuotientGroup.quotientKerEquivOfSurjective,
      QuotientGroup.quotientKerEquivOfRightInverse]

@[simp] theorem sHoma.ofSurjective_hom {G : Type u} {H : Type v}
    [Group G] [Group H] (f : G →* H) (hf : Function.Surjective f) :
    (sHoma.ofSurjective f hf).hom = f := rfl

/-- The actual kernel of a packaged epimorphism. -/
abbrev sHoma.kernel {G : Type u} {H : Type v} [Group G] [Group H]
    (f : sHoma G H) : Subgroup G :=
  MonoidHom.ker f.hom

/-- Named surjectivity projection for a packaged epimorphism. -/
theorem sHoma.surj {G : Type u} {H : Type v} [Group G] [Group H]
    (f : sHoma G H) : Function.Surjective f.hom :=
  f.surjective

/-- The quotient equivalence commutes with the displayed homomorphism. -/
theorem sHoma.quotient_comm_apply {G : Type u} {H : Type v}
    [Group G] [Group H] (f : sHoma G H) (g : G) :
    f.quotientEquiv (QuotientGroup.mk g) = f.hom g :=
  f.quotient_comm g

/-- Kernel membership is equality to one under the displayed homomorphism. -/
theorem sHoma.mem_kernel_iff {G : Type u} {H : Type v}
    [Group G] [Group H] (f : sHoma G H) (g : G) :
    g ∈ f.kernel ↔ f.hom g = 1 := Iff.rfl

/-- Truncation of an indexed family at degree `N`, retaining only bounded degrees. -/
def truncation (A : ℕ → Type u) (N : ℕ) : Type u :=
  (n : {n : ℕ // n ≤ N}) → A n.1

/-- A binary product operation without assuming commutativity. -/
abbrev noncommutativeProduct (α : Type u) [Mul α] : α → α → α := (· * ·)

/-- The set of group commutators `[x,y] = x*y*x⁻¹*y⁻¹`. -/
def commutators (G : Type u) [Group G] : Set G :=
  Set.range (fun p : G × G => p.1 * p.2 * p.1⁻¹ * p.2⁻¹)

/-- The positive-indexed lower central term `γ_i(G)` used in the classical
Zassenhaus formula.  Mathlib's `Subgroup.lowerCentralSeries G` starts at index `0`, so
`γ_1(G)` is `Subgroup.lowerCentralSeries G 0 = G`. -/
abbrev zassenhausLowerTerm (G : Type u) [Group G] (i : ℕ) : Subgroup G :=
  Subgroup.lowerCentralSeries G (i - 1)

@[simp] theorem zassenhaus_lower_term (G : Type u) [Group G] :
    zassenhausLowerTerm G 1 = ⊤ := by
  simp [zassenhausLowerTerm, Subgroup.lowerCentralSeries_zero]

/-- Generators for the classical Zassenhaus formula: `p^j`-powers of elements in
the positive-indexed lower central term `γ_i(G)` with `i * p^j ≥ n`.  Taking
normal closure gives a concrete subgroup candidate for `D_n`. -/
def zassenhausFormulaGenerators (p n : ℕ) (G : Type u) [Group G] : Set G :=
  {x | Nat.Prime p ∧ 0 < n ∧
    ∃ (i j : ℕ) (y : G), 0 < i ∧ y ∈ zassenhausLowerTerm G i ∧
      n ≤ i * p ^ j ∧ x = y ^ (p ^ j)}

/-- The subgroup given by the standard product/closure formula for the nth
Zassenhaus term.  We use normal closure, which is the Lean-friendly version of
the product of all indicated normal subgroups. -/
def zFTerm (p n : ℕ) (G : Type u) [Group G] : Subgroup G :=
  Subgroup.normalClosure (zassenhausFormulaGenerators p n G)

instance zFTerm.instNormal (p n : ℕ) (G : Type u) [Group G] :
    (zFTerm p n G).Normal :=
  Subgroup.normalClosure_normal

@[simp] theorem formula_zero_bot (p : ℕ) (G : Type u) [Group G] :
    zFTerm p 0 G = ⊥ := by
  rw [zFTerm]
  apply le_antisymm
  · apply Subgroup.normalClosure_le_normal
    intro x hx
    rcases hx with ⟨_hp, hn, _⟩
    omega
  · exact bot_le

/-- At a nonprime modulus, the classical formula has no generators. -/
theorem formula_bot_not
    {p n : ℕ} (hp : ¬Nat.Prime p) (G : Type u) [Group G] :
    zFTerm p n G = ⊥ := by
  rw [zFTerm]
  apply le_antisymm
  · apply Subgroup.normalClosure_le_normal
    intro x hx
    exact (hp hx.1).elim
  · exact bot_le

/-- Each classical formula generator belongs to the corresponding formula term. -/
theorem formula_subset_term (p n : ℕ) (G : Type u) [Group G] :
    zassenhausFormulaGenerators p n G ⊆ zFTerm p n G :=
  Subgroup.subset_normalClosure

/-- A lower-central element raised to a sufficiently large prime power belongs to the
corresponding classical formula term. -/
theorem formula_term_central
    {p n i j : ℕ} [Fact p.Prime] {G : Type u} [Group G]
    (hn : 0 < n) {y : G}
    (hy : y ∈ zassenhausLowerTerm G i)
    (hweight : n ≤ i * p ^ j) :
    y ^ (p ^ j) ∈ zFTerm p n G := by
  apply Subgroup.subset_normalClosure
  refine ⟨Fact.out, hn, i, j, y, ?_, hy, hweight, rfl⟩
  by_contra hi
  have : i = 0 := Nat.eq_zero_of_not_pos hi
  subst i
  simp at hweight
  omega

/-- Lower-central terms occur at their expected depths in the classical formula. -/
theorem zassenhaus_term_formula
    {p n i : ℕ} [Fact p.Prime] {G : Type u} [Group G]
    (hn : 0 < n) (hni : n ≤ i) :
    zassenhausLowerTerm G i ≤ zFTerm p n G := by
  intro y hy
  simpa using
    (formula_term_central
      (p := p) (n := n) (i := i) (j := 0) hn hy (by simpa using hni))

/-- A positive lower-central term belongs to the matching classical formula term. -/
theorem term_formula_self
    {p i : ℕ} [Fact p.Prime] {G : Type u} [Group G]
    (hi : 0 < i) :
    zassenhausLowerTerm G i ≤ zFTerm p i G :=
  zassenhaus_term_formula hi le_rfl

/-- Positive-indexed classical formula terms form a descending chain. -/
theorem formula_term_antitone
    {p m n : ℕ} {G : Type u} [Group G]
    (hm : 0 < m) (hmn : m ≤ n) :
    zFTerm p n G ≤ zFTerm p m G := by
  apply Subgroup.normalClosure_mono
  rintro x ⟨hp, _hn, i, j, y, hi, hy, hweight, rfl⟩
  exact ⟨hp, hm, i, j, y, hi, hy, hmn.trans hweight, rfl⟩

/-- The degree-one classical formula term is the whole group. -/
@[simp] theorem formula_term_top
    {p : ℕ} [Fact p.Prime] (G : Type u) [Group G] :
    zFTerm p 1 G = ⊤ := by
  apply top_unique
  intro g _hg
  apply Subgroup.subset_normalClosure
  refine ⟨Fact.out, by norm_num, 1, 0, g, by norm_num, ?_, by norm_num, ?_⟩
  · simp [zassenhausLowerTerm, Subgroup.lowerCentralSeries_zero]
  · simp

/-- Group homomorphisms preserve classical formula terms. -/
theorem formula_term
    {G : Type u} {H : Type v} [Group G] [Group H]
    (f : G →* H) (p n : ℕ) :
    Subgroup.map f (zFTerm p n G) ≤ zFTerm p n H := by
  rw [Subgroup.map_le_iff_le_comap]
  apply Subgroup.normalClosure_le_normal
  rintro x ⟨hp, hn, i, j, y, hi, hy, hweight, rfl⟩
  apply Subgroup.subset_normalClosure
  refine ⟨hp, hn, i, j, f y, hi, ?_, hweight, by simp⟩
  exact Subgroup.lowerCentralSeries.map f (i - 1) (Subgroup.mem_map_of_mem f hy)

private theorem lower_surjective_formula
    {G : Type u} {H : Type v} [Group G] [Group H]
    (f : G →* H) (hf : Function.Surjective f) (i : ℕ) :
    Subgroup.lowerCentralSeries H i ≤ Subgroup.map f (Subgroup.lowerCentralSeries G i) := by
  induction i with
  | zero =>
      rw [Subgroup.lowerCentralSeries_zero, Subgroup.lowerCentralSeries_zero]
      exact (Subgroup.map_top_of_surjective f hf).ge
  | succ i ih =>
      change
        ⁅Subgroup.lowerCentralSeries H i, (⊤ : Subgroup H)⁆ ≤
          Subgroup.map f ⁅Subgroup.lowerCentralSeries G i, (⊤ : Subgroup G)⁆
      exact
        Subgroup.commutator_le_map_commutator ih
          ((Subgroup.map_top_of_surjective f hf).ge)

/-- Surjective homomorphisms map classical formula terms onto the target term. -/
theorem formula_term_surjective
    {G : Type u} {H : Type v} [Group G] [Group H]
    (f : G →* H) (hf : Function.Surjective f) (p n : ℕ) :
    Subgroup.map f (zFTerm p n G) = zFTerm p n H := by
  apply le_antisymm
  · exact formula_term f p n
  · haveI : (Subgroup.map f (zFTerm p n G)).Normal :=
      Subgroup.Normal.map inferInstance f hf
    apply Subgroup.normalClosure_le_normal
    rintro x ⟨hp, hn, i, j, y, hi, hy, hweight, rfl⟩
    have hyMap :
        y ∈ Subgroup.map f (zassenhausLowerTerm G i) :=
      lower_surjective_formula f hf (i - 1) hy
    rcases hyMap with ⟨y0, hy0, hyEq⟩
    refine ⟨y0 ^ (p ^ j), ?_, ?_⟩
    · apply Subgroup.subset_normalClosure
      exact ⟨hp, hn, i, j, y0, hi, hy0, hweight, rfl⟩
    · simp [hyEq]

/-- Classical formula terms of a subgroup map into the ambient formula terms. -/
theorem formula_term_subtype
    {G : Type u} [Group G] (H : Subgroup G) (p n : ℕ) :
    Subgroup.map H.subtype (zFTerm p n H) ≤ zFTerm p n G :=
  formula_term H.subtype p n

/-- A classical formula term vanishing in the ambient group also vanishes in every
subgroup. -/
theorem zassenhaus_formula_bot
    {p n : ℕ} {G : Type u} [Group G] {H : Subgroup G}
    (hG : zFTerm p n G = ⊥) :
    zFTerm p n H = ⊥ := by
  rw [Subgroup.eq_bot_iff_forall]
  intro x hx
  apply Subtype.ext
  have hxMap :
      H.subtype x ∈ zFTerm p n G :=
    formula_term_subtype H p n (Subgroup.mem_map_of_mem H.subtype hx)
  have : H.subtype x ∈ (⊥ : Subgroup G) := by
    simpa [hG] using hxMap
  simpa using this

/-- Quotienting by a classical formula term kills that formula term. -/
theorem formula_self_bot
    (p n : ℕ) (G : Type u) [Group G] :
    zFTerm p n (G ⧸ zFTerm p n G) = ⊥ := by
  let q : G →* G ⧸ zFTerm p n G :=
    QuotientGroup.mk' (zFTerm p n G)
  rw [← formula_term_surjective q (QuotientGroup.mk'_surjective _) p n]
  rw [Subgroup.eq_bot_iff_forall]
  rintro _ ⟨x, hx, rfl⟩
  exact (QuotientGroup.eq_one_iff x).mpr hx

/-- If a positive classical formula term vanishes, then the matching lower-central
term vanishes as well. -/
theorem term_bot_formula
    {p : ℕ} [Fact p.Prime] {G : Type u} [Group G] {n : ℕ}
    (hn : 0 < n)
    (hZ : zFTerm p n G = ⊥) :
    zassenhausLowerTerm G n = ⊥ := by
  rw [Subgroup.eq_bot_iff_forall]
  intro x hx
  have hxFormula :
      x ∈ zFTerm p n G :=
    term_formula_self hn hx
  simpa [hZ] using hxFormula

/-- If a positive classical formula term vanishes, every sufficiently large
prime-power exponent kills the group. -/
theorem formula_term_bot
    {p : ℕ} [Fact p.Prime] {G : Type u} [Group G] {n j : ℕ}
    (hn : 0 < n) (hle : n ≤ p ^ j)
    (hZ : zFTerm p n G = ⊥) (g : G) :
    g ^ (p ^ j) = 1 := by
  have hgLower : g ∈ zassenhausLowerTerm G 1 := by
    simp
  have hgFormula :
      g ^ (p ^ j) ∈ zFTerm p n G :=
    formula_term_central hn hgLower (by simpa using hle)
  simpa [hZ] using hgFormula

/-- Laws certifying that a descending filtration behaves like the Zassenhaus
filtration at prime `p`: commutators add degrees, `p`th powers multiply degrees,
and optionally each term agrees with the explicit lower-central/power formula. -/
structure zFLaws (p : ℕ) (G : Type u) [Group G]
    (F : DFilt G) : Prop where
  prime : Nat.Prime p
  one_eq_top : F 1 = ⊤
  commutator_mem : ∀ {m n : ℕ} {x y : G}, x ∈ F m → y ∈ F n →
    x * y * x⁻¹ * y⁻¹ ∈ F (m + n)
  pow_mem : ∀ {n : ℕ} {x : G}, x ∈ F n → x ^ p ∈ F (p * n)
  formula_le : ∀ {n}, 0 < n → zFTerm p n G ≤ F n
  le_formula : ∀ {n}, 0 < n → F n ≤ zFTerm p n G

/-- A certified Zassenhaus filtration starts with the whole group in degree one. -/
theorem zFLaws.one_eq_top' {p : ℕ} {G : Type u} [Group G]
    {F : DFilt G} (L : zFLaws p G F) : F 1 = ⊤ :=
  L.one_eq_top

/-- A certified Zassenhaus filtration supplies the usual prime fact for its exponent. -/
@[reducible] def zFLaws.fact_prime {p : ℕ} {G : Type u} [Group G]
    {F : DFilt G} (L : zFLaws p G F) : Fact p.Prime :=
  ⟨L.prime⟩

/-- A reordering witness for two lists: they differ by a permutation. -/
def reordering {α : Type u} (xs ys : List α) : Prop := xs.Perm ys


/-- Characteristic `p` as a proposition on a semiring. -/
abbrev characteristicP (R : Type u) [Semiring R] (p : ℕ) : Prop := CharP R p

/-- A sequence of coefficients of a formal power series. -/
abbrev powerSeriesCoefficients (R : Type u) : Type u := ℕ → R

/-- Kernel of a group homomorphism. -/
abbrev kernel {G : Type u} {H : Type v} [Group G] [Group H] (f : G →* H) : Subgroup G :=
  MonoidHom.ker f

/-- A normal subgroup packaged with its normality witness. -/
structure nSubgro (G : Type u) [Group G] where
  carrier : Subgroup G
  normal' : carrier.Normal

attribute [instance] nSubgro.normal'

/-- Packaged normal subgroups are closed under conjugation. -/
theorem nSubgro.conj_mem {G : Type u} [Group G] (N : nSubgro G)
    {x : G} (hx : x ∈ N.carrier) (g : G) : g * x * g⁻¹ ∈ N.carrier :=
  Subgroup.Normal.conj_mem N.normal' x hx g

/-- Intersection of packaged normal subgroups. -/
def nSubgro.inf {G : Type u} [Group G] (N M : nSubgro G) : nSubgro G where
  carrier := N.carrier ⊓ M.carrier
  normal' := by infer_instance

@[simp] theorem nSubgro.mem_inf {G : Type u} [Group G]
    (N M : nSubgro G) {x : G} :
    x ∈ (N.inf M).carrier ↔ x ∈ N.carrier ∧ x ∈ M.carrier := Iff.rfl

/-- The quotient group by a packaged normal subgroup. -/
abbrev quotientGroup {G : Type u} [Group G] (N : nSubgro G) : Type u :=
  G ⧸ N.carrier

/-- Canonical projection attached to a packaged normal subgroup. -/
def nSubgro.projection {G : Type u} [Group G] (N : nSubgro G) :
    G →* quotientGroup N :=
  QuotientGroup.mk' N.carrier

/-- The canonical quotient projection is surjective. -/
theorem nSubgro.projection_surjective {G : Type u} [Group G] (N : nSubgro G) :
    Function.Surjective N.projection := by
  simpa [nSubgro.projection] using QuotientGroup.mk'_surjective N.carrier

/-- Its kernel is exactly the packaged subgroup. -/
theorem nSubgro.ker_projection {G : Type u} [Group G] (N : nSubgro G) :
    MonoidHom.ker N.projection = N.carrier := by
  ext g
  simp [nSubgro.projection]

/-- If `N ≤ M`, there is a canonical map `G/N → G/M`. -/
noncomputable def quotientMapLE {G : Type u} [Group G]
    (N M : nSubgro G) (h : N.carrier ≤ M.carrier) :
    quotientGroup N →* quotientGroup M := by
  refine QuotientGroup.lift N.carrier M.projection ?_
  intro x hx
  change M.projection x = 1
  rw [show M.projection = QuotientGroup.mk' M.carrier from rfl]
  exact (QuotientGroup.eq_one_iff (N := M.carrier) x).2 (h hx)

@[simp] theorem quotient_mk {G : Type u} [Group G]
    (N M : nSubgro G) (h : N.carrier ≤ M.carrier) (x : G) :
    quotientMapLE N M h (QuotientGroup.mk' N.carrier x) = QuotientGroup.mk' M.carrier x := by
  simp [quotientMapLE, nSubgro.projection]

@[simp] theorem quotient_self {G : Type u} [Group G]
    (N : nSubgro G) :
    quotientMapLE N N (le_rfl) = MonoidHom.id (quotientGroup N) := by
  ext x
  simp [quotientMapLE, nSubgro.projection]

theorem of_le_surjective {G : Type u} [Group G]
    (N M : nSubgro G) (h : N.carrier ≤ M.carrier) :
    Function.Surjective (quotientMapLE N M h) := by
  intro q
  refine QuotientGroup.induction_on q ?_
  intro x
  exact ⟨QuotientGroup.mk' N.carrier x, by simp [quotientMapLE, nSubgro.projection]⟩

@[simp] theorem of_le_comp {G : Type u} [Group G]
    (N M K : nSubgro G) (hNM : N.carrier ≤ M.carrier)
    (hMK : M.carrier ≤ K.carrier) :
    (quotientMapLE M K hMK).comp (quotientMapLE N M hNM) =
      quotientMapLE N K (le_trans hNM hMK) := by
  ext x
  simp [quotientMapLE, nSubgro.projection]

/-- A finite quotient of a group. -/
structure fQuotie (G : Type u) [Group G] where
  normal : nSubgro G
  finite' : Finite (quotientGroup normal)
  projection_surjective : Function.Surjective (QuotientGroup.mk' normal.carrier) :=
    QuotientGroup.mk'_surjective normal.carrier

/-- Build a finite quotient from a packaged normal subgroup and a finiteness instance. -/
def fQuotie.ofNormal {G : Type u} [Group G] (N : nSubgro G)
    (hfin : Finite (quotientGroup N)) : fQuotie G where
  normal := N
  finite' := hfin
  projection_surjective := N.projection_surjective

/-- The canonical projection of a finite quotient. -/
def fQuotie.projection {G : Type u} [Group G] (Q : fQuotie G) :
    G →* quotientGroup Q.normal := Q.normal.projection

/-- The canonical projection of a finite quotient is surjective. -/
theorem fQuotie.projection_surj {G : Type u} [Group G]
    (Q : fQuotie G) : Function.Surjective Q.projection :=
  Q.normal.projection_surjective


/-- Its kernel is the displayed normal subgroup. -/
theorem fQuotie.ker_projection {G : Type u} [Group G] (Q : fQuotie G) :
    MonoidHom.ker Q.projection = Q.normal.carrier := Q.normal.ker_projection

/-- Refa of finite quotients by inclusion of kernels. -/
def fQuotie.refines {G : Type u} [Group G] (Q R : fQuotie G) : Prop :=
  Q.normal.carrier ≤ R.normal.carrier

@[refl] theorem fQuotie.refines_refl {G : Type u} [Group G]
    (Q : fQuotie G) : Q.refines Q := le_rfl

@[trans] theorem fQuotie.refines_trans {G : Type u} [Group G]
    {Q R S : fQuotie G} (hQR : Q.refines R) (hRS : R.refines S) :
    Q.refines S := le_trans hQR hRS

/-- Transition map between nested finite quotients. -/
noncomputable def fQuotie.transition {G : Type u} [Group G]
    {Q R : fQuotie G} (h : Q.refines R) :
    quotientGroup Q.normal →* quotientGroup R.normal :=
  quotientMapLE Q.normal R.normal h

@[simp] theorem fQuotie.transition_mk {G : Type u} [Group G]
    {Q R : fQuotie G} (h : Q.refines R) (g : G) :
    fQuotie.transition h (Q.projection g) = R.projection g := by
  simpa [fQuotie.transition, fQuotie.projection]
    using quotient_mk Q.normal R.normal h g

theorem fQuotie.transition_comp_projection {G : Type u} [Group G]
    {Q R : fQuotie G} (h : Q.refines R) :
    (fQuotie.transition h).comp Q.projection = R.projection := by
  ext g
  exact fQuotie.transition_mk h g

/-- Transition maps between nested finite quotients are surjective. -/
theorem fQuotie.transition_surj {G : Type u} [Group G]
    {Q R : fQuotie G} (h : Q.refines R) :
    Function.Surjective (fQuotie.transition h) :=
  of_le_surjective Q.normal R.normal h


@[simp] theorem fQuotie.transition_self {G : Type u} [Group G]
    (Q : fQuotie G) :
    fQuotie.transition (Q.refines_refl) = MonoidHom.id (quotientGroup Q.normal) :=
  quotient_self Q.normal

@[simp] theorem fQuotie.transition_comp {G : Type u} [Group G]
    {Q R S : fQuotie G} (hQR : Q.refines R) (hRS : R.refines S) :
    (fQuotie.transition hRS).comp (fQuotie.transition hQR) =
      fQuotie.transition (fQuotie.refines_trans hQR hRS) := by
  simp [fQuotie.transition, of_le_comp]

/-- A quotient together with a cutoff degree, including the canonical projection
and the assertion that this is the quotient used at that truncation level. -/
structure cQuotie (G : Type u) [Group G] where
  quotient : nSubgro G
  cutoff : ℕ
  projection : G →* quotientGroup quotient := QuotientGroup.mk' quotient.carrier
  projection_surjective : Function.Surjective projection
  /-- Cut quotients are meant to be finite computational truncations. -/
  finite_quotient : Finite (quotientGroup quotient)
  /-- The named projection really has the packaged subgroup as kernel. -/
  kernel_eq : MonoidHom.ker projection = quotient.carrier

/-- Build a cut quotient from a finite packaged normal subgroup. -/
def cQuotie.ofNormal {G : Type u} [Group G] (N : nSubgro G) (c : ℕ)
    (hfin : Finite (quotientGroup N)) : cQuotie G where
  quotient := N
  cutoff := c
  projection := N.projection
  projection_surjective := N.projection_surjective
  finite_quotient := hfin
  kernel_eq := N.ker_projection

/-- Forget a cut quotient to a finite quotient. -/
def cQuotie.toFiniteQuotient {G : Type u} [Group G] (Q : cQuotie G) :
    fQuotie G where
  normal := Q.quotient
  finite' := Q.finite_quotient
  projection_surjective := Q.quotient.projection_surjective

/-- Kernel-refinement relation for cut quotients. -/
def cQuotie.refines {G : Type u} [Group G] (Q R : cQuotie G) : Prop :=
  Q.quotient.carrier ≤ R.quotient.carrier

@[refl] theorem cQuotie.refines_refl {G : Type u} [Group G]
    (Q : cQuotie G) : Q.refines Q := le_rfl

@[trans] theorem cQuotie.refines_trans {G : Type u} [Group G]
    {Q R S : cQuotie G} (hQR : Q.refines R) (hRS : R.refines S) :
    Q.refines S := le_trans hQR hRS

/-- Kernel membership for the displayed projection of a cut quotient. -/
theorem cQuotie.mem_kernel_iff {G : Type u} [Group G]
    (Q : cQuotie G) (g : G) :
    g ∈ MonoidHom.ker Q.projection ↔ g ∈ Q.quotient.carrier := by
  rw [Q.kernel_eq]

/-- The displayed projection of a cut quotient is surjective. -/
theorem cQuotie.projection_surj {G : Type u} [Group G]
    (Q : cQuotie G) : Function.Surjective Q.projection :=
  Q.projection_surjective


/-- Transition map between nested cut quotients. -/
noncomputable def cQuotie.transition {G : Type u} [Group G]
    {Q R : cQuotie G} (h : Q.refines R) :
    quotientGroup Q.quotient →* quotientGroup R.quotient :=
  quotientMapLE Q.quotient R.quotient h

@[simp] theorem cQuotie.transition_mk {G : Type u} [Group G]
    {Q R : cQuotie G} (h : Q.refines R) (g : G) :
    cQuotie.transition h (QuotientGroup.mk' Q.quotient.carrier g) =
      QuotientGroup.mk' R.quotient.carrier g := by
  simpa [cQuotie.transition] using quotient_mk Q.quotient R.quotient h g

@[simp] theorem cQuotie.transition_self {G : Type u} [Group G]
    (Q : cQuotie G) :
    cQuotie.transition (Q.refines_refl) = MonoidHom.id (quotientGroup Q.quotient) :=
  quotient_self Q.quotient

/-- Transition maps between nested cut quotients are surjective. -/
theorem cQuotie.transition_surj {G : Type u} [Group G]
    {Q R : cQuotie G} (h : Q.refines R) :
    Function.Surjective (cQuotie.transition h) :=
  of_le_surjective Q.quotient R.quotient h


@[simp] theorem cQuotie.transition_comp {G : Type u} [Group G]
    {Q R S : cQuotie G} (hQR : Q.refines R) (hRS : R.refines S) :
    (cQuotie.transition hRS).comp (cQuotie.transition hQR) =
      cQuotie.transition (cQuotie.refines_trans hQR hRS) := by
  simp [cQuotie.transition, of_le_comp]

/-- A family of finite group layers indexed by degree, with transition maps
between deeper and shallower layers. -/
structure fLayers where
  layer : ℕ → Type u
  [group_layer : ∀ n, Group (layer n)]
  finite_layer : ∀ n, Finite (layer n)
  transition : ∀ {m n : ℕ}, m ≤ n → layer n →* layer m
  transition_surjective : ∀ {m n : ℕ} (h : m ≤ n), Function.Surjective (transition h)
  transition_id : ∀ n, transition (Nat.le_refl n) = MonoidHom.id (layer n)
  transition_comp : ∀ {k m n : ℕ} (hkm : k ≤ m) (hmn : m ≤ n),
    (transition hkm).comp (transition hmn) = transition (Nat.le_trans hkm hmn)

attribute [instance] fLayers.group_layer
attribute [instance] fLayers.finite_layer

/-- Named surjectivity accessor for finite-layer transition maps. -/
theorem fLayers.transition_surj (L : fLayers.{u}) {m n : ℕ} (h : m ≤ n) :
    Function.Surjective (L.transition h) :=
  L.transition_surjective h

/-- Named identity law for finite-layer transitions. -/
theorem fLayers.transition_id_hom (L : fLayers.{u}) (n : ℕ) :
    L.transition (Nat.le_refl n) = MonoidHom.id (L.layer n) :=
  L.transition_id n



@[simp] theorem fLayers.transition_id_apply (L : fLayers.{u}) (n : ℕ) (x : L.layer n) :
    L.transition (Nat.le_refl n) x = x := by
  have h := L.transition_id n
  exact congrArg (fun f : L.layer n →* L.layer n => f x) h

/-- Pointwise composition law for finite layers. -/
theorem fLayers.transition_comp_apply (L : fLayers.{u})
    {k m n : ℕ} (hkm : k ≤ m) (hmn : m ≤ n) (x : L.layer n) :
    L.transition hkm (L.transition hmn x) = L.transition (Nat.le_trans hkm hmn) x := by
  have h := L.transition_comp hkm hmn
  exact congrArg (fun f : L.layer n →* L.layer k => f x) h

/-- A kernel designated as a filtration kernel. -/
abbrev filtrationKernel {G : Type u} {H : Type v} [Group G] [Group H] (f : G →* H) : Subgroup G :=
  kernel f


end Group
end Towers
