import Mathlib

namespace Submission.NumberTheory

namespace NQUnits

theorem or_neg_two
    {d : ℤ} (hd : d ≤ -2) (x : ℤ√d) :
    IsUnit x ↔ x = 1 ∨ x = -1 := by
  constructor
  · intro hx
    have hnorm : x.norm = 1 :=
      (Zsqrtd.norm_eq_one_iff' (hd.trans (by norm_num)) x).mpr hx
    rw [Zsqrtd.norm_def] at hnorm
    have him : x.im = 0 := by
      by_contra him
      have him_pos : 0 < x.im ^ 2 := sq_pos_of_ne_zero him
      have him_one : 1 ≤ x.im ^ 2 := by omega
      have hnegd : 2 ≤ -d := by omega
      have hprod : (2 : ℤ) ≤ (-d) * x.im ^ 2 := by
        calc
          (2 : ℤ) = 2 * 1 := by norm_num
          _ ≤ (-d) * x.im ^ 2 := mul_le_mul hnegd him_one (by norm_num) (by omega)
      nlinarith [sq_nonneg x.re]
    have hre : x.re ^ 2 = 1 := by
      rw [him] at hnorm
      simpa [pow_two] using hnorm
    rcases sq_eq_one_iff.mp hre with hre | hre
    · exact Or.inl (Zsqrtd.ext_iff.mpr ⟨by simpa using hre, by simpa using him⟩)
    · exact Or.inr (Zsqrtd.ext_iff.mpr ⟨by simpa using hre, by simpa using him⟩)
  · rintro (rfl | rfl) <;> simp

theorem gaussian_unit (x : GaussianInt) :
    IsUnit x ↔
      x = 1 ∨ x = -1 ∨ x = Zsqrtd.sqrtd ∨ x = -Zsqrtd.sqrtd := by
  constructor
  · intro hx
    have hnorm : x.norm = 1 :=
      (Zsqrtd.norm_eq_one_iff' (by norm_num : (-1 : ℤ) ≤ 0) x).mpr hx
    rw [Zsqrtd.norm_def] at hnorm
    have hre_lower : -2 < x.re := by
      nlinarith [sq_nonneg (x.re + 2), sq_nonneg x.im]
    have hre_upper : x.re < 2 := by
      nlinarith [sq_nonneg (x.re - 2), sq_nonneg x.im]
    have him_lower : -2 < x.im := by
      nlinarith [sq_nonneg x.re, sq_nonneg (x.im + 2)]
    have him_upper : x.im < 2 := by
      nlinarith [sq_nonneg x.re, sq_nonneg (x.im - 2)]
    interval_cases hre : x.re <;> interval_cases him : x.im <;>
      simp [hre, him, Zsqrtd.ext_iff, Zsqrtd.sqrtd] at hnorm ⊢
  · rintro (rfl | rfl | rfl | rfl) <;>
      apply (Zsqrtd.norm_eq_one_iff' (by norm_num : (-1 : ℤ) ≤ 0) _).mp <;>
      norm_num [Zsqrtd.norm_def]

end NQUnits

/-- The half-integral quadratic order `ℤ[η]`, where `η² = η + a`. For a square-free
`m = 4a + 1`, this is the integral model generated by `(1 + √m) / 2`. -/
abbrev HQInts (a : ℤ) := QuadraticAlgebra ℤ a 1

namespace HQInts

private lemma norm_formula (a : ℤ) (x : HQInts a) :
    x.norm = x.re ^ 2 + x.re * x.im - a * x.im ^ 2 := by
  rw [QuadraticAlgebra.norm_def]
  ring

private lemma norm_nonnegative {a : ℤ} (ha : a ≤ -2) (x : HQInts a) :
    0 ≤ x.norm := by
  have hidentity :
      4 * x.norm = (2 * x.re + x.im) ^ 2 - (4 * a + 1) * x.im ^ 2 := by
    rw [norm_formula]
    ring
  have hcoef : 0 ≤ -(4 * a + 1) := by omega
  nlinarith [sq_nonneg (2 * x.re + x.im),
    mul_nonneg hcoef (sq_nonneg x.im)]

/-- Proposition 96 for imaginary quadratic rings with half-integral basis and discriminant at
most `-7`: their only units are `±1`. The exceptional value `a = -1` is the Eisenstein case. -/
theorem or_neg_two
    {a : ℤ} (ha : a ≤ -2) (x : HQInts a) :
    IsUnit x ↔ x = 1 ∨ x = -1 := by
  constructor
  · intro hx
    have hnormUnit : IsUnit x.norm :=
      QuadraticAlgebra.isUnit_iff_norm_isUnit.mp hx
    have hnorm : x.norm = 1 := by
      rcases Int.isUnit_iff.mp hnormUnit with hnorm | hnorm
      · exact hnorm
      · have := norm_nonnegative ha x
        omega
    have hidentity :
        4 = (2 * x.re + x.im) ^ 2 - (4 * a + 1) * x.im ^ 2 := by
      calc
        4 = 4 * x.norm := by rw [hnorm]; norm_num
        _ = (2 * x.re + x.im) ^ 2 - (4 * a + 1) * x.im ^ 2 := by
          rw [norm_formula]
          ring
    have him : x.im = 0 := by
      by_contra him
      have himsq : 1 ≤ x.im ^ 2 := by nlinarith [sq_pos_of_ne_zero him]
      have hcoef : 7 ≤ -(4 * a + 1) := by omega
      nlinarith [sq_nonneg (2 * x.re + x.im),
        mul_le_mul hcoef himsq (by omega) (by omega)]
    have hre : x.re ^ 2 = 1 := by
      rw [norm_formula, him] at hnorm
      simpa using hnorm
    rcases sq_eq_one_iff.mp hre with hre | hre
    · exact Or.inl (QuadraticAlgebra.ext_iff.mpr ⟨by simpa using hre, by simpa using him⟩)
    · exact Or.inr (QuadraticAlgebra.ext_iff.mpr ⟨by simpa using hre, by simpa using him⟩)
  · rintro (rfl | rfl) <;> simp

end HQInts

abbrev SqrtTwo := ℤ√(2)

namespace SqrtTwo

def fundamentalUnit : SqrtTwoˣ where
  val := ⟨1, 1⟩
  inv := ⟨-1, 1⟩
  val_inv := by ext <;> norm_num
  inv_val := by ext <;> norm_num

@[simp] theorem fundamentalUnit_val :
    ((fundamentalUnit : SqrtTwoˣ) : SqrtTwo) = ⟨1, 1⟩ := rfl

private def pellFundamental : Pell.Solution₁ 2 :=
  Pell.Solution₁.mk 3 2 (by norm_num)

private lemma pell_fundamental : Pell.IsFundamental pellFundamental := by
  refine ⟨by norm_num [pellFundamental], by norm_num [pellFundamental], ?_⟩
  intro b hb
  change 3 ≤ b.x
  by_contra h
  have hbx : b.x = 2 := by omega
  have hprop := b.prop
  rw [hbx] at hprop
  norm_num at hprop
  omega

private lemma pell_fundamental_units :
    Unitary.toUnits pellFundamental = fundamentalUnit ^ 2 := by
  apply Units.ext
  ext <;> norm_num [pellFundamental, fundamentalUnit, pow_two]

private lemma even_or_neg
    (u : SqrtTwoˣ) (hnorm : (u.val : SqrtTwo).norm = 1) :
    ∃ n : ℤ, u = fundamentalUnit ^ (2 * n) ∨ u = -fundamentalUnit ^ (2 * n) := by
  let s : Pell.Solution₁ 2 :=
    ⟨u.val, Zsqrtd.norm_eq_one_iff_mem_unitary.mp hnorm⟩
  obtain ⟨n, hn | hn⟩ := pell_fundamental.eq_zpow_or_neg_zpow s
  · refine ⟨n, Or.inl ?_⟩
    have hs : Unitary.toUnits s = u := Units.ext rfl
    calc
      u = Unitary.toUnits s := hs.symm
      _ = Unitary.toUnits (pellFundamental ^ n) := congrArg Unitary.toUnits hn
      _ = (Unitary.toUnits pellFundamental) ^ n :=
        map_zpow (Unitary.toUnits : unitary SqrtTwo →* SqrtTwoˣ) pellFundamental n
      _ = fundamentalUnit ^ (2 * n) := by
        rw [pell_fundamental_units]
        exact (zpow_mul fundamentalUnit 2 n).symm
  · refine ⟨n, Or.inr ?_⟩
    have hs : Unitary.toUnits s = u := Units.ext rfl
    calc
      u = Unitary.toUnits s := hs.symm
      _ = Unitary.toUnits (-pellFundamental ^ n) := congrArg Unitary.toUnits hn
      _ = -Unitary.toUnits (pellFundamental ^ n) := by apply Units.ext; rfl
      _ = -(Unitary.toUnits pellFundamental) ^ n := by
        exact congrArg Neg.neg
          (map_zpow (Unitary.toUnits : unitary SqrtTwo →* SqrtTwoˣ) pellFundamental n)
      _ = -fundamentalUnit ^ (2 * n) := by
        rw [pell_fundamental_units]
        exact congrArg Neg.neg (zpow_mul fundamentalUnit 2 n).symm

theorem power_or_neg (u : SqrtTwoˣ) :
    ∃ n : ℤ, u = fundamentalUnit ^ n ∨ u = -fundamentalUnit ^ n := by
  have habs : u.val.norm.natAbs = 1 := Zsqrtd.norm_eq_one_iff.mpr u.isUnit
  have hnorm : u.val.norm = 1 ∨ u.val.norm = -1 := by
    simpa using (Int.natAbs_eq_iff.mp habs)
  rcases hnorm with hnorm | hnorm
  · obtain ⟨n, hn⟩ := even_or_neg u hnorm
    exact ⟨2 * n, hn⟩
  · have huvnorm : (u * fundamentalUnit).val.norm = 1 := by
      rw [Units.val_mul, Zsqrtd.norm_mul, hnorm]
      norm_num [fundamentalUnit, Zsqrtd.norm_def]
    obtain ⟨n, hn | hn⟩ := even_or_neg (u * fundamentalUnit) huvnorm
    · refine ⟨2 * n - 1, Or.inl ?_⟩
      calc
        u = (u * fundamentalUnit) * fundamentalUnit⁻¹ := by simp
        _ = fundamentalUnit ^ (2 * n) * fundamentalUnit⁻¹ := by rw [hn]
        _ = fundamentalUnit ^ (2 * n - 1) := by rw [zpow_sub]; simp
    · refine ⟨2 * n - 1, Or.inr ?_⟩
      calc
        u = (u * fundamentalUnit) * fundamentalUnit⁻¹ := by simp
        _ = (-fundamentalUnit ^ (2 * n)) * fundamentalUnit⁻¹ := by rw [hn]
        _ = -fundamentalUnit ^ (2 * n - 1) := by rw [zpow_sub]; simp

noncomputable def realEmbedding : SqrtTwo →+* ℝ :=
  Zsqrtd.toReal (by norm_num)

noncomputable def unitReal : SqrtTwoˣ →* ℝ :=
  (Units.coeHom ℝ).comp (Units.map realEmbedding)

@[simp] lemma unitReal_apply (u : SqrtTwoˣ) :
    unitReal u = realEmbedding u.val := rfl

@[simp] lemma unit_real_fundamental :
    unitReal fundamentalUnit = 1 + Real.sqrt 2 := by
  norm_num [unitReal, realEmbedding, fundamentalUnit, Zsqrtd.toReal_apply]

@[simp] lemma unitReal_neg (u : SqrtTwoˣ) : unitReal (-u) = -unitReal u := by
  change realEmbedding (-u.val) = -realEmbedding u.val
  simp

/-- Wright's Lemma 98: in the positive real embedding, no unit of `ℤ[√2]` lies strictly
between `1` and the fundamental unit `1 + √2`. -/
theorem strictly_between_fundamental (u : SqrtTwoˣ) :
    ¬ (1 < unitReal u ∧ unitReal u < unitReal fundamentalUnit) := by
  rintro ⟨h1, h2⟩
  have hlambda : 1 < unitReal fundamentalUnit := by
    rw [unit_real_fundamental]
    have hsqrt : 0 < Real.sqrt 2 := Real.sqrt_pos.2 (by norm_num)
    linarith
  obtain ⟨n, hn | hn⟩ := power_or_neg u
  · rw [hn, MonoidHom.map_zpow unitReal fundamentalUnit n] at h1 h2
    have hn0 : 0 < n := (one_lt_zpow_iff_right₀ hlambda).mp h1
    have hn1 : n < 1 := by
      exact (zpow_lt_zpow_iff_right₀ hlambda).mp (by simpa using h2)
    omega
  · have hneg : unitReal u < 0 := by
      rw [hn, unitReal_neg, MonoidHom.map_zpow unitReal fundamentalUnit n]
      exact neg_neg_of_pos (zpow_pos (lt_trans zero_lt_one hlambda) n)
    linarith

end SqrtTwo

end Submission.NumberTheory
