import Submission.Group.Frattini
import Submission.Group.FrattiniFunctor
import Submission.Group.Zassenhaus
import Mathlib.Algebra.TrivSqZeroExt.Basic

/-!
# First degree comparison for the mod-`p` filtration

This file records the easy inclusion `G^p [G,G] ≤ D₂` for the dimension/Zassenhaus
filtration.  The reverse inclusion (and hence equality for the intended hypotheses)
is the harder degree-one/dimension-subgroup theorem and is left for later layers.
-/

open scoped commutatorElement

namespace Submission

open GroupAlgebra

variable (p : ℕ) (G : Type*) [Group G]

/-- The subgroup generated by `p`th powers lies in the second Zassenhaus term. -/
theorem p_zassenhaus_two :
    pPowerSubgroup p G ≤ zSubgro p G 2 := by
  haveI : (zSubgro p G 2).Normal := zassenhausSubgroup_normal p G 2
  dsimp [pPowerSubgroup]
  apply Subgroup.normalClosure_le_normal
  intro x hx
  rcases hx with ⟨g, rfl⟩
  exact pow_subgroup_two p G g

/-- The commutator subgroup lies in the second Zassenhaus term. -/
theorem commutator_two :
    _root_.commutator G ≤ zSubgro p G 2 := by
  haveI : (zSubgro p G 2).Normal := zassenhausSubgroup_normal p G 2
  rw [_root_.commutator_eq_normalClosure]
  apply Subgroup.normalClosure_le_normal
  intro x hx
  rcases hx with ⟨g, h, rfl⟩
  exact commutator_subgroup_two p G g h

/-- Easy half of the degree-one comparison: `G^p [G,G] ≤ D₂`. -/
theorem mod_p_two :
    modPFrattini p G ≤ zSubgro p G 2 := by
  dsimp [modPFrattini]
  exact sup_le (p_zassenhaus_two p G)
    (commutator_two p G)

/-- An elementary abelian quotient has trivial second Zassenhaus term. -/
lemma bot_comm_exponent
    {Q : Type*} [Group Q] [IsMulCommutative Q]
    (hpQ : ∀ q : Q, q ^ p = 1) :
    zSubgro p Q 2 ≤ ⊥ := by
  classical
  letI : AddCommGroup (Additive Q) :=
    { (inferInstance : AddGroup (Additive Q)) with
      add_comm := by
        intro x y
        change Additive.ofMul (Additive.toMul x * Additive.toMul y) =
          Additive.ofMul (Additive.toMul y * Additive.toMul x)
        rw [IsMulCommutative.is_comm.comm (Additive.toMul x) (Additive.toMul y)] }
  letI : Module (ZMod p) (Additive Q) := by
    apply AddCommGroup.zmodModule
    intro x
    change Additive.ofMul ((Additive.toMul x) ^ p) = Additive.ofMul (1 : Q)
    simp [hpQ (Additive.toMul x)]
  letI : Module (ZMod p)ᵐᵒᵖ (Additive Q) :=
    Module.compHom _ ((RingHom.id (ZMod p)).fromOpposite mul_comm)
  haveI : IsCentralScalar (ZMod p) (Additive Q) := ⟨fun _ _ => rfl⟩
  let S := TrivSqZeroExt (ZMod p) (Additive Q)
  let j : Q →* S :=
  { toFun := fun q => ⟨1, Additive.ofMul q⟩
    map_one' := by
      ext <;> simp
    map_mul' := by
      intro q r
      ext
      · simp [S]
      · simpa [S] using (IsMulCommutative.is_comm.comm q r) }
  let π : S →ₐ[ZMod p] ZMod p :=
    TrivSqZeroExt.fstHom (ZMod p) (ZMod p) (Additive Q)
  let F : MonoidAlgebra (ZMod p) Q →ₐ[ZMod p] S :=
    _root_.MonoidAlgebra.lift (ZMod p) S Q j
  have hπF : π.comp F = augmentation (ZMod p) Q := by
    ext q
    simp [π, F, augmentation, trivialCharacter, j, S]
  let I := augmentationIdeal (ZMod p) Q
  have hfst_zero : ∀ a ∈ I, (F a).fst = 0 := by
    intro a ha
    have ha0 : (augmentation (ZMod p) Q) a = 0 := by
      simpa [I, augmentationIdeal] using ha
    have hπa : π (F a) = 0 := by
      change (π.comp F) a = 0
      rw [hπF]
      exact ha0
    simpa [π] using hπa
  have hmul_zero : ∀ z w : S, z.fst = 0 → w.fst = 0 → z * w = 0 := by
    intro z w hz hw
    ext
    · simp [S, hz, hw]
    · simp [S, hz, hw]
  have hker : I ^ 2 ≤ RingHom.ker F.toRingHom := by
    rw [show (2 : ℕ) = 1 + 1 by norm_num, Submodule.pow_succ, Submodule.pow_one]
    rw [Ideal.mul_le]
    intro a ha b hb
    change F (a * b) = 0
    rw [map_mul]
    exact hmul_zero (F a) (F b) (hfst_zero a ha) (hfst_zero b hb)
  intro q hq
  change (_root_.MonoidAlgebra.of (ZMod p) Q q - 1 :
      MonoidAlgebra (ZMod p) Q) ∈ augmentationPower (ZMod p) Q 2 at hq
  have hx : (_root_.MonoidAlgebra.of (ZMod p) Q q - 1 :
      MonoidAlgebra (ZMod p) Q) ∈ I ^ 2 := by
    simpa [I, augmentationPower] using hq
  have hFzero : F (_root_.MonoidAlgebra.of (ZMod p) Q q - 1) = 0 := by
    change F (_root_.MonoidAlgebra.of (ZMod p) Q q - 1) = 0
    exact hker hx
  have hsnd_zero :
      (F (_root_.MonoidAlgebra.of (ZMod p) Q q - 1)).snd = 0 := by
    rw [hFzero]
    simp
  have hsnd_calc :
      (F (_root_.MonoidAlgebra.of (ZMod p) Q q - 1)).snd = Additive.ofMul q := by
    simp [F, j, S]
  have hq0 : Additive.ofMul q = 0 := by
    rw [← hsnd_calc]
    exact hsnd_zero
  change q = 1
  simpa using congrArg Additive.toMul hq0

/-- Hard half of the first-degree dimension-subgroup theorem:
`D₂(G)` is contained in the mod-`p` Frattini subgroup `G^p [G,G]`. -/
theorem zassenhaus_two_frattini [Fact p.Prime] :
    zSubgro p G 2 ≤ modPFrattini p G := by
  classical
  intro g hg
  let N : Subgroup G := modPFrattini p G
  haveI : N.Normal := by
    dsimp [N]
    infer_instance
  let Q := G ⧸ N
  have hcomm_le_N : _root_.commutator G ≤ N := by
    dsimp [N, modPFrattini]
    exact le_sup_right
  haveI : IsMulCommutative Q :=
    (Subgroup.Normal.quotient_commutative_iff_commutator_le (N := N)).mpr hcomm_le_N
  let q : G →* Q := QuotientGroup.mk' N
  have hpQ : ∀ x : Q, x ^ p = 1 := by
    intro x
    refine QuotientGroup.induction_on x ?_
    intro a
    have hp_mem : a ^ p ∈ pPowerSubgroup p G := by
      dsimp [pPowerSubgroup]
      exact Subgroup.subset_normalClosure ⟨a, rfl⟩
    have hmemN : a ^ p ∈ N := by
      dsimp [N, modPFrattini]
      exact
        (show pPowerSubgroup p G ≤ pPowerSubgroup p G ⊔ _root_.commutator G from
          le_sup_left) hp_mem
    have hmk : (QuotientGroup.mk' N) (a ^ p) = 1 := by
      exact (QuotientGroup.eq_one_iff (N := N) (a ^ p)).mpr hmemN
    simpa using hmk
  have hgQ : q g ∈ zSubgro p Q 2 := by
    exact zassenhaus_subgroup_comap p G q 2 hg
  have hbot : zSubgro p Q 2 ≤ (⊥ : Subgroup Q) :=
    bot_comm_exponent (p := p) (Q := Q) hpQ
  have hq_bot : q g ∈ (⊥ : Subgroup Q) := hbot hgQ
  have hq_one : q g = 1 := by
    simpa only [Subgroup.mem_bot] using hq_bot
  have hq_one' : (QuotientGroup.mk' N) g = 1 := by
    simpa only [q] using hq_one
  change g ∈ N
  exact (QuotientGroup.eq_one_iff (N := N) g).mp hq_one'

/-- First-degree Jennings-Lazard-Zassenhaus comparison:
`D₂(G) = G^p [G,G]`. -/
theorem two_p_frattini [Fact p.Prime] :
    zSubgro p G 2 = modPFrattini p G := by
  exact le_antisymm
    (zassenhaus_two_frattini p G)
    (mod_p_two p G)

end Submission

namespace Submission

open GroupAlgebra

noncomputable section

variable (p : ℕ) (G : Type*) [Group G]

/-- The easy inclusion `G^p [G,G] ≤ D₂` induces a canonical map from the
mod-`p` Frattini quotient to the first Zassenhaus quotient. -/
def mFQuot.toZassenhausTwo :
    mFQuot p G →* zQuot p G 2 := by
  refine QuotientGroup.lift (modPFrattini p G)
    (QuotientGroup.mk' (zSubgro p G 2)) ?_
  intro x hx
  exact (QuotientGroup.eq_one_iff x).mpr ((mod_p_two p G) hx)

@[simp] theorem mFQuot.zass_two_mk (g : G) :
    mFQuot.toZassenhausTwo p G (mFQuot.mk p G g) =
      QuotientGroup.mk' (zSubgro p G 2) g := rfl

/-- The canonical map to `G/D₂` is surjective. -/
theorem mFQuot.zass_two_surj :
    Function.Surjective (mFQuot.toZassenhausTwo p G) := by
  intro q
  refine QuotientGroup.induction_on q ?_
  intro g
  exact ⟨mFQuot.mk p G g, rfl⟩

/-- Additive version of the canonical map to the first Zassenhaus quotient. -/
def mFAdditi.zass_two_add :
    mFAdditi p G →+ zTAdditi p G :=
  (mFQuot.toZassenhausTwo p G).toAdditive

@[simp] theorem mFAdditi.zass_two_addmul
    (q : mFQuot p G) :
    mFAdditi.zass_two_add p G (Additive.ofMul q) =
      Additive.ofMul (mFQuot.toZassenhausTwo p G q) := rfl

/-- Linear version of the canonical map to the first Zassenhaus quotient. -/
def mFAdditi.zass_two_lin :
    mFAdditi p G →ₗ[ZMod p] zTAdditi p G :=
  (mFAdditi.zass_two_add p G).toZModLinearMap p

@[simp] theorem mFAdditi.zass_two_linapply
    (x : mFAdditi p G) :
    mFAdditi.zass_two_lin p G x =
      mFAdditi.zass_two_add p G x := rfl

/-- Naturality of the canonical map from the Frattini quotient to `G/D₂`. -/
@[simp] theorem mFQuot.zass_two_natural
    {H : Type*} [Group H] (f : G →* H) :
    (zQuot.map p G f 2).comp (mFQuot.toZassenhausTwo p G) =
      (mFQuot.toZassenhausTwo p H).comp
        (mFQuot.map (p := p) f) := by
  apply MonoidHom.ext
  intro q
  refine QuotientGroup.induction_on q ?_
  intro g
  rfl

/-- Linear naturality of the canonical first-degree comparison map. -/
@[simp] theorem mFAdditi.zass_two_linnatural
    {H : Type*} [Group H] (f : G →* H) :
    (zTAdditi.mapLinear p G f).comp
        (mFAdditi.zass_two_lin p G) =
      (mFAdditi.zass_two_lin p H).comp
        (mFAdditi.mapLinear (p := p) f) := by
  ext x
  induction x using Additive.rec with
  | ofMul q =>
      refine QuotientGroup.induction_on q ?_
      intro g
      rfl

end

end Submission

namespace Submission

open GroupAlgebra

noncomputable section

variable (p : ℕ) (G : Type*) [Group G]

/-- If the reverse degree-one inclusion holds, the canonical map has trivial kernel. -/
theorem mFQuot.zass_twoeq_onereverse
    (hrev : zSubgro p G 2 ≤ modPFrattini p G)
    {q : mFQuot p G}
    (hq : mFQuot.toZassenhausTwo p G q = 1) : q = 1 := by
  refine QuotientGroup.induction_on q ?_ hq
  intro g hgq
  change QuotientGroup.mk' (zSubgro p G 2) g = 1 at hgq
  have hg : g ∈ zSubgro p G 2 := (QuotientGroup.eq_one_iff g).1 hgq
  exact (QuotientGroup.eq_one_iff g).2 (hrev hg)

/-- If `D₂ ≤ G^p [G,G]`, the canonical map from the Frattini quotient to `G/D₂`
is injective (hence bijective, since it is always surjective). -/
theorem mFQuot.zass_two_injreverse
    (hrev : zSubgro p G 2 ≤ modPFrattini p G) :
    Function.Injective (mFQuot.toZassenhausTwo p G) := by
  intro a b hab
  apply eq_of_mul_inv_eq_one
  apply mFQuot.zass_twoeq_onereverse p G hrev
  rw [map_mul, map_inv, hab, mul_inv_cancel]


/-- Conversely, injectivity of the canonical map to `G/D₂` forces the reverse
containment `D₂ ≤ G^p [G,G]`. -/
theorem p_frattini_injective
    (hinj : Function.Injective (mFQuot.toZassenhausTwo p G)) :
    zSubgro p G 2 ≤ modPFrattini p G := by
  intro g hg
  have hmap : mFQuot.toZassenhausTwo p G
        (mFQuot.mk p G g) =
      mFQuot.toZassenhausTwo p G
        (mFQuot.mk p G 1) := by
    change QuotientGroup.mk' (zSubgro p G 2) g =
      QuotientGroup.mk' (zSubgro p G 2) 1
    exact (QuotientGroup.eq_one_iff g).mpr hg
  have hq := hinj hmap
  change QuotientGroup.mk' (modPFrattini p G) g =
    QuotientGroup.mk' (modPFrattini p G) 1 at hq
  simpa using (QuotientGroup.eq.mp hq)

/-- Reverse containment is equivalent to injectivity of the canonical map from
Frattini quotient to `G/D₂`. -/
theorem zassenhaus_injective_reverse :
    Function.Injective (mFQuot.toZassenhausTwo p G) ↔
      zSubgro p G 2 ≤ modPFrattini p G :=
  ⟨p_frattini_injective p G,
    mFQuot.zass_two_injreverse p G⟩


/-- Reverse containment is also equivalent to bijectivity of the canonical map,
since that map is always surjective. -/
theorem zassenhaus_bijective_reverse :
    Function.Bijective (mFQuot.toZassenhausTwo p G) ↔
      zSubgro p G 2 ≤ modPFrattini p G := by
  constructor
  · intro hb
    exact p_frattini_injective p G hb.1
  · intro hrev
    exact ⟨mFQuot.zass_two_injreverse p G hrev,
      mFQuot.zass_two_surj p G⟩

/-- The multiplicative comparison map has full range. -/
theorem mFQuot.zass_tworange_eqtop :
    (mFQuot.toZassenhausTwo p G).range = ⊤ := by
  exact (MonoidHom.range_eq_top).2
    (mFQuot.zass_two_surj p G)

/-- Under reverse containment, the multiplicative comparison map has trivial kernel. -/
theorem mFQuot.zasstwo_kereq_botreverse
    (hrev : zSubgro p G 2 ≤ modPFrattini p G) :
    (mFQuot.toZassenhausTwo p G).ker = ⊥ := by
  exact (MonoidHom.ker_eq_bot_iff (mFQuot.toZassenhausTwo p G)).2
    (mFQuot.zass_two_injreverse p G hrev)

/-- Additive/linear injectivity form of the conditional reverse-inclusion criterion. -/
theorem mFAdditi.zass_twolin_injreverse
    (hrev : zSubgro p G 2 ≤ modPFrattini p G) :
    Function.Injective (mFAdditi.zass_two_lin p G) := by
  intro x y h
  induction x using Additive.rec with
  | ofMul a =>
  induction y using Additive.rec with
  | ofMul b =>
  change Additive.ofMul (mFQuot.toZassenhausTwo p G a) =
    Additive.ofMul (mFQuot.toZassenhausTwo p G b) at h
  have hab := congrArg Additive.toMul h
  simp only [EmbeddingLike.apply_eq_iff_eq] at hab
  congr
  exact mFQuot.zass_two_injreverse p G hrev hab

/-- The linear map is always surjective. -/
theorem mFAdditi.zass_two_linsurj :
    Function.Surjective (mFAdditi.zass_two_lin p G) := by
  intro y
  induction y using Additive.rec with
  | ofMul q =>
  rcases mFQuot.zass_two_surj p G q with ⟨a, ha⟩
  refine ⟨Additive.ofMul a, ?_⟩
  change Additive.ofMul (mFQuot.toZassenhausTwo p G a) = Additive.ofMul q
  rw [ha]

/-- The comparison linear map has full range. -/
theorem mFAdditi.zasstwo_linrange_eqtop :
    LinearMap.range (mFAdditi.zass_two_lin p G) = ⊤ := by
  exact LinearMap.range_eq_top_of_surjective _
    (mFAdditi.zass_two_linsurj p G)

/-- Under reverse containment, the comparison linear map has trivial kernel. -/
theorem mFAdditi.zasstwo_linker_eqbotreverse
    (hrev : zSubgro p G 2 ≤ modPFrattini p G) :
    LinearMap.ker (mFAdditi.zass_two_lin p G) = ⊥ := by
  exact LinearMap.ker_eq_bot_of_injective
    (mFAdditi.zass_twolin_injreverse p G hrev)

/-- Linear injectivity of the comparison map is equivalent to reverse containment. -/
theorem linear_injective_reverse [Fact p.Prime] :
    Function.Injective (mFAdditi.zass_two_lin p G) ↔
      zSubgro p G 2 ≤ modPFrattini p G := by
  constructor
  · intro hinj
    apply p_frattini_injective p G
    intro a b h
    have ha : mFAdditi.zass_two_lin p G (Additive.ofMul a) =
        mFAdditi.zass_two_lin p G (Additive.ofMul b) := by
      change Additive.ofMul (mFQuot.toZassenhausTwo p G a) =
        Additive.ofMul (mFQuot.toZassenhausTwo p G b)
      rw [h]
    exact congrArg Additive.toMul (hinj ha)
  · exact mFAdditi.zass_twolin_injreverse p G

/-- Linear bijectivity of the comparison map is equivalent to reverse containment. -/
theorem linear_bijective_reverse [Fact p.Prime] :
    Function.Bijective (mFAdditi.zass_two_lin p G) ↔
      zSubgro p G 2 ≤ modPFrattini p G := by
  constructor
  · intro hb
    exact (linear_injective_reverse p G).mp hb.1
  · intro hrev
    exact ⟨mFAdditi.zass_twolin_injreverse p G hrev,
      mFAdditi.zass_two_linsurj p G⟩

/-- Under the reverse inclusion, the first Zassenhaus quotient is linearly equivalent
to the mod-`p` Frattini quotient.  This isolates the hard dimension-subgroup input
as a single subgroup-containment hypothesis. -/
noncomputable def mFAdditi.zass_twolin_equivreverse
    (hrev : zSubgro p G 2 ≤ modPFrattini p G) :
    mFAdditi p G ≃ₗ[ZMod p] zTAdditi p G :=
  LinearEquiv.ofBijective (mFAdditi.zass_two_lin p G)
    ⟨mFAdditi.zass_twolin_injreverse p G hrev,
      mFAdditi.zass_two_linsurj p G⟩

@[simp] theorem mFAdditi.zasstwo_linequiv_reverselinmap
    (hrev : zSubgro p G 2 ≤ modPFrattini p G) :
    (mFAdditi.zass_twolin_equivreverse p G hrev).toLinearMap =
      mFAdditi.zass_two_lin p G := rfl

@[simp] theorem mFAdditi.zasstwo_linequiv_reverseapply
    (hrev : zSubgro p G 2 ≤ modPFrattini p G)
    (x : mFAdditi p G) :
    mFAdditi.zass_twolin_equivreverse p G hrev x =
      mFAdditi.zass_two_lin p G x := rfl

@[simp] theorem mFAdditi.zasstwo_linequivreverse_symmapplymap
    (hrev : zSubgro p G 2 ≤ modPFrattini p G)
    (x : mFAdditi p G) :
    (mFAdditi.zass_twolin_equivreverse p G hrev).symm
        (mFAdditi.zass_two_lin p G x) = x := by
  exact (mFAdditi.zass_twolin_equivreverse p G hrev).left_inv x

@[simp] theorem mFAdditi.zasstwo_linapply_equivsymm
    (hrev : zSubgro p G 2 ≤ modPFrattini p G)
    (y : zTAdditi p G) :
    mFAdditi.zass_two_lin p G
        ((mFAdditi.zass_twolin_equivreverse p G hrev).symm y) = y := by
  change mFAdditi.zass_twolin_equivreverse p G hrev
      ((mFAdditi.zass_twolin_equivreverse p G hrev).symm y) = y
  exact (mFAdditi.zass_twolin_equivreverse p G hrev).right_inv y

/-- The conditional equivalences are natural (their underlying maps are the canonical ones). -/
theorem mFAdditi.zasstwo_linequiv_reversenatural
    {H : Type*} [Group H]
    (hG : zSubgro p G 2 ≤ modPFrattini p G)
    (hH : zSubgro p H 2 ≤ modPFrattini p H) (f : G →* H) :
    (mFAdditi.zass_twolin_equivreverse p H hH).toLinearMap.comp
        (mFAdditi.mapLinear (p := p) f) =
      (zTAdditi.mapLinear p G f).comp
        (mFAdditi.zass_twolin_equivreverse p G hG).toLinearMap := by
  ext x
  have h := congrArg (fun L => L x)
    (mFAdditi.zass_two_linnatural (p := p) (G := G) f)
  exact h.symm

/-- Pointwise form of naturality for the conditional Frattini-to-`D₂` equivalence. -/
theorem mFAdditi.zasstwo_linequiv_revenatuappl
    {H : Type*} [Group H]
    (hG : zSubgro p G 2 ≤ modPFrattini p G)
    (hH : zSubgro p H 2 ≤ modPFrattini p H) (f : G →* H)
    (x : mFAdditi p G) :
    (mFAdditi.zass_twolin_equivreverse p H hH)
        (mFAdditi.mapLinear (p := p) f x) =
      zTAdditi.mapLinear p G f
        ((mFAdditi.zass_twolin_equivreverse p G hG) x) := by
  change mFAdditi.zass_two_lin p H
        (mFAdditi.mapLinear (p := p) f x) =
      zTAdditi.mapLinear p G f
        (mFAdditi.zass_two_lin p G x)
  have h := congrArg
    (fun L : mFAdditi p G →ₗ[ZMod p] zTAdditi p H => L x)
    (mFAdditi.zass_two_linnatural (p := p) (G := G) f)
  simpa only [LinearMap.comp_apply] using h.symm

/-- Inverse pointwise naturality for the conditional Frattini-to-`D₂` equivalence. -/
theorem mFAdditi.zasstwo_linequivreverse_symmnatuappl
    {H : Type*} [Group H]
    (hG : zSubgro p G 2 ≤ modPFrattini p G)
    (hH : zSubgro p H 2 ≤ modPFrattini p H) (f : G →* H)
    (y : zTAdditi p G) :
    (mFAdditi.zass_twolin_equivreverse p H hH).symm
        (zTAdditi.mapLinear p G f y) =
      mFAdditi.mapLinear (p := p) f
        ((mFAdditi.zass_twolin_equivreverse p G hG).symm y) := by
  let x := (mFAdditi.zass_twolin_equivreverse p G hG).symm y
  have hn := mFAdditi.zasstwo_linequiv_revenatuappl
    (p := p) (G := G) hG hH f x
  calc
    (mFAdditi.zass_twolin_equivreverse p H hH).symm
        (zTAdditi.mapLinear p G f y)
        = (mFAdditi.zass_twolin_equivreverse p H hH).symm
            (zTAdditi.mapLinear p G f
              ((mFAdditi.zass_twolin_equivreverse p G hG) x)) := by
          simp [x]
    _ = (mFAdditi.zass_twolin_equivreverse p H hH).symm
          ((mFAdditi.zass_twolin_equivreverse p H hH)
            (mFAdditi.mapLinear (p := p) f x)) := by
          rw [← hn]
    _ = mFAdditi.mapLinear (p := p) f x := by
          exact (mFAdditi.zass_twolin_equivreverse p H hH).left_inv _

end

end Submission

namespace Submission

open GroupAlgebra

noncomputable section

variable (p : ℕ) (G : Type*) [Group G]

/-- Prime-case linear map from the Frattini quotient directly to the first layer kernel
(rather than the ambient quotient `G/D₂`). -/
def mFAdditi.zass_layer_onelin [Fact p.Prime] :
    mFAdditi p G →ₗ[ZMod p] Additive (zLKern p G 1) :=
  (zassenhausLinearEquiv p G).symm.toLinearMap.comp
    (mFAdditi.zass_two_lin p G)

/-- Naturality of the direct map from the Frattini quotient to the first layer kernel. -/
@[simp] theorem mFAdditi.zass_layerone_linnatural
    [Fact p.Prime] {H : Type*} [Group H] (f : G →* H) :
    (zLKern.mapLinear p G f 1).comp
        (mFAdditi.zass_layer_onelin p G) =
      (mFAdditi.zass_layer_onelin p H).comp
        (mFAdditi.mapLinear (p := p) f) := by
  apply LinearMap.ext
  intro x
  apply (zassenhausLinearEquiv p H).injective
  dsimp [mFAdditi.zass_layer_onelin]
  have hn := congrArg (fun L => L ((zassenhausLinearEquiv p G).symm
      ((mFAdditi.zass_two_lin p G) x)))
    (zassenhaus_linear_naturality (p := p) (G := G) f)
  simp only [Nat.reduceAdd, mFAdditi.zass_two_linapply,
    LinearMap.comp_apply, zLKern.mapLinear_apply, LinearEquiv.coe_coe,
    LinearEquiv.apply_symm_apply, zTAdditi.mapLinear_apply] at hn ⊢
  rw [hn]
  have hm := congrArg (fun L => L x)
    (mFAdditi.zass_two_linnatural (p := p) (G := G) f)
  exact hm

/-- The direct map to the first layer kernel is surjective. -/
theorem mFAdditi.zass_layerone_linsurj [Fact p.Prime] :
    Function.Surjective (mFAdditi.zass_layer_onelin p G) := by
  intro y
  let e := zassenhausLinearEquiv p G
  rcases mFAdditi.zass_two_linsurj p G (e y) with ⟨x, hx⟩
  refine ⟨x, ?_⟩
  dsimp [mFAdditi.zass_layer_onelin]
  change e.symm ((mFAdditi.zass_two_lin p G) x) = y
  rw [hx]
  exact e.symm_apply_apply y

/-- Under the reverse containment, the direct map to the first layer kernel is injective. -/
theorem mFAdditi.zasslayer_onelin_injreverse [Fact p.Prime]
    (hrev : zSubgro p G 2 ≤ modPFrattini p G) :
    Function.Injective (mFAdditi.zass_layer_onelin p G) := by
  intro x y h
  apply mFAdditi.zass_twolin_injreverse p G hrev
  let e := zassenhausLinearEquiv p G
  have hh := congrArg e h
  simpa [mFAdditi.zass_layer_onelin] using hh

/-- The direct map to the first layer kernel has full range. -/
theorem mFAdditi.zasslayer_onelin_rangeeqtop [Fact p.Prime] :
    LinearMap.range (mFAdditi.zass_layer_onelin p G) = ⊤ := by
  exact LinearMap.range_eq_top_of_surjective _
    (mFAdditi.zass_layerone_linsurj p G)

/-- Under reverse containment, the direct map to the first layer kernel has trivial kernel. -/
theorem mFAdditi.zasslayer_onelinker_eqbotreverse [Fact p.Prime]
    (hrev : zSubgro p G 2 ≤ modPFrattini p G) :
    LinearMap.ker (mFAdditi.zass_layer_onelin p G) = ⊥ := by
  exact LinearMap.ker_eq_bot_of_injective
    (mFAdditi.zasslayer_onelin_injreverse p G hrev)

/-- Conditional equivalence from the Frattini quotient directly to the first layer kernel. -/
def mFAdditi.zasslayer_onelin_equivreverse [Fact p.Prime]
    (hrev : zSubgro p G 2 ≤ modPFrattini p G) :
    mFAdditi p G ≃ₗ[ZMod p] Additive (zLKern p G 1) :=
  (mFAdditi.zass_twolin_equivreverse p G hrev).trans
    (zassenhausLinearEquiv p G).symm

@[simp] theorem mFAdditi.zasslayer_onelin_equireveappl
    [Fact p.Prime] (hrev : zSubgro p G 2 ≤ modPFrattini p G)
    (x : mFAdditi p G) :
    mFAdditi.zasslayer_onelin_equivreverse p G hrev x =
      mFAdditi.zass_layer_onelin p G x := rfl

@[simp] theorem mFAdditi.zasslayer_onelinequiv_reverselinmap
    [Fact p.Prime] (hrev : zSubgro p G 2 ≤ modPFrattini p G) :
    (mFAdditi.zasslayer_onelin_equivreverse p G hrev).toLinearMap =
      mFAdditi.zass_layer_onelin p G := by
  apply LinearMap.ext
  intro x
  rfl

@[simp] theorem mFAdditi.zasslayer_onelinequiv_symmapplymap
    [Fact p.Prime] (hrev : zSubgro p G 2 ≤ modPFrattini p G)
    (x : mFAdditi p G) :
    (mFAdditi.zasslayer_onelin_equivreverse p G hrev).symm
        (mFAdditi.zass_layer_onelin p G x) = x := by
  exact (mFAdditi.zasslayer_onelin_equivreverse p G hrev).left_inv x

@[simp] theorem mFAdditi.zasslayer_onelin_applyequivsymm
    [Fact p.Prime] (hrev : zSubgro p G 2 ≤ modPFrattini p G)
    (y : Additive (zLKern p G 1)) :
    mFAdditi.zass_layer_onelin p G
        ((mFAdditi.zasslayer_onelin_equivreverse p G hrev).symm y) = y := by
  change mFAdditi.zasslayer_onelin_equivreverse p G hrev
      ((mFAdditi.zasslayer_onelin_equivreverse p G hrev).symm y) = y
  exact (mFAdditi.zasslayer_onelin_equivreverse p G hrev).right_inv y

/-- Naturality of the conditional direct equivalence to the first layer kernel. -/
theorem mFAdditi.zasslayer_onelin_equirevenatu
    [Fact p.Prime] {H : Type*} [Group H]
    (hG : zSubgro p G 2 ≤ modPFrattini p G)
    (hH : zSubgro p H 2 ≤ modPFrattini p H) (f : G →* H) :
    (zLKern.mapLinear p G f 1).comp
        (mFAdditi.zasslayer_onelin_equivreverse p G hG).toLinearMap =
      (mFAdditi.zasslayer_onelin_equivreverse p H hH).toLinearMap.comp
        (mFAdditi.mapLinear (p := p) f) := by
  rw [mFAdditi.zasslayer_onelinequiv_reverselinmap,
    mFAdditi.zasslayer_onelinequiv_reverselinmap]
  exact mFAdditi.zass_layerone_linnatural (p := p) (G := G) f

/-- Pointwise form of naturality for the conditional direct equivalence. -/
theorem mFAdditi.zasslayer_onelinequiv_revenatuappl
    [Fact p.Prime] {H : Type*} [Group H]
    (hG : zSubgro p G 2 ≤ modPFrattini p G)
    (hH : zSubgro p H 2 ≤ modPFrattini p H) (f : G →* H)
    (x : mFAdditi p G) :
    zLKern.mapLinear p G f 1
        ((mFAdditi.zasslayer_onelin_equivreverse p G hG) x) =
      (mFAdditi.zasslayer_onelin_equivreverse p H hH)
        (mFAdditi.mapLinear (p := p) f x) := by
  change zLKern.mapLinear p G f 1
        (mFAdditi.zass_layer_onelin p G x) =
      mFAdditi.zass_layer_onelin p H
        (mFAdditi.mapLinear (p := p) f x)
  have h := congrArg
    (fun L : mFAdditi p G →ₗ[ZMod p] Additive (zLKern p H 1) => L x)
    (mFAdditi.zass_layerone_linnatural (p := p) (G := G) f)
  simpa only [LinearMap.comp_apply] using h

/-- Inverse pointwise form of naturality for the conditional direct equivalence. -/
theorem mFAdditi.zasslayerone_linequivreverse_symmnatuappl
    [Fact p.Prime] {H : Type*} [Group H]
    (hG : zSubgro p G 2 ≤ modPFrattini p G)
    (hH : zSubgro p H 2 ≤ modPFrattini p H) (f : G →* H)
    (y : Additive (zLKern p G 1)) :
    (mFAdditi.zasslayer_onelin_equivreverse p H hH).symm
        (zLKern.mapLinear p G f 1 y) =
      mFAdditi.mapLinear (p := p) f
        ((mFAdditi.zasslayer_onelin_equivreverse p G hG).symm y) := by
  let x := (mFAdditi.zasslayer_onelin_equivreverse p G hG).symm y
  have hn := mFAdditi.zasslayer_onelinequiv_revenatuappl
    (p := p) (G := G) hG hH f x
  calc
    (mFAdditi.zasslayer_onelin_equivreverse p H hH).symm
        (zLKern.mapLinear p G f 1 y)
        = (mFAdditi.zasslayer_onelin_equivreverse p H hH).symm
            (zLKern.mapLinear p G f 1
              ((mFAdditi.zasslayer_onelin_equivreverse p G hG) x)) := by
          simp [x]
    _ = (mFAdditi.zasslayer_onelin_equivreverse p H hH).symm
          ((mFAdditi.zasslayer_onelin_equivreverse p H hH)
            (mFAdditi.mapLinear (p := p) f x)) := by
          rw [hn]
    _ = mFAdditi.mapLinear (p := p) f x := by simp

end

end Submission
