import Submission.NumberTheory.TameDiscriminant


open Filter
open scoped Pointwise EuclideanGeometry Topology

noncomputable section

open NumberField

namespace Submission

/-- The generating set for the `p`-Zassenhaus filtration. We use the standard description
`D_n = ∏_{(i+1) p^j ≥ n} γ_{i+1}(G)^{p^j}`, expressed as the subgroup generated by the
corresponding powers of elements in the lower central series. Mathlib indexes the lower central
series by `γ₁(G) = G = Subgroup.lowerCentralSeries G 0`, hence the shift by `i + 1` below. -/
def zassenhausGeneratorSet (p : ℕ) (G : Type*) [Group G] (n : ℕ) : Set G :=
  { g | ∃ i j : ℕ, ∃ x : G,
      x ∈ Subgroup.lowerCentralSeries G i ∧
      n ≤ (i + 1) * p ^ j ∧
      x ^ (p ^ j) = g }

/-- The `p`-Zassenhaus filtration of a group, indexed so that `D₁(G) = G`. -/
def zassenhausFiltration (p : ℕ) (G : Type*) [Group G] (n : ℕ) : Subgroup G :=
  Subgroup.closure (zassenhausGeneratorSet p G n)

theorem generator_set_antitone (p : ℕ) (G : Type*) [Group G] :
    Antitone (zassenhausGeneratorSet p G) := by
  intro m n hmn g hg
  rcases hg with ⟨i, j, x, hx, hbound, hpow⟩
  exact ⟨i, j, x, hx, le_trans hmn hbound, hpow⟩

theorem zassenhausFiltration_antitone (p : ℕ) (G : Type*) [Group G] :
    Antitone (zassenhausFiltration p G) := by
  intro m n hmn
  exact Subgroup.closure_mono ((generator_set_antitone p G) hmn)

theorem zassenhausFiltration_one (p : ℕ) (G : Type*) [Group G] :
    zassenhausFiltration p G 1 = ⊤ := by
  apply top_unique
  intro g hg
  refine Subgroup.subset_closure ?_
  refine ⟨0, 0, g, ?_, ?_, ?_⟩
  · simp [Subgroup.lowerCentralSeries_zero]
  · simp
  · simp

theorem zassenhausFiltration_characteristic (p : ℕ) (G : Type*) [Group G] (n : ℕ) :
    (zassenhausFiltration p G n).Characteristic := by
  rw [Subgroup.characteristic_iff_map_le]
  intro ϕ
  rw [zassenhausFiltration, MonoidHom.map_closure]
  apply Subgroup.closure_mono
  rintro _ ⟨g, hg, rfl⟩
  rcases hg with ⟨i, j, x, hx, hbound, rfl⟩
  exact ⟨i, j, ϕ x,
    (Subgroup.lowerCentralSeries.map ϕ.toMonoidHom i) (Subgroup.mem_map_of_mem ϕ.toMonoidHom hx),
    hbound,
    by simp⟩

theorem zassenhausFiltration_normal (p : ℕ) (G : Type*) [Group G] (n : ℕ) :
    (zassenhausFiltration p G n).Normal := by
  letI : (zassenhausFiltration p G n).Characteristic :=
    zassenhausFiltration_characteristic p G n
  infer_instance


/-- In the finite case, a pro-`p` group is simply a finite `p`-group. We package an actual
finite nontrivial `p`-group witness here and keep the numerical invariants in
`PPDatum` separate. -/
structure NPP where
  p : ℕ
  [prime_p : Fact p.Prime]
  carrier : Type
  [instGroup : Group carrier]
  [instFinite : Finite carrier]
  isPGroup : IsPGroup p carrier
  [instNontrivial : Nontrivial carrier]

attribute [instance] NPP.prime_p
attribute [instance] NPP.instGroup
attribute [instance] NPP.instFinite
attribute [instance] NPP.instNontrivial

/-- The possible sizes of finite generating families for the underlying finite `p`-group. -/
def NPP.GeneratorCounts (P : NPP) : Set ℕ := by
  letI := P.instGroup
  exact {n | ∃ φ : FreeGroup (Fin n) →* P.carrier, Function.Surjective φ}

/-- The generator rank `d(G)`: the least number of generators of the finite `p`-group. We model
this as the least `n` for which there is a surjection `FreeGroup (Fin n) -> G`. -/
noncomputable def NPP.generatorRank
    (P : NPP) : ℕ :=
  sInf P.GeneratorCounts

/-- The possible sizes of finite relation sets in presentations of `G` on a minimal generating
set. -/
def NPP.RelationCounts (P : NPP) : Set ℕ := by
  letI := P.instGroup
  exact {r |
    ∃ rels : Fin r → FreeGroup (Fin P.generatorRank),
      Nonempty (PresentedGroup (Set.range rels) ≃* P.carrier)}

/-- The relation rank `r(G)`: the least number of defining relations in a presentation of `G`
using exactly `d(G)` generators. -/
noncomputable def NPP.relationRank
    (P : NPP) : ℕ :=
  sInf P.RelationCounts

/-- An abstract finite pro-`p` group datum: the group itself is now real data, and the numerical
invariants are derived from that group rather than stored independently. -/
structure PPDatum where
  realizesFiniteNontrivial : NPP

/-- The minimal number of generators of the underlying finite `p`-group. -/
noncomputable def PPDatum.generatorRank (H : PPDatum) : ℕ :=
  H.realizesFiniteNontrivial.generatorRank

/-- The minimal number of relations in a minimal-generator presentation of the underlying finite
`p`-group. -/
noncomputable def PPDatum.relationRank (H : PPDatum) : ℕ :=
  H.realizesFiniteNontrivial.relationRank


namespace GShafar

/-!
# Golod--Shafarevich

This file starts a direct proof of the Golod--Shafarevich inequality at the
level of the classical quadratic polynomial `1 - d * t + r * t^2`.

The intended proof splits into two pieces.

1. A group-theoretic/Hilbert-series argument showing positivity of the quadratic
   `1 - d * t + r * t^2` on the interval `(0, 1)`.
2. A short analytic minimization argument turning that positivity into the strict
   inequality `r > d^2 / 4`.

The present file only sets up those statements in a way that can later be
hooked into the abstract pro-`p` infrastructure from the imported source.
-/

/-- The classical Golod--Shafarevich quadratic polynomial. -/
def polynomial (d r t : ℝ) : ℝ :=
  1 - d * t + r * t ^ (2 : ℕ)

/--
The remaining small-generator group-theoretic input, in its sharp one-relator form:
every two-generator one-relator group is infinite.

For the present development, this is the exact ingredient needed to rule out
`generatorRank = 2` and `relationRank = 1` for a finite nontrivial `p`-group.
-/
def TwoRelatorInfinite : Prop :=
  ∀ w : FreeGroup (Fin 2),
    Infinite (PresentedGroup ({w} : Set (FreeGroup (Fin 2))))

/-- The image of a relator in the abelianization of the free group on two generators. -/
def relatorVector (w : FreeGroup (Fin 2)) : Fin 2 →₀ ℤ :=
  FreeAbelianGroup.toFinsupp (Additive.ofMul (Abelianization.of w))

lemma free_abelian_sum {α A : Type*} [Fintype α] [AddCommGroup A]
    (f : α → A) (a : FreeAbelianGroup α) :
    FreeAbelianGroup.lift f a = ∑ i, (FreeAbelianGroup.toFinsupp a i) • f i := by
  have hsum :
      FreeAbelianGroup.lift f a =
        (FreeAbelianGroup.toFinsupp a).sum fun i n => n • f i := by
    induction a using FreeAbelianGroup.induction_on with
    | zero =>
        simp
    | of x =>
        simp
    | neg x hx =>
        simp [hx, Finsupp.sum_neg_index, Finsupp.sum_single_index]
    | add x y hx hy =>
        rw [map_add, hx, hy]
        symm
        simpa [map_add] using (Finsupp.sum_add_index'
          (f := FreeAbelianGroup.toFinsupp x)
          (g := FreeAbelianGroup.toFinsupp y)
          (h := fun i n => n • f i)
          (h_zero := by intro i; simp)
          (h_add := by intro i n₁ n₂; simp [add_zsmul]))
  rw [hsum, Finsupp.sum_fintype]
  intro i
  simp

/-- The image of a free-group word in the integral abelianization basis. -/
def abelianizationVector {α : Type*} [Fintype α] (w : FreeGroup α) : α →₀ ℤ :=
  FreeAbelianGroup.toFinsupp (Additive.ofMul (Abelianization.of w))

lemma lift_abelianization_vector {α : Type*} [Fintype α]
    (f : α → ℤ) (w : FreeGroup α) :
    FreeGroup.lift (fun i => Multiplicative.ofAdd (f i)) w =
      Multiplicative.ofAdd (∑ i, abelianizationVector w i * f i) := by
  change
    Multiplicative.ofAdd ((FreeAbelianGroup.lift f) (Additive.ofMul (Abelianization.of w))) =
      Multiplicative.ofAdd (∑ i, abelianizationVector w i * f i)
  congr 1
  simpa [abelianizationVector, zsmul_eq_mul] using
    free_abelian_sum f (Additive.ofMul (Abelianization.of w))

lemma abelianization_vector_zsmul {α A : Type*} [Fintype α]
    [AddCommGroup A] (f : α → A) (w : FreeGroup α) :
    FreeGroup.lift (fun i => Multiplicative.ofAdd (f i)) w =
      Multiplicative.ofAdd (∑ i, abelianizationVector w i • f i) := by
  change
    Multiplicative.ofAdd ((FreeAbelianGroup.lift f) (Additive.ofMul (Abelianization.of w))) =
      Multiplicative.ofAdd (∑ i, abelianizationVector w i • f i)
  congr 1
  simpa [abelianizationVector] using
    free_abelian_sum f (Additive.ofMul (Abelianization.of w))

lemma free_lift_vector (f : Fin 2 → ℤ) (w : FreeGroup (Fin 2)) :
    FreeGroup.lift (fun i => Multiplicative.ofAdd (f i)) w =
      Multiplicative.ofAdd (∑ i, relatorVector w i * f i) := by
  simpa [relatorVector, abelianizationVector] using
    lift_abelianization_vector f w

lemma surjective_multiplicative_preimage {G : Type*} [Group G]
    (φ : G →* Multiplicative ℤ)
    (hgen : ∃ g : G, φ g = Multiplicative.ofAdd (1 : ℤ)) :
    Function.Surjective φ := by
  intro y
  obtain ⟨z, rfl⟩ := Multiplicative.ofAdd.surjective y
  rcases hgen with ⟨g, hg⟩
  refine ⟨g ^ z, ?_⟩
  rw [map_zpow, hg]
  simpa using (Int.ofAdd_mul (1 : ℤ) z).symm

lemma presented_surjects_onto (w : FreeGroup (Fin 2))
    (hv : relatorVector w = 0) :
    ∃ φ : PresentedGroup ({w} : Set (FreeGroup (Fin 2))) →* Multiplicative ℤ,
      Function.Surjective φ := by
  let f : Fin 2 → ℤ := fun i => if i = 0 then 1 else 0
  have hw : FreeGroup.lift (fun i => Multiplicative.ofAdd (f i)) w = 1 := by
    simpa [hv, f, Fin.sum_univ_two]
      using free_lift_vector f w
  have hw' : ∀ r ∈ ({w} : Set (FreeGroup (Fin 2))),
      FreeGroup.lift (fun i => Multiplicative.ofAdd (f i)) r = 1 := by
    intro r hr
    simpa [Set.mem_singleton_iff.mp hr] using hw
  let φ : PresentedGroup ({w} : Set (FreeGroup (Fin 2))) →* Multiplicative ℤ :=
    PresentedGroup.toGroup (rels := ({w} : Set (FreeGroup (Fin 2)))) hw'
  refine ⟨φ, surjective_multiplicative_preimage φ ?_⟩
  refine ⟨PresentedGroup.of (rels := ({w} : Set (FreeGroup (Fin 2)))) 0, ?_⟩
  simp [φ, f]

lemma presented_surjects_vector (w : FreeGroup (Fin 2))
    (hv : relatorVector w ≠ 0) :
    ∃ φ : PresentedGroup ({w} : Set (FreeGroup (Fin 2))) →* Multiplicative ℤ,
      Function.Surjective φ := by
  let m : ℤ := relatorVector w 0
  let n : ℤ := relatorVector w 1
  have hmn : ¬ (m = 0 ∧ n = 0) := by
    intro h
    apply hv
    ext i
    fin_cases i
    · simpa [m] using h.1
    · simpa [n] using h.2
  have hgpos : 0 < m.gcd n := by
    exact Nat.pos_of_ne_zero fun h0 => hmn (Int.gcd_eq_zero_iff.mp h0)
  let d : ℤ := Int.gcd m n
  let u₀ : ℤ := n / d
  let v₁ : ℤ := m / d
  let f : Fin 2 → ℤ := fun i => if i = 0 then u₀ else -v₁
  have hdvdm : d ∣ m := by simpa [d] using (Int.gcd_dvd_left m n)
  have hdvdn : d ∣ n := by simpa [d] using (Int.gcd_dvd_right m n)
  have hsum : ∑ i, relatorVector w i * f i = 0 := by
    rw [Fin.sum_univ_two]
    change m * u₀ + n * (-v₁) = 0
    rw [← Int.mul_ediv_assoc m hdvdn]
    simp only [v₁]
    rw [mul_neg, ← Int.mul_ediv_assoc n hdvdm]
    ring_nf
  have hw : FreeGroup.lift (fun i => Multiplicative.ofAdd (f i)) w = 1 := by
    rw [free_lift_vector, hsum]
    simp
  have hw' : ∀ r ∈ ({w} : Set (FreeGroup (Fin 2))),
      FreeGroup.lift (fun i => Multiplicative.ofAdd (f i)) r = 1 := by
    intro r hr
    simpa [Set.mem_singleton_iff.mp hr] using hw
  let φ : PresentedGroup ({w} : Set (FreeGroup (Fin 2))) →* Multiplicative ℤ :=
    PresentedGroup.toGroup (rels := ({w} : Set (FreeGroup (Fin 2)))) hw'
  have hcop : u₀.gcd v₁ = 1 := by
    dsimp [u₀, v₁, d]
    simpa [Int.gcd_comm n m] using
      (Int.gcd_ediv_gcd_ediv_gcd (i := n) (j := m) (by simpa [Int.gcd_comm n m] using hgpos))
  have hbez : u₀ * Int.gcdA u₀ v₁ + (-Int.gcdB u₀ v₁) * (-v₁) = 1 := by
    have h : (1 : ℤ) = u₀ * Int.gcdA u₀ v₁ + v₁ * Int.gcdB u₀ v₁ := by
      simpa [hcop] using (Int.gcd_eq_gcd_ab u₀ v₁)
    nlinarith
  have hbez' : u₀ * Int.gcdA u₀ v₁ + (-v₁) * (-Int.gcdB u₀ v₁) = 1 := by
    simpa [mul_comm] using hbez
  refine ⟨φ, surjective_multiplicative_preimage φ ?_⟩
  refine ⟨(PresentedGroup.of (rels := ({w} : Set (FreeGroup (Fin 2)))) 0) ^ Int.gcdA u₀ v₁ *
      (PresentedGroup.of (rels := ({w} : Set (FreeGroup (Fin 2)))) 1) ^ (-Int.gcdB u₀ v₁), ?_⟩
  have hφ :
      φ ((PresentedGroup.of (rels := ({w} : Set (FreeGroup (Fin 2)))) 0) ^ Int.gcdA u₀ v₁ *
          (PresentedGroup.of (rels := ({w} : Set (FreeGroup (Fin 2)))) 1) ^ (-Int.gcdB u₀ v₁)) =
        Multiplicative.ofAdd
          (u₀ * Int.gcdA u₀ v₁ + (-v₁) * (-Int.gcdB u₀ v₁)) := by
    simp [φ, f, Int.ofAdd_mul, mul_comm]
  rw [hφ, hbez']

/--
The one-relator input needed for the Golod--Shafarevich reduction:
every two-generator one-relator group has a surjection onto `ℤ`, hence is
infinite.
-/
theorem twoRelatorInfinite : TwoRelatorInfinite := by
  intro w
  by_cases hv : relatorVector w = 0
  · rcases presented_surjects_onto w hv with ⟨φ, hφ⟩
    exact Infinite.of_surjective φ hφ
  · rcases presented_surjects_vector w hv with ⟨φ, hφ⟩
    exact Infinite.of_surjective φ hφ

@[simp] lemma abelianizationVector_one {α : Type*} [Fintype α] :
    abelianizationVector (1 : FreeGroup α) = 0 := by
  change FreeAbelianGroup.toFinsupp (Additive.ofMul (Abelianization.of (1 : FreeGroup α))) = 0
  rw [map_one]
  exact FreeAbelianGroup.toFinsupp.map_zero

@[simp] lemma abelianizationVector_mul {α : Type*} [Fintype α]
    (u v : FreeGroup α) :
    abelianizationVector (u * v) = abelianizationVector u + abelianizationVector v := by
  change
    FreeAbelianGroup.toFinsupp (Additive.ofMul (Abelianization.of (u * v))) =
      FreeAbelianGroup.toFinsupp (Additive.ofMul (Abelianization.of u)) +
        FreeAbelianGroup.toFinsupp (Additive.ofMul (Abelianization.of v))
  rw [map_mul]
  exact FreeAbelianGroup.toFinsupp.map_add _ _

@[simp] lemma abelianizationVector_inv {α : Type*} [Fintype α]
    (u : FreeGroup α) :
    abelianizationVector u⁻¹ = -abelianizationVector u := by
  change
    FreeAbelianGroup.toFinsupp (Additive.ofMul (Abelianization.of u⁻¹)) =
      -FreeAbelianGroup.toFinsupp (Additive.ofMul (Abelianization.of u))
  rw [map_inv]
  exact FreeAbelianGroup.toFinsupp.map_neg _

lemma free_abelianization_vector {α : Type*} [Fintype α]
    (w : FreeGroup α) :
    FreeGroup.lift
        (fun i => Multiplicative.ofAdd (Finsupp.single i (1 : ℤ) : α →₀ ℤ)) w =
      Multiplicative.ofAdd (abelianizationVector w) := by
  apply Multiplicative.ofAdd.injective
  simpa [abelianizationVector, Finsupp.sum_single] using
    (free_abelian_sum
      (f := fun i => (Finsupp.single i (1 : ℤ) : α →₀ ℤ))
      (a := Additive.ofMul (Abelianization.of w)))

@[simp] lemma abelianization_vector_zpow {α : Type*} [Fintype α]
    (a : α) (n : ℤ) :
    abelianizationVector ((FreeGroup.of a) ^ n) = Finsupp.single a n := by
  have h :=
    free_abelianization_vector
      (α := α) (w := (FreeGroup.of a) ^ n)
  rw [map_zpow] at h
  simpa using congrArg Multiplicative.toAdd h.symm

lemma word_abelianization_vector {α : Type*} [Fintype α] (v : α →₀ ℤ) :
    ∃ w : FreeGroup α, abelianizationVector w = v := by
  classical
  refine Finsupp.induction v ?_ ?_
  · exact ⟨1, by simp⟩
  · intro a n v ha hn ih
    rcases ih with ⟨w, hw⟩
    refine ⟨(FreeGroup.of a) ^ n * w, ?_⟩
    simp [hw]

/-- A chosen word in the free group realizing a finitely supported exponent vector. -/
noncomputable def wordOfFinsupp {α : Type*} [Fintype α] (v : α →₀ ℤ) : FreeGroup α :=
  Classical.choose (word_abelianization_vector (α := α) v)

lemma abelianization_vector_finsupp {α : Type*} [Fintype α] (v : α →₀ ℤ) :
    abelianizationVector (wordOfFinsupp v) = v := by
  exact Classical.choose_spec (word_abelianization_vector (α := α) v)

lemma commutator_abelianization_vector {α : Type*} [Fintype α]
    {w : FreeGroup α} (hzero : abelianizationVector w = 0) :
    w ∈ _root_.commutator (FreeGroup α) := by
  have hab : Additive.ofMul (Abelianization.of w) = 0 := by
    simpa [abelianizationVector] using congrArg Finsupp.toFreeAbelianGroup hzero
  have hker_eq : Abelianization.of w = 1 := by
    simpa using hab
  rw [← Abelianization.ker_of]
  exact MonoidHom.mem_ker.mpr hker_eq

lemma zassenhaus_filtration_commutator {α : Type*}
    {p : ℕ} [Fact p.Prime] {w : FreeGroup α}
    (hw : w ∈ _root_.commutator (FreeGroup α)) :
    w ∈ zassenhausFiltration p (FreeGroup α) 2 := by
  refine Subgroup.subset_closure ?_
  refine ⟨1, 0, w, ?_, ?_, ?_⟩
  · simpa [Subgroup.lowerCentralSeries_one] using hw
  · simp
  · simp

lemma pow_filtration_two {α : Type*}
    {p : ℕ} [Fact p.Prime] (w : FreeGroup α) :
    w ^ p ∈ zassenhausFiltration p (FreeGroup α) 2 := by
  have hp2 : 2 ≤ p := Nat.Prime.two_le (Fact.out : Nat.Prime p)
  refine Subgroup.subset_closure ?_
  refine ⟨0, 1, w, ?_, ?_, ?_⟩
  · simp [Subgroup.lowerCentralSeries_zero]
  · simpa using hp2
  · simp

lemma filtration_dvd_finsupp
    {α : Type*} [Fintype α] {p : ℕ} [Fact p.Prime] (v : α →₀ ℤ)
    (hdiv : ∀ a, (p : ℤ) ∣ v a) :
    ∃ u : FreeGroup α,
      abelianizationVector u = v ∧
      u ∈ zassenhausFiltration p (FreeGroup α) 2 := by
  classical
  let D₂ := zassenhausFiltration p (FreeGroup α) 2
  refine Finsupp.induction v ?_ ?_ hdiv
  · intro _
    refine ⟨1, by simp, D₂.one_mem⟩
  · intro a n v ha hn ih hdiv'
    have hva : v a = 0 := Finsupp.notMem_support_iff.mp ha
    have hdn : (p : ℤ) ∣ n := by
      simpa [hva] using hdiv' a
    have hdivv : ∀ b, (p : ℤ) ∣ v b := by
      intro b
      by_cases hb : b = a
      · subst hb
        simp [hva]
      · simpa [Finsupp.single_eq_of_ne hb] using hdiv' b
    rcases ih hdivv with ⟨u, huvec, huD₂⟩
    obtain ⟨k, hk⟩ := hdn
    have hpow : (FreeGroup.of a) ^ n ∈ D₂ := by
      have hbase : (FreeGroup.of a) ^ (p : ℤ) ∈ D₂ := by
        simpa [zpow_natCast] using
          (pow_filtration_two (α := α) (FreeGroup.of a))
      rw [hk, zpow_mul]
      exact D₂.zpow_mem hbase k
    refine ⟨(FreeGroup.of a) ^ n * u, ?_, D₂.mul_mem hpow huD₂⟩
    simp [huvec]

/--
If every coordinate of a relator's integral abelianization is divisible by `p`,
then the relator already lies in the second Zassenhaus term `D₂`.

This is the exact algebraic input needed to turn mod-`p` abelianization control
of minimal relators into the depth-`2` part of the Golod--Shafarevich setup.
-/
theorem dvd_abelianization_vector
    {α : Type*} [Fintype α] {p : ℕ} [Fact p.Prime] {w : FreeGroup α}
    (hdiv : ∀ a, (p : ℤ) ∣ abelianizationVector w a) :
    w ∈ zassenhausFiltration p (FreeGroup α) 2 := by
  let D₂ := zassenhausFiltration p (FreeGroup α) 2
  rcases filtration_dvd_finsupp
      (p := p) (v := abelianizationVector w) hdiv with ⟨u, huvec, hu⟩
  have hzero : abelianizationVector (w * u⁻¹) = 0 := by
    simp [huvec]
  have hwu : w * u⁻¹ ∈ D₂ := by
    exact zassenhaus_filtration_commutator
      (commutator_abelianization_vector hzero)
  have hmul : (w * u⁻¹) * u ∈ D₂ := D₂.mul_mem hwu hu
  simpa using hmul

/-- The relator abelianization vector reduced modulo `p`. -/
def modAbelianizationVector {α : Type*} [Fintype α] (p : ℕ) (w : FreeGroup α) :
    α →₀ ZMod p :=
  (abelianizationVector w).mapRange (fun z : ℤ => (z : ZMod p)) (by simp)

lemma zsmul_abelianization_vector {α : Type*} [Fintype α]
    (p : ℕ) (w : FreeGroup α) :
    (∑ i, abelianizationVector w i •
      (Finsupp.single i (1 : ZMod p) : α →₀ ZMod p)) =
      modAbelianizationVector p w := by
  calc
    (∑ i, abelianizationVector w i •
      (Finsupp.single i (1 : ZMod p) : α →₀ ZMod p)) =
        ∑ i, Finsupp.single i ((abelianizationVector w i : ℤ) : ZMod p) := by
          refine Finset.sum_congr rfl ?_
          intro i hi
          ext a
          simp
    _ = modAbelianizationVector p w := by
      simpa [modAbelianizationVector] using
        (Finsupp.univ_sum_single (f := modAbelianizationVector p w))

lemma single_abelianization_vector {α : Type*} [Fintype α]
    (p : ℕ) (w : FreeGroup α) :
    FreeGroup.lift
        (fun i => Multiplicative.ofAdd (Finsupp.single i (1 : ZMod p) : α →₀ ZMod p)) w =
      Multiplicative.ofAdd (modAbelianizationVector p w) := by
  rw [abelianization_vector_zsmul]
  congr 1
  exact zsmul_abelianization_vector p w

/--
Vanishing of the mod-`p` abelianization vector is equivalent to divisibility of
every integral abelianization coordinate by `p`.
-/
theorem abelianization_vector_zero {α : Type*} [Fintype α]
    {p : ℕ} [Fact p.Prime] {w : FreeGroup α} :
    modAbelianizationVector p w = 0 ↔
      ∀ a, (p : ℤ) ∣ abelianizationVector w a := by
  constructor
  · intro h a
    have ha : modAbelianizationVector p w a = 0 := by
      simpa using congrArg (fun v : α →₀ ZMod p => v a) h
    have ha' : (((abelianizationVector w a : ℤ) : ZMod p) = 0) := by
      simpa [modAbelianizationVector] using ha
    exact (ZMod.intCast_zmod_eq_zero_iff_dvd (abelianizationVector w a) p).mp ha'
  · intro h
    ext a
    have ha' : (((abelianizationVector w a : ℤ) : ZMod p) = 0) :=
      (ZMod.intCast_zmod_eq_zero_iff_dvd (abelianizationVector w a) p).2 (h a)
    simpa [modAbelianizationVector] using ha'

/--
The depth-`2` upgrade can be phrased directly in the mod-`p` abelianization:
if a relator dies in the elementary abelian `p`-quotient of the free group,
then it already lies in the second Zassenhaus term.
-/
theorem filtration_abelianization_vector
    {α : Type*} [Fintype α] {p : ℕ} [Fact p.Prime] {w : FreeGroup α}
    (hzero : modAbelianizationVector p w = 0) :
    w ∈ zassenhausFiltration p (FreeGroup α) 2 := by
  apply dvd_abelianization_vector
  exact (abelianization_vector_zero (p := p) (w := w)).mp hzero

section MonoidAlgebraCharacteristic

variable {R M : Type*} [Semiring R] [MulOneClass M]

theorem single_ring_injective :
    Function.Injective (MonoidAlgebra.singleOneRingHom (R := R) (M := M)) := by
  intro a b hab
  have h1 := congrArg (fun f : MonoidAlgebra R M => f 1) hab
  simpa [MonoidAlgebra.singleOneRingHom, Finsupp.single_apply] using h1

instance monoid_char_p (p : ℕ) [CharP R p] : CharP (MonoidAlgebra R M) p :=
  charP_of_injective_ringHom single_ring_injective p

end MonoidAlgebraCharacteristic

section AugmentationIdeal

variable {R G : Type*} [CommRing R] [Group G]

/-- The trivial multiplicative character of a group into its coefficient ring. -/
def augmentationCharacter (R G : Type*) [Semiring R] [Monoid G] : G →* R where
  toFun _ := 1
  map_one' := rfl
  map_mul' _ _ := by simp

/-- The augmentation homomorphism on the group algebra `R[G]`. -/
def augmentationHom (R G : Type*) [CommSemiring R] [Monoid G] :
    MonoidAlgebra R G →ₐ[R] R :=
  MonoidAlgebra.lift R R G (augmentationCharacter R G)

/-- The augmentation ideal of the group algebra `R[G]`. -/
def augmentationIdeal (R G : Type*) [CommSemiring R] [Monoid G] :
    Ideal (MonoidAlgebra R G) :=
  RingHom.ker (augmentationHom R G).toRingHom

instance augmentation_ideal_sided :
    (augmentationIdeal (R := R) (G := G)).IsTwoSided := by
  dsimp [augmentationIdeal]
  infer_instance

@[simp] lemma augmentationHom_of (g : G) :
    augmentationHom (R := R) (G := G) (MonoidAlgebra.of R G g) = 1 := by
  simp [augmentationHom, augmentationCharacter]

@[simp] lemma augmentationHom_one :
    augmentationHom (R := R) (G := G) (1 : MonoidAlgebra R G) = 1 := by
  simp [augmentationHom]

lemma sub_augmentation_ideal (g : G) :
    MonoidAlgebra.of R G g - 1 ∈ augmentationIdeal (R := R) (G := G) := by
  rw [augmentationIdeal, RingHom.mem_ker, map_sub, map_one]
  simp [augmentationHom, augmentationCharacter]

lemma of_sub_eq (g h : G) :
    MonoidAlgebra.of R G (g * h) - 1 =
      (MonoidAlgebra.of R G g - 1) * (MonoidAlgebra.of R G h - 1) +
        (MonoidAlgebra.of R G g - 1) + (MonoidAlgebra.of R G h - 1) := by
  rw [MonoidHom.map_mul]
  noncomm_ring

lemma inv_sub (g : G) :
    MonoidAlgebra.of R G g⁻¹ - 1 =
      -MonoidAlgebra.of R G g⁻¹ * (MonoidAlgebra.of R G g - 1) := by
  have hmul : MonoidAlgebra.of R G g⁻¹ * MonoidAlgebra.of R G g = 1 := by
    calc
      MonoidAlgebra.of R G g⁻¹ * MonoidAlgebra.of R G g
          = MonoidAlgebra.of R G (g⁻¹ * g) := by simp
      _ = 1 := by
        rw [inv_mul_cancel]
        rfl
  calc
    MonoidAlgebra.of R G g⁻¹ - 1 =
      MonoidAlgebra.of R G g⁻¹ - MonoidAlgebra.of R G g⁻¹ * MonoidAlgebra.of R G g := by
        rw [hmul]
    _ = -MonoidAlgebra.of R G g⁻¹ * (MonoidAlgebra.of R G g - 1) := by
      noncomm_ring

/--
Group elements whose augmentation difference lies in the `n`th power of the
augmentation ideal.
-/
def augmentationPowerSubgroup (n : ℕ) : Subgroup G where
  carrier := { g | MonoidAlgebra.of R G g - 1 ∈ augmentationIdeal (R := R) (G := G) ^ n }
  one_mem' := by
    change MonoidAlgebra.single (1 : G) (1 : R) - 1 ∈ augmentationIdeal (R := R) (G := G) ^ n
    rw [MonoidAlgebra.one_def, sub_self]
    exact (augmentationIdeal (R := R) (G := G) ^ n).zero_mem
  mul_mem' := by
    intro a b ha hb
    change MonoidAlgebra.of R G (a * b) - 1 ∈ augmentationIdeal (R := R) (G := G) ^ n
    rw [of_sub_eq]
    let I : Ideal (MonoidAlgebra R G) := augmentationIdeal (R := R) (G := G)
    have hprod :
        (MonoidAlgebra.of R G a - 1) * (MonoidAlgebra.of R G b - 1) ∈ I ^ n * I ^ n :=
      Ideal.mul_mem_mul ha hb
    have hprod' :
        (MonoidAlgebra.of R G a - 1) * (MonoidAlgebra.of R G b - 1) ∈ I ^ n := by
      exact (Ideal.mul_le_left (I := I ^ n) (J := I ^ n)) hprod
    exact Ideal.add_mem _ (Ideal.add_mem _ hprod' ha) hb
  inv_mem' := by
    intro a ha
    change MonoidAlgebra.of R G a⁻¹ - 1 ∈ augmentationIdeal (R := R) (G := G) ^ n
    rw [inv_sub]
    have hmul :
        MonoidAlgebra.of R G a⁻¹ * (MonoidAlgebra.of R G a - 1) ∈
          augmentationIdeal (R := R) (G := G) ^ n :=
      Ideal.mul_mem_left _ (MonoidAlgebra.of R G a⁻¹) ha
    simpa [neg_mul] using neg_mem hmul

lemma commutator_sub_one (g h : G) :
    MonoidAlgebra.of R G (g * h * g⁻¹ * h⁻¹) - 1 =
      (((MonoidAlgebra.of R G g - 1) * (MonoidAlgebra.of R G h - 1) -
          (MonoidAlgebra.of R G h - 1) * (MonoidAlgebra.of R G g - 1)) *
          MonoidAlgebra.of R G g⁻¹) * MonoidAlgebra.of R G h⁻¹ := by
  let u := MonoidAlgebra.of R G g
  let v := MonoidAlgebra.of R G h
  let uinv := MonoidAlgebra.of R G g⁻¹
  let vinv := MonoidAlgebra.of R G h⁻¹
  calc
    MonoidAlgebra.of R G (g * h * g⁻¹ * h⁻¹) - 1 = u * v * uinv * vinv - 1 := by
      simp [u, v, uinv, vinv, mul_assoc]
    _ = u * v * uinv * vinv - v * u * uinv * vinv := by
      have hcancel : v * u * uinv * vinv = 1 := by
        simp [u, v, uinv, vinv, mul_assoc, MonoidAlgebra.one_def]
      rw [hcancel]
    _ = ((u * v - v * u) * uinv) * vinv := by
      noncomm_ring
    _ =
        (((u - 1) * (v - 1) - (v - 1) * (u - 1)) * uinv) * vinv := by
      noncomm_ring

theorem commutator_augmentation_subgroup {m n : ℕ} {g h : G}
    (hg : g ∈ augmentationPowerSubgroup (R := R) (G := G) n)
    (hh : h ∈ augmentationPowerSubgroup (R := R) (G := G) m) :
    g * h * g⁻¹ * h⁻¹ ∈ augmentationPowerSubgroup (R := R) (G := G) (n + m) := by
  change MonoidAlgebra.of R G (g * h * g⁻¹ * h⁻¹) - 1 ∈
    augmentationIdeal (R := R) (G := G) ^ (n + m)
  rw [commutator_sub_one]
  let I : Ideal (MonoidAlgebra R G) := augmentationIdeal (R := R) (G := G)
  letI : I.IsTwoSided := by
    dsimp [I, augmentationIdeal]
    infer_instance
  have hnm :
      (MonoidAlgebra.of R G g - 1) * (MonoidAlgebra.of R G h - 1) ∈ I ^ (n + m) := by
    have hmul :
        (MonoidAlgebra.of R G g - 1) * (MonoidAlgebra.of R G h - 1) ∈ I ^ n * I ^ m :=
      Ideal.mul_mem_mul hg hh
    have hpow : I ^ (n + m) = I ^ n * I ^ m := by
      simpa using (Ideal.IsTwoSided.pow_add (I := I) (m := n) (n := m))
    exact hpow.symm ▸ hmul
  have hmn :
      (MonoidAlgebra.of R G h - 1) * (MonoidAlgebra.of R G g - 1) ∈ I ^ (n + m) := by
    have hmul :
        (MonoidAlgebra.of R G h - 1) * (MonoidAlgebra.of R G g - 1) ∈ I ^ m * I ^ n :=
      Ideal.mul_mem_mul hh hg
    have hpow : I ^ (m + n) = I ^ m * I ^ n := by
      simpa using (Ideal.IsTwoSided.pow_add (I := I) (m := m) (n := n))
    exact by
      rw [Nat.add_comm] at hpow
      exact hpow.symm ▸ hmul
  have hsub :
      (MonoidAlgebra.of R G g - 1) * (MonoidAlgebra.of R G h - 1) -
        (MonoidAlgebra.of R G h - 1) * (MonoidAlgebra.of R G g - 1) ∈ I ^ (n + m) :=
    sub_mem hnm hmn
  have hright :
      (((MonoidAlgebra.of R G g - 1) * (MonoidAlgebra.of R G h - 1) -
          (MonoidAlgebra.of R G h - 1) * (MonoidAlgebra.of R G g - 1)) *
          MonoidAlgebra.of R G g⁻¹) ∈ I ^ (n + m) :=
    Ideal.mul_mem_right (MonoidAlgebra.of R G g⁻¹) (I ^ (n + m)) hsub
  exact Ideal.mul_mem_right (MonoidAlgebra.of R G h⁻¹) (I ^ (n + m)) hright

theorem augmentation_descending_series :
    Subgroup.IsDescendingCentralSeries
      (fun n => augmentationPowerSubgroup (R := R) (G := G) (n + 1)) := by
  constructor
  · ext g
    constructor
    · intro _
      simp
    · intro _
      have h :
          MonoidAlgebra.of R G g - 1 ∈ augmentationIdeal (R := R) (G := G) ^ 1 := by
        simpa [Submodule.pow_one] using
          (sub_augmentation_ideal (R := R) (G := G) g)
      simpa [augmentationPowerSubgroup] using h
  · intro x n hx g
    have hg : g ∈ augmentationPowerSubgroup (R := R) (G := G) 1 := by
      have h :
          MonoidAlgebra.of R G g - 1 ∈ augmentationIdeal (R := R) (G := G) ^ 1 := by
        simpa [Submodule.pow_one] using
          (sub_augmentation_ideal (R := R) (G := G) g)
      simpa [augmentationPowerSubgroup] using h
    simpa [Nat.add_assoc] using
      (commutator_augmentation_subgroup (R := R) (G := G) hx hg)

theorem lower_series_succ (n : ℕ) :
    Subgroup.lowerCentralSeries G n ≤ augmentationPowerSubgroup (R := R) (G := G) (n + 1) := by
  exact Subgroup.descending_central_series_ge_lower
    (H := fun k => augmentationPowerSubgroup (R := R) (G := G) (k + 1))
    augmentation_descending_series n

theorem augmentation_subgroup_antitone :
    Antitone (augmentationPowerSubgroup (R := R) (G := G)) := by
  intro m n hmn g hg
  exact (Ideal.pow_le_pow_right hmn) hg

end AugmentationIdeal

lemma ideal_pow_mul {R : Type*} [Semiring R] (I : Ideal R) [I.IsTwoSided] (m n : ℕ) :
    (I ^ m) ^ n = I ^ (m * n) := by
  induction n with
  | zero =>
      rw [Submodule.pow_zero, Nat.mul_zero, Submodule.pow_zero]
  | succ n ih =>
      calc
        (I ^ m) ^ (n + 1) = (I ^ m) ^ n * I ^ m := by
          rw [Submodule.pow_succ]
        _ = I ^ (m * n) * I ^ m := by
          rw [ih]
        _ = I ^ (m * n + m) := by
          rw [← Ideal.IsTwoSided.pow_add (I := I) (m := m * n) (n := m)]
        _ = I ^ (m * (n + 1)) := by
          rw [Nat.mul_succ]

section ZassenhausAugmentation

variable {p : ℕ} [Fact p.Prime]
variable {G : Type*} [Group G]

lemma sub_pow_prime (j : ℕ) (g : G) :
    (MonoidAlgebra.of (ZMod p) G g - 1) ^ (p ^ j) =
      MonoidAlgebra.of (ZMod p) G (g ^ (p ^ j)) - 1 := by
  rw [sub_pow_char_pow_of_commute (p := p) (n := j)
    (x := MonoidAlgebra.of (ZMod p) G g)
    (y := (1 : MonoidAlgebra (ZMod p) G)) (Commute.one_right _)]
  simp [MonoidHom.map_pow]

theorem pow_augmentation_subgroup {m j : ℕ} {g : G}
    (hg : g ∈ augmentationPowerSubgroup (R := ZMod p) (G := G) m) :
    g ^ (p ^ j) ∈ augmentationPowerSubgroup (R := ZMod p) (G := G) (m * p ^ j) := by
  let I : Ideal (MonoidAlgebra (ZMod p) G) := augmentationIdeal (R := ZMod p) (G := G)
  letI : I.IsTwoSided := by
    dsimp [I, augmentationIdeal]
    infer_instance
  change MonoidAlgebra.of (ZMod p) G (g ^ (p ^ j)) - 1 ∈
    I ^ (m * p ^ j)
  rw [← sub_pow_prime (p := p) (j := j) (g := g)]
  have hpow :
      (MonoidAlgebra.of (ZMod p) G g - 1) ^ (p ^ j) ∈
        (I ^ m) ^ (p ^ j) :=
    Ideal.pow_mem_pow hg (p ^ j)
  convert hpow using 1
  exact (ideal_pow_mul I m (p ^ j)).symm

theorem zassenhaus_filtration_subgroup (n : ℕ) :
    zassenhausFiltration p G n ≤
      augmentationPowerSubgroup (R := ZMod p) (G := G) n := by
  change Subgroup.closure (zassenhausGeneratorSet p G n) ≤
    augmentationPowerSubgroup (R := ZMod p) (G := G) n
  refine (Subgroup.closure_le
    (K := augmentationPowerSubgroup (R := ZMod p) (G := G) n)).2 ?_
  intro g hg
  rcases hg with ⟨i, j, x, hx, hbound, rfl⟩
  have hx' :
      x ∈ augmentationPowerSubgroup (R := ZMod p) (G := G) (i + 1) :=
    lower_series_succ
      (R := ZMod p) (G := G) i hx
  have hpow :
      x ^ (p ^ j) ∈
        augmentationPowerSubgroup (R := ZMod p) (G := G) ((i + 1) * p ^ j) :=
    pow_augmentation_subgroup
      (p := p) (m := i + 1) (j := j) hx'
  exact (augmentation_subgroup_antitone
    (R := ZMod p) (G := G) hbound) hpow

end ZassenhausAugmentation

section PresentedGroupAlgebra

variable {R α ι : Type*} [Ring R]

/--
The canonical map from the free-group algebra to the group algebra of the
presented group on the same relators.

This is the ring-level quotient map that kills the differences `of r - 1` for
the prescribed relations `r`.
-/
abbrev presentedAlgebra (rels : Set (FreeGroup α)) :
    MonoidAlgebra R (FreeGroup α) →+* MonoidAlgebra R (PresentedGroup rels) :=
  MonoidAlgebra.mapDomainRingHom R (PresentedGroup.mk rels)

/--
Each defining relator contributes a kernel element `of r - 1` in the free-group
algebra.
-/
lemma relator_presented_algebra
    {rels : Set (FreeGroup α)} {r : FreeGroup α} (hr : r ∈ rels) :
    MonoidAlgebra.of R (FreeGroup α) r - 1 ∈
      RingHom.ker (presentedAlgebra (R := R) rels) := by
  change presentedAlgebra (R := R) rels
      (MonoidAlgebra.of R (FreeGroup α) r - 1) = 0
  rw [map_sub, map_one]
  simp [presentedAlgebra, PresentedGroup.one_of_mem hr, MonoidAlgebra.one_def]

/--
For a relator family `rels`, the ideal generated by the differences
`of (rels i) - 1` lies in the kernel of the canonical map to the presented
group algebra.
-/
lemma span_presented_algebra
    (rels : ι → FreeGroup α) :
    Ideal.span (Set.range fun i => MonoidAlgebra.of R (FreeGroup α) (rels i) - 1) ≤
      RingHom.ker (presentedAlgebra (R := R) (Set.range rels)) := by
  rw [Ideal.span_le]
  rintro _ ⟨i, rfl⟩
  exact relator_presented_algebra
    (R := R) (rels := Set.range rels) (r := rels i) (Set.mem_range_self i)

/--
The ideal generated by the relator differences `of (rels i) - 1` in the free-group algebra.

This is the algebraic relation ideal that appears in the classical Golod--Shafarevich
Hilbert-series argument.
-/
def relatorDifferenceIdeal (rels : ι → FreeGroup α) :
    Ideal (MonoidAlgebra R (FreeGroup α)) :=
  (TwoSidedIdeal.span
    (Set.range fun i => MonoidAlgebra.of R (FreeGroup α) (rels i) - 1)).asIdeal

instance relator_difference_sided (rels : ι → FreeGroup α) :
    (relatorDifferenceIdeal (R := R) rels).IsTwoSided := by
  dsimp [relatorDifferenceIdeal]
  infer_instance

lemma difference_presented_algebra
    (rels : ι → FreeGroup α) :
    relatorDifferenceIdeal (R := R) rels ≤
      RingHom.ker (presentedAlgebra (R := R) (Set.range rels)) := by
  intro x hx
  change x ∈ TwoSidedIdeal.span
      (Set.range fun i => MonoidAlgebra.of R (FreeGroup α) (rels i) - 1) at hx
  have hspan :
      TwoSidedIdeal.span
          (Set.range fun i => MonoidAlgebra.of R (FreeGroup α) (rels i) - 1) ≤
        (RingHom.ker (presentedAlgebra (R := R) (Set.range rels))).toTwoSided := by
    rw [TwoSidedIdeal.span_le]
    rintro _ ⟨i, rfl⟩
    simpa using relator_presented_algebra
      (R := R) (rels := Set.range rels) (r := rels i) (Set.mem_range_self i)
  simpa using hspan hx

lemma presented_algebra_surjective (rels : Set (FreeGroup α)) :
    Function.Surjective (presentedAlgebra (R := R) rels) := by
  simpa [presentedAlgebra] using
    (Finsupp.mapDomain_surjective (M := R) (PresentedGroup.mk_surjective rels))

/--
The quotient of the free-group algebra by the relator-difference ideal still maps onto the
presented-group algebra.

This is the clean quotient-algebra form of the local relator package: the presented-group algebra
is obtained as a further quotient of the relator-difference quotient.
-/
abbrev relatorDifferenceAlgebra (rels : ι → FreeGroup α) :
    MonoidAlgebra R (FreeGroup α) ⧸ relatorDifferenceIdeal (R := R) rels →+*
      MonoidAlgebra R (PresentedGroup (Set.range rels)) :=
  Ideal.Quotient.lift _ (presentedAlgebra (R := R) (Set.range rels))
    (fun _ hx =>
      RingHom.mem_ker.mp
        ((difference_presented_algebra
          (R := R) rels) hx))

@[simp] lemma relator_difference_mk
    (rels : ι → FreeGroup α) (x : MonoidAlgebra R (FreeGroup α)) :
    relatorDifferenceAlgebra rels
        (Ideal.Quotient.mk _ x) =
      presentedAlgebra (R := R) (Set.range rels) x := by
  rfl

theorem relator_difference_surjective
    (rels : ι → FreeGroup α) :
    Function.Surjective
      (show MonoidAlgebra R (FreeGroup α) ⧸ relatorDifferenceIdeal (R := R) rels →+*
          MonoidAlgebra R (PresentedGroup (Set.range rels)) from
        relatorDifferenceAlgebra rels) := by
  let f : MonoidAlgebra R (FreeGroup α) →+*
      MonoidAlgebra R (PresentedGroup (Set.range rels)) :=
    presentedAlgebra (R := R) (Set.range rels)
  simpa [relatorDifferenceAlgebra, f] using
    (Ideal.Quotient.lift_surjective_of_surjective
      (I := relatorDifferenceIdeal rels)
      (f := f)
      (H := fun x hx =>
        RingHom.mem_ker.mp
          ((difference_presented_algebra
            rels) hx))
      (presented_algebra_surjective (R := R) (Set.range rels)))

section FirstOrderModel

variable {α : Type*} [Fintype α] {p : ℕ}

/--
The multiplicative first-order model on the mod-`p` abelianization of a free
group: a vector `v` is sent to the unit `1 + ε_v` in the trivial square-zero
extension.
-/
def inrMonoidHom :
    Multiplicative (α →₀ ZMod p) →*
      TrivSqZeroExt (ZMod p) (α →₀ ZMod p) where
  toFun x := 1 + TrivSqZeroExt.inr x.toAdd
  map_one' := by
    apply TrivSqZeroExt.ext <;> simp
  map_mul' x y := by
    apply TrivSqZeroExt.ext <;> simp [add_comm]

/--
The free group on `α` maps to the first-order square-zero model by sending each
generator to `1 + ε_i`.
-/
def freeGroupOrder :
    FreeGroup α →*
      TrivSqZeroExt (ZMod p) (α →₀ ZMod p) :=
  (inrMonoidHom (α := α) (p := p)).comp
    (FreeGroup.lift
      (fun i => Multiplicative.ofAdd (Finsupp.single i (1 : ZMod p))))

@[simp] lemma free_group_order (w : FreeGroup α) :
    freeGroupOrder (α := α) (p := p) w =
      1 + TrivSqZeroExt.inr (modAbelianizationVector p w) := by
  unfold freeGroupOrder
  rw [MonoidHom.comp_apply, single_abelianization_vector]
  rfl

/--
The free-group algebra maps to the same first-order square-zero model by linear
extension.
-/
def freeFirstOrder :
    MonoidAlgebra (ZMod p) (FreeGroup α) →ₐ[ZMod p]
      TrivSqZeroExt (ZMod p) (α →₀ ZMod p) :=
  MonoidAlgebra.lift (ZMod p)
    (TrivSqZeroExt (ZMod p) (α →₀ ZMod p))
    (FreeGroup α)
    (freeGroupOrder (α := α) (p := p))

@[simp] lemma free_first_order (w : FreeGroup α) :
    freeFirstOrder (α := α) (p := p)
        (MonoidAlgebra.of (ZMod p) (FreeGroup α) w) =
      1 + TrivSqZeroExt.inr (modAbelianizationVector p w) := by
  simp [freeFirstOrder]

@[simp] lemma free_relator_difference (w : FreeGroup α) :
    freeFirstOrder (α := α) (p := p)
        (MonoidAlgebra.of (ZMod p) (FreeGroup α) w - 1) =
      TrivSqZeroExt.inr (modAbelianizationVector p w) := by
  rw [map_sub]
  simp [freeFirstOrder]

set_option linter.unusedFintypeInType false in
lemma fst_comp_order :
    (TrivSqZeroExt.fstHom (ZMod p) (ZMod p) (α →₀ ZMod p)).comp
        (freeFirstOrder (α := α) (p := p)) =
      MonoidAlgebra.lift (ZMod p) (ZMod p) (FreeGroup α)
        (augmentationCharacter (R := ZMod p) (G := FreeGroup α)) := by
  ext w
  simp [freeFirstOrder, free_group_order, augmentationCharacter]

set_option linter.unusedFintypeInType false in
@[simp] lemma fst_free_order
    (x : MonoidAlgebra (ZMod p) (FreeGroup α)) :
    TrivSqZeroExt.fst (freeFirstOrder (α := α) (p := p) x) =
      augmentationHom (R := ZMod p) (G := FreeGroup α) x := by
  change
    ((TrivSqZeroExt.fstHom (ZMod p) (ZMod p) (α →₀ ZMod p)).comp
      (freeFirstOrder (α := α) (p := p)) x) =
        augmentationHom (R := ZMod p) (G := FreeGroup α) x
  simpa [augmentationHom] using
    congrArg (fun f => f x) (fst_comp_order (α := α) (p := p))

@[simp] lemma p_abelianization_vector (p : ℕ) :
    modAbelianizationVector p (1 : FreeGroup α) = 0 := by
  simp [modAbelianizationVector]

@[simp] lemma mod_p_abelianization (p : ℕ) (a : α) :
    modAbelianizationVector p (FreeGroup.of a) = Finsupp.single a (1 : ZMod p) := by
  apply Multiplicative.ofAdd.injective
  simpa using
    (single_abelianization_vector
      (α := α) p (FreeGroup.of a)).symm

section

variable {α : Type*} [Fintype α] {p : ℕ}

lemma smul_single_finsupp (v : α →₀ ZMod p) :
    (∑ i, v i • (Finsupp.single i (1 : ZMod p) : α →₀ ZMod p)) = v := by
  ext i
  simp

/-
The first-order model kills the square of the augmentation ideal: products of
two augmentation differences become zero in the trivial square-zero extension.
-/
set_option linter.unusedFintypeInType false in
theorem augmentation_sq_order :
    augmentationIdeal (R := ZMod p) (G := FreeGroup α) ^ 2 ≤
      RingHom.ker (freeFirstOrder (α := α) (p := p)).toRingHom := by
  convert
    (show augmentationIdeal (R := ZMod p) (G := FreeGroup α) *
        augmentationIdeal (R := ZMod p) (G := FreeGroup α) ≤
          RingHom.ker (freeFirstOrder (α := α) (p := p)).toRingHom from by
      refine Ideal.mul_le.2 ?_
      intro x hx y hy
      rw [RingHom.mem_ker]
      have hx0 : augmentationHom (R := ZMod p) (G := FreeGroup α) x = 0 :=
        RingHom.mem_ker.mp hx
      have hy0 : augmentationHom (R := ZMod p) (G := FreeGroup α) y = 0 :=
        RingHom.mem_ker.mp hy
      have hx' :
          freeFirstOrder (α := α) (p := p) x ∈
            TrivSqZeroExt.kerIdeal (ZMod p) (α →₀ ZMod p) := by
        rw [TrivSqZeroExt.kerIdeal, RingHom.mem_ker]
        simpa [fst_free_order] using hx0
      have hy' :
          freeFirstOrder (α := α) (p := p) y ∈
            TrivSqZeroExt.kerIdeal (ZMod p) (α →₀ ZMod p) := by
        rw [TrivSqZeroExt.kerIdeal, RingHom.mem_ker]
        simpa [fst_free_order] using hy0
      have hxy :
          freeFirstOrder (α := α) (p := p) x *
            freeFirstOrder (α := α) (p := p) y ∈
              TrivSqZeroExt.kerIdeal (ZMod p) (α →₀ ZMod p) ^ 2 := by
        simpa [pow_two] using
          (Ideal.mul_mem_mul hx' hy' :
            freeFirstOrder (α := α) (p := p) x *
              freeFirstOrder (α := α) (p := p) y ∈
                TrivSqZeroExt.kerIdeal (ZMod p) (α →₀ ZMod p) *
                  TrivSqZeroExt.kerIdeal (ZMod p) (α →₀ ZMod p))
      rw [TrivSqZeroExt.kerIdeal_sq, Ideal.mem_bot] at hxy
      simpa [map_mul] using hxy)
  rw [Submodule.pow_succ, Submodule.pow_one]

/--
The quadratic truncation `A / I²` of the free-group algebra still surjects onto
the explicit first-order square-zero algebra on the mod-`p` abelianization.
-/
abbrev augmentationSqOrder :
    MonoidAlgebra (ZMod p) (FreeGroup α) ⧸
        augmentationIdeal (R := ZMod p) (G := FreeGroup α) ^ 2 →+*
      TrivSqZeroExt (ZMod p) (α →₀ ZMod p) :=
  Ideal.Quotient.lift _
    (freeFirstOrder (α := α) (p := p)).toRingHom
    (fun _ hx =>
      RingHom.mem_ker.mp
        ((augmentation_sq_order
          (α := α) (p := p)) hx))

/--
The same quadratic truncation map, remembered as an algebra hom over `ZMod p`.
-/
abbrev augmentationSqAlg :
    MonoidAlgebra (ZMod p) (FreeGroup α) ⧸
        augmentationIdeal (R := ZMod p) (G := FreeGroup α) ^ 2 →ₐ[ZMod p]
      TrivSqZeroExt (ZMod p) (α →₀ ZMod p) :=
  Ideal.Quotient.liftₐ
    (augmentationIdeal (R := ZMod p) (G := FreeGroup α) ^ 2)
    (freeFirstOrder (α := α) (p := p))
    (fun _ hx =>
      RingHom.mem_ker.mp
        ((augmentation_sq_order
          (α := α) (p := p)) hx))

@[simp] lemma augmentation_sq_mk
    (x : MonoidAlgebra (ZMod p) (FreeGroup α)) :
    augmentationSqOrder (α := α) (p := p)
        (Ideal.Quotient.mk _ x) =
      freeFirstOrder (α := α) (p := p) x := by
  rfl

@[simp] lemma sq_alg_mk
    (x : MonoidAlgebra (ZMod p) (FreeGroup α)) :
    augmentationSqAlg (α := α) (p := p)
        (Ideal.Quotient.mkₐ (ZMod p)
          (augmentationIdeal (R := ZMod p) (G := FreeGroup α) ^ 2) x) =
      freeFirstOrder (α := α) (p := p) x := by
  rfl

set_option linter.unusedFintypeInType false in
theorem free_order_surjective :
    Function.Surjective (freeFirstOrder (α := α) (p := p)) := by
  intro x
  refine ⟨MonoidAlgebra.single (1 : FreeGroup α) x.fst +
      ∑ i, x.snd i •
        (MonoidAlgebra.of (ZMod p) (FreeGroup α) (FreeGroup.of i) - 1), ?_⟩
  apply TrivSqZeroExt.ext
  · rw [map_add, TrivSqZeroExt.fst_add, map_sum, TrivSqZeroExt.fst_sum]
    simp [freeFirstOrder, free_group_order,
      p_abelianization_vector, mod_p_abelianization]
  · rw [map_add, TrivSqZeroExt.snd_add, map_sum, TrivSqZeroExt.snd_sum]
    simp [freeFirstOrder, free_group_order,
      p_abelianization_vector, mod_p_abelianization]

theorem augmentation_sq_surjective :
    Function.Surjective
      (show MonoidAlgebra (ZMod p) (FreeGroup α) ⧸
          augmentationIdeal (R := ZMod p) (G := FreeGroup α) ^ 2 →+*
            TrivSqZeroExt (ZMod p) (α →₀ ZMod p) from
        augmentationSqOrder (α := α) (p := p)) := by
  let f : MonoidAlgebra (ZMod p) (FreeGroup α) →+*
      TrivSqZeroExt (ZMod p) (α →₀ ZMod p) :=
    (freeFirstOrder (α := α) (p := p)).toRingHom
  simpa [augmentationSqOrder, f] using
    (Ideal.Quotient.lift_surjective_of_surjective
      (I := augmentationIdeal (R := ZMod p) (G := FreeGroup α) ^ 2)
      (f := f)
      (H := fun x hx =>
        RingHom.mem_ker.mp
          ((augmentation_sq_order
            (α := α) (p := p)) hx))
      (free_order_surjective (α := α) (p := p)))

/--
The explicit first-order model has exactly one scalar direction and one basis
direction for each free generator.
-/
lemma nat_card_model [Fact p.Prime] :
    Nat.card (TrivSqZeroExt (ZMod p) (α →₀ ZMod p)) =
      p ^ (Fintype.card α + 1) := by
  classical
  letI : DecidableEq α := Classical.decEq α
  change Nat.card (ZMod p × (α →₀ ZMod p)) = p ^ (Fintype.card α + 1)
  rw [Nat.card_eq_fintype_card, Fintype.card_prod, Fintype.card_finsupp, ZMod.card]
  simp [pow_succ']
attribute [simp] nat_card_model

/--
The same degree-`0/1` model has `d + 1` dimensions over `𝔽_p`.
-/
lemma finrank_first_model [Fact p.Prime] :
    Module.finrank (ZMod p) (TrivSqZeroExt (ZMod p) (α →₀ ZMod p)) =
      Fintype.card α + 1 := by
  classical
  letI : DecidableEq α := Classical.decEq α
  change Module.finrank (ZMod p) (ZMod p × (α →₀ ZMod p)) =
    Fintype.card α + 1
  rw [Module.finrank_prod, CommSemiring.finrank_self, Module.finrank_finsupp_self]
  omega
attribute [simp] finrank_first_model

/--
Any finite-dimensional `𝔽_p`-algebra that surjects onto the explicit first-order
model already has dimension at least `d + 1`.

This isolates the exact degree-`0/1` lower bound that the remaining
Golod--Shafarevich Hilbert-series bridge must eventually realize for the
relevant truncated quotient algebras.
-/
lemma order_model_surjective
    [Fact p.Prime]
    {V : Type*} [AddCommMonoid V] [Module (ZMod p) V] [Module.Finite (ZMod p) V]
    (f : V →ₗ[ZMod p] TrivSqZeroExt (ZMod p) (α →₀ ZMod p))
    (hf : Function.Surjective f) :
    Fintype.card α + 1 ≤ Module.finrank (ZMod p) V := by
  letI : Module.Finite (ZMod p) (TrivSqZeroExt (ZMod p) (α →₀ ZMod p)) := by
    change Module.Finite (ZMod p) (ZMod p × (α →₀ ZMod p))
    infer_instance
  have hle :=
    Module.finrank_le_finrank_of_rank_le_rank
      (LinearMap.lift_rank_le_of_surjective f hf)
      (Module.rank_lt_aleph0 (ZMod p) V)
  simpa [finrank_first_model (α := α) (p := p)] using hle

end

section

variable {α : Type*} {p : ℕ}

/-- The basic first-order point `1 + ε_v` in the square-zero model. -/
def firstOrderPoint (v : α →₀ ZMod p) :
    TrivSqZeroExt (ZMod p) (α →₀ ZMod p) :=
  (1 : TrivSqZeroExt (ZMod p) (α →₀ ZMod p)) + TrivSqZeroExt.inr v

lemma fst_first_point (v : α →₀ ZMod p) :
    (firstOrderPoint (α := α) (p := p) v).fst = 1 := by
  simp [firstOrderPoint]
attribute [simp] fst_first_point

lemma snd_first_point (v : α →₀ ZMod p) :
    (firstOrderPoint (α := α) (p := p) v).snd = v := by
  simp [firstOrderPoint]
attribute [simp] snd_first_point

/--
Every first-order element `1 + ε_v` is a unit, so relators with trivial mod-`p`
abelianization can be evaluated directly in the square-zero model.
-/
noncomputable def addInrUnit (v : α →₀ ZMod p) :
    Units (TrivSqZeroExt (ZMod p) (α →₀ ZMod p)) :=
  IsUnit.unit <| by
    rw [TrivSqZeroExt.isUnit_iff_isUnit_fst]
    change IsUnit ((firstOrderPoint (α := α) (p := p) v).fst)
    simp [firstOrderPoint]

lemma inr_unit_val (v : α →₀ ZMod p) :
    ((addInrUnit (α := α) (p := p) v :
        Units (TrivSqZeroExt (ZMod p) (α →₀ ZMod p))) :
        TrivSqZeroExt (ZMod p) (α →₀ ZMod p)) =
      firstOrderPoint (α := α) (p := p) v := by
  exact IsUnit.unit_spec _
attribute [simp] inr_unit_val

lemma inr_monoid_hom (v : α →₀ ZMod p) :
    inrMonoidHom (α := α) (p := p) (Multiplicative.ofAdd v) =
      firstOrderPoint (α := α) (p := p) v := by
  rfl
attribute [simp] inr_monoid_hom

end

/--
If each relator has trivial mod-`p` abelianization, then the presented group
already maps to the multiplicative mod-`p` abelianization.
-/
noncomputable def presentedPAbelianization
    (rels : ι → FreeGroup α)
    (hzero : ∀ i, modAbelianizationVector p (rels i) = 0) :
    PresentedGroup (Set.range rels) →* Multiplicative (α →₀ ZMod p) :=
  PresentedGroup.toGroup
    (f := fun a => Multiplicative.ofAdd (Finsupp.single a (1 : ZMod p)))
    (by
      intro r hr
      rcases hr with ⟨i, rfl⟩
      simpa [hzero i] using
        (single_abelianization_vector
          (α := α) (p := p) (w := rels i)))

@[simp] lemma presented_p_abelianization
    (rels : ι → FreeGroup α)
    (hzero : ∀ i, modAbelianizationVector p (rels i) = 0)
    (a : α) :
    presentedPAbelianization (α := α) (p := p) rels hzero (PresentedGroup.of a) =
      Multiplicative.ofAdd (Finsupp.single a (1 : ZMod p)) := by
  simp [presentedPAbelianization]

/--
Composing the presented-group map to the multiplicative mod-`p` abelianization
with the universal first-order square-zero model lands in units.
-/
noncomputable def presentedOrderUnits
    (rels : ι → FreeGroup α)
    (hzero : ∀ i, modAbelianizationVector p (rels i) = 0) :
    PresentedGroup (Set.range rels) →*
      Units (TrivSqZeroExt (ZMod p) (α →₀ ZMod p)) :=
  ((inrMonoidHom (α := α) (p := p)).toHomUnits).comp
    (presentedPAbelianization (α := α) (p := p) rels hzero)

@[simp] lemma presented_order_units
    (rels : ι → FreeGroup α)
    (hzero : ∀ i, modAbelianizationVector p (rels i) = 0)
    (a : α) :
    presentedOrderUnits (α := α) (p := p) rels hzero (PresentedGroup.of a) =
      (inrMonoidHom (α := α) (p := p)).toHomUnits
        (Multiplicative.ofAdd (Finsupp.single a (1 : ZMod p))) := by
  simp [presentedOrderUnits]

/--
Under vanishing mod-`p` abelianized relators, the presented-group algebra
already surjects onto the explicit degree-`0/1` square-zero model.
-/
noncomputable def presentedFirstOrder
    (rels : ι → FreeGroup α)
    (hzero : ∀ i, modAbelianizationVector p (rels i) = 0) :
    MonoidAlgebra (ZMod p) (PresentedGroup (Set.range rels)) →ₐ[ZMod p]
      TrivSqZeroExt (ZMod p) (α →₀ ZMod p) :=
  MonoidAlgebra.lift (ZMod p)
    (TrivSqZeroExt (ZMod p) (α →₀ ZMod p))
    (PresentedGroup (Set.range rels))
    ((Units.coeHom (TrivSqZeroExt (ZMod p) (α →₀ ZMod p))).comp
      (presentedOrderUnits (α := α) (p := p) rels hzero))

@[simp] lemma presented_first_order
    (rels : ι → FreeGroup α)
    (hzero : ∀ i, modAbelianizationVector p (rels i) = 0)
    (a : α) :
    presentedFirstOrder (α := α) (p := p) rels hzero
        (MonoidAlgebra.of (ZMod p) (PresentedGroup (Set.range rels))
          (PresentedGroup.of a)) =
      firstOrderPoint (α := α) (p := p) (Finsupp.single a (1 : ZMod p)) := by
  simp [presentedFirstOrder, firstOrderPoint]

theorem presented_order_surjective
    (rels : ι → FreeGroup α)
    (hzero : ∀ i, modAbelianizationVector p (rels i) = 0) :
    Function.Surjective
      (presentedFirstOrder (α := α) (p := p) rels hzero) := by
  intro x
  refine ⟨MonoidAlgebra.single (1 : PresentedGroup (Set.range rels)) x.fst +
      ∑ i, x.snd i •
        (MonoidAlgebra.of (ZMod p) (PresentedGroup (Set.range rels))
          (PresentedGroup.of i) - 1), ?_⟩
  apply TrivSqZeroExt.ext
  · rw [map_add, TrivSqZeroExt.fst_add, map_sum, TrivSqZeroExt.fst_sum]
    simp [presentedFirstOrder, firstOrderPoint]
  · rw [map_add, TrivSqZeroExt.snd_add, map_sum, TrivSqZeroExt.snd_sum]
    simp [presentedFirstOrder, firstOrderPoint]

/--
The first-order map on the presented-group algebra has the expected scalar part:
its composite with `fst` is the augmentation homomorphism.
-/
lemma fst_presented_order
    (rels : ι → FreeGroup α)
    (hzero : ∀ i, modAbelianizationVector p (rels i) = 0) :
    (TrivSqZeroExt.fstHom (ZMod p) (ZMod p) (α →₀ ZMod p)).comp
        (presentedFirstOrder (α := α) (p := p) rels hzero) =
      MonoidAlgebra.lift (ZMod p) (ZMod p) (PresentedGroup (Set.range rels))
        (augmentationCharacter (R := ZMod p) (G := PresentedGroup (Set.range rels))) := by
  ext g
  simp [presentedFirstOrder, presentedOrderUnits,
    inrMonoidHom, augmentationCharacter]

@[simp] lemma fst_first_order
    (rels : ι → FreeGroup α)
    (hzero : ∀ i, modAbelianizationVector p (rels i) = 0)
    (x : MonoidAlgebra (ZMod p) (PresentedGroup (Set.range rels))) :
    TrivSqZeroExt.fst
        (presentedFirstOrder (α := α) (p := p) rels hzero x) =
      augmentationHom (R := ZMod p) (G := PresentedGroup (Set.range rels)) x := by
  change
    ((TrivSqZeroExt.fstHom (ZMod p) (ZMod p) (α →₀ ZMod p)).comp
      (presentedFirstOrder (α := α) (p := p) rels hzero) x) =
        augmentationHom (R := ZMod p) (G := PresentedGroup (Set.range rels)) x
  simpa [augmentationHom] using
    congrArg (fun f => f x)
      (fst_presented_order
        (rels := rels) (hzero := hzero))

/--
The presented-group first-order model also kills the square of the augmentation
ideal, so the degree-`0/1` information factors through the quadratic truncation
of the presented-group algebra itself.
-/
theorem sq_presented_order
    (rels : ι → FreeGroup α)
    (hzero : ∀ i, modAbelianizationVector p (rels i) = 0) :
    augmentationIdeal (R := ZMod p) (G := PresentedGroup (Set.range rels)) ^ 2 ≤
      RingHom.ker (presentedFirstOrder
        (α := α) (p := p) rels hzero).toRingHom := by
  convert
    (show augmentationIdeal (R := ZMod p) (G := PresentedGroup (Set.range rels)) *
        augmentationIdeal (R := ZMod p) (G := PresentedGroup (Set.range rels)) ≤
          RingHom.ker (presentedFirstOrder
            (α := α) (p := p) rels hzero).toRingHom from by
      refine Ideal.mul_le.2 ?_
      intro x hx y hy
      rw [RingHom.mem_ker]
      have hx0 :
          augmentationHom (R := ZMod p) (G := PresentedGroup (Set.range rels)) x = 0 :=
        RingHom.mem_ker.mp hx
      have hy0 :
          augmentationHom (R := ZMod p) (G := PresentedGroup (Set.range rels)) y = 0 :=
        RingHom.mem_ker.mp hy
      have hx' :
          presentedFirstOrder (α := α) (p := p) rels hzero x ∈
            TrivSqZeroExt.kerIdeal (ZMod p) (α →₀ ZMod p) := by
        rw [TrivSqZeroExt.kerIdeal, RingHom.mem_ker]
        simpa [fst_first_order] using hx0
      have hy' :
          presentedFirstOrder (α := α) (p := p) rels hzero y ∈
            TrivSqZeroExt.kerIdeal (ZMod p) (α →₀ ZMod p) := by
        rw [TrivSqZeroExt.kerIdeal, RingHom.mem_ker]
        simpa [fst_first_order] using hy0
      have hxy :
          presentedFirstOrder (α := α) (p := p) rels hzero x *
            presentedFirstOrder (α := α) (p := p) rels hzero y ∈
              TrivSqZeroExt.kerIdeal (ZMod p) (α →₀ ZMod p) ^ 2 := by
        simpa [pow_two] using
          (Ideal.mul_mem_mul hx' hy' :
            presentedFirstOrder (α := α) (p := p) rels hzero x *
              presentedFirstOrder (α := α) (p := p) rels hzero y ∈
                TrivSqZeroExt.kerIdeal (ZMod p) (α →₀ ZMod p) *
                  TrivSqZeroExt.kerIdeal (ZMod p) (α →₀ ZMod p))
      rw [TrivSqZeroExt.kerIdeal_sq, Ideal.mem_bot] at hxy
      simpa [map_mul] using hxy)
  rw [Submodule.pow_succ, Submodule.pow_one]

/--
The presented-group algebra map to the explicit degree-`0/1` model descends to
the quadratic truncation by its own augmentation ideal.
-/
abbrev presentedSqOrder :
    (rels : ι → FreeGroup α) →
    (hzero : ∀ i, modAbelianizationVector p (rels i) = 0) →
    MonoidAlgebra (ZMod p) (PresentedGroup (Set.range rels)) ⧸
        augmentationIdeal (R := ZMod p) (G := PresentedGroup (Set.range rels)) ^ 2 →+*
      TrivSqZeroExt (ZMod p) (α →₀ ZMod p) :=
  fun rels hzero =>
    Ideal.Quotient.lift _
      (presentedFirstOrder (α := α) (p := p) rels hzero).toRingHom
      (fun _ hx =>
        RingHom.mem_ker.mp
          ((sq_presented_order
            (rels := rels) (hzero := hzero)) hx))

/--
The same descended map, remembered as an algebra hom over `ZMod p`.
-/
abbrev presentedSqAlg :
    (rels : ι → FreeGroup α) →
    (hzero : ∀ i, modAbelianizationVector p (rels i) = 0) →
    MonoidAlgebra (ZMod p) (PresentedGroup (Set.range rels)) ⧸
        augmentationIdeal (R := ZMod p) (G := PresentedGroup (Set.range rels)) ^ 2 →ₐ[ZMod p]
      TrivSqZeroExt (ZMod p) (α →₀ ZMod p) :=
  fun rels hzero =>
    Ideal.Quotient.liftₐ
      (augmentationIdeal (R := ZMod p) (G := PresentedGroup (Set.range rels)) ^ 2)
      (presentedFirstOrder (α := α) (p := p) rels hzero)
      (fun _ hx =>
        RingHom.mem_ker.mp
          ((sq_presented_order
            (rels := rels) (hzero := hzero)) hx))

@[simp] lemma presented_order_mk
    (rels : ι → FreeGroup α)
    (hzero : ∀ i, modAbelianizationVector p (rels i) = 0)
    (x : MonoidAlgebra (ZMod p) (PresentedGroup (Set.range rels))) :
    presentedSqOrder
        rels hzero
        (Ideal.Quotient.mk _ x) =
      presentedFirstOrder (α := α) (p := p) rels hzero x := by
  rfl

@[simp] lemma presented_sq_mk
    (rels : ι → FreeGroup α)
    (hzero : ∀ i, modAbelianizationVector p (rels i) = 0)
    (x : MonoidAlgebra (ZMod p) (PresentedGroup (Set.range rels))) :
    presentedSqAlg
        rels hzero
        (Ideal.Quotient.mkₐ (ZMod p)
          (augmentationIdeal (R := ZMod p) (G := PresentedGroup (Set.range rels)) ^ 2) x) =
      presentedFirstOrder (α := α) (p := p) rels hzero x := by
  rfl

@[simp] theorem presented_through_sq
    (rels : ι → FreeGroup α)
    (hzero : ∀ i, modAbelianizationVector p (rels i) = 0) :
    (presentedSqAlg
        rels hzero).comp
        (Ideal.Quotient.mkₐ (ZMod p)
          (augmentationIdeal (R := ZMod p) (G := PresentedGroup (Set.range rels)) ^ 2)) =
      presentedFirstOrder (α := α) (p := p) rels hzero := by
  ext x <;> simp [presentedSqAlg]

theorem presented_sq_surjective
    (rels : ι → FreeGroup α)
    (hzero : ∀ i, modAbelianizationVector p (rels i) = 0) :
    Function.Surjective
      (show MonoidAlgebra (ZMod p) (PresentedGroup (Set.range rels)) ⧸
          augmentationIdeal (R := ZMod p) (G := PresentedGroup (Set.range rels)) ^ 2 →+*
            TrivSqZeroExt (ZMod p) (α →₀ ZMod p) from
        presentedSqOrder rels hzero) := by
  let f : MonoidAlgebra (ZMod p) (PresentedGroup (Set.range rels)) →+*
      TrivSqZeroExt (ZMod p) (α →₀ ZMod p) :=
    (presentedFirstOrder (α := α) (p := p) rels hzero).toRingHom
  simpa [presentedSqOrder, f] using
    (Ideal.Quotient.lift_surjective_of_surjective
      (I := augmentationIdeal (R := ZMod p) (G := PresentedGroup (Set.range rels)) ^ 2)
      (f := f)
      (H := fun x hx =>
        RingHom.mem_ker.mp
          ((sq_presented_order
            (rels := rels) (hzero := hzero)) hx))
      (presented_order_surjective
        (α := α) (ι := ι) (p := p) rels hzero))

/--
The explicit degree-`0/1` lower bound already holds for the quadratic
augmentation truncation of the presented-group algebra itself.
-/
theorem finrank_aug_sq
    (rels : ι → FreeGroup α)
    [Fact p.Prime] [Module.Finite (ZMod p)
      (MonoidAlgebra (ZMod p) (PresentedGroup (Set.range rels)) ⧸
        augmentationIdeal (R := ZMod p) (G := PresentedGroup (Set.range rels)) ^ 2)]
    (hzero : ∀ i, modAbelianizationVector p (rels i) = 0) :
    Fintype.card α + 1 ≤
      Module.finrank (ZMod p)
        (MonoidAlgebra (ZMod p) (PresentedGroup (Set.range rels)) ⧸
          augmentationIdeal (R := ZMod p) (G := PresentedGroup (Set.range rels)) ^ 2) := by
  exact order_model_surjective
    (α := α) (p := p)
    (V := MonoidAlgebra (ZMod p) (PresentedGroup (Set.range rels)) ⧸
      augmentationIdeal (R := ZMod p) (G := PresentedGroup (Set.range rels)) ^ 2)
    (presentedSqAlg
      rels hzero).toLinearMap
    (presented_sq_surjective
      rels hzero)

/-- Compatibility name used by the finite-p-group and Hilbert-series APIs. -/
theorem finrank_model_sq
    (rels : ι → FreeGroup α)
    [Fact p.Prime] [Module.Finite (ZMod p)
      (MonoidAlgebra (ZMod p) (PresentedGroup (Set.range rels)) ⧸
        augmentationIdeal (R := ZMod p) (G := PresentedGroup (Set.range rels)) ^ 2)]
    (hzero : ∀ i, modAbelianizationVector p (rels i) = 0) :
    Fintype.card α + 1 ≤
      Module.finrank (ZMod p)
        (MonoidAlgebra (ZMod p) (PresentedGroup (Set.range rels)) ⧸
          augmentationIdeal (R := ZMod p) (G := PresentedGroup (Set.range rels)) ^ 2) :=
  finrank_aug_sq rels hzero

/--
The degree-`0/1` lower bound now holds directly for the presented-group algebra
whenever its relators vanish in mod-`p` abelianization.
-/
theorem finrank_model_surjective
    (rels : ι → FreeGroup α)
    [Fact p.Prime] [Module.Finite (ZMod p)
      (MonoidAlgebra (ZMod p) (PresentedGroup (Set.range rels)))]
    (hzero : ∀ i, modAbelianizationVector p (rels i) = 0) :
    Fintype.card α + 1 ≤
      Module.finrank (ZMod p)
        (MonoidAlgebra (ZMod p) (PresentedGroup (Set.range rels))) := by
  exact order_model_surjective
    (α := α) (p := p)
    (V := MonoidAlgebra (ZMod p) (PresentedGroup (Set.range rels)))
    (presentedFirstOrder (α := α) (p := p) rels hzero).toLinearMap
    (presented_order_surjective
      (α := α) (p := p) rels hzero)

end FirstOrderModel

section AugmentationPowerQuotients

variable {R α : Type*} [CommRing R]

/--
The canonical free-to-presented group algebra map preserves augmentation:
applying augmentation after imposing relators is the same as augmenting first.
-/
lemma comp_presented_algebra
    (rels : Set (FreeGroup α)) :
    (augmentationHom R (PresentedGroup rels)).toRingHom.comp
        (presentedAlgebra (R := R) rels) =
      (augmentationHom R (FreeGroup α)).toRingHom := by
  apply MonoidAlgebra.ringHom_ext
  · intro r
    simp [RingHom.comp_apply, augmentationHom, augmentationCharacter]
  · intro w
    simp [RingHom.comp_apply, presentedAlgebra, augmentationHom, augmentationCharacter]

lemma presented_algebra_ideal
    (rels : Set (FreeGroup α))
    {x : MonoidAlgebra R (FreeGroup α)}
    (hx : x ∈ augmentationIdeal (R := R) (G := FreeGroup α)) :
    presentedAlgebra (R := R) rels x ∈
      augmentationIdeal (R := R) (G := PresentedGroup rels) := by
  rw [augmentationIdeal, RingHom.mem_ker] at hx ⊢
  rw [← RingHom.comp_apply, comp_presented_algebra]
  exact hx

/--
The same compatibility holds in every augmentation-ideal power, so the
presented-group algebra map descends to all truncated augmentation quotients.
-/
theorem presented_algebra_pow
    (rels : Set (FreeGroup α)) :
    ∀ {n : ℕ} {x : MonoidAlgebra R (FreeGroup α)},
      x ∈ augmentationIdeal (R := R) (G := FreeGroup α) ^ n →
        presentedAlgebra (R := R) rels x ∈
          augmentationIdeal (R := R) (G := PresentedGroup rels) ^ n
  | 0, x, _ => by
      simp [Submodule.pow_zero]
  | n + 1, x, hx => by
      rw [Submodule.pow_succ] at hx ⊢
      refine Submodule.mul_induction_on hx ?_ ?_
      · intro a ha b hb
        simpa [map_mul] using
          (Submodule.mul_mem_mul
            (presented_algebra_pow (rels := rels) ha)
            (presented_algebra_ideal (rels := rels) hb))
      · intro a b ha hb
        simpa [map_add] using AddSubmonoid.add_mem _ ha hb

/--
For every `n`, the `n`th augmentation quotient of the free-group algebra still
maps onto the corresponding `n`th augmentation quotient of the presented-group
algebra.
-/
abbrev
    freePresentedAug
    (rels : Set (FreeGroup α)) (n : ℕ) :
    MonoidAlgebra R (FreeGroup α) ⧸
        augmentationIdeal (R := R) (G := FreeGroup α) ^ n →+*
      MonoidAlgebra R (PresentedGroup rels) ⧸
        augmentationIdeal (R := R) (G := PresentedGroup rels) ^ n :=
  Ideal.Quotient.lift _
    ((Ideal.Quotient.mk _).comp (presentedAlgebra (R := R) rels))
    (fun _ hx =>
      Ideal.Quotient.eq_zero_iff_mem.2
        (presented_algebra_pow
          (R := R) (rels := rels) hx))

@[simp] lemma
    presented_aug_mk
    (rels : Set (FreeGroup α)) (n : ℕ)
    (x : MonoidAlgebra R (FreeGroup α)) :
    freePresentedAug
        (R := R) rels n (Ideal.Quotient.mk _ x) =
      Ideal.Quotient.mk _
        (presentedAlgebra (R := R) rels x) := by
  rfl

theorem
    presented_aug_surjective
    (rels : Set (FreeGroup α)) (n : ℕ) :
    Function.Surjective
      (freePresentedAug
        (R := R) rels n) := by
  let f :
      MonoidAlgebra R (FreeGroup α) →+*
        MonoidAlgebra R (PresentedGroup rels) ⧸
          augmentationIdeal (R := R) (G := PresentedGroup rels) ^ n :=
    (Ideal.Quotient.mk _).comp (presentedAlgebra (R := R) rels)
  simpa
      [freePresentedAug,
        f] using
    (Ideal.Quotient.lift_surjective_of_surjective
      (I := augmentationIdeal (R := R) (G := FreeGroup α) ^ n)
      (f := f)
      (H := fun x hx =>
        Ideal.Quotient.eq_zero_iff_mem.2
          (presented_algebra_pow
            (R := R) (rels := rels) hx))
      (Ideal.Quotient.mk_surjective.comp
        (presented_algebra_surjective (R := R) rels)))

end AugmentationPowerQuotients

end PresentedGroupAlgebra

lemma polynomial_two_div {d r : ℝ} (hd : d ≠ 0) :
    polynomial d r (2 / d) = (4 * r - d ^ (2 : ℕ)) / d ^ (2 : ℕ) := by
  unfold polynomial
  field_simp [hd]
  ring_nf

/--
Analytic endgame of the Golod--Shafarevich inequality.

Once the Golod--Shafarevich quadratic is known to stay positive on `(0, 1)`,
the usual minimization argument yields the strict bound `r > d^2 / 4` as soon
as `d > 2`.
-/
theorem strict_pos_interval
    {d r : ℕ}
    (hd : 2 < d)
    (hpos : ∀ t : ℝ, 0 < t → t < 1 → 0 < polynomial d r t) :
    (r : ℝ) > (d : ℝ) ^ (2 : ℕ) / 4 := by
  have hd0 : (d : ℝ) ≠ 0 := by positivity
  have ht0 : 0 < (2 : ℝ) / d := by positivity
  have ht1 : (2 : ℝ) / d < 1 := by
    have hdpos : (0 : ℝ) < d := by positivity
    exact (div_lt_one hdpos).2 (by exact_mod_cast hd)
  have h := hpos ((2 : ℝ) / d) ht0 ht1
  rw [polynomial_two_div (d := d) (r := r) hd0] at h
  have hd_sq_pos : 0 < (d : ℝ) ^ (2 : ℕ) := by positivity
  have hnum : 0 < 4 * (r : ℝ) - (d : ℝ) ^ (2 : ℕ) := by
    exact (div_pos_iff_of_pos_right hd_sq_pos).mp h
  nlinarith

/--
Full analytic wrapper: the large-generator case comes from the quadratic
minimization argument, while the cases `d ≤ 2` are supplied separately.
-/
theorem pos_unit_interval
    {d r : ℕ}
    (hsmall : d ≤ 2 → (r : ℝ) > (d : ℝ) ^ (2 : ℕ) / 4)
    (hpos : ∀ t : ℝ, 0 < t → t < 1 → 0 < polynomial d r t) :
    (r : ℝ) > (d : ℝ) ^ (2 : ℕ) / 4 := by
  by_cases hd : d ≤ 2
  · exact hsmall hd
  · exact strict_pos_interval (Nat.lt_of_not_ge hd) hpos

/--
Concrete discharge of the small-generator cases.

For `d = 0` or `d = 1`, positivity of `r` is enough. For `d = 2`, one needs the
extra input `2 ≤ r`.
-/
theorem small_case_bounds
    {d r : ℕ}
    (hd : d ≤ 2)
    (hr : 1 ≤ r)
    (hr2 : d = 2 → 2 ≤ r) :
    (r : ℝ) > (d : ℝ) ^ (2 : ℕ) / 4 := by
  interval_cases d
  · have hr' : (1 : ℝ) ≤ r := by exact_mod_cast hr
    nlinarith
  · have hr' : (1 : ℝ) ≤ r := by exact_mod_cast hr
    nlinarith
  · have hr' : (2 : ℝ) ≤ r := by exact_mod_cast hr2 rfl
    nlinarith

/--
For `0 < t < 1`, any power `t^n` with `n ≥ 2` is bounded above by `t^2`.

This is the elementary inequality that lets the full depth-counted Golod--Shafarevich
relation series dominate the quadratic truncation `r * t^2`.
-/
lemma pow_sq_two {t : ℝ} (ht0 : 0 < t) (ht1 : t < 1) {n : ℕ} (hn : 2 ≤ n) :
    t ^ n ≤ t ^ (2 : ℕ) := by
  obtain ⟨m, rfl⟩ := Nat.exists_eq_add_of_le hn
  have hpow : t ^ m ≤ 1 := by
    have ht_nonneg : 0 ≤ t := le_of_lt ht0
    simpa using (pow_le_one₀ (a := t) ht_nonneg ht1.le : t ^ m ≤ 1)
  calc
    t ^ (2 + m) = t ^ (2 : ℕ) * t ^ m := by rw [pow_add]
    _ ≤ t ^ (2 : ℕ) * 1 := by gcongr
    _ = t ^ (2 : ℕ) := by ring

/--
The depth-counted Golod--Shafarevich expression attached to `r` relators with
individual depths `depth i`.

In the classical setup one takes `depth i` to be the Zassenhaus depth of the `i`-th
relator in a minimal presentation. The comparison theorem below only needs the
numerical lower bound `2 ≤ depth i`.
-/
def relatorExpression (d r : ℕ) (depth : Fin r → ℕ) (t : ℝ) : ℝ :=
  1 - d * t + ∑ i, t ^ depth i

/--
The polynomial form of the depth-counted Golod--Shafarevich relation
expression.

This is the object that appears in the classical Hilbert-series inequality
`(1 - dX + Σ_i X^(depth i)) * H(X)`.
-/
def relatorSeriesPolynomial (d r : ℕ) (depth : Fin r → ℕ) : Polynomial ℝ :=
  Polynomial.C (1 : ℝ) - Polynomial.C (d : ℝ) * Polynomial.X + ∑ i, Polynomial.X ^ depth i

lemma relator_series_polynomial (d r : ℕ) (depth : Fin r → ℕ) (t : ℝ) :
    (relatorSeriesPolynomial d r depth).eval t = relatorExpression d r depth t := by
  simp [relatorSeriesPolynomial, relatorExpression, Polynomial.eval_finsetSum, sub_eq_add_neg,
    add_assoc, add_left_comm, add_comm, mul_comm]

lemma coeff_relator_series
    {d r : ℕ} (depth : Fin r → ℕ) (hdepth : ∀ i, 1 ≤ depth i) :
    (relatorSeriesPolynomial d r depth).coeff 0 = 1 := by
  have hdepth0 : ∀ i, 0 ≠ depth i := by
    intro i
    have hi : 0 < depth i := lt_of_lt_of_le (by decide : 0 < 1) (hdepth i)
    simpa [eq_comm] using (Nat.pos_iff_ne_zero.mp hi)
  simp [relatorSeriesPolynomial, hdepth0]

lemma pos_coeff_nonneg (P : Polynomial ℝ)
    (hcoeff : ∀ n, 0 ≤ P.coeff n) (h0 : 0 < P.coeff 0) {t : ℝ} (ht : 0 < t) :
    0 < P.eval t := by
  rw [show P.eval t = Polynomial.eval₂ (RingHom.id ℝ) t P by rfl,
    Polynomial.eval₂_eq_sum_range]
  have hnonneg :
      ∀ i ∈ Finset.range (P.natDegree + 1),
        0 ≤ (RingHom.id ℝ) (P.coeff i) * t ^ i := by
    intro i hi
    exact mul_nonneg (hcoeff i) (pow_nonneg (le_of_lt ht) i)
  have hle :
      (RingHom.id ℝ) (P.coeff 0) * t ^ 0 ≤
        ∑ x ∈ Finset.range (P.natDegree + 1), (RingHom.id ℝ) (P.coeff x) * t ^ x := by
    exact Finset.single_le_sum hnonneg (by exact Finset.mem_range.mpr (Nat.succ_pos _))
  have hterm0 :
      0 < (RingHom.id ℝ) (P.coeff 0) * t ^ 0 := by
    simpa using h0
  linarith

/--
An abstract coefficientwise Hilbert-series inequality already implies positivity
of the depth-counted Golod--Shafarevich relation expression.

This cleanly separates the remaining classical step from the present algebraic
setup: it is enough to build a polynomial `P` with nonnegative coefficients,
positive constant term, and such that every coefficient of
`(1 - dX + Σ_i X^(depth i)) * P` is nonnegative.
-/
theorem coefficientwise_hilbert_inequality
    {d r : ℕ} (depth : Fin r → ℕ)
    (hdepth : ∀ i, 2 ≤ depth i)
    {P : Polynomial ℝ}
    (hPcoeff : ∀ n, 0 ≤ P.coeff n)
    (hP0 : 0 < P.coeff 0)
    (hprodcoeff :
      ∀ n, 0 ≤ ((relatorSeriesPolynomial d r depth) * P).coeff n) :
    ∀ t : ℝ, 0 < t → 0 < relatorExpression d r depth t := by
  intro t ht
  have hP_eval : 0 < P.eval t :=
    pos_coeff_nonneg P hPcoeff hP0 ht
  have hdepth1 : ∀ i, 1 ≤ depth i := by
    intro i
    exact le_trans (by decide : 1 ≤ 2) (hdepth i)
  have hprod0 : 0 < (((relatorSeriesPolynomial d r depth) * P).coeff 0) := by
    have hcoeff0 : (relatorSeriesPolynomial d r depth).coeff 0 = 1 := by
      simpa using coeff_relator_series depth hdepth1
    rw [Polynomial.coeff_mul]
    simp only [Finset.antidiagonal_zero, Finset.sum_singleton]
    rw [hcoeff0]
    simpa using hP0
  have hprod_eval : 0 < ((relatorSeriesPolynomial d r depth) * P).eval t :=
    pos_coeff_nonneg
      ((relatorSeriesPolynomial d r depth) * P) hprodcoeff hprod0 ht
  rw [Polynomial.eval_mul, relator_series_polynomial] at hprod_eval
  nlinarith

/--
The zero-extended coefficient sequence attached to a finite truncation.

This is the natural format for the first genuinely Hilbert-series-style
dimension recursion: the classical quotient dimensions produce a finite initial
segment, and we extend it by `0` outside that range.
-/
def truncatedSequence (a : ℕ → ℝ) (N n : ℕ) : ℝ :=
  if n ≤ N then a n else 0

/--
The polynomial whose coefficients are the finite truncation of a sequence
`a 0, ..., a N`.
-/
def truncationPolynomial (a : ℕ → ℝ) (N : ℕ) : Polynomial ℝ :=
  Finset.sum (Finset.range (N + 1)) fun n => Polynomial.monomial n (a n)

@[simp] lemma coeff_truncationPolynomial (a : ℕ → ℝ) (N n : ℕ) :
    (truncationPolynomial a N).coeff n = truncatedSequence a N n := by
  by_cases hn : n ≤ N
  · rw [truncationPolynomial, Polynomial.finsetSum_coeff, truncatedSequence, if_pos hn]
    have hnmem : n ∈ Finset.range (N + 1) := Finset.mem_range.mpr (Nat.lt_succ_iff.mpr hn)
    rw [Finset.sum_eq_single n]
    · simp
    · intro m hm hmn
      simp [Polynomial.coeff_monomial, hmn]
    · intro hnot
      exact (hnot hnmem).elim
  · rw [truncationPolynomial, Polynomial.finsetSum_coeff, truncatedSequence, if_neg hn]
    refine Finset.sum_eq_zero ?_
    intro m hm
    have hmne : m ≠ n := by
      intro hmn
      apply hn
      simpa [hmn] using Nat.le_of_lt_succ (Finset.mem_range.mp hm)
    simp [Polynomial.coeff_monomial, hmne]

/--
The coefficientwise Hilbert-series term for a truncated sequence is exactly the
expected recursion
`a_n - d a_{n-1} + Σ_i a_{n - depth i}`
after extending the sequence by `0` outside the chosen range.
-/
lemma coeff_relator_truncation
    (a : ℕ → ℝ) (N : ℕ) (d r : ℕ) (depth : Fin r → ℕ) (n : ℕ) :
    ((relatorSeriesPolynomial d r depth) * truncationPolynomial a N).coeff n =
      truncatedSequence a N n
        - (d : ℝ) * (if 1 ≤ n then truncatedSequence a N (n - 1) else 0)
        + ∑ i, if depth i ≤ n then truncatedSequence a N (n - depth i) else 0 := by
  rw [relatorSeriesPolynomial, sub_eq_add_neg, add_mul, add_mul, neg_mul, Finset.sum_mul,
    Polynomial.coeff_add, Polynomial.coeff_add, Polynomial.coeff_neg, Polynomial.finsetSum_coeff,
    Polynomial.coeff_C_mul, mul_assoc, Polynomial.coeff_C_mul]
  simp_rw [Polynomial.coeff_X_pow_mul', coeff_truncationPolynomial]
  have hX :
      (Polynomial.X * truncationPolynomial a N).coeff n =
        if 1 ≤ n then truncatedSequence a N (n - 1) else 0 := by
    simpa [pow_one, coeff_truncationPolynomial] using
      (Polynomial.coeff_X_pow_mul' (truncationPolynomial a N) 1 n)
  rw [hX]
  ring

/--
Above the natural coefficient window of the product
`(1 - dX + Σ_i X^(depth i)) * truncationPolynomial a N`, every term vanishes.

The extra `max 1` accounts for the linear term `-dX`, while `sup depth` covers
the relator contributions.
-/
lemma truncation_recurrence_window
    (a : ℕ → ℝ) (N : ℕ) (d r : ℕ) (depth : Fin r → ℕ) {n : ℕ}
    (hn : N + max 1 (Finset.univ.sup depth) < n) :
    truncatedSequence a N n
      - (d : ℝ) * (if 1 ≤ n then truncatedSequence a N (n - 1) else 0)
      + (∑ i, if depth i ≤ n then truncatedSequence a N (n - depth i) else 0) = 0 := by
  have hnN : N < n := by
    omega
  have hn1 : 1 ≤ n := by
    omega
  have hnm1 : N < n - 1 := by
    omega
  have hsum :
      (∑ i, if depth i ≤ n then truncatedSequence a N (n - depth i) else 0) = 0 := by
    refine Finset.sum_eq_zero ?_
    intro i _
    have hdepthi : depth i ≤ Finset.univ.sup depth := by
      exact Finset.le_sup (by simp)
    have hdepthn : depth i ≤ n := by
      omega
    have hsub : N < n - depth i := by
      omega
    simp [hdepthn, truncatedSequence, Nat.not_le.mpr hsub]
  have h0 : truncatedSequence a N n = 0 := by
    simp [truncatedSequence, Nat.not_le.mpr hnN]
  have h1 : (if 1 ≤ n then truncatedSequence a N (n - 1) else 0) = 0 := by
    simp [hn1, truncatedSequence, Nat.not_le.mpr hnm1]
  calc
    truncatedSequence a N n
        - (d : ℝ) * (if 1 ≤ n then truncatedSequence a N (n - 1) else 0)
        + (∑ i, if depth i ≤ n then truncatedSequence a N (n - depth i) else 0)
      = 0 - (d : ℝ) * 0 + 0 := by rw [h0, h1, hsum]
    _ = 0 := by ring

/--
Consequently, it is enough to verify the truncated recurrence on the finite
window `0 ≤ n ≤ N + max 1 (sup depth)`.

This is a sharper reduction than the raw all-`n` statement: once a coefficient
sequence is truncated at `N`, the product polynomial has no support beyond this
explicit bound.
-/
theorem witness_truncation_recurrence
    {d r : ℕ} (depth : Fin r → ℕ)
    {a : ℕ → ℝ} {N : ℕ}
    (ha : ∀ n, 0 ≤ a n)
    (ha0 : 0 < a 0)
    (hrec :
      ∀ n ≤ N + max 1 (Finset.univ.sup depth), 0 ≤
        truncatedSequence a N n
          - (d : ℝ) * (if 1 ≤ n then truncatedSequence a N (n - 1) else 0)
          + ∑ i, if depth i ≤ n then truncatedSequence a N (n - depth i) else 0) :
    ∃ P : Polynomial ℝ,
      (∀ n, 0 ≤ P.coeff n) ∧
      0 < P.coeff 0 ∧
      (∀ n, 0 ≤ ((relatorSeriesPolynomial d r depth) * P).coeff n) := by
  refine ⟨truncationPolynomial a N, ?_, ?_, ?_⟩
  · intro n
    rw [coeff_truncationPolynomial]
    by_cases hn : n ≤ N
    · simp [truncatedSequence, hn, ha n]
    · simp [truncatedSequence, hn]
  · simpa [coeff_truncationPolynomial, truncatedSequence] using ha0
  · intro n
    rw [coeff_relator_truncation]
    by_cases hn' : n ≤ N + max 1 (Finset.univ.sup depth)
    · exact hrec n hn'
    · have hzero :=
        truncation_recurrence_window
          (a := a) (N := N) (d := d) (r := r) (depth := depth)
          (n := n) (Nat.lt_of_not_ge hn')
      simp only [mul_ite, mul_zero, ge_iff_le] at hzero ⊢
      rw [hzero]

/--
Hence positivity of the Golod--Shafarevich relation series already follows from
checking the truncated coefficient recursion on that same finite window.
-/
theorem expression_pos_recurrence
    {d r : ℕ} (depth : Fin r → ℕ)
    (hdepth : ∀ i, 2 ≤ depth i)
    {a : ℕ → ℝ} {N : ℕ}
    (ha : ∀ n, 0 ≤ a n)
    (ha0 : 0 < a 0)
    (hrec :
      ∀ n ≤ N + max 1 (Finset.univ.sup depth), 0 ≤
        truncatedSequence a N n
          - (d : ℝ) * (if 1 ≤ n then truncatedSequence a N (n - 1) else 0)
          + ∑ i, if depth i ≤ n then truncatedSequence a N (n - depth i) else 0) :
    ∀ t : ℝ, 0 < t → 0 < relatorExpression d r depth t := by
  rcases witness_truncation_recurrence
      (d := d) (r := r) (depth := depth) ha ha0 hrec with
    ⟨P, hPcoeff, hP0, hprodcoeff⟩
  exact
    coefficientwise_hilbert_inequality
      (d := d) (r := r) depth hdepth hPcoeff hP0 hprodcoeff

/--
An explicit finite recursion on a coefficient sequence already produces the
polynomial witness needed for the Hilbert-series inequality.

This is the next honest reduction after the abstract coefficientwise statement:
the remaining task is to manufacture such a truncated sequence from quotient
dimensions.
-/
theorem witness_polynomial_recurrence
    {d r : ℕ} (depth : Fin r → ℕ)
    {a : ℕ → ℝ} {N : ℕ}
    (ha : ∀ n, 0 ≤ a n)
    (ha0 : 0 < a 0)
    (hrec :
      ∀ n, 0 ≤
        truncatedSequence a N n
          - (d : ℝ) * (if 1 ≤ n then truncatedSequence a N (n - 1) else 0)
          + ∑ i, if depth i ≤ n then truncatedSequence a N (n - depth i) else 0) :
    ∃ P : Polynomial ℝ,
      (∀ n, 0 ≤ P.coeff n) ∧
      0 < P.coeff 0 ∧
      (∀ n, 0 ≤ ((relatorSeriesPolynomial d r depth) * P).coeff n) := by
  refine ⟨truncationPolynomial a N, ?_, ?_, ?_⟩
  · intro n
    rw [coeff_truncationPolynomial]
    by_cases hn : n ≤ N
    · simp [truncatedSequence, hn, ha n]
    · simp [truncatedSequence, hn]
  · simpa [coeff_truncationPolynomial, truncatedSequence] using ha0
  · intro n
    simpa [coeff_relator_truncation] using hrec n

/--
Consequently, positivity of the Golod--Shafarevich relation series follows from
an explicit finite recursion on a truncated coefficient sequence.
-/
theorem expression_truncation_recurrence
    {d r : ℕ} (depth : Fin r → ℕ)
    (hdepth : ∀ i, 2 ≤ depth i)
    {a : ℕ → ℝ} {N : ℕ}
    (ha : ∀ n, 0 ≤ a n)
    (ha0 : 0 < a 0)
    (hrec :
      ∀ n, 0 ≤
        truncatedSequence a N n
          - (d : ℝ) * (if 1 ≤ n then truncatedSequence a N (n - 1) else 0)
          + ∑ i, if depth i ≤ n then truncatedSequence a N (n - depth i) else 0) :
    ∀ t : ℝ, 0 < t → 0 < relatorExpression d r depth t := by
  rcases witness_polynomial_recurrence
      (d := d) (r := r) (depth := depth) ha ha0 hrec with
    ⟨P, hPcoeff, hP0, hprodcoeff⟩
  exact
    coefficientwise_hilbert_inequality
      (d := d) (r := r) depth hdepth hPcoeff hP0 hprodcoeff


/--
The remaining mathematical core of the Hilbert-series argument, phrased as the
coefficientwise polynomial witness that the classical proof constructs from the
finite-dimensional augmentation filtration.
-/
def CoefficientwiseHilbertWitness (d r : ℕ) (depth : Fin r → ℕ) : Prop :=
  ∃ P : Polynomial ℝ,
    (∀ n, 0 ≤ P.coeff n) ∧
    0 < P.coeff 0 ∧
    ∀ n, 0 ≤ ((relatorSeriesPolynomial d r depth) * P).coeff n

/--
The finite coefficient window for the product of a truncation of length `N`
with the relation polynomial. The `max 1` accounts for the linear term `-dX`;
the `sup depth` accounts for the relator terms.
-/
def truncationWindow {r : ℕ} (N : ℕ) (depth : Fin r → ℕ) : ℕ :=
  N + max 1 (Finset.univ.sup depth)

/--
It is enough to verify the truncated recurrence on the finite coefficient
window, since all larger coefficients are automa zero.
-/
theorem coefficientwise_witness_recurrence
    {d r : ℕ} (depth : Fin r → ℕ)
    {a : ℕ → ℝ} {N : ℕ}
    (ha : ∀ n, 0 ≤ a n)
    (ha0 : 0 < a 0)
    (hrec :
      ∀ n, n ≤ truncationWindow N depth → 0 ≤
        truncatedSequence a N n
          - (d : ℝ) * (if 1 ≤ n then truncatedSequence a N (n - 1) else 0)
          + ∑ i, if depth i ≤ n then truncatedSequence a N (n - depth i) else 0) :
    CoefficientwiseHilbertWitness d r depth := by
  simpa [CoefficientwiseHilbertWitness, truncationWindow] using
    witness_truncation_recurrence
      (d := d) (r := r) (depth := depth) (a := a) (N := N) ha ha0
      (by
        intro n hn
        exact hrec n (by simpa [truncationWindow] using hn))

/--
A nonnegative truncated sequence satisfying the coefficient recurrence supplies
the coefficientwise Hilbert witness. This is purely formal polynomial algebra;
the remaining mathematical task is to build such a sequence from the
augmentation-filtration dimensions of the presented finite `p`-group.
-/
theorem coefficientwise_hilbert_witness
    {d r : ℕ} (depth : Fin r → ℕ)
    {a : ℕ → ℝ} {N : ℕ}
    (ha : ∀ n, 0 ≤ a n)
    (ha0 : 0 < a 0)
    (hrec :
      ∀ n, 0 ≤
        truncatedSequence a N n
          - (d : ℝ) * (if 1 ≤ n then truncatedSequence a N (n - 1) else 0)
          + ∑ i, if depth i ≤ n then truncatedSequence a N (n - depth i) else 0) :
    CoefficientwiseHilbertWitness d r depth := by
  simpa [CoefficientwiseHilbertWitness] using
    witness_polynomial_recurrence
      (d := d) (r := r) (depth := depth) (a := a) (N := N) ha ha0 hrec

/-- The generator contribution in the Hilbert-series recurrence. -/
def recurrenceGeneratorTerm (a : ℕ → ℝ) (N n : ℕ) : ℝ :=
  if 1 ≤ n then truncatedSequence a N (n - 1) else 0

/-- The relator contribution in the Hilbert-series recurrence. -/
def recurrenceRelatorTerm {r : ℕ} (a : ℕ → ℝ) (N : ℕ) (depth : Fin r → ℕ)
    (n : ℕ) : ℝ :=
  ∑ i, if depth i ≤ n then truncatedSequence a N (n - depth i) else 0

/--
The dimension-inequality form of the Golod--Shafarevich recurrence at one
coefficient.
-/
def recurrenceCoefficientInequality {r : ℕ}
    (d : ℕ) (a : ℕ → ℝ) (N : ℕ) (depth : Fin r → ℕ) (n : ℕ) : Prop :=
  (d : ℝ) * recurrenceGeneratorTerm a N n ≤
    truncatedSequence a N n + recurrenceRelatorTerm a N depth n

/-- The zero-extended natural-number coefficient sequence attached to a truncation. -/
def truncatedNatSequence (b : ℕ → ℕ) (N n : ℕ) : ℕ :=
  if n ≤ N then b n else 0

/-- The natural-number generator contribution in the recurrence. -/
def recurrenceNatTerm (b : ℕ → ℕ) (N n : ℕ) : ℕ :=
  if 1 ≤ n then truncatedNatSequence b N (n - 1) else 0

/-- The natural-number relator contribution in the recurrence. -/
def recurrenceNatRelator {r : ℕ} (b : ℕ → ℕ) (N : ℕ) (depth : Fin r → ℕ)
    (n : ℕ) : ℕ :=
  ∑ i, if depth i ≤ n then truncatedNatSequence b N (n - depth i) else 0

/--
The natural-number dimension-inequality form of the recurrence.
-/
def recurrenceNatInequality {r : ℕ}
    (d : ℕ) (b : ℕ → ℕ) (N : ℕ) (depth : Fin r → ℕ) (n : ℕ) : Prop :=
  d * recurrenceNatTerm b N n ≤
    truncatedNatSequence b N n + recurrenceNatRelator b N depth n

/-- The untruncated natural-number generator contribution. -/
def fullNatTerm (b : ℕ → ℕ) (n : ℕ) : ℕ :=
  if 1 ≤ n then b (n - 1) else 0

/-- The untruncated natural-number relator contribution. -/
def fullRelatorTerm {r : ℕ} (b : ℕ → ℕ) (depth : Fin r → ℕ)
    (n : ℕ) : ℕ :=
  ∑ i, if depth i ≤ n then b (n - depth i) else 0

/--
The untruncated natural-number dimension inequality. This is the direct
coefficientwise inequality for the associated graded algebra, before choosing a
finite cutoff.
-/
def fullCoefficientInequality {r : ℕ}
    (d : ℕ) (b : ℕ → ℕ) (depth : Fin r → ℕ) (n : ℕ) : Prop :=
  d * fullNatTerm b n ≤ b n + fullRelatorTerm b depth n

/--
If a natural-number sequence vanishes from `N` onward, truncating it at `N`
does not change it.
-/
lemma truncated_sequence_eventually
    {b : ℕ → ℕ} {N n : ℕ}
    (hzero : ∀ k, N ≤ k → b k = 0) :
    truncatedNatSequence b N n = b n := by
  unfold truncatedNatSequence
  by_cases hn : n ≤ N
  · simp [hn]
  · have hNn : N ≤ n := Nat.le_of_lt (Nat.lt_of_not_ge hn)
    simp [hn, hzero n hNn]

/--
Under eventual vanishing, the truncated generator term agrees with the full
generator term.
-/
lemma recurrence_full_eventually
    {b : ℕ → ℕ} {N n : ℕ}
    (hzero : ∀ k, N ≤ k → b k = 0) :
    recurrenceNatTerm b N n = fullNatTerm b n := by
  unfold recurrenceNatTerm fullNatTerm
  by_cases hn : 1 ≤ n
  · simp [hn, truncated_sequence_eventually (N := N) hzero]
  · simp [hn]

/--
Under eventual vanishing, the truncated relator term agrees with the full
relator term.
-/
lemma recurrence_eventually_zero
    {r : ℕ} {b : ℕ → ℕ} {N n : ℕ} {depth : Fin r → ℕ}
    (hzero : ∀ k, N ≤ k → b k = 0) :
    recurrenceNatRelator b N depth n = fullRelatorTerm b depth n := by
  unfold recurrenceNatRelator fullRelatorTerm
  refine Finset.sum_congr rfl ?_
  intro i _hi
  by_cases hdepth : depth i ≤ n
  · simp [hdepth, truncated_sequence_eventually (N := N) hzero]
  · simp [hdepth]

/--
The finite truncated coefficient inequality follows formally from the
untruncated inequality once the coefficient sequence is known to vanish from the
chosen cutoff onward.
-/
lemma recurrence_inequality_eventually
    {d r : ℕ} {b : ℕ → ℕ} {N n : ℕ} {depth : Fin r → ℕ}
    (hzero : ∀ k, N ≤ k → b k = 0)
    (hfull : fullCoefficientInequality d b depth n) :
    recurrenceNatInequality d b N depth n := by
  unfold recurrenceNatInequality fullCoefficientInequality at *
  rw [recurrence_full_eventually (N := N) hzero]
  rw [recurrence_eventually_zero (N := N) hzero]
  rw [truncated_sequence_eventually (N := N) hzero]
  exact hfull

/-- Casting the truncated natural sequence gives the real truncated sequence. -/
lemma nat_cast_sequence (b : ℕ → ℕ) (N n : ℕ) :
    ((truncatedNatSequence b N n : ℕ) : ℝ) =
      truncatedSequence (fun n => (b n : ℝ)) N n := by
  unfold truncatedNatSequence truncatedSequence
  split <;> simp

/-- Casting the natural generator term gives the real generator term. -/
lemma cast_recurrence_term (b : ℕ → ℕ) (N n : ℕ) :
    ((recurrenceNatTerm b N n : ℕ) : ℝ) =
      recurrenceGeneratorTerm (fun n => (b n : ℝ)) N n := by
  unfold recurrenceNatTerm recurrenceGeneratorTerm
  split <;> simp [nat_cast_sequence]

/-- Casting the natural relator term gives the real relator term. -/
lemma nat_cast_recurrence
    {r : ℕ} (b : ℕ → ℕ) (N : ℕ) (depth : Fin r → ℕ) (n : ℕ) :
    ((recurrenceNatRelator b N depth n : ℕ) : ℝ) =
      recurrenceRelatorTerm (fun n => (b n : ℝ)) N depth n := by
  unfold recurrenceNatRelator recurrenceRelatorTerm
  rw [Nat.cast_sum]
  refine Finset.sum_congr rfl ?_
  intro i _hi
  split <;> simp [nat_cast_sequence]

/--
A natural-number dimension inequality yields the corresponding real-valued
coefficient inequality.
-/
lemma recurrence_inequality_nat
    {d r : ℕ} {b : ℕ → ℕ} {N : ℕ} {depth : Fin r → ℕ} {n : ℕ}
    (hineq : recurrenceNatInequality d b N depth n) :
    recurrenceCoefficientInequality d (fun n => (b n : ℝ)) N depth n := by
  unfold recurrenceNatInequality at hineq
  unfold recurrenceCoefficientInequality
  rw [← nat_cast_sequence b N n]
  rw [← cast_recurrence_term b N n]
  rw [← nat_cast_recurrence b N depth n]
  exact_mod_cast hineq

/-- The nonnegative-defect form of the same recurrence. -/
def recurrenceDefect {r : ℕ}
    (d : ℕ) (a : ℕ → ℝ) (N : ℕ) (depth : Fin r → ℕ) (n : ℕ) : ℝ :=
  truncatedSequence a N n
    - (d : ℝ) * recurrenceGeneratorTerm a N n
    + recurrenceRelatorTerm a N depth n

/--
The coefficientwise dimension inequality is exactly the nonnegativity of the
usual recurrence defect.
-/
lemma recurrence_nonneg_inequality
    {d r : ℕ} {a : ℕ → ℝ} {N : ℕ} {depth : Fin r → ℕ} {n : ℕ}
    (hineq : recurrenceCoefficientInequality d a N depth n) :
    0 ≤ recurrenceDefect d a N depth n := by
  unfold recurrenceCoefficientInequality at hineq
  unfold recurrenceDefect
  linarith

/--
Unfolding the named recurrence defect recovers the expression used in the
polynomial coefficient calculation.
-/
lemma recurrence_defect_expression
    {d r : ℕ} (a : ℕ → ℝ) (N : ℕ) (depth : Fin r → ℕ) (n : ℕ) :
    recurrenceDefect d a N depth n =
      truncatedSequence a N n
        - (d : ℝ) * (if 1 ≤ n then truncatedSequence a N (n - 1) else 0)
        + ∑ i, if depth i ≤ n then truncatedSequence a N (n - depth i) else 0 := by
  rw [recurrenceDefect, recurrenceGeneratorTerm, recurrenceRelatorTerm]

/--
A finite-window family of coefficientwise dimension inequalities gives the
finite-window truncated recurrence.
-/
theorem truncation_recurrence_inequalities
    {d r : ℕ} {a : ℕ → ℝ} {N : ℕ} {depth : Fin r → ℕ}
    (hineq :
      ∀ n, n ≤ truncationWindow N depth →
        recurrenceCoefficientInequality d a N depth n) :
    ∀ n, n ≤ truncationWindow N depth → 0 ≤
      truncatedSequence a N n
        - (d : ℝ) * (if 1 ≤ n then truncatedSequence a N (n - 1) else 0)
        + ∑ i, if depth i ≤ n then truncatedSequence a N (n - depth i) else 0 := by
  intro n hn
  have hdefect : 0 ≤ recurrenceDefect d a N depth n :=
    recurrence_nonneg_inequality (hineq n hn)
  rwa [← recurrence_defect_expression]

/--
Combining the previous formal reductions: a finite-window family of dimension
inequalities supplies the coefficientwise Hilbert witness directly.
-/
theorem coefficientwise_hilbert_inequalities
    {d r : ℕ} (depth : Fin r → ℕ)
    {a : ℕ → ℝ} {N : ℕ}
    (ha : ∀ n, 0 ≤ a n)
    (ha0 : 0 < a 0)
    (hineq :
      ∀ n, n ≤ truncationWindow N depth →
        recurrenceCoefficientInequality d a N depth n) :
    CoefficientwiseHilbertWitness d r depth := by
  exact coefficientwise_witness_recurrence
    (d := d) (r := r) depth ha ha0
    (truncation_recurrence_inequalities
      (d := d) (a := a) (N := N) (depth := depth) hineq)

/--
If every relator has depth at least `2`, then the full depth-counted relation expression
is bounded above by the quadratic truncation `1 - d t + r t^2` on `(0,1)`.
-/
lemma relator_expression_polynomial
    {d r : ℕ} (depth : Fin r → ℕ)
    (hdepth : ∀ i, 2 ≤ depth i)
    {t : ℝ} (ht0 : 0 < t) (ht1 : t < 1) :
    relatorExpression d r depth t ≤ polynomial d r t := by
  unfold relatorExpression polynomial
  have hsum : ∑ i, t ^ depth i ≤ ∑ _i : Fin r, t ^ (2 : ℕ) := by
    refine Finset.sum_le_sum ?_
    intro i hi
    exact pow_sq_two ht0 ht1 (hdepth i)
  have hcard : (∑ _i : Fin r, t ^ (2 : ℕ)) = r * t ^ (2 : ℕ) := by
    simp [nsmul_eq_mul]
  linarith

/--
Positivity of the full depth-counted Golod--Shafarevich relation expression implies
positivity of the quadratic truncation used in the analytic endgame.
-/
theorem pos_relator_expression
    {d r : ℕ} (depth : Fin r → ℕ)
    (hdepth : ∀ i, 2 ≤ depth i)
    (hpos : ∀ t : ℝ, 0 < t → t < 1 → 0 < relatorExpression d r depth t) :
    ∀ t : ℝ, 0 < t → t < 1 → 0 < polynomial d r t := by
  intro t ht0 ht1
  have hseries : 0 < relatorExpression d r depth t := hpos t ht0 ht1
  have hle : relatorExpression d r depth t ≤ polynomial d r t :=
    relator_expression_polynomial depth hdepth ht0 ht1
  linarith

/--
The remaining Hilbert-series input, packaged in a depth-counted finite form.

To finish the classical Golod--Shafarevich proof for a finite `p`-group with generator
rank `d` and relation rank `r`, it is enough to produce one depth `depth i ≥ 2` for
each relator in a minimal presentation and show that the full relation expression
`1 - d t + Σ_i t^(depth i)` stays positive on `(0,1)`.
-/
def PositiveRelationWitness (d r : ℕ) : Prop :=
  ∃ depth : Fin r → ℕ,
    (∀ i, 2 ≤ depth i) ∧
    ∀ t : ℝ, 0 < t → t < 1 → 0 < relatorExpression d r depth t

/--
The depth-counted Hilbert-series witness above implies the quadratic positivity
hypothesis used by `GShafar.inequality`.
-/
theorem pos_positive_witness
    {d r : ℕ}
    (h : PositiveRelationWitness d r) :
    ∀ t : ℝ, 0 < t → t < 1 → 0 < polynomial d r t := by
  rcases h with ⟨depth, hdepth, hpos⟩
  exact pos_relator_expression depth hdepth hpos

/--
Abstract finite-presentation data for the eventual pro-`p` application.

The intended future input is that a finite pro-`p` presentation supplies the
standard relation-rank lower bound in the case `d = 2`, together with the
required positivity statement for the Golod--Shafarevich polynomial.

For actual `PPDatum`, positivity of `relationRank` is now
derived below from the presentation model by showing `RelationCounts` is
nonempty and then ruling out the zero-relator case by identifying it with a
free group. We still keep `relationRank_pos` as part of this abstract wrapper,
since a bare finite presentation datum need not come from that concrete model.
-/
structure FinitePresentationDatum where
  generatorRank : ℕ
  relationRank : ℕ
  relationRank_pos : 1 ≤ relationRank
  relation_rank_two : generatorRank = 2 → 2 ≤ relationRank
  gs_positive : ∀ t : ℝ, 0 < t → t < 1 → 0 < polynomial generatorRank relationRank t

/--
Once a finite presentation datum satisfies the positivity hypothesis, the strict
Golod--Shafarevich inequality follows.
-/
theorem inequality (H : FinitePresentationDatum) :
    (H.relationRank : ℝ) > (H.generatorRank : ℝ) ^ (2 : ℕ) / 4 := by
  apply pos_unit_interval
  · intro hsmall
    exact small_case_bounds
      hsmall H.relationRank_pos H.relation_rank_two
  · exact H.gs_positive

end GShafar

end Submission
