import Mathlib
import Submission.Group.FinitePGS
import Submission.Group.GolodShafarevichTruncation


open scoped Topology Pointwise

noncomputable section

namespace Submission

universe u
universe v w z

/--
Degree-one generation modulo `I²` propagates to all positive augmentation
powers.

If `I / I²` is generated by the chosen degree-one differences, then
`I^n / I^(n+1)` is generated by multiplying those differences by `I^(n-1)`.
-/
theorem
PPDatum.presaug_powerleft_modulosquare
    (H : PPDatum)
    {rels : Fin H.relationRank → FreeGroup (Fin H.generatorRank)}
    (genDiff : Fin H.generatorRank → H.presentedGroupAlgebra rels)
    (hgen : ∀ j, genDiff j ∈ H.presentedAugmentationIdeal rels)
    (n : ℕ)
    (hn : 1 ≤ n)
    (hleft :
      augmentationModuloSquare
        (ZMod H.realizesFiniteNontrivial.p)
        (H.pGroup rels)
        (Fin H.generatorRank)
        genDiff) :
    H.presentedAugmentationGenerated
      (rels := rels) genDiff hgen n hn := by
  classical
  let A := H.presentedGroupAlgebra rels
  let I : Ideal A := H.presentedAugmentationIdeal rels
  haveI : I.IsTwoSided := by
    change (H.presentedAugmentationIdeal rels).IsTwoSided
    dsimp [PPDatum.presentedAugmentationIdeal,
      GShafar.augmentationIdeal]
    infer_instance
  intro x
  have hxmul : (x : A) ∈ I * I ^ (n - 1) := by
    have hxpow : (x : A) ∈ I ^ n := by
      simp [I, PPDatum.presentedAugmentationSubmodule]
    have hdegree : 1 + (n - 1) = n := by omega
    have hpow : I ^ n = I * I ^ (n - 1) := by
      calc
        I ^ n = I ^ (1 + (n - 1)) := by rw [hdegree]
        _ = I ^ 1 * I ^ (n - 1) := by rw [Ideal.IsTwoSided.pow_add]
        _ = I * I ^ (n - 1) := by rw [Submodule.pow_one]
    simpa [hpow] using hxpow
  let P : A → Prop := fun z =>
    ∃ y : Fin H.generatorRank →
        H.presentedAugmentationSubmodule (rels := rels) (n - 1),
      z - ∑ j, genDiff j *
        ((y j : H.presentedAugmentationSubmodule (rels := rels) (n - 1)) :
          A) ∈ I ^ (n + 1)
  have hxP : P (x : A) := by
    refine Submodule.mul_induction_on hxmul ?mul_mem ?add_mem
    · intro a ha b hb
      rcases hleft a (by simpa [I] using ha) with ⟨coeff, hcoeff⟩
      let y : Fin H.generatorRank →
          H.presentedAugmentationSubmodule (rels := rels) (n - 1) :=
        fun j => ⟨coeff j * b, (I ^ (n - 1)).mul_mem_left (coeff j) hb⟩
      refine ⟨y, ?_⟩
      have hsum_mul :
          (∑ j, genDiff j * coeff j) * b =
            ∑ j, genDiff j *
              ((y j :
                H.presentedAugmentationSubmodule (rels := rels) (n - 1)) :
                A) := by
        dsimp [y]
        rw [Finset.sum_mul]
        apply Finset.sum_congr rfl
        intro j _hj
        rw [mul_assoc]
      have herr_eq :
          a * b -
              ∑ j, genDiff j *
                ((y j :
                  H.presentedAugmentationSubmodule (rels := rels) (n - 1)) :
                  A) =
            (a - ∑ j, genDiff j * coeff j) * b := by
        rw [← hsum_mul]
        noncomm_ring
      rw [herr_eq]
      have herr_prod :
          (a - ∑ j, genDiff j * coeff j) * b ∈
            I ^ (2 : ℕ) * I ^ (n - 1) :=
        Ideal.mul_mem_mul (by simpa [I] using hcoeff) hb
      have hdegree : (2 : ℕ) + (n - 1) = n + 1 := by omega
      rw [← hdegree, Ideal.IsTwoSided.pow_add]
      exact herr_prod
    · intro u v hu hv
      rcases hu with ⟨yu, hyu⟩
      rcases hv with ⟨yv, hyv⟩
      let y : Fin H.generatorRank →
          H.presentedAugmentationSubmodule (rels := rels) (n - 1) :=
        fun j => yu j + yv j
      refine ⟨y, ?_⟩
      have hsum_add :
          ∑ j, genDiff j *
              ((y j :
                H.presentedAugmentationSubmodule (rels := rels) (n - 1)) :
                A) =
            (∑ j, genDiff j *
              ((yu j :
                H.presentedAugmentationSubmodule (rels := rels) (n - 1)) :
                A)) +
            (∑ j, genDiff j *
              ((yv j :
                H.presentedAugmentationSubmodule (rels := rels) (n - 1)) :
                A)) := by
        dsimp [y]
        simp [mul_add, Finset.sum_add_distrib]
      have herr_eq :
          u + v -
              ∑ j, genDiff j *
                ((y j :
                  H.presentedAugmentationSubmodule (rels := rels) (n - 1)) :
                  A) =
            (u -
              ∑ j, genDiff j *
                ((yu j :
                  H.presentedAugmentationSubmodule (rels := rels) (n - 1)) :
                  A)) +
            (v -
              ∑ j, genDiff j *
                ((yv j :
                  H.presentedAugmentationSubmodule (rels := rels) (n - 1)) :
                  A)) := by
        rw [hsum_add]
        noncomm_ring
      rw [herr_eq]
      exact (I ^ (n + 1)).add_mem hyu hyv
  simpa [P, I, PPDatum.presentedAugmentationSubmodule] using hxP
/-- Presentation-generator differences lie in the presented augmentation ideal. -/
lemma PPDatum.presented_difference_ideal
    (H : PPDatum)
    {rels : Fin H.relationRank → FreeGroup (Fin H.generatorRank)}
    (j : Fin H.generatorRank) :
    H.presentedGeneratorDifference (rels := rels) j ∈
      H.presentedAugmentationIdeal rels := by
  simpa [PPDatum.presentedGeneratorDifference,
    PPDatum.presentedAugmentationIdeal] using
    augmentation_difference_ideal
      (ZMod H.realizesFiniteNontrivial.p)
      (H.pGroup rels)
      (PresentedGroup.of (rels := Set.range rels) j)
/--
The degree-one classes of the presentation-generator differences span
`I / I²`.

This is the formal use of the fact that `PresentedGroup.of` generates the
presented group.
-/
theorem PPDatum.presented_classes_top
    (H : PPDatum)
    (_p_prime : Nat.Prime H.realizesFiniteNontrivial.p)
    [Finite H.realizesFiniteNontrivial.carrier]
    {rels : Fin H.relationRank → FreeGroup (Fin H.generatorRank)}
    (hrels :
      Nonempty (PresentedGroup (Set.range rels) ≃* H.realizesFiniteNontrivial.carrier)) :
    Submodule.span (ZMod H.realizesFiniteNontrivial.p)
      (Set.range fun j : Fin H.generatorRank =>
        augmentationDegreeClass
          (ZMod H.realizesFiniteNontrivial.p)
          (H.pGroup rels)
          (PresentedGroup.of (rels := Set.range rels) j)) =
      ⊤ := by
  classical
  let p := H.realizesFiniteNontrivial.p
  haveI : Fact p.Prime := ⟨_p_prime⟩
  haveI : Finite (H.pGroup rels) := H.presentedGroup_finite hrels
  have hall :
      Submodule.span (ZMod p)
        (Set.range fun g : H.pGroup rels =>
          augmentationDegreeClass (ZMod p) (H.pGroup rels) g) =
        ⊤ :=
    augmentation_span_top (ZMod p) (H.pGroup rels)
  apply le_antisymm
  · exact le_top
  · rw [← hall]
    refine Submodule.span_le.mpr ?_
    intro x hx
    rcases hx with ⟨g, rfl⟩
    have hg :
        g ∈ Subgroup.closure
          (Set.range
            (PresentedGroup.of :
              Fin H.generatorRank → H.pGroup rels)) := by
      rw [PresentedGroup.closure_range_of (Set.range rels)]
      exact Subgroup.mem_top g
    exact
      span_range_closure
        (ZMod p)
        (H.pGroup rels)
        (Fin H.generatorRank)
        (fun j : Fin H.generatorRank =>
          PresentedGroup.of (rels := Set.range rels) j)
        hg
/--
Presentation-generator differences left-generate the augmentation ideal modulo
`I²`.
-/
theorem PPDatum.differences_modulo_square
    (H : PPDatum)
    (_p_prime : Nat.Prime H.realizesFiniteNontrivial.p)
    [Finite H.realizesFiniteNontrivial.carrier]
    {rels : Fin H.relationRank → FreeGroup (Fin H.generatorRank)}
    (hrels :
      Nonempty (PresentedGroup (Set.range rels) ≃* H.realizesFiniteNontrivial.carrier)) :
    augmentationModuloSquare
      (ZMod H.realizesFiniteNontrivial.p)
      (H.pGroup rels)
      (Fin H.generatorRank)
      (H.presentedGeneratorDifference (rels := rels)) := by
  classical
  let p := H.realizesFiniteNontrivial.p
  let genDiff : Fin H.generatorRank → H.presentedGroupAlgebra rels :=
    H.presentedGeneratorDifference (rels := rels)
  have hgen :
      ∀ j, genDiff j ∈ H.presentedAugmentationIdeal rels := by
    intro j
    exact H.presented_difference_ideal (rels := rels) j
  have hspanClass :
      Submodule.span (ZMod p)
        (Set.range fun j : Fin H.generatorRank =>
          augmentationDegreeMk
            (ZMod p)
            (H.pGroup rels)
            (genDiff j)
            (hgen j)) =
        ⊤ := by
    simpa [p, genDiff, PPDatum.presentedGeneratorDifference,
      augmentationDegreeMk, augmentationDegreeClass] using
      H.presented_classes_top _p_prime hrels
  exact
    modulo_square_span
      (ZMod p)
      (H.pGroup rels)
      (Fin H.generatorRank)
      genDiff
      hgen
      hspanClass
/--
Presentation-generator differences right-generate the augmentation ideal modulo
`I²`.
-/
theorem PPDatum.differences_generate_modulo
    (H : PPDatum)
    (_p_prime : Nat.Prime H.realizesFiniteNontrivial.p)
    [Finite H.realizesFiniteNontrivial.carrier]
    {rels : Fin H.relationRank → FreeGroup (Fin H.generatorRank)}
    (hrels :
      Nonempty (PresentedGroup (Set.range rels) ≃* H.realizesFiniteNontrivial.carrier)) :
    generatedModuloSquare
      (ZMod H.realizesFiniteNontrivial.p)
      (H.pGroup rels)
      (Fin H.generatorRank)
      (H.presentedGeneratorDifference (rels := rels)) := by
  classical
  let p := H.realizesFiniteNontrivial.p
  let genDiff : Fin H.generatorRank → H.presentedGroupAlgebra rels :=
    H.presentedGeneratorDifference (rels := rels)
  have hgen :
      ∀ j, genDiff j ∈ H.presentedAugmentationIdeal rels := by
    intro j
    exact H.presented_difference_ideal (rels := rels) j
  have hspanClass :
      Submodule.span (ZMod p)
        (Set.range fun j : Fin H.generatorRank =>
          augmentationDegreeMk
            (ZMod p)
            (H.pGroup rels)
            (genDiff j)
            (hgen j)) =
        ⊤ := by
    simpa [p, genDiff, PPDatum.presentedGeneratorDifference,
      augmentationDegreeMk, augmentationDegreeClass] using
      H.presented_classes_top _p_prime hrels
  exact
    generated_modulo_square
      (ZMod p)
      (H.pGroup rels)
      (Fin H.generatorRank)
      genDiff
      hgen
      hspanClass
/--
The numerator-level generation statement implies surjectivity of the descended
high-degree generator multiplication map.
-/
theorem
    PPDatum.presented_multiplication_surjective
    (H : PPDatum)
    {rels : Fin H.relationRank → FreeGroup (Fin H.generatorRank)}
    (genDiff : Fin H.generatorRank → H.presentedGroupAlgebra rels)
    (hgen : ∀ j, genDiff j ∈ H.presentedAugmentationIdeal rels)
    (n : ℕ)
    (hn : 1 ≤ n)
    (hspan :
      H.presentedAugmentationGenerated
        (rels := rels) genDiff hgen n hn) :
    Function.Surjective
      (H.presentedGeneratorMultiplication
        (rels := rels) genDiff hgen n hn) := by
  classical
  intro z
  rcases (H.presentedAugmentationKernel (rels := rels) n).mkQ_surjective z with
    ⟨x, rfl⟩
  rcases hspan x with ⟨y, hy⟩
  let yLayer : H.pres_highdegree_gensource (rels := rels) n :=
    fun j =>
      (H.presentedAugmentationKernel (rels := rels) (n - 1)).mkQ (y j)
  let hdegree : 1 + (n - 1) = n := by omega
  let yProduct : Fin H.generatorRank →
      H.presentedAugmentationSubmodule (rels := rels) n :=
    fun j =>
      H.presentedAugmentationLeft
        (m := 1) (n := n - 1) (k := n) hdegree
        (genDiff j)
        (by simpa [Submodule.pow_one] using hgen j)
        (y j)
  let s : H.presentedAugmentationSubmodule (rels := rels) n :=
    ∑ j, yProduct j
  let K := H.presentedAugmentationKernel (rels := rels) n
  refine ⟨yLayer, ?_⟩
  have hmap :
      H.presentedGeneratorMultiplication
          (rels := rels) genDiff hgen n hn yLayer =
        K.mkQ s := by
    have hβsum :
        H.presentedGeneratorMultiplication
            (rels := rels) genDiff hgen n hn yLayer =
          ∑ j, K.mkQ (yProduct j) := by
      dsimp [PPDatum.presentedGeneratorMultiplication,
        yLayer]
      simp only [LinearMap.sum_apply, LinearMap.comp_apply, LinearMap.proj_apply]
      apply Finset.sum_congr rfl
      intro j _hj
      dsimp [yProduct, K]
      exact H.presented_left_mk
        (m := 1) (n := n - 1) (k := n) hdegree
        (genDiff j)
        (by simpa [Submodule.pow_one] using hgen j)
        (y j)
    have hsum :
        (∑ j, K.mkQ (yProduct j)) = K.mkQ s := by
      dsimp [s]
      exact (map_sum K.mkQ yProduct Finset.univ).symm
    exact hβsum.trans hsum
  have hsval :
      (s : H.presentedGroupAlgebra rels) =
        ∑ j, genDiff j *
          ((y j :
            H.presentedAugmentationSubmodule (rels := rels) (n - 1)) :
            H.presentedGroupAlgebra rels) := by
    dsimp [s, yProduct]
    simp
  have hkernel :
      x - s ∈ H.presentedAugmentationKernel (rels := rels) n := by
    change ((x - s :
        H.presentedAugmentationSubmodule (rels := rels) n) :
        H.presentedGroupAlgebra rels) ∈
      H.presentedAugmentationSubmodule (rels := rels) (n + 1)
    simpa [sub_eq_add_neg, hsval] using hy
  have hkernel' :
      s - x ∈ H.presentedAugmentationKernel (rels := rels) n := by
    rw [← neg_sub]
    exact (H.presentedAugmentationKernel (rels := rels) n).neg_mem hkernel
  rw [hmap]
  exact (Submodule.Quotient.eq (H.presentedAugmentationKernel (rels := rels) n)).mpr
    hkernel'
/--
The right-oriented numerator-level generation statement implies surjectivity of
the descended right multiplication map.
-/
theorem
    PPDatum.presented_multiplication_gen
    (H : PPDatum)
    {rels : Fin H.relationRank → FreeGroup (Fin H.generatorRank)}
    (genDiff : Fin H.generatorRank → H.presentedGroupAlgebra rels)
    (hgen : ∀ j, genDiff j ∈ H.presentedAugmentationIdeal rels)
    (n : ℕ)
    (hn : 1 ≤ n)
    (hspan :
      H.presentedGeneratedDegree
        (rels := rels) genDiff hgen n hn) :
    Function.Surjective
      (H.highDegreeMultiplication
        (rels := rels) genDiff hgen n hn) := by
  classical
  intro z
  rcases (H.presentedAugmentationKernel (rels := rels) n).mkQ_surjective z with
    ⟨x, rfl⟩
  rcases hspan x with ⟨y, hy⟩
  let yLayer : H.pres_highdegree_gensource (rels := rels) n :=
    fun j =>
      (H.presentedAugmentationKernel (rels := rels) (n - 1)).mkQ (y j)
  let hdegree : (n - 1) + 1 = n := by omega
  let yProduct : Fin H.generatorRank →
      H.presentedAugmentationSubmodule (rels := rels) n :=
    fun j =>
      H.presentedRightMul
        (m := 1) (n := n - 1) (k := n) hdegree
        (genDiff j)
        (by simpa [Submodule.pow_one] using hgen j)
        (y j)
  let s : H.presentedAugmentationSubmodule (rels := rels) n :=
    ∑ j, yProduct j
  let K := H.presentedAugmentationKernel (rels := rels) n
  refine ⟨yLayer, ?_⟩
  have hmap :
      H.highDegreeMultiplication
          (rels := rels) genDiff hgen n hn yLayer =
        K.mkQ s := by
    have hβsum :
        H.highDegreeMultiplication
            (rels := rels) genDiff hgen n hn yLayer =
          ∑ j, K.mkQ (yProduct j) := by
      dsimp [PPDatum.highDegreeMultiplication,
        yLayer]
      simp only [LinearMap.sum_apply, LinearMap.comp_apply, LinearMap.proj_apply]
      apply Finset.sum_congr rfl
      intro j _hj
      dsimp [yProduct, K]
      exact H.presented_augmentation_mk
        (m := 1) (n := n - 1) (k := n) hdegree
        (genDiff j)
        (by simpa [Submodule.pow_one] using hgen j)
        (y j)
    have hsum :
        (∑ j, K.mkQ (yProduct j)) = K.mkQ s := by
      dsimp [s]
      exact (map_sum K.mkQ yProduct Finset.univ).symm
    exact hβsum.trans hsum
  have hsval :
      (s : H.presentedGroupAlgebra rels) =
        ∑ j,
          ((y j :
            H.presentedAugmentationSubmodule (rels := rels) (n - 1)) :
            H.presentedGroupAlgebra rels) *
            genDiff j := by
    dsimp [s, yProduct]
    simp
  have hkernel :
      x - s ∈ H.presentedAugmentationKernel (rels := rels) n := by
    change ((x - s :
        H.presentedAugmentationSubmodule (rels := rels) n) :
        H.presentedGroupAlgebra rels) ∈
      H.presentedAugmentationSubmodule (rels := rels) (n + 1)
    simpa [sub_eq_add_neg, hsval] using hy
  have hkernel' :
      s - x ∈ H.presentedAugmentationKernel (rels := rels) n := by
    rw [← neg_sub]
    exact (H.presentedAugmentationKernel (rels := rels) n).neg_mem hkernel
  rw [hmap]
  exact (Submodule.Quotient.eq (H.presentedAugmentationKernel (rels := rels) n)).mpr
    hkernel'
/--
For a finite minimal presentation, the presentation generator differences
generate each positive associated-graded augmentation layer.

This is the remaining group-algebra content behind the generator side of the
Golod--Shafarevich complex, separated from the quotient-linear-algebra
unwinding above.
-/
theorem
    PPDatum.presaug_powergen_presgensexists
    (H : PPDatum)
    (_p_prime : Nat.Prime H.realizesFiniteNontrivial.p)
    [Finite H.realizesFiniteNontrivial.carrier]
    [Nontrivial H.realizesFiniteNontrivial.carrier]
    (_isPGroup : IsPGroup H.realizesFiniteNontrivial.p H.realizesFiniteNontrivial.carrier)
    {rels : Fin H.relationRank → FreeGroup (Fin H.generatorRank)}
    (_hrels :
      Nonempty (PresentedGroup (Set.range rels) ≃* H.realizesFiniteNontrivial.carrier))
    (n : ℕ)
    (hn : 1 ≤ n) :
    ∃ genDiff : Fin H.generatorRank → H.presentedGroupAlgebra rels,
      ∃ hgen : ∀ j, genDiff j ∈ H.presentedAugmentationIdeal rels,
        H.presentedAugmentationGenerated
          (rels := rels) genDiff hgen n hn := by
  let genDiff : Fin H.generatorRank → H.presentedGroupAlgebra rels :=
    H.presentedGeneratorDifference (rels := rels)
  have hgen : ∀ j, genDiff j ∈ H.presentedAugmentationIdeal rels := by
    intro j
    exact H.presented_difference_ideal (rels := rels) j
  have hleft :
      augmentationModuloSquare
        (ZMod H.realizesFiniteNontrivial.p)
        (H.pGroup rels)
        (Fin H.generatorRank)
        genDiff := by
    simpa [genDiff] using
      H.differences_modulo_square _p_prime _hrels
  refine ⟨genDiff, hgen, ?_⟩
  exact
    H.presaug_powerleft_modulosquare
      (rels := rels) genDiff hgen n hn hleft

set_option synthInstance.maxHeartbeats 80000 in
-- The dependent quotient/pi fields need extra search for their linear-map structures.
/--
The exact high-degree Golod--Shafarevich complex.

The map `generatorToTarget` is induced by multiplying degree `n - 1`
augmentation classes by the degree-one classes of the presentation generators.
The map `relatorToGenerator` is induced by the leading forms of the relators.
The two proof fields are the right-exactness assertions needed for the
coefficient estimate.
-/
structure PPDatum.PresHighdegreeGscomplex
    (H : PPDatum)
    {rels : Fin H.relationRank → FreeGroup (Fin H.generatorRank)}
    (depth : Fin H.relationRank → ℕ)
    (n : ℕ) where
  generatorToTarget :
    H.pres_highdegree_gensource (rels := rels) n →ₗ[ZMod
        H.realizesFiniteNontrivial.p]
      H.pALayer (rels := rels) n
  relatorToGenerator :
    H.pHSrc (rels := rels) depth n →ₗ[ZMod
        H.realizesFiniteNontrivial.p]
      H.pres_highdegree_gensource (rels := rels) n
  generator_target_surjective :
    Function.Surjective generatorToTarget
  relator_covers_kernel :
    LinearMap.ker generatorToTarget ≤ LinearMap.range relatorToGenerator
/--
The degree-`n` multiplication part of the GS complex exists.

This is the assertion that the associated graded algebra of the augmentation
filtration is generated in degree one by the presentation generators. It is
strictly smaller than the full high-degree estimate: it says nothing about
relations, only that the map from generator copies of degree `n - 1` onto the
degree-`n` layer is available.
-/
theorem PPDatum.preshigh_degreegen_targsurjexis
    (H : PPDatum)
    (_p_prime : Nat.Prime H.realizesFiniteNontrivial.p)
    [Finite H.realizesFiniteNontrivial.carrier]
    [Nontrivial H.realizesFiniteNontrivial.carrier]
    (_isPGroup : IsPGroup H.realizesFiniteNontrivial.p H.realizesFiniteNontrivial.carrier)
    {rels : Fin H.relationRank → FreeGroup (Fin H.generatorRank)}
    (hrels :
      Nonempty (PresentedGroup (Set.range rels) ≃* H.realizesFiniteNontrivial.carrier))
    (n : ℕ)
    (hn : 2 ≤ n) :
    ∃ β :
      H.pres_highdegree_gensource (rels := rels) n →ₗ[
          ZMod H.realizesFiniteNontrivial.p]
      H.pALayer (rels := rels) n,
      Function.Surjective β := by
  have hn' : 1 ≤ n := by omega
  rcases H.presaug_powergen_presgensexists
      _p_prime _isPGroup hrels n hn' with
    ⟨genDiff, hgen, hspan⟩
  refine ⟨
    H.presentedGeneratorMultiplication
      (rels := rels) genDiff hgen n hn',
    ?_⟩
  exact
    H.presented_multiplication_surjective
      (rels := rels) genDiff hgen n hn' hspan
/--
The concrete generator-to-target map used in the high-degree
Golod--Shafarevich complex.

This specializes the abstract multiplication map to the actual presentation
generators.  Writing this map once is useful because the relator side must
cover the kernel of this specific map: it is the map whose `j`th summand is
left multiplication by the class of `x_j - 1`.
-/
noncomputable def
    PPDatum.preshigh_degreepres_genmulmap
    (H : PPDatum)
    {rels : Fin H.relationRank → FreeGroup (Fin H.generatorRank)}
    (n : ℕ)
    (hn : 1 ≤ n) :
    H.pres_highdegree_gensource (rels := rels) n →ₗ[ZMod
        H.realizesFiniteNontrivial.p]
      H.pALayer (rels := rels) n :=
  H.presentedGeneratorMultiplication
    (rels := rels)
    (H.presentedGeneratorDifference (rels := rels))
    (fun j => H.presented_difference_ideal (rels := rels) j)
    n
    hn
/--
The right-oriented concrete presentation-generator multiplication map.

This is the generator-to-target map compatible with the Fox identity
`∑ (∂r/∂x_j)(x_j - 1) = r - 1`.
-/
noncomputable def
    PPDatum.presentedHighMultiplication
    (H : PPDatum)
    {rels : Fin H.relationRank → FreeGroup (Fin H.generatorRank)}
    (n : ℕ)
    (hn : 1 ≤ n) :
    H.pres_highdegree_gensource (rels := rels) n →ₗ[ZMod
        H.realizesFiniteNontrivial.p]
      H.pALayer (rels := rels) n :=
  H.highDegreeMultiplication
    (rels := rels)
    (H.presentedGeneratorDifference (rels := rels))
    (fun j => H.presented_difference_ideal (rels := rels) j)
    n
    hn
/--
The concrete presentation-generator multiplication map is surjective.

Mathematically, this is exactly the generator half of the associated-graded
statement: the classes of the presentation generators generate the whole
augmentation graded algebra in positive degree.  The proof combines the
degree-one Frattini/augmentation spanning theorem with the propagation lemma
for powers of the augmentation ideal.
-/
theorem
    PPDatum.preshigh_degreepresgen_mulmapsurj
    (H : PPDatum)
    (_p_prime : Nat.Prime H.realizesFiniteNontrivial.p)
    [Finite H.realizesFiniteNontrivial.carrier]
    [Nontrivial H.realizesFiniteNontrivial.carrier]
    (_isPGroup : IsPGroup H.realizesFiniteNontrivial.p H.realizesFiniteNontrivial.carrier)
    {rels : Fin H.relationRank → FreeGroup (Fin H.generatorRank)}
    (hrels :
      Nonempty (PresentedGroup (Set.range rels) ≃* H.realizesFiniteNontrivial.carrier))
    (n : ℕ)
    (hn : 1 ≤ n) :
    Function.Surjective
      (H.preshigh_degreepres_genmulmap
        (rels := rels) n hn) := by
  let genDiff : Fin H.generatorRank → H.presentedGroupAlgebra rels :=
    H.presentedGeneratorDifference (rels := rels)
  have hgen : ∀ j, genDiff j ∈ H.presentedAugmentationIdeal rels := by
    intro j
    exact H.presented_difference_ideal (rels := rels) j
  have hleft :
      augmentationModuloSquare
        (ZMod H.realizesFiniteNontrivial.p)
        (H.pGroup rels)
        (Fin H.generatorRank)
        genDiff := by
    simpa [genDiff] using
      H.differences_modulo_square _p_prime hrels
  have hspan :
      H.presentedAugmentationGenerated
        (rels := rels) genDiff hgen n hn :=
    H.presaug_powerleft_modulosquare
      (rels := rels) genDiff hgen n hn hleft
  simpa [PPDatum.preshigh_degreepres_genmulmap,
    genDiff, hgen] using
    H.presented_multiplication_surjective
      (rels := rels) genDiff hgen n hn hspan
/--
The concrete right-oriented presentation-generator multiplication map is
surjective.
-/
theorem
    PPDatum.presented_high_multiplication
    (H : PPDatum)
    (_p_prime : Nat.Prime H.realizesFiniteNontrivial.p)
    [Finite H.realizesFiniteNontrivial.carrier]
    [Nontrivial H.realizesFiniteNontrivial.carrier]
    (_isPGroup : IsPGroup H.realizesFiniteNontrivial.p H.realizesFiniteNontrivial.carrier)
    {rels : Fin H.relationRank → FreeGroup (Fin H.generatorRank)}
    (hrels :
      Nonempty (PresentedGroup (Set.range rels) ≃* H.realizesFiniteNontrivial.carrier))
    (n : ℕ)
    (hn : 1 ≤ n) :
    Function.Surjective
      (H.presentedHighMultiplication
        (rels := rels) n hn) := by
  let genDiff : Fin H.generatorRank → H.presentedGroupAlgebra rels :=
    H.presentedGeneratorDifference (rels := rels)
  have hgen : ∀ j, genDiff j ∈ H.presentedAugmentationIdeal rels := by
    intro j
    exact H.presented_difference_ideal (rels := rels) j
  have hright :
      generatedModuloSquare
        (ZMod H.realizesFiniteNontrivial.p)
        (H.pGroup rels)
        (Fin H.generatorRank)
        genDiff := by
    simpa [genDiff] using
      H.differences_generate_modulo _p_prime hrels
  have hspan :
      H.presentedGeneratedDegree
        (rels := rels) genDiff hgen n hn :=
    H.presented_aug_square
      (rels := rels) genDiff hgen n hn hright
  simpa [PPDatum.presentedHighMultiplication,
    genDiff, hgen] using
    H.presented_multiplication_gen
      (rels := rels) genDiff hgen n hn hspan

set_option synthInstance.maxHeartbeats 80000 in
-- The dependent quotient/pi types in the component-kernel proof need extra search.
set_option maxHeartbeats 800000 in
-- The rank-count proof unfolds several finite-dimensional product and Pi computations.
/--
The finite-dimensional rank count following from the high-degree
Golod--Shafarevich map.

This theorem is deliberately separated from the construction of the map above:
it should follow from surjectivity, the product/pi dimension formulas, and the
fact that summing over the contributing subtype is the same as summing the
original `if depth i ≤ n then ... else 0` expression.
-/
theorem
    PPDatum.preshigh_degreegen_relaestisurj
    (H : PPDatum)
    (_p_prime : Nat.Prime H.realizesFiniteNontrivial.p)
    [Finite H.realizesFiniteNontrivial.carrier]
    {rels : Fin H.relationRank → FreeGroup (Fin H.generatorRank)}
    {depth : Fin H.relationRank → ℕ}
    (hrels :
      Nonempty (PresentedGroup (Set.range rels) ≃* H.realizesFiniteNontrivial.carrier))
    (n : ℕ)
    (_hn : 2 ≤ n)
    (hΨ :
      ∃ Ψ :
        H.pres_highdegree_targetrelators (rels := rels) depth n →ₗ[ZMod
            H.realizesFiniteNontrivial.p]
          H.pres_highdegree_gensource (rels := rels) n,
        Function.Surjective Ψ) :
    H.generatorRank * H.presentedAugmentationFinrank hrels (n - 1) ≤
      H.presentedAugmentationFinrank hrels n +
        ∑ i, if depth i ≤ n then
          H.presentedAugmentationFinrank hrels (n - depth i)
        else
          0 := by
  classical
  let p := H.realizesFiniteNontrivial.p
  letI : Fact p.Prime := ⟨_p_prime⟩
  haveI : Fact H.realizesFiniteNontrivial.p.Prime := ⟨_p_prime⟩
  haveI : Finite (H.pGroup rels) := H.presentedGroup_finite hrels
  haveI : ∀ i : Fin H.generatorRank,
      Module.Free (ZMod H.realizesFiniteNontrivial.p)
        (H.pALayer (rels := rels) (n - 1)) := fun _ =>
    Module.Free.of_divisionRing
      (ZMod H.realizesFiniteNontrivial.p)
      (H.pALayer (rels := rels) (n - 1))
  haveI : ∀ i : H.pres_highdegree_relatorindex depth n,
      Module.Free (ZMod H.realizesFiniteNontrivial.p)
        (H.pALayer (rels := rels) (n - depth i.1)) := fun i =>
    Module.Free.of_divisionRing
      (ZMod H.realizesFiniteNontrivial.p)
      (H.pALayer (rels := rels) (n - depth i.1))
  haveI : Module.Free (ZMod H.realizesFiniteNontrivial.p)
      (H.pALayer (rels := rels) n) := by
    exact Module.Free.of_divisionRing
      (ZMod H.realizesFiniteNontrivial.p)
      (H.pALayer (rels := rels) n)
  haveI : Module.Free (ZMod H.realizesFiniteNontrivial.p)
      (H.pHSrc (rels := rels) depth n) := by
    dsimp [PPDatum.pHSrc]
    infer_instance
  rcases hΨ with ⟨Ψ, hΨsurj⟩
  have hdim :
      Module.finrank (ZMod H.realizesFiniteNontrivial.p)
          (H.pres_highdegree_gensource (rels := rels) n) ≤
        Module.finrank (ZMod H.realizesFiniteNontrivial.p)
          (H.pres_highdegree_targetrelators (rels := rels) depth n) := by
    have hrank :
        Cardinal.lift.{0}
            (Module.rank (ZMod H.realizesFiniteNontrivial.p)
              (H.pres_highdegree_gensource (rels := rels) n)) ≤
          Cardinal.lift
            (Module.rank (ZMod H.realizesFiniteNontrivial.p)
              (H.pres_highdegree_targetrelators (rels := rels) depth n)) :=
      LinearMap.lift_rank_le_of_surjective Ψ hΨsurj
    exact Module.finrank_le_finrank_of_rank_le_rank hrank
      (Module.rank_lt_aleph0 (ZMod H.realizesFiniteNontrivial.p)
        (H.pres_highdegree_targetrelators (rels := rels) depth n))
  have hsource :
      Module.finrank (ZMod H.realizesFiniteNontrivial.p)
          (H.pres_highdegree_gensource (rels := rels) n) =
        H.generatorRank * H.presentedAugmentationFinrank hrels (n - 1) := by
    let hfree : ∀ i : Fin H.generatorRank,
        Module.Free (ZMod H.realizesFiniteNontrivial.p)
          (H.pALayer (rels := rels) (n - 1)) := fun _ =>
      Module.Free.of_divisionRing
        (ZMod H.realizesFiniteNontrivial.p)
        (H.pALayer (rels := rels) (n - 1))
    let hfinite : ∀ i : Fin H.generatorRank,
        Module.Finite (ZMod H.realizesFiniteNontrivial.p)
          (H.pALayer (rels := rels) (n - 1)) := fun _ =>
      inferInstance
    dsimp [PPDatum.pres_highdegree_gensource]
    rw [@Module.finrank_pi_fintype
      (ZMod H.realizesFiniteNontrivial.p)
      _ _
      (Fin H.generatorRank)
      _
      (fun _ => H.pALayer (rels := rels) (n - 1))
      _ _
      hfree hfinite]
    simp [PPDatum.presentedAugmentationFinrank]
  have hrelator :
      Module.finrank (ZMod H.realizesFiniteNontrivial.p)
          (H.pHSrc (rels := rels) depth n) =
        ∑ i, if depth i ≤ n then
          H.presentedAugmentationFinrank hrels (n - depth i)
        else
          0 := by
    let hfree : ∀ i : H.pres_highdegree_relatorindex depth n,
        Module.Free (ZMod H.realizesFiniteNontrivial.p)
          (H.pALayer (rels := rels) (n - depth i.1)) := fun i =>
      Module.Free.of_divisionRing
        (ZMod H.realizesFiniteNontrivial.p)
        (H.pALayer (rels := rels) (n - depth i.1))
    let hfinite : ∀ i : H.pres_highdegree_relatorindex depth n,
        Module.Finite (ZMod H.realizesFiniteNontrivial.p)
          (H.pALayer (rels := rels) (n - depth i.1)) := fun _ =>
      inferInstance
    dsimp [PPDatum.pHSrc, PPDatum.pres_highdegree_relatorindex]
    rw [@Module.finrank_pi_fintype
      (ZMod H.realizesFiniteNontrivial.p)
      _ _
      (H.pres_highdegree_relatorindex depth n)
      _
      (fun i => H.pALayer (rels := rels) (n - depth i.1))
      _ _
      hfree hfinite]
    change
      (∑ i : { i : Fin H.relationRank // depth i ≤ n },
          Module.finrank (ZMod H.realizesFiniteNontrivial.p)
            (H.pALayer (rels := rels) (n - depth i.1))) =
        ∑ i, if depth i ≤ n then
          Module.finrank (ZMod H.realizesFiniteNontrivial.p)
            (H.pALayer (rels := rels) (n - depth i))
        else
          0
    rw [← Finset.sum_filter]
    simpa [PPDatum.presentedAugmentationFinrank] using
      (Finset.sum_subtype
        (s := (Finset.univ.filter fun i : Fin H.relationRank => depth i ≤ n))
        (p := fun i : Fin H.relationRank => depth i ≤ n)
        (by intro i; simp)
        (fun i => Module.finrank (ZMod H.realizesFiniteNontrivial.p)
          (H.pALayer (rels := rels) (n - depth i)))).symm
  have htarget :
      Module.finrank (ZMod H.realizesFiniteNontrivial.p)
          (H.pres_highdegree_targetrelators (rels := rels) depth n) =
        H.presentedAugmentationFinrank hrels n +
          ∑ i, if depth i ≤ n then
            H.presentedAugmentationFinrank hrels (n - depth i)
          else
            0 := by
    dsimp [PPDatum.pres_highdegree_targetrelators]
    rw [Module.finrank_prod, hrelator]
    simp [PPDatum.presentedAugmentationFinrank]
  simpa [hsource, htarget] using hdim
/--
The augmentation-layer Hilbert sequence eventually vanishes for the finite
presented group algebra.

Mathematically this is nilpotence of the augmentation ideal in the group algebra
of a finite `p`-group.
-/
theorem PPDatum.presaug_layerfinrank_eventuallyzero
    (H : PPDatum)
    (_p_prime : Nat.Prime H.realizesFiniteNontrivial.p)
    [Finite H.realizesFiniteNontrivial.carrier]
    [Nontrivial H.realizesFiniteNontrivial.carrier]
    (_isPGroup : IsPGroup H.realizesFiniteNontrivial.p H.realizesFiniteNontrivial.carrier) :
  ∀ ⦃rels : Fin H.relationRank → FreeGroup (Fin H.generatorRank)⦄,
      (hrels :
        Nonempty (PresentedGroup (Set.range rels) ≃* H.realizesFiniteNontrivial.carrier)) →
      ∃ N : ℕ, ∀ n, N ≤ n → H.presentedAugmentationFinrank hrels n = 0 := by
  intro rels hrels
  exact H.presaug_layerfinrank_evenzeronilp
    _p_prime hrels
    (H.pres_aug_idealnilpotent _p_prime _isPGroup hrels)
/--
The bridge theorem follows formally from the coefficientwise Hilbert-series
witness: this lemma removes the analytic part from the remaining group-algebra
work.
-/
theorem PPDatum.minpres_hilbertseries_bridcoefwitn
    (H : PPDatum)
    (hcoeff :
      ∀ ⦃rels : Fin H.relationRank → FreeGroup (Fin H.generatorRank)⦄
        ⦃depth : Fin H.relationRank → ℕ⦄,
          Nonempty (PresentedGroup (Set.range rels) ≃* H.realizesFiniteNontrivial.carrier) →
          (∀ i, rels i ∈ H.relatorZassenhausFiltration (depth i)) →
          (∀ i, 2 ≤ depth i) →
          GShafar.CoefficientwiseHilbertWitness
            H.generatorRank H.relationRank depth) :
  ∀ ⦃rels : Fin H.relationRank → FreeGroup (Fin H.generatorRank)⦄
    ⦃depth : Fin H.relationRank → ℕ⦄,
      Nonempty (PresentedGroup (Set.range rels) ≃* H.realizesFiniteNontrivial.carrier) →
      (∀ i, rels i ∈ H.relatorZassenhausFiltration (depth i)) →
      (∀ i, 2 ≤ depth i) →
      ∀ t : ℝ, 0 < t → t < 1 →
        0 < GShafar.relatorExpression H.generatorRank H.relationRank depth t := by
  intro rels depth hrels hmem hdepth t ht0 _ht1
  rcases hcoeff hrels hmem hdepth with ⟨P, hPcoeff, hPzero, hprodcoeff⟩
  exact
    GShafar.coefficientwise_hilbert_inequality
      (d := H.generatorRank)
      (r := H.relationRank)
      depth hdepth hPcoeff hPzero hprodcoeff t ht0
end Submission
