import Towers.NumberTheory.Locals.FiniteFieldExample
import Towers.NumberTheory.Locals.UnramifiedResidueLift
import Towers.ClassField.NormCorrespondence.UnramifiedFrobenius
import Towers.ClassField.LocalBrauer.LocalField
import Towers.ClassField.LocalBrauer.UnramifiedAdjoin
import Mathlib.FieldTheory.SeparableClosure


/-!
# Chapter IV, Section 4: unramified extensions of each degree

For every positive integer `n`, the finite residue field of a nonarchimedean
local field has a chosen degree-`n` extension.  We lift the minimal
polynomial of a primitive element to the integer ring.  The resulting
adjoining-root algebra has rank `n`, is local, and is formally unramified.

The residue extension is Galois and cyclic, generated by arithmetic
Frobenius.  The following `UnramifiedExtensionGalois` module lifts this
structure to the fraction field.
-/

namespace Towers.CField.LBrauer

noncomputable section

open Polynomial
open scoped Valued

universe u

variable (K : Type u) [NontriviallyNormedField K] [IsUltrametricDist K]
  [ValuativeRel K] [IsNonarchimedeanLocalField K]
  [Valuation.Compatible (NormedField.valuation (K := K))]

local instance : IsDiscreteValuationRing 𝒪[K] :=
  discrete_valuation_ring K

local instance : IsFractionRing 𝒪[K] K :=
  (Valuation.integer.integers (ValuativeRel.valuation K)).isFractionRing

local instance : Finite 𝓀[K] := local_field_residue K

local instance : Fact (ringChar 𝓀[K]).Prime :=
  ⟨CharP.char_is_prime 𝓀[K] _⟩

include K in
/-- The chosen degree-`n` extension of the residue field of `K`. -/
abbrev localResidueExtension (n : ℕ) [NeZero n] :=
  FiniteField.Extension 𝓀[K] (ringChar 𝓀[K]) n

omit [IsUltrametricDist K]
  [Valuation.Compatible (NormedField.valuation (K := K))] in
/-- The chosen residue extension has degree `n`, cyclic Galois group, and
arithmetic Frobenius as a generator. -/
theorem residue_extension_structure (n : ℕ) [NeZero n] :
    Module.finrank 𝓀[K] (localResidueExtension (K := K) n) = n ∧
      IsGalois 𝓀[K] (localResidueExtension (K := K) n) ∧
      IsCyclic Gal(localResidueExtension (K := K) n / 𝓀[K]) ∧
      orderOf (FiniteField.Extension.frob 𝓀[K] (ringChar 𝓀[K]) n) = n ∧
        ∀ σ : Gal(localResidueExtension (K := K) n / 𝓀[K]),
          ∃ i < n,
            FiniteField.Extension.frob 𝓀[K] (ringChar 𝓀[K]) n ^ i = σ := by
  letI : Finite 𝓀[K] := local_field_residue K
  letI : Fact (ringChar 𝓀[K]).Prime := ⟨CharP.char_is_prime 𝓀[K] _⟩
  refine ⟨FiniteField.finrank_extension 𝓀[K] (ringChar 𝓀[K]) n,
    inferInstance, inferInstance, ?_, ?_⟩
  · letI := Fintype.ofFinite 𝓀[K]
    simpa [FiniteField.Extension.frob,
      FiniteField.finrank_extension 𝓀[K] (ringChar 𝓀[K]) n] using
      Towers.CField.NCorr.order_residue_frobenius
        𝓀[K] (localResidueExtension (K := K) n)
  · exact FiniteField.Extension.exists_frob_pow_eq
      𝓀[K] (ringChar 𝓀[K]) n

set_option maxHeartbeats 1000000 in
-- Extra heartbeats are needed for the large search space in this proof.
omit [IsUltrametricDist K]
  [Valuation.Compatible (NormedField.valuation (K := K))] in
/-- A degree-`n` finite residue extension lifts to a monic polynomial over
the integer ring whose adjoining-root algebra is local and unramified.

This is the integral algebra underlying the unramified extension used in
Proposition IV.4.3. -/
theorem unramified_integer_extension (n : ℕ) [NeZero n] :
    ∃ f : 𝒪[K][X],
      f.Monic ∧ f.natDegree = n ∧
        Irreducible (f.map (IsLocalRing.residue 𝒪[K])) ∧
        (f.map (IsLocalRing.residue 𝒪[K])).Separable ∧
        let U := AdjoinRoot f
        ∃ hfirr : Irreducible f,
          letI : IsDomain U := AdjoinRoot.isDomain_of_prime hfirr.prime
          Module.finrank 𝒪[K] U = n ∧
            ∃ hlocal : IsLocalRing U,
              letI := hlocal
              IsDiscreteValuationRing U ∧
                Algebra.FormallyUnramified 𝒪[K] U ∧
                Algebra.IsUnramifiedAt 𝒪[K] (IsLocalRing.maximalIdeal U) := by
  let k := 𝓀[K]
  let p := ringChar k
  letI : Finite k := local_field_residue K
  letI : Fact p.Prime := ⟨CharP.char_is_prime k _⟩
  let l := FiniteField.Extension k p n
  obtain ⟨a, ha⟩ := Field.exists_primitive_element k l
  let f₀ : k[X] := minpoly k a
  have hf₀monic : f₀.Monic := minpoly.monic (Algebra.IsIntegral.isIntegral a)
  have hf₀degree : f₀.natDegree = n := by
    rw [← FiniteField.finrank_extension k p n]
    exact (Field.primitive_element_iff_minpoly_natDegree_eq k a).mp ha
  have hf₀lift : f₀ ∈ Polynomial.lifts (IsLocalRing.residue 𝒪[K]) :=
    Polynomial.map_surjective (IsLocalRing.residue 𝒪[K])
      Ideal.Quotient.mk_surjective f₀
  obtain ⟨f, hfmap, hfdegree, hfmonic⟩ :=
    Polynomial.lifts_and_natDegree_eq_and_monic hf₀lift hf₀monic
  have hfred : Irreducible (f.map (IsLocalRing.residue 𝒪[K])) := by
    rw [hfmap]
    exact minpoly.irreducible (Algebra.IsIntegral.isIntegral a)
  have hfsep : (f.map (IsLocalRing.residue 𝒪[K])).Separable := by
    rw [hfmap]
    exact Algebra.IsSeparable.isSeparable k a
  have hdegree : f.natDegree = n := hfdegree.trans hf₀degree
  let U := AdjoinRoot f
  let hlocal : IsLocalRing U :=
    adjoin_ring_irreducible
      𝒪[K] f hfmonic hfred
  letI : IsLocalRing U := hlocal
  have hfirr : Irreducible f :=
    hfmonic.irreducible_of_irreducible_map (IsLocalRing.residue 𝒪[K]) f hfred
  letI : IsDomain U := AdjoinRoot.isDomain_of_prime hfirr.prime
  have hfdegree_ne : f.degree ≠ 0 := by
    rw [degree_eq_natDegree hfirr.ne_zero, hdegree]
    exact_mod_cast (NeZero.ne n)
  have hOf : Function.Injective (algebraMap 𝒪[K] U) := by
    simpa [AdjoinRoot.algebraMap_eq] using
      AdjoinRoot.of.injective_of_degree_ne_zero hfdegree_ne
  letI : FaithfulSMul 𝒪[K] U :=
    (faithfulSMul_iff_algebraMap_injective 𝒪[K] U).2 hOf
  letI : Module.Finite 𝒪[K] U := hfmonic.finite_adjoinRoot
  letI : Algebra.IsIntegral 𝒪[K] U := Algebra.IsIntegral.of_finite 𝒪[K] U
  letI : Algebra.FormallyUnramified 𝒪[K] U :=
    formally_irreducible_separable
      𝒪[K] f hfmonic hfred hfsep
  have hfinrank : Module.finrank 𝒪[K] U = n := by
    exact (AdjoinRoot.powerBasis' hfmonic).finrank.trans hdegree
  letI : IsDedekindDomain U := isDedekindDomain.of_formallyUnramified 𝒪[K] U
  have hnfield : ¬ IsField U := by
    intro hU
    exact IsDiscreteValuationRing.not_isField 𝒪[K]
      (isField_of_isIntegral_of_isField
        (FaithfulSMul.algebraMap_injective 𝒪[K] U) hU)
  have hdvr : IsDiscreteValuationRing U :=
    ((IsDiscreteValuationRing.TFAE U hnfield).out 2 0).mp
      (inferInstance : IsDedekindDomain U)
  refine ⟨f, hfmonic, hdegree, hfred, hfsep, hfirr, hfinrank, hlocal, hdvr,
    inferInstance, ?_⟩
  change Algebra.FormallyUnramified 𝒪[K]
    (Localization.AtPrime (IsLocalRing.maximalIdeal U))
  infer_instance

end

end Towers.CField.LBrauer
