import Towers.Group.Petresco.Coefficients
import Towers.Group.Edmonton.HallEmbeddings

/-!
# Certified factors for Edmonton collection

A collected factor records a formal commutator, its integral exponent, and
the free-group word which conjugates it.  Admissibility is indexed by the
exact bidegree of the formal commutator.

The first collection target is a normal closure rather than an ordered
factorization.  This absorbs conjugates, inverses, products, and additions of
admissible exponents without requiring a canonical trace order.
-/

namespace Towers
namespace Edmonton

universe u

/-- A collected mixed commutator factor with an admissible exponent and its
free-group conjugator. -/
structure CFactor (M N : ℕ) where
  word : FormalCommutator Bool
  exponent : ℤ
  conjugator : FreeGroup Bool
  mixed : 0 < leftDegree word ∧ 0 < rightDegree word
  admissible :
    exponent ∈
      admissibleCoefficients M N (leftDegree word) (rightDegree word)

namespace CFactor

/-- The divisibility certificate carried by an admissible factor exponent. -/
lemma exponent_divisibility
    {M N : ℕ} (factor : CFactor M N) :
    (M : ℤ) ∣ (leftDegree factor.word : ℤ) * factor.exponent ∧
      (N : ℤ) ∣ (rightDegree factor.word : ℤ) * factor.exponent :=
  admissibleCoefficient_divisibility factor.admissible

end CFactor

/-- Evaluate the two free generators at `x` and `y`. -/
def twoGeneratorFree
    {G : Type u} [Group G] (x y : G) : FreeGroup Bool →* G :=
  FreeGroup.lift fun
    | false => x
    | true => y

@[simp]
lemma two_generator_false
    {G : Type u} [Group G] (x y : G) :
    twoGeneratorFree x y (FreeGroup.of false) = x := by
  simp [twoGeneratorFree]

@[simp]
lemma two_generator_true
    {G : Type u} [Group G] (x y : G) :
    twoGeneratorFree x y (FreeGroup.of true) = y := by
  simp [twoGeneratorFree]

/-- Evaluate a two-generator formal commutator at `x` and `y`. -/
def generatorFormalCommutator
    {G : Type u} [Group G] (x y : G)
    (word : FormalCommutator Bool) : G :=
  formalGroupCommutator
    (fun
      | false => x
      | true => y)
    word

@[simp]
lemma generator_formal_false
    {G : Type u} [Group G] (x y : G) :
    generatorFormalCommutator x y (FreeMagma.of false) = x :=
  rfl

@[simp]
lemma generator_formal_true
    {G : Type u} [Group G] (x y : G) :
    generatorFormalCommutator x y (FreeMagma.of true) = y :=
  rfl

@[simp]
lemma generator_formal_bracket
    {G : Type u} [Group G] (x y : G)
    (a b : FormalCommutator Bool) :
    generatorFormalCommutator x y (formalBracket a b) =
      hallCommutator
        (generatorFormalCommutator x y a)
        (generatorFormalCommutator x y b) :=
  rfl

/-- Edmonton's adjacent collection identity specialized to two generators. -/
lemma generator_formal_swap
    {G : Type u} [Group G] (x y : G)
    (a b : FormalCommutator Bool) :
    generatorFormalCommutator x y a *
        generatorFormalCommutator x y b =
      generatorFormalCommutator x y b *
          generatorFormalCommutator x y a *
        generatorFormalCommutator x y (formalBracket a b) :=
  eval_formal_swap
    (fun
      | false => x
      | true => y)
    a b

/-- Evaluate a certified factor, including its recorded conjugator. -/
def CFactor.eval
    {G : Type u} [Group G] {M N : ℕ}
    (x y : G) (factor : CFactor M N) : G :=
  twoGeneratorFree x y factor.conjugator *
      generatorFormalCommutator x y factor.word ^ factor.exponent *
    (twoGeneratorFree x y factor.conjugator)⁻¹

/-- The unconjugated mixed admissible powers at `x` and `y`. -/
def admissibleHallGenerators
    {G : Type u} [Group G] (M N : ℕ) (x y : G) : Set G :=
  { z |
    ∃ word : FormalCommutator Bool, ∃ exponent : ℤ,
      0 < leftDegree word ∧
        0 < rightDegree word ∧
          exponent ∈
            admissibleCoefficients M N
              (leftDegree word) (rightDegree word) ∧
            generatorFormalCommutator x y word ^ exponent = z }

/-- The normal subgroup generated by all mixed formal commutators raised to
admissible exponents. -/
def admissibleHallSubgroup
    {G : Type u} [Group G] (M N : ℕ) (x y : G) : Subgroup G :=
  Subgroup.normalClosure (admissibleHallGenerators M N x y)

instance admissible_subgroup_normal
    {G : Type u} [Group G] (M N : ℕ) (x y : G) :
    (admissibleHallSubgroup M N x y).Normal :=
  Subgroup.normalClosure_normal

/-- Every mixed admissible power is one of the normal generators. -/
lemma admissible_hall_generator
    {G : Type u} [Group G] {M N : ℕ} {x y : G}
    {word : FormalCommutator Bool} {exponent : ℤ}
    (hmixed : 0 < leftDegree word ∧ 0 < rightDegree word)
    (hadmissible :
      exponent ∈
        admissibleCoefficients M N
          (leftDegree word) (rightDegree word)) :
    generatorFormalCommutator x y word ^ exponent ∈
      admissibleHallSubgroup M N x y :=
  Subgroup.subset_normalClosure
    ⟨word, exponent, hmixed.1, hmixed.2, hadmissible, rfl⟩

/-- The unconjugated power underlying a certified factor lies in the
admissible Hall subgroup. -/
lemma CFactor.core_memadmissible_hallsubgroup
    {G : Type u} [Group G] {M N : ℕ} {x y : G}
    (factor : CFactor M N) :
    generatorFormalCommutator x y factor.word ^ factor.exponent ∈
      admissibleHallSubgroup M N x y :=
  admissible_hall_generator factor.mixed factor.admissible

/-- Every certified factor evaluates into the admissible Hall subgroup.  The
stored conjugator is absorbed by normality. -/
lemma CFactor.eval_memadmissible_hallsubgroup
    {G : Type u} [Group G] {M N : ℕ} {x y : G}
    (factor : CFactor M N) :
    factor.eval x y ∈ admissibleHallSubgroup M N x y := by
  exact
    (inferInstance : (admissibleHallSubgroup M N x y).Normal).conj_mem
      _ factor.core_memadmissible_hallsubgroup
      (twoGeneratorFree x y factor.conjugator)

/-- Arbitrary conjugates of certified factor values remain in the target
normal subgroup. -/
lemma CFactor.conjeval_memadmissible_hallsubgroup
    {G : Type u} [Group G] {M N : ℕ} {x y g : G}
    (factor : CFactor M N) :
    g * factor.eval x y * g⁻¹ ∈ admissibleHallSubgroup M N x y :=
  (inferInstance : (admissibleHallSubgroup M N x y).Normal).conj_mem
    _ factor.eval_memadmissible_hallsubgroup g

/-- Inverses of certified factor values remain in the admissible Hall
subgroup. -/
lemma CFactor.inveval_memadmissible_hallsubgroup
    {G : Type u} [Group G] {M N : ℕ} {x y : G}
    (factor : CFactor M N) :
    (factor.eval x y)⁻¹ ∈ admissibleHallSubgroup M N x y :=
  (admissibleHallSubgroup M N x y).inv_mem
    factor.eval_memadmissible_hallsubgroup

/-- Products of evaluated certified factors remain in the admissible Hall
subgroup, independently of their order. -/
lemma certified_admissible_subgroup
    {G : Type u} [Group G] {M N : ℕ} {x y : G}
    (factors : List (CFactor M N)) :
    (factors.map (CFactor.eval x y)).prod ∈
      admissibleHallSubgroup M N x y := by
  induction factors with
  | nil =>
      simp
  | cons factor factors ih =>
      simpa using
        (admissibleHallSubgroup M N x y).mul_mem
          factor.eval_memadmissible_hallsubgroup ih

/-- The sum of two admissible exponents for the same mixed formal word is
again an admissible exponent and hence gives a generator of the subgroup. -/
lemma admissible_generator_exponents
    {G : Type u} [Group G] {M N : ℕ} {x y : G}
    {word : FormalCommutator Bool} {a b : ℤ}
    (hmixed : 0 < leftDegree word ∧ 0 < rightDegree word)
    (ha :
      a ∈ admissibleCoefficients M N
        (leftDegree word) (rightDegree word))
    (hb :
      b ∈ admissibleCoefficients M N
        (leftDegree word) (rightDegree word)) :
    generatorFormalCommutator x y word ^ (a + b) ∈
      admissibleHallSubgroup M N x y :=
  admissible_hall_generator hmixed
    ((admissibleCoefficients M N
      (leftDegree word) (rightDegree word)).add_mem ha hb)

end Edmonton
end Towers
