import Mathlib
import Towers.Group.DenseGenerators.RestrictedBurnside


open scoped Topology Pointwise

noncomputable section

namespace Towers

universe u
universe v w z

/-- A finitely generated nilpotent torsion group is finite.

This is the abstract group-theoretic finiteness input used below.  The proof is by induction on
the nilpotency class, quotienting by the center.  The quotient is finite by induction, so the center
has finite index and is finitely generated by Schreier; the center is abelian and torsion, hence
finite by the finitely generated abelian torsion theorem. -/
lemma fg_nilpotent_torsion
    (G : Type u) [Group G] [Group.IsNilpotent G]
    [Group.FG G] (hT : Monoid.IsTorsion G) :
    Finite G := by
  classical
  let P : (G : Type u) → [Group G] → [Group.IsNilpotent G] → Prop :=
    fun (G : Type u) [Group G] [Group.IsNilpotent G] =>
      Group.FG G → Monoid.IsTorsion G → Finite G
  exact
    Group.nilpotent_center_quotient_ind (P := P) G
      (hbase := by
        intro G _ _hsub hfg hT
        exact Finite.of_injective (fun _ : G => PUnit.unit)
          (fun x y _ => Subsingleton.elim x y))
      (hstep := by
        intro G _ _hNil ih hfg hT
        haveI : Group.FG G := hfg
        haveI : Group.FG (G ⧸ Subgroup.center G) := inferInstance
        have hTquot : Monoid.IsTorsion (G ⧸ Subgroup.center G) :=
          IsTorsion.of_surjective
            (QuotientGroup.mk'_surjective (Subgroup.center G)) hT
        haveI : Finite (G ⧸ Subgroup.center G) :=
          ih inferInstance hTquot
        haveI : (Subgroup.center G).FiniteIndex :=
          Subgroup.finiteIndex_of_finite_quotient
        haveI : Group.FG (Subgroup.center G) := inferInstance
        letI : CommGroup (Subgroup.center G) :=
          { (inferInstance : Group (Subgroup.center G)) with mul_comm := mul_comm' }
        have hTcenter : Monoid.IsTorsion (Subgroup.center G) :=
          IsTorsion.subgroup hT (Subgroup.center G)
        haveI : Finite (Subgroup.center G) :=
          CommGroup.finite_of_fg_torsion (Subgroup.center G) hTcenter
        exact Finite.of_subgroup_quotient (Subgroup.center G))
      inferInstance hT

end Towers
