import Mathlib.GroupTheory.Complement
import Mathlib.GroupTheory.Exponent
import Mathlib.GroupTheory.FiniteAbelian.Duality
import Mathlib.FieldTheory.Galois.Abelian
import Mathlib.FieldTheory.Galois.Basic
import Mathlib.RingTheory.RootsOfUnity.AlgebraicallyClosed

/-!
# Class Field Theory, Chapter I, Lemma 4.11: the finite-group splitting

The field-theoretic statement of Lemma 4.11 uses the following elementary
fact.  If a finite abelian group contains an element whose order is the
exponent of the group, then the cyclic subgroup generated by that element is
a direct factor.

The proof extends a faithful character of the cyclic subgroup to the whole
group using finite-abelian duality.  Codrestricting the extended character to
the roots of unity gives a retraction onto the cyclic subgroup; its kernel is
the required complementary subgroup.
-/

namespace Towers.CField.Ramification

open Subgroup

/-- The kernel of a retraction onto a subgroup is an internal complement to
that subgroup. -/
theorem complement_ker_retraction {G : Type*} [Group G]
    (C : Subgroup G) (r : G →* C)
    (hr : r.comp C.subtype = MonoidHom.id C) :
    IsComplement' C r.ker := by
  apply isComplement'_of_disjoint_and_mul_eq_univ
  · rw [Subgroup.disjoint_def]
    intro x hxC hxker
    have hfix : r x = (⟨x, hxC⟩ : C) := by
      change (r.comp C.subtype) ⟨x, hxC⟩ = ⟨x, hxC⟩
      rw [hr]
      rfl
    have hone : (⟨x, hxC⟩ : C) = 1 :=
      hfix.symm.trans (MonoidHom.mem_ker.mp hxker)
    exact congrArg Subtype.val hone
  · apply Set.eq_univ_iff_forall.mpr
    intro g
    let c : C := r g
    let h : G := (c : G)⁻¹ * g
    have hfix : r (c : G) = c := by
      change (r.comp C.subtype) c = c
      rw [hr]
      rfl
    have hh : h ∈ r.ker := by
      rw [MonoidHom.mem_ker]
      dsimp [h]
      rw [map_mul, map_inv, hfix]
      change c⁻¹ * c = 1
      simp
    exact ⟨c, c.property, h, hh, by simp [h]⟩

/-- In a commutative group, an internal complement gives the displayed
direct-product decomposition by multiplication. -/
noncomputable def IsComplement'.prodMulEquiv
    {G : Type*} [CommGroup G] {C H : Subgroup G}
    (h : IsComplement' C H) : C × H ≃* G :=
  MulEquiv.ofBijective (C.subtype.coprod H.subtype) h

@[simp]
theorem IsComplement'.prodMul_apply
    {G : Type*} [CommGroup G] {C H : Subgroup G}
    (h : IsComplement' C H) (x : C × H) :
    IsComplement'.prodMulEquiv h x = (x.1 : G) * (x.2 : G) :=
  rfl

/-- The exponent calculation at the start of Lemma 4.11.  If restriction to
two subextensions is jointly injective and both restrictions are killed by
`m`, then the compositum Galois group is killed by `m`; an element whose
second restriction has order `m` forces equality of exponents. -/
theorem exponent_image_order
    {G H I : Type*} [Monoid G] [Monoid H] [Monoid I] [Finite G]
    (f : G →* H) (g : G →* I)
    (hinj : Function.Injective (f.prod g)) (m : ℕ)
    (hf : ∀ x : G, f x ^ m = 1) (hg : ∀ x : G, g x ^ m = 1)
    (tau : G) (htau : orderOf (g tau) = m) :
    Monoid.exponent G = m := by
  apply Nat.dvd_antisymm
  · apply Monoid.exponent_dvd_of_forall_pow_eq_one
    intro x
    apply hinj
    apply Prod.ext
    · simp [map_pow, hf x]
    · simp [map_pow, hg x]
  · rw [← htau]
    exact (orderOf_map_dvd g tau).trans (Monoid.order_dvd_exponent tau)

/-- If the image of an element already has order equal to the exponent of
the source, then the element itself has that full order. -/
theorem order_exponent
    {G H : Type*} [Monoid G] [Monoid H]
    (f : G →* H) (tau : G)
    (h : orderOf (f tau) = Monoid.exponent G) :
    orderOf tau = Monoid.exponent G := by
  apply Nat.dvd_antisymm
  · exact Monoid.order_dvd_exponent tau
  · rw [← h]
    exact orderOf_map_dvd f tau

/-- A lift of a generator whose order is the exponent gives the precise
kernel complement used in Lemma 4.11.  In the application, `f` is restriction
to the unramified degree-`m` extension and `c` is Frobenius. -/
theorem lift_complement_zpowers
    {G C : Type*} [Group G] [Finite G] [Group C]
    (f : G →* C) (hf : Function.Surjective f) (c : C)
    (hc : Subgroup.zpowers c = ⊤)
    (hexp : Monoid.exponent G = orderOf c) :
    ∃ tau : G, f tau = c ∧
      IsComplement' (Subgroup.zpowers tau) f.ker := by
  obtain ⟨tau, htau⟩ := hf c
  have htauOrder : orderOf tau = Monoid.exponent G :=
    order_exponent f tau (by simpa [htau] using hexp.symm)
  let T := Subgroup.zpowers tau
  let t : T := ⟨tau, Subgroup.mem_zpowers tau⟩
  have htGenerator : ∀ x : T, x ∈ Subgroup.zpowers t := by
    rintro ⟨x, hx⟩
    obtain ⟨k, hk⟩ := Subgroup.mem_zpowers_iff.mp hx
    apply Subgroup.mem_zpowers_iff.mpr
    exact ⟨k, Subtype.ext hk⟩
  have hcGenerator : ∀ x : C, x ∈ Subgroup.zpowers c := by
    intro x
    rw [hc]
    trivial
  have htOrder : orderOf t = orderOf c := by
    calc
      orderOf t = orderOf (t : G) := (Subgroup.orderOf_coe t).symm
      _ = orderOf tau := by rfl
      _ = orderOf c := htauOrder.trans hexp
  let e : T ≃* C :=
    mulEquivOfOrderOfEq htGenerator hcGenerator htOrder
  let r : G →* T := e.symm.toMonoidHom.comp f
  have hr : r.comp T.subtype = MonoidHom.id T := by
    apply (MonoidHom.eq_iff_eq_on_generator htGenerator _ _).mpr
    change e.symm (f tau) = t
    rw [htau]
    exact mulEquivOfOrderOfEq_symm_apply_gen htGenerator hcGenerator htOrder
  have hker : r.ker = f.ker := by
    ext x
    simp [r]
  refine ⟨tau, htau, ?_⟩
  rw [← hker]
  exact complement_ker_retraction T r hr

/-- The Galois-correspondence part of the compositum equality in Lemma 4.11:
fixed fields of complementary subgroups generate the full extension. -/
theorem fixed_sup_complement
    {K E : Type*} [Field K] [Field E] [Algebra K E]
    [FiniteDimensional K E] [IsGalois K E]
    {C H : Subgroup Gal(E/K)} (h : IsComplement' C H) :
    IntermediateField.fixedField C ⊔
        IntermediateField.fixedField H = ⊤ := by
  have hfix :
      (IntermediateField.fixedField C ⊔
          IntermediateField.fixedField H).fixingSubgroup =
        (⊤ : IntermediateField K E).fixingSubgroup := by
    rw [IntermediateField.fixingSubgroup_sup,
      IntermediateField.fixingSubgroup_fixedField,
      IntermediateField.fixingSubgroup_fixedField,
      IntermediateField.fixingSubgroup_top]
    exact h.disjoint.eq_bot
  calc
    IntermediateField.fixedField C ⊔ IntermediateField.fixedField H =
        IntermediateField.fixedField
          ((IntermediateField.fixedField C ⊔
            IntermediateField.fixedField H).fixingSubgroup) :=
      (IsGalois.fixedField_fixingSubgroup _).symm
    _ = IntermediateField.fixedField
          ((⊤ : IntermediateField K E).fixingSubgroup) :=
      congrArg IntermediateField.fixedField hfix
    _ = ⊤ := IsGalois.fixedField_fixingSubgroup _

/-- The finite-Galois field wrapper for the splitting step in Lemma 4.11.
If an automorphism of a normal intermediate field generates its Galois group
and has order equal to the exponent upstairs, it has a lift whose fixed field
and the intermediate field generate the whole extension. -/
theorem zpowers_sup_top
    {K E : Type*} [Field K] [Field E] [Algebra K E]
    [FiniteDimensional K E] [IsAbelianGalois K E]
    (M : IntermediateField K E) [Normal K M]
    (c : Gal(M/K)) (hc : Subgroup.zpowers c = ⊤)
    (hexp : Monoid.exponent Gal(E/K) = orderOf c) :
    ∃ tau : Gal(E/K), AlgEquiv.restrictNormalHom M tau = c ∧
      IntermediateField.fixedField (Subgroup.zpowers tau) ⊔ M = ⊤ := by
  let f : Gal(E/K) →* Gal(M/K) := AlgEquiv.restrictNormalHom M
  have hf : Function.Surjective f := by
    change Function.Surjective (AlgEquiv.restrictNormalHom M)
    exact AlgEquiv.restrictNormalHom_surjective (F := K) (K₁ := M) (E := E)
  obtain ⟨tau, htau, hcomplement⟩ :=
    lift_complement_zpowers f hf c hc hexp
  have hfixed : IntermediateField.fixedField f.ker = M := by
    rw [IntermediateField.restrictNormalHom_ker]
    exact IsGalois.fixedField_fixingSubgroup M
  refine ⟨tau, htau, ?_⟩
  rw [← hfixed]
  exact fixed_sup_complement hcomplement

/-- The finite-abelian group-theoretic core of Lemma 4.11: an element whose
order equals the exponent of the group generates a direct factor. -/
theorem complement_zpowers_exponent
    (G : Type*) [CommGroup G] [Finite G] (tau : G)
    (htau : orderOf tau = Monoid.exponent G) :
    ∃ H : Subgroup G, IsComplement' (Subgroup.zpowers tau) H := by
  let m := Monoid.exponent G
  let C := Subgroup.zpowers tau
  let t : C := ⟨tau, Subgroup.mem_zpowers tau⟩
  let M := AlgebraicClosure ℚ
  obtain ⟨zeta, hzeta⟩ := HasEnoughRootsOfUnity.exists_primitiveRoot M m
  let xi : rootsOfUnity m M := hzeta.toRootsOfUnity
  have ht_generator : ∀ x : C, x ∈ Subgroup.zpowers t := by
    rintro ⟨x, hx⟩
    obtain ⟨k, hk⟩ := Subgroup.mem_zpowers_iff.mp hx
    apply Subgroup.mem_zpowers_iff.mpr
    exact ⟨k, Subtype.ext hk⟩
  have hxi_generator : ∀ x : rootsOfUnity m M, x ∈ Subgroup.zpowers xi := by
    intro x
    have hzeta_units : IsPrimitiveRoot xi.val m := by
      apply IsPrimitiveRoot.coe_units_iff.mp
      simpa [xi] using hzeta
    have hx : (x : Mˣ) ∈ Subgroup.zpowers xi.val := by
      rw [hzeta_units.zpowers_eq]
      exact x.property
    obtain ⟨k, hk⟩ := Subgroup.mem_zpowers_iff.mp hx
    apply Subgroup.mem_zpowers_iff.mpr
    exact ⟨k, Subtype.ext hk⟩
  have ht_order : orderOf t = m := by
    simpa [t, m] using htau
  have hxi_order : orderOf xi = m := by
    refine Eq.trans ?_ hzeta.eq_orderOf.symm
    rw [← hzeta.val_toRootsOfUnity_coe, orderOf_units, Subgroup.orderOf_coe]
  let e : C ≃* rootsOfUnity m M :=
    mulEquivOfOrderOfEq ht_generator hxi_generator (ht_order.trans hxi_order.symm)
  let psi : C →* Mˣ := (rootsOfUnity m M).subtype.comp e.toMonoidHom
  obtain ⟨phi, hphi⟩ := (MonoidHom.restrict_surjective (M := M) C) psi
  have hphi_roots (g : G) : phi g ∈ rootsOfUnity m M := by
    rw [mem_rootsOfUnity]
    calc
      phi g ^ m = phi (g ^ m) := (map_pow phi g m).symm
      _ = phi 1 := congrArg phi (by simpa [m] using Monoid.pow_exponent_eq_one g)
      _ = 1 := phi.map_one
  let phiRoots : G →* rootsOfUnity m M :=
    phi.codRestrict (rootsOfUnity m M) hphi_roots
  let r : G →* C := e.symm.toMonoidHom.comp phiRoots
  have hr : r.comp C.subtype = MonoidHom.id C := by
    apply MonoidHom.ext
    intro c
    change e.symm (phiRoots (c : G)) = c
    apply e.injective
    rw [e.apply_symm_apply]
    apply Subtype.ext
    have hc := DFunLike.congr_fun hphi c
    simpa [phiRoots, psi] using hc
  exact ⟨r.ker, complement_ker_retraction C r hr⟩

/-- Milne's direct-product conclusion in Lemma 4.11: under the exponent
hypothesis, `G` is multiplicatively equivalent to `⟨tau⟩ × H`. -/
theorem zpowers_order_exponent
    (G : Type*) [CommGroup G] [Finite G] (tau : G)
    (htau : orderOf tau = Monoid.exponent G) :
    ∃ H : Subgroup G, Nonempty (Subgroup.zpowers tau × H ≃* G) := by
  obtain ⟨H, hH⟩ :=
    complement_zpowers_exponent G tau htau
  exact ⟨H, ⟨IsComplement'.prodMulEquiv hH⟩⟩

end Towers.CField.Ramification
