import Mathlib.FieldTheory.Galois.NormalBasis
import Mathlib.LinearAlgebra.Basis.Submodule
import Mathlib.RepresentationTheory.Homological.GroupCohomology.Functoriality
import Mathlib.RepresentationTheory.Homological.GroupCohomology.Shapiro
import Mathlib.RingTheory.DedekindDomain.IntegralClosure
import Mathlib.Topology.Algebra.Valued.ValuationTopology
import Towers.NumberTheory.Integers.IntegralCoordinates

open Towers.NumberTheory.Milne

/-!
# Milne, Class Field Theory, Lemma III.2.3: the regular-lattice core

Milne chooses a scaled normal basis and lets `V` be its integral span.  The
last step of his proof is that `V` is the regular module over the integer ring
of the base field, hence has zero positive-degree group cohomology.

This file clears a common denominator, constructs the integral scaled
normal-basis lattice, proves Galois stability, identifies its representation
with the regular representation, proves openness from integrality of the
valuation integers, and deduces positive-degree cohomology vanishing.
-/

namespace Towers.CField.LClass

open CategoryTheory
open scoped Pointwise

universe u

section IntegralNormalBasis

variable (A K L : Type u) [CommRing A] [IsDomain A]
variable [Field K] [Field L] [Algebra A K] [IsFractionRing A K]
variable [Algebra K L] [Algebra A L] [IsScalarTower A K L]
variable [FiniteDimensional K L] [IsGalois K L]

/-- A normal basis of a finite Galois extension has a common nonzero
denominator over the base domain.  After scaling by it, every normal-basis
vector is integral.  This formalizes the denominator-clearing step in the
proof of Lemma III.2.3. -/
theorem integral_multiple_basis :
    ∃ d ≠ (0 : A), ∀ g : Gal(L/K),
      IsIntegral A (d • IsGalois.normalBasis K L g) := by
  classical
  let b := IsGalois.normalBasis K L
  obtain ⟨d, hd, hint⟩ :=
    exists_integral_multiples A K (Finset.univ.image b)
  refine ⟨d, hd, fun g ↦ hint (b g) ?_⟩
  exact Finset.mem_image.mpr ⟨g, Finset.mem_univ g, rfl⟩

/-- The normal basis scaled by a nonzero element of the base domain remains a
basis over the fraction field. -/
noncomputable def scaledNormalBasis (d : A) (hd : d ≠ 0) :
    Module.Basis Gal(L/K) K L :=
  let dK : Kˣ := Units.mk0 (algebraMap A K d)
    ((map_ne_zero_iff (algebraMap A K)
      (FaithfulSMul.algebraMap_injective A K)).2 hd)
  dK • IsGalois.normalBasis K L

omit [IsDomain A] in
@[simp]
theorem scaled_normal_basis (d : A) (hd : d ≠ 0) (g : Gal(L/K)) :
    scaledNormalBasis A K L d hd g = d • IsGalois.normalBasis K L g := by
  change algebraMap A K d • IsGalois.normalBasis K L g = _
  exact (IsScalarTower.algebraMap_smul (A := K) d
    (IsGalois.normalBasis K L g : L))

/-- The `A`-lattice generated by a scaled normal basis. -/
noncomputable def integralNormalSpan (d : A) (hd : d ≠ 0) :
    Submodule A L :=
  Submodule.span A (Set.range (scaledNormalBasis A K L d hd))

/-- The scaled normal basis is an `A`-basis of the lattice that it generates. -/
noncomputable def integralBasisSpan (d : A) (hd : d ≠ 0) :
    Module.Basis Gal(L/K) A (integralNormalSpan A K L d hd) :=
  (scaledNormalBasis A K L d hd).restrictScalars A

@[simp]
theorem integral_basis_span (d : A) (hd : d ≠ 0)
    (g : Gal(L/K)) :
    ((integralBasisSpan A K L d hd g :
      integralNormalSpan A K L d hd) : L) =
      d • IsGalois.normalBasis K L g := by
  change (((scaledNormalBasis A K L d hd).restrictScalars A g :
    integralNormalSpan A K L d hd) : L) = _
  simpa only [Module.Basis.restrictScalars_apply] using
    scaled_normal_basis A K L d hd g

omit [IsDomain A] in
/-- If the scaled normal-basis vectors are integral, their entire lattice is
contained in the integral closure. -/
theorem integral_basis_closure
    (d : A) (hd : d ≠ 0)
    (hint : ∀ g : Gal(L/K), IsIntegral A (d • IsGalois.normalBasis K L g)) :
    integralNormalSpan A K L d hd ≤
      Subalgebra.toSubmodule (integralClosure A L) := by
  rw [integralNormalSpan, Submodule.span_le]
  rintro _ ⟨g, rfl⟩
  rw [scaled_normal_basis]
  exact (mem_integralClosure_iff A L).2 (hint g)

/-- A scaled normal-basis lattice lying inside the integral closure always
exists. -/
theorem integral_normal_span :
    ∃ (d : A) (hd : d ≠ 0),
      integralNormalSpan A K L d hd ≤
        Subalgebra.toSubmodule (integralClosure A L) := by
  obtain ⟨d, hd, hint⟩ := integral_multiple_basis A K L
  exact ⟨d, hd, integral_basis_closure A K L d hd hint⟩

/-- The integral closure is commensurable with the lattice generated by an
integral scaled normal basis: a nonzero scalar from the base ring sends every
integral element into that lattice.  This is the algebraic input in Milne's
argument that the lattice is open. -/
theorem nonzero_smul_span
    [IsIntegrallyClosed A]
    (d : A) (hd : d ≠ 0)
    (hint : ∀ g : Gal(L/K), IsIntegral A (d • IsGalois.normalBasis K L g)) :
    ∃ a ≠ (0 : A), ∀ z : L, z ∈ integralClosure A L →
      a • z ∈ integralNormalSpan A K L d hd := by
  classical
  let b := scaledNormalBasis A K L d hd
  have hb : ∀ i, IsIntegral A (b i) := by
    intro i
    simpa only [b, scaled_normal_basis] using hint i
  obtain ⟨a, ha⟩ :=
    IsIntegrallyClosed.isIntegral_iff.mp (Algebra.discr_isIntegral K hb)
  have ha0 : a ≠ 0 := by
    intro hzero
    have hdisc : Algebra.discr K b = 0 := by
      rw [← ha]
      simp [hzero]
    exact Algebra.discr_not_zero_of_basis K b hdisc
  refine ⟨a, ha0, fun z hz ↦ ?_⟩
  have hzspan :=
    (inv_discr_smul
      A K L b hb).2 hz
  refine Submodule.span_induction
    (s := Set.range fun i ↦ (Algebra.discr K b)⁻¹ • b i)
    (p := fun x _ ↦ a • x ∈ integralNormalSpan A K L d hd)
    ?_ ?_ ?_ ?_ hzspan
  · rintro x ⟨i, rfl⟩
    rw [← IsScalarTower.algebraMap_smul (A := K), smul_smul, ha,
      mul_inv_cancel₀ (Algebra.discr_not_zero_of_basis K b), one_smul]
    exact Submodule.subset_span (Set.mem_range_self i)
  · simpa only [smul_zero] using
      (integralNormalSpan A K L d hd).zero_mem
  · intro x y hx hy ihx ihy
    simpa only [smul_add] using
      (integralNormalSpan A K L d hd).add_mem ihx ihy
  · intro r x hx ihx
    simpa only [smul_smul, mul_comm r a] using
      (integralNormalSpan A K L d hd).smul_mem r ihx

omit [IsDomain A] in
/-- The Galois group permutes the scaled normal-basis vectors by left
multiplication. -/
theorem gal_scaled_basis (d : A) (hd : d ≠ 0)
    (g h : Gal(L/K)) :
    g • scaledNormalBasis A K L d hd h =
      scaledNormalBasis A K L d hd (g * h) := by
  rw [scaled_normal_basis, scaled_normal_basis]
  change g (d • IsGalois.normalBasis K L h) =
    d • IsGalois.normalBasis K L (g * h)
  calc
    g (d • IsGalois.normalBasis K L h) =
        g ((algebraMap A K d) • IsGalois.normalBasis K L h) := by
          rw [IsScalarTower.algebraMap_smul (A := K)]
    _ = (algebraMap A K d) • g (IsGalois.normalBasis K L h) := by
      rw [map_smul]
    _ = (algebraMap A K d) • IsGalois.normalBasis K L (g * h) := by
      congr 1
      rw [show IsGalois.normalBasis K L (g * h) =
          (g * h) (IsGalois.normalBasis K L 1) from
            IsGalois.normalBasis_apply (g * h),
        show IsGalois.normalBasis K L h =
          h (IsGalois.normalBasis K L 1) from IsGalois.normalBasis_apply h]
      rfl
    _ = d • IsGalois.normalBasis K L (g * h) :=
      IsScalarTower.algebraMap_smul (A := K) d _

omit [IsDomain A] in
/-- The scaled normal-basis lattice is stable under the Galois action. -/
theorem integral_basis_stable (d : A) (hd : d ≠ 0)
    (g : Gal(L/K)) :
    integralNormalSpan A K L d hd ≤
      (integralNormalSpan A K L d hd).comap
        ((Rep.ofDistribMulAction A Gal(L/K) L).ρ g) := by
  rw [integralNormalSpan, Submodule.span_le]
  rintro _ ⟨h, rfl⟩
  change g • scaledNormalBasis A K L d hd h ∈
    integralNormalSpan A K L d hd
  rw [gal_scaled_basis]
  exact Submodule.subset_span (Set.mem_range_self (g * h))

/-- The representation on the scaled normal-basis lattice obtained by
restricting the additive Galois action on `L`. -/
noncomputable def integralBasisRepresentation (d : A) (hd : d ≠ 0) :
    Rep A Gal(L/K) :=
  Rep.of ((Rep.ofDistribMulAction A Gal(L/K) L).ρ.subrepresentation
    (integralNormalSpan A K L d hd)
    (integral_basis_stable A K L d hd))

/-- The scaled integral normal-basis lattice is the regular representation
over `A`. -/
noncomputable def representationIsoRegular
    (d : A) (hd : d ≠ 0) :
    Rep.leftRegular A Gal(L/K) ≅ integralBasisRepresentation A K L d hd := by
  let B := integralBasisSpan A K L d hd
  exact Rep.mkIso (.mk B.repr.symm fun g ↦ by
    apply Finsupp.lhom_ext'
    intro h
    apply LinearMap.ext
    intro r
    simp only [LinearMap.comp_apply, Finsupp.lsingle_apply,
      Representation.ofMulAction_single]
    change B.repr.symm (Finsupp.single (g * h) r) =
      (integralBasisRepresentation A K L d hd).ρ g
        (B.repr.symm (Finsupp.single h r))
    rw [B.repr_symm_single, B.repr_symm_single]
    symm
    calc
      (integralBasisRepresentation A K L d hd).ρ g (r • B h) =
          r • (integralBasisRepresentation A K L d hd).ρ g (B h) :=
        ((integralBasisRepresentation A K L d hd).ρ g).map_smul r (B h)
      _ = r • B (g * h) := by
        congr 1
        apply Subtype.ext
        change g • (↑(B h) : L) = (↑(B (g * h)) : L)
        dsimp only [B]
        rw [integral_basis_span,
          integral_basis_span]
        simpa only [scaled_normal_basis] using
          gal_scaled_basis A K L d hd g h)

/-- Choosing the common denominator supplies an integral, Galois-stable
lattice whose representation is regular. -/
theorem integral_regular_lattice :
    ∃ (d : A) (hd : d ≠ 0),
      integralNormalSpan A K L d hd ≤
          Subalgebra.toSubmodule (integralClosure A L) ∧
        Nonempty (Rep.leftRegular A Gal(L/K) ≅
          integralBasisRepresentation A K L d hd) := by
  obtain ⟨d, hd, hint⟩ := integral_multiple_basis A K L
  exact ⟨d, hd, integral_basis_closure A K L d hd hint,
    ⟨representationIsoRegular A K L d hd⟩⟩

variable {Γ₀ : Type*} [LinearOrderedCommGroupWithZero Γ₀] [Valued L Γ₀]

/-- If the valuation integers of `L` are integral over the base domain, the
integral scaled normal-basis lattice is open.  The proof implements Milne's
commensurability argument: a nonzero scalar multiple of the open valuation
ring lies inside the lattice. -/
theorem integral_basis_open
    [IsIntegrallyClosed A]
    (d : A) (hd : d ≠ 0)
    (hint : ∀ g : Gal(L/K), IsIntegral A (d • IsGalois.normalBasis K L g))
    (hinteger : ∀ z : Valued.integer L, IsIntegral A (z : L)) :
    IsOpen (integralNormalSpan A K L d hd : Set L) := by
  obtain ⟨a, ha, hcontain⟩ :=
    nonzero_smul_span
      A K L d hd hint
  have haK : algebraMap A K a ≠ 0 :=
    (map_ne_zero_iff (algebraMap A K) (IsFractionRing.injective A K)).2 ha
  have haL : algebraMap A L a ≠ 0 :=
    fun h ↦ haK ((algebraMap K L).injective (by
      simpa only [IsScalarTower.algebraMap_apply A K L, map_zero] using h))
  have hopen :
      IsOpen ((algebraMap A L a) • (Valued.integer L : Set L)) :=
    (Valued.isOpen_integer L).smul₀ haL
  apply (integralNormalSpan A K L d hd).toAddSubgroup.isOpen_of_mem_nhds
  refine Filter.mem_of_superset
    (hopen.mem_nhds (Set.zero_mem_smul_set (Valued.integer L).zero_mem)) ?_
  rintro y ⟨z, hz, rfl⟩
  simpa only [Algebra.smul_def] using
    hcontain z ((mem_integralClosure_iff A L).2 (hinteger ⟨z, hz⟩))

/-- Under the same integrality hypothesis, there exists an open integral
lattice whose Galois representation is the regular representation.  This is
the full structural assertion of Milne's Lemma III.2.3. -/
theorem regular_basis_lattice
    [IsIntegrallyClosed A]
    (hinteger : ∀ z : Valued.integer L, IsIntegral A (z : L)) :
    ∃ (d : A) (hd : d ≠ 0),
      integralNormalSpan A K L d hd ≤
          Subalgebra.toSubmodule (integralClosure A L) ∧
        IsOpen (integralNormalSpan A K L d hd : Set L) ∧
        Nonempty (Rep.leftRegular A Gal(L/K) ≅
          integralBasisRepresentation A K L d hd) := by
  obtain ⟨d, hd, hint⟩ := integral_multiple_basis A K L
  exact ⟨d, hd, integral_basis_closure A K L d hd hint,
    integral_basis_open A K L d hd hint hinteger,
    ⟨representationIsoRegular A K L d hd⟩⟩

section IntegralValuationRing

variable [Algebra A (Valued.integer L)]
variable [IsScalarTower A (Valued.integer L) L]

/-- Typeclass form of the open-lattice theorem.  In applications where the
valuation ring of `L` is known to be integral over `A`, no elementwise
integrality argument is needed. -/
theorem open_regular_lattice
    [IsIntegrallyClosed A] [Algebra.IsIntegral A (Valued.integer L)] :
    ∃ (d : A) (hd : d ≠ 0),
      integralNormalSpan A K L d hd ≤
          Subalgebra.toSubmodule (integralClosure A L) ∧
        IsOpen (integralNormalSpan A K L d hd : Set L) ∧
        Nonempty (Rep.leftRegular A Gal(L/K) ≅
          integralBasisRepresentation A K L d hd) :=
  regular_basis_lattice A K L fun z ↦
    (Algebra.IsIntegral.isIntegral z).algebraMap

end IntegralValuationRing

end IntegralNormalBasis

variable (R : Type u) [CommRing R]
variable {G : Type u} [Group G] [Finite G]

private noncomputable def regularTrivialCoind :
    Rep.leftRegular R G →ₗ[R]
      Rep.coind (⊥ : Subgroup G).subtype (Rep.trivial R (⊥ : Subgroup G) R) where
  toFun x := ⟨fun g ↦ x g⁻¹, by
    intro s g
    have hs : s = (1 : (⊥ : Subgroup G)) :=
      Subtype.ext (Subgroup.mem_bot.mp s.property)
    subst hs
    simp⟩
  map_add' _ _ := by ext; simp
  map_smul' _ _ := by ext; simp

private theorem regular_coind_bijective :
    Function.Bijective (regularTrivialCoind R (G := G)) := by
  constructor
  · intro x y hxy
    apply Finsupp.ext
    intro g
    have h := congrArg (fun f ↦ f.1 g⁻¹) hxy
    change x ((g⁻¹)⁻¹) = y ((g⁻¹)⁻¹) at h
    simpa using h
  · intro f
    let x : G →₀ R := Finsupp.equivFunOnFinite.symm fun g ↦ f.1 g⁻¹
    refine ⟨x, Subtype.ext ?_⟩
    funext g
    simp [regularTrivialCoind, x]

/-- Over any commutative ring, the regular representation is coinduced from
the trivial subgroup. -/
noncomputable def isoTrivialCoind :
    Rep.leftRegular R G ≅ Rep.coind (⊥ : Subgroup G).subtype
      (Rep.trivial R (⊥ : Subgroup G) R) :=
  Rep.mkIso (.mk
    (LinearEquiv.ofBijective (regularTrivialCoind R (G := G))
      (regular_coind_bijective R))
    (by
      intro g
      apply LinearMap.ext
      intro x
      apply Subtype.ext
      funext h
      change (Representation.ofMulAction R G G g x) h⁻¹ = x (h * g)⁻¹
      rw [Representation.ofMulAction_apply]
      simp))

/-- The regular representation has zero positive-degree group cohomology.
This is the cohomological conclusion used for the lattice `V` in Lemma
III.2.3. -/
theorem cohomology_left_regular (r : ℕ) (hr : 0 < r) :
    Limits.IsZero (groupCohomology (Rep.leftRegular R G) r) := by
  obtain ⟨n, rfl⟩ := Nat.exists_eq_succ_of_ne_zero (Nat.ne_of_gt hr)
  let A : Rep R (⊥ : Subgroup G) := Rep.trivial R (⊥ : Subgroup G) R
  have hA : Limits.IsZero (groupCohomology A (n + 1)) :=
    isZero_groupCohomology_succ_of_subsingleton A n
  have hcoind : Limits.IsZero
      (groupCohomology (Rep.coind (⊥ : Subgroup G).subtype A) (n + 1)) :=
    Limits.IsZero.of_iso hA (groupCohomology.coindIso A (n + 1))
  exact Limits.IsZero.of_iso hcoind
    ((groupCohomology.functor R G (n + 1)).mapIso
      (isoTrivialCoind R))

/-- Any `G`-module identified with the regular representation has zero
positive-degree cohomology.  Applying this to Milne's integral normal-basis
lattice gives the final assertion of Lemma III.2.3. -/
theorem cohomology_iso_regular
    (V : Rep R G) (e : V ≅ Rep.leftRegular R G)
    (r : ℕ) (hr : 0 < r) :
    Limits.IsZero (groupCohomology V r) :=
  Limits.IsZero.of_iso (cohomology_left_regular R r hr)
    ((groupCohomology.functor R G r).mapIso e)

end Towers.CField.LClass
