import Mathlib.RingTheory.Ideal.NatInt
import Mathlib.RingTheory.Localization.AtPrime.Basic

/-!
# Milne, Algebraic Number Theory, Example 1.13(b): prime ideals of `Z_(2)`

The localization of `Z` at the prime ideal `(2)` has exactly two prime ideals: zero and
the extension of `(2)`.
-/

namespace Submission.NumberTheory.Milne

open Ideal

abbrev integerIdealTwo : Ideal ℤ :=
  Ideal.span ({(2 : ℤ)} : Set ℤ)

private instance : integerIdealTwo.IsPrime :=
  Ideal.isPrime_int_iff.mpr (Or.inr ⟨2, Nat.prime_two, rfl⟩)

abbrev IntegersAtTwo := Localization.AtPrime integerIdealTwo

/-- The prime ideals of `Z_(2)` are `(0)` and the maximal ideal generated by `2`. -/
theorem integers_two_prime (P : Ideal IntegersAtTwo) :
    P.IsPrime ↔
      P = ⊥ ∨
        P = Ideal.map (algebraMap ℤ IntegersAtTwo) integerIdealTwo := by
  constructor
  · intro hP
    have hcontract :=
      (IsLocalization.isPrime_iff_isPrime_disjoint
        integerIdealTwo.primeCompl IntegersAtTwo P).mp hP
    have hcontractLe :
        P.under ℤ ≤ integerIdealTwo := by
      simpa [Ideal.primeCompl, ← le_compl_iff_disjoint_left] using hcontract.2
    have hmapComap :
        Ideal.map (algebraMap ℤ IntegersAtTwo)
            (P.under ℤ) = P :=
      IsLocalization.map_under integerIdealTwo.primeCompl IntegersAtTwo P
    rcases Ideal.isPrime_int_iff.mp hcontract.1 with hbot | ⟨p, hp, hpSpan⟩
    · left
      rw [hbot, Ideal.map_bot] at hmapComap
      exact hmapComap.symm
    · right
      have hle : Ideal.span ({(p : ℤ)} : Set ℤ) ≤ integerIdealTwo := by
        rw [← hpSpan]
        exact hcontractLe
      have htwoDvdInt : (2 : ℤ) ∣ (p : ℤ) :=
        Ideal.span_singleton_le_span_singleton.mp hle
      have htwoDvd : 2 ∣ p := by exact_mod_cast htwoDvdInt
      have hpEq : p = 2 := by
        rcases (Nat.dvd_prime hp).mp htwoDvd with htwoOne | htwoEq
        · norm_num at htwoOne
        · exact htwoEq.symm
      subst p
      calc
        P = Ideal.map (algebraMap ℤ IntegersAtTwo)
            (P.under ℤ) := hmapComap.symm
        _ = Ideal.map (algebraMap ℤ IntegersAtTwo)
            (Ideal.span ({(2 : ℤ)} : Set ℤ)) := congrArg _ hpSpan
        _ = Ideal.map (algebraMap ℤ IntegersAtTwo)
            integerIdealTwo := rfl
  · rintro (rfl | rfl)
    · exact Ideal.isPrime_bot
    · exact IsLocalization.isPrime_of_isPrime_disjoint
        integerIdealTwo.primeCompl IntegersAtTwo integerIdealTwo
        (by infer_instance) disjoint_compl_left

end Submission.NumberTheory.Milne
