import Submission.NumberTheory.Commutative.IntegerLocalizations
import Mathlib.RingTheory.Ideal.NatInt
import Mathlib.RingTheory.Localization.Ideal

/-!
# Milne, Algebraic Number Theory, Example 1.13(b): prime ideals of `Z_2`

Here `Z_2` has Milne's localization meaning: denominators are powers of `2`.
Its prime ideals are zero and the ideals generated by odd rational primes.
-/

namespace Submission.NumberTheory.Milne

open Ideal

abbrev IntegersAwayTwo := Localization.Away (2 : ℤ)

private instance : IsDomain IntegersAwayTwo :=
  IsLocalization.isDomain_of_le_nonZeroDivisors IntegersAwayTwo
    (powers_le_nonZeroDivisors_of_noZeroDivisors
      (by norm_num : (2 : ℤ) ≠ 0))

private lemma span_disjoint_powers {p : ℕ}
    (hp : p.Prime) (hp2 : p ≠ 2) :
    Disjoint (Submonoid.powers (2 : ℤ) : Set ℤ)
      (Ideal.span ({(p : ℤ)} : Set ℤ) : Set ℤ) := by
  rw [Set.disjoint_left]
  intro x hxPowers hxSpan
  obtain ⟨n, rfl⟩ :=
    (Submonoid.mem_powers_iff x (2 : ℤ)).mp hxPowers
  have hpPow : (p : ℤ) ∣ (2 : ℤ) ^ n :=
    Ideal.mem_span_singleton.mp hxSpan
  have hpDvdTwoInt : (p : ℤ) ∣ (2 : ℤ) :=
    Int.Prime.dvd_pow' hp hpPow
  have hpDvdTwo : p ∣ 2 := Int.natCast_dvd_natCast.mp hpDvdTwoInt
  exact hp2 ((Nat.prime_dvd_prime_iff_eq hp Nat.prime_two).mp hpDvdTwo)

/-- The prime ideals of `Z[1/2]` are `(0)` and `(p)` for odd rational primes `p`. -/
theorem integers_away_prime (P : Ideal IntegersAwayTwo) :
    P.IsPrime ↔
      P = ⊥ ∨
        ∃ p : ℕ, p.Prime ∧ p ≠ 2 ∧
          P = Ideal.map (algebraMap ℤ IntegersAwayTwo)
            (Ideal.span ({(p : ℤ)} : Set ℤ)) := by
  constructor
  · intro hP
    have hcontractPrime :
        (P.under ℤ).IsPrime :=
      ((IsLocalization.isPrime_iff_isPrime_disjoint
        (Submonoid.powers (2 : ℤ)) IntegersAwayTwo P).mp hP).1
    have hmapComap :
        Ideal.map (algebraMap ℤ IntegersAwayTwo)
            (P.under ℤ) = P :=
      IsLocalization.map_under (Submonoid.powers (2 : ℤ)) IntegersAwayTwo P
    rcases Ideal.isPrime_int_iff.mp hcontractPrime with hbot | ⟨p, hp, hpSpan⟩
    · left
      rw [hbot, Ideal.map_bot] at hmapComap
      exact hmapComap.symm
    · right
      refine ⟨p, hp, ?_, ?_⟩
      · intro hp2
        subst p
        have hdisjoint : Disjoint
            (Submonoid.powers (2 : ℤ) : Set ℤ)
            (P.under ℤ : Set ℤ) :=
          ((IsLocalization.isPrime_iff_isPrime_disjoint
            (Submonoid.powers (2 : ℤ)) IntegersAwayTwo P).mp hP).2
        exact Set.disjoint_left.mp hdisjoint
          (Submonoid.mem_powers (2 : ℤ)) (by
            rw [hpSpan]
            exact Ideal.subset_span (by simp))
      · rw [← hpSpan]
        exact hmapComap.symm
  · rintro (rfl | ⟨p, hp, hp2, rfl⟩)
    · exact Ideal.isPrime_bot
    · exact IsLocalization.isPrime_of_isPrime_disjoint
        (Submonoid.powers (2 : ℤ))
        IntegersAwayTwo
        (Ideal.span ({(p : ℤ)} : Set ℤ))
        (Ideal.isPrime_int_iff.mpr (Or.inr ⟨p, hp, rfl⟩))
        (span_disjoint_powers hp hp2)

end Submission.NumberTheory.Milne
