import Mathlib

open scoped commutatorElement

noncomputable section

namespace Submission

universe u

/-- Adjoin one cyclic class to a normal subgroup by taking the preimage of its cyclic subgroup
in the quotient. -/
def cyclicPrefixSubgroup
    {G : Type u} [Group G]
    (K : Subgroup G) [K.Normal]
    (x : G) :
    Subgroup G :=
  (Subgroup.zpowers (QuotientGroup.mk' K x)).comap (QuotientGroup.mk' K)

/-- An element whose commutators lie in `K` becomes central modulo `K`. -/
lemma mk_center_commutator
    {G : Type u} [Group G]
    (K : Subgroup G) [K.Normal]
    {x : G}
    (hcomm : ∀ y : G, ⁅x, y⁆ ∈ K) :
    QuotientGroup.mk' K x ∈ Subgroup.center (G ⧸ K) := by
  rw [Subgroup.mem_center_iff]
  intro y
  rcases QuotientGroup.mk'_surjective K y with ⟨y, rfl⟩
  have hxy :
      ⁅QuotientGroup.mk' K x, QuotientGroup.mk' K y⁆ = 1 := by
    rw [← map_commutatorElement]
    exact (QuotientGroup.eq_one_iff ⁅x, y⁆).mpr (hcomm y)
  exact (commutatorElement_eq_one_iff_mul_comm.mp hxy).symm

/-- The cyclic subgroup generated by a central element is normal. -/
lemma zpowers_normal_center
    {G : Type u} [Group G]
    {x : G}
    (hx : x ∈ Subgroup.center G) :
    (Subgroup.zpowers x).Normal := by
  have hle : Subgroup.zpowers x ≤ Subgroup.center G :=
    Subgroup.zpowers_le.mpr hx
  constructor
  intro n hn g
  have hncenter : n ∈ Subgroup.center G :=
    hle hn
  have heq : g * n * g⁻¹ = n := by
    calc
      g * n * g⁻¹ = n * g * g⁻¹ := by
        rw [Subgroup.mem_center_iff.mp hncenter g]
      _ = n := by simp
  simpa [heq] using hn

/-- A cyclic prefix is normal if the newly adjoined class is central modulo the old prefix. -/
lemma cyclic_prefix_normal
    {G : Type u} [Group G]
    (K : Subgroup G) [K.Normal]
    {x : G}
    (hcomm : ∀ y : G, ⁅x, y⁆ ∈ K) :
    (cyclicPrefixSubgroup K x).Normal := by
  apply Subgroup.Normal.comap
  exact
    zpowers_normal_center
      (mk_center_commutator K hcomm)

/-- The old normal subgroup is contained in its cyclic extension. -/
lemma cyclic_subgroup
    {G : Type u} [Group G]
    (K : Subgroup G) [K.Normal]
    (x : G) :
    K ≤ cyclicPrefixSubgroup K x := by
  intro y hy
  change QuotientGroup.mk' K y ∈ Subgroup.zpowers (QuotientGroup.mk' K x)
  have hyq : QuotientGroup.mk' K y = 1 :=
    (QuotientGroup.eq_one_iff y).mpr hy
  rw [hyq]
  exact Subgroup.one_mem _

/-- The adjoined element belongs to its cyclic extension. -/
lemma cyclic_prefix
    {G : Type u} [Group G]
    (K : Subgroup G) [K.Normal]
    (x : G) :
    x ∈ cyclicPrefixSubgroup K x := by
  exact Subgroup.mem_zpowers (QuotientGroup.mk' K x)

/-- If `x^p` lies in `K` while `x` does not, the class of `x` modulo `K` has order exactly `p`. -/
lemma order_mk_prime
    {p : ℕ} [Fact p.Prime]
    {G : Type u} [Group G]
    (K : Subgroup G) [K.Normal]
    {x : G}
    (hpow : x ^ p ∈ K)
    (hnot : x ∉ K) :
    orderOf (QuotientGroup.mk' K x) = p := by
  apply orderOf_eq_prime
  · rw [← map_pow]
    exact (QuotientGroup.eq_one_iff (x ^ p)).mpr hpow
  · intro hx
    exact hnot ((QuotientGroup.eq_one_iff x).mp hx)

/-- Every element of a cyclic prefix has an old-prefix factor followed by one exponent in
`0, ..., p - 1`. -/
lemma cyclic_prefix_subgroup
    {p : ℕ} [Fact p.Prime]
    {G : Type u} [Group G]
    (K : Subgroup G) [K.Normal]
    {x y : G}
    (hpow : x ^ p ∈ K)
    (hnot : x ∉ K)
    (hy : y ∈ cyclicPrefixSubgroup K x) :
    ∃ k : K, ∃ e : Fin p, (k : G) * x ^ e.val = y := by
  let q : G →* G ⧸ K := QuotientGroup.mk' K
  have hord : orderOf (q x) = p :=
    order_mk_prime K hpow hnot
  have hfin : IsOfFinOrder (q x) := by
    rw [isOfFinOrder_iff_pow_eq_one]
    exact
      ⟨p, (Fact.out : Nat.Prime p).pos,
        by rw [← map_pow]; exact (QuotientGroup.eq_one_iff _).mpr hpow⟩
  have hy' : q y ∈ Subgroup.zpowers (q x) :=
    hy
  let eOrder : Fin (orderOf (q x)) :=
    (finEquivZPowers hfin).symm ⟨q y, hy'⟩
  let e : Fin p := Fin.cast hord eOrder
  have hqpow : q x ^ e.val = q y := by
    have happly :
        finEquivZPowers hfin eOrder = ⟨q y, hy'⟩ :=
      (finEquivZPowers hfin).apply_symm_apply ⟨q y, hy'⟩
    exact congrArg Subtype.val happly
  have hk : y * (x ^ e.val)⁻¹ ∈ K := by
    rw [← QuotientGroup.eq_one_iff]
    change q (y * (x ^ e.val)⁻¹) = 1
    rw [map_mul, map_inv, map_pow, hqpow, mul_inv_cancel]
  refine ⟨⟨y * (x ^ e.val)⁻¹, hk⟩, e, ?_⟩
  group

/-- The bounded exponent in a cyclic-prefix decomposition is unique. -/
lemma fin_mul_pow
    {p : ℕ} [Fact p.Prime]
    {G : Type u} [Group G]
    (K : Subgroup G) [K.Normal]
    {x : G}
    (hpow : x ^ p ∈ K)
    (hnot : x ∉ K)
    {k l : K}
    {e f : Fin p}
    (hef : (k : G) * x ^ e.val = (l : G) * x ^ f.val) :
    e = f := by
  let q : G →* G ⧸ K := QuotientGroup.mk' K
  have hord : orderOf (q x) = p :=
    order_mk_prime K hpow hnot
  have hpows : q x ^ e.val = q x ^ f.val := by
    have hmap := congrArg q hef
    have hkq : q (k : G) = 1 :=
      (QuotientGroup.eq_one_iff (k : G)).mpr k.property
    have hlq : q (l : G) = 1 :=
      (QuotientGroup.eq_one_iff (l : G)).mpr l.property
    simpa only [map_mul, map_pow, hkq, hlq, one_mul] using hmap
  apply Fin.ext
  exact
    pow_injOn_Iio_orderOf
      (by simp [hord])
      (by simp [hord])
      hpows

/-- One cyclic prefix is canonically represented by an old-prefix element and one bounded
exponent. -/
noncomputable def cyclicPrefixEquiv
    {p : ℕ} [Fact p.Prime]
    {G : Type u} [Group G]
    (K : Subgroup G) [K.Normal]
    {x : G}
    (hpow : x ^ p ∈ K)
    (hnot : x ∉ K) :
    K × Fin p ≃ cyclicPrefixSubgroup K x := by
  let f : K × Fin p → cyclicPrefixSubgroup K x :=
    fun ke =>
      ⟨(ke.1 : G) * x ^ ke.2.val,
        (cyclicPrefixSubgroup K x).mul_mem
          (cyclic_subgroup K x ke.1.property)
          ((cyclicPrefixSubgroup K x).pow_mem (cyclic_prefix K x) ke.2.val)⟩
  apply Equiv.ofBijective f
  constructor
  · intro a b hab
    have he : a.2 = b.2 := by
      apply fin_mul_pow K hpow hnot
      exact congrArg Subtype.val hab
    apply Prod.ext
    · apply Subtype.ext
      have hval := congrArg Subtype.val hab
      change (a.1 : G) * x ^ a.2.val = (b.1 : G) * x ^ b.2.val at hval
      rw [he] at hval
      exact mul_right_cancel hval
    · exact he
  · intro y
    rcases
        cyclic_prefix_subgroup
          K hpow hnot y.property with
      ⟨k, e, hke⟩
    exact ⟨(k, e), Subtype.ext hke⟩

@[simp]
lemma cyclic_prefix_equiv
    {p : ℕ} [Fact p.Prime]
    {G : Type u} [Group G]
    (K : Subgroup G) [K.Normal]
    {x : G}
    (hpow : x ^ p ∈ K)
    (hnot : x ∉ K)
    (ke : K × Fin p) :
    ((cyclicPrefixEquiv K hpow hnot ke : cyclicPrefixSubgroup K x) : G) =
      (ke.1 : G) * x ^ ke.2.val :=
  rfl

/-- Ordered words for a cyclic pc prefix, with newly adjoined generators placed on the right. -/
def cyclicPCWord
    {p : ℕ}
    {G : Type u} [Group G] :
    (r : ℕ) → (Fin r → G) → (Fin r → Fin p) → G
  | 0, _gen, _e => 1
  | r + 1, gen, e =>
      cyclicPCWord r
          (fun i : Fin r => gen i.castSucc)
          (fun i : Fin r => e i.castSucc) *
        gen (Fin.last r) ^ (e (Fin.last r)).val

/-- A subgroup together with an ordered bounded-exponent normal form built by cyclic extensions. -/
structure CPForm
    (p : ℕ) [Fact p.Prime]
    (G : Type u) [Group G] where
  r : ℕ
  subgroup : Subgroup G
  normal : subgroup.Normal
  gen : Fin r → G
  wordEquiv : (Fin r → Fin p) ≃ subgroup
  wordEquiv_apply :
    ∀ e, (wordEquiv e : G) = cyclicPCWord r gen e

attribute [instance] CPForm.normal

namespace CPForm

/-- The empty pc prefix represents the trivial subgroup. -/
noncomputable def empty
    (p : ℕ) [Fact p.Prime]
    (G : Type u) [Group G] :
    CPForm p G where
  r := 0
  subgroup := ⊥
  normal := inferInstance
  gen := fun i => Fin.elim0 i
  wordEquiv := Equiv.ofUnique _ _
  wordEquiv_apply := by
    intro e
    change ((Equiv.ofUnique _ _ e : (⊥ : Subgroup G)) : G) = 1
    exact
      Subgroup.mem_bot.mp
        ((Equiv.ofUnique (Fin 0 → Fin p) (⊥ : Subgroup G) e).property)

/-- Append one central-modulo-prefix order-`p` class to an ordered pc normal form. -/
noncomputable def extend
    {p : ℕ} [Fact p.Prime]
    {G : Type u} [Group G]
    (P : CPForm p G)
    (x : G)
    (hpow : x ^ p ∈ P.subgroup)
    (hnot : x ∉ P.subgroup)
    (hcomm : ∀ y : G, ⁅x, y⁆ ∈ P.subgroup) :
    CPForm p G where
  r := P.r + 1
  subgroup := cyclicPrefixSubgroup P.subgroup x
  normal := cyclic_prefix_normal P.subgroup hcomm
  gen := Fin.snoc P.gen x
  wordEquiv :=
    ((Fin.snocEquiv (fun _ : Fin (P.r + 1) => Fin p)).symm.trans
        (Equiv.prodComm _ _)).trans
      ((P.wordEquiv.prodCongr (Equiv.refl (Fin p))).trans
        (cyclicPrefixEquiv P.subgroup hpow hnot))
  wordEquiv_apply := by
    intro e
    simp only [Equiv.trans_apply, Equiv.prodComm_apply, Equiv.prodCongr_apply,
      Fin.snocEquiv_symm_apply, cyclic_prefix_equiv,
      cyclicPCWord, Fin.snoc_castSucc, Fin.snoc_last]
    change
      (P.wordEquiv (fun i : Fin P.r => e i.castSucc) : G) *
          x ^ (e (Fin.last P.r)).val =
        cyclicPCWord P.r P.gen (fun i : Fin P.r => e i.castSucc) *
          x ^ (e (Fin.last P.r)).val
    rw [P.wordEquiv_apply]

@[simp]
lemma base_subgroup
    {p : ℕ} [Fact p.Prime]
    {G : Type u} [Group G] :
    (empty p G).subgroup = ⊥ :=
  rfl

@[simp]
lemma extend_subgroup
    {p : ℕ} [Fact p.Prime]
    {G : Type u} [Group G]
    (P : CPForm p G)
    (x : G)
    (hpow : x ^ p ∈ P.subgroup)
    (hnot : x ∉ P.subgroup)
    (hcomm : ∀ y : G, ⁅x, y⁆ ∈ P.subgroup) :
    (P.extend x hpow hnot hcomm).subgroup =
      cyclicPrefixSubgroup P.subgroup x :=
  rfl

@[simp]
lemma extend_word_equiv
    {p : ℕ} [Fact p.Prime]
    {G : Type u} [Group G]
    (P : CPForm p G)
    (x : G)
    (hpow : x ^ p ∈ P.subgroup)
    (hnot : x ∉ P.subgroup)
    (hcomm : ∀ y : G, ⁅x, y⁆ ∈ P.subgroup)
    (e : Fin (P.r + 1) → Fin p) :
    (((P.extend x hpow hnot hcomm).wordEquiv e :
        (P.extend x hpow hnot hcomm).subgroup) : G) =
      (P.wordEquiv (fun i : Fin P.r => e i.castSucc) : G) *
        x ^ (e (Fin.last P.r)).val := by
  rw [(P.extend x hpow hnot hcomm).wordEquiv_apply, P.wordEquiv_apply]
  change
    cyclicPCWord (P.r + 1) (Fin.snoc P.gen x) e =
      (cyclicPCWord P.r P.gen fun i => e i.castSucc) *
        x ^ (e (Fin.last P.r)).val
  rw [cyclicPCWord]
  simp only [Fin.snoc_castSucc, Fin.snoc_last]

end CPForm

end Submission
