import Mathlib.RingTheory.ClassGroup
import Submission.NumberTheory.Ideals.IdealGenerationCorollaries


/-!
# Chapter V, Section 1, Lemma 1.1

For a finite set `S` of height-one primes, `IdealsPrimeTo S` is the group of
nonzero fractional ideals whose exponent at every prime in `S` is zero.
Principal ideals define a map from the corresponding subgroup of `K^x`, and
the class-group map is onto.  Its kernel is exactly the image of the principal
ideal map.  This is the exact part

`K^S -> I^S -> Cl(R) -> 0`

of Milne's sequence; the kernel of the first map is, definitionally, the
elements generating the unit fractional ideal, canonically the units of `R`.
-/

namespace Submission.CField.RCGroups

open IsDedekindDomain
open scoped nonZeroDivisors

noncomputable section

variable (R K : Type*) [CommRing R] [IsDomain R] [IsDedekindDomain R]
  [Field K] [Algebra R K] [IsFractionRing R K]

/-- The product of the finite primes that are to be excluded. -/
def forbiddenIdeal (S : Finset (HeightOneSpectrum R)) : Ideal R :=
  S.prod fun p => p.asIdeal

omit [IsDedekindDomain R] in
theorem forbidden_ne_zero (S : Finset (HeightOneSpectrum R)) :
    forbiddenIdeal R S ≠ 0 := by
  classical
  rw [forbiddenIdeal, Finset.prod_ne_zero_iff]
  exact fun p hp => p.ne_bot

omit [IsDomain R] [IsDedekindDomain R] in
theorem forbidden_ideal {S : Finset (HeightOneSpectrum R)}
    {p : HeightOneSpectrum R} (hp : p ∈ S) :
    forbiddenIdeal R S ≤ p.asIdeal := by
  classical
  induction S using Finset.induction_on with
  | empty => simp at hp
  | @insert q S hq ih =>
      rw [forbiddenIdeal, Finset.prod_insert hq]
      rcases Finset.mem_insert.mp hp with rfl | hp
      · exact Ideal.mul_le_right
      · exact (Ideal.mul_le_left : q.asIdeal * forbiddenIdeal R S ≤
          forbiddenIdeal R S) |>.trans (ih hp)

/-- The group `I^S` of nonzero fractional ideals with no factor in `S`. -/
def IdealsPrimeTo (S : Finset (HeightOneSpectrum R)) :
    Subgroup (FractionalIdeal R⁰ K)ˣ where
  carrier := {I | ∀ p ∈ S, FractionalIdeal.count K p (I : FractionalIdeal R⁰ K) = 0}
  one_mem' := by
    intro p hp
    exact FractionalIdeal.count_one K p
  mul_mem' := by
    intro I J hI hJ p hp
    rw [Units.val_mul, FractionalIdeal.count_mul K p I.ne_zero J.ne_zero,
      hI p hp, hJ p hp, add_zero]
  inv_mem' := by
    intro I hI p hp
    rw [Units.val_inv_eq_inv_val, FractionalIdeal.count_inv K p, hI p hp, neg_zero]

/-- The subgroup `K^S`: nonzero field elements whose principal ideals lie in
`I^S`. -/
def ElementsPrimeTo (S : Finset (HeightOneSpectrum R)) : Subgroup Kˣ :=
  (IdealsPrimeTo R K S).comap (toPrincipalIdeal R K)

/-- The principal-ideal map `K^S -> I^S`. -/
def principalIdealPrime (S : Finset (HeightOneSpectrum R)) :
    ElementsPrimeTo R K S →* IdealsPrimeTo R K S where
  toFun x := ⟨toPrincipalIdeal R K x, x.property⟩
  map_one' := by
    apply Subtype.ext
    change toPrincipalIdeal R K (1 : Kˣ) = 1
    exact map_one (toPrincipalIdeal R K)
  map_mul' x y := by
    apply Subtype.ext
    change toPrincipalIdeal R K (x.1 * y.1) =
      toPrincipalIdeal R K x.1 * toPrincipalIdeal R K y.1
    exact map_mul (toPrincipalIdeal R K) x.1 y.1

/-- The natural map `I^S -> Cl(R)`. -/
def idealClassPrime (S : Finset (HeightOneSpectrum R)) :
    IdealsPrimeTo R K S →* ClassGroup R :=
  (ClassGroup.mk (R := R) (K := K)).comp (IdealsPrimeTo R K S).subtype

theorem ideal_class_principal
    (S : Finset (HeightOneSpectrum R)) (x : ElementsPrimeTo R K S) :
    idealClassPrime R K S (principalIdealPrime R K S x) = 1 := by
  rw [idealClassPrime, principalIdealPrime, MonoidHom.comp_apply,
    Subgroup.coe_subtype, ClassGroup.mk_eq_one_iff,
    FractionalIdeal.isPrincipal_iff]
  refine ⟨((x.1 : Kˣ) : K), ?_⟩
  change (toPrincipalIdeal R K x.1 : FractionalIdeal R⁰ K) =
    FractionalIdeal.spanSingleton R⁰ (x.1 : K)
  exact coe_toPrincipalIdeal x.1

/-- Exactness at `I^S`: the ideals mapping to the trivial ideal class are
exactly the principal ideals generated by elements of `K^S`. -/
theorem range_principal_class
    (S : Finset (HeightOneSpectrum R)) :
    (principalIdealPrime R K S).range = (idealClassPrime R K S).ker := by
  ext I
  constructor
  · rintro ⟨x, rfl⟩
    exact ideal_class_principal R K S x
  · intro hI
    rw [MonoidHom.mem_ker] at hI
    change ClassGroup.mk K I.1 = 1 at hI
    have hprincipal :
        ((I.1 : (FractionalIdeal R⁰ K)ˣ) : Submodule R K).IsPrincipal := by
      exact ClassGroup.mk_eq_one_iff.mp hI
    obtain ⟨x, hx⟩ :=
      (FractionalIdeal.isPrincipal_iff (I.1 : FractionalIdeal R⁰ K)).mp hprincipal
    have hx0 : x ≠ 0 := by
      intro hx0
      subst x
      rw [FractionalIdeal.spanSingleton_zero] at hx
      exact I.1.ne_zero hx
    let xu : Kˣ := Units.mk0 x hx0
    have hxu : toPrincipalIdeal R K xu = (I : (FractionalIdeal R⁰ K)ˣ) := by
      apply Units.ext
      simpa [xu] using hx.symm
    let y : ElementsPrimeTo R K S :=
      ⟨xu, by
        change toPrincipalIdeal R K xu ∈ IdealsPrimeTo R K S
        rw [hxu]
        exact I.property⟩
    refine ⟨y, ?_⟩
    apply Subtype.ext
    change toPrincipalIdeal R K xu = I.1
    exact hxu

omit [IsDomain R] in
private theorem coe_coprime_forbidden
    {S : Finset (HeightOneSpectrum R)} {J : Ideal R}
    (hJ : J ≠ 0) (hcop : IsCoprime J (forbiddenIdeal R S))
    {p : HeightOneSpectrum R} (hp : p ∈ S) :
    FractionalIdeal.count K p (J : FractionalIdeal R⁰ K) = 0 := by
  have hcop' : IsCoprime J p.asIdeal := by
    rw [Ideal.isCoprime_iff_sup_eq] at hcop ⊢
    have hle : J ⊔ forbiddenIdeal R S ≤ J ⊔ p.asIdeal :=
      sup_le_sup_left (forbidden_ideal R hp) J
    rw [hcop] at hle
    exact top_unique hle
  have hnotdvd : ¬p.asIdeal ∣ J := by
    intro hdvd
    have hJle : J ≤ p.asIdeal := Ideal.dvd_iff_le.mp hdvd
    have hsup : J ⊔ p.asIdeal = p.asIdeal := sup_eq_right.mpr hJle
    rw [Ideal.isCoprime_iff_sup_eq, hsup] at hcop'
    exact p.isPrime.ne_top hcop'
  rw [FractionalIdeal.count_coe K p hJ]
  norm_cast
  rw [← not_ne_iff]
  rwa [Associates.count_ne_zero_iff_dvd hJ p.irreducible]

/-- The final map in Lemma 1.1 is surjective: every ideal class has a
representative prime to the prescribed finite set. -/
theorem ideal_class_surjective (S : Finset (HeightOneSpectrum R)) :
    Function.Surjective (idealClassPrime R K S) := by
  intro c
  obtain ⟨I, hIclass⟩ :=
    (ClassGroup.mk0_surjective (R := R)) c⁻¹
  have hI0 : (I : Ideal R) ≠ 0 :=
    mem_nonZeroDivisors_iff_ne_zero.mp I.property
  obtain ⟨J, hJ0, hJcop, hIJprincipal⟩ :=
    Submission.NumberTheory.Milne.coprime_nonzero_principal
      hI0 (forbidden_ne_zero R S)
  let J0 : (Ideal R)⁰ :=
    ⟨J, mem_nonZeroDivisors_iff_ne_zero.mpr hJ0⟩
  have hprodclass : ClassGroup.mk0 I * ClassGroup.mk0 J0 = 1 := by
    rw [← map_mul]
    exact (ClassGroup.mk0_eq_one_iff (R := R) (I * J0).property).mpr hIJprincipal
  have hJclass : ClassGroup.mk0 J0 = c := by
    have h := congrArg (fun z : ClassGroup R => c * z) hprodclass
    rw [hIclass] at h
    simpa [mul_assoc] using h
  let Jfrac : (FractionalIdeal R⁰ K)ˣ := FractionalIdeal.mk0 K J0
  have hprime : Jfrac ∈ IdealsPrimeTo R K S := by
    intro p hp
    simpa [Jfrac, J0] using
      coe_coprime_forbidden R K hJ0 hJcop hp
  refine ⟨⟨Jfrac, hprime⟩, ?_⟩
  change ClassGroup.mk K Jfrac = c
  rw [ClassGroup.mk_mk0]
  exact hJclass

/-- Lemma 1.1 in exactness form from `K^S` onward. -/
theorem forbiddenIdealExact (S : Finset (HeightOneSpectrum R)) :
    (principalIdealPrime R K S).range = (idealClassPrime R K S).ker ∧
      Function.Surjective (idealClassPrime R K S) :=
  ⟨range_principal_class R K S,
    ideal_class_surjective R K S⟩

end

end Submission.CField.RCGroups
