import Towers.ClassField.KummerTheory.KummerCorrespondenceProof

/-!
# The ordered Kummer correspondence

Theorem VII.A.3 is more than a bijection of finite objects: inclusion of
finite abelian exponent-`n` extensions is exactly inclusion of their radical
power-class groups.  Equivalently, radical generation is an order embedding.

This file proves the two concrete monotonicity statements (including the
transport of radical units through an inclusion of intermediate fields),
upgrades them to iff criteria using the reconstruction theorems, and packages
the Kummer correspondence as an order isomorphism.
-/

namespace Towers.CField.KTheory

noncomputable section

universe u

variable {K Omega : Type u} [Field K] [Field Omega] [Algebra K Omega]
  [IsAlgClosure K Omega]

/-- Radical generation is monotone: enlarging the power-class subgroup can
only enlarge the field generated by the selected radicals. -/
theorem kummerField_mono
    {n : Nat} (hn : 0 < n) {B C : PCSubgro K n}
    (hBC : B.carrier <= C.carrier) :
    kummerField K Omega n hn B <= kummerField K Omega n hn C := by
  unfold kummerField
  rw [IntermediateField.adjoin_le_iff]
  rintro x ⟨b, rfl⟩
  let c : C.carrier := ⟨b.1, hBC b.2⟩
  exact IntermediateField.subset_adjoin K
    (Set.range fun c : C.carrier ↦ kummerRoot K Omega n hn c.1)
    ⟨c, rfl⟩

omit [IsAlgClosure K Omega] in
/-- Radical power classes are monotone in the ambient intermediate field.
The proof transports a witnessing unit through the actual field inclusion and
checks compatibility of the two base-field algebra maps. -/
theorem radical_classes_mono
    {n : Nat} {L M : IntermediateField K Omega} (hLM : L <= M) :
    radicalPowerClasses K Omega n L <= radicalPowerClasses K Omega n M := by
  rintro b ⟨a, ⟨x, hx⟩, rfl⟩
  let iLM : L →ₐ[K] M := IntermediateField.inclusion hLM
  let y : Mˣ := Units.map iLM.toMonoidHom x
  refine ⟨a, ⟨y, ?_⟩, rfl⟩
  change (Units.map iLM.toMonoidHom x) ^ n =
    Units.map (algebraMap K M).toMonoidHom a
  rw [← map_pow, hx]
  apply Units.ext
  rfl

/-- Containment of finite power-class subgroups is detected exactly by
containment of their Kummer fields.  The reverse implication is genuinely
Kummer-theoretic: it uses exact reconstruction of a subgroup from the field
it generates, not merely the evident behavior of generators. -/
theorem kummer
    (n : Nat) (hn : 0 < n)
    (hroots : (primitiveRoots n K).Nonempty)
    (B C : PCSubgro K n) :
    kummerField K Omega n hn B <= kummerField K Omega n hn C <->
      B.carrier <= C.carrier := by
  constructor
  · intro hfield
    rw [← radical_classes_field
      (K := K) (Omega := Omega) n hn hroots B]
    rw [← radical_classes_field
      (K := K) (Omega := Omega) n hn hroots C]
    exact radical_classes_mono hfield
  · exact kummerField_mono hn

/-- Equality of multiradical fields is equivalent to equality of the finite
power-class subgroups which generate them. -/
theorem kummer_field
    (n : Nat) (hn : 0 < n)
    (hroots : (primitiveRoots n K).Nonempty)
    (B C : PCSubgro K n) :
    kummerField K Omega n hn B = kummerField K Omega n hn C <-> B = C := by
  constructor
  · intro hfield
    apply PCSubgro.ext_carrier K
    apply le_antisymm
    · exact (kummer n hn hroots B C).mp hfield.le
    · exact (kummer n hn hroots C B).mp hfield.ge
  · intro h
    exact congrArg (kummerField K Omega n hn) h

set_option synthInstance.maxHeartbeats 200000 in
-- The finite-dimensional tower instances are expensive to synthesize on Lean 4.30.
/-- The relative degree in a nested multiradical tower is the quotient of
the orders of the corresponding power-class groups.  Thus the exact degree
formula in Theorem A.3 is compatible not only with the ground field but with
every inclusion on the subgroup side. -/
theorem finrank_kummer_div
    (n : Nat) (hn : 0 < n)
    (hroots : (primitiveRoots n K).Nonempty)
    (B C : PCSubgro K n)
    (hBC : B.carrier <= C.carrier) :
    Module.finrank (kummerField K Omega n hn B)
        ↥(IntermediateField.extendScalars
          (kummerField_mono (K := K) (Omega := Omega) hn hBC)) =
      C.card / B.card := by
  let F := kummerField K Omega n hn B
  let E := kummerField K Omega n hn C
  let hFE : F <= E := kummerField_mono (K := K) (Omega := Omega) hn hBC
  let EoverF : IntermediateField F Omega :=
    IntermediateField.extendScalars hFE
  letI : FiniteDimensional K F :=
    dimensional_kummer_field K Omega n hn B
  letI : FiniteDimensional K E :=
    dimensional_kummer_field K Omega n hn C
  letI : Module.Finite K EoverF := by
    exact Module.Finite.equiv
      (IntermediateField.equivOfEq
        (IntermediateField.extendScalars_restrictScalars hFE)).symm.toLinearEquiv
  letI : Module.Finite F EoverF :=
    Module.Finite.of_restrictScalars_finite K F EoverF
  have hFdegree : Module.finrank K F = B.card :=
    finrank_kummer_field n hn hroots B
  have hEdegree : Module.finrank K EoverF = C.card := by
    change Module.finrank K (EoverF.restrictScalars K) = C.card
    rw [IntermediateField.extendScalars_restrictScalars]
    exact finrank_kummer_field n hn hroots C
  apply Nat.eq_div_of_mul_eq_left (by
    rw [← hFdegree]
    exact Module.finrank_pos.ne')
  calc
    Module.finrank F EoverF * B.card =
        Module.finrank K F * Module.finrank F EoverF := by
      rw [hFdegree]
      exact Nat.mul_comm _ _
    _ = Module.finrank K EoverF :=
      Module.finrank_mul_finrank K F EoverF
    _ = C.card := hEdegree

/-- Inclusion of finite Kummer radical groups forces divisibility of their
orders.  The quotient is realized by the degree of the relative radical
extension, rather than obtained from an abstract finite-group argument. -/
theorem card_dvd_subgroup
    (Omega : Type u) [Field Omega] [Algebra K Omega] [IsAlgClosure K Omega]
    (n : Nat) (hn : 0 < n)
    (hroots : (primitiveRoots n K).Nonempty)
    (B C : PCSubgro K n)
    (hBC : B.carrier <= C.carrier) : B.card ∣ C.card := by
  let F := kummerField K Omega n hn B
  let E := kummerField K Omega n hn C
  let hFE : F <= E := kummerField_mono (K := K) (Omega := Omega) hn hBC
  let EoverF : IntermediateField F Omega :=
    IntermediateField.extendScalars hFE
  letI : FiniteDimensional K F :=
    dimensional_kummer_field K Omega n hn B
  letI : FiniteDimensional K E :=
    dimensional_kummer_field K Omega n hn C
  letI : Module.Finite K EoverF := by
    exact Module.Finite.equiv
      (IntermediateField.equivOfEq
        (IntermediateField.extendScalars_restrictScalars hFE)).symm.toLinearEquiv
  letI : Module.Finite F EoverF :=
    Module.Finite.of_restrictScalars_finite K F EoverF
  refine ⟨Module.finrank F EoverF, ?_⟩
  calc
    C.card = Module.finrank K EoverF := by
      symm
      change Module.finrank K (EoverF.restrictScalars K) = C.card
      rw [IntermediateField.extendScalars_restrictScalars]
      exact finrank_kummer_field n hn hroots C
    _ = Module.finrank K F * Module.finrank F EoverF :=
      (Module.finrank_mul_finrank K F EoverF).symm
    _ = B.card * Module.finrank F EoverF := by
      rw [finrank_kummer_field n hn hroots B]

namespace PCSubgro

instance {n : Nat} : PartialOrder (PCSubgro K n) where
  le B C := B.carrier <= C.carrier
  le_refl B := le_rfl
  le_trans _ _ _ hBC hCD := fun b hb ↦ hCD (hBC hb)
  le_antisymm B C hBC hCB :=
    ext_carrier K (le_antisymm hBC hCB)

@[simp]
theorem le_carrier_le {n : Nat} (B C : PCSubgro K n) :
    B <= C <-> B.carrier <= C.carrier :=
  Iff.rfl

end PCSubgro

namespace AESubext

instance {n : Nat} : PartialOrder
    (AESubext K Omega n) where
  le L M := L.carrier <= M.carrier
  le_refl L := le_rfl
  le_trans _ _ _ hLM hMN := fun x hx ↦ hMN (hLM hx)
  le_antisymm L M hLM hML :=
    ext_carrier K Omega (le_antisymm hLM hML)

omit [IsAlgClosure K Omega] in
@[simp]
theorem le_carrier_le {n : Nat}
    (L M : AESubext K Omega n) :
    L <= M <-> L.carrier <= M.carrier :=
  Iff.rfl

end AESubext

/-- For finite abelian exponent-`n` extensions, containment of fields is
equivalent to containment of radical power-class groups. -/
theorem radical_power_classes
    (n : Nat) (hn : 0 < n)
    (hroots : (primitiveRoots n K).Nonempty)
    (L M : AESubext K Omega n) :
    radicalPowerClasses K Omega n L.carrier <=
        radicalPowerClasses K Omega n M.carrier <->
      L <= M := by
  constructor
  · intro hradical
    change L.carrier <= M.carrier
    rw [← kummer_radical_subgroup
      (K := K) (Omega := Omega) n hn hroots L]
    rw [← kummer_radical_subgroup
      (K := K) (Omega := Omega) n hn hroots M]
    exact kummerField_mono hn hradical
  · intro hfield
    exact radical_classes_mono hfield

/-- The full ordered form of Theorem VII.A.3.  The usual Kummer equivalence
is an order isomorphism: subextensions correspond to subgroups, and both
directions preserve and reflect inclusion. -/
def kummerCorrespondenceIso
    (n : Nat) (hn : 0 < n)
    (hroots : (primitiveRoots n K).Nonempty) :
    AESubext K Omega n ≃o
      PCSubgro K n where
  toEquiv := kummerCorrespondenceEquiv n hn hroots
  map_rel_iff' {L M} := by
    change radicalPowerClasses K Omega n L.carrier <=
        radicalPowerClasses K Omega n M.carrier <-> L.carrier <= M.carrier
    exact radical_power_classes n hn hroots L M

end

end Towers.CField.KTheory
