import Submission.NumberTheory.Cyclotomic.PrimePowerCyclotomic
import Mathlib.FieldTheory.Finite.Basic


/-!
# Pairwise coprimality of the Fermat factors

This file formalizes Lemma 6.9 of Milne's *Algebraic Number Theory* notes.
-/

namespace Submission.NumberTheory.Milne

open Algebra Ideal IsCyclotomicExtension NumberField Polynomial

open scoped Cyclotomic Function

variable {p : ℕ} {K : Type*} [Field K] [CharZero K] [hp : Fact p.Prime]
variable [hK : IsCyclotomicExtension {p} ℚ K]

/-- Milne, Lemma 6.9: in the first case of Fermat's equation, the principal
ideals generated by the cyclotomic factors `x + ζⁱ y` are relatively prime
in pairs. -/
theorem fermat_pairwise_coprime {zeta : K} (hzeta : IsPrimitiveRoot zeta p)
    {x y z : ℤ} (hxy : IsCoprime x y) (hFermat : x ^ p + y ^ p = z ^ p)
    (hpz : ¬ (p : ℤ) ∣ z) :
    Pairwise (IsCoprime on fun i : Fin p ↦
      Ideal.span
        {algebraMap ℤ (𝓞 K) x + hzeta.toInteger ^ (i : ℕ) * algebraMap ℤ (𝓞 K) y}) := by
  letI : NumberField K := IsCyclotomicExtension.numberField {p} ℚ K
  let O := 𝓞 K
  let zetaO : O := hzeta.toInteger
  let xO : O := algebraMap ℤ O x
  let yO : O := algebraMap ℤ O y
  have hzetaO : IsPrimitiveRoot zetaO p := hzeta.toInteger_isPrimitiveRoot
  intro i j hij
  apply Ideal.coprime_of_no_prime_ge
  intro P hiP hjP hP
  letI : P.IsPrime := hP
  have hfi : xO + zetaO ^ (i : ℕ) * yO ∈ P := by
    apply hiP
    exact Ideal.subset_span (Set.mem_singleton _)
  have hfj : xO + zetaO ^ (j : ℕ) * yO ∈ P := by
    apply hjP
    exact Ideal.subset_span (Set.mem_singleton _)
  have hdiff_y : (zetaO ^ (i : ℕ) - zetaO ^ (j : ℕ)) * yO ∈ P := by
    convert P.sub_mem hfi hfj using 1 ; ring
  have hdiff_x : (zetaO ^ (j : ℕ) - zetaO ^ (i : ℕ)) * xO ∈ P := by
    have h := P.sub_mem (P.mul_mem_left (zetaO ^ (j : ℕ)) hfi)
      (P.mul_mem_left (zetaO ^ (i : ℕ)) hfj)
    convert h using 1 ; ring
  have hdiff : zetaO ^ (i : ℕ) - zetaO ^ (j : ℕ) ∈ P := by
    by_contra hnot
    have hyP : yO ∈ P :=
      (hP.mul_mem_iff_mem_or_mem.mp hdiff_y).resolve_left hnot
    have hnot' : zetaO ^ (j : ℕ) - zetaO ^ (i : ℕ) ∉ P := by
      simpa only [neg_sub] using P.neg_mem_iff.not.mpr hnot
    have hxP : xO ∈ P :=
      (hP.mul_mem_iff_mem_or_mem.mp hdiff_x).resolve_left hnot'
    have hxyO : IsCoprime xO yO := hxy.map (algebraMap ℤ O)
    exact (hP.notMem_of_isCoprime_of_mem hxyO hxP) hyP
  have hiRoot : zetaO ^ (i : ℕ) ∈ Polynomial.nthRootsFinset p (1 : O) := by
    rw [Polynomial.mem_nthRootsFinset hp.out.pos]
    calc
      (zetaO ^ (i : ℕ)) ^ p = (zetaO ^ p) ^ (i : ℕ) := by
        rw [← pow_mul, ← pow_mul, mul_comm]
      _ = 1 := by rw [hzetaO.pow_eq_one, one_pow]
  have hjRoot : zetaO ^ (j : ℕ) ∈ Polynomial.nthRootsFinset p (1 : O) := by
    rw [Polynomial.mem_nthRootsFinset hp.out.pos]
    calc
      (zetaO ^ (j : ℕ)) ^ p = (zetaO ^ p) ^ (j : ℕ) := by
        rw [← pow_mul, ← pow_mul, mul_comm]
      _ = 1 := by rw [hzetaO.pow_eq_one, one_pow]
  have hpowers_ne : zetaO ^ (i : ℕ) ≠ zetaO ^ (j : ℕ) := by
    intro heq
    apply hij
    apply Fin.ext
    exact hzetaO.pow_inj i.isLt j.isLt heq
  have hassoc : Associated (zetaO - 1)
      (zetaO ^ (i : ℕ) - zetaO ^ (j : ℕ)) :=
    hzetaO.ntRootsFinset_pairwise_associated_sub_one_sub_of_prime hp.out
      hiRoot hjRoot hpowers_ne
  have hzeta_sub_one : zetaO - 1 ∈ P :=
    P.mem_of_dvd hassoc.dvd' hdiff
  have hpP : (p : O) ∈ P := by
    apply (Ideal.span_singleton_le_iff_mem P).mpr hzeta_sub_one
    letI : IsCyclotomicExtension {p ^ (0 + 1)} ℚ K := by simpa using hK
    have hzeta' : IsPrimitiveRoot zeta (p ^ (0 + 1)) := by simpa using hzeta
    exact IsCyclotomicExtension.Rat.p_mem_span_zeta_sub_one p 0 hzeta'
  letI : P.LiesOver (Ideal.span {(p : ℤ)}) := by
    rw [Ideal.liesOver_iff]
    refine Ideal.IsMaximal.eq_of_le (Int.ideal_span_isMaximal_of_prime p) IsPrime.ne_top' ?_
    rw [Ideal.span_singleton_le_iff_mem, Ideal.mem_comap, algebraMap_int_eq, map_natCast]
    exact hpP
  have hzeta_pow_sub_one : zetaO ^ (i : ℕ) - 1 ∈ P := by
    apply P.mem_of_dvd _ hzeta_sub_one
    simpa only [one_pow] using sub_dvd_pow_sub_pow zetaO 1 (i : ℕ)
  have hsumO : xO + yO ∈ P := by
    have hmul : (zetaO ^ (i : ℕ) - 1) * yO ∈ P :=
      P.mul_mem_right yO hzeta_pow_sub_one
    convert P.sub_mem hfi hmul using 1 ; ring
  have hsum_mem : x + y ∈ Ideal.span {(p : ℤ)} := by
    rw [Ideal.mem_of_liesOver P (Ideal.span {(p : ℤ)})]
    simpa [xO, yO, O, map_add] using hsumO
  have hp_sum : (p : ℤ) ∣ x + y := by
    simpa [Ideal.mem_span_singleton] using hsum_mem
  have hpow_sum : x ^ p + y ^ p ≡ x + y [ZMOD (p : ℤ)] :=
    (Int.ModEq.pow_prime_eq_self hp.out x).add (Int.ModEq.pow_prime_eq_self hp.out y)
  have hzpow_zero : z ^ p ≡ 0 [ZMOD (p : ℤ)] := by
    rw [← hFermat]
    exact hpow_sum.trans (Int.modEq_zero_iff_dvd.mpr hp_sum)
  have hz_zero : z ≡ 0 [ZMOD (p : ℤ)] :=
    (Int.ModEq.pow_prime_eq_self hp.out z).symm.trans hzpow_zero
  exact hpz (Int.modEq_zero_iff_dvd.mp hz_zero)

/-- The element-level formulation of Milne's Lemma 6.9. -/
theorem fermat_pairwise_elements {zeta : K}
    (hzeta : IsPrimitiveRoot zeta p) {x y z : ℤ} (hxy : IsCoprime x y)
    (hFermat : x ^ p + y ^ p = z ^ p) (hpz : ¬ (p : ℤ) ∣ z) :
    Pairwise (IsCoprime on fun i : Fin p ↦
      algebraMap ℤ (𝓞 K) x + hzeta.toInteger ^ (i : ℕ) * algebraMap ℤ (𝓞 K) y) := by
  have h := fermat_pairwise_coprime hzeta hxy hFermat hpz
  intro i j hij
  change IsCoprime
    (algebraMap ℤ (𝓞 K) x + hzeta.toInteger ^ (i : ℕ) * algebraMap ℤ (𝓞 K) y)
    (algebraMap ℤ (𝓞 K) x + hzeta.toInteger ^ (j : ℕ) * algebraMap ℤ (𝓞 K) y)
  rw [← Ideal.isCoprime_span_singleton_iff]
  exact h hij

end Submission.NumberTheory.Milne
