import Submission.Group.OpenRelators.NormalRelatorFactorization


open scoped Topology

noncomputable section

namespace Submission
namespace ONCompar

open PRFact
open ONFact

universe u w

variable
    {F : Type u}
    {G : Type u}
    [Group F]
    [TopologicalSpace F]
    [IsTopologicalGroup F]
    [Group G]
    {ι : Type w}
    {q : F →* G}
    {relator : ι → F}

/-- The ordinary finite layer cut out by one open-normal subgroup. -/
abbrev OpenNormalLayer
    (N : OpenNormalSubgroup F) :=
  F ⧸ (N : Subgroup F)

/-- The canonical quotient map into one open-normal finite layer. -/
abbrev openNormalLayer
    (N : OpenNormalSubgroup F) :
    F →* OpenNormalLayer N :=
  QuotientGroup.mk' (N : Subgroup F)

/--
The image of the candidate global kernel inside one open-normal finite layer.
-/
def kernelImage
    (q : F →* G)
    (N : OpenNormalSubgroup F) :
    Subgroup (OpenNormalLayer N) :=
  q.ker.map (openNormalLayer N)

/--
The image of the algebraic normal subgroup generated by the displayed
relators inside one open-normal finite layer.
-/
def relatorImage
    (relator : ι → F)
    (N : OpenNormalSubgroup F) :
    Subgroup (OpenNormalLayer N) :=
  (relationSubgroup relator).map (openNormalLayer N)

instance kernelImage_normal
    (q : F →* G)
    (N : OpenNormalSubgroup F) :
    (kernelImage q N).Normal := by
  exact (inferInstance : q.ker.Normal).map _
    (QuotientGroup.mk'_surjective (N : Subgroup F))

instance relatorImage_normal
    (relator : ι → F)
    (N : OpenNormalSubgroup F) :
    (relatorImage relator N).Normal := by
  exact (inferInstance : (relationSubgroup relator).Normal).map _
    (QuotientGroup.mk'_surjective (N : Subgroup F))

omit [IsTopologicalGroup F] in
/--
The finite-layer algebraic generation predicate is exactly inclusion of the
kernel image in the relator image.
-/
lemma algebraically_open_relator
    (q : F →* G)
    (relator : ι → F)
    (N : OpenNormalSubgroup F) :
    GeneratedAlgebraicallyOpen q relator N ↔
      kernelImage q N ≤ relatorImage relator N := by
  constructor
  · intro h z hz
    rcases hz with ⟨x, hx, rfl⟩
    exact h x hx
  · intro h x hx
    exact h ⟨x, hx, rfl⟩

omit [IsTopologicalGroup F] in
/--
If the candidate quotient kills the displayed relators, then the relator image
lies in the candidate-kernel image in every finite layer.
-/
lemma image_kills_relators
    (q : F →* G)
    (relator : ι → F)
    (N : OpenNormalSubgroup F)
    (hkill : KillsRelators relator q) :
    relatorImage relator N ≤ kernelImage q N := by
  exact Subgroup.map_mono
    ((kills_relators_relation relator q).mp hkill)

omit [IsTopologicalGroup F] in
/--
When the candidate quotient kills the displayed relators, algebraic
finite-layer generation is equality between the relator image and the
candidate-kernel image.
-/
lemma algebraically_open_kills
    (q : F →* G)
    (relator : ι → F)
    (N : OpenNormalSubgroup F)
    (hkill : KillsRelators relator q) :
    GeneratedAlgebraicallyOpen q relator N ↔
      kernelImage q N = relatorImage relator N := by
  rw [algebraically_open_relator]
  constructor
  · intro hkernel
    exact le_antisymm hkernel (image_kills_relators q relator N hkill)
  · intro heq
    exact heq.le

/--
The finite quotient of one open-normal layer obtained by algebraically killing
the displayed relator image.
-/
abbrev RelatorImageQuotient
    (relator : ι → F)
    (N : OpenNormalSubgroup F) :=
  OpenNormalLayer N ⧸ relatorImage relator N

/--
The finite quotient of one open-normal layer obtained by killing the image of
the candidate global kernel.
-/
abbrev KernelImageQuotient
    (q : F →* G)
    (N : OpenNormalSubgroup F) :=
  OpenNormalLayer N ⧸ kernelImage q N

/--
The canonical map from the relator quotient of a finite layer to the quotient
by the image of the candidate global kernel.  It exists as soon as the
candidate quotient kills the displayed relators.
-/
def relatorKernelComparison
    (q : F →* G)
    (relator : ι → F)
    (N : OpenNormalSubgroup F)
    (hkill : KillsRelators relator q) :
    RelatorImageQuotient relator N →* KernelImageQuotient q N :=
  QuotientGroup.lift
    (relatorImage relator N)
    (QuotientGroup.mk' (kernelImage q N))
    (by
      rw [QuotientGroup.ker_mk']
      exact image_kills_relators q relator N hkill)

omit [IsTopologicalGroup F] in
/--
The comparison map sends a finite-layer class to the class represented by the
same finite-layer element.
-/
lemma relator_comparison_mk
    (q : F →* G)
    (relator : ι → F)
    (N : OpenNormalSubgroup F)
    (hkill : KillsRelators relator q)
    (x : OpenNormalLayer N) :
    relatorKernelComparison q relator N hkill
        (QuotientGroup.mk' (relatorImage relator N) x) =
      QuotientGroup.mk' (kernelImage q N) x := by
  exact QuotientGroup.lift_mk' _ _ x

omit [IsTopologicalGroup F] in
/--
The comparison map is always surjective: both layer quotients are quotients of
the same finite layer.
-/
lemma relator_comparison_surjective
    (q : F →* G)
    (relator : ι → F)
    (N : OpenNormalSubgroup F)
    (hkill : KillsRelators relator q) :
    Function.Surjective (relatorKernelComparison q relator N hkill) := by
  exact QuotientGroup.lift_surjective_of_surjective
    (N := relatorImage relator N)
    (QuotientGroup.mk' (kernelImage q N))
    (QuotientGroup.mk'_surjective (kernelImage q N))
    (by
      rw [QuotientGroup.ker_mk']
      exact image_kills_relators q relator N hkill)

omit [IsTopologicalGroup F] in
/--
The comparison kernel is the image of the candidate-kernel image in the
relator quotient.
-/
lemma relator_image_comparison
    (q : F →* G)
    (relator : ι → F)
    (N : OpenNormalSubgroup F)
    (hkill : KillsRelators relator q) :
    (relatorKernelComparison q relator N hkill).ker =
      (kernelImage q N).map (QuotientGroup.mk' (relatorImage relator N)) := by
  simpa [relatorKernelComparison] using QuotientGroup.ker_lift
    (relatorImage relator N)
    (QuotientGroup.mk' (kernelImage q N))
    (by
      rw [QuotientGroup.ker_mk']
      exact image_kills_relators q relator N hkill)

omit [IsTopologicalGroup F] in
/--
The canonical finite-layer comparison is injective exactly when the candidate
kernel image already lies in the relator image.
-/
lemma relator_comparison_injective
    (q : F →* G)
    (relator : ι → F)
    (N : OpenNormalSubgroup F)
    (hkill : KillsRelators relator q) :
    Function.Injective (relatorKernelComparison q relator N hkill) ↔
      kernelImage q N ≤ relatorImage relator N := by
  rw [← MonoidHom.ker_eq_bot_iff]
  rw [relator_image_comparison]
  rw [Subgroup.map_eq_bot_iff]
  rw [QuotientGroup.ker_mk']

omit [IsTopologicalGroup F] in
/--
For a relator-killing candidate quotient, algebraic generation in one finite
layer is exactly injectivity of the canonical comparison of finite quotients.
-/
lemma algebraically_injective_kills
    (q : F →* G)
    (relator : ι → F)
    (N : OpenNormalSubgroup F)
    (hkill : KillsRelators relator q) :
    GeneratedAlgebraicallyOpen q relator N ↔
      Function.Injective (relatorKernelComparison q relator N hkill) := by
  rw [algebraically_open_relator]
  exact (relator_comparison_injective
    q relator N hkill).symm

omit [IsTopologicalGroup F] in
/--
For a relator-killing candidate quotient, algebraic generation in one finite
layer is exactly bijectivity of the canonical comparison of finite quotients.
-/
lemma algebraically_bijective_kills
    (q : F →* G)
    (relator : ι → F)
    (N : OpenNormalSubgroup F)
    (hkill : KillsRelators relator q) :
    GeneratedAlgebraicallyOpen q relator N ↔
      Function.Bijective (relatorKernelComparison q relator N hkill) := by
  rw [algebraically_injective_kills
    q relator N hkill]
  constructor
  · intro hinj
    exact ⟨hinj, relator_comparison_surjective q relator N hkill⟩
  · exact fun hbij => hbij.1

/--
The canonical comparison is an isomorphism precisely when it is bijective.
This named predicate lets later finite-layer arguments state their target
without unpacking the comparison map each time.
-/
def ImageComparisonIsomorphism
    (q : F →* G)
    (relator : ι → F)
    (N : OpenNormalSubgroup F)
    (hkill : KillsRelators relator q) :
    Prop :=
  Function.Bijective (relatorKernelComparison q relator N hkill)

omit [IsTopologicalGroup F] in
/--
For a relator-killing candidate quotient, algebraic generation in one finite
layer is exactly the canonical finite-layer comparison isomorphism predicate.
-/
lemma algebraically_iso_kills
    (q : F →* G)
    (relator : ι → F)
    (N : OpenNormalSubgroup F)
    (hkill : KillsRelators relator q) :
    GeneratedAlgebraicallyOpen q relator N ↔
      ImageComparisonIsomorphism q relator N hkill := by
  exact algebraically_bijective_kills
    q relator N hkill

omit [IsTopologicalGroup F] in
/--
For a relator-killing candidate quotient, algebraic generation in every
open-normal finite layer is exactly injectivity of every canonical finite-layer
comparison.
-/
lemma algebraically_kills_relators
    (q : F →* G)
    (relator : ι → F)
    (hkill : KillsRelators relator q) :
    GeneratedAlgebraicallyEvery q relator ↔
      ∀ N : OpenNormalSubgroup F,
        Function.Injective (relatorKernelComparison q relator N hkill) := by
  constructor
  · intro hgen N
    exact (algebraically_injective_kills
      q relator N hkill).mp (hgen N)
  · intro h N
    exact (algebraically_injective_kills
      q relator N hkill).mpr (h N)

omit [IsTopologicalGroup F] in
/--
For a relator-killing candidate quotient, algebraic generation in every
open-normal finite layer is exactly bijectivity of every canonical finite-layer
comparison.
-/
lemma algebraically_every_kills
    (q : F →* G)
    (relator : ι → F)
    (hkill : KillsRelators relator q) :
    GeneratedAlgebraicallyEvery q relator ↔
      ∀ N : OpenNormalSubgroup F,
        Function.Bijective (relatorKernelComparison q relator N hkill) := by
  constructor
  · intro hgen N
    exact (algebraically_bijective_kills
      q relator N hkill).mp (hgen N)
  · intro h N
    exact (algebraically_bijective_kills
      q relator N hkill).mpr (h N)

omit [IsTopologicalGroup F] in
/--
For a relator-killing candidate quotient, algebraic generation in every
open-normal finite layer is exactly the canonical comparison isomorphism
predicate in every finite layer.
-/
lemma algebraically_every_relators
    (q : F →* G)
    (relator : ι → F)
    (hkill : KillsRelators relator q) :
    GeneratedAlgebraicallyEvery q relator ↔
      ∀ N : OpenNormalSubgroup F,
        ImageComparisonIsomorphism q relator N hkill := by
  exact algebraically_every_kills
    q relator hkill

/--
For a pro-`p` source and a relator-killing candidate quotient, the finite
relator quotient factorization property is exactly the canonical comparison
isomorphism predicate in every open-normal finite layer.
-/
lemma property_kills_relators
    {p : ℕ}
    [CompactSpace F]
    (hProP : ProP.ProPGroup p F)
    (q : F →* G)
    (relator : ι → F)
    (hkill : KillsRelators relator q) :
    PRQuotie.QuotientFactorizationProperty p relator q ↔
      ∀ N : OpenNormalSubgroup F,
        ImageComparisonIsomorphism q relator N hkill := by
  rw [ONFact.property_every_pro
    hProP q]
  exact algebraically_every_relators
    q relator hkill

/--
Under algebraic generation in one finite layer, the relator quotient and the
candidate-kernel-image quotient are canonically isomorphic.
-/
def relatorComparisonEquiv
    (q : F →* G)
    (relator : ι → F)
    (N : OpenNormalSubgroup F)
    (hkill : KillsRelators relator q)
    (hgen : GeneratedAlgebraicallyOpen q relator N) :
    RelatorImageQuotient relator N ≃* KernelImageQuotient q N :=
  MulEquiv.ofBijective
    (relatorKernelComparison q relator N hkill)
    ((algebraically_bijective_kills
      q relator N hkill).mp hgen)

omit [IsTopologicalGroup F] in
/--
The candidate-kernel image in one layer is also the image of the subgroup
`N ⊔ ker(q)` before passing to the quotient by `N`.
-/
lemma sup_open_image
    (q : F →* G)
    (N : OpenNormalSubgroup F) :
    (((N : Subgroup F) ⊔ q.ker).map (openNormalLayer N)) =
      kernelImage q N := by
  rw [Subgroup.map_sup]
  rw [QuotientGroup.map_mk'_self]
  rw [bot_sup_eq]
  rfl

/--
Quotienting one finite layer by the candidate-kernel image is canonically the
same as quotienting the original group by `N ⊔ ker(q)`.
-/
def kernelImageSup
    (q : F →* G)
    (N : OpenNormalSubgroup F) :
    KernelImageQuotient q N ≃* F ⧸ ((N : Subgroup F) ⊔ q.ker) :=
  (QuotientGroup.quotientMulEquivOfEq
      (sup_open_image q N).symm).trans
    (QuotientGroup.quotientQuotientEquivQuotient
      (N : Subgroup F)
      ((N : Subgroup F) ⊔ q.ker)
      le_sup_left)

end ONCompar
end Submission
