import Towers.NumberTheory.Discriminant.FiniteIndexDiscriminant
import Towers.NumberTheory.Discriminant.PolynomialExamples
import Towers.NumberTheory.Discriminant.PowerBasisDiscriminant

/-!
# Milne, Examples 2.36 and 2.37

The squarefree discriminants `-23` and `-31` show that the powers of a root
of `X^3 - X - 1` or `X^3 + X + 1` form an integral basis.  Consequently the
corresponding ring of integers is generated by that root.
-/

namespace Towers.NumberTheory.Milne

open Module NumberField Polynomial
open scoped NumberField

noncomputable section

private theorem cube_basis_dim
    {K : Type*} [Field K] [NumberField K]
    (B : PowerBasis ℚ K)
    (hmin : minpoly ℚ B.gen = X ^ 3 - X - 1) :
    B.dim = 3 := by
  rw [← B.natDegree_minpoly, hmin]
  compute_degree
  norm_num

/-- The rational power basis attached to a root of `X^3 - X - 1` has
discriminant `-23`. -/
theorem first_example_discr
    {K : Type*} [Field K] [NumberField K]
    (B : PowerBasis ℚ K)
    (hmin : minpoly ℚ B.gen = X ^ 3 - X - 1) :
    Algebra.discr ℚ B.basis = -23 := by
  rw [basis_discr_minpoly B, hmin]
  convert discr_cube_b (-1 : ℚ) (-1 : ℚ) using 1 <;>
    norm_num [sub_eq_add_neg]

private theorem squarefree_neg_twenty : Squarefree (-23 : ℤ) := by
  have hp : Prime (23 : ℤ) := by norm_num
  rw [(show Associated (-23 : ℤ) 23 from
    (Associated.refl (23 : ℤ)).neg_left).squarefree_iff]
  exact hp.squarefree

/-- Example 2.36: `1, alpha, alpha^2` form an integral basis. -/
theorem first_cubic_example
    {K : Type*} [Field K] [NumberField K]
    (alpha : RingOfIntegers K)
    (B : PowerBasis ℚ K)
    (hgen : B.gen = (alpha : K))
    (hmin : minpoly ℚ B.gen = X ^ 3 - X - 1) :
    ∃ PB : PowerBasis ℤ (RingOfIntegers K),
      PB.gen = alpha ∧ PB.dim = 3 := by
  obtain ⟨PB, hPBgen, hPBdim⟩ :=
    integers_discr_squarefree
      alpha B hgen (-23) (first_example_discr B hmin)
        squarefree_neg_twenty
  exact ⟨PB, hPBgen, hPBdim.trans
    (cube_basis_dim B hmin)⟩

/-- Example 2.36: the full ring of integers is `ℤ[alpha]`. -/
theorem first_example_adjoin
    {K : Type*} [Field K] [NumberField K]
    (alpha : RingOfIntegers K)
    (B : PowerBasis ℚ K)
    (hgen : B.gen = (alpha : K))
    (hmin : minpoly ℚ B.gen = X ^ 3 - X - 1) :
    Algebra.adjoin ℤ ({alpha} : Set (RingOfIntegers K)) = ⊤ := by
  exact adjoin_discr_squarefree
    alpha B hgen (-23) (first_example_discr B hmin)
      squarefree_neg_twenty

private theorem first_example_monic :
    (X ^ 3 - X - 1 : ℚ[X]).Monic := by
  rw [show (X ^ 3 - X - 1 : ℚ[X]) = X ^ 3 + (-X - 1) by ring]
  apply monic_X_pow_add
  compute_degree
  norm_num

/-- Example 2.36 in the source's literal presentation.  From a root `alpha`
which generates `K`, this constructs its integral lift and proves both the
integral-basis and ring-of-integers conclusions. -/
theorem example_adjoin_top
    {K : Type*} [Field K] [NumberField K]
    (alpha : K)
    (hroot : Polynomial.aeval alpha (X ^ 3 - X - 1 : ℚ[X]) = 0)
    (hadjoin : Algebra.adjoin ℚ ({alpha} : Set K) = ⊤) :
    ∃ alphaInt : RingOfIntegers K,
      (alphaInt : K) = alpha ∧
      (∃ PB : PowerBasis ℤ (RingOfIntegers K),
        PB.gen = alphaInt ∧ PB.dim = 3) ∧
      Algebra.adjoin ℤ ({alphaInt} : Set (RingOfIntegers K)) = ⊤ := by
  have halphaIntegral : IsIntegral ℤ alpha := by
    refine ⟨X ^ 3 - X - 1, ?_, ?_⟩
    · rw [show (X ^ 3 - X - 1 : ℤ[X]) = X ^ 3 + (-X - 1) by ring]
      apply monic_X_pow_add
      compute_degree
      norm_num
    · change Polynomial.aeval alpha (X ^ 3 - X - 1 : ℤ[X]) = 0
      rw [← Polynomial.aeval_map_algebraMap ℚ]
      simpa using hroot
  let alphaInt : RingOfIntegers K := ⟨alpha, halphaIntegral⟩
  let B : PowerBasis ℚ K :=
    PowerBasis.ofAdjoinEqTop (Algebra.IsIntegral.isIntegral alpha) hadjoin
  have hBgen : B.gen = alpha := by
    exact PowerBasis.ofAdjoinEqTop_gen
      (Algebra.IsIntegral.isIntegral alpha) hadjoin
  have hmin : minpoly ℚ B.gen = X ^ 3 - X - 1 := by
    exact (minpoly.eq_of_irreducible_of_monic
      irreducible_cube_sub (by simpa [hBgen] using hroot)
        first_example_monic).symm
  have hgenInt : B.gen = (alphaInt : K) := by
    exact hBgen
  refine ⟨alphaInt, rfl, ?_, ?_⟩
  · exact first_cubic_example alphaInt B hgenInt hmin
  · exact first_example_adjoin alphaInt B hgenInt hmin

private theorem cube_x_dim
    {K : Type*} [Field K] [NumberField K]
    (B : PowerBasis ℚ K)
    (hmin : minpoly ℚ B.gen = X ^ 3 + X + 1) :
    B.dim = 3 := by
  rw [← B.natDegree_minpoly, hmin]
  compute_degree
  norm_num

/-- The rational power basis attached to a root of `X^3 + X + 1` has
discriminant `-31`. -/
theorem second_example_discr
    {K : Type*} [Field K] [NumberField K]
    (B : PowerBasis ℚ K)
    (hmin : minpoly ℚ B.gen = X ^ 3 + X + 1) :
    Algebra.discr ℚ B.basis = -31 := by
  rw [basis_discr_minpoly B, hmin]
  convert discr_cube_b (1 : ℚ) (1 : ℚ) using 1 <;>
    norm_num

private theorem squarefree_neg_thirty : Squarefree (-31 : ℤ) := by
  have hp : Prime (31 : ℤ) := by norm_num
  rw [(show Associated (-31 : ℤ) 31 from
    (Associated.refl (31 : ℤ)).neg_left).squarefree_iff]
  exact hp.squarefree

/-- Example 2.37: `1, alpha, alpha^2` form an integral basis. -/
theorem second_cubic_example
    {K : Type*} [Field K] [NumberField K]
    (alpha : RingOfIntegers K)
    (B : PowerBasis ℚ K)
    (hgen : B.gen = (alpha : K))
    (hmin : minpoly ℚ B.gen = X ^ 3 + X + 1) :
    ∃ PB : PowerBasis ℤ (RingOfIntegers K),
      PB.gen = alpha ∧ PB.dim = 3 := by
  obtain ⟨PB, hPBgen, hPBdim⟩ :=
    integers_discr_squarefree
      alpha B hgen (-31) (second_example_discr B hmin)
        squarefree_neg_thirty
  exact ⟨PB, hPBgen, hPBdim.trans
    (cube_x_dim B hmin)⟩

/-- Example 2.37: the full ring of integers is `ℤ[alpha]`. -/
theorem example_integers_adjoin
    {K : Type*} [Field K] [NumberField K]
    (alpha : RingOfIntegers K)
    (B : PowerBasis ℚ K)
    (hgen : B.gen = (alpha : K))
    (hmin : minpoly ℚ B.gen = X ^ 3 + X + 1) :
    Algebra.adjoin ℤ ({alpha} : Set (RingOfIntegers K)) = ⊤ := by
  exact adjoin_discr_squarefree
    alpha B hgen (-31) (second_example_discr B hmin)
      squarefree_neg_thirty

private theorem second_example_monic :
    (X ^ 3 + X + 1 : ℚ[X]).Monic := by
  rw [show (X ^ 3 + X + 1 : ℚ[X]) = X ^ 3 + (X + 1) by ring]
  apply monic_X_pow_add
  compute_degree
  norm_num

/-- Example 2.37 in the source's literal root-generated presentation. -/
theorem second_example_top
    {K : Type*} [Field K] [NumberField K]
    (alpha : K)
    (hroot : Polynomial.aeval alpha (X ^ 3 + X + 1 : ℚ[X]) = 0)
    (hadjoin : Algebra.adjoin ℚ ({alpha} : Set K) = ⊤) :
    ∃ alphaInt : RingOfIntegers K,
      (alphaInt : K) = alpha ∧
      (∃ PB : PowerBasis ℤ (RingOfIntegers K),
        PB.gen = alphaInt ∧ PB.dim = 3) ∧
      Algebra.adjoin ℤ ({alphaInt} : Set (RingOfIntegers K)) = ⊤ := by
  have halphaIntegral : IsIntegral ℤ alpha := by
    refine ⟨X ^ 3 + X + 1, ?_, ?_⟩
    · rw [show (X ^ 3 + X + 1 : ℤ[X]) = X ^ 3 + (X + 1) by ring]
      apply monic_X_pow_add
      compute_degree
      norm_num
    · change Polynomial.aeval alpha (X ^ 3 + X + 1 : ℤ[X]) = 0
      rw [← Polynomial.aeval_map_algebraMap ℚ]
      simpa using hroot
  let alphaInt : RingOfIntegers K := ⟨alpha, halphaIntegral⟩
  let B : PowerBasis ℚ K :=
    PowerBasis.ofAdjoinEqTop (Algebra.IsIntegral.isIntegral alpha) hadjoin
  have hBgen : B.gen = alpha := by
    exact PowerBasis.ofAdjoinEqTop_gen
      (Algebra.IsIntegral.isIntegral alpha) hadjoin
  have hmin : minpoly ℚ B.gen = X ^ 3 + X + 1 := by
    exact (minpoly.eq_of_irreducible_of_monic
      irreducible_cube_add (by simpa [hBgen] using hroot)
        second_example_monic).symm
  have hgenInt : B.gen = (alphaInt : K) := by
    exact hBgen
  refine ⟨alphaInt, rfl, ?_, ?_⟩
  · exact second_cubic_example alphaInt B hgenInt hmin
  · exact example_integers_adjoin alphaInt B hgenInt hmin

end

end Towers.NumberTheory.Milne
