import Mathlib
import Towers.NumberTheory.Ramification.EisensteinRamification

/-!
# Milne, Algebraic Number Theory: two-hour examination, Question 2(a)

If `alpha` is a root of `X ^ n - 2`, with `n >= 2`, and `K = Q(alpha)`, then
`[K : Q] = n`.  The proof is Eisenstein's criterion at the prime `2`.
-/

namespace Towers.NumberTheory.Milne

noncomputable section

open Module Polynomial IntermediateField

/-- The integer polynomial `X ^ n - 2` is Eisenstein at the ideal generated by `2`. -/
theorem x_sub_eisenstein (n : ℕ) (hn : 0 < n) :
    (X ^ n - C (2 : ℤ)).IsEisensteinAt (Ideal.span {(2 : ℤ)}) := by
  have hp : (Ideal.span {(2 : ℤ)}).IsPrime :=
    (Ideal.span_singleton_prime (by norm_num : (2 : ℤ) ≠ 0)).mpr
      (Nat.prime_iff_prime_int.mp Nat.prime_two)
  refine (monic_X_pow_sub_C (2 : ℤ) hn.ne').isEisensteinAt_of_mem_of_notMem ?_ ?_ ?_
  · exact hp.ne_top
  · intro i hi
    rw [natDegree_X_pow_sub_C] at hi
    rw [coeff_sub, coeff_X_pow, coeff_C]
    by_cases hi0 : i = 0
    · subst i
      rw [if_neg hn.ne'.symm, if_pos rfl]
      simp
    · have hin : i ≠ n := Nat.ne_of_lt hi
      rw [if_neg hin, if_neg hi0, sub_zero]
      exact Ideal.zero_mem _
  · rw [coeff_zero_eq_eval_zero, eval_sub, eval_pow, eval_X, eval_C, zero_pow hn.ne',
      zero_sub, Ideal.span_singleton_pow, Ideal.mem_span_singleton]
    norm_num

/-- Eisenstein irreducibility of `X ^ n - 2` over the rationals. -/
theorem irreducible_x_rat (n : ℕ) (hn : 0 < n) :
    Irreducible (X ^ n - C (2 : ℚ)) := by
  have h := eisenstein_irreducible_fraction (A := ℤ) (K := ℚ)
    ((Ideal.span_singleton_prime (by norm_num : (2 : ℤ) ≠ 0)).mpr
      (Nat.prime_iff_prime_int.mp Nat.prime_two))
    (x_sub_eisenstein n hn)
    (monic_X_pow_sub_C (2 : ℤ) hn.ne')
    (by rw [natDegree_X_pow_sub_C]; exact hn)
  simpa using h

/-- A root of `X ^ n - 2` has that polynomial as its minimal polynomial over `Q`. -/
theorem minpoly_x_two
    {K : Type*} [Field K] [Algebra ℚ K]
    {n : ℕ} (hn : 0 < n) {α : K} (hα : α ^ n = algebraMap ℚ K 2) :
    minpoly ℚ α = X ^ n - C (2 : ℚ) := by
  have heval : aeval α (X ^ n - C (2 : ℚ)) = 0 := by
    simp [hα]
  exact (minpoly.eq_of_irreducible_of_monic
    (irreducible_x_rat n hn) heval
    (monic_X_pow_sub_C (2 : ℚ) hn.ne')).symm

/-- Milne's examination answer: if `K = Q(alpha)` and `alpha ^ n = 2`, then `[K : Q] = n`. -/
theorem two_adjoin_top
    {K : Type*} [Field K] [Algebra ℚ K]
    {n : ℕ} (hn : 2 ≤ n) {α : K}
    (hα : α ^ n = algebraMap ℚ K 2) (hgen : ℚ⟮α⟯ = ⊤) :
    finrank ℚ K = n := by
  have hnpos : 0 < n := hn.trans_lt' (by norm_num)
  have hint : IsIntegral ℚ α := by
    refine ⟨X ^ n - C (2 : ℚ), monic_X_pow_sub_C (2 : ℚ) hnpos.ne', ?_⟩
    simp [hα]
  rw [← IntermediateField.finrank_top', ← hgen,
    IntermediateField.adjoin.finrank hint, minpoly_x_two hnpos hα,
    natDegree_X_pow_sub_C]

end

end Towers.NumberTheory.Milne
