import Mathlib.LinearAlgebra.QuadraticForm.Basic
import Mathlib.LinearAlgebra.QuadraticForm.IsometryEquiv
import Mathlib.LinearAlgebra.Reflection

/-!
# Chapter VIII, Section 6: symmetries of a quadratic space

For a vector `y` of nonzero quadratic value, the source defines the reflection

`tau_y(x) = x - (2 B(x,y) / Q(y)) y`.

Mathlib's polar form is `2 B`, so the construction is the generic module
reflection for the normalized linear functional `x |-> polar Q y x / Q(y)`.
-/

namespace Towers.CField.QForms

variable {k V : Type*} [Field k] [AddCommGroup V] [Module k V]

/-- The normalized linear functional defining reflection in the hyperplane
orthogonal to `y`. -/
noncomputable def symmetryFunctional
    (Q : QuadraticForm k V) (y : V) : Module.Dual k V :=
  (Q y)⁻¹ • Q.polarBilin y

theorem symmetryFunctional_apply
    (Q : QuadraticForm k V) (y x : V) :
    symmetryFunctional Q y x = (Q y)⁻¹ * QuadraticMap.polar Q y x := by
  simp [symmetryFunctional, QuadraticMap.polarBilin_apply_apply]

theorem symmetryFunctional_self
    (Q : QuadraticForm k V) {y : V} (hy : Q y ≠ 0) :
    symmetryFunctional Q y y = 2 := by
  rw [symmetryFunctional_apply, QuadraticMap.polar_self]
  simp only [nsmul_eq_mul]
  field_simp [hy]
  norm_num

/-- The symmetry with respect to the line generated by `y`. -/
noncomputable def symmetry
    (Q : QuadraticForm k V) (y : V) (hy : Q y ≠ 0) : V ≃ₗ[k] V :=
  Module.reflection (symmetryFunctional_self Q hy)

theorem symmetry_apply
    (Q : QuadraticForm k V) (y : V) (hy : Q y ≠ 0) (x : V) :
    symmetry Q y hy x =
      x - (QuadraticMap.polar Q x y / Q y) • y := by
  rw [symmetry, Module.reflection_apply, symmetryFunctional_apply]
  rw [QuadraticMap.polar_comm]
  congr 2
  rw [div_eq_mul_inv, mul_comm]

/-- The symmetry reverses its defining vector. -/
@[simp]
theorem symmetry_apply_self [NeZero (2 : k)]
    (Q : QuadraticForm k V) (y : V) (hy : Q y ≠ 0) :
    symmetry Q y hy y = -y := by
  exact Module.reflection_apply_self (symmetryFunctional_self Q hy)

/-- The symmetry is an involution. -/
theorem symmetry_involutive [NeZero (2 : k)]
    (Q : QuadraticForm k V) (y : V) (hy : Q y ≠ 0) :
    Function.Involutive (symmetry Q y hy) :=
  Module.involutive_reflection (symmetryFunctional_self Q hy)

/-- The symmetry fixes every vector orthogonal to its defining line. -/
theorem symmetry_ortho [NeZero (2 : k)]
    (Q : QuadraticForm k V) (y : V) (hy : Q y ≠ 0) {x : V}
    (hxy : QuadraticMap.polar Q x y = 0) :
    symmetry Q y hy x = x := by
  rw [symmetry_apply, hxy]
  simp

/-- The symmetry preserves the quadratic form. -/
theorem symmetry_preserves [NeZero (2 : k)]
    (Q : QuadraticForm k V) (y : V) (hy : Q y ≠ 0) (x : V) :
    Q (symmetry Q y hy x) = Q x := by
  let c : k := QuadraticMap.polar Q x y / Q y
  rw [symmetry_apply]
  change Q (x - c • y) = Q x
  rw [sub_eq_add_neg]
  rw [QuadraticMap.map_add Q, Q.map_neg, Q.map_smul]
  rw [QuadraticMap.polar_neg_right Q, QuadraticMap.polar_smul_right Q]
  simp only [smul_eq_mul]
  dsimp [c]
  field_simp [hy]
  ring

/-- The symmetry, bundled as an isometry of the quadratic space. -/
noncomputable def symmetryIsometryEquiv [NeZero (2 : k)]
    (Q : QuadraticForm k V) (y : V) (hy : Q y ≠ 0) :
    Q.IsometryEquiv Q where
  toLinearEquiv := symmetry Q y hy
  map_app' := symmetry_preserves Q y hy

end Towers.CField.QForms
