import Mathlib.RingTheory.DedekindDomain.AdicValuation
import Mathlib.RingTheory.LocalRing.RingHom.Basic
import Towers.NumberTheory.Locals.CompleteDiscreteExtension
import Towers.NumberTheory.Locals.CompleteDVRHenselian
import Towers.NumberTheory.Locals.TotallyRamifiedEisenstein
import Towers.NumberTheory.Locals.MaximalUnramifiedExtension


/-!
# The unramified/totally ramified decomposition

This file completes the local decomposition used in Milne, Corollary 7.51.
A finite local extension is first generated by a lift of a primitive residue
element.  The resulting intermediate DVR is unramified, and the remaining
extension is totally ramified because its residue-field map is onto.
-/

namespace Towers.NumberTheory.Milne

open Algebra IsLocalRing
open scoped NNReal NormedField Valued

noncomputable section

attribute [local instance] Ideal.Quotient.field

/-- Eisenstein conditions are invariant under a change of coefficient ring
by a ring equivalence.  This is the coefficient-level transport used when
replacing an abstract DVR by a compatible norm-defined integer ring. -/
theorem Polynomial.IsEisensteinAt.map_rin
    {R S : Type*} [CommRing R] [CommRing S]
    {f : Polynomial R} {p : Ideal R} (hf : f.IsEisensteinAt p)
    (e : R ≃+* S) :
    (f.map e).IsEisensteinAt (p.map e) := by
  constructor
  · rw [Polynomial.leadingCoeff_map_of_injective e.injective f]
    simpa using hf.leading
  · intro n hn
    rw [Polynomial.natDegree_map_eq_of_injective e.injective f] at hn
    rw [Polynomial.coeff_map]
    exact Ideal.mem_map_of_mem e (hf.mem hn)
  · rw [Polynomial.coeff_map, ← Ideal.map_pow]
    simpa using hf.notMem

section IntegralClosureOfValuedIntegers

variable (K L : Type*)
  [NontriviallyNormedField K] [CompleteSpace K] [IsUltrametricDist K]
  [NontriviallyNormedField L] [IsUltrametricDist L]
  [NormedAlgebra K L] [Algebra.IsAlgebraic K L]

attribute [local instance] NormedField.toValued

omit [CompleteSpace K] [Algebra.IsAlgebraic K L] in
theorem valuation_normed_algebra :
    Valuation.HasExtension
      (NormedField.valuation (K := K))
      (NormedField.valuation (K := L)) := by
  constructor
  intro x y
  simp only [Valuation.comap_apply, NormedField.valuation_apply,
    nnnorm_algebraMap']

set_option maxHeartbeats 1000000 in
-- Reconstructing the lifted minimal polynomial through both integer rings is expensive.
/-- For an algebraic extension of a complete nonarchimedean normed field,
the norm-defined integer ring upstairs is the integral closure of the
norm-defined integer ring downstairs. -/
theorem valued_integer_closure :
    letI : Valuation.HasExtension
        (NormedField.valuation (K := K))
        (NormedField.valuation (K := L)) :=
      valuation_normed_algebra K L
    IsIntegralClosure 𝒪[L] 𝒪[K] L := by
  letI : Valuation.HasExtension
      (NormedField.valuation (K := K))
      (NormedField.valuation (K := L)) :=
    valuation_normed_algebra K L
  letI : Algebra.IsIntegral 𝒪[K] 𝒪[L] := by
    rw [Algebra.isIntegral_def]
    intro x
    let y : L := x
    let p : Polynomial K := minpoly K y
    have hpmonic : p.Monic :=
      minpoly.monic (Algebra.IsIntegral.isIntegral y)
    have hynorm : ‖y‖ ≤ 1 := by
      have hy : (NormedField.valuation (K := L)) y ≤ 1 := x.property
      exact_mod_cast hy
    have hspectral : spectralValue p ≤ 1 := by
      change spectralNorm K L y ≤ 1
      rw [← NormedAlgebra.norm_eq_spectralNorm K]
      exact hynorm
    have hcoeff : ∀ n : ℕ, ‖p.coeff n‖ ≤ 1 :=
      (spectralValue_le_one_iff hpmonic).mp hspectral
    have hpcoeffs : (↑p.coeffs : Set K) ⊆ 𝒪[K] := by
      intro c hc
      change ‖c‖₊ ≤ 1
      obtain ⟨n, _hn, rfl⟩ := Polynomial.mem_coeffs_iff.mp hc
      exact_mod_cast hcoeff n
    let q : Polynomial 𝒪[K] := p.toSubring 𝒪[K] hpcoeffs
    refine ⟨q, (Polynomial.monic_toSubring p 𝒪[K] hpcoeffs).mpr hpmonic, ?_⟩
    apply Subtype.ext
    change (𝒪[L]).subtype
        (Polynomial.eval₂ (algebraMap 𝒪[K] 𝒪[L]) x q) =
      (𝒪[L]).subtype 0
    rw [Polynomial.hom_eval₂]
    have hmap : (𝒪[L]).subtype.comp (algebraMap 𝒪[K] 𝒪[L]) =
        (algebraMap K L).comp (𝒪[K]).subtype := rfl
    rw [hmap, ← Polynomial.eval₂_map, Polynomial.map_toSubring]
    change Polynomial.eval₂ (algebraMap K L) y p = 0
    exact minpoly.aeval K y
  letI : IsFractionRing 𝒪[L] L :=
    (Valuation.integer.integers
      (NormedField.valuation (K := L))).isFractionRing
  letI : IsIntegrallyClosed 𝒪[L] :=
    (Valuation.integer.integers
      (NormedField.valuation (K := L))).isIntegrallyClosed
  exact IsIntegralClosure.of_isIntegrallyClosed 𝒪[L] 𝒪[K] L

/-- The valuation ring of an algebraically closed nonarchimedean field is
Henselian, without any completeness hypothesis on the field.

A monic polynomial over the valuation ring splits in the algebraically
closed fraction field.  Its roots are integral over the valuation ring, so
integral closedness puts them back in the valuation ring.  Reducing this
factorization shows that every simple residue root (in fact, every residue
root) lifts. -/
theorem valued_henselian_closed
    (L : Type*) [NontriviallyNormedField L] [IsUltrametricDist L]
    [IsAlgClosed L] :
    HenselianLocalRing 𝒪[L] := by
  apply ((HenselianLocalRing.TFAE 𝒪[L]).out 1 0).mp
  intro f hf a₀ ha₀ _ha₀simple
  have hsplitsL :
      (f.map (Valued.integer L).subtype).Splits :=
    IsAlgClosed.splits _
  have hsplits : f.Splits := by
    apply hsplitsL.of_splits_map_of_injective Subtype.val_injective
    intro x hx
    have hxroot : (f.map (Valued.integer L).subtype).eval x = 0 :=
      (Polynomial.mem_roots (hf.map _).ne_zero).mp hx
    have hxint : IsIntegral 𝒪[L] x := by
      refine ⟨f, hf, ?_⟩
      have hmap : algebraMap 𝒪[L] L = (Valued.integer L).subtype := by
        ext y
        rfl
      rw [hmap, ← Polynomial.eval_map]
      exact hxroot
    obtain ⟨y, hy⟩ := IsIntegrallyClosed.isIntegral_iff.mp hxint
    exact ⟨y, hy⟩
  have hfres0 : f.map (residue 𝒪[L]) ≠ 0 := (hf.map _).ne_zero
  have ha₀mem : a₀ ∈ (f.map (residue 𝒪[L])).roots := by
    apply (Polynomial.mem_roots hfres0).mpr
    have ha₀' := ha₀
    rw [Polynomial.aeval_def, ResidueField.algebraMap_eq,
      ← Polynomial.eval_map] at ha₀'
    exact ha₀'
  rw [hsplits.roots_map_of_ne_zero hfres0, Multiset.mem_map] at ha₀mem
  obtain ⟨a, ha, hresidue⟩ := ha₀mem
  refine ⟨a, (Polynomial.mem_roots hf.ne_zero).mp ha, ?_⟩
  exact hresidue

set_option synthInstance.maxHeartbeats 200000 in
-- The residue-field tower instance is expensive to synthesize on Lean 4.30.
/-- For an algebraically closed algebraic extension of a complete
nonarchimedean field, the residue field of the extended norm valuation is an
algebraic closure of the base residue field.

This is Corollary 7.52 for the specific prolongation selected by the norm on
`L`.  The identification of `𝒪[L]` with the integral closure of `𝒪[K]` is
provided by `valued_integer_closure`. -/
theorem residue_valued_closure
    (K L : Type*)
    [NontriviallyNormedField K] [CompleteSpace K] [IsUltrametricDist K]
    [NontriviallyNormedField L] [IsUltrametricDist L]
    [NormedAlgebra K L] [Algebra.IsAlgebraic K L] [IsAlgClosed L] :
    letI : Valuation.HasExtension
        (NormedField.valuation (K := K))
        (NormedField.valuation (K := L)) :=
      valuation_normed_algebra K L
    IsAlgClosure (ResidueField 𝒪[K]) (ResidueField 𝒪[L]) := by
  letI : Valuation.HasExtension
      (NormedField.valuation (K := K))
      (NormedField.valuation (K := L)) :=
    valuation_normed_algebra K L
  letI : IsIntegralClosure 𝒪[L] 𝒪[K] L :=
    valued_integer_closure K L
  letI : Algebra.IsIntegral 𝒪[K] 𝒪[L] :=
    IsIntegralClosure.isIntegral_algebra 𝒪[K] L
  letI : Algebra.IsIntegral (ResidueField 𝒪[K]) (ResidueField 𝒪[L]) := by
    change Algebra.IsIntegral
      (𝒪[K] ⧸ maximalIdeal 𝒪[K]) (𝒪[L] ⧸ maximalIdeal 𝒪[L])
    infer_instance
  apply IsAlgClosure.of_splits
  intro f₀ hf₀monic _hf₀irreducible
  have hf₀lift : f₀ ∈ Polynomial.lifts (residue 𝒪[K]) :=
    Polynomial.map_surjective (residue 𝒪[K])
      Ideal.Quotient.mk_surjective f₀
  obtain ⟨f, hfmap, _hfdegree, hfmonic⟩ :=
    Polynomial.lifts_and_natDegree_eq_and_monic hf₀lift hf₀monic
  have hsplitsL :
      (f.map (algebraMap 𝒪[K] L)).Splits :=
    IsAlgClosed.splits _
  have hmap : algebraMap 𝒪[K] L =
      (Valued.integer L).subtype.comp (algebraMap 𝒪[K] 𝒪[L]) := by
    ext y
    rfl
  have hsplitsB : (f.map (algebraMap 𝒪[K] 𝒪[L])).Splits := by
    apply Polynomial.Splits.of_splits_map_of_injective
      (i := (Valued.integer L).subtype) Subtype.val_injective
    · rw [Polynomial.map_map, ← hmap]
      exact hsplitsL
    · intro x hx
      have hxroot :
          ((f.map (algebraMap 𝒪[K] 𝒪[L])).map
            (Valued.integer L).subtype).eval x = 0 :=
        (Polynomial.mem_roots
          (((hfmonic.map (algebraMap 𝒪[K] 𝒪[L])).map
            (Valued.integer L).subtype).ne_zero)).mp hx
      have hxintegral : IsIntegral 𝒪[K] x := by
        refine ⟨f, hfmonic, ?_⟩
        rw [hmap, ← Polynomial.eval_map]
        rw [← Polynomial.map_map]
        exact hxroot
      obtain ⟨b, hb⟩ :=
        (IsIntegralClosure.isIntegral_iff (R := 𝒪[K]) (A := 𝒪[L])
          (B := L)).mp hxintegral
      exact ⟨b, hb⟩
  have hsplitsResidue := hsplitsB.map (residue 𝒪[L])
  have hreduce :
      (f.map (algebraMap 𝒪[K] 𝒪[L])).map (residue 𝒪[L]) =
        f₀.map (algebraMap (ResidueField 𝒪[K]) (ResidueField 𝒪[L])) := by
    rw [← hfmap]
    ext n
    simp only [Polynomial.coeff_map]
    exact (IsLocalRing.ResidueField.algebraMap_residue (f.coeff n)).symm
  rw [hreduce] at hsplitsResidue
  exact hsplitsResidue

end IntegralClosureOfValuedIntegers

section FiniteValuedExtension

variable (K L : Type*)
  [NontriviallyNormedField K] [CompleteSpace K] [IsUltrametricDist K]
  [NontriviallyNormedField L] [IsUltrametricDist L]
  [NormedAlgebra K L] [FiniteDimensional K L]
  [Algebra.IsSeparable K L]
  [IsDiscreteValuationRing 𝒪[K]]

attribute [local instance] NormedField.toValued

/-- The integer ring of a finite extension of a complete discretely valued
field is finite over the base integer ring. -/
theorem valued_integer_module :
    letI : Valuation.HasExtension
        (NormedField.valuation (K := K))
        (NormedField.valuation (K := L)) :=
      valuation_normed_algebra K L
    Module.Finite 𝒪[K] 𝒪[L] := by
  letI : Valuation.HasExtension
      (NormedField.valuation (K := K))
      (NormedField.valuation (K := L)) :=
    valuation_normed_algebra K L
  letI : IsIntegralClosure 𝒪[L] 𝒪[K] L :=
    valued_integer_closure K L
  exact IsIntegralClosure.finite 𝒪[K] K L 𝒪[L]

include K

/-- Discreteness of the valuation ring passes to a finite extension.  The
integral-closure theorem gives a Dedekind domain; the extended valuation is
nontrivial because a base uniformizer remains a nonunit. -/
theorem valued_discrete_valuation :
    letI : Valuation.HasExtension
        (NormedField.valuation (K := K))
        (NormedField.valuation (K := L)) :=
      valuation_normed_algebra K L
    IsDiscreteValuationRing 𝒪[L] := by
  letI : Valuation.HasExtension
      (NormedField.valuation (K := K))
      (NormedField.valuation (K := L)) :=
    valuation_normed_algebra K L
  letI : IsIntegralClosure 𝒪[L] 𝒪[K] L :=
    valued_integer_closure K L
  letI : IsDedekindDomain 𝒪[L] :=
    IsIntegralClosure.isDedekindDomain 𝒪[K] K L 𝒪[L]
  have hnotfield : ¬ IsField 𝒪[L] := by
    intro hfield
    letI : Field 𝒪[L] := hfield.toField
    obtain ⟨pi, hpi⟩ := IsDiscreteValuationRing.exists_irreducible 𝒪[K]
    let piL : 𝒪[L] := algebraMap 𝒪[K] 𝒪[L] pi
    have hpiL0 : piL ≠ 0 := by
      simpa [piL] using
        (FaithfulSMul.algebraMap_injective 𝒪[K] 𝒪[L]).ne hpi.ne_zero
    have hpiLunit : IsUnit piL := (isUnit_iff_ne_zero).mpr hpiL0
    have hnormlt : ‖piL‖ < 1 := by
      change ‖(algebraMap K L (pi : K))‖ < 1
      rw [norm_algebraMap]
      simpa using Valued.integer.norm_irreducible_lt_one hpi
    exact (ne_of_lt hnormlt)
      (Valued.integer.isUnit_iff_norm_eq_one.mp hpiLunit)
  exact ((IsDiscreteValuationRing.TFAE 𝒪[L] hnotfield).out 2 0).mp
    (inferInstance : IsDedekindDomain 𝒪[L])

/-- The integer ring of a finite extension is Henselian for the uniquely
extended complete valuation. -/
theorem valued_henselian_extension :
    letI : Valuation.HasExtension
        (NormedField.valuation (K := K))
        (NormedField.valuation (K := L)) :=
      valuation_normed_algebra K L
    HenselianLocalRing 𝒪[L] := by
  letI : Valuation.HasExtension
      (NormedField.valuation (K := K))
      (NormedField.valuation (K := L)) :=
    valuation_normed_algebra K L
  letI : CompleteSpace L := FiniteDimensional.complete K L
  letI : IsDiscreteValuationRing 𝒪[L] :=
    valued_discrete_valuation K L
  exact valued_henselian_ring L

end FiniteValuedExtension

section IntrinsicIntegralModel

variable (A K Omega : Type*)
  [CommRing A] [IsDomain A] [Field K] [Field Omega]
  [Algebra A K] [IsFractionRing A K]
  [Algebra K Omega] [Algebra A Omega] [IsScalarTower A K Omega]
  [IsAlgClosure K Omega]

omit [IsDomain A] [IsFractionRing A K] [IsAlgClosure K Omega] in
/-- The intrinsic integral model of a finite embedded field is its integral
closure over the base DVR.  This packages the identification used implicitly
in `intermediate_dedekind_domain`. -/
theorem intermediate_model_closure
    (E : IntermediateField K Omega) :
    letI : Algebra (intermediateIntegralModel A K Omega E) E :=
      intermediateModelAlgebra A K Omega E
    IsIntegralClosure (intermediateIntegralModel A K Omega E) A E := by
  let B := integralClosure A Omega
  let U := intermediateIntegralModel A K Omega E
  let algUE : Algebra U E := intermediateModelAlgebra A K Omega E
  letI : SMul U E := algUE.toSMul
  letI : Algebra U E := algUE
  letI : IsScalarTower A U E := IsScalarTower.of_algebraMap_eq' <| by
    ext a
    change algebraMap A Omega a =
      algebraMap B Omega (algebraMap A B a)
    exact IsScalarTower.algebraMap_apply A B Omega a
  refine { algebraMap_injective := ?_, isIntegral_iff := ?_ }
  · intro x y hxy
    apply Subtype.ext
    apply Subtype.ext
    exact congrArg (fun z : E ↦ (z : Omega)) hxy
  · intro x
    constructor
    · intro hx
      have hxOmega : IsIntegral A (x : Omega) :=
        hx.map (E.val.restrictScalars A)
      obtain ⟨b, hb⟩ :=
        (IsIntegralClosure.isIntegral_iff (R := A) (A := B)
          (B := Omega)).mp hxOmega
      have hbE : algebraMap B Omega b ∈ E := by
        rw [hb]
        exact x.property
      refine ⟨⟨b, hbE⟩, ?_⟩
      apply E.val.injective
      change algebraMap B Omega b = (x : Omega)
      exact hb
    · rintro ⟨y, rfl⟩
      apply (isIntegral_algHom_iff (E.val.restrictScalars A)
        E.val.injective).mp
      change IsIntegral A (algebraMap B Omega (y : B))
      exact (IsIntegralClosure.isIntegral A Omega (y : B)).map
        (IsScalarTower.toAlgHom A B Omega)

/-- The intrinsic integral model of a finite embedded field has that field
as its fraction field. -/
theorem intermediate_model_ring
    (E : IntermediateField K Omega) (hEfg : E.FG) :
    letI : Algebra (intermediateIntegralModel A K Omega E) E :=
      intermediateModelAlgebra A K Omega E
    IsFractionRing (intermediateIntegralModel A K Omega E) E := by
  let U := intermediateIntegralModel A K Omega E
  let algUE : Algebra U E :=
    intermediateModelAlgebra A K Omega E
  letI : SMul U E := algUE.toSMul
  letI : Algebra U E := algUE
  letI : Algebra.EssFiniteType K E :=
    IntermediateField.essFiniteType_iff.mpr hEfg
  letI : Module.Finite K E :=
    Algebra.finite_of_essFiniteType_of_isAlgebraic
  letI : IsScalarTower A U E :=
    IsScalarTower.of_algebraMap_eq' <| by
      ext a
      change algebraMap A Omega a =
        algebraMap (integralClosure A Omega) Omega
          (algebraMap A (integralClosure A Omega) a)
      exact IsScalarTower.algebraMap_apply A (integralClosure A Omega) Omega a
  letI : IsIntegralClosure U A E :=
    intermediate_model_closure A K Omega E
  exact IsIntegralClosure.isFractionRing_of_finite_extension A K E U

end IntrinsicIntegralModel

section IntegralDVRCompatibility

variable (K U KU : Type*)
  [NontriviallyNormedField K] [CompleteSpace K] [IsUltrametricDist K]
  [NontriviallyNormedField KU] [IsUltrametricDist KU]
  [NormedAlgebra K KU] [Algebra.IsAlgebraic K KU]
  [CommRing U] [IsDomain U] [IsDiscreteValuationRing U]
  [Algebra 𝒪[K] U] [Algebra U KU] [IsFractionRing U KU]
  [IsScalarTower 𝒪[K] U KU] [Algebra.IsIntegral 𝒪[K] U]

attribute [local instance] NormedField.toValued

/-- An integral DVR model inside an algebraic extension of a complete
nonarchimedean field is the norm-defined integer ring of its fraction
field. -/
noncomputable def dvrValuedInteger : U ≃+* 𝒪[KU] := by
  letI : Valuation.HasExtension
      (NormedField.valuation (K := K))
      (NormedField.valuation (K := KU)) :=
    valuation_normed_algebra K KU
  letI : IsIntegralClosure 𝒪[KU] 𝒪[K] KU :=
    valued_integer_closure K KU
  letI : IsIntegralClosure U 𝒪[K] KU :=
    IsIntegralClosure.of_isIntegrallyClosed U 𝒪[K] KU
  exact (IsIntegralClosure.equiv 𝒪[K] U KU 𝒪[KU]).toRingEquiv

@[simp]
theorem coe_dvr_valued (u : U) :
    ((dvrValuedInteger K U KU u : 𝒪[KU]) : KU) =
      algebraMap U KU u := by
  letI : Valuation.HasExtension
      (NormedField.valuation (K := K))
      (NormedField.valuation (K := KU)) :=
    valuation_normed_algebra K KU
  letI : IsIntegralClosure 𝒪[KU] 𝒪[K] KU :=
    valued_integer_closure K KU
  letI : IsIntegralClosure U 𝒪[K] KU :=
    IsIntegralClosure.of_isIntegrallyClosed U 𝒪[K] KU
  exact IsIntegralClosure.algebraMap_equiv 𝒪[K] U KU 𝒪[KU] u

/-- Evaluation commutes with transporting coefficients from an integral DVR
model to the norm-defined integer ring. -/
theorem aeval_dvr_valued
    {E : Type*} [CommRing E]
    [Algebra KU E] [Algebra U E] [Algebra 𝒪[KU] E]
    [IsScalarTower U KU E] [IsScalarTower 𝒪[KU] KU E]
    (p : Polynomial U) (x : E) :
    Polynomial.aeval x
        (p.map (dvrValuedInteger K U KU).toRingHom) =
      Polynomial.eval₂ (algebraMap U E) x p := by
  rw [Polynomial.aeval_def, Polynomial.eval₂_map]
  congr 1
  ext u
  change algebraMap 𝒪[KU] E (dvrValuedInteger K U KU u) =
    algebraMap U E u
  calc
    algebraMap 𝒪[KU] E (dvrValuedInteger K U KU u) =
        algebraMap KU E
          ((dvrValuedInteger K U KU u : 𝒪[KU]) : KU) :=
      IsScalarTower.algebraMap_apply 𝒪[KU] KU E _
    _ = algebraMap KU E (algebraMap U KU u) := by
      rw [coe_dvr_valued K U KU]
    _ = algebraMap U E u := (IsScalarTower.algebraMap_apply U KU E u).symm

include K in
/-- Uniqueness of the extension valuation in the concrete form needed for
Remark 7.65: the DVR valuation attached to an integral DVR model and the
ambient norm valuation on its fraction field are equivalent. -/
theorem integral_dvr_valuation :
    ((IsDiscreteValuationRing.maximalIdeal U).valuation KU).IsEquiv
      (Valued.v : Valuation KU NNReal) := by
  rw [Valuation.isEquiv_iff_val_le_one]
  intro x
  constructor
  · intro hx
    obtain ⟨u, hu⟩ :=
      IsDiscreteValuationRing.exists_lift_of_le_one
        (A := U) (K := KU) hx
    let ux : 𝒪[KU] := dvrValuedInteger K U KU u
    have hux : (Valued.v : Valuation KU NNReal) (ux : KU) ≤ 1 := ux.property
    have huxcoe : (ux : KU) = x := by
      calc
        (ux : KU) = algebraMap U KU u :=
          coe_dvr_valued K U KU u
        _ = x := hu
    rw [huxcoe] at hux
    exact hux
  · intro hx
    let ux : 𝒪[KU] := ⟨x, hx⟩
    let u : U := (dvrValuedInteger K U KU).symm ux
    have hu : ((IsDiscreteValuationRing.maximalIdeal U).valuation KU)
        (algebraMap U KU u) ≤ 1 :=
      IsDedekindDomain.HeightOneSpectrum.valuation_le_one
        (v := IsDiscreteValuationRing.maximalIdeal U) (K := KU) u
    have hcoe : algebraMap U KU u = x := by
      change algebraMap U KU
          ((dvrValuedInteger K U KU).symm ux) = x
      rw [← coe_dvr_valued K U KU]
      simp [ux]
    simpa [hcoe] using hu

end IntegralDVRCompatibility

section CompatibleValuationRing

variable (U KU : Type*)
  [CommRing U] [IsDomain U] [IsDiscreteValuationRing U]
  [NontriviallyNormedField KU] [IsUltrametricDist KU]
  [Algebra U KU] [IsFractionRing U KU]

attribute [local instance] NormedField.toValued

/-- A DVR is the norm-defined integer ring of its fraction field as soon as
the norm valuation is equivalent to the intrinsic discrete valuation.

This is the precise compatibility bridge needed in Remark 7.65: for the
maximal unramified DVR `U` with fraction field `KU`, uniqueness of the
extension of the local-field valuation supplies `h`, and this equivalence
then identifies the abstract DVR used by the unramified construction with
the concrete ring `𝒪[KU]` used in Proposition 7.64. -/
noncomputable def dvrEquivValued
    (h : ((IsDiscreteValuationRing.maximalIdeal U).valuation KU).IsEquiv
      (Valued.v : Valuation KU NNReal)) :
    U ≃+* 𝒪[KU] := by
  let f : U →+* 𝒪[KU] :=
    { toFun := fun u ↦ ⟨algebraMap U KU u, by
        change (Valued.v : Valuation KU NNReal) (algebraMap U KU u) ≤ 1
        simpa using (h (algebraMap U KU u) 1).mp (by
          simpa using
            (IsDedekindDomain.HeightOneSpectrum.valuation_le_one
              (v := IsDiscreteValuationRing.maximalIdeal U)
              (K := KU) u))⟩
      map_zero' := Subtype.ext (map_zero (algebraMap U KU))
      map_one' := Subtype.ext (map_one (algebraMap U KU))
      map_add' := fun x y ↦ Subtype.ext (map_add (algebraMap U KU) x y)
      map_mul' := fun x y ↦ Subtype.ext (map_mul (algebraMap U KU) x y) }
  exact RingEquiv.ofBijective f
    ⟨fun _ _ hxy ↦ IsFractionRing.injective U KU (congrArg Subtype.val hxy),
      fun x ↦ by
        have hx : ((IsDiscreteValuationRing.maximalIdeal U).valuation KU) (x : KU) ≤ 1 := by
          have hxv : (Valued.v : Valuation KU NNReal) (x : KU) ≤ 1 := x.property
          simpa using (h (x : KU) 1).mpr (by simpa using hxv)
        obtain ⟨u, hu⟩ :=
          IsDiscreteValuationRing.exists_lift_of_le_one
            (A := U) (K := KU) hx
        exact ⟨u, Subtype.ext hu⟩⟩

@[simp]
theorem dvr_valued_integer
    (h : ((IsDiscreteValuationRing.maximalIdeal U).valuation KU).IsEquiv
      (Valued.v : Valuation KU NNReal)) (u : U) :
    ((dvrEquivValued U KU h u : 𝒪[KU]) : KU) =
      algebraMap U KU u :=
  by simp [dvrEquivValued]

set_option synthInstance.maxHeartbeats 100000 in
-- The target valuation ring has several reducibly equal local-ring instances.
/-- The compatible DVR equivalence carries the intrinsic maximal ideal to
the maximal ideal of the norm-defined integer ring.  Consequently
Eisenstein conditions can be transported across `dvrEquivValued`. -/
theorem maximal_dvr_valued
    (h : ((IsDiscreteValuationRing.maximalIdeal U).valuation KU).IsEquiv
      (Valued.v : Valuation KU NNReal)) :
    (IsLocalRing.maximalIdeal U).map (dvrEquivValued U KU h) =
      IsLocalRing.maximalIdeal 𝒪[KU] :=
  IsLocalRing.map_ringEquiv_maximalIdeal (dvrEquivValued U KU h)

end CompatibleValuationRing

/-- A finite extension of DVRs with surjective residue-field map is totally
ramified. -/
theorem totally_ramified_surjective
    (A B K L : Type*)
    [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    [CommRing B] [IsDomain B] [IsDiscreteValuationRing B]
    [Algebra A B] [Module.Finite A B] [Module.IsTorsionFree A B]
    [Field K] [Algebra A K] [IsFractionRing A K]
    [Field L] [Algebra B L] [IsFractionRing B L]
    [Algebra K L] [Algebra A L]
    [IsScalarTower A B L] [IsScalarTower A K L]
    (hres : Function.Surjective
      (algebraMap (ResidueField A) (ResidueField B))) :
    TotallyRamified A B (maximalIdeal A) := by
  let p := maximalIdeal A
  let P := maximalIdeal B
  letI : Algebra.IsIntegral A B := Algebra.IsIntegral.of_finite A B
  letI : IsLocalHom (algebraMap A B) :=
    Algebra.IsIntegral.isLocalHom A B
  have hp0 : p ≠ ⊥ := IsDiscreteValuationRing.not_a_field A
  have hP0 : P ≠ ⊥ := IsDiscreteValuationRing.not_a_field B
  let e : ResidueField A ≃ₗ[ResidueField A] ResidueField B :=
    LinearEquiv.ofBijective (Algebra.linearMap (ResidueField A) (ResidueField B))
      ⟨RingHom.injective _, hres⟩
  have hresDegree : Module.finrank (ResidueField A) (ResidueField B) = 1 := by
    rw [← e.finrank_eq]
    exact Module.finrank_self (ResidueField A)
  have hinertia : p.inertiaDeg P = 1 := by
    rw [Ideal.inertiaDeg_algebraMap]
    exact hresDegree
  have hdegree :=
    Ideal.ramificationIdx_mul_inertiaDeg_of_isLocalRing
      (R := A) B K L hp0
  have hfieldRank : Module.finrank K L = Module.finrank A B :=
    Algebra.IsAlgebraic.finrank_of_isFractionRing A K B L
  have hramification : p.ramificationIdx P = Module.finrank A B := by
    rw [hinertia, mul_one, hfieldRank] at hdegree
    exact hdegree
  have hmap0 : p.map (algebraMap A B) ≠ ⊥ :=
    (Ideal.map_eq_bot_iff_of_injective
      (FaithfulSMul.algebraMap_injective A B)).not.mpr hp0
  obtain ⟨n, hn⟩ := exists_maximalIdeal_pow_eq_of_principal B
    (IsPrincipalIdealRing.principal _) (p.map (algebraMap A B)) hmap0
  have hPprime : P.IsPrime := inferInstance
  have hPirr : Irreducible P :=
    Ideal.prime_of_isPrime hP0 hPprime |>.irreducible
  have hramificationN : p.ramificationIdx P = n := by
    rw [Ideal.IsDedekindDomain.ramificationIdx_eq_normalizedFactors_count
      hmap0 hPprime hP0,
      hn, UniqueFactorizationMonoid.normalizedFactors_pow,
      UniqueFactorizationMonoid.normalizedFactors_irreducible hPirr]
    simp
  have hmap : p.map (algebraMap A B) = P ^ Module.finrank A B := by
    rw [hn, ← hramificationN, hramification]
  refine ⟨P, hPprime, inferInstance, hmap, hramification, ?_⟩
  intro Q hQprime hQover
  have hQ0 : Q ≠ ⊥ := Ideal.ne_bot_of_liesOver_of_ne_bot hp0 Q
  exact IsLocalRing.eq_maximalIdeal (hQprime.isMaximal hQ0)

set_option maxHeartbeats 1000000 in
-- Resolving the fraction-field scalar towers for the generated subalgebra is expensive.
/-- Milne, Corollary 7.51 and Remark 7.65: after passing from a finite local
extension to its maximal unramified subalgebra, the remaining extension is
totally ramified.

The fraction fields and their scalar towers are kept explicit because the
fraction field of a subalgebra is only unique up to equivalence.  Finiteness
of `B` over the maximal unramified subalgebra is deduced from its finiteness
over `A`; the residue-field surjectivity is supplied by the maximal
unramified construction. -/
theorem subalgebra_totally_ramified
    (A B KU L : Type*)
    [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    [CommRing B] [IsDomain B] [IsDiscreteValuationRing B]
    [HenselianLocalRing A] [HenselianLocalRing B]
    [Algebra A B] [IsLocalHom (algebraMap A B)]
    [Module.Finite A B] [Module.IsTorsionFree A B]
    [Algebra.IsIntegral A B]
    [FiniteDimensional (ResidueField A) (ResidueField B)]
    [Algebra.IsSeparable (ResidueField A) (ResidueField B)]
    [Field KU] [algUKU : Algebra (maximalUnramifiedSubalgebra A B) KU]
    [IsFractionRing (maximalUnramifiedSubalgebra A B) KU]
    [Field L] [algBL : Algebra B L] [IsFractionRing B L]
    [algKUL : Algebra KU L]
    [hUBL : IsScalarTower (maximalUnramifiedSubalgebra A B) B L]
    [hUKUL : IsScalarTower (maximalUnramifiedSubalgebra A B) KU L] :
    letI : IsLocalRing (maximalUnramifiedSubalgebra A B) :=
      maximal_subalgebra_ring A B
    TotallyRamified (maximalUnramifiedSubalgebra A B) B
      (maximalIdeal (maximalUnramifiedSubalgebra A B)) := by
  letI : IsLocalRing (maximalUnramifiedSubalgebra A B) :=
    maximal_subalgebra_ring A B
  letI : IsDiscreteValuationRing (maximalUnramifiedSubalgebra A B) :=
    subalgebra_discrete_valuation A B
  letI : Module.IsTorsionFree (maximalUnramifiedSubalgebra A B) B := by
    apply Module.isTorsionFree_iff_algebraMap_injective.mpr
    exact Subtype.val_injective
  letI : Module.Finite (maximalUnramifiedSubalgebra A B) B :=
    Module.Finite.of_restrictScalars_finite A
      (maximalUnramifiedSubalgebra A B) B
  letI : Algebra.IsIntegral (maximalUnramifiedSubalgebra A B) B :=
    Algebra.IsIntegral.of_finite (maximalUnramifiedSubalgebra A B) B
  letI : IsLocalHom
      (algebraMap (maximalUnramifiedSubalgebra A B) B) :=
    Algebra.IsIntegral.isLocalHom (maximalUnramifiedSubalgebra A B) B
  letI : IsScalarTower (maximalUnramifiedSubalgebra A B) B L := hUBL
  letI : IsScalarTower (maximalUnramifiedSubalgebra A B) KU L := hUKUL
  have hres : Function.Surjective
      (algebraMap
        (ResidueField (maximalUnramifiedSubalgebra A B))
        (ResidueField B)) := by
    intro y
    obtain ⟨b, rfl⟩ :=
      (residue_surjective : Function.Surjective (residue B)) y
    have hb : residue B b ∈
        residueImage A B (maximalUnramifiedSubalgebra A B) := by
      rw [maximal_subalgebra_image A B]
      trivial
    obtain ⟨u, hu, hures⟩ := hb
    let uU : maximalUnramifiedSubalgebra A B := ⟨u, hu⟩
    refine ⟨residue (maximalUnramifiedSubalgebra A B) uU, ?_⟩
    rw [IsLocalRing.ResidueField.algebraMap_residue]
    exact hures
  exact totally_ramified_surjective
    (maximalUnramifiedSubalgebra A B) B KU L hres

/-- The degree of the maximal unramified subextension divides the degree of
the original finite local extension.  This is the numerical step `m ∣ n`
used in Milne's Remark 7.65.

The finite-dimensional field extensions are obtained from the corresponding
finite extensions of DVRs by localization; they are not additional
hypotheses. -/
theorem maximal_subalgebra_dvd
    (A B K KU L : Type*)
    [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    [CommRing B] [IsDomain B] [IsDiscreteValuationRing B]
    [HenselianLocalRing A] [HenselianLocalRing B]
    [Algebra A B] [Module.Finite A B] [Module.IsTorsionFree A B]
    [Algebra.IsIntegral A B]
    [FiniteDimensional (ResidueField A) (ResidueField B)]
    [Algebra.IsSeparable (ResidueField A) (ResidueField B)]
    [Field K] [Algebra A K] [IsFractionRing A K]
    [Field KU] [Algebra (maximalUnramifiedSubalgebra A B) KU]
    [IsFractionRing (maximalUnramifiedSubalgebra A B) KU]
    [Field L] [Algebra B L] [IsFractionRing B L]
    [Algebra A KU] [Algebra A L] [Algebra K KU] [Algebra K L] [Algebra KU L]
    [IsScalarTower A B L]
    [IsScalarTower A (maximalUnramifiedSubalgebra A B) KU]
    [IsScalarTower A K KU] [IsScalarTower A K L]
    [IsScalarTower K KU L]
    [IsScalarTower (maximalUnramifiedSubalgebra A B) B L]
    [IsScalarTower (maximalUnramifiedSubalgebra A B) KU L] :
    Module.finrank K KU ∣ Module.finrank K L := by
  let U := maximalUnramifiedSubalgebra A B
  letI : Module.IsTorsionFree U B := by
    apply Module.isTorsionFree_iff_algebraMap_injective.mpr
    exact Subtype.val_injective
  letI : Module.Finite A U :=
    Module.Finite.of_injective U.val.toLinearMap Subtype.val_injective
  letI : Module.Finite U B :=
    Module.Finite.of_restrictScalars_finite A U B
  letI : Algebra.IsIntegral U B := Algebra.IsIntegral.of_finite U B
  letI : Module.Finite K KU := by
    apply Module.Finite.of_isLocalization A U (nonZeroDivisors A)
  letI : Module.Finite KU L := by
    apply Module.Finite.of_isLocalization U B (nonZeroDivisors U)
  exact ⟨Module.finrank KU L, (Module.finrank_mul_finrank K KU L).symm⟩

/-- For a finite formally unramified extension of DVRs, the degree of the
fraction-field extension is its residue degree.  This is the numerical form
of Proposition 7.50 used to select the degree-`m` base in Remark 7.65. -/
theorem formally_unramified_fraction
    (A U K KU : Type*)
    [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    [CommRing U] [IsDomain U] [IsDiscreteValuationRing U]
    [Algebra A U] [Module.Finite A U]
    [Module.IsTorsionFree A U] [Algebra.FormallyUnramified A U]
    [Field K] [Algebra A K] [IsFractionRing A K]
    [Field KU] [Algebra U KU] [IsFractionRing U KU]
    [Algebra A KU] [Algebra K KU]
    [IsScalarTower A U KU] [IsScalarTower A K KU] :
    Module.finrank K KU =
      Module.finrank (ResidueField A) (ResidueField U) := by
  letI : Algebra.IsIntegral A U := Algebra.IsIntegral.of_finite A U
  letI : IsLocalHom (algebraMap A U) :=
    Algebra.IsIntegral.isLocalHom A U
  letI : (maximalIdeal U).LiesOver (maximalIdeal A) := inferInstance
  letI : Algebra.IsUnramifiedAt A (maximalIdeal U) := inferInstance
  simpa using finrank_unramified_local
    (R := A) (S := U) (K := K) (L := KU) (maximalIdeal A)
      (IsDiscreteValuationRing.not_a_field A)
      (IsDiscreteValuationRing.not_a_field U)

set_option maxHeartbeats 1000000 in
-- Resolving both fraction-field scalar towers in one statement is expensive.
/-- Milne, Remark 7.65, the complete algebraic decomposition package.  The
fraction field of the maximal unramified subalgebra has degree dividing the
original degree, and the remaining extension of DVRs is totally ramified.

This theorem deliberately keeps the fraction field `KU` explicit.  Passing
from its abstract DVR `maximalUnramifiedSubalgebra A B` to the norm-defined
valuation ring `𝒪[KU]` is the additional topological identification needed
to feed the result directly to Proposition 7.64. -/
theorem maximal_subalgebra_decomposition
    (A B K KU L : Type*)
    [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    [CommRing B] [IsDomain B] [IsDiscreteValuationRing B]
    [HenselianLocalRing A] [HenselianLocalRing B]
    [Algebra A B] [IsLocalHom (algebraMap A B)]
    [Module.Finite A B] [Module.IsTorsionFree A B]
    [Algebra.IsIntegral A B]
    [FiniteDimensional (ResidueField A) (ResidueField B)]
    [Algebra.IsSeparable (ResidueField A) (ResidueField B)]
    [Field K] [Algebra A K] [IsFractionRing A K]
    [Field KU] [Algebra (maximalUnramifiedSubalgebra A B) KU]
    [IsFractionRing (maximalUnramifiedSubalgebra A B) KU]
    [Field L] [Algebra B L] [IsFractionRing B L]
    [Algebra A KU] [Algebra A L] [Algebra K KU] [Algebra K L] [Algebra KU L]
    [IsScalarTower A B L]
    [IsScalarTower A (maximalUnramifiedSubalgebra A B) KU]
    [IsScalarTower A K KU] [IsScalarTower A K L]
    [IsScalarTower K KU L]
    [IsScalarTower (maximalUnramifiedSubalgebra A B) B L]
    [IsScalarTower (maximalUnramifiedSubalgebra A B) KU L] :
    letI : IsLocalRing (maximalUnramifiedSubalgebra A B) :=
      maximal_subalgebra_ring A B
    TotallyRamified (maximalUnramifiedSubalgebra A B) B
        (maximalIdeal (maximalUnramifiedSubalgebra A B)) ∧
      Module.finrank K KU ∣ Module.finrank K L := by
  letI : IsLocalRing (maximalUnramifiedSubalgebra A B) :=
    maximal_subalgebra_ring A B
  constructor
  · exact subalgebra_totally_ramified A B KU L
  · exact maximal_subalgebra_dvd A B K KU L

end

end Towers.NumberTheory.Milne
