import Towers.NumberTheory.Ramification.EisensteinRamification
import Towers.NumberTheory.Fields.CubicIntegralClosure
import Towers.NumberTheory.Locals.LocalDegreeFormula
import Mathlib.RingTheory.Discriminant
import Mathlib.RingTheory.Ideal.Norm.RelNorm
import Mathlib.RingTheory.Polynomial.Eisenstein.IsIntegral

/-!
# Milne, Algebraic Number Theory, Proposition 7.55

This file records both directions of the characterization of totally ramified extensions by
Eisenstein generators.  In the converse direction, ideal ramification, residue degree, norm, and
discriminant arguments show that an upstairs uniformizer has Eisenstein minimal polynomial and
generates the integral closure.
-/

namespace Towers.NumberTheory.Milne

open Algebra Polynomial

attribute [local instance] Ideal.Quotient.field

/-- An integral algebra has an Eisenstein generator at `p` if it is generated by an integral
element whose minimal polynomial is Eisenstein at `p`. -/
def HasEisensteinGenerator
    (A B : Type*) [CommRing A] [CommRing B] [Algebra A B] (p : Ideal A) : Prop :=
  ∃ alpha : B, IsIntegral A alpha ∧ Algebra.adjoin A {alpha} = ⊤ ∧
    (minpoly A alpha).IsEisensteinAt p

/-- The integral-algebra formulation of having an Eisenstein generator is equivalent to an
explicit presentation as the quotient by a monic Eisenstein polynomial. -/
theorem eisenstein_adjoin_monic
    (A B : Type*) [CommRing A] [IsDomain A] [IsIntegrallyClosed A]
    [CommRing B] [IsDomain B] [Algebra A B] [Module.IsTorsionFree A B]
    (p : Ideal A) (hp : p.IsPrime) :
    HasEisensteinGenerator A B p ↔
      ∃ (f : A[X]) (_h : IsAdjoinRootMonic B f), f.IsEisensteinAt p := by
  constructor
  · rintro ⟨alpha, halpha, hadjoin, heis⟩
    exact ⟨minpoly A alpha, IsAdjoinRootMonic.mkOfAdjoinEqTop halpha hadjoin, heis⟩
  · rintro ⟨f, h, heis⟩
    have hdeg : 0 < f.natDegree := h.deg_pos
    have hirr : Irreducible f :=
      eisenstein_irreducible hp heis h.monic hdeg
    refine ⟨h.root, h.isIntegral_root, h.adjoin_root_eq_top, ?_⟩
    simpa [h.minpoly_eq hirr] using heis

/-- Ring-theoretic total ramification at `p`: there is one prime above `p`, its ramification
index is the full module rank, and the extended ideal is the corresponding power. -/
def TotallyRamified
    (A B : Type*) [CommRing A] [CommRing B] [Algebra A B] (p : Ideal A) : Prop :=
  ∃ P : Ideal B,
    P.IsPrime ∧ P.LiesOver p ∧
      p.map (algebraMap A B) = P ^ Module.finrank A B ∧
      Ideal.ramificationIdx p P = Module.finrank A B ∧
      ∀ Q : Ideal B, Q.IsPrime → Q.LiesOver p → Q = P

/-- The degree argument in the converse direction of Proposition 7.55.  If `Pi` is a
uniformizer upstairs and the minimal polynomial of `Pi` is weakly Eisenstein, then full
ramification forces its degree to be the whole extension degree.

Indeed, weak Eisenstein gives `Pi ^ deg(minpoly) ∈ pB`, while total ramification identifies
`pB` with `(Pi) ^ [L : K]`.  Divisibility of powers gives one degree inequality, and the usual
minimal-polynomial bound over the fraction fields gives the other. -/
theorem minpoly_weakly_uniformizer
    (A B K L : Type*) [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    [CommRing B] [IsDomain B] [IsDiscreteValuationRing B] [Algebra A B]
    [Module.Finite A B] [Module.IsTorsionFree A B]
    [Field K] [Algebra A K] [IsFractionRing A K]
    [Field L] [Algebra B L] [IsFractionRing B L]
    [Algebra K L] [FiniteDimensional K L] [Algebra A L]
    [IsScalarTower A B L] [IsScalarTower A K L]
    (Pi : B) (hPi : Irreducible Pi)
    (hmap : (IsLocalRing.maximalIdeal A).map (algebraMap A B) =
      (IsLocalRing.maximalIdeal B) ^ Module.finrank A B)
    (hweak : (minpoly A Pi).IsWeaklyEisensteinAt
      (IsLocalRing.maximalIdeal A)) :
    (minpoly A Pi).natDegree = Module.finrank A B := by
  have hPiInt : IsIntegral A Pi := Algebra.IsIntegral.isIntegral Pi
  have hpowMem : Pi ^ (minpoly A Pi).natDegree ∈
      (IsLocalRing.maximalIdeal A).map (algebraMap A B) := by
    apply hweak.pow_natDegree_le_of_aeval_zero_of_monic_mem_map
      (minpoly.aeval A Pi) (minpoly.monic hPiInt)
    simpa using (minpoly.monic hPiInt).natDegree_map (algebraMap A B) |>.le
  have hpowDvd : Pi ^ Module.finrank A B ∣
      Pi ^ (minpoly A Pi).natDegree := by
    rw [hmap, hPi.maximalIdeal_eq, Ideal.span_singleton_pow,
      Ideal.mem_span_singleton] at hpowMem
    exact hpowMem
  have hlower : Module.finrank A B ≤ (minpoly A Pi).natDegree :=
    (pow_dvd_pow_iff hPi.ne_zero hPi.not_isUnit).mp hpowDvd
  have hfieldDegree :
      (minpoly K (algebraMap B L Pi)).natDegree = (minpoly A Pi).natDegree := by
    rw [minpoly.isIntegrallyClosed_eq_field_fractions K L hPiInt,
      (minpoly.monic hPiInt).natDegree_map]
  have hfinrank : Module.finrank K L = Module.finrank A B :=
    Algebra.IsAlgebraic.finrank_of_isFractionRing A K B L
  have hupper : (minpoly A Pi).natDegree ≤ Module.finrank A B := by
    rw [← hfieldDegree, ← hfinrank]
    exact minpoly.natDegree_le (algebraMap B L Pi)
  exact Nat.le_antisymm hupper hlower

/-- Under the hypotheses of the preceding degree argument, the uniformizer generates the
fraction-field extension.  This removes the field-generation hypothesis from the remaining
Eisenstein part of the converse to Proposition 7.55. -/
theorem weakly_eisenstein_uniformizer
    (A B K L : Type*) [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    [CommRing B] [IsDomain B] [IsDiscreteValuationRing B] [Algebra A B]
    [Module.Finite A B] [Module.IsTorsionFree A B]
    [Field K] [Algebra A K] [IsFractionRing A K]
    [Field L] [Algebra B L] [IsFractionRing B L]
    [Algebra K L] [FiniteDimensional K L] [Algebra A L]
    [IsScalarTower A B L] [IsScalarTower A K L]
    (Pi : B) (hPi : Irreducible Pi)
    (hmap : (IsLocalRing.maximalIdeal A).map (algebraMap A B) =
      (IsLocalRing.maximalIdeal B) ^ Module.finrank A B)
    (hweak : (minpoly A Pi).IsWeaklyEisensteinAt
      (IsLocalRing.maximalIdeal A)) :
    IntermediateField.adjoin K ({algebraMap B L Pi} : Set L) = ⊤ := by
  apply (Field.primitive_element_iff_minpoly_natDegree_eq K
    (algebraMap B L Pi)).2
  have hPiInt : IsIntegral A Pi := Algebra.IsIntegral.isIntegral Pi
  rw [minpoly.isIntegrallyClosed_eq_field_fractions K L hPiInt,
    (minpoly.monic hPiInt).natDegree_map,
    minpoly_weakly_uniformizer
      A B K L Pi hPi hmap hweak,
    Algebra.IsAlgebraic.finrank_of_isFractionRing A K B L]

/-- Proposition 7.55, converse degree step in its intrinsic totally ramified form.  Once the
minimal polynomial of an upstairs uniformizer is known to be weakly Eisenstein, total
ramification itself forces that uniformizer to generate the fraction-field extension. -/
theorem fraction_weakly_eisenstein
    (A B K L : Type*) [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    [CommRing B] [IsDomain B] [IsDiscreteValuationRing B] [Algebra A B]
    [Module.Finite A B] [Module.IsTorsionFree A B]
    [Field K] [Algebra A K] [IsFractionRing A K]
    [Field L] [Algebra B L] [IsFractionRing B L]
    [Algebra K L] [FiniteDimensional K L] [Algebra A L]
    [IsScalarTower A B L] [IsScalarTower A K L]
    (htr : TotallyRamified A B (IsLocalRing.maximalIdeal A))
    (Pi : B) (hPi : Irreducible Pi)
    (hweak : (minpoly A Pi).IsWeaklyEisensteinAt
      (IsLocalRing.maximalIdeal A)) :
    IntermediateField.adjoin K ({algebraMap B L Pi} : Set L) = ⊤ := by
  rcases htr with ⟨P, hPprime, hPover, hmap, _hram, _hunique⟩
  have hp0 : IsLocalRing.maximalIdeal A ≠ ⊥ :=
    IsDiscreteValuationRing.not_a_field A
  have hP0 : P ≠ ⊥ := Ideal.ne_bot_of_liesOver_of_ne_bot hp0 P
  have hPmax : P = IsLocalRing.maximalIdeal B :=
    IsLocalRing.eq_maximalIdeal (hPprime.isMaximal hP0)
  apply weakly_eisenstein_uniformizer
    A B K L Pi hPi
  · simpa [hPmax] using hmap
  · exact hweak

/-- A totally ramified extension has trivial residue-field extension.  This
is the degree-one form of the assertion in Milne's Remark 7.56 that the two
valuation rings have the same residue field. -/
theorem deg_totally_ramified
    (A B K L : Type*) [CommRing A] [IsDedekindDomain A]
    [CommRing B] [IsDedekindDomain B] [Algebra A B]
    [Module.Finite A B] [Module.IsTorsionFree A B]
    [Field K] [Algebra A K] [IsFractionRing A K]
    [Field L] [Algebra B L] [IsFractionRing B L]
    [Algebra K L] [Algebra A L]
    [IsScalarTower A B L] [IsScalarTower A K L]
    {p : Ideal A} [p.IsPrime] (hp : p ≠ ⊥)
    (h : TotallyRamified A B p) :
    ∃ P : Ideal B, P.IsPrime ∧ P.LiesOver p ∧
      Ideal.inertiaDeg p P = 1 := by
  letI : p.IsMaximal := (inferInstance : p.IsPrime).isMaximal hp
  rcases h with ⟨P, hPprime, hPover, _hpow, hram, hunique⟩
  letI : P.IsPrime := hPprime
  letI : P.LiesOver p := hPover
  have hprimes : IsDedekindDomain.primesOverFinset p B = {P} := by
    ext Q
    rw [Finset.mem_singleton, IsDedekindDomain.mem_primesOverFinset_iff hp B]
    constructor
    · rintro ⟨hQprime, hQover⟩
      exact hunique Q hQprime hQover
    · rintro rfl
      exact ⟨hPprime, hPover⟩
  have hdegree :=
    ramification_deg_unique
      A B K L hp hprimes
  have hfinrank : Module.finrank K L = Module.finrank A B :=
    Algebra.IsAlgebraic.finrank_of_isFractionRing A K B L
  have hmul : Module.finrank A B * Ideal.inertiaDeg p P =
      Module.finrank A B * 1 := by
    simpa [hram, hfinrank] using hdegree
  have hpos : 0 < Module.finrank A B := by
    exact Module.finrank_pos_iff.mpr inferInstance
  refine ⟨P, hPprime, hPover, ?_⟩
  exact Nat.eq_of_mul_eq_mul_left hpos hmul

/-- Canonical residue-field form of total ramification: if `P` is the unique
prime above `p` and its ramification index is the full extension degree, then
reduction induces an isomorphism of residue fields. -/
theorem bijective_full_idx
    (A B K L : Type*) [CommRing A] [IsDedekindDomain A]
    [CommRing B] [IsDedekindDomain B] [Algebra A B]
    [Module.Finite A B] [Module.IsTorsionFree A B]
    [Field K] [Algebra A K] [IsFractionRing A K]
    [Field L] [Algebra B L] [IsFractionRing B L]
    [Algebra K L] [Algebra A L]
    [IsScalarTower A B L] [IsScalarTower A K L]
    {p : Ideal A} [p.IsPrime] [p.IsMaximal] (hp : p ≠ ⊥)
    {P : Ideal B} [P.IsPrime] [P.IsMaximal] [P.LiesOver p]
    (hunique : IsDedekindDomain.primesOverFinset p B = {P})
    (hram : Ideal.ramificationIdx p P = Module.finrank A B) :
    Function.Bijective (algebraMap (A ⧸ p) (B ⧸ P)) := by
  have hdegree :=
    ramification_deg_unique
      A B K L hp hunique
  have hfieldRank : Module.finrank K L = Module.finrank A B :=
    Algebra.IsAlgebraic.finrank_of_isFractionRing A K B L
  have hmul : Module.finrank A B * Ideal.inertiaDeg p P =
      Module.finrank A B * 1 := by
    simpa [hram, hfieldRank] using hdegree
  have hpos : 0 < Module.finrank A B :=
    Module.finrank_pos_iff.mpr inferInstance
  have hdeg : Ideal.inertiaDeg p P = 1 :=
    Nat.eq_of_mul_eq_mul_left hpos hmul
  have hfinrank : Module.finrank (A ⧸ p) (B ⧸ P) = 1 := by
    rw [← Ideal.inertiaDeg_algebraMap]
    exact hdeg
  have hsurj : Function.Surjective (algebraMap (A ⧸ p) (B ⧸ P)) := by
    intro x
    obtain ⟨c, hc⟩ :=
      (finrank_eq_one_iff_of_nonzero' (K := A ⧸ p) (1 : B ⧸ P) one_ne_zero).mp
        hfinrank x
    refine ⟨c, ?_⟩
    simpa [Algebra.smul_def] using hc
  exact ⟨RingHom.injective _, hsurj⟩

/-- The remaining Eisenstein step in the converse to Proposition 7.55.  Over a perfect
fraction field, weak Eisenstein plus total ramification already implies Eisenstein: the
uniformizer generates the fraction field by the degree argument above, so its constant
coefficient is its norm.  The relative ideal norm of the upstairs maximal ideal is the
base maximal ideal (the inertia degree is one), hence that constant coefficient cannot lie
in the square of the base maximal ideal. -/
theorem minpoly_eisenstein_weakly
    (A B K L : Type*) [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    [CommRing B] [IsDomain B] [IsDiscreteValuationRing B] [Algebra A B]
    [Module.Finite A B] [Module.IsTorsionFree A B]
    [Field K] [Algebra A K] [IsFractionRing A K]
    [Field L] [Algebra B L] [IsFractionRing B L]
    [Algebra K L] [FiniteDimensional K L] [Algebra A L]
    [IsScalarTower A B L] [IsScalarTower A K L]
    [PerfectField (FractionRing A)]
    (htr : TotallyRamified A B (IsLocalRing.maximalIdeal A))
    (Pi : B) (hPi : Irreducible Pi)
    (hweak : (minpoly A Pi).IsWeaklyEisensteinAt
      (IsLocalRing.maximalIdeal A)) :
    (minpoly A Pi).IsEisensteinAt (IsLocalRing.maximalIdeal A) := by
  have hPiInt : IsIntegral A Pi := Algebra.IsIntegral.isIntegral Pi
  rcases htr with ⟨P, hPprime, hPover, hmap, _hram, _hunique⟩
  have hp0 : IsLocalRing.maximalIdeal A ≠ ⊥ :=
    IsDiscreteValuationRing.not_a_field A
  have hP0 : P ≠ ⊥ := Ideal.ne_bot_of_liesOver_of_ne_bot hp0 P
  have hPmax : P = IsLocalRing.maximalIdeal B :=
    IsLocalRing.eq_maximalIdeal (hPprime.isMaximal hP0)
  have hmapMax : (IsLocalRing.maximalIdeal A).map (algebraMap A B) =
      (IsLocalRing.maximalIdeal B) ^ Module.finrank A B := by
    simpa [hPmax] using hmap
  have hdegree : (minpoly A Pi).natDegree = Module.finrank A B :=
    minpoly_weakly_uniformizer
      A B K L Pi hPi hmapMax hweak
  have hmapMin : (IsLocalRing.maximalIdeal A).map (algebraMap A B) =
      (Ideal.span ({Pi} : Set B)) ^ (minpoly A Pi).natDegree := by
    simpa [hPi.maximalIdeal_eq, hdegree] using hmapMax
  let n := (minpoly A Pi).natDegree
  have hn : 0 < n := minpoly.natDegree_pos hPiInt
  refine ⟨(minpoly.monic hPiInt).leadingCoeff_notMem
      (IsLocalRing.maximalIdeal.isMaximal A).ne_top, hweak.mem, ?_⟩
  intro hconstant
  have hcoeff_mem (i : ℕ) (hi : i < n) :
      algebraMap A B ((minpoly A Pi).coeff i) * Pi ^ i ∈
        Ideal.span ({Pi ^ (n + 1)} : Set B) := by
    rw [Ideal.mem_span_singleton]
    by_cases hi0 : i = 0
    · subst i
      simp only [pow_zero, mul_one]
      have hmem : algebraMap A B ((minpoly A Pi).coeff 0) ∈
          ((IsLocalRing.maximalIdeal A) ^ 2).map (algebraMap A B) :=
        Ideal.mem_map_of_mem _ hconstant
      rw [Ideal.map_pow, hmapMin, ← pow_mul, Ideal.span_singleton_pow,
        Ideal.mem_span_singleton] at hmem
      exact (pow_dvd_pow Pi (by omega : n + 1 ≤ n * 2)).trans hmem
    · have hmem : algebraMap A B ((minpoly A Pi).coeff i) ∈
          (IsLocalRing.maximalIdeal A).map (algebraMap A B) :=
        Ideal.mem_map_of_mem _ (hweak.mem hi)
      rw [hmapMin, Ideal.span_singleton_pow, Ideal.mem_span_singleton] at hmem
      have hpow : Pi ^ (n + 1) ∣ Pi ^ n * Pi ^ i := by
        simpa [← pow_add] using
          (pow_dvd_pow Pi (by omega : n + 1 ≤ n + i))
      exact hpow.trans (mul_dvd_mul_right hmem (Pi ^ i))
  have hsum : ∑ i ∈ Finset.range n,
      algebraMap A B ((minpoly A Pi).coeff i) * Pi ^ i ∈
        Ideal.span ({Pi ^ (n + 1)} : Set B) := by
    exact Ideal.sum_mem _ fun i hi => hcoeff_mem i (Finset.mem_range.mp hi)
  have hroot := minpoly.aeval A Pi
  rw [aeval_eq_sum_range, Finset.sum_range_succ,
    (minpoly.monic hPiInt).coeff_natDegree, one_smul] at hroot
  have hpown : Pi ^ n ∈ Ideal.span ({Pi ^ (n + 1)} : Set B) := by
    have heq : Pi ^ n = -∑ i ∈ Finset.range n,
        algebraMap A B ((minpoly A Pi).coeff i) * Pi ^ i := by
      simpa [n, Algebra.smul_def] using eq_neg_of_add_eq_zero_right hroot
    rw [heq]
    exact (Submodule.neg_mem_iff _).mpr hsum
  have hdiv : Pi ^ (n + 1) ∣ Pi ^ n := Ideal.mem_span_singleton.mp hpown
  have := (pow_dvd_pow_iff hPi.ne_zero hPi.not_isUnit).mp hdiv
  omega

/-- The forward implication of Proposition 7.55 in its exact ideal-theoretic form: an
Eisenstein generator gives a unique prime above `p`, and `p` is its full-degree power. -/
theorem totally_ramified_eisenstein
    (A B : Type*) [CommRing A] [IsDedekindDomain A]
    [CommRing B] [IsDedekindDomain B] [Algebra A B]
    [Module.IsTorsionFree A B]
    {p : Ideal A} (hp : p.IsPrime) (hp0 : p ≠ ⊥)
    (hgen : HasEisensteinGenerator A B p) :
    TotallyRamified A B p := by
  rcases hgen with ⟨alpha, halpha, hadjoin, heis⟩
  let h : IsAdjoinRootMonic B (minpoly A alpha) :=
    IsAdjoinRootMonic.mkOfAdjoinEqTop halpha hadjoin
  let P : Ideal B := p.map (algebraMap A B) ⊔ Ideal.span {alpha}
  have hroot : h.root = alpha := by
    exact IsAdjoinRoot.mkOfAdjoinEqTop_root (hα := halpha) (hα₂ := hadjoin)
  have hram := eisenstein_total_monic
    hp hp0 heis h
  dsimp only at hram
  change (p.map (algebraMap A B) ⊔ Ideal.span {h.root}).IsPrime ∧
      p.map (algebraMap A B) =
        (p.map (algebraMap A B) ⊔ Ideal.span {h.root}) ^ (minpoly A alpha).natDegree ∧
      Ideal.ramificationIdx p (p.map (algebraMap A B) ⊔ Ideal.span {h.root}) =
        (minpoly A alpha).natDegree ∧
      ∀ Q : Ideal B, Q.IsPrime → Q.LiesOver p →
        Q = p.map (algebraMap A B) ⊔ Ideal.span {h.root} at hram
  have hram' : P.IsPrime ∧
      p.map (algebraMap A B) = P ^ (minpoly A alpha).natDegree ∧
      Ideal.ramificationIdx p P = (minpoly A alpha).natDegree ∧
      ∀ Q : Ideal B, Q.IsPrime → Q.LiesOver p → Q = P := by
    simpa [P, hroot] using hram
  rcases hram' with ⟨hPprime, hpow, hidx, hunique⟩
  have hfinrank : Module.finrank A B = (minpoly A alpha).natDegree := h.finrank
  have hmap_le : p.map (algebraMap A B) ≤ P := le_sup_left
  have hp_le_comap : p ≤ P.comap (algebraMap A B) :=
    Ideal.map_le_iff_le_comap.mp hmap_le
  have hcomap_prime : (P.comap (algebraMap A B)).IsPrime :=
    hPprime.comap (algebraMap A B)
  have hcomap : P.comap (algebraMap A B) = p := by
    exact (hp.isMaximal hp0).eq_of_le hcomap_prime.ne_top hp_le_comap |>.symm
  have hPover : P.LiesOver p := ⟨hcomap.symm⟩
  refine ⟨P, hPprime, hPover, ?_, ?_, hunique⟩
  · simpa [hfinrank] using hpow
  · simpa [hfinrank] using hidx

/-- Milne, Remark 7.56, the final order argument.  Suppose every element of
`S` is congruent modulo `Π S` to an element of `R[Π]`, a power of `q`
times `S` lies in `R[Π]`, and a power of `Π` is `q` times an element of
`S`.  Then `Π` generates `S` as an `R`-algebra. -/
theorem adjoin_uniformizer_containment
    {R S : Type*} [CommRing R] [CommRing S] [Algebra R S]
    (pi q u : S) (d m : ℕ)
    (hdecomp : ∀ x : S, ∃ a : S, a ∈ Algebra.adjoin R {pi} ∧
      ∃ y : S, x = a + pi * y)
    (hscale : ∀ x : S, q ^ m * x ∈ Algebra.adjoin R {pi})
    (hpow : pi ^ d = q * u) :
    Algebra.adjoin R {pi} = ⊤ := by
  apply subalgebra_top_decompose
    (Algebra.adjoin R {pi}) pi q u d m
  · exact Algebra.subset_adjoin (Set.mem_singleton pi)
  · exact hdecomp
  · exact hscale
  · exact hpow

/-- Proposition 7.55, converse reduced to Milne's two valuation-theoretic
inputs.  A uniformizer whose minimal polynomial is Eisenstein and which
satisfies the order-generation hypotheses is an Eisenstein generator. -/
theorem eisenstein_uniformizer_data
    {R S : Type*} [CommRing R] [CommRing S] [Algebra R S] [IsLocalRing R]
    (pi q u : S) (d m : ℕ)
    (hpiInt : IsIntegral R pi)
    (hpiEis : (minpoly R pi).IsEisensteinAt (IsLocalRing.maximalIdeal R))
    (hdecomp : ∀ x : S, ∃ a : S, a ∈ Algebra.adjoin R {pi} ∧
      ∃ y : S, x = a + pi * y)
    (hscale : ∀ x : S, q ^ m * x ∈ Algebra.adjoin R {pi})
    (hpow : pi ^ d = q * u) :
    HasEisensteinGenerator R S (IsLocalRing.maximalIdeal R) := by
  refine ⟨pi, hpiInt, ?_, hpiEis⟩
  exact adjoin_uniformizer_containment
    pi q u d m hdecomp hscale hpow

/-- The valuation-theoretic final step in the converse of Proposition 7.55.
Suppose the reduction of the minimal polynomial of a uniformizer `alpha` is
`X ^ n`, and the prime downstairs extends to the `n`th power of `(alpha)`.
Then its constant coefficient cannot lie in the square of the prime: otherwise
the minimal-polynomial relation would make `alpha ^ (n + 1)` divide
`alpha ^ n`.  Hence the minimal polynomial is Eisenstein. -/
theorem minpoly_eisenstein_distinguished
    {A B : Type*} [CommRing A] [CommRing B] [IsDomain B] [Algebra A B]
    {p : Ideal A} {alpha : B} (halpha : IsIntegral A alpha)
    (halphaPrime : Prime alpha)
    (hmap : p.map (algebraMap A B) =
      (Ideal.span ({alpha} : Set B)) ^ (minpoly A alpha).natDegree)
    (hdist : (minpoly A alpha).IsDistinguishedAt p) :
    (minpoly A alpha).IsEisensteinAt p := by
  let n := (minpoly A alpha).natDegree
  have hn : 0 < n := minpoly.natDegree_pos halpha
  have hp : p ≠ ⊤ := by
    intro hp
    have hpow : (Ideal.span ({alpha} : Set B)) ^ n = ⊤ := by
      rw [← hmap, hp, Ideal.map_top]
    rw [Ideal.pow_eq_top_iff] at hpow
    rcases hpow with hspan | hn0
    · exact (Ideal.span_singleton_ne_top halphaPrime.not_unit) hspan
    · exact hn.ne' hn0
  apply (minpoly.monic halpha).isEisensteinAt_of_mem_of_notMem
  · exact hp
  · exact fun hi => hdist.mem hi
  · intro hconstant
    have hcoeff_mem (i : ℕ) (hi : i < n) :
        algebraMap A B ((minpoly A alpha).coeff i) * alpha ^ i ∈
          Ideal.span ({alpha ^ (n + 1)} : Set B) := by
      rw [Ideal.mem_span_singleton]
      by_cases hi0 : i = 0
      · subst i
        simp only [pow_zero, mul_one]
        have hmem : algebraMap A B ((minpoly A alpha).coeff 0) ∈
            (p ^ 2).map (algebraMap A B) := Ideal.mem_map_of_mem _ hconstant
        rw [Ideal.map_pow, hmap, ← pow_mul, Ideal.span_singleton_pow,
          Ideal.mem_span_singleton] at hmem
        exact (pow_dvd_pow alpha (by omega : n + 1 ≤ n * 2)).trans hmem
      · have hmem : algebraMap A B ((minpoly A alpha).coeff i) ∈
            p.map (algebraMap A B) :=
          Ideal.mem_map_of_mem _ (hdist.mem hi)
        rw [hmap, Ideal.span_singleton_pow, Ideal.mem_span_singleton] at hmem
        have hpow : alpha ^ (n + 1) ∣ alpha ^ n * alpha ^ i := by
          simpa [← pow_add] using
            (pow_dvd_pow alpha (by omega : n + 1 ≤ n + i))
        exact hpow.trans (mul_dvd_mul_right hmem (alpha ^ i))
    have hsum : ∑ i ∈ Finset.range n,
        algebraMap A B ((minpoly A alpha).coeff i) * alpha ^ i ∈
          Ideal.span ({alpha ^ (n + 1)} : Set B) := by
      exact Ideal.sum_mem _ fun i hi => hcoeff_mem i (Finset.mem_range.mp hi)
    have hroot := minpoly.aeval A alpha
    rw [aeval_eq_sum_range, Finset.sum_range_succ,
      (minpoly.monic halpha).coeff_natDegree, one_smul] at hroot
    have hpown : alpha ^ n ∈ Ideal.span ({alpha ^ (n + 1)} : Set B) := by
      have heq : alpha ^ n = -∑ i ∈ Finset.range n,
          algebraMap A B ((minpoly A alpha).coeff i) * alpha ^ i := by
        simpa [n, Algebra.smul_def] using eq_neg_of_add_eq_zero_right hroot
      rw [heq]
      exact (Submodule.neg_mem_iff _).mpr hsum
    have hdiv : alpha ^ (n + 1) ∣ alpha ^ n :=
      Ideal.mem_span_singleton.mp hpown
    have := (pow_dvd_pow_iff halphaPrime.ne_zero halphaPrime.not_unit).mp hdiv
    omega

/-- The coefficient-divisibility step in the converse of Proposition 7.55.
If `(alpha)` lies over `p`, the extension of `p` is a sufficiently high power
of `(alpha)`, and that exponent is at least the degree of the minimal
polynomial, then the minimal polynomial is distinguished at `p`.

The proof follows Milne's valuation argument algebraically.  Inducting through
the coefficients, all earlier terms in the minimal-polynomial relation are
divisible by the full ramification power, while every later term contains an
extra power of `alpha`.  Cancellation forces the current coefficient to lie
in the contraction of `(alpha)`, namely `p`. -/
theorem minpol_disti_ramif
    {A B : Type*} [CommRing A] [CommRing B] [IsDomain B] [Algebra A B]
    {p : Ideal A} {alpha : B} (halpha : IsIntegral A alpha)
    (halphaPrime : Prime alpha)
    (hover : (Ideal.span ({alpha} : Set B)).comap (algebraMap A B) = p)
    {e : ℕ} (hdegree : (minpoly A alpha).natDegree ≤ e)
    (hmap : p.map (algebraMap A B) = (Ideal.span ({alpha} : Set B)) ^ e) :
    (minpoly A alpha).IsDistinguishedAt p := by
  let d := (minpoly A alpha).natDegree
  refine ⟨⟨?_⟩, minpoly.monic halpha⟩
  intro i hi
  induction i using Nat.strong_induction_on with
  | h i ih =>
      let I : Ideal B := Ideal.span ({alpha ^ (i + 1)} : Set B)
      have hother (j : ℕ) (hj : j < d) (hji : j ≠ i) :
          algebraMap A B ((minpoly A alpha).coeff j) * alpha ^ j ∈ I := by
        rw [Ideal.mem_span_singleton]
        rcases lt_or_gt_of_ne hji with hlt | hgt
        · have hcoeff : (minpoly A alpha).coeff j ∈ p := ih j hlt hj
          have hcoeffMap : algebraMap A B ((minpoly A alpha).coeff j) ∈
              p.map (algebraMap A B) := Ideal.mem_map_of_mem _ hcoeff
          rw [hmap, Ideal.span_singleton_pow, Ideal.mem_span_singleton] at hcoeffMap
          have hpow : alpha ^ (i + 1) ∣ alpha ^ e * alpha ^ j := by
            simpa [← pow_add] using
              (pow_dvd_pow alpha (by omega : i + 1 ≤ e + j))
          exact hpow.trans (mul_dvd_mul_right hcoeffMap (alpha ^ j))
        · have hpow : alpha ^ (i + 1) ∣ alpha ^ j :=
            pow_dvd_pow alpha hgt
          exact dvd_mul_of_dvd_right hpow _
      have hiRange : i ∈ Finset.range d := Finset.mem_range.mpr hi
      have hrest :
          (∑ j ∈ (Finset.range d).erase i,
              algebraMap A B ((minpoly A alpha).coeff j) * alpha ^ j) +
              alpha ^ d ∈ I := by
        apply I.add_mem
        · apply Ideal.sum_mem
          intro j hj
          exact hother j (Finset.mem_range.mp (Finset.mem_of_mem_erase hj))
            (Finset.ne_of_mem_erase hj)
        · rw [Ideal.mem_span_singleton]
          exact pow_dvd_pow alpha (by omega)
      have hroot := minpoly.aeval A alpha
      rw [aeval_eq_sum_range, Finset.sum_range_succ,
        (minpoly.monic halpha).coeff_natDegree, one_smul] at hroot
      have hzero :
          algebraMap A B ((minpoly A alpha).coeff i) * alpha ^ i +
            ((∑ j ∈ (Finset.range d).erase i,
                algebraMap A B ((minpoly A alpha).coeff j) * alpha ^ j) +
              alpha ^ d) = 0 := by
        have hsumErase :
            (∑ j ∈ (Finset.range d).erase i,
                algebraMap A B ((minpoly A alpha).coeff j) * alpha ^ j) +
              algebraMap A B ((minpoly A alpha).coeff i) * alpha ^ i =
            ∑ j ∈ Finset.range d,
              algebraMap A B ((minpoly A alpha).coeff j) * alpha ^ j :=
          Finset.sum_erase_add (Finset.range d)
            (fun j => algebraMap A B ((minpoly A alpha).coeff j) * alpha ^ j) hiRange
        calc
          _ = (∑ j ∈ (Finset.range d).erase i,
                algebraMap A B ((minpoly A alpha).coeff j) * alpha ^ j) +
              algebraMap A B ((minpoly A alpha).coeff i) * alpha ^ i +
              alpha ^ d := by ac_rfl
          _ = 0 := by
            rw [hsumErase]
            simpa [d, Algebra.smul_def] using hroot
      have hterm : algebraMap A B ((minpoly A alpha).coeff i) * alpha ^ i ∈ I := by
        rw [eq_neg_of_add_eq_zero_left hzero]
        exact (Submodule.neg_mem_iff _).mpr hrest
      rw [Ideal.mem_span_singleton] at hterm
      obtain ⟨c, hc⟩ := hterm
      have hcancel : algebraMap A B ((minpoly A alpha).coeff i) = alpha * c := by
        apply mul_left_cancel₀ (pow_ne_zero i halphaPrime.ne_zero)
        calc
          alpha ^ i * algebraMap A B ((minpoly A alpha).coeff i) =
              algebraMap A B ((minpoly A alpha).coeff i) * alpha ^ i := mul_comm _ _
          _ = alpha ^ (i + 1) * c := hc
          _ = alpha ^ i * (alpha * c) := by rw [pow_succ, mul_assoc]
      have hmem : algebraMap A B ((minpoly A alpha).coeff i) ∈
          Ideal.span ({alpha} : Set B) :=
        Ideal.mem_span_singleton.mpr ⟨c, hcancel⟩
      rw [← hover]
      exact hmem

/-- Proposition 7.55, intrinsic converse for the minimal polynomial.  In a
finite totally ramified extension of discrete valuation rings, every
uniformizer upstairs has Eisenstein minimal polynomial downstairs. -/
theorem minpoly_eisenstein_ramified
    (A B K L : Type*) [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    [CommRing B] [IsDomain B] [IsDiscreteValuationRing B] [Algebra A B]
    [Module.Finite A B] [Module.IsTorsionFree A B]
    [Field K] [Algebra A K] [IsFractionRing A K]
    [Field L] [Algebra B L] [IsFractionRing B L]
    [Algebra K L] [FiniteDimensional K L] [Algebra A L]
    [IsScalarTower A B L] [IsScalarTower A K L]
    (htr : TotallyRamified A B (IsLocalRing.maximalIdeal A))
    (Pi : B) (hPi : Irreducible Pi) :
    (minpoly A Pi).IsEisensteinAt (IsLocalRing.maximalIdeal A) := by
  have hPiInt : IsIntegral A Pi := Algebra.IsIntegral.isIntegral Pi
  rcases htr with ⟨P, hPprime, hPover, hmap, _hram, _hunique⟩
  have hp0 : IsLocalRing.maximalIdeal A ≠ ⊥ :=
    IsDiscreteValuationRing.not_a_field A
  have hP0 : P ≠ ⊥ := Ideal.ne_bot_of_liesOver_of_ne_bot hp0 P
  have hPmax : P = IsLocalRing.maximalIdeal B :=
    IsLocalRing.eq_maximalIdeal (hPprime.isMaximal hP0)
  have hPspan : P = Ideal.span ({Pi} : Set B) :=
    hPmax.trans hPi.maximalIdeal_eq
  have hover : (Ideal.span ({Pi} : Set B)).comap (algebraMap A B) =
      IsLocalRing.maximalIdeal A := by
    simpa [← hPspan] using hPover.over.symm
  have hfieldDegree :
      (minpoly K (algebraMap B L Pi)).natDegree = (minpoly A Pi).natDegree := by
    rw [minpoly.isIntegrallyClosed_eq_field_fractions K L hPiInt,
      (minpoly.monic hPiInt).natDegree_map]
  have hfieldRank : Module.finrank K L = Module.finrank A B :=
    Algebra.IsAlgebraic.finrank_of_isFractionRing A K B L
  have hdegree : (minpoly A Pi).natDegree ≤ Module.finrank A B := by
    rw [← hfieldDegree, ← hfieldRank]
    exact minpoly.natDegree_le (algebraMap B L Pi)
  have hmapSpan : (IsLocalRing.maximalIdeal A).map (algebraMap A B) =
      (Ideal.span ({Pi} : Set B)) ^ Module.finrank A B := by
    simpa [hPspan] using hmap
  have hdist : (minpoly A Pi).IsDistinguishedAt
      (IsLocalRing.maximalIdeal A) :=
    minpol_disti_ramif hPiInt hPi.prime
      hover hdegree hmapSpan
  have hmapMax : (IsLocalRing.maximalIdeal A).map (algebraMap A B) =
      (IsLocalRing.maximalIdeal B) ^ Module.finrank A B := by
    simpa [hPi.maximalIdeal_eq] using hmapSpan
  have hdegreeEq : (minpoly A Pi).natDegree = Module.finrank A B :=
    minpoly_weakly_uniformizer
      A B K L Pi hPi hmapMax hdist.toIsWeaklyEisensteinAt
  have hmapMin : (IsLocalRing.maximalIdeal A).map (algebraMap A B) =
      (Ideal.span ({Pi} : Set B)) ^ (minpoly A Pi).natDegree := by
    simpa [hdegreeEq] using hmapSpan
  exact minpoly_eisenstein_distinguished
    hPiInt hPi.prime hmapMin hdist

/-- Milne, Remark 7.56: over a discrete valuation ring, an Eisenstein generator of the
fraction-field extension also generates the integral closure. Thus, when `alpha` is the
uniformizer supplied by the converse direction of Proposition 7.55, the valuation ring upstairs
is exactly `A[alpha]`.

The proof is Milne's discriminant argument. The discriminant clears denominators of every
integral element; in a DVR it is associated to a power of the chosen prime, and the Eisenstein
condition lets us divide that power back out while remaining in the generated order. -/
theorem adjoin_minpoly_eisenstein
    (A K L : Type*) [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    [Field K] [Field L] [Algebra A K] [IsFractionRing A K]
    [Algebra K L] [Algebra A L] [IsScalarTower A K L]
    [FiniteDimensional K L] [Algebra.IsSeparable K L]
    (B : PowerBasis K L) (hBint : IsIntegral A B.gen)
    {pi : A} (hpi : Irreducible pi)
    (heis : (minpoly A B.gen).IsEisensteinAt (Ideal.span {pi})) :
    Algebra.adjoin A ({B.gen} : Set L) = integralClosure A L := by
  apply le_antisymm
  · exact adjoin_le_integralClosure hBint
  · intro z hz
    have hzint : IsIntegral A z := (mem_integralClosure_iff A L).mp hz
    have hdisc : Algebra.discr K B.basis ≠ 0 := Algebra.discr_not_zero_of_basis K B.basis
    have hdiscInt : IsIntegral A (Algebra.discr K B.basis) := by
      apply Algebra.discr_isIntegral
      intro i
      rw [B.basis_eq_pow]
      exact hBint.pow i
    obtain ⟨discA, hdiscA⟩ := IsIntegrallyClosed.isIntegral_iff.mp hdiscInt
    have hdiscA0 : discA ≠ 0 := by
      intro hzero
      apply hdisc
      rw [← hdiscA, hzero, map_zero]
    obtain ⟨n, hn⟩ :=
      IsDiscreteValuationRing.associated_pow_irreducible (R := A) hdiscA0 hpi
    obtain ⟨c, hc⟩ := hn.dvd
    have hdisc_z : Algebra.discr K B.basis • z ∈
        Algebra.adjoin A ({B.gen} : Set L) :=
      Algebra.discr_mul_isIntegral_mem_adjoin
        (K := K) (R := A) (L := L) (B := B) hBint hzint
    have hdiscA_z : discA • z ∈ Algebra.adjoin A ({B.gen} : Set L) := by
      rw [← IsScalarTower.algebraMap_smul K, hdiscA]
      exact hdisc_z
    have hpi_z : pi ^ n • z ∈ Algebra.adjoin A ({B.gen} : Set L) := by
      rw [hc, mul_smul]
      simpa [smul_smul, mul_comm] using
        (Algebra.adjoin A ({B.gen} : Set L)).smul_mem hdiscA_z c
    exact mem_adjoin_of_smul_prime_pow_smul_of_minpoly_isEisensteinAt
      hpi.prime hBint hzint hpi_z heis

/-- Fixed-generator form of the converse in Proposition 7.55.  Under total
ramification, an upstairs uniformizer with weakly Eisenstein minimal
polynomial is integral, generates the entire upstairs valuation ring, and
has Eisenstein minimal polynomial.

The preceding degree and norm arguments promote weak Eisenstein to Eisenstein and show that
the uniformizer generates the fraction field.  Milne's discriminant argument then identifies
the generated order with the integral closure, and injectivity of `B → L` transports this
equality back to `B`. -/
theorem eisenstein_ramified_weakly
    (A B K L : Type*) [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    [CommRing B] [IsDomain B] [IsDiscreteValuationRing B] [Algebra A B]
    [Module.Finite A B] [Module.IsTorsionFree A B]
    [Field K] [Algebra A K] [IsFractionRing A K]
    [Field L] [Algebra B L] [IsFractionRing B L]
    [Algebra K L] [FiniteDimensional K L] [Algebra A L]
    [IsScalarTower A B L] [IsScalarTower A K L]
    [Algebra.IsSeparable K L] [PerfectField (FractionRing A)]
    (htr : TotallyRamified A B (IsLocalRing.maximalIdeal A))
    (Pi : B) (hPi : Irreducible Pi)
    (hweak : (minpoly A Pi).IsWeaklyEisensteinAt
      (IsLocalRing.maximalIdeal A)) :
    IsIntegral A Pi ∧
      Algebra.adjoin A ({Pi} : Set B) = ⊤ ∧
      (minpoly A Pi).IsEisensteinAt
        (IsLocalRing.maximalIdeal A) := by
  have hPiInt : IsIntegral A Pi := Algebra.IsIntegral.isIntegral Pi
  have heis : (minpoly A Pi).IsEisensteinAt
      (IsLocalRing.maximalIdeal A) :=
    minpoly_eisenstein_weakly
      A B K L htr Pi hPi hweak
  let piL : L := algebraMap B L Pi
  have hgen : IntermediateField.adjoin K ({piL} : Set L) = ⊤ :=
    fraction_weakly_eisenstein
      A B K L htr Pi hPi hweak
  have hpiLInt : IsIntegral K piL := Algebra.IsIntegral.isIntegral piL
  have hgenAlg : Algebra.adjoin K ({piL} : Set L) = ⊤ := by
    rw [← IntermediateField.adjoin_simple_toSubalgebra_of_isAlgebraic
        (Algebra.IsAlgebraic.isAlgebraic piL),
      hgen]
    rfl
  let powerBasis : PowerBasis K L := PowerBasis.ofAdjoinEqTop hpiLInt hgenAlg
  have hpowerBasisGen : powerBasis.gen = piL := by
    exact PowerBasis.ofAdjoinEqTop_gen hpiLInt hgenAlg
  have hpiLIntA : IsIntegral A piL :=
    hPiInt.map (IsScalarTower.toAlgHom A B L)
  have hpowerBasisInt : IsIntegral A powerBasis.gen := by
    simpa [hpowerBasisGen] using hpiLIntA
  obtain ⟨q, hq⟩ := IsDiscreteValuationRing.exists_irreducible A
  have hpq : IsLocalRing.maximalIdeal A = Ideal.span ({q} : Set A) :=
    hq.maximalIdeal_eq
  have hmin : minpoly A piL = minpoly A Pi := by
    exact minpoly.algebraMap_eq (IsFractionRing.injective B L) Pi
  have heisL : (minpoly A powerBasis.gen).IsEisensteinAt
      (Ideal.span ({q} : Set A)) := by
    simpa [hpowerBasisGen, hmin, ← hpq] using heis
  have hclosure : Algebra.adjoin A ({piL} : Set L) = integralClosure A L := by
    simpa [hpowerBasisGen] using
      adjoin_minpoly_eisenstein
        A K L powerBasis hpowerBasisInt hq heisL
  have hadjoin : Algebra.adjoin A ({Pi} : Set B) = ⊤ := by
    apply top_unique
    intro x _hx
    let f : B →ₐ[A] L := IsScalarTower.toAlgHom A B L
    have hxInt : IsIntegral A (f x) :=
      (Algebra.IsIntegral.isIntegral x).map f
    have hxClosure : f x ∈ integralClosure A L :=
      (mem_integralClosure_iff A L).2 hxInt
    have hxL : f x ∈ Algebra.adjoin A ({piL} : Set L) := by
      rw [hclosure]
      exact hxClosure
    have hxMap : f x ∈ (Algebra.adjoin A ({Pi} : Set B)).map f := by
      rw [AlgHom.map_adjoin, Set.image_singleton]
      exact hxL
    rw [Subalgebra.mem_map] at hxMap
    rcases hxMap with ⟨y, hy, hxy⟩
    have hyx : y = x := (FaithfulSMul.algebraMap_injective B L) hxy
    simpa [hyx] using hy
  exact ⟨hPiInt, hadjoin, heis⟩

/-- Proposition 7.55, converse reduced to the weak-Eisenstein coefficient
statement supplied by the uniqueness of the extended complete discrete
valuation. -/
theorem eisenstein_totally_weakly
    (A B K L : Type*) [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    [CommRing B] [IsDomain B] [IsDiscreteValuationRing B] [Algebra A B]
    [Module.Finite A B] [Module.IsTorsionFree A B]
    [Field K] [Algebra A K] [IsFractionRing A K]
    [Field L] [Algebra B L] [IsFractionRing B L]
    [Algebra K L] [FiniteDimensional K L] [Algebra A L]
    [IsScalarTower A B L] [IsScalarTower A K L]
    [Algebra.IsSeparable K L] [PerfectField (FractionRing A)]
    (htr : TotallyRamified A B (IsLocalRing.maximalIdeal A))
    (Pi : B) (hPi : Irreducible Pi)
    (hweak : (minpoly A Pi).IsWeaklyEisensteinAt
      (IsLocalRing.maximalIdeal A)) :
    HasEisensteinGenerator A B (IsLocalRing.maximalIdeal A) := by
  exact ⟨Pi,
    eisenstein_ramified_weakly
      A B K L htr Pi hPi hweak⟩

/-- An Eisenstein generator of an integral order also generates its fraction
field.  This is the field-level bridge used when Proposition 7.55 is fed into
the compactness argument of Proposition 7.64. -/
theorem fraction_generator_eisenstein
    (A B K L : Type*) [CommRing A] [IsDomain A] [IsIntegrallyClosed A]
    [CommRing B] [IsDomain B] [Algebra A B]
    [Module.Finite A B] [Module.IsTorsionFree A B]
    [Field K] [Algebra A K] [IsFractionRing A K]
    [Field L] [Algebra B L] [IsFractionRing B L]
    [Algebra K L] [FiniteDimensional K L] [Algebra A L]
    [IsScalarTower A B L] [IsScalarTower A K L]
    {p : Ideal A} (hgen : HasEisensteinGenerator A B p) :
    ∃ alpha : B,
      IsIntegral A alpha ∧
        (minpoly A alpha).IsEisensteinAt p ∧
        IntermediateField.adjoin K ({algebraMap B L alpha} : Set L) = ⊤ := by
  rcases hgen with ⟨alpha, halpha, hadjoin, heis⟩
  refine ⟨alpha, halpha, heis, ?_⟩
  apply (Field.primitive_element_iff_minpoly_natDegree_eq K
    (algebraMap B L alpha)).2
  let hroot : IsAdjoinRootMonic B (minpoly A alpha) :=
    IsAdjoinRootMonic.mkOfAdjoinEqTop halpha hadjoin
  rw [minpoly.isIntegrallyClosed_eq_field_fractions K L halpha,
    (minpoly.monic halpha).natDegree_map, ← hroot.finrank,
    Algebra.IsAlgebraic.finrank_of_isFractionRing A K B L]

/-- Milne, Proposition 7.55, converse for a chosen upstairs uniformizer.
If the extension is totally ramified, every irreducible element of the upstairs
discrete valuation ring is an Eisenstein generator. -/
theorem eisenstein_totally_uniformizer
    (A B K L : Type*) [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    [CommRing B] [IsDomain B] [IsDiscreteValuationRing B] [Algebra A B]
    [Module.Finite A B] [Module.IsTorsionFree A B]
    [Field K] [Algebra A K] [IsFractionRing A K]
    [Field L] [Algebra B L] [IsFractionRing B L]
    [Algebra K L] [FiniteDimensional K L] [Algebra A L]
    [IsScalarTower A B L] [IsScalarTower A K L]
    [Algebra.IsSeparable K L] [PerfectField (FractionRing A)]
    (htr : TotallyRamified A B (IsLocalRing.maximalIdeal A))
    (Pi : B) (hPi : Irreducible Pi) :
    HasEisensteinGenerator A B (IsLocalRing.maximalIdeal A) := by
  have heis : (minpoly A Pi).IsEisensteinAt
      (IsLocalRing.maximalIdeal A) :=
    minpoly_eisenstein_ramified A B K L htr Pi hPi
  exact eisenstein_totally_weakly
    A B K L htr Pi hPi heis.isWeaklyEisensteinAt

/-- Milne, Proposition 7.55, converse: a finite totally ramified extension of
complete discretely valued fields is generated integrally by a root of an
Eisenstein polynomial. -/
theorem eisenstein_generator_ramified
    (A B K L : Type*) [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    [CommRing B] [IsDomain B] [IsDiscreteValuationRing B] [Algebra A B]
    [Module.Finite A B] [Module.IsTorsionFree A B]
    [Field K] [Algebra A K] [IsFractionRing A K]
    [Field L] [Algebra B L] [IsFractionRing B L]
    [Algebra K L] [FiniteDimensional K L] [Algebra A L]
    [IsScalarTower A B L] [IsScalarTower A K L]
    [Algebra.IsSeparable K L] [PerfectField (FractionRing A)]
    (htr : TotallyRamified A B (IsLocalRing.maximalIdeal A)) :
    HasEisensteinGenerator A B (IsLocalRing.maximalIdeal A) := by
  obtain ⟨Pi, hPi⟩ := IsDiscreteValuationRing.exists_irreducible B
  exact eisenstein_totally_uniformizer
    A B K L htr Pi hPi

/-- Proposition 7.55 in field-generator form: a finite totally ramified
extension of complete discrete valuation fields has an integral generator
whose minimal polynomial is Eisenstein, and that element generates the whole
fraction-field extension. -/
theorem fraction_eisenstein_ramified
    (A B K L : Type*) [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    [CommRing B] [IsDomain B] [IsDiscreteValuationRing B] [Algebra A B]
    [Module.Finite A B] [Module.IsTorsionFree A B]
    [Field K] [Algebra A K] [IsFractionRing A K]
    [Field L] [Algebra B L] [IsFractionRing B L]
    [Algebra K L] [FiniteDimensional K L] [Algebra A L]
    [IsScalarTower A B L] [IsScalarTower A K L]
    (htr : TotallyRamified A B (IsLocalRing.maximalIdeal A)) :
    ∃ alpha : B,
      IsIntegral A alpha ∧
        (minpoly A alpha).IsEisensteinAt
          (IsLocalRing.maximalIdeal A) ∧
        IntermediateField.adjoin K ({algebraMap B L alpha} : Set L) = ⊤ := by
  obtain ⟨Pi, hPi⟩ := IsDiscreteValuationRing.exists_irreducible B
  have heis : (minpoly A Pi).IsEisensteinAt
      (IsLocalRing.maximalIdeal A) :=
    minpoly_eisenstein_ramified A B K L htr Pi hPi
  refine ⟨Pi, Algebra.IsIntegral.isIntegral Pi, heis, ?_⟩
  exact fraction_weakly_eisenstein
    A B K L htr Pi hPi heis.isWeaklyEisensteinAt

end Towers.NumberTheory.Milne
