import Mathlib
import Towers.Group.DenseGenerators.ZassenhausSeparation
import Towers.Group.PowerWidth.DenseQuotient


open scoped Topology Pointwise

noncomputable section

namespace Towers

universe u
universe v w z

/-- Large enough prime powers exist. -/
lemma exists_pow_ge
    (p n : ℕ) [Fact p.Prime] :
    ∃ j : ℕ, n ≤ p ^ j := by
  refine ⟨n, ?_⟩
  have hp2 : 2 ≤ p := (Fact.out : Nat.Prime p).two_le
  exact
    n.lt_two_pow_self.le.trans
      (Nat.pow_le_pow_left hp2 n)
/-- The subgroup generated by `p^j`th powers lies in `D_n` whenever `n ≤ p^j`. -/
lemma power_subgroup_filtration
    {p : ℕ}
    {Γ : Type u} [Group Γ]
    {n j : ℕ}
    (hjn : n ≤ p ^ j) :
    powerSubgroup Γ (p ^ j) ≤ zassenhausFiltration p Γ n := by
  rw [powerSubgroup]
  haveI : (zassenhausFiltration p Γ n).Normal :=
    zassenhausFiltration_normal p Γ n
  refine Subgroup.normalClosure_le_normal ?_
  rintro _ ⟨x, rfl⟩
  rw [zassenhausFiltration]
  exact Subgroup.subset_closure
    ⟨0, j, x, by simp [Subgroup.lowerCentralSeries_zero], by simpa using hjn, rfl⟩
/-- A Nikolov-Segal prime-power subgroup input gives an open normal subgroup inside `D_n`.

This is a bridge lemma: the hard mathematical work is isolated in the hypothesis that some open
normal subgroup lies in each prime-power subgroup. The rest is just the defining `i = 0`
Zassenhaus generator. -/
lemma open_filtration_power
    {p : ℕ} [Fact p.Prime]
    {Γ : Type u} [Group Γ] [TopologicalSpace Γ]
    {n : ℕ}
    (hpower :
      ∀ j : ℕ, ∃ N : OpenNormalSubgroup Γ,
        N.toSubgroup ≤ powerSubgroup Γ (p ^ j)) :
    ∃ N : OpenNormalSubgroup Γ,
      N.toSubgroup ≤ zassenhausFiltration p Γ n := by
  rcases exists_pow_ge p n with ⟨j, hj⟩
  rcases hpower j with ⟨N, hN⟩
  exact ⟨N, hN.trans (power_subgroup_filtration (p := p) hj)⟩
/-- If a power subgroup is open, it is itself an open normal subgroup. -/
lemma open_normal_power
    {Γ : Type u} [Group Γ] [TopologicalSpace Γ]
    {m : ℕ}
    (hopen : IsOpen ((powerSubgroup Γ m : Subgroup Γ) : Set Γ)) :
    ∃ N : OpenNormalSubgroup Γ,
      N.toSubgroup ≤ powerSubgroup Γ m := by
  let N : OpenNormalSubgroup Γ :=
    { toOpenSubgroup :=
        { toSubgroup := powerSubgroup Γ m
          isOpen' := hopen }
      isNormal' := powerSubgroup_normal Γ m }
  exact ⟨N, by intro x hx; simpa [N] using hx⟩
/-- Openness of all prime-power subgroups gives an open normal subgroup inside `D_n`. -/
lemma open_normal_filtration
    {p : ℕ} [Fact p.Prime]
    {Γ : Type u} [Group Γ] [TopologicalSpace Γ]
    {n : ℕ}
    (hopen :
      ∀ j : ℕ, IsOpen ((powerSubgroup Γ (p ^ j) : Subgroup Γ) : Set Γ)) :
    ∃ N : OpenNormalSubgroup Γ,
      N.toSubgroup ≤ zassenhausFiltration p Γ n := by
  refine
    open_filtration_power
      (p := p) (Γ := Γ) (n := n) ?_
  intro j
  exact open_normal_power (hopen j)
/-- Zassenhaus filtrations commute with surjective homomorphisms. -/
lemma filtration_surjective
    {p : ℕ}
    {Γ Λ : Type u} [Group Γ] [Group Λ]
    (n : ℕ)
    (φ : Γ →* Λ)
    (hφ : Function.Surjective φ) :
    Subgroup.map φ (zassenhausFiltration p Γ n) =
      zassenhausFiltration p Λ n := by
  rw [zassenhausFiltration,
    zassenhausFiltration,
    ← image_set_surjective p n φ hφ]
  exact MonoidHom.map_closure φ (zassenhausGeneratorSet p Γ n)
/-- In an open-normal quotient, the target Zassenhaus subgroup is the image of the source one. -/
lemma zassenhaus_filtration_quotient
    {p : ℕ}
    {Γ : Type u} [Group Γ] [TopologicalSpace Γ]
    (N : OpenNormalSubgroup Γ)
    (n : ℕ) :
    zassenhausFiltration p (Γ ⧸ N.toSubgroup) n =
      Subgroup.map (QuotientGroup.mk' N.toSubgroup)
        (zassenhausFiltration p Γ n) := by
  simpa using
    (filtration_surjective
      (p := p)
      (Γ := Γ)
      (Λ := Γ ⧸ N.toSubgroup)
      n
      (QuotientGroup.mk' N.toSubgroup)
      (QuotientGroup.mk'_surjective N.toSubgroup)).symm
/-- An open normal subgroup contained in `D_n` separates every point outside `D_n`. -/
lemma filtration_separates_normal
    {p : ℕ}
    {Γ : Type u} [Group Γ] [TopologicalSpace Γ]
    {n : ℕ}
    (N : OpenNormalSubgroup Γ)
    (hN : N.toSubgroup ≤ zassenhausFiltration p Γ n)
    {g : Γ}
    (hg : g ∉ zassenhausFiltration p Γ n) :
    QuotientGroup.mk' N.toSubgroup g ∉
      zassenhausFiltration p (Γ ⧸ N.toSubgroup) n := by
  intro hgq
  let π : Γ →* Γ ⧸ N.toSubgroup := QuotientGroup.mk' N.toSubgroup
  have hgmap :
      π g ∈ Subgroup.map π (zassenhausFiltration p Γ n) := by
    simpa [π, zassenhaus_filtration_quotient (p := p) N n] using hgq
  rcases hgmap with ⟨x, hxD, hxg⟩
  have hxNg : x⁻¹ * g ∈ N.toSubgroup := by
    refine (QuotientGroup.eq_one_iff (N := N.toSubgroup) (x⁻¹ * g)).mp ?_
    calc
      π (x⁻¹ * g) = (π x)⁻¹ * π g := by simp [π]
      _ = 1 := by simp [hxg]
  have hxNgD : x⁻¹ * g ∈ zassenhausFiltration p Γ n :=
    hN hxNg
  exact hg <| by
    have hdecomp : g = x * (x⁻¹ * g) := by group
    rw [hdecomp]
    exact (zassenhausFiltration p Γ n).mul_mem hxD hxNgD
/-- An open normal subgroup inside a large enough power subgroup separates outside `D_n`. -/
lemma separates_open_subgroup
    {p : ℕ}
    {Γ : Type u} [Group Γ] [TopologicalSpace Γ]
    {n j : ℕ}
    (hjn : n ≤ p ^ j)
    (N : OpenNormalSubgroup Γ)
    (hN : N.toSubgroup ≤ powerSubgroup Γ (p ^ j))
    {g : Γ}
    (hg : g ∉ zassenhausFiltration p Γ n) :
    QuotientGroup.mk' N.toSubgroup g ∉
      zassenhausFiltration p (Γ ⧸ N.toSubgroup) n := by
  exact
    filtration_separates_normal
      (p := p)
      (Γ := Γ)
      (n := n)
      N
      (le_trans hN
        (power_subgroup_filtration
          (p := p) (Γ := Γ) (n := n) (j := j) hjn))
      (g := g)
      hg
/-- Openness of one sufficiently deep prime-power subgroup is enough for finite-quotient
separation outside `D_n`. -/
lemma filtration_separates_subgroup
    {p : ℕ}
    {Γ : Type u} [Group Γ] [TopologicalSpace Γ]
    {n j : ℕ}
    (hjn : n ≤ p ^ j)
    (hpow : IsOpen ((powerSubgroup Γ (p ^ j) : Subgroup Γ) : Set Γ))
    {g : Γ}
    (hg : g ∉ zassenhausFiltration p Γ n) :
    ∃ N : OpenNormalSubgroup Γ,
      QuotientGroup.mk' N.toSubgroup g ∉
        zassenhausFiltration p (Γ ⧸ N.toSubgroup) n := by
  rcases
      open_normal_power
        (Γ := Γ)
        (m := p ^ j)
        hpow with
    ⟨N, hN⟩
  exact
    ⟨N,
      separates_open_subgroup
        (p := p)
        (Γ := Γ)
        (n := n)
        (j := j)
        hjn
        N
        hN
        (g := g)
        hg⟩
/-- It is enough to know openness of prime-power subgroups for prime powers at least `n`. -/
lemma filtration_separates_eventually
    {p : ℕ} [Fact p.Prime]
    {Γ : Type u} [Group Γ] [TopologicalSpace Γ]
    {n : ℕ}
    (hopen :
      ∀ j : ℕ, n ≤ p ^ j →
        IsOpen ((powerSubgroup Γ (p ^ j) : Subgroup Γ) : Set Γ))
    {g : Γ}
    (hg : g ∉ zassenhausFiltration p Γ n) :
    ∃ N : OpenNormalSubgroup Γ,
      QuotientGroup.mk' N.toSubgroup g ∉
        zassenhausFiltration p (Γ ⧸ N.toSubgroup) n := by
  rcases exists_pow_ge p n with ⟨j, hjn⟩
  exact
    filtration_separates_subgroup
      (p := p)
      (Γ := Γ)
      (n := n)
      (j := j)
      hjn
      (hopen j hjn)
      (g := g)
      hg
/-- Prime-power open-normal input implies finite-quotient separation for `D_n`. -/
lemma zassenhaus_filtration_separates
    {p : ℕ} [Fact p.Prime]
    {Γ : Type u} [Group Γ] [TopologicalSpace Γ]
    {n : ℕ}
    (hpower :
      ∀ j : ℕ, ∃ N : OpenNormalSubgroup Γ,
        N.toSubgroup ≤ powerSubgroup Γ (p ^ j))
    {g : Γ}
    (hg : g ∉ zassenhausFiltration p Γ n) :
    ∃ N : OpenNormalSubgroup Γ,
      QuotientGroup.mk' N.toSubgroup g ∉
        zassenhausFiltration p (Γ ⧸ N.toSubgroup) n := by
  rcases
      open_filtration_power
        (p := p) (Γ := Γ) (n := n) hpower with
    ⟨N, hN⟩
  exact
    ⟨N,
      filtration_separates_normal
        (p := p) (Γ := Γ) (n := n) N hN hg⟩
end Towers
