import Towers.FieldTheory.HMRFiniteGeneration
import Towers.Group.FiniteFrattiniSelection
import Towers.NumberTheory.LocalInertia
import Towers.NumberTheory.UnramifiedInertia

/-!
# The initial HMR pro-3 presentation

This file gives honest topological meanings to the ranks used in the initial HMR
argument:

* `initialProRank` is `d_3(G)`, the least size of a finite dense
  generating family of the initial Galois group;
* `proRelationRank` is `r_3(G)`, the least number of relators in a
  finite free pro-`3` presentation on `d_3(G)` generators.

Large structural facts are named separately. The final Shafarevich theorem at
the bottom is only the numerical relation-rank estimate `r_3(G) ≤ d_3(G)`.
-/

open scoped Pointwise Topology commutatorElement

noncomputable section

namespace Towers
namespace TBluepr

open STBuild

/-!
## Koch-presentation scaffold

The arithmetic Koch theorem has three logically separate inputs:

1. choose five tame generators of the maximal pro-`3` Galois group;
2. choose a Frobenius lift at each ramified prime and verify its local tame
   relation;
3. prove that those five local relations topologically normally generate the
   kernel of the resulting free pro-`3` quotient.

The definitions and lemmas in this section discharge the topological and
group-theoretic assembly once those arithmetic inputs are available.  This
keeps the unresolved obligations narrower than the final presentation theorem:
none of them asks for a `ProP.Presentation`, and none of them contains the
packaging work proved below.
-/

private instance initialThreeFact : Fact (Nat.Prime 3) :=
  ⟨Nat.prime_three⟩

namespace KPScaffo

universe u v

/--
A displayed finite family of topological generators.

This structure is intentionally independent of free pro-`p` groups.  Arithmetic
arguments may first produce generators in the target Galois group and only
later invoke the universal property of the free pro-`p` group.
-/
structure GData
    (d : ℕ)
    (G : Type v)
    [Group G]
    [TopologicalSpace G]
    [IsTopologicalGroup G] where
  generator :
    Fin d → G
  topologicallyGenerates :
    ProP.TopologicallyGenerates generator

namespace GData

/--
The algebraic subgroup generated by a displayed topological generating family
is contained in every subgroup containing the displayed values.
-/
lemma closure_le
    {d : ℕ}
    {G : Type v}
    [Group G]
    [TopologicalSpace G]
    [IsTopologicalGroup G]
    (D : GData d G)
    (H : Subgroup G)
    (hH : ∀ i, D.generator i ∈ H) :
    Subgroup.closure (Set.range D.generator) ≤ H := by
  rw [Subgroup.closure_le]
  rintro x ⟨i, rfl⟩
  exact hH i

/--
Any closed subgroup containing a displayed topological generating family is
the whole target group.
-/
lemma top_closed_generator
    {d : ℕ}
    {G : Type v}
    [Group G]
    [TopologicalSpace G]
    [IsTopologicalGroup G]
    (D : GData d G)
    (H : Subgroup G)
    (hHclosed : IsClosed (H : Set G))
    (hH : ∀ i, D.generator i ∈ H) :
    H = ⊤ := by
  apply top_unique
  rw [← D.topologicallyGenerates]
  apply Subgroup.topologicalClosure_minimal
  · exact D.closure_le H hH
  · exact hHclosed

end GData

/--
The range of a continuous homomorphism out of a compact group is closed in a
Hausdorff target.
-/
lemma closed_compact
    {F : Type u}
    {G : Type v}
    [Group F]
    [TopologicalSpace F]
    [CompactSpace F]
    [Group G]
    [TopologicalSpace G]
    [T2Space G]
    (q : F →* G)
    (hq : Continuous q) :
    IsClosed (q.range : Set G) := by
  rw [MonoidHom.coe_range]
  exact
    (isCompact_range hq).isClosed

/--
A continuous homomorphism from a compact group is surjective as soon as its
range contains a displayed topological generating family.
-/
lemma surjective_compact_images
    {d : ℕ}
    {F : Type u}
    {G : Type v}
    [Group F]
    [TopologicalSpace F]
    [CompactSpace F]
    [Group G]
    [TopologicalSpace G]
    [IsTopologicalGroup G]
    [T2Space G]
    (D : GData d G)
    (q : F →* G)
    (hq : Continuous q)
    (source : Fin d → F)
    (hsource : ∀ i, q (source i) = D.generator i) :
    Function.Surjective q := by
  have hrangeClosed :
      IsClosed (q.range : Set G) :=
    closed_compact q hq
  have hrangeTop :
      q.range = ⊤ := by
    apply D.top_closed_generator q.range hrangeClosed
    intro i
    refine ⟨source i, ?_⟩
    exact hsource i
  exact
    MonoidHom.range_eq_top.mp hrangeTop

/--
Lift displayed generators to a continuous map from a chosen free pro-`p`
group.
-/
noncomputable def freeLift
    {p d : ℕ}
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    [IsTopologicalGroup G]
    [CompactSpace G]
    [TotallyDisconnectedSpace G]
    (free : ProP.FreeGroup.{u} p d)
    (hProP : ProP.ProPGroup p G)
    (D : GData d G) :
    ProP.ContinuousHom free.Carrier G :=
  free.lift hProP D.generator

/--
The free lift sends each universal generator to the corresponding displayed
target generator.
-/
lemma freeLift_generator
    {p d : ℕ}
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    [IsTopologicalGroup G]
    [CompactSpace G]
    [TotallyDisconnectedSpace G]
    (free : ProP.FreeGroup.{u} p d)
    (hProP : ProP.ProPGroup p G)
    (D : GData d G)
    (i : Fin d) :
    freeLift free hProP D (free.generator i) =
      D.generator i := by
  unfold freeLift
  exact
    free.lift_generator hProP D.generator i

/--
The free lift onto a target with displayed topological generators is
surjective.
-/
lemma freeLift_surjective
    {p d : ℕ}
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    [IsTopologicalGroup G]
    [CompactSpace G]
    [TotallyDisconnectedSpace G]
    [T2Space G]
    (free : ProP.FreeGroup.{u} p d)
    (hProP : ProP.ProPGroup p G)
    (D : GData d G) :
    Function.Surjective (freeLift free hProP D).toMonoidHom := by
  apply
    surjective_compact_images
      D
      (freeLift free hProP D).toMonoidHom
      (freeLift free hProP D).continuous_toFun
      free.generator
  intro i
  exact
    freeLift_generator free hProP D i

/--
A finite family of relators known individually to vanish under a quotient
homomorphism.
-/
structure RData
    {F : Type u}
    {G : Type v}
    [Group F]
    [TopologicalSpace F]
    [IsTopologicalGroup F]
    [Group G]
    [TopologicalSpace G]
    [IsTopologicalGroup G]
    (r : ℕ)
    (q : F →* G) where
  relator :
    Fin r → F
  relator_maps_one :
    ∀ i, q (relator i) = 1

namespace RData

/--
Each displayed relator belongs to the quotient kernel.
-/
lemma relator_mem_kernel
    {F : Type u}
    {G : Type v}
    [Group F]
    [TopologicalSpace F]
    [IsTopologicalGroup F]
    [Group G]
    [TopologicalSpace G]
    [IsTopologicalGroup G]
    {r : ℕ}
    {q : F →* G}
    (D : RData r q)
    (i : Fin r) :
    D.relator i ∈ q.ker := by
  rw [MonoidHom.mem_ker]
  exact
    D.relator_maps_one i

/--
The algebraic normal closure of displayed relators lies in the quotient
kernel.
-/
lemma normal_closure_kernel
    {F : Type u}
    {G : Type v}
    [Group F]
    [TopologicalSpace F]
    [IsTopologicalGroup F]
    [Group G]
    [TopologicalSpace G]
    [IsTopologicalGroup G]
    {r : ℕ}
    {q : F →* G}
    (D : RData r q) :
    Subgroup.normalClosure (Set.range D.relator) ≤ q.ker := by
  apply
    Subgroup.normalClosure_le_normal
  rintro x ⟨i, rfl⟩
  exact
    D.relator_mem_kernel i

/--
The kernel of a continuous homomorphism into a Hausdorff topological group is
closed.
-/
lemma kernel_isClosed
    {F : Type u}
    {G : Type v}
    [Group F]
    [TopologicalSpace F]
    [IsTopologicalGroup F]
    [Group G]
    [TopologicalSpace G]
    [IsTopologicalGroup G]
    [T2Space G]
    (q : F →* G)
    (hq : Continuous q) :
    IsClosed (q.ker : Set F) := by
  change IsClosed {x | q x = 1}
  exact
    isClosed_singleton.preimage hq

/--
The topological normal closure of displayed relators lies in the quotient
kernel.
-/
lemma topological_normal_closure
    {F : Type u}
    {G : Type v}
    [Group F]
    [TopologicalSpace F]
    [IsTopologicalGroup F]
    [Group G]
    [TopologicalSpace G]
    [IsTopologicalGroup G]
    [T2Space G]
    {r : ℕ}
    {q : F →* G}
    (D : RData r q)
    (hq : Continuous q) :
    (Subgroup.normalClosure (Set.range D.relator)).topologicalClosure ≤
      q.ker := by
  apply
    Subgroup.topologicalClosure_minimal
  · exact
      D.normal_closure_kernel
  · exact
      kernel_isClosed q hq

end RData

/--
The remaining direction needed for a topological kernel presentation:
everything in the quotient kernel is generated by the displayed relators.
-/
structure KGData
    {F : Type u}
    {G : Type v}
    [Group F]
    [TopologicalSpace F]
    [IsTopologicalGroup F]
    [Group G]
    [TopologicalSpace G]
    [IsTopologicalGroup G]
    (r : ℕ)
    (q : F →* G)
    extends RData r q where
  kernel_topological_closure :
    q.ker ≤
      (Subgroup.normalClosure (Set.range relator)).topologicalClosure

namespace KGData

/--
A kernel-generation certificate gives the exact kernel equality required by a
`ProP.Presentation`.
-/
lemma kernel_eq
    {F : Type u}
    {G : Type v}
    [Group F]
    [TopologicalSpace F]
    [IsTopologicalGroup F]
    [Group G]
    [TopologicalSpace G]
    [IsTopologicalGroup G]
    [T2Space G]
    {r : ℕ}
    {q : F →* G}
    (D : KGData r q)
    (hq : Continuous q) :
    q.ker =
      (Subgroup.normalClosure (Set.range D.relator)).topologicalClosure := by
  apply le_antisymm
  · exact
      D.kernel_topological_closure
  · exact
      D.toRData.topological_normal_closure hq

end KGData

/--
Package a free quotient and an exact kernel-generation certificate as a
finite free pro-`p` presentation.
-/
def presentation
    {p d r : ℕ}
    {G : Type v}
    [Group G]
    [TopologicalSpace G]
    [IsTopologicalGroup G]
    [T2Space G]
    (free : ProP.FreeGroup.{u} p d)
    (q : free.Carrier →* G)
    (hq : Continuous q)
    (hqSurjective : Function.Surjective q)
    (D : KGData r q) :
    ProP.Presentation.{u, v} p d r G where
  free :=
    free
  quotientMap :=
    q
  quotientMap_continuous :=
    hq
  quotientMap_surjective :=
    hqSurjective
  relator :=
    D.relator
  kernel_eq :=
    D.kernel_eq hq

end KPScaffo

open KPScaffo

/-!
## The three arithmetic inputs

The fixed ordering `initialRamifiedOrder` is already constructed in
`HMRInitialExtension`.  We now use it to index the five local tame relations.
The unresolved theorems below isolate the missing global arithmetic rather
than postulating the final presentation wholesale.
-/

/--
The ramified prime corresponding to one position in the five-generator Koch
presentation.
-/
def initialKochPrime (i : Fin 5) : ℕ :=
  (initialRamifiedOrder i).1

/--
The tame exponent in the local relation at the `i`th ramified prime.
-/
def initialTameExponent (i : Fin 5) : ℕ :=
  initialKochPrime i - 1

/--
The selected Koch primes belong to the initial ramification set.
-/
lemma initial_ramified_primes
    (i : Fin 5) :
    initialKochPrime i ∈ initialRamifiedPrimes := by
  unfold initialKochPrime
  exact
    (initialRamifiedOrder i).2

/--
Every selected Koch prime is prime.
-/
lemma initial_koch_prime
    (i : Fin 5) :
    Nat.Prime (initialKochPrime i) := by
  apply
    ramified_primes_prime
  exact
    initial_ramified_primes i

/--
Every selected Koch prime is congruent to one modulo three.
-/
lemma initial_koch_mod
    (i : Fin 5) :
    initialKochPrime i ≡ 1 [MOD 3] := by
  apply
    ramified_primes_mod
  exact
    initial_ramified_primes i

/--
The pro-prime is not one of the selected tame ramification primes.
-/
lemma initial_ne_three
    (i : Fin 5) :
    initialKochPrime i ≠ 3 := by
  apply
    ramified_primes_ne
  exact
    initial_ramified_primes i

/-!
### Finite-quotient reduction for the tame generators

The arithmetic construction of the five tame inertia elements is naturally
checked in finite Galois quotients.  The lemmas below isolate the profinite
passage from those finite checks to dense generation in the inverse limit.

This section is deliberately generic.  It applies to any compact totally
disconnected topological group and any displayed family of elements.  The
specialization to the five initial Koch primes appears after the generic
bridge.
-/

namespace IGScaffoa

universe u w

/--
The algebraic subgroup generated by a displayed family.

This abbreviation is used to keep the finite-shadow argument readable: the
topological closure of this subgroup is the candidate dense subgroup.
-/
abbrev generatedSubgroup
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    [IsTopologicalGroup G]
    {ι : Type w}
    (generator : ι → G) :
    Subgroup G :=
  Subgroup.closure (Set.range generator)

/--
The closed subgroup topologically generated by a displayed family.
-/
abbrev completedGeneratedSubgroup
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    [IsTopologicalGroup G]
    {ι : Type w}
    (generator : ι → G) :
    Subgroup G :=
  (generatedSubgroup generator).topologicalClosure

/--
The quotient map associated to an open normal subgroup.
-/
def quotientMap
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    (N : OpenNormalSubgroup G) :
    G →* G ⧸ N.toSubgroup :=
  QuotientGroup.mk' N.toSubgroup

/--
A displayed family generates one open-normal quotient when its images
algebraically generate that finite quotient.
-/
def GeneratesOpenNormal
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    {ι : Type w}
    (generator : ι → G)
    (N : OpenNormalSubgroup G) :
    Prop :=
  Subgroup.closure
      (Set.range (fun i => quotientMap N (generator i))) =
    ⊤

/--
A displayed family generates every finite shadow coming from an open normal
subgroup.
-/
def GeneratesEveryOpen
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    {ι : Type w}
    (generator : ι → G) :
    Prop :=
  ∀ N : OpenNormalSubgroup G,
    GeneratesOpenNormal generator N

/--
Each displayed generator belongs to its algebraically generated subgroup.
-/
lemma generator_generated_subgroup
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    [IsTopologicalGroup G]
    {ι : Type w}
    (generator : ι → G)
    (i : ι) :
    generator i ∈ generatedSubgroup generator := by
  apply
    Subgroup.subset_closure
  exact
    Set.mem_range_self i

/--
Each displayed generator belongs to the closed subgroup that it
topologically generates.
-/
lemma generator_completed_generated
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    [IsTopologicalGroup G]
    {ι : Type w}
    (generator : ι → G)
    (i : ι) :
    generator i ∈ completedGeneratedSubgroup generator := by
  apply
    (generatedSubgroup generator).le_topologicalClosure
  exact
    generator_generated_subgroup generator i

/--
The closed subgroup topologically generated by a family is closed.
-/
lemma completed_generated_closed
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    [IsTopologicalGroup G]
    {ι : Type w}
    (generator : ι → G) :
    IsClosed (completedGeneratedSubgroup generator : Set G) := by
  exact
    Subgroup.isClosed_topologicalClosure
      (generatedSubgroup generator)

/--
The quotient map associated to an open normal subgroup is onto.
-/
lemma quotientMap_surjective
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    (N : OpenNormalSubgroup G) :
    Function.Surjective (quotientMap N) := by
  exact
    QuotientGroup.mk'_surjective N.toSubgroup

/--
The quotient map associated to an open normal subgroup is continuous.
-/
lemma quotientMap_continuous
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    (N : OpenNormalSubgroup G) :
    Continuous (quotientMap N) := by
  exact
    pro_open_continuous N

/--
The image of each displayed generator belongs to the image of the completed
generated subgroup in every open-normal quotient.
-/
lemma completed_generated_subgroup
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    [IsTopologicalGroup G]
    {ι : Type w}
    (generator : ι → G)
    (N : OpenNormalSubgroup G)
    (i : ι) :
    quotientMap N (generator i) ∈
      (completedGeneratedSubgroup generator).map (quotientMap N) := by
  refine
    ⟨generator i, ?_, rfl⟩
  exact
    generator_completed_generated generator i

/--
The subgroup generated by the quotient images is contained in the image of
the completed generated subgroup.
-/
lemma closure_completed_generated
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    [IsTopologicalGroup G]
    {ι : Type w}
    (generator : ι → G)
    (N : OpenNormalSubgroup G) :
    Subgroup.closure
        (Set.range (fun i => quotientMap N (generator i))) ≤
      (completedGeneratedSubgroup generator).map (quotientMap N) := by
  rw [Subgroup.closure_le]
  rintro _ ⟨i, rfl⟩
  exact
    completed_generated_subgroup
      generator
      N
      i

/--
If the displayed family generates one open-normal quotient, then the image
of its completed generated subgroup is the whole quotient.
-/
lemma completed_generated_generates
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    [IsTopologicalGroup G]
    {ι : Type w}
    (generator : ι → G)
    (N : OpenNormalSubgroup G)
    (hN : GeneratesOpenNormal generator N) :
    (completedGeneratedSubgroup generator).map (quotientMap N) =
      ⊤ := by
  apply
    top_unique
  rw [← hN]
  exact
    closure_completed_generated
      generator
      N

/--
If the displayed family generates one finite shadow, every element of that
shadow is represented by an element of the completed generated subgroup.
-/
lemma image_completed_generated
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    [IsTopologicalGroup G]
    {ι : Type w}
    (generator : ι → G)
    (N : OpenNormalSubgroup G)
    (hN : GeneratesOpenNormal generator N)
    (x : G) :
    quotientMap N x ∈
      quotientMap N '' (completedGeneratedSubgroup generator : Set G) := by
  have htop :
      (completedGeneratedSubgroup generator).map (quotientMap N) =
        ⊤ :=
    completed_generated_generates
      generator
      N
      hN
  have hx :
      quotientMap N x ∈
        (completedGeneratedSubgroup generator).map (quotientMap N) := by
    rw [htop]
    exact
      trivial
  rcases hx with ⟨y, hy, hyx⟩
  exact
    ⟨y, hy, hyx⟩

/--
Finite-shadow generation forces every ambient element into the completed
generated subgroup.  The proof uses separation of a closed set from an
exterior point by an open-normal quotient.
-/
lemma completed_generates_every
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    [IsTopologicalGroup G]
    [CompactSpace G]
    [TotallyDisconnectedSpace G]
    {ι : Type w}
    (generator : ι → G)
    (hgenerator : GeneratesEveryOpen generator)
    (x : G) :
    x ∈ completedGeneratedSubgroup generator := by
  by_contra hx
  have hclosed :
      IsClosed (completedGeneratedSubgroup generator : Set G) :=
    completed_generated_closed generator
  rcases
      separate_sets_disconnected
        hclosed
        x
        hx with
    ⟨N, hN⟩
  apply
    hN
  simpa [quotientMap] using
    image_completed_generated
      generator
      N
      (hgenerator N)
      x

/--
Generation in every open-normal finite quotient implies dense generation in
the compact totally disconnected group.
-/
lemma topologically_generates_every
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    [IsTopologicalGroup G]
    [CompactSpace G]
    [TotallyDisconnectedSpace G]
    {ι : Type w}
    (generator : ι → G)
    (hgenerator : GeneratesEveryOpen generator) :
    ProP.TopologicallyGenerates generator := by
  apply
    top_unique
  intro x _hx
  exact
    completed_generates_every
      generator
      hgenerator
      x

/--
Dense generation descends to algebraic generation in every open-normal
finite quotient.
-/
lemma generates_normal_topologically
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    [IsTopologicalGroup G]
    {ι : Type w}
    (generator : ι → G)
    (hgenerator : ProP.TopologicallyGenerates generator)
    (N : OpenNormalSubgroup G) :
    GeneratesOpenNormal generator N := by
  let K :
      Subgroup (G ⧸ N.toSubgroup) :=
    Subgroup.closure
      (Set.range (fun i => quotientMap N (generator i)))
  have hle :
      generatedSubgroup generator ≤
        K.comap (quotientMap N) := by
    rw [Subgroup.closure_le]
    rintro _ ⟨i, rfl⟩
    exact
      Subgroup.subset_closure
        ⟨i, rfl⟩
  letI :
      DiscreteTopology (G ⧸ N.toSubgroup) :=
    pro_discrete_topology N
  have hKclosed :
      IsClosed (K : Set (G ⧸ N.toSubgroup)) := by
    exact
      isClosed_discrete _
  have hpreimageClosed :
      IsClosed (K.comap (quotientMap N) : Set G) := by
    change
      IsClosed
        ((quotientMap N) ⁻¹' (K : Set (G ⧸ N.toSubgroup)))
    exact
      hKclosed.preimage
        (quotientMap_continuous N)
  have hcompletedLe :
      completedGeneratedSubgroup generator ≤
        K.comap (quotientMap N) :=
    Subgroup.topologicalClosure_minimal
      (generatedSubgroup generator)
      hle
      hpreimageClosed
  have htopLe :
      (⊤ : Subgroup G) ≤
        K.comap (quotientMap N) := by
    rw [← hgenerator]
    exact
      hcompletedLe
  have hKtop :
      (⊤ : Subgroup (G ⧸ N.toSubgroup)) ≤ K := by
    intro y _hy
    rcases quotientMap_surjective N y with ⟨x, rfl⟩
    exact
      htopLe trivial
  exact
    top_unique hKtop

/--
Dense generation descends simultaneously to every open-normal quotient.
-/
lemma generates_open_topologically
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    [IsTopologicalGroup G]
    {ι : Type w}
    (generator : ι → G)
    (hgenerator : ProP.TopologicallyGenerates generator) :
    GeneratesEveryOpen generator := by
  intro N
  exact
    generates_normal_topologically
      generator
      hgenerator
      N

/--
For compact totally disconnected groups, dense generation is equivalent to
generation in every open-normal finite quotient.
-/
lemma generates_every_topologically
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    [IsTopologicalGroup G]
    [CompactSpace G]
    [TotallyDisconnectedSpace G]
    {ι : Type w}
    (generator : ι → G) :
    GeneratesEveryOpen generator ↔
      ProP.TopologicallyGenerates generator := by
  constructor
  · exact
      topologically_generates_every
        generator
  · exact
      generates_open_topologically
        generator

end IGScaffoa

open IGScaffoa

/--
The type of primes in the initial ramification set.
-/
abbrev InitialKochRamified :=
  {r : ℕ // r ∈ initialRamifiedPrimes}

/--
Reindex a family attached to the actual ramified primes by the fixed
five-prime ordering used in the Koch presentation.
-/
def initialTameGenerator
    {G : Type*}
    (generator : InitialKochRamified → G) :
    Fin 5 → G :=
  fun i =>
    generator (initialRamifiedOrder i)

/--
The fixed ordering reaches every initial ramified prime, so reindexing does
not change the range of a tame generator family.
-/
lemma initial_koch_range
    {G : Type*}
    (generator : InitialKochRamified → G) :
    Set.range (initialTameGenerator generator) =
      Set.range generator := by
  apply
    Set.Subset.antisymm
  · rintro x ⟨i, rfl⟩
    exact
      ⟨initialRamifiedOrder i, rfl⟩
  · rintro x ⟨r, rfl⟩
    rcases
        initial_ramified_surjective r with
      ⟨i, rfl⟩
    exact
      ⟨i, rfl⟩

/--
Reindexing also preserves the range after applying any map.
-/
lemma initial_tame_range
    {G H : Type*}
    (generator : InitialKochRamified → G)
    (f : G → H) :
    Set.range (fun i => f (initialTameGenerator generator i)) =
      Set.range (fun r => f (generator r)) := by
  apply
    Set.Subset.antisymm
  · rintro x ⟨i, rfl⟩
    exact
      ⟨initialRamifiedOrder i, rfl⟩
  · rintro x ⟨r, rfl⟩
    rcases
        initial_ramified_surjective r with
      ⟨i, rfl⟩
    exact
      ⟨i, rfl⟩

/--
Reindexing preserves the algebraic subgroup generated after applying a map.
-/
lemma initial_tame_closure
    {G H : Type*}
    [Group H]
    (generator : InitialKochRamified → G)
    (f : G → H) :
    Subgroup.closure
        (Set.range (fun i => f (initialTameGenerator generator i))) =
      Subgroup.closure
        (Set.range (fun r => f (generator r))) := by
  rw [
    initial_tame_range
      generator
      f
  ]

/-!
## Compact selection of compatible finite-shadow generators

The arithmetic argument naturally constructs generators one finite Galois
layer at a time.  Those layerwise choices need not initially be compatible.
The lemmas below isolate the compactness argument that turns the existence of
a generating tuple in each open-normal quotient into one tuple in the
profinite group whose image generates every such quotient simultaneously.

For an open normal subgroup `N`, consider the closed subset of tuples whose
image generates `G / N`.  A tuple generating a quotient by a smaller subgroup
also generates every coarser quotient.  Consequently, the generating-tuple
sets have the finite intersection property: for a finite family of quotients,
choose a tuple for their common refinement.  Compactness of the tuple space
then gives a point in their total intersection.
-/

namespace GSScaffo

open IGScaffoa

universe u w

/--
The coordinatewise image of a displayed tuple in the quotient by an
open-normal subgroup.

Keeping this map named makes the closed-set argument below independent of the
particular arithmetic source of the tuple.
-/
def quotientTuple
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    {ι : Type w}
    (N : OpenNormalSubgroup G) :
    (ι → G) → (ι → G ⧸ N.toSubgroup) :=
  fun generator i =>
    quotientMap N (generator i)

/--
The quotient tuple is continuous: each coordinate is evaluation followed by
the continuous open-normal quotient map.
-/
lemma quotientTuple_continuous
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    {ι : Type w}
    (N : OpenNormalSubgroup G) :
    Continuous (quotientTuple (ι := ι) N) := by
  apply
    continuous_pi
  intro i
  exact
    (quotientMap_continuous N).comp
      (continuous_apply i)

/--
The algebraic generating tuples in a target group.  Later the target will be
a finite discrete quotient of a profinite group.
-/
def algebraicallyGeneratingSet
    (ι : Type w)
    (Q : Type u)
    [Group Q] :
    Set (ι → Q) :=
  { generator |
      Subgroup.closure (Set.range generator) =
        ⊤ }

/--
Membership in the algebraic generating-tuple set is exactly algebraic
generation of the target group.
-/
lemma algebraically_generating_set
    {ι : Type w}
    {Q : Type u}
    [Group Q]
    (generator : ι → Q) :
    generator ∈ algebraicallyGeneratingSet ι Q ↔
      Subgroup.closure (Set.range generator) =
        ⊤ := by
  rfl

/--
In a finite discrete group, the set of algebraically generating tuples is
closed.  Finiteness of the index type is used only to make the tuple space
finite; no enumeration of tuples is needed.
-/
lemma algebraically_generating_closed
    (ι : Type w)
    (Q : Type u)
    [Group Q]
    [TopologicalSpace Q]
    [DiscreteTopology Q]
    [Finite ι]
    [Finite Q] :
    IsClosed (algebraicallyGeneratingSet ι Q) := by
  exact
    Set.toFinite
      (algebraicallyGeneratingSet ι Q) |>.isClosed

/--
The tuples in `G` whose images generate the quotient by `N`.
-/
def generatingTupleSet
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    (ι : Type w)
    (N : OpenNormalSubgroup G) :
    Set (ι → G) :=
  { generator |
      GeneratesOpenNormal generator N }

/--
Membership in the quotient generating-tuple set unfolds to generation in the
specified open-normal quotient.
-/
lemma generating_tuple_set
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    {ι : Type w}
    (N : OpenNormalSubgroup G)
    (generator : ι → G) :
    generator ∈ generatingTupleSet ι N ↔
      GeneratesOpenNormal generator N := by
  rfl

/--
The quotient generating-tuple set is the inverse image of the algebraic
generating-tuple set under the coordinatewise quotient map.
-/
lemma generating_tuple_preimage
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    {ι : Type w}
    (N : OpenNormalSubgroup G) :
    generatingTupleSet ι N =
      quotientTuple N ⁻¹'
        algebraicallyGeneratingSet
          ι
          (G ⧸ N.toSubgroup) := by
  rfl

/--
For a compact profinite source, generation of one finite shadow is a closed
condition on tuples in the source group.

The local discrete topology instance is deliberately confined to the proof:
the quotient topology used by the rest of the file remains unchanged.
-/
lemma generating_tuple_closed
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    [IsTopologicalGroup G]
    [CompactSpace G]
    {ι : Type w}
    [Finite ι]
    (N : OpenNormalSubgroup G) :
    IsClosed (generatingTupleSet ι N) := by
  letI :
      DiscreteTopology (G ⧸ N.toSubgroup) :=
    pro_discrete_topology N
  rw [
    generating_tuple_preimage
      (ι := ι)
      N
  ]
  exact
    (algebraically_generating_closed
      ι
      (G ⧸ N.toSubgroup)).preimage
        (quotientTuple_continuous N)

/--
The canonical transition from a finer open-normal quotient to a coarser one.
-/
noncomputable def quotientTransition
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    {K N : OpenNormalSubgroup G}
    (hKN : (K : Subgroup G) ≤ (N : Subgroup G)) :
    (G ⧸ K.toSubgroup) →*
      (G ⧸ N.toSubgroup) :=
  QuotientGroup.lift
    K.toSubgroup
    (quotientMap N)
    (by
      intro x hx
      change
        QuotientGroup.mk' N.toSubgroup x =
          1
      exact
        (QuotientGroup.eq_one_iff
          (N := N.toSubgroup)
          x).2
            (hKN hx))

/--
The transition between nested quotients sends the class of an ambient element
to its class in the coarser quotient.
-/
lemma quotient_transition
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    {K N : OpenNormalSubgroup G}
    (hKN : (K : Subgroup G) ≤ (N : Subgroup G))
    (x : G) :
    quotientTransition hKN (quotientMap K x) =
      quotientMap N x := by
  rfl

/--
Generation descends along a transition from a finer open-normal quotient to a
coarser quotient.

This is the algebraic heart of the finite-intersection argument.  Rather than
using cardinalities, the proof maps the generated subgroup through the
canonical quotient transition.
-/
lemma generates_open_normal
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    {ι : Type w}
    (generator : ι → G)
    {K N : OpenNormalSubgroup G}
    (hKN : (K : Subgroup G) ≤ (N : Subgroup G))
    (hK : GeneratesOpenNormal generator K) :
    GeneratesOpenNormal generator N := by
  let transition :
      (G ⧸ K.toSubgroup) →*
        (G ⧸ N.toSubgroup) :=
    quotientTransition hKN
  let target :
      Subgroup (G ⧸ N.toSubgroup) :=
    Subgroup.closure
      (Set.range
        (fun i =>
          quotientMap N (generator i)))
  have hgeneratedLe :
      Subgroup.closure
          (Set.range
            (fun i =>
              quotientMap K (generator i))) ≤
        target.comap transition := by
    rw [
      Subgroup.closure_le
    ]
    rintro _ ⟨i, rfl⟩
    change
      transition (quotientMap K (generator i)) ∈
        target
    rw [
      show
        transition (quotientMap K (generator i)) =
          quotientMap N (generator i) by
            exact
              quotient_transition
                hKN
                (generator i)
    ]
    exact
      Subgroup.subset_closure
        ⟨i, rfl⟩
  apply
    top_unique
  intro y _hy
  rcases
      quotientMap_surjective N y with
    ⟨x, rfl⟩
  have hxK :
      quotientMap K x ∈
        Subgroup.closure
          (Set.range
            (fun i =>
              quotientMap K (generator i))) := by
    rw [
      hK
    ]
    exact
      trivial
  have hxTarget :
      transition (quotientMap K x) ∈
        target :=
    hgeneratedLe hxK
  change
    quotientMap N x ∈
      Subgroup.closure
        (Set.range
          (fun i =>
            quotientMap N (generator i)))
  rw [
    ← quotient_transition
      hKN
      x
  ]
  exact
    hxTarget

/--
The quotient generating-tuple sets are monotone under refinement: a tuple
which generates a finer quotient belongs to the set for every coarser
quotient.
-/
lemma generating_tuple_mono
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    {ι : Type w}
    {K N : OpenNormalSubgroup G}
    (hKN : (K : Subgroup G) ≤ (N : Subgroup G)) :
    generatingTupleSet ι K ⊆
      generatingTupleSet ι N := by
  intro generator hgenerator
  exact
    generates_open_normal
      generator
      hKN
      hgenerator

/--
A tuple for the intersection of finitely many open-normal subgroups generates
each quotient in the finite family.
-/
lemma generates_finset_inf
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    {ι : Type w}
    (generator : ι → G)
    (s : Finset (OpenNormalSubgroup G))
    (hgenerator :
      GeneratesOpenNormal
        generator
        (s.inf (fun M : OpenNormalSubgroup G => M))) :
    ∀ N ∈ s,
      GeneratesOpenNormal
        generator
        N := by
  intro N hN
  apply
    generates_open_normal
      generator
      (K := s.inf (fun M : OpenNormalSubgroup G => M))
      (N := N)
  · have hKN :
        s.inf (fun M : OpenNormalSubgroup G => M) ≤
          N :=
      Finset.inf_le hN
    exact
      hKN
  · exact
      hgenerator

/--
If every individual open-normal quotient has some generating tuple, then the
closed generating-tuple sets have the finite intersection property.
-/
lemma generating_intersection_property
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    {ι : Type w}
    (hexists :
      ∀ N : OpenNormalSubgroup G,
        ∃ generator : ι → G,
          GeneratesOpenNormal generator N) :
    ∀ s : Finset (OpenNormalSubgroup G),
      (⋂ N ∈ s,
        generatingTupleSet ι N).Nonempty := by
  intro s
  rcases
      hexists (s.inf (fun M : OpenNormalSubgroup G => M)) with
    ⟨generator, hgenerator⟩
  refine
    ⟨generator, ?_⟩
  rw [
    Set.mem_iInter₂
  ]
  intro N hN
  exact
    generates_finset_inf
      generator
      s
      hgenerator
      N
      hN

/--
Compact selection principle for profinite generators.

The hypothesis is layerwise: for each open-normal quotient it permits a fresh
tuple of lifts.  The conclusion is simultaneous: one tuple works in every
open-normal quotient.  This is exactly the compatibility step needed between
finite Galois calculations and the inverse-limit Koch presentation.
-/
lemma generates_every_layerwise
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    [IsTopologicalGroup G]
    [CompactSpace G]
    {ι : Type w}
    [Finite ι]
    (hexists :
      ∀ N : OpenNormalSubgroup G,
        ∃ generator : ι → G,
          GeneratesOpenNormal generator N) :
    ∃ generator : ι → G,
      GeneratesEveryOpen generator := by
  have hclosed :
      ∀ N : OpenNormalSubgroup G,
        IsClosed
          (generatingTupleSet ι N) := by
    intro N
    exact
      generating_tuple_closed N
  have hfip :
      ∀ s : Finset (OpenNormalSubgroup G),
        (⋂ N ∈ s,
          generatingTupleSet ι N).Nonempty :=
    generating_intersection_property
      hexists
  have hall :
      (⋂ N : OpenNormalSubgroup G,
        generatingTupleSet ι N).Nonempty := by
    exact
      CompactSpace.iInter_nonempty
        hclosed
        hfip
  rcases
      hall with
    ⟨generator, hgenerator⟩
  refine
    ⟨generator, ?_⟩
  intro N
  exact
    Set.mem_iInter.mp
      hgenerator
      N

end GSScaffo

open GSScaffo

/-!
## Lifting generators from one finite layer

The compact-selection argument above only needs one generating tuple in each
finite quotient.  The arithmetic input is most naturally stated inside that
finite quotient: inertia classes are finite-layer objects before compatible
ambient lifts have been chosen.

This section separates those two tasks.  A `QGData` value is a
generating tuple in one finite quotient.  The quotient map is surjective, so
each coordinate can be lifted independently to the ambient profinite group.
The lemmas below verify that the lifted tuple still generates the specified
quotient.  No compatibility between distinct open-normal subgroups is used
here; that remains the job of the compact-selection scaffold.
-/

namespace ILScaffo

open IGScaffoa

universe u w

/--
A displayed generating family in one open-normal quotient.

Unlike `GeneratesOpenNormal`, this structure stores quotient elements
directly.  Thus an arithmetic proof may construct finite-layer inertia classes
without simultaneously choosing representatives in the ambient profinite
group.
-/
structure QGData
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    (ι : Type w)
    (N : OpenNormalSubgroup G) where
  generator :
    ι → G ⧸ N.toSubgroup
  generates :
    Subgroup.closure (Set.range generator) =
      ⊤

namespace QGData

/--
Every displayed quotient generator belongs to the subgroup generated by the
displayed quotient family.
-/
lemma generator_mem_closure
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    {ι : Type w}
    {N : OpenNormalSubgroup G}
    (D : QGData ι N)
    (i : ι) :
    D.generator i ∈
      Subgroup.closure (Set.range D.generator) := by
  apply
    Subgroup.subset_closure
  exact
    Set.mem_range_self i

/--
Every quotient element belongs to the subgroup generated by a quotient
generator datum.
-/
lemma mem_closure
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    {ι : Type w}
    {N : OpenNormalSubgroup G}
    (D : QGData ι N)
    (x : G ⧸ N.toSubgroup) :
    x ∈ Subgroup.closure (Set.range D.generator) := by
  rw [
    D.generates
  ]
  exact
    trivial

/--
Reindex a quotient generating family along a surjective map of index types.

This is useful when arithmetic data is naturally indexed by an ordered list
of primes and the surrounding presentation is indexed by the corresponding
subtype of ramified primes.
-/
def reindex
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    {ι κ : Type w}
    {N : OpenNormalSubgroup G}
    (D : QGData ι N)
    (e : κ → ι)
    (he : Function.Surjective e) :
    QGData κ N where
  generator :=
    fun j =>
      D.generator (e j)
  generates := by
    have hrange :
        Set.range (fun j => D.generator (e j)) =
          Set.range D.generator := by
      apply
        Set.Subset.antisymm
      · rintro x ⟨j, rfl⟩
        exact
          ⟨e j, rfl⟩
      · rintro x ⟨i, rfl⟩
        rcases
            he i with
          ⟨j, rfl⟩
        exact
          ⟨j, rfl⟩
    rw [
      hrange,
      D.generates
    ]

/--
Reindexing does not change the range of a quotient generating family.
-/
lemma reindex_range
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    {ι κ : Type w}
    {N : OpenNormalSubgroup G}
    (D : QGData ι N)
    (e : κ → ι)
    (he : Function.Surjective e) :
    Set.range ((D.reindex e he).generator) =
      Set.range D.generator := by
  apply
    Set.Subset.antisymm
  · rintro x ⟨j, rfl⟩
    exact
      ⟨e j, rfl⟩
  · rintro x ⟨i, rfl⟩
    rcases
        he i with
      ⟨j, rfl⟩
    exact
      ⟨j, rfl⟩

end QGData

/--
A coordinatewise lift of quotient generator data to the ambient group.

The structure deliberately records the pointwise quotient-map equality.  The
proofs below use that equality to transport ranges and generated subgroups
without any topological argument.
-/
structure LiftData
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    {ι : Type w}
    {N : OpenNormalSubgroup G}
    (D : QGData ι N) where
  lift :
    ι → G
  mapsTo :
    ∀ i,
      quotientMap N (lift i) =
        D.generator i

/--
Choose one representative of a quotient element.

This choice is made only inside a fixed open-normal quotient.  It has no
compatibility requirement with choices made for a different quotient.
-/
noncomputable def chooseLift
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    (N : OpenNormalSubgroup G)
    (x : G ⧸ N.toSubgroup) :
    G :=
  Classical.choose
    (quotientMap_surjective N x)

/--
The chosen representative maps back to its quotient element.
-/
lemma choose_lift_maps
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    (N : OpenNormalSubgroup G)
    (x : G ⧸ N.toSubgroup) :
    quotientMap N (chooseLift N x) =
      x := by
  exact
    Classical.choose_spec
      (quotientMap_surjective N x)

/--
Canonical coordinatewise lifts of a quotient generating family.
-/
noncomputable def canonicalLiftData
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    {ι : Type w}
    {N : OpenNormalSubgroup G}
    (D : QGData ι N) :
    LiftData D where
  lift :=
    fun i =>
      chooseLift N (D.generator i)
  mapsTo := by
    intro i
    exact
      choose_lift_maps
        N
        (D.generator i)

namespace LiftData

/--
Each lifted coordinate maps to the corresponding displayed quotient
generator.
-/
lemma quotientMap_lift
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    {ι : Type w}
    {N : OpenNormalSubgroup G}
    {D : QGData ι N}
    (L : LiftData D)
    (i : ι) :
    quotientMap N (L.lift i) =
      D.generator i := by
  exact
    L.mapsTo i

/--
Every quotient image of a lifted coordinate belongs to the range of the
stored quotient generating family.
-/
lemma image_subset_generator
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    {ι : Type w}
    {N : OpenNormalSubgroup G}
    {D : QGData ι N}
    (L : LiftData D) :
    Set.range (fun i => quotientMap N (L.lift i)) ⊆
      Set.range D.generator := by
  rintro x ⟨i, rfl⟩
  refine
    ⟨i, ?_⟩
  exact
    (L.quotientMap_lift i).symm

/--
Every stored quotient generator occurs as the image of its lifted
coordinate.
-/
lemma generator_subset_image
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    {ι : Type w}
    {N : OpenNormalSubgroup G}
    {D : QGData ι N}
    (L : LiftData D) :
    Set.range D.generator ⊆
      Set.range (fun i => quotientMap N (L.lift i)) := by
  rintro x ⟨i, rfl⟩
  refine
    ⟨i, ?_⟩
  exact
    L.quotientMap_lift i

/--
The quotient images of lifted coordinates have exactly the same range as the
stored quotient generating family.
-/
lemma image_range_generator
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    {ι : Type w}
    {N : OpenNormalSubgroup G}
    {D : QGData ι N}
    (L : LiftData D) :
    Set.range (fun i => quotientMap N (L.lift i)) =
      Set.range D.generator := by
  apply
    Set.Subset.antisymm
  · exact
      L.image_subset_generator
  · exact
      L.generator_subset_image

/--
The generated subgroup of the lifted quotient images is the generated
subgroup of the original quotient tuple.
-/
lemma image_closure_generator
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    {ι : Type w}
    {N : OpenNormalSubgroup G}
    {D : QGData ι N}
    (L : LiftData D) :
    Subgroup.closure
        (Set.range (fun i => quotientMap N (L.lift i))) =
      Subgroup.closure (Set.range D.generator) := by
  rw [
    L.image_range_generator
  ]

/--
The lifted tuple generates the quotient because the stored quotient tuple
does.
-/
lemma generatesOpenNormal
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    {ι : Type w}
    {N : OpenNormalSubgroup G}
    {D : QGData ι N}
    (L : LiftData D) :
    GeneratesOpenNormal L.lift N := by
  change
    Subgroup.closure
        (Set.range (fun i => quotientMap N (L.lift i))) =
      ⊤
  rw [
    L.image_closure_generator,
    D.generates
  ]

/--
A lift datum can be reindexed whenever the quotient generating datum is
reindexed along a surjective map.
-/
def reindex
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    {ι κ : Type w}
    {N : OpenNormalSubgroup G}
    {D : QGData ι N}
    (L : LiftData D)
    (e : κ → ι)
    (he : Function.Surjective e) :
    LiftData (D.reindex e he) where
  lift :=
    fun j =>
      L.lift (e j)
  mapsTo := by
    intro j
    exact
      L.mapsTo (e j)

/--
Reindexing a lift datum does not change its ambient range.
-/
lemma reindex_range
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    {ι κ : Type w}
    {N : OpenNormalSubgroup G}
    {D : QGData ι N}
    (L : LiftData D)
    (e : κ → ι)
    (he : Function.Surjective e) :
    Set.range ((L.reindex e he).lift) =
      Set.range L.lift := by
  apply
    Set.Subset.antisymm
  · rintro x ⟨j, rfl⟩
    exact
      ⟨e j, rfl⟩
  · rintro x ⟨i, rfl⟩
    rcases
        he i with
      ⟨j, rfl⟩
    exact
      ⟨j, rfl⟩

end LiftData

/--
Any quotient generating datum admits ambient representatives whose images
still generate the specified quotient.
-/
lemma lift_generates_open
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    {ι : Type w}
    {N : OpenNormalSubgroup G}
    (D : QGData ι N) :
    ∃ generator : ι → G,
      GeneratesOpenNormal generator N := by
  let L :
      LiftData D :=
    canonicalLiftData D
  refine
    ⟨L.lift, ?_⟩
  exact
    L.generatesOpenNormal

/--
The existential finite-layer lift bridge: quotient-side generation is enough
to produce an ambient tuple generating that one quotient.
-/
lemma lift_generates_nonempty
    {G : Type u}
    [Group G]
    [TopologicalSpace G]
    {ι : Type w}
    {N : OpenNormalSubgroup G}
    (hD : Nonempty (QGData ι N)) :
    ∃ generator : ι → G,
      GeneratesOpenNormal generator N := by
  rcases
      hD with
    ⟨D⟩
  exact
    lift_generates_open
      D

end ILScaffo

open ILScaffo

/--
The closed subgroup corresponding to one open-normal finite layer of the
initial pro-`3` extension.
-/
noncomputable def initialKochClosed
    (N : OpenNormalSubgroup initialGaloisGroup) :
    ClosedSubgroup initialGaloisGroup where
  toSubgroup := N
  isClosed' := N.toOpenSubgroup.isClosed

/--
The fixed field corresponding to one open-normal finite layer of the initial
pro-`3` extension.
-/
noncomputable abbrev initialKochLayer
    (N : OpenNormalSubgroup initialGaloisGroup) :=
  ↥(IntermediateField.fixedField
    (initialKochClosed N).1)

/--
The fixed-field inclusion associated to containment of open-normal
subgroups.  The direction reverses because larger subgroups fix smaller
fields.
-/
noncomputable def initialKochInclusion
    {M N : OpenNormalSubgroup initialGaloisGroup}
    (hMN : M ≤ N) :
    initialKochLayer N →ₐ[ℚ]
      initialKochLayer M := by
  apply IntermediateField.inclusion
  apply IntermediateField.fixedField_le
  exact hMN

/--
The corresponding descent map on rings of integers.
-/
noncomputable def initialIntegersInclusion
    {M N : OpenNormalSubgroup initialGaloisGroup}
    (hMN : M ≤ N) :
    NumberField.RingOfIntegers (initialKochLayer N) →+*
      NumberField.RingOfIntegers (initialKochLayer M) :=
  NumberField.RingOfIntegers.mapRingHom
    (initialKochInclusion hMN).toRingHom

/--
The Galois correspondence equivalence between an open-normal quotient and the
Galois group of its fixed field.
-/
noncomputable def initialKochEquiv
    (N : OpenNormalSubgroup initialGaloisGroup) :
    initialGaloisGroup ⧸ N.toSubgroup ≃*
      Gal(initialKochLayer N / ℚ) := by
  let H := initialKochClosed N
  letI : H.toSubgroup.Normal := by
    change (N : Subgroup initialGaloisGroup).Normal
    infer_instance
  simpa [H, initialKochLayer] using
    galoisFixedField H

/--
Certified tame inertia generators in one finite Galois layer.

The displayed quotient tuple is not merely a generating tuple: each
coordinate is identified with an element of the inertia subgroup at an
explicit prime above the indexed rational prime.
-/
structure TameInertiaData
    (N : OpenNormalSubgroup initialGaloisGroup) where
  quotientGeneratorData :
    QGData InitialKochRamified N
  primeAbove :
    InitialKochRamified →
      Ideal (NumberField.RingOfIntegers (initialKochLayer N))
  primeAbove_mem :
    ∀ r,
      primeAbove r ∈
        Ideal.primesOver
          (Ideal.rationalPrimeIdeal r.1)
          (NumberField.RingOfIntegers (initialKochLayer N))
  inertiaGenerator :
    ∀ r,
      (primeAbove r).inertia
        (Gal(initialKochLayer N / ℚ))
  inertiaGenerator_generates :
    ∀ r,
      Subgroup.closure
          ({(inertiaGenerator r :
            Gal(initialKochLayer N / ℚ))} : Set _) =
        (primeAbove r).inertia
          (Gal(initialKochLayer N / ℚ))
  generator_eq :
    ∀ r,
      quotientGeneratorData.generator r =
        (initialKochEquiv N).symm
          (inertiaGenerator r)

/--
One compatible family of tame inertia elements in the inverse limit.

The finite-layer certificates and their compatibly descending primes are
retained because the local Koch relation must later be proved for these
specific generators.  Merely choosing generating tuples and primes
independently in each finite quotient and then forgetting their inertia
provenance would not suffice.
-/
structure InitialInertiaData where
  generator :
    InitialKochRamified → initialGaloisGroup
  finiteLayerData :
    ∀ N : OpenNormalSubgroup initialGaloisGroup,
      TameInertiaData N
  mapsFiniteLayer :
    ∀ (N : OpenNormalSubgroup initialGaloisGroup) r,
      IGScaffoa.quotientMap N (generator r) =
        (finiteLayerData N).quotientGeneratorData.generator r
  primeAbove_comap :
    ∀ {M N : OpenNormalSubgroup initialGaloisGroup}
      (hMN : M ≤ N) r,
        Ideal.comap
            (initialIntegersInclusion hMN)
            ((finiteLayerData M).primeAbove r) =
          (finiteLayerData N).primeAbove r

/--
In a finite `p`-group, normal generation implies generation.

Indeed, if the generated subgroup were proper, it would lie in a maximal
subgroup.  Every maximal subgroup of a finite `p`-group is normal, contradicting
normal generation.
-/
lemma closure_top_pgroup
    {p : ℕ}
    {G : Type*}
    [Group G]
    [Finite G]
    [Fact (Nat.Prime p)]
    (hG : IsPGroup p G)
    {S : Set G}
    (hS : Subgroup.normalClosure S = ⊤) :
    Subgroup.closure S = ⊤ := by
  by_contra hne
  obtain ⟨M, hle, hM⟩ :=
    FFSelect.maximal_subgroup
      (H := Subgroup.closure S)
      hne
  letI : M.Normal :=
    FFSelect.maximal_normal_pgroup
      hG
      hM
  have hnormal :
      Subgroup.normalClosure S ≤ M := by
    apply
      Subgroup.normalClosure_le_normal
    exact
      fun x hx =>
        hle (Subgroup.subset_closure hx)
  rw [
    hS
  ] at hnormal
  exact
    hM.1 (top_unique hnormal)

lemma number_restrict_inertia
    {L : Type*} [Field L] [NumberField L] [Algebra ℚ L]
    [FiniteDimensional ℚ L] [IsGalois ℚ L]
    (E : IntermediateField ℚ L)
    (hE : @Normal ℚ ↥E _ _ E.algebra')
    {q : ℕ}
    {P : Ideal (NumberField.RingOfIntegers L)}
    [P.IsPrime] [P.LiesOver (Ideal.rationalPrimeIdeal q)]
    (σ : Gal(L/ℚ))
    (hσ : σ ∈ P.inertia (Gal(L/ℚ))) :
    ∀ x : NumberField.RingOfIntegers E,
      MulSemiringAction.toAlgHom ℤ (NumberField.RingOfIntegers E)
          ((@AlgEquiv.restrictNormalHom ℚ _ L _ _ ↥E _ E.algebra' _ _ hE) σ) x -
        x ∈
      P.under (NumberField.RingOfIntegers E) := by
  let Q : Ideal (NumberField.RingOfIntegers E) :=
    P.under (NumberField.RingOfIntegers E)
  intro x
  change
    MulSemiringAction.toAlgHom ℤ (NumberField.RingOfIntegers E)
        ((@AlgEquiv.restrictNormalHom ℚ _ L _ _ ↥E _ E.algebra' _ _ hE) σ) x - x ∈
      Q
  rw [Ideal.mem_of_liesOver
    (A := NumberField.RingOfIntegers E)
    (B := NumberField.RingOfIntegers L)
    (p := Q)
    (P := P)]
  rw [map_sub]
  have hmap :
      algebraMap (NumberField.RingOfIntegers E)
          (NumberField.RingOfIntegers L)
          (MulSemiringAction.toAlgHom ℤ
            (NumberField.RingOfIntegers E)
            ((@AlgEquiv.restrictNormalHom ℚ _ L _ _ ↥E _ E.algebra' _ _ hE) σ) x) =
        MulSemiringAction.toAlgHom ℤ
          (NumberField.RingOfIntegers L) σ
            (algebraMap (NumberField.RingOfIntegers E)
              (NumberField.RingOfIntegers L) x) := by
    apply Subtype.ext
    change
      algebraMap ↥E L
          (((@AlgEquiv.restrictNormalHom ℚ _ L _ _ ↥E _ E.algebra' _ _ hE) σ)
            (algebraMap (NumberField.RingOfIntegers E) ↥E x)) =
        σ
          (algebraMap ↥E L
            (algebraMap (NumberField.RingOfIntegers E) ↥E x))
    simpa using
      (@AlgEquiv.restrictNormalHom_apply
        ℚ
        _
        L
        _
        _
        E
        hE
        σ
        (algebraMap (NumberField.RingOfIntegers E) ↥E x))
  rw [hmap]
  simpa using
    hσ
      (algebraMap (NumberField.RingOfIntegers E)
        (NumberField.RingOfIntegers L) x)

noncomputable def numberInertiaRestriction
    {L : Type*} [Field L] [NumberField L] [Algebra ℚ L]
    [FiniteDimensional ℚ L] [IsGalois ℚ L]
    (E : IntermediateField ℚ L)
    (hE : @Normal ℚ ↥E _ _ E.algebra')
    (q : ℕ)
    (P : Ideal (NumberField.RingOfIntegers L))
    [P.IsPrime] [P.LiesOver (Ideal.rationalPrimeIdeal q)] :
    letI : Algebra ℚ ↥E := E.algebra'
    P.inertia (Gal(L/ℚ)) →*
      (P.under (NumberField.RingOfIntegers E)).inertia
        (Gal(↥E/ℚ)) := by
  letI : Algebra ℚ ↥E := E.algebra'
  letI : Normal ℚ ↥E := hE
  exact
    { toFun := fun σ =>
        ⟨AlgEquiv.restrictNormalHom E σ.1,
          number_restrict_inertia E hE
            (q := q) σ.1 σ.2⟩
      map_one' := by
        ext
        simp
      map_mul' := by
        intro σ τ
        ext
        simp }

set_option synthInstance.maxHeartbeats 200000 in
-- long proof
lemma number_restriction_surjective
    {L : Type*} [Field L] [NumberField L] [Algebra ℚ L]
    [FiniteDimensional ℚ L] [IsGalois ℚ L]
    (E : IntermediateField ℚ L)
    (hEfin :
      letI : Algebra ℚ ↥E := E.algebra'
      FiniteDimensional ℚ ↥E)
    (hEgal :
      letI : Algebra ℚ ↥E := E.algebra'
      IsGalois ℚ ↥E)
    {q : ℕ} (hq : Nat.Prime q)
    (P : Ideal (NumberField.RingOfIntegers L))
    [P.IsPrime] [P.LiesOver (Ideal.rationalPrimeIdeal q)] :
    letI : Algebra ℚ ↥E := E.algebra'
    Function.Surjective
      (numberInertiaRestriction E hEgal.to_normal q P) := by
  letI : Algebra ℚ ↥E := E.algebra'
  letI : FiniteDimensional ℚ ↥E := hEfin
  letI : IsGalois ℚ ↥E := hEgal
  letI : NumberField ↥E := NumberField.of_module_finite ℚ ↥E
  let qI : Ideal ℤ := Ideal.rationalPrimeIdeal q
  let Q : Ideal (NumberField.RingOfIntegers E) :=
    P.under (NumberField.RingOfIntegers E)
  let f :=
    numberInertiaRestriction E hEgal.to_normal q P
  have hqI0 : qI ≠ ⊥ :=
    rational_ne_bot hq
  letI : qI.IsMaximal :=
    rational_ideal_maximal hq
  letI : Q.LiesOver qI := by
    rw [Ideal.liesOver_iff]
    simpa [Q, qI, Ideal.liesOver_iff] using
      (show P.LiesOver (Ideal.rationalPrimeIdeal q) by infer_instance)
  have hQ0 : Q ≠ ⊥ :=
    Ideal.ne_bot_of_liesOver_of_ne_bot hqI0 Q
  letI : Q.IsMaximal :=
    Ideal.IsMaximal.of_liesOver_isMaximal (p := qI) (P := Q)
  letI : P.LiesOver Q := by
    simp [Q, Ideal.liesOver_iff]
  have hP0 : P ≠ ⊥ :=
    Ideal.ne_bot_of_liesOver_of_ne_bot hQ0 P
  letI : P.IsMaximal :=
    Ideal.IsMaximal.of_liesOver_isMaximal (p := Q) (P := P)
  letI : Field ((NumberField.RingOfIntegers E) ⧸ Q) :=
    Ideal.Quotient.field Q
  letI : Field ((NumberField.RingOfIntegers L) ⧸ P) :=
    Ideal.Quotient.field P
  letI : IsGaloisGroup E.fixingSubgroup ↥E L :=
    IsGaloisGroup.intermediateField
      (G := Gal(L/ℚ)) (K := ℚ) (L := L) (F := E)
  letI := IsIntegralClosure.MulSemiringAction
    (NumberField.RingOfIntegers E) E L
    (NumberField.RingOfIntegers L)
  letI : IsGaloisGroup E.fixingSubgroup
      (NumberField.RingOfIntegers E)
      (NumberField.RingOfIntegers L) :=
    IsGaloisGroup.of_isFractionRing
      (G := E.fixingSubgroup)
      (A := NumberField.RingOfIntegers E)
      (B := NumberField.RingOfIntegers L)
      (K := ↥E) (L := L)
  letI : Algebra.IsSeparable
      ((NumberField.RingOfIntegers E) ⧸ Q)
      ((NumberField.RingOfIntegers L) ⧸ P) := by
    letI : IsGalois
        ((NumberField.RingOfIntegers E) ⧸ Q)
        ((NumberField.RingOfIntegers L) ⧸ P) :=
      { __ := Ideal.Quotient.normal
          (A := NumberField.RingOfIntegers E)
          (G := E.fixingSubgroup) Q P }
    infer_instance
  have hsource :
      Nat.card (P.inertia (Gal(L/ℚ))) =
        Ideal.ramificationIdx qI P := by
    simpa [qI] using
      inertia_ramification_idx
        (L := L) hq P
  have htarget :
      Nat.card (Q.inertia (Gal(↥E/ℚ))) =
        Ideal.ramificationIdx qI Q := by
    simpa [Q, qI] using
      inertia_ramification_idx
        (L := ↥E) hq Q
  have hrelative :
      Nat.card (P.inertia E.fixingSubgroup) =
        Ideal.ramificationIdx Q P := by
    calc
      Nat.card (P.inertia E.fixingSubgroup) =
          Q.ramificationIdxIn (NumberField.RingOfIntegers L) := by
        exact
          Ideal.card_inertia_eq_ramificationIdxIn
            (G := E.fixingSubgroup) Q hQ0 P
      _ = Ideal.ramificationIdx Q P := by
        exact
          Ideal.ramificationIdxIn_eq_ramificationIdx
            (p := Q) (P := P) (G := E.fixingSubgroup)
  have hramification :
      Ideal.ramificationIdx qI P =
        Ideal.ramificationIdx qI Q *
          Ideal.ramificationIdx Q P := by
    exact
      Ideal.ramificationIdx_algebra_tower' qI Q P
  let kernelEmbedding :
      f.ker ↪ P.inertia E.fixingSubgroup :=
    { toFun := fun σ =>
        ⟨⟨σ.1.1, by
            rw [← IntermediateField.restrictNormalHom_ker E]
            apply MonoidHom.mem_ker.mpr
            exact congrArg Subtype.val σ.2⟩,
          σ.1.2⟩
      inj' := by
        intro σ τ hστ
        exact
          Subtype.ext
            (Subtype.ext
              (congrArg
                (fun x : P.inertia E.fixingSubgroup =>
                  (x.1.1 : Gal(L/ℚ)))
                hστ)) }
  have hker :
      Nat.card f.ker ≤
        Nat.card (P.inertia E.fixingSubgroup) :=
    Nat.card_le_card_of_injective kernelEmbedding kernelEmbedding.injective
  apply
    MonoidHom.surjective_of_card_ker_le_div
  rw [hsource, htarget, hramification]
  change Nat.card f.ker ≤ _
  calc
    Nat.card f.ker ≤ Nat.card (P.inertia E.fixingSubgroup) :=
      hker
    _ = Ideal.ramificationIdx Q P :=
      hrelative
    _ = (Ideal.ramificationIdx qI Q *
          Ideal.ramificationIdx Q P) /
          Ideal.ramificationIdx qI Q := by
      symm
      exact
        Nat.mul_div_cancel_left _
          (Nat.pos_iff_ne_zero.mpr
            (Ideal.IsDedekindDomain.ramificationIdx_ne_zero_of_liesOver Q hqI0))

lemma number_restrict_tower
    {K L : Type*} [Field K] [NumberField K] [Field L] [NumberField L]
    [Algebra ℚ K] [Algebra ℚ L] [Algebra K L]
    [IsScalarTower ℚ K L] [FiniteDimensional ℚ L] [IsGalois ℚ L]
    [Normal ℚ K]
    {q : ℕ}
    {P : Ideal (NumberField.RingOfIntegers L)}
    [P.IsPrime] [P.LiesOver (Ideal.rationalPrimeIdeal q)]
    (σ : Gal(L/ℚ))
    (hσ : σ ∈ P.inertia (Gal(L/ℚ))) :
    ∀ x : NumberField.RingOfIntegers K,
      MulSemiringAction.toAlgHom ℤ (NumberField.RingOfIntegers K)
          (σ.restrictNormalHom K) x -
        x ∈
      P.under (NumberField.RingOfIntegers K) := by
  let Q : Ideal (NumberField.RingOfIntegers K) :=
    P.under (NumberField.RingOfIntegers K)
  intro x
  change
    MulSemiringAction.toAlgHom ℤ (NumberField.RingOfIntegers K)
        (σ.restrictNormalHom K) x - x ∈
      Q
  rw [Ideal.mem_of_liesOver
    (A := NumberField.RingOfIntegers K)
    (B := NumberField.RingOfIntegers L)
    (p := Q)
    (P := P)]
  rw [map_sub]
  have hmap :
      algebraMap (NumberField.RingOfIntegers K)
          (NumberField.RingOfIntegers L)
          (MulSemiringAction.toAlgHom ℤ
            (NumberField.RingOfIntegers K)
            (σ.restrictNormalHom K) x) =
        MulSemiringAction.toAlgHom ℤ
          (NumberField.RingOfIntegers L) σ
            (algebraMap (NumberField.RingOfIntegers K)
              (NumberField.RingOfIntegers L) x) := by
    apply Subtype.ext
    change
      algebraMap K L
          ((σ.restrictNormalHom K)
            (algebraMap (NumberField.RingOfIntegers K) K x)) =
        σ
          (algebraMap K L
            (algebraMap (NumberField.RingOfIntegers K) K x))
    simp [AlgEquiv.restrictNormalHom]
  rw [hmap]
  simpa using
    hσ
      (algebraMap (NumberField.RingOfIntegers K)
        (NumberField.RingOfIntegers L) x)

noncomputable def numberRestrictionTower
    (K L : Type*) [Field K] [NumberField K] [Field L] [NumberField L]
    [Algebra ℚ K] [Algebra ℚ L] [Algebra K L]
    [IsScalarTower ℚ K L] [FiniteDimensional ℚ L] [IsGalois ℚ L]
    [Normal ℚ K]
    (q : ℕ)
    (P : Ideal (NumberField.RingOfIntegers L))
    [P.IsPrime] [P.LiesOver (Ideal.rationalPrimeIdeal q)] :
    P.inertia (Gal(L/ℚ)) →*
      (P.under (NumberField.RingOfIntegers K)).inertia
        (Gal(K/ℚ)) :=
  { toFun := fun σ =>
      ⟨σ.1.restrictNormalHom K,
        number_restrict_tower
          (q := q) σ.1 σ.2⟩
    map_one' := by
      ext
      simp
    map_mul' := by
      intro σ τ
      ext
      simp }

/--
Every inertia element downstairs admits an inertia lift through a finite
Galois intermediate field.

This is the one-step selection form of
`number_restriction_surjective`.  The inverse-limit construction
below repeatedly needs witnesses rather than a bare surjectivity predicate,
so keeping this wrapper explicit prevents the arithmetic lifting step from
being hidden inside a later compactness argument.
-/
lemma number_restriction_preimage
    {L : Type*} [Field L] [NumberField L] [Algebra ℚ L]
    [FiniteDimensional ℚ L] [IsGalois ℚ L]
    (E : IntermediateField ℚ L)
    (hEfin :
      letI : Algebra ℚ ↥E := E.algebra'
      FiniteDimensional ℚ ↥E)
    (hEgal :
      letI : Algebra ℚ ↥E := E.algebra'
      IsGalois ℚ ↥E)
    {q : ℕ} (hq : Nat.Prime q)
    (P : Ideal (NumberField.RingOfIntegers L))
    [P.IsPrime] [P.LiesOver (Ideal.rationalPrimeIdeal q)]
    (τ :
      letI : Algebra ℚ ↥E := E.algebra'
      (P.under (NumberField.RingOfIntegers E)).inertia
        (Gal(↥E/ℚ))) :
    letI : Algebra ℚ ↥E := E.algebra'
    ∃ σ : P.inertia (Gal(L/ℚ)),
      numberInertiaRestriction E hEgal.to_normal q P σ =
        τ := by
  letI : Algebra ℚ ↥E := E.algebra'
  exact
    (number_restriction_surjective
      E
      hEfin
      hEgal
      hq
      P)
      τ

/-!
## Compatible tame inertia selection

The arithmetic choice needed by the Koch presentation has three logically
separate parts.

1. For one ramified rational prime, choose primes above it in every finite
   fixed-field quotient, compatibly under descent.
2. For that coherent prime family, choose one ambient inertia element whose
   image generates the inertia group in every finite layer.
3. Show that the five selected inertia elements generate each fixed finite
   quotient.

Only the third part mixes the five ramified primes.  The first two are
one-coordinate inverse-limit problems.  Keeping them separate records where
the restriction maps above are used and avoids replacing the original
profinite construction with a renamed copy of itself.
-/

/--
A compatible family of primes above one initially ramified rational prime.

This datum contains no inertia elements and no generation assertion.  It is
the prime-ideal inverse system on which the later inertia selection runs.
-/
structure CAData
    (r : InitialKochRamified) where
  primeAbove :
    ∀ N : OpenNormalSubgroup initialGaloisGroup,
      Ideal (NumberField.RingOfIntegers (initialKochLayer N))
  primeAbove_mem :
    ∀ N : OpenNormalSubgroup initialGaloisGroup,
      primeAbove N ∈
        Ideal.primesOver
          (Ideal.rationalPrimeIdeal r.1)
          (NumberField.RingOfIntegers (initialKochLayer N))
  primeAbove_comap :
    ∀ {M N : OpenNormalSubgroup initialGaloisGroup}
      (hMN : M ≤ N),
        Ideal.comap
            (initialIntegersInclusion hMN)
            (primeAbove M) =
          primeAbove N

namespace CAData

/--
The selected prime in one finite layer is prime.
-/
lemma prime_above
    {r : InitialKochRamified}
    (P : CAData r)
    (N : OpenNormalSubgroup initialGaloisGroup) :
    (P.primeAbove N).IsPrime := by
  exact
    (P.primeAbove_mem N).1

/--
The selected prime in one finite layer lies over the indexed rational prime.
-/
lemma prime_above_lies
    {r : InitialKochRamified}
    (P : CAData r)
    (N : OpenNormalSubgroup initialGaloisGroup) :
    (P.primeAbove N).LiesOver
      (Ideal.rationalPrimeIdeal r.1) := by
  exact
    (P.primeAbove_mem N).2

end CAData

/--
Arithmetic leaf: choose a coherent tower of primes above one ramified
rational prime.

This is strictly smaller than `tame_inertia_nonempty`:
it chooses no Galois-group elements, proves no inertia cyclicity, and contains
no generation statement.  The missing input is the inverse-limit
nonemptiness of the finite sets of primes above `r`.
-/
theorem coherent_above_nonempty
    (r : InitialKochRamified) :
    Nonempty (CAData r) := by
  classical
  have hlayerFG :
      ∀ N : OpenNormalSubgroup initialGaloisGroup,
        FiniteDimensional ℚ (initialKochLayer N) ∧
          IsGalois ℚ (initialKochLayer N) := by
    intro N
    let Nclosed : ClosedSubgroup initialGaloisGroup :=
      { toSubgroup := (N : Subgroup initialGaloisGroup)
        isClosed' := OpenSubgroup.isClosed N.toOpenSubgroup }
    let KN : IntermediateField ℚ initialProExtension :=
      IntermediateField.fixedField Nclosed.1
    letI : Algebra ℚ KN := KN.algebra'
    have hKNfix : KN.fixingSubgroup = Nclosed.1 := by
      simpa [KN] using
        (InfiniteGalois.fixingSubgroup_fixedField
          (k := ℚ) (K := initialProExtension) Nclosed)
    simpa [initialKochLayer, initialKochClosed, KN, Nclosed] using
      (InfiniteGalois.isOpen_and_normal_iff_finite_and_isGalois
        (k := ℚ) (K := initialProExtension) KN).mp <| by
          rw [hKNfix]
          refine ⟨N.isOpen', ?_⟩
          change (N : Subgroup initialGaloisGroup).Normal
          infer_instance
  letI :
      (Ideal.rationalPrimeIdeal r.1).IsPrime :=
    rational_prime_ideal
      (ramified_primes_prime r.1 r.2)
  letI :
      (Ideal.rationalPrimeIdeal r.1).IsMaximal :=
    rational_ideal_maximal
      (ramified_primes_prime r.1 r.2)
  letI (N : OpenNormalSubgroup initialGaloisGroup) :
      FiniteDimensional ℚ (initialKochLayer N) :=
    (hlayerFG N).1
  letI (N : OpenNormalSubgroup initialGaloisGroup) :
      IsGalois ℚ (initialKochLayer N) :=
    (hlayerFG N).2
  letI (N : OpenNormalSubgroup initialGaloisGroup) :
      NumberField (initialKochLayer N) :=
    NumberField.of_module_finite ℚ (initialKochLayer N)
  let PrimeChoice :
      OpenNormalSubgroup initialGaloisGroup → Type :=
    fun N =>
      {P : Ideal (NumberField.RingOfIntegers (initialKochLayer N)) //
        P ∈
          Ideal.primesOver
            (Ideal.rationalPrimeIdeal r.1)
            (NumberField.RingOfIntegers (initialKochLayer N))}
  letI (N : OpenNormalSubgroup initialGaloisGroup) :
      TopologicalSpace (PrimeChoice N) :=
    ⊥
  letI (N : OpenNormalSubgroup initialGaloisGroup) :
      DiscreteTopology (PrimeChoice N) :=
    ⟨rfl⟩
  letI (N : OpenNormalSubgroup initialGaloisGroup) :
      UniformSpace (PrimeChoice N) :=
    ⊥
  letI (N : OpenNormalSubgroup initialGaloisGroup) :
      Fintype (PrimeChoice N) :=
    (IsDedekindDomain.primesOver_finite
      (Ideal.rationalPrimeIdeal r.1)
      (NumberField.RingOfIntegers (initialKochLayer N))).fintype
  letI (N : OpenNormalSubgroup initialGaloisGroup) :
      CompactSpace (PrimeChoice N) := by
    infer_instance
  let FamilySpace :
      Type :=
    (N : OpenNormalSubgroup initialGaloisGroup) → PrimeChoice N
  letI : UniformSpace FamilySpace := by
    infer_instance
  letI : CompactSpace FamilySpace := by
    infer_instance
  let descend :
      ∀ {M N : OpenNormalSubgroup initialGaloisGroup},
        M ≤ N → PrimeChoice M → PrimeChoice N := by
    intro M N hMN P
    refine
      ⟨Ideal.comap (initialIntegersInclusion hMN) P.1, ?_⟩
    constructor
    · exact
        Ideal.comap_isPrime
          (initialIntegersInclusion hMN)
          P.1
    · rw [Ideal.liesOver_iff]
      simpa [Ideal.liesOver_iff] using (show P.1.LiesOver
        (Ideal.rationalPrimeIdeal r.1) from P.2.2)
  let SolutionIndex :
      Type :=
    {mn :
      OpenNormalSubgroup initialGaloisGroup ×
        OpenNormalSubgroup initialGaloisGroup //
      mn.1 ≤ mn.2}
  let coherentSet :
      SolutionIndex → Set FamilySpace :=
    fun mn =>
      {family |
        descend mn.2 (family (mn.1.1)) =
          family (mn.1.2)}
  have hcoherentSetClosed :
      ∀ mn : SolutionIndex,
        IsClosed (coherentSet mn) := by
    intro mn
    let leftMap :
        FamilySpace → PrimeChoice (mn.1.2) :=
      fun family =>
        descend mn.2 (family (mn.1.1))
    let rightMap :
        FamilySpace → PrimeChoice (mn.1.2) :=
      fun family =>
        family (mn.1.2)
    have hleft :
        Continuous leftMap := by
      have hdesc :
          Continuous
            (descend mn.2 :
              PrimeChoice (mn.1.1) →
                PrimeChoice (mn.1.2)) :=
        continuous_of_discreteTopology
      exact
        hdesc.comp
          (continuous_apply mn.1.1)
    have hright :
        Continuous rightMap :=
      continuous_apply mn.1.2
    simpa [coherentSet, leftMap, rightMap] using isClosed_eq hleft hright
  have hcoherentSetFIP :
      ∀ s : Finset SolutionIndex,
        (⋂ mn ∈ s, coherentSet mn).Nonempty := by
    intro s
    let support : Finset (OpenNormalSubgroup initialGaloisGroup) :=
      s.biUnion fun mn => {mn.1.1, mn.1.2}
    let K : OpenNormalSubgroup initialGaloisGroup :=
      support.inf (fun N : OpenNormalSubgroup initialGaloisGroup => N)
    let defaultChoice :
        (N : OpenNormalSubgroup initialGaloisGroup) → PrimeChoice N :=
      fun N =>
        Classical.choice
          (nonempty_primes_integers
            (L := initialKochLayer N)
            (ramified_primes_prime r.1 r.2))
    let PK : PrimeChoice K := defaultChoice K
    let family : FamilySpace :=
      fun N =>
        if hN : N ∈ support then
          descend (Finset.inf_le hN) PK
        else
          defaultChoice N
    refine ⟨family, ?_⟩
    rw [Set.mem_iInter₂]
    intro mn hmn
    have hM :
        mn.1.1 ∈ support := by
      refine Finset.mem_biUnion.mpr ?_
      exact ⟨mn, hmn, by simp⟩
    have hN :
        mn.1.2 ∈ support := by
      refine Finset.mem_biUnion.mpr ?_
      exact ⟨mn, hmn, by simp⟩
    have hKM :
        K ≤ mn.1.1 :=
      Finset.inf_le hM
    have hKN :
        K ≤ mn.1.2 :=
      Finset.inf_le hN
    have hKN' :
        hKN = hKM.trans mn.2 := by
      apply Subsingleton.elim
    change descend mn.2 (family (mn.1.1)) = family (mn.1.2)
    dsimp [family]
    rw [dif_pos hM, dif_pos hN]
    subst hKN
    have hcomp :
        (initialIntegersInclusion hKM).comp
            (initialIntegersInclusion mn.2) =
          initialIntegersInclusion
            (hKM.trans mn.2) := by
      ext x
      rfl
    ext x
    rw [Ideal.mem_comap, Ideal.mem_comap, Ideal.mem_comap]
    have hmap :
        (initialIntegersInclusion hKM)
            ((initialIntegersInclusion mn.2) x) =
          (initialIntegersInclusion
            (hKM.trans mn.2)) x := by
      simpa [RingHom.comp_apply] using
        congrArg (fun f => f x) hcomp
    simp [hmap]
  have hall :
      (⋂ mn : SolutionIndex, coherentSet mn).Nonempty := by
    exact
      CompactSpace.iInter_nonempty
        hcoherentSetClosed
        hcoherentSetFIP
  rcases hall with ⟨family, hfamily⟩
  refine
    ⟨{
      primeAbove := fun N => (family N).1
      primeAbove_mem := fun N => (family N).2
      primeAbove_comap := ?_
    }⟩
  intro M N hMN
  let mn : SolutionIndex := ⟨(M, N), hMN⟩
  exact congrArg Subtype.val (Set.mem_iInter.mp hfamily mn)

/--
One compatible inertia generator over a previously selected coherent prime
tower.

The ambient element is retained because later local Frobenius relations must
refer to the same element in every finite quotient.  The generation field is
coordinatewise: it asks only that this element generate the local inertia
group at the fixed rational prime `r`.
-/
structure CIData
    (r : InitialKochRamified)
    (P : CAData r) where
  generator :
    initialGaloisGroup
  inertiaGenerator :
    ∀ N : OpenNormalSubgroup initialGaloisGroup,
      (P.primeAbove N).inertia
        (Gal(initialKochLayer N / ℚ))
  mapsFiniteLayer :
    ∀ N : OpenNormalSubgroup initialGaloisGroup,
      initialKochEquiv N
          (IGScaffoa.quotientMap N generator) =
        (inertiaGenerator N :
          Gal(initialKochLayer N / ℚ))
  inertiaGenerator_generates :
    ∀ N : OpenNormalSubgroup initialGaloisGroup,
      Subgroup.closure
          ({(inertiaGenerator N :
            Gal(initialKochLayer N / ℚ))} : Set _) =
        (P.primeAbove N).inertia
          (Gal(initialKochLayer N / ℚ))

/--
For one coherent prime tower, the ambient elements whose image in one fixed
finite layer is an inertia generator.

This is the local closed condition used in the one-coordinate compactness
argument.  It records only one finite quotient at a time, with no compatibility
between different `N`.
-/
def compatibleGoodSet
    (r : InitialKochRamified)
    (P : CAData r)
    (N : OpenNormalSubgroup initialGaloisGroup) :
    Set initialGaloisGroup :=
  {g |
    let σ :=
      initialKochEquiv N
        (IGScaffoa.quotientMap N g)
    σ ∈ (P.primeAbove N).inertia
        (Gal(initialKochLayer N / ℚ)) ∧
      Subgroup.closure ({σ} : Set (Gal(initialKochLayer N / ℚ))) =
        (P.primeAbove N).inertia
          (Gal(initialKochLayer N / ℚ))}

/--
Unfold the local good-generator condition.
-/
lemma compatible_good_set
    (r : InitialKochRamified)
    (P : CAData r)
    (N : OpenNormalSubgroup initialGaloisGroup)
    (g : initialGaloisGroup) :
    g ∈ compatibleGoodSet r P N ↔
      let σ :=
        initialKochEquiv N
          (IGScaffoa.quotientMap N g)
      σ ∈ (P.primeAbove N).inertia
          (Gal(initialKochLayer N / ℚ)) ∧
        Subgroup.closure ({σ} : Set (Gal(initialKochLayer N / ℚ))) =
          (P.primeAbove N).inertia
            (Gal(initialKochLayer N / ℚ)) := by
  rfl

/--
Each local good-generator set is closed because it is the preimage of a subset
of a finite discrete quotient.
-/
theorem compatible_good_closed
    (r : InitialKochRamified)
    (P : CAData r)
    (N : OpenNormalSubgroup initialGaloisGroup) :
    IsClosed (compatibleGoodSet r P N) := by
  change
    IsClosed
      ((IGScaffoa.quotientMap N) ⁻¹'
        {x |
          let σ := initialKochEquiv N x
          σ ∈ (P.primeAbove N).inertia
              (Gal(initialKochLayer N / ℚ)) ∧
            Subgroup.closure ({σ} : Set (Gal(initialKochLayer N / ℚ))) =
              (P.primeAbove N).inertia
                (Gal(initialKochLayer N / ℚ))})
  exact
    (Set.toFinite
      {x : initialGaloisGroup ⧸ N.toSubgroup |
        let σ := initialKochEquiv N x
        σ ∈ (P.primeAbove N).inertia
            (Gal(initialKochLayer N / ℚ)) ∧
          Subgroup.closure ({σ} : Set (Gal(initialKochLayer N / ℚ))) =
            (P.primeAbove N).inertia
              (Gal(initialKochLayer N / ℚ))}).isClosed.preimage
      (IGScaffoa.quotientMap_continuous N)

/--
In one finite layer, tame inertia admits a single generator.

This is the finite arithmetic leaf needed before any compatibility or compact
selection enters the picture.
-/
theorem initial_inertia_generator
    (r : InitialKochRamified)
    (P : CAData r)
    (N : OpenNormalSubgroup initialGaloisGroup) :
    ∃ σ : Gal(initialKochLayer N / ℚ),
      σ ∈ (P.primeAbove N).inertia
          (Gal(initialKochLayer N / ℚ)) ∧
        Subgroup.closure ({σ} : Set (Gal(initialKochLayer N / ℚ))) =
          (P.primeAbove N).inertia
            (Gal(initialKochLayer N / ℚ)) := by
  have hNfg :
      FiniteDimensional ℚ (initialKochLayer N) ∧
        IsGalois ℚ (initialKochLayer N) := by
    simpa [initialKochLayer, initialKochClosed] using
      (STBuild.initial_galois_open N)
  letI : FiniteDimensional ℚ (initialKochLayer N) :=
    hNfg.1
  letI : IsGalois ℚ (initialKochLayer N) :=
    hNfg.2
  letI : NumberField (initialKochLayer N) :=
    NumberField.of_module_finite ℚ (initialKochLayer N)
  have hPmem :
      P.primeAbove N ∈
        Ideal.primesOver
          (Ideal.rationalPrimeIdeal r.1)
          (NumberField.RingOfIntegers (initialKochLayer N)) :=
    P.primeAbove_mem N
  letI : (P.primeAbove N).IsPrime :=
    hPmem.1
  letI : (P.primeAbove N).LiesOver (Ideal.rationalPrimeIdeal r.1) :=
    hPmem.2
  have hrPrime :
      Nat.Prime r.1 :=
    ramified_primes_prime r.1 r.2
  have hPGroup :
      IsPGroup 3 (Gal(initialKochLayer N / ℚ)) := by
    exact
      @STBuild.initial_pro_subextension
        (IntermediateField.fixedField
          (initialKochClosed N).1)
        hNfg.1
        hNfg.2
  have hCardCoprime :
      Nat.Coprime r.1
        (Nat.card (Gal(initialKochLayer N / ℚ))) :=
    STBuild.p_coprime_ramified
      hPGroup
      r
  have hTame :
      RationalTamePrimes
        (S := NumberField.RingOfIntegers (initialKochLayer N))
        r.1 :=
    STBuild.primes_coprime_card
      (L := initialKochLayer N)
      hrPrime
      hCardCoprime
  have hInertiaCyclic :
      IsCyclic ((P.primeAbove N).inertia (Gal(initialKochLayer N / ℚ))) :=
    tame_cyclic
      (L := initialKochLayer N)
      hrPrime
      hTame
      (P.primeAbove N)
  obtain ⟨σ, hσgen⟩ :=
    (Subgroup.isCyclic_iff_exists_zpowers_eq_top
      ((P.primeAbove N).inertia (Gal(initialKochLayer N / ℚ)))).mp
      hInertiaCyclic
  refine ⟨σ, ?_, ?_⟩
  · rw [← hσgen]
    exact Subgroup.mem_zpowers σ
  · simpa [Subgroup.zpowers_eq_closure] using hσgen

end TBluepr
end Towers
