import Towers.FieldTheory.HMRProThree.KochData

open scoped Pointwise Topology commutatorElement

noncomputable section

namespace Towers
namespace TBluepr

open STBuild
open KPScaffo
open IGScaffoa
open GSScaffo
open ILScaffo

private instance initialThreeFact : Fact (Nat.Prime 3) :=
  ⟨Nat.prime_three⟩

/-!
## Finite-shadow bridge for Koch kernel generation

The remaining Koch relation theorem is naturally arithmetic: the five tame
relations generate every relation in the maximal pro-`3` Galois group.  The
arithmetic proof is most conveniently checked after passage to finite Galois
layers.  The generic lemmas below isolate the profinite passage from those
finite checks to topological normal generation in the free pro-`3` group.

There are two finite-shadow predicates.  The algebraic predicate is the one
that finite Galois theory should prove: modulo an open normal subgroup, every
kernel element is represented by an element of the ordinary normal closure of
the displayed relators.  The topological predicate is a formally weaker
variant using the topological normal closure.  Profinite separation turns the
topological finite-shadow predicate into the desired global inclusion, while a
short algebraic argument promotes the arithmetic predicate to the topological
one.
-/

namespace IGScaffo

universe u v w

/--
The algebraic normal subgroup generated by a displayed family of relators.
-/
abbrev relationSubgroup
    {F : Type u}
    [Group F]
    {ι : Type w}
    (relator : ι → F) :
    Subgroup F :=
  Subgroup.normalClosure (Set.range relator)

/--
The closed normal subgroup topologically generated by a displayed family of
relators.
-/
abbrev completedRelationSubgroup
    {F : Type u}
    [Group F]
    [TopologicalSpace F]
    [IsTopologicalGroup F]
    {ι : Type w}
    (relator : ι → F) :
    Subgroup F :=
  (relationSubgroup relator).topologicalClosure

/--
A displayed relator belongs to its algebraic normal closure.
-/
lemma relator_relation_subgroup
    {F : Type u}
    [Group F]
    {ι : Type w}
    (relator : ι → F)
    (i : ι) :
    relator i ∈ relationSubgroup relator := by
  apply
    Subgroup.subset_normalClosure
  exact
    Set.mem_range_self i

/--
The algebraic normal closure is contained in the corresponding topological
normal closure.
-/
lemma relation_completed
    {F : Type u}
    [Group F]
    [TopologicalSpace F]
    [IsTopologicalGroup F]
    {ι : Type w}
    (relator : ι → F) :
    relationSubgroup relator ≤
      completedRelationSubgroup relator := by
  exact
    (relationSubgroup relator).le_topologicalClosure

/--
Every displayed relator belongs to the corresponding topological normal
closure.
-/
lemma relator_completed_subgroup
    {F : Type u}
    [Group F]
    [TopologicalSpace F]
    [IsTopologicalGroup F]
    {ι : Type w}
    (relator : ι → F)
    (i : ι) :
    relator i ∈ completedRelationSubgroup relator := by
  apply
    relation_completed relator
  exact
    relator_relation_subgroup relator i

/--
The topological normal closure is closed.
-/
lemma completed_relation_closed
    {F : Type u}
    [Group F]
    [TopologicalSpace F]
    [IsTopologicalGroup F]
    {ι : Type w}
    (relator : ι → F) :
    IsClosed (completedRelationSubgroup relator : Set F) := by
  exact
    Subgroup.isClosed_topologicalClosure
      (relationSubgroup relator)

/--
The image of the algebraic normal closure in an open-normal finite shadow is
contained in the image of the completed normal closure.
-/
lemma relation_subgroup_completed
    {F : Type u}
    [Group F]
    [TopologicalSpace F]
    [IsTopologicalGroup F]
    {ι : Type w}
    (relator : ι → F)
    (N : OpenNormalSubgroup F) :
    (relationSubgroup relator).map
        (IGScaffoa.quotientMap N) ≤
      (completedRelationSubgroup relator).map
        (IGScaffoa.quotientMap N) := by
  intro y hy
  rcases hy with ⟨x, hx, rfl⟩
  exact
    ⟨x,
      relation_completed relator hx,
      rfl⟩

/--
The image of a displayed relator belongs to the image of its completed normal
closure in every open-normal finite shadow.
-/
lemma relator_completed_relation
    {F : Type u}
    [Group F]
    [TopologicalSpace F]
    [IsTopologicalGroup F]
    {ι : Type w}
    (relator : ι → F)
    (N : OpenNormalSubgroup F)
    (i : ι) :
    IGScaffoa.quotientMap N (relator i) ∈
      (completedRelationSubgroup relator).map
        (IGScaffoa.quotientMap N) := by
  refine
    ⟨relator i, ?_, rfl⟩
  exact
    relator_completed_subgroup relator i

/--
Finite-layer arithmetic kernel generation: after quotienting by one open
normal subgroup, every element of the global kernel is congruent to an element
of the ordinary normal closure of the displayed relators.
-/
def GeneratedAlgebraicallyOpen
    {F : Type u}
    {G : Type v}
    [Group F]
    [TopologicalSpace F]
    [Group G]
    {ι : Type w}
    (q : F →* G)
    (relator : ι → F)
    (N : OpenNormalSubgroup F) :
    Prop :=
  ∀ x ∈ q.ker,
    IGScaffoa.quotientMap N x ∈
      (relationSubgroup relator).map
        (IGScaffoa.quotientMap N)

/--
The algebraic finite-layer predicate simultaneously for all open-normal
finite shadows.
-/
def GeneratedAlgebraicallyEvery
    {F : Type u}
    {G : Type v}
    [Group F]
    [TopologicalSpace F]
    [Group G]
    {ι : Type w}
    (q : F →* G)
    (relator : ι → F) :
    Prop :=
  ∀ N : OpenNormalSubgroup F,
    GeneratedAlgebraicallyOpen q relator N

/--
Topological finite-shadow kernel generation: after quotienting by one open
normal subgroup, every element of the global kernel is represented by an
element of the completed normal closure of the displayed relators.
-/
def GeneratedTopologicallyOpen
    {F : Type u}
    {G : Type v}
    [Group F]
    [TopologicalSpace F]
    [IsTopologicalGroup F]
    [Group G]
    {ι : Type w}
    (q : F →* G)
    (relator : ι → F)
    (N : OpenNormalSubgroup F) :
    Prop :=
  ∀ x ∈ q.ker,
    IGScaffoa.quotientMap N x ∈
      (completedRelationSubgroup relator).map
        (IGScaffoa.quotientMap N)

/--
The topological finite-shadow predicate simultaneously for all open-normal
finite shadows.
-/
def GeneratedTopologicallyEvery
    {F : Type u}
    {G : Type v}
    [Group F]
    [TopologicalSpace F]
    [IsTopologicalGroup F]
    [Group G]
    {ι : Type w}
    (q : F →* G)
    (relator : ι → F) :
    Prop :=
  ∀ N : OpenNormalSubgroup F,
    GeneratedTopologicallyOpen q relator N

/--
Algebraic finite-layer generation implies topological finite-layer generation
for a fixed open-normal quotient.
-/
lemma topologically_open_algebraically
    {F : Type u}
    {G : Type v}
    [Group F]
    [TopologicalSpace F]
    [IsTopologicalGroup F]
    [Group G]
    {ι : Type w}
    {q : F →* G}
    {relator : ι → F}
    (N : OpenNormalSubgroup F)
    (hN : GeneratedAlgebraicallyOpen q relator N) :
    GeneratedTopologicallyOpen q relator N := by
  intro x hx
  apply
    relation_subgroup_completed relator N
  exact
    hN x hx

/--
Algebraic finite-layer generation in every shadow implies topological
finite-layer generation in every shadow.
-/
lemma topologically_every_algebraically
    {F : Type u}
    {G : Type v}
    [Group F]
    [TopologicalSpace F]
    [IsTopologicalGroup F]
    [Group G]
    {ι : Type w}
    {q : F →* G}
    {relator : ι → F}
    (h :
      GeneratedAlgebraicallyEvery q relator) :
    GeneratedTopologicallyEvery q relator := by
  intro N
  exact
    topologically_open_algebraically
      N
      (h N)

/--
A global kernel inclusion immediately gives its topological finite-shadow
form.
-/
lemma generated_topologically_every
    {F : Type u}
    {G : Type v}
    [Group F]
    [TopologicalSpace F]
    [IsTopologicalGroup F]
    [Group G]
    {ι : Type w}
    {q : F →* G}
    {relator : ι → F}
    (hkernel :
      q.ker ≤ completedRelationSubgroup relator) :
    GeneratedTopologicallyEvery q relator := by
  intro N x hx
  refine
    ⟨x, ?_, rfl⟩
  exact
    hkernel hx

/--
Under topological finite-shadow generation, every global kernel element has
the same image as an element of the completed normal closure in each
open-normal quotient.
-/
lemma image_completed_relation
    {F : Type u}
    {G : Type v}
    [Group F]
    [TopologicalSpace F]
    [IsTopologicalGroup F]
    [Group G]
    {ι : Type w}
    {q : F →* G}
    {relator : ι → F}
    (h :
      GeneratedTopologicallyEvery q relator)
    (x : F)
    (hx : x ∈ q.ker)
    (N : OpenNormalSubgroup F) :
    IGScaffoa.quotientMap N x ∈
      IGScaffoa.quotientMap N ''
        (completedRelationSubgroup relator : Set F) := by
  rcases
      h N x hx with
    ⟨y, hy, hyx⟩
  exact
    ⟨y, hy, hyx⟩

/--
Profinite separation upgrades topological finite-shadow kernel generation to
membership in the completed normal closure.
-/
lemma completed_topologically_every
    {F : Type u}
    {G : Type v}
    [Group F]
    [TopologicalSpace F]
    [IsTopologicalGroup F]
    [CompactSpace F]
    [TotallyDisconnectedSpace F]
    [Group G]
    {ι : Type w}
    {q : F →* G}
    {relator : ι → F}
    (h :
      GeneratedTopologicallyEvery q relator)
    (x : F)
    (hx : x ∈ q.ker) :
    x ∈ completedRelationSubgroup relator := by
  by_contra hxclosure
  have hclosed :
      IsClosed (completedRelationSubgroup relator : Set F) :=
    completed_relation_closed relator
  rcases
      separate_sets_disconnected
        hclosed
        x
        hxclosure with
    ⟨N, hN⟩
  apply
    hN
  simpa [IGScaffoa.quotientMap] using
    image_completed_relation
      h
      x
      hx
      N

/--
Topological kernel generation in every finite shadow gives the global
topological normal-closure inclusion.
-/
lemma relation_topological_shadows
    {F : Type u}
    {G : Type v}
    [Group F]
    [TopologicalSpace F]
    [IsTopologicalGroup F]
    [CompactSpace F]
    [TotallyDisconnectedSpace F]
    [Group G]
    {ι : Type w}
    {q : F →* G}
    {relator : ι → F}
    (h :
      GeneratedTopologicallyEvery q relator) :
    q.ker ≤ completedRelationSubgroup relator := by
  intro x hx
  exact
    completed_topologically_every
      h
      x
      hx

/--
For profinite groups, global topological kernel generation is equivalent to
topological kernel generation in every open-normal finite shadow.
-/
lemma completed_topological_shadows
    {F : Type u}
    {G : Type v}
    [Group F]
    [TopologicalSpace F]
    [IsTopologicalGroup F]
    [CompactSpace F]
    [TotallyDisconnectedSpace F]
    [Group G]
    {ι : Type w}
    {q : F →* G}
    {relator : ι → F} :
    q.ker ≤ completedRelationSubgroup relator ↔
      GeneratedTopologicallyEvery q relator := by
  constructor
  · exact
      generated_topologically_every
  · exact
      relation_topological_shadows

/--
Algebraic generation in every finite shadow is sufficient for the global
topological kernel inclusion.
-/
lemma completed_algebraic_shadows
    {F : Type u}
    {G : Type v}
    [Group F]
    [TopologicalSpace F]
    [IsTopologicalGroup F]
    [CompactSpace F]
    [TotallyDisconnectedSpace F]
    [Group G]
    {ι : Type w}
    {q : F →* G}
    {relator : ι → F}
    (h :
      GeneratedAlgebraicallyEvery q relator) :
    q.ker ≤ completedRelationSubgroup relator := by
  apply
    relation_topological_shadows
  exact
    topologically_every_algebraically
      h

end IGScaffo

open IGScaffo

/-!
## Explicit finite relation words

The finite-shadow arithmetic input can be reduced one step further.  Inside a
fixed finite quotient, membership in the normal closure of the five Koch
relators is witnessed by a finite product of conjugates of those relators and
their inverses.  The scaffold below records that concrete witness and proves
that a pointwise supply of such words is enough for the all-shadows predicate
used above.

This leaves arithmetic with a deliberately local obligation: one open-normal
finite quotient and one element of the quotient-map kernel at a time.  There is
no topology, closure, inverse limit, or simultaneous choice of words in the
remaining statement.
-/

namespace IRScaffo

universe u v w

/--
One signed conjugate of a displayed relator.  These are the letters from which
an explicit witness for membership in a normal closure is assembled.
-/
structure SConjug
    (ι : Type w)
    (F : Type u)
    [Group F] where
  conjugator :
    F
  relatorIndex :
    ι
  isInverse :
    Bool

namespace SConjug

/--
Evaluate a signed conjugate letter in the ambient group.
-/
def value
    {ι : Type w}
    {F : Type u}
    [Group F]
    (relator : ι → F)
    (letter : SConjug ι F) :
    F :=
  if letter.isInverse then
    letter.conjugator * (relator letter.relatorIndex)⁻¹ * letter.conjugator⁻¹
  else
    letter.conjugator * relator letter.relatorIndex * letter.conjugator⁻¹

/--
The positive signed conjugate with the displayed conjugator and relator index.
-/
def positive
    {ι : Type w}
    {F : Type u}
    [Group F]
    (conjugator : F)
    (relatorIndex : ι) :
    SConjug ι F where
  conjugator :=
    conjugator
  relatorIndex :=
    relatorIndex
  isInverse :=
    false

/--
The negative signed conjugate with the displayed conjugator and relator index.
-/
def negative
    {ι : Type w}
    {F : Type u}
    [Group F]
    (conjugator : F)
    (relatorIndex : ι) :
    SConjug ι F where
  conjugator :=
    conjugator
  relatorIndex :=
    relatorIndex
  isInverse :=
    true

/--
Evaluating a positive signed conjugate gives the expected group expression.
-/
@[simp]
lemma value_positive
    {ι : Type w}
    {F : Type u}
    [Group F]
    (relator : ι → F)
    (conjugator : F)
    (relatorIndex : ι) :
    value relator (positive conjugator relatorIndex) =
      conjugator * relator relatorIndex * conjugator⁻¹ := by
  rfl

/--
Evaluating a negative signed conjugate gives the expected group expression.
-/
@[simp]
lemma value_negative
    {ι : Type w}
    {F : Type u}
    [Group F]
    (relator : ι → F)
    (conjugator : F)
    (relatorIndex : ι) :
    value relator (negative conjugator relatorIndex) =
      conjugator * (relator relatorIndex)⁻¹ * conjugator⁻¹ := by
  rfl

/--
Every signed conjugate belongs to the algebraic normal subgroup generated by
the displayed relators.
-/
lemma value_relation
    {ι : Type w}
    {F : Type u}
    [Group F]
    (relator : ι → F)
    (letter : SConjug ι F) :
    value relator letter ∈ relationSubgroup relator := by
  rw [value]
  split_ifs
  · exact
      Subgroup.normalClosure_normal.conj_mem
        _
        ((relationSubgroup relator).inv_mem
          (relator_relation_subgroup relator letter.relatorIndex))
        _
  · exact
      Subgroup.normalClosure_normal.conj_mem
        _
        (relator_relation_subgroup relator letter.relatorIndex)
        _

end SConjug

/--
A finite normal-closure witness is a finite list of signed conjugates.
-/
abbrev RWord
    (ι : Type w)
    (F : Type u)
    [Group F] :=
  List (SConjug ι F)

namespace RWord

/--
Evaluate a finite relation word by multiplying its signed conjugate letters in
order.
-/
def value
    {ι : Type w}
    {F : Type u}
    [Group F]
    (relator : ι → F)
    (word : RWord ι F) :
    F :=
  (word.map (fun letter => letter.value relator)).prod

/--
The empty relation word evaluates to one.
-/
@[simp]
lemma value_nil
    {ι : Type w}
    {F : Type u}
    [Group F]
    (relator : ι → F) :
    value relator [] = 1 := by
  rfl

/--
Evaluation of a relation word beginning with one letter splits into a product.
-/
@[simp]
lemma value_cons
    {ι : Type w}
    {F : Type u}
    [Group F]
    (relator : ι → F)
    (letter : SConjug ι F)
    (word : RWord ι F) :
    value relator (letter :: word) =
      letter.value relator * value relator word := by
  rfl

/--
Evaluation carries concatenation of relation words to group multiplication.
-/
@[simp]
lemma value_append
    {ι : Type w}
    {F : Type u}
    [Group F]
    (relator : ι → F)
    (left right : RWord ι F) :
    value relator (left ++ right) =
      value relator left * value relator right := by
  simp [value, List.map_append, List.prod_append]

/--
Every evaluated relation word belongs to the algebraic normal subgroup
generated by the displayed relators.
-/
lemma value_relation
    {ι : Type w}
    {F : Type u}
    [Group F]
    (relator : ι → F)
    (word : RWord ι F) :
    value relator word ∈ relationSubgroup relator := by
  induction word with
  | nil =>
      exact
        (relationSubgroup relator).one_mem
  | cons letter word ih =>
      rw [value_cons]
      exact
        (relationSubgroup relator).mul_mem
          (letter.value_relation relator)
          ih

/--
The singleton positive word evaluates to the corresponding conjugate.
-/
@[simp]
lemma value_singleton_positive
    {ι : Type w}
    {F : Type u}
    [Group F]
    (relator : ι → F)
    (conjugator : F)
    (relatorIndex : ι) :
    value relator [SConjug.positive conjugator relatorIndex] =
      conjugator * relator relatorIndex * conjugator⁻¹ := by
  simp

/--
The singleton negative word evaluates to the corresponding inverse conjugate.
-/
@[simp]
lemma value_singleton_negative
    {ι : Type w}
    {F : Type u}
    [Group F]
    (relator : ι → F)
    (conjugator : F)
    (relatorIndex : ι) :
    value relator [SConjug.negative conjugator relatorIndex] =
      conjugator * (relator relatorIndex)⁻¹ * conjugator⁻¹ := by
  simp

/--
Invert a signed conjugate letter without changing its conjugator or relator
index.  This operation is used below to build an explicit relation word for
the inverse of an already represented element.
-/
def inverseLetter
    {ι : Type w}
    {F : Type u}
    [Group F]
    (letter : SConjug ι F) :
    SConjug ι F where
  conjugator :=
    letter.conjugator
  relatorIndex :=
    letter.relatorIndex
  isInverse :=
    !letter.isInverse

/--
Evaluation commutes with inversion of a signed conjugate letter.
-/
@[simp]
lemma value_inverseLetter
    {ι : Type w}
    {F : Type u}
    [Group F]
    (relator : ι → F)
    (letter : SConjug ι F) :
    (inverseLetter letter).value relator =
      (letter.value relator)⁻¹ := by
  cases letter with
  | mk conjugator relatorIndex isInverse =>
      cases isInverse <;>
        simp [inverseLetter, SConjug.value, mul_assoc]

/--
Conjugate a signed-conjugate letter by multiplying its stored conjugator on
the left.  Letterwise conjugation is the useful operation because a conjugate
of a product of relation letters is again a product of relation letters.
-/
def conjugateLetter
    {ι : Type w}
    {F : Type u}
    [Group F]
    (conjugator : F)
    (letter : SConjug ι F) :
    SConjug ι F where
  conjugator :=
    conjugator * letter.conjugator
  relatorIndex :=
    letter.relatorIndex
  isInverse :=
    letter.isInverse

/--
Evaluation commutes with letterwise conjugation.
-/
@[simp]
lemma value_conjugateLetter
    {ι : Type w}
    {F : Type u}
    [Group F]
    (relator : ι → F)
    (conjugator : F)
    (letter : SConjug ι F) :
    (conjugateLetter conjugator letter).value relator =
      conjugator * letter.value relator * conjugator⁻¹ := by
  cases letter with
  | mk letterConjugator relatorIndex isInverse =>
      cases isInverse <;>
        simp [conjugateLetter, SConjug.value, mul_assoc]

/--
The explicit inverse of a relation word reverses the order of its letters and
inverts each letter.
-/
def inverse
    {ι : Type w}
    {F : Type u}
    [Group F] :
    RWord ι F → RWord ι F
  | [] =>
      []
  | letter :: word =>
      inverse word ++ [inverseLetter letter]

/--
Evaluation commutes with inversion of relation words.
-/
@[simp]
lemma value_inverse
    {ι : Type w}
    {F : Type u}
    [Group F]
    (relator : ι → F)
    (word : RWord ι F) :
    value relator word.inverse =
      (value relator word)⁻¹ := by
  induction word with
  | nil =>
      simp [inverse]
  | cons letter word ih =>
      simp [inverse, ih]

/--
Conjugate every letter in a relation word by one ambient group element.
-/
def conjugate
    {ι : Type w}
    {F : Type u}
    [Group F]
    (conjugator : F)
    (word : RWord ι F) :
    RWord ι F :=
  word.map (fun letter => conjugateLetter conjugator letter)

/--
Evaluation commutes with conjugation of relation words.
-/
@[simp]
lemma value_conjugate
    {ι : Type w}
    {F : Type u}
    [Group F]
    (relator : ι → F)
    (conjugator : F)
    (word : RWord ι F) :
    value relator (word.conjugate conjugator) =
      conjugator * value relator word * conjugator⁻¹ := by
  induction word with
  | nil =>
      simp [conjugate]
  | cons letter word ih =>
      rw [show
        conjugate conjugator (letter :: word) =
          conjugateLetter conjugator letter ::
            conjugate conjugator word by
        rfl]
      rw [value_cons]
      rw [value_conjugateLetter]
      rw [ih]
      simp [mul_assoc]

/--
The elements represented by explicit relation words form a subgroup.
-/
def representedSubgroup
    {ι : Type w}
    {F : Type u}
    [Group F]
    (relator : ι → F) :
    Subgroup F where
  carrier :=
    { x | ∃ word : RWord ι F, value relator word = x }
  one_mem' := by
    exact
      ⟨[], by simp⟩
  mul_mem' := by
    intro left right hleft hright
    rcases hleft with ⟨leftWord, rfl⟩
    rcases hright with ⟨rightWord, rfl⟩
    exact
      ⟨leftWord ++ rightWord, by simp⟩
  inv_mem' := by
    intro x hx
    rcases hx with ⟨word, rfl⟩
    exact
      ⟨word.inverse, by simp⟩

/--
Membership in the represented subgroup is precisely existence of an explicit
relation word.
-/
lemma represented_subgroup
    {ι : Type w}
    {F : Type u}
    [Group F]
    (relator : ι → F)
    (x : F) :
    x ∈ representedSubgroup relator ↔
      ∃ word : RWord ι F, value relator word = x := by
  rfl

/--
The represented subgroup is closed under conjugation.  This is the key
algebraic reason that it contains the normal closure of the relators.
-/
lemma represented_subgroup_conj
    {ι : Type w}
    {F : Type u}
    [Group F]
    (relator : ι → F)
    (x : F)
    (hx : x ∈ representedSubgroup relator)
    (conjugator : F) :
    conjugator * x * conjugator⁻¹ ∈
      representedSubgroup relator := by
  rcases hx with ⟨word, rfl⟩
  exact
    ⟨word.conjugate conjugator, by simp⟩

/--
The subgroup represented by relation words is normal.
-/
lemma representedSubgroup_normal
    {ι : Type w}
    {F : Type u}
    [Group F]
    (relator : ι → F) :
    (representedSubgroup relator).Normal where
  conj_mem := by
    intro x hx conjugator
    exact
      represented_subgroup_conj relator x hx conjugator

/--
Every displayed relator has an explicit one-letter representation.
-/
lemma relator_represented_subgroup
    {ι : Type w}
    {F : Type u}
    [Group F]
    (relator : ι → F)
    (relatorIndex : ι) :
    relator relatorIndex ∈ representedSubgroup relator := by
  refine
    ⟨[SConjug.positive 1 relatorIndex], ?_⟩
  simp

/--
The algebraic normal closure of the relators lies in the subgroup represented
by explicit relation words.
-/
lemma relation_subgroup_represented
    {ι : Type w}
    {F : Type u}
    [Group F]
    (relator : ι → F) :
    relationSubgroup relator ≤
      representedSubgroup relator := by
  letI :
      (representedSubgroup relator).Normal :=
    representedSubgroup_normal relator
  apply
    Subgroup.normalClosure_le_normal
  intro x hx
  rcases hx with ⟨relatorIndex, rfl⟩
  exact
    relator_represented_subgroup relator relatorIndex

/--
Every explicit relation word evaluates into the ordinary normal closure.
-/
lemma represented_relation
    {ι : Type w}
    {F : Type u}
    [Group F]
    (relator : ι → F) :
    representedSubgroup relator ≤
      relationSubgroup relator := by
  intro x hx
  rcases hx with ⟨word, rfl⟩
  exact
    value_relation relator word

/--
Explicit relation words represent exactly the ordinary normal closure of the
displayed relators.
-/
lemma represented_subgroup_relation
    {ι : Type w}
    {F : Type u}
    [Group F]
    (relator : ι → F) :
    representedSubgroup relator =
      relationSubgroup relator := by
  apply
    le_antisymm
  · exact
      represented_relation relator
  · exact
      relation_subgroup_represented relator

/--
Normal-closure membership can be unpacked as one explicit finite relation
word.  This is the constructive bridge used by the quotient-level scaffold
below.
-/
lemma value_relation_subgroup
    {ι : Type w}
    {F : Type u}
    [Group F]
    (relator : ι → F)
    (x : F)
    (hx : x ∈ relationSubgroup relator) :
    ∃ word : RWord ι F,
      value relator word = x := by
  have hx' :
      x ∈ representedSubgroup relator := by
    rw [represented_subgroup_relation relator]
    exact
      hx
  exact
    hx'

end RWord

/--
An abstract quotient-level normal-closure membership certificate.  It records
one representative before converting that representative into a concrete
signed-conjugate word.
-/
structure RMCert
    {ι : Type w}
    {F : Type u}
    {Q : Type v}
    [Group F]
    [Group Q]
    (relator : ι → F)
    (quotientMap : F →* Q)
    (x : F) where
  representative :
    F
  representative_mem :
    representative ∈ relationSubgroup relator
  quotient_value_eq :
    quotientMap representative =
      quotientMap x

namespace RMCert

/--
Membership in the mapped relation subgroup supplies an abstract quotient
certificate.
-/
noncomputable def ofMemMap
    {ι : Type w}
    {F : Type u}
    {Q : Type v}
    [Group F]
    [Group Q]
    (relator : ι → F)
    (quotientMap : F →* Q)
    (x : F)
    (hx :
      quotientMap x ∈
        (relationSubgroup relator).map quotientMap) :
    RMCert
      relator quotientMap x := by
  let representative :
      F :=
    Classical.choose hx
  have hrepresentative :
      representative ∈ relationSubgroup relator :=
    (Classical.choose_spec hx).1
  have heq :
      quotientMap representative =
        quotientMap x :=
    (Classical.choose_spec hx).2
  exact
    { representative := representative
      representative_mem := hrepresentative
      quotient_value_eq := heq }

/--
The representative in an abstract quotient certificate has a concrete
relation-word witness.
-/
lemma representative_relation_word
    {ι : Type w}
    {F : Type u}
    {Q : Type v}
    [Group F]
    [Group Q]
    {relator : ι → F}
    {quotientMap : F →* Q}
    {x : F}
    (C :
      RMCert
        relator quotientMap x) :
    ∃ word : RWord ι F,
      word.value relator =
        C.representative := by
  exact
    RWord.value_relation_subgroup
      relator
      C.representative
      C.representative_mem

/--
An abstract quotient membership certificate yields a relation word with the
same image as the target element.
-/
lemma relation_word_value
    {ι : Type w}
    {F : Type u}
    {Q : Type v}
    [Group F]
    [Group Q]
    {relator : ι → F}
    {quotientMap : F →* Q}
    {x : F}
    (C :
      RMCert
        relator quotientMap x) :
    ∃ word : RWord ι F,
      quotientMap (word.value relator) =
        quotientMap x := by
  rcases C.representative_relation_word with ⟨word, hword⟩
  refine
    ⟨word, ?_⟩
  rw [hword]
  exact
    C.quotient_value_eq

end RMCert

/--
An explicit relation-word certificate for one kernel element in one
open-normal finite quotient.
-/
structure KECert
    {F : Type u}
    {G : Type v}
    [Group F]
    [TopologicalSpace F]
    [Group G]
    {ι : Type w}
    (q : F →* G)
    (relator : ι → F)
    (N : OpenNormalSubgroup F)
    (x : F) where
  word :
    RWord ι F
  quotient_value_eq :
    IGScaffoa.quotientMap N
        (word.value relator) =
      IGScaffoa.quotientMap N x

namespace KECert

/--
Mapped relation-subgroup membership is enough to construct the explicit
relation-word certificate expected by the all-finite-shadows argument.
-/
noncomputable def quotient_relation_subgroup
    {F : Type u}
    {G : Type v}
    [Group F]
    [TopologicalSpace F]
    [Group G]
    {ι : Type w}
    (q : F →* G)
    (relator : ι → F)
    (N : OpenNormalSubgroup F)
    (x : F)
    (hx :
      IGScaffoa.quotientMap N x ∈
        (relationSubgroup relator).map
          (IGScaffoa.quotientMap N)) :
    KECert q relator N x := by
  let C :
      RMCert
        relator
        (IGScaffoa.quotientMap N)
        x :=
    RMCert.ofMemMap
      relator
      (IGScaffoa.quotientMap N)
      x
      hx
  let word :
      RWord ι F :=
    Classical.choose C.relation_word_value
  have hword :
      IGScaffoa.quotientMap N
          (word.value relator) =
        IGScaffoa.quotientMap N x :=
    Classical.choose_spec C.relation_word_value
  exact
    { word := word
      quotient_value_eq := hword }

/--
The evaluated representative carried by a pointwise certificate belongs to
the ordinary normal closure of the relators.
-/
lemma repres_relat_subgr
    {F : Type u}
    {G : Type v}
    [Group F]
    [TopologicalSpace F]
    [Group G]
    {ι : Type w}
    {q : F →* G}
    {relator : ι → F}
    {N : OpenNormalSubgroup F}
    {x : F}
    (C : KECert q relator N x) :
    C.word.value relator ∈ relationSubgroup relator := by
  exact
    C.word.value_relation relator

/--
A pointwise relation-word certificate proves the required membership statement
in the finite quotient.
-/
lemma relation_subgroup
    {F : Type u}
    {G : Type v}
    [Group F]
    [TopologicalSpace F]
    [Group G]
    {ι : Type w}
    {q : F →* G}
    {relator : ι → F}
    {N : OpenNormalSubgroup F}
    {x : F}
    (C : KECert q relator N x) :
    IGScaffoa.quotientMap N x ∈
      (relationSubgroup relator).map
        (IGScaffoa.quotientMap N) := by
  refine
    ⟨C.word.value relator, C.repres_relat_subgr, ?_⟩
  exact
    C.quotient_value_eq

end KECert

/--
A certificate for one finite layer assigns an explicit relation word to every
element of the quotient-map kernel.
-/
structure ORCert
    {F : Type u}
    {G : Type v}
    [Group F]
    [TopologicalSpace F]
    [Group G]
    {ι : Type w}
    (q : F →* G)
    (relator : ι → F)
    (N : OpenNormalSubgroup F) where
  wordFor :
    ∀ x : F, x ∈ q.ker →
      KECert q relator N x

namespace ORCert

/--
A finite-layer relation-word certificate proves algebraic kernel generation in
that open-normal quotient.
-/
lemma kernelGeneratedAlgebraically
    {F : Type u}
    {G : Type v}
    [Group F]
    [TopologicalSpace F]
    [Group G]
    {ι : Type w}
    {q : F →* G}
    {relator : ι → F}
    {N : OpenNormalSubgroup F}
    (C : ORCert q relator N) :
    GeneratedAlgebraicallyOpen q relator N := by
  intro x hx
  exact
    (C.wordFor x hx).relation_subgroup

/--
Pointwise existence of relation words assembles into a certificate for one
finite layer.
-/
noncomputable def ofPointwise
    {F : Type u}
    {G : Type v}
    [Group F]
    [TopologicalSpace F]
    [Group G]
    {ι : Type w}
    {q : F →* G}
    {relator : ι → F}
    {N : OpenNormalSubgroup F}
    (h :
      ∀ x : F, x ∈ q.ker →
        Nonempty (KECert q relator N x)) :
    ORCert q relator N where
  wordFor :=
    fun x hx => Classical.choice (h x hx)

end ORCert

/--
Pointwise relation-word witnesses in every finite layer imply the
all-open-normal-quotients algebraic generation predicate.
-/
lemma algebraically_every_words
    {F : Type u}
    {G : Type v}
    [Group F]
    [TopologicalSpace F]
    [Group G]
    {ι : Type w}
    {q : F →* G}
    {relator : ι → F}
    (h :
      ∀ (N : OpenNormalSubgroup F) (x : F), x ∈ q.ker →
        Nonempty (KECert q relator N x)) :
    GeneratedAlgebraicallyEvery q relator := by
  intro N
  exact
    (ORCert.ofPointwise
      (fun x hx => h N x hx)).kernelGeneratedAlgebraically

end IRScaffo

open IRScaffo

end TBluepr
end Towers
