import Submission.NumberTheory.Locals.LocalUnramifiedDecomposition
import Submission.NumberTheory.Locals.TeichmullerSplitting
import Mathlib.FieldTheory.Finite.Extension

/-!
# The finite-field input to Milne's Example 7.54

For a finite field `k` and every positive integer `n`, Mathlib constructs a
degree-`n` extension.  It is the splitting field of `X^(q^n) - X`, is unique
up to `k`-isomorphism, and has cyclic Galois group generated by arithmetic
Frobenius.  Proposition 7.50 then transfers an embedded copy of this residue
extension to a finite formally unramified valuation algebra.
-/

namespace Submission.NumberTheory.Milne

noncomputable section

open Polynomial

variable (k : Type*) [Field k] [Finite k]
variable (p : ℕ) [Fact p.Prime] [CharP k p]
variable (n : ℕ) [NeZero n]

/-- The chosen degree-`n` extension of the finite residue field in Milne's
Example 7.54. -/
abbrev finiteResidueExtension := FiniteField.Extension k p n

/-- The chosen finite residue extension has degree `n`. -/
theorem residue_extension_finrank :
    Module.finrank k (finiteResidueExtension k p n) = n :=
  FiniteField.finrank_extension k p n

/-- The chosen degree-`n` residue extension has `q^n` elements. -/
theorem extension_nat_card :
    Nat.card (finiteResidueExtension k p n) = Nat.card k ^ n :=
  FiniteField.natCard_extension k p n

/-- Milne, Example 7.54: the degree-`n` residue extension is the splitting
field of `X^(q^n) - X`. -/
theorem residue_extension_splitting :
    Polynomial.IsSplittingField k (finiteResidueExtension k p n)
      (Polynomial.X ^ Nat.card k ^ n - Polynomial.X) := by
  change Polynomial.IsSplittingField k (FiniteField.Extension k p n)
    (Polynomial.X ^ Nat.card k ^ n - Polynomial.X)
  exact
    FiniteField.instIsSplittingFieldExtensionHSubPolynomialHPowNatXCard
      k p n

/-- The degree-`n` extension of a finite field is Galois. -/
theorem residue_extension_galois :
    IsGalois k (finiteResidueExtension k p n) := by
  infer_instance

/-- Its Galois group is cyclic. -/
theorem residue_extension_cyclic :
    IsCyclic Gal(finiteResidueExtension k p n / k) := by
  infer_instance

/-- Its Galois group has order `n`. -/
theorem residue_extension_card :
    Nat.card Gal(finiteResidueExtension k p n / k) = n :=
  FiniteField.natCard_algEquiv_extension k p n

/-- Arithmetic Frobenius on the chosen residue extension. -/
abbrev finiteResidueFrobenius :
    Gal(finiteResidueExtension k p n / k) :=
  FiniteField.Extension.frob k p n

/-- Arithmetic Frobenius acts by `x ↦ x^q`. -/
theorem finite_residue_frobenius
    (x : finiteResidueExtension k p n) :
    finiteResidueFrobenius k p n x = x ^ Nat.card k :=
  FiniteField.Extension.frob_apply k p n

/-- Arithmetic Frobenius generates the Galois group. -/
theorem residue_frobenius_pow
    (g : Gal(finiteResidueExtension k p n/k)) :
    ∃ i < n, finiteResidueFrobenius k p n ^ i = g :=
  FiniteField.Extension.exists_frob_pow_eq k p n g

/-- Any other degree-`n` extension of `k` is isomorphic to the chosen one. -/
theorem residue_extension_unique
    (l : Type*) [Field l] [Algebra k l]
    (h : Module.finrank k l = n) :
    Nonempty (l ≃ₐ[k] finiteResidueExtension k p n) :=
  ⟨FiniteField.algEquivExtension k p n l h⟩

section FrobeniusTransport

variable (k' l' K' L' : Type*)
  [Field k'] [Field l'] [Algebra k' l'] [Fintype k'] [Finite l']
  [Field K'] [Field L'] [Algebra K' L']

/-- Transport arithmetic Frobenius across a Galois-group equivalence.  For
Proposition 7.50(b), the equivalence is reduction from the Galois group of an
unramified local extension to that of its residue extension. -/
noncomputable def frobeniusLiftResidue
    (e : Gal(L'/K') ≃* Gal(l'/k')) : Gal(L'/K') :=
  e.symm (FiniteField.frobeniusAlgEquivOfAlgebraic k' l')

/-- The transported element reduces to arithmetic Frobenius. -/
theorem residue_galois_lift
    (e : Gal(L'/K') ≃* Gal(l'/k')) :
    e (frobeniusLiftResidue k' l' K' L' e) =
      FiniteField.frobeniusAlgEquivOfAlgebraic k' l' := by
  simp [frobeniusLiftResidue]

/-- Hence its action after reduction is `x ↦ x ^ #k`. -/
theorem residue_frobenius_lift
    (e : Gal(L'/K') ≃* Gal(l'/k')) (x : l') :
    e (frobeniusLiftResidue k' l' K' L' e) x =
      x ^ Nat.card k' := by
  rw [residue_galois_lift]
  change x ^ Fintype.card k' = x ^ Nat.card k'
  rw [Fintype.card_eq_nat_card]

/-- The lift of residue-field Frobenius generates the Galois group upstairs. -/
theorem frobenius_lift_pow
    (e : Gal(L'/K') ≃* Gal(l'/k')) (g : Gal(L'/K')) :
    ∃ i < Module.finrank k' l',
      frobeniusLiftResidue k' l' K' L' e ^ i = g := by
  obtain ⟨i, hi⟩ :=
    (FiniteField.bijective_frobeniusAlgEquivOfAlgebraic_pow k' l').2 (e g)
  refine ⟨i, i.isLt, ?_⟩
  apply e.injective
  rw [map_pow, residue_galois_lift]
  exact hi

end FrobeniusTransport

section UnramifiedFrobenius

open IsLocalRing

variable (R S K' L' : Type*)
  [CommRing R] [CommRing S] [Algebra R S]
  [IsDomain R] [IsDiscreteValuationRing R]
  [IsDomain S] [IsDiscreteValuationRing S]
  [Module.Finite R S] [Module.IsTorsionFree R S]
  [Field K'] [Field L'] [Algebra K' L']
  [Finite Gal(L'/K')] [MulSemiringAction Gal(L'/K') S]
  [IsGaloisGroup Gal(L'/K') R S]
  [(maximalIdeal S).LiesOver (maximalIdeal R)]
  [Algebra.IsUnramifiedAt R (maximalIdeal S)]
  [Fintype (ResidueField R)] [Finite (ResidueField S)]

/-- Arithmetic Frobenius in a finite unramified local Galois extension,
defined as the inverse image of finite-field Frobenius under Proposition
7.50(b)'s canonical reduction equivalence. -/
noncomputable def unramifiedFrobenius : Gal(L'/K') :=
  frobeniusLiftResidue
    (ResidueField R) (ResidueField S) K' L'
    (galois_unramified_local
      (R := R) (S := S) (G := Gal(L'/K')) (maximalIdeal R)
        (IsDiscreteValuationRing.not_a_field R)
        (IsDiscreteValuationRing.not_a_field S))

/-- Reduction sends local arithmetic Frobenius to finite-field Frobenius. -/
theorem unramifiedFrobenius_reduction :
    galois_unramified_local
        (R := R) (S := S) (G := Gal(L'/K')) (maximalIdeal R)
          (IsDiscreteValuationRing.not_a_field R)
          (IsDiscreteValuationRing.not_a_field S)
        (unramifiedFrobenius R S K' L') =
      FiniteField.frobeniusAlgEquivOfAlgebraic
        (ResidueField R) (ResidueField S) := by
  exact residue_galois_lift
    (ResidueField R) (ResidueField S) K' L' _

/-- On the residue field, local arithmetic Frobenius is the cardinality
power map. -/
theorem unramified_frobenius_reduction (x : ResidueField S) :
    galois_unramified_local
        (R := R) (S := S) (G := Gal(L'/K')) (maximalIdeal R)
          (IsDiscreteValuationRing.not_a_field R)
          (IsDiscreteValuationRing.not_a_field S)
        (unramifiedFrobenius R S K' L') x =
      x ^ Nat.card (ResidueField R) := by
  exact residue_frobenius_lift
    (ResidueField R) (ResidueField S) K' L' _ x

/-- Local arithmetic Frobenius generates the unramified local Galois group. -/
theorem unramified_frobenius_pow (g : Gal(L'/K')) :
    ∃ i < Module.finrank (ResidueField R) (ResidueField S),
      unramifiedFrobenius R S K' L' ^ i = g := by
  exact frobenius_lift_pow
    (ResidueField R) (ResidueField S) K' L' _ g

end UnramifiedFrobenius

section UnramifiedLift

open IsLocalRing

variable (A B : Type*) [CommRing A] [CommRing B]
  [HenselianLocalRing A] [HenselianLocalRing B]
  [Algebra A B] [IsLocalHom (algebraMap A B)]
  [IsDomain A] [IsDiscreteValuationRing A] [IsDomain B]
  [Module.IsTorsionFree A B] [Algebra.IsIntegral A B]
  [Finite (ResidueField A)]
  [CharP (ResidueField A) p]
  [IsAlgClosure (ResidueField A) (ResidueField B)]

include p

/-- Milne, Example 7.54 and Corollary 7.51: in an ambient extension whose
residue field is an algebraic closure, there is a finite formally unramified
stage of every positive residue degree `n`. -/
theorem formally_subalgebra_finrank :
    ∃ U : Subalgebra A B,
      Module.Finite A U ∧ Algebra.FormallyUnramified A U ∧
        Module.finrank (ResidueField A)
          (residueIntermediateField A B U) = n := by
  letI : IsAlgClosed (ResidueField B) :=
    IsAlgClosure.isAlgClosed (ResidueField A)
  let l := finiteResidueExtension (ResidueField A) p n
  let f : l →ₐ[ResidueField A] ResidueField B := IsAlgClosed.lift
  let E : IntermediateField (ResidueField A) (ResidueField B) :=
    f.fieldRange
  letI : Module.Finite (ResidueField A) E :=
    f.toLinearMap.finiteDimensional_range
  letI : Algebra.IsSeparable (ResidueField A) E :=
    AlgEquiv.Algebra.isSeparable (AlgEquiv.ofInjectiveField f)
  let U := unramifiedAdjoinIntermediate A B E
  refine ⟨U,
    unramified_adjoin_residue A B E,
    adjoin_intermediate_formally A B E,
    ?_⟩
  rw [residue_intermediate_adjoin]
  let e : l ≃ₐ[ResidueField A] E := AlgEquiv.ofInjectiveField f
  calc
    Module.finrank (ResidueField A) E =
        Module.finrank (ResidueField A) l := e.toLinearEquiv.finrank_eq.symm
    _ = n := residue_extension_finrank (ResidueField A) p n

section FractionField

variable (K L : Type*)
  [Field K] [Algebra A K] [IsFractionRing A K]
  [Field L] [Algebra B L] [IsFractionRing B L]
  [Algebra K L] [Algebra A L]
  [IsScalarTower A B L] [IsScalarTower A K L]

/-- Milne, Example 7.54, at the local-field level: the finite residue
extension of degree `n` lifts to a finite formally unramified valuation
algebra whose embedded fraction field is a cyclic Galois extension of degree
`n` over the base field. -/
theorem unramified_intermediate_cyclic
    [IsAdicComplete (maximalIdeal A) A] :
    ∃ U : Subalgebra A B,
      Module.Finite A U ∧ Algebra.FormallyUnramified A U ∧
        Module.finrank K
            (fractionFieldSubalgebra A B K L U) = n ∧
          IsGalois K (fractionFieldSubalgebra A B K L U) ∧
          IsCyclic Gal(fractionFieldSubalgebra A B K L U/K) ∧
          Polynomial.IsSplittingField K
            (fractionFieldSubalgebra A B K L U)
            (Polynomial.X ^ Nat.card (ResidueField A) ^ n - Polynomial.X) := by
  letI : IsAlgClosed (ResidueField B) :=
    IsAlgClosure.isAlgClosed (ResidueField A)
  let l := finiteResidueExtension (ResidueField A) p n
  let f : l →ₐ[ResidueField A] ResidueField B := IsAlgClosed.lift
  let E : IntermediateField (ResidueField A) (ResidueField B) :=
    f.fieldRange
  letI : Module.Finite (ResidueField A) E :=
    f.toLinearMap.finiteDimensional_range
  letI : Algebra.IsSeparable (ResidueField A) E :=
    AlgEquiv.Algebra.isSeparable (AlgEquiv.ofInjectiveField f)
  let U := unramifiedAdjoinIntermediate A B E
  let F := fractionFieldSubalgebra A B K L U
  let algUF : Algebra U F :=
    fractionIntermediateSubalgebra A B K L U
  letI : SMul U F := algUF.toSMul
  letI : Algebra U F := algUF
  letI : IsFractionRing U F :=
    fraction_intermediate_subalgebra A B K L U
  letI : Module.Finite A U :=
    unramified_adjoin_residue A B E
  letI : Algebra.FormallyUnramified A U :=
    adjoin_intermediate_formally A B E
  letI : IsDiscreteValuationRing U :=
    intermediate_discrete_valuation A B E
  letI : IsLocalRing U := subalgebra_ring_integral A B U
  letI : HenselianLocalRing U :=
    adjoin_intermediate_henselian A B E
  letI : FaithfulSMul A U :=
    (faithfulSMul_iff_algebraMap_injective A U).mpr <| by
      intro x y hxy
      apply FaithfulSMul.algebraMap_injective A B
      exact congrArg Subtype.val hxy
  letI : Algebra.IsIntegral A U := Algebra.IsIntegral.of_finite A U
  letI : IsLocalHom (algebraMap A U) :=
    Algebra.IsIntegral.isLocalHom A U
  letI : Algebra U B := U.val.toRingHom.toAlgebra
  letI : FaithfulSMul U B :=
    (faithfulSMul_iff_algebraMap_injective U B).mpr Subtype.val_injective
  letI : IsScalarTower A U B := IsScalarTower.of_algebraMap_eq' rfl
  letI : Algebra.IsIntegral U B := Algebra.IsIntegral.tower_top A
  letI : IsLocalHom (algebraMap U B) :=
    (algebraMap_isIntegral_iff.mpr
      (inferInstance : Algebra.IsIntegral U B)).isLocalHom
        Subtype.val_injective
  let residueMap := IsScalarTower.toAlgHom (ResidueField A)
    (ResidueField U) (ResidueField B)
  let residueEquiv : ResidueField U ≃ₐ[ResidueField A]
      residueIntermediateField A B U :=
    AlgEquiv.ofInjectiveField residueMap
  have hres : Module.finrank (ResidueField A) (ResidueField U) = n := by
    let e : l ≃ₐ[ResidueField A] E := AlgEquiv.ofInjectiveField f
    calc
      Module.finrank (ResidueField A) (ResidueField U) =
          Module.finrank (ResidueField A)
            (residueIntermediateField A B U) :=
        residueEquiv.toLinearEquiv.finrank_eq
      _ = Module.finrank (ResidueField A) E := by
        rw [residue_intermediate_adjoin]
      _ = Module.finrank (ResidueField A) l :=
        e.toLinearEquiv.finrank_eq.symm
      _ = n := residue_extension_finrank (ResidueField A) p n
  letI : IsScalarTower A U F := IsScalarTower.of_algebraMap_eq' <| by
    ext a
    change algebraMap A L a = algebraMap B L (algebraMap A B a)
    exact IsScalarTower.algebraMap_apply A B L a
  let residueExtensionEquiv :=
    FiniteField.algEquivExtension (ResidueField A) p n (ResidueField U) hres
  have hdegree : Module.finrank K F = n := by
    rw [formally_unramified_fraction A U K F]
    exact hres
  letI : Module.Finite K F := Module.finite_of_finrank_pos <| by
    rw [hdegree]
    exact NeZero.pos n
  letI : IsGalois (ResidueField A) (ResidueField U) :=
    IsGalois.of_algEquiv residueExtensionEquiv.symm
  letI : IsGalois K F :=
    fraction_formally_residue
      A U K F
  letI : Finite Gal(F/K) := IsGaloisGroup.finite Gal(F/K) K F
  letI : IsIntegralClosure U A F :=
    IsIntegralClosure.of_isIntegrallyClosed U A F
  letI : MulSemiringAction Gal(F/K) U :=
    IsIntegralClosure.MulSemiringAction A K F U
  letI : IsGaloisGroup Gal(F/K) A U :=
    IsGaloisGroup.of_isFractionRing Gal(F/K) A U K F
  let galoisEquivResidue :=
    galois_unramified_local
      (R := A) (S := U) (G := Gal(F/K)) (maximalIdeal A)
        (IsDiscreteValuationRing.not_a_field A)
        (IsDiscreteValuationRing.not_a_field U)
  letI : Finite (ResidueField U) :=
    Module.finite_of_finite (ResidueField A)
  letI : Fintype (ResidueField U) := Fintype.ofFinite (ResidueField U)
  have hresidueCyclic : IsCyclic Gal(ResidueField U/ResidueField A) :=
    FiniteField.instIsCyclicAlgEquivOfFinite
      (ResidueField A) (ResidueField U)
  have hcyclic : IsCyclic Gal(F/K) :=
    galoisEquivResidue.isCyclic.mpr hresidueCyclic
  have hresidueCard :
      Nat.card (ResidueField U) = Nat.card (ResidueField A) ^ n := by
    calc
      Nat.card (ResidueField U) =
          Nat.card (ResidueField A) ^
            Module.finrank (ResidueField A) (ResidueField U) :=
        Module.natCard_eq_pow_finrank
      _ = Nat.card (ResidueField A) ^ n := by rw [hres]
  have hsplittingField :
      Polynomial.IsSplittingField K F
        (Polynomial.X ^ Nat.card (ResidueField A) ^ n - Polynomial.X) := by
    rw [← hresidueCard]
    exact splitting_x_fraction A U K F
  exact ⟨U, inferInstance, inferInstance, hdegree, inferInstance, hcyclic,
    hsplittingField⟩

/-- The degree-only form of the local lift in Example 7.54. -/
theorem unramified_intermediate_finrank
    [IsAdicComplete (maximalIdeal A) A] :
    ∃ U : Subalgebra A B,
      Module.Finite A U ∧ Algebra.FormallyUnramified A U ∧
        Module.finrank K
          (fractionFieldSubalgebra A B K L U) = n := by
  obtain ⟨U, hUfinite, hUunramified, hdegree, _⟩ :=
    unramified_intermediate_cyclic
      (p := p) (n := n) A B K L
  exact ⟨U, hUfinite, hUunramified, hdegree⟩

end FractionField

end UnramifiedLift

end

end Submission.NumberTheory.Milne
