import Mathlib.RingTheory.SimpleModule.Basic

/-!
# Chapter IV, Proposition 1.4

A module generated by a family of simple submodules has complements made from that
same family.  The indexed family may contain repetitions, so the conclusion selects a
set of distinct submodules from its range.
-/

namespace Towers.CField.SAlgebr

open Set

private theorem s_indep_compl
    {L : Type*} [CompleteLattice L] [IsModularLattice L] [IsCompactlyGenerated L]
    (generators : Set L) (hAtom : ∀ a ∈ generators, IsAtom a)
    (hTop : sSup generators = ⊤) (b : L) :
    ∃ s : Set L, s ⊆ generators ∧ sSupIndep s ∧ IsCompl b (sSup s) := by
  have zorn := zorn_subset
    (S := {s : Set L | s ⊆ generators ∧ sSupIndep s ∧ Disjoint b (sSup s)})
    fun c hc hchain =>
      ⟨⋃₀ c,
        ⟨fun a ⟨s, hs, ha⟩ => (hc hs).1 ha,
          iSupIndep_sUnion_of_directed hchain.directedOn fun s hs => (hc hs).2.1,
          ?_⟩,
        fun _ => Set.subset_sUnion_of_mem⟩
  swap
  · rw [sSup_sUnion, ← sSup_image, DirectedOn.disjoint_sSup_right]
    · rintro _ ⟨s, hs, rfl⟩
      exact (hc hs).2.2
    · rw [directedOn_image]
      exact hchain.directedOn.mono @fun s t => sSup_le_sSup
  simp_rw [maximal_subset_iff] at zorn
  obtain ⟨s, ⟨hsGen, hsIndep, hbDisj⟩, hsMax⟩ := zorn
  refine ⟨s, hsGen, hsIndep, ⟨hbDisj, ?_⟩⟩
  rw [codisjoint_iff]
  apply top_unique
  rw [← hTop, sSup_le_iff]
  intro a ha
  have haAtom := hAtom a ha
  rw [← inf_eq_left]
  refine (haAtom.le_iff.mp inf_le_left).resolve_left fun hEq => haAtom.1 ?_
  rw [← hEq, eq_comm, inf_eq_left]
  refine (le_sSup ?_).trans le_sup_right
  rw [← disjoint_iff] at hEq
  have haDisj : Disjoint a (sSup s) := hEq.mono_right le_sup_right
  rw [hsMax ⟨?_, ?_, ?_⟩ Set.subset_union_left]
  · exact Set.mem_union_right _ (Set.mem_singleton _)
  · intro x hx
    rw [Set.mem_union, Set.mem_singleton_iff] at hx
    obtain hx | rfl := hx
    · exact hsGen hx
    · exact ha
  · intro x hx
    rw [Set.mem_union, Set.mem_singleton_iff] at hx
    obtain rfl | hxa := eq_or_ne x a
    · simp only [Set.mem_singleton, Set.insert_diff_of_mem, Set.union_singleton]
      exact hEq.mono_right ((sSup_le_sSup Set.diff_subset).trans le_sup_right)
    · have hdiff : (s ∪ {a}) \ {x} = s \ {x} ∪ {a} := by
        simp only [Set.union_singleton]
        rw [Set.insert_diff_of_notMem]
        rw [Set.mem_singleton_iff]
        exact Ne.symm hxa
      rw [hdiff, sSup_union, sSup_singleton]
      apply
        (hsIndep (hx.resolve_right hxa)).disjoint_sup_right_of_disjoint_sup_left
          (haDisj.mono_right _).symm
      rw [← sSup_insert, Set.insert_diff_singleton, Set.insert_eq_of_mem
        (hx.resolve_right hxa)]
  · rw [sSup_union, sSup_singleton]
    exact hbDisj.disjoint_sup_right_of_disjoint_sup_left hEq.symm

variable {R M ι : Type*} [Ring R] [AddCommGroup M] [Module R M]

/-- Proposition IV.1.4: if a family of simple submodules generates `M`, every submodule
has a complement which is a direct sum of distinct members of that family. -/
theorem complement_simple_generators (S : ι → Submodule R M)
    (hS : ∀ i, IsSimpleModule R (S i)) (hTop : ⨆ i, S i = ⊤)
    (W : Submodule R M) :
    ∃ T : Set (Submodule R M),
      T ⊆ Set.range S ∧ sSupIndep T ∧ IsCompl W (sSup T) := by
  apply s_indep_compl (Set.range S) _ _ W
  · rintro A ⟨i, rfl⟩
    exact isSimpleModule_iff_isAtom.mp (hS i)
  · simpa [sSup_range] using hTop

/-- The semisimplicity consequence of Proposition IV.1.4, in Mathlib's standard form. -/
theorem semisimple_i_simple (S : ι → Submodule R M)
    (hS : ∀ i, IsSimpleModule R (S i)) (hTop : ⨆ i, S i = ⊤) :
    IsSemisimpleModule R M := by
  apply isSemisimpleModule_of_isSemisimpleModule_submodule' (p := S) ?_ hTop
  intro i
  letI : IsSimpleModule R (S i) := hS i
  infer_instance

end Towers.CField.SAlgebr
