import Towers.NumberTheory.Quadratic.PrimeFactorization
import Towers.NumberTheory.ClassGroup.MinkowskiClassBound
import Towers.NumberTheory.Quadratic.QuadraticUnitExamples

attribute [-instance] DivisionRing.toRatAlgebra
attribute [-instance] QuadraticAlgebra.instAddMonoid
attribute [-instance] QuadraticAlgebra.instAddCommMonoid
attribute [-instance] QuadraticAlgebra.instAddGroup
attribute [-instance] QuadraticAlgebra.instAddCommGroup
attribute [-instance] QuadraticAlgebra.instAddCommMonoidWithOne
attribute [-instance] QuadraticAlgebra.instAddCommGroupWithOne
attribute [-instance] QuadraticAlgebra.instNonUnitalNonAssocSemiring
attribute [-instance] QuadraticAlgebra.instNonAssocSemiring
attribute [-instance] QuadraticAlgebra.instCommSemiring
attribute [-instance] QuadraticAlgebra.instModule
attribute [-instance] LieAlgebra.ofAssociativeAlgebra

/-!
# Class Field Theory, Example 0.6: the field Q(sqrt(6))

This file proves the class-number-one assertion in Example 0.6.  The Minkowski bound is
strictly between `2` and `3`, and the unique prime that must be checked is the ramified prime
above `2`; it is generated by `2 + sqrt(6)`.  We also record the norm-one unit `5 + 2 sqrt(6)`
and the elementary congruence obstruction to a unit of norm `-1`.
-/

namespace Towers.CField.Examples

open Ideal
open Towers.NumberTheory
open scoped NumberField Real

noncomputable section

/-- The coordinate model of `Q(sqrt(6))`. -/
abbrev SqrtSixField := QFModel 6

/-- The ring `Z[sqrt(6)]`, which is the full ring of integers of `Q(sqrt(6))`. -/
abbrev SqrtSixIntegers := QOrd 6 0

private def sqrtSixEmbedding : SqrtSixIntegers →+* SqrtSixField where
  toFun z := ⟨(z.re : ℚ), (z.im : ℚ)⟩
  map_zero' := by apply QuadraticAlgebra.ext <;> norm_num
  map_one' := by
    apply QuadraticAlgebra.ext <;>
      norm_num [QuadraticAlgebra.re_one, QuadraticAlgebra.im_one]
  map_add' x y := by
    apply QuadraticAlgebra.ext <;>
      simp only [QuadraticAlgebra.re_add, QuadraticAlgebra.im_add] <;> norm_cast
  map_mul' x y := by
    apply QuadraticAlgebra.ext
    · simp only [QuadraticAlgebra.re_mul]
      push_cast
      ring
    · simp only [QuadraticAlgebra.im_mul]
      push_cast
      ring

private theorem sqrt_six_injective :
    Function.Injective sqrtSixEmbedding := by
  intro x y hxy
  apply QuadraticAlgebra.ext
  · exact Rat.intCast_injective (congrArg QuadraticAlgebra.re hxy)
  · exact Rat.intCast_injective (congrArg QuadraticAlgebra.im hxy)

private local instance : Algebra SqrtSixIntegers SqrtSixField :=
  sqrtSixEmbedding.toAlgebra

private local instance : IsScalarTower ℤ SqrtSixIntegers SqrtSixField :=
  IsScalarTower.of_algebraMap_eq' rfl

private theorem sqrtSix_nonsquare :
    ∀ r : ℚ, r ^ 2 ≠ ((6 : ℤ) : ℚ) + 0 * r := by
  intro r hr
  have hsquare : IsSquare (6 : ℚ) := ⟨r, by simpa [pow_two] using hr.symm⟩
  norm_num at hsquare

private local instance : Fact (∀ r : ℚ, r ^ 2 ≠ ((6 : ℤ) : ℚ) + 0 * r) :=
  ⟨sqrtSix_nonsquare⟩

private def sqrtSixBasis : Module.Basis (Fin 2) ℚ SqrtSixField :=
  QuadraticAlgebra.basis (6 : ℚ) 0

private local instance : Module.Free ℚ SqrtSixField :=
  Module.Free.of_basis sqrtSixBasis

private local instance : Module.Finite ℚ SqrtSixField :=
  Module.Finite.of_basis sqrtSixBasis

private local instance : NumberField SqrtSixField :=
  NumberField.of_module_finite ℚ SqrtSixField

@[reducible] private def sqrtSixClosure :
    IsIntegralClosure SqrtSixIntegers ℤ SqrtSixField where
  algebraMap_injective := sqrt_six_injective
  isIntegral_iff {x} := by
    have hm : Squarefree (6 : ℤ) := by
      rw [← Int.squarefree_natAbs]
      change Squarefree (6 : ℕ)
      rw [show (6 : ℕ) = 2 * 3 by norm_num, Nat.squarefree_mul (by norm_num)]
      exact ⟨Nat.prime_two.squarefree, Nat.prime_three.squarefree⟩
    rw [QFModel.integral_integer_coordinates 6 hm (by norm_num)]
    constructor
    · rintro ⟨a, b, ha, hb⟩
      refine ⟨(⟨a, b⟩ : SqrtSixIntegers), ?_⟩
      apply QuadraticAlgebra.ext
      · exact ha.symm
      · exact hb.symm
    · rintro ⟨y, rfl⟩
      exact ⟨y.re, y.im, rfl, rfl⟩

private local instance : IsIntegralClosure SqrtSixIntegers ℤ SqrtSixField :=
  sqrtSixClosure

private lemma quadratic_algebra_formula (A B : ℤ)
    (x : QuadraticAlgebra ℤ A B) :
    Algebra.trace ℤ (QuadraticAlgebra ℤ A B) x = 2 * x.re + B * x.im := by
  have hmat : Algebra.leftMulMatrix (QuadraticAlgebra.basis A B) x =
      !![x.re, A * x.im; x.im, x.re + B * x.im] := by
    ext i j
    fin_cases i <;> fin_cases j <;>
      simp [Algebra.leftMulMatrix_eq_repr_mul, QuadraticAlgebra.basis,
        QuadraticAlgebra.linearEquivTuple, QuadraticAlgebra.equivProd,
        QuadraticAlgebra.re_mul, QuadraticAlgebra.im_mul]
  rw [Algebra.trace_eq_matrix_trace (QuadraticAlgebra.basis A B), hmat,
    Matrix.trace_fin_two_of]
  ring

private theorem quadratic_discr_basis (A B : ℤ) :
    Algebra.discr ℤ (QuadraticAlgebra.basis A B) = B ^ 2 + 4 * A := by
  rw [Algebra.discr_def]
  have hmat : Algebra.traceMatrix ℤ (QuadraticAlgebra.basis A B) =
      !![2, B; B, 2 * A + B ^ 2] := by
    ext i j
    fin_cases i <;> fin_cases j
    all_goals
      simp [Algebra.traceMatrix_apply, Algebra.traceForm_apply,
        quadratic_algebra_formula, QuadraticAlgebra.basis,
        QuadraticAlgebra.linearEquivTuple, QuadraticAlgebra.equivProd]
    ring
  rw [hmat, Matrix.det_fin_two_of]
  ring

private theorem sqrtSix_discr : NumberField.discr SqrtSixField = 24 := by
  let eRing : 𝓞 SqrtSixField ≃+* SqrtSixIntegers :=
    @NumberField.RingOfIntegers.equiv SqrtSixField inferInstance
      SqrtSixIntegers inferInstance inferInstance sqrtSixClosure
  let eAlg : SqrtSixIntegers ≃ₐ[ℤ] 𝓞 SqrtSixField :=
    AlgEquiv.ofRingEquiv (f := eRing.symm) (fun z => by simp)
  let b : Module.Basis (Fin 2) ℤ (𝓞 SqrtSixField) :=
    (QuadraticAlgebra.basis (6 : ℤ) 0).map eAlg.toLinearEquiv
  calc
    NumberField.discr SqrtSixField = Algebra.discr ℤ b :=
      (NumberField.discr_eq_discr SqrtSixField b).symm
    _ = Algebra.discr ℤ (QuadraticAlgebra.basis (6 : ℤ) 0) := by
      simpa [b] using
        (Algebra.discr_eq_discr_of_algEquiv
          (QuadraticAlgebra.basis (6 : ℤ) 0 : Fin 2 → SqrtSixIntegers) eAlg).symm
    _ = 24 := by norm_num [quadratic_discr_basis]

private theorem sqrtSix_finrank : Module.finrank ℚ SqrtSixField = 2 := by
  rw [Module.finrank_eq_card_basis sqrtSixBasis]
  simp

private theorem sqrt_six_finrank :
    @Module.finrank ℚ SqrtSixField inferInstance inferInstance
      (@Algebra.toModule ℚ SqrtSixField inferInstance inferInstance
        (@DivisionRing.toRatAlgebra SqrtSixField inferInstance inferInstance)) = 2 := by
  have hAlgebra :
      (inferInstance : Algebra ℚ SqrtSixField) =
        @DivisionRing.toRatAlgebra SqrtSixField inferInstance inferInstance :=
    Subsingleton.elim _ _
  rw [← hAlgebra]
  exact sqrtSix_finrank

private abbrev sqrtSixFinrank : ℕ :=
  @Module.finrank ℚ SqrtSixField inferInstance inferInstance
    (@Algebra.toModule ℚ SqrtSixField inferInstance inferInstance
      (@DivisionRing.toRatAlgebra SqrtSixField inferInstance inferInstance))

private theorem sqrt_six_nr :
    NumberField.InfinitePlace.nrComplexPlaces SqrtSixField = 0 := by
  have hcard := NumberField.InfinitePlace.card_add_two_mul_card_eq_rank SqrtSixField
  have hcard2 : NumberField.InfinitePlace.nrRealPlaces SqrtSixField +
      2 * NumberField.InfinitePlace.nrComplexPlaces SqrtSixField = 2 :=
    hcard.trans sqrt_six_finrank
  have hcomplex_le : NumberField.InfinitePlace.nrComplexPlaces SqrtSixField ≤ 1 := by omega
  have hsign := NumberField.sign_discr (K := SqrtSixField)
  rw [sqrtSix_discr] at hsign
  interval_cases hcomplex : NumberField.InfinitePlace.nrComplexPlaces SqrtSixField
  · rfl
  · norm_num at hsign

private theorem sqrt_minkowski_floor :
    ⌊(4 / Real.pi) ^ NumberField.InfinitePlace.nrComplexPlaces SqrtSixField *
      ((Nat.factorial sqrtSixFinrank : ℝ) /
        (sqrtSixFinrank : ℝ) ^ sqrtSixFinrank *
        Real.sqrt |NumberField.discr SqrtSixField|)⌋₊ = 2 := by
  have hrank : sqrtSixFinrank = 2 := sqrt_six_finrank
  rw [sqrt_six_nr, hrank, sqrtSix_discr]
  norm_num
  rw [Nat.floor_eq_iff (by positivity)]
  have hsqrt_sq : (Real.sqrt (24 : ℝ)) ^ 2 = 24 := Real.sq_sqrt (by norm_num)
  have hsqrt_nonneg : 0 ≤ Real.sqrt (24 : ℝ) := Real.sqrt_nonneg _
  constructor <;> nlinarith

/-- The ramified ideal `(2, sqrt(6))` is generated by `2 + sqrt(6)`. -/
theorem sqrt_six_span :
    QOrd.rootIdeal 6 0 2 0 =
      span {((2 : SqrtSixIntegers) + QuadraticAlgebra.omega)} := by
  apply le_antisymm
  · rw [QOrd.rootIdeal, span_le]
    intro z hz
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hz
    rcases hz with rfl | rfl
    · apply Ideal.mem_span_singleton.mpr
      refine ⟨QuadraticAlgebra.omega - (2 : SqrtSixIntegers), ?_⟩
      apply QuadraticAlgebra.ext <;>
        simp [QuadraticAlgebra.re_mul, QuadraticAlgebra.im_mul,
          QuadraticAlgebra.re_ofNat, QuadraticAlgebra.im_ofNat]
    · change QuadraticAlgebra.omega ∈ span
          {((2 : SqrtSixIntegers) + QuadraticAlgebra.omega)}
      apply Ideal.mem_span_singleton.mpr
      refine ⟨(3 : SqrtSixIntegers) - QuadraticAlgebra.omega, ?_⟩
      apply QuadraticAlgebra.ext <;>
        simp [QuadraticAlgebra.re_mul, QuadraticAlgebra.im_mul,
          QuadraticAlgebra.re_ofNat, QuadraticAlgebra.im_ofNat]
  · rw [span_singleton_le_iff_mem, QOrd.rootIdeal]
    apply add_mem
    · exact subset_span (Set.mem_insert _ _)
    · simpa using
        (subset_span (Set.mem_insert_iff.mpr (Or.inr (Set.mem_singleton _))) :
          QuadraticAlgebra.omega ∈ span
            {((2 : SqrtSixIntegers)), QuadraticAlgebra.omega - (0 : SqrtSixIntegers)})

/-- The prime ideal above `2`, transported to the ring of integers. -/
noncomputable def sqrtSixAbove : Ideal (𝓞 SqrtSixField) :=
  let eRing : 𝓞 SqrtSixField ≃+* SqrtSixIntegers :=
    @NumberField.RingOfIntegers.equiv SqrtSixField inferInstance
      SqrtSixIntegers inferInstance inferInstance sqrtSixClosure
  (QOrd.rootIdeal 6 0 2 0).comap eRing

private theorem sqrt_six_above : sqrtSixAbove.IsPrime := by
  let eRing : 𝓞 SqrtSixField ≃+* SqrtSixIntegers :=
    @NumberField.RingOfIntegers.equiv SqrtSixField inferInstance
      SqrtSixIntegers inferInstance inferInstance sqrtSixClosure
  have hprime : (QOrd.rootIdeal 6 0 2 0).IsPrime :=
    (QOrd.ramifies_four_add 1).1
  exact hprime.comap eRing

private theorem sqrt_six_sq :
    sqrtSixAbove ^ 2 = span {(2 : 𝓞 SqrtSixField)} := by
  let eRing : 𝓞 SqrtSixField ≃+* SqrtSixIntegers :=
    @NumberField.RingOfIntegers.equiv SqrtSixField inferInstance
      SqrtSixIntegers inferInstance inferInstance sqrtSixClosure
  apply eRing.idealComapOrderIso.symm.injective
  simp only [RingEquiv.idealComapOrderIso_symm_apply, Ideal.map_pow]
  have hmap : Ideal.map eRing sqrtSixAbove =
      QOrd.rootIdeal 6 0 2 0 := by
    exact Ideal.map_comap_eq_self_of_equiv eRing _
  have hram :
      QOrd.rootIdeal 6 0 2 0 * QOrd.rootIdeal 6 0 2 0 =
        span {(2 : SqrtSixIntegers)} := by
    convert (QOrd.ramifies_four_add 1).2 using 1
  rw [hmap, pow_two, hram]
  rw [Ideal.map_span, Set.image_singleton, map_ofNat]

private theorem sqrt_six_primes :
    sqrtSixAbove ∈ primesOver (span {(2 : ℤ)}) (𝓞 SqrtSixField) := by
  letI : (span {(2 : ℤ)}).IsMaximal :=
    ((Ideal.span_singleton_prime (by norm_num : (2 : ℤ) ≠ 0)).mpr
      (by norm_num : Prime (2 : ℤ))).isMaximal (by norm_num)
  refine ⟨sqrt_six_above, ?_⟩
  rw [Ideal.liesOver_iff_dvd_map sqrt_six_above.ne_top]
  refine ⟨sqrtSixAbove, ?_⟩
  rw [Ideal.map_span, Set.image_singleton, map_ofNat]
  simpa [pow_two] using sqrt_six_sq.symm

private theorem sqrt_six_principal :
    sqrtSixAbove.IsPrincipal := by
  let eRing : 𝓞 SqrtSixField ≃+* SqrtSixIntegers :=
    @NumberField.RingOfIntegers.equiv SqrtSixField inferInstance
      SqrtSixIntegers inferInstance inferInstance sqrtSixClosure
  have hprincipal : (QOrd.rootIdeal 6 0 2 0).IsPrincipal := by
    rw [sqrt_six_span]
    exact ⟨_, rfl⟩
  have hmap : Ideal.map eRing.symm (QOrd.rootIdeal 6 0 2 0) =
      sqrtSixAbove := by
    exact Ideal.map_symm eRing
  rw [← hmap]
  exact hprincipal.map_ringHom eRing.symm

/-- Example 0.6: `Q(sqrt(6))` has class number one. -/
theorem sqrt_six_number :
    NumberField.classNumber SqrtSixField = 1 := by
  rw [NumberField.classNumber_eq_one_iff]
  apply
    RingOfIntegers.isPrincipalIdealRing_of_isPrincipal_of_pow_le_of_mem_primesOver_of_mem_Icc
  intro p hp hpprime P hP _
  have hp_two : p = 2 := by
    rw [sqrt_minkowski_floor] at hp
    have hp_le : p ≤ 2 := (Finset.mem_Icc.mp hp).2
    exact le_antisymm hp_le hpprime.two_le
  subst p
  letI : (span {(2 : ℤ)}).IsMaximal :=
    ((Ideal.span_singleton_prime (by norm_num : (2 : ℤ) ≠ 0)).mpr
      (by norm_num : Prime (2 : ℤ))).isMaximal (by norm_num)
  have hPprime : Prime P :=
    Ideal.prime_of_mem_primesOver (by simp) hP
  have hPdvd : P ∣ span {(2 : 𝓞 SqrtSixField)} := by
    have := (Ideal.liesOver_iff_dvd_map hP.1.ne_top).mp hP.2
    simpa [Ideal.map_span, Set.image_singleton, map_ofNat] using this
  rw [← sqrt_six_sq] at hPdvd
  have hPdvdQ : P ∣ sqrtSixAbove := hPprime.dvd_of_dvd_pow hPdvd
  have hle : sqrtSixAbove ≤ P := Ideal.dvd_iff_le.mp hPdvdQ
  have hQ0 : sqrtSixAbove ≠ ⊥ :=
    Ideal.ne_bot_of_mem_primesOver (by simp) sqrt_six_primes
  have hEq : P = sqrtSixAbove :=
    (sqrt_six_above.isMaximal hQ0).eq_of_le hP.1.ne_top hle |>.symm
  rw [hEq]
  exact sqrt_six_principal

/-- The unit displayed in the class-number discussion has norm one. -/
theorem six_fundamental_norm :
    QuadraticAlgebra.norm (⟨5, 2⟩ : SqrtSixIntegers) = 1 := by
  norm_num [QuadraticAlgebra.norm_def]

/-- The element `5 + 2 sqrt(6)` is a unit of `Z[sqrt(6)]`. -/
theorem sqrt_six_fundamental :
    IsUnit (⟨5, 2⟩ : SqrtSixIntegers) := by
  rw [QuadraticAlgebra.isUnit_iff_norm_isUnit, six_fundamental_norm]
  exact isUnit_one

/-- The negative Pell equation `x^2 - 6y^2 = -1` has no integral solution. -/
theorem sqrt_six_pell (x y : ℤ) :
    x ^ 2 - 6 * y ^ 2 ≠ -1 := by
  intro h
  have hmod := congrArg (fun z : ℤ => (z : ZMod 3)) h
  push_cast at hmod
  have hsix : (6 : ZMod 3) = 0 := by decide
  have hneg : (-1 : ZMod 3) = 2 := by decide
  rw [hsix, zero_mul, sub_zero, hneg] at hmod
  have hnonsquare : ∀ z : ZMod 3, z ^ 2 ≠ 2 := by decide
  exact hnonsquare x hmod

/-- Consequently no element of `Z[sqrt(6)]` has norm `-1`; in particular no unit does. -/
theorem sqrt_six_ne (u : SqrtSixIntegers) :
    QuadraticAlgebra.norm u ≠ -1 := by
  intro h
  apply sqrt_six_pell u.re u.im
  rw [QuadraticAlgebra.norm_def] at h
  nlinarith

end

end Towers.CField.Examples
