import Submission.NumberTheory.Completions.FractionRingBridge
import Submission.NumberTheory.Completions.DifferentTransport

/-!
# Trace-dual base change into a completed total quotient ring

An integral basis identifies the scalar extension of the integral lattice
inside `F ⊗[K] L`.  The fraction-ring tensor equivalence carries that lattice
to the integral completed tensor ring inside its common-denominator
localization.  Transporting the trace pairing then identifies its trace dual
with the completed image of the global trace dual.
-/

namespace Submission.NumberTheory.Milne

open Module Submodule nonZeroDivisors
open scoped TensorProduct

noncomputable section

universe u

variable {R S K L C F Q : Type u}
  [CommRing R] [CommRing S] [Field K] [Field L]
  [Algebra R S] [Algebra R K] [IsFractionRing R K]
  [Algebra S L] [Algebra R L] [Algebra K L]
  [IsScalarTower R S L] [IsScalarTower R K L]
  [IsLocalization (Algebra.algebraMapSubmonoid S R⁰) L]
  [CommRing C] [IsDomain C] [Algebra R C]
  [Field F] [Algebra C F] [IsFractionRing C F]
  [Algebra R F] [IsScalarTower R C F]
  [Algebra K F] [IsScalarTower R K F]
  [CommRing Q] [Algebra (C ⊗[R] S) Q]
  [Algebra C Q] [IsScalarTower C (C ⊗[R] S) Q]
  [Algebra F Q] [IsScalarTower C F Q]
  [IsLocalization
    (Algebra.algebraMapSubmonoid (C ⊗[R] S) C⁰) Q]
  [FiniteDimensional K L] [Algebra.IsSeparable K L]

section IntegralLattice

variable {ι : Type*} [Finite ι]

omit [IsDomain C] [FiniteDimensional K L] [Algebra.IsSeparable K L]
  [Finite ι] in
/-- The fraction-ring tensor equivalence carries the lattice generated by
the scalar-extended integral basis to the completed integral tensor ring. -/
theorem scalar_fraction_span
    (b : Basis ι R S) :
    let e := scalarFractionTensor
      (R := R) (S := S) (K := K) (L := L)
      (C := C) (F := F) (Q := Q)
    (Submodule.span C
      (Set.range
        (Algebra.TensorProduct.basis F
          (b.localizationLocalization K R⁰ L)))).map
        (e.toLinearEquiv.restrictScalars C).toLinearMap =
      (1 : Submodule (C ⊗[R] S) Q).restrictScalars C := by
  classical
  let B := C ⊗[R] S
  let e := scalarFractionTensor
    (R := R) (S := S) (K := K) (L := L)
    (C := C) (F := F) (Q := Q)
  let eC : (F ⊗[K] L) ≃ₗ[C] Q := e.toLinearEquiv.restrictScalars C
  let g : B →ₗ[C] Q := (Algebra.linearMap B Q).restrictScalars C
  let bK : Basis ι K L := b.localizationLocalization K R⁰ L
  let bC : Basis ι C B := Algebra.TensorProduct.basis C b
  have himage :
      eC '' Set.range (Algebra.TensorProduct.basis F bK) =
        g '' Set.range bC := by
    ext q
    constructor
    · rintro ⟨_, ⟨i, rfl⟩, rfl⟩
      refine ⟨bC i, ⟨i, rfl⟩, ?_⟩
      change algebraMap (C ⊗[R] S) Q
          (Algebra.TensorProduct.basis C b i) =
        e (Algebra.TensorProduct.basis F bK i)
      rw [Algebra.TensorProduct.basis_apply,
        Algebra.TensorProduct.basis_apply,
        Basis.localizationLocalization_apply]
      rw [scalar_fraction_tmul]
      simp
    · rintro ⟨_, ⟨i, rfl⟩, rfl⟩
      refine ⟨Algebra.TensorProduct.basis F bK i, ⟨i, rfl⟩, ?_⟩
      change e (Algebra.TensorProduct.basis F bK i) =
        algebraMap (C ⊗[R] S) Q
          (Algebra.TensorProduct.basis C b i)
      rw [Algebra.TensorProduct.basis_apply,
        Basis.localizationLocalization_apply,
        Algebra.TensorProduct.basis_apply]
      rw [scalar_fraction_tmul]
      simp
  calc
    (Submodule.span C
        (Set.range (Algebra.TensorProduct.basis F bK))).map eC.toLinearMap =
        Submodule.span C
          (eC '' Set.range (Algebra.TensorProduct.basis F bK)) :=
      Submodule.map_span _ _
    _ = Submodule.span C (g '' Set.range bC) := by rw [himage]
    _ = (Submodule.span C (Set.range bC)).map g :=
      (Submodule.map_span _ _).symm
    _ = (⊤ : Submodule C B).map g := by rw [bC.span_eq]
    _ = (1 : Submodule B Q).restrictScalars C := by
      ext q
      simp only [Submodule.mem_map, Submodule.mem_top, true_and,
        Submodule.restrictScalars_mem]
      constructor
      · rintro ⟨y, hy⟩
        exact Submodule.mem_one.mpr ⟨y, hy⟩
      · intro hq
        obtain ⟨y, hy⟩ := Submodule.mem_one.mp hq
        exact ⟨y, hy⟩

end IntegralLattice

section TraceDual

variable {ι : Type*} [Finite ι]

omit [IsDomain C] in
/-- The trace dual of the completed integral tensor lattice is the
`C`-span of the image of the global trace dual under the completed tensor
embedding.  This is the basis-level `hdual` used in product recovery. -/
theorem form_dual_submodule
    (b : Basis ι R S) :
    let e := scalarFractionTensor
      (R := R) (S := S) (K := K) (L := L)
      (C := C) (F := F) (Q := Q)
    (Algebra.traceForm F Q).dualSubmodule
        ((1 : Submodule (C ⊗[R] S) Q).restrictScalars C) =
      Submodule.span C
        ((fun x : L => e ((1 : F) ⊗ₜ[K] x)) ''
          (Submodule.traceDual R K (1 : Submodule S L) : Set L)) := by
  classical
  let e := scalarFractionTensor
    (R := R) (S := S) (K := K) (L := L)
    (C := C) (F := F) (Q := Q)
  let eC : (F ⊗[K] L) ≃ₗ[C] Q := e.toLinearEquiv.restrictScalars C
  let bK : Basis ι K L := b.localizationLocalization K R⁰ L
  let N : Submodule C (F ⊗[K] L) :=
    Submodule.span C (Set.range (Algebra.TensorProduct.basis F bK))
  have hN : N.map eC.toLinearMap =
      (1 : Submodule (C ⊗[R] S) Q).restrictScalars C :=
    scalar_fraction_span
      (R := R) (S := S) (K := K) (L := L)
      (C := C) (F := F) (Q := Q) b
  have hbasis :
      (Algebra.traceForm F (F ⊗[K] L)).dualSubmodule N =
        Submodule.span C
          ((fun x : L => (1 : F) ⊗ₜ[K] x) ''
            (Submodule.traceDual R K (1 : Submodule S L) : Set L)) :=
    dual_submodule_image
      R S K L F C b
  have htransport := dual_submodule_alg e N
  rw [hN] at htransport
  calc
    (Algebra.traceForm F Q).dualSubmodule
        ((1 : Submodule (C ⊗[R] S) Q).restrictScalars C) =
        ((Algebra.traceForm F (F ⊗[K] L)).dualSubmodule N).map
          eC.toLinearMap := htransport.symm
    _ = (Submodule.span C
          ((fun x : L => (1 : F) ⊗ₜ[K] x) ''
            (Submodule.traceDual R K (1 : Submodule S L) : Set L))).map
          eC.toLinearMap := by rw [hbasis]
    _ = Submodule.span C
        (eC '' ((fun x : L => (1 : F) ⊗ₜ[K] x) ''
          (Submodule.traceDual R K (1 : Submodule S L) : Set L))) :=
      Submodule.map_span _ _
    _ = Submodule.span C
        ((fun x : L => e ((1 : F) ⊗ₜ[K] x)) ''
          (Submodule.traceDual R K (1 : Submodule S L) : Set L)) := by
      rw [Set.image_image]
      rfl

end TraceDual

end

end Submission.NumberTheory.Milne
