import Towers.ClassField.NormLimitation.FiniteQuotients
import Towers.ClassField.NormLimitation.PrimeIndexSupergroup
import Towers.ClassField.NormLimitation.ExistenceStatement
import Towers.ClassField.NormLimitation.SubgroupQuotientMap
import Towers.ClassField.NormLimitation.OfGlobalReciprocity
import Towers.ClassField.NormLimitation.IsUnitOutside
import Towers.ClassField.NormLimitation.SubgroupIntermediate
import Towers.ClassField.NormLimitation.ExistenceInterface
import Towers.ClassField.NormLimitation.CoreDefinitions
import Towers.ClassField.NormLimitation.OpenCoreStatement
import Towers.ClassField.NormLimitation.KummerCoreStatement
import Towers.ClassField.NormLimitation.PlaceSelection
import Towers.ClassField.NormLimitation.ExponentGroupAssembly
import Towers.ClassField.NormLimitation.OpenCore
import Towers.ClassField.NormLimitation.KummerCore
import Towers.ClassField.NormLimitation.ExponentGroupReciprocity
import Towers.ClassField.NormLimitation.NormLimitationBridge
import Towers.ClassField.NormLimitation.NormLimitation
import Towers.ClassField.NormLimitation.ReductionData
import Towers.ClassField.NormLimitation.PrimeReduction
import Towers.ClassField.NormLimitation.GlobalReduction

/-! # Chapter VII, Section 9: the existence theorem -/
