import Mathlib.RingTheory.SimpleModule.Basic

/-!
# Milne, Class Field Theory, Corollaries IV.1.5 and IV.1.6

These corollaries characterize semisimple modules and record their closure
under sums, submodules, and quotients.
-/

namespace Submission.CField.SAlgebr

universe u v w

variable {R : Type u} {M : Type v} [Ring R] [AddCommGroup M] [Module R M]

/-- **Corollary IV.1.5, (a) iff (b).** A module is semisimple exactly when it
is generated by its simple submodules. -/
theorem semisimple_simples_top :
    IsSemisimpleModule R M ↔
      sSup {S : Submodule R M | IsSimpleModule R S} = ⊤ :=
  sSup_simples_eq_top_iff_isSemisimpleModule.symm

/-- **Corollary IV.1.5, (a) iff (c).** A module is semisimple exactly when its
submodule lattice is complemented. -/
theorem semisimple_complemented_lattice :
    IsSemisimpleModule R M ↔ ComplementedLattice (Submodule R M) :=
  isSemisimpleModule_iff R M

/-- Elementwise form of the complement characterization in Corollary IV.1.5. -/
theorem semisimple_every_complement :
    IsSemisimpleModule R M ↔
      ∀ W : Submodule R M, ∃ W' : Submodule R M, IsCompl W W' := by
  constructor
  · intro _ W
    exact exists_isCompl W
  · intro h
    apply (isSemisimpleModule_iff R M).mpr
    exact ⟨h⟩

/-- **Corollary IV.1.6, sums.** A sum of semisimple submodules is
semisimple. -/
theorem semisimple_i_sup
    {ι : Type w} (S : ι → Submodule R M)
    (hS : ∀ i, IsSemisimpleModule R (S i)) :
    IsSemisimpleModule R ↥(⨆ i, S i) := by
  have heq : (⨆ i ∈ (Set.univ : Set ι), S i) = ⨆ i, S i := by
    apply le_antisymm
    · exact iSup_le fun i ↦ iSup_le fun _ ↦ le_iSup S i
    · exact iSup_le fun i ↦
        le_iSup_of_le i (le_iSup_of_le (Set.mem_univ i) le_rfl)
  rw [← heq]
  exact isSemisimpleModule_biSup_of_isSemisimpleModule_submodule
    (s := Set.univ) (p := S) (fun i _ ↦ hS i)

/-- **Corollary IV.1.6, submodules.** Every submodule of a semisimple module
is semisimple. -/
theorem semisimple_module_submodule [IsSemisimpleModule R M]
    (W : Submodule R M) :
    IsSemisimpleModule R W :=
  inferInstance

/-- **Corollary IV.1.6, quotients.** Every quotient of a semisimple module is
semisimple. -/
theorem semisimple_module_quotient [IsSemisimpleModule R M]
    (W : Submodule R M) :
    IsSemisimpleModule R (M ⧸ W) :=
  inferInstance

end Submission.CField.SAlgebr
