import Towers.NumberTheory.ClassGroup.ClassNumberFinite
import Towers.NumberTheory.Units.SUnits
import Towers.ClassField.NormIndex.FractionalIdealPrime
import Towers.ClassField.KummerNormIndex.PlaceValue

/-!
# Choosing the finite set of places in Lemma VII.9.3

For the openness argument we only need a finite set containing all infinite
places, all places dividing `p`, and enough finite primes to generate the
ideal class group.  This is a smaller selection result than the Kummer
radicand construction used in Section 6.
-/

namespace Towers.CField.NLimita

open Filter IsDedekindDomain NumberField Set
open Towers.NumberTheory.Milne
open Towers.CField.Ideles
open Towers.CField.NIndex
open Towers.CField.KNIndex
open scoped nonZeroDivisors

noncomputable section

universe u

private abbrev OK (K : Type u) [Field K] [NumberField K] :=
  RingOfIntegers K

private abbrev FI (K : Type u) [Field K] [NumberField K] :=
  (FractionalIdeal (OK K)⁰ K)ˣ

/-- The finite places where a nonzero field element has nontrivial
normalized absolute value. -/
noncomputable def finiteSupportPlaces
    (K : Type u) [Field K] [NumberField K] (x : Kˣ) :
    Finset (NumberFieldPlace K) := by
  have hfinite :
      {w : FinitePlace K | w (x : K) ≠ 1}.Finite := by
    simpa only [Function.HasFiniteMulSupport, Function.mulSupport] using
      (FinitePlace.hasFiniteMulSupport x.ne_zero)
  exact (hfinite.image fun w ↦
    (Sum.inl w.maximalIdeal : NumberFieldPlace K)).toFinset

theorem support_places_normalized
    (K : Type u) [Field K] [NumberField K] (x : Kˣ)
    (P : FinitePrime K)
    (hP : normalizedPlaceValue K (Sum.inl P) (x : K) ≠ 1) :
    (Sum.inl P : NumberFieldPlace K) ∈ finiteSupportPlaces K x := by
  classical
  unfold finiteSupportPlaces
  rw [Set.Finite.mem_toFinset]
  let w : FinitePlace K := FinitePlace.equivHeightOneSpectrum.symm P
  refine ⟨w, ?_, ?_⟩
  · simpa only [normalizedPlaceValue,
      FinitePlace.equivHeightOneSpectrum_symm_apply] using hP
  · exact congrArg Sum.inl
      (FinitePlace.equivHeightOneSpectrum.apply_symm_apply P)

/-- Membership in the subgroup generated by the finite primes in `S` is
equivalent to vanishing of all prime exponents outside `S`. -/
private theorem fractional_ideals_places
    {K : Type u} [Field K] [NumberField K]
    (S : Finset (NumberFieldPlace K)) (I : FI K) :
    I ∈ fractionalIdealsPlaces K S ↔
      ∀ P : HeightOneSpectrum (OK K),
        (Sum.inl P : NumberFieldPlace K) ∉ S →
          FractionalIdeal.count K P
            (I : FractionalIdeal (OK K)⁰ K) = 0 := by
  classical
  let Z : Subgroup (FI K) :=
  { carrier := {J | ∀ P : HeightOneSpectrum (OK K),
      (Sum.inl P : NumberFieldPlace K) ∉ S →
        FractionalIdeal.count K P
          (J : FractionalIdeal (OK K)⁰ K) = 0}
    one_mem' := by
      intro P _
      exact FractionalIdeal.count_one K P
    mul_mem' := by
      intro A B hA hB P hP
      rw [Units.val_mul,
        FractionalIdeal.count_mul K P A.ne_zero B.ne_zero,
        hA P hP, hB P hP, add_zero]
    inv_mem' := by
      intro A hA P hP
      rw [Units.val_inv_eq_inv_val, FractionalIdeal.count_inv,
        hA P hP, neg_zero] }
  constructor
  · intro hI
    have hle : fractionalIdealsPlaces K S ≤ Z := by
      apply (Subgroup.closure_le Z).mpr
      rintro J ⟨P, hPS, rfl⟩
      intro Q hQS
      change FractionalIdeal.count K Q
        (P.asIdeal : FractionalIdeal (OK K)⁰ K) = 0
      rw [FractionalIdeal.count_maximal]
      simp only [ite_eq_right_iff]
      intro hQP
      subst Q
      exact (hQS hPS).elim
    exact hle hI
  · intro hI
    let f : HeightOneSpectrum (OK K) → FI K := fun P ↦
      fractionalIdealPrime K P ^
        FractionalIdeal.count K P (I : FractionalIdeal (OK K)⁰ K)
    have hf : ∀ P, f P ∈ fractionalIdealsPlaces K S := by
      intro P
      by_cases hPS : (Sum.inl P : NumberFieldPlace K) ∈ S
      · exact (fractionalIdealsPlaces K S).zpow_mem
          (Subgroup.subset_closure ⟨P, hPS, rfl⟩) _
      · dsimp only [f]
        rw [hI P hPS]
        rw [zpow_zero]
        exact (fractionalIdealsPlaces K S).one_mem
    have hprod : (∏ᶠ P, f P) ∈ fractionalIdealsPlaces K S :=
      finprod_induction _
        (fractionalIdealsPlaces K S).one_mem
        (fun _ _ ↦ (fractionalIdealsPlaces K S).mul_mem) hf
    have hprod_eq : (∏ᶠ P, f P) = I := by
      apply Units.ext
      change (Units.coeHom (FractionalIdeal (OK K)⁰ K)) (∏ᶠ P, f P) =
        (I : FractionalIdeal (OK K)⁰ K)
      rw [(Units.coeHom (FractionalIdeal (OK K)⁰ K)).map_finprod_of_injective
        Units.coeHom_injective]
      simp only [f, map_zpow, Units.coeHom_apply,
        fractionalIdealPrime]
      change (∏ᶠ P : HeightOneSpectrum (OK K),
          (P.asIdeal : FractionalIdeal (OK K)⁰ K) ^
            FractionalIdeal.count K P
              (I : FractionalIdeal (OK K)⁰ K)) =
        (I : FractionalIdeal (OK K)⁰ K)
      exact FractionalIdeal.finprod_heightOneSpectrum_factorization' K I.ne_zero
    rwa [hprod_eq] at hprod

/-- Containing ideal-class generators is preserved under enlargement. -/
theorem contains_generators_mono
    (K : Type u) [Field K] [NumberField K]
    {S T : Finset (NumberFieldPlace K)}
    (hS : CIGenera K S) (hST : S ⊆ T) :
    CIGenera K T := by
  unfold CIGenera at hS ⊢
  apply top_unique
  rw [← hS]
  apply Subgroup.map_mono
  apply Subgroup.closure_mono
  rintro I ⟨P, hPS, rfl⟩
  exact ⟨P, hST hPS, rfl⟩

/-- A finite set satisfying the three place conditions used in the
openness half of Lemma 9.3. -/
theorem exists_BasePlaces
    (p : ℕ) (hp : p.Prime)
    (K : Type u) [Field K] [NumberField K] :
    ∃ S : Finset (NumberFieldPlace K),
      ContainsAllPlaces K S ∧
      (∀ v : NumberFieldPlace K,
        normalizedPlaceValue K v (p : K) ≠ 1 → v ∈ S) ∧
      CIGenera K S := by
  classical
  letI : Finite (ClassGroup (OK K)) := classGroup_finite K
  let representativeIdeal : ClassGroup (OK K) → (Ideal (OK K))⁰ := fun C ↦
    Classical.choose (ClassGroup.mk0_surjective C)
  have representativeIdeal_spec (C : ClassGroup (OK K)) :
      ClassGroup.mk0 (representativeIdeal C) = C :=
    Classical.choose_spec (ClassGroup.mk0_surjective C)
  let representative : ClassGroup (OK K) → FI K := fun C ↦
    FractionalIdeal.mk0 K (representativeIdeal C)
  have representative_spec (C : ClassGroup (OK K)) :
      ClassGroup.mk K (representative C) = C := by
    change ClassGroup.mk K
      (FractionalIdeal.mk0 K (representativeIdeal C)) = C
    rw [ClassGroup.mk_mk0, representativeIdeal_spec]
  let generatorPrimes : Set (FinitePrime K) :=
    {P | ∃ C : ClassGroup (OK K),
      FractionalIdeal.count K P
        (representative C : FractionalIdeal (OK K)⁰ K) ≠ 0}
  have generatorPrimes_finite : generatorPrimes.Finite := by
    have hfinite : (⋃ C : ClassGroup (OK K), {P : FinitePrime K |
        FractionalIdeal.count K P
          (representative C : FractionalIdeal (OK K)⁰ K) ≠ 0}).Finite :=
      Set.finite_iUnion fun C ↦ Filter.eventually_cofinite.mp
        (FractionalIdeal.finite_factors
          (representative C : FractionalIdeal (OK K)⁰ K))
    apply hfinite.subset
    intro P hP
    rcases hP with ⟨C, hPC⟩
    exact Set.mem_iUnion.mpr ⟨C, hPC⟩
  let classPlaces : Finset (NumberFieldPlace K) :=
    generatorPrimes_finite.toFinset.image Sum.inl
  have hclass : CIGenera K classPlaces := by
    unfold CIGenera
    apply top_unique
    intro C _
    refine ⟨representative C, ?_, representative_spec C⟩
    apply (fractional_ideals_places
      classPlaces (representative C)).2
    intro P hP
    by_contra hcount
    apply hP
    apply Finset.mem_image.mpr
    refine ⟨P, ?_, rfl⟩
    exact (Set.Finite.mem_toFinset generatorPrimes_finite).mpr ⟨C, hcount⟩
  let infinitePlaces : Finset (NumberFieldPlace K) :=
    Finset.univ.image Sum.inr
  have hpK : (p : K) ≠ 0 := by
    exact_mod_cast hp.ne_zero
  let pUnit : Kˣ := Units.mk0 (p : K) hpK
  let S : Finset (NumberFieldPlace K) :=
    classPlaces ∪ infinitePlaces ∪ finiteSupportPlaces K pUnit
  refine ⟨S, ?_, ?_, ?_⟩
  · intro v
    apply Finset.mem_union_left
    apply Finset.mem_union_right
    exact Finset.mem_image.mpr ⟨v, Finset.mem_univ _, rfl⟩
  · intro v hv
    cases v with
    | inl P =>
        apply Finset.mem_union_right
        exact support_places_normalized
          K pUnit P (by simpa [pUnit] using hv)
    | inr v =>
        apply Finset.mem_union_left
        apply Finset.mem_union_right
        exact Finset.mem_image.mpr ⟨v, Finset.mem_univ _, rfl⟩
  · exact contains_generators_mono K hclass
      (fun _ hv ↦ Finset.mem_union_left _ (Finset.mem_union_left _ hv))

end

end Towers.CField.NLimita
