import Towers.ClassField.KummerNormIndex.SecondInequalityAssembly
import Towers.ClassField.KummerNormIndex.SUnitUnramified
import Towers.ClassField.NormLimitation.OfGlobalReciprocity
import Towers.ClassField.NormLimitation.KummerCore
import Towers.ClassField.NormLimitation.KummerCoreStatement

/-!
# The Kummer norm group in Lemma VII.9.3

For `T = ∅`, the subgroup `E` of Lemma VII.6.4 is exactly the subgroup
used in Lemma 9.3: local `p`th powers at `S` and local units away from `S`.
The index calculation from Lemmas 6.5--6.7 gives

`[ℐ_K : Kˣ E] = p ^ |S|`.

The Kummer field generated by the `p`th roots of the `S`-units has the same
degree, and reciprocity gives the same index for its norm group.  Since
`E` is already contained in the idèle norm group by Lemma 6.4, the two
subgroups are equal.
-/

namespace Towers.CField.NLimita

open IsDedekindDomain NumberField
open Towers.CField.LFTheory
open Towers.CField.Ideles
open Towers.CField.Recip
open Towers.CField.ICohomo
open Towers.CField.HQuotie
open Towers.CField.NIndex
open Towers.CField.KNIndex

noncomputable section

universe u

private abbrev OK (K : Type u) [Field K] [NumberField K] :=
  NumberField.RingOfIntegers K

private abbrev IK (K : Type u) [Field K] [NumberField K] :=
  IdeleGroup (OK K) K

/-- The exact idèle index calculation used in Lemma VII.9.3. -/
theorem principal_sup_kummer
    (p : ℕ) (K : Type u) [Field K] [NumberField K]
    (hp : p.Prime) (hroots : (primitiveRoots p K).Nonempty)
    (S : Finset (NumberFieldPlace K))
    (hInfinite : ContainsAllPlaces K S)
    (hDividing : ∀ v : NumberFieldPlace K,
      normalizedPlaceValue K v (p : K) ≠ 1 → v ∈ S)
    (hClass : CIGenera K S) :
    (principalIdeles (OK K) K ⊔
      ideleSubgroup K p S ∅).index = p ^ S.card := by
  classical
  let E := ideleSubgroup K p S ∅
  let I := idelesAtPlaces (K := K) (L := K)
    (combinedPlaces K S ∅)
  let C := principalIdeles (OK K) K
  have hdisjoint : ∀ P : HeightOneSpectrum (OK K),
      P ∈ (∅ : Finset (HeightOneSpectrum (OK K))) →
      (Sum.inl P : NumberFieldPlace K) ∉ S := by simp
  have hsurjective : Function.Surjective
      (obviousMap K p S ∅ hdisjoint) :=
    fun y ↦ ⟨1, by
      funext P
      exact (List.not_mem_nil P.2).elim⟩
  have hintersection :
      (principalIntersection K p S ∅).index = p ^ S.card := by
    simpa using intersectionPowerStatement p K hp hroots S ∅
      hInfinite hDividing hClass hdisjoint hsurjective
  have htotal : E.relIndex I = p ^ (2 * S.card) := by
    simpa only [E, I] using
      localIndexStatement p K hp hroots S ∅
        hInfinite hDividing hdisjoint
  have hEI : E ≤ I := by
    intro x hx P hP
    change (Sum.inl (P.under (OK K)) : NumberFieldPlace K) ∉
      combinedPlaces K S ∅ at hP
    have hunder : P.under (OK K) = P := by
      apply HeightOneSpectrum.ext
      ext z
      simp [Ideal.under_def]
    rw [hunder] at hP
    exact hx.2.2 P (fun hPS ↦ hP (by
      exact Finset.mem_union_left _ hPS)) (by simp)
  have hSI : idelesAtPlaces K S ≤ I := by
    intro x hx P hP
    apply hx P
    intro hPS
    apply hP
    exact Finset.mem_union_left _ hPS
  have htopS : C ⊔ idelesAtPlaces K S = ⊤ :=
    Towers.CField.BLoc.fractionalIdealPrime
      K S hInfinite hClass
  have htop : I ⊔ C = ⊤ := by
    rw [sup_comm]
    apply top_unique
    rw [← htopS]
    exact sup_le_sup le_rfl hSI
  have hindexProduct := subgroup_relIndex I E C hEI
  change (E ⊔ C).relIndex (I ⊔ C) *
      (E ⊓ C).relIndex (I ⊓ C) = E.relIndex I at hindexProduct
  rw [htop, Subgroup.relIndex_top_right,
    principal_intersection_rel K p S ∅,
    hintersection, htotal] at hindexProduct
  apply Nat.mul_right_cancel (pow_pos hp.pos S.card)
  calc
    (C ⊔ E).index * p ^ S.card = p ^ (2 * S.card) := by
      simpa [sup_comm] using hindexProduct
    _ = p ^ S.card * p ^ S.card := by
      rw [← pow_add]
      congr 1
      omega

/-- The literal Kummer field `K[U(S)^(1/p)]`, regarded as a finite abelian
subextension of the chosen separable closure. -/
noncomputable def sKummerSubextension
    (p : ℕ) (K : Type u) [Field K] [NumberField K]
    (hp : p.Prime) (hroots : (primitiveRoots p K).Nonempty)
    (S : Finset (NumberFieldPlace K))
    (hInfinite : ContainsAllPlaces K S) :
    FASubext K := by
  let M := sKummerField K (SeparableClosure K)
    p hp hroots S hInfinite
  letI : FiniteDimensional K M :=
    sKummerDimensional K (SeparableClosure K)
      p hp hroots S hInfinite
  letI : IsAbelianGalois K M :=
    sAbelianGalois K (SeparableClosure K)
      p hp hroots S hInfinite
  exact
    { finiteIntermediateField :=
        { M with
          finiteDimensional := inferInstance
          isGalois := inferInstance }
      isAbelian := inferInstance }

theorem s_subextension_finrank
    (p : ℕ) (K : Type u) [Field K] [NumberField K]
    (hp : p.Prime) (hroots : (primitiveRoots p K).Nonempty)
    (S : Finset (NumberFieldPlace K))
    (hInfinite : ContainsAllPlaces K S) :
    Module.finrank K
      (sKummerSubextension p K hp hroots S hInfinite).1 =
        p ^ S.card :=
  finrank_s_kummer K (SeparableClosure K)
    p hp hroots S hInfinite

set_option maxHeartbeats 2000000 in
-- Comparing the two finite-index idèle subgroups expands the Artin kernel.
/-- Recip and the index calculation identify the norm group of the
`S`-unit Kummer field with the concrete subgroup represented by `E`. -/
theorem s_kummer_group
    (p : ℕ) (K : Type u) [Field K] [NumberField K]
    (hp : p.Prime) (hroots : (primitiveRoots p K).Nonempty)
    (S : Finset (NumberFieldPlace K))
    (hInfinite : ContainsAllPlaces K S)
    (hDividing : ∀ v : NumberFieldPlace K,
      normalizedPlaceValue K v (p : K) ≠ 1 → v ∈ S)
    (hClass : CIGenera K S)
    (hArtin : GlobalArtinProposition (K := K))
    (hrec : IdeleReciprocityLaw (K := K)) :
    ideleClassSubgroup
        (sKummerSubextension p K hp hroots S hInfinite) =
      kummerIdeleClasses K p S := by
  classical
  let M := sKummerField K (SeparableClosure K)
    p hp hroots S hInfinite
  letI : FiniteDimensional K M :=
    sKummerDimensional K (SeparableClosure K)
      p hp hroots S hInfinite
  letI : NumberField M :=
    sKummerNumber K (SeparableClosure K)
      p hp hroots S hInfinite
  letI : IsAbelianGalois K M :=
    sAbelianGalois K (SeparableClosure K)
      p hp hroots S hInfinite
  let L := sKummerSubextension p K hp hroots S hInfinite
  let E := ideleSubgroup K p S ∅
  let N := ideleNormSubgroup (K := K) (L := M)
  let C := principalIdeles (OK K) K
  have hselected : SelectedLocallyTrivial K M ∅ := by
    intro P hP
    simp at hP
  have hunramified : ∀ Q : HeightOneSpectrum (OK M),
      (Sum.inl (Q.under (OK K)) : NumberFieldPlace K) ∉ S →
        Algebra.IsUnramifiedAt (OK K) Q.asIdeal :=
    s_kummer_outside K (SeparableClosure K)
      p hp hroots S hInfinite hDividing
  have hEN : E ≤ N := by
    exact localBridgesStatement p K M
      (s_kummer_galois
        K (SeparableClosure K) p hp hroots S hInfinite)
      S ∅ hInfinite hselected hunramified
  have hEindex : (C ⊔ E).index = p ^ S.card := by
    exact principal_sup_kummer
      p K hp hroots S hInfinite hDividing hClass
  obtain ⟨phi, hphi, _⟩ := hArtin
  have hfinite := (hrec phi hphi).2 L
  have hNindex : (C ⊔ N).index = p ^ S.card := by
    calc
      (C ⊔ N).index =
          (((localAbelianRestriction L).comp phi).ker).index :=
        congrArg Subgroup.index hfinite.2
      _ = Nat.card (((localAbelianRestriction L).comp phi).range) :=
        Subgroup.index_ker _
      _ = Nat.card Gal(L.1/K) := by
        rw [MonoidHom.range_eq_top.mpr hfinite.1, Subgroup.card_top]
      _ = Module.finrank K L.1 := IsGalois.card_aut_eq_finrank K L.1
      _ = p ^ S.card :=
        s_subextension_finrank
          p K hp hroots S hInfinite
  have hCN : C ⊔ E ≤ C ⊔ N := sup_le_sup le_rfl hEN
  have hsup : C ⊔ E = C ⊔ N := by
    have hfactor := Subgroup.relIndex_mul_index hCN
    have hrel : (C ⊔ E).relIndex (C ⊔ N) = 1 := by
      apply Nat.mul_right_cancel (pow_pos hp.pos S.card)
      simpa [hEindex, hNindex] using hfactor
    exact le_antisymm hCN (Subgroup.relIndex_eq_one.mp hrel)
  let q := QuotientGroup.mk' (principalIdeles (OK K) K)
  change N.map q = E.map q
  calc
    N.map q = (C ⊔ N).map q := by
      rw [Subgroup.map_sup, QuotientGroup.map_mk'_self, bot_sup_eq]
    _ = (C ⊔ E).map q := congrArg (fun H : Subgroup (IK K) ↦ H.map q) hsup.symm
    _ = E.map q := by
      rw [Subgroup.map_sup, QuotientGroup.map_mk'_self, bot_sup_eq]

/-- The Kummer norm-core bridge from the already established global Artin
map and reciprocity law. -/
theorem kummer_core_reciprocity
    (hArtin : ∀ (K : Type u) [Field K] [NumberField K],
      GlobalArtinProposition (K := K))
    (hrec : ∀ (K : Type u) [Field K] [NumberField K],
      IdeleReciprocityLaw (K := K)) :
    KummerCoreBridge.{u} := by
  intro p K _ _ hp hroots S hInfinite hDividing hClass
  let L := sKummerSubextension p K hp hroots S hInfinite
  refine ⟨L, ?_⟩
  rw [s_kummer_group p K hp hroots S
    hInfinite hDividing hClass (hArtin K) (hrec K)]
  exact kummer_classes_core p K S

end

end Towers.CField.NLimita
