import Towers.ClassField.ArtinReciprocity.Statements
import Towers.ClassField.Ideles.FiniteRaySubgroup
import Towers.ClassField.Ideles.FiniteCoordinate
import Towers.ClassField.Reciprocity.ArtinMapStatements

/-!
# Chapter V, Section 5, Theorem 5.5: the idelic existence theorem

This file records Milne's theorem with finite abelian extensions represented
as intermediate fields of the fixed separable closure.  Thus the uniqueness
clause is literal equality of subextensions, not merely existence of an
abstract isomorphism.

The formal reduction below separates the two arithmetic inputs in the
printed proof:

* passage from ideal class fields (Theorem V.3.6), using the ray/idèle
  comparison of Propositions V.4.6--4.7, to existence of an idèle class
  field with the prescribed norm group;
* surjectivity of the global Artin map.  Together with reciprocity, this
  makes the norm-group map injective by the Galois correspondence.

All group-theoretic and fixed-closure uniqueness arguments are proved here.
The first item is isolated as one sharply named bridge because the project
does not yet identify the ideal norm group furnished by Theorem V.3.6 with
the image of the canonical idèle-class norm.
-/

namespace Towers.CField.Recip

open IsDedekindDomain NumberField
open Towers.CField.LFTheory
open Towers.CField.RCGroups
open Towers.CField.ARecip
open Towers.CField.Ideles

noncomputable section

universe u

variable {K : Type u} [Field K] [NumberField K]

noncomputable local instance idelicExistenceNumberField
    (L : FASubext K) : NumberField L.1 :=
  NumberField.of_module_finite K L.1

local notation "ᵒK" => NumberField.RingOfIntegers K

/-- The literal source assertion of Theorem V.5.5.  The ambient separable
closure built into `FASubext` is the fixed algebraic closure
in the statement (every finite extension in an algebraic closure is
separable in characteristic zero). -/
abbrev IdelicExistenceStatement : Prop :=
  IdeleExistenceTheorem (K := K)

/-- The exact existence-only consequence which remains after Theorem V.3.6
is transported through Propositions V.4.6--4.7.  Its dependence on the
actual ideal existence theorem is explicit; it does not assume an idelic
existence theorem or any uniqueness assertion.

Concretely, Proposition 4.6 identifies the relevant ray class quotient with
an idèle quotient, Proposition 4.7 extends the ideal character continuously
to the idèles, and compatibility of ideal and idèle norms identifies the
resulting kernel with `ideleClassSubgroup L`. -/
structure RayComparisonData where
  /-- The restriction of the canonical idèle-to-ideal map away from each
  finite set of places. -/
  idealMaps : ∀ S : Finset (HeightOneSpectrum ᵒK),
    IdeleAwayData K S
  /-- The two quotient identifications in Proposition V.4.6. -/
  raySubgroupStatement : ∀ m : Modulus K, RayLocalDecomposition m
  /-- The ideal-character/idèle-character equivalence of Proposition V.4.7,
  specialized only by the target finite group. -/
  ideleExistenceStatement : ∀ (G : Type u) [CommGroup G] [Finite G]
      [TopologicalSpace G] [DiscreteTopology G],
    ((
        ∀ (S : Finset (HeightOneSpectrum (O K)))
            (ψ : IdealsPrimeTo (O K) K S →* G),
            CharacterAdmitsModulus K S ψ →
              ∃! φ : IdeleGroup (O K) K →* G,
                IsIdeleExtension K S (idealMaps S) ψ φ
      ) ∧
          (
            ∀ φ : IdeleGroup (O K) K →* G,
                Continuous φ →
                principalIdeles (O K) K ≤ φ.ker →
                  ∃ (S : Finset (HeightOneSpectrum (O K)))
                    (ψ : IdealsPrimeTo (O K) K S →* G),
                    CharacterAdmitsModulus K S ψ ∧
                      IsIdeleExtension K S (idealMaps S) ψ φ
          ))

/-- The one remaining arithmetic bridge in the ideal-theoretic proof of
Theorem V.5.5: the class field supplied by ideal existence, transported
through the actual comparisons of Propositions V.4.6--4.7, has idèle-class
norm image equal to the prescribed subgroup. -/
def IdealExistenceBridge
    (_hIdeal : GlobalExistenceTheorem K)
    (_comparison : RayComparisonData (K := K)) : Prop :=
  ∀ N : Subgroup (IdeleClassGroup ᵒK K),
    IsOpen (N : Set (IdeleClassGroup ᵒK K)) →
    N.FiniteIndex →
      ∃ L : FASubext K,
        ideleClassSubgroup L = N

/-- A quotient by principal idèles pulls the image of an idèle norm subgroup
back to the subgroup generated by principal idèles and idèle norms. -/
theorem comap_idele_subgroup
    (L : FASubext K) :
    (ideleClassSubgroup L).comap
        (QuotientGroup.mk' (principalIdeles ᵒK K)) =
      principalIdeles ᵒK K ⊔ ideleNormSubgroup (K := K) (L := L.1) := by
  rw [ideleClassSubgroup]
  rw [Subgroup.comap_map_eq, QuotientGroup.ker_mk', sup_comm]

/-- Equality of idèle-class norm groups implies equality of the corresponding
subgroups of the idèle group after adjoining the principal idèles. -/
theorem principal_sup_class
    {L M : FASubext K}
    (h : ideleClassSubgroup L = ideleClassSubgroup M) :
    principalIdeles ᵒK K ⊔ ideleNormSubgroup (K := K) (L := L.1) =
      principalIdeles ᵒK K ⊔ ideleNormSubgroup (K := K) (L := M.1) := by
  rw [← comap_idele_subgroup L,
    ← comap_idele_subgroup M, h]

set_option maxHeartbeats 8000000 in
-- The nested topological abelianization restrictions elaborate slowly.
/- A finite abelian subextension of the fixed separable closure is
determined by the kernel of restriction from the abelianized absolute Galois
group.  This is the fixed-closure uniqueness step in the existence theorem. -/
theorem abelian_subextension_restriction
    {L M : FASubext K}
    (hker : (localAbelianRestriction L).ker =
      (localAbelianRestriction M).ker) :
    L = M := by
  let q := localAbelianizationMap K
  have hcomap : (localAbelianRestriction L).ker.comap q =
      (localAbelianRestriction M).ker.comap q := congrArg (fun H => H.comap q) hker
  have hfix :
      L.finiteIntermediateField.toIntermediateField.fixingSubgroup =
        M.finiteIntermediateField.toIntermediateField.fixingSubgroup := by
    rw [← IntermediateField.restrictNormalHom_ker,
      ← IntermediateField.restrictNormalHom_ker]
    ext σ
    change localAbelianRestriction L (q σ) = 1 ↔
      localAbelianRestriction M (q σ) = 1
    exact SetLike.ext_iff.mp hcomap σ
  have hfield :
      L.finiteIntermediateField.toIntermediateField =
        M.finiteIntermediateField.toIntermediateField := by
    rw [← InfiniteGalois.fixedField_fixingSubgroup
        L.finiteIntermediateField.toIntermediateField,
      hfix,
      InfiniteGalois.fixedField_fixingSubgroup
        M.finiteIntermediateField.toIntermediateField]
  have hfinite : L.finiteIntermediateField =
      M.finiteIntermediateField :=
    FiniteGaloisIntermediateField.val_injective hfield
  cases L
  cases M
  simp_all

set_option maxHeartbeats 8000000 in
-- The finite-level restrictions of the global Artin map elaborate slowly.
/- Recip and surjectivity of the global Artin map make the idèle-class
norm-group assignment injective.  The surjectivity used here is exactly the
number-field assertion recorded immediately after Corollary V.5.6 in the
source; it is not folded into the statement of Theorem V.5.5. -/
theorem idele_injective_reciprocity
    (phi : IdeleGroup ᵒK K →* AbsoluteAbelianGalois K)
    (hphi : ContinuousGlobalArtin phi)
    (hsurj : Function.Surjective phi)
    (hrec : IdeleReciprocityLaw (K := K)) :
    Function.Injective (ideleClassSubgroup (K := K)) := by
  intro L M hnorm
  have hrecL := (hrec phi hphi).2 L
  have hrecM := (hrec phi hphi).2 M
  have hcompKer : ((localAbelianRestriction L).comp phi).ker =
      ((localAbelianRestriction M).comp phi).ker := by
    rw [← hrecL.2, ← hrecM.2]
    exact principal_sup_class hnorm
  have hrestrictionKer : (localAbelianRestriction L).ker =
      (localAbelianRestriction M).ker := by
    apply Subgroup.comap_injective hsurj
    ext a
    exact SetLike.ext_iff.mp hcompKer a
  exact abelian_subextension_restriction hrestrictionKer

set_option maxHeartbeats 8000000 in
-- This combines the preceding finite-level restriction arguments.
/- The full literal Theorem V.5.5 follows from ideal existence transported
through the ray/idèle comparison, global reciprocity, and surjectivity of the
global Artin map.  No hypotheses are added to the theorem statement itself. -/
theorem ideal_existence_artin
    (hIdeal : GlobalExistenceTheorem K)
    (comparison : RayComparisonData (K := K))
    (hIdealIdele : IdealExistenceBridge hIdeal comparison)
    (phi : IdeleGroup ᵒK K →* AbsoluteAbelianGalois K)
    (hphi : ContinuousGlobalArtin phi)
    (hsurj : Function.Surjective phi)
    (hrec : IdeleReciprocityLaw (K := K)) :
    IdelicExistenceStatement (K := K) := by
  intro N hopen hfinite
  obtain ⟨L, hL⟩ := hIdealIdele N hopen hfinite
  refine ⟨L, hL, ?_⟩
  intro M hM
  exact idele_injective_reciprocity
    phi hphi hsurj hrec (hM.trans hL.symm)

end

end Towers.CField.Recip
