import Submission.Group.GolodShafarevichCore
import Submission.Group.LowerCentralStrong

/-!
# Elementary exact-generator API for the explicit Zassenhaus filtration

This file contains the part of the explicit Zassenhaus filtration that is
independent of the reverse Jennings theorem.  In particular, it may be used by
the Jennings reduction that eventually proves that theorem.

The completed restricted-series API lives in `Submission.Group.ZassenhausRestricted`.
Keeping the elementary exact-generator layer here prevents the algebraic
Jennings construction from depending on that completed API.
-/

namespace Submission

open scoped commutatorElement

/-- Raw Zassenhaus generators of exact weight `n`, rather than weight merely
bounded below by `n`.  These are the generators used when refining one layer at
a time. -/
def exactGeneratorSet (p : ℕ) (G : Type*) [Group G] (n : ℕ) : Set G :=
  { g | ∃ i j : ℕ, ∃ x : G,
      x ∈ Subgroup.lowerCentralSeries G i ∧
      n = (i + 1) * p ^ j ∧
      x ^ (p ^ j) = g }

/-- Every exact-weight generator is a generator of the corresponding filtration
term. -/
lemma exact_set_subset
    {p : ℕ} {G : Type*} [Group G] {n : ℕ} :
    exactGeneratorSet p G n ⊆ zassenhausGeneratorSet p G n := by
  intro g hg
  rcases hg with ⟨i, j, x, hx, hweight, hpow⟩
  exact ⟨i, j, x, hx, hweight.le, hpow⟩

/-- Every exact-weight generator belongs to the corresponding filtration term. -/
lemma exact_subset_filtration
    {p : ℕ} {G : Type*} [Group G] {n : ℕ} :
    exactGeneratorSet p G n ⊆ zassenhausFiltration p G n := by
  intro g hg
  exact Subgroup.subset_closure
    (exact_set_subset hg)

/-- Exact Zassenhaus generators have positive exact weight for prime `p`. -/
lemma exact_set_pos
    {p : ℕ} [Fact p.Prime] {G : Type*} [Group G] {n : ℕ} {g : G}
    (hg : g ∈ exactGeneratorSet p G n) :
    0 < n := by
  rcases hg with ⟨i, j, _x, _hx, hweight, _hpow⟩
  rw [hweight]
  exact Nat.mul_pos (Nat.succ_pos i) (pow_pos (Fact.out : Nat.Prime p).pos j)

/-- A commutator of lower-central elements is an exact Zassenhaus generator of
summed weight. -/
lemma exact_set_series
    {p : ℕ} {G : Type*} [Group G] {i j : ℕ} {x y : G}
    (hx : x ∈ Subgroup.lowerCentralSeries G i)
    (hy : y ∈ Subgroup.lowerCentralSeries G j) :
    ⁅x, y⁆ ∈ exactGeneratorSet p G ((i + 1) + (j + 1)) := by
  refine ⟨i + j + 1, 0, ⁅x, y⁆, ?_, ?_, by simp⟩
  · exact lower_commutator_succ i j
      (Subgroup.commutator_mem_commutator hx hy)
  · simp
    omega

/-- A commutator of lower-central elements belongs to the explicit Zassenhaus
term of summed lower-central weight. -/
lemma commutator_element_series
    {p : ℕ} {G : Type*} [Group G]
    {i j : ℕ} {x y : G}
    (hx : x ∈ Subgroup.lowerCentralSeries G i)
    (hy : y ∈ Subgroup.lowerCentralSeries G j) :
    ⁅x, y⁆ ∈ zassenhausFiltration p G ((i + 1) + (j + 1)) := by
  exact
    exact_subset_filtration
      (exact_set_series hx hy)

/-- Taking a `p`th power of an exact-weight generator multiplies its exact
weight by `p`. -/
lemma exact_set_prime
    {p : ℕ} {G : Type*} [Group G] {n : ℕ} {g : G}
    (hg : g ∈ exactGeneratorSet p G n) :
    g ^ p ∈ exactGeneratorSet p G (p * n) := by
  rcases hg with ⟨i, j, x, hx, hweight, rfl⟩
  refine ⟨i, j + 1, x, hx, ?_, ?_⟩
  · calc
      p * n = p * ((i + 1) * p ^ j) := by rw [hweight]
      _ = (i + 1) * p ^ (j + 1) := by
        simp only [pow_succ]
        ac_rfl
  · rw [pow_succ, pow_mul]

/-- Every raw generator at level `n` either has exact weight `n` or already
belongs to the successor generating set. -/
lemma subset_exact_union
    {p : ℕ} {G : Type*} [Group G] (n : ℕ) :
    zassenhausGeneratorSet p G n ⊆
      exactGeneratorSet p G n ∪ zassenhausGeneratorSet p G (n + 1) := by
  intro g hg
  rcases hg with ⟨i, j, x, hx, hbound, hpow⟩
  by_cases hweight : n = (i + 1) * p ^ j
  · exact Set.mem_union_left _ ⟨i, j, x, hx, hweight, hpow⟩
  · exact Set.mem_union_right _ ⟨i, j, x, hx, by omega, hpow⟩

/-- One filtration layer is generated by its exact-weight generators together
with the successor term.  This is the group-theoretic decomposition used to
choose cyclic refinements. -/
lemma exact_sup_succ
    {p : ℕ} {G : Type*} [Group G] (n : ℕ) :
    zassenhausFiltration p G n =
      Subgroup.closure (exactGeneratorSet p G n) ⊔
        zassenhausFiltration p G (n + 1) := by
  apply le_antisymm
  · rw [zassenhausFiltration, Subgroup.closure_le]
    intro g hg
    rcases subset_exact_union n hg with hg | hg
    · exact
        (SetLike.coe_subset_coe.mpr
          (show
            Subgroup.closure (exactGeneratorSet p G n) ≤
              Subgroup.closure (exactGeneratorSet p G n) ⊔
                zassenhausFiltration p G (n + 1) from le_sup_left))
          (Subgroup.subset_closure hg)
    · exact
        (SetLike.coe_subset_coe.mpr
          (show
            zassenhausFiltration p G (n + 1) ≤
              Subgroup.closure (exactGeneratorSet p G n) ⊔
                zassenhausFiltration p G (n + 1) from le_sup_right))
          (Subgroup.subset_closure hg)
  · apply sup_le
    · rw [Subgroup.closure_le]
      exact fun _ hg =>
        Subgroup.subset_closure
          (exact_set_subset hg)
    · exact zassenhausFiltration_antitone p G (Nat.le_succ n)

/-- Every group element is an exact generator of weight one. -/
lemma zassenhaus_exact_set
    {p : ℕ} {G : Type*} [Group G] (g : G) :
    g ∈ exactGeneratorSet p G 1 := by
  refine ⟨0, 0, g, ?_, ?_, ?_⟩
  · simp [Subgroup.lowerCentralSeries_zero]
  · simp
  · simp

/-- For a positive exact weight, taking a `p`th power lands in the successor
filtration term. -/
lemma exact_filtration_succ
    {p : ℕ} {G : Type*} [Group G] [Fact p.Prime]
    {n : ℕ} (hn : 0 < n) {g : G}
    (hg : g ∈ exactGeneratorSet p G n) :
    g ^ p ∈ zassenhausFiltration p G (n + 1) := by
  have hp2 : 2 ≤ p := (Fact.out : Nat.Prime p).two_le
  have hn_succ_le_two_mul : n + 1 ≤ 2 * n := by omega
  have htwo_mul_le : 2 * n ≤ p * n :=
    Nat.mul_le_mul_right n hp2
  exact
    (zassenhausFiltration_antitone p G
      (le_trans hn_succ_le_two_mul htwo_mul_le))
      (exact_subset_filtration
        (exact_set_prime hg))

/-- If all generators from two sets commute modulo a normal subgroup, then their
subgroup closures commute modulo that normal subgroup. -/
lemma commutator_element_closure
    {G : Type*} [Group G] {A B : Set G} {K : Subgroup G} [K.Normal]
    (hAB :
      ∀ {a b : G}, a ∈ A → b ∈ B → ⁅a, b⁆ ∈ K) :
    ∀ {x y : G},
      x ∈ Subgroup.closure A →
      y ∈ Subgroup.closure B →
        ⁅x, y⁆ ∈ K := by
  let q : G →* G ⧸ K := QuotientGroup.mk' K
  have hcomm_gen :
      ∀ {a b : G}, a ∈ A → b ∈ B → Commute (q a) (q b) := by
    intro a b ha hb
    rw [← commutatorElement_eq_one_iff_commute, ← map_commutatorElement]
    exact (QuotientGroup.eq_one_iff (N := K) ⁅a, b⁆).mpr (hAB ha hb)
  have hcomm_right :
      ∀ {a y : G}, a ∈ A → y ∈ Subgroup.closure B → Commute (q a) (q y) := by
    intro a y ha hy
    let P : (z : G) → z ∈ Subgroup.closure B → Prop :=
      fun z _ => Commute (q a) (q z)
    exact
      Subgroup.closure_induction
        (p := P)
        (fun b hb => hcomm_gen ha hb)
        (by
          change Commute (q a) (q 1)
          simp)
        (fun x y _ _ hx_comm hy_comm => by
          change Commute (q a) (q (x * y))
          simpa using hx_comm.mul_right hy_comm)
        (fun x _ hx_comm => by
          change Commute (q a) (q x⁻¹)
          simpa using hx_comm.inv_right)
        hy
  intro x y hx hy
  have hcomm_left :
      ∀ {x : G}, x ∈ Subgroup.closure A → Commute (q x) (q y) := by
    intro x hx
    let P : (z : G) → z ∈ Subgroup.closure A → Prop :=
      fun z _ => Commute (q z) (q y)
    exact
      Subgroup.closure_induction
        (p := P)
        (fun a ha => hcomm_right ha hy)
        (by
          change Commute (q 1) (q y)
          simp)
        (fun x z _ _ hx_comm hz_comm => by
          change Commute (q (x * z)) (q y)
          simpa using hx_comm.mul_left hz_comm)
        (fun x _ hx_comm => by
          change Commute (q x⁻¹) (q y)
          simpa using hx_comm.inv_left)
        hx
  have hxy : Commute (q x) (q y) := hcomm_left hx
  have hq : q ⁅x, y⁆ = 1 := by
    rw [map_commutatorElement, commutatorElement_eq_one_iff_commute]
    exact hxy
  exact
    (QuotientGroup.eq_one_iff (N := K) ⁅x, y⁆).mp
      (by
        change QuotientGroup.mk' K ⁅x, y⁆ = 1 at hq
        exact hq)

/-- To prove a commutator estimate between two explicit Zassenhaus filtration
terms, it is enough to check the raw generators. -/
lemma element_set_bound
    {p : ℕ} {G : Type*} [Group G] {r s : ℕ}
    (hgen :
      ∀ {x y : G},
        x ∈ zassenhausGeneratorSet p G r →
        y ∈ zassenhausGeneratorSet p G s →
          ⁅x, y⁆ ∈ zassenhausFiltration p G (r + s)) :
    ∀ {x y : G},
      x ∈ zassenhausFiltration p G r →
      y ∈ zassenhausFiltration p G s →
        ⁅x, y⁆ ∈ zassenhausFiltration p G (r + s) := by
  intro x y hx hy
  rw [zassenhausFiltration] at hx hy
  haveI : (zassenhausFiltration p G (r + s)).Normal :=
    zassenhausFiltration_normal p G (r + s)
  exact
    commutator_element_closure
      (K := zassenhausFiltration p G (r + s))
      hgen hx hy

/-- Raw generators at level `n` belong to the corresponding explicit
Zassenhaus filtration term. -/
lemma set_subset_filtration
    {p : ℕ} {G : Type*} [Group G] {n : ℕ} :
    zassenhausGeneratorSet p G n ⊆ zassenhausFiltration p G n := by
  intro g hg
  exact Subgroup.subset_closure hg

/-- In a quotient where `D_n = 1`, every raw generator of weight at least `n`
is trivial. -/
lemma generator_set_trivial
    {p : ℕ} {G : Type*} [Group G] {n r : ℕ} {g : G}
    (hbot : zassenhausFiltration p G n = ⊥)
    (hnr : n ≤ r)
    (hg : g ∈ zassenhausGeneratorSet p G r) :
    g = 1 := by
  have hgD_r : g ∈ zassenhausFiltration p G r :=
    set_subset_filtration hg
  have hgD_n : g ∈ zassenhausFiltration p G n :=
    zassenhausFiltration_antitone p G hnr hgD_r
  have hgbot : g ∈ (⊥ : Subgroup G) := by
    simpa [hbot] using hgD_n
  simpa using hgbot

/-- If the left raw generator already has killed weight, the commutator
estimate is automatic. -/
lemma filtration_trivial_high
    {p : ℕ} {G : Type*} [Group G] {n r s : ℕ} {x y : G}
    (hbot : zassenhausFiltration p G n = ⊥)
    (hnr : n ≤ r)
    (hx : x ∈ zassenhausGeneratorSet p G r) :
    ⁅x, y⁆ ∈ zassenhausFiltration p G (r + s) := by
  have hxone : x = 1 :=
    generator_set_trivial hbot hnr hx
  simp [hxone]

/-- If the right raw generator already has killed weight, the commutator
estimate is automatic. -/
lemma element_trivial_high
    {p : ℕ} {G : Type*} [Group G] {n r s : ℕ} {x y : G}
    (hbot : zassenhausFiltration p G n = ⊥)
    (hns : n ≤ s)
    (hy : y ∈ zassenhausGeneratorSet p G s) :
    ⁅x, y⁆ ∈ zassenhausFiltration p G (r + s) := by
  have hyone : y = 1 :=
    generator_set_trivial hbot hns hy
  simp [hyone]

/-- On a killed layer, it is enough to check raw-generator commutators below
the killed weight. -/
lemma killed_low_bound
    {p : ℕ} {G : Type*} [Group G] {n : ℕ}
    (hbot : zassenhausFiltration p G n = ⊥)
    (hgen_low :
      ∀ {r s : ℕ} {x y : G},
        r < n →
        s < n →
        x ∈ zassenhausGeneratorSet p G r →
        y ∈ zassenhausGeneratorSet p G s →
          ⁅x, y⁆ ∈ zassenhausFiltration p G (r + s)) :
    ∀ {r s : ℕ} {x y : G},
      x ∈ zassenhausGeneratorSet p G r →
      y ∈ zassenhausGeneratorSet p G s →
        ⁅x, y⁆ ∈ zassenhausFiltration p G (r + s) := by
  intro r s x y hx hy
  by_cases hr : r < n
  · by_cases hs : s < n
    · exact hgen_low hr hs hx hy
    · exact
        element_trivial_high
          hbot (Nat.le_of_not_gt hs) hy
  · exact
      filtration_trivial_high
        hbot (Nat.le_of_not_gt hr) hx

/-- Killed-layer low-weight raw-generator checks lift to the full explicit
filtration terms. -/
lemma element_killed_low
    {p : ℕ} {G : Type*} [Group G] {n : ℕ}
    (hbot : zassenhausFiltration p G n = ⊥)
    (hgen_low :
      ∀ {r s : ℕ} {x y : G},
        r < n →
        s < n →
        x ∈ zassenhausGeneratorSet p G r →
        y ∈ zassenhausGeneratorSet p G s →
          ⁅x, y⁆ ∈ zassenhausFiltration p G (r + s)) :
    ∀ {r s : ℕ} {x y : G},
      x ∈ zassenhausFiltration p G r →
      y ∈ zassenhausFiltration p G s →
        ⁅x, y⁆ ∈ zassenhausFiltration p G (r + s) := by
  intro r s x y hx hy
  exact
    element_set_bound
      (killed_low_bound
        hbot hgen_low)
      hx hy

/-- In a killed layer, every raw generator is either trivial or has some exact
weight below the killed cutoff. -/
lemma or_exact_trivial
    {p : ℕ} {G : Type*} [Group G] {n r : ℕ} {g : G}
    (hbot : zassenhausFiltration p G n = ⊥)
    (hg : g ∈ zassenhausGeneratorSet p G r) :
    g = 1 ∨
      ∃ k : ℕ,
        r ≤ k ∧
          k < n ∧
            g ∈ exactGeneratorSet p G k := by
  rcases hg with ⟨i, j, x, hx, hbound, hpow⟩
  by_cases hk : (i + 1) * p ^ j < n
  · exact
      Or.inr
        ⟨(i + 1) * p ^ j, hbound, hk,
          ⟨i, j, x, hx, rfl, hpow⟩⟩
  · have hn_le : n ≤ (i + 1) * p ^ j := Nat.le_of_not_gt hk
    have hg_high : g ∈ zassenhausGeneratorSet p G n :=
      ⟨i, j, x, hx, hn_le, hpow⟩
    exact
      Or.inl
        (generator_set_trivial
          hbot (Nat.le_refl n) hg_high)

/-- On a killed layer, exact-weight commutator checks below the killed cutoff
imply the corresponding low-weight raw-generator checks. -/
lemma killed_exact_bound
    {p : ℕ} {G : Type*} [Group G] {n : ℕ}
    (hbot : zassenhausFiltration p G n = ⊥)
    (hexact :
      ∀ {r s : ℕ} {x y : G},
        r < n →
        s < n →
        x ∈ exactGeneratorSet p G r →
        y ∈ exactGeneratorSet p G s →
          ⁅x, y⁆ ∈ zassenhausFiltration p G (r + s)) :
    ∀ {r s : ℕ} {x y : G},
      r < n →
      s < n →
      x ∈ zassenhausGeneratorSet p G r →
      y ∈ zassenhausGeneratorSet p G s →
        ⁅x, y⁆ ∈ zassenhausFiltration p G (r + s) := by
  intro r s x y _hr _hs hx hy
  rcases or_exact_trivial
      hbot hx with hxone | ⟨rx, hrx, hxr_n, hxexact⟩
  · simp [hxone]
  rcases or_exact_trivial
      hbot hy with hyone | ⟨sy, hsy, hys_n, hyexact⟩
  · simp [hyone]
  exact
    zassenhausFiltration_antitone p G
      (Nat.add_le_add hrx hsy)
      (hexact hxr_n hys_n hxexact hyexact)

/-- Killed-layer exact-weight commutator checks lift all the way to the full
explicit filtration terms. -/
lemma element_killed_bound
    {p : ℕ} {G : Type*} [Group G] {n : ℕ}
    (hbot : zassenhausFiltration p G n = ⊥)
    (hexact :
      ∀ {r s : ℕ} {x y : G},
        r < n →
        s < n →
        x ∈ exactGeneratorSet p G r →
        y ∈ exactGeneratorSet p G s →
          ⁅x, y⁆ ∈ zassenhausFiltration p G (r + s)) :
    ∀ {r s : ℕ} {x y : G},
      x ∈ zassenhausFiltration p G r →
      y ∈ zassenhausFiltration p G s →
        ⁅x, y⁆ ∈ zassenhausFiltration p G (r + s) := by
  exact
    element_killed_low
      hbot
      (killed_exact_bound
        hbot hexact)

end Submission
