import Submission.ClassField.BrauerLocalization.SumSurjectivity
import Submission.ClassField.BrauerLocalization.AbsoluteKernelLifting
import Submission.ClassField.BrauerLocalization.BrauerKernelLifting
import Submission.ClassField.BrauerLocalization.LocalKernelVanishing
import Submission.ClassField.BrauerLocalization.ArchimedeanData
import Submission.ClassField.BrauerLocalization.Main
import Submission.ClassField.BrauerLocalization.Relative2Comparison
import Submission.ClassField.BrauerLocalization.RelativeIdele
import Submission.ClassField.BrauerLocalization.CompletionNaturality
import Submission.ClassField.BrauerLocalization.CrossedProduct
import Submission.ClassField.BrauerLocalization.InfiniteCrossedProduct
import Submission.ClassField.BrauerLocalization.H2Comparison
import Submission.ClassField.BrauerLocalization.CohomologicalData
import Submission.ClassField.BrauerLocalization.Injectivity
import Submission.ClassField.BrauerLocalization.ExactnessAssembly
import Submission.ClassField.BrauerLocalization.KernelLiftingAssembly
import Submission.ClassField.BrauerLocalization.KillingSelection
import Submission.ClassField.BrauerLocalization.CokernelAssembly
import Submission.ClassField.BrauerLocalization.KernelAssembly
import Submission.ClassField.BrauerLocalization.HerbrandExact
import Submission.ClassField.BrauerLocalization.LocalHilbert90
import Submission.ClassField.BrauerLocalization.FiniteTateZero
import Submission.ClassField.BrauerLocalization.FiniteZeroDirect
import Submission.ClassField.BrauerLocalization.InfiniteTateZero
import Submission.ClassField.BrauerLocalization.LocalTateZero
import Submission.ClassField.BrauerLocalization.RestrictedProductZero
import Submission.ClassField.BrauerLocalization.RestrictedNegOne
import Submission.ClassField.BrauerLocalization.IdeleIdealSupport
import Submission.ClassField.BrauerLocalization.FiniteCyclicSequence
import Submission.ClassField.BrauerLocalization.FiniteCyclicCohomology
import Submission.ClassField.BrauerLocalization.SpectralBaseChange
import Submission.ClassField.BrauerLocalization.NormIndexConsequences
import Submission.ClassField.BrauerLocalization.CyclicIdeleCohomology

/-!
# Assembly modules for CFT Theorem VIII.4.2
-/
