import Submission.ClassField.IdeleCohomology.InducedModule
import Submission.ClassField.IdeleCohomology.ShapiroHilbert90
import Submission.ClassField.IdeleCohomology.CompletionConjugation
import Submission.ClassField.IdeleCohomology.RestrictedProductAction
import Submission.ClassField.IdeleCohomology.DecompositionStatements
import Submission.ClassField.IdeleCohomology.CompletionProductAction
import Submission.ClassField.IdeleCohomology.CompletionInducedModule
import Submission.ClassField.IdeleCohomology.FiniteIdeleAction
import Submission.ClassField.IdeleCohomology.InfiniteIdeleAction

/-! # Chapter VII, Section 2: cohomology of the ideles -/
