import Submission.ClassField.KummerNormIndex.CoprimeExponent
import Submission.ClassField.KummerNormIndex.SubgroupIndex
import Submission.ClassField.KummerNormIndex.PowerIndex
import Submission.ClassField.KummerNormIndex.IdeleClassQuotient
import Submission.ClassField.KummerNormIndex.NormExponent
import Submission.ClassField.KummerNormIndex.CyclotomicDegree
import Submission.ClassField.KummerNormIndex.CyclotomicCompositum
import Submission.ClassField.KummerNormIndex.IdeleExtensionTower
import Submission.ClassField.KummerNormIndex.BaseChangeNorm
import Submission.ClassField.KummerNormIndex.CyclotomicBaseChange
import Submission.ClassField.KummerNormIndex.CompletionRestriction
import Submission.ClassField.KummerNormIndex.KummerBridge
import Submission.ClassField.KummerNormIndex.IdeleSubgroup
import Submission.ClassField.KummerNormIndex.LocalNormBridges
import Submission.ClassField.KummerNormIndex.ComplexAbsoluteValue
import Submission.ClassField.KummerNormIndex.LocalPowerIndex
import Submission.ClassField.KummerNormIndex.PlaceValue
import Submission.ClassField.KummerNormIndex.IntersectionPower
import Submission.ClassField.KummerNormIndex.KummerPairing
import Submission.ClassField.KummerNormIndex.NthPowerPlace
import Submission.ClassField.KummerNormIndex.KummerExtension
import Submission.ClassField.KummerNormIndex.LocalSplitting
import Submission.ClassField.KummerNormIndex.LocalCriterionIdeles
import Submission.ClassField.KummerNormIndex.SecondInequalityTower

/-! # Chapter VII, Section 6: algebraic proof of the second inequality -/
