import Mathlib.Data.Finite.Perm
import Mathlib.GroupTheory.Perm.Centralizer
import Mathlib.GroupTheory.Perm.Fin
import Mathlib.GroupTheory.SpecificGroups.Cyclic.Basic
import Submission.NumberTheory.Density.ChebotarevDensity

/-!
# Milne, Chapter 8, Example 8.36: the cubic density table

This file proves the `1`, `C₂`, `A₃`, and `S₃` rows of Milne's table.  In
particular, the three conjugacy classes in `S₃` have sizes one, three, and
two, giving densities `1/6`, `1/2`, and `1/3` under Chebotarev.

The earlier Frobenius-factorization results identify these cycle types with
complete splitting, a linear factor times an irreducible quadratic, and
irreducibility modulo the prime.
-/

namespace Submission.NumberTheory.Milne

open Equiv IsDedekindDomain NumberField

noncomputable section

private theorem conjugacy_carrier_type
    {n : ℕ} (g : Equiv.Perm (Fin n)) :
    (ConjClasses.mk g).carrier = {h | h.cycleType = g.cycleType} := by
  ext h
  simp only [ConjClasses.mem_carrier_iff_mk_eq, Set.mem_setOf_eq]
  rw [ConjClasses.mk_eq_mk_iff_isConj, Equiv.Perm.isConj_iff_cycleType_eq]

/-- In a finite symmetric group, the size of the conjugacy class of a
permutation is the number of permutations with its cycle type. -/
theorem conjugacy_ncard_type
    {n : ℕ} (g : Equiv.Perm (Fin n)) :
    (ConjClasses.mk g).carrier.ncard =
      ({h | h.cycleType = g.cycleType} : Finset (Equiv.Perm (Fin n))).card := by
  rw [conjugacy_carrier_type]
  rw [Set.ncard_eq_toFinset_card]
  congr
  ext h
  simp

/-- The symmetric group on three letters has order six. -/
theorem s3_card : Nat.card (Equiv.Perm (Fin 3)) = 6 := by
  rw [Nat.card_perm]
  norm_num

/-- Every permutation of three letters is the identity, a transposition, or a
three-cycle. -/
theorem s_3_cycle (g : Equiv.Perm (Fin 3)) :
    g = 1 ∨ g.IsSwap ∨ g.IsThreeCycle := by
  by_cases hg : g = 1
  · exact Or.inl hg
  · right
    have hge : 2 ≤ g.support.card :=
      Equiv.Perm.two_le_card_support_of_ne_one hg
    have hle : g.support.card ≤ 3 := by
      simpa using g.support.card_le_univ
    have hcard : g.support.card = 2 ∨ g.support.card = 3 := by omega
    rcases hcard with hcard | hcard
    · exact Or.inl (Equiv.Perm.card_support_eq_two.mp hcard)
    · exact Or.inr (card_support_eq_three_iff.mp hcard)

/-- The three transpositions form one conjugacy class in `S₃`. -/
theorem s_transposition_ncard
    (g : Equiv.Perm (Fin 3)) (hg : g.cycleType = {2}) :
    (ConjClasses.mk g).carrier.ncard = 3 := by
  rw [conjugacy_ncard_type, hg]
  rw [Equiv.Perm.card_of_cycleType_singleton (by norm_num) (by norm_num)]
  norm_num

/-- The two three-cycles form one conjugacy class in `S₃`. -/
theorem s_3_ncard
    (g : Equiv.Perm (Fin 3)) (hg : g.cycleType = {3}) :
    (ConjClasses.mk g).carrier.ncard = 2 := by
  rw [conjugacy_ncard_type, hg]
  rw [Equiv.Perm.card_of_cycleType_singleton (by norm_num) (by norm_num)]
  norm_num

/-- The transitive copy of `C₂` generated by a transposition in the
natural cubic permutation representation. -/
def cubicC2 : Subgroup (Equiv.Perm (Fin 3)) :=
  Subgroup.zpowers (Equiv.swap 0 1)

local instance cubicC2IsCyclic : IsCyclic cubicC2 := by
  change IsCyclic (Subgroup.zpowers (Equiv.swap (0 : Fin 3) 1))
  infer_instance

noncomputable local instance cubicC2CommGroup : CommGroup cubicC2 :=
  IsCyclic.commGroup

/-- The generator of the cubic `C₂`. -/
def cubicCSwap : cubicC2 :=
  ⟨Equiv.swap 0 1, by simp [cubicC2]⟩

/-- The cubic transposition subgroup has order two. -/
@[simp]
theorem cubic_c_card : Nat.card cubicC2 = 2 := by
  rw [cubicC2, Nat.card_zpowers]
  exact (Equiv.Perm.swap_isSwap_iff.mpr (by decide)).orderOf

/-- The chosen generator of the cubic `C₂` is nontrivial. -/
theorem cubic_c_swap : cubicCSwap ≠ 1 := by
  intro h
  have h0 := congrArg (fun sigma : cubicC2 =>
    (sigma : Equiv.Perm (Fin 3)) 0) h
  simp [cubicCSwap] at h0

/-- Every nonidentity element in the cubic `C₂` acts as a transposition. -/
theorem c_cycle_type (sigma : cubicC2) (hsigma : sigma ≠ 1) :
    (sigma : Equiv.Perm (Fin 3)).cycleType = {2} := by
  obtain ⟨tau, htau, hunique⟩ :=
    (Nat.card_eq_two_iff' (1 : cubicC2)).mp cubic_c_card
  have hsigma_tau : sigma = tau := hunique sigma hsigma
  have hswap_tau : cubicCSwap = tau :=
    hunique cubicCSwap cubic_c_swap
  rw [hsigma_tau, ← hswap_tau]
  exact Equiv.Perm.isSwap_iff_cycleType.mp
    (Equiv.Perm.swap_isSwap_iff.mpr (by decide))

variable (K : Type*) [Field K] [NumberField K]

/-- Milne's `G = 1` cubic row at the Frobenius-class level: the identity
class has density one. -/
theorem trivial_identity_chebotarev
    {G : Type*} [Group G] [Finite G] [Subsingleton G]
    {frobeniusClass : HeightOneSpectrum (𝓞 K) → Option (ConjClasses G)}
    (hcheb : ChebotarevDensityProperty K frobeniusClass) :
    PNDensit K
      (primesFrobeniusClass K frobeniusClass (ConjClasses.mk 1)) 1 := by
  simpa [Nat.card_unique] using
    (identity_frobenius_density K hcheb)

/-- In Milne's cubic `G = C₂` row, identity Frobenius has density one
half. -/
theorem c_identity_chebotarev
    {frobeniusClass : HeightOneSpectrum (𝓞 K) →
      Option (ConjClasses cubicC2)}
    (hcheb : ChebotarevDensityProperty K frobeniusClass) :
    PNDensit K
      (primesFrobeniusClass K frobeniusClass (ConjClasses.mk 1))
      (1 / 2) := by
  simpa using quadratic_density_chebotarev K hcheb cubic_c_card
    (1 : cubicC2)

/-- In Milne's cubic `G = C₂` row, transposition Frobenius has density one
half.  Its cycle type `{2}` corresponds to a linear factor times an
irreducible quadratic. -/
theorem c_transposition_chebotarev
    {frobeniusClass : HeightOneSpectrum (𝓞 K) →
      Option (ConjClasses cubicC2)}
    (hcheb : ChebotarevDensityProperty K frobeniusClass) :
    PNDensit K
      (primesFrobeniusClass K frobeniusClass
        (ConjClasses.mk cubicCSwap)) (1 / 2) := by
  simpa using quadratic_density_chebotarev K hcheb cubic_c_card
    cubicCSwap

/-- The identity class in an abelian group of order three has density `1/3`.
This is the completely split entry in Milne's `A₃` cubic row. -/
theorem identity_density_chebotarev
    {G : Type*} [CommGroup G] [Finite G]
    {frobeniusClass : HeightOneSpectrum (𝓞 K) → Option (ConjClasses G)}
    (hcheb : ChebotarevDensityProperty K frobeniusClass)
    (hcard : Nat.card G = 3) :
    PNDensit K
      (primesFrobeniusClass K frobeniusClass (ConjClasses.mk 1))
      (1 / 3) := by
  simpa [hcard] using identity_frobenius_density K hcheb

/-- Two distinct Frobenius elements in an abelian group of order three occur
together with density `2/3`.  For `A₃`, these are the two three-cycles and
give the irreducible entry in Milne's cubic table. -/
theorem classes_density_chebotarev
    {G : Type*} [CommGroup G] [Finite G]
    {frobeniusClass : HeightOneSpectrum (𝓞 K) → Option (ConjClasses G)}
    (hcheb : ChebotarevDensityProperty K frobeniusClass)
    (hcard : Nat.card G = 3) {sigma tau : G} (hne : sigma ≠ tau) :
    PNDensit K
      (primesFrobeniusClass K frobeniusClass (ConjClasses.mk sigma) ∪
        primesFrobeniusClass K frobeniusClass (ConjClasses.mk tau))
      (2 / 3) := by
  have hclass_ne : ConjClasses.mk sigma ≠ ConjClasses.mk tau := by
    intro h
    rw [ConjClasses.mk_eq_mk_iff_isConj, isConj_iff_eq] at h
    exact hne h
  have hdisj := disjoint_primes_frobenius K
    (frobeniusClass := frobeniusClass) hclass_ne
  have hSigma := abelian_density_chebotarev K hcheb sigma
  have hTau := abelian_density_chebotarev K hcheb tau
  rw [hcard] at hSigma hTau
  have hUnion := hSigma.union_of_disjoint K hTau hdisj
  convert hUnion using 1 ; norm_num

/-- The completely split row of Milne's `S₃` cubic table has density `1/6`. -/
theorem s_3_identity
    {frobeniusClass : HeightOneSpectrum (𝓞 K) →
      Option (ConjClasses (Equiv.Perm (Fin 3)))}
    (hcheb : ChebotarevDensityProperty K frobeniusClass) :
    PNDensit K
      (primesFrobeniusClass K frobeniusClass (ConjClasses.mk 1))
      (1 / 6) := by
  simpa [s3_card] using identity_frobenius_density K hcheb

/-- The linear-times-quadratic row of Milne's `S₃` cubic table has density
`1/2`. -/
theorem s_3_transposition
    {frobeniusClass : HeightOneSpectrum (𝓞 K) →
      Option (ConjClasses (Equiv.Perm (Fin 3)))}
    (hcheb : ChebotarevDensityProperty K frobeniusClass)
    (g : Equiv.Perm (Fin 3)) (hg : g.cycleType = {2}) :
    PNDensit K
      (primesFrobeniusClass K frobeniusClass (ConjClasses.mk g))
      (1 / 2) := by
  have h := hcheb (ConjClasses.mk g)
  rw [s_transposition_ncard g hg, s3_card] at h
  convert h using 1 ; norm_num

/-- The irreducible row of Milne's `S₃` cubic table has density `1/3`. -/
theorem s_3_chebotarev
    {frobeniusClass : HeightOneSpectrum (𝓞 K) →
      Option (ConjClasses (Equiv.Perm (Fin 3)))}
    (hcheb : ChebotarevDensityProperty K frobeniusClass)
    (g : Equiv.Perm (Fin 3)) (hg : g.cycleType = {3}) :
    PNDensit K
      (primesFrobeniusClass K frobeniusClass (ConjClasses.mk g))
      (1 / 3) := by
  have h := hcheb (ConjClasses.mk g)
  rw [s_3_ncard g hg, s3_card] at h
  convert h using 1 ; norm_num

end

end Submission.NumberTheory.Milne
