import Submission.ClassField.RayClassGroups.ForbiddenIdeal
import Submission.ClassField.Ideles.GlobalPlace
import Submission.ClassField.Ideles.IdeleIdealMap

/-!
# Chapter VII, Section 4, Lemma 4.2

If a finite set `S` contains every infinite place and finite primes whose
classes generate the ideal class group, then every idèle is a product of a
principal idèle and an idèle which is a unit outside `S`.
-/

namespace Submission.CField.NIndex

open IsDedekindDomain NumberField
open Submission.NumberTheory.Milne
open Submission.CField.Ideles
open scoped nonZeroDivisors

noncomputable section

universe u

variable (K : Type u) [Field K] [NumberField K]

private abbrev OK := NumberField.RingOfIntegers K
private abbrev IK := IdeleGroup (OK K) K
private abbrev FI := (FractionalIdeal (OK K)⁰ K)ˣ

/-- The nonzero fractional ideal represented by a finite prime. -/
def fractionalIdealPrime
    (p : HeightOneSpectrum (OK K)) : FI K :=
  FractionalIdeal.mk0 K
    ⟨p.asIdeal, mem_nonZeroDivisors_iff_ne_zero.mpr p.ne_bot⟩

/-- The subgroup of fractional ideals generated by the finite members of
`S`.  These are exactly the fractional ideals supported on `S`. -/
def fractionalIdealsPlaces
    (S : Finset (NumberFieldPlace K)) : Subgroup (FI K) :=
  Subgroup.closure
    {I | ∃ p : HeightOneSpectrum (OK K),
      (Sum.inl p : NumberFieldPlace K) ∈ S ∧
        I = fractionalIdealPrime K p}

/-- The source hypothesis `S ⊇ S_∞`. -/
def ContainsAllPlaces (S : Finset (NumberFieldPlace K)) : Prop :=
  ∀ v : InfinitePlace K, (Sum.inr v : NumberFieldPlace K) ∈ S

/-- The source hypothesis that `S` contains a set of prime-ideal generators
for the ideal class group.  It says precisely that the classes of the finite
primes belonging to `S` generate the whole class group. -/
def CIGenera
    (S : Finset (NumberFieldPlace K)) : Prop :=
  Subgroup.map (ClassGroup.mk (R := OK K) (K := K))
      (fractionalIdealsPlaces K S) = ⊤

/-- Milne's `ℐ_S`: idèles which are local units at every finite place
outside `S`.  Infinite coordinates are unrestricted; the source separately
assumes that all infinite places belong to `S`. -/
def idelesAtPlaces
    (S : Finset (NumberFieldPlace K)) : Subgroup (IK K) where
  carrier := {x | ∀ p : HeightOneSpectrum (OK K),
    (Sum.inl p : NumberFieldPlace K) ∉ S →
      x.2.1 p ∈ IdeleUnitSubgroup (OK K) K p}
  one_mem' := by
    intro p hp
    exact (IdeleUnitSubgroup (OK K) K p).one_mem
  mul_mem' := by
    intro x y hx hy p hp
    exact (IdeleUnitSubgroup (OK K) K p).mul_mem
      (hx p hp) (hy p hp)
  inv_mem' := by
    intro x hx p hp
    exact (IdeleUnitSubgroup (OK K) K p).inv_mem (hx p hp)

/-- The finite-place compatibility of Statement V.4.1 needed here: being a
unit outside `S` is equivalent to the attached fractional ideal being
supported on `S`.  Statement 4.1 constructs both sides, but this restriction
identity is not yet exported by the completed-valuation API. -/
def IdeleSupportBridge : Prop :=
  ∀ (K : Type u) [Field K] [NumberField K]
    (S : Finset (NumberFieldPlace K)),
    idelesAtPlaces K S =
      (fractionalIdealsPlaces K S).comap
        (ideleIdealMap (OK K) K)

/-- The diagonal compatibility needed in the proof: the ideal attached to a
principal idèle is its principal fractional ideal. -/
def PrincipalIdeleBridge : Prop :=
  ∀ (K : Type u) [Field K] [NumberField K] (a : Kˣ),
    ideleIdealMap (OK K) K (principalIdele (OK K) K a) =
      toPrincipalIdeal (OK K) K a

/-- Lemma 4.2 from the two precise local compatibilities of the canonical
idèle-to-ideal map.  The ideal-class-generator argument is proved here. -/
theorem fractional_ideal_prime
    (hsupport : IdeleSupportBridge.{u})
    (hprincipal : PrincipalIdeleBridge.{u}) :
    (∀ (K : Type u) [Field K] [NumberField K]
          (S : Finset (NumberFieldPlace K)),
          ContainsAllPlaces K S →
            CIGenera K S →
            principalIdeles (OK K) K ⊔ idelesAtPlaces K S = ⊤) := by
  intro K _ _ S _hInfinite hgenerators
  apply top_unique
  intro x hx
  let classMap : FI K →* ClassGroup (OK K) :=
    ClassGroup.mk (R := OK K) (K := K)
  let P := fractionalIdealsPlaces K S
  let I : FI K := ideleIdealMap (OK K) K x
  have hclass : classMap I ∈ Subgroup.map classMap P := by
    rw [hgenerators]
    trivial
  obtain ⟨J, hJP, hJI⟩ := hclass
  have hprincipalClass : classMap (I * J⁻¹) = 1 := by
    rw [map_mul, map_inv, hJI]
    exact mul_inv_cancel _
  have hprincipalSubmodule :
      (((I * J⁻¹ : FI K) : FractionalIdeal (OK K)⁰ K) :
        Submodule (OK K) K).IsPrincipal := by
    exact ClassGroup.mk_eq_one_iff.mp hprincipalClass
  obtain ⟨a, ha⟩ :=
    (FractionalIdeal.isPrincipal_iff
      ((I * J⁻¹ : FI K) : FractionalIdeal (OK K)⁰ K)).mp
      hprincipalSubmodule
  have ha0 : a ≠ 0 := by
    intro ha0
    subst a
    rw [FractionalIdeal.spanSingleton_zero] at ha
    exact (I * J⁻¹).ne_zero ha
  let au : Kˣ := Units.mk0 a ha0
  have hau : toPrincipalIdeal (OK K) K au = I * J⁻¹ := by
    apply Units.ext
    simpa [au] using ha.symm
  let p : IK K := principalIdele (OK K) K au
  let y : IK K := p⁻¹ * x
  have hyIdeal : ideleIdealMap (OK K) K y = J := by
    change ideleIdealMap (OK K) K
        ((principalIdele (OK K) K au)⁻¹ * x) = J
    rw [map_mul, map_inv, hprincipal K au, hau]
    change (I * J⁻¹)⁻¹ * I = J
    simp only [mul_inv_rev, inv_inv]
    group
  have hp : p ∈ principalIdeles (OK K) K := by
    exact ⟨au, rfl⟩
  have hy : y ∈ idelesAtPlaces K S := by
    rw [hsupport K S]
    change ideleIdealMap (OK K) K y ∈ P
    rw [hyIdeal]
    exact hJP
  have hpmem : p ∈
      principalIdeles (OK K) K ⊔ idelesAtPlaces K S :=
    (le_sup_left : principalIdeles (OK K) K ≤
      principalIdeles (OK K) K ⊔ idelesAtPlaces K S) hp
  have hymem : y ∈
      principalIdeles (OK K) K ⊔ idelesAtPlaces K S :=
    (le_sup_right : idelesAtPlaces K S ≤
      principalIdeles (OK K) K ⊔ idelesAtPlaces K S) hy
  have hxy :=
    (principalIdeles (OK K) K ⊔ idelesAtPlaces K S).mul_mem
      hpmem hymem
  simpa [p, y] using hxy

end

end Submission.CField.NIndex
