import Submission.ClassField.KummerNormIndex.GeneratedPthRoots
import Submission.ClassField.NormIndex.CyclicSubextensionData

/-!
# Chapter VII, Section 6, Proposition 6.10

Let `K` contain a primitive `n`th root of unity.  For suitable disjoint sets
of places `S` and `T`, Milne uses the surjection

`U(S) → ∏ P ∈ T, U_P / U_P^n`

to prove an idèle factorization.  Applied to `L = K[b^(1/n)]`, Lemma 4.5
then shows that `L = K`, and hence that `b` is an `n`th power in `K`.

The actual local-unit map from Lemma 6.9 and the actual idèle groups are used
below.  The idèle factorization is proved outright.  Two arithmetic steps
remain as narrow bridges:

* construction of the Kummer extension generated by an `n`th root of `b`;
* inclusion of the concrete subgroup `D` in the idèle norm range, obtained
  from the three local norm calculations in the printed proof.
-/

namespace Submission.CField.KNIndex

open IsDedekindDomain NumberField
open Submission.NumberTheory.Milne
open Submission.CField.Ideles
open Submission.CField.HQuotie
open Submission.CField.NIndex

noncomputable section

universe u

private abbrev OK (K : Type u) [Field K] [NumberField K] :=
  NumberField.RingOfIntegers K

private abbrev IK (K : Type u) [Field K] [NumberField K] :=
  IdeleGroup (OK K) K

/-- The literal assertion that `b` is an `n`th power in the completion at a
finite or infinite number-field place. -/
def nthPowerPlace
    (K : Type u) [Field K] [NumberField K]
    (n : ℕ) (b : Kˣ) : NumberFieldPlace K → Prop
  | .inl P => ∃ x : P.adicCompletion K,
      x ^ n = algebraMap K (P.adicCompletion K) (b : K)
  | .inr v => ∃ x : v.Completion,
      x ^ n = algebraMap K v.Completion (b : K)

/-- The source condition that `b` is a unit at every finite prime outside
`S ∪ T`, expressed by its normalized finite valuation. -/
def nthPlaceOutside
    (K : Type u) [Field K] [NumberField K]
    (b : Kˣ) (S : Finset (NumberFieldPlace K))
    (T : Finset (FinitePrime K)) : Prop :=
  ∀ P : FinitePrime K,
    (Sum.inl P : NumberFieldPlace K) ∉ combinedPlaces K S T →
      P.valuation K b = 1

/-- At `P ∈ T`, an idèle belonging to `I_S` has a local-unit coordinate.
This is that coordinate, regarded as an element of the literal ring-unit
group `(P.adicCompletionIntegers K)ˣ`. -/
noncomputable def restrictedIdeleHom
    (K : Type u) [Field K] [NumberField K]
    (S : Finset (NumberFieldPlace K)) (T : Finset (FinitePrime K))
    (hDisjoint : ∀ P : FinitePrime K, P ∈ T →
      (Sum.inl P : NumberFieldPlace K) ∉ S)
    (P : T) :
    idelesAtPlaces K S →* (P.1.adicCompletionIntegers K)ˣ :=
  (P.1.adicCompletionIntegers K).unitsEquivUnitsType.toMonoidHom.comp
    { toFun := fun a =>
        ⟨a.1.2.1 P.1, a.2 P.1 (hDisjoint P.1 P.2)⟩
      map_one' := by
        apply Subtype.ext
        rfl
      map_mul' := fun _ _ => by
        apply Subtype.ext
        rfl }

/-- The quotient map from `I_S` to the product of the local-unit groups
modulo `n`th powers at `T`. -/
noncomputable def restrictedIdeleClass
    (K : Type u) [Field K] [NumberField K]
    (n : ℕ) (S : Finset (NumberFieldPlace K))
    (T : Finset (FinitePrime K))
    (hDisjoint : ∀ P : FinitePrime K, P ∈ T →
      (Sum.inl P : NumberFieldPlace K) ∉ S) :
    idelesAtPlaces K S →*
      localUnitClasses K n T :=
  Pi.monoidHom fun P =>
    (QuotientGroup.mk'
      (pthPowerSubgroup n (P.1.adicCompletionIntegers K)ˣ)).comp
        (restrictedIdeleHom
          K S T hDisjoint P)

/-- The diagonal embedding `U(S) → I_S`. -/
noncomputable def principalSHom
    (K : Type u) [Field K] [NumberField K]
    (S : Finset (NumberFieldPlace K)) :
    ArithmeticSUnits K (finitePrimePart K S) →*
      idelesAtPlaces K S where
  toFun x :=
    ⟨principalIdele (OK K) K (x : Kˣ), by
      intro P hP
      rw [principal_idele_finite]
      exact (place_embedding_subgroup
        (L := K) P (x : Kˣ)).2 (x.property P hP)⟩
  map_one' := by
    apply Subtype.ext
    exact map_one (principalIdele (OK K) K)
  map_mul' x y := by
    apply Subtype.ext
    exact map_mul (principalIdele (OK K) K) (x : Kˣ) (y : Kˣ)

/-- On principal `S`-idèles, the restricted idèle class map is exactly the
obvious map of Lemma 6.9. -/
theorem restricted_idele_principal
    (K : Type u) [Field K] [NumberField K]
    (n : ℕ) (S : Finset (NumberFieldPlace K))
    (T : Finset (FinitePrime K))
    (hDisjoint : ∀ P : FinitePrime K, P ∈ T →
      (Sum.inl P : NumberFieldPlace K) ∉ S)
    (x : ArithmeticSUnits K (finitePrimePart K S)) :
    restrictedIdeleClass K n S T hDisjoint
        (principalSHom K S x) =
      obviousMap K n S T hDisjoint x := by
  funext P
  rfl

set_option synthInstance.maxHeartbeats 300000 in
-- The kernel subgroup is built from a dependent product of local power-class
-- quotients whose group instances require deeper search.
/-- Milne's subgroup

`D = ∏_{v∈S} K_vˣ × ∏_{P∈T} U_P^n × ∏_{P∉S∪T} U_P`.

Inside `I_S`, it is exactly the kernel of the local class map.  Mapping that
kernel into the full idèle group gives the literal global subgroup `D`. -/
def nthIdeleSubgroup
    (K : Type u) [Field K] [NumberField K]
    (n : ℕ) (S : Finset (NumberFieldPlace K))
    (T : Finset (FinitePrime K))
    (hDisjoint : ∀ P : FinitePrime K, P ∈ T →
      (Sum.inl P : NumberFieldPlace K) ∉ S) :
    Subgroup (IK K) :=
  (restrictedIdeleClass K n S T hDisjoint).ker.map
    (idelesAtPlaces K S).subtype

set_option synthInstance.maxHeartbeats 300000 in
-- The subgroup factorization uses the dependent local quotient map throughout
-- its kernel and supremum calculations.
/-- Surjectivity in Lemma 6.9 proves the source's equality
`I_S = D · U(S)`, here in the form needed inside the full idèle group. -/
theorem ideles_d_principal
    (K : Type u) [Field K] [NumberField K]
    (n : ℕ) (S : Finset (NumberFieldPlace K))
    (T : Finset (FinitePrime K))
    (hDisjoint : ∀ P : FinitePrime K, P ∈ T →
      (Sum.inl P : NumberFieldPlace K) ∉ S)
    (hsurjective :
      Function.Surjective (obviousMap K n S T hDisjoint)) :
    idelesAtPlaces K S ≤
      nthIdeleSubgroup K n S T hDisjoint ⊔
        principalIdeles (OK K) K := by
  intro a ha
  let aS : idelesAtPlaces K S := ⟨a, ha⟩
  obtain ⟨x, hx⟩ := hsurjective
    (restrictedIdeleClass K n S T hDisjoint aS)
  let y := principalSHom K S x
  let d : idelesAtPlaces K S := aS * y⁻¹
  have hd : d ∈
      (restrictedIdeleClass K n S T hDisjoint).ker := by
    rw [MonoidHom.mem_ker]
    change restrictedIdeleClass K n S T hDisjoint
        (aS * y⁻¹) = 1
    rw [map_mul, map_inv]
    have hy : restrictedIdeleClass K n S T hDisjoint y =
        restrictedIdeleClass K n S T hDisjoint aS := by
      rw [restricted_idele_principal]
      exact hx
    rw [hy]
    simp
  have hdGlobal : (d : IK K) ∈
      nthIdeleSubgroup K n S T hDisjoint :=
    ⟨d, hd, rfl⟩
  have hyGlobal : (y : IK K) ∈ principalIdeles (OK K) K :=
    ⟨(x : Kˣ), rfl⟩
  have hprod :=
    (nthIdeleSubgroup K n S T hDisjoint ⊔
      principalIdeles (OK K) K).mul_mem
        ((le_sup_left : nthIdeleSubgroup K n S T hDisjoint ≤
          nthIdeleSubgroup K n S T hDisjoint ⊔
            principalIdeles (OK K) K) hdGlobal)
        ((le_sup_right : principalIdeles (OK K) K ≤
          nthIdeleSubgroup K n S T hDisjoint ⊔
            principalIdeles (OK K) K) hyGlobal)
  simpa [d, y, aS] using hprod

set_option synthInstance.maxHeartbeats 300000 in
-- Combining the idèle subgroup with the principal subgroup repeatedly
-- resolves the dependent local power-class product.
/-- Combining the preceding factorization with Lemma 4.2 gives the source's
condition `(b)`: `D · Kˣ = I_K`. -/
theorem idele_factorization
    (h42 : (∀ (K : Type u) [Field K] [NumberField K]
          (S : Finset (NumberFieldPlace K)),
          ContainsAllPlaces K S →
            CIGenera K S →
            principalIdeles (OK K) K ⊔ idelesAtPlaces K S = ⊤))
    (K : Type u) [Field K] [NumberField K]
    (n : ℕ) (S : Finset (NumberFieldPlace K))
    (T : Finset (FinitePrime K))
    (hInfinite : ContainsAllPlaces K S)
    (hClass : CIGenera K S)
    (hDisjoint : ∀ P : FinitePrime K, P ∈ T →
      (Sum.inl P : NumberFieldPlace K) ∉ S)
    (hsurjective :
      Function.Surjective (obviousMap K n S T hDisjoint)) :
    principalIdeles (OK K) K ⊔
        nthIdeleSubgroup K n S T hDisjoint = ⊤ := by
  rw [← h42 K S hInfinite hClass]
  apply le_antisymm
  · apply sup_le
    · exact le_sup_left
    · rintro a ⟨d, _hd, rfl⟩
      exact (le_sup_right : idelesAtPlaces K S ≤
        principalIdeles (OK K) K ⊔ idelesAtPlaces K S) d.property
  · apply sup_le
    · exact le_sup_left
    · simpa [sup_comm] using
      ideles_d_principal
        K n S T hDisjoint hsurjective

/-- The concrete Kummer extension `K[b^(1/n)]` needed in the proof.  The
last field records literally that the chosen root generates the extension. -/
structure KEData
    (K : Type u) [Field K] [NumberField K]
    (n : ℕ) (b : Kˣ) where
  L : Type u
  fieldL : Field L
  numberFieldL : NumberField L
  algebraKL : Algebra K L
  finiteDimensionalKL : FiniteDimensional K L
  isGaloisKL : IsGalois K L
  isSolvableGal : IsSolvable Gal(L/K)
  root : L
  root_pow : root ^ n = algebraMap K L (b : K)
  adjoin_root_top : IntermediateField.adjoin K {root} = ⊤

/-- Construction of `K[b^(1/n)]` as a finite solvable Galois extension when
`K` contains a primitive `n`th root.  This is the Kummer-extension input,
not the proposition's desired conclusion. -/
def KummerExtensionBridge : Prop :=
  ∀ (n : ℕ) (K : Type u) [Field K] [NumberField K] (b : Kˣ),
    (primitiveRoots n K).Nonempty →
      Nonempty (KEData K n b)

/-- The local norm calculation denoted `(a)` in the source proof.

At places in `S` the Kummer extension splits because `b` is locally an
`n`th power; at places in `T`, local reciprocity makes every `n`th power a
norm; outside `S ∪ T`, the extension is unramified and every local unit is a
norm.  The conclusion mentions only the actual idèle norm range. -/
def LocalNormBridge : Prop :=
  ∀ (n : ℕ) (K : Type u) [Field K] [NumberField K]
    (b : Kˣ), (primitiveRoots n K).Nonempty →
    ∀ (S : Finset (NumberFieldPlace K))
    (T : Finset (FinitePrime K))
    (_hInfinite : ContainsAllPlaces K S)
    (_hDividing : ∀ v : NumberFieldPlace K,
      normalizedPlaceValue K v (n : K) ≠ 1 → v ∈ S)
    (hDisjoint : ∀ P : FinitePrime K, P ∈ T →
      (Sum.inl P : NumberFieldPlace K) ∉ S)
    (_hLocal : ∀ v : NumberFieldPlace K, v ∈ S →
      nthPowerPlace K n b v)
    (_hUnit : nthPlaceOutside K b S T)
    (data : KEData K n b),
    letI : Field data.L := data.fieldL
    letI : NumberField data.L := data.numberFieldL
    letI : Algebra K data.L := data.algebraKL
    letI : FiniteDimensional K data.L := data.finiteDimensionalKL
    letI : IsGalois K data.L := data.isGaloisKL
    nthIdeleSubgroup K n S T hDisjoint ≤
      ideleNormSubgroup (K := K) (L := data.L)

/-- Proposition 6.10 from the Kummer-extension construction, the three
local norm calculations, Lemma 4.2, and Lemma 4.5.  The final passage from
degree one to an `n`th root in `K` is proved here. -/
theorem nth_statement_bridges
    (hkummer : KummerExtensionBridge.{u})
    (hnorm : LocalNormBridge.{u})
    (h42 : (∀ (K : Type u) [Field K] [NumberField K]
          (S : Finset (NumberFieldPlace K)),
          ContainsAllPlaces K S →
            CIGenera K S →
            principalIdeles (OK K) K ⊔ idelesAtPlaces K S = ⊤))
    (h45 : (∀ (K L : Type u) [Field K] [Field L] [NumberField K] [NumberField L]
          [Algebra K L] [FiniteDimensional K L] [IsGalois K L]
          [IsSolvable Gal(L/K)],
          ∀ D : Subgroup (IK K),
            D ≤ ideleNormSubgroup (K := K) (L := L) →
            Dense ((principalIdeles (NumberField.RingOfIntegers K) K ⊔ D :
              Subgroup (IK K)) : Set (IK K)) →
            Module.finrank K L = 1)) :
    (∀ (n : ℕ) (K : Type u) [Field K] [NumberField K],
          (primitiveRoots n K).Nonempty →
          ∀ (S : Finset (NumberFieldPlace K)) (T : Finset (FinitePrime K)),
            ContainsAllPlaces K S →
            (∀ v : NumberFieldPlace K,
              normalizedPlaceValue K v (n : K) ≠ 1 → v ∈ S) →
            CIGenera K S →
            ∀ (hDisjoint : ∀ P : FinitePrime K, P ∈ T →
              (Sum.inl P : NumberFieldPlace K) ∉ S),
            Function.Surjective (obviousMap K n S T hDisjoint) →
            ∀ b : Kˣ,
              (∀ v : NumberFieldPlace K, v ∈ S →
                nthPowerPlace K n b v) →
              nthPlaceOutside K b S T →
              b ∈ (powMonoidHom n : Kˣ →* Kˣ).range) := by
  intro n K _ _ hroots S T hInfinite hDividing hClass hDisjoint
    hsurjective b hLocal hUnit
  obtain ⟨data⟩ := hkummer n K b hroots
  letI : Field data.L := data.fieldL
  letI : NumberField data.L := data.numberFieldL
  letI : Algebra K data.L := data.algebraKL
  letI : FiniteDimensional K data.L := data.finiteDimensionalKL
  letI : IsGalois K data.L := data.isGaloisKL
  letI : IsSolvable Gal(data.L/K) := data.isSolvableGal
  let D := nthIdeleSubgroup K n S T hDisjoint
  have htop := idele_factorization h42 K n S T
    hInfinite hClass hDisjoint hsurjective
  have hdense : Dense
      (((principalIdeles (OK K) K ⊔ D : Subgroup (IK K))) : Set (IK K)) := by
    rw [htop]
    exact dense_univ
  have hdegree : Module.finrank K data.L = 1 :=
    h45 K data.L D
    (hnorm n K b hroots S T hInfinite hDividing hDisjoint hLocal hUnit data) hdense
  have hn : n ≠ 0 := by
    intro hn
    subst n
    simp [primitiveRoots_zero] at hroots
  have hroot0 : data.root ≠ 0 := by
    intro hroot0
    apply b.ne_zero
    apply (algebraMap K data.L).injective
    simpa [hroot0, zero_pow hn] using data.root_pow.symm
  obtain ⟨c, hc⟩ :=
    (finrank_eq_one_iff_of_nonzero'
      (K := K) (1 : data.L) one_ne_zero).mp hdegree data.root
  have hc' : algebraMap K data.L c = data.root := by
    simpa [Algebra.smul_def] using hc
  have hc0 : c ≠ 0 := by
    intro hc0
    apply hroot0
    rw [← hc', hc0, map_zero]
  refine ⟨Units.mk0 c hc0, ?_⟩
  apply Units.ext
  change c ^ n = (b : K)
  apply (algebraMap K data.L).injective
  rw [map_pow, hc', data.root_pow]

end

end Submission.CField.KNIndex
