import Submission.ClassField.LubinTate.NatCompX
import Mathlib.RingTheory.Polynomial.Eisenstein.Distinguished
import Mathlib.RingTheory.Valuation.Extension

/-!
# Class Field Theory, Chapter I, Remark 3.1: valuations of roots

The Newton-polygon consequence used in Remark 3.1 can be proved directly by
nonarchimedean dominance.  If a monic polynomial has every coefficient below
the leading one in the maximal ideal, then every root has valuation less than
one (equivalently, positive additive valuation).
-/

namespace Submission.CField.LTate

noncomputable section

open Polynomial
open Submission.CField.FGroups

/-- If all nonleading coefficients of a monic polynomial have valuation less
than one, every root has valuation less than one.  This is the root-valuation
consequence of the Newton polygon used in Remark 3.1. -/
theorem valuation_aeval_monic
    {K L Γ : Type*} [CommRing K] [Field L] [Algebra K L]
    [LinearOrderedCommGroupWithZero Γ]
    (v : Valuation L Γ) {p : K[X]} (hp : p.Monic)
    (hcoeff : ∀ i, i < p.natDegree →
      v (algebraMap K L (p.coeff i)) < 1)
    {x : L} (hx : Polynomial.aeval x p = 0) :
    v x < 1 := by
  by_contra hxlt
  have hxge : 1 ≤ v x := le_of_not_gt hxlt
  have heval : p.eval₂ (algebraMap K L) x = 0 := by
    simpa only [Polynomial.aeval_def] using hx
  have hdominant : v (p.eval₂ (algebraMap K L) x) = v x ^ p.natDegree := by
    rw [Polynomial.eval₂_eq_sum_range]
    calc
      v (∑ i ∈ Finset.range (p.natDegree + 1),
          algebraMap K L (p.coeff i) * x ^ i) =
          v (algebraMap K L (p.coeff p.natDegree) *
            x ^ p.natDegree) := by
        apply v.map_sum_eq_of_lt
        · simp
        · intro i hi
          simp only [Finset.mem_sdiff, Finset.mem_range,
            Finset.mem_singleton] at hi
          have hilow : i < p.natDegree := by omega
          simp only [v.map_mul, v.map_pow, hp.coeff_natDegree,
            map_one, one_mul]
          exact (mul_lt_of_lt_one_left
            (pow_pos (lt_of_lt_of_le zero_lt_one hxge) i)
            (hcoeff i hilow)).trans_le
              (pow_le_pow_right₀ hxge hilow.le)
      _ = v x ^ p.natDegree := by simp [hp.coeff_natDegree]
  rw [heval, v.map_zero] at hdominant
  have hone : (1 : Γ) ≤ v x ^ p.natDegree := one_le_pow₀ hxge
  rw [← hdominant] at hone
  exact (not_le_of_gt zero_lt_one) hone

/-- Reduction modulo an ideal commutes with compositional iteration. -/
theorem iterate_x
    {R S : Type*} [CommSemiring R] [CommSemiring S]
    (φ : R →+* S) (f : R[X]) (n : ℕ) :
    (f.comp^[n] Polynomial.X).map φ =
      (f.map φ).comp^[n] Polynomial.X := by
  induction n with
  | zero => simp
  | succ n ih =>
      rw [Function.iterate_succ_apply', Function.iterate_succ_apply',
        Polynomial.map_comp, ih]

/-- The reduction of an iterate of a distinguished polynomial is the
corresponding power of `X`. -/
theorem iterate_x_distinguished
    {R : Type*} [CommRing R] {I : Ideal R} {f : R[X]}
    (hf : f.IsDistinguishedAt I) (n : ℕ) :
    (f.comp^[n] Polynomial.X).map (Ideal.Quotient.mk I) =
      Polynomial.X ^ (f.natDegree ^ n) := by
  rw [iterate_x]
  induction n with
  | zero => simp
  | succ n ih =>
      rw [Function.iterate_succ_apply', ih, hf.map_eq_X_pow,
        Polynomial.X_pow_comp]
      simp only [← pow_mul, pow_succ]

/-- A positive-degree distinguished polynomial remains distinguished after
every compositional iteration. -/
theorem distinguished_iterate_x
    {R : Type*} [CommRing R] [IsDomain R]
    {I : Ideal R} {f : R[X]} (hf : f.IsDistinguishedAt I)
    (hdeg : f.natDegree ≠ 0) (n : ℕ) :
    (f.comp^[n] Polynomial.X).IsDistinguishedAt I := by
  let g := f.comp^[n] Polynomial.X
  have hgnat : g.natDegree = f.natDegree ^ n :=
    nat_iterate_x f n
  refine ⟨⟨?_⟩, monic_iterate_x hf.monic hdeg n⟩
  intro i hi
  have hmap :=
    iterate_x_distinguished hf n
  have hcoeff := congrArg (fun p : (R ⧸ I)[X] ↦ p.coeff i) hmap
  have hi' : i ≠ f.natDegree ^ n := by
    rw [← hgnat]
    exact ne_of_lt hi
  simp only [Polynomial.coeff_map] at hcoeff
  rw [Polynomial.coeff_X_pow, if_neg hi'] at hcoeff
  exact Ideal.Quotient.eq_zero_iff_mem.mp hcoeff

/-- A monic polynomial which is a Lubin--Tate series is distinguished at the
ideal generated by its uniformizer. -/
theorem distinguished_span_lubin
    {R : Type*} [CommRing R] {pi : R} {q : ℕ} {f : R[X]}
    (hf : LubinSeries pi q (f : PowerSeries R))
    (hmonic : f.Monic) (hdeg : f.natDegree = q) :
    f.IsDistinguishedAt (Ideal.span {pi}) := by
  have hmap : f.map (Ideal.Quotient.mk (Ideal.span {pi})) =
      Polynomial.X ^ q := by
    apply Polynomial.coe_injective
    simpa only [Polynomial.polynomial_map_coe, Polynomial.coe_X,
      Polynomial.coe_pow] using hf.2.2
  refine ⟨⟨?_⟩, hmonic⟩
  intro i hi
  have hcoeff := congrArg
    (fun p : (R ⧸ Ideal.span {pi})[X] ↦ p.coeff i) hmap
  simp only [Polynomial.coeff_map] at hcoeff
  have hi' : i ≠ q := by
    rw [← hdeg]
    exact ne_of_lt hi
  rw [Polynomial.coeff_X_pow, if_neg hi'] at hcoeff
  exact Ideal.Quotient.eq_zero_iff_mem.mp hcoeff

/-- Remark 3.1's root-valuation conclusion for a distinguished polynomial
over a valuation ring and an explicitly chosen extension of the valuation.
Every root of every positive compositional iterate has valuation less than
one, i.e. positive additive valuation. -/
theorem valuation_iterate_x
    {K L ΓK ΓL : Type*} [Field K] [Field L] [Algebra K L]
    [LinearOrderedCommGroupWithZero ΓK]
    [LinearOrderedCommGroupWithZero ΓL]
    (vK : Valuation K ΓK) (vL : Valuation L ΓL)
    [vK.HasExtension vL] [IsScalarTower vK.integer K L]
    {f : vK.integer[X]}
    (hf : f.IsDistinguishedAt
      (IsLocalRing.maximalIdeal vK.integer))
    (hdeg : f.natDegree ≠ 0) (n : ℕ) {x : L}
    (hx : Polynomial.aeval x (f.comp^[n] Polynomial.X) = 0) :
    vL x < 1 := by
  have hiter := distinguished_iterate_x hf hdeg n
  apply valuation_aeval_monic
    (K := vK.integer) vL hiter.monic
  · intro i hi
    have hmem := hiter.mem hi
    have hbase : vK ((f.comp^[n] Polynomial.X).coeff i : K) < 1 :=
      Valuation.Integer.not_isUnit_iff_valuation_lt_one.mp (by
        simpa only [IsLocalRing.mem_maximalIdeal] using hmem)
    have hext :=
      (Valuation.HasExtension.val_map_lt_one_iff vK vL
        ((f.comp^[n] Polynomial.X).coeff i : K)).2 hbase
    simpa only [IsScalarTower.algebraMap_apply vK.integer K L] using hext
  · exact hx

/-- Remark 3.1 for a polynomial Lubin--Tate series.  If `pi` has valuation
less than one, every root of `f^(n)` in any field with an extending valuation
has absolute value (valuation) less than one. -/
theorem valuation_lubin_iterate
    {K L ΓK ΓL : Type*} [Field K] [Field L] [Algebra K L]
    [LinearOrderedCommGroupWithZero ΓK]
    [LinearOrderedCommGroupWithZero ΓL]
    (vK : Valuation K ΓK) (vL : Valuation L ΓL)
    [vK.HasExtension vL] [IsScalarTower vK.integer K L]
    (pi : vK.integer) {q : ℕ} {f : vK.integer[X]}
    (hf : LubinSeries pi q (f : PowerSeries vK.integer))
    (hmonic : f.Monic) (hdeg : f.natDegree = q) (hq : q ≠ 0)
    (hpi : vK (pi : K) < 1)
    (n : ℕ) {x : L}
    (hx : Polynomial.aeval x (f.comp^[n] Polynomial.X) = 0) :
    vL x < 1 := by
  have hdistSpan :=
    distinguished_span_lubin hf hmonic hdeg
  have hdeg0 : f.natDegree ≠ 0 := by
    rw [hdeg]
    exact hq
  have hiter := distinguished_iterate_x hdistSpan hdeg0 n
  apply valuation_aeval_monic
    (K := vK.integer) vL hiter.monic
  · intro i hi
    obtain ⟨a, ha⟩ := Ideal.mem_span_singleton.mp (hiter.mem hi)
    have hbase : vK ((f.comp^[n] Polynomial.X).coeff i : K) < 1 := by
      rw [ha, Subring.coe_mul, vK.map_mul]
      exact mul_lt_one_of_nonneg_of_lt_one_left
        (zero_le' : (0 : ΓK) ≤ vK (pi : K))
        hpi a.2
    have hext :=
      (Valuation.HasExtension.val_map_lt_one_iff vK vL
        ((f.comp^[n] Polynomial.X).coeff i : K)).2 hbase
    simpa only [IsScalarTower.algebraMap_apply vK.integer K L] using hext
  · exact hx

end

end Submission.CField.LTate
