import Submission.ClassField.KummerNormIndex.IdeleSubgroup
import Submission.ClassField.NormLimitation.CoreDefinitions

/-!
# The concrete Kummer subgroup in Lemma VII.9.3

For `T = ∅`, Milne's subgroup `E` consists of local `p`th powers at the
places in `S` and local units away from `S`.  Coordinatewise choices of
`p`th roots at the finitely many places in `S` show that every class
represented by `E` is generated by a global idèle `p`th power and the basic
outside-unit neighborhood.
-/

namespace Submission.CField.NLimita

open IsDedekindDomain NumberField
open Submission.CField.Ideles
open Submission.CField.KNIndex

noncomputable section

universe u

private abbrev OK (K : Type u) [Field K] [NumberField K] :=
  RingOfIntegers K

private abbrev IK (K : Type u) [Field K] [NumberField K] :=
  IdeleGroup (OK K) K

/-- The class subgroup represented by Milne's
`E = ∏_{v∈S} K_v^{×p} × ∏_{v∉S} U_v`. -/
def kummerIdeleClasses
    (K : Type u) [Field K] [NumberField K]
    (p : ℕ) (S : Finset (NumberFieldPlace K)) :
    Subgroup (IdeleClassGroup (OK K) K) :=
  (ideleSubgroup K p S ∅).map
    (QuotientGroup.mk' (principalIdeles (OK K) K))

set_option maxHeartbeats 1000000 in
-- The witness is an idèle assembled from independently chosen roots at the
-- finitely many places in `S`.
/-- The concrete subgroup `E` is generated by global idèle `p`th powers and
the basic outside-unit neighborhood. -/
theorem kummer_classes_core
    (p : ℕ) (K : Type u) [Field K] [NumberField K]
    (S : Finset (NumberFieldPlace K)) :
    kummerIdeleClasses K p S ≤ kummerCore K p S := by
  classical
  let q := QuotientGroup.mk' (principalIdeles (OK K) K)
  rintro c ⟨a, ha, rfl⟩
  let rootInfinite : ∀ v : InfinitePlace K, v.Completionˣ := fun v ↦
    if hv : (Sum.inr v : NumberFieldPlace K) ∈ S then
      Classical.choose (ha.1 v hv)
    else 1
  let rootFinite : ∀ P : HeightOneSpectrum (OK K), (P.adicCompletion K)ˣ := fun P ↦
    if hP : (Sum.inl P : NumberFieldPlace K) ∈ S then
      Classical.choose (ha.2.1 P hP)
    else 1
  have hrootInfinite (v : InfinitePlace K)
      (hv : (Sum.inr v : NumberFieldPlace K) ∈ S) :
      rootInfinite v ^ p = MulEquiv.piUnits a.1 v := by
    simpa only [rootInfinite, dif_pos hv] using
      Classical.choose_spec (ha.1 v hv)
  have hrootFinite (P : HeightOneSpectrum (OK K))
      (hP : (Sum.inl P : NumberFieldPlace K) ∈ S) :
      rootFinite P ^ p = a.2.1 P := by
    simpa only [rootFinite, dif_pos hP] using
      Classical.choose_spec (ha.2.1 P hP)
  have hrootFiniteOutside (P : HeightOneSpectrum (OK K))
      (hP : (Sum.inl P : NumberFieldPlace K) ∉ S) :
      rootFinite P = 1 := by
    simp only [rootFinite, dif_neg hP]
  have hrootFiniteRestricted : ∀ᶠ P in Filter.cofinite,
      rootFinite P ∈ IdeleUnitSubgroup (OK K) K P := by
    rw [Filter.eventually_cofinite]
    refine (S.finite_toSet.preimage Sum.inl_injective.injOn).subset ?_
    intro P hPbad
    change ¬rootFinite P ∈ IdeleUnitSubgroup (OK K) K P at hPbad
    by_contra hP
    exact hPbad (hrootFiniteOutside P hP ▸
      (IdeleUnitSubgroup (OK K) K P).one_mem)
  let bFinite : FiniteIdeles (OK K) K :=
    RestrictedProduct.mk rootFinite hrootFiniteRestricted
  let b : IK K := (MulEquiv.piUnits.symm rootInfinite, bFinite)
  let d : IK K := a * (b ^ p)⁻¹
  have hd : d ∈ outsideNeighborhoodIdeles K S := by
    refine ⟨?_, ?_, ?_⟩
    · intro v hv
      change MulEquiv.piUnits (a.1 * (b.1 ^ p)⁻¹) v = 1
      rw [show MulEquiv.piUnits (a.1 * (b.1 ^ p)⁻¹) v =
          MulEquiv.piUnits a.1 v * MulEquiv.piUnits ((b.1 ^ p)⁻¹) v by
        exact congrFun (map_mul (MulEquiv.piUnits :
          (InfiniteAdeleRing K)ˣ ≃* ((w : InfinitePlace K) → w.Completionˣ))
            a.1 ((b.1 ^ p)⁻¹)) v,
        show MulEquiv.piUnits ((b.1 ^ p)⁻¹) v =
            (MulEquiv.piUnits (b.1 ^ p) v)⁻¹ by
          exact congrFun (map_inv (MulEquiv.piUnits :
            (InfiniteAdeleRing K)ˣ ≃* ((w : InfinitePlace K) → w.Completionˣ))
              (b.1 ^ p)) v,
        show MulEquiv.piUnits (b.1 ^ p) v =
            MulEquiv.piUnits b.1 v ^ p by
          exact congrFun (map_pow (MulEquiv.piUnits :
            (InfiniteAdeleRing K)ˣ ≃* ((w : InfinitePlace K) → w.Completionˣ))
              b.1 p) v]
      change MulEquiv.piUnits a.1 v * (rootInfinite v ^ p)⁻¹ = 1
      rw [hrootInfinite v hv, mul_inv_cancel]
    · intro P hP
      change a.2.1 P * (b.2.1 P ^ p)⁻¹ = 1
      change a.2.1 P * (rootFinite P ^ p)⁻¹ = 1
      rw [hrootFinite P hP, mul_inv_cancel]
    · intro P hP
      change a.2.1 P * (b.2.1 P ^ p)⁻¹ ∈
        IdeleUnitSubgroup (OK K) K P
      rw [show b.2.1 P = rootFinite P from rfl,
        hrootFiniteOutside P hP, one_pow, inv_one, mul_one]
      exact ha.2.2 P hP (by simp)
  have hdecomp : b ^ p * d = a := by
    simp only [d]
    calc
      b ^ p * (a * (b ^ p)⁻¹) = a * (b ^ p * (b ^ p)⁻¹) := by
        ac_rfl
      _ = a := by simp
  apply Subgroup.mem_sup.mpr
  refine ⟨q (b ^ p), ?_, q d, ?_, ?_⟩
  · refine ⟨q b, ?_⟩
    rfl
  · exact ⟨d, hd, rfl⟩
  · rw [← map_mul, hdecomp]

end

end Submission.CField.NLimita
