import Mathlib.RepresentationTheory.Homological.GroupHomology.LowDegree

/-!
# Milne, Class Field Theory, Statement II.2.1

The zeroth homology of a `G`-module is its module of coinvariants.
-/

namespace Submission.CField.TCohomo

open CategoryTheory

variable {G : Type} [Group G]

/-- **Statement II.2.1.** The zeroth integral group homology of `M` is
canonically isomorphic to its module of coinvariants.  The latter is the
quotient of `M` by the submodule generated by the differences `g • m - m`. -/
noncomputable def homologyIsoCoinvariants (M : Rep ℤ G) :
    groupHomology M 0 ≅ (Rep.coinvariantsFunctor ℤ G).obj M :=
  groupHomology.H0Iso M

/-- The isomorphism in Statement II.2.1 is canonical: it carries the usual
map from the coefficient module to `H₀` to the quotient map defining
coinvariants. -/
@[reassoc]
theorem H0π_comp_groupHomologyZeroIsoCoinvariants_hom (M : Rep ℤ G) :
    groupHomology.H0π M ≫ (homologyIsoCoinvariants M).hom =
      (Rep.coinvariantsMk ℤ G).app M := by
  exact groupHomology.H0π_comp_H0Iso_hom M

end Submission.CField.TCohomo
