import Towers.Group.PresentedHilbert


open Filter
open scoped Pointwise EuclideanGeometry Topology BigOperators

noncomputable section

namespace Towers

/--
The relator-difference ideal contains `g - 1` for every element of the normal
closure of the defining relators.

This is the group-algebra form of the elementary fact that the presentation
ideal is closed under products, inverses, and conjugation of relators.
-/
lemma augmentation_difference_closure
    {R α ι : Type*} [CommRing R]
    (rels : ι → FreeGroup α) {g : FreeGroup α}
    (hg : g ∈ Subgroup.normalClosure (Set.range rels)) :
    augmentationDifference R (FreeGroup α) g ∈
      GShafar.relatorDifferenceIdeal (R := R) rels := by
  classical
  let F := FreeGroup α
  let J : Ideal (MonoidAlgebra R F) :=
    GShafar.relatorDifferenceIdeal (R := R) rels
  let N : Subgroup F :=
    { carrier := {g | augmentationDifference R F g ∈ J}
      one_mem' := by
        change augmentationDifference R F 1 ∈ J
        simp [augmentationDifference, MonoidAlgebra.one_def]
      mul_mem' := by
        intro x y hx hy
        change augmentationDifference R F (x * y) ∈ J
        rw [augmentation_difference_left]
        exact J.add_mem hx (J.mul_mem_left _ hy)
      inv_mem' := by
        intro x hx
        change augmentationDifference R F x⁻¹ ∈ J
        rw [difference_inv_neg]
        exact J.mul_mem_left _ hx }
  have hNnormal : N.Normal := by
    refine Subgroup.Normal.mk ?_
    intro n hn a
    change augmentationDifference R F (a * n * a⁻¹) ∈ J
    have hconj :
        augmentationDifference R F (a * n * a⁻¹) =
          MonoidAlgebra.single a (1 : R) *
            augmentationDifference R F n *
              MonoidAlgebra.single a⁻¹ (1 : R) := by
      unfold augmentationDifference
      have hmul₁ :
          MonoidAlgebra.single a (1 : R) *
              MonoidAlgebra.single n (1 : R) =
            MonoidAlgebra.single (a * n) (1 : R) := by
        simp [MonoidAlgebra.single_mul_single]
      have hmul₂ :
          MonoidAlgebra.single (a * n) (1 : R) *
              MonoidAlgebra.single a⁻¹ (1 : R) =
            MonoidAlgebra.single (a * n * a⁻¹) (1 : R) := by
        simp [MonoidAlgebra.single_mul_single, mul_assoc]
      have hone :
          MonoidAlgebra.single a (1 : R) *
              MonoidAlgebra.single a⁻¹ (1 : R) =
            (1 : MonoidAlgebra R F) := by
        have ha : a * a⁻¹ = (1 : F) := mul_inv_cancel a
        rw [MonoidAlgebra.single_mul_single, ha]
        simp [MonoidAlgebra.one_def]
      calc
        MonoidAlgebra.single (a * n * a⁻¹) (1 : R) - 1 =
            (MonoidAlgebra.single a (1 : R) *
                MonoidAlgebra.single n (1 : R)) *
                MonoidAlgebra.single a⁻¹ (1 : R) -
              MonoidAlgebra.single a (1 : R) *
                MonoidAlgebra.single a⁻¹ (1 : R) := by
              rw [hmul₁, hmul₂, hone]
        _ =
            MonoidAlgebra.single a (1 : R) *
              (MonoidAlgebra.single n (1 : R) - 1) *
                MonoidAlgebra.single a⁻¹ (1 : R) := by
              rw [mul_sub, sub_mul, mul_one]
    rw [hconj]
    exact J.mul_mem_right _ (J.mul_mem_left _ hn)
  have hrels_le : Set.range rels ⊆ (N : Set F) := by
    rintro _ ⟨i, rfl⟩
    change
      (MonoidAlgebra.single (rels i) (1 : R) - 1 :
          MonoidAlgebra R F) ∈
        GShafar.relatorDifferenceIdeal (R := R) rels
    change
      (MonoidAlgebra.single (rels i) (1 : R) - 1 :
          MonoidAlgebra R F) ∈
        TwoSidedIdeal.span
          (Set.range fun i =>
            MonoidAlgebra.of R F (rels i) - 1)
    exact TwoSidedIdeal.subset_span ⟨i, by
      simp [MonoidAlgebra.of_apply]⟩
  have hclosure_le : Subgroup.normalClosure (Set.range rels) ≤ N := by
    letI : N.Normal := hNnormal
    exact Subgroup.normalClosure_le_normal hrels_le
  exact hclosure_le hg

/--
The kernel of the canonical free-to-presented group-algebra map is exactly the
two-sided ideal generated by the defining relator differences.

The imported file already proved the easy inclusion from the ideal into the
kernel.  The reverse inclusion is the usual finite-support argument: subtract,
inside each presented-group fibre, a chosen representative; the remaining
terms are multiples of `k - 1` for elements `k` in the normal closure of the
relators, hence lie in the relator-difference ideal.
-/
theorem relator_difference_algebra
    {R α ι : Type*} [CommRing R]
    (rels : ι → FreeGroup α) :
    GShafar.relatorDifferenceIdeal (R := R) rels =
      RingHom.ker
        (GShafar.presentedAlgebra
          (R := R) (Set.range rels)) := by
  classical
  apply le_antisymm
  · exact
      GShafar.difference_presented_algebra
        (R := R) rels
  · intro x hx
    let F := FreeGroup α
    let Q := PresentedGroup (Set.range rels)
    let q : F →* Q := PresentedGroup.mk (Set.range rels)
    let J : Ideal (MonoidAlgebra R F) :=
      GShafar.relatorDifferenceIdeal (R := R) rels
    let sec : Q → F := fun y =>
      Classical.choose (PresentedGroup.mk_surjective (rels := Set.range rels) y)
    have hsec : ∀ y : Q, q (sec y) = y := by
      intro y
      exact Classical.choose_spec (PresentedGroup.mk_surjective (rels := Set.range rels) y)
    let rep : F → F := fun g => sec (q g)
    have hx_map :
        MonoidAlgebra.mapDomain q x = 0 := by
      simpa [GShafar.presentedAlgebra, q] using
        (RingHom.mem_ker.mp hx)
    have hrep_zero :
        MonoidAlgebra.mapDomain rep x = 0 := by
      have hmap :
          Finsupp.mapDomain sec
              (Finsupp.mapDomain (fun g : F => q g) x) = 0 := by
        have hmap' := congrArg (MonoidAlgebra.mapDomain sec) hx_map
        simpa [MonoidAlgebra.mapDomain] using hmap'
      rw [← Finsupp.mapDomain_comp] at hmap
      simpa [MonoidAlgebra.mapDomain, rep, q, Function.comp_def] using hmap
    have hdiff :
        x - MonoidAlgebra.mapDomain rep x ∈ J := by
      refine
        MonoidAlgebra.induction_on
          (p := fun u => u - MonoidAlgebra.mapDomain rep u ∈ J)
          x ?hof ?hadd ?hsmul
      · intro g
        change
          MonoidAlgebra.of R F g -
              MonoidAlgebra.mapDomain rep (MonoidAlgebra.of R F g) ∈ J
        let k : F := (rep g)⁻¹ * g
        have hkq : q k = 1 := by
          dsimp [k, rep]
          rw [map_mul, map_inv, hsec]
          exact inv_mul_cancel (q g)
        have hknormal : k ∈ Subgroup.normalClosure (Set.range rels) := by
          simpa [q, k] using
            (PresentedGroup.mk_eq_one_iff
              (rels := Set.range rels) (x := k)).mp hkq
        have hkJ :
            augmentationDifference R F k ∈ J := by
          simpa [J, F] using
            augmentation_difference_closure
              (R := R) rels hknormal
        have hterm :
          MonoidAlgebra.of R F g -
              MonoidAlgebra.mapDomain rep (MonoidAlgebra.of R F g) =
            MonoidAlgebra.single (rep g) (1 : R) *
              augmentationDifference R F k := by
          dsimp [rep, k]
          rw [MonoidAlgebra.mapDomain_single]
          unfold augmentationDifference
          have hmul :
              MonoidAlgebra.single (sec (q g)) (1 : R) *
                  MonoidAlgebra.single ((sec (q g))⁻¹ * g) (1 : R) =
                MonoidAlgebra.single g (1 : R) := by
            rw [MonoidAlgebra.single_mul_single]
            have hcancel : sec (q g) * ((sec (q g))⁻¹ * g) = g := by
              rw [← mul_assoc, mul_inv_cancel, one_mul]
            rw [hcancel]
            simp
          rw [← hmul]
          rw [mul_sub, mul_one]
        rw [hterm]
        exact J.mul_mem_left _ hkJ
      · intro u v hu hv
        simpa [MonoidAlgebra.mapDomain_add, add_sub_add_comm] using
          J.add_mem hu hv
      · intro c u hu
        have hmap :
            MonoidAlgebra.mapDomain rep (c • u) =
              c • MonoidAlgebra.mapDomain rep u := by
          simpa [MonoidAlgebra.mapDomain] using
            (Finsupp.mapDomain_smul (f := rep) c u)
        rw [hmap]
        have hscalar :
            c • u - c • MonoidAlgebra.mapDomain rep u =
              c • (u - MonoidAlgebra.mapDomain rep u) := by
          simp [smul_sub]
        rw [hscalar]
        simpa [Algebra.smul_def] using
          J.mul_mem_left (algebraMap R (MonoidAlgebra R F) c) hu
    simpa [hrep_zero, J] using hdiff
end Towers
