import Mathlib.NumberTheory.Cyclotomic.Gal
import Mathlib.RingTheory.ZMod.UnitsCyclic
import Mathlib.GroupTheory.Complement
import Mathlib.GroupTheory.Index


/-!
# Milne, Algebraic Number Theory, Exercise 6-3

The odd-prime-power part of the exercise follows from the faithful action on
a primitive root and the cyclicity of units modulo an odd prime power.
-/

namespace Towers.NumberTheory.Milne

open IsCyclotomicExtension
open scoped Cyclotomic

/-- Exercise 6-3, odd-prime-power case, in a form stronger than the printed
tower statement: the automorphism group of any `p^r`-cyclotomic extension is
cyclic when `p` is odd. -/
theorem exercise_six_aut
    {p r : ℕ} (hp : p.Prime) (hp2 : p ≠ 2)
    (K L : Type*) [Field K] [Field L] [Algebra K L]
    [IsCyclotomicExtension {p ^ r} K L] :
    IsCyclic (L ≃ₐ[K] L) := by
  letI : NeZero (p ^ r) := ⟨pow_ne_zero r hp.ne_zero⟩
  letI : IsCyclic (ZMod (p ^ r))ˣ :=
    ZMod.isCyclic_units_of_prime_pow p hp hp2 r
  let zeta := IsCyclotomicExtension.zeta_spec (p ^ r) K L
  apply isCyclic_of_injective (zeta.autToPow K)
  exact IsPrimitiveRoot.autToPow_injective K zeta

section TwoPower

/-- The congruence subgroup of units modulo `2^r` that are `1` modulo `4` is
cyclic.  This is the group generated by `5` in the usual description
`(Z / 2^r Z)ˣ ≅ {±1} × ⟨5⟩`. -/
theorem exercise_six_units
    {r : ℕ} (hr : 2 ≤ r) :
    IsCyclic (ZMod.unitsMap (show 4 ∣ 2 ^ r by
      rw [show 4 = 2 ^ 2 by norm_num]
      exact pow_dvd_pow 2 hr)).ker := by
  let hdiv : 4 ∣ 2 ^ r := by
    rw [show 4 = 2 ^ 2 by norm_num]
    exact pow_dvd_pow 2 hr
  let f : (ZMod (2 ^ r))ˣ →* (ZMod 4)ˣ := ZMod.unitsMap hdiv
  let five : (ZMod (2 ^ r))ˣ :=
    ZMod.unitOfCoprime 5 (by
      apply Nat.Coprime.pow_right
      norm_num)
  have hfive_mem : five ∈ f.ker := by
    rw [MonoidHom.mem_ker]
    apply Units.ext
    change ((5 : ZMod (2 ^ r)).cast : ZMod 4) = 1
    calc
      ((5 : ZMod (2 ^ r)).cast : ZMod 4) = (5 : ZMod 4) :=
        ZMod.cast_natCast hdiv 5
      _ = 1 := by decide
  let fiveKer : f.ker := ⟨five, hfive_mem⟩
  have hr_eq : r - 2 + 2 = r := Nat.sub_add_cancel hr
  have horder : orderOf fiveKer = 2 ^ (r - 2) := by
    rw [Subgroup.orderOf_mk, ← orderOf_injective _ Units.coeHom_injective five]
    change orderOf (5 : ZMod (2 ^ r)) = 2 ^ (r - 2)
    rw [← hr_eq]
    exact ZMod.orderOf_five (r - 2)
  have hcard_domain : Nat.card (ZMod (2 ^ r))ˣ = 2 ^ (r - 1) := by
    rw [Nat.card_eq_fintype_card, ZMod.card_units_eq_totient,
      Nat.totient_prime_pow Nat.prime_two (by omega)]
    norm_num
  have hcard_codomain : Nat.card (ZMod 4)ˣ = 2 := by
    rw [Nat.card_eq_fintype_card, ZMod.card_units_eq_totient]
    decide
  have hsurj : Function.Surjective f := ZMod.unitsMap_surjective hdiv
  have hindex : f.ker.index = 2 := by
    rw [Subgroup.index_ker]
    have hrange : f.range = ⊤ := MonoidHom.range_eq_top.mpr hsurj
    rw [hrange]
    simpa using hcard_codomain
  have hcard_kernel : Nat.card f.ker = 2 ^ (r - 2) := by
    have hmul := f.ker.card_mul_index
    rw [hindex, hcard_domain] at hmul
    have hrpow : 2 ^ (r - 1) = 2 ^ (r - 2) * 2 := by
      rw [← pow_succ]
      congr 1
      omega
    rw [hrpow] at hmul
    omega
  rw [isCyclic_iff_exists_orderOf_eq_natCard]
  exact ⟨fiveKer, horder.trans hcard_kernel.symm⟩

/-- The quotient of `(Z / 2^r Z)ˣ` by its order-two subgroup generated by
`-1` is cyclic.  This is the Galois group of the maximal real fixed field
used in the two-primary part of Lemma VII.7.3. -/
theorem exercise_six_cyclic
    {r : ℕ} (hr : 2 ≤ r) :
    IsCyclic ((ZMod (2 ^ r))ˣ ⧸
      Subgroup.zpowers (-1 : (ZMod (2 ^ r))ˣ)) := by
  letI : NeZero (2 ^ r) := ⟨pow_ne_zero r (by norm_num)⟩
  letI : Fact (1 < 2 ^ r) :=
    ⟨one_lt_pow' (by norm_num) (by omega)⟩
  let U := (ZMod (2 ^ r))ˣ
  let hdiv : 4 ∣ 2 ^ r := by
    rw [show 4 = 2 ^ 2 by norm_num]
    exact pow_dvd_pow 2 hr
  let f : U →* (ZMod 4)ˣ := ZMod.unitsMap hdiv
  let K : Subgroup U := f.ker
  let H : Subgroup U := Subgroup.zpowers (-1 : U)
  have hKcyclic : IsCyclic K := by
    simpa only [K, f] using
      (exercise_six_units (r := r) hr)
  letI : IsCyclic K := hKcyclic
  have hcardU : Nat.card U = 2 ^ (r - 1) := by
    rw [Nat.card_eq_fintype_card, ZMod.card_units_eq_totient,
      Nat.totient_prime_pow Nat.prime_two (by omega)]
    norm_num
  have hcardFour : Nat.card (ZMod 4)ˣ = 2 := by
    rw [Nat.card_eq_fintype_card, ZMod.card_units_eq_totient]
    decide
  have hsurj : Function.Surjective f := ZMod.unitsMap_surjective hdiv
  have hindexK : K.index = 2 := by
    change f.ker.index = 2
    rw [Subgroup.index_ker]
    have hrange : f.range = ⊤ := MonoidHom.range_eq_top.mpr hsurj
    rw [hrange]
    simpa using hcardFour
  have hcardK : Nat.card K = 2 ^ (r - 2) := by
    have hmul := K.card_mul_index
    rw [hindexK, hcardU] at hmul
    have hrpow : 2 ^ (r - 1) = 2 ^ (r - 2) * 2 := by
      rw [← pow_succ]
      congr 1
      omega
    rw [hrpow] at hmul
    omega
  have horderNeg : orderOf (-1 : U) = 2 := by
    rw [← orderOf_units, Units.coe_neg_one, orderOf_neg_one,
      ringChar.eq (ZMod (2 ^ r)) (2 ^ r), if_neg]
    omega
  have hcardH : Nat.card H = 2 := by
    change Nat.card (Subgroup.zpowers (-1 : U)) = 2
    rw [Nat.card_zpowers, horderNeg]
  have hnegNotK : (-1 : U) ∉ K := by
    change f (-1 : U) ≠ 1
    intro h
    have hv := congrArg Units.val h
    change ((-1 : ZMod (2 ^ r)).cast : ZMod 4) = 1 at hv
    have hcast : ((-1 : ZMod (2 ^ r)).cast : ZMod 4) = -1 := by
      rw [ZMod.cast_neg hdiv, ZMod.cast_one hdiv]
    rw [hcast] at hv
    exact (by decide : (-1 : ZMod 4) ≠ 1) hv
  have hdisjoint : Disjoint K H := by
    rw [Subgroup.disjoint_def]
    intro x hxK hxH
    by_contra hxone
    let xH : H := ⟨x, hxH⟩
    let negH : H := ⟨-1, Subgroup.mem_zpowers (-1 : U)⟩
    have hxH_ne : xH ≠ 1 := by
      intro hx
      exact hxone (congrArg Subtype.val hx)
    have hnegH_ne : negH ≠ 1 := by
      intro hneg
      apply hnegNotK
      have hnegone : (-1 : U) = 1 := congrArg Subtype.val hneg
      rw [hnegone]
      exact K.one_mem
    have htwo := Classical.choose_spec
      ((Nat.card_eq_two_iff' (1 : H)).mp hcardH)
    have hxeqH : xH = negH :=
      (htwo.2 xH hxH_ne).trans (htwo.2 negH hnegH_ne).symm
    have hxeq : x = (-1 : U) := congrArg Subtype.val hxeqH
    exact hnegNotK (hxeq ▸ hxK)
  have hcardMul : Nat.card K * Nat.card H = Nat.card U := by
    rw [hcardK, hcardH, hcardU, ← pow_succ]
    congr 1
    omega
  have hcomplement : K.IsComplement' H :=
    Subgroup.isComplement'_of_card_mul_and_disjoint hcardMul hdisjoint
  letI : H.Normal := by infer_instance
  exact hcomplement.QuotientMulEquiv.isCyclic.mpr inferInstance

/-- The order-two element obtained by multiplying complex conjugation by
the unique order-two element in the cyclic `1 mod 4` factor of
`(Z / 2^r Z)ˣ`.  Its fixed field is the complex cyclic two-primary field
needed in Lemma VII.7.3. -/
noncomputable def exercise_six_diagonal (r : ℕ) :
    (ZMod (2 ^ r))ˣ :=
  -1 * (ZMod.unitOfCoprime 5 (by
    apply Nat.Coprime.pow_right
    norm_num) : (ZMod (2 ^ r))ˣ) ^ (2 ^ (r - 3))

/-- The diagonal order-two subgroup in the standard decomposition
`(Z / 2^r Z)ˣ ≅ C₂ × C_(2^(r-2))`. -/
noncomputable def exercise_six_subgroup (r : ℕ) :
    Subgroup (ZMod (2 ^ r))ˣ :=
  Subgroup.zpowers (exercise_six_diagonal r)

/-- For `r ≥ 3`, the diagonal subgroup has order two, does not contain
complex conjugation, and has cyclic quotient.  In contrast to quotienting
by `<-1>`, this is the group-theoretic choice whose fixed field is totally
complex. -/
theorem exercise_six_spec
    {r : ℕ} (hr : 3 ≤ r) :
    Nat.card (exercise_six_subgroup r) = 2 ∧
      (-1 : (ZMod (2 ^ r))ˣ) ∉
        exercise_six_subgroup r ∧
      IsCyclic ((ZMod (2 ^ r))ˣ ⧸
        exercise_six_subgroup r) := by
  letI : NeZero (2 ^ r) := ⟨pow_ne_zero r (by norm_num)⟩
  letI : Fact (1 < 2 ^ r) :=
    ⟨one_lt_pow' (by norm_num) (by omega)⟩
  let U := (ZMod (2 ^ r))ˣ
  let hdiv : 4 ∣ 2 ^ r := by
    rw [show 4 = 2 ^ 2 by norm_num]
    exact pow_dvd_pow 2 (by omega)
  let f : U →* (ZMod 4)ˣ := ZMod.unitsMap hdiv
  let K : Subgroup U := f.ker
  let five : U :=
    ZMod.unitOfCoprime 5 (by
      apply Nat.Coprime.pow_right
      norm_num)
  have hfiveK : five ∈ K := by
    rw [MonoidHom.mem_ker]
    apply Units.ext
    change ((5 : ZMod (2 ^ r)).cast : ZMod 4) = 1
    calc
      ((5 : ZMod (2 ^ r)).cast : ZMod 4) = (5 : ZMod 4) :=
        ZMod.cast_natCast hdiv 5
      _ = 1 := by decide
  let fiveK : K := ⟨five, hfiveK⟩
  have horderFiveK : orderOf fiveK = 2 ^ (r - 2) := by
    rw [Subgroup.orderOf_mk, ← orderOf_injective _ Units.coeHom_injective five]
    change orderOf (5 : ZMod (2 ^ r)) = 2 ^ (r - 2)
    have hr_eq : r - 2 + 2 = r := Nat.sub_add_cancel (by omega)
    rw [← hr_eq]
    exact ZMod.orderOf_five (r - 2)
  have horderFive : orderOf five = 2 ^ (r - 2) := by
    exact (Subgroup.orderOf_mk five hfiveK).symm.trans horderFiveK
  let half : U := five ^ (2 ^ (r - 3))
  have hhalfK : half ∈ K := K.pow_mem hfiveK _
  have hhalf_sq : half ^ 2 = 1 := by
    have hfivePow : five ^ (2 ^ (r - 2)) = 1 := by
      rw [← horderFive]
      exact pow_orderOf_eq_one five
    calc
      half ^ 2 = five ^ (2 ^ (r - 3) * 2) := by
        rw [pow_mul]
      _ = five ^ (2 ^ (r - 2)) := by
        congr 1
        rw [← pow_succ]
        congr 1
        omega
      _ = 1 := hfivePow
  have hhalf_ne : half ≠ 1 := by
    intro hhalf
    have hdvd : 2 ^ (r - 2) ∣ 2 ^ (r - 3) := by
      rw [← horderFive]
      exact orderOf_dvd_iff_pow_eq_one.mpr hhalf
    have hle : 2 ^ (r - 2) ≤ 2 ^ (r - 3) :=
      Nat.le_of_dvd (pow_pos (by norm_num) _) hdvd
    have hlt : 2 ^ (r - 3) < 2 ^ (r - 2) := by
      exact Nat.pow_lt_pow_right (by norm_num) (by omega)
    omega
  let diagonal : U := -1 * half
  let D : Subgroup U := Subgroup.zpowers diagonal
  have hdiag_sq : diagonal ^ 2 = 1 := by
    dsimp only [diagonal]
    rw [mul_pow]
    have hnegSq : (-1 : U) ^ 2 = 1 := by
      apply Units.ext
      change (-1 : ZMod (2 ^ r)) ^ 2 = 1
      ring
    rw [hnegSq, hhalf_sq, one_mul]
  have hcardU : Nat.card U = 2 ^ (r - 1) := by
    rw [Nat.card_eq_fintype_card, ZMod.card_units_eq_totient,
      Nat.totient_prime_pow Nat.prime_two (by omega)]
    norm_num
  have hcardFour : Nat.card (ZMod 4)ˣ = 2 := by
    rw [Nat.card_eq_fintype_card, ZMod.card_units_eq_totient]
    decide
  have hsurjF : Function.Surjective f := ZMod.unitsMap_surjective hdiv
  have hindexK : K.index = 2 := by
    change f.ker.index = 2
    rw [Subgroup.index_ker]
    have hrange : f.range = ⊤ := MonoidHom.range_eq_top.mpr hsurjF
    rw [hrange]
    simpa using hcardFour
  have hcardK : Nat.card K = 2 ^ (r - 2) := by
    have hmul := K.card_mul_index
    rw [hindexK, hcardU] at hmul
    have hrpow : 2 ^ (r - 1) = 2 ^ (r - 2) * 2 := by
      rw [← pow_succ]
      congr 1
      omega
    rw [hrpow] at hmul
    omega
  have hnegNotK : (-1 : U) ∉ K := by
    change f (-1 : U) ≠ 1
    intro h
    have hv := congrArg Units.val h
    change ((-1 : ZMod (2 ^ r)).cast : ZMod 4) = 1 at hv
    have hcast : ((-1 : ZMod (2 ^ r)).cast : ZMod 4) = -1 := by
      rw [ZMod.cast_neg hdiv, ZMod.cast_one hdiv]
    rw [hcast] at hv
    exact (by decide : (-1 : ZMod 4) ≠ 1) hv
  have hdiagNotK : diagonal ∉ K := by
    intro hdiagK
    apply hnegNotK
    have heq : diagonal * half⁻¹ = (-1 : U) := by
      dsimp only [diagonal]
      rw [mul_assoc, mul_inv_cancel, mul_one]
    rw [← heq]
    exact K.mul_mem hdiagK (K.inv_mem hhalfK)
  have hdiag_ne : diagonal ≠ 1 := by
    intro hdiag
    apply hdiagNotK
    rw [hdiag]
    exact K.one_mem
  have hcardD : Nat.card D = 2 := by
    change Nat.card (Subgroup.zpowers diagonal) = 2
    rw [Nat.card_zpowers, orderOf_eq_prime hdiag_sq hdiag_ne]
  have hdisjoint : Disjoint K D := by
    rw [Subgroup.disjoint_def]
    intro x hxK hxD
    by_contra hxone
    let xD : D := ⟨x, hxD⟩
    let diagonalD : D :=
      ⟨diagonal, Subgroup.mem_zpowers diagonal⟩
    have hxD_ne : xD ≠ 1 := by
      intro hx
      exact hxone (congrArg Subtype.val hx)
    have hdiagD_ne : diagonalD ≠ 1 := by
      intro hdiag
      exact hdiag_ne (congrArg Subtype.val hdiag)
    have htwo := Classical.choose_spec
      ((Nat.card_eq_two_iff' (1 : D)).mp hcardD)
    have hxeqD : xD = diagonalD :=
      (htwo.2 xD hxD_ne).trans (htwo.2 diagonalD hdiagD_ne).symm
    apply hdiagNotK
    have hxeq : x = diagonal := congrArg Subtype.val hxeqD
    exact hxeq ▸ hxK
  have hnegNotD : (-1 : U) ∉ D := by
    intro hnegD
    let negD : D := ⟨-1, hnegD⟩
    let diagonalD : D :=
      ⟨diagonal, Subgroup.mem_zpowers diagonal⟩
    have hnegD_ne : negD ≠ 1 := by
      intro hneg
      have hnegOne : (-1 : U) = 1 := congrArg Subtype.val hneg
      apply hnegNotK
      rw [hnegOne]
      exact K.one_mem
    have hdiagD_ne : diagonalD ≠ 1 := by
      intro hdiag
      exact hdiag_ne (congrArg Subtype.val hdiag)
    have htwo := Classical.choose_spec
      ((Nat.card_eq_two_iff' (1 : D)).mp hcardD)
    have hEq : negD = diagonalD :=
      (htwo.2 negD hnegD_ne).trans (htwo.2 diagonalD hdiagD_ne).symm
    have hnegDiag : (-1 : U) = diagonal := congrArg Subtype.val hEq
    apply hhalf_ne
    have := congrArg (fun z : U ↦ (-1 : U) * z) hnegDiag
    simpa [diagonal] using this
  letI : D.Normal := by infer_instance
  let phi : K →* U ⧸ D :=
    (QuotientGroup.mk' D).comp K.subtype
  have hphiInjective : Function.Injective phi := by
    apply (injective_iff_map_eq_one phi).2
    intro x hx
    have hxD : (x : U) ∈ D := by
      exact QuotientGroup.eq_one_iff (x : U) |>.mp hx
    have hxOne : (x : U) = 1 :=
      (Subgroup.disjoint_def.mp hdisjoint) x.2 hxD
    exact Subtype.ext hxOne
  have hcardQuotient : Nat.card (U ⧸ D) = 2 ^ (r - 2) := by
    have hcard := D.card_eq_card_quotient_mul_card_subgroup
    rw [hcardU, hcardD] at hcard
    have hrpow : 2 ^ (r - 1) = 2 ^ (r - 2) * 2 := by
      rw [← pow_succ]
      congr 1
      omega
    rw [hrpow] at hcard
    omega
  have hphiBijective : Function.Bijective phi :=
    (Nat.bijective_iff_injective_and_card phi).mpr
      ⟨hphiInjective, hcardK.trans hcardQuotient.symm⟩
  have hKcyclic : IsCyclic K := by
    simpa only [K, f] using
      (exercise_six_units (r := r) (by omega))
  letI : IsCyclic K := hKcyclic
  have hquotientCyclic : IsCyclic (U ⧸ D) :=
    isCyclic_of_surjective phi hphiBijective.surjective
  change Nat.card (exercise_six_subgroup r) = 2 ∧
    (-1 : U) ∉ exercise_six_subgroup r ∧
      IsCyclic (U ⧸ exercise_six_subgroup r)
  simpa only [exercise_six_subgroup,
    exercise_six_diagonal, diagonal, half, five, D, U]
    using And.intro hcardD (And.intro hnegNotD hquotientCyclic)

/-- Exercise 6-3, two-power case.  If the base field contains a primitive
fourth root of unity, the cyclotomic character of a `2^r`-cyclotomic
extension lands in the cyclic subgroup of units that are `1` modulo `4`. -/
theorem exercise_aut_cyclic
    {r : ℕ} (hr : 2 ≤ r)
    (K L : Type*) [Field K] [Field L] [Algebra K L]
    [IsCyclotomicExtension {2 ^ r} K L]
    (mu : K) (hmu : IsPrimitiveRoot mu 4) :
    IsCyclic (L ≃ₐ[K] L) := by
  letI : NeZero (2 ^ r) := ⟨pow_ne_zero r (by norm_num)⟩
  let hdiv : 4 ∣ 2 ^ r := by
    rw [show 4 = 2 ^ 2 by norm_num]
    exact pow_dvd_pow 2 hr
  let f : (ZMod (2 ^ r))ˣ →* (ZMod 4)ˣ := ZMod.unitsMap hdiv
  let zeta : L := IsCyclotomicExtension.zeta (2 ^ r) K L
  have hzeta : IsPrimitiveRoot zeta (2 ^ r) :=
    IsCyclotomicExtension.zeta_spec (2 ^ r) K L
  let zetaFour : L := zeta ^ (2 ^ (r - 2))
  have hpow_decomp : 2 ^ r = 2 ^ (r - 2) * 4 := by
    rw [show 4 = 2 ^ 2 by norm_num, ← pow_add, Nat.sub_add_cancel hr]
  have hzetaFour : IsPrimitiveRoot zetaFour 4 := by
    exact hzeta.pow (pow_pos (by norm_num) r) hpow_decomp
  have hmuL : IsPrimitiveRoot (algebraMap K L mu) 4 :=
    hmu.map_of_injective (algebraMap K L).injective
  obtain ⟨i, hi, hmu_pow⟩ := hmuL.eq_pow_of_pow_eq_one hzetaFour.pow_eq_one
  have hzetaFour_fixed (sigma : L ≃ₐ[K] L) : sigma zetaFour = zetaFour := by
    rw [← hmu_pow, map_pow, sigma.commutes]
  have hcharacter_mem (sigma : L ≃ₐ[K] L) :
      hzeta.autToPow K sigma ∈ f.ker := by
    rw [MonoidHom.mem_ker]
    apply Units.ext
    let u : (ZMod (2 ^ r))ˣ := hzeta.autToPow K sigma
    have hzetaFour_pow : zetaFour ^ (u : ZMod (2 ^ r)).val = zetaFour ^ 1 := by
      rw [pow_one]
      calc
        zetaFour ^ (u : ZMod (2 ^ r)).val =
            (zeta ^ (u : ZMod (2 ^ r)).val) ^ (2 ^ (r - 2)) := by
          simp only [zetaFour]
          rw [← pow_mul, ← pow_mul, Nat.mul_comm]
        _ = (sigma zeta) ^ (2 ^ (r - 2)) := by
          rw [show zeta ^ (u : ZMod (2 ^ r)).val = sigma zeta by
            simp [u]]
        _ = sigma zetaFour := by
          simp only [zetaFour, map_pow]
        _ = zetaFour := hzetaFour_fixed sigma
    have hmod : (u : ZMod (2 ^ r)).val ≡ 1 [MOD 4] := by
      have h := (hzetaFour.isOfFinOrder (by norm_num)).pow_eq_pow_iff_modEq.mp
        hzetaFour_pow
      exact hzetaFour.eq_orderOf.symm ▸ h
    change (((u : ZMod (2 ^ r)).cast : ZMod 4)) = 1
    calc
      ((u : ZMod (2 ^ r)).cast : ZMod 4) = ((u : ZMod (2 ^ r)).val : ZMod 4) :=
        ZMod.cast_eq_val (u : ZMod (2 ^ r))
      _ = 1 := (ZMod.natCast_eq_natCast_iff (u : ZMod (2 ^ r)).val 1 4).2 hmod
  let character : (L ≃ₐ[K] L) →* f.ker :=
    (hzeta.autToPow K).codRestrict f.ker hcharacter_mem
  letI : IsCyclic f.ker :=
    exercise_six_units hr
  apply isCyclic_of_injective character
  intro sigma tau h
  apply hzeta.autToPow_injective K
  exact congrArg Subtype.val h

end TwoPower

end Towers.NumberTheory.Milne
