import Mathlib.FieldTheory.AbsoluteGaloisGroup
import Mathlib.NumberTheory.NumberField.CMField

/-!
# Chapter V, Section 3: Theorem 3.33

Milne's theorem identifies the extension of a CM-field generated by all
special values of rational-weight automorphic functions on canonical models
of Shimura varieties with

`(Kᵃᵇ)^H · ℚᵃᵇ`,

where `H` is the image of the Verlag from the abelianized absolute
Galois group of the maximal totally real subfield.

Mathlib already has CM-fields, maximal real subfields, absolute Galois
groups, and their *topological* abelianizations.  It does not yet have
Shimura varieties, canonical models, their automorphic functions, or the
absolute Verlag obtained by placing the absolute Galois groups of `K`
and `K⁺` in a common algebraic closure.  `Data` contains exactly
the realizations needed to *state* the source theorem.  In particular it
does not contain either inclusion, or the equality, asserted by the
theorem.

All fields in the displayed formula are realized inside one ambient field
`Ω`.  The compositum is therefore the lattice supremum of intermediate
fields, and the fixed field is Mathlib's actual Galois fixed field of the
image of the supplied absolute transfer.
-/

namespace Towers.CField.ARecip

open NumberField

noncomputable section

universe u

variable {K : Type u} [Field K] [NumberField K]
  [NumberField.IsCMField K]

local notation "Kplus" => NumberField.maximalRealSubfield K

/-- The source hypothesis `[K : F] = 2` is already part of Mathlib's
definition of a CM-field. -/
theorem finrank_real_subfield :
    Module.finrank Kplus K = 2 :=
  Algebra.IsQuadraticExtension.finrank_eq_two Kplus K

/-- The common realization used to state Theorem V.3.33.

`kAbelianClosure` models `Kᵃᵇ`; its Galois group is identified with the
topological abelianization of the absolute Galois group of `K`.
`absoluteTransfer` is the Verlag from the maximal real subfield.
`rationalAbelianClosure` models `ℚᵃᵇ` inside the common ambient field.
Finally, `rationalSpecialValues` is literally the set of all
special values named in the source.  Constructing these realizations and
defining that set are precisely the unavailable absolute-class-field and
Shimura-variety inputs; they are data, not additional hypotheses on the
source equality. -/
structure Data (K : Type u) [Field K] [NumberField K]
    [NumberField.IsCMField K] where
  kAbelianClosure : Type u
  [closureField : Field kAbelianClosure]
  [closureAlgebra : Algebra K kAbelianClosure]
  [closureRatAlgebra : Algebra ℚ kAbelianClosure]
  [closureScalarTower : IsScalarTower ℚ K kAbelianClosure]
  absoluteAbelianEquiv :
    Field.absoluteGaloisGroupAbelianization K ≃*
      Gal(kAbelianClosure/K)
  absoluteTransfer :
    Field.absoluteGaloisGroupAbelianization
        (NumberField.maximalRealSubfield K) →*
      Field.absoluteGaloisGroupAbelianization K
  ambient : Type u
  [ambientField : Field ambient]
  [ambientRatAlgebra : Algebra ℚ ambient]
  kAbelianEmbedding : kAbelianClosure →ₐ[ℚ] ambient
  rationalAbelianClosure : IntermediateField ℚ ambient
  rationalSpecialValues : Set ambient

attribute [instance]
  Data.closureField
  Data.closureAlgebra
  Data.closureRatAlgebra
  Data.closureScalarTower
  Data.ambientField
  Data.ambientRatAlgebra

namespace Data

variable (D : Data K)

/-- The embedding of `K` into the common ambient field, obtained through
the chosen realization of `Kᵃᵇ`. -/
def kEmbedding : K →ₐ[ℚ] D.ambient :=
  D.kAbelianEmbedding.comp
    ((Algebra.ofId K D.kAbelianClosure).restrictScalars ℚ)

/-- `H`, the image of the Verlag after identifying the Galois group of
`Kᵃᵇ/K` with the abelianized absolute Galois group of `K`. -/
def transferImage : Subgroup Gal(D.kAbelianClosure/K) :=
  MonoidHom.range
    (D.absoluteAbelianEquiv.toMonoidHom.comp D.absoluteTransfer)

/-- `(Kᵃᵇ)^H` before embedding it into the common ambient field. -/
def transferFixedField : IntermediateField K D.kAbelianClosure :=
  IntermediateField.fixedField D.transferImage

/-- `(Kᵃᵇ)^H` as an intermediate field of the common ambient field over
`ℚ`. -/
def transferFixedAmbient : IntermediateField ℚ D.ambient :=
  (D.transferFixedField.restrictScalars ℚ).map D.kAbelianEmbedding

/-- The extension of `K` obtained by adjoining all rational-weight Shimura
special values, represented inside `Ω`. -/
def shimuraSpecialExtension : IntermediateField ℚ D.ambient :=
  IntermediateField.adjoin ℚ
    (Set.range D.kEmbedding ∪ D.rationalSpecialValues)

/-- The chosen copy of `K` lies in the special-value extension. -/
theorem k_shimura_special (x : K) :
    D.kEmbedding x ∈ D.shimuraSpecialExtension := by
  apply IntermediateField.subset_adjoin
  exact Or.inl ⟨x, rfl⟩

/-- Every special value named by the source lies in the generated
extension. -/
theorem shimura_special_extension
    {x : D.ambient} (hx : x ∈ D.rationalSpecialValues) :
    x ∈ D.shimuraSpecialExtension := by
  apply IntermediateField.subset_adjoin
  exact Or.inr hx

/-- The fixed field `(Kᵃᵇ)^H` contains the base field `K`. -/
theorem base_transfer_ambient :
    ((⊥ : IntermediateField K D.kAbelianClosure).restrictScalars ℚ).map
        D.kAbelianEmbedding ≤
      D.transferFixedAmbient := by
  apply IntermediateField.map_mono D.kAbelianEmbedding
  change (⊥ : IntermediateField K D.kAbelianClosure) ≤ D.transferFixedField
  exact bot_le

end Data

/-- The displayed equality is equivalent to the two exact field
inclusions.  This is the sharp formal reduction available before importing
the external Shimura reciprocity theorem of Wei. -/
theorem iff_two_inclusions (D : Data K) :
    (D.shimuraSpecialExtension =
          D.transferFixedAmbient ⊔ D.rationalAbelianClosure
    ) ↔
      D.shimuraSpecialExtension ≤
          D.transferFixedAmbient ⊔ D.rationalAbelianClosure ∧
        D.transferFixedAmbient ⊔ D.rationalAbelianClosure ≤
          D.shimuraSpecialExtension := by
  constructor
  · intro h
    exact ⟨h.le, h.ge⟩
  · rintro ⟨h₁, h₂⟩
    exact le_antisymm h₁ h₂

/-- The exact external input still required from the main theorem of
complex multiplication for Shimura varieties.  Its two fields are the two
sides of Milne's displayed equality, and it asks only for the two genuine
arithmetic inclusions. -/
structure ShimuraReciprocity (D : Data K) : Prop where
  specialValues_le :
    D.shimuraSpecialExtension ≤
      D.transferFixedAmbient ⊔ D.rationalAbelianClosure
  fixedCompositum_le :
    D.transferFixedAmbient ⊔ D.rationalAbelianClosure ≤
      D.shimuraSpecialExtension

/-- Once the two inclusions supplied by Shimura reciprocity are available,
the literal compositum equality follows with no further hypotheses. -/
theorem of_shimura_reciprocity (D : Data K)
    (h : ShimuraReciprocity D) :
    (
      D.shimuraSpecialExtension =
          D.transferFixedAmbient ⊔ D.rationalAbelianClosure) :=
  le_antisymm h.specialValues_le h.fixedCompositum_le

end

end Towers.CField.ARecip
