import Mathlib.FieldTheory.KummerExtension

/-!
# Milne, Class Field Theory, Section III.4, Step 2: Kummer extensions

For the norm criterion used in Theorem III.4.4(d), Milne recalls that adjoining
an `n`th root over a field containing a primitive `n`th root of unity gives a
cyclic extension of degree `n` (when the defining polynomial is irreducible),
and that a generator sends the chosen root `α` to `ζ • α`.
-/

namespace Submission.CField.HSymbol

open Polynomial

universe u

variable {K L : Type u} [Field K] [Field L] [Algebra K L]
variable {n : ℕ} [NeZero n] {a ζ : K}
variable [IsSplittingField K L (X ^ n - C a)]

private theorem primitiveRoots_nonempty (hζ : IsPrimitiveRoot ζ n) :
    (primitiveRoots n K).Nonempty :=
  ⟨ζ, (mem_primitiveRoots (NeZero.pos n)).mpr hζ⟩

/-- An irreducible Kummer splitting field over a field containing a primitive
`n`th root of unity is Galois, cyclic, and has degree `n`. -/
theorem kummer_splitting_structure
    (H : Irreducible (X ^ n - C a)) (hζ : IsPrimitiveRoot ζ n) :
    IsGalois K L ∧ IsCyclic Gal(L/K) ∧ Module.finrank K L = n := by
  let hroots := primitiveRoots_nonempty hζ
  exact ⟨isGalois_of_isSplittingField_X_pow_sub_C hroots H L,
    isCyclic_of_isSplittingField_X_pow_sub_C hroots H L,
    finrank_of_isSplittingField_X_pow_sub_C hroots H L⟩

/-- The Kummer automorphism corresponding to `1 ∈ ZMod n`. -/
noncomputable def kummerGenerator
    (H : Irreducible (X ^ n - C a)) (hζ : IsPrimitiveRoot ζ n) :
    Gal(L/K) :=
  (autEquivZmod H L hζ).symm (Multiplicative.ofAdd (1 : ZMod n))

/-- The chosen Kummer generator sends an `n`th root `α` of `a` to
`ζ • α`. -/
theorem kummer_generator_root
    (H : Irreducible (X ^ n - C a)) (hζ : IsPrimitiveRoot ζ n)
    {α : L} (hα : α ^ n = algebraMap K L a) :
    kummerGenerator H hζ α = ζ • α := by
  simpa [kummerGenerator] using
    (autEquivZmod_symm_apply_natCast H L hα hζ 1)

/-- Every automorphism of the Kummer splitting field is an integer power of
the chosen generator. -/
theorem kummerGenerator_generates
    (H : Irreducible (X ^ n - C a)) (hζ : IsPrimitiveRoot ζ n) :
    ∀ τ : Gal(L/K), τ ∈ Subgroup.zpowers (kummerGenerator H hζ) := by
  intro τ
  rw [Subgroup.mem_zpowers_iff]
  let e := autEquivZmod H L hζ
  obtain ⟨m, hm⟩ := ZMod.intCast_surjective (Multiplicative.toAdd (e τ))
  refine ⟨m, ?_⟩
  apply e.injective
  simp only [map_zpow, kummerGenerator, e, MulEquiv.apply_symm_apply]
  apply Multiplicative.toAdd.injective
  simpa using hm

/-- Equivalently, the cyclic subgroup generated by the chosen Kummer
automorphism is the full Galois group. -/
theorem kummer_zpowers_top
    (H : Irreducible (X ^ n - C a)) (hζ : IsPrimitiveRoot ζ n) :
    Subgroup.zpowers (kummerGenerator (L := L) H hζ) = ⊤ :=
  (Subgroup.eq_top_iff' _).mpr (kummerGenerator_generates (L := L) H hζ)

end Submission.CField.HSymbol
