import Mathlib.Algebra.Field.Basic
import Mathlib.Algebra.Group.Subgroup.Even
import Mathlib.Algebra.QuadraticAlgebra.Basic
import Mathlib.Tactic.FieldSimp
import Mathlib.Tactic.Ring

/-!
# Milne, Class Field Theory, Section III.4: the quadratic special case

Before constructing the general Hilbert symbol, Milne treats the case
`K = ℚ_p` and `n = 2` by declaring the symbol trivial exactly when

`z² = a x² + b y²`

has a nontrivial solution.  The local-field input proving bilinearity and
nondegeneracy is not currently available in Mathlib.  This file records the
elementary algebraic part of the argument, valid over every field: the
condition is symmetric, depends only on the arguments modulo nonzero
squares, and for nonsquare `a` is equivalent to the usual quadratic norm
equation `b = z² - a x²`.
-/

namespace Submission.CField.HSymbol

variable {K : Type*} [Field K]

/-- The conic used to define the quadratic Hilbert symbol has a nontrivial
`K`-point. -/
def NontrivialQuadraticConic (a b : K) : Prop :=
  ∃ x y z : K,
    (x ≠ 0 ∨ y ≠ 0 ∨ z ≠ 0) ∧ z ^ 2 = a * x ^ 2 + b * y ^ 2

/-- The quadratic conic condition is symmetric in its two coefficients. -/
theorem nontrivial_conic_comm (a b : K) :
    NontrivialQuadraticConic a b ↔
      NontrivialQuadraticConic b a := by
  constructor
  · rintro ⟨x, y, z, hne, hxy⟩
    refine ⟨y, x, z, ?_, ?_⟩
    · rcases hne with hx | hy | hz
      · exact Or.inr (Or.inl hx)
      · exact Or.inl hy
      · exact Or.inr (Or.inr hz)
    · simpa only [add_comm] using hxy
  · rintro ⟨x, y, z, hne, hxy⟩
    refine ⟨y, x, z, ?_, ?_⟩
    · rcases hne with hx | hy | hz
      · exact Or.inr (Or.inl hx)
      · exact Or.inl hy
      · exact Or.inr (Or.inr hz)
    · simpa only [add_comm] using hxy

private theorem nontrivial_conic_rescale
    (a b u : K) (hu : u ≠ 0) :
    NontrivialQuadraticConic (a * u ^ 2) b →
      NontrivialQuadraticConic a b := by
  rintro ⟨x, y, z, hne, hxy⟩
  refine ⟨u * x, y, z, ?_, ?_⟩
  · rcases hne with hx | hy | hz
    · exact Or.inl (mul_ne_zero hu hx)
    · exact Or.inr (Or.inl hy)
    · exact Or.inr (Or.inr hz)
  · calc
      z ^ 2 = (a * u ^ 2) * x ^ 2 + b * y ^ 2 := hxy
      _ = a * (u * x) ^ 2 + b * y ^ 2 := by ring

/-- Multiplying the first coefficient by a nonzero square does not change
whether the quadratic conic has a nontrivial point. -/
theorem nontrivial_quadratic_conic
    (a b u : K) (hu : u ≠ 0) :
    NontrivialQuadraticConic (a * u ^ 2) b ↔
      NontrivialQuadraticConic a b := by
  refine ⟨nontrivial_conic_rescale a b u hu, ?_⟩
  intro h
  apply nontrivial_conic_rescale
    (a * u ^ 2) b u⁻¹ (inv_ne_zero hu)
  have hcancel : (a * u ^ 2) * u⁻¹ ^ 2 = a := by
    field_simp [hu]
  simpa only [hcancel] using h

/-- Multiplying the second coefficient by a nonzero square does not change
whether the quadratic conic has a nontrivial point. -/
theorem nontrivial_conic_sq
    (a b u : K) (hu : u ≠ 0) :
    NontrivialQuadraticConic a (b * u ^ 2) ↔
      NontrivialQuadraticConic a b := by
  rw [nontrivial_conic_comm a (b * u ^ 2),
    nontrivial_quadratic_conic b a u hu,
    nontrivial_conic_comm b a]

/-- The quadratic norm equation occurring in Milne's special-case proof. -/
def QuadraticValue (a b : K) : Prop :=
  ∃ z x : K, b = z ^ 2 - a * x ^ 2

/-- The displayed quadratic norm equation is exactly the norm formula in the
quadratic algebra generated by an element whose square is `a`. -/
theorem quadratic_value_algebra (a b : K) :
    QuadraticValue a b ↔
      ∃ w : QuadraticAlgebra K a 0, w.norm = b := by
  constructor
  · rintro ⟨z, x, rfl⟩
    refine ⟨⟨z, x⟩, ?_⟩
    simp [QuadraticAlgebra.norm_def, pow_two]
    ring
  · rintro ⟨w, hw⟩
    refine ⟨w.re, w.im, ?_⟩
    rw [← hw]
    simp [QuadraticAlgebra.norm_def, pow_two]
    ring

/-- For nonsquare `a`, the quadratic norm equation is equivalent to the
existence of a nontrivial point on `z² = a x² + b y²`.  This is the middle
equivalence in the `K = ℚ_p`, `n = 2` special case of Proposition III.4.1. -/
theorem nontrivial_conic_solution
    {a b : K} (ha : ¬ IsSquare a) :
    QuadraticValue a b ↔
      NontrivialQuadraticConic a b := by
  constructor
  · rintro ⟨z, x, rfl⟩
    refine ⟨x, 1, z, Or.inr (Or.inl one_ne_zero), ?_⟩
    ring
  · rintro ⟨x, y, z, hne, hxy⟩
    have hy : y ≠ 0 := by
      intro hy
      have hzx : z ^ 2 = a * x ^ 2 := by simpa [hy] using hxy
      by_cases hx : x = 0
      · have hzpow : z ^ 2 = 0 := by simpa [hx] using hzx
        have hz : z = 0 := eq_zero_of_pow_eq_zero hzpow
        rcases hne with hx' | hy' | hz'
        · exact hx' hx
        · exact hy' hy
        · exact hz' hz
      · apply ha
        refine ⟨z / x, ?_⟩
        field_simp [hx]
        simpa only [pow_two] using hzx.symm
    refine ⟨z / y, x / y, ?_⟩
    field_simp [hy]
    rw [hxy]
    ring

/-- The sign attached to Milne's quadratic conic: `1` when it has a
nontrivial point and `-1` otherwise. Over a nonarchimedean local field this
is the quadratic Hilbert symbol. -/
noncomputable def quadraticHilbertSign (a b : K) : ℤˣ :=
  letI : Decidable (NontrivialQuadraticConic a b) :=
    Classical.propDecidable _
  if NontrivialQuadraticConic a b then 1 else -1

@[simp]
theorem hilbert_sign_one (a b : K) :
    quadraticHilbertSign a b = 1 ↔
      NontrivialQuadraticConic a b := by
  classical
  by_cases h : NontrivialQuadraticConic a b <;>
    simp [quadraticHilbertSign, h]

@[simp]
theorem hilbert_sign_neg (a b : K) :
    quadraticHilbertSign a b = -1 ↔
      ¬ NontrivialQuadraticConic a b := by
  classical
  by_cases h : NontrivialQuadraticConic a b <;>
    simp [quadraticHilbertSign, h]

/-- The quadratic indicator is symmetric. -/
theorem quadratic_sign_comm (a b : K) :
    quadraticHilbertSign a b = quadraticHilbertSign b a := by
  classical
  unfold quadraticHilbertSign
  rw [nontrivial_conic_comm]

/-- The quadratic indicator is unchanged when its first argument is
multiplied by a nonzero square. -/
theorem quadratic_sign_sq (a b u : K) (hu : u ≠ 0) :
    quadraticHilbertSign (a * u ^ 2) b = quadraticHilbertSign a b := by
  classical
  unfold quadraticHilbertSign
  rw [nontrivial_quadratic_conic a b u hu]

/-- The quadratic indicator is unchanged when its second argument is
multiplied by a nonzero square. -/
theorem hilbert_sign_sq (a b u : K) (hu : u ≠ 0) :
    quadraticHilbertSign a (b * u ^ 2) = quadraticHilbertSign a b := by
  classical
  unfold quadraticHilbertSign
  rw [nontrivial_conic_sq a b u hu]

@[simp]
theorem hilbert_sign_left (a : K) :
    quadraticHilbertSign 1 a = 1 := by
  rw [hilbert_sign_one]
  refine ⟨1, 0, 1, Or.inl one_ne_zero, ?_⟩
  simp

@[simp]
theorem hilbert_sign_right (a : K) :
    quadraticHilbertSign a 1 = 1 := by
  rw [quadratic_sign_comm]
  exact hilbert_sign_left a

@[simp]
theorem quadratic_sign_neg (a : K) :
    quadraticHilbertSign a (-a) = 1 := by
  rw [hilbert_sign_one]
  refine ⟨1, 1, 0, Or.inl one_ne_zero, ?_⟩
  ring

/-- For nonsquare `a`, triviality of the quadratic indicator is exactly the
quadratic norm equation used by Milne. -/
theorem quadratic_hilbert_sign
    {a b : K} (ha : ¬ IsSquare a) :
    quadraticHilbertSign a b = 1 ↔ QuadraticValue a b := by
  rw [hilbert_sign_one]
  exact (nontrivial_conic_solution ha).symm

end Submission.CField.HSymbol
