import Towers.NumberTheory.Galois.FrobeniusElement
import Towers.NumberTheory.Galois.CompositumSplittingPrimes
import Towers.ClassField.IdeleCohomology.FiniteIdeleAction
import Towers.ClassField.NormIndex.SplitAwayNorm

/-!
# Chapter VII, Section 4, Proposition 4.7

For a finite solvable Galois extension `L/K`, the arithmetic Frobenius
elements outside any finite set containing the ramified primes generate the
whole Galois group.

The generated subgroup below is the ordinary subgroup closure, not a normal
closure.  As in Milne's proof, the exceptional set is first enlarged to a
Galois-stable finite set; Frobenius conjugacy then makes the corresponding
generated subgroup normal.  Its fixed field is shown to split at every prime
outside a finite set, so Proposition 4.6 forces that fixed field to be `K`.
-/

namespace Towers.CField.NIndex

open IsDedekindDomain NumberField
open scoped Pointwise
open Towers.NumberTheory.Milne
open Towers.CField.ICohomo
open Towers.CField.Ideles

noncomputable section

universe u

private abbrev OK (K : Type u) [Field K] [NumberField K] :=
  NumberField.RingOfIntegers K

private abbrev IK (K : Type u) [Field K] [NumberField K] :=
  IdeleGroup (NumberField.RingOfIntegers K) K

variable {K L : Type u} [Field K] [Field L] [NumberField K] [NumberField L]
  [Algebra K L] [FiniteDimensional K L] [IsGalois K L]

local instance ringOfIntegersGaloisAction :
    MulSemiringAction Gal(L/K) (OK L) :=
  IsIntegralClosure.MulSemiringAction (OK K) K L (OK L)

local instance ringOfIntegersGaloisAction_smulCommClass :
    SMulCommClass Gal(L/K) (OK K) (OK L) where
  smul_comm sigma a b := by
    apply Subtype.ext
    have hG (x : OK L) : ((sigma • x : OK L) : L) = sigma (x : L) :=
      algebraMap.coe_smul' (B := OK L) (C := L) sigma x
    have hA (x : OK L) : ((a • x : OK L) : L) = (a : K) • (x : L) :=
      algebraMap.coe_smul (A := OK K) (B := OK L) (C := L) a x
    calc
      ((sigma • (a • b) : OK L) : L) = sigma (((a • b : OK L) : L)) := hG (a • b)
      _ = sigma ((a : K) • (b : L)) := congrArg sigma (hA b)
      _ = (a : K) • sigma (b : L) := smul_comm sigma (a : K) (b : L)
      _ = (a : K) • ((sigma • b : OK L) : L) :=
        congrArg (fun y : L ↦ (a : K) • y) (hG b).symm
      _ = ((a • (sigma • b) : OK L) : L) := (hA (sigma • b)).symm

local instance ringOfIntegersGaloisAction_isInvariant :
    Algebra.IsInvariant (OK K) (OK L) Gal(L/K) := by
  exact Algebra.isInvariant_of_isGalois (A := OK K) (K := K)
    (L := L) (B := OK L)

local instance ringOfIntegersIsGaloisGroup :
    IsGaloisGroup Gal(L/K) (OK K) (OK L) :=
  IsGaloisGroup.of_isFractionRing (G := Gal(L/K))
    (A := OK K) (B := OK L) (K := K) (L := L)

/-- The actual arithmetic Frobenius `(Q,L/K)` at a finite prime `Q` of `L`.
Outside the ramified primes this is the unique lift of residue Frobenius. -/
noncomputable def numberFrobeniusElement
    (Q : FinitePrime L) : Gal(L/K) :=
  arithFrobAt (OK K) Gal(L/K) Q.asIdeal

/-- A finite exceptional set contains every ramified prime precisely when
every prime outside it is unramified. -/
def ContainsRamifiedPrimes
    (T : Finset (FinitePrime L)) : Prop :=
  ∀ Q : FinitePrime L, Q ∉ T →
    Algebra.IsUnramifiedAt (OK K) Q.asIdeal

/-- The set of actual Frobenius elements at primes outside `T`. -/
def frobeniusElementsOutside
    (T : Finset (FinitePrime L)) : Set Gal(L/K) :=
  {sigma | ∃ Q : FinitePrime L,
    Q ∉ T ∧ numberFrobeniusElement (K := K) Q = sigma}

/-- The ordinary subgroup generated by Frobenius elements outside `T`. -/
def frobeniusGeneratedSubgroup
    (T : Finset (FinitePrime L)) : Subgroup Gal(L/K) :=
  Subgroup.closure (frobeniusElementsOutside (K := K) T)

/-- Stability of a finite set of primes under the actual Galois action. -/
def GaloisStableSet
    (T : Finset (FinitePrime L)) : Prop :=
  ∀ (sigma : Gal(L/K)) (Q : FinitePrime L),
    Q ∈ T ↔
      letI := finitePrimeAction (K := K) (L := L)
      sigma • Q ∈ T

/-- The finite primes of `K` lying below members of `T`. -/
noncomputable def contractedExceptionalPrimes
    (T : Finset (FinitePrime L)) : Finset (FinitePrime K) := by
  classical
  exact T.image fun Q ↦ Q.under (OK K)

/-- Milne's replacement of `T` by the union of its finitely many Galois
conjugates. -/
noncomputable def galoisSaturation
    (T : Finset (FinitePrime L)) : Finset (FinitePrime L) := by
  classical
  letI := finitePrimeAction (K := K) (L := L)
  exact Finset.univ.biUnion fun (sigma : Gal(L/K)) ↦
    T.image fun (Q : FinitePrime L) ↦ sigma • Q

omit [NumberField K] [IsGalois K L] in
theorem subset_galoisSaturation
    (T : Finset (FinitePrime L)) :
    ∀ (Q : FinitePrime L), Q ∈ T →
      Q ∈ galoisSaturation (K := K) (L := L) T := by
  classical
  letI := finitePrimeAction (K := K) (L := L)
  intro Q hQ
  simp only [galoisSaturation, Finset.mem_biUnion, Finset.mem_univ,
    Finset.mem_image, true_and]
  exact ⟨1, Q, hQ, one_smul Gal(L/K) Q⟩

omit [NumberField K] [IsGalois K L] in
theorem galoisSaturation_stable
    (T : Finset (FinitePrime L)) :
    GaloisStableSet (K := K) (L := L)
      (galoisSaturation (K := K) (L := L) T) := by
  classical
  letI := finitePrimeAction (K := K) (L := L)
  intro sigma Q
  simp only [galoisSaturation, Finset.mem_biUnion, Finset.mem_univ,
    Finset.mem_image, true_and]
  constructor
  · rintro ⟨tau, P, hPT, rfl⟩
    exact ⟨sigma * tau, P, hPT, (mul_smul sigma tau P).symm⟩
  · rintro ⟨tau, P, hPT, hP⟩
    refine ⟨sigma⁻¹ * tau, P, hPT, ?_⟩
    rw [mul_smul, hP, inv_smul_smul]

/-- For a stable exceptional set containing the ramified primes, Frobenius
conjugacy makes the ordinary generated subgroup normal. -/
theorem frobenius_generated_stable
    (T : Finset (FinitePrime L))
    (hramified : ContainsRamifiedPrimes (K := K) (L := L) T)
    (hstable : GaloisStableSet (K := K) (L := L) T) :
    (frobeniusGeneratedSubgroup (K := K) (L := L) T).Normal := by
  letI := finitePrimeAction (K := K) (L := L)
  refine ⟨fun n hn sigma ↦ ?_⟩
  refine Subgroup.closure_induction (p := fun n _ ↦
      sigma * n * sigma⁻¹ ∈
        frobeniusGeneratedSubgroup (K := K) (L := L) T)
    (fun n hn ↦ ?_) ?_ (fun x y _ _ hx hy ↦ ?_)
      (fun x _ hx ↦ ?_) hn
  · obtain ⟨Q, hQT, rfl⟩ := hn
    letI : Algebra.IsUnramifiedAt (OK K) Q.asIdeal := hramified Q hQT
    have hsigmaQT : sigma • Q ∉ T := by
      intro hmem
      exact hQT ((hstable sigma Q).mpr hmem)
    apply Subgroup.subset_closure
    refine ⟨sigma • Q, hsigmaQT, ?_⟩
    change arithFrobAt (OK K) Gal(L/K) (sigma • Q).asIdeal = _
    have hIdeal : (sigma • Q).asIdeal =
        (sigma • Q.asIdeal : Ideal (OK L)) :=
      prime_action_ideal (K := K) (L := L) sigma Q
    letI : Finite ((OK L) ⧸ (sigma • Q.asIdeal : Ideal (OK L))) := by
      rw [← hIdeal]
      infer_instance
    simpa only [prime_action_ideal] using
      (arith_frob_conjugate Q.asIdeal sigma)
  · simp
  · change sigma * (x * y) * sigma⁻¹ ∈
      frobeniusGeneratedSubgroup (K := K) (L := L) T
    rw [← conj_mul]
    exact (frobeniusGeneratedSubgroup (K := K) (L := L) T).mul_mem hx hy
  · change sigma * x⁻¹ * sigma⁻¹ ∈
      frobeniusGeneratedSubgroup (K := K) (L := L) T
    rw [← conj_inv]
    exact (frobeniusGeneratedSubgroup (K := K) (L := L) T).inv_mem hx

/-- Frobenius restriction to the fixed field.  Since every generating
Frobenius belongs to `H`, its restriction to `L^H` is the identity; the
unramified Frobenius criterion then says that every base prime not lying
below `T` splits completely in `L^H`.

This bridge isolates only the integral-closure comparison between primes of
the abstract fixed-field subtype and contractions of primes of `L`. -/
def FixedSplittingBridge : Prop :=
  ∀ (K L : Type u) [Field K] [Field L] [NumberField K] [NumberField L]
    [Algebra K L] [FiniteDimensional K L] [IsGalois K L]
    (T : Finset (FinitePrime L))
    (_hunramified : ContainsRamifiedPrimes (K := K) (L := L) T)
    (hHnormal :
      (frobeniusGeneratedSubgroup (K := K) (L := L) T).Normal),
    let H := frobeniusGeneratedSubgroup (K := K) (L := L) T
    letI : H.Normal := hHnormal
    ∀ p : FinitePrime K,
      p ∉ contractedExceptionalPrimes (K := K) (L := L) T →
        SplitsCompletelyAt K (IntermediateField.fixedField H) p

set_option synthInstance.maxHeartbeats 500000 in
-- Fixed-field ring-of-integers towers and Frobenius restriction are dependent.
set_option maxHeartbeats 4000000 in
/-- Frobenius restriction proves the fixed-field splitting bridge used in
Proposition VII.4.7. -/
theorem fixedSplittingBridge :
    FixedSplittingBridge.{u} := by
  classical
  intro K L _ _ _ _ _ _ _ T hunramified hHnormal
  dsimp only
  intro p hp
  let H := frobeniusGeneratedSubgroup (K := K) (L := L) T
  letI : H.Normal := hHnormal
  let E := IntermediateField.fixedField H
  letI : IsGalois K E := IsGalois.of_fixedField_normal_subgroup H
  letI : Algebra E L := E.toAlgebra
  letI : IsScalarTower K E L := IsScalarTower.of_algebraMap_eq' rfl
  letI : IsScalarTower (OK K) (OK E) (OK L) := by
    refine IsScalarTower.of_algebraMap_eq ?_
    intro x
    apply Subtype.ext
    exact IsScalarTower.algebraMap_apply K E L x
  letI : MulSemiringAction Gal(E/K) (OK E) :=
    IsIntegralClosure.MulSemiringAction (OK K) K E (OK E)
  letI : IsGaloisGroup Gal(E/K) (OK K) (OK E) :=
    IsGaloisGroup.of_isFractionRing Gal(E/K) (OK K) (OK E) K E
  obtain ⟨⟨P, hPprime, hPover⟩⟩ :=
    p.asIdeal.nonempty_primesOver (S := OK L)
  letI : P.IsPrime := hPprime
  letI : P.LiesOver p.asIdeal := hPover
  have hP0 : P ≠ ⊥ :=
    Ideal.ne_bot_of_liesOver_of_ne_bot p.ne_bot P
  let upper : FinitePrime L := ⟨P, hPprime, hP0⟩
  have hupperUnder : upper.under (OK K) = p := by
    apply HeightOneSpectrum.ext
    exact hPover.over.symm
  have hupperNotT : upper ∉ T := by
    intro hupperT
    apply hp
    rw [contractedExceptionalPrimes]
    exact Finset.mem_image.mpr ⟨upper, hupperT, hupperUnder⟩
  letI : Algebra.IsUnramifiedAt (OK K) P :=
    hunramified upper hupperNotT
  letI : Finite (OK L ⧸ P) :=
    Ring.HasFiniteQuotients.finiteQuotient hP0
  let Q : Ideal (OK E) := P.under (OK E)
  letI : Q.IsPrime := Ideal.IsPrime.under (OK E) P
  letI : P.LiesOver Q := ⟨rfl⟩
  letI : Q.LiesOver p.asIdeal := ⟨by
    dsimp [Q]
    rw [Ideal.under_under]
    exact hPover.over⟩
  have hQ0 : Q ≠ ⊥ :=
    Ideal.ne_bot_of_liesOver_of_ne_bot p.ne_bot Q
  letI : Q.IsMaximal := Ideal.IsPrime.isMaximal
    (show Q.IsPrime from inferInstance) hQ0
  letI : Finite (OK E ⧸ Q) :=
    Ring.HasFiniteQuotients.finiteQuotient hQ0
  letI : Algebra.IsUnramifiedAt (OK K) Q :=
    Algebra.IsUnramifiedAt.of_liesOver (OK K) Q P
  let res : Gal(L/K) →* Gal(E/K) := AlgEquiv.restrictNormalHom E
  have hres_smul (sigma : Gal(L/K)) (x : OK E) :
      algebraMap (OK E) (OK L) (res sigma • x) =
        sigma • algebraMap (OK E) (OK L) x := by
    exact (integers_smul_restrict
      (F := K) (E := E) (N := L) sigma x).symm
  let frob := numberFrobeniusElement (K := K) upper
  have hfrobH : frob ∈ H := by
    apply Subgroup.subset_closure
    exact ⟨upper, hupperNotT, rfl⟩
  have hfrobFix : frob ∈ E.fixingSubgroup := by
    change frob ∈ (IntermediateField.fixedField H).fixingSubgroup
    rwa [IntermediateField.fixingSubgroup_fixedField H]
  have hresFrob : res frob = 1 := by
    rw [← E.restrictNormalHom_ker] at hfrobFix
    exact hfrobFix
  have hrestrict : res frob = arithFrobAt (OK K) Gal(E/K) Q := by
    exact arith_restrict_unramified
      (R := OK K) (S := OK L) (G := Gal(L/K)) P res hres_smul
  have hQfrob : arithFrobAt (OK K) Gal(E/K) Q = 1 := by
    rw [← hrestrict]
    exact hresFrob
  have hf : Ideal.inertiaDeg p.asIdeal Q = 1 := by
    have hf' :=
      (number_frob_deg
        (K := K) (L := E) Q).mp hQfrob
    have hQunder : Q.under (OK K) = p.asIdeal :=
      (show Q.LiesOver p.asIdeal from inferInstance).over.symm
    simpa only [hQunder] using hf'
  have he : Ideal.ramificationIdx p.asIdeal Q = 1 := by
    exact (unramified_ramification_idx
      p.asIdeal Q hQ0).mp inferInstance
  exact splits_completely_prime K E p Q
    ⟨inferInstance, inferInstance⟩ he hf

/-- Enlarging the exceptional set only decreases the set of Frobenius
generators. -/
theorem frobenius_generated_mono
    {T T' : Finset (FinitePrime L)}
    (hTT' : ∀ (Q : FinitePrime L), Q ∈ T → Q ∈ T') :
    frobeniusGeneratedSubgroup (K := K) (L := L) T' ≤
      frobeniusGeneratedSubgroup (K := K) (L := L) T := by
  apply Subgroup.closure_mono
  rintro sigma ⟨Q, hQT', rfl⟩
  exact ⟨Q, fun hQT ↦ hQT' (hTT' Q hQT), rfl⟩

/-- Proposition 4.7 from Proposition 4.6 and the fixed-field splitting
interface. -/
theorem number_statement_components
    (h46 : NontrivialNonsplitPrimes.{u})
    (hfixed : FixedSplittingBridge.{u}) :
    (∀ (K L : Type u) [Field K] [Field L] [NumberField K] [NumberField L]
          [Algebra K L] [FiniteDimensional K L] [IsGalois K L]
          [IsSolvable Gal(L/K)],
          ∀ T : Finset (FinitePrime L),
            ContainsRamifiedPrimes (K := K) (L := L) T →
              frobeniusGeneratedSubgroup (K := K) (L := L) T = ⊤) := by
  classical
  intro K L _ _ _ _ _ _ _ _ T hramified
  let T' := galoisSaturation (K := K) (L := L) T
  let H := frobeniusGeneratedSubgroup (K := K) (L := L) T'
  have hramified' : ContainsRamifiedPrimes (K := K) (L := L) T' := by
    intro Q hQT'
    exact hramified Q fun hQT ↦
      hQT' (subset_galoisSaturation (K := K) (L := L) T Q hQT)
  have hHnormal : H.Normal :=
    frobenius_generated_stable T' hramified'
      (galoisSaturation_stable (K := K) (L := L) T)
  letI : H.Normal := hHnormal
  let E := IntermediateField.fixedField H
  letI : IsGalois K E := IsGalois.of_fixedField_normal_subgroup H
  letI : IsSolvable Gal(E/K) :=
    solvable_of_surjective
      (AlgEquiv.restrictNormalHom_surjective (F := K) (K₁ := E) (E := L))
  have hsplitOutside : ∀ p : FinitePrime K,
      p ∉ contractedExceptionalPrimes (K := K) (L := L) T' →
        SplitsCompletelyAt K E p := by
    exact hfixed K L T' hramified' hHnormal
  have hnonsplittingFinite : (splittingPrimes K E)ᶜ.Finite := by
    apply (contractedExceptionalPrimes (K := K) (L := L) T').finite_toSet.subset
    intro p hp
    by_contra hpT'
    exact hp (hsplitOutside p hpT')
  have hdegree : Module.finrank K E = 1 := by
    by_contra hdegree
    exact (h46 K E hdegree) hnonsplittingFinite
  have hEbot : E = ⊥ := IntermediateField.finrank_eq_one_iff.mp hdegree
  have hHtop : H = ⊤ := by
    calc
      H = IntermediateField.fixingSubgroup E :=
        (IntermediateField.fixingSubgroup_fixedField H).symm
      _ = IntermediateField.fixingSubgroup (⊥ : IntermediateField K L) := by
        rw [hEbot]
      _ = ⊤ := IntermediateField.fixingSubgroup_bot
  apply top_unique
  rw [← hHtop]
  exact frobenius_generated_mono (K := K) (L := L)
    (subset_galoisSaturation (K := K) (L := L) T)

/-- **Proposition VII.4.7.** Proposition VII.4.6 implies that the arithmetic
Frobenius elements outside any finite ramified exceptional set generate the
whole solvable Galois group. -/
theorem numberElementStatement
    (h46 : NontrivialNonsplitPrimes.{u}) :
    (∀ (K L : Type u) [Field K] [Field L] [NumberField K] [NumberField L]
          [Algebra K L] [FiniteDimensional K L] [IsGalois K L]
          [IsSolvable Gal(L/K)],
          ∀ T : Finset (FinitePrime L),
            ContainsRamifiedPrimes (K := K) (L := L) T →
              frobeniusGeneratedSubgroup (K := K) (L := L) T = ⊤) :=
  number_statement_components
    h46 fixedSplittingBridge

/-- With weak approximation formalized, Proposition 4.7 reduces directly to
Lemma 4.5 and split-away idèle-norm assembly. -/
theorem statement_split_away
    (h45 : (∀ (K L : Type u) [Field K] [Field L] [NumberField K] [NumberField L]
          [Algebra K L] [FiniteDimensional K L] [IsGalois K L]
          [IsSolvable Gal(L/K)],
          ∀ D : Subgroup (IK K),
            D ≤ ideleNormSubgroup (K := K) (L := L) →
            Dense ((principalIdeles (NumberField.RingOfIntegers K) K ⊔ D :
              Subgroup (IK K)) : Set (IK K)) →
            Module.finrank K L = 1))
    (hnorm : SplitAwayBridge.{u}) :
    (∀ (K L : Type u) [Field K] [Field L] [NumberField K] [NumberField L]
          [Algebra K L] [FiniteDimensional K L] [IsGalois K L]
          [IsSolvable Gal(L/K)],
          ∀ T : Finset (FinitePrime L),
            ContainsRamifiedPrimes (K := K) (L := L) T →
              frobeniusGeneratedSubgroup (K := K) (L := L) T = ⊤) :=
  numberElementStatement
    (place_statement_away h45 hnorm)

/-- Proposition VII.4.7 now depends only on Lemma VII.4.5; split-away norm
assembly and weak approximation are both internal. -/
theorem number_statement_only
    (h45 : (∀ (K L : Type u) [Field K] [Field L] [NumberField K] [NumberField L]
          [Algebra K L] [FiniteDimensional K L] [IsGalois K L]
          [IsSolvable Gal(L/K)],
          ∀ D : Subgroup (IK K),
            D ≤ ideleNormSubgroup (K := K) (L := L) →
            Dense ((principalIdeles (NumberField.RingOfIntegers K) K ⊔ D :
              Subgroup (IK K)) : Set (IK K)) →
            Module.finrank K L = 1)) : (
      ∀ (K L : Type u) [Field K] [Field L] [NumberField K] [NumberField L]
          [Algebra K L] [FiniteDimensional K L] [IsGalois K L]
          [IsSolvable Gal(L/K)],
          ∀ T : Finset (FinitePrime L),
            ContainsRamifiedPrimes (K := K) (L := L) T →
              frobeniusGeneratedSubgroup (K := K) (L := L) T = ⊤
    ) :=
  numberElementStatement
    (split_away_only h45)

end

end Towers.CField.NIndex
